### ISSUE TITLE
请问简书可以支持吗

### ISSUE THREAD

**Issue by livc** [DIYgod/RSSHub#1]

**Comment by wizos** [comment]
可以用 http://jianshu.milkythinking.com

**Comment by metowolf** [comment]
参考项目 https://github.com/hutushen222/JianshuRSS

**Comment by liwanglin12** [comment]
@metowolf meto发话了一定要支持（

**Comment by livc** [comment]
@wizos 这个貌似不支持rss某个作者的所有文章啊

@metowolf 请问这个是需要自己搭建吗？没有online的服务吧。我看这个readme并不知道如何把它运行起来。

**Comment by wizos** [comment]
@livc 可以的，你直接把作者的主页贴进去就好。 @metowolf 提供的就是这个网站的github地址。自己要搭建的话很简单，找个支持php虚拟空间，把源代码放进去就好了

**Comment by livc** [comment]
@wizos 作者主页（https://www.jianshu.com/u/dbb14da93531）贴进去返回的是 feed://jianshu.milkythinking.com/feeds/homepage
我将其改为 feed://jianshu.milkythinking.com/feeds/users/d0be5ae77914
在RSS阅读器中无法添加

**Comment by wizos** [comment]
@livc 这个应该是原作者网站的bug，你贴的地址把https改为http就可以。比如你上面这个是http://jianshu.milkythinking.com/feeds/users/dbb14da93531

**Comment by livc** [comment]
@wizos Thanks.

**Comment by DIYgod** [comment]
RSSHub 将会提供支持

**Comment by DIYgod** [comment]
Done. 

[简书 - RSSHub](https://rsshub.js.org/#/?id=%E7%AE%80%E4%B9%A6)
