### ISSUE TITLE
求助，无法定制知乎的用户动态。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#100]
订阅zhihu的用户，终端提示：

> info: /zhihu/people/activities/guo-zi-501, user IP: ::ffff:IP隐去
> error: Promise error: TypeError: Cannot read property 'name' of undefined
>     at module.exports (/root/RSSHub/routes/zhihu/activities.js:23:33)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7

网页提示：

> RSSHub 发生了一些意外: TypeError: Cannot read property 'name' of undefined

系统是 CentOS 6 x64，按照[https://www.moerats.com/archives/587/](url)一步步操作下来的。

**Comment by DIYgod** [comment]
可能是网络原因数据抓取失败导致的

**Comment by DIYgod** [comment]
无法复现，issue 将被关闭
