### ISSUE TITLE
在bilibili等一些需要cookie的路由在cookie过期后进行提醒

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#10003]
### 这是一个什么样的功能？

例如哔哩哔哩bilibili 的 [用户关注视频动态](https://docs.rsshub.app/social-media.html#bilibili-yong-hu-guan-zhu-shi-pin-dong-tai) 路由，它需要自建，自己去提供cookie，但cookie会过期，想在它过期时及时进行提醒。

是否可以在cookie过期时，所订阅的RSS条目里生成新的一条条目进行提醒？ 不过，这样似乎就不太优雅了，毕竟，那不是该订阅源应该生成的正常条目。

或者可以有其它方法，进行通知自己吗？

：）

### 这个功能可以解决什么问题？

自建需要cookie的路由，当它的cookie过期时能及时被发现。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by 362227** [comment]
这个只能在RSS条目里生成新的提醒，没有其他办法的。如果通过短信、TG、邮件推送，应该不属于这个项目的

**Comment by TonyRL** [comment]
Closed in 52481ce24d379a49a455bac62bc2c693dc7b7075
