### ISSUE TITLE
国家药品监督管理局药品审评中心-信息公开

### ISSUE THREAD

**Issue by qupb** [DIYgod/RSSHub#10021]
### 这是一个什么样的功能？

 网站地址
[www.cde.org.cn](https://www.cde.org.cn/main/xxgk/listpage/4b5255eb0a84820cef4ca3e8b6bbe20c)

网站描述
这是国家药品审评网站**信息公开**部分，有助于快速了解目前中国新药获批情况

内容一
**1 .优先审评公示**
了解目前国家药品监督管理局纳入优先审评公示药品目录
 内容二
**2 突破性治疗公示**
了解目前国家药品监督管理局纳入突破性治疗药品目录
内容三
**3.临床试验默示许可**
及时了解目前中国新药获批临床情况

### 这个功能可以解决什么问题？

可以帮助中国医药从业人员和普通民众了解目前我国药品审批和临床研发情况

### 额外描述

已在feed43、fetchrss等网站工具进行相关RSS创制，发现为非法url或无法访问
所以有此次issue提交，谢谢各位

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please use the right form for [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new/choose).
