### ISSUE TITLE
request to add content from @akn_k0

### ISSUE THREAD

**Issue by senoowe** [DIYgod/RSSHub#10089]
### What feature is it?

akn_k0 only fans subscription content

### What problem does this feature solve?

adding more creator content to coomer.party

### This is not a duplicated feature request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested

**Comment by TonyRL** [comment]
Please use the correct form for a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml)
