### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by nesrad** [DIYgod/RSSHub#10093]
### Routes

```routes
https://rsshub.app/telegram/channel/contrasperantia
```

### Full routes

```fullroutes
https://rsshub.app/telegram/channel/contrasperantia
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#telegram

### What is expected?

It should display an RSS feed

### What is actually happening?

![image](https://user-images.githubusercontent.com/32225492/176927383-c61e3980-27a8-4864-915c-b892521f654b.png)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
none
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
This is what the log said:
> Unable to fetch message feed from this channel.
Please **check this URL** to see if you can view the message preview: https://t.me/s/contrasperantia

This is what the related documentation said from the link you have provided:
> Due to Telegram restrictions, some channels involving pornography, copyright, and politics **cannot be subscribed**. You can confirm by visiting https://t.me/s/:username.
