### ISSUE TITLE
希望在Bilibili的UP主动态路由中，添加直接显示专栏文章全文的参数

### ISSUE THREAD

**Issue by HamadaMasatoshi** [DIYgod/RSSHub#10116]
### 这是一个什么样的功能？

希望订阅 Biblibili 某个UP主动态并设置直接显示专栏文章全文的参数后，如果该UP主发布了专栏，能直接在阅读器中输出专栏全文。

目前微博[博主路由](https://docs.rsshub.app/social-media.html#wei-bo)如果添加 displayArticle=1 的参数，已经可以实现此效果。

### 这个功能可以解决什么问题？

目前 Bilibili 的[UP主动态路由](https://docs.rsshub.app/social-media.html#bilibili-up-zhu-dong-tai)，只有是否开启内嵌视频的参数，没有其他参数。

如果UP主发布了视频、图片、文字动态，可以在阅读器里直接浏览。

但是如果发布了专栏，阅读器里只显示专栏封面、文章开头一部分摘要和一个文章链接，还是需要浏览器跳转到专栏页面才能阅读全文。

### 额外描述

微博博主路由添加 displayArticle=1 参数直接显示微博文章的示例：
https://rsshub.app/weibo/user/2478163131/displayArticle=1

Bilibili UP主动态路由当前专栏显示效果的示例：
https://rsshub.app/bilibili/user/dynamic/35581334

![image](https://user-images.githubusercontent.com/77891959/177203663-2f9fc35f-810d-4921-a9ce-421b7c5b2890.png)

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by shininome** [comment]
可以使用专栏订阅解决问题,

**Comment by HamadaMasatoshi** [comment]
> 可以使用专栏订阅解决问题,

请看完我的描述和示例再提出建议

**Comment by shininome** [comment]
> > 可以使用专栏订阅解决问题,
> 
> 
> 
> 请看完我的描述和示例再提出建议

那你去看下专栏返回的json和其余消息的json吧，

**Comment by HamadaMasatoshi** [comment]
> > > 可以使用专栏订阅解决问题,
> > 
> > 
> > 请看完我的描述和示例再提出建议
> 
> 那你去看下专栏返回的json和其余消息的json吧，

那你看专栏全文能不能在动态的 feed 中完整显示吧，我已经拿微博举例了，自己不看还让别人看别的

**Comment by shininome** [comment]
> > > > 可以使用专栏订阅解决问题,
> > > 
> > > 
> > > 请看完我的描述和示例再提出建议
> > 
> > 
> > 那你去看下专栏返回的json和其余消息的json吧，
> 
> 那你看专栏全文能不能在动态的 feed 中完整显示吧，我已经拿微博举例了，自己不看还让别人看别的
> 
> 专栏的 json 里面有 UP 主的视频投稿吗？动态吗？
> 
> > 目前 Bilibili 的[UP主动态路由](https://docs.rsshub.app/social-media.html#bilibili-up-zhu-dong-tai)，只有是否开启内嵌视频的参数，没有其他参数。
> > 如果UP主发布了视频、图片、文字动态，可以在阅读器里直接浏览。
> > 但是如果发布了专栏，阅读器里只显示专栏封面、文章开头一部分摘要和一个文章链接，还是需要浏览器跳转到专栏页面才能阅读全文。
> 
> 我发 issue 已经写明了，希望视频、图片、文字动态和专栏，都可以在订阅动态的 feed 后直接在阅读器里面浏览，还拿微博举例，微博那边已经做到了。请问微博那边需要单独订阅微博专栏 feed 和普通微博 feed 吗？看不懂就问，别自作聪明。

唔,很有道理,那请求一下你可以照着微博的写一下新的动态路由造福一下愚笨的我吗,谢谢
