### ISSUE TITLE
更新 国家药品监督管理局 的路由

### ISSUE THREAD

**Issue by terrytw** [DIYgod/RSSHub#10129]
### 类型

政务消息

### 网站地址

https://www.nmpa.gov.cn/

### 网站描述

国家药品监督管理局

### 需要生成什么内容？

该网站已由 https://github.com/DIYgod/RSSHub/pull/10108 添加
目前已有路由：
/gov/nmpa/xxgk/ggtg
/gov/nmpa/xxgk/chpzhh/ypzhh
/gov/nmpa/yaopin/ypanqjsh
/gov/nmpa/yaopin/ypjgdt

希望增加路由：
ylqx/ylqxjgdt
ylqx/ylqxggtg
ylqx/ylqxfgwj
ylqx/ylqxzhcjd
xxgk/fxjzh/ylqxfxjch
xxgk/chpzhh/ylqxzhh
xxgk/kpzhsh/kpzhshylqx
xxgk/yjjsh/ylqxblshjtb
yaopin/ypggtg
yaopin/ypfgwj
yaopin/ypzhcjd
xxgk/fxjzh/ypfxjch
xxgk/chpzhh/ypzhh
xxgk/kpzhsh/kpzhshyp

其各页面格式应该完全相同，更新工作量应该不大，感谢了！

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Please read the docs more carefully.
https://docs.rsshub.app/government.html#guo-jia-yao-pin-jian-du-guan-li-ju

[https://rsshub.app/gov/nmpa/ylqx/ylqxjgdt](https://rsshub.app/gov/nmpa/ylqx/ylqxjgdt)  
[https://rsshub.app/gov/nmpa/ylqx/ylqxggtg](https://rsshub.app/gov/nmpa/ylqx/ylqxggtg)
...
so on
should work out of the box.
