### ISSUE TITLE
技术討论区 抓取的是所有主题 会重复抓取 请改成今日主题

### ISSUE THREAD

**Issue by iwanfu** [DIYgod/RSSHub#1013]
今日<https://www.t66y.com/thread0806.php?fid=7&search=today>

**Comment by DIYgod** [comment]
RSS 都会重复抓取

**Comment by iwanfu** [comment]
@DIYgod 所有主题是`按最后回复排序`的这样就会重复 ，今日主题是`按时间排序`的应该不会重复吧？`或者技术討论区再区分一个今日主题的rss`

**Comment by DIYgod** [comment]
@iwanfu get

**Comment by iwanfu** [comment]
@DIYgod 没有更新？ `热门帖子`还是会`推送`两次及以上
