### ISSUE TITLE
请求大佬做个草榴社区的路由，只需要两个图片板块

### ISSUE THREAD

**Issue by xlggit** [DIYgod/RSSHub#10154]
### 类型

图片

### 网站地址

https://www.t66y.com/index.php

### 网站描述

草榴社区是老牌福利分享论坛，包含影片资源的bt种子，和原创自拍图片等

### 需要生成什么内容？

只需要做两个板块，[新時代的我們](https://www.t66y.com/thread0806.php?fid=8)，和[達蓋爾的旗幟](https://www.t66y.com/thread0806.php?fid=16)，这是两个图片分享板块。希望做成已有的2048论坛那种，能无限翻页，而不仅仅只有新增的10条之类的

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Please read the docs carefully.
Https://docs.rsshub.app
