### ISSUE TITLE
希望添加B站的【合集】的采集

### ISSUE THREAD

**Issue by visiLi** [DIYgod/RSSHub#10162]
### 这是一个什么样的功能？

从B站获取UP主的【合集】采集
参考地址如下：https://space.bilibili.com/669944419/channel/seriesdetail?sid=496801

### 这个功能可以解决什么问题？

可以区分当前UP的多个【合集】和【投稿】视频

### 额外描述

依据合集，可以区分管理分类、

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by shininome** [comment]
所以需要内嵌视频吗，要是只是一个封面的预览和标题的预览我应该能很快做出来，内嵌视频的话就需要研究研究了，没做过

**Comment by TonyRL** [comment]
Closed in https://github.com/DIYgod/RSSHub/pull/10470
