### ISSUE TITLE
后续网站路由部分损坏。

### ISSUE THREAD

**Issue by borpubi** [DIYgod/RSSHub#10163]
### 路由地址

```routes
/houxu/:category?
```

### 完整路由地址

```fullroutes
https://rsshub.app/houxu/index
https://rsshub.app/houxu/featured
https://rsshub.app/houxu/memory
https://rsshub.app/houxu/events
```

### 相关文档

https://docs.rsshub.app/new-media.html#hou-xu

### 预期是什么？

正常读取订阅信息流

### 实际发生了什么？

Looks like something went wrong

Route requested: /index

Error message: key.startsWith is not a function

Helpful Information to provide when opening issue:
Path: /index
Node version: v16.3.0
Git Hash: 17402bb
        

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong

Route requested: /index

Error message: key.startsWith is not a function

Helpful Information to provide when opening issue:
Path: /index
Node version: v16.3.0
Git Hash: 17402bb
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by borpubi** [comment]
@nczitzk 请协助检查，谢谢。

**Comment by nczitzk** [comment]
> @nczitzk 请协助检查，谢谢。

该路由在自建服务时正常工作，无法复现该错误，可以考虑先自建服务使用该路由。

**Comment by borpubi** [comment]
> > @nczitzk 请协助检查，谢谢。
> 
> 该路由在自建服务时正常工作，无法复现该错误，可以考虑先自建服务使用该路由。

我使用自建的也会报错：
https://rss.9aidh.com/houxu/index
`Route requested: /index

Error message: key.startsWith is not a function

Helpful Information to provide when opening issue:
Path: /index
Node version: v16.15.1
Git Hash: 14974fa
        `
![image](https://user-images.githubusercontent.com/28093885/177912063-0fcd2b06-0384-4c21-a74e-8b253d81d33a.png)

**Comment by nczitzk** [comment]
了解了。但我在本地自建服务是正常工作的，我再看看 😅

**Comment by KawausoJyou** [comment]
> 我是用 docker 自建的服务。
> 已经删除重新摘取最新版docker file 重新自建了服务。

你的问题解决了吗？我更新RSSHub后还是不行，是需要等待分支合并吗？
