### ISSUE TITLE
Outage.Report 可能的Typo/大小写错误

### ISSUE THREAD

**Issue by lunzima** [DIYgod/RSSHub#10164]
### 路由地址

```routes
/outagereport/ubisoft
```

### 完整路由地址

```fullroutes
/outagereport/ubisoft/5
```

### 相关文档

https://docs.rsshub.app/forecast.html#outage-report

### 预期是什么？

正常输出

### 实际发生了什么？

Error message: Class constructor URL cannot be invoked without 'new'

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
./lib/routes/outagereport/service.js
两处
link: URL
似乎应为
link: url
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lunzima** [comment]
问题和name字段无关

**Comment by lunzima** [comment]
需要同时完成迁移到v2规范路由么？

**Comment by nczitzk** [comment]
#10166 完成了迁移工作

**Comment by lunzima** [comment]
感谢！

**Comment by nczitzk** [comment]
😊
