### ISSUE TITLE
网易号已经无法抓取

### ISSUE THREAD

**Issue by tingmusic** [DIYgod/RSSHub#10177]
### 路由地址

```routes
/netease/dy/:id
```

### 完整路由地址

```fullroutes
/netease/dy2/T1438840302520
```

### 相关文档

https://docs.rsshub.app/new-media.html#wang-yi-hao

### 预期是什么？

能够正常订阅

### 实际发生了什么？

抓取失败，已无法订阅

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/163/dy2/T1438840302520
```

**Comment by TonyRL** [comment]
Closed in #11809
