### ISSUE TITLE
Bloomberg Businessweek

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#10188]
### Category

News

### Website URL

https://www.bloomberg.com/businessweek

### Website description

One of the premier American weekly business magazines covering national as well as international issues with focuses on technology, finance, economics, solutions, pursuits, and more.

### What content should be included?

Title, URI, author, timestamp, content, enclosures such as photos and videos, and categories as well as the full article for articles listed on [the main webpage](https://www.bloomberg.com/businessweek) as well as the five “Latest Issue” magazines listed on the main webpage, which are currently [1](https://www.bloomberg.com/magazine/businessweek/22_29), [2](https://www.bloomberg.com/magazine/businessweek/22_28), [3](https://www.bloomberg.com/magazine/businessweek/22_27), [4](https://www.bloomberg.com/magazine/businessweek/22_26), and [5](https://www.bloomberg.com/magazine/businessweek/22_24).

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Closed in #11131
