### ISSUE TITLE
NGA 网事杂谈分区 路由报错

### ISSUE THREAD

**Issue by OpenWaygate** [DIYgod/RSSHub#10185]
### 路由地址

```routes
/nga/forum/:fid/:recommend?
```

### 完整路由地址

```fullroutes
https://rsshub.app/nga/forum/-7
```

### 相关文档

https://docs.rsshub.app/bbs.html#nga-fen-qu-tie-zi

### 预期是什么？

正常显示

### 实际发生了什么？

报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /nga/forum/-7
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /nga/forum/-7
Node version: v16.3.0
Git Hash: 56fc5fd
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://bbs.nga.cn/thread.php?fid=-7 requires logging in. You need to [host your own instance](https://docs.rsshub.app/en/install/).
