### ISSUE TITLE
希望增加sankakucomplex的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#1019]
-   需求描述 | Description ：主页 或者 more popular images
-   源网站地址 | Website URL： https://idol.sankakucomplex.com/ 或者 https://idol.sankakucomplex.com/?tags=order%3Apopular

**Comment by DIYgod** [comment]
源站提供 RSS: https://idol.sankakucomplex.com/post/atom

**Comment by tomatomash** [comment]
> 源站提供 RSS: https://idol.sankakucomplex.com/post/atom

我已经订阅过，但无论在feedly还是inoreader上，结果显示图片都是https://idol.sankakucomplex.com/redirect.png
尝试过做feed43，做好之后也是显示这个redirect.png

**Comment by DIYgod** [comment]
@tomatomash 应该是源站加了防盗链，没什么好办法

**Comment by xyqfer** [comment]
我觉得是地址的锅，应该不是防盗链的问题，晚点我试下看看：
<img width="743" alt="wx20181101-213358 2x" src="https://user-images.githubusercontent.com/5186792/47854878-ef990180-de1d-11e8-897f-491f17d518b3.png">

[http://is.sankakucomplex.com/data/preview/b0/7b/b07b496560bd3c79ad9c7fe239758b52.jpg](http://is.sankakucomplex.com/data/preview/b0/7b/b07b496560bd3c79ad9c7fe239758b52.jpg)

**Comment by tomatomash** [comment]
@xyqfer 感谢大佬！

**Comment by tomatomash** [comment]
ty guys @DIYgod @xyqfer

**Comment by tomatomash** [comment]
https://rsshub.app/sankakucomplex/post在inoreader和feedly上都找不到，直接打开是显示“RSSHub 发生了一些意外”

**Comment by DIYgod** [comment]
@xyqfer heroku 请求源站返回 500 了...可能是 heroku 的问题

**Comment by tomatomash** [comment]
大佬们，这个是不是搞不定了？ (ノへ￣、)

**Comment by xyqfer** [comment]
建议有条件自己部署试下，本地测试是好的，目测如上面所说可能是 heroku 的问题 🌚

**Comment by tomatomash** [comment]
如果是用到vps的话，我明年准备弄，今年看来没戏了，谢谢大佬
