### ISSUE TITLE
小红书路由多次失效

### ISSUE THREAD

**Issue by dasoumao** [DIYgod/RSSHub#10198]
### 路由地址

```routes
/xiaohongshu/user/:user_id/notes
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/62a1afbf0000000021020ffb/notes
```

### 相关文档

https://docs.rsshub.app/social-media.html#xiao-hong-shu

### 预期是什么？

返回正常抓取结果

### 实际发生了什么？

未能返回抓取结果，返回包括503等错误

### 部署

自建

### 部署相关信息

Debian Docker

### 额外信息

```shell
Route requested: /user/62a1afbf0000000021020ffb/notes
Error message: Protocol error (Runtime.callFunctionOn): Target closed.
Helpful Information to provide when opening issue:
Path: /user/62a1afbf0000000021020ffb/notes
Node version: v16.16.0
Git Hash: 749f2fe
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dasoumao** [comment]
机器人识别不到小红书路由
打开页面显示如下：
Route requested: /user/62a1afbf0000000021020ffb/notes
Error message: Protocol error (Runtime.callFunctionOn): Target closed.
Helpful Information to provide when opening issue:
Path: /user/62a1afbf0000000021020ffb/notes
Node version: v16.16.0
Git Hash: 749f2fe

rsshub路由也显示失败

**Comment by TonyRL** [comment]
The page https://www.xiaohongshu.com/user/profile/593032945e87e77791e03696 is protected by captcha.

**Comment by cxumol** [comment]
Use some URL params to bypass captcha

```
?app_platform=android&app_version=7.47.0&share_from_user_hidden=true&xhsshare=CopyLink&appuid=XXXXXXXXXXXXXXXXXXXX&apptime=XXXXXXXXXX
```

```
?xhsshare=WeixinSession&appuid=XXXXXXXXXXXXXXXXXXXX&apptime=XXXXXXXXXX
```

You have to use their APP to get these params.

Life time are unknow, though should be long

**Comment by Achilles-10** [comment]
> Use some URL params to bypass captcha
> 
> ```
> ?app_platform=android&app_version=7.47.0&share_from_user_hidden=true&xhsshare=CopyLink&appuid=XXXXXXXXXXXXXXXXXXXX&apptime=XXXXXXXXXX
> ```
> 
> ```
> ?xhsshare=WeixinSession&appuid=XXXXXXXXXXXXXXXXXXXX&apptime=XXXXXXXXXX
> ```
> 
> You have to use their APP to get these params.
> 
> Life time are unknow, though should be long

What does the complete routing address look like after adding these parameters

**Comment by TonyRL** [comment]
/test
```routes
/xiaohongshu/user/62a1afbf0000000021020ffb/notes
```
