### ISSUE TITLE
微博Issue - 付费图片显示错误

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#102]
weibo url: `https://weibo.com/1111681197/Gfnl0iFMw`

![image](https://user-images.githubusercontent.com/10363328/39955125-a1dbfdd4-55fc-11e8-9f7d-c6bf669ddf1c.png)

![image](https://user-images.githubusercontent.com/10363328/39955128-b1dbcdfe-55fc-11e8-9f86-d1b37f30ffca.png)

**Comment by DIYgod** [comment]
@DerekTso 想多了

**Comment by HenryQW** [comment]
需要一个更新的例子来修复这个问题
