### ISSUE TITLE
NHK日本國際傳媒

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#10208]
### 类型

新媒体

### 网站地址

https://www3.nhk.or.jp/nhkworld/

### 网站描述

关于NHK日本国际传媒: https://www3.nhk.or.jp/nhkworld/zh/about/

> NHK日本国际传媒是日本公共传媒机构NHK的对外播出平台，通过电视、广播以及互联网，向全球受众提供日本乃至亚洲的最新资讯。

![image](https://user-images.githubusercontent.com/86122516/178689600-c60d5406-31ab-4e9a-90f7-73b2fc0409b6.png)

wikipedia: https://zh.m.wikipedia.org/zh-hant/NHK%E6%97%A5%E6%9C%AC%E5%9B%BD%E9%99%85%E4%BC%A0%E5%AA%92

https://github.com/DIYgod/RSSHub/issues/8105

### `新聞一覽`
- https://www3.nhk.or.jp/nhkworld/zh/news/list/
- https://www3.nhk.or.jp/nhkworld/zt/news/list/

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/traditional-media.html#nhk

**Comment by c2xusnpq6** [comment]
我剛可能沒有說清楚，但我要的是可以篩選子類別，因為我只想nhk搞的「亞洲」新聞以及「全球」新聞。請把它重新打開~ 🤔😃🤝 @TonyRL 

![](https://user-images.githubusercontent.com/75058881/178755385-2d6564e7-2cf2-4211-9488-f0aee5ec404b.png)

![](https://user-images.githubusercontent.com/75058881/178755417-81ea340b-211c-4fc7-88a8-31f074111640.png)

@nczitzk

**Comment by wft44maqb** [comment]
我剛可能沒有說清楚，但我要的是可以篩選子類別，因為我只想nhk搞的「亞洲」新聞以及「全球」新聞。請把它重新打開~ 🤔😃🤝 @TonyRL

![](https://user-images.githubusercontent.com/75058881/178755385-2d6564e7-2cf2-4211-9488-f0aee5ec404b.png)

![](https://user-images.githubusercontent.com/75058881/178755417-81ea340b-211c-4fc7-88a8-31f074111640.png)

@nczitzk
