### ISSUE TITLE
缺省格式设置为 Atom

### ISSUE THREAD

**Issue by RivenNero** [DIYgod/RSSHub#10202]
### 这是一个什么样的功能？

建议将缺省格式设置为 Atom 而不是 RSS 2.0

### 这个功能可以解决什么问题？

Atom 本身就是 RSS 2.0 的改进版本，优于 RSS 2.0。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Closing this in favour of https://github.com/DIYgod/RSSHub/issues/10807
