### ISSUE TITLE
博客订阅源请求

### ISSUE THREAD

**Issue by BaldStrong** [DIYgod/RSSHub#10217]
### 类型

博客

### 网站地址

https://danielw.cn/

### 网站描述

分布式系统

### 需要生成什么内容？

RSS订阅

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://danielw.cn/feed.xml
