### ISSUE TITLE
[Wanted] php.cn RSS

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#1022]
## 新 RSS 需求 | New RSS requirement

-   需求描述 | Description ：php中文网的技术文章RSS, e.g. H5教程
-   是否已提供官网 RSS | Does the website provide an official RSS feed：No
-   源网站地址 | Website URL：http://www.php.cn/html5-tutorial.html

**Comment by xyqfer** [comment]
话说这种正文里有大量代码内容的输出全文看效果可能会不太好的(代码挤成一团没换行什么的)，建议是做更新提醒然后去原文看不输出全文
