### ISSUE TITLE
为什么自己fork rsshub自建服务器后，有些路由会出错

### ISSUE THREAD

**Issue by lblbk** [DIYgod/RSSHub#10244]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
https://rsshub.app/36kr/newsflashes
https://heroku.lblbk.fun/36kr/user/5652071
```

### 相关文档

https://docs.rsshub.app/new-media.html#_36kr-sou-suo-wen-zhang

### 预期是什么？

使用官方和自建的服务器，访问同一个路由，自建服务器无法访问，这不是第一次遇到这个问题，在提交issue之前我甚至重新fork了仓库，不知道这是什么问题

### 实际发生了什么？

自建服务器去访问的时候会提示路由错误

### 部署

自建

### 部署相关信息

heroku

### 额外信息

```shell
Route requested: /user/5652071
Error message: Response code 405 (Not Allowed): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /user/5652071
Node version: v16.14.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/36kr/newsflashes
/36kr/user/5652071
```

**Comment by hi-unc1e** [comment]
因为你抓取网页的请求方式有问题。应该是get，可能不小心弄成了post。
