### ISSUE TITLE
BleachBit

### ISSUE THREAD

**Issue by RivenNero** [DIYgod/RSSHub#10252]
### 类型

程序更新

### 网站地址

https://www.bleachbit.org/download

### 网站描述

BleachBit 官网下载页面

### 需要生成什么内容？

BleachBit 更新推送

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nczitzk** [comment]
https://www.bleachbit.org/blog/1/feed

**Comment by RivenNero** [comment]
> https://www.bleachbit.org/blog/1/feed

Thank you!
