### ISSUE TITLE
新需求：安理会五常又行使否决权了

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#1026]
## 新 RSS 需求 | New RSS requirement

-   需求描述 | Description ：想看安理会五常在什么决议上耍流氓
-   是否已提供官网 RSS | No
-   源网站地址 | Website URL：https://en.wikipedia.org/wiki/List_of_vetoed_United_Nations_Security_Council_resolutions

**Comment by sgqy** [comment]
获取页面源代码：`append ?action=raw`
https://en.wikipedia.org/wiki/List_of_vetoed_United_Nations_Security_Council_resolutions?action=raw

**Comment by HenryQW** [comment]
@sgqy 这个新技能厉害了

**Comment by DIYgod** [comment]
厉害了，还以为 [维基百科-中国大陆新闻动态](https://docs.rsshub.app/#%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91) 能用上，但[这个页面](https://zh.wikipedia.org/wiki/Portal:%E4%B8%AD%E5%9C%8B%E5%A4%A7%E9%99%B8%E6%96%B0%E8%81%9E%E5%8B%95%E6%85%8B)没效果

**Comment by sgqy** [comment]
来试试[这个](https://zh.wikipedia.org/wiki/2018%E5%B9%B410%E6%9C%88%E4%B8%AD%E5%9B%BD?action=raw) :thinking:

**Comment by DIYgod** [comment]
Done. 8afe64a8f49fa3c80accf019c2aafe83481f8532
