### ISSUE TITLE
能不能弄个虎扑的RSS，感谢

### ISSUE THREAD

**Issue by ListeningLTG** [DIYgod/RSSHub#1027]
## 新 RSS 需求 | New RSS requirement

-   需求描述 | Description ：如题
-   是否已提供官网 RSS | Does the website provide an official RSS feed：No
-   源网站地址 | Website URL：https://www.hupu.com/

**Comment by Wei-Xia** [comment]
如果只是虎扑 NBA 新闻的话，他们已经有现成的 RSS 了。 https://voice.hupu.com/generated/voice/news_nba.xml

其他球类没有查，不知道有没有。

**Comment by ListeningLTG** [comment]
> 如果只是虎扑NBA新闻的话，他们已经有现成的RSS了。https://voice.hupu.com/generated/voice/news_nba.xml
> 
> 其他球类没有查，不知道有没有。

感谢！
