### ISSUE TITLE
新 RSS 需求 | 希望新增国外新闻媒体中文网 RSS

### ISSUE THREAD

**Issue by SKY-rainbow-lh** [DIYgod/RSSHub#1028]
## 新 RSS 需求 | New RSS requirement

-   需求描述 | Description ：有些国外比较知名的新闻媒体面向中国开设的中文站有 RSS 订阅功能，有些没有，可以的话希望能整合一下，放到新分类里面，也方便订阅

**Comment by tgly307** [comment]
国外比较知名的新闻媒体具体指什么，这怎么让人做？建议按照issue模板填写内容。

**Comment by HenryQW** [comment]
有些国外比较知名的新闻媒体面向中国开设的中文站 RSSHub 已经支持了，有些没有，可以的话希望能整合一下，放到 issue 描述里面，也方便开发
