### ISSUE TITLE
中華共和囯商務部

### ISSUE THREAD

**Issue by wcsolski** [DIYgod/RSSHub#10289]
### Category

Government

### Website URL

http://www.mofcom.gov.cn/article/xwfb/

### Website description

Government articles

### What content should be included?

.

### Additional description

Can anyone please add this site to RSS feed?

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://docs.rsshub.app/government.html#zhong-hua-ren-min-gong-he-guo-shang-wu-bu

**Comment by wcsolski** [comment]
Thank you for replying. 

A small bug exists, e.g. I can't grab http://www.mofcom.gov.cn/article/xwfb/xwrcxw/ 's RSS feed through https://rsshub.app/mofcom/article/xwfb/xwrcxw;
