### ISSUE TITLE
可以添加不支持的网页吗

### ISSUE THREAD

**Issue by monnerHenster** [DIYgod/RSSHub#1029]
我想要一些比较小众的网站的rss源，虽然已经通过feed43做了源，但是他的更新时间比较慢，能够使用rsshub生成rss吗。这些网站不在公共路由里。

**Comment by tgly307** [comment]
rsshub支持的rss内容都需要单独写路由逻辑，思路和feed43是类似的。

**Comment by monnerHenster** [comment]
> rsshub支持的rss内容都需要单独写路由逻辑，思路和feed43是类似的。

有路由逻辑模板么，我可以自己写完上传上来~我想做个GNN的源。

**Comment by tgly307** [comment]
项目routes文件夹下所有的路由都是参考，选个类似情况的照葫芦画瓢写一下就好了。

**Comment by monnerHenster** [comment]
> 项目routes文件夹下所有的路由都是参考，选个类似情况的照葫芦画瓢写一下就好了。

3Q~

**Comment by monnerHenster** [comment]
找了好几个 没看懂怎么写阿，例如电影天堂的路由表，都没看懂匹配规则在哪。。我本身不是搞代码的。
