### ISSUE TITLE
起点章节路由、讨论区路由错误

### ISSUE THREAD

**Issue by cmj2002** [DIYgod/RSSHub#10319]
### 路由地址

```routes
/qidian/chapter/:id
/qidian/forum/:id
```

### 完整路由地址

```fullroutes
/qidian/chapter/1010400217
/qidian/forum/1010400217
```

### 相关文档

https://docs.rsshub.app/reading.html#qi-dian

### 预期是什么？

获取信息并正确生成 RSS Feed

### 实际发生了什么？

章节：`Error message: Cannot read property 'split' of undefined`

讨论区：`Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.`

讨论区应该并不是因为反爬被禁的，我使用部署在香港的私人实例也得到相同结果。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

演示站, Node version: v16.3.0, Git Hash: 2af4df2

### 额外信息

拿不到演示站日志，用的私人实例日志。

```shell
info: /qidian/forum/1010400217, user IP: 172.16.0.1
error: Error in /qidian/forum/1010400217: Response code 404 (Not Found): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.
info: /qidian/chapter/1010400217, user IP: 172.16.0.1
error: Error in /qidian/chapter/1010400217: Cannot read properties of undefined (reading 'split')
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by cmj2002** [comment]
应该是起点更新了反爬策略。而且即使是使用 puppeteer 也触发了验证码（在CodeSpaces环境下，也可能是因为IP在新加坡）

**Comment by shininome** [comment]
章节加密了= =，等研究研究怎么解密吧
