### ISSUE TITLE
Bug quando o user do tiktok começa com _

### ISSUE THREAD

**Issue by peraltaespectro** [DIYgod/RSSHub#10328]
### Routes

```routes
ERROR: Erro de código de status HTTP (404 Not Found)
```

### Full routes

```fullroutes
/test https://rsshub.app/tiktok/user/_vitali01_
```

### Related documentation

/test https://rsshub.app/tiktok/user/_vitali01_

### What is expected?

/test https://rsshub.app/tiktok/user/_vitali01_

### What is actually happening?

Quando eu quero vê um perfil do tiktok que começa com _ ele da erro

Exemplo 

/test https://rsshub.app/tiktok/user/_vitali01_

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Linux 18.4

### Additional info

```shell
ERROR: Erro de código de status HTTP (404 Not Found)
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please take a look at the docs first 
https://docs.rsshub.app
