### ISSUE TITLE
98堂 - have two magnet link together

### ISSUE THREAD

**Issue by tony-hk** [DIYgod/RSSHub#10321]
### Routes

```routes
/dsndsht23/gqzwzm
```

### Full routes

```fullroutes
https://rsshub.app/dsndsht23/gqzwzm
```

### Related documentation

https://rsshub.app/dsndsht23/gqzwzm

### What is expected?

Get first magnet link in RSS

### What is actually happening?

![image](https://user-images.githubusercontent.com/40762298/180670681-1ed11b88-1d93-46ec-8dc8-39e581512975.png)

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Linux

### Additional info

```shell
Can't get the magnet link automatically.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by tyhunter** [comment]
temporarily found this situation at https://rsshub.app/dsndsht23/gqzwzm and https://rsshub.app/dsndsht23/yzwmyc, and seems it was the publisher wanted to avoid block by 115Yun so have to make two different magnet, the first is normal and the second is anti-block, but in rsshub program, those two magnets had sum to one magnet make the qbitorrent or other BitTorrent client can't read correctly
