### ISSUE TITLE
“今日热榜” 路由功能失效 

### ISSUE THREAD

**Issue by q1ngs** [DIYgod/RSSHub#10329]
### Routes

```routes
https://rsshub.app/tophub/:id
```

### Full routes

```fullroutes
https://rsshub.app/tophub/5VaobgvAj1
```

### Related documentation

https://docs.rsshub.app/new-media.html#jin-ri-re-bang

### What is expected?

正常返回数据

### What is actually happening?

Route requested: /tophub/5VaobgvAj1
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /tophub/5VaobgvAj1
Node version: v16.3.0
Git Hash: bb1279e

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Route requested: /tophub/5VaobgvAj1
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /tophub/5VaobgvAj1
Node version: v16.3.0
Git Hash: bb1279e

- https://rsshub.app/tophub/5VaobgvAj1
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/tophub/5VaobgvAj1
```
