### ISSUE TITLE
经济学人 The Economist 无法抓取全文

### ISSUE THREAD

**Issue by aturret** [DIYgod/RSSHub#10335]
### 路由地址

```routes
/economist/:endpoint
```

### 完整路由地址

```fullroutes
/economist/latest
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#the-economist

### 预期是什么？

可以输出全文

### 实际发生了什么？

从两周前开始无法抓取全文

### 部署

自建

### 额外信息

```shell
详见：https://rsshub.app/economist/latest
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ImSingee** [comment]
看上去是因为经济学人最近 UI 框架换成了 NextJS 整个结构变了；简单看了下不是很好办，我周末看看有没有办法搞定
