### ISSUE TITLE
桃花族

### ISSUE THREAD

**Issue by tony-hk** [DIYgod/RSSHub#10338]
### 类型

音视频

### 网站地址

http://61thz.com/forum.php?mod=forumdisplay&fid=181&filter=typeid&typeid=770

### 网站描述

BT 下載網站

### 需要生成什么内容？

RSS feed

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/bbs.html#discuz
