### ISSUE TITLE
javdb rackings routing issue

### ISSUE THREAD

**Issue by starowner** [DIYgod/RSSHub#10373]
### 路由地址

```routes
/javdb/rankings/:category?/:time?
```

### 完整路由地址

```fullroutes
/javdb/rackings/uncensored/monthly
/javdb/rackings/censored/monthly
```

### 相关文档

https://docs.rsshub.app/multimedia.html#javdb

### 预期是什么？

get a rss list from my own rsshub

### 实际发生了什么？

It's not working both on rsshub.app and my own rsshub

### 部署

自建

### 部署相关信息

Docker: 3.0.56

### 额外信息

```shell
Looks like something went wrong
Route requested: /rackings/uncensored/monthly
Error message: getaddrinfo ENOTFOUND javdb.comrackings: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /rackings/uncensored/monthly
Node version: v16.16.0
Git Hash: 640c310
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
From the log you provided, you used ra**c**kings instead of ra**n**kings

**Comment by starowner** [comment]
> From the log you provided, you used ra**c**kings instead of ra**n**kings

I used the "https://myrsshub.xxx.com:8443/javdb/rankings/uncensored/monthly"

below is the result:

Looks like something went wrong
Route requested: /rankings/uncensored/monthly
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /rankings/uncensored/monthly
Node version: v16.16.0
Git Hash: 640c310

but "https://myrsshub.xxx.com:8443/javdb/"is working fine.
