### ISSUE TITLE
财联社不能提取

### ISSUE THREAD

**Issue by cafebox** [DIYgod/RSSHub#10399]
### 路由地址

```routes
cls/depth/1000
cls/telegraph/red
```

### 完整路由地址

```fullroutes
https://myrss-nine.vercel.app/cls/telegraph/red
https://myrss-nine.vercel.app/cls/depth/1000
```

### 相关文档

https://docs.rsshub.app/finance.html#cai-lian-she

### 预期是什么？

恢复RSS提取

### 实际发生了什么？

无法提取

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/cls/depth/1000
/cls/telegraph/red
```
