### ISSUE TITLE
36kr #资讯 报错

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#10398]
### 路由地址

```routes
/36kr/information/
```

### 完整路由地址

```fullroutes
https://rsshub.app/36kr/information/web_news
```

### 相关文档

https://docs.rsshub.app/new-media.html#_36kr

### 预期是什么？

返回正常rss输出

### 实际发生了什么？

Looks like something went wrong
Route requested: /information/web_news
Error message: Cannot read property 'replace' of undefined
Helpful Information to provide when opening issue:
Path: /information/web_news
Node version: v16.3.0
Git Hash: c7796fb

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

https://rsshub.app

### 额外信息

```shell
Looks like something went wrong
Route requested: /information/web_news
Error message: Cannot read property 'replace' of undefined
Helpful Information to provide when opening issue:
Path: /information/web_news
Node version: v16.3.0
Git Hash: c7796fb
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Jkker** [comment]
这个报错大概率是触发了36氪的反爬rate limit导致的。36氪更新反爬策略后每日限额挺低的，正常使用有的时候都会被临时ban掉IP。

**Comment by TonyRL** [comment]
/test
```routes
/36kr/information/web_news
```
