### ISSUE TITLE
请求开通bilibili 直播rss源

### ISSUE THREAD

**Issue by huobaolajiao** [DIYgod/RSSHub#104]
1按照分区/标签检索，如：户外，学习
2按照关键词检索，如：无人机，写代码
3.......更多打开方式

tips：可能存在的非技术问题：时效性及服务器压力。
如果觉得合适敬请采纳，或者我日后尝试开发，如果不喜欢，请随意关闭issue
ps：非常支持RSSHub这个项目，今年我脑海里一直有个“统一信息处理平台”的设想，但尝试demo不尽人意，现在私以为rss是个很好链接爬虫数据和订阅消息的方式，暑假尝试来壮大此项目

**Comment by DIYgod** [comment]
具体用途可能是什么？暂时并没有想到可能的应用场景

时效默认为固定的5分钟；服务器压力并不大

**Comment by huobaolajiao** [comment]
监控感兴趣的直播内容，非特定up的开播吧
