### ISSUE TITLE
贴吧 帖子动态、楼主动态 路由失效

### ISSUE THREAD

**Issue by stainge** [DIYgod/RSSHub#10407]
### 路由地址

```routes
/tieba/post/:id
/tieba/post/lz/:id
```

### 完整路由地址

```fullroutes
/tieba/post/7171344019
/tieba/post/lz/7171344019
```

### 相关文档

https://docs.rsshub.app/bbs.html#tie-ba

### 预期是什么？

获取信息并正确生成 RSS Feed

### 实际发生了什么？

两个路由均报错`Error message: Pseudo-selector has cannot be quoted`

### 部署

自建

### 额外信息

```shell
Route requested: /tieba/post/7171344019
Error message: Pseudo-selector has cannot be quoted
Helpful Information to provide when opening issue:
Path: /tieba/post/7171344019
Node version: v16.15.0
Git Hash: d4f340e
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by axojhf** [comment]
碰到了同样的问题，不知道doc上写的维护者能不能帮帮忙解决一下 @u3u
