### ISSUE TITLE
Error RSSHub无法访问

### ISSUE THREAD

**Issue by fireindark707** [DIYgod/RSSHub#10408]
### 路由地址

```routes
/archdaily
```

### 完整路由地址

```fullroutes
/archdaily
```

### 相关文档

https://rsshub.app/archdaily

### 预期是什么？

显示RSS页面

### 实际发生了什么？

Looks like something went wrong
Route requested: /archdaily
Error message: This path is currently fetching, please come back later!
Helpful Information to provide when opening issue:
Path: /archdaily
Node version: v16.16.0
Git Hash: d4f340e

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
几乎所有Rsshub演示地址都有这个问题
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/archdaily
```
