### ISSUE TITLE
电影天堂 路由返回empty

### ISSUE THREAD

**Issue by tyhunter** [DIYgod/RSSHub#10416]
### 路由地址

```routes
/dytt
```

### 完整路由地址

```fullroutes
/dytt
```

### 相关文档

https://docs.rsshub.app/multimedia.html#dian-ying-tian-tang

### 预期是什么？

Can Get the detail of this route
可以正常访问

### 实际发生了什么？

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /dytt
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /dytt
Node version: v16.16.0
Git Hash: 0f4404a
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by tyhunter** [comment]
路由地址：https://rsshub.app/dytt

**Comment by TonyRL** [comment]
/test
```routes
/dytt
```
