### ISSUE TITLE
[BilibiliUP 主投稿]部分UID无法订阅

### ISSUE THREAD

**Issue by broven** [DIYgod/RSSHub#1041]
### **问题描述 | Description**

在使用RSShub进行订阅 `BilibiliUP 主投稿`时发现有些uid无法订阅
复现:
- https://rsshub.app/bilibili/user/video/10345615
- https://rsshub.app/bilibili/user/video/35789774
- https://rsshub.app/bilibili/user/video/25876945
- https://rsshub.app/bilibili/user/video/1885078
up的个人页:
- https://space.bilibili.com/10345615/#/
- https://space.bilibili.com/35789774/#/
### **路由地址 | Involved route**
/bilibili/user/video/:uid

**Comment by broven** [comment]
https://rsshub.app/bilibili/user/video/25876945

**Comment by DIYgod** [comment]
最近偶尔会崩溃，暂时已经好了
