### ISSUE TITLE
海角社区rss不能用

### ISSUE THREAD

**Issue by jy53655** [DIYgod/RSSHub#10423]
### 路由地址

```routes
/hjedd/hot
```

### 完整路由地址

```fullroutes
https://rsshub.app/hjedd/hot
```

### 相关文档

https://docs.rsshub.app/bbs.html#guang-gu-she-qu

### 预期是什么？

能通过https://rsshub.app/使用rss

### 实际发生了什么？

无法使用,所有子板块的rss都无法使用

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /hot
Error message: key.startsWith is not a function
Helpful Information to provide when opening issue:
Path: /hot
Node version: v16.16.0
Git Hash: 76cf3e9
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by shininome** [comment]
太刺激了，我可能撑不到做完  = =，我还以为是海外生活之类的

**Comment by jy53655** [comment]
> 太刺激了，我可能撑不到做完 = =，我还以为是海外生活之类的

**Comment by jy53655** [comment]
兄弟加油，你可以的

**Comment by leezone** [comment]
又不能用了，好像域名换了，哪位大佬给看看？
