### ISSUE TITLE
上海市药品监督管理局 route 505错误

### ISSUE THREAD

**Issue by terrytw** [DIYgod/RSSHub#10420]
### 路由地址

```routes
/gov/shanghai/yjj/:path+
```

### 完整路由地址

```fullroutes
/gov/shanghai/yjj/zx-ylqx
/gov/shanghai/yjj/ykqxaqxcz
/gov/shanghai/yjj/fg-ylqx
/gov/shanghai/yjj/zcjd
/gov/shanghai/yjj/zxts
```

### 相关文档

https://docs.rsshub.app/government.html#shang-hai-shi-ren-min-zheng-fu-shang-hai-shi-yao-pin-jian-du-guan-li-ju

### 预期是什么？

正常获取

### 实际发生了什么？

505错误

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
上周五开始这几个route就基本上反复505报错
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nczitzk** [comment]
上述路由本地部署测试工作正常，可以自建 RSSHub 使用该路由 😊

**Comment by TonyRL** [comment]
<details><summary>/gov/shanghai/yjj/zx-ylqx</summary>

![image](https://user-images.githubusercontent.com/11386903/183464605-4fda7cbb-7249-4307-b979-f65adce8d77d.png)

</details>
