### ISSUE TITLE
需要javbus的系列feed和导演feed

### ISSUE THREAD

**Issue by luckyhacking** [DIYgod/RSSHub#10431]
### 类型

论坛

### 网站地址

https://www.javbus.com/

### 网站描述

目前rsshub提供的javbus相关feed不提供系列feed和导演feed，比如：

- [REBD - 搜尋 - 影片 - JavBus](https://www.javbus.com/search/REBD&type=&parent=ce)
- [紋℃ - 導演 - 影片](https://www.javbus.com/director/9p)

### 需要生成什么内容？

系列和导演的feed

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
/test
```routes
/javbus/studio/pw
/javbus/director/9p
```
https://docs.rsshub.app/multimedia.html#javbus
Please read the docs carefully
![pic](https://user-images.githubusercontent.com/11386903/183801851-84c5f224-9de1-42c6-8661-2d97a1dcf06d.png)
