### ISSUE TITLE
科学期刊 - Nature 系列 - Nature挂了

### ISSUE THREAD

**Issue by ImVictorCheng** [DIYgod/RSSHub#10448]
### 路由地址

```routes
/research/nature
```

### 完整路由地址

```fullroutes
https://rsshub.app/nature/research/nature
```

### 相关文档

https://rsshub.app/nature/research/nature

### 预期是什么？

正常抓取内容

### 实际发生了什么？

Looks like something went wrong
Route requested: /research/nature
Error message: Cannot read properties of null (reading 'mainEntity')
Helpful Information to provide when opening issue:
Path: /research/nature
Node version: v16.16.0
Git Hash: 7c171c8

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/nature/research/nature
```
