### ISSUE TITLE
中南大学 计算机学院 rss失效

### ISSUE THREAD

**Issue by suradaBANG** [DIYgod/RSSHub#10440]
### 路由地址

```routes
/csu/cse/:type?
```

### 完整路由地址

```fullroutes
/csu/cse
/csu/cse/xyxw
/csu/cse/tzgg
/csu/cse/xsxx
```

### 相关文档

https://docs.rsshub.app/university.html#zhong-nan-da-xue

### 预期是什么？

成功展示中南大学计算机学院各项通知信息

### 实际发生了什么？

无法使用

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /cse
Error message: key.startsWith is not a function
Helpful Information to provide when opening issue:
Path: /cse
Node version: v16.16.0
Git Hash: d5165be
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by j1g5awi** [comment]
和 Node 版本有关，我自己的实例没问题。

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/blob/a03d51ae2dcd32800c4b772afe0f1008bbad55af/lib/v2/csu/cse.js#L20

The key must be `string` instead of `URL`

**Comment by j1g5awi** [comment]
Ok，I will fix it.

**Comment by suradaBANG** [comment]
> Ok，I will fix it.

![Z8SYNDBUCU %X{MMT%IFU$0](https://user-images.githubusercontent.com/50293246/184096916-8062139a-2260-4d10-a15e-1531367b6af3.gif)
