### ISSUE TITLE
能否给一个明确的设置项，让我可以连接带密码的redis

### ISSUE THREAD

**Issue by ggtony233** [DIYgod/RSSHub#10452]
### 这是一个什么样的功能？

如题

### 这个功能可以解决什么问题？

降低redis数据库被爆破的风险

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
https://stackoverflow.com/questions/44344628/how-to-create-a-redis-cloud-connection-url-with-an-auth-password
