### ISSUE TITLE
能不能给文档加个配置好的config.js的范本

### ISSUE THREAD

**Issue by EnderAvaritia** [DIYgod/RSSHub#10462]
### 这是一个什么样的功能？

希望能给个配置好的config.js的范本

### 这个功能可以解决什么问题？

现在配置服务，完全不知道我不能使用是因为填的是格式错误还是啥，应该填啥格式我也不知道……
如果有个范本的话多少知道点。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
You should **NOT** edit `lib/config.js` directly. You should provide the value through environment variable. The format varies as it depends on how you deploy your instance.

**Comment by EnderAvaritia** [comment]
> You should **NOT** edit `lib/config.js` directly. You should provide the value through environment variable. The format varies as it depends on how you deploy your instance.
![image](https://user-images.githubusercontent.com/84321282/184927795-b70c79b5-f6ef-4e89-81bb-e44c47db6998.png)
it seems i have trouble for my  sbility of understanding it can't work (running in vercel)
