### ISSUE TITLE
pianyuan网RSS失效

### ISSUE THREAD

**Issue by dechunwang** [DIYgod/RSSHub#10473]
### Routes

```routes
/pianyuan/index/:media?
```

### Full routes

```fullroutes
/pianyuan/index/
/pianyuan/index/tv
/pianyuan/index/mv
```

### Related documentation

https://docs.rsshub.app/multimedia.html#pian-yuan-wang

### What is expected?

返回对应RSS。

### What is actually happening?

<img width="758" alt="image" src="https://user-images.githubusercontent.com/16343127/184593960-167affe8-8092-42a6-96ee-c83c148130c0.png">
Error message: key.startsWith is not a function
无法访问。

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

ubuntu via docker-compose

### Additional info

```shell
部署所用docker-compose.yaml

version: '3'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'  # marked
            PIANYUAN_COOKIE: "py_loginauth=xxxxxxxxxxx"
        depends_on:
            - redis
            - browserless  # marked

    browserless:  # marked
        image: browserless/chrome  # marked
        restart: always  # marked
        ulimits:  # marked
          core:  # marked
            hard: 0  # marked
            soft: 0  # marked

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:

docker logs：
: Error in /index/mv: key.startsWith is not a function
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please test again with the latest docker image

**Comment by dechunwang** [comment]
最新版的已经可以使用， 感谢大神。
就是feedbro 加载不了， 很奇怪， 估计是feedbro的问题。
