### ISSUE TITLE
Bilibili UP 主所有视频，似乎即使自建也容易触发反爬

### ISSUE THREAD

**Issue by cyx20080216** [DIYgod/RSSHub#10511]
### 路由地址

```routes
/bilibili/user/video-all/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video-all/335098315
/bilibili/user/video-all/436361287
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

正常返回RSS数据

### 实际发生了什么？

当访问第二条地址时，RSSHub报错

另外，访问两条地址后，浏览器可以正常浏览有关网页（已禁用缓存），但Python爬虫库`requests_html`调用有关API时会返回`412`

### 部署

自建

### 部署相关信息

Windows, Node: v18.7.0

### 额外信息

```shell
Route requested: /user/video-all/436361288
Error message: Response code 412 (Precondition Failed): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /user/video-all/436361288
Node version: v18.7.0
Git Hash: 6b34eb8
```

### 这不是重复的 issue

- [x] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by CcccFz** [comment]
@cyx20080216 感谢您使用此路由，并指出该问题，我将在近期修复该问题

**Comment by CcccFz** [comment]
@cyx20080216 B站反爬太严，/bilibili/user/video/335098315仅获取单页的视频也会被限制。待认识的爬虫高人有空时，为我指导一二

**Comment by cyx20080216** [comment]
知道了，谢谢，我最近也遇到了这种情况

**Comment by cyx20080216** [comment]
刚刚测试了一下，似乎可以通过先访问`https://www.bilibili.com/`获取Cookie，请求API时再带上来在一定程度上解决获取单页视频时受到的限制
