### ISSUE TITLE
增加B站 up主的最近点赞的视频推荐列表feed

### ISSUE THREAD

**Issue by Whichbfj28** [DIYgod/RSSHub#10520]
### 这是一个什么样的功能？

我看了rsshub的B站很多都可以变为feed。唯独缺少点赞视频的列表

### 这个功能可以解决什么问题？

增加B站 up主的最近点赞的视频推荐列表feed

### 这不是重复的功能请求

- [ ] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Pleasa use the correct form for new route proposal
