### ISSUE TITLE
Macfilos

### ISSUE THREAD

**Issue by whereiswhere** [DIYgod/RSSHub#10541]
### Category

Uncategorized

### Website URL

https://www.macfilos.com

### Website description

Macfilos is an eclectic mix of news and views on photography, technology, productivity and writing. We cover subjects that interest us and, we hope, will inspire you. 

### What content should be included?

Full-text article of new blog post

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by axojhf** [comment]
The source site already provides the rss feed
[https://www.macfilos.com/feed/](https://www.macfilos.com/feed/)
