### ISSUE TITLE
Instagram使用账号密码登录，失败几率高，账号异常几率高，能换成网页ck登录么？

### ISSUE THREAD

**Issue by xssviggo** [DIYgod/RSSHub#10558]
### 这是一个什么样的功能？

提高使用Instagram路由的体验。

### 这个功能可以解决什么问题？

解决instagram路由频繁错误，账号登录异常的问题。

### 额外描述

![image](https://user-images.githubusercontent.com/61963810/185792279-ef3f2d2e-109c-418f-a4ce-c472c06f824c.png)
![image](https://user-images.githubusercontent.com/61963810/185792299-f1c6ec47-31aa-4ab7-8fd0-0fe26279e434.png)

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by typenoob** [comment]
现在登录ig，会出现风险提示，即使确认本人还是无法登录
![image](https://user-images.githubusercontent.com/61347081/204005898-39baf29e-bc42-4e4a-a95d-e34b9347a621.png)
![image](https://user-images.githubusercontent.com/61347081/204005916-fdc9e144-afcf-4cef-9891-b9823bc8c2e2.png)

**Comment by xssviggo** [comment]
我已经弃用了
