### ISSUE TITLE
telegram频道无法抓取信息（rtnews和SputnikInt）

### ISSUE THREAD

**Issue by Sh1n1ma** [DIYgod/RSSHub#10561]
### 路由地址

```routes
/telegram/channel/:username/:routeParams?
```

### 完整路由地址

```fullroutes
/telegram/channel/rtnews
/telegram/channel/SputnikInt
```

### 相关文档

https://docs.rsshub.app/social-media.html#telegram

### 预期是什么？

正常工作

### 实际发生了什么？

报错无法获取信息，tg频道预览界面可以正常显示。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
错误信息1（rtnews频道）：
Route requested: /channel/rtnews
Error message: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/rtnews
Helpful Information to provide when opening issue:
Path: /channel/rtnews
Node version: v16.17.0
Git Hash: f78ad03


错误信息2（SputnikInt频道）：
Error message: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/SputnikInt
Helpful Information to provide when opening issue:
Path: /channel/SputnikInt
Node version: v16.17.0
Git Hash: f78ad03
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/telegram/channel/rtnews
/telegram/channel/SputnikInt
```

**Comment by TonyRL** [comment]
https://t.me/s/rtnews
https://t.me/s/SputnikInt

Previews are blocked

**Comment by Sh1n1ma** [comment]
> Previews are blocked

It looks like this page can be accessed
![image](https://user-images.githubusercontent.com/68672629/185819391-572a8b8b-63a4-4db1-9c08-d08e5f804dd7.png)

**Comment by TonyRL** [comment]
Previews are not available for machines in Singapore where demo instances are hosted. If you can see the previews, you can [host your own RSSHub instance](https://docs.rsshub.app/install/).

**Comment by Sh1n1ma** [comment]
> Previews are not available for machines in Singapore where demo instances are hosted. If you can see the previews, you can [host your own RSSHub instance](https://docs.rsshub.app/install/).

ok,thank u
