### ISSUE TITLE
"科学期刊 - Science 系列 - Science"挂了

### ISSUE THREAD

**Issue by ImVictorCheng** [DIYgod/RSSHub#10562]
### 路由地址

```routes
/sciencemag/current/:journal
```

### 完整路由地址

```fullroutes
/sciencemag/current/science
```

### 相关文档

https://rsshub.app/sciencemag/current/science

### 预期是什么？

正常抓取数据

### 实际发生了什么？

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/20416460/185830600-aa2bfe2b-a2ac-4265-a368-65d8baa36ca2.png">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /sciencemag/current/science
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /sciencemag/current/science
Node version: v16.17.0
Git Hash: f78ad03
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
science似乎在约1年半前改了链接，可能这是一个原因，另，选择器好像也有一点修改，靠我的码力有点搞不定

**Comment by huangwb8** [comment]
Science官网有各种RSS，不需要自己搞了吧？比如这个：https://www.science.org/action/showFeed?type=axatoc&feed=rss&jc=science

**Comment by huangwb8** [comment]
全部官方可用的RSS都在这里：https://www.science.org/content/page/email-alerts-and-rss-feeds

**Comment by lychichem** [comment]
> Science官网有各种RSS，不需要自己搞了吧？比如这个：https://www.science.org/action/showFeed?type=axatoc&feed=rss&jc=science

只有标题和作者，没有任何摘要和toc信息

**Comment by huangwb8** [comment]
> 

大佬加油！好像Cell也没有，希望可以搞出来！Nature目前是有的
