### ISSUE TITLE
🔴 虎嗅网｜首页资讯，添加过滤「视频资讯」的功能

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#10578]
### 这是一个什么样的功能？

- 虎嗅网｜资讯：https://www.huxiu.com/article/

- RSSHub 示例：https://rsshub.app/huxiu/article

- RSSHub 路由地址：https://docs.rsshub.app/new-media.html#hu-xiu-shou-ye-zi-xun

- 路由：`/huxiu/article`

🔴 希望添加用来筛选的参数，可以选择「只获取文章」、「只获取视频」、「全部获取」

![SCR-20220823-k41](https://user-images.githubusercontent.com/106761803/186087197-bf2c96a6-c9ff-45f4-8d38-40590ca1ad20.jpeg)

### 这个功能可以解决什么问题？

- 虎嗅网的视频资讯过于烦人，而且质量低下

- 只想阅读文章，但是点标题进去后发现只是寥寥数字的视频简介，有被欺骗的感觉

- 视频资讯降低了信噪比，浪费了用户时间，影响到正常的用户体验

![SCR-20220823-kb6](https://user-images.githubusercontent.com/106761803/186088442-4732bdc9-4c33-442e-8514-38e570040b89.jpeg)

![SCR-20220823-kb7](https://user-images.githubusercontent.com/106761803/186088444-c12fa935-cdfd-409b-a97f-117e87eb3b46.jpeg)

![SCR-20220823-kb0](https://user-images.githubusercontent.com/106761803/186088426-90c6c156-9f19-4915-a34e-e08a4330ebcb.jpeg)

![SCR-20220823-kb4](https://user-images.githubusercontent.com/106761803/186088437-e4decf3a-54d5-440d-af40-132fca3d062d.jpeg)

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by lblbk** [comment]
大佬能不能顺便做一下 虎嗅的简报...

**Comment by lblbk** [comment]
大佬 能不能做下这个简报 麻烦了...  https://www.huxiu.com/briefColumn/

**Comment by TonyRL** [comment]
https://docs.rsshub.app/parameter#filtering

/test
```routes
/huxiu/article?filter_description=video
```

**Comment by TonyRL** [comment]
/test
```routes
/huxiu/article?filter_description=video
```

**Comment by TonyRL** [comment]
https://docs.rsshub.app/parameter#filtering
