### ISSUE TITLE
アニメ新番組(/bangumi/online) {pubDate} 視頻上架時間

### ISSUE THREAD

**Issue by TermSelf** [DIYgod/RSSHub#10581]
### 这是一个什么样的功能？

{pubDate} 視頻的上架時間

### 这个功能可以解决什么问题？

可以方便知道Feed是什麼時候發布

### 额外描述

非常感謝 @devinmugen 製作了初版 /bangumi/online
另外抱歉之前忘記順便提出這功能

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TermSelf** [comment]
It sounds like the implementation was a bit of a hassle, but it's okay without it, thanks for your answer.

**Comment by devinmugen** [comment]
This feature has been added.
