### ISSUE TITLE
The media list path on Twitter is incorrect, and RSS cannot be generated

### ISSUE THREAD

**Issue by zhaungzhan** [DIYgod/RSSHub#10580]
### Routes

```routes
/twitter/media/:id/:routeParams?
```

### Full routes

```fullroutes
https://rsshub.app/twitter/media/Sexynvwang0
```

### Related documentation

https://docs.rsshub.app/social-media.html#twitter

### What is expected?

I hope it can be solved as soon as possible. I really need it

### What is actually happening?

Cannot subscribe

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
NO
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/twitter/media/DIYgod
```

**Comment by zhaungzhan** [comment]
你的邮件我已经收到了，我会尽快查看的。

**Comment by TonyRL** [comment]
`/twitter/media/:id/:routeParams?` works without any issues. Note that age-restricted adult content requires logging in.

**Comment by zhaungzhan** [comment]
你的邮件我已经收到了，我会尽快查看的。
