### ISSUE TITLE
nga获取帖子功能出错

### ISSUE THREAD

**Issue by axojhf** [DIYgod/RSSHub#10585]
### 路由地址

```routes
/nga/post/:tid/:authorId?
```

### 完整路由地址

```fullroutes
/nga/post/:tid/:authorId?
```

### 相关文档

https://docs.rsshub.app/bbs.html#nga-tie-zi

### 预期是什么？

正常获取RSS

### 实际发生了什么？

Route requested: /post/30710672
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /post/30710672
Node version: v16.17.0
Git Hash: 9ecf42a

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /post/30710672
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /post/30710672
Node version: v16.17.0
Git Hash: 9ecf42a
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by syrinka** [comment]
正在修正在修，十分抱歉 :confounded:

**Comment by syrinka** [comment]
ok 了
