### ISSUE TITLE
telegram RSS has not worked since yesterday!

### ISSUE THREAD

**Issue by nekooee** [DIYgod/RSSHub#1059]
Hi,
telegram RSS has not worked since yesterday! Your example does not even work as well. look:
https://rsshub.app/telegram/channel/awesomeDIYgod

```
<rss version="2.0">
<channel>
<title>
<![CDATA[ undefined - Telegram 频道 ]]>
</title>
<link>https://t.me/awesomeDIYgod</link>
<description>
<![CDATA[
undefined - Telegram 频道 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)
]]>
</description>
<generator>RSSHub</generator>
<webMaster>i@diygod.me</webMaster>
<language>zh-cn</language>
<lastBuildDate>Sat, 03 Nov 2018 09:20:07 GMT</lastBuildDate>
<ttl>600</ttl>
</channel>
</rss>
```

**Comment by HenryQW** [comment]
1. Demo doesn't guarantee 100% availability
1. I believe you need a token and some [extra configurations](https://docs.rsshub.app/en/#telegram)
1. Please use [issues template](https://github.com/DIYgod/RSSHub/issues/new?template=bug_report_en.md)

**Comment by nekooee** [comment]
Hi
I've done the settings. In the settings of the telegram, there is no token according to the documentation of your site. And I did not see the Token Telegram settings.

for Telegram only need add bot in channel and set it administrator. 
On the first day worked without problems. But now it does not work. Like your own example, it worked first. But now it does not work.
I think there was a problem in your script. Detects the channel name but can not read the messages.
