### ISSUE TITLE
端传媒抓取失败, Response code 401 (UNAUTHORIZED)

### ISSUE THREAD

**Issue by reeceyng** [DIYgod/RSSHub#10595]
### 路由地址

```routes
/initium/:type?/:language?
```

### 完整路由地址

```fullroutes
/initium/latest/zh-hans
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#duan-chuan-mei https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

### 预期是什么？

成功抓取

### 实际发生了什么？

从8月20日开始端传媒抓取失败，之前一直通过 INITIUM_USERNAME 和 INITIUM_PASSWORD 的方式进行认证，刚才试了下 INITIUM_BEARER_TOKEN 也是一样的错误

```
Route requested: /initium/latest/zh-hans

Error message: Response code 401 (UNAUTHORIZED): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue:
Path: /initium/latest/zh-hans
Node version: v16.17.0
Git Hash: 3c2731d
```

### 部署

自建

### 部署相关信息

 OS:linux, node:v16.17.0, docker: 20.10.17

### 额外信息

```shell
docker日志


error: Error in /initium/latest: Response code 401 (UNAUTHORIZED): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/initium/latest/zh-hans
```

**Comment by reeceyng** [comment]
Success now, looks like a temporary error.

**Comment by lucky13820** [comment]
我也遇到这个问题了，想问你最后怎么解决的？
