### ISSUE TITLE
Instagram rss not working since `diygod/rsshub:2022-08-17`

### ISSUE THREAD

**Issue by decentral1se** [DIYgod/RSSHub#10608]
### Routes

```routes
/instagram/user/
```

### Full routes

```fullroutes
/api/v1/users/search/?timezone_offset=28800&q=<IG_USERNAME>&count=30
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#instagram

### What is expected?

Instagram user page generates an rss feed.

### What is actually happening?

> 
> Route requested: /instagram/user/<IG_USERNAME>
> 
> Error message: GET /api/v1/users/search/?timezone_offset=28800&q=<IG_USERNAME>&count=30 - 403 Forbidden; login_required
> 
> Helpful Information to provide when opening issue:
> Path: /instagram/user/<IG_USERNAME>
> Node version: v16.17.0
> Git Hash: 1902fba
>         
> 
> 如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
> If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

diygod/rsshub:2022-08-17

### Additional info

It was working, now it isn't. I have the password loaded and it was authenticating before it stopped working for unknown reasons. I have a Tor socks proxy configured.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by decentral1se** [comment]
Whhhhhhhy do they keep getting closed? :scream:

**Comment by TonyRL** [comment]
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11386903/186741128-8c26df12-0ca0-4492-8196-b1a3aa6f2aec.png)
</details>

**Comment by decentral1se** [comment]
@TonyRL are you a robot? What does this mean? Are there any humans here?

**Comment by TonyRL** [comment]
That's a screenshot of the Instagram RSS generated right after you opening this issue.
This means the route is working fine.
