### ISSUE TITLE
DOMP4影视

### ISSUE THREAD

**Issue by zhaohui0923** [DIYgod/RSSHub#10601]
### 路由地址

```routes
/domp4/detail/:id
```

### 完整路由地址

```fullroutes
/domp4/detail/1sGmWdSSSSSd
```

### 相关文档

https://docs.rsshub.app/multimedia.html#domp4-ying-shi-ju-ji-ding-yue

### 预期是什么？

每个item的guid不同

### 实际发生了什么？

每个item的guid相同，导致多个item被rss阅读器识别成一条

### 部署

自建

### 部署相关信息

Docker arm64 LATEST 0825

### 额外信息

```shell
自身无报错，但是由于guid相同导致rss阅读器无法正确识别多个item
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by savokiss** [comment]
有具体的 case 么？
这个 detail 是用来订阅剧集更新的，我用 inoreader 是可以正常识别的~

**Comment by savokiss** [comment]
明白了~这块儿还真没太注意，我最近看下把每个 item 搞成唯一的~
