### ISSUE TITLE
增加虎嗅简报的路由

### ISSUE THREAD

**Issue by lblbk** [DIYgod/RSSHub#10604]
### 这是一个什么样的功能？

虎嗅简报单独放到了一个栏目里面，包括早报和晚报及其他栏目，能不能为这个栏目增加一个路由...
https://www.huxiu.com/briefColumn/

### 这个功能可以解决什么问题？

订阅虎嗅早报和晚报

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please use the correct form for a new route proposal
