### ISSUE TITLE
希望能有好友给一下抓取喜马拉雅rss的方法

### ISSUE THREAD

**Issue by iwoodme** [DIYgod/RSSHub#1061]
我想用泛用行播客客户端订阅喜马拉雅上的资源，尤其是那些需要付费的，我已经购买了，但是我不会抓取。

**Comment by HenryQW** [comment]
这个应该可以 getpodcast.xyz

**Comment by iwoodme** [comment]
谢谢，这个我找到啦，而且任大还制作了一个捷径，可以直接订阅喜马拉雅包括ytb等上面的内容

发自我的 iPhone
