### ISSUE TITLE
请问pubDate怎么填写

### ISSUE THREAD

**Issue by monnerHenster** [DIYgod/RSSHub#1062]
我顺利的抓取了 title、link，但是这个pubDate没看懂，直接复制路由表的其他js的语句的话，只有第一个有日期显示。 基他全是invalidDate

**还有请问下，rss阅读器是判断guid还是pudate来看看是不是新的**

[我是拿简书改的]

```
const axios = require('../../utils/axios');
const cheerio = require('cheerio');
module.exports = async (ctx) => {
    const response = await axios({
        method: 'get',
        url: 'https://gnn.gamer.com.tw/',
        headers: {
            Referer: 'hhttps://gnn.gamer.com.tw/',
        },
    });
    const data = response.data;
    const $ = cheerio.load(data);
    const list = $('.GN-lbox2 .GN-lbox2B');
    ctx.state.data = {
        title: 'GNN 新聞網 - 巴哈姆特 edited by monner',
        link: 'https://gnn.gamer.com.tw/',
        description: '巴 哈 姆 特 電 玩 資 訊 站 https://www.gamer.com.tw',
        item:
            list &&
            list
                .map((index, item) => {
                    // item2 = $(item).find('.GN-lbox2D a');

                    item = $(item);
                    return {
                        title: item.find('.GN-lbox2D').text(),
                        description: item.find('.GN-lbox2C').text(),
                        pubDate: new Date(
                                   $(item)
                                       .find('font')
                                       .text()
                               ).toUTCString(),
                        // pubDate: 'date',
                        link: item.find('.GN-lbox2D a').attr('href'),
                        // link: 'link',
                        // link: item2.find('a').text(),
                        // link: 'link',
                    };
                })
                .get(),
    };
};
```

这是我的地址：http://jp2.iioo.pub:1200/jianshu/home

**Comment by HenryQW** [comment]
1. 抓取日期值
1. 传入js `Date`
1. 转为 UTC 或 ISO 格式

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by monnerHenster** [comment]
> 1. 抓取日期值
> 2. 传入js `Date`
> 3. 转为 UTC 或 ISO 格式
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

请问是抓页面的每一个文章日期值吗，文章列表没有日期的时候是怎么实现抓取的呢，我看了下简书和电影天堂的js，他们的item.find()的日期的内容也没能在网页里可以搜索出来。

**Comment by HenryQW** [comment]
每个网站日期字段显示的地方以及格式都不一样，自行判断。

https://gnn.gamer.com.tw/2/170552.html

```js
$('#BH-master > div.BH-lbox.GN-lbox3 > div.GN-lbox3B > span').html().split('）')[1].trim();
```

**Comment by monnerHenster** [comment]
> 每个网站日期字段显示的地方以及格式都不一样，自行判断。
> 
> https://gnn.gamer.com.tw/2/170552.html
> 
> ```js
> $('#BH-master > div.BH-lbox.GN-lbox3 > div.GN-lbox3B > span').html().split('）')[1].trim();
> ```

这个日期不填写或者抓取错误或者只填写个固定时间 会影响rsss更新吗

官方路由的简书的pubDate抓取就是错误的。

**Comment by xyqfer** [comment]
> 还有请问下，rss阅读器是判断guid还是pudate来看看是不是新的

应该是 `guid` 吧，我看[文档](https://docs.rsshub.app/joinus/#%E7%94%9F%E6%88%90-rss)是这么写的：

> guid: '', // 文章唯一标示, 必须唯一, 可选, 默认为文章链接

**Comment by HenryQW** [comment]
> > 每个网站日期字段显示的地方以及格式都不一样，自行判断。
> > [gnn.gamer.com.tw/2/170552.html](https://gnn.gamer.com.tw/2/170552.html)
> > ```js
> > $('#BH-master > div.BH-lbox.GN-lbox3 > div.GN-lbox3B > span').html().split('）')[1].trim();
> > ```
> 
> 这个日期不填写或者抓取错误或者只填写个固定时间 会影响rsss更新吗
> 
> 官方路由的简书的pubDate抓取就是错误的。

不影响


> 还有请问下，rss阅读器是判断guid还是pudate来看看是不是新的

取决于阅读器，大部分阅读器好像不支持 pubDate 来判断同一 guid 内容是否有更新。
