### ISSUE TITLE
哈尔滨工业大学（深圳）通知文章路由失效

### ISSUE THREAD

**Issue by TankNee** [DIYgod/RSSHub#10620]
### 路由地址

```routes
/hitsz/article/:category?
```

### 完整路由地址

```fullroutes
/hitsz/article/id-74
```

### 相关文档

https://docs.rsshub.app/university.html#ha-er-bin-gong-ye-da-xue-shen-zhen

### 预期是什么？

返回通知内容

### 实际发生了什么？

![Uploading image.png…]()

### 部署

自建

### 部署相关信息

686f7a9 v16.15.0

### 额外信息

```shell
Path: /hitsz/article/id-74
Node version: v16.15.0
Git Hash: 686f7a9
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by linbuxiao** [comment]
通知文章板块目前需要鉴权访问
