### ISSUE TITLE
Youtube订阅列表过了一小时会失效

### ISSUE THREAD

**Issue by sunnytower** [DIYgod/RSSHub#10630]
### 路由地址

```routes
/youtube/subscriptions
```

### 完整路由地址

```fullroutes
/youtube/subscriptions/:embed?
```

### 相关文档

https://docs.rsshub.app/social-media.html#youtube-ding-yue-lie-biao

### 预期是什么？

返回订阅内容

### 实际发生了什么？

![SCR-20220827-gzq](https://user-images.githubusercontent.com/77821870/187013980-f49fd542-5d54-457e-b2f1-5bd1439fc4b0.png)

通过文档提供的方法在playground获取的refresh token即使在勾选了Use your own OAuth credentials，一个小时后就失效了，不清楚是什么原因。看起来是access token没有刷新？

### 部署

自建

### 额外信息

```shell
Route requested: /subscriptions
Error message: Cannot read properties of undefined (reading 'data')
Helpful Information to provide when opening issue:
Path: /subscriptions
Node version: v16.17.0
Git Hash: 17fa8f5
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by uJZk** [comment]
![屏幕截图 2022-10-09 202745](https://user-images.githubusercontent.com/34388941/194786421-e4e85997-44a5-4c27-bea5-7aadc3b183c4.png)
同样的问题。经测试打开缓存后，重启 RSSHub 后，在第一次访问以及缓存内访问 /youtube/subscriptions 正常。一旦缓存过期，再次访问即出现以上问题。

**Comment by Ton-yi** [comment]
一样情况
我尝试使用重新生成的 refresh token 后返回 unauthorized_client
使用原 refresh token 仍是  Cannot read properties of undefined (reading 'data')![image](https://user-images.githubusercontent.com/73752817/197318031-352a4e7f-02c6-4721-9b11-446c79e830f4.png)

我的服务器目前通过socks5代理连接，是否与此有关

**Comment by ZefanHu** [comment]
请问怎么解决的呀？
