### ISSUE TITLE
Vercel自动部署失败

### ISSUE THREAD

**Issue by Misakaou** [DIYgod/RSSHub#10657]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/en/install/#docker-compose-deployment-update

### 预期是什么？

完全按照默认，部署至vercel，访问网址出现RSSHub的欢迎页

### 实际发生了什么？

<img width="588" alt="Screen Shot 2022-08-30 at 17 39 48" src="https://user-images.githubusercontent.com/40706446/187404303-27c29a9e-469f-420b-8a9b-fb8e123d492a.png">

如图所示，vercel认为函数崩溃了。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Vercel

### 额外信息

```shell
[GET] /
17:41:18:49
2022-08-30T09:41:19.404Z	undefined	ERROR	Cannot find module 'got'
Require stack:
- /var/task/lib/utils/got.js
- /var/task/lib/middleware/parameter.js
- /var/task/lib/app.js
- /var/task/api/vercel.js
2022-08-30T09:41:19.405Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?
RequestId: 92eda7c1-5ea9-49c0-8b6b-970df2bb91e7 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
It's caused by recent 0.22.0 update of `@vercel/nft` as I believe it's used by Vercel's internal builder.
For more details, please refer to https://github.com/vercel/nft/issues/307.

**Comment by Misakaou** [comment]
> It's caused by recent 0.22.0 update of `@vercel/nft` as I believe it's used by Vercel's internal builder.
> For more details, please refer to [vercel/nft#307](https://github.com/vercel/nft/issues/307).

Okay, thank you. I'll wait for the vercel update.

**Comment by evnydd0sf** [comment]
目前可以在 vercel 里面添加环境参数来临时避免这个问题。

VERCEL_CLI_VERSION = vercel@28.1.4
