### ISSUE TITLE
A岛匿名版改名为X岛匿名版，域名修改导致无法抓取

### ISSUE THREAD

**Issue by SekiBetu** [DIYgod/RSSHub#10677]
### 路由地址

```routes
/adnmb/:pid
```

### 完整路由地址

```fullroutes
https://rsshub.app/adnmb/20
```

### 相关文档

https://docs.rsshub.app/bbs.html#a-dao-ni-ming-ban

### 预期是什么？

能够抓取内容

### 实际发生了什么？

因为地址变动无法抓取

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
A岛现在已经更换了域名为 nmbxd.com 并改名X岛，希望修改下
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SekiBetu** [comment]
https://www.nmbxd1.com/t/50000002
@zcx1218029121

**Comment by SekiBetu** [comment]
https://github.com/DIYgod/RSSHub/compare/master...SekiBetu:RSSHub:nmbxd
我自己尝试着改了下，但是发现
```
Error message: Cannot read properties of undefined (reading 'forEach')
```
![image](https://user-images.githubusercontent.com/38283893/188034737-43b436f1-acb3-4ae5-87ab-70466dd8919a.png)

**Comment by miles170** [comment]
我看了一下发现其后端 API 应有做更动
现在应只能透过 `cherrio` 从网页抓取资料
