### ISSUE TITLE
Pixiv排行榜错误，pixiv not login

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#1068]
### 路由地址
https://rsshub.app/pixiv/ranking/week

### 预期是什么？
正常获取订阅内容

### 实际发生了什么？
```
RSSHub 发生了一些意外:
pixiv not login
```

**Comment by SukkaW** [comment]
@Andiedie Pixiv Auth Cookie 过期导致的。推荐架设自己的 RSSHub 实例并使用自己账户的 Cookie。

**Comment by DIYgod** [comment]
@SukkaW 是因为部分 heroku 的 IP 被 pixiv 封了，每次重启完都要看脸

**Comment by SukkaW** [comment]
@DIYgod 应该只有日本 IP 被封的概率小一些

**Comment by Andiedie** [comment]
现已正常
