### ISSUE TITLE
腾讯企鹅号报错：The argument 'size' is invalid. Received NaN

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#10715]
### Routes

```routes
/tencent/news/author/:mid
```

### Full routes

```fullroutes
/tencent/news/author/:mid
```

### Related documentation

https://docs.rsshub.app/new-media.html#teng-xun-gu-yu

### What is expected?

无法正常获取rss

### What is actually happening?

无法正常获取rss

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Route requested: /tencent/news/author/5933889

Error message: The argument 'size' is invalid. Received NaN

Helpful Information to provide when opening issue:
Path: /tencent/news/author/5933889
Node version: v16.17.0
Git Hash: 43baaf9
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by linbuxiao** [comment]
@linbuxiao
