### ISSUE TITLE
本地部署时是否可以使用代理

### ISSUE THREAD

**Issue by hosven** [DIYgod/RSSHub#1073]
### 这是一个什么样的功能？
在本地部署时，无法获取外网内容，比如instagram。
是否可以使用本地的sock5代理。

### 这个功能可以解决什么问题？
在本地部署时，无法获取外网内容，比如instagram。
是否可以使用本地的sock5代理。

**Comment by sgqy** [comment]
环境变量可以用http代理，然而开https网站它就不行了
试着用tunnel也没配出来 :thinking: 
~~[这个](https://github.com/axios/axios/issues/925)和[这个](https://janmolak.com/8b17a6f31f9d)都是假的~~
~~axios和axios-https-proxy-fix两个目录也完全相同~~

**Comment by xyqfer** [comment]
我用 axios-https-proxy-fix 可以。。。

**Comment by DerekTso** [comment]
@sgqy I have tried those axios proxy methods, none of them works. Then I replace those axios request with nodejs http package, it works.

**Comment by HenryQW** [comment]
> 环境变量可以用http代理，然而开https网站它就不行了
> 试着用tunnel也没配出来 🤔
> [这个](https://github.com/axios/axios/issues/925)和[这个](https://janmolak.com/8b17a6f31f9d)都是假的
> axios和axios-https-proxy-fix两个目录也完全相同


亲测，可以用公司的 squid http 代理。socks5 就不清楚了

https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d

```js
const agent = tunnel.httpsOverHttp({
    proxy: {
        host: 'proxy.mycorp.com',
        port: 8000,
    },
});
const axiosClient: AxiosInstance = axios.create({
    baseURL: 'https://some.api.com',
    httpsAgent: agent,
});
```

**Comment by DIYgod** [comment]
axios@next + tunnel 本地 http 代理可以

但用的一个在线代理会报 `Error: self signed certificate in certificate chain`

**Comment by HenryQW** [comment]
或者增量路由弃用 axios

**Comment by librix** [comment]
可以给‘\axios\lib\adapters\http.js’添加https://www.npmjs.com/package/socks-proxy-agent 的支持吗？

**Comment by dzcpy** [comment]
socket5 应该不能用，如果需要支持socks5的话就用superagent+superagent-proxy吧

**Comment by CoderTonyChan** [comment]
> > 环境变量可以用http代理，然而开https网站它就不行了
> > 试着用tunnel也没配出来 🤔
> > [这个](https://github.com/axios/axios/issues/925)和[这个](https://janmolak.com/8b17a6f31f9d)都是假的
> > axios和axios-https-proxy-fix两个目录也完全相同
> 
> 亲测，可以用公司的 squid http 代理。socks5 就不清楚了
> 
> https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d
> 
> ```js
> const agent = tunnel.httpsOverHttp({
>     proxy: {
>         host: 'proxy.mycorp.com',
>         port: 8000,
>     },
> });
> const axiosClient = axios.create({
>     baseURL: 'https://some.api.com',
>     httpsAgent: agent,
> });
> ```

试了一圈只有这种方法可以
本地开发要加这些 有方便的方法么?

```
const { httpsOverHttp } = require('tunnel');

const agent = httpsOverHttp({
    proxy: {
        host: '127.0.0.1',
        port: 1087,
    },
});
const axiosClient = axios.create({
    baseURL: 'https://some.api.com',
    httpsAgent: agent,
});
```

**Comment by dzcpy** [comment]
https://github.com/TooTallNate/node-socks-proxy-agent

**Comment by sgqy** [comment]
前两天用`telnet`的时候在[爆栈](https://unix.stackexchange.com/a/36643)上搜到个野路子：用`proxychains`。这个应该能先解决一下燃眉之急。:thinking:

**Comment by dzcpy** [comment]
@sgqy 看下我上面发的那个链接 https://github.com/DIYgod/RSSHub/issues/1073#issuecomment-464428655 用`socks-proxy-agent`可以给`axios`挂上`socks5`代理

**Comment by imlonghao** [comment]
@dzcpy 已经加上了这个，部署文档设置三个参数就可以使用了。

**Comment by DIYgod** [comment]
Done. df026d71987c46add85b2fb15d13af8c40129c7a

关键代码： 
```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```
