### ISSUE TITLE
Bluestacks 5 Navigation failed because browser has disconnected!

### ISSUE THREAD

**Issue by RivenNero** [DIYgod/RSSHub#10733]
### 路由地址

```routes
/bluestacks/release/5
```

### 完整路由地址

```fullroutes
/bluestacks/release/5.atom
```

### 相关文档

https://docs.rsshub.app/en/program-update.html#bluestacks

### 预期是什么？

正常抓取信息

### 实际发生了什么？

无法正常抓取信息，显示 Navigation failed because browser has disconnected! 错误

![image](https://user-images.githubusercontent.com/35187885/188811594-c51945e1-b057-417a-a342-082bfb1110b2.png)

### 部署

自建

### 部署相关信息

OS: Debian 11.4, Node: v16.17.0, Docker: v20.10.17

### 额外信息

```shell
RSSHub
Looks like something went wrong
Route requested: /release/5
Error message: Navigation failed because browser has disconnected!
Helpful Information to provide when opening issue:
Path: /release/5
Node version: v16.17.0
Git Hash: e15406f
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by RivenNero** [comment]
已修改路由地址

**Comment by RivenNero** [comment]
已修改路由地址

**Comment by TonyRL** [comment]
/test
```routes
/bluestacks/release/5
```

**Comment by TonyRL** [comment]
Route is working fine in a self-hosted environment. This route makes use of puppeteer, you need to make sure it works fine.
