### ISSUE TITLE
法庭線 The Witness

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#10741]
### 类型

新媒体

### 网站地址

https://thewitnesshk.com/

### 网站描述

> 由一群前法庭記者創立。在瞬息萬變的時代，我們身在香港和法庭現場，見證記錄。 ([twitter](https://mobile.twitter.com/thewitnesshk))

> 香港正經歷急速變革，與人權、自由等公眾利益息息相關的案件，每天在各級法院提堂、審訊和判決。不過隨着數間媒體停運，數十名法庭記者流失，法庭新聞報道減少，部分案件缺乏關注，甚或消失於公眾視線。
> 
> 有見及此，一群前法庭記者創立名為《法庭線 The Witness》的新媒體，盼繼續在法庭現場記錄及報道，讓大眾及時和更容易了解法庭審訊和裁決，以及其對自身權利的影響，從而拉近公眾與法庭的距離。
> 
> 在瞬息萬變的時代，《法庭線 The Witness》記者身在香港和法庭現場，見證記錄。
> 宗旨
> 《法庭線 The Witness》秉持獨立、準確和持平的新聞原則，透過在香港和法庭實地採訪，保障公眾知情權，維護公眾利益。
> 
> 營運模式
> 《法庭線 The Witness》所有訂閱收入用於媒體營運及發展，包括支付編採團隊薪金、辦公室租金，以及其他所需開支。本媒體依賴讀者訂閱維持營運，報道全部免費向公眾開放。 ([關於《法庭線》](https://thewitnesshk.com/about-us/))

### 需要生成什么内容？

~

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://thewitnesshk.com/feed

[RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar) Browser extension that simplifies finding and subscribing RSS and RSSHub
