### ISSUE TITLE
纽约时报 - 全文输出需求

### ISSUE THREAD

**Issue by Wei-Xia** [DIYgod/RSSHub#1076]
### 源站地址
https://cn.nytimes.com/rss/

### 需要生成什么内容？
需要全文输出每条的新闻的全部内容

### 额外描述
我通过阅读「参与我们」的文档自行完成编程部分，但今天分析了下这个 Feed 的内容，觉得好像做不到全文输出。麻烦帮忙看下，如果觉得可以全文输出，希望提供个思路，我来完成代码的实际操作部分。

**Comment by HenryQW** [comment]
可以参考 BBC 路由 

https://github.com/DIYgod/RSSHub/blob/ff2257b4a53e33282be8e1fa9b7e6fb2a8c2494b/routes/bbc/index.js#L38-L61

1. **遍历**通过 RSS 获取的文章 `url`, `title, `author`, `pubDate`
1. 对**每个** `url` 发起 axios 请求，获取 `description`：
	1. 获取全文
	1. 处理图片、视频
	1. 移除非必要元素
1. **合并** `description`, `title`, `author`, `pubDate` 为一篇文章
