### ISSUE TITLE
抖音有些用户RSS订阅不到，可能与新老账号有关

### ISSUE THREAD

**Issue by DengSchoo** [DIYgod/RSSHub#10764]
### Routes

```routes
/douyin/user
```

### Full routes

```fullroutes
/douyin/user/MS4wLjABAAAAIjWBhXv-MoX96zVlQt9BtRriXZ3aInZWtFAoBzu-A8w
```

### Related documentation

https://docs.rsshub.app/social-media.html#dou-yin

### What is expected?

应该所有用户都可以订阅到RSS

### What is actually happening?

得到显示以下两类错误：
- Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
- Error message: Cannot convert undefined or null to object

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Node version: v16.17.0 Git Hash: 7ef81ae

### Additional info

```shell
1、Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

2、Error message: Cannot convert undefined or null to object
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Returning <code>Error: this route is empty, please <b>check the original site</b></code> is expected behaviour since this user has no feed items
