### ISSUE TITLE
求内蒙古音乐之声《爱艺思音乐专线》RSS

### ISSUE THREAD

**Issue by dycfan** [DIYgod/RSSHub#10804]
### 类型

音视频

### 网站地址

http://www.nmtv.cn/folder292/folder663/folder664/folder675/folder808/

### 网站描述

内蒙古音乐之声《爱艺思音乐专线》是截至目前，国内唯一一个提供民族歌曲收听的电台栏目，非常有特色。希望有大神基于RSSHUB，提供内蒙古音乐之声《爱艺思音乐专线》的RSS路由，用于泛用型播客客户端订阅收听。谢谢。

补充：
胡乱抓包，接口如下：
https://mapi.m2oplus.nmtv.cn/api/v1/contents.php?&count=19&offset=0&column_id=808

### 需要生成什么内容？

RSS文档包含标题，对应的音频媒体文件链接。其他遵从RSSHUB规范。

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Closed in #11252
