### ISSUE TITLE
请求添加雪球热帖

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#10811]
### 类型

金融

### 网站地址

https://xueqiu.com/today

### 网站描述

最大的散户交流网

### 需要生成什么内容？

雪球热榜：https://xueqiu.com/today
![image](https://user-images.githubusercontent.com/69616271/190847979-16f98e8d-e069-45d3-8142-4c6061fc94f7.png)

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Please double check the docs.
