### ISSUE TITLE
国家药品监督管理局  路由失效

### ISSUE THREAD

**Issue by mrchenxxx** [DIYgod/RSSHub#10822]
### 路由地址

```routes
/gov/nmpa/:path+
```

### 完整路由地址

```fullroutes
/gov/nmpa/xxgk/ggtg
```

### 相关文档

https://docs.rsshub.app/government.html#guo-jia-yao-pin-jian-du-guan-li-ju

### 预期是什么？

能正常的订阅rss

### 实际发生了什么？

Route requested: /gov/nmpa/xxgk/ggtg
Error message: This path is currently fetching, please come back later!
Helpful Information to provide when opening issue:
Path: /gov/nmpa/xxgk/ggtg
Node version: v16.17.0
Git Hash: 1400df7

### 部署

自建

### 部署相关信息

Docker version 20.10.5, build 55c4c88

### 额外信息

```shell
Looks like something went wrong
Route requested: /gov/nmpa/xxgk/ggtg
Error message: This path is currently fetching, please come back later!
Helpful Information to provide when opening issue:
Path: /gov/nmpa/xxgk/ggtg
Node version: v16.17.0
Git Hash: 1400df7
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/gov/nmpa/xxgk/ggtg
```

**Comment by TonyRL** [comment]
Please wait for puppeteer request to be finished instead of keep refreshing
