### ISSUE TITLE
Bilibili 视频动态返回「undefined 的 bilibili 空间」

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#10824]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### 预期是什么？

返回 UP 的名字

### 实际发生了什么？

返回 undefined

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
None
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ruleroller** [comment]
https://docs.rsshub.app/social-media.html#bilibili-yong-hu-guan-zhu-dong-tai

https://docs.rsshub.app/social-media.html#bilibili-yong-hu-guan-zhu-shi-pin-dong-tai

https://docs.rsshub.app/social-media.html#bilibili-yong-hu-guan-zhu-zhuan-lan

以上我自建在用的这三个哔哩哔哩的路由：**用户关注动态、用户关注视频动态、用户关注专栏**，也都是如此情况。其它有uid的似乎都出了问题，但奇怪的是 **UP 主动态** 和**UP 主非默认收藏夹**  是可显示的，比如[文档例子](https://rsshub.app/bilibili/user/dynamic/2267573) ，可能未测全面。

我看了一下，或许是主站有变动， cache.js 里面获取name上，某个地方出现了问题，但我水平不够，不知道怎么改才正确。

cc @Qixingchen @TigerCubDen @LogicJake @woshiluo ，大佬们谁有空看看呀？

**Comment by woshiluo** [comment]
看了眼，服务器返回了非法访问。

但是直接通过 `curl` 发起请求都没有问题，这太奇怪了。

**Comment by Konano** [comment]
> 看了眼，服务器返回了非法访问。
> 
> 但是直接通过 `curl` 发起请求都没有问题，这太奇怪了。

和请求带的 UA 有关？

**Comment by raining1123** [comment]
> 试了下加了 Referer 在我这就正常了。

请问能否讲讲具体步骤？ @woshiluo
