### ISSUE TITLE
转发指定RSS，添加Access-Control-Allow-Origin头

### ISSUE THREAD

**Issue by tiaod** [DIYgod/RSSHub#1082]
### 这是一个什么样的功能？
新增一个路由，转发指定地址的RSS，添加http响应头：`Access-Control-Allow-Origin:*`
### 这个功能可以解决什么问题？
有些RSS不支持CORS，转发添加CORS头就可以得到支持，可以给网页客户端使用。

**Comment by DIYgod** [comment]
不属于 RSS 功能
