### ISSUE TITLE
联合早报图片问题

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#10830]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/zaobao/realtime/china
/zaobao/realtime/singapore
/zaobao/realtime/world
/zaobao/realtime/zfinance
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#lian-he-zao-bao

### 预期是什么？

与下图一样显示图片
![image](https://user-images.githubusercontent.com/69616271/190958309-be0c612b-2a09-4b60-b930-faa0362b2730.png)

### 实际发生了什么？

文章没有图片
![image](https://user-images.githubusercontent.com/69616271/190958467-e3287ea9-836f-4455-8c62-22c3aaee64ae.png)
![image](https://user-images.githubusercontent.com/69616271/190958502-21ecba68-8e02-41b0-b379-13758d149ebb.png)
而有些帖子又可以显示图片
![image](https://user-images.githubusercontent.com/69616271/190958527-5a90d80c-e4c7-48c5-a908-8bfa4f01f4c0.png)

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
可否提供具体的新闻页面链接？以及您使用的是靠近香港的服务器还是远离香港的服务器呢？

**Comment by sin572** [comment]
即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime

**Comment by sin572** [comment]
> 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime

**Comment by sin572** [comment]
> 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> 
> 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的

即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime

**Comment by lychichem** [comment]
> > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> 
> 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime

是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=https://static.zaobao.com${pathname}

**Comment by JaHuck** [comment]
> > > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> > 
> > 
> > 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime
> 
> 是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}](https://static.zaobao.com$%7Bpathname%7D)

用的Fluent Reader，订阅端加上后还是有一些不能显示图片，图片为即时-国际页面。
![image](https://user-images.githubusercontent.com/69616271/191251012-3ff377bc-2b92-463d-8d5d-712e36e1d04d.png)

**Comment by lychichem** [comment]
> > > > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > > > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> > > 
> > > 
> > > 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime
> > 
> > 是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}](https://static.zaobao.com$%7Bpathname%7D)
> 
> 用的Fluent Reader，订阅端加上后还是有一些不能显示图片，图片为即时-国际页面。
> ![image](https://user-images.githubusercontent.com/69616271/191251012-3ff377bc-2b92-463d-8d5d-712e36e1d04d.png)
> 

你把部署版本更新下（）

**Comment by JaHuck** [comment]
> > > > > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > > > > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> > > > 
> > > > 
> > > > 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime
> > > 
> > > 
> > > 是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}](https://static.zaobao.com$%7Bpathname%7D)
> > 
> > 
> > 用的Fluent Reader，订阅端加上后还是有一些不能显示图片，图片为即时-国际页面。
> > ![image](https://user-images.githubusercontent.com/69616271/191251012-3ff377bc-2b92-463d-8d5d-712e36e1d04d.png)
> 
> 你把部署版本更新下（）

![image](https://user-images.githubusercontent.com/69616271/191252882-668e58c0-949f-4700-9aae-4d61ef6bf259.png)
是最新的，
手机上有部分也不能显示
![174ab5bb52e4d73b6bb477d52e85384](https://user-images.githubusercontent.com/69616271/191253367-16f7472f-0c02-4ef4-8ac8-e4bedf9520f0.jpg)

**Comment by lychichem** [comment]
> > > > > > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > > > > > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> > > > > 
> > > > > 
> > > > > 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime
> > > > 
> > > > 
> > > > 是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}](https://static.zaobao.com$%7Bpathname%7D)
> > > 
> > > 
> > > 用的Fluent Reader，订阅端加上后还是有一些不能显示图片，图片为即时-国际页面。
> > > ![image](https://user-images.githubusercontent.com/69616271/191251012-3ff377bc-2b92-463d-8d5d-712e36e1d04d.png)
> > 
> > 
> > 你把部署版本更新下（）
> 
> ![image](https://user-images.githubusercontent.com/69616271/191252882-668e58c0-949f-4700-9aae-4d61ef6bf259.png) 是最新的， 手机上有部分也不能显示 ![174ab5bb52e4d73b6bb477d52e85384](https://user-images.githubusercontent.com/69616271/191253367-16f7472f-0c02-4ef4-8ac8-e4bedf9520f0.jpg)

你确定开了图像处理的参数（https://docs.rsshub.app/parameter.html#duo-mei-ti-chu-li）吗？我这边电脑tt-rss和手机的feedme都是正常的

**Comment by JaHuck** [comment]
> > > > > > > 可否提供具体的新闻页面链接？以及您使用靠近香港的服务器还是远离香港的服务器呢？
> > > > > > > 我想起来了，目前的控制规则有点bug，需要自己用文档里的图片处理规则把联合早报图片服务器域名改成static.zaobao.com/file什么的
> > > > > > 
> > > > > > 
> > > > > > 即时下4个页面都不能显示图片，服务器是新加坡的，具体访问https://www.zaobao.com.sg/realtime
> > > > > 
> > > > > 
> > > > > 是了，目前的路由图片重定向有点bug，如果你用的tt-rss或者inoreader之类的会有加载不出图的情况，需要手动开下图片处理参数，然后在订阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}](https://static.zaobao.com$%7Bpathname%7D)
> > > > 
> > > > 
> > > > 用的Fluent Reader，订阅端加上后还是有一些不能显示图片，图片为即时-国际页面。
> > > > ![image](https://user-images.githubusercontent.com/69616271/191251012-3ff377bc-2b92-463d-8d5d-712e36e1d04d.png)
> > > 
> > > 
> > > 你把部署版本更新下（）
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69616271/191252882-668e58c0-949f-4700-9aae-4d61ef6bf259.png) 是最新的， 手机上有部分也不能显示 ![174ab5bb52e4d73b6bb477d52e85384](https://user-images.githubusercontent.com/69616271/191253367-16f7472f-0c02-4ef4-8ac8-e4bedf9520f0.jpg)
> 
> 你确定开了图像处理的参数（https://docs.rsshub.app/parameter.html#duo-mei-ti-chu-li ）吗？我这边电脑tt-rss和手机的feedme都是正常的
![image](https://user-images.githubusercontent.com/69616271/191262536-071e0f83-6f23-44fb-bf1e-e781993ed4a4.png)
这个确实是开的，重新创建了还是不行

**Comment by JaHuck** [comment]
今天重新部署又可以看图片了
一开启图片处理功能 ：https://docs.rsshub.app/parameter.html#duo-mei-ti-chu-li
![image](https://user-images.githubusercontent.com/69616271/192076973-7b772311-fd0d-474e-ab86-f12c8c07ebf5.png)
二 阅源末尾加上?image_hotlink_template=[https://static.zaobao.com${pathname}]
