### ISSUE TITLE
Get Podcasts Shows from Spotify via RSS

### ISSUE THREAD

**Issue by VinyCola** [DIYgod/RSSHub#10846]
### What feature is it?

To pull-up new podcasts episodes from Spotify exclusives

Example:

https://open.spotify.com/show/3IM0lmZxpFAY7CwMuv9H4g

Could be:

https://rsshub.app/spotify/show/3IM0lmZxpFAY7CwMuv9H4g

### What problem does this feature solve?

Since many podcasters today are signing contracts with Spotify and the platform is currently not expected to create an RSS resource, this feature could help and those who uses Spotify as their main player could get shows directly from the RSS feed

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
Closing as it’s **indeed** a new RSS proposal.
