### ISSUE TITLE
新增Web3Caff RSS支持

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#10841]
### 类型

新媒体

### 网站地址

https://web3caff.com/

### 网站描述

Web3Caff 是一家致力於 Web3.0 領域研究的區塊鏈垂直媒體平台，在這裡你可以同我們一起以全球視野探索 Web3.0 生態的產業發展趨勢及新經濟動態。 Web3Caff 將報道最新且熱門的 Web3.0 項目動態、創業團隊故事、 政策環境、投融資事件等，歡迎您與我們一起連接這全新的 Web3.0 時代。

### 需要生成什么内容？

https://web3caff.com/zh/ ：首页文章

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://web3caff.com/feed
