### ISSUE TITLE
BBC中文网问题

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#10845]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/bbc/chinese/business
/bbc/chinese/world
/bbc/chinese/china
/bbc/chinese/uk
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#bbc

### 预期是什么？

正常使用

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/69616271/191282580-0c7f1bb2-aca9-456e-8649-830d40b68488.png)

### 部署

自建

### 额外信息

```shell
演示站也无法使用，所有参数都无法使用

路由地址填/bbc/:lang/:channel?和/bbc/chinese/business都会被机器人关
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by JaHuck** [comment]
@HenryQW 大佬来看看

**Comment by TonyRL** [comment]
Duplicate of #6996
