### ISSUE TITLE
南华早报无法显示图片

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#10866]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/scmp/91
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#nan-hua-zao-bao-scmp

### 预期是什么？

正常显示图片

### 实际发生了什么？

无法显示图片
![image](https://user-images.githubusercontent.com/113758409/191888051-301ff393-684e-452f-a070-d99e7d1dc7b7.png)
![image](https://user-images.githubusercontent.com/113758409/191888079-643e5b42-343a-40cb-8234-65aa9792e800.png)

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
我记得上次说联合早报图片不显示的也是你_(:з」∠)，你可以试试其他的阅读器能否显示吗？或者你打开一下订阅源rss的地址，看下图片对应的链接，在浏览器里是否能打开呢？

**Comment by lychichem** [comment]
啊，这个看来是路由有问题，amp.scmp.com已经不存在了，所以图可能解析不出来，这得请大佬重写路由了
