### ISSUE TITLE
/people/activities forbidden by zhihu

### ISSUE THREAD

**Issue by YukiSou** [DIYgod/RSSHub#10869]
### 路由地址

```routes
/people/activities/weijiechen
```

### 完整路由地址

```fullroutes
http://*:1200/zhihu/people/activities/weijiechen
```

### 相关文档

NA

### 预期是什么？

success

### 实际发生了什么？

Route requested: /people/activities/weijiechen

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

自建

### 部署相关信息

Ubuntu 20.04.1

### 额外信息

```shell
Helpful Information to provide when opening issue:
Path: /people/activities/weijiechen
Node version: v16.15.1
Git Hash: 5021299
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by sl1729-git** [comment]
看起来是因为知乎的api:/api/v3/moments/${id}/activities?limit=7&desktop=true被禁用了，而且我手工看了新版的api，/api/v4/moments/${id}/activities?limit=7&desktop=true，我目前找到的区别有data[0].actor被移到了data[0].source.actor，以及对于answer和article的内容不做完整返回
