### ISSUE TITLE
美联社 AP News路由错误

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#10867]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/apnews/topics/world-news
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#ap-news

### 预期是什么？

正常访问https://apnews.com/hub/world-news 的RSS路由

### 实际发生了什么？

无法访问
![image](https://user-images.githubusercontent.com/113758409/191891049-a1272786-efb8-4560-8fa4-e3ec6031abb3.png)

### 部署

自建

### 额外信息

```shell
Route requested: /topics/world-news
Error message: Cannot read properties of undefined (reading 'storyHTML')
Helpful Information to provide when opening issue:
Path: /topics/world-news
Node version: v16.16.0
Git Hash: eac49cf
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
`NOROUTE` should only be used if it's not route related.
