### ISSUE TITLE
微博图片无法显示

### ISSUE THREAD

**Issue by nick008a** [DIYgod/RSSHub#10874]
### 路由地址

```routes
/weibo/user/1195230310
```

### 完整路由地址

```fullroutes
/weibo/user/1195230310
```

### 相关文档

https://rsshub.app/weibo/user/1195230310

### 预期是什么？

微博图片显示

### 实际发生了什么？

```
403 Forbidden
nginx
```

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://github.com/HenryQW/Awesome-TTRSS/issues/399
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nick008a** [comment]
@Rongronggg9 
是不是可以加一个能够附带发送referrer的图片代理，然后重写正文的URL ``https://wx1.sinaimg.cn/large/4aa1.................jpg`` 到代理的地址上，这样微博的图片就可以正常看了。

**Comment by Rongronggg9** [comment]
参阅 https://docs.rsshub.app/parameter.html#duo-mei-ti-chu-li

遗憾的是，因为一位维护者的强烈反对，该功能并非默认可用。

**Comment by Rongronggg9** [comment]
> 试着自己搭了一下，但好像目前好像没有针对微博发送referrer的proxy可用。微博的验证机制似乎是要求referrer来自weibo.com，而非sinaimg.cn。
> 也许还是需要实现一个自己的proxy？

微博的媒体只要求 referer 来自微博或者不存在 referer。迄今为止，只要不发送 referer，都是可以正常返回图片的。如果公开的图片反代不能使用，可能是服务器被 ban。

**Comment by c71an** [comment]
docker stop rsshub
docker rm rsshub
docker run -d --name rsshub --restart unless-stopped -p 1200:1200 -e CACHE_EXPIRE=600 -e DEBUG_INFO=false -e HOTLINK_TEMPLATE='https://proxy.duckduckgo.com/iu/?u=${href}' diygod/rsshub

**Comment by KawausoJyou** [comment]
> 试着自己搭了一下，但好像目前好像没有针对微博发送referrer的proxy可用。微博的验证机制似乎是要求referrer来自weibo.com，而非sinaimg.cn。 也许还是需要实现一个自己的proxy？

你好，请问你解决这个问题了吗？

**Comment by Rongronggg9** [comment]
> 试着自己搭了一下，但好像目前好像没有针对微博发送referrer的proxy可用。微博的验证机制似乎是要求referrer来自weibo.com，而非sinaimg.cn。 也许还是需要实现一个自己的proxy？

https://github.com/DIYgod/RSSHub/issues/11096#issuecomment-1279749785
https://github.com/DIYgod/RSSHub/issues/11096#issuecomment-1279750612

**Comment by Rongronggg9** [comment]
Upd: https://github.com/Rongronggg9/rsstt-img-relay now comes with sinaimg workaround: https://github.com/Rongronggg9/rsstt-img-relay/commit/8a24955bb200a4f3e71919b1ff50a044f7338f6d

**Comment by sangjeedondrub** [comment]
写个浏览器 tampermonkey 脚本好像可以： https://greasyfork.org/en/scripts/480961-weiboimageurlreplacer
