### ISSUE TITLE
请求添加 中国货币网 全国银行间同业拆借中心

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#10880]
### 类型

金融

### 网站地址

https://www.chinamoney.com.cn/

### 网站描述

汇集中国外汇和本币市场最新政策和公告，包括国内所有主要利率的查询。

### 需要生成什么内容？

市场公告：https://www.chinamoney.com.cn/chinese/scgg-whscgg/
![image](https://user-images.githubusercontent.com/69616271/192080399-6d0ce38e-e164-4198-b7b4-161b398255f4.png)
具体需要如下
--------------- (必选) ---------- (可选)
市场公告 > 外汇市场公告 >    最新 | 市场公告通知 | 中心会员公告 | 会员信息公告
------------- 本币市场公告 >    最新 | 市场公告通知 | 中心成员公告| 成员信息公告
------------- 央行业务公告 >    最新 | 公开市场操作 | 中央国库现金管理

LPR公告：https://www.chinamoney.com.cn/chinese/bklpr/
![image](https://user-images.githubusercontent.com/69616271/192080485-935c4a3f-7934-4a42-b31e-fb3c4700ed4e.png)

      

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by ssky87** [comment]
https://www.chinamoney.com.cn/ags/ms/cm-u-bk-currency/LprHis?lang=CN
