### ISSUE TITLE
软餐路由失效了

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#10891]
### 路由地址

```routes
/ruancan
```

### 完整路由地址

```fullroutes
/ruancan
```

### 相关文档

https://docs.rsshub.app/new-media.html#ruan-can

### 预期是什么？

抓取全文

### 实际发生了什么？

抓取失败

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自带feed：https://www.ruancan.com/feed，但不抓取全文，只有摘要
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Alphabet1226** [comment]
重新审核，路由地址：https://rsshub.app/ruancan

**Comment by Alphabet1226** [comment]
还是没有恢复过来

**Comment by IlIllIl** [comment]
又失效了呢
