### ISSUE TITLE
jandan section.js error

### ISSUE THREAD

**Issue by qjebbs** [DIYgod/RSSHub#10901]
### Routes

```routes
/jandan/ooxx
```

### Full routes

```fullroutes
/jandan/ooxx
```

### Related documentation

...

### What is expected?

no error

### What is actually happening?

error msg:
```
Route requested: /ooxx
Error message: Cannot read properties of null (reading '1')
```

In `lib/v2/jandan/section.js`:
```js
ctx.state.data = {
        title: `${$('title').text()} - 煎蛋`,
        link: currentUrl,
        item: items,
        description: response.data.match(/"description": "([\s\S]*)",/)[1], // error on no match
    };
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
...
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by qjebbs** [comment]
NOROUTE: undocumented route

**Comment by TonyRL** [comment]
This is **not** undocumented
https://docs.rsshub.app/picture.html#jian-dan
