### ISSUE TITLE
Error message: Cannot read properties of undefined (reading 'entries')

### ISSUE THREAD

**Issue by fjlhub** [DIYgod/RSSHub#10928]
### Routes

```routes
/twitter/user/fjlhub
```

### Full routes

```fullroutes
/user/fjlhub
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter

### What is expected?

For RSS feed to show up.

### What is actually happening?

Route requested: /user/fjlhub
Error message: Cannot read properties of undefined (reading 'entries')
Helpful Information to provide when opening issue:
Path: /user/fjlhub
Node version: v16.17.1
Git Hash: b0216ca

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
https://rsshub.app/twitter/user/fjlhub
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by fjlhub** [comment]
请问如果添加fjlhub路由

**Comment by TonyRL** [comment]
/test
```routes
/twitter/user/fjlhub
```

**Comment by fjlhub** [comment]
好了，谢谢！
