### ISSUE TITLE
Yahoo Finance 雅虎财经

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#10948]
### 类型

金融

### 网站地址

https://finance.yahoo.com/news/

### 网站描述

知名财经网站

### 需要生成什么内容？

雅虎财经英文 最新资讯：https://finance.yahoo.com/news/

![image](https://user-images.githubusercontent.com/113758409/192958539-96f13af9-89b3-438d-95b6-5391d1fc1a4e.png)

雅虎财经香港 最新资讯：https://hk.finance.yahoo.com/

![image](https://user-images.githubusercontent.com/113758409/193858958-8e9bd8e7-3da5-4b4a-a39a-eaba6fd95a6b.png)

雅虎财经台湾 最新资讯：https://tw.finance.yahoo.com/news

![image](https://user-images.githubusercontent.com/113758409/193859149-b6a2f384-c282-41a0-b72d-e60ea8df4b6a.png)

### 额外描述
图片和摘要能保持完善

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/traditional-media.html#yahoo
