### ISSUE TITLE
Goodreads

### ISSUE THREAD

**Issue by yasirbilgic** [DIYgod/RSSHub#10943]
### Category

Reading

### Website URL

https://www.goodreads.com/

### Website description

Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists.

### What content should be included?

User Profiles
Writer Profiles

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
[Author](https://www.goodreads.com/author/show/1077326.J_K_Rowling)'s blog RSS: https://www.goodreads.com/author/show/1077326.J_K_Rowling/blog?format=rss
[User](https://www.goodreads.com/user/show/86285-angie)'s recent update RSS: https://www.goodreads.com/user/updates_rss/86285
