### ISSUE TITLE
无法正常抓取知乎问题

### ISSUE THREAD

**Issue by zjkfly** [DIYgod/RSSHub#10952]
### 路由地址

```routes
/zhihu/question/:questionId/:sortBy
```

### 完整路由地址

```fullroutes
/zhihu/question/538986890/default
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-wen-ti

### 预期是什么？

正常抓取知乎问题

### 实际发生了什么？

Response code 403 (Forbidden)

### 部署

自建

### 部署相关信息

OS:Win11 Node:v16.16.0

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #10951
