### ISSUE TITLE
知乎问题无法获取数据

### ISSUE THREAD

**Issue by zjkfly** [DIYgod/RSSHub#10951]
### 路由地址

```routes
/zhihu/question/:questionId/:sortBy
```

### 完整路由地址

```fullroutes
/zhihu/question/538986890/default
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-wen-ti

### 预期是什么？

正常抓取知乎问题

### 实际发生了什么？

Response code 403 (Forbidden)

### 部署

自建

### 部署相关信息

OS:Win11 Node:v16.16.0 

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by huangwb8** [comment]
2022-10-7，仍存在此问题，即无法正常爬取知乎问题的更新。

**Comment by QGB** [comment]
```
Route requested: /question/315630571
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /question/315630571
Node version: v16.17.0
Git Hash: 24c6413
```
