### ISSUE TITLE
bilibili UP主投稿返回404

### ISSUE THREAD

**Issue by heunghingwan** [DIYgod/RSSHub#10957]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### 预期是什么？

bilibili UP主投稿

### 实际发生了什么？

404

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Path: /bilibili/user/video/2267573
Node version: v16.17.1
Git Hash: d1b4a05
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by ivensfor** [comment]
遇到了相同的情況，自建的 RSSHub，今天无法获取 RSS 更新。

Route requested: /bilibili/user/video/8465957

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

Helpful Information to provide when opening issue:
Path: /bilibili/user/video/8465957
Node version: v16.17.0
Git Hash: 31feadc
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报]

**Comment by TonyRL** [comment]
Duplicate of #10971
