### ISSUE TITLE
【知乎】自建报错TypeError: __g._encrypt is not a function

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#10960]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/wang-tian-tian-91-22
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常运转

### 实际发生了什么？

报错

### 部署

自建

### 部署相关信息

cenos 7 node 14.18 yarn 1.22.19 docker 20.20.11

### 额外信息
更新 glibc-2.18.tar.gz 后，报错变成
```
Error message: TypeError: __g._encrypt is not a function
    at D (/RSSHub/lib/v2/zhihu/execlib/g_encrypt_3.js:428:16)
    at module.exports (/RSSHub/lib/v2/zhihu/activities.js:41:29)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /RSSHub/node_modules/koa-mount/index.js:58:5
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /RSSHub/lib/middleware/cache/index.js:122:13
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://github.com/Automattic/node-canvas/issues/1796

**Comment by Azureki** [comment]
Same problem. But my log is 
```
Error in /zhihu/people/activities/sb: Error: libcairo.so.2: cannot open shared object file: No such file or directory
```
It still happens even I have run `sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`.

**Comment by KwToPA** [comment]
> Same problem. But my log is
> 
> ```
> Error in /zhihu/people/activities/sb: Error: libcairo.so.2: cannot open shared object file: No such file or directory
> ```
> 
> It still happens even I have run `sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev` and restarted docker.

https://github.com/Automattic/node-canvas/issues/1796#issuecomment-921823147

你照着这个试试

**Comment by KwToPA** [comment]
gcc编译时间太长，已经终止。
绝大部分报错 Error: wrong path，只有一两个是version `CXXABI_1.3.9' not found

**Comment by KwToPA** [comment]
我按照 [https://github.com/Automattic/node-canvas/issues/1796#issuecomment-1253159308](https://github.com/Automattic/node-canvas/issues/1796#issuecomment-1253159308) 替换了 libstdc++.so.6
```
strings /usr/lib64/libstdc++.so.6|grep CXXABI
```
出现了 CXXABI_1.3.9，之前报错缺失CXXABI_1.3.9的那条，错误信息变更为

```
Error: wrong path
```

**Comment by KwToPA** [comment]
@Azureki  你可以试试我上面回复的那条，虽然问题依然没解决

**Comment by KwToPA** [comment]
通过把```/RSSHub/node_modules/canvas/build/Release/```中的```libstdc++.so.6```和```libz.so.1``` 复制粘贴到```/lib64```中，修复了```Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found```和```Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found```

最新报错
```
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found
 (required by /RSSHub/node_modules/canvas/build/Release/librsvg-2.so.2)
```

发现```/RSSHub/node_modules/canvas/build/Release/```中没有libc.so.6，本地的是libc-2.17.so

编译的方法见[https://github.com/Automattic/node-canvas/issues/1796#issuecomment-1253159308](https://github.com/Automattic/node-canvas/issues/1796#issuecomment-1253159308)

我的小机器拖不动，编译估计要好几个小时，

## 能否提前编译libc.so.6，放到```/RSSHub/node_modules/canvas/build/Release/```中？

谢谢

**Comment by KwToPA** [comment]
更新 glibc-2.18.tar.gz 后，报错变成
```
Error message: TypeError: __g._encrypt is not a function
    at D (/RSSHub/lib/v2/zhihu/execlib/g_encrypt_3.js:428:16)
    at module.exports (/RSSHub/lib/v2/zhihu/activities.js:41:29)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /RSSHub/node_modules/koa-mount/index.js:58:5
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /RSSHub/lib/middleware/cache/index.js:122:13
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
```

**Comment by KwToPA** [comment]
谢谢
