### ISSUE TITLE
bilibili UP 主投稿自建服务器返回 404

### ISSUE THREAD

**Issue by WilliamK7** [DIYgod/RSSHub#10971]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### 预期是什么？

显示XML文件

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/82304956/193286804-95cbb699-9237-43bb-b55f-abeff683448d.png)

### 部署

自建

### 部署相关信息

OS: Windows, Node: 14.20.0

### 额外信息

```shell
Path: /bilibili/user/video/2267573
Node version: v14.20.0
Git Hash: unknown
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by cyx20080216** [comment]
已在 #10886 中解决，请尝试更新
