### ISSUE TITLE
文档分割

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1098]
### 这是一个什么样的功能？

把文档指南页的不同分类分为不同页面

### 这个功能可以解决什么问题？

文档卡顿

### 额外描述

可以参考 vuepress 官方文档的[写法](https://github.com/vuejs/vuepress/blob/0.x/docs/.vuepress/config.js#L101)

**Comment by yefoenix** [comment]
本 issue 是不是可以关闭了 @DIYgod

**Comment by DIYgod** [comment]
Done. 0b4f026e02916072bd5da27e81e0611817e344e8
