### ISSUE TITLE
天下雜誌訂閱地址報錯

### ISSUE THREAD

**Issue by ivensfor** [DIYgod/RSSHub#11010]
### 路由地址

```routes
/cw/today
/cw/master/:channel
```

### 完整路由地址

```fullroutes
/cw/today
cw/master/8
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#tian-xia-za-zhi

### 预期是什么？

使用自建 RSSHub 訂閱天下雜誌文章

### 实际发生了什么？

訂閱地址報錯。使用自建地址以及演示地址均提示 403 錯誤

### 部署

自建

### 额外信息

```shell
Route requested: /today

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /today
Node version: v16.17.1
Git Hash: a6b0803
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
<details> 

<summary>Screenshot</summary>

![screenshot](https://user-images.githubusercontent.com/11386903/194126262-ef2359ae-1a08-4b6a-96af-6265ebc829ce.png)
</details>

**Comment by ivensfor** [comment]
請問天下雜誌的路由是否不可用？目前使用自建 RSSHub 依然沒法訂閱。
