### ISSUE TITLE
无法订阅特定B站用户的投稿

### ISSUE THREAD

**Issue by cloudjuice** [DIYgod/RSSHub#11024]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/video/57598190
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

使用订阅up主投稿功能
```
UP 主投稿
[反爬严格](https://docs.rsshub.app/faq.html) [支持浏览器扩展](https://github.com/DIYgod/RSSHub-Radar) [支持 RSSBud](https://github.com/Cay-Zhang/RSSBud)

作者: [@DIYgod](https://github.com/DIYgod)

举例: https://rsshub.app/bilibili/user/video/2267573

路由: /bilibili/user/video/:uid/:disableEmbed?
```
订阅用户“电影传送门主页妹”，uid：57598190

### 实际发生了什么？

显示Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

测试了几个其他的up主uid都可以正常订阅，同频道动态订阅https://rsshub.app/bilibili/user/dynamic/57598190也没有问题

### 部署

自建

### 部署相关信息

https://rssh-ub-rose-ten.vercel.app

### 额外信息

```shell
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/57598190
```
