### ISSUE TITLE
澎湃新闻

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#11036]
### 路由地址

```routes
/thepaper/featured
```

### 完整路由地址

```fullroutes
/thepaper/featured
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#peng-pai-xin-wen

### 预期是什么？

文章数量显示全，用PC端thepaper.cn域名爬取。

### 实际发生了什么？

文章数量不全，经常比官网的文章少，没有抓取到。

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by bigfei** [comment]
建议增加刷新的频率，我这边按照15分钟刷一遍没有遗漏的。
