### ISSUE TITLE
金十数据

### ISSUE THREAD

**Issue by JaHuck** [DIYgod/RSSHub#11037]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/jinshi/index
```

### 相关文档

https://docs.rsshub.app/finance.html#jin-shi-shu-ju

### 预期是什么？

内容显示正常，图片显示正常。重要消息，字体可以像原网站一样加红色。

设置带【】为标题。不带【】都是短文，标题就是本文。

![image](https://user-images.githubusercontent.com/69616271/194742838-4e444e43-b04c-4778-930e-ca4b157bdecf.png)

### 实际发生了什么？

没有内容，没有图片，链接不是原地址。

![image](https://user-images.githubusercontent.com/69616271/194742928-ea2bf9a6-598d-4dda-8872-8e68ff74ffa1.png)

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Using `NOROUTE` for route related issue
