### ISSUE TITLE
百度贴吧无法提取

### ISSUE THREAD

**Issue by Pengkaniu** [DIYgod/RSSHub#11079]
### 路由地址

```routes
/baidu/tieba/forum/:kw
```

### 完整路由地址

```fullroutes
/baidu/tieba/forum/temtem
```

### 相关文档

https://docs.rsshub.app/bbs.html#bai-du-tie-ba

### 预期是什么？

应该正常输出

### 实际发生了什么？

wrong,以前提取贴吧是用的网页源代码的kw，这个不管用什么方法都无法提取。

### 部署

自建

### 部署相关信息

vercel

### 额外信息

```shell
Route requested: /baidu/tieba/forum/temtem
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /baidu/tieba/forum/temtem
Node version: v14.20.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Please update your self-hosted instance.
