### ISSUE TITLE
条目限制功能拓展

### ISSUE THREAD

**Issue by 821938089** [DIYgod/RSSHub#1109]
### 这是一个什么样的功能？
仅返回特定部分的条目。
还有加一个pn来做成可翻页的功能。
当pn小于等于0时取最后一页，超过范围也取最后一页
返回的数据中增加总pn数
### 这个功能可以解决什么问题？
解决请求一次（某些）api所返回数据量过大，但是我所需要的数据只占很小一部分。
还可以有效提升rss的刷新速度。
### 额外描述
我看过文档了，有类似的条目限制，但是不适合我用，他只能取前面的，取不了某一部分的内容，有些鸡肋。
希望作者能够完善一下这个功能。

**Comment by DIYgod** [comment]
RSS 只获取更新内容，这个不属于 RSS 功能
