### ISSUE TITLE
联合早报要求登录以查看全文

### ISSUE THREAD

**Issue by lychichem** [DIYgod/RSSHub#11135]
### 路由地址

```routes
/zaobao/realtime/:section?
```

### 完整路由地址

```fullroutes
/zaobao/realtime/china
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#lian-he-zao-bao

### 预期是什么？

能正常输出全文

### 实际发生了什么？

只显示部分内容并在最下方提示须登录或订阅以查看全文

### 部署

自建

### 部署相关信息

OS: Ubuntu 20.04 x64, docker最新版

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
![Screenshot_2022-10-22-19-03-29-71_547cb517dbc67c82fd4f9b8f2ef91c95.jpg](https://user-images.githubusercontent.com/9316590/197335624-427aa289-1413-4457-a848-4d2f0472c487.jpg)
截图

**Comment by lychichem** [comment]
> ~~似乎可以通过修改 UA 为移动端，来获取到完整内容。~~
> 
> 测试了下，发现不可行，完全是因为我用了 HK 节点访问，所以能查看全文。
> 要想查看全文，估计还是要在 HK 服务器上部署，但是又可能会有之前的文章排版问题 ( #10309 ) 。
> 倒是图片地址的问题 ( #10830 ) 解决了，但是不确定文章排版会不会受影响。

不好说，我当时观察到的结论是只有特定专题（例如，二十大）才会要求登录，你最近看的内容应该没有强制要登录后查看全文的。
文章排版估计我是无解，hk版那个js目前我没啥好招。
图片地址问题能修吗？我记得那是个oss服务器，不加referer且没重定向会直接给403的，像ttrss就不能看图所以我才折腾的

**Comment by NekoAria** [comment]
> > ~~似乎可以通过修改 UA 为移动端，来获取到完整内容。~~
> > 
> > 测试了下，发现不可行，完全是因为我用了 HK 节点访问，所以能查看全文。
> > 要想查看全文，估计还是要在 HK 服务器上部署，但是又可能会有之前的文章排版问题 ( #10309 ) 。
> > 倒是图片地址的问题 ( #10830 ) 解决了，但是不确定文章排版会不会受影响。
> 
> 不好说，我当时观察到的结论是只有特定专题（例如，二十大）才会要求登录，你最近看的内容应该没有强制要登录后查看全文的。
> 文章排版估计我是无解，hk版那个js目前我没啥好招。
> 图片地址问题能修吗？我记得那是个oss服务器，不加referer且没重定向会直接给403的，像ttrss就不能看图所以我才折腾的

我后来观察了几天，发现不稳定，有时候拿到的图片地址还是不对的，并不能完全解决。

**Comment by TonyRL** [comment]
/test
```routes
/zaobao/realtime/china
```

**Comment by lychichem** [comment]
@TonyRL 目前暂时没观测到会触发这个问题的新闻主题，issue我先关闭了，目测到两会的时候可能会再次出现，到时候再看有啥办法吧

**Comment by lychichem** [comment]
> 仍然存在这个问题，就算是今天。 不过节点是 /zaobao/znews/china 。
> 
> 看了下，并不只是个人部署才有这个问题，官方源也一样。

已确认，目前的观察显示要解决登录问题得用hk版本（部署在靠近香港的服务器上），但没法解决排版问题；要解决排版问题得用sg版本，但就没法解决登录问题。可能得请pupptter，但是这个可能就会造成自建部署大规模报错了（

**Comment by TonyRL** [comment]
/test
```routes
/zaobao/realtime/china
```
