### ISSUE TITLE
移除 json 格式输出

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1114]
### 这是一个什么样的功能？

移除 json 格式输出

### 这个功能可以解决什么问题？

json 格式对 RSS 功能没有任何用处，还容易被滥用

### 额外描述

如果有正常使用场景可以留言讨论

**Comment by gixid192** [comment]
I'm using RSSHub as a source to crawl data from Twitter, using node js or fetch API from browsers to get the tweets. As you already know, Javascript doesn't work well with XML so I really hope this feature will be available again.

**Comment by SettingDust** [comment]
@gixid192 Someone use the offical demo for api. So I think, is there a env to set the json format will output?

**Comment by gixid192** [comment]
@SettingDust I'm not sure what you mean.
Yes, it is doable within the API but if we implement the API, we won't need RSSHub.
What I wanted here is a consistency way to implement the config and the data (All I need is using RSSHub links instead of implementing different APIs).

**Comment by SettingDust** [comment]
@gixid192 Someone use the official json for their own develop. My advice is add a env var

**Comment by gixid192** [comment]
@SettingDust I'm not sure what you mean by "Someone", "offcial json" xD
Anyway, if you mean adding an env var as a workaround to this issue, I think it depends, as we are not the one who code it, need to read the code to see if we can use the setting there.

**Comment by SettingDust** [comment]
@gixid192 Someone is some people.
official json is rsshub.app json data

**Comment by HenryQW** [comment]
@gixid192 We have detected users abusing RSSHub’s JSON feed with abnormal request frequency, resulting in direct ban by multiple sites, which in turn affects everyone else. If you wish to use JSON feed please deploy your own instance.

**Comment by DIYgod** [comment]
@gixid192 The problem is that RSSHub is a RSS service, I don't want any abuse.

You should deploy your own service if you want a web API.

**Comment by gixid192** [comment]
I see. Thank you guys @HenryQW @DIYgod

**Comment by zicjin** [comment]
为什么不能给一个配置选项呢。如此武断地直接移除。逼迫用户还要fork一份代码，修复代码，再“deploy your own service”？

**Comment by SettingDust** [comment]
> 为什么不能给一个配置选项呢。如此武断地直接移除。逼迫用户还要fork一份代码，修复代码，再“deploy your own service”？

欢迎 PR 新的配置

**Comment by hoilc** [comment]
> 为什么不能给一个配置选项呢。如此武断地直接移除。逼迫用户还要fork一份代码，修复代码，再“deploy your own service”？

RSSHub不是商业产品，对用户没有什么义务...JSON输出的滥用不仅仅影响demo服务器，而且潜在地会导致更多的反扒措施...你确定你现在是想用做rss用途吗？

**Comment by yefoenix** [comment]
> RSSHub is a RSS service, I don't want any abuse.
 DIY 说的已经很清楚了，RSSHub 项目的宗旨就是提供rss输出，json 已经偏离太多了。

**Comment by vicdorke** [comment]
需要这个功能啊！

**Comment by mashirozx** [comment]
Revert 了 Json 输出（有 bug 请告诉我），有需要的请自行 cherry pick：https://github.com/mashirozx/RSSHub/commit/f220ac89ce2e77034c4050fcf8d318b4ad5b463c

合并的时候记得把 package.json 里面的 git hook 删掉，否则过不了语法检查。

因为自己要用，所以会长期更新，可以关注我的 fork，每次更新我会 rebase 到最上面的 commit 里面。

另想请问官方是否有意愿 revert？我可以：

- 加上是否启用 JSON 输出的选项（关闭的情况下保证不改变原有逻辑，只加一个简单的 if 判断）
- 保证长期维护（模板如果没有其他人维护我来维护，不会给别人添麻烦的）

如果官方有意愿合并，我会整理出干净的 PR。

**Comment by HenryQW** [comment]
> Revert 了 Json 输出（有 bug 请告诉我），有需要的请自行 cherry pick：[mashirozx@f220ac8](https://github.com/mashirozx/RSSHub/commit/f220ac89ce2e77034c4050fcf8d318b4ad5b463c)
> 
> 合并的时候记得把 package.json 里面的 git hook 删掉，否则过不了语法检查。
> 
> 因为自己要用，所以会长期更新，可以关注我的 fork，每次更新我会 rebase 到最上面的 commit 里面。
> 
> 另想请问官方是否有意愿接受 revert 这个功能？我可以：
> 
> * 加上是否启用 JSON 输出的选项（关闭的情况下保证不改变原有逻辑，只加一个简单的 if 判断）
> * 优化相关代码
> * 保证长期维护（模板如果没有其他人维护我会尽力维护，不会给别人添麻烦）
> 
> 如果有肯定的答复，我会认真整理一个干净的 PR。

输出 JSON 的目的是什么？RSSHub 的主要目的就是输出符合 RSS 协议规范的源。上面也说得很清楚了，小部分用户滥用了输出 JSON 的功能导致大部分人受影响（网站封了 RSSHub 的访问），所以移除了相关代码。

**Comment by mashirozx** [comment]
> > Revert 了 Json 输出（有 bug 请告诉我），有需要的请自行 cherry pick：[mashirozx@f220ac8](https://github.com/mashirozx/RSSHub/commit/f220ac89ce2e77034c4050fcf8d318b4ad5b463c)
> > 合并的时候记得把 package.json 里面的 git hook 删掉，否则过不了语法检查。
> > 因为自己要用，所以会长期更新，可以关注我的 fork，每次更新我会 rebase 到最上面的 commit 里面。
> > 另想请问官方是否有意愿接受 revert 这个功能？我可以：
> > 
> > * 加上是否启用 JSON 输出的选项（关闭的情况下保证不改变原有逻辑，只加一个简单的 if 判断）
> > * 优化相关代码
> > * 保证长期维护（模板如果没有其他人维护我会尽力维护，不会给别人添麻烦）
> > 
> > 如果有肯定的答复，我会认真整理一个干净的 PR。
> 
> 输出 JSON 的目的是什么？RSSHub 的主要目的就是输出符合 RSS 协议规范的源。上面也说得很清楚了，小部分用户滥用了输出 JSON 的功能导致大部分人受影响（网站封了 RSSHub 的访问），所以移除了相关代码。

不瞒你说，我自己是把rsshub作为API用的，这是一个很方便的框架。我已经提到，会做成一个默认关闭的选项，官网不开起这个功能即可。

**Comment by tuchang** [comment]
> > 为什么不能给一个配置选项呢。如此武断地直接移除。逼迫用户还要fork一份代码，修复代码，再“deploy your own service”？
> 
> 欢迎 PR 新的配置

后面交流的意思是
不欢迎 PR 新的配置 新配置其实也不会过 
是吗，还是说有不同的情况？

**Comment by mashirozx** [comment]
OK，我明白你们的意思了，或许是有导致更严格反爬措施的可能性。
仅提出我的观点：对于爬取量大的用户，仅仅是移除JSON，从根本上无法阻止他们的滥用，一个RSS parser或者加一个JSON模板对他们来说都是小意思。
既然这是事实，不如接受这一点，索性给动手能力一般的用户一个使用JSON接口的机会。普通用户不应该为爬虫大佬的行为买单（不方便）。

**Comment by DIYgod** [comment]
Thanks for the discussion.

But the point is that RSSHub is an RSS service, so even if there were no abuse issues, this should not be done.

The right thing to do is to make a separate service for converting RSS to JSON, which is unrelated to RSSHub and independent of it.

**Comment by datatube-owner** [comment]
同意 RSShub codebase 应该默认不支持以防止滥用。https://datatube.dev/ 我的节点在 RSSHub 外面加了一层 JSON 支持。

**Comment by vicdorke** [comment]
太棒了

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/discussions/8226

作为开发者debug选项开启，有能力的开发者可以自行接入，默认关闭

这个部分还在探讨，但是自定义模版是应该100%会在支持选项里面，进度可以关注https://github.com/DIYgod/RSSHub/pull/8224

**Comment by mashirozx** [comment]
> #8226
> 
> 作为开发者debug选项开启，有能力的开发者可以自行接入，默认关闭
> 
> 这个部分还在探讨，作为插件规范的一部分，RSS限制比较多
> 但是自定义模版是应该100%会在支持选项里面，进度可以关注#8224

好耶
![image](https://user-images.githubusercontent.com/16148054/134289626-add23cd6-ba9e-466b-bcde-072c7172366d.png)

**Comment by NeverBehave** [comment]
https://docs.rsshub.app/joinus/script-standard.html

实验性支持已经添加，后续追踪请使用 https://github.com/DIYgod/RSSHub/discussions/8236
