### ISSUE TITLE
简书无法抓取

### ISSUE THREAD

**Issue by chenyue404** [DIYgod/RSSHub#11140]
### 路由地址

```routes
/jianshu/user/
```

### 完整路由地址

```fullroutes
https://rsshub.app/jianshu/user/4f2c483c12d8
```

### 相关文档

https://docs.rsshub.app/social-media.html#jian-shu-zuo-zhe

### 预期是什么？

正常返回数据

### 实际发生了什么？

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /jianshu/user/4f2c483c12d8
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /jianshu/user/4f2c483c12d8
Node version: v16.18.0
Git Hash: 2c6318d

包括自建的和其他公共的rsshub，都是如此。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/jianshu/user/4f2c483c12d8
```
