### ISSUE TITLE
希望增加对住建局网站的RSS提案

### ISSUE THREAD

**Issue by chofan007** [DIYgod/RSSHub#11141]
### 类型

政务消息

### 网站地址

https://zw.cdzjryb.com/lottery/accept/projectList

### 网站描述

这是成都市商品房购买登记查询网站，最新房源信息展示。

### 需要生成什么内容？

想生成：成都各大区最新房源登记信息，用于提醒。

### 额外描述

希望大佬能帮助我实现一下，其他人应该也需要。我已经弄了几天没成功，只能求助了，感谢！

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by terrytw** [comment]
这网站要登录，一般来说是没戏的
