### ISSUE TITLE
联合早报、澎湃新闻报错

### ISSUE THREAD

**Issue by xeqtr1982** [DIYgod/RSSHub#11163]
### 路由地址

```routes
/zaobao/realtime/:section?
/thepaper/featured
```

### 完整路由地址

```fullroutes
/zaobao/realtime/china
/thepaper/featured
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#lian-he-zao-bao https://docs.rsshub.app/traditional-media.html#peng-pai-xin-wen

### 预期是什么？

能正常输出全文

### 实际发生了什么？

this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

自建

### 部署相关信息

OS: 群晖6.2.4, Node version: v14.18.1, Docker version 20.10.3, build b35e731

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
在我自己的部署上均没有问题，尝试更新下部署版本？

**Comment by bigfei** [comment]
独立部署没有问题，会不会是版本的问题？

**Comment by xeqtr1982** [comment]
多谢二位，可能跟用了阿里云的docker镜像加速器有关系。重新下了一个Docker Hub上的，虽然很慢，但是重新部署没问题了。
