### ISSUE TITLE
Odaily文章订阅返回错误（找到初步原因）

### ISSUE THREAD

**Issue by windsurf2sky** [DIYgod/RSSHub#11174]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

https://rsshub.app/odaily 返回正常xml文件

### 实际发生了什么？

Looks like something went wrong
Route requested: /
Error message: Cannot read properties of undefined (reading 'name')

Helpful Information to provide when opening issue:
Path: /
Node version: v16.18.0
Git Hash: 90a593c

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://www.0daily.com/api/pp/api-front/feed-stream?feed_id=280 返回异常404
https://www.odaily.news/api/pp/api/feed-stream?feed_id=280 返回看起来正常
估计是由于API路径变化导致爬取时出现异常
前面提的Issue已被bot关闭，只能重提一个，并补充了初步问题原因
https://github.com/DIYgod/RSSHub/issues/11172
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lylunula** [comment]
提点不成熟的小建议：
1. 能否读取他们301跳转的最新域名来爬取，我看最终都会跳转指向正确的域名；
2. 一个rss背后能否有多个备用域名，这样可以在不通的时候作为backup。
辛苦啦😯
