### ISSUE TITLE
希望添加国家电网停电通知

### ISSUE THREAD

**Issue by whwq2012** [DIYgod/RSSHub#1117]
### 源站地址
http://www.95598.cn/95598/outageNotice/initCityOutageNotice?orgNo=3610136411&amp;startTime&startTime=2018-11-11%2000:00&endTime=2018-11-18%2000:00
### 需要生成什么内容？

- [ ] 内容一
输入市和县就能查询到哪些区域有停电通知
- [ ] 内容二

**Comment by LogicJake** [comment]
这么多地区有点难处理
