### ISSUE TITLE
cnbeta.com.tw

### ISSUE THREAD

**Issue by c71an** [DIYgod/RSSHub#11192]
### 类型

新媒体

### 网站地址

https://www.cnbeta.com.tw/

### 网站描述

cnbeta.com目前无法访问，可选择访问域名cnbeta.com.tw以继续访问

### 需要生成什么内容？

图文全文

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by terrytw** [comment]
https://www.cnbeta.com.tw/backend.php is required for this site to work. And it is empty now.

Please contact owner of the website to fix this before it can be implemented.
