### ISSUE TITLE
什么值得买关键词这几天开始无法获取了

### ISSUE THREAD

**Issue by murderer17** [DIYgod/RSSHub#11193]
### Routes

```routes
Route requested: /smzdm/keyword/6730
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /smzdm/keyword/6730
Node version: v16.17.0
Git Hash: 89ee2f9
```

### Full routes

```fullroutes
Route requested: https://rsshub.app/smzdm/keyword/6730
```

### Related documentation

https://rsshub.app/smzdm/keyword/6730

### What is expected?

希望能够修复什么值得买的关键词获取

### What is actually happening?

什么值得买的关键词获取失败了，从这几天开始

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by murderer17** [comment]
https://rsshub.app/smzdm/keyword/6730  可以打开呀，但是里面内容是错误

**Comment by david9965** [comment]
NOROUTE

**Comment by david9965** [comment]
> ##### Searching for maintainers:
> * `Route requested: /smzdm/keyword/6730`: **Route not found**
> * `Error message: this route is empty, please check the original site or create an issue`: **Route not found**
> * `Helpful Information to provide when opening issue:`: **Route not found**
> * `Path: /smzdm/keyword/6730`: **Route not found**
> * `Node version: v16.17.0`: **Route not found**
> * `Git Hash: 89ee2f9`: **Route not found**
> 
> > To maintainers: if you are not willing to be disturbed, list your username in `scripts/workflow/test-issue/call-maintainer.js`. In this way, your username will be wrapped in an inline code block when tagged so you will not be notified.
> 
> 如果有任何路由无法匹配，issue 将会被自动关闭。如果 issue 和路由无关，请使用 `NOROUTE` 关键词，或者留下评论。我们会重新审核。 If there is any route not found, the issue will be closed automatically. Please use `NOROUTE` for a route-irrelevant issue or leave a comment if it is a mistake.

NOROUTE
