### ISSUE TITLE
线报酷

### ISSUE THREAD

**Issue by nanbowaner** [DIYgod/RSSHub#11217]
### 类型

购物

### 网站地址

https://v1.xianbao.fun/

### 网站描述

线报酷收集分享各类项目和活动信息

### 需要生成什么内容？

按分类生成rss，如 豆瓣线报 https://v1.xianbao.fun/category-douban.html

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by suibianzai** [comment]
同求
