### ISSUE TITLE
Email RSS

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1121]
### 源站地址

https://www.mailgun.com/

### 需要生成什么内容？

- [ ] 不同 id 的邮件列表

### 额外描述

使用 mailgun 托管一个邮箱，比如 `rss@rsshub.app`

用户给 `rss+id@rsshub.app` 发邮件

`/email/:id` 路由生成 `rss+id@rsshub.app` 的邮件列表 RSS

或者使用 Gmail：https://developers.google.com/apis-explorer/#search/gmail/gmail/v1/

**Comment by DIYgod** [comment]
想到的使用场景：

- 仅支持 Email 的数据源
- IFTTT 联动
- ...

**Comment by HenryQW** [comment]
https://github.com/leafac/kill-the-newsletter

**Comment by yefoenix** [comment]
https://zapier.com/apps/gmail/integrations/rss
免费版有数量限制
