### ISSUE TITLE
部分网易号无法提取

### ISSUE THREAD

**Issue by hypopo103** [DIYgod/RSSHub#11247]
### 路由地址

```routes
/netease/dy/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/netease/dy/W2428587692377158123
https://rsshub.app/netease/dy/W8883822875351758544
```

### 相关文档

https://docs.rsshub.app/new-media.html#wang-yi-du-jia

### 预期是什么？

网易号RSS可以工作

### 实际发生了什么？

Reeder could not find a feed at the specified location.

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Reeder could not find a feed at the specified location.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed in #11809
