### ISSUE TITLE
NMPA not working anymore

### ISSUE THREAD

**Issue by terrytw** [DIYgod/RSSHub#11263]
### Routes

```routes
/gov/nmpa/:path+
```

### Full routes

```fullroutes
/gov/nmpa/ylqx/ylqxzhcjd
```

### Related documentation

https://docs.rsshub.app/government.html#guo-jia-yao-pin-jian-du-guan-li-ju

### What is expected?

RSS generated

### What is actually happening?

Error message: Waiting for selector .list failed: Protocol error (Runtime.callFunctionOn): Target closed.

Helpful Information to provide when opening issue:
Path: /nmpa/ylqx/ylqxzhcjd
Node version: v16.18.1
Git Hash: 8b88fef

### Deployment information

Self-hosted

### Additional info

```shell
None.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/gov/nmpa/ylqx/ylqxzhcjd
```

**Comment by TonyRL** [comment]
It works fine

<details><summary>/gov/nmpa/ylqx/ylqxzhjd</summary>

![screenshot](https://user-images.githubusercontent.com/11386903/201697736-e8e797a4-fa09-4bc0-8079-3d2dd433445f.png)
</details>

**Comment by terrytw** [comment]
@TonyRL Hi, I have tested it on 3 of my own servers, and it definitely does not work. Even your test run on Saturday showed the same result 
`ProtocolError: Waiting for selector `.list` failed: Protocol error (Runtime.callFunctionOn): Target closed.`

**Comment by terrytw** [comment]
Thanks!
