### ISSUE TITLE
Lofter Tag路由从9月25日起失效

### ISSUE THREAD

**Issue by yett1873** [DIYgod/RSSHub#11287]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/lofter/tag/:name?/:type?
```

### 相关文档

https://docs.rsshub.app/en/social-media.html#lofter

### 预期是什么？

。

### 实际发生了什么？

User路由一直正常，Tag自9月25日起失效，无法获取新内容。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/lofter/tag/摄影/date
```
