### ISSUE TITLE
AIEA upcoming seminars

### ISSUE THREAD

**Issue by fredericky123** [DIYgod/RSSHub#11288]
### 类型

学习

### 网站地址

http://www.aiea.org/0504

### 网站描述

亚洲创新创业协会

### 需要生成什么内容？

需要生成近期的学术会议
谢谢

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by zxx-457** [comment]
你好

请问 http://www.aiea.org/0504 的 0504 路径是固定的吗

**Comment by fredericky123** [comment]
> 你好
> 
> 请问 http://www.aiea.org/0504 的 0504 路径是固定的吗

目前来看，是的，谢谢啦
