### ISSUE TITLE
喜马拉雅 ximalaya 专辑路由 部分播客 无法获取音频节目

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#11286]
### 路由地址

```routes
/ximalaya/:type/:id/:all?
```

### 完整路由地址

```fullroutes
/ximalaya/album/56640264/
/ximalaya/album/71604776
```

### 相关文档

https://docs.rsshub.app/multimedia.html#xi-ma-la-ya-zhuan-ji-bu-shu-chu-shownote

### 预期是什么？

能获取节目的音频文件

### 实际发生了什么？

RSS feed里，节目内容都提示“该内容需付费”，但实际上网页上这两个播客（[1](https://www.ximalaya.com/album/56640264)、[2](https://www.ximalaya.com/album/71604776)），都是可以免费收听的。这是rsshub的获取错误，还是喜马拉雅那边故意设置呢？如果是前者，希望能修复一下啊，后者的话，是否有办法处理一下，毕竟网页端是能正常收听的。

![image](https://user-images.githubusercontent.com/3047708/202338524-9ee7754a-5e0f-4ef2-862f-01c06ccb8adb.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ruleroller** [comment]
还有这个：/ximalaya/album/20954575

估计还有其它的漏网之鱼，不再一一列举了。难怪不少播客播放器里都未能抓取到新节目了。Orz

**Comment by prnake** [comment]
问题来源于喜马拉雅的 API，比如 `http://mobile.ximalaya.com/mobile/v1/album/track/?albumId=56640264`，在大陆以外地区请求时不会返回音频 url。
使用网页版本会提示 `应版权方要求，该资源仅限中国大陆用户使用`。
只能在国内部署 RSSHub服务解决。
