### ISSUE TITLE
知乎日报-瞎扯获取不到最新内容

### ISSUE THREAD

**Issue by xmt328** [DIYgod/RSSHub#11291]
### 路由地址

```routes
/zhihu/daily/section/:sectionId
```

### 完整路由地址

```fullroutes
/zhihu/daily/section/2
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-zhi-hu-ri-bao-he-ji

### 预期是什么？

能够获取到最新的文章，比如https://daily.zhihu.com/story/9755090

### 实际发生了什么？

实际上最新的一条到11月9日就结束了 https://daily.zhihu.com/story/9754911

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by JimenezLi** [comment]
Do you still have this problem? The problem may be caused because the data from zhihu API is reversed. I have added the time and the items should be sorted by time.

**Comment by TonyRL** [comment]
Can't repro in #13020
