### ISSUE TITLE
 知乎只有收藏夹RSS work

### ISSUE THREAD

**Issue by Crystaleee** [DIYgod/RSSHub#113]
其他要么403（用户动态、用户回答）
要么typeerror (专栏)

**Comment by lilydjwg** [comment]
是不是抓太狠了？可以说一下每分钟的请求数吗？
[我的知乎RSS服务](https://rss.lilydjwg.me/)目前每分钟请求数在一二十，一直工作正常（偶尔会网络不好）。

**Comment by DIYgod** [comment]
@lilydjwg 用的人越来越多，接口访问太频繁了，现在缓存改成了 10 分钟
