### ISSUE TITLE
B站UP主投稿路由问题

### ISSUE THREAD

**Issue by vidawn324** [DIYgod/RSSHub#11327]
### 路由地址

```routes
/bilibili/user/video/2267573
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

正常抓取

### 实际发生了什么？

UP 主投稿出问题，UP 主动态缺可以

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: this route is empty, please check the original site or create an issue
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```
