### ISSUE TITLE
代理，优化其他网站的 rss 链接

### ISSUE THREAD

**Issue by Kevin6872** [DIYgod/RSSHub#11332]
### 这是一个什么样的功能？

借助 RSSHub已有的功能，可以对网站本身支持 rss， 但支持并不是很好的网站进行优化。

### 这个功能可以解决什么问题？

对支持 rss ，但网站内图片有防盗链的网站图片进行处理，对繁体网站转换为简体，对网站内容进行过滤，对不支持全文输出的网站输出全文……只要是 RSSHub 支持的功能，都可以应用在其他网站上。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/issues/8874 https://github.com/DIYgod/RSSHub/issues/7122 https://github.com/DIYgod/RSSHub/discussions/6671

**Comment by TonyRL** [comment]
Duplicate of #8874
