### ISSUE TITLE
能否为小宇宙feed的每个item添加author

### ISSUE THREAD

**Issue by hapihacking** [DIYgod/RSSHub#11354]
### 这是一个什么样的功能？

目前该feed缺少必须参数author

![image](https://user-images.githubusercontent.com/8591495/204480785-ab80d40b-54bd-40f7-9310-9483780e1f25.png)

### 这个功能可以解决什么问题？

可以解决rss管理器无法获取某个item的作者的问题

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by prnake** [comment]
泛用性播客客户端应该不需要这个字段，只需要 `itunes:author`，参考喜马拉雅的实现 `https://rsshub.app/ximalaya/album/56640264`
