### ISSUE TITLE
中国法学网

### ISSUE THREAD

**Issue by FeiLZX3Km** [DIYgod/RSSHub#11373]
### 类型

学习

### 网站地址

http://iolaw.cssn.cn/

### 网站描述

中国法学网是由中国社会科学院法学研究所设立、建设和管理的法学专业网站，旨在拓展法学研究所及其员工存在和发展的虚拟空间，展示科研成果，传播法学信息，提供法律 ...

### 需要生成什么内容？

http://iolaw.cssn.cn/zxzp/

http://iolaw.cssn.cn/llwz/

等

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Closed in #12363
