### ISSUE TITLE
Pikapods 自建除微博热搜外其他无法使用

### ISSUE THREAD

**Issue by Pauluooooo** [DIYgod/RSSHub#11372]
### 路由地址

```routes
/weibo/search/hot
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
weibo/search/hot?key=XXX
weibo/user/2832402680?key=XXX
```

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo

### 预期是什么？

都能正常访问

### 实际发生了什么？

微博热搜能够正常访问，个人用户无法访问，后面测试了 B 站，知乎，都无法访问

### 部署

自建

### 部署相关信息

pikapods

### 额外信息

```shell
Route requested: /weibo/user/2832402680
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /weibo/user/2832402680
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Pauluooooo** [comment]
> 

刚刚路由参数填错了

**Comment by TonyRL** [comment]
Please update your self-hosted instance. You're using codes from March this year.

**Comment by Pauluooooo** [comment]
> Please update your self-hosted instance. You're using codes from March this year.

There is no option to update in Pikapods.
