### ISSUE TITLE
🔴「Picuki」RSS 失效

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#11398]
### 路由地址

```routes
/picuki/profile/:id/:functionalFlag?
```

### 完整路由地址

```fullroutes
/picuki/profile/stefaniejoosten
```

### 相关文档

https://docs.rsshub.app/social-media.html#picuki-yong-hu

## 「官方演示」和「自建」均出现报错

失效了已经有一段时间了

https://rsshub.app/picuki/profile/stefaniejoosten

https://github.com/DIYgod/RSSHub/issues/11348

## Looks like something went wrong

Route requested: /profile/stefaniejoosten
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /profile/stefaniejoosten
Node version: v16.18.1
Git Hash: 314b052

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v16.18.1 Git Hash: 314b052

### 额外信息

```shell
Route requested: /profile/stefaniejoosten
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /profile/stefaniejoosten
Node version: v16.18.1
Git Hash: 314b052
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Rongronggg9** [comment]
反爬严格

**Comment by FallenFolkFox** [comment]
yup having the same issue - on self-hosted instance too

**Comment by Japhys** [comment]
Same here
