### ISSUE TITLE
时光网rss失效

### ISSUE THREAD

**Issue by mxh173** [DIYgod/RSSHub#11428]
### 路由地址

```routes
/mtime/news
```

### 完整路由地址

```fullroutes
/mtime/news
```

### 相关文档

https://docs.rsshub.app/multimedia.html#shi-guang-wang

### 预期是什么？

返回rss订阅

### 实际发生了什么？

Looks like something went wrong
Route requested: /news
Error message: connect ECONNREFUSED 127.0.0.1:443: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /news
Node version: v16.18.1
Git Hash: cd0b88f
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /news
Error message: connect ECONNREFUSED 127.0.0.1:443: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /news
Node version: v16.18.1
Git Hash: cd0b88f
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
```bash
$ nslookup news.mtime.com
```
is returning 127.0.0.1
