### ISSUE TITLE
Tiktok video URLs don't work

### ISSUE THREAD

**Issue by jcmag** [DIYgod/RSSHub#11438]
### Routes

```routes
/tiktok/user/:user
```

### Full routes

```fullroutes
/tiktok/user/@iyakhyar0v
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#tiktok

### What is expected?

A URL to a video that is working

### What is actually happening?

Here is an example of an item in this feed:

`
 <description><![CDATA[<video controls="" loop="" poster="https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/o8CB3rEok4AfIhn8G6IvEwN4FnzdgABIbB9xdE?x-expires=1670886000&amp;x-signature=wPYvHZ9P62MRgidGVYxuBxyrgPk%3D" preload="none">
<source src="https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/owEoQDRgRPFQjA5bJuQhsPe4geOnEB8WJ3WBmu/?a=1988&amp;ch=0&amp;cr=0&amp;dr=0&amp;lr=tiktok_m&amp;cd=0%7C0%7C1%7C0&amp;cv=1&amp;br=2730&amp;bt=1365&amp;cs=0&amp;ds=3&amp;ft=ebLH6H-qMyq8Zze-vhe2N.dufl7Gb&amp;mime_type=video_mp4&amp;qs=0&amp;rc=OWk0NzllZTU5ZDM8M2c5OkBpM2k4eDc6Zm9paDMzNzczM0BgYy4vMC00XjQxLTM1YTVfYSMxay1icjRnNC9gLS1kMTZzcw%3D%3D&amp;expire=1670886275&amp;l=20221212170421BE775643E704C154E37E&amp;policy=2&amp;signature=3743a6d5f6675ca070425cf458819058&amp;tk=tt_chain_token">
</video>]]></description>`

the "source" tag points to an invalid video:
[https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/owEoQDRgRPFQjA5bJuQhsPe4geOnEB8WJ3WBmu/?a=1988&amp;ch=0&amp;cr=0&amp;dr=0&amp;lr=tiktok_m&amp;cd=0%7C0%7C1%7C0&amp;cv=1&amp;br=2730&amp;bt=1365&amp;cs=0&amp;ds=3&amp;ft=ebLH6H-qMyq8Zze-vhe2N.dufl7Gb&amp;mime_type=video_mp4&amp;qs=0&amp;rc=OWk0NzllZTU5ZDM8M2c5OkBpM2k4eDc6Zm9paDMzNzczM0BgYy4vMC00XjQxLTM1YTVfYSMxay1icjRnNC9gLS1kMTZzcw%3D%3D&amp;expire=1670886275&amp;l=20221212170421BE775643E704C154E37E&amp;policy=2&amp;signature=3743a6d5f6675ca070425cf458819058&amp;tk=tt_chain_token](https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/owEoQDRgRPFQjA5bJuQhsPe4geOnEB8WJ3WBmu/?a=1988&amp;ch=0&amp;cr=0&amp;dr=0&amp;lr=tiktok_m&amp;cd=0%7C0%7C1%7C0&amp;cv=1&amp;br=2730&amp;bt=1365&amp;cs=0&amp;ds=3&amp;ft=ebLH6H-qMyq8Zze-vhe2N.dufl7Gb&amp;mime_type=video_mp4&amp;qs=0&amp;rc=OWk0NzllZTU5ZDM8M2c5OkBpM2k4eDc6Zm9paDMzNzczM0BgYy4vMC00XjQxLTM1YTVfYSMxay1icjRnNC9gLS1kMTZzcw%3D%3D&amp;expire=1670886275&amp;l=20221212170421BE775643E704C154E37E&amp;policy=2&amp;signature=3743a6d5f6675ca070425cf458819058&amp;tk=tt_chain_token)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
no errors, but every "source" tag is invalid
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/tiktok/user/@iyakhyar0v
```

**Comment by TonyRL** [comment]
Looks like videos from `v16m-webapp.tiktokcdn-us.com` are fine but not `v16-webapp-prime.us.tiktok.com`

**Comment by TonyRL** [comment]
/test
```routes
/tiktok/user/@iyakhyar0v
```

**Comment by TonyRL** [comment]
All videos are now returning `v16m-webapp.tiktokcdn-us.com`

**Comment by hardik-lolly** [comment]
Looks like videos from v16m-webapp.tiktokcdn-us.com are fine but not v16-webapp-prime.us.tiktok.com

I am getting same issue, getting few videos with webapp-prime.us.tiktok.com url. How did you solve this?

**Comment by wik3d** [comment]
> Looks like videos from v16m-webapp.tiktokcdn-us.com are fine but not v16-webapp-prime.us.tiktok.com
> 
> I am getting same issue, getting few videos with webapp-prime.us.tiktok.com url. How did you solve this?

I am also having this issue

**Comment by backwards221** [comment]
@hardik-lolly @wik3d All videos now are from v16-webapp-prime.tiktok.com now. Were you able to solve this?

**Comment by jcmag** [comment]
> All videos are now returning `v16m-webapp.tiktokcdn-us.com`

what is this issue closed? the problem is still active...

**Comment by tuanvn91** [comment]
is this issue fixed ?
