### ISSUE TITLE
抖音 douyin 博主路由报错

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#11466]
### 路由地址

```routes
/douyin/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/douyin/user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN-1eBcPqao
```

### 相关文档

https://docs.rsshub.app/social-media.html#dou-yin-bo-zhu

### 预期是什么？

正常显示RSS条目

### 实际发生了什么？

报错，无法获取RSS项目。

官方demo出错示例：
![image](https://user-images.githubusercontent.com/3047708/208268884-82e023ac-0d7e-44b2-844e-52e2cd4ebba7.png)

自建出错示例：
![image](https://user-images.githubusercontent.com/3047708/208268896-12b6d8a8-9679-4c61-a766-4c8027c22b7d.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Path: /user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN-1eBcPqao
Node version: v16.18.0
Git Hash: 6624c1c

另外，最近一次还能用是12月15日，当时还在用dc51f25be这个commit，不知道是之后RSSHub更新导致还是抖音官方改动了导致现在的出错。

请尽快修复一下吧，挺需要的，辛苦，谢谢啦~
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/douyin/user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN-1eBcPqao
```

**Comment by Rongronggg9** [comment]
Unable to reproduce the issue on my personal instance. Your IP may be banned.

![](https://user-images.githubusercontent.com/15956627/208282184-458e9731-e430-4ba7-b2ca-ad50fa242d83.png)

**Comment by ruleroller** [comment]
Hmmm. 我尝试了另一个不太用（大约2个月前才用过）的机器上跑，也同样是这样的问题。另一个，两台机器上，抖音的直播路由/douyin/live，至今都是可用的。

如果ban掉的话，live路由应该也用不了的吧…… 当然，如果user路由和live路由没有关联的话，那就另当别论了。

或许我的两台机器的ip都被ban掉了。

**Comment by shaderein** [comment]
Having the same issue on my end. The user profile is protected by captcha, which can be solved if cookies are passed in.

**Comment by Rongronggg9** [comment]
> 我尝试了另一个不太用（大约2个月前才用过）的机器上跑

IP from outside of mainland China or IP owned by cloud hosting providers could be banned unconditionally.

> 如果ban掉的话，live路由应该也用不了的吧……

n

> 当然，如果user路由和live路由没有关联的话，那就另当别论了。

y

**Comment by week12** [comment]
Having the same issue

**Comment by week12** [comment]
> > 我尝试了另一个不太用（大约2个月前才用过）的机器上跑
> 
> IP from outside of mainland China or IP owned by cloud hosting providers could be banned unconditionally.
> 
> > 如果ban掉的话，live路由应该也用不了的吧……
> 
> n
> 
> > 当然，如果user路由和live路由没有关联的话，那就另当别论了。
> 
> y

I get the page with curl and the file is also normal. My rsshub is running on a cloud server in Seoul.
So, may be the reason  is not that IP is banned? I don't known.
![1671431917220](https://user-images.githubusercontent.com/38879375/208363302-4f57718a-7f9f-40db-81ba-a0dcf62ef3eb.jpg)
![image](https://user-images.githubusercontent.com/38879375/208363403-caab9131-c7dd-4efe-b344-45f43728b146.png)

**Comment by ruleroller** [comment]
我也再次在两台机子上按照楼上老哥的方法测试了一下，也都是和楼上一样的效果。能ping通，也可用curl获取到网页文件，能看到页面里的文本内容（例如视频的标题等），就是不知道，这样测试是否被屏蔽的方法够不够准确。技术菜，我也不会用别的方式测试了，抱歉。

**Comment by Rongronggg9** [comment]
It seems that only requests from browsers (the fingerprint is UA) will be filtered by WAF. Interesting behavior. Non-browser requests may be unconditionally considered to be from search engine spiders and get whitelisted. I will investigate later!

A browser UA leads to WAF filtering:

```sh 
curl -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' https://www.douyin.com/user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN
```
