### ISSUE TITLE
[CI] Shield Github Workflow 链接需要迁移

### ISSUE THREAD

**Issue by SettingDust** [DIYgod/RSSHub#11469]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

正确显示 CI 状态

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/19922286/208338551-2cd07d6b-4282-4f30-9884-0291fe9aff67.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://github.com/badges/shields/issues/8671
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/pull/11457

Please clear your browser cache
