### ISSUE TITLE
部分用户「推特媒体时间线」RSS地址报错

### ISSUE THREAD

**Issue by li0817** [DIYgod/RSSHub#11479]
### 路由地址

```routes
/twitter/media/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/media/ttk_genshin
/twitter/media/mapi_hoyo36
/twitter/media/MitMin3525
/twitter/media/H1iR0nnn
/twitter/media/AOIkanzume
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

正常显示RSS内容

### 实际发生了什么？

推特用户的媒体时间线RSS地址报错
（不是所有用户都报错，只是部分的推特用户会报错）
![image](https://user-images.githubusercontent.com/27659768/208630135-1dd7d4b6-172b-44e5-9d5b-9ab83b2405f2.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: Cannot read properties of undefined (reading 'legacy')
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by li0817** [comment]
怎么自动关闭issue了，我填错路由了吗

**Comment by li0817** [comment]
> 怎么自动关闭issue了，我填错路由了吗

可能是没填参数的原因吧，改了一下路由地址；
不过该怎么留下评论以便供人重新审核啊，@某个人吗，还是就这样随便评论下就可以了……

**Comment by Felix2yu** [comment]
我也碰到了，而且有的是自建也报这个错，但是用官方的`rsshub.app`却可以，比如`/twitter/media/FSQR91`（内含成人内容）
