### ISSUE TITLE
B站 UP主投稿异常

### ISSUE THREAD

**Issue by WilliamK7** [DIYgod/RSSHub#11500]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### 预期是什么？

返回XML文件

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/82304956/209490872-c8efac9f-dc1c-4689-97df-c06a8f14f5d0.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Path: /bilibili/user/video/2267573
Node version: v16.19.0
Git Hash: a69dfac
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by TonyRL** [comment]
Due to the anti-crawling policy implemented by certain websites, some RSS routes provided by the demo instance will return 403 or empty.
