### ISSUE TITLE
求位大佬添加华南理工教务以及学院通知的RSS

### ISSUE THREAD

**Issue by daxiang123456** [DIYgod/RSSHub#1150]
如上！本人能力有限QAQ

**Comment by daxiang123456** [comment]
地址：http://jwc.scuteo.com/jiaowuchu/cms/category/index.do?id=f25701314e90988c014e90ad57500004
          http://jwc.scuteo.com/jiaowuchu/cms/category/index.do?id=8a8a8a5d4ed27047014ed2729a770000

**Comment by SettingDust** [comment]
@daxiang123456 模板 请

**Comment by daxiang123456** [comment]
> @daxiang123456 模板 请

什么模板？

**Comment by HenryQW** [comment]
除非是用的移动版，不然的话，https://github.com/DIYgod/RSSHub/issues/new/choose

![image](https://user-images.githubusercontent.com/5896343/48481605-1be15480-e806-11e8-8ca0-2d3b2df4fd32.png)

**Comment by daxiang123456** [comment]
### 源站地址
http://jwc.scuteo.com/jiaowuchu/cms/category/index.do?id=f25701314e90988c014e90ad57500004
http://jwc.scuteo.com/jiaowuchu/cms/category/index.do?id=8a8a8a5d4ed27047014ed2729a770000
### 需要生成什么内容？
内容一：可以收到教务更新的通知
额外描述
能带上标题就好！

**Comment by HenryQW** [comment]
@xyqfer 这是你的学长，他说如果你是妹子就帮你做

**Comment by xyqfer** [comment]
囧。。

**Comment by daxiang123456** [comment]
女装行吗QAQ

**Comment by HenryQW** [comment]
@daxiang123456 他就爱女装

**Comment by xyqfer** [comment]
女装请右转 @DIYgod

**Comment by daxiang123456** [comment]
......真要女装啊

**Comment by DIYgod** [comment]
@daxiang123456 请 https://github.com/komeiji-satori/Dress

**Comment by daxiang123456** [comment]
> @daxiang123456 请 https://github.com/komeiji-satori/Dress

请问安装axios进行到
C:\Users\65768>npm install --save axios vue-axios
npm WARN vue-axios@2.1.4 requires a peer of vue@>= 1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN 65768@1.0.0 No description
npm WARN 65768@1.0.0 No repository field.

+ axios@1.0.0
+ vue-axios@2.1.4
这一步后该做些啥..

**Comment by daxiang123456** [comment]
> @daxiang123456 他就爱女装



> 女装请右转 @DIYgod

求助！

**Comment by xyqfer** [comment]
https://docs.rsshub.app/install/

**Comment by DIYgod** [comment]
Done.
