### ISSUE TITLE
Issue with IKEA New Products

### ISSUE THREAD

**Issue by AlastairDewar** [DIYgod/RSSHub#11563]
### Routes

```routes
/ikea/uk/new
```

### Full routes

```fullroutes
/ikea/uk/new
```

### Related documentation

https://docs.rsshub.app/en/shopping.html#ikea

### What is expected?

An RSS Feed is to be generated.

### What is actually happening?

A 400 Bad Request is being returned on both the demo and self-hosted versions.

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Node version: v16.19.0, Git Hash: 729a16c

### Additional info

```shell
It may be due to the redirect to https://www.ikea.com/gb/en/new/ or a change in the page structure.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by AlastairDewar** [comment]
@HenryQW

**Comment by HenryQW** [comment]
Most likely they've updated the their APIs, I'm afraid that I don't have the time to update the route.
