### ISSUE TITLE
什么值得买-好文分类，订阅地址404

### ISSUE THREAD

**Issue by skefy** [DIYgod/RSSHub#11567]
### 路由地址

```routes
/smzdm/haowen/fenlei/:name/:sort?
```

### 完整路由地址

```fullroutes
/smzdm/haowen/fenlei/touyingshebei/
```

### 相关文档

https://docs.rsshub.app/shopping.html#shen-me-zhi-de-mai

### 预期是什么？

值得买的好文分类url发生更新，之前的url会404. 

之前的 ：llink = `https://post.smzdm.com/fenlei/${name}/`;

改之后应该是：link = `https://www.smzdm.com/fenlei/${name}/post/` ， 例如：https://www.smzdm.com/fenlei/touyingshebei/post/

### 实际发生了什么？

如上

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
```sh
$ curl -I https://post.smzdm.com/fenlei/touyingshebei/
HTTP/1.1 200 OK
Server: TencentWAF
Date: Sun, 08 Jan 2023 15:26:37 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: __ckguid=***; Max-Age=31536000; Domain=smzdm.com; Path=/; HttpOnly
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Zhi-Request-Id: ***
Cache-Control: max-age=60
S-D-S: 0.001
```
