### ISSUE TITLE
🔴「虎嗅网」首页资讯，RSS 失效

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#11565]
### 路由地址

```routes
/huxiu/article
```

### 完整路由地址

```fullroutes
https://rsshub.app/huxiu/article
```

### 相关文档

https://docs.rsshub.app/new-media.html#hu-xiu-shou-ye-zi-xun

### 预期是什么？

- 「虎嗅网」首页资讯，RSS 失效

- [Error in RSSHub!](https://rsshub.app/huxiu/article)

### 实际发生了什么？

- 「官方部署」和「自建」均出现报错

- [Error in RSSHub!](https://rsshub.app/huxiu/article)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v16.19.0 Git Hash: 729a16c

### 额外信息

```shell
Looks like something went wrong

Route requested: /article
Error message: Hostname/IP does not match certificate's altnames: Host: www.huxiu.com. is not in the cert's altnames: DNS:*.huxiucdn.com, DNS:huxiucdn.com: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /article
Node version: v16.19.0
Git Hash: 729a16c
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/huxiu/article
```
