### ISSUE TITLE
即刻主题的description多了用户昵称无用字段，应去掉

### ISSUE THREAD

**Issue by susumr** [DIYgod/RSSHub#11589]
### 路由地址

```routes
/jike/topic/:id
```

### 完整路由地址

```fullroutes
/jike/topic/556688fae4b00c57d9dd46ee
```

### 相关文档

https://docs.rsshub.app/social-media.html#ji-ke

### 预期是什么？

description中正常显示内容

### 实际发生了什么？

description中前部分多出了用户昵称、Username字段，内容显示在后面。应该去掉用户昵称、Username字段。
 
如，/jike/topic/556688fae4b00c57d9dd46ee
description 应该去掉“<span>用户昵称：CaGe_ <br> Username：FF8BD551-1F08-440A-8428-7B120E3A3BB9</span>”

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by prnake** [comment]
感觉确实是多余字段
