### ISSUE TITLE
Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by lanlanwa** [DIYgod/RSSHub#11590]
### 路由地址

```routes
/twitter/user/SaveYourPrimos
```

### 完整路由地址

```fullroutes
/twitter/user/SaveYourPrimos
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

正常获取RSS订阅信息

### 实际发生了什么？

Route requested: /user/SaveYourPrimos
Error message: Cannot read properties of undefined (reading 'user')
Helpful Information to provide when opening issue:
Path: /user/SaveYourPrimos
Node version: v16.19.0
Git Hash: ab2f618

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /user/SaveYourPrimos
Error message: Cannot read properties of undefined (reading 'user')
Helpful Information to provide when opening issue:
Path: /user/SaveYourPrimos
Node version: v16.19.0
Git Hash: ab2f618
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lanlanwa** [comment]
这样提BUG不行吗...

**Comment by lanlanwa** [comment]
@TonyRL 我看您解决过类似问题,可以帮忙看一下吗

**Comment by TonyRL** [comment]
/test
```routes
/twitter/user/SaveYourPrimos
```
