### ISSUE TITLE
希望能实现支持DISCUZ的论坛的内容

### ISSUE THREAD

**Issue by han963xiao** [DIYgod/RSSHub#116]

**Comment by zgq354** [comment]
Discuz本身是有RSS输出的
/forum.php?mod=rss&fid=版块id&auth=用户的key
版块右上角有专属的订阅链接
![image](https://user-images.githubusercontent.com/9024954/40030169-a503c4c6-581b-11e8-8a76-2b836fc4ed32.png)

**Comment by lolstudio** [comment]
discuz的论坛某些板块没有‘订阅’这个按钮，这个有解决办法么？

**Comment by DIYgod** [comment]
超时，issue 暂时关闭
