### ISSUE TITLE
希望优化91porn 能订阅作者个人

### ISSUE THREAD

**Issue by zhibo12** [DIYgod/RSSHub#11649]
### 这是一个什么样的功能？

如题

#6859

### 这个功能可以解决什么问题？

如题

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by zhibo12** [comment]
已存在的不支持个人

这不是提要URL。但我在这个页面上找到了一些：
RSS - 20个最新视频：https://91porn.com/rss/new/
RSS - 20个观看次数最多的视频：https://91porn.com/rss/views/
RSS - 20个评论最多的视频：https://91porn.com/rss/comments/
把订阅的确切链接发给我。

**Comment by TonyRL** [comment]
Please search the docs https://docs.rsshub.app

**Comment by TonyRL** [comment]
Duplicate of #1630
