### ISSUE TITLE
希望能增加 twitch 的直播开下?播提醒。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#1164]
### 这是一个什么样的功能？
主播开播或者下播时，能生成对应的RSS条目。

### 这个功能可以解决什么问题？
可以更方便地关注自己喜欢的twitch主播的直播动态。

### 额外描述
开播是强烈需求的，如果有下播提醒，那更是锦上添花，多谢。

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
