### ISSUE TITLE
微信公众号Feeddd错误

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#11671]
### 路由地址

```routes
/wechat/feeddd/:id
```

### 完整路由地址

```fullroutes
/wechat/feeddd/613381fa1269c358aa0eadb1
```

### 相关文档

https://docs.rsshub.app/new-media.html#wei-xin-gong-zhong-hao-feeddd-lai-yuan

### 预期是什么？

像其他Feeddd订阅源一样正常使用

### 实际发生了什么？

Looks like something went wrong
Route requested: /feeddd/613381fa1269c358aa0eadb1
Error message: wechat-mp: URL host must be "mp.weixin.qq.com", but got http://www.infzm.com/content/240769?from=nfzmwx
Helpful Information to provide when opening issue:
Path: /feeddd/613381fa1269c358aa0eadb1
Node version: v16.19.0
Git Hash: 7e6fbdb

### 部署

自建

### 部署相关信息

OS:Linux, Node:v16.19.0, Docker:v20.10.21

### 额外信息

```shell
正如实际发生所报错。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/wechat/feeddd/613381fa1269c358aa0eadb1
```
