### ISSUE TITLE
品玩用户动态获取全文失效

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#11709]
### 路由地址

```routes
/pingwest/user/:uid/:type?
```

### 完整路由地址

```fullroutes
https://rsshub.app/pingwest/user/7781550877/article
```

### 相关文档

https://docs.rsshub.app/new-media.html#pin-wan

### 预期是什么？

全文输出

### 实际发生了什么？

只抓去摘要

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/blob/304c84a0d12ace7368770294480db539da5c4878/lib/routes/pingwest/user.js#L36-L43
https://github.com/DIYgod/RSSHub/blob/304c84a0d12ace7368770294480db539da5c4878/lib/routes/pingwest/utils.js#L30-L51
This route is expected to return the article list and it's working fine

**Comment by TonyRL** [comment]
As said before
> https://github.com/DIYgod/RSSHub/blob/304c84a0d12ace7368770294480db539da5c4878/lib/routes/pingwest/user.js#L36-L43
> https://github.com/DIYgod/RSSHub/blob/304c84a0d12ace7368770294480db539da5c4878/lib/routes/pingwest/utils.js#L30-L51
> This route is expected to return the article list and it's working fine

The route is expected to return the article list from the API but **not the full article**. This is **not a bug**.
