### ISSUE TITLE
微博携带refer请求

### ISSUE THREAD

**Issue by W4J1e** [DIYgod/RSSHub#11716]
### 这是一个什么样的功能？

在更新微博路由的时候携带 refer 以便能正常显示图片。

### 这个功能可以解决什么问题？

由于 rsshub 默认不发送 refer ，加上现在微博禁止空 refer 访问图片资源，估计是有些人滥用微博当图床导致，空 refer 请求微博图片会返回 403。
可以解决当前微博路由无法显示图片的问题。

### 额外描述

文档里提到的 image_hotlink_template 未免有些复杂
，所以是否可以考虑通过该路由的 :routeParams? 实现携带 refer 或者默认携带？

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by ttxhxz** [comment]
请问一下这个特性是做完了吗？我在更新日志里面好像没搜到这个编号的提交？我拉取了最新的RSSHUB也无法显示微博图片，我使用的是ttrss

**Comment by W4J1e** [comment]
@ttxhxz 没有更新，感觉应该也没人关注。
但是我找到了两个可以正常显示微博图片的 rss 阅读器，一个是 ego reader ，一个是开源的 readyou 。目前尚未深入了解这两个 app 有没有针对微博的 referer 做特殊处理。

**Comment by ttxhxz** [comment]
@W4J1e 最近看微博都没图了，太难了。上面说的两个阅读器我也去看看，感谢
