### ISSUE TITLE
`/bilibili/user/video` Broken for Some Uploaders

### ISSUE THREAD

**Issue by JasonHK** [DIYgod/RSSHub#11720]
### Routes

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### Full routes

```fullroutes
/user/video/11783021
```

### Related documentation

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### What is expected?

Should be working without any errors.

### What is actually happening?

```
Error message: Cannot read properties of undefined (reading 'name')
```

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

PikaPods, Node version: v16.19.0, Git Hash: 7e6fbdb

### Additional info

```shell
N/A
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by AlieZVzz** [comment]
same error
<img width="1001" alt="图片" src="https://user-images.githubusercontent.com/47358078/217405068-5ca73e76-0848-4959-88ad-8d2770dd303b.png">

**Comment by JasonHK** [comment]
> same error
> <img width="1001" alt="图片" src="https://user-images.githubusercontent.com/47358078/217405068-5ca73e76-0848-4959-88ad-8d2770dd303b.png">
> 

@AlieZVzz This is not the same. Are you using the demo instance? If so, self-host will likely solve your problem.

**Comment by AlieZVzz** [comment]
got it:)

**Comment by curly210102** [comment]
@JasonHK Is the user 11783021 exist in bilibili? I've try to open https://space.bilibili.com/11783021, but return an empty page.
