### ISSUE TITLE
添加pixiv排行榜关键词筛选

### ISSUE THREAD

**Issue by Kevin6872** [DIYgod/RSSHub#11733]
### 这是一个什么样的功能？

筛选pixiv排行榜作品下的关键词，可按黑名单和白名单筛选

### 这个功能可以解决什么问题？

按喜好使用黑名单和白名单筛选pixiv排行榜作品

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/parameter.html
