### ISSUE TITLE
百度贴吧的rss不能用了

### ISSUE THREAD

**Issue by jingxingx** [DIYgod/RSSHub#11766]
### 路由地址

```routes
/baidu/tieba/forum/:kw
```

### 完整路由地址

```fullroutes
baidu/tieba/forum/酱香白酒吧
```

### 相关文档

https://docs.rsshub.app/bbs.html#bai-du-tie-ba

### 预期是什么？

能够展示rss xml

### 实际发生了什么？

Looks like something went wrong
Route requested: /baidu/tieba/forum/%E9%85%B1%E9%A6%99%E7%99%BD%E9%85%92%E5%90%A7
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /baidu/tieba/forum/%E9%85%B1%E9%A6%99%E7%99%BD%E9%85%92%E5%90%A7
Node version: v14.18.1
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=&template=bug_report.md)
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=&template=bug_report.md)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /baidu/tieba/forum/%E9%85%B1%E9%A6%99%E7%99%BD%E9%85%92%E5%90%A7
Node version: v14.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/baidu/tieba/forum/酱香白酒吧
```

**Comment by TonyRL** [comment]
This is not what demo instance returned. Demo instance runs on node v16.19.0 as of replying.
