### ISSUE TITLE
希望添加 无垠 的博客的 rss

### ISSUE THREAD

**Issue by a180285** [DIYgod/RSSHub#11762]
### 类型

编程

### 网站地址

https://flyhigher.top/

### 网站描述

应该是 无垠 的博客，看上去是一个技术类的

### 需要生成什么内容？

博客文章

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by SkysCrystal** [comment]
这个博客自带 [rss](https://flyhigher.top/rss) 订阅

**Comment by a180285** [comment]
@SkysCrystal 感谢。

我上次没找到，因为看 RSSHub Radar 也没提示，就以为这个网站，没有。

很奇怪，为啥 RSSHub Radar 没有检测到呢，我刚也看了一下，确实在网页底部就有订阅。
