### ISSUE TITLE
Picuki的RSS订阅地址失效

### ISSUE THREAD

**Issue by li0817** [DIYgod/RSSHub#11769]
### 路由地址

```routes
/picuki/profile/:id/:functionalFlag?
```

### 完整路由地址

```fullroutes
/picuki/profile/maple.tofu
```

### 相关文档

https://docs.rsshub.app/social-media.html#picuki

### 预期是什么？

成功显示RSS订阅消息页面

### 实际发生了什么？

显示路由不存在
![image](https://user-images.githubusercontent.com/27659768/216788190-ac4e81e4-4d93-48d7-aa3f-ca67ecaff0e0.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: this route is empty, please check the original site or create an issue
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/picuki/profile/maple.tofu
```

**Comment by TonyRL** [comment]
Duplicate of #11673

**Comment by li0817** [comment]
虽然本issue关闭了，但没太明白，既然将bug的标签换成了反爬，是不是说明这并非一个BUG，所以无需修复；
而从关联的issue来看，是说只能用自建来解决？
