### ISSUE TITLE
希望增加百度风云榜

### ISSUE THREAD

**Issue by Specher** [DIYgod/RSSHub#1177]
### 源站地址
http://top.baidu.com/buzz?b=1

### 需要生成什么内容？

- [ ] 百度风云榜
百度风云榜可以利用手机版网页抓取数据：http://top.baidu.com/m
实时热点json数据地址：http://top.baidu.com/mobile_v2/buzz?b=1&c=515
今日热点：http://top.baidu.com/mobile_v2/buzz?b=561&c=515
体育热点：http://top.baidu.com/mobile_v2/buzz?b=534&c=515

### 额外描述

这些都是非常好的数据源，实时更新的，但由于本人不懂node.js，只会Java，然后自学了一点php。
希望大佬能帮忙写个这一类的范例，如果我能看懂的话可以帮忙写出其他类似的热搜榜，比如谷歌趋势、搜狗热搜、360热搜等。

**Comment by HenryQW** [comment]
@Specher 这个刷新频率貌似很高的样子？

**Comment by Specher** [comment]
> @Specher 这个刷新频率貌似很高的样子？

“实时热点”榜单，每1~2小时更新1次。其它榜单，根据24小时前的搜索量统计并计算生成，每一天至少更新一次，上榜词变化大时可能一天不定时多次更新。
