### ISSUE TITLE
blockbeats RSS订阅返回错误

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#11771]
### 路由地址

```routes
/blockbeats/:channel?
```

### 完整路由地址

```fullroutes
/blockbeats/news
```

### 相关文档

https://docs.rsshub.app/new-media.html#lu-dong

### 预期是什么？

订阅成功

### 实际发生了什么？

订阅失败

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /blockbeats/news
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /blockbeats/news
Node version: v16.19.0
Git Hash: 6bed7cb
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lylunula** [comment]
看起来是在修复了么？https://github.com/DIYgod/RSSHub/pull/11713

**Comment by Fatpandac** [comment]
是的
