### ISSUE TITLE
知乎虎山行不行的动态 源更新错误 但其他知乎答主更新正常 请问如何能解决

### ISSUE THREAD

**Issue by GarlicChocolate** [DIYgod/RSSHub#11804]
### Category

Social Media

### Website URL

https://rsshub.app/zhihu/people/activities/asura-3-28

### Website description

目前红字显示 There are issues with this feed. Please check it and resubscribe if necessary. 
点开后ERROR： A feed could not be found at https://rsshub.app/zhihu/people/activities/asura-3-28. This does not appear to be a valid RSS or Atom feed.

### What content should be included?

就正常更新 目前五天的动态都抓不过来 如能帮忙解决或指导解决 万分感谢

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
This is not a new RSS proposal
