### ISSUE TITLE
联合早报时间获取方式失效

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#11802]
### 路由地址

```routes
/zaobao/realtime/:section?
/zaobao/znews/:section?
```

### 完整路由地址

```fullroutes
/zaobao/realtime/:section?
/zaobao/znews/:section?
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#lian-he-zao-bao

### 预期是什么？

请求返回文章时间. 

### 实际发生了什么？

请求不含时间. 对源代码:
https://github.com/DIYgod/RSSHub/blob/26cb04c1393119c6ec291451dbbd79c54f581e0a/lib/v2/zaobao/util.js#L93-L98
分析显示`time`变量一直为空. 
国内与国际版都有这样的问题. 

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
国际版下可使用:
```
new Date(JSON.parse($("head > script:nth-child(77)").text())["@graph"][0]["dateModified"])
```

**Comment by shunf4** [comment]
> 国际版下可使用:
> 
> ```
> new Date(JSON.parse($("head > script:nth-child(77)").text())["@graph"][0]["dateModified"])
> ```

这么复杂，有没有更通用一点的？

**Comment by dzx-dzx** [comment]
我又研究了下, 这样应该也可以L
```
 new Date($("meta[property='og:updated_time']").attr('content'))
```
不过需要调整下时区.

**Comment by dzx-dzx** [comment]
> 我又研究了下, 这样应该也可以:
> 
> ```
>  new Date($("meta[property='og:updated_time']").attr('content'))
> ```
> 
> 不过需要调整下时区.

em不能用于国内版。

**Comment by dzx-dzx** [comment]
```
new Date(JSON.parse($("head script[type='application/ld+json']").text())["@graph"][0]["dateModified"]) 
```
与
```
new Date(Number((JSON.parse($("head script[type='application/json']").text()))["articleDetails"]["created"])*1000)
```
也可以。@shunf4
