### ISSUE TITLE
instagram登录失败

### ISSUE THREAD

**Issue by musicyy** [DIYgod/RSSHub#11816]
### 路由地址

```routes
/instagram/:category/:key
```

### 完整路由地址

```fullroutes
/instagram/user/xxxx
```

### 相关文档

https://docs.rsshub.app/social-media.html#telegram

### 预期是什么？

获取Instagram用户时间线

### 实际发生了什么？

在docker中部署，参数-e IG_USERNAME=xxxx@gmail.com -e IG_PASSWORD=xxxxxxx -e CACHE_EXPIRE=600

Looks like something went wrong
Route requested: /instagram/user/yua_mikami
Error message: GET /api/v1/users/search/?timezone_offset=28800&q=xxxx&count=30 - 401 Unauthorized; Please wait a few minutes before you try again.
Helpful Information to provide when opening issue:
Path: /instagram/user/yua_mikami
Node version: v16.19.0
Git Hash: 7c56e2a

### 部署

自建

### 部署相关信息

OS:Debian 10,Docker:20.10.23

### 额外信息

```shell
docker log:
error: Instagram error: IgResponseError: GET /api/v1/users/search/?timezone_offset=28800&q=xxxx&count=30 - 401 Unauthorized; Please wait a few minutes before you try again.
error: Error in /instagram/user/yua_mikami: GET /api/v1/users/search/?timezone_offset=28800&q=xxxx&count=30 - 401 Unauthorized; Please wait a few minutes before you try again.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by musicyy** [comment]
路由地址：
/instagram/:category/:key
完整路由地址：
/instagram/user/xxxx

**Comment by musicyy** [comment]
用docker部署无法获取，本机部署可以获取，不知道哪里出了问题

**Comment by TonyRL** [comment]
Can you try login in using your Instagram username instead of email?
