### ISSUE TITLE
阻止正在使用的不变内容缓存过期

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1182]
### 这是一个什么样的功能？

每次获取不变内容（比如全文内容）时更新缓存过期时间，阻止正在使用的不变内容缓存过期

### 这个功能可以解决什么问题？

减少请求，优化性能

### 额外描述

实现：

- lru-cache: 使用 updateAgeOnGet 参数

- redis-cache: 使用 EXPIRE 命令

**Comment by HenryQW** [comment]
没搜到`updateAgeOnGet`相关使用例子，按照我的理解是需要限制最长缓存时间了，否则有可能会导致更新延迟。比如知乎日报设置24小时缓存，第23小时59分59秒有人访问，导致缓存过期时间被重置，这样要等到第47小时59分59秒才刷新。

**Comment by DIYgod** [comment]
@HenryQW 只对不变内容用啊，这些内容不会更新，就不会有更新延迟的问题

**Comment by HenryQW** [comment]
那 lru 就是加
```js
updateAgeOnGet: true
```
到这里
https://github.com/DIYgod/RSSHub/blob/c7961a241e78af6d89202b258a0f3d915e965745/lib/middleware/lru-cache.js#L17

redis 好像改动就多一点
