### ISSUE TITLE
信報即時新聞

### ISSUE THREAD

**Issue by mm2li** [DIYgod/RSSHub#11823]
### 类型

金融

### 网站地址

https://www2.hkej.com/instantnews

### 网站描述

財經新聞

### 需要生成什么内容？

所有即時新聞

### 额外描述

現有的信報RSS用不了
謝謝!!

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
/test
```routes
/hkej
```

**Comment by TonyRL** [comment]
It works
