### ISSUE TITLE
金十数据

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#11820]
### 路由地址

```routes
/jin10/:important?
```

### 完整路由地址

```fullroutes
/jin10/1
```

### 相关文档

https://docs.rsshub.app/finance.html#jin-shi-shu-ju

### 预期是什么？

正常使用

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/113758409/217840528-c06dfbbf-7123-4e9d-a62a-4d23a62b2110.png)
无法使用

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /
Error message: Cannot read properties of undefined (reading 'match')
Helpful Information to provide when opening issue:
Path: /
Node version: v16.19.0
Git Hash: 49c369b
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
https://github.com/DIYgod/RSSHub/issues/11812#issuecomment-1424252960

**Comment by TonyRL** [comment]
/test
```routes
/jin10/1
```

**Comment by TonyRL** [comment]
It works
