### ISSUE TITLE
The Economist 经济学人 失效

### ISSUE THREAD

**Issue by aturret** [DIYgod/RSSHub#11824]
### 路由地址

```routes
/economist/:endpoint
```

### 完整路由地址

```fullroutes
/economist/latest
```

### 相关文档

https://docs.rsshub.app/en/traditional-media.html#the-economist

### 预期是什么？

能够抓取

### 实际发生了什么？

报错，没有抓取
Error message: Status code 403

演示：
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

自建

### 额外信息

```shell
自建和演示都出现了同样的错误
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by aturret** [comment]
今天早上自建的突然恢复了一阵，而演示依然失效。看来是反爬严格爬取随缘了。

**Comment by TonyRL** [comment]
/test
```routes
/economist/latest
```
