### ISSUE TITLE
/mastodon/acct: Get the feed directly from the acct's instance, configuration-free

### ISSUE THREAD

**Issue by notofoe** [DIYgod/RSSHub#11836]
### What feature is it?

For Mastodon instances with deployment version 4.0.0 or above, calling the `search` API no longer requires a user access token by default, so when fetching a user's tweet, RSSHub may now first try to call the `search` API of the instance they are on, get the user ID, and then fetch posts directly from that instance, possibly eliminating the need to fetch on other instance given by RSSHub provider.

For example, to fetch posts from [@CatWhitney@mastodon.social](https://mastodon.social/@CatWhitney), if https://mastodon.social is deployed with version 4.0.0 or above, RSSHub can now fetch them directly from https://mastodon.social. Fetching posts from the instance given by RSSHub provider may be not necessary. 

### What problem does this feature solve?

If some users are on a newer version of Mastodon's instance, fetching posts from these users via the route `/mastodon/acct/:acct/statuses/:only_media?` no longer requires additional configuration of the RSSHub.

### Additional description

For backward compatibility, the original query mechanism must remain in place as a failback. The server where the queried user is on does not have to be Mastodon.

Links to check: 
 - <https://docs.joinmastodon.org/methods/search/>
 - <https://docs-develop.pleroma.social/backend/development/API/differences_in_mastoapi_responses/>

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by myl7** [comment]
Sorry for the bothering! I wrongly included the issue slug in the commit message.
