### ISSUE TITLE
GOCN的路由挂了

### ISSUE THREAD

**Issue by hapihacking** [DIYgod/RSSHub#11845]
### 路由地址

```routes
https://rsshub.app/gocn
```

### 完整路由地址

```fullroutes
https://rsshub.app/gocn
```

### 相关文档

https://docs.rsshub.app/programming.html#gocn

### 预期是什么？

目前无法执行，应该是网站又又又改版导致的

### 实际发生了什么？

Error message: Cannot read properties of null (reading 'map')

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
🈚️
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
> Cannot read properties of null (reading 'map')
This error is caused by https://gocn.vip/
