### ISSUE TITLE
Annual Reviews 系列期刊

### ISSUE THREAD

**Issue by skymagician** [DIYgod/RSSHub#11861]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/11861)

### Category

Scientific Journal

### Website URL

https://www.annualreviews.org/action/showPublications

### Website description

Annual Reviews 系列期刊

### What content should be included?

最新一期的目录、摘要、标题、作者、日期。

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/25891462?v=4' alt='skymagician' width=24 height=24> skymagician](https://issuehunt.io/u/skymagician) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by bigfei** [comment]
thanks for your contribution, I find the annualreviews provides a bunch of [RSS feeds](https://www.annualreviews.org/page/about/rssfeeds) on their page, you can even import the OPML onto your RSS feed reader.

**Comment by skymagician** [comment]
> thanks for your contribution, I find the annualreviews provides a bunch of [RSS feeds](https://www.annualreviews.org/page/about/rssfeeds) on their page, you can even import the OPML onto your RSS feed reader.

I knew, but those official RSS feeds do not provide abstract, just titles.
