### ISSUE TITLE
【知乎】用户动态 diygod 正常，其他报错 Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#11868]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/zhihu/people/activities/diygod
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常工作

### 实际发生了什么？

用户动态 diygod 正常，其他报错 Response code 403 (Forbidden)

举例子

报错 https://rsshub.app/zhihu/people/activities/xu-wu-gui-21-43

正常 https://rsshub.app/zhihu/people/activities/diygod

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /people/activities/xu-wu-gui-21-43
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /people/activities/xu-wu-gui-21-43
Node version: v16.19.0
Git Hash: 2e5df2a
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/xu-wu-gui-21-43
```

**Comment by TonyRL** [comment]
It works!
