### ISSUE TITLE
36氪

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#11887]
### 类型

新媒体

### 网站地址

https://36kr.com/

### 网站描述

中国知名商业网

### 需要生成什么内容？

24小时热榜：

![image](https://user-images.githubusercontent.com/113758409/219350331-e0cbc09a-6156-48e8-a614-21ae5c280c91.png)

https://36kr.com/hot-list/catalog
人气榜：
综合榜：
收藏榜：

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by YiweiShen** [comment]
已经存在：https://docs.rsshub.app/new-media.html#_36kr
