### ISSUE TITLE
Picuki 失效 localhost正常運行 rsshub部署顯示 this route is empty

### ISSUE THREAD

**Issue by jameshih** [DIYgod/RSSHub#11883]
### 路由地址

```routes
/picuki/profile/:id/:functionalFlag?
```

### 完整路由地址

```fullroutes
https://rsshub.app/picuki/profile/stefaniejoosten
```

### 相关文档

https://docs.rsshub.app/social-media.html#picuki

### 预期是什么？

能夠抓取

### 实际发生了什么？

無法抓取
Error message: this route is empty

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: this route is empty
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/picuki/profile/stefaniejoosten
```

**Comment by TonyRL** [comment]
> Requests from public demo might be filtered by WAF. Deploy yours plz.

_Originally posted by Rongronggg9 in https://github.com/DIYgod/RSSHub/issues/11661#issuecomment-1398629646_
