### ISSUE TITLE
少数派

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#11888]
### 类型

新媒体

### 网站地址

https://sspai.com/

### 网站描述

高效工作，品质生活

### 需要生成什么内容？

最热：

![image](https://user-images.githubusercontent.com/113758409/219352837-22578976-b5bf-43fa-b7e8-47d5f763b0bb.png)

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/new-media.html#shao-shu-pai-sspai

**Comment by sin572** [comment]
> https://docs.rsshub.app/new-media.html#shao-shu-pai-sspai

请问现有的rss少数派，如何使用最热的功能？首页的rss并没有参数

**Comment by TonyRL** [comment]
/test
```routes
/sspai/tag/热门文章
``

**Comment by TonyRL** [comment]
/test
```routes
/sspai/tag/热门文章
```
