### ISSUE TITLE
人人都是产品经理

### ISSUE THREAD

**Issue by sin572** [DIYgod/RSSHub#11894]
### 路由地址

```routes
/woshipm/popular/:range?
```

### 完整路由地址

```fullroutes
/woshipm/popular
/woshipm/popular/daily
```

### 相关文档

https://docs.rsshub.app/new-media.html#ren-ren-dou-shi-chan-pin-jing-li

### 预期是什么？

正常使用

### 实际发生了什么？

报错

![image](https://user-images.githubusercontent.com/113758409/219641654-8d94bb0f-3b7e-47f0-a480-fa44f33c5e7d.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /popular
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /popular
Node version: v16.19.0
Git Hash: 2229033
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/woshipm/popular
/woshipm/popular/daily
```

**Comment by TonyRL** [comment]
It works
