### ISSUE TITLE
申请收录评论尸的博客“虹线”

### ISSUE THREAD

**Issue by Zachdemo** [DIYgod/RSSHub#11903]
### 类型

社交媒体

### 网站地址

https://1q43.blog/post/796

### 网站描述

互联网观察家评论尸的博客

### 需要生成什么内容？

抓取图文

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Full article RSS is available in https://1q43.blog/feed
