### ISSUE TITLE
知乎专栏失效

### ISSUE THREAD

**Issue by StrollStars** [DIYgod/RSSHub#11950]
### Routes

```routes
/zhihu/zhuanlan/:id
```

### Full routes

```fullroutes
https://rsshub.app/zhihu/zhuanlan/googledevelopers
```

### Related documentation

https://docs.rsshub.app/

### What is expected?

能够正常显示列表

### What is actually happening?

出现页面：Looks like something went wrong

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/zhuanlan/googledevelopers
```

**Comment by TonyRL** [comment]
It works
