### ISSUE TITLE
Pixiv RSS, show personal feed

### ISSUE THREAD

**Issue by Inoreen** [DIYgod/RSSHub#1196]
Please add an RSS feed thats takes the data from your own feed
(https://www.pixiv.net/stacc?mode=unify)

**Comment by SettingDust** [comment]
@Inoreen Please use the template or close

**Comment by Inoreen** [comment]
Sorry, I don't really understand what you mean.

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/49006372-dce5c400-f160-11e8-9044-4f27fc849c83.png)
