### ISSUE TITLE
RSS Pixiv, personal feed

### ISSUE THREAD

**Issue by Inoreen** [DIYgod/RSSHub#1197]
### Website URL
https://www.pixiv.net/stacc/my/home/favorite/activity?mode=unify
### What content should be included?

- [ ] personal Pixiv feed

### Additional description
At the moment, the supported RSS for Pixiv are just getting either the bookmarks or the activity for one user.
I would like to request an additional RSS feed, which has the content of the link above. It contains submissions/bookmarks/follows of ALL users you are following.

Alternatively, it would be fine also if it is possible to combine RSS feeds so e.g http://rsshub.app/pixiv/user/bookmarks/12345 **&** 6789 would get you a RSS feed of the user 12345 and the user 6789

**Comment by Inoreen** [comment]
Well currently the supported RSS feeds are only bookmarks or user, but not ALL bookmarks/follow etc from MY feed

**Comment by maple3142** [comment]
I don't think it is possible without providing your username & password.
However, providing your account is not practical at all, so subscribe multiple feeds might be a better solution.

**Comment by SettingDust** [comment]
@Inoreen So you can feed all user and bookmarks. Why not

**Comment by Inoreen** [comment]
@maple3142 yeah that's what I did for now. I just thought it would be a nice idea, but I guess I'll just continue subscribe to the feeds manually

**Comment by DIYgod** [comment]
It's not possible to get others' personal feed. can't do it.
