### ISSUE TITLE
知乎用户动态activities路由报错Error: Failed to extract `d_c0` from cookies

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#11984]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/diygod
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常抓取知乎用户动态

### 实际发生了什么？

Error: Failed to extract `d_c0` from cookies

### 部署

自建

### 额外信息

```shell
rsshub的tg群里有用户反馈 知乎路由复活了

我自建的机器报错从 Response code 403 (Forbidden): target website might be blocking our access

 变成 Error: Failed to extract `d_c0` from cookies
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/11882  相关的问题

**Comment by KwToPA** [comment]
https://rsshub.app/zhihu/people/activities/418f5d9091f40cb323f6f6845993727d

官方的还是403

**Comment by KwToPA** [comment]
vps上搭建的  知乎路由恢复了

**Comment by KawausoJyou** [comment]
> vps上搭建的 知乎路由恢复了

我的自建还是显示Error message: Failed to extract `d_c0` from cookies呢，和官方版本是一样的

**Comment by KwToPA** [comment]
@KawausoJyou   我的vps IP在海外，你的IP在哪？

**Comment by KwToPA** [comment]
在这边讨论吧  https://github.com/DIYgod/RSSHub/issues/11882

**Comment by KwToPA** [comment]
一晚上只更新了若干个， 又变成全红  报错  Failed to extract `d_c0` from cookies

**Comment by KwToPA** [comment]
自建 又报错 Failed to extract `d_c0` from cookies

官方rsshub是403 禁止

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/diygod
```
