### ISSUE TITLE
开播提醒

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#120]
- [x] bilibili
- [x] 斗鱼
- [x] 熊猫

**Comment by DIYgod** [comment]
@DIYgod +关播提醒

**Comment by DIYgod** [comment]
Done. cf71bf981a1b0a83f88d71ba3af4cb7a58de6f97 0201ee122dd86de905f72044abb7501c66e5a1b3

**Comment by ErichTao** [comment]
斗鱼某些直播间无法订阅
![image](https://user-images.githubusercontent.com/39548509/61027455-ca1ab980-a3e8-11e9-8daf-e7f35fbdc69c.png)

**Comment by DIYgod** [comment]
> 斗鱼某些直播间无法订阅
> ![image](https://user-images.githubusercontent.com/39548509/61027455-ca1ab980-a3e8-11e9-8daf-e7f35fbdc69c.png)

抓包看到 id 是 5910850 不是 52000，我也不知道为什么 https://rsshub.app/douyu/room/5910850
