### ISSUE TITLE
Transit blog

### ISSUE THREAD

**Issue by johan456789** [DIYgod/RSSHub#12020]
### Category

Blog

### Website URL

https://blog.transitapp.com/

### Website description

Transit is a mobile app providing real-time public transit data. 

### What content should be included?

Title, Summary, Thumbnail. Like this:

![image](https://user-images.githubusercontent.com/14802181/222571899-e37a2c03-76c9-4dcf-85b6-476ddd30a329.png)

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Full article RSS is provided from `https://blog.transitapp.com/feed/`

**Comment by johan456789** [comment]
Oh didn't notice that. Thank you!
