### ISSUE TITLE
请求添加nite07.com

### ISSUE THREAD

**Issue by liu2-3zhi** [DIYgod/RSSHub#12032]
### 类型

社交媒体

### 网站地址

https://www.nite07.com/

### 网站描述

一个软件分享论坛

### 需要生成什么内容？

更新的博客。
如果可以带上本身的软件分类最好不过

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Full article RSS with categories is available from `https://www.nite07.com/atom.xml`
