### ISSUE TITLE
好奇心日报源，文章图片全部显示为同一logo图片

### ISSUE THREAD

**Issue by imrayyu** [DIYgod/RSSHub#12031]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
https://rsshub.netlify.app/new-media.html#guo-ke-wang
```

### 相关文档

https://rsshub.netlify.app/new-media.html#guo-ke-wang

### 预期是什么？

图片正常显示

### 实际发生了什么？

文章图显示均为同一logo图片

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
NA
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Do not report route related issues using `NOROUTE`.
Can't reproduce if nothing is provided.
