### ISSUE TITLE
Tailscale; website unreachable error

### ISSUE THREAD

**Issue by crawfordlong** [DIYgod/RSSHub#12071]
### Routes

```routes
/youtube/
```

### Full routes

```fullroutes
/youtube/user/@AdamNeely (but could be anyone)
```

### Related documentation

n/a

### What is expected?

I am migrating my rsshub installation from a publicly accessible installation to a private tailscale network. 

I can browse directly to rsshub from another machine on the tailscale network, e.g., https://rsshub.$my.$domain/youtube/user/@AdamNeely, and see the resulting RSS feed. If I leave the tailscale network, I can no longer browse to the rsshub resource. **This is expected.**

If I subscribe to an rsshub feed from miniflux, I should see the feed in my reader (this was working properly with the public-facing installation of each). 

### What is actually happening?

If I subscribe to an rsshub link in **miniflux**, any attempt to refresh times out with: 
`[ERROR] [UI:RefreshFeed] This website is unreachable (original error: "dial tcp 100.$x.$y.$z: i/o timeout")`

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Ubuntu 22.10; Docker 20.10.16

### Additional info

```shell
I cannot figure out a way to troubleshoot this. I figure there's a decent chance this error is occurring in miniflux (in which case feel free to close this error). 

What seems to be happening is that, somewhere in the chain, a resource outside my tailscale network is attempting to access the rsshub. The only thing outside the network that I can think is involved in any transaction with rsshub is youtube -- is the youtube API call doing some sort of reverse transaction that requires that it be able to resolve and access the resource that is making the call?
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by crawfordlong** [comment]
I may have misunderstood what was being requested regarding the term 'route'. Apologies if so.

**Comment by TonyRL** [comment]
This is really a tailscale-related issue.

You have to make sure your RSSHub instance:
1. can visit the internet
2. can be visited through your tailscale network

and make sure your miniflux instance:
1. can visit your RSSHub instance through your tailscale network

**Comment by crawfordlong** [comment]
That’s the thing: as far as I can tell, the answer to all 3 of your questions is “yes”. For example, I don’t have any issue “seeing” the rsshub container from within the miniflux instance. This is perhaps useless but anecdotal, but several other containers are communicating with exactly the same setup, eg various containers hitting a Postgres or redis container without any issues.   
  

  
As near as I can tell, the only application having any trouble, and only in this peculiar case, is miniflux (or rsshub, but the error is showing up in miniflux logs), and I can’t see any user error reason why this would be the case.   
  
  
  
  
  
  

  
  
>
