### ISSUE TITLE
字幕组 RSS 

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1208]
### 源站地址

http://www.zimuzu.tv

### 需要生成什么内容？

- [x] 带 enclosure 字段的 RSS，比如：`<enclosure url="magnet:?xt=urn:btih:xxxx" length="1" type="application/x-bittorrent"/>`

### 额外描述

[官方提供的 RSS](http://diaodiaode.me/rss/feed/36980) 字段不标准，无法识别 magnet 地址，抓取官方 RSS 修改即可

**Comment by DIYgod** [comment]
Done. 2269b3b7e7ce91bc5b97562999123b8f3de18318

**Comment by cxyzzz** [comment]
当不带id的时候输出的是最近更新，能顺便支持下吗？:smile:

**Comment by kks2385** [comment]
字幕组TV的网站提供了很多不同的清晰度版本的选择，这个RSS似乎只能抓取到一部分版本，希望能更新一下。

**Comment by lengthmin** [comment]
@kks2385 说得对，希望可以增加一个字段来选择清晰度

**Comment by jiey2016** [comment]
@DIYgod 字幕组订阅出现问题，无法抓取，望解决。

**Comment by jiey2016** [comment]
@DIYgod 
![BaiduShurufa_2019-4-16_11-52-3](https://user-images.githubusercontent.com/19381978/56180969-21093080-603e-11e9-938c-f27f2c9a0865.jpg)

**Comment by ruleroller** [comment]
@DIYgod @xyqfer bug的产生原因或许是zimuzu的源rss地址已经发生变化，但不知道是临时还是永久。旧的，也是rsshub里目前使用的 http://diaodiaode.me/rss/feed 是404状态， 我灵机一动，发现这个新地址有输出RSS内容 http://www.zimuzu.io/rss/feed 。

自己本地简单更换掉链接地址之后，测试发现还是存在问题， 用示例中的 zimuzu/resource/37031 的路由，依旧输出全部结果。

期待大佬们能修复此问题。

**Comment by jiey2016** [comment]
![image](https://user-images.githubusercontent.com/19381978/58297184-712b9d80-7e09-11e9-9b05-8433476dd782.png)
貌似字幕组的rss又出问题了 @DIYgod

**Comment by tgly307** [comment]
@jiey2016 试了试没问题啊 https://rsshub.app/zimuzu/resource/36162
