### ISSUE TITLE
请求增加https://www.gamersky.com/news/ 

### ISSUE THREAD

**Issue by hegpt** [DIYgod/RSSHub#12107]
### Category

Uncategorized

### Website URL

https://www.gamersky.com/news/

### Website description

资讯_游民星空 GamerSky.com - 打造及时有趣的游戏资讯中心

### What content should be included?

今日推荐 单机 电玩  NS 手游 网游 业界 硬件 科技

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://docs.rsshub.app/game.html#you-min-xing-kong
