### ISSUE TITLE
npm sdk 方式使用,  RSSHub.request('/bilibili/bangumi/media/9192') 支持同时订阅多个 URL吗 

### ISSUE THREAD

**Issue by wujunze** [DIYgod/RSSHub#12117]
### 这是一个什么样的功能？

npm sdk 方式使用,  RSSHub.request('/bilibili/bangumi/media/9192') 支持同时订阅多个 URL吗 

### 这个功能可以解决什么问题？

同时订阅多个 URL 方便做开发

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
Neither web based nor the npm package supports subscribing to multiple RSS feeds in single request. You have to send multiple `RSSHub.request('/xxx')` instead.

**Comment by TonyRL** [comment]
Related #10246
