### ISSUE TITLE
Youtube Community - Error message: Cannot read properties of undefined (reading 'regExp')

### ISSUE THREAD

**Issue by jiongjiongzj** [DIYgod/RSSHub#12116]
### 路由地址

```routes
/youtube/community/:handle
```

### 完整路由地址

```fullroutes
/youtube/community/UCR6qhsLpn62WVxCBK1dkLow
```

### 相关文档

https://docs.rsshub.app/social-media.html#youtube

### 预期是什么？

正常抓取Youtube社区页面的内容

### 实际发生了什么？

无法抓取，显示以下报错信息：
Route requested: /community/UCR6qhsLpn62WVxCBK1dkLow
Error message: Cannot read properties of undefined (reading 'regExp')
Helpful Information to provide when opening issue:
Path: /community/UCR6qhsLpn62WVxCBK1dkLow
Node version: v16.19.1
Git Hash: 48570cc

### 部署

自建

### 部署相关信息

OS: Linux, Node: v16.19.1, Docker: 20.10.21

### 额外信息

```shell
Route requested: /community/UCR6qhsLpn62WVxCBK1dkLow
Error message: Cannot read properties of undefined (reading 'regExp')
Helpful Information to provide when opening issue:
Path: /community/UCR6qhsLpn62WVxCBK1dkLow
Node version: v16.19.1
Git Hash: 48570cc

实测RSSHub演示地址抓取正常，但是自建服务抓取失败。把community换成channel用来抓取视频页面内容没有问题，加上community的规则是近期添加的，猜测可能是规则问题或者我少配置了重要的环境变量（我只填了YOUTUBE_KEY，没有填OAuth 2.0相关的3个变量）。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by jiongjiongzj** [comment]
> ##### Searching for maintainers:
> * `/youtube/community/:handle`: **Route not found**
> 
> > To maintainers: if you are not willing to be disturbed, list your username in `scripts/workflow/test-issue/call-maintainer.js`. In this way, your username will be wrapped in an inline code block when tagged so you will not be notified.
> 
> 如果有任何路由无法匹配，issue 将会被自动关闭。如果 issue 和路由无关，请使用 `NOROUTE` 关键词，或者留下评论。我们会重新审核。 If there is any route not found, the issue will be closed automatically. Please use `NOROUTE` for a route-irrelevant issue or leave a comment if it is a mistake.

这个路由是已经存在的。

**Comment by TonyRL** [comment]
It works
