### ISSUE TITLE
南华早报 SCMP 不能抓取原文，只能抓取摘要

### ISSUE THREAD

**Issue by ayunhe** [DIYgod/RSSHub#12135]
### 路由地址

```routes
/scmp/:category_id
```

### 完整路由地址

```fullroutes
https://rsshub.app/scmp/3
https://rsshub.app/scmp/318198
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#nan-hua-zao-bao-scmp

### 预期是什么？

能够抓取原文，而不仅仅是只有摘要

### 实际发生了什么？

只有文章摘要，看不到某新闻的全部内容

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #10384
