### ISSUE TITLE
微信公众号-二十次幂来源在特定情况下会出错

### ISSUE THREAD

**Issue by jiongjiongzj** [DIYgod/RSSHub#12138]
### 路由地址

```routes
/wechat/ershicimi/:id
```

### 完整路由地址

```fullroutes
/wechat/ershicimi/M3eZdylO
```

### 相关文档

https://docs.rsshub.app/new-media.html#wei-xin-gong-zhong-hao-er-shi-ci-mi-lai-yuan

### 预期是什么？

正常通过二十次幂抓取微信公众号“正面连接”的RSS

### 实际发生了什么？

报错，提示返回了404。实测演示地址也出现同样情况，并且只有这一个公众号报错。完整报错信息如下：
Route requested: /ershicimi/M3eZdylO
Error message: Response code 404 (NOT FOUND): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /ershicimi/M3eZdylO
Node version: v16.19.1
Git Hash: 48570cc

### 部署

自建

### 部署相关信息

OS: Linux, Node: v16.19.1, Docker: 20.10.21

### 额外信息

```shell
Route requested: /ershicimi/M3eZdylO
Error message: Response code 404 (NOT FOUND): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /ershicimi/M3eZdylO
Node version: v16.19.1
Git Hash: 48570cc
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by jiongjiongzj** [comment]
> ##### Searching for maintainers:
> * `/wechat/ershicimi/:id`: @sanmmm
> 
> > To maintainers: if you are not willing to be disturbed, list your username in `scripts/workflow/test-issue/call-maintainer.js`. In this way, your username will be wrapped in an inline code block when tagged so you will not be notified.
> 
> 如果有任何路由无法匹配，issue 将会被自动关闭。如果 issue 和路由无关，请使用 `NOROUTE` 关键词，或者留下评论。我们会重新审核。 If there is any route not found, the issue will be closed automatically. Please use `NOROUTE` for a route-irrelevant issue or leave a comment if it is a mistake.

这个路由是已经存在的。

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/blob/e17a1ae3162625e3674a5cc04d1973f2eabb2cdd/lib/v2/wechat/ershcimi.js#L8-L11
https://www.cimidata.com/a/M3eZdylO does not exist
