### ISSUE TITLE
Axios to Request

### ISSUE THREAD

**Issue by SettingDust** [DIYgod/RSSHub#1217]
### What feature is it?
Axios to Request
### What problem does this feature solve?
Proxy

**Comment by NStal** [comment]
I add some levels of socks support to `axios` wrapper. So we can avoid massive refactoring, though I personally prefer request. 
Not widely tested yet. I'm new to this project.

https://github.com/DIYgod/RSSHub/pull/1379

**Comment by yefoenix** [comment]
这个 issue 是不是可以关闭了
