### ISSUE TITLE
是否可以支持订阅任何其它RSS再进行输出？

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#122]
标题看起来有些绕，我解释一下。

目前rsshub的是将一些服务输出成RSS，这个愿景和目前的实现都很好。

但最基础的将已有的第三方RSS重新订阅，然后输出，是不是也能实现一下。

这样可以好好利用Filter的过滤功能。

**Comment by huobaolajiao** [comment]
转接rss需求可能偏了，但应该很容易在本地实现，我觉得我们可以找个开源rss的作品fork成rsshub的专属客户端

**Comment by kastnerorz** [comment]
既然已经有了 rss 源直接用就好了嘛，我觉得作者的本意是将本没有 rss 源的生成 rss 源，所以我认为转接不是必要需求

**Comment by ruleroller** [comment]
是直接可以用，可如果要过滤一下呢？rsshub的filter功能就有帮助了，否则还是得用其它工具，更加费事。既然是hub，那多一个增强功能，没什么不好的。

**Comment by wydwww** [comment]
@ruleroller 这样的工具很多，比如 https://siftrss.com

https://www.quora.com/What-is-the-best-tool-to-filter-RSS-Feeds

**Comment by DIYgod** [comment]
无意义，建议使用客户端实现

**Comment by imjoeyli** [comment]
> 无意义，建议使用客户端实现

客户端相对不可控，比如 telegram-rssbot 就不支持过滤。

而 RSShub 若支持用关键词过滤已有 RSS 地址，就能兼容所有客户端。

**Comment by imjoeyli** [comment]
> @ruleroller 这样的工具很多，比如 https://siftrss.com
> 
> https://www.quora.com/What-is-the-best-tool-to-filter-RSS-Feeds

可惜是第三方，不如自建的 RSShub 可控。
