### ISSUE TITLE
Docs: Window 上的 scroll event listener 导致浏览指南时上下滚动有卡顿

### ISSUE THREAD

**Issue by ShenHongFei** [DIYgod/RSSHub#1220]
**删除 Window 上的 scroll event listener 后才恢复流畅。文档比较长，可能因为文档比较长导致性能下降过多引起。**

![0022](https://user-images.githubusercontent.com/15074472/49336241-54bc5e80-f639-11e8-9607-93befa6215b5.png)

**Comment by ShenHongFei** [comment]
@DIYgod 类似的 Issue #1098

**Comment by SettingDust** [comment]
@ShenHongFei Issue请使用模板

**Comment by ShenHongFei** [comment]
@SettingDust 3 个现有的模板都和我提的这个 Bug 的内容不匹配，没有办法用模板写。

**Comment by SettingDust** [comment]
请确保 [文档](https://docs.rsshub.app) 和 [issue](https://github.com/DIYgod/RSSHub/issues) 中没有相关内容，**并按照模版提供信息**
**否则 issue 将被立即关闭**

### 这是一个什么样的功能？
修复Scroll事件处理速度问题
### 这个功能可以解决什么问题？
文档滚动卡顿

**Comment by DIYgod** [comment]
重复 #1098

**Comment by cooper1x** [comment]
我也是很卡，换了浏览器也不行。
这个你是怎么移除的呢？ @ShenHongFei

**Comment by ShenHongFei** [comment]
@cooper1x F12 打开 Developer Tools → 右边 Event Listeners → 展开 scroll → 点 Window 右边的 Remove
