### ISSUE TITLE
通过搜狗获取公众号文章，有没有希望建立一种稳定的订阅源？

### ISSUE THREAD

**Issue by bowencool** [DIYgod/RSSHub#12215]
### 这是一个什么样的功能？

通过搜狗获取公众号文章，有没有希望建立一种稳定的订阅源？参考 https://github.com/howie6879/liuli

### 这个功能可以解决什么问题？

目前的订阅源都不是很稳定，当然我这里也只是提供一种想法而已。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
Duplicate of #817
