### ISSUE TITLE
Twitter 路由支持 user id

### ISSUE THREAD

**Issue by cxplay** [DIYgod/RSSHub#12221]
### 这是一个什么样的功能？

现在的 Twitter 路由对用户仅支持 user name, 希望支持使用 user id 定位用户.

### 这个功能可以解决什么问题？

user name 可由用户自由修改，并非是与用户唯一关联的 id, 如果使用 user id 来定位用户，即使用户名发生变动也不会影响路由定位用户 (除非用户销号).

### 额外描述

使用以下 url 将 user id 作为参数可定位到用户主页:
> - `https://twitter.com/intent/user?user_id=UID`
> - `https://twitter.com/i/user/UID`

示例:
- https://twitter.com/intent/user?user_id=11348282
- https://twitter.com/i/user/11348282

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by clacknya** [comment]
any update?

**Comment by RaiseYI** [comment]
# 这个问题解决了吗,目前我订阅不了自己的x,但是可以订阅openai的,而且有的其他的也不能订阅rss,请问怎么办呢?

**Comment by 123hi123** [comment]
我也是一樣的問題
目前看起來有的可以有的不行rss

**Comment by VaJoy** [comment]
订阅不了，例如：https://rsshub.app/twitter/user/AxelAdlerJr/routeParams=exclude_rts_replies

**Comment by Att000** [comment]
如何查询他人X的ID

**Comment by shylock-wu** [comment]
> 如何查询他人X的ID

这个就是地址栏的 id，id 是用户名的意思，唯一的，例如`https://x.com/elonmusk`,那么 id 就是`elonmusk`
