### ISSUE TITLE
微博网页链接的图标没有删除

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#12248]
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/1401527553?showLinkIconInDescription=0
```

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

### 预期是什么？

网页链接应该只是一个链接，不带图标

### 实际发生了什么？

仍然有图标

这个格式在Unread中无法正常显示，点击`网页链接`会放大这个链接图标，而不是打开网页

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ttttmr** [comment]
补两个图，正则看着ok

![image](https://user-images.githubusercontent.com/32825326/230328729-992239b2-beae-4715-896f-ba7ffdb82a44.png)
![image](https://user-images.githubusercontent.com/32825326/230329464-fe0319a4-b3b0-44cf-8e98-a0fed491d7f3.png)

**Comment by Rongronggg9** [comment]
```
/weibo/user/:uid/:routeParams?
                ^
```

```
/weibo/user/1401527553?showLinkIconInDescription=0
                      ^
```

FYI: https://docs.rsshub.app/parameter.html
