### ISSUE TITLE
请求修复picuki RSS

### ISSUE THREAD

**Issue by Jacky-Chang1024** [DIYgod/RSSHub#12247]
### Routes

```routes
/picuki/profile/:id/:functionalFlag?
```

### Full routes

```fullroutes
https://rsshub.app/picuki/profile/:id/:functionalFlag?
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#picuki

### What is expected?

加载出正常的rss页面

### What is actually happening?

![image](https://user-images.githubusercontent.com/77572354/230264985-5bf8514a-3549-4572-9c58-353411da10da.png)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
有人在一个ins的issue下提到过，但并不是那个issue的主题，因此这里题出一下
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Rongronggg9** [comment]
/test

```route
/picuki/profile/stefaniejoosten
```

**Comment by Rongronggg9** [comment]
/test
```routes
/picuki/profile/stefaniejoosten
```

**Comment by TonyRL** [comment]
It works. 

> Requests from public demo might be filtered by WAF. Deploy yours plz.

_Originally posted by Rongronggg9 in https://github.com/DIYgod/RSSHub/issues/11661#issuecomment-1398629646_

The pictures you're showing is Instagram **not picuki**.
