### ISSUE TITLE
B站up主视频页面失效

### ISSUE THREAD

**Issue by korosu1** [DIYgod/RSSHub#12261]
### 路由地址

```routes
/bilibili/user/video-all/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video-all/436361287
```

### 相关文档

https://rsshub.app/bilibili/user/video-all/436361287

### 预期是什么？

可以正常使用

### 实际发生了什么？

B站up主视频订阅界面无法访问，之前订阅的无法更新

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
B站up主视频订阅界面无法访问，之前订阅的无法更新
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video-all/436361287
```

**Comment by TonyRL** [comment]
It works

**Comment by korosu1** [comment]
No,I tried,it doesn't work
these work
https://rsshub.app/bilibili/bangumi/media/9192
https://rsshub.app/bilibili/user/bangumi/208259


but these not,change the ID also not work.
https://rsshub.app/bilibili/user/video/2267573
https://rsshub.app/bilibili/user/video-all/436361287



Hope to deal with it, thanks!










zxy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIYgod/RSSHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月8日(星期六) 凌晨3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIYgod/RSSHub] B站up主视频页面失效 (Issue #12261)





 
Closed #12261 as completed.

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by SunsetjesusCame2me** [comment]
/test
`/bilibili/user/video/491306902`

**Comment by SunsetjesusCame2me** [comment]
/test
> /bilibili/user/video/491306902

**Comment by SunsetjesusCame2me** [comment]
/test

`/bilibili/user/video/491306902`

**Comment by SunsetjesusCame2me** [comment]
/test

```
/bilibili/user/video/2267573
```

**Comment by SunsetjesusCame2me** [comment]
/test

```
/bilibili/user/video-all/491306902
```

**Comment by SunsetjesusCame2me** [comment]
/test
```
/bilibili/user/video-all/491306902
```
