### ISSUE TITLE
/hexo/next/:url 不工作

### ISSUE THREAD

**Issue by Jonathan523** [DIYgod/RSSHub#12270]
### 路由地址

```routes
/hexo/next/:url
```

### 完整路由地址

```fullroutes
/hexo/next/diygod.me
```

### 相关文档

https://docs.rsshub.app/en/blog.html#hexo-blog

### 预期是什么？

正常获得RSS内容

### 实际发生了什么？

报错this route is empty, please check the original site or create an issue

### 部署

自建

### 部署相关信息

Vercel node 18.x

### 额外信息

```shell
Route requested: /hexo/next/diygod.me
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /hexo/next/diygod.me
Node version: v18.13.0
Git Hash: de0a5cf
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/hexo/next/archive.diygod.me
```

**Comment by TonyRL** [comment]
It works
