### ISSUE TITLE
国家统计局  最新发布 网址发生改变

### ISSUE THREAD

**Issue by willowj** [DIYgod/RSSHub#12288]
### Category

Government

### Website URL

http://www.stats.gov.cn/sj/zxfb/

### Website description

国家统计局 #统计数据 > 最新发布   

### What content should be included?

http://www.stats.gov.cn/sj/zxfb/ 最新发布内容

### Additional description

国家统计局 #统计数据 > 最新发布  https://docs.rsshub.app/government.html#guo-jia-shui-wu-zong-ju

网址发生改变，新rss路由 https://rsshub.app/gov/stats/sj/zxfb/

Route requested: /gov/stats/sj/zxfb/
Error message: this route is empty,

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by OleNet** [comment]
好像这个 rss 也会出现问题

**Comment by willowj** [comment]
您好，谢谢您的来信，会尽快查收。
