### ISSUE TITLE
Error when using picnob

### ISSUE THREAD

**Issue by kb-0912** [DIYgod/RSSHub#12298]
### Routes

```routes
/picnob/user/:id
```

### Full routes

```fullroutes
/picnob/user/:id
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#picnob

### What is expected?

Return rss

### What is actually happening?

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Docker version 20.10.21, build baeda1f

### Additional info

```shell
Helpful Information to provide when opening issue:
Path: /user/fragile.club
Node version: v18.15.0
Git Hash: 64a5a7d
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
It works

**Comment by kb-0912** [comment]
@TonyRL 
159.223.86.11:1200/picnob/user/fragile.club

Can you tell me why it’s not working on my end

**Comment by Hadi7546** [comment]
/test 
```
/picnob/user/tarasalahi
```

**Comment by Japhys** [comment]
Same here, 403 with picnob and picuki. Not straight away but after a while it just stops working. I think it's just blocking rsshub as a result of too many requests. Even when you self host.
