### ISSUE TITLE
Facebook RSS wanted

### ISSUE THREAD

**Issue by stu43005** [DIYgod/RSSHub#123]

**Comment by stu43005** [comment]
https://github.com/stefansundin/rssbox

自己找到了這個project支持了各種的網站，包括Facebook、Twitter、Youtube等

可以當作參考

**Comment by uufrienduu** [comment]
有辦法把facebook的個人頁面轉換為RSS Feed嗎？

**Comment by maple3142** [comment]
似乎沒辦法直接取得個人頁面的，不過粉絲專頁可透過 facebook api 取得
但這需要: https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS 的權限...

**Comment by uufrienduu** [comment]
有無可能透過連結之應用程式偵測自己好友與追蹤對象的發文呢？

**Comment by uufrienduu** [comment]
@DIYgod  反爬的風險指的是？
