### ISSUE TITLE
/bilibili/user/video Error

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#12359]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/2267573
/bilibili/user/video/287795639
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

/bilibili/user/video

### 实际发生了什么？

RSSHub.app
Error message: Response code 412 (Precondition Failed): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

自建
Error message: Cannot read properties of undefined (reading 'name')

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
dynamic依然可用
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
/bilibili/user/video/287795639
```

**Comment by RekiDunois** [comment]
我这边自建的dynamic也失效了

**Comment by Jiematcha** [comment]
多刷新几次有概率成功

**Comment by curly210102** [comment]
@RekiDunois 我这边没有出现问题欸，能贴下出问题的路由地址么？还有错误信息是什么？
