### ISSUE TITLE
twitter 路由显示长推特不全

### ISSUE THREAD

**Issue by zizhengwu** [DIYgod/RSSHub#12360]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/fangshimin/readable=1&showAuthorInTitle=0&showAuthorInDesc=0&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=1&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150&excludeReplies=1&forceWebApi=1
```

### 相关文档

https://docs.rsshub.app/en/social-media.html#twitter

### 预期是什么？

可以完整显示长推特。

### 实际发生了什么？

只显示了长推特的部分内容，超过字数被截断，如下图。注意我使用了 `forceWebApi=1`

![image](https://user-images.githubusercontent.com/2246655/233534498-f91b1725-45c1-469d-80e4-569bfc91ae68.png)

完整推特：

![image](https://user-images.githubusercontent.com/2246655/233534550-bd9b170f-f545-4921-a729-5be49da831aa.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
n/a
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by zizhengwu** [comment]
`/twitter/user: Route not found` 不应该啊。。感觉这个判断有点问题。。请求重新审核。

另外我觉得 @Rongronggg9 可能是这个路由以及 `forceWebApi=1` 的作者，所以 fyi，谢谢。

**Comment by Revertron** [comment]
So, any news for this issue?
