### ISSUE TITLE
pre-commit report error after run build:radar

### ISSUE THREAD

**Issue by drgnchan** [DIYgod/RSSHub#12454]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

None

### 预期是什么？

预期可以提交成功，也就是npm run format:staged 不报错

### 实际发生了什么？

提交不成功，报错信息如下。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
重现步骤：
1. npm run build:radar
2. npm run format:staged

报错信息如下：


```
<img width="963" alt="image" src="https://user-images.githubusercontent.com/40224023/236591398-c1dfabff-e5fb-4ed9-b797-16654bd93c1d.png">

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/joinus/script-standard.html#v2-lu-you-gui-fan-wei-hu-zhe-lie-biao
