### ISSUE TITLE
B站up主视频无法更新

### ISSUE THREAD

**Issue by korosu1** [DIYgod/RSSHub#12461]
### 路由地址

```routes
/bilibili/user/video-all/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video-all/351562235
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

希望能正常更新
![屏幕截图 2023-05-06 220510](https://user-images.githubusercontent.com/130169836/236628997-c98fb4b2-4351-43da-ac82-0c45f5e49b7c.jpg)

### 实际发生了什么？

B站有好几个规则，up主专栏、动态、订阅番剧这些都可以正常使用，我不知道up主全部视频跟这些规则有什么区别，也不知道为什么你们测试了是正常的，请你们能用普通的浏览器打开网址，站在普通使用者的角度来看一看到底能不能用吗？我已经几个月都用不了了，能试的都试了。感谢。
![屏幕截图 2023-05-06 220510](https://user-images.githubusercontent.com/130169836/236629007-d0ad3895-4090-4dcb-b51c-0a5d352881a1.jpg)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
B站有好几个规则，up主专栏、动态、订阅番剧这些都可以正常使用，我不知道up主全部视频跟这些规则有什么区别，也不知道为什么你们测试了是正常的，请你们能用普通的浏览器打开网址，站在普通使用者的角度来看一看到底能不能用吗？我已经几个月都用不了了，能试的都试了。感谢。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ImSanae** [comment]
试了下 RSSHub 演示站点路由返回 Error，但自建的实例可以成功抓取内容

**Comment by korosu1** [comment]
> 试了下 RSSHub 演示站点路由返回 Error，但自建的实例可以成功抓取内容

能分享一下您的自建地址或者跟我说一下是通过什么方式自建的吗？我用的是在网上找的别人自建的https://rsshub.rssforever.com，刚刚换了好几个也还是都一样

**Comment by Sean19899999** [comment]
+1

确实这两个栏目用不了。

**Comment by lirtual** [comment]
我怀疑是b站做了限流，自建测试都是通过的，也确实能够获取到数据，但是很快被限流后都会失败，这也是为什么测试都通过，但是使用者都无法使用的原因。

**Comment by macOSWk** [comment]
vercel 自建 部分up投稿视频也无法获取 例如 https://space.bilibili.com/72647293

**Comment by korosu1** [comment]
> 我怀疑是b站做了限流，自建测试都是通过的，也确实能够获取到数据，但是很快被限流后都会失败，这也是为什么测试都通过，但是使用者都无法使用的原因。



> 我怀疑是b站做了限流，自建测试都是通过的，也确实能够获取到数据，但是很快被限流后都会失败，这也是为什么测试都通过，但是使用者都无法使用的原因。

我觉得不像，因为我试了一下订阅自己，根本没有视频，也是同样的失败界面，但是订阅Up主下面的合集是可以正常用的

**Comment by MarkXHu1943** [comment]
我在2周前也遇到了相同的问题，在此之前的4个月都使用的很正常，路径是up主的全部视频，很期望这个问题能够被解决

**Comment by kennir** [comment]
我也刚发现无法使用了，

There is a problem with this feed
Resource not found (404), this feed doesn't exist anymore, check the feed URL

用miniflux看直接显示404了

**Comment by curly210102** [comment]
> > 试了下 RSSHub 演示站点路由返回 Error，但自建的实例可以成功抓取内容
> 
> 能分享一下您的自建地址或者跟我说一下是通过什么方式自建的吗？我用的是在网上找的别人自建的[https://rsshub.rssforever.com，刚刚换了好几个也还是都一样](https://rsshub.rssforever.com%EF%BC%8C%E5%88%9A%E5%88%9A%E6%8D%A2%E4%BA%86%E5%A5%BD%E5%87%A0%E4%B8%AA%E4%B9%9F%E8%BF%98%E6%98%AF%E9%83%BD%E4%B8%80%E6%A0%B7)

可以选择Verce来自部署一个RSSHub服务，https://docs.rsshub.app/install/#bu-shu-dao-vercel-zeit-now 点击 Deploy 按钮再用 GitHub 账户继续流程就好了，Vercel 每月有100GB免费带宽，足够了。部署后 Vercel 会分配一个域名给你用它替换 https://rsshub.app/ 就好了

**Comment by korosu1** [comment]
> > > 试了下 RSSHub 演示站点路由返回 Error，但自建的实例可以成功抓取内容
> > 
> > 
> > 能分享一下您的自建地址或者跟我说一下是通过什么方式自建的吗？我用的是在网上找的别人自建的 [https://rsshub.rssforever.com，刚刚换了好几个也还是都一样](https://rsshub.rssforever.com%EF%BC%8C%E5%88%9A%E5%88%9A%E6%8D%A2%E4%BA%86%E5%A5%BD%E5%87%A0%E4%B8%AA%E4%B9%9F%E8%BF%98%E6%98%AF%E9%83%BD%E4%B8%80%E6%A0%B7)
> 
> 可以选择Vercel来自部署一个RSSHub服务，https://docs.rsshub.app/install/#bu-shu-dao-vercel-zeit-now 点击 Deploy 按钮再用 GitHub 账户继续流程就好了，Vercel 每月有100GB免费带宽，足够了。部署后 Vercel 会分配一个域名给你用它替换 https://rsshub.app/ 就好了

哇，真的解决了，可以用了，感谢大佬

**Comment by curly210102** [comment]
video-all 会去取 UP 主的所有视频，B站提供30个视频一页的分页接口，UP主的视频数量越多分页请求数也越多，在大批量请求下B站会要求进行验证码验证，最终导致获取不到全量数据。

video 只会请求最新一页的视频，如果只需要 feed 抓取最近30个视频，使用 video 路由的稳定性会比 video-all 高很多。

@MarkXHu1943  @macOSWk  可以看一下UP主的投稿列表页数

**Comment by curly210102** [comment]
video-all 会去取 UP 主的所有视频，B站提供30个视频一页的分页接口，UP主的视频数量越多分页请求数也越多，在大批量请求下B站会要求进行验证码验证，最终导致获取不到全量数据。

video 只会请求最新一页的视频，如果只需要 feed 抓取最近30个视频，使用 video 路由的稳定性会比 video-all 高很多。

@MarkXHu1943  @macOSWk  可以看一下UP主的投稿列表页数

**Comment by MarkXHu1943** [comment]
@curly210102 
之前订阅的大多数都是分页很多的up主，尝试更换为video路由之后，仍然报错：
Route requested: /user/video/2267573
Error message: Cannot read properties of undefined (reading 'name')
Helpful Information to provide when opening issue:
Path: /user/video/2267573
Node version: v18.15.0
Git Hash: f93d1ea

**Comment by MarkXHu1943** [comment]
也是用的vercel自建

**Comment by Lao-Tz** [comment]
> > > 试了下 RSSHub 演示站点路由返回 Error，但自建的实例可以成功抓取内容
> > 
> > 
> > 能分享一下您的自建地址或者跟我说一下是通过什么方式自建的吗？我用的是在网上找的别人自建的[https://rsshub.rssforever.com，刚刚换了好几个也还是都一样](https://rsshub.rssforever.com%EF%BC%8C%E5%88%9A%E5%88%9A%E6%8D%A2%E4%BA%86%E5%A5%BD%E5%87%A0%E4%B8%AA%E4%B9%9F%E8%BF%98%E6%98%AF%E9%83%BD%E4%B8%80%E6%A0%B7)
> 
> 可以选择Vercel来自部署一个RSSHub服务，https://docs.rsshub.app/install/#bu-shu-dao-vercel-zeit-now 点击 Deploy 按钮再用 GitHub 账户继续流程就好了，Vercel 每月有100GB免费带宽，足够了。部署后 Vercel 会分配一个域名给你用它替换 https://rsshub.app/ 就好了

感谢老哥，成功了，刚刚没看清还部署了下fly.io，卡在信用卡那才发现看岔了

**Comment by cyddgh** [comment]
我自己的站点也突然无法追踪B站up主的投稿视频。

**Comment by MarkXHu1943** [comment]
删除vercel之前部署的rsshub，然后重新部署之后功能正常

**Comment by curly210102** [comment]
@MarkXHu1943 应该是请求过多 IP 被限了

**Comment by korosu1** [comment]
@curly210102 大佬，麻烦问一下你现在还能用吗？之前我试了一下可以，但是现在又不行了，而且我每次刷新订阅列表的时候都必须要打开这个网站登录才能刷新，请问可以让他一直在线吗？而且现在好像B站这个规则又不行了

**Comment by korosu1** [comment]
为什么我评论了一句就把帖子关掉了啊，重新打开一下

**Comment by curly210102** [comment]
@korosu1 后面我加了一点代码，你需要先同步一下 RSSHub 最新的代码，等它重新部署完毕后再看一下效果

> 每次刷新订阅列表的时候都必须要打开这个网站登录才能刷新
这是说要打开Vercel登录才能刷新？应该不会有这种情况。可以贴一下订阅的路径，具体说一下现象吗？

**Comment by korosu1** [comment]
@curly210102 不知道是不是因为我用的user/video-all这个规则，就前段时间可以用，最近不行了，现在user/video这个规则还可以用，但是只能显示30条，这个有办法吗？我上面说的确实是要打开Vercel登录才能刷新，而且我每天早上要收到好多封邮件说什么什么失败

**Comment by korosu1** [comment]
请问“同步一下 RSSHub 最新的代码”这个应该怎么操作呢？还有就是这些视频我可以直接在rss播放器里播放吗？我用的是播客那种可以播音频视频的软件，目前看到的全是列表，就只能看一集手动勾一集，里面没有嵌视频，不过这个需求比较排后一点，现在能同步列表信息都已经心满意足了，感谢大佬

**Comment by korosu1** [comment]
@curly210102 收到的邮件没法截图，因为有好几封不同的格式，太多了，网站截图我贴一个，消息也提示说那个部署失败，但是我登录之后就好了，有时候点一下deploy，重新部署成功了第二天又收到说失败了
![image](https://github.com/DIYgod/RSSHub/assets/130169836/bd8dfd7b-ba0d-46e8-b59d-e2fddfacbf4b)

**Comment by curly210102** [comment]
@korosu1 通过 Vercel Deploy Button 创建的仓库并没有 fork DIYgod/RSSHub，因此不能更新到最新代码，需要Fork并部署一个新项目，操作如下：

1. Fork DIYgod/RSSHub 到你的Github（https://github.com/DIYgod/RSSHub/fork）
2. 去 Vercel 导入仓库部署一个新项目 （https://vercel.com/new/korosu） 
3. 安装 Pull 应用，定期将 RSSHub 改动自动同步到你的仓库（https://github.com/apps/pull）

**Comment by korosu1** [comment]
@curly210102 好的，我按照这个教程部署好了，看看下次还能不能正常更新，谢谢大神！但是user/video-all这个规则还是不能用T_T

**Comment by korosu1** [comment]
现在基本绝大部分B站的规则都用不了了

**Comment by heunghingwan** [comment]
> @curly210102 之前订阅的大多数都是分页很多的up主，尝试更换为video路由之后，仍然报错： Route requested: /user/video/2267573 Error message: Cannot read properties of undefined (reading 'name') Helpful Information to provide when opening issue: Path: /user/video/2267573 Node version: v18.15.0 Git Hash: f93d1ea

最近也遇到這個問題，我是用docker compose部署的，我將redis的volume清掉就好了

**Comment by kuusoo** [comment]
临时解决方案https://github.com/kuusoo/bilibili-rss
