### ISSUE TITLE
B站up主投稿所有视频规则更新失败

### ISSUE THREAD

**Issue by korosu1** [DIYgod/RSSHub#12460]
### 路由地址

```routes
/bilibili/user/video-all/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video-all/351562235
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

能正常获取更新的视频

### 实际发生了什么？

以前在软件里订阅了规则都可以正常使用，这几个月刷新都一直更新失败，以前直接访问规则地址都可以看到节目列表，现在就是访问错误

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video-all/351562235
```

**Comment by TonyRL** [comment]
It works

**Comment by korosu1** [comment]
> It works

可是为什么我用不了啊，B站的其他几个规则都可以，比如订阅番剧、专栏、频道都可以，就只有up所有视频的用不了，这些规则有什么区别吗？请问我还可以有什么设置的办法可以尝试吗？感谢

**Comment by a930389426** [comment]
我也有一样的情况，只有UP的视频用不了
