### ISSUE TITLE
Youtube: widespread but inconsistent 404 errors

### ISSUE THREAD

**Issue by crawfordlong** [DIYgod/RSSHub#12468]
### Routes

```routes
/youtube/user/:username
```

### Full routes

```fullroutes
/youtube/user/:username
```

### Related documentation

n/a

### What is expected?

A valid RSS feed.

### What is actually happening?

**Error message:**

```
Route requested: /user/@DrBecky
Error message: Cannot read properties of undefined (reading 'data')
Helpful Information to provide when opening issue:
Path: /user/@DrBecky
Node version: v18.16.0
Git Hash: 4069ce7
```

If I visit the feed url from miniflux, the result is a 404 error. 

This is happening across multiple /user paths, but it is not happening consistently with _any_ particular path. If I refresh several times, a particular feed might work or it might continue to fail.

I have refreshed my keys and tokens, even created an entirely new application in the Google API dashboard. 

Google's API console (https://console.cloud.google.com/apis/) is reporting an approximately 30% error rate. 

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Ubuntu 22.10, Node version: v18.16.0, docker version: Docker version 23.0.1, build a5ee5b1

### Additional info

```shell
n/a
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by crawfordlong** [comment]
Apologies if my format was not correct. The instruction for the route was not clear. /youtube/user/@DrBecky is an example of this error.

**Comment by ZefanHu** [comment]
I have the same Error message.

**Comment by ZefanHu** [comment]
> 

After a few minutes, I can access the feed URL normally without error message

**Comment by crawfordlong** [comment]
Same. Put another way, my feed is populating over time, but at any given time almost all of my youtube feeds are showing a recent error. I spun up a different tool (rss-bridge) to test and I am receiving some of the same errors. My google console is not currently showing any specific issues. My question is whether Google might have changed its API in a way that is affecting both applications, but only sometimes. This is an exceedingly frustrating issue to troubleshoot.

**Comment by ZefanHu** [comment]
Just had the same problem again. i feel confused. "Cannot read properties of undefined (reading 'data')"
It seems that youtube was successfully accessed, but youtube did not return the correct properties.
Just a guess, I don't understand the logic inside the program, I just got into RSSHUB for two days.

**Comment by ZefanHu** [comment]
Youtube seems to provide an official feed. I use inoreader to search for youtube channels, and just click to follow.
like this, https://www.youtube.com/feeds/videos.xml?channel_id=UCvijahEyGtvMpmMHBu4FS2w

**Comment by crawfordlong** [comment]
I switched away from youtube's official feeds because Google has an inconsistent approach to their availability. But I'm about to have no choice, as the error rate is creeping up to 100%. 

I am also seeing the error on the RSSHub.app website. I'm wondering if the inconsistent error rate relates to a change that Google is rolling out gradually. I am unsure how to submit a correctly formatted bug report however, as this one was closed for having the wrong format.

**Comment by ZefanHu** [comment]
youtube.com/user/YouTube This may be outdated, the official explanation is that using the old username URL can direct viewers to your own channel, I can use rsshub's /youtube/user/:username to access some users, such as Taylor swift , but most users cannot access, now the official use is youtube.com/channel/UCUZHFZ9jIKrLroW8LcyJEQQ, I can use the second route to access normally, on rsshub, for example this https://rsshub-three-eta.vercel.app/youtube/channel/UCSs4A6HYKmHA2MG_0z-F0xw, using this format I can get all channels , you only need to find the channel id of the corresponding channel.

**Comment by ZefanHu** [comment]
https://support.google.com/youtube/answer/6180214?sjid=9147147528235765374-AP
