### ISSUE TITLE
2048无法爬取

### ISSUE THREAD

**Issue by wzzqq** [DIYgod/RSSHub#12480]
### 路由地址

```routes
/2048/:id?
```

### 完整路由地址

```fullroutes
/2048/15
```

### 相关文档

https://docs.rsshub.app/multimedia.html#_2048-he-ji-di

### 预期是什么？

正常爬取

### 实际发生了什么？

Looks like something went wrong
Route requested: /15
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

自建

### 部署相关信息

Node version: v18.13.0 Git Hash: 9204ec3

### 额外信息

```shell
Route requested: /15
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by old-chow** [comment]
2048前置了cf

**Comment by kid101x** [comment]
自建服务器也一样会遇到反爬问题
```
Route requested: /2
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /2
Node version: v18.16.1
Git Hash: 7775ee5
```
