### ISSUE TITLE
twitter 输出图片不支持 gif

### ISSUE THREAD

**Issue by ivysrono** [DIYgod/RSSHub#1248]
### 路由地址
随便哪个账号的twitter，上传一张gif动图，twitter本身是支持的。
### 预期是什么？
应该是 gif 动图
### 实际发生了什么？
实际输出了静态图片
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by xyqfer** [comment]
印象中 twitter 会把 gif 转成 video 了， 我看看怎么搞。。。

**Comment by ivysrono** [comment]
我倒是觉得有些video也被rss输出成静态图了，待我找找例子看。

**Comment by xyqfer** [comment]
确实是，晚点我再改掉好了。。
