### ISSUE TITLE
知网作者期刊文献疑似无法使用

### ISSUE THREAD

**Issue by yzy-lex** [DIYgod/RSSHub#12490]
### 路由地址

```routes
/cnki/author/:code
```

### 完整路由地址

```fullroutes
/cnki/author/000037748936
```

### 相关文档

https://docs.rsshub.app/journal.html#zhong-guo-zhi-wang

### 预期是什么？

可以在inoreader订阅。

### 实际发生了什么？

除了rsshub给定举例外，在inoreader里面无法订阅。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by harveyqiu** [comment]
> ### 路由地址
> ```
> /cnki/author/:code
> ```
> 
> ### 完整路由地址
> ```
> /cnki/author/000037748936
> ```
> 
> ### 相关文档
> https://docs.rsshub.app/journal.html#zhong-guo-zhi-wang
> 
> ### 预期是什么？
> 可以在inoreader订阅。
> 
> ### 实际发生了什么？
> 除了rsshub给定举例外，在inoreader里面无法订阅。
> 
> ### 部署
> RSSHub 演示 (https://rsshub.app)
> 
> ### 部署相关信息
> _No response_
> 
> ### 额外信息
> ```shell
> 无
> ```
> 
> ### 这不是重复的 issue
> * [x]  我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

Work in progress https://github.com/DIYgod/RSSHub/pull/12415

**Comment by yzy1228682367** [comment]
好的，谢谢❤️
