### ISSUE TITLE
domp4域名变更mp4kan后,出现个别电视剧内容无法读取的错误.

### ISSUE THREAD

**Issue by zzlufida** [DIYgod/RSSHub#12502]
### 路由地址

```routes
domp4/detail/MpT13RDDDDDR.html
```

### 完整路由地址

```fullroutes
https://rsshub.app/domp4/detail/MpT13RDDDDDR.html
```

### 相关文档

https://rsshub.app/domp4/detail/MpT13RDDDDDR.html

### 预期是什么？

应该返回电视据的内容.

### 实际发生了什么？

Route requested: /detail/MpT13RDDDDDR.html
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /detail/MpT13RDDDDDR.html
Node version: v18.16.0
Git Hash: 6742ef8

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /detail/MpT13RDDDDDR.html
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /detail/MpT13RDDDDDR.html
Node version: v18.16.0
Git Hash: 6742ef8
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by rbforelle** [comment]
我也发现了这个问题，但应该和域名无关。最新的电视剧网页内容的格式有所更改，可能和这个有关系。
例如长月烬明https://www.mp4kan.com/html/xw1i85000005.html可以正常获取，护心https://www.mp4kan.com/html/7DRkFXAAAAAX.html就不能获取。
前者有一个checkbox在url-left这个div下面
![image](https://github.com/DIYgod/RSSHub/assets/29765197/c7df013e-e55c-4049-8ae5-6786208a989e)
后者这个checkbox直接放到上一级的li下面了
![image](https://github.com/DIYgod/RSSHub/assets/29765197/ab376c7a-f1e3-421a-9635-d46edc4f8f37)

所有checkbox在li下面的链接似乎都没法正常获取。


@zzlufida 你能把路由地址改成`/domp4/detail/:id`吗？要不然这个issue似乎不会被审核

**Comment by rbforelle** [comment]
我也发现了这个问题，但应该和域名无关。最新的电视剧网页内容的格式有所更改，可能和这个有关系。
例如长月烬明https://www.mp4kan.com/html/xw1i85000005.html可以正常获取，护心https://www.mp4kan.com/html/7DRkFXAAAAAX.html就不能获取。
前者有一个checkbox在url-left这个div下面
![image](https://github.com/DIYgod/RSSHub/assets/29765197/c7df013e-e55c-4049-8ae5-6786208a989e)
后者这个checkbox直接放到上一级的li下面了
![image](https://github.com/DIYgod/RSSHub/assets/29765197/ab376c7a-f1e3-421a-9635-d46edc4f8f37)

所有checkbox在li下面的链接似乎都没法正常获取。


@zzlufida 你能把路由地址改成`/domp4/detail/:id`吗？要不然这个issue似乎不会被审核

**Comment by savokiss** [comment]
嗯，我这几天看看哈~ 问题应该不大~
