### ISSUE TITLE
Telegram feed no longer works since yesterday

### ISSUE THREAD

**Issue by BarbzYHOOL** [DIYgod/RSSHub#12504]
### What feature is it?

Sry I chose feature because I didn't understand the fields in the "bug report"

Hello,

I'm using rsshub.app to generate some feeds from telegram previews

It worked fine for months until yesterday

Example:

https://rsshub.app/telegram/channel/momotchiii

That page works, but in my RSS reader "fluent reader" it doesn't display anymore (and I haven't updated my RSS reader, there is no new version anyway)

### What problem does this feature solve?

fix telegram issue

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
> That page works

If you're able to see the latest item of an RSS feed on the web page, but unable to view it on your RSS reader, then the issue lies with your RSS reader rather than RSSHub. 
The fact that the latest item is visible on the web page confirms that RSSHub is working correctly.

**Comment by BarbzYHOOL** [comment]
i have no idea why but it works again, while it wasn't working for 2-3 days
and no update from the rss reader either
