### ISSUE TITLE
光谷社区 请求修复，现论坛已更换为过早客

### ISSUE THREAD

**Issue by wxy-skye** [DIYgod/RSSHub#12517]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://rsshub.app/guozaoke/index

### 预期是什么？

现论坛已更换为过早客，guozaoke.com

### 实际发生了什么？

还是之前的论坛地址，已经无法访问

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed since it's indeed a route related issue. Please fill in the issue form properly.
