### ISSUE TITLE
网易云音乐电台节目链接格式错误，导致无法打开。

### ISSUE THREAD

**Issue by lkoujiu** [DIYgod/RSSHub#12529]
### 路由地址

```routes
/163/music/djradio/:id
```

### 完整路由地址

```fullroutes
163/music/djradio/794262404
```

### 相关文档

https://docs.rsshub.app/multimedia.html#wang-yi-yun-yin-yue

### 预期是什么？

预期某一集节目链接是 https://music.163.com/#/program?id=2522200587

### 实际发生了什么？

实际链接是 https://music.163.com/program/2522200587 ，导致无法打开。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://github.com/DIYgod/RSSHub/blob/master/lib/v2/163/music/djradio.js#L49

https://rsshub.app/163/music/djradio/794262404
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ueiu** [comment]
https://music.163.com/#/program?id=2522200587
https://music.163.com/program/2522200587
刚刚试了下，这两个链接都能打开同一个节目吧

**Comment by lkoujiu** [comment]
抱歉才看到，现在是可以的，可能之前网易云的解析出现了问题，谢谢。

**Comment by lkoujiu** [comment]
抱歉才看到，现在是可以的，可能之前网易云的解析出现了问题，谢谢。
