### ISSUE TITLE
小红书抓取错误

### ISSUE THREAD

**Issue by AmintaCCCP** [DIYgod/RSSHub#12520]
### 路由地址

```routes
/xiaohongshu/user/:user_id/notes/:fulltext?
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/593032945e87e77791e03696/notes
```

### 相关文档

https://docs.rsshub.app/social-media.html#xiao-hong-shu

### 预期是什么？

抓取成功

### 实际发生了什么？

Route requested: /user/593032945e87e77791e03696/notes
Error message: Could not find Chrome (ver. 113.0.5672.63). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /user/593032945e87e77791e03696/notes
Node version: v18.16.0
Git Hash: 488cb4b

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
Route requested: /user/593032945e87e77791e03696/notes
Error message: Could not find Chrome (ver. 113.0.5672.63). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /user/593032945e87e77791e03696/notes
Node version: v18.16.0
Git Hash: 488cb4b
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AmintaCCCP** [comment]
更新了一下，报错变了

Route requested: /user/********/notes/
Error message: Waiting for selector `.feeds-container:nth-child(1) .note-item` failed: Protocol error (Runtime.callFunctionOn): Target closed
Helpful Information to provide when opening issue:
Path: /user/********/notes/
Node version: v18.16.0
Git Hash: 488cb4b

**Comment by AmintaCCCP** [comment]
> 这两个错误的出现的原因不一样。
> 
> 
> 
> 第一个Puppeteer说找不到Chromium。但是似乎后面已经解决了？
> 
> 
> 
> 第二个可能是撞上了小红书的反爬机制。个人的经验是多试几次。不知道用代理地址能不能一劳永逸地解决这个问题。

试了几个国家的节点都不行，而且出站是家宽的ip
每次连接都会一分多钟然后超时

**Comment by howerhe** [comment]
RSSHub的举例是正常的。可能还是和部署有些关系。

> 试了几个国家的节点都不行，而且出站是家宽的ip 每次连接都会一分多钟然后超时

“连接都会一分多钟然后超时”指的是什么？

**Comment by AmintaCCCP** [comment]
可以了，用了cf的warf，绕开了反扒

**Comment by chenyucheng0503** [comment]
> 

可以单独针对小红书或者单独针对rsshub套warp吗

**Comment by chenyucheng0503** [comment]
> 可以了，用了cf的warf，绕开了反扒

可以单独针对小红书或者单独针对rsshub套warp吗

**Comment by AmintaCCCP** [comment]
> > 可以了，用了cf的warf，绕开了反扒
> 
> 
> 
> 可以单独针对小红书或者单独针对rsshub套warp吗

可以套,mitm对应域名,然后匹配规则就行.
不过现在warp也不好使了,估计这个路由又坏了.
![image](https://github.com/DIYgod/RSSHub/assets/74942183/a9337030-9e41-433d-bd7f-8d6bd3b839f1)
![image](https://github.com/DIYgod/RSSHub/assets/74942183/1bad89c8-f038-4b37-9763-f50b3ed9d291)

**Comment by howerhe** [comment]
过段时间再试试呢

**Comment by AmintaCCCP** [comment]
挂了挺长时间了,应该是小红书升级反爬了

**Comment by chenyucheng0503** [comment]
> 挂了挺长时间了,应该是小红书升级反爬了

应该是的，之前自己手搓过小红书爬虫为了整理自己3000+的收藏夹，用的是微信小程序的接口。后来小红书直接把那个小程序下架了，换上了一个抓不到包的小程序😂。这公司应该对反爬很重视
