### ISSUE TITLE
请求 微小领微信公众号路由 增加路由可选参数page=？或者单次抓取20篇以上的文章

### ISSUE THREAD

**Issue by HouYiqi** [DIYgod/RSSHub#12535]
### 这是一个什么样的功能？

微小领微信公众号路由目前获取的是指定页面最新的20篇文章 请求增加路由可选参数page=？或者单次抓取20篇以上的文章

### 这个功能可以解决什么问题？

增加路由可选参数page=？来获取最近因微小领平台抓取逻辑导致遗漏的文章（当某个公众号一天推送文章数超过20篇，而微小领平台每日仅抓取一次时就会有文章遗漏）

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
> 很多路由上限10条，无法增大。
> 
> 1. 消耗大量服务器资源。
> 2. 容易被反爬虫。
> 3. 绝大部分过时 feed 没有意义。

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416757360_

> RSS 是用来获取更新，增大条目无意义
> 
> 特殊需求请在相应模块里自行修改

_Originally posted by DIYgod in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416802920_

> rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

_Originally posted by yefoenix in https://github.com/DIYgod/RSSHub/issues/7291#issuecomment-809019525_

> You should not expect RSSHub to retrospectively retrieve every feed item.

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110077752_

> Do not expect it can provide you everything that happens since the stone age.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110091835_

> RSS 强调获取内容更新。若有“一次性获取全部条目”的需求，应设计针对该内容的爬虫。

_Originally posted by nczitzk in https://github.com/DIYgod/RSSHub/issues/9964#issuecomment-1157343694_
