### ISSUE TITLE
热点RSS建设

### ISSUE THREAD

**Issue by aidangaiguo230331** [DIYgod/RSSHub#12542]
### Category

New media

### Website URL

https://api-hot.zyw.asia/

### Website description

这是一个实时获取热点的网站，
有哔哩哔哩 | 微博 | 知乎 | 36 氪 | 百度 | 少数派 | IT 之家 | 澎湃新闻 | 今日头条 | 百度贴吧 | 稀土掘金 | 腾讯新闻这些网站热点新闻。
他们对应的参数分别为bilibili | weibo | zhihu | 36kr | baidu | sspai | ithome | thepaper | toutiao | tieba | juejin | newsqq。
具体的链接举例为https://api-hot.zyw.asia/bilibili      同理可得其他参数的使用方法。
如果想要获取最新的热点，举例为https://api-hot.zyw.asia/bilibili/new       同理可得其他参数的使用方法。
请帮我建设RSS。谢谢！

### What content should be included?

应该包含参数为bilibili | weibo | zhihu | 36kr | baidu | sspai | ithome | thepaper | toutiao | tieba | juejin | newsqq的所有数据。并且有两种获取。一为缓存的数据，二为实时数据。

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Closed in #12527
