### ISSUE TITLE
微信公众号‘罗辑思维’（二十次幂来源）链接失效

### ISSUE THREAD

**Issue by 3040541584** [DIYgod/RSSHub#12553]
### 路由地址

```routes
/wechat/ershicimi/:id
```

### 完整路由地址

```fullroutes
/wechat/ershicimi/M8380y3x
```

### 相关文档

https://docs.rsshub.app/new-media.html#wei-xin-gong-zhong-hao-er-shi-ci-mi-lai-yuan

### 预期是什么？

正常通过二十次幂抓取公众号的RSS文章

### 实际发生了什么？

用着用着链接突然失效了，可是原网页（https://www.[cimidata.com/a/M8380y3x](https://www.cimidata.com/a/M8380y3x)）还在正常更新

### 部署

自建

### 额外信息

```shell
Route requested: /ershicimi/M8380y3x
Error message: wechat-mp: URL host must be "mp.weixin.qq.com", but got https://www.dedao.cn/activity#/activity/index?aid=646b6fce02ca3a4d0a61b052
Helpful Information to provide when opening issue:
Path: /ershicimi/M8380y3x
Node version: v18.16.0
Git Hash: 8e147c7
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/wechat/ershicimi/M8380y3x
```
