### ISSUE TITLE
网易云音乐无法抓取指定歌手歌曲

### ISSUE THREAD

**Issue by yizhimengxin2233** [DIYgod/RSSHub#12554]
### 路由地址

```routes
/163/music/artist/songs/:id
```

### 完整路由地址

```fullroutes
/163/music/artist/songs/15396
```

### 相关文档

https://docs.rsshub.app/multimedia.html#wang-yi-yun-yin-yue

### 预期是什么？

正常输出rss内容

### 实际发生了什么？

显示Error in RSSHub

### 部署

自建

### 部署相关信息

使用zeabur部署

### 额外信息

```shell
Error message: Cannot read properties of undefined (reading 'find')
Helpful Information to provide when opening issue:
Path: /music/artist/songs/15396
Node version: v18.16.0
Git Hash: 809dd41
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
It works
