### ISSUE TITLE
bilibili up主投稿无法抓取

### ISSUE THREAD

**Issue by fengpan0403** [DIYgod/RSSHub#12556]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

抓取up主投稿列表

### 实际发生了什么？

Route requested: /user/video/2267573
Error message: Cannot read properties of undefined (reading 'name')
Helpful Information to provide when opening issue:
Path: /user/video/2267573
Node version: v18.16.0
Git Hash: 3b751bc

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /user/video/2267573
Error message: Cannot read properties of undefined (reading 'name')
Helpful Information to provide when opening issue:
Path: /user/video/2267573
Node version: v18.16.0
Git Hash: 3b751bc
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by TonyRL** [comment]
It works.

**Comment by KawausoJyou** [comment]
> It works.

No, it doesn't work.

**Comment by Left024** [comment]
me too

**Comment by stirp** [comment]
same here. Route requested: /bilibili/followings/video/49081361
Error message: Cannot read property 'name' of undefined

**Comment by fengpan0403** [comment]
/test
`/bilibili/user/video/2267573`

**Comment by fengpan0403** [comment]
/test
`/bilibili/user/video/2267573`

**Comment by fengpan0403** [comment]
/test
`/bilibili/user/video/2267573`

**Comment by Left024** [comment]
My ip has been blocked by bilibili, changing to a different IP resolved the issue

**Comment by KawausoJyou** [comment]
> My ip has been blocked by bilibili, changing to a different IP resolved the issue
After I replace the IP, it prompts "Error message: Cannot read properties of undefined (reading 'name')"
