### ISSUE TITLE
sis001

### ISSUE THREAD

**Issue by msfind** [DIYgod/RSSHub#12559]
### 类型

论坛

### 网站地址

http://sis001.com/

### 网站描述

http://sis001.com/forum/forum-200-1.html

### 需要生成什么内容？

无法订阅

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/bbs.html#di-yi-hui-suo
