### ISSUE TITLE
纽约时报-新闻简报无法抓取

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#12565]
### 路由地址

```routes
/nytimes/daily_briefing_chinese
```

### 完整路由地址

```fullroutes
/nytimes/daily_briefing_chinese
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao

### 预期是什么？

获得新闻标题及内容。

### 实际发生了什么？

显示 "Looks like something went wrong" 页面。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /daily_briefing_chinese

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /daily_briefing_chinese
Node version: v18.16.0
Git Hash: 4e2c3ef
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by whaler-ragweed** [comment]
纽约时报-新闻简报似已不再更新，网站上显示最后一篇文章停留在6/15。
