### ISSUE TITLE
Missing locale / country for Epic Games Store

### ISSUE THREAD

**Issue by KatyPurry** [DIYgod/RSSHub#12563]
### Routes

```routes
/epicgames/freegames/:locale?/:country?
```

### Full routes

```fullroutes
https://rsshub.app/epicgames/freegames/fr_FR/fr_FR/
https://rsshub.app/epicgames/freegames/de_DE/de_DE/
```

### Related documentation

https://docs.rsshub.app/en/game.html#dekudeals

### What is expected?

```
Looks like something went wrong

Route requested: /freegames/de_DE/de_DE/

Error message: Cannot read properties of null (reading 'elements')
```

### What is actually happening?

I tried few countries / locales but its return error 404 each time.  Only us_US seems work. Is it intendend ? Thank you

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Looks like something went wrong

Route requested: /freegames/de_DE/de_DE/

Error message: Cannot read properties of null (reading 'elements')

Helpful Information to provide when opening issue:
Path: /freegames/de_DE/de_DE/
Node version: v18.16.0
Git Hash: 65b6f94
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Yorzaren** [comment]
@KatyPurry I think it's still working, but EpicGames changed how it handles countries. 

These links should work:
https://rsshub.app/epicgames/freegames/fr_FR/FR/
https://rsshub.app/epicgames/freegames/de_DE/DE/

**Comment by TonyRL** [comment]
/test
```routes
/epicgames/freegames/fr_FR/FR
```

**Comment by TonyRL** [comment]
<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/user-attachments/assets/83348a22-8c24-4d38-81a8-d3e30ae3d68a)
</details>
