### ISSUE TITLE
请求生成美国国家地理官网rss

### ISSUE THREAD

**Issue by jy53655** [DIYgod/RSSHub#12592]
### 类型

出行旅游

### 网站地址

https://www.nationalgeographic.com/

### 网站描述

美国国家地理

### 需要生成什么内容？

LATEST STORIES的最新文章

### 额外描述

最好是能抓取全文，谢谢。

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by miles170** [comment]
> 其实还是无法使用，打不开[https://rsshub.app/nationalgeographic/latest-stories。结果显示：Route](https://rsshub.app/nationalgeographic/latest-stories%E3%80%82%E7%BB%93%E6%9E%9C%E6%98%BE%E7%A4%BA%EF%BC%9ARoute) requested: /latest-stories Error message: Cannot read properties of undefined (reading 'map') Helpful Information to provide when opening issue: Path: /latest-stories Node version: v18.16.0 Git Hash: 44f2121

试试看最新的 commit, 应可正常显示了

**Comment by jy53655** [comment]
非常感谢，能用了！
