### ISSUE TITLE
色花堂图片无法正常显示

### ISSUE THREAD

**Issue by JamYiz** [DIYgod/RSSHub#12599]
### 路由地址

```routes
/sehuatang/:subforumid?/:type?
/sehuatang/user/:uid
```

### 完整路由地址

```fullroutes
https://rsshub.app/sehuatang/
```

### 相关文档

https://docs.rsshub.app/multimedia.html#se-hua-tang

### 预期是什么？

正常显示图片

### 实际发生了什么？

所有图片均不显示

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
已拦截跨源请求：同源策略禁止读取位于 https://sentry.innologica.com/api/2/envelope/?sentry_key=b2b1f03ae7014af78358c1715cb34b80&sentry_version=7 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by chouchouxsl** [comment]
防盗链 和 使用模板都试了  也不显示图片 求解决

**Comment by JamYiz** [comment]
> 防盗链 和 使用模板都试了 也不显示图片 求解决

使用header editor给图片添加防盗链，发送sehuatang的referer

**Comment by chouchouxsl** [comment]
大佬可否细说 我用的是本地的阅读器 reeder 5 这种方法是不是需要网页版的阅读器
