### ISSUE TITLE
rsshub 连接拒绝

### ISSUE THREAD

**Issue by primejava** [DIYgod/RSSHub#12601]
### 路由地址

```routes
/javdb/actors/:id/:filter?
```

### 完整路由地址

```fullroutes
https://rsshub.app/javdb/actors/QV2x9
```

### 相关文档

https://rsshub.app/javdb/actors

### 预期是什么？

希望能够稳定地拉取内容。

### 实际发生了什么？

自建RSSHub服务，没有绑定域名，结合FreshRss使用。添加订阅后当天可以使用，并且设置的爬取时间间隔为一天一次。
但从第二天开始就全部失效。
FreshRss检查订阅连接有效性返回 Server returned [Errno 111] Connection refused。

### 部署

自建

### 额外信息

```shell
FreshRss检查订阅连接有效性返回 Server returned [Errno 111] Connection refused。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Please provide logs from RSSHub instead.

**Comment by primejava** [comment]
Git Hash:3b751bc
Request Amount:66
Request Frequency:0.031 times/minute
Cache Hit Ratio:0.167
Memory Usage:29.995008 MB
CPU Usage:0%
Run Time:35.05 hour(s)
Hot Routes:18  /user/video/:uid/:disableEmbed?
9  /bilibili/user/video/:uid/:disableEmbed?
6  /javbus/([\w/-]+)?/
3  /
2  /javdb/actors/:id/:filter?
2  /([\w/-]+)?/
1  /javdb/makers/:id/:filter?
1  /javlibrary/mostwanted/:language?/:mode?
1  /javdb/tags/:query?/:category?
1  /javlibrary/bestrated/:language?/:mode?
1  /movie/weekly/:type?
1  /movie/playing/:score
1  /actors/:id/:filter?
1  /makers/:id/:filter?
Hot Paths:26  /bilibili/user/video/504715181
6  /
4  /javbus/star/xkf
4  /javbus/studio/2p
3  /javbus/studio/75
3  /javdb/actors/GgVz
3  /javdb/makers/q6
2  /javdb/actors/QV2x9
2  /javbus/star/b64
2  /javlibrary/mostwanted/cn
2  /javdb/tags/c6=41
2  /javlibrary/bestrated/cn
2  //bilibili/user/video/628122353
1  /javbus/star/2jv
1  /nice%20ports%2C/Tri%6Eity.txt%2ebak
1  /douban/movie/weekly
1  /bilibili/user/video/628122353
1  /douban/movie/playing/7.5
Hot Error Routes:18  /user/video/:uid/:disableEmbed?
2  /([\w/-]+)?/
1  /movie/weekly/:type?
1  /movie/playing/:score
1  /actors/:id/:filter?
1  /makers/:id/:filter?
Hot Error Paths:17  /user/video/504715181
2  /
2  //bilibili/user/video/628122353
1  /nice%20ports%2C/Tri%6Eity.txt%2ebak
1  /movie/weekly
1  /user/video/628122353
1  /movie/playing/7.5
1  /star/xkf
1  /actors/GgVz
1  /studio/2p
1  /makers/q6

**Comment by primejava** [comment]
this is my log，please look it 
Route requested: /star/xkf
Error message: getaddrinfo EAI_AGAIN www.javbus.com: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /star/xkf
Node version: v18.16.0
Git Hash: 3b751bc

**Comment by TonyRL** [comment]
> target website might be blocking our access

Make sure your instance can visit www.javbus.com.
