### ISSUE TITLE
“大连理工大学教务处-重要通告”失效

### ISSUE THREAD

**Issue by ProudBenzene** [DIYgod/RSSHub#12635]
### 路由地址

```routes
/dut/teach/:category?
```

### 完整路由地址

```fullroutes
/dut/teach/:category?
```

### 相关文档

https://docs.rsshub.app/university.html#da-lian-li-gong-da-xue-jiao-wu-chu

### 预期是什么？

可以成功查看教务处“重要通告”内容

### 实际发生了什么？

已经很久没有收到教务处的RSS信息，访问显示Something Went Wrong

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

macOS 12.6.6，Node 17.8.0，Docker 4.19.0

### 额外信息

```shell
Route requested: /teach/zytg
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /teach/zytg
Node version: v18.16.0
Git Hash: bd759b4
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by BeautyyuYanli** [comment]
Hello！近期教务处所有子栏目都被设为内网保护，你可能要在校园网内自己部署 rsshub 使用。。

**Comment by ProudBenzene** [comment]
你好！可以简单告诉我具体应该怎么在校园网内部署嘛🥲我有点小白 不是很懂怎么让部署可以通过校园网或者校园VPN

**Comment by BeautyyuYanli** [comment]
> 你好！可以简单告诉我具体应该怎么在校园网内部署嘛🥲我有点小白 不是很懂怎么让部署可以通过校园网或者校园VPN

现在也许只能你自己拿一台校园网内的机器自己部署使用了。。部署就是按本项目的文档的做法

**Comment by ProudBenzene** [comment]
> > 你好！可以简单告诉我具体应该怎么在校园网内部署嘛🥲我有点小白 不是很懂怎么让部署可以通过校园网或者校园VPN
> 
> 现在也许只能你自己拿一台校园网内的机器自己部署使用了。。部署就是按本项目的文档的做法

好的，我试一下，谢谢！
