### ISSUE TITLE
[bilibili user] routes broken

### ISSUE THREAD

**Issue by quzzimi** [DIYgod/RSSHub#12642]
### Routes

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### Full routes

```fullroutes
/bilibili/user/video/2267573
```

### Related documentation

https://docs.rsshub.app/social-media.html#bilibili

### What is expected?

rss feed should show up

### What is actually happening?

broken route

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

ubuntu 20

### Additional info

```shell
2|rsshub  | error: Error in /bilibili/user/video/161775300: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by TonyRL** [comment]
It works.
