### ISSUE TITLE
Tamilmv

### ISSUE THREAD

**Issue by Anandhuanandhue** [DIYgod/RSSHub#12651]
### Category

Social Media

### Website URL

https://www.1tamilmv.cafe/

### Website description

Website which provides new movies 

### What content should be included?

Name, Magnet link, file size

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://www.1tamilmv.cafe/index.php?/forums/forum/10-predvd-dvdscr-cam-tc.xml/
https://www.1tamilmv.cafe/index.php?/forums/forum/11-web-hd-itunes-hd-bluray.xml/
...

**Comment by TanujairamV** [comment]
But this doesnt provides the magnet link
