### ISSUE TITLE
picuki route empty

### ISSUE THREAD

**Issue by slikie** [DIYgod/RSSHub#12657]
### Routes

```routes
/picuki/profile/:id/:functionalFlag?
```

### Full routes

```fullroutes
/picuki/profile/stefaniejoosten
/picuki/profile/newjeans_official/10
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#picuki

### What is expected?

Return feed of picuki

### What is actually happening?

Error message: this route is empty

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
-
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/picuki/profile/stefaniejoosten
/picuki/profile/stefaniejoosten/0
/picuki/profile/stefaniejoosten/1
```

**Comment by slikie** [comment]
/test
```
/picuki/profile/stefaniejoosten
```

**Comment by TonyRL** [comment]
/test
```routes
/picuki/profile/stefaniejoosten
/picuki/profile/stefaniejoosten/0
/picuki/profile/stefaniejoosten/1
```
