### ISSUE TITLE
[Twitter] No media support on nsfw accounts

### ISSUE THREAD

**Issue by Sorinmar** [DIYgod/RSSHub#12668]
### Routes

```routes
/twitter/media/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/media/reiq
/twitter/media/bartolomeobari2
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter-user-media

### What is expected?

RSS feed

### What is actually happening?

error page

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
NA
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Duplicate of #11582
