### ISSUE TITLE
docs.rsshub.app页面的搜索功能有问题，会无法直达搜索结果

### ISSUE THREAD

**Issue by zzz6839** [DIYgod/RSSHub#12724]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

当在搜索栏输入任何关键词时，能直达对应的搜索结果

### 实际发生了什么？

以pixiv为例，当在搜索栏输入“pixiv”之后敲击“ENTER”键或者点击“pixiv”的关联词，页面会滚动在"FACEBOOK"的关键词一栏，需要二次输入“pixiv”才能直达相关联的搜索。
![image](https://github.com/DIYgod/RSSHub/assets/57741549/99ed46eb-7a10-4ac8-8c5f-229f311800e2)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

WIN11，windows edge: 114.0.1823.58 

### 额外信息

```shell
这个bug中英文页面都存在
如果你搜索的是“Facebook”，他页面会滚动到“CuriousCat”相关词条
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #7550
