### ISSUE TITLE
希望增加香港电台 即时新闻 路由

### ISSUE THREAD

**Issue by wuabuhuan** [DIYgod/RSSHub#12730]
### 这是一个什么样的功能？

可以即时的展示所有地区和各个方面的新闻

### 这个功能可以解决什么问题？

可以即时的展示所有地区和各个方面的新闻

### 额外描述

https://news.rthk.hk/rthk/ch/latest-news.htm

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
This is indeed a new RSS proposal.
