### ISSUE TITLE
APNews "Cannot read properties of null (reading '1')"

### ISSUE THREAD

**Issue by georgecwan** [DIYgod/RSSHub#12733]
### Routes

```routes
/apnews/topics/:topic?
```

### Full routes

```fullroutes
/apnews/topics/:topic?
```

### Related documentation

https://docs.rsshub.app/en/traditional-media.html#ap-news

### What is expected?

RSS feed XML data is returned

### What is actually happening?

Route requested: /topics/apf-topnews
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /topics/apf-topnews
Node version: v18.16.1
Git Hash: 7775ee5

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
N/A
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by GcWan** [comment]
The route does indeed exist!

**Comment by GcWan** [comment]
Fixed route in issue description

**Comment by dzx-dzx** [comment]
改版后的AP页面看来有些复杂……
