### ISSUE TITLE
公众号（搜狗来源）失效

### ISSUE THREAD

**Issue by zhuxining** [DIYgod/RSSHub#12745]
### 路由地址

```routes
/wechat/sogou/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/wechat/sogou/qimao0908
```

### 相关文档

https://docs.rsshub.app/new-media.html#wei-xin-gong-zhong-hao-sou-gou-lai-yuan

### 预期是什么？

得到该id对应公众号下rss订阅

### 实际发生了什么？

Route requested: /sogou/qimao0908
Error message: getaddrinfo ENOTFOUND weixin.sogou.comundefined: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /sogou/qimao0908
Node version: v18.16.1
Git Hash: 623d890

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /sogou/qimao0908
Error message: getaddrinfo ENOTFOUND weixin.sogou.comundefined: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /sogou/qimao0908
Node version: v18.16.1
Git Hash: 623d890
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/wechat/sogou/qimao0908
```

**Comment by TonyRL** [comment]
It works
