### ISSUE TITLE
小红书用户笔记路由无法使用

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#12740]
### 路由地址

```routes
/xiaohongshu/user/:user_id/notes/:fulltext?
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/593032945e87e77791e03696/notes
```

### 相关文档

https://docs.rsshub.app/social-media.html#xiao-hong-shu

### 预期是什么？

预期返回的内容是小红书该用户的笔记rss订阅源。

### 实际发生了什么？

Looks like something went wrong

Route requested: /user/593032945e87e77791e03696/collect
Error message: Waiting for selector `.feeds-container:nth-child(1) .note-item` failed: Protocol error (Runtime.callFunctionOn): Target closed
Helpful Information to provide when opening issue:
Path: /user/593032945e87e77791e03696/collect
Node version: v18.16.1
Git Hash: 623d890
        
If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
我在我自建的服务器上也测试过，这是logs：
info: /xiaohongshu/user/593032945e87e77791e03696/collect, user IP: [😜]
error: Error in /user/593032945e87e77791e03696/collect: Waiting for selector `.feeds-container:nth-child(1) .note-item` failed: Protocol error (Runtime.callFunctionOn): Target closed
这个问题在用户收藏上也有相同问题，专辑路由表现正常，求求大神修复下，很着急看摸鱼书🥺
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by LLLLLFish** [comment]
路由填错了sry

**Comment by howerhe** [comment]
Looks like the problem is for `collect`, not `notes`. And the full text version of `notes` was implemented using in a different way from the regular one.

The error you encountered seems to be a common one. Maybe you can try to refresh the page after waiting for a few minutes?

**Comment by leenacl** [comment]
> 路由填错了sry

你好，请问问题解决了，这个我看之前的说法应该是反爬机制的问题。
