### ISSUE TITLE
twitter路由失效

### ISSUE THREAD

**Issue by ddaodan** [DIYgod/RSSHub#12751]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/norioo_
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter-yong-hu-shi-jian-xian

### 预期是什么？

正常返回推特内容

### 实际发生了什么？

Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

自建

### 额外信息

```shell
Helpful Information to provide when opening issue: 
Path: /twitter/user/norioo_
Node version: v14.21.3
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #12732
