### ISSUE TITLE
Unable to subscribe  Annual Reviews

### ISSUE THREAD

**Issue by VectorZhao** [DIYgod/RSSHub#12756]
### 路由地址

```routes
/annualreviews/:earth
```

### 完整路由地址

```fullroutes
https://xxxxxxxx.xx/annualreviews/earth
```

### 相关文档

https://docs.rsshub.app/journal.html#annual-reviews

### 预期是什么？

subscribe Annual Reviews

### 实际发生了什么？

can not subscribe

### 部署

自建

### 额外信息

```shell
訂閲至Tiny Tiny RSS 

无法订阅 https://xxxxx.xxx/annualreviews/earth。
无法下载订阅源的 URL。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Lao-Tz** [comment]
I have the same problem.
