### ISSUE TITLE
网易云音乐用户歌单RSS返回报错

### ISSUE THREAD

**Issue by Jefffish09** [DIYgod/RSSHub#1276]
### 路由地址
/ncm/user/playlist/:uid

### 预期是什么？
正常返回RSS。

### 实际发生了什么？
实际返回报错信息
RSSHub 发生了一些意外:
TypeError: Cannot destructure property `nickname` of 'undefined' or 'null'.
    at module.exports (/app/routes/ncm/userplaylist.js:25:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/44800122/49839642-ea4eaf80-fdea-11e8-96a7-8934299b066d.png)

**Comment by xyqfer** [comment]
我试了下本地是好的，自搭的在国外的也是跟上面的一样报错，目测是云音乐限制了海外 ip 的访问吧。。

**Comment by Jefffish09** [comment]
@DIYgod 
https://rsshub.app/ncm/user/playlist/45441555
目前还是报错，是不是像楼上所说的这个api限制了海外ip的访问？

**Comment by Jefffish09** [comment]
@xyqfer 竟然这样，我都没注意，谢谢你的提醒！

**Comment by DIYgod** [comment]
@Jefffish09 是，建议自建
