### ISSUE TITLE
财新网支持模块配置Cookie以获取付费内容

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#12765]
### 这是一个什么样的功能？

财新网支持模块配置Cookie以获取付费内容（https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi）
比如端传媒、南方周末

### 这个功能可以解决什么问题？

直接获取付费内容全文

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by rainrdx** [comment]
曾经想做过，后来发现财新鉴权比较复杂。希望有高手会写。

**Comment by learningdog1** [comment]
希望有高手会写
