### ISSUE TITLE
豆瓣用户广播无法正常显示图片

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#12786]
### 路由地址

```routes
douban/people/:userid/status/:routeParams
```

### 完整路由地址

```fullroutes
douban/people/1385730/status/readable=1&showAuthorInTitle=0&showEmojiForRetweet=1&showRetweetTextInTitle=1&showTimestampInDescription=1&showComments=1
```

### 相关文档

https://docs.rsshub.app/social-media.html#dou-ban-yong-hu-guang-bo

### 预期是什么？

正常显示用户广播附图

### 实际发生了什么？

图片无法加载
![image](https://github.com/DIYgod/RSSHub/assets/92703641/1d5334b6-2f1e-4e2c-95d6-87657d41bffc)

直接打开图片链接显示如下：
{
    "code": "40310999",
    "msg": "edge rule triggered"
}
![image](https://github.com/DIYgod/RSSHub/assets/92703641/dd76b125-a5e0-4c60-a9b5-d58a58924a3e)

### 部署

自建

### 部署相关信息

OS: Linux, Node: v18.16.1, Docker: v20.10.21

### 额外信息

```shell
{
    "code": "40310999",
    "msg": "edge rule triggered"
}
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KawausoJyou** [comment]
用户广播
[支持浏览器扩展](https://github.com/DIYgod/RSSHub-Radar)
作者: [@alfredcai](https://github.com/alfredcai)
举例: https://rsshub.app/douban/people/62759792/status
路由: douban/people/:userid/status/:routeParams
参数:
userid, 必选 - 整数型用户 id
routeParams, 必选 - 额外参数；见下
---------------------------
为什么会无法匹配呢？

**Comment by TonyRL** [comment]
douban has reverted its changes on referrer policy
