### ISSUE TITLE
twitter 列表时间线获取失败，提示需要使用v2 api

### ISSUE THREAD

**Issue by yzkoori** [DIYgod/RSSHub#12794]
### 路由地址

```routes
/twitter/list/:id/:name/:routeParams?
```

### 完整路由地址

```fullroutes
/list/Twitter/Official%20Twitter%20Accounts
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

能正常获取时间线推文

### 实际发生了什么？

无法获取并报错code 453，该问题从07/13 4:00(UTC+8)左右开始出现，一直持续，之前可正常使用.

### 部署

自建

### 部署相关信息

OS: Debian GNU/Linux 11 x86_64(Py3.7.9) Node: v18.16.0

### 额外信息

```shell
Route requested: /list/Twitter/Official%20Twitter%20Accounts
Error message: Error: Request failed with code 403 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product (Twitter code 453)
    at RequestHandlerHelper.createResponseError (/app/RSSHub/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (/app/RSSHub/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:252:25)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Helpful Information to provide when opening issue:
Path: /list/Twitter/Official%20Twitter%20Accounts
Node version: v18.16.0
Git Hash: b33499b

最近一个月网络上有相关问题报告，除了将api更换为v2外好像没有其他有效方法
```

### 这不是重复的 issue

- [x] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by shawn8888** [comment]
完全同样的错误。期待高手解决。

**Comment by ZZzzzioi** [comment]
同样遇到了这个问题，前几天V1应该还能用，估计是马斯克更新完之后不行了

**Comment by shawn8888** [comment]
路由地址
/twitter/followings/:id/:routeParams?

完整路由地址
Example:
https://rsshub.app/twitter/followings/DIYgod

**Comment by KawausoJyou** [comment]
同样的错误

**Comment by shawn8888** [comment]
莫非这个问题无解？还是用推特RSS的人太少？

**Comment by yzkoori** [comment]
本来想整个v2试试但是看官方说明跟v1.1差太多了，等大佬吧，没有rss爬推文这日子没法过了（

**Comment by shawn8888** [comment]
> 本来想整个v2试试但是看官方说明跟v1.1差太多了，等大佬吧，没有rss爬推文这日子没法过了（

我还以为是v2收费了。免费的午餐没有了。原来只是API版本更新？

**Comment by ZZzzzioi** [comment]
大手子快来救救小趴菜们

**Comment by wqh0109663** [comment]
> > 本来想整个v2试试但是看官方说明跟v1.1差太多了，等大佬吧，没有rss爬推文这日子没法过了（
> 
> 我还以为是v2收费了。免费的午餐没有了。原来只是API版本更新？

v2是收费了啊 而且base功能只有发推文 并没有获取的 只有订阅才有获取信息的接口

**Comment by MetaverseMan** [comment]
已经购买了basic版本 但是访问api都是453啥情况 急啊

**Comment by TonyRL** [comment]
Closed in 9032153c7de4c9ca189482d495696986e9795106

**Comment by Azureki** [comment]
为什么close？
修复的是 `/user/` 路由，时间线并没有修复。

**Comment by TonyRL** [comment]
Closed in 1bc24075c75a546b7fe2c2944da0b02023ca1b0f
