### ISSUE TITLE
会员购看不到图？

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#1279]
### 路由地址
https://mall.bilibili.com/date.html?page=new
### 预期是什么？
应该看到图
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/33424662/49910034-33226900-febc-11e8-8f23-3728a7b2777d.png)
![image](https://user-images.githubusercontent.com/33424662/49910045-3cabd100-febc-11e8-8e1e-6e034db006a7.png)

**Comment by DIYgod** [comment]
@xyqfer 我这里正常，也有可能是你的阅读器去掉了图片的 referrerpolicy 属性
