### ISSUE TITLE
自建】小宇宙-发现生成RSS失败

### ISSUE THREAD

**Issue by aaro-n** [DIYgod/RSSHub#12811]
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
/xiaoyuzhou?key=访问密钥
```

### Related documentation

https://docs.rsshub.app/multimedia.html#xiao-yu-zhou-fa-xian

### What is expected?

正常输出小宇宙发现

### What is actually happening?

无法正常输出RSS，7月15号上午还可以正常使用，已经重新配置`XIAOYUZHOU_TOKEN`变量，环境变量已经抓包配置`XIAOYUZHOU_ID` `XIAOYUZHOU_TOKEN`，RSSHub抓取小宇宙播客正常

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Docker

### Additional info

```shell
Route requested: /
Error message: Cannot read properties of undefined (reading 'author')
Helpful Information to provide when opening issue:
Path: /
Node version: v18.16.1
Git Hash: b9c8321
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by aaro-n** [comment]
今天更新Docker镜像，小宇宙发现又正常了，关闭此问题。

**Comment by brandon0824** [comment]
你好，请问能否大概说说如何抓包小宇宙的两个变量？

**Comment by aaro-n** [comment]
@brandon0824 可以通过IOS端和android端抓取
# android （已放弃）
android 高版本无法手动导入证书到根证书，导入的证书在用户证书下，抓取小宇宙APP里的内容无法解析，只做记录，上次成功抓取还是半年前。
需要的APP：低于Android 10，HttpCanary（开发者已放弃），高版本，Reqable，需要将证书安装到根证书
# iOS端（在用）
需要的APP：Reqable，小宇宙app
1. 下载并安装reqable，按照要求，导入生成的证书。
2. 关闭所有后台APP，打开reqable抓包，打开小宇宙并登录，小宇宙之前只要打开app就可以抓取到那两个变量，现在要登录后出现一次，之后不在出现。
3. 在小宇宙app看到"发现"刷新了，切换reqable，关闭抓包，从头开始检查抓包的内容。在这里会有所需要的变量。

**Comment by brandon0824** [comment]
> @brandon0824 可以通过IOS端和android端抓取
> 
> # android （已放弃）
> android 高版本无法手动导入证书到根证书，导入的证书在用户证书下，抓取小宇宙APP里的内容无法解析，只做记录，上次成功抓取还是半年前。 需要的APP：低于Android 10，HttpCanary（开发者已放弃），高版本，Reqable，需要将证书安装到根证书
> 
> # iOS端（在用）
> 需要的APP：Reqable，小宇宙app
> 
> 1. 下载并安装reqable，按照要求，导入生成的证书。
> 2. 关闭所有后台APP，打开reqable抓包，打开小宇宙并登录，小宇宙之前只要打开app就可以抓取到那两个变量，现在要登录后出现一次，之后不在出现。
> 3. 在小宇宙app看到"发现"刷新了，切换reqable，关闭抓包，从头开始检查抓包的内容。在这里会有所需要的变量。

感激不尽！
