### ISSUE TITLE
部分微博页面打开报错

### ISSUE THREAD

**Issue by cooper1x** [DIYgod/RSSHub#1284]
### 路由地址
https://rss.shuxinfe.com/weibo/user2/1640663582
### 预期是什么？
正常打开页面
### 实际发生了什么？
抱歉，你访问的页面地址有误，或者该页面不存在。
这个页面提示：https://weibo.com/sorry?pagenotfound
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  centos6 x64  |
| Node version       |       11      |
| if Docker, version |     no        |

### 额外信息（日志、报错等）
```
[root@host ~]# pm2 log RSSHub/
[TAILING] Tailing last 15 lines for [RSSHub/] process (change the value with --lines option)
```

**Comment by xyqfer** [comment]
现在试了下是好的，目测是微博偶尔抽风吧。。。

**Comment by xyqfer** [comment]
理解错了，是指的链接挂了。。= =

**Comment by xyqfer** [comment]
http://weibo.com/1640663582/H74rGjOSV 试了下第一条微博的链接，如果是未登录情况下点进去的话确实会跟你说的一样报 pagenotfound 的错误，登录之后可以正常查看。。。

**Comment by sinchang** [comment]
https://rsshub.app/weibo/user/1195230310 418 了，能 fix 下吗？ @DIYgod

**Comment by SettingDust** [comment]
@sinchang 正常显示

**Comment by sinchang** [comment]
@SettingDust thanks, 是挂代理的原因。
