### ISSUE TITLE
Please deliver RSS feeds for all research topics on academia.edu 

### ISSUE THREAD

**Issue by jbionic2016** [DIYgod/RSSHub#12849]
### Category

Scientific Journal

### Website URL

https://www.academia.edu

### Website description

Academic papers on various research topics

### What content should be included?

There are various research topics available on academia.edu. The complete list of topics can be found at https://www.academia.edu/topics

The below examples show direct links for such topics as Semantic Web, Early Christianity, Content Based Image Retrieval
https://www.academia.edu/Documents/in/Semantic_Web/MostRecent 
https://www.academia.edu/Documents/in/Early_Christianity/MostRecent
https://www.academia.edu/Documents/in/Content-Based_Image_Retrieval/MostRecent

Ideally, for each topic there must be a RSS link to facilitate the process of getting regular updates

Since all papers come out in different languages, while every user would normally read only in a few languages, it is also advisable to make a option in order to filter out any results that come out in languages other than the user can read ( I don't know if this is possible yet because this requires an artificial-intelligence engine to process new papers in order to determine the language identifier for each paper)

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by K33k0** [comment]
I've done the basics. I feel like the language analysis is a little out of scope, and will almost certainly add extra dependencies and probably back end configuration. However, if following an interest/category is all you want. Consider it done (providing the PR is approved)

**Comment by jbionic2016** [comment]
I can't find a parameter that would make the route extract the newest articles from a topic

![IMG_20240602_095129](https://github.com/DIYgod/RSSHub/assets/23212486/627633d2-e671-41d5-9502-34ee2a0a07ec)

**Comment by K33k0** [comment]
It should be pulling the most recent/newest papers first by default. The URL it pulls is `https://www.academia.edu/Documents/in/${interest}/MostRecent`. https://github.com/DIYgod/RSSHub/blob/a0bee48d9f9d2db78e81f37194a9efc2b1a21645/lib/routes/academia/topics.ts#L24C36-L24C96
