### ISSUE TITLE
提供 `multimedia_hotlink_template` 对应的环境变量

### ISSUE THREAD

**Issue by bennyyip** [DIYgod/RSSHub#12841]
### 这是一个什么样的功能？

目前 `image_hotlink_template` 有对应的环境变量 `HOTLINK_TEMPLATE`。
但是 `multimedia_hotlink_template` 并没有对应的环境变量，添加 feed 要手动填写 URL参数，不是很方便。希望能提供环境变量配置。

或者在 RSSHub Radar 让用户配置各个 route 的 URL 参数?

相关代码： https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/anti-hotlink.js#L117

### 这个功能可以解决什么问题？

免去添加 feed 手动填写 multimedia_hotlink_template 的麻烦

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by bestlzk** [comment]
能否将 `HOTLINK_TEMPLATE ` 环境变量也应用于 `multimediaHotlinkTemplate`，在代码中添加：

```typescript
multimediaHotlinkTemplate = filterPath(ctx.req.path) ? config.hotlink.template : undefined;
```

https://github.com/DIYgod/RSSHub/blob/52e72e2c60e77df7ed877308b522e760340b57da/lib/middleware/anti-hotlink.ts#L119
