### ISSUE TITLE
喜马拉雅rss拉取错误

### ISSUE THREAD

**Issue by stefaneliu** [DIYgod/RSSHub#12861]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/ximalaya/album/299146
/ximalaya/album/39488639/0/shownote
```

### 相关文档

https://docs.rsshub.app/multimedia.html#xi-ma-la-ya

### 预期是什么？

可以抓取喜马拉雅rss

### 实际发生了什么？

RSS页面出现如下错误信息：

Looks like something went wrong
Route requested: /ximalaya/album/299146
Error message: Cannot read properties of undefined (reading 'categoryTitle')
Helpful Information to provide when opening issue:
Path: /ximalaya/album/299146
Node version: v18.17.0
Git Hash: 7defaea

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无论是rsshub还是自建，也无论是哪个节目，喜马拉雅的rss抓取都是这个错误结果。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Shane-Meng** [comment]
没有老大维护这个路由了吗？一直靠他转播客，以前坏过几次，索幸都有人修。

**Comment by wangfeng35** [comment]
+10086 求修复

**Comment by Shane-Meng** [comment]
同好们，我尽力了，将原作者们骚扰了个遍，这已经是我第三次发邮件请他们关注issue了，要么不回复，要么已经无暇兼顾此小项目。开源产品的宿命就是这样？不能指望作者一直为爱发电？各位同好也发动下资源吧，看看有没有可能再挽救一下。

**Comment by Shane-Meng** [comment]
感谢leo，应该是可以用了

**Comment by stefaneliu** [comment]
> 感谢leo，应该是可以用了

你好，自建docker的话是要更新容器后才能恢复使用的是吗？谢谢。

**Comment by Shane-Meng** [comment]
是的
