### ISSUE TITLE
信报财经新闻RSS失效

### ISSUE THREAD

**Issue by ufo1024k** [DIYgod/RSSHub#12860]
### 路由地址

```routes
/hkej/:category?
```

### 完整路由地址

```fullroutes
/hkej/:category?
```

### 相关文档

https://rsshub.app/hkej/index

### 预期是什么？

RSS可以稳定 https://rsshub.app/hkej/index

### 实际发生了什么？

一直不能用，希望能修復 ，謝謝！

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/hkej/index
```

**Comment by TonyRL** [comment]
<details><summary>Feed screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/caf494d9-3d97-45ed-a79f-a6d7b6db2b5a)
</details>

Please note that the demo instance is provided on an 'as-is' basis. Host your own instance if you want more stability.
