### ISSUE TITLE
github订阅多个文件的 commit 无法成功

### ISSUE THREAD

**Issue by hiby-arch** [DIYgod/RSSHub#12865]
### 路由地址

```routes
/github/file/:user/:repo/:branch/:filepath+
```

### 完整路由地址

```fullroutes
https://rsshub.app/github/file/DIYgod/RSSHub/master/lib/router.js,/lib/config.js
```

### 相关文档

https://docs.rsshub.app/programming.html#github

### 预期是什么？

预期订阅成功多个，但不知格式如何撰写，无法订阅成功
也希望在帮助文档中基于实例。

原始文档内容：
路由: /github/file/:user/:repo/:branch/:filepath+

参数:

user, 必选 - 用户名
repo, 必选 - 仓库名
branch, 必选 - 分支名
filepath, 单个或多个 - 文件路径

### 实际发生了什么？

返回报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
You have to subscribe to 2 RSS feeds if you want to monitor changes for 2 files. "One or more" in the docs mean it will match the rest of the URL path instead of stopping at `master` only
