### ISSUE TITLE
All Threads.net profile RSS feeds are broken

### ISSUE THREAD

**Issue by untitaker** [DIYgod/RSSHub#12871]
### Routes

```routes
/threads/:user/:routeParams?
```

### Full routes

```fullroutes
/threads/zuck
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#threads

### What is expected?

valid rss feed

### What is actually happening?

500 internal server error

```
Route requested: /zuck

Error message: Cannot read properties of null (reading 'match')

Helpful Information to provide when opening issue:
Path: /zuck
Node version: v18.17.0
Git Hash: aea62bf
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
tried multiple profiles, all broken
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by ninboy** [comment]
/test

```
/threads/zuck
```

**Comment by ninboy** [comment]
/test
```routes
/threads/zuck
```

**Comment by ninboy** [comment]
The route is working. This is consistent with my local testing.
<img width="609" alt="image" src="https://github.com/DIYgod/RSSHub/assets/34670/08ee6044-3d85-4186-b3f2-e0d00899541a">

**Comment by TonyRL** [comment]
It works.

**Comment by untitaker** [comment]
odd. it must have been flaky. everything works now.
