### ISSUE TITLE
Unable to access content from a few Twitter users.

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#12873]
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/waylybaye/readable=1&showEmojiForRetweetAndReply=1&showQuotedInTitle=1&excludeReplies=1
/twitter/user/+24124203/readable=1&showEmojiForRetweetAndReply=1&showQuotedInTitle=1&excludeReplies=1
```

### Related documentation

https://docs.rsshub.app/social-media.html#twitter-yong-hu-shi-jian-xian

### What is expected?

Accessing Twitter user content normally.

### What is actually happening?

Looks like something went wrong
Route requested: /user/waylybaye/readable=1&showEmojiForRetweetAndReply=1&showQuotedInTitle=1&excludeReplies=1
Error message: Cannot read properties of undefined (reading 'user_results')
Helpful Information to provide when opening issue:
Path: /user/waylybaye/readable=1&showEmojiForRetweetAndReply=1&showQuotedInTitle=1&excludeReplies=1
Node version: v18.17.0
Git Hash: a832e97

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Linux, Node: v18.17.0, Docker: v20.10.21

### Additional info

```shell
.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by mashirozx** [comment]
寄了
