### ISSUE TITLE
请求添加 Twitch 的 RSS

### ISSUE THREAD

**Issue by Vstory** [DIYgod/RSSHub#12883]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/DIYgod/RSSHub/issues/12883)

### 类型

音视频

### 网站地址

https://www.twitch.tv/

### 网站描述

一个直播平台

### 需要生成什么内容？

类似现有的哔哩哔哩用户动态一样，只要订阅了该用户后。可以自动获取以下内容，也可以选择性订阅以下内容。
1. 支持订阅用户的开播提醒；
2. 直播时间表推送；
3. 用户上传的视频

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars.githubusercontent.com/u/20795557?v=4' alt='vstory' width=24 height=24> vstory](https://oss.issuehunt.io/u/vstory) ($10.00)

### Submitted pull Requests
- [#13464 feat(route): add twitch](https://oss.issuehunt.io/r/DIYgod/RSSHub/pull/13464)
---

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Vstory** [comment]
@1164

**Comment by Vstory** [comment]
@ruleroller 
已经完成了，有大佬搞定了。

**Comment by ruleroller** [comment]
@Vstory 

WoW！

谢谢你的特意提醒，以及你的悬赏请来了开发大神。刚才，还去看了，原来我之前提相关的issue快5年了……
