### ISSUE TITLE
抖音 douyin 博主路由报错

### ISSUE THREAD

**Issue by gkotta0311** [DIYgod/RSSHub#12898]
### 路由地址

```routes
/douyin/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/douyin/user/MS4wLjABAAAAkveIL_GBgTuPD3f-tPOmkA8aMIuRWPOAwuH7VkGqQNA
```

### 相关文档

https://docs.rsshub.app/social-media.html#dou-yin-bo-zhu

### 预期是什么？

正常显示RSS条目

### 实际发生了什么？

报错，无法获取RSS项目。
![208268884-82e023ac-0d7e-44b2-844e-52e2cd4ebba7](https://github.com/DIYgod/RSSHub/assets/139966554/199ecf68-03de-4f4a-ab19-de4e628762e8)
自建出错示例：
![image](https://github.com/DIYgod/RSSHub/assets/139966554/55e924c6-a711-4e47-af40-86fa50025728)

### 部署

自建

### 部署相关信息

Podman  Version: 3.4.4 API Version:  3.4.4 Go Version:   go1.18.1 OS/Arch:      linux/amd64

### 额外信息

```shell
It seems that this problem can be solved by adding cookies
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #12029
