### ISSUE TITLE
#Untag全文获取失效

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#12919]
### 路由地址

```routes
/utgd/timeline
```

### 完整路由地址

```fullroutes
/utgd/timeline
```

### 相关文档

https://docs.rsshub.app/new-media.html#untag

### 预期是什么？

之前可以获取全文

### 实际发生了什么？

现在只有摘要

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
5e655ebc3bfc3b0c63c9078f56f0f660f2af6dcc

If you don't like this changes. You can always maintain your own fork of RSSHub.
