### ISSUE TITLE
内容过滤中的正文过滤失效

### ISSUE THREAD

**Issue by pipiepig** [DIYgod/RSSHub#1292]
### 路由地址
https://rsshub.app/ifanr/appso?filterout=%E6%B8%B8%E6%88%8F%7C%E6%89%8B%E6%B8%B8
### 预期是什么？
不会向我推荐有游戏和手游相关的内容

### 实际发生了什么？
向我推荐了
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
Fixed in c550842732a8c1d7e5afa5dfe7ab8894138004b9
