### ISSUE TITLE
Oxford University Press

### ISSUE THREAD

**Issue by nicholastc2** [DIYgod/RSSHub#12923]
### 路由地址

```routes
/oup/journals/:name
```

### 完整路由地址

```fullroutes
/oup/journals/:name
```

### 相关文档

https://docs.rsshub.app/journal.html#oxford-university-press

### 预期是什么？

work

### 实际发生了什么？

cant work

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

rsshub.app

### 额外信息

```shell
Looks like something went wrong
Route requested: /journals/adaptation
Error message: Cannot read properties of undefined (reading 'map')
Helpful Information to provide when opening issue:
Path: /journals/adaptation
Node version: v18.17.0
Git Hash: e86265b
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by rainrdx** [comment]
I venture to guess this is due to their very aggressive anti crawling. Maybe you wanna use a private deployment ideally from a residential IP
