### ISSUE TITLE
rsshub connection failed Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by SecondaryH** [DIYgod/RSSHub#12925]
### 路由地址

```routes
/javlibrary/newentries/:language?
```

### 完整路由地址

```fullroutes
localhost:1200/javlibrary/newentries/en
```

### 相关文档

https://rsshub.app/javlibrary/newentries/en

### 预期是什么？

generate feed which i can use

### 实际发生了什么？

doesnt load any feed and instead throws an error message

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
https://i.imgur.com/Ty7MPVZ.png
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SecondaryH** [comment]
problem still occurs

**Comment by SecondaryH** [comment]
Proper route: /javlibrary/newentries/:language?

**Comment by TonyRL** [comment]
/test
```routes
/javlibrary/newentries/en
```

**Comment by TonyRL** [comment]
Please make sure your IP is not blocked.
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/980f8b33-6c57-4091-ab76-6fd559ef5d32)
</details>
