### ISSUE TITLE
twitter 用户喜欢列表 失效

### ISSUE THREAD

**Issue by stainge** [DIYgod/RSSHub#12928]
### 路由地址

```routes
/twitter/likes/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/likes/Kojima_Hideo
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

获取信息并正确生成 RSS Feed

### 实际发生了什么？

无法生成rss，报错 code 403

### 部署

自建

### 额外信息

```shell
Route requested: /likes/Kojima_Hideo
Error message: Request failed with code 403 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product (Twitter code 453)
Helpful Information to provide when opening issue:
Path: /likes/Kojima_Hideo
Node version: v18.17.0
Git Hash: e86265b
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SecondaryH** [comment]
From what I've read most features require you to pay for v2 

The free tier doesn't allow for data retrieval.

The basic tier(100$/month) does, see pictures

![firefox_JDd1lV2BO6](https://github.com/DIYgod/RSSHub/assets/76407423/8919f2b3-f562-440c-a3e8-c50a71e9152c)
![firefox_kM2oEFFP2R](https://github.com/DIYgod/RSSHub/assets/76407423/c9051976-b3be-4117-b1cd-07620a83f7b4)

**Comment by DerekTso** [comment]
遇到同样的问题，请问，怎么解决呢？

> Error Message:
> Twitter RSS is disabled due to the lack of <a href="https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi">relevant config</a>

> 更新到最新版本的RSSHub并根据文档进行配置，报错信息改变成了`Twitter RSS is disabled due to the lack of [relevant config](https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi)`，推测是因为[feat: bring back twitter routes](https://github.com/DIYgod/RSSHub/commit/9032153c7de4c9ca189482d495696986e9795106#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62)导致的配置改变引起的 ![image](https://private-user-images.githubusercontent.com/48624558/287445129-38a79217-2df4-42ce-8eb1-8d29400d12bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDU0MjIsIm5iZiI6MTcxMTcwNTEyMiwicGF0aCI6Ii80ODYyNDU1OC8yODc0NDUxMjktMzhhNzkyMTctMmRmNC00MmNlLThlYjEtOGQyOTQwMGQxMmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5Mzg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNzE0NDYxNDAzMjM1ZWJjMGRiYTdiNGE1NGE5Yzk2NzI3ODIxMDIyYWM4MmViYjUwMjQ4NTczMjk2NTgwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.793-HZMFGeXHj5_mNpejFetGPSOx94x-rxbL4gmr04w)
