### ISSUE TITLE
https://rsshub.app/dytt出现错误

### ISSUE THREAD

**Issue by feixu0530** [DIYgod/RSSHub#12946]
### Routes

```routes
/dytt
```

### Full routes

```fullroutes
/dytt
```

### Related documentation

https://docs.rsshub.app/multimedia.html#dian-ying-shou-fa-zhan

### What is expected?

抓取不到出现错误

### What is actually happening?

Error message: unable to verify the first certificate: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /dytt
Node version: v18.17.0
Git Hash: 291e127

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Error message: unable to verify the first certificate: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /dytt
Node version: v18.17.0
Git Hash: 291e127
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by People-11** [comment]
这个网站已经不存在了，此 Issue 应该被关闭。
