### ISSUE TITLE
bilibili.com 失效的太多，没失效的也是AV号，现在哔哩哔哩用的是BV号了 测试网址 https://space.bilibili.com/674510452

### ISSUE THREAD

**Issue by orisgh** [DIYgod/RSSHub#12956]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

NOROUTE

### 预期是什么？

订阅up们的最新视频

### 实际发生了什么？

比如想用 
https://chrome.google.com/webstore/detail/rsshub-radar/kefjpfngnndepjbopdmoebkipbgkggaa
订阅他仨的更新
https://space.bilibili.com/674510452
https://space.bilibili.com/1629347259
https://space.bilibili.com/12695676
选择
“当前up主投稿”    前两个都有bug，只有第三个是没bug的
“当前up主所有视频”    第一个无效，后两个能用
还有，b站视频已经换用BV号了，订阅出来的视频还都是AV号
总之，在up主的空间页，无法完成对up最新视频的订阅

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
如上
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Vstory** [comment]
尝试订阅 UP 主的动态，即可解决。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/674510452
/bilibili/user/video/1629347259
/bilibili/user/video/12695676
```

**Comment by TonyRL** [comment]
All of the three RSS feeds work and do provide the latest content.
