### ISSUE TITLE
希望增加flickr.com rss

### ISSUE THREAD

**Issue by willie91** [DIYgod/RSSHub#1296]
### https://www.flickr.com/photos/162166559@N02/  (比如王动的照片更新,最近他跑到flickr去了,找了半天也没有订阅)

谢谢

**Comment by imlonghao** [comment]
有官方 Feed
https://www.flickr.com/services/feeds/

例如你要订阅的这个人就是
https://api.flickr.com/services/feeds/photos_public.gne?id=162166559@N02

**Comment by willie91** [comment]
> 有官方Feed 
> https://www.flickr.com/services/feeds/
> 
> 你例如订阅要的这个人就是
> https://api.flickr.com/services/feeds/photos_public.gne?id=162166559@N02

感谢，不过看了下需要登陆账号才能看到= =。没登陆看不到内容

**Comment by DIYgod** [comment]
非公开内容用 RSSHub 也无法订阅
