### ISSUE TITLE
Inoreader无法加载Bilibili图片

### ISSUE THREAD

**Issue by Pseudotruth** [DIYgod/RSSHub#1297]
用inoreader加载Bilibili的RSS时，会出现一些图片无法显示的问题，原因貌似是下载图片时被服务器拒绝。
请求头：
```
GET https://i1.hdslb.com/bfs/archive/39c6ca720c8ed18ebfa2fb63f7ca9fb14547a4de.jpg
Host: i1.hdslb.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate, br
Referer: https://www.inoreader.com/
Connection: keep-alive
```
响应头：
```
HTTP/1.1 403 Forbidden
Server: Tengine
Date: Tue, 18 Dec 2018 03:32:27 GMT
Content-Type: text/html
Content-Length: 254
Connection: keep-alive
X-Tengine-Error: denied by Refer ACL
x-cache-webcdn: AL
access-control-allow-origin: *
Via: cache10.cn115[,0]
Timing-Allow-Origin: *
EagleId: 65e2b55e15451039477676120e
```
响应：
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<h1>403 Forbidden</h1>
<p>You don't have permission to access the URL on this server.<hr/>Powered by Tengine</body>
</html>
```
浏览器直接打开[https://i1.hdslb.com/bfs/archive/39c6ca720c8ed18ebfa2fb63f7ca9fb14547a4de.jpg](https://i1.hdslb.com/bfs/archive/39c6ca720c8ed18ebfa2fb63f7ca9fb14547a4de.jpg)倒是没问题。
虽然是小问题，希望可以解决。

**Comment by Pseudotruth** [comment]
嗯，没人理我……
又找了下原因，发现是hdslb.com的图片防盗链把inoreader误伤了……
折腾了2个小时，写了个脚本伪造referer总算是解决了……

**Comment by SuperMaxine** [comment]
> 嗯，没人理我…… 又找了下原因，发现是hdslb.com的图片防盗链把inoreader误伤了…… 折腾了2个小时，写了个脚本伪造referer总算是解决了……

求求大佬教教咋搞的，我网页版inoreader也遇到这个问题好久了，不过因为大部分时间在手机上用没太在意，今天突然想起来搜了一下才发现您已经搞定了，能不能分享下🙏

**Comment by SuperMaxine** [comment]
> 嗯，没人理我…… 又找了下原因，发现是hdslb.com的图片防盗链把inoreader误伤了…… 折腾了2个小时，写了个脚本伪造referer总算是解决了……

试了一些油猴上的脚本，都是在head里面修改meta来设置no-referrer，但是网络里面的请求照样带着inoread的referer😂还是显示不出来，好奇大佬咋搞得

**Comment by Pseudotruth** [comment]
> > 嗯，没人理我…… 又找了下原因，发现是hdslb.com的图片防盗链把inoreader误伤了…… 折腾了2个小时，写了个脚本伪造referer总算是解决了……
> 
> 试了一些油猴上的脚本，都是在head里面修改meta来设置no-referrer，但是网络里面的请求照样带着inoread的referer😂还是显示不出来，好奇大佬咋搞得

用脚本也行，最简单的方法，安装一个可以设置referer的浏览器插件，启用并在其中创建规则，from domain: www.inoreader.com，Change referer to: [TARGET_HOST]。

**Comment by SuperMaxine** [comment]
> > > 嗯，没人理我…… 又找了下原因，发现是hdslb.com的图片防盗链把inoreader误伤了…… 折腾了2个小时，写了个脚本伪造referer总算是解决了……
> > 
> > 
> > 试了一些油猴上的脚本，都是在head里面修改meta来设置no-referrer，但是网络里面的请求照样带着inoread的referer😂还是显示不出来，好奇大佬咋搞得
> 
> 用脚本也行，最简单的方法，安装一个可以设置referer的浏览器插件，启用并在其中创建规则，from domain: [www.inoreader.com，Change](http://www.inoreader.com%EF%BC%8CChange) referer to: [TARGET_HOST]。

大佬NB啊，我发现我Chrome已经装过Referer Control做别的来着，直接加条规则就解决了，这下舒服了😂
