### ISSUE TITLE
创业邦

### ISSUE THREAD

**Issue by cylcs** [DIYgod/RSSHub#12990]
### Routes

```routes
https://rsshub.app/cyzone/author/611705
```

### Full routes

```fullroutes
https://rsshub.app/cyzone/author/611705

http://127.0.0.1:1200/cyzone/author/1225562
```

### Related documentation

https://docs.rsshub.app/new-media.html#chuang-ye-bang

### What is expected?

请求修复

### What is actually happening?

Looks like something went wrong
Route requested: /cyzone/author/1225562
Error message: getaddrinfo ENOTFOUND article: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /cyzone/author/1225562
Node version: v18.17.1
Git Hash: f0fab18
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
        
For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

在线文档与支持，请访问 [docs.rsshub.app](https://docs.rsshub.app/)。

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Docker version 24.0.2, build cb74dfc

### Additional info

```shell
diygod/rsshub              latest    fa0588b37956   About an hour ago   325MB

http://127.0.0.1:1200/cyzone/author/1225562
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/cyzone/author/611705
/cyzone/author/1225562
```
