### ISSUE TITLE
优化错误处理

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#13]
有些参数有误时会导致程序异常退出，需要一种更通用的错误处理

**Comment by iwestlin** [comment]
还有为啥用request不用axios，后者跟await搭配用起来跟飞一样，写起来像同步，错误处理也跟同步一样，彻底告别回调地狱……
至于express的错误处理，大致看了下代码，似乎都没有处理`err`? 而`base.js`里的try catch 是抓不到异步错误的。。路由函数一般都有第三个参数next，遇到错误就调用`next(err)`，然后路由最后面会设置一个errorHandler。这里是官方文档： https://expressjs.com/zh-cn/guide/error-handling.html

我不是找茬。。其实自己也曾是rss重度用户，多谢楼主写了个这样的工具 👍

**Comment by DIYgod** [comment]
@iwestlin 原来如此...学到了...

**Comment by zgq354** [comment]
通过 Promise 的方式处理异步应该更好一些，所有的异步任务都返回Promise，然后在最顶层的地方 catch 一下就好了
我这个项目
 https://github.com/zgq354/weibo-rss 也是通过 Promise 处理的，目前在我的小服务器中暂时没有发现因为未捕获异常导致重启的问题

**Comment by DIYgod** [comment]
换了 koa 和 axios，写起来果然爽

3f940a6906779edcbf9a51da825c4ccaa2ab89a5

**Comment by iwestlin** [comment]
楼主效率真高……
还有个小问题就是，next参数一般在写中间件的时候才用得到，作用是把控制权交给下一个中间件，既然route里已经设置`ctx.body = ...`了，就不需要手动调用next了。。
