### ISSUE TITLE
docs dev/build error

### ISSUE THREAD

**Issue by lxl66566** [DIYgod/RSSHub#13007]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/joinus/new-rss/add-docs.html

### 预期是什么？

successfully start a vuepress1 server / build docs

### 实际发生了什么？

> node:internal/crypto/hash:69
>   this[kHandle] = new _Hash(algorithm, xofLen);
> &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           ^
> Error: error:0308010C:digital envelope routines::unsupported

[here is the full error log](https://pastebin.com/PgrxYVEd)

I also tried nodejs-lts (v18.17.1), and it raised the same error; 
also tried install dependencies with `pnpm i --shamefully-hoist`, same error.

### 部署

自建

### 部署相关信息

OS: Windows 11, node: v20.4.0

### 额外信息

```shell
built from the latest RSSHub commit:

git clone git@github.com:DIYgod/RSSHub.git
cd RSSHub/docs
pnpm i
pnpm docs:dev
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://github.com/webpack/webpack/issues/14532
So if you're on node v17 or above, use `NODE_OPTIONS=--openssl-legacy-provider pnpm docs:dev`
