### ISSUE TITLE
Facebook Page route failed

### ISSUE THREAD

**Issue by BaksiLi** [DIYgod/RSSHub#13008]
### 路由地址

```routes
/facebook/page/:id
```

### 完整路由地址

```fullroutes
/facebook/page/:id
```

### 相关文档

https://docs.rsshub.app/en/social-media.html#facebook-page

### 预期是什么？

預期一個訂閱返回。

### 实际发生了什么？

Looks like something went wrong

Route requested: /facebook/page/SonetPCR

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
這個可以關注粉專的 route 很有意義，可惜官方頁面上的 Example 都跑不了。希望解決。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #7512
