### ISSUE TITLE
Bilibili 自建实例投币视频路由失效

### ISSUE THREAD

**Issue by shyrz** [DIYgod/RSSHub#13012]
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
NOROUTE
```

### Related documentation

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-bi-shi-pin

### What is expected?

Bilibili 自建实例投币视频路由失效

### What is actually happening?

![image](https://github.com/DIYgod/RSSHub/assets/5728981/ac54008c-98e1-4626-aad8-95fc2cc1a793)

### Deployment information

Zeabur / Vercel

### Additional info

```shell
Error message: Cannot read properties of undefined (reading 'map')

Helpful Information to provide when opening issue:
Path: /user/coin/208259
Node version: v18.16.1
Git Hash: f4ec715
```

### This is not a duplicated issue

- [x] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by JimenezLi** [comment]
I cannot reproduce this bug. Can you provide more information, or do you still have this problem?

**Comment by shyrz** [comment]
> I cannot reproduce this bug. Can you provide more information, or do you still have this problem?

Solved. I deployed my instance on Zeabur, and added full Bilibili cookie with UI then. I found that the `BILIBILI_COOKIE_XXX` parameter was not quoted with `"`. Document this here for future users experiencing this issue.
