### ISSUE TITLE
希望增加Linkedin动态RSS

### ISSUE THREAD

**Issue by idealclover** [DIYgod/RSSHub#1304]
### 源站地址
https://www.linkedin.com/in/XXX/detail/recent-activity/posts/
[example](https://www.linkedin.com/in/%E4%BB%8A%E6%97%A5%E5%BF%85%E8%AF%BB-%E9%A2%86%E8%8B%B1-6a3599159/detail/recent-activity/posts/)
https://www.linkedin.com/in/XXX/detail/recent-activity/shares/
[example](https://www.linkedin.com/in/%E4%BB%8A%E6%97%A5%E5%BF%85%E8%AF%BB-%E9%A2%86%E8%8B%B1-6a3599159/detail/recent-activity/shares/)
https://www.linkedin.com/in/XXX/detail/recent-activity/
[example](https://www.linkedin.com/in/%E4%BB%8A%E6%97%A5%E5%BF%85%E8%AF%BB-%E9%A2%86%E8%8B%B1-6a3599159/detail/recent-activity/)

### 需要生成什么内容？

- [ ] 文章
- [ ] 动态
- [ ] 全部动态

### 额外描述

Long Live RSS!

**Comment by HenryQW** [comment]
直接爬需要登录，走 API: https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
