### ISSUE TITLE
bilibili用户投稿视频报错

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#13054]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/21778075
```

### 相关文档

https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-tou-gao

### 预期是什么？

响应rss

### 实际发生了什么？

报错

### 部署

自建

### 额外信息

```shell
Error message: Cannot read properties of undefined (reading 'map')
Helpful Information to provide when opening issue:
Path: /user/video/21778075
Node version: v18.17.1
Git Hash: 1539817
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/21778075
```
