### ISSUE TITLE
路由 西北农林科技大学-信息工程学院公告 可能已被移除

### ISSUE THREAD

**Issue by TTsdzb** [DIYgod/RSSHub#13068]
### 路由地址

```routes
/nwafu/cie
```

### 完整路由地址

```fullroutes
/nwafu/cie
```

### 相关文档

https://docs.rsshub.app/routes/university#xi-bei-nong-lin-ke-ji-da-xue-xin-xi-gong-cheng-xue-yuan-gong-gao

### 预期是什么？

返回对应的 RSS feed

### 实际发生了什么？

Looks like something went wrong
Route requested: /nwafu/cie
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /nwafu/cie
Node version: v18.17.1
Git Hash: 25e4d85
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
        
For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

在线文档与支持，请访问 [docs.rsshub.app](https://docs.rsshub.app/)。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
如果路由已失效或被移除，请更新官方文档的相应部分。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TTsdzb** [comment]
该路由在文档中存在，但最近它变成了一个空路由。如果它不再可用，请从文档中移除。如果没有对它做出更改，那么可能出现了一些异常情况。

**Comment by JimenezLi** [comment]
#13067

**Comment by TonyRL** [comment]
Closed in #13067
