### ISSUE TITLE
喜马拉雅专辑第二页的音频抓取

### ISSUE THREAD

**Issue by Frigac** [DIYgod/RSSHub#1307]
### 源站地址
https://www.ximalaya.com/xiangsheng/3855088/p2/
### 需要生成什么内容？
尝试用站内的抓取方法只能够抓取到第一页的音频，想要抓取第二页的音频但是无法单纯更改后缀生成
希望能够开发特定单页抓取或者批量多页抓取的方式

**Comment by DIYgod** [comment]
@Frigac RSS 只获取更新，请勿把 RSSHub 用作爬虫
