### ISSUE TITLE
知乎用户文章路由报错

### ISSUE THREAD

**Issue by gjhuai** [DIYgod/RSSHub#13081]
### 路由地址

```routes
/zhihu/posts/:usertype/:id
```

### 完整路由地址

```fullroutes
/zhihu/posts/people/frederchen
```

### 相关文档

https://docs.rsshub.app/routes/social-media#zhi-hu-yong-hu-wen-zhang

### 预期是什么？

正常显示

### 实际发生了什么？

Looks like something went wrong
Route requested: /zhihu/posts/people/frederchen
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /zhihu/posts/people/frederchen
Node version: v18.17.1
Git Hash: 6422474

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /zhihu/posts/people/frederchen
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /zhihu/posts/people/frederchen
Node version: v18.17.1
Git Hash: 6422474
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/posts/people/frederchen
```

**Comment by TonyRL** [comment]
It works.
