### ISSUE TITLE
Twitter 个人时间线需求

### ISSUE THREAD

**Issue by Jacob-zh** [DIYgod/RSSHub#1312]
### Twitter 的个人时间线需求

既然已经使用了Twitter的key了，那能不能实现获取用户自己的时间线功能。
主要是因为Twitter官方客户端推荐太多，第三方那个胖鸟也不好用了。
之前有用个php做的脚本，现在大部分源都转到rsshub上来了，迫切渴望个人时间线功能。

**Comment by SettingDust** [comment]
@JZhao919 建议你自己订阅关注到一个分类里

**Comment by JZhao919** [comment]
> @ JZhao919建议你自己订阅关注到一个分类里

正准备这样用。

**Comment by SettingDust** [comment]
如果你会开发的话 可以在[RSSHelper](https://greasyfork.org/zh-CN/scripts/374570-rsshelper)加路由，方便的订阅XD

**Comment by JZhao919** [comment]
突然发现InoReader内账号关联后可以直接订阅自己的时间线，经测试很好用。
