### ISSUE TITLE
RSSHUB 演示服务不可用 (https://rsshub.app)

### ISSUE THREAD

**Issue by xc1427** [DIYgod/RSSHub#13159]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/zaobao/realtime/china#所有路由都不可用,这里仅举一例
```

### 相关文档

https://docs.rsshub.app

### 预期是什么？

正常返回 xml, http 状态码 200

### 实际发生了什么？

http 状态码 404，页面提示如下，

> Route requested: /realtime/china
Error message: Proxy connection timed out: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /realtime/china
Node version: v18.17.1
Git Hash: 560480c
        
> If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)

![image](https://github.com/DIYgod/RSSHub/assets/5611770/b124e414-f164-4ed6-b2e5-71d22972d101)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
如果使用 gitpod.io 等服务启动，是没问题的。证明是 rsshub 演示服务出了问题。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by jinweijie** [comment]
同样的问题，用Docker在自部署实例上也是同样问题

**Comment by flytiny** [comment]
+1
mark

**Comment by hexsix** [comment]
昨天上午开始不可用（2023/8/29 10:11 GMT+8）
前天上午可用（2023/8/30 9:50 GMT+8）

**Comment by jinweijie** [comment]
发现AP News 和 Reuters也有同样的问题，已提issue。

**Comment by TonyRL** [comment]
/test
```routes
/zaobao/realtime/china
```

**Comment by mintyfrankie** [comment]
Confirmed same issue on self-hosted instance.

**Comment by xiaosaaaa** [comment]
> 成功[生成](https://github.com/DIYgod/RSSHub/actions/runs/6020953412)如下：
> 
> http://localhost:1200/zaobao/realtime/china - 成功✔️
又失效了

**Comment by xiaosaaaa** [comment]
> 成功[生成](https://github.com/DIYgod/RSSHub/actions/runs/6020953412)如下：
> 
> http://localhost:1200/zaobao/realtime/china - 成功✔️

再一次失效了
