### ISSUE TITLE
求澎湃新闻支持不同内容频道

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1315]
### 源站地址
https://www.thepaper.cn/list_id
例如：https://www.thepaper.cn/list_25457
### 需要生成什么内容？
每个频道的独立rss链接（包括标题、全文）
### 额外描述
目前Rsshub已支持湃新闻首页更新，希望能增加按频道订阅的功能

**Comment by yefoenix** [comment]
请问这个无法实现吗？

**Comment by yefoenix** [comment]
请问这个无法实现吗? @DIYgod

**Comment by DIYgod** [comment]
@yefoenix https://github.com/DIYgod/RSSHub/issues/new?template=rss_request_zh.md

**Comment by yefoenix** [comment]
已更新需求描述 @DIYgod
