### ISSUE TITLE
PORNHUB的RSS部分不能正常获取，显示路由为空或者RSS无内容

### ISSUE THREAD

**Issue by 502880166** [DIYgod/RSSHub#13166]
### 路由地址

```routes
/pornhub/:language?/users/:username
/pornhub/:language?/model/:username/:sort?
/pornhub/:language?/pornstar/:username/:sort?
```

### 完整路由地址

```fullroutes
https://rsshub.app/pornhub/users/pornhubmodels
https://rsshub.app/pornhub/model/stacy-starando
https://rsshub.app/pornhub/pornstar/june-liu
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#pornhub

### 预期是什么？

会正常显示内容

### 实际发生了什么？

USER的实际订阅源可以订阅但是内容为空，其他两个是显示路由器Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /pornhub/model/yuzukitty
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /pornhub/model/yuzukitty
Node version: v18.17.1
Git Hash: ea22ebc
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/pornhub/users/pornhubmodels
/pornhub/model/stacy-starando
/pornhub/pornstar/june-liu
```
