### ISSUE TITLE
AP News not working

### ISSUE THREAD

**Issue by jinweijie** [DIYgod/RSSHub#13164]
### Routes

```routes
/apnews/topics/:topic?
```

### Full routes

```fullroutes
/apnews/topics/apf-topnews
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#ap-news

### What is expected?

Status Code 200

### What is actually happening?

RSSHub
Looks like something went wrong
Route requested: /topics/apf-topnews
Error message: Proxy connection timed out: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /topics/apf-topnews
Node version: v18.17.1
Git Hash: 560480c
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
        
For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

在线文档与支持，请访问 [docs.rsshub.app](https://docs.rsshub.app/)。

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Author: @zoenglinghou @mjysci @TonyRL

Thanks for your contribution!
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/apnews/topics/apf-topnews
```

**Comment by EmmanuilZorg** [comment]
same issue with Telegram routes. fro ex.:

Route requested: /channel/PercivalWulfric457az
Error message: Proxy connection timed out: target website might be blocking our access, 
Helpful Information to provide when opening issue:
Path: /channel/PercivalWulfric457az
Node version: v18.17.1
Git Hash: 560480c
