### ISSUE TITLE
華視新聞RSS抓取失敗

### ISSUE THREAD

**Issue by ufo1024k** [DIYgod/RSSHub#13174]
### 路由地址

```routes
/cts/:category
```

### 完整路由地址

```fullroutes
/cts/real
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#hua-shi-xin-wen

### 预期是什么？

可以正常運行抓取https://rsshub.app/cts/real

### 实际发生了什么？

抓取失敗

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /real

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /real
Node version: v18.17.1
Git Hash: 121763b
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by miles170** [comment]
看起來是華視新聞有使用 CloudFront 阻擋, 我使用台灣的伺服器測試正常.
