### ISSUE TITLE
信报财经新闻RSS抓取失敗

### ISSUE THREAD

**Issue by ufo1024k** [DIYgod/RSSHub#13175]
### 路由地址

```routes
/hkej/:category?
```

### 完整路由地址

```fullroutes
/hkej/index
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#xin-bao-cai-jing-xin-wen

### 预期是什么？

正常穩定抓取https://rsshub.app/hkej/index

### 实际发生了什么？

不能正常抓取https://rsshub.app/hkej/index

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /index

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /index
Node version: v18.17.1
Git Hash: 121763b
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #12860

**Comment by TonyRL** [comment]
/test
```routes
/hkej/index
```
