### ISSUE TITLE
财新网 china板块无法订阅

### ISSUE THREAD

**Issue by toyo2333** [DIYgod/RSSHub#13188]
### Routes

```routes
/caixin/:column/:category
```

### Full routes

```fullroutes
/caixin/china
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#cai-xin-wang

### What is expected?

返回对应的feed

### What is actually happening?

Route requested: /caixin/china
Error message: wrong path
Helpful Information to provide when opening issue:
Path: /caixin/china
Node version: v18.17.1
Git Hash: c103270

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by JimenezLi** [comment]
category 是必选参数，得带上 category 参数才能订阅

**Comment by toyo2333** [comment]
> category 是必选参数，得带上 category 参数才能订阅

谢谢
