### ISSUE TITLE
可以加入翻译功能吗

### ISSUE THREAD

**Issue by Whichbfj28** [DIYgod/RSSHub#13189]
### 这是一个什么样的功能？

把feed的英文自动翻译为中文。
目前已经实现了繁体中文<-->简体中文
不知道能否实现其他语言的翻译

### 这个功能可以解决什么问题？

可以方便的订阅国外的feed

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
Duplicate of #6696
