### ISSUE TITLE
闲鱼关键词订阅 RSS Wanted

### ISSUE THREAD

**Issue by Hipd** [DIYgod/RSSHub#132]
希望支持闲鱼关键词订阅

**Comment by MoguCloud** [comment]
https://s.2.taobao.com/list/list.htm?_input_charset=utf8&q=${keyword}

**Comment by tiaod** [comment]
@MoguCloud 
加个参数st_edtime=1，按最新排序
https://s.2.taobao.com/list/list.htm?st_edtime=1&_input_charset=utf8&q=${keyword}

效果还行吧，就是要登录

**Comment by DIYgod** [comment]
登录不好解决

**Comment by tiaod** [comment]
是的，阿里反爬虫很强

**Comment by njxz** [comment]
有人有思路么

**Comment by njxz** [comment]
@DIYgod 淘宝都能爬，闲鱼爬不来 倒是让人觉得很诧异

**Comment by tiaod** [comment]
@njxz 淘宝爬虫有实现吗？

**Comment by njxz** [comment]
@tiaod 今年2月份实现过一个，现在不知道之前的逻辑能用不了

**Comment by njxz** [comment]
@tiaod 用的selenium 登录的，获取cookie以后，在调用的其他的

**Comment by tiaod** [comment]
@njxz 淘宝的cookie会过期。如果没办法实现自动化登陆，还是爬不了闲鱼啊

**Comment by njxz** [comment]
@Hipd 最关键的还是，登录上去以后，还是搜索不了 用selenium都不行
