### ISSUE TITLE
bilibili 部分订阅接口失效

### ISSUE THREAD

**Issue by wuhao-igno** [DIYgod/RSSHub#13201]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/13164144
```

### 相关文档

https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-tou-gao

### 预期是什么？

返回 UP 主的投稿视频信息

### 实际发生了什么？

未返回相关信息，推测是最近 B 站部分接口改为需要鉴权导致；获取 UP 主全部视频也有类似的问题。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /user/video/13164144
Error message: Got error code -401 while fetching: 非法访问
Helpful Information to provide when opening issue:
Path: /user/video/13164144
Node version: v18.17.1
Git Hash: 38e4f1a
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/13164144
```
