### ISSUE TITLE
bilibili/user/video 401 非法访问

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#13287]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/569956690
```

### 相关文档

https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-tou-gao

### 预期是什么？

CGTN 投稿视频

### 实际发生了什么？

Route requested: /user/video/569956690
Error message: Got error code -401 while fetching: 非法访问
Helpful Information to provide when opening issue:
Path: /user/video/569956690
Node version: v18.17.1
Git Hash: 9031ea8

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Docker

### 额外信息

```shell
自建 与 演示地址均出现 401
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by EricGao-Byte** [comment]
+1 确实有问题，不知道是不是b站把接口改成鉴权的了。

**Comment by matakk** [comment]
+1 出现了好几天了.一直尝试解决没有搞定.

**Comment by morenjojo** [comment]
+1

**Comment by JimmyLv** [comment]
+1

**Comment by Jiematcha** [comment]
9/15 15:00 似乎已恢复

**Comment by Jiematcha** [comment]
9/15 15:00 似乎已恢复

**Comment by WilliamK7** [comment]
2023.09.22 依然报错 -401

**Comment by Crayon-ShinChan** [comment]
2023.11.04 仍然有问题
