### ISSUE TITLE
摸鱼kik的订阅源请求

### ISSUE THREAD

**Issue by 1githubpassword** [DIYgod/RSSHub#13300]
### 类型

社交媒体

### 网站地址

https://h5-ol.sns.sohu.com/hy-moyukik-h5/share/topic/587?sf_my=copylink&cid=027095394541654000000&uid=1144194

### 网站描述

摸鱼kik是可以订阅国内各种社交媒体的平台，如微信公众号，抖音等。

### 需要生成什么内容？

希望可以将摸鱼Kik的订阅链接制作为订阅源，从而在阅读器里阅读，实现国内外平台资源的整合。而其已经优化了显示界面，所以可以打开其内部链接进行浏览，因此需要制作其订阅源，将其标题 ，缩略图以及文章链接集合为订阅源实现订阅

### 额外描述

这样可以减少你们应对国内平台不断屏蔽而不断更改的工作量，以及订阅源不时失效的状况

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #9434

**Comment by 1githubpassword** [comment]
请问现在有可以订阅的摸鱼kik的订阅源了吗





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DIYgod/RSSHub] 摸鱼kik的订阅源请求 (Issue #13300)




 
Duplicate of #9434
