### ISSUE TITLE
bilibili 401 Error message: Got error code -401

### ISSUE THREAD

**Issue by xusenfa** [DIYgod/RSSHub#13315]
### 路由地址

```routes
/bilibili/user/video/63231
```

### 完整路由地址

```fullroutes
无
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#bilibili-up-zhu-tou-gao

### 预期是什么？

正常获取

### 实际发生了什么？

401错误

### 部署

自建

### 部署相关信息

OS:Linux Docker: 24.0.5 

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by equt** [comment]
- https://github.com/DIYgod/RSSHub/issues/13287
- https://github.com/DIYgod/RSSHub/issues/13228
- https://github.com/DIYgod/RSSHub/issues/13201
