### ISSUE TITLE
知识星需求球RSS源订阅需求

### ISSUE THREAD

**Issue by MAGICYMZ** [DIYgod/RSSHub#1332]
### 源站地址
https://wx.zsxq.com/dweb

### 需要生成什么内容？

- [ ] 订阅的「知识星球」提供RSS源

### 额外描述
例如，我在知识星球中订阅了「可能吧」能不能提供对应的RSS，目前知识星球中的内容只能在App浏览查看

**Comment by imlonghao** [comment]
无公开可访问页面

**Comment by udbmnm** [comment]
除非登陆了才行，收费内容这么搞不好吧

**Comment by MAGICYMZ** [comment]
> 除非登陆了才行，收费内容这么搞不好吧

也有很多免费的星球呀

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
