### ISSUE TITLE
建议rsshub的说明文档网页（docs.rsshub.app）设置为默认中文。

### ISSUE THREAD

**Issue by Whichbfj28** [DIYgod/RSSHub#13329]
### 这是一个什么样的功能？

建议【https://docs.rsshub.app】设置为默认中文。
我不知道这玩意外国人用的多不多。但是国内很多人使用。而且开发者就是国人。为什么要用英文作为默认语言?

### 这个功能可以解决什么问题？

1、方便找文档。
2、经常已经搜索到文档内容了。。一旦切换到中文模式。又要重新搜索

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
#13075
