### ISSUE TITLE
bilibili用户关注动态title显示undefined

### ISSUE THREAD

**Issue by stainge** [DIYgod/RSSHub#13334]
### 路由地址

```routes
/bilibili/followings/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/followings/dynamic/:uid/:routeParams?
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#bilibili-yong-hu-guan-zhu-dong-tai

### 预期是什么？

显示正确的title

### 实际发生了什么？

显示undefined
![image](https://github.com/DIYgod/RSSHub/assets/48624558/611c36cd-8094-4c7b-b883-7bbde1b163a7)

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by JimenezLi** [comment]
获取用户名的接口有反爬虫，目前暂时还没有解决方案
