### ISSUE TITLE
TypeError: protocolLike.toLowerCase is not a function

### ISSUE THREAD

**Issue by maximBortnik** [DIYgod/RSSHub#13343]
### Routes

```routes
/instagram/:category/:key
```

### Full routes

```fullroutes
/instagram/user/championsleague
```

### Related documentation

https://docs.rsshub.app/install/#route-specific-configurations

### What is expected?

I expect to see rss feed

### What is actually happening?

Route requested: /user/championsleague
Error message: TypeError: protocolLike.toLowerCase is not a function: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /user/championsleague
Node version: v18.17.1
Git Hash: 2cc8a58

### Deployment information

Self-hosted

### Additional info

```shell
I'm hosting the service myself using the docker-compose. 
Specify the username and password as per the IG description section in the documentation, 
but failed to get the RSS feed for the "user" type, 
however, I can successfully get the RSS feed from the "tags" type.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Can't reproduce.
![image](https://github.com/DIYgod/RSSHub/assets/11386903/85ed22c8-de0b-47ee-8b4e-a365c7be1e3a)

**Comment by maximBortnik** [comment]
Could you please describe in more details which credentials I need to specify? I’ve just provided my username and password, is it correct?

**Comment by TonyRL** [comment]
For the private api one, you need the username and password only. For the cookie one, you need the cookie after logging in on web browser. It's suggested to use the cookie one instead of the private api one since the private api [is no longer updated](https://www.npmjs.com/package/instagram-private-api), weird stuff might happen.

**Comment by maximBortnik** [comment]
Thank you for explanation. I have one more question, should I use credential from developer account(https://developers.facebook.com/docs/instagram) or just from IG account?

**Comment by TonyRL** [comment]
A typical instagram account or a disposable one since meta has a pretty strict policy on crawling.

**Comment by maximBortnik** [comment]
sorry for disturbing you, I provided the IG_COOKIE: csrftoken=dasfkadjsfl and it says **Error message: Invalid cookie**. what I've done wrong?

**Comment by TonyRL** [comment]
You need the whole lengthy cookies
<details><summary>Screenshot taken from <a href="https://www.npmjs.com/package/instagram-without-api-node">here</a></summary>

![](https://user-images.githubusercontent.com/6490641/181632823-42fb2308-4c3f-421a-848a-58cefcf98915.png)
</details>

**Comment by maximBortnik** [comment]
Do you have a chance to have a quick call, because it still doesn't work for me?:(

**Comment by justinwaltrip** [comment]
@maximBortnik I am facing the same issue, how did you resolve?

**Comment by maximBortnik** [comment]
@justinwaltrip I stopped using warp-socks in the docker-compose file
