### ISSUE TITLE
支持RSS标题的英中翻译

### ISSUE THREAD

**Issue by toyo2333** [DIYgod/RSSHub#13389]
### 这是一个什么样的功能？

支持且仅限于在自部署的rsshub上实现RSS标题翻译，方便高效阅读英文媒体新闻订阅源

* 支持用户填写自己的Openai或DeepL的apikey，最好是都支持。（两者翻译各有特色和擅长的领域）
* 仅翻译标题就可以快速进行信息筛选，达到最高的阅读效率，也能节省token，全文内容目前有很多插件可以支持不需要rsshub翻译
* 可以在docker的环境变量里填写apiKey，然后以通用参数的方式支持哪个feed翻译、用哪种api来进行翻译（这个也可以放在环境变量里）
* openai的prompt可以参考“沉浸式翻译插件”里的写法直接套用。
* 可以参考这个产品：https://www.rsstranslator.com/

### 这个功能可以解决什么问题？

比如经济学人英文版、彭博社等新闻源很好，但feed提供量巨大，大量的英文标题里很难筛选出哪些是自己需要的。提供翻译功能后：
* 可以快速找到自己感兴趣的内容，从而进一步进行阅读（不感兴趣的，就直接“标记已读”）
* 需要进一步阅读的，用户可以自己再去使用其他成熟的bypass插件或者翻译插件进行全文翻译阅读
* 为什么不想使用第三方的https://www.rsstranslator.com/  这种，因为和rsshub自部署的初衷一样，都希望自己完全掌控管理自己的信息和内容渠道，保护隐私。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
Duplicate of #6696
