### ISSUE TITLE
The Initium 端传媒 router fails to fetch full text article behind paywall

### ISSUE THREAD

**Issue by yunanwg** [DIYgod/RSSHub#13388]
### Routes

```routes
/theinitium/channel/:type?/:language?
```

### Full routes

```fullroutes
/theinitium/channel/latest/zh-hans
```

### Related documentation

https://docs.rsshub.app/routes/new-media#duan-chuan-mei-zhuan-ti-lan-mu

### What is expected?

With default ENV variable or personal variable like `INITIUM_BEARER_TOKEN`, the router should be able to fetch full-text article from the source.

### What is actually happening?

Some articles failed to be fetched in full-text mode, showing for example :

![CleanShot 2023-09-25 at 14 28 18](https://github.com/DIYgod/RSSHub/assets/77310871/6b5a1c02-c1d2-4f8f-9d90-fe1e507f365e)

### Deployment information

Self-hosted

### Additional info

```shell
No relative logs found regarding this issue.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by mintyfrankie** [comment]
Thanks! Happy to help if you need some more information to trace down the issue.

**Comment by shyrz** [comment]
The same issue. Please help to check.

**Comment by prnake** [comment]
I think it's a known issue that The Initium disables access to the full text behind paywall via a fake (or real) search engine bot UA, which started in August. And I tested the full text accessing via configured password or token from a paid account works fine now.

**Comment by mintyfrankie** [comment]
Hi @prnake,

Just want to give a quick update on the issue; withe either `INITIUM_BEARER_TOKEN` or env variables on login and password it seems to work fine now; however the `INITIUM_IAP_RECEIPT` doesn't work anymore.

I sniffed the iOS application and found that it uses a standard `Authorization` header, with its value as `token xxxxx` rather than `Bearer xxxx`. Maybe it can be interesting to update the script, as from my testings this authorization method can keep alive much longer than bearer token.

I'd be happy to contribute and raise a PR if you want to, or you can patch a quick fix right away.

**Comment by mintyfrankie** [comment]
Also:

> I think it's a known issue that The Initium disables access to the full text behind paywall via a fake (or real) search engine bot UA started from August, which means only paid accounts can read the full text. And I tested the full text accessing via configured password or token from a paid account works fine now.

Perhaps then we don't need to fake a search bot anymore, as it cannot bypass the paywall. Can be interesting to do a cleanup on the script to streamline the logic.

**Comment by prnake** [comment]
> Hi @prnake,
> 
> Just want to give a quick update on the issue; withe either `INITIUM_BEARER_TOKEN` or env variables on login and password it seems to work fine now; however the `INITIUM_IAP_RECEIPT` doesn't work anymore.
> 
> I sniffed the iOS application and found that it uses a standard `Authorization` header, with its value as `token xxxxx` rather than `Bearer xxxx`. Maybe it can be interesting to update the script, as from my testings this authorization method can keep alive much longer than bearer token.
> 
> I'd be happy to contribute and raise a PR if you want to, or you can patch a quick fix right away.

It’s great if you would like to PR for the IOS login method. And although the current fake UA is not working, it does not cause side effects, so I think it’s not necessary to replace it.

**Comment by lucky13820** [comment]
I'm using my email and password, but it still fails to fetch full text, it shows Response code 401 (UNAUTHORIZED). Any idea why it doesn't work?

**Comment by mintyfrankie** [comment]
@lucky13820 I believe that we still haven't fixed the router on this issue; I'd like to work on this if possible but unfortunately I don't have the subscription anymore.

**Comment by lucky13820** [comment]
I’m happy to share my credentials for you to work on his router. How should I give it to you?  Thanks,Ryan Yao在 2024年5月27日，上午1:40，minty_frankie ***@***.***> 写道：﻿
@lucky13820 I believe that we still haven't fixed the router on this issue; I'd like to work on this if possible but unfortunately I don't have the subscription anymore.

**Comment by mintyfrankie** [comment]
> I’m happy to share my credentials for you to work on his router. How should I give it to you?  Thanks,Ryan Yao在 2024年5月27日，上午1:40，minty_frankie ***@***.***> 写道：﻿ @lucky13820 I believe that we still haven't fixed the router on this issue; I'd like to work on this if possible but unfortunately I don't have the subscription anymore. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

That would be great! You can email me on `minty at sent dot at`.

I will delete this message once your email is sent.

**Comment by mintyfrankie** [comment]
> I’m happy to share my credentials for you to work on his router. How should I give it to you?  Thanks,Ryan Yao在 2024年5月27日，上午1:40，minty_frankie ***@***.***> 写道：﻿ @lucky13820 I believe that we still haven't fixed the router on this issue; I'd like to work on this if possible but unfortunately I don't have the subscription anymore. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

That would be great! You can reach me at `gentle.flame4249 at fastmail.com`.
