### ISSUE TITLE
澎湃新闻图片及视频与正文重复

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#13401]
### 路由地址

```routes
/thepaper/featured
```

### 完整路由地址

```fullroutes
/thepaper/featured
```

### 相关文档

https://docs.rsshub.app/routes/traditional-media#peng-pai-xin-wen-shou-ye-tou-tiao

### 预期是什么？

全文获取仅包含正文内容。

### 实际发生了什么？

正文内图片与视频会被单独提取出来放在前面，而之后的正文部分也有图片与视频。
如 https://m.thepaper.cn/detail/24747910
![Screen Shot 2023-09-26 at 13 30 53](https://github.com/DIYgod/RSSHub/assets/31068367/c0392e28-9ec7-45af-b1d3-f58ba72b9729)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息
在代码中这似乎是故意如此设计的：
https://github.com/DIYgod/RSSHub/blob/8e6f87b988c67338e5ec3922a22d90aeb200d595/lib/v2/thepaper/utils.js#L36-L49

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by bigfei** [comment]
是故意这么设计的，有些rss软件不会显示media中的图片，而那个时候澎湃新闻的全文也不包括video image，由js动态插入。
目前可能澎湃新闻修改了逻辑，全文的api中也有了相应的内容。
建议增加一个toggle，默认为关闭，即不重复引用Video/image等内容，或者进一步的，智能判断对应的内容是否在description中包括。
欢迎提供PR
