### ISSUE TITLE
无法正常显示收藏夹内容

### ISSUE THREAD

**Issue by aantior** [DIYgod/RSSHub#13403]
### Routes

```routes
/bilibili/fav/:uid/:fid/:disableEmbed?
```

### Full routes

```fullroutes
/bilibili/user/fav/3356903/2043534403
```

### Related documentation

https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-mo-ren-shou-cang-jia

### What is expected?

已经如下格式（BILIBILI_COOKIE_1465080156="----"）添加自己的cookie到docker的env中，但无法访问路由/bilibili/user/fav/3356903/2043534403

### What is actually happening?

自建RSSHub，尝试doc文档默认的链接，可以正常访问。
https://rsshub.app/bilibili/fav/756508/50948568

但是更换收藏夹为自己的uid后，提示路由错误。

已经如下格式添加自己的cookie到docker的env中：

BILIBILI_COOKIE_1465080156="----"

### Deployment information

Self-hosted

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Qixingchen** [comment]
`/bilibili/user/fav/:uid/:disableEmbed?` `/bilibili/fav/:uid/:fid/:disableEmbed?` 测试均正常.目前不需要 cookie

请注意你 issue 中前后使用了不同的路由  
使用 UP 主默认收藏夹 `/bilibili/user/fav/:uid/:disableEmbed?` 只需要用户 uid ,请确认用户的默认收藏夹是公开的  
使用 UP 主非默认收藏夹 `/bilibili/fav/:uid/:fid/:disableEmbed?` 需要 uid 和收藏夹 fid ,也需要对应的收藏夹是公开的.  

![image](https://github.com/DIYgod/RSSHub/assets/4182240/b913f50c-a8d7-4249-9954-d8dee284effe)
你给的 uid 对应的用户收藏夹并不公开

**Comment by aantior** [comment]
该用户为我自己，我也提供了自己的 cookie，是否可以追加读取自己收藏夹的路由

--------------原始邮件--------------
发件人："qixingchen ***@***.***&gt;;
发送时间：2023年9月26日(星期二) 晚上6:06
收件人："DIYgod/RSSHub" ***@***.***&gt;;
抄送："aantior ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [DIYgod/RSSHub] 无法正常显示收藏夹内容 (Issue #13403)
-----------------------------------

 

 
/bilibili/user/fav/:uid/:disableEmbed? /bilibili/fav/:uid/:fid/:disableEmbed? 测试均正常.目前不需要 cookie
 
请注意你 issue 中前后使用了不同的路由
 使用 UP 主默认收藏夹 /bilibili/user/fav/:uid/:disableEmbed? 只需要用户 uid ,请确认用户的默认收藏夹是公开的
 使用 UP 主非默认收藏夹 /bilibili/fav/:uid/:fid/:disableEmbed? 需要 uid 和收藏夹 fid ,也需要对应的收藏夹是公开的.
 

 你给的 uid 对应的用户收藏夹并不公开

**Comment by Qixingchen** [comment]
改发一个新的 RSS 提案 issue  
https://github.com/DIYgod/RSSHub/issues/new/choose
