### ISSUE TITLE
javbus订阅提示需要登录

### ISSUE THREAD

**Issue by chouchouxsl** [DIYgod/RSSHub#13437]
### Routes

```routes
/javbus/studio/:id
```

### Full routes

```fullroutes
/javbus/studio/1
```

### Related documentation

httphttps://docs.rsshub.app/routes/multimedia#javbus

### What is expected?

可以正常访问

### What is actually happening?

javbus 订阅提示需要登录 自建服务也一样

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
JavBus - 登錄 - 老司機論壇 https://www.javbus.com/en JavBus - 登錄 - 老司機論壇 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub) RSSHub i@diygod.me (DIYgod) zh-cn Fri, 29 Sep 2023 00:02:17 GMT 120
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by uclinch** [comment]
同问，无法访问订阅地址，提示需要先登录才行。

**Comment by lifetyper** [comment]
需要在cookies中增加一个bus_auth键值，在scrapy中实测是可以的，不太懂rsshub里怎么实现。

**Comment by Hohenheimp** [comment]
同问，增加参数后还是需要登陆
