### ISSUE TITLE
MacOS/iOS app Reeder无法更新订阅

### ISSUE THREAD

**Issue by ImVictorCheng** [DIYgod/RSSHub#13443]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOTOUTE
```

### 相关文档

NOROUTE

### 预期是什么？

正常抓取内容，更新订阅

### 实际发生了什么？

Reeder返回错误提示：
Unable to Subscribe
A server with the specified hostname could not be found.

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Reeder app抓取其它rss订阅源正常，RSSHub提供的链接在浏览器访问能正常获取xml文件，但Reeder不能抓取RSSHub提供的RSS订阅文件。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
> A server with the specified hostname could not be found.

Make sure the computer can visit https://rsshub.app without any issues.
