### ISSUE TITLE
汽车之家论坛RSS

### ISSUE THREAD

**Issue by Nat30** [DIYgod/RSSHub#1344]
### 源站地址
https://club.autohome.com.cn/bbs/forum-c-692-1.html#pvareaid=6825482

### 需要生成什么内容？

- 论坛帖子内容
- 论坛帖子评论

### 额外描述
以上地址只是拿奥迪A4L论坛作为一个举例，希望能够RSS所有汽车之家论坛。

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
