### ISSUE TITLE
苹果商店 App Update 路由 app的平台细分提醒问题和优化建议

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#13456]
### 这是一个什么样的功能？

以 Stash 这个 app 为例，[ RSS 条目里](https://rsshub.app/apple/apps/update/us/id1596063349)出现了更新（2.4.3 和 2.4.5 版本），但实际上这两个版本只是更新了在 tvOS 上，在[网页商店](https://apps.apple.com/us/app/id1596063349)或者 iPhone 商店都刷新不出这两个版本（请见下图），因为我没有 apple TV，无法验证那上面是否可以获得这两个版本的更新，但推测是可以的。

![image](https://github.com/DIYgod/RSSHub/assets/3047708/c7067b7e-af8c-41c1-9e5c-41e06e0609de)

为了剔除没必要的干扰，有两个建议，供参考：

- 在现有的显示全部提醒的基础上，直接在 正文每个项目标题里 判断平台后加上 "on tvOS"、“on iOS”、"on macOS"等文字尾巴，订阅者可以用 filter 自行过滤。那整个 RSS 的标题里的 “for iOS”字段就可以拿掉了。
- 弄一个分类。如果不加参数，那默认是全部都提醒，如果在路由里加个小尾巴参数，可以设定需要平台的 app 更新提醒，比如iOS、macOS、tvOS 等。

以上两个想法是过滤方法不同，我个人倾向于第一个，更灵活一些。当然，我思考不周，或许有更好的方法。

### 这个功能可以解决什么问题？

获取需要平台的app更新提醒，尽量避免无效的提醒。

### 额外描述

无。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by ruleroller** [comment]
@nczitzk 谢谢大佬的出手~

也请考虑到可能一个更新是适用于多个平台的，比如同时可用于iOS以及tvOS等，不知道这种情况时有什么优雅的方法能够体现出来。

**Comment by nczitzk** [comment]
> @nczitzk 谢谢大佬的出手~

@ruleroller 客气了。根据你的建议和 App Store 提供的数据，我选择的方案如下。

在 `/apple/apps/update/:country/:id` 的基础上添加可选的 `platform` 参数，即路由变更为 `/apple/apps/update/:country/:id/:platform?`。其中，`platform` 参数可选 `iOS` 或 `macOS` 或 `tvOS`，即获取指定平台的更新内容。该参数留空则获取全部平台的更新内容。

在路由变更的基础上，我对获取条目的标题和分类也做了更改。其中，标题末尾加入 `for <platform>`，分类设定为 `<platform>` 分类。如此指明该更新内容条目针对的是何种平台，可以方便用户根据标题或分类进行筛选。

另外，“适用于多个平台的同一版本更新”在 App Store 的数据源中会分别罗列在每个平台的更新内容中，所以理应不会出现被筛选遗漏的情况。
