### ISSUE TITLE
微博不能获取多张配图

### ISSUE THREAD

**Issue by Glowin** [DIYgod/RSSHub#1345]
### 路由地址
https://rsshub.app/weibo/user2/1402400261

### 预期是什么？
按照原微博博主的个人主页，[这个微博](https://weibo.com/1402400261/Ha1Ftrtqb)是有三张配图，但是 RSSHub 的输出结果中只有一张配图。

### 实际发生了什么？
RSSHub 输出结果：
![image](https://user-images.githubusercontent.com/1147941/50581910-03ea9080-0e99-11e9-87ec-f6d112e7fa0b.png)

**Comment by Glowin** [comment]
看了一下源代码，发现从 `http://service.weibo.com/widget/widget_blog.php?uid=${uid}` 获取到的微博内容全都只显示一个配图，看来是数据源的问题。

**Comment by DIYgod** [comment]
微博有两种接口，用 `/weibo/user/:uid` 应该是可以的
