### ISSUE TITLE
RSS Route for Boston Review

### ISSUE THREAD

**Issue by ShijianXu** [DIYgod/RSSHub#13498]
### Category

Blog

### Website URL

https://www.bostonreview.net/

### Website description

Boston Review is a political and literary forum—a public space for discussion of ideas, politics, and culture. Independent and nonprofit, animated by hope and committed to equality, we believe in the power of collective reasoning and imagination to create a more just world.

### What content should be included?

All the articles.

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://www.bostonreview.net/feed/

**Comment by ShijianXu** [comment]
This RSS feed link does not work. It cannot extract all the articles from the website, only a few test samples.
<img width="1101" alt="Screenshot 2023-10-11 at 17 39 55" src="https://github.com/DIYgod/RSSHub/assets/15571333/96565492-4071-40d5-b8ef-67b473054192">

**Comment by ShijianXu** [comment]
solved: https://www.bostonreview.net/articles/feed/
