### ISSUE TITLE
希望能增加直接粘贴地址就是RSS地址的傻瓜操作

### ISSUE THREAD

**Issue by amozom** [DIYgod/RSSHub#135]
手机上转换微博的rss地址有点麻烦，希望能增加一个直接把微博主页接在vps地址后面就能生成RSS地址的功能。

比如，假设我的vps地址是baidu.com，我想订阅的博主是https://weibo.com/anotherhome，那么我输入baidu.com/https://weibo.com/anotherhome就是RSS地址。

或者能不能内建一个网址，然后有一个输入框，还有我粘贴https://weibo.com/anotherhome这个地址并提交，浏览器返回https://rsshub.app/weibo/user/3306934123给我用。

一点建议。

**Comment by DIYgod** [comment]
第一种方法导致会多一个请求，暂不考虑；第二种方法可以，但不属于 RSSHub 自身内容，低优先级

issue 将保持 open，欢迎 pr

**Comment by DIYgod** [comment]
@DIYgod https://github.com/zgq354/weibo-rss/blob/master/common/weibo.js#L72

**Comment by yingziwu** [comment]
创建一个书签就可以了，创建好了，点击一下就会自动打开相应的RSS页面。
书签的内容如下，可以根根需要自己修改。
```
javascript:function%20t(){if(location.host!='weibo.com'){alert('%E8%AF%B7%E5%9C%A8%E5%BE%AE%E5%8D%9A%E9%A1%B5%E9%9D%A2%E4%BD%BF%E7%94%A8');return}else{var%20id=/uid=(\d+)/.exec(document.querySelector('.opt_box%20.btn_bed').getAttribute('action-data'))[1];var%20base_url='https://rsshub.app';var%20router='/weibo/user/';window.open(base_url+router+id)}}t();
```
原本的javascript代码：
```javascript
function t() {
  if (location.host != 'weibo.com') {
    alert('请在微博页面使用');
    return;
  } else {
    var id = /uid=(\d+)/.exec(document.querySelector('.opt_box .btn_bed').getAttribute('action-data')) [1];
    var base_url = 'https://rsshub.app';
    var router = '/weibo/user/';
    window.open(base_url + router + id);
  }
}
t();
```

**Comment by DerekTso** [comment]
补充：
修改一下 `window.open` 中的 **RSS_URL**,  可以直接将 RSS 添加到 RSS reader
e.g. **inoreader**
```
var inoreader_addFeed = 'http://www.inoreader.com/?add_feed=';
window.open(inoreader_addFeed + base_url + router + id);
```

**Comment by NeverBehave** [comment]
https://github.com/NeverBehave/RSShub-Generator

基于目前已有的规则建立的生成器，为了做一个可以直接基于链接订阅RSS的Bot
理论是可以完全前端实现但是目前的文档似乎不是很方便改动。目前只有API接口
