### ISSUE TITLE
求更新2048地址

### ISSUE THREAD

**Issue by lanshizhe** [DIYgod/RSSHub#13500]
### 类型

音视频

### 网站地址

https://dwd2go.com/

### 网站描述

2048地址过期了，这是新地址https://dwd2go.com/

### 需要生成什么内容？

2048地址过期了，这是新地址https://dwd2go.com/

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Not a new RSS proposal.
