### ISSUE TITLE
Readhub 路由失效

### ISSUE THREAD

**Issue by shyrz** [DIYgod/RSSHub#13525]
### 路由地址

```routes
/readhub/:category?/:overview?
```

### 完整路由地址

```fullroutes
/readhub
/readhub/category/topic
```

### 相关文档

https://docs.rsshub.app/routes/new-media#readhub

### 预期是什么？

Readhub 网页内容

### 实际发生了什么？

报错 404
![image](https://github.com/DIYgod/RSSHub/assets/5728981/be4cd265-2876-4c5a-bb74-b9221cd4ecad)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /
Node version: v18.18.1
Git Hash: c05524b
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by fashioncj** [comment]
https://api.readhub.cn 这个接口被下掉了...

**Comment by shyrz** [comment]
> [api.readhub.cn](https://api.readhub.cn) 这个接口被下掉了...

我在他们官网看到的请求里还有 api.readhub.cn, 但是只用作信息流滚动更新，首屏加载没有

https://api.readhub.cn/topic/list?max_topic_id=8Tx1PpZUvcH&size=20
