### ISSUE TITLE
All Spotify-related routes return errors

### ISSUE THREAD

**Issue by TheTwoRites** [DIYgod/RSSHub#13547]
### 路由地址

```routes
/spotify/artist/:id
/spotify/playlist/:id
/spotify/saved/:limit?
/spotify/top/tracks
/spotify/top/artists
/spotify/show/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/spotify/artist/6k9TBCxyr4bXwZ8Y21Kwn1
https://rsshub.app/spotify/playlist/4UBVy1LttvodwivPUuwJk2
https://rsshub.app/spotify/saved/50
https://rsshub.app/spotify/top/tracks
https://rsshub.app/spotify/top/artists
https://rsshub.app/spotify/show/38bS44xjbVVZ3No3ByF1dJ
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#spotify

### 预期是什么？

For playlist route, should return RSS feed XML containing playlist info and tracks.
For album route, should return RSS feed XML containing album info and tracks.
For artist route, should return RSS feed XML containing new releases/tracks by the artist.

### 实际发生了什么？

Looks like something went wrong
Route requested: /artist/6k9TBCxyr4bXwZ8Y21Kwn1
Error message: Spotify public RSS is disabled due to the lack of [relevant config](https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi)
Helpful Information to provide when opening issue:
Path: /artist/6k9TBCxyr4bXwZ8Y21Kwn1
Node version: v18.18.2
Git Hash: ed1f70c
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
        
For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

在线文档与支持，请访问 [docs.rsshub.app](https://docs.rsshub.app/)。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /artist/6k9TBCxyr4bXwZ8Y21Kwn1
Error message: Spotify public RSS is disabled due to the lack of relevant config
Helpful Information to provide when opening issue:
Path: /artist/6k9TBCxyr4bXwZ8Y21Kwn1
Node version: v18.18.2
Git Hash: ed1f70c
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Please take look at the error messages and the docs.
