### ISSUE TITLE
Colamanga漫画更新RSS

### ISSUE THREAD

**Issue by jukkui** [DIYgod/RSSHub#13565]
### 类型

二次元

### 网站地址

https://www.colamanga.com/

### 网站描述

免费漫画网站

### 需要生成什么内容？

希望可以生成漫画更新通知

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #11692
