### ISSUE TITLE
希望添加惠誉评级的rss

### ISSUE THREAD

**Issue by hehe007** [DIYgod/RSSHub#1357]
### 源站地址
https://www.fitchratings.com/site/search?content=fitchwire
https://www.fitchratings.com/site/economics
一个网站下的2个版块
### 需要生成什么内容？

- [x] 内容一：fitchwire页面的rss
- [ ] 内容二：economics页面的rss

### 额外描述
希望可以全文输出，谢谢！

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
