### ISSUE TITLE
文档页滚动也太卡了

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [DIYgod/RSSHub#1360]
### 路由地址
不是关于项目本身，是关于[指南文档](https://docs.rsshub.app/#%E9%B8%A3%E8%B0%A2)的

### 预期是什么？
能正常浏览

### 实际发生了什么？
滚动非常卡顿，体验极差
![image](https://user-images.githubusercontent.com/12682063/50754796-dbe0a000-1291-11e9-9563-e86c0db97a81.png)

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/12682063/50754845-07638a80-1292-11e9-8670-2fde1eadca30.png)

**Comment by tgly307** [comment]
vuepress的问题，暂时好没办法解决，建议使用左边的导航栏快速跳转

**Comment by zhengxiaoyao0716** [comment]
@tgly307 不是吧？[以前的文档](https://github.com/DIYgod/RSSHub/tree/1530143396782ac9c3539b65c89c1fd6effb8edc)没这么卡的啊？

**Comment by tgly307** [comment]
![image](https://user-images.githubusercontent.com/25153311/50760342-7fd24780-12a2-11e9-86fa-6933991b3ba8.png)
和GA关系不大，是滚动的时候触发的滚动事件用时太长了。

**Comment by zhengxiaoyao0716** [comment]
那个勇士太长的滚动时间可能就是GA？毕竟每次滚动都能看到控制台网络多一条请求

**Comment by tgly307** [comment]
不是，去掉GA跑起来一样的

**Comment by zhengxiaoyao0716** [comment]
哦，那就确实不是了。没事，我直接看Markdown吧

**Comment by KellyHwong** [comment]
> 哦，那就确实不是了。没事，我直接看Markdown吧

好方法_(:з」∠)_
