### ISSUE TITLE
【知乎用户动态】网页端改版 报错 Error message: Failed to extract `d_c0` from cookies

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#13651]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/diygod
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常推送

### 实际发生了什么？

自建 报错  Error message: Failed to extract `d_c0` from cookies

官方 403

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
是不是api又换了，f12反馈的api为

https://www.zhihu.com/api/v3/moments/shen-chen-7-10/activities?offset=1698466135354&page_num=1

用户

https://www.zhihu.com/people/shen-chen-7-10

https://www.zhihu.com/people/86b4e03e7fbbe1c4adf161f86b47b088
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/diygod
```
