### ISSUE TITLE
希望 api 返回的路由列表中加入路由的名称或描述字段

### ISSUE THREAD

**Issue by imgss** [DIYgod/RSSHub#1365]
### 这是一个什么样的功能？
希望 api 返回的路由列表中加入路由的名称或描述字段，例如下面的路由：

`https://rsshub.app/api/routes/mzitu`

当前返回的数据格式如下:

```js
mzitu: {
  routes: [
    "/mzitu/home/:type?",
    "/mzitu/tags",
    "/mzitu/category/:category",
    "/mzitu/post/:id",
    "/mzitu/tag/:tag"
 ]
},

```
增加名称字段后：

```js
mzitu: {
  name: '妹子图',
  routes: [
    ...
 ]
}
```

### 这个功能可以解决什么问题？

给每个路由一个对用户友好的名称，开发应用时便于展示

**Comment by HenryQW** [comment]
https://rsshub.app/rsshub/rss.rss
