### ISSUE TITLE
BBC中文网只有主页，没有其他频道的选项

### ISSUE THREAD

**Issue by 1amfine2333** [DIYgod/RSSHub#13657]
### 路由地址

```routes
/bbc/:lang/:channel?
```

### 完整路由地址

```fullroutes
/bbc/chinese/
/bbc/chinese/world
/bbc/chinese/china
/bbc/chinese/uk
/bbc/chinese/business
/bbc/chinese/interactive
/bbc/chinese/multimedia
/bbc/chinese/indepth
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#bbc-bbc-zhong-wen-wang

### 预期是什么？

范围下面的频道，返回相应的频道rss数据
/bbc/chinese/world
/bbc/chinese/china
/bbc/chinese/uk
/bbc/chinese/business
/bbc/chinese/interactive
/bbc/chinese/multimedia
/bbc/chinese/indepth

### 实际发生了什么？

返回报错，429

Route requested: /chinese/world
Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://rsshub.app/bbc/chinese/world

Route requested: /chinese/world
Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /chinese/world
Node version: v18.18.2
Git Hash: bd6528e
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by HenryQW** [comment]
429是被数据源限流了，不是代码逻辑的问题。

**Comment by 1amfine2333** [comment]
我看文档中，可以通过Cloudflare Workers配置反向代理url，明天配置下试试
