### ISSUE TITLE
【 国家市场监督管理总局留言咨询】certificate has expired

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#13673]
### 路由地址

```routes
/gov/samr/xgzlyhd/:category?/:department?
```

### 完整路由地址

```fullroutes
https://rsshub.app/gov/samr/xgzlyhd
```

### 相关文档

https://docs.rsshub.app/routes/government#guo-jia-shi-chang-jian-du-guan-li-zong-ju

### 预期是什么？

正常工作

### 实际发生了什么？

无法工作

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /samr/xgzlyhd
Error message: certificate has expired: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /samr/xgzlyhd
Node version: v18.18.2
Git Hash: 51ac5f8

---

感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by People-11** [comment]
这不是 RSSHub 的问题，目标网站的证书在昨天过期了，所以出现了这个错误。请联系或等待目标网站更新其证书。
也可以在代码内添加 `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;` 以绕过证书检查，但是我不建议这样做，因为这会导致安全问题。

**Comment by KwToPA** [comment]
已经恢复
