### ISSUE TITLE
半岛电视台路由失效

### ISSUE THREAD

**Issue by congnews** [DIYgod/RSSHub#13672]
### 路由地址

```routes
/aljazeera/:language?/:category?
/aljazeera/:language?/tag/:id
```

### 完整路由地址

```fullroutes
/aljazeera/english/news
/aljazeera/chinese/news
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#aljazeera-ban-dao-dian-shi-tai

### 预期是什么？

返回半岛电视台网站最新新闻

### 实际发生了什么？

Route requested: /chinese/news
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /chinese/news
Node version: v18.18.2
Git Hash: 51ac5f8

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v18.18.2

### 额外信息

```shell
Route requested: /chinese/news
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /chinese/news
Node version: v18.18.2
Git Hash: 51ac5f8
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Fixed in #13671

**Comment by TonyRL** [comment]
/test
```routes
/aljazeera/english/news
/aljazeera/chinese/news
```
