### ISSUE TITLE
dytt无法订阅

### ISSUE THREAD

**Issue by ljhnchina** [DIYgod/RSSHub#13688]
### 路由地址

```routes
/dytt
```

### 完整路由地址

```fullroutes
https://rsshub.app/dytt
```

### 相关文档

https://github.com/imgss

### 预期是什么？

rss能打开订阅

### 实际发生了什么？

出现错误

### 部署

自建

### 部署相关信息

container manager 20.10.23-1437

### 额外信息

```shell
Route requested: /dytt
Error message: unable to verify the first certificate: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /dytt
Node version: v18.18.2
Git Hash: 9002602
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #12946
