### ISSUE TITLE
小黑盒路由出错

### ISSUE THREAD

**Issue by sakurayang** [DIYgod/RSSHub#13686]
### 路由地址

```routes
/xiaoheihe/news
```

### 完整路由地址

```fullroutes
/xiaoheihe/news
```

### 相关文档

https://docs.rsshub.app/zh/routes/game#xiao-hei-he-you-xi-xin-wen

### 预期是什么？

得到正常的xml输出

### 实际发生了什么？

pull 下来调试了一下，发现是[这一行](https://github.com/DIYgod/RSSHub/blob/e8212ff05ef1f4a10c4ce9ca1db27b12702e1886/lib/routes/xiaoheihe/news.js#L9)出了问题。
其中 data 是
```json
{
  "status": "failed",
  "msg": "您的版本过低，请您更新版本",
  "version": "1.0",
  "result": {
  },
}
```

于是对原 url 进行了修改
```diff
https://api.xiaoheihe.cn/maxnews/app/list?tag=-1&offset=0&limit=30&rec_mark=timeline&heybox_id=12777814&imei=867252032615972&os_type=Android&os_version=9
-&version=1.1.55
+&version=1.3.290
&_time=1551801017&hkey=b28cd7a1cba463b4d9176ba2f8f42d35
```

随后提示系统时间错误

于是对原 url 进行了修改
```diff
https://api.xiaoheihe.cn/maxnews/app/list?tag=-1&offset=0&limit=30&rec_mark=timeline&heybox_id=12777814&imei=867252032615972&os_type=Android&os_version=9&version=1.3.290
-&_time=1551801017
+&_time=${Math.round(new Date().getTime()/1000)}
&hkey=b28cd7a1cba463b4d9176ba2f8f42d35
```

随后提示验证参数不正确

翻阅相关仓库，从 [chr233/xhh_auto](https://github.com/chr233/xhh_auto) 与 [chr233/Xiaoheihe_CShape](https://github.com/chr233/Xiaoheihe_CShape) 这两个仓库中发现小黑盒对请求的验证发生了变化。

~P.S. 上班摸鱼的时候弄的，再摸就要被 gank 了 修不动orz~

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /xiaoheihe/news
Error message: response.data.result.filter is not a function
Helpful Information to provide when opening issue:
Path: /xiaoheihe/news
Node version: v18.18.2
Git Hash: d595dab
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #11511

**Comment by TonyRL** [comment]
You can take a look at https://github.com/huandu/heybox-url as well.
