### ISSUE TITLE
路透社中国分区503

### ISSUE THREAD

**Issue by 1amfine2333** [DIYgod/RSSHub#13727]
### 路由地址

```routes
/reuters/:category/:topic?
```

### 完整路由地址

```fullroutes
/reuters/world/china
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#reuters-lu-tou-she

### 预期是什么？

https://rsshub.app/reuters/world/china
现在报错503，自部署也是503
<img width="1179" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/b5084479-937f-4286-adae-dd0c84758f6a">
路透社官网正常
<img width="942" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/7c2d0d92-5bea-46e5-89d4-4a431794121f">
us正常
<img width="1073" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/d856d8f8-2d21-429e-b7ea-1a4498d04e36">

### 实际发生了什么？

现在报错503
<img width="1179" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/b5084479-937f-4286-adae-dd0c84758f6a">
自部署也是503
<img width="1048" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/88f61662-8a6b-464d-95f4-9070b8a56dc4">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /world/china
Error message: Response code 503 (Service Temporarily Unavailable): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /world/china
Node version: v18.18.2
Git Hash: 04b47ef
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/reuters/world/china
```

**Comment by TonyRL** [comment]
This article
https://www.reuters.com/video/us-chinese-officials-held-arms-control-talks-monday-state-dept-2023-11-07/
is causing 503.

**Comment by 1amfine2333** [comment]
> As you can see from the [log](https://github.com/DIYgod/RSSHub/actions/runs/6792997853/job/18467141715#step:9:33), this article https://www.reuters.com/video/us-chinese-officials-held-arms-control-talks-monday-state-dept-2023-11-07/ is causing 503.

有没有什么解决办法之类的，之后可能还会有文章503的情况

**Comment by 1amfine2333** [comment]
能否配置检测到503，跳过

**Comment by black-desk** [comment]
单篇文章503就打个warning跳过?

**Comment by 1amfine2333** [comment]
> 单篇文章503就打个warning跳过?

感觉可以的，跳过单篇503的文章再生成xml吧

**Comment by 1amfine2333** [comment]
也可以这样，访问单篇的时候，状态码不等于200的时候，直接跳过抓起内容，这样也能保证生成rss.xml
