### ISSUE TITLE
电子科技大学教务处通知rss没有内容

### ISSUE THREAD

**Issue by sklf** [DIYgod/RSSHub#1372]
### 路由地址
https://rsshub.app/uestc/jwc/student
### 预期是什么？
可以查看教务处通知
### 实际发生了什么？
只能查看标题，无法获取内容
### 部署相关信息
使用rsshub.app, 客户端为ios端的reeder3

### 额外信息（日志、报错等）
无

**Comment by imlonghao** [comment]
恐怕无法实现，查看教务处通知的详细内容需要电子科技大学内网访问权限。

> 对不起，您无法访问此页面！
> 您现在正在进入电子科技大学教务处网，由于您的IP地址非电子科技大学的IP地址，因此被限制访问！

**Comment by DIYgod** [comment]
无法实现，issue 将被关闭
