### ISSUE TITLE
懂球帝 dongqiudi 的 专题 路由 失效

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#13761]
### 路由地址

```routes
/dongqiudi/special/:id
```

### 完整路由地址

```fullroutes
dongqiudi/special/41
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#dong-qiu-di-zhuan-ti

### 预期是什么？

正确生成RSS条目。

### 实际发生了什么？

报错，如下图：
![image](https://github.com/DIYgod/RSSHub/assets/3047708/232923bf-5dfc-41a4-85e0-b26630c5912f)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
- 自建也同样出错。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed in #13781.
