### ISSUE TITLE
自建RSSHub，希望增加B站UP所有视频列表的功能

### ISSUE THREAD

**Issue by aantior** [DIYgod/RSSHub#13806]
### 这是一个什么样的功能？

目前的UP主视频仅显示最近的20条，但是由于是自建的RSSHub，希望能够有选项列出所有的UP主视频

### 这个功能可以解决什么问题？

列出所有的UP主视频

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
#10352

**Comment by Vstory** [comment]
看来根本就没有搜索issuse
