### ISSUE TITLE
知乎文章获取失败显示 502

### ISSUE THREAD

**Issue by Mapz** [DIYgod/RSSHub#13815]
### Routes

```routes
/zhihu/posts/:usertype/:id
```

### Full routes

```fullroutes
/zhihu/posts/people/xiang-tian-ying
```

### Related documentation

https://docs.rsshub.app/routes/social-media#zhi-hu

### What is expected?

正常处理返回

### What is actually happening?

Looks like something went wrong
Route requested: /zhihu/posts/people/xiang-tian-ying
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /zhihu/posts/people/xiang-tian-ying
Node version: v20.9.0
Git Hash: 05d53e0
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
        
For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

在线文档与支持，请访问 [docs.rsshub.app](https://docs.rsshub.app/)。

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/posts/people/xiang-tian-ying
```
