### ISSUE TITLE
bdys 哔嘀影视 只获取到一个种子下载链接

### ISSUE THREAD

**Issue by o5rhaxzc** [DIYgod/RSSHub#13835]
### 路由地址

```routes
/bdys/:caty?/:type?/:area?/:year?/:order?
```

### 完整路由地址

```fullroutes
/bdys/all/1/%E4%B8%AD%E5%9B%BD%E9%A6%99%E6%B8%AF/2023/0
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#bi-di-ying-shi

### 预期是什么？

应该获取全部的torrent下载链接

### 实际发生了什么？

只获取到一个地址
![image](https://github.com/DIYgod/RSSHub/assets/149476903/56ef9576-d1ba-40f5-a685-81b1bafd3ccf)
网站是有两个的
![image](https://github.com/DIYgod/RSSHub/assets/149476903/782cd7f2-7019-4878-89f5-34432ff7aa92)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
‎
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
This is expected behavior. As suggested by the [RSS Best Practices Profile](https://www.rssboard.org/rss-profile#element-channel-item-enclosure), RSSHub only provides one enclosure.
