### ISSUE TITLE
使用docker compose安裝時，映像檔docker-warp-socks無法解析域名

### ISSUE THREAD

**Issue by shiefu** [DIYgod/RSSHub#13854]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/install#%E5%AE%89%E8%A3%85

### 预期是什么？

可以回報docker-warp-socks作者DNS無法解析的狀況，並更新版解決此問題

### 实际发生了什么？

docker-warp-socks無法解析域名的問題

### 部署

自建

### 额外信息

```shell
docker logs docker-warp-socks-1出現無法解析域名的錯誤訊息，經確認(有實際進到container中進行測試)是該image的問題。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Upstream issue https://github.com/Mon-ius/Docker-Warp-Socks/issues/20 and probably https://github.com/ViRb3/wgcf/issues/158

**Comment by yimmy23** [comment]
可以考虑使用如下代理：https://github.com/aleskxyz/warp-svc

这是我修改后的docker compose:

`version: '3.9'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'  # marked
            PROXY_URI: 'socks5h://warp-socks:1080'
        depends_on:
            - redis
            - browserless  # marked

    browserless:  # marked
        image: browserless/chrome  # marked
        restart: always  # marked
        ulimits:  # marked
          core:  # marked
            hard: 0  # marked
            soft: 0  # marked

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

    warp:  # new warp service
        image: aleskxyz/warp-svc:latest
        expose:
            - 1080
        restart: always
        environment:
            WARP_LICENSE: xxxxxxxx-xxxxxxxx-xxxxxxxx #get license from https://t.me/generatewarpplusbot.
            FAMILIES_MODE: off
        volumes:
            - ./warp:/var/lib/cloudflare-warp


volumes:
    redis-data:
`
