### ISSUE TITLE
bilibili 所有 rss 链接全部失效

### ISSUE THREAD

**Issue by chaixuqing** [DIYgod/RSSHub#13882]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/video/2267573
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#bilibili

### 预期是什么？

返回该up主的所有投稿的 RSS 链接

### 实际发生了什么？

Route requested: /user/video/2267573
Error message: Got error code -352 while fetching: 风控校验失败
Helpful Information to provide when opening issue:
Path: /user/video/2267573
Node version: v20.10.0
Git Hash: 3c87558

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /user/video/2267573
Error message: Got error code -352 while fetching: 风控校验失败
Helpful Information to provide when opening issue:
Path: /user/video/2267573
Node version: v20.10.0
Git Hash: 3c87558
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```

**Comment by liaohui5** [comment]
有解决办法了吗?

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/video/2267573
```
