### ISSUE TITLE
[Bilibili 系 RSS] RSS Title 的用户名偶发性显示为 undefined

### ISSUE THREAD

**Issue by Just-Prog** [DIYgod/RSSHub#13917]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/1459104794
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#bilibili-up-zhu-tou-gao

### 预期是什么？

```
<title>
<![CDATA[ MyGO_AveMujica 的 bilibili 空间 ]]>
</title>
```

### 实际发生了什么？

```
<title>
<![CDATA[ undefined 的 bilibili 空间 ]]>
</title>
```

偶尔会复现此状态，有时会恢复到预期行为，动态内容的获取均正常未出现问题

### 部署

自建

### 部署相关信息

Vercel / NodeJS: 18.x / Git: ee901f8 / Branch: master

### 额外信息

```shell
暂无

在9月份的issues记录中有发现一部分相关错误的报告 #13293 #13334 ，不清楚是否依然是用户名接口风控的因素。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Just-Prog** [comment]
route address: /bilibili/user/video/:uid/:disableEmbed?
full route address: /bilibili/user/video/1459104794

**Comment by TonyRL** [comment]
Duplicate of #13334
