### ISSUE TITLE
Error message: [object Object] at Bluestacks5

### ISSUE THREAD

**Issue by slord399** [DIYgod/RSSHub#13940]
### Routes

```routes
/bluestacks/release/5
```

### Full routes

```fullroutes
/bluestacks/release/5
```

### Related documentation

https://docs.rsshub.app/

### What is expected?

Could load Bluestacks5 Changelog.

### What is actually happening?

Error message: [object Object]

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Looks like something went wrong

Route requested: /release/5

Error message: [object Object]

Helpful Information to provide when opening issue:
Path: /release/5
Node version: v20.10.0
Git Hash: c1c757c
        

If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报
        

For online documentation and support please refer to docs.rsshub.app.

在线文档与支持，请访问 docs.rsshub.app。
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/bluestacks/release/5
```
