### ISSUE TITLE
增加对传送门全文抓取的支持

### ISSUE THREAD

**Issue by kevin7lou** [DIYgod/RSSHub#1397]
### 这是一个什么样的功能？
1. 希望对[传送门](https://chuansongme.com)的各个频道进行RSS全文抓取
1. 通过对该站的某个公众号进行RSS全文抓取，从而实现更稳定的“微信公众号”的RSS订阅

### 这个功能可以解决什么问题？
1. 相比于[即刻和瓦斯来源](https://docs.rsshub.app/#%E5%BE%AE%E4%BF%A1)，传送门可以实现更稳定的“微信公众号”的RSS订阅

### 额外描述
无

**Comment by alphardex** [comment]
https://rsshub-python.herokuapp.com/chuansongme/articles
没做全文的，因为请求过多导致heroku上直接瘫了

**Comment by HenryQW** [comment]
传送门不提供公众号直链，不是很想支持
