### ISSUE TITLE
141jav 403

### ISSUE THREAD

**Issue by AiraNadih** [DIYgod/RSSHub#13996]
### 路由地址

```routes
/141jav/:type?/:keyword?
```

### 完整路由地址

```fullroutes
/141jav/popular/30
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#141jav

### 预期是什么？

正常返回

### 实际发生了什么？

403 。包括自建的。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /141jav/popular/30
Node version: v20.10.0
Git Hash: 8ec0902
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/141jav/popular/30
```

**Comment by TonyRL** [comment]
/test
```routes
/141jav/popular/30
```

**Comment by TonyRL** [comment]
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/b489f052-57ff-46cb-869a-348091367743)
</details>
