### ISSUE TITLE
Error message: Invalid cookie

### ISSUE THREAD

**Issue by MoLinOwO** [DIYgod/RSSHub#14002]
### 路由地址

```routes
/instagram/2/:category/:key
```

### 完整路由地址

```fullroutes
rsshub.app/instagram/2/user/tw.nikke
包含自建:
rss.vtbmoyu.com/instagram/2/user/tw.nikke
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#instagram

### 预期是什么？

顯示RSS XML網頁內容

### 实际发生了什么？

Error message: Invalid cookie

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

OS:ubuntu , Node version: v20.10.0 Docker: v24.0.7

### 额外信息

```shell
Route requested: /instagram/2/user/tw.nikke
Error message: Invalid cookie
Helpful Information to provide when opening issue:
Path: /instagram/2/user/tw.nikke
Node version: v20.10.0
Git Hash: 06e3892
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/instagram/2/user/tw.nikke
```

**Comment by TonyRL** [comment]
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/2b3958b6-2602-4220-b3bc-ee4e32d73ce0)
</details>

**Comment by MoLinOwO** [comment]
我知道怎麼新增Cookie了，但有時候還是會失效

**Comment by TonyRL** [comment]
/test
```routes
/instagram/2/user/tw.nikke
```

**Comment by TonyRL** [comment]
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/89b3900a-de9f-4793-a732-8959009fa14e)
</details>
