### ISSUE TITLE
推特获取当前用户时间线报错

### ISSUE THREAD

**Issue by a805034104** [DIYgod/RSSHub#14005]
### 路由地址

```routes
/twitter/user/abskoop
```

### 完整路由地址

```fullroutes
http://172.245.134.180:1200/twitter/user/abskoop
```

### 相关文档

https://docs.rsshub.app/routes/social-media#twitter

### 预期是什么？

想要访问推特当前用户时间线

### 实际发生了什么？

发生报错：Route requested: /twitter/user/abskoop

Error message: Invalid twitter oauth tokens

Helpful Information to provide when opening issue:
Path: /twitter/user/abskoop
Node version: v20.10.0
Git Hash: 06e3892
        

### 部署

自建

### 部署相关信息

Linux，Node version: v20.10.0，docker version：latest

### 额外信息

```shell
Route requested: /twitter/user/abskoop

Error message: Invalid twitter oauth tokens

Helpful Information to provide when opening issue:
Path: /twitter/user/abskoop
Node version: v20.10.0
Git Hash: 06e3892
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by a805034104** [comment]
请重新审核一下
![Uploading 图片.png…]()

**Comment by a805034104** [comment]
![Uploading a8596866d9ab8479560eeda977dc6fe.png…]()

**Comment by a805034104** [comment]
![817924b9aeb98dcc25bf0445330afd7](https://github.com/DIYgod/RSSHub/assets/130194654/29802045-f413-4a30-8ea8-8dd76fb0064a)

**Comment by a805034104** [comment]
![Uploading a8596866d9ab8479560eeda977dc6fe.png…]()

**Comment by zhgqthomas** [comment]
这是因为部署的时候环境变量里没有配置 twitter 的oauth token，https://docs.rsshub.app/install/config#twitter
