### ISSUE TITLE
Neil Patel's Digital Marketing Blog

### ISSUE THREAD

**Issue by 1oneisall** [DIYgod/RSSHub#14037]
### Category

Social Media

### Website URL

https://neilpatel.com/blog/

### Website description

Resource for digital marketing tips, trends, and strategies to help you build a successful online business.

### What content should be included?

Blog articles

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://neilpatel.com/blog/feed/
