### ISSUE TITLE
主线版本在 heroku 更新失败

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1403]
### 路由地址
*.herokuapp.com
### 预期是什么？
将heroku app 与主线版本同步
### 实际发生了什么？
Automatic deployment of XXXX（项目名称） failed.
An automatic deployment for XXXX（项目名称） failed. To inspect the failure you can view the build log.
You can check that the user who connected the app or pipeline to GitHub still has access to the app and to the Github repository.
In this case, reconnecting to GitHub will often fix the issue.
If you believe that this build failure was not due to an issue in your app, please open a support ticket.
### 部署相关信息
使用fork自主线版本的项目 https://github.com/yefoenix/RSSHub 与heroku进行关联，保持项目更新。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
安装日志如下：

-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=false
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  >=8.0.0
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=8.0.0...
       Downloading and installing node 11.6.0...
       Using default npm version: 6.5.0-next.0
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.13.0)...
       Installed yarn 1.13.0
       
-----> Restoring cache
       Caching has been disabled because NODE_MODULES_CACHE=false
       
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.13.0
       [1/4] Resolving packages...
       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
 !     Outdated Yarn lockfile
       Your application contains a Yarn lockfile (yarn.lock) which does not
       match the dependencies in package.json. This can happen if you use npm
       to install or update a dependency instead of Yarn.
       Please run the following command in your application directory and check
       in the new yarn.lock file:
       $ yarn install
       $ git add yarn.lock
       $ git commit -m "Updated Yarn lockfile"
       $ git push heroku master
    
       https://kb.heroku.com/why-is-my-node-js-build-failing-because-of-an-outdated-yarn-lockfile
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by DIYgod** [comment]
fixed
