### ISSUE TITLE
Using TypeScript

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#14069]
### What feature is it?

Convert all js modules to ts modules to get better code suggestions and error prompts.

### What problem does this feature solve?

The current types are too chaotic, and it is also difficult to detect code errors.

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by bzy-debug** [comment]
really like this project and wanna help with this issue, any instructions?

**Comment by DIYgod** [comment]
No instructions, this change is too big, and I don't know where to start.

**Comment by JimenezLi** [comment]
#7531
