### ISSUE TITLE
希望增加华尔街见闻的RSS

### ISSUE THREAD

**Issue by kevin7lou** [DIYgod/RSSHub#1408]
### 源站地址
华尔街见闻 https://wallstreetcn.com/

### 需要生成什么内容？
- [ ] 最新咨询
- [ ] 最热文章
- [ ] 主题 

### 额外描述
1. 希望全文抓取

**Comment by HenryQW** [comment]
@kevin7lou 见非全文版 #1405

**Comment by HenryQW** [comment]
官方源：https://dedicated.wallstreetcn.com/rss.xml

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭

**Comment by lvii** [comment]
https://dedicated.wallstreetcn.com/rss.xml 失效了，还是希望能支持一下全文输出
