### ISSUE TITLE
请回退Commit ea6ec94 (至少其中的myft部分代码)

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#14096]
### 这是一个什么样的功能？

回退 ea6ec949bf619402fe7697680d34953f2eecc6a3

### 这个功能可以解决什么问题？

恢复myft等路由功能。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by DIYgod** [comment]
This route is no longer valid, and rolling back will not help. However, you can submit a pull request to fix it.

**Comment by dzx-dzx** [comment]
I rollbacked on my self hosted server and it works. 

I conjure that, you might believe the route is not working because the `example` field for this route in the documentation is `/ft/myft/rss-key`, which *is* an invalid route since the real way to use it is to replace the `rss-key` with the key obtained from one's own ft account. It is not expected to be tested for validity.

**Comment by dzx-dzx** [comment]
@DIYgod I can give my own example if I can contact you in private,
