### ISSUE TITLE
https://papers.cool/arxiv/

### ISSUE THREAD

**Issue by nick008a** [DIYgod/RSSHub#14118]
### Category

Scientific Journal

### Website URL

https://papers.cool/arxiv/cs.CV

### Website description

https://zhuanlan.zhihu.com/p/674190123

### What content should be included?

英文版和 Kimi摘要

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by nczitzk** [comment]
> 如果能加上Kimi摘要就更完美了！ @nczitzk

原文链接是指向 Kimi 摘要的，可以通过访问原网址查看到 😊
