### ISSUE TITLE
NOROUTE 使用docker启动rsshub，能够看到首页，但是无法解析任何路由

### ISSUE THREAD

**Issue by maoze** [DIYgod/RSSHub#14133]
### Routes

```routes
/twitter/user/DIYgod
```

### Full routes

```fullroutes
/twitter/user/DIYgod
```

### Related documentation

https://docs.rsshub.app/install

### What is expected?

rsshub可以正常使用

### What is actually happening?

Route requested: /twitter/user/DIYgod
Error message: Invalid twitter oauth tokens
Helpful Information to provide when opening issue:
Path: /twitter/user/DIYgod
Node version: v20.10.0
Git Hash: https://github.com/DIYgod/RSSHub/commit/2eefc7fecc52caf826bf3c3b72f356d84a249fb6

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS:Ubuntu 22.04.3 LTS，docker 24.0.5

### Additional info

```shell
我使用aws的美国的ecs，系统信息如上。我按照install文档，分别使用docker-compose和docker启动了rsshub，这两种方式都能看到首页，但输入路由就报错。
rsshub运行在1200端口，我加了nginx代理。但由于一直有问题，我目前的测试方法是在ecs上使用curl localhost:1200/twitter/user/DIYgod来测试，但也报同样的错误。
我在本地使用命令curl https://rsshub.app/twitter/user/DIYgod是没问题的
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by la3rence** [comment]
https://docs.rsshub.app/zh/install/config#twitter

> 鉴于 Twitter 和其 API 访问的最新变化，已经设计了一种新的匿名访问 Twitter 的方法。该方法涉及使用在通过 Android 应用程序进行注册流程时创建的临时访客账户。
详细信息请参阅 [Nitter - Guest Account Branch Deployment](https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment) 和 [zedeus/nitter#983](https://github.com/zedeus/nitter/issues/983)。
另外我们也准备了一个 Node.js 脚本来帮助你使用代理批量创建这些 token，[请点击这里](https://github.com/DIYgod/RSSHub/tree/master/scripts/twitter-token/generate.js)。
`TWITTER_OAUTH_TOKEN`: 支持多个 key，用英文逗号 , 隔开
`TWITTER_OAUTH_TOKEN_SECRET`: 支持多个 key，用英文逗号 , 隔开
