### ISSUE TITLE
北京市教育科学规划网 课题申报 立项课题

### ISSUE THREAD

**Issue by fredericky123** [DIYgod/RSSHub#14168]
### 类型

政务消息

### 网站地址

https://gh.bjedu.cn/ghsite/bjghktsb/index.html

### 网站描述

北京市教育科学规划网相关课题的申报和公示

### 需要生成什么内容？

关于课题的申报和公示生成内容推送

### 额外描述

https://gh.bjedu.cn/ghsite/bjghlxkt/index.html

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by fredericky123** [comment]
@TonyRL 
谢谢，试了这两个还是无法订阅，不知哪里的bug
https://rsshub.app/gov/beijing/bjedu/gh/zxtzgg
https://rsshub.app/gov/beijing/bjedu/gh/bjghktsb

**Comment by TonyRL** [comment]
Deploy your own instace if you want the latest changes. Demo instances have a delayed update schedule.

**Comment by fredericky123** [comment]
Thank you!
