### ISSUE TITLE
domp4，当有多种下载地址时，只会爬取第一种下载地址

### ISSUE THREAD

**Issue by qinghao101** [DIYgod/RSSHub#14181]
### 这是一个什么样的功能？

比如繁华这个电视剧，有两种语言，1.沪语版  2.普通话 ，当用ID去rss时，只会取到沪语版，普通话则没有被取到，希望可以取到全部的数据 @savokiss 求求了大佬！

### 这个功能可以解决什么问题？

获取到想要的语种

### 额外描述

非常感谢您

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by qinghao101** [comment]
刚想起来，可以增加一个url在id后边吗？比如***/id/下载地址1 | 下载地址2 这样子

**Comment by savokiss** [comment]
繁花这个确实比较特殊，两个下载地址的资源不一样，目前只取的第一个，我看看怎么区分一下~

**Comment by qinghao101** [comment]
谢谢大佬回复，再次感谢大佬！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月5日(周五) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DIYgod/RSSHub] domp4，当有多种下载地址时，只会爬取第一种下载地址 (Issue #14181)




 
繁花这个确实比较特殊，两个下载地址的资源不一样，目前只取的第一个，我看看怎么区分一下~

**Comment by qinghao101** [comment]
大佬好！我下载了最新的docker镜像，但仍旧没有效果，是你提交的代码还未被合并吗？




　　小色魔.
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIYgod/RSSHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIYgod/RSSHub] domp4，当有多种下载地址时，只会爬取第一种下载地址 (Issue #14181)





 
Closed #14181 as completed via #14189.

**Comment by qinghao101** [comment]
不对，不好意思大佬，好像可以了，感谢感谢！！




　　小色魔.
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIYgod/RSSHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIYgod/RSSHub] domp4，当有多种下载地址时，只会爬取第一种下载地址 (Issue #14181)





 
Closed #14181 as completed via #14189.
