### ISSUE TITLE
新增功能参数：second，加上后并未有效的获取下载地址二

### ISSUE THREAD

**Issue by qinghao101** [DIYgod/RSSHub#14195]
### 路由地址

```routes
domp4/detail/
```

### 完整路由地址

```fullroutes
domp4/detail/A8kjc4333334?second=2
domp4/detail/A8kjc4333334?second=1
domp4/detail/A8kjc4333334
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#domp4-ying-shi

### 预期是什么？

domp4/detail/A8kjc4333334?second=2    
预期用于获取下载地址二

domp4/detail/A8kjc4333334
预期用于获取下载地址一

### 实际发生了什么？

domp4/detail/A8kjc4333334?second=1   
参数我尝试了  “A8kjc4333334?second=1 ”  与  “A8kjc4333334?second=2”  与  `**“A8kjc4333334”**，但发现内容都一样，获取的均是普通话版，也就是下载地址二，虽然满足了我的需求，但是确实是有bug，我怕影响其他的使用者使用此功能，既然是我提出的问题需求，那我就有责任提出因此需求产生的bug，请查看一下

domp4/detail/A8kjc4333334
如上一个url及参数遇到的问题描述，此url与参数并未获取到沪语版的下载地址一，而是获取到了下载地址二，也就是普通话版，请查看一下

刚测试，好像这两个地址结果会混在一起，或者说，会隔段时间统一变为普通话或者沪语版：要不，一段时间都是普通话，要不，一段时间都是沪语版，不知道是啥情况

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

自建：群晖docker  , 演示：挂梯子访问

### 额外信息

```shell
使用两种方式：
1、自建：群晖docker  
2、演示：挂梯子访问 

两种方式的访问地址，均是  会隔段时间统一变为普通话或者沪语版  的情况
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by qinghao101** [comment]
@savokiss 不好意思又打扰了，遇到些问题，麻烦看看，因为是我前两天提的需求，遇到了bug，心里挺忐忑的，赶紧写个bug测试报告给您

**Comment by savokiss** [comment]
从现象上看估计是针对路由 path 有缓存，但是对 query 没有。
你个人用的话先用 `second=1` 访问，拿的就是下载地址二的，然后一定时间内不加 second 拿的是地址一的，等缓存时间过期就正常了。
因为大部分地址一和二都一样，所有一般不会影响其他人使用，后续我再想想办法优化嗯。

**Comment by qinghao101** [comment]
好嘞，谢谢！




　　小色魔.
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DIYgod/RSSHub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月6日(星期六) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DIYgod/RSSHub] 新增功能参数：second，加上后并未有效的获取下载地址二 (Issue #14195)





 
从现象上看估计是针对路由 path 有缓存，但是对 query 没有。
 你个人用的话先用 second=1 访问，拿的就是下载地址二的，然后一定时间内不加 second 拿的是地址一的，等缓存时间过期就正常了。
 因为大部分地址一和二都一样，所有一般不会影响其他人使用，后续我再想想办法优化嗯。
