### ISSUE TITLE
twitter动态图片和视频的自动播放和循环播放

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#1421]
### 这是一个什么样的功能？
twitter动态图片和视频的自动播放和循环播放
### 这个功能可以解决什么问题？
提升查看动态图的体验，目前因为需要不断的点开内容-->右键勾选循环播放-->点播放-->关闭内容，如果能自动播放并循环播放，会带来很大改观。感谢大佬！
### 额外描述
无

**Comment by DIYgod** [comment]
一般来说，除非用户有足够的预期，自动播放并不是一个很好的体验

**Comment by tomatomash** [comment]
> 一般来说，除非用户有足够的预期，自动播放并不是一个很好的体验

在twitter上是的，不过在阅读器里没有点击图片任何地方开始播放的功能，结果是每次都要点击那个特别小的播放键😭大佬你怎么看

**Comment by DIYgod** [comment]
@tomatomash 可以把 video 大小弄大点
