### ISSUE TITLE
Twitter keyword route throws an error when processing a keyword with a hash

### ISSUE THREAD

**Issue by anatoliykmetyuk** [DIYgod/RSSHub#14225]
### Routes

```routes
/twitter/keyword/:keyword/:routeParams?
```

### Full routes

```fullroutes
/twitter/keyword/:keyword/:routeParams?
```

### Related documentation

https://docs.rsshub.app/routes/social-media#twitter-keyword

### What is expected?

https://rsshub.app/twitter/keyword/#Bitcoin - when using a route with a hash symbol, it should work.

### What is actually happening?

It shows an error:

```
Route requested: /twitter/keyword/
Error message: wrong path
Helpful Information to provide when opening issue:
Path: /twitter/keyword/
Node version: v20.10.0
Git Hash: 12b409f
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
When you remove the hash symbol from the keyword, it works: https://rsshub.app/twitter/keyword/Bitcoin
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Use `/twitter/keyword/%23Bitcoin` instead.
`#` should be encoded.

**Comment by anatoliykmetyuk** [comment]
@TonyRL RSSHub Radar doesn't automatically encode the hash and therefore, when you try to subscribe to a keyword hashtag feed via Radar, it reports an error.
