### ISSUE TITLE
b站u主专栏，最近的专栏只显示一行字，早期的专栏还能正常显示内容

### ISSUE THREAD

**Issue by glassywater** [DIYgod/RSSHub#14231]
### 路由地址

```routes
/bilibili/user/article/:uid
```

### 完整路由地址

```fullroutes
/bilibili/user/article/36397742
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#bilibili-up-zhu-zhuan-lan

### 预期是什么？

![image](https://github.com/DIYgod/RSSHub/assets/42326344/1d200ef6-5b7b-4797-8ccf-7c850cf8f2b1)
预期是正常显示专栏内容

### 实际发生了什么？

![image](https://github.com/DIYgod/RSSHub/assets/42326344/5393d7e0-1b72-41ac-90c6-af02e61abb66)
![image](https://github.com/DIYgod/RSSHub/assets/42326344/b48a8a10-3a9a-4ad4-b3ca-ef3b06d666f6)
实际是近期的专栏只有个标题，很早之前的专栏倒是能正常显示

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Path: /bilibili/user/article/36397742
Node version: v14.20.0
Git Hash: unknown
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Qixingchen** [comment]
新的专栏改了格式,需要另外从 API 中抓取,而且需要自行格式化. 这个 API 也有较强的反爬.
