### ISSUE TITLE
new site support

### ISSUE THREAD

**Issue by akashmuraliNEW** [DIYgod/RSSHub#14239]
### What feature is it?

Can you add 1tamilmv site please

### What problem does this feature solve?

Helps many peoples think

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
This is **indeed** a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by akashmuraliNEW** [comment]
Added please check
