### ISSUE TITLE
洋同学的宏观笔记 RSS支持

### ISSUE THREAD

**Issue by Laeoo** [DIYgod/RSSHub#14269]
### 类型

博客

### 网站地址

https://ocmacro.com/

### 网站描述

政策研究

### 需要生成什么内容？

https://ocmacro.com/database
https://ocmacro.com/fed
https://ocmacro.com/144b70a4c2a641f798ebc3dbc1abb3c6

这几个sub page 的文章

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #10871
