### ISSUE TITLE
Discord route is down

### ISSUE THREAD

**Issue by anatoliykmetyuk** [DIYgod/RSSHub#14262]
### Routes

```routes
/discord/channel/:channelId
```

### Full routes

```fullroutes
/discord/channel/:channelId
```

### Related documentation

https://docs.rsshub.app/routes/social-media#discord

### What is expected?

For it to work.

### What is actually happening?

Error message: Discord RSS is disabled due to the lack of [relevant config](https://docs.rsshub.app/en/install/#configuration-route-specific-configurations)
Helpful Information to provide when opening issue:
Path: /discord/channel/950465850056536084
Node version: v20.11.0
Git Hash: 987d6fe

### Deployment information

Self-hosted

### Additional info

The relevant  config is in fact provided.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
The error is quite obvious.
You need to provide a valid Discord authorization token obtained to your self-hosted RSSHub instance from your browser as mentioned in the [relevant config](https://docs.rsshub.app/en/install/#configuration-route-specific-configurations) docs.

<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/9aedcb24-bc18-4196-a16e-9a164bc68a4e)
</details>

Make sure you've joined the server(guild).
The example `/discord/channel/950465850056536084` listed in the docs is an announcement channel from [Discord Admin Community Server](https://support.discord.com/hc/en-us/articles/5309276245271-Discord-Admin-Community-FAQ)

**Comment by anatoliykmetyuk** [comment]
@TonyRL as mentioned in the issue, I did configure the instance as described. I obtained the token from here:

<img width="458" alt="Screenshot 2024-01-16 at 21 04 34" src="https://github.com/DIYgod/RSSHub/assets/2614813/948c1dfa-f3d4-42d6-9c6a-0470e830cf0e">

Then I put it under DISCORD_AUTHORIZATION envvar on my instance as specced.

**Comment by TonyRL** [comment]
> Note also how in the [docs page](https://docs.rsshub.app/routes/social-media#discord-channel-messages) the example is indicated as "down" giving the same error I described.

Because the demo instances do not have this variable set.

Since you didn't mention how you deployed your instance, what I can only tell you is that your instance does not have this env set. 
Either it's because the cache is taking precedence or the instance is deployed without this env.
FYI, an invalid token will throw an error of `Response code 401 (Unauthorized)` instead.

**Comment by anatoliykmetyuk** [comment]
> Since you didn't mention how you deployed your instance, what I can only tell you is that your instance does not have this env set.

I just connected a terminal to that instance, ran `echo $DISCORD_AUTHORIZATION`, and got the output I set. So the variable must be set. Yet, the error is exactly the one I mentioned, not 401.
