### ISSUE TITLE
twitter : Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by tjsky** [DIYgod/RSSHub#14281]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/DIYgod
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#twitter

### 预期是什么？

正确订阅用过户时间线

### 实际发生了什么？

报错

### 部署

自建

### 部署相关信息

Docker：24.0.7

### 额外信息

```shell
Route requested: /twitter/user/DIYgod
Error message: Cannot read properties of undefined (reading 'match')
Helpful Information to provide when opening issue:
Path: /twitter/user/DIYgod
Node version: v20.11.0
Git Hash: 30c453e（自部署）|6d901cb（演示站）

实际测试自部署和演示站都会报同同样的错
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by DIYgod** [comment]
Fixed in 1574105a922f5074c234d13d4edc06a5336cf268
