### ISSUE TITLE
Heroku 部署下抖音报错

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1430]
### 路由地址
*.herokuapp.com/douyin/user/:id
### 预期是什么？
获取指定用户作品列表
### 实际发生了什么？
报错（如下）
### 部署相关信息

heroku 同步主线分制最新版
| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
RSSHub 发生了一些意外:
Error: Failed to launch chrome!
[0118/041630.896870:ERROR:platform_thread_posix.cc(128)] pthread_create: Resource temporarily unavailable (11)
[0118/041630.913967:ERROR:platform_thread_posix.cc(128)] pthread_create: Resource temporarily unavailable (11)
[0118/041630.927645:ERROR:platform_thread_posix.cc(128)] pthread_create: Resource temporarily unavailable (11)
[0118/041630.927695:FATAL:simple_thread.cc(56)] Check failed: success. 
#0 0x558e22ae17df base::debug::StackTrace::StackTrace()
#1 0x558e22a5af70 logging::LogMessage::~LogMessage()
#2 0x558e22ab857f base::SimpleThread::Start()
#3 0x558e2175eb16 content::GpuProcessTransportFactory::GpuProcessTransportFactory()
#4 0x558e21305a33 content::BrowserMainLoop::BrowserThreadsStarted()
#5 0x558e216a2b67 content::StartupTaskRunner::RunAllTasksNow()
#6 0x558e213052b6 content::BrowserMainLoop::CreateStartupTasks()
#7 0x558e21309060 content::BrowserMainRunnerImpl::Initialize()
#8 0x558e26a7d5da headless::HeadlessContentMainDelegate::RunProcess()
#9 0x558e226bee46 content::ContentMainRunnerImpl::Run()
#10 0x558e226f042b service_manager::Main()
#11 0x558e226bd111 content::ContentMain()
#12 0x558e26a7c488 headless::(anonymous namespace)::RunContentMain()
#13 0x558e26a7c515 headless::HeadlessBrowserMain()
#14 0x558e226ee8b2 headless::HeadlessShellMain()
#15 0x558e208051ac ChromeMain
#16 0x7fb3f436ab97 __libc_start_main
#17 0x558e2080502a _start

Received signal 6
#0 0x558e22ae17df base::debug::StackTrace::StackTrace()
#1 0x558e22ae1351 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fb3fa5df890 
#3 0x7fb3f4387e97 gsignal
#4 0x7fb3f4389801 abort
#5 0x558e22ae0185 base::debug::BreakDebugger()
#6 0x558e22a5b3e2 logging::LogMessage::~LogMessage()
#7 0x558e22ab857f base::SimpleThread::Start()
#8 0x558e2175eb16 content::GpuProcessTransportFactory::GpuProcessTransportFactory()
#9 0x558e21305a33 content::BrowserMainLoop::BrowserThreadsStarted()
#10 0x558e216a2b67 content::StartupTaskRunner::RunAllTasksNow()
#11 0x558e213052b6 content::BrowserMainLoop::CreateStartupTasks()
#12 0x558e21309060 content::BrowserMainRunnerImpl::Initialize()
#13 0x558e26a7d5da headless::HeadlessContentMainDelegate::RunProcess()
#14 0x558e226bee46 content::ContentMainRunnerImpl::Run()
#15 0x558e226f042b service_manager::Main()
#16 0x558e226bd111 content::ContentMain()
#17 0x558e26a7c488 headless::(anonymous namespace)::RunContentMain()
#18 0x558e26a7c515 headless::HeadlessBrowserMain()
#19 0x558e226ee8b2 headless::HeadlessShellMain()
#20 0x558e208051ac ChromeMain
#21 0x7fb3f436ab97 __libc_start_main
#22 0x558e2080502a _start
  r8: 0000000000000000  r9: 00007fff2f765e90 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fff2f766a80 r13: 0000000000000047 r14: 00007fff2f766a88 r15: 00007fff2f766a90
  di: 0000000000000002  si: 00007fff2f765e90  bp: 00007fff2f7660e0  bx: 00007fff2f766140
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fb3f4387e97  sp: 00007fff2f765e90
  ip: 00007fb3f4387e97 efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:193:15)
    at Interface.EventEmitter.emit (domain.js:441:20)
    at Interface.close (readline.js:395:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:193:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by DIYgod** [comment]
See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-heroku

**Comment by yefoenix** [comment]
![_20190120235832](https://user-images.githubusercontent.com/8215230/51441730-605e0480-1d0f-11e9-8de2-569986818f4b.png)
尝试过同时加上两个 buildpack 以及分别增加其中一个，依然会报错。我发现是在每次重新 Deploy 之后可以短暂地正常运行一段时间，大概几十分钟之后就开始报错了。
@DIYgod
