### ISSUE TITLE
川流严选 RSS bug

### ISSUE THREAD

**Issue by Passionfruit-055** [DIYgod/RSSHub#14318]
### 路由地址

```routes
/chuanliu/nice
```

### 完整路由地址

```fullroutes
https://rsshub.app/chuanliu/nice
```

### 相关文档

NULL

### 预期是什么？

生成订阅源

### 实际发生了什么？

订阅源无法加载

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v20.11.0

### 额外信息

```shell
Route requested: /chuanliu/nice
Error message: wrong path
Helpful Information to provide when opening issue:
Path: /chuanliu/nice
Node version: v20.11.0
Git Hash: 542d039
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Passionfruit-055** [comment]
不是很确定是否是路由的问题

**Comment by TonyRL** [comment]
/test
```routes
/chuanliu/nice
```
