### ISSUE TITLE
韩国联合通讯社 cn.yna.co.kr

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#14332]
### Category

Social Media

### Website URL

https://cn.yna.co.kr/

### Website description

韩国联合通讯社，有官方RSS：
https://cn.yna.co.kr/channel/rss
但无法正常添加到FreshRSS中
cURL error 35: OpenSSL/3.0.11: error:0A000152:SSL routines::unsafe legacy renegotiation disabled [https://cn.yna.co.kr/RSS/news.xml]

### What content should be included?

https://cn.yna.co.kr/channel/rss

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by libukai** [comment]
我也遇到了这个问题，是对方服务器的 SSL 配置版本问题吗？

**Comment by Limour-dev** [comment]
通过 Github Action进行转换后可以了：https://github.com/Limour-dev/Rss-Translation/raw/main/rss/yna_cn.xml
