### ISSUE TITLE
instagram: Error message: Cannot read properties of undefined (reading 'edges')

### ISSUE THREAD

**Issue by imTHAI** [DIYgod/RSSHub#14355]
### Routes

```routes
/instagram/2/:category/:key
```

### Full routes

```fullroutes
Route requested: /instagram/2/user/shannenmichaela
```

### Related documentation

https://docs.rsshub.app/routes/social-media#instagram

### What is expected?

xml page

### What is actually happening?
```shell
Route requested: /instagram/2/user/shannenmichaela
Error message: Cannot read properties of undefined (reading 'edges')
Helpful Information to provide when opening issue:
Path: /instagram/2/user/shannenmichaela
Node version: v20.11.0
Git Hash: a712fd5
```

### Deployment information (for self-hosted)

RSSHub docker container on my home server (unraid).

### Additional info
For some users it works, for some users like this one above, it gives this error message.
(I've set my IG_USERNAME and IG_PASSWORD through ENV variables)

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
It works.
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/36479aab-0f76-4cae-841e-6482ab7dd999)
</details>

Please note that `IG_USERNAME` and `IG_PASSWORD` are for `/instagram/:category/:key`.
