### ISSUE TITLE
Socks5 proxy error for retrieving Twitter User timeline

### ISSUE THREAD

**Issue by 0xRaduan** [DIYgod/RSSHub#14374]
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/gregisenberg
```

### Related documentation

https://docs.rsshub.app/routes/social-media#twitter-user-timeline

### What is expected?

I am self-hosting RSSHub and expecting to retrieve tweets of a user(I have created an account and also have made 2FA)
I am expecting to retrieve RSS feed of a user timeline.

### What is actually happening?

I get next error:
```
Error message: Socks5 proxy rejected connection - HostUnreachable: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /twitter/user/gregisenberg
Node version: v20.11.0
Git Hash: 002302f
```

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: MacOS, Docker version 20.10.12

### Additional info

```shell
Feb  2 11:23:10 (1706872990.962914) danted[72]: info: block(1): tcp/connect ]: 172.18.0.5.38426 172.18.0.2.9091: could not resolve hostname "api.twitter.com": Temporary failure in name resolution
Feb  2 11:23:10 (1706872990.965972) danted[72]: info: block(1): tcp/accept ]: 172.18.0.5.38426 172.18.0.2.9091: request was not performed due to error: could not resolve hostname "api.twitter.com": Temporary failure in name resolution
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by 0xRaduan** [comment]
Updated routes, this was a mistake.

**Comment by 0xRaduan** [comment]
from what i can see, perhaps an issue is on my side, because I am trying some telegram routes as well – and hitting same socks5 issue.

I also missed doc part, where it says not to enable 2FA for twitter. I disabled it, however still facing troubles.

**Comment by 0xRaduan** [comment]
Yep, I think the issue was in socks5. Will wait for maintainers to comment, but once I removed proxy_url env variable – I was able to access it properly(both twitter and telegram).

I have few questions, which I will post in a different thread.

**Comment by Rongronggg9** [comment]
Your proxy is facing a DNS failure. Try both `socks5://` and `socks5h://`?

**Comment by TonyRL** [comment]
Closed since socks proxy support was removed in #14922
