### ISSUE TITLE
代理添加不行

### ISSUE THREAD

**Issue by sherlcok314159** [DIYgod/RSSHub#14375]
### Routes

```routes
twitter/user/_akhaliq
```

### Full routes

```fullroutes
no
```

### Related documentation

https://docs.rsshub.app/zh/install/config#%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE

### What is expected?

正常运行

### What is actually happening?

无论是 http 在 7890，还是 socks 在 7891，均是一样的结果

![image](https://github.com/DIYgod/RSSHub/assets/76043326/afda49c1-6baa-4815-8844-00ba8f02345e)

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Ubuntu 20.04; Docker: 24.0.6, build ed223bc

### Additional info

```shell
docker-compose.yml 如下，config.yaml 是没问题的


version: '3'

services:
    clash:
        image: dreamacro/clash
        restart: always
        ports:
            - "5090:9090"
            - "5890:7890"
            - "5891:7891"
        volumes:
            - ./config.yaml:/root/.config/clash/config.yaml

    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000' # marked
            # 以下两种都试过，不行
            PROXY_URI: "socks://clash:7891" # 代理，若不使用代理则去掉代理相关配置
            PROXY_URI: "http://clash:7890" # 代理，若不使用代理则去掉代理相关配置
        depends_on:
            - clash
            - redis
            - browserless # marked

    browserless:
        # marked
        image: browserless/chrome # marked
        restart: always # marked
        ulimits:
            # marked
            core:
                # marked
                hard: 0 # marked
                soft: 0 # marked
        depends_on:
            - clash
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by sherlcok314159** [comment]
需要重新审核，谢谢

**Comment by TonyRL** [comment]
https://docs.docker.com/compose/networking/

**Comment by sherlcok314159** [comment]
谢谢你的参与，不过你提供的我并未发现有效的解决方案

**Comment by TonyRL** [comment]
https://docs.docker.com/compose/networking/

```yml
  db:
    image: postgres
    ports:
      - "8001:5432"
```

> It is important to note the distinction between `HOST_PORT` and `CONTAINER_PORT`. In the above example, for `db`, the `HOST_PORT` is `8001` and the container port is `5432` (postgres default). Networked service-to-service communication uses the `CONTAINER_PORT`. When `HOST_PORT` is defined, the service is accessible outside the swarm as well.

**Comment by sherlcok314159** [comment]
抱歉我还是没办法理解这有助于解决我的问题，我在 `docker-compose.yml`中用了：

```yml
PROXY_URL: "http://clash:7890"
```

**Comment by sherlcok314159** [comment]
给后面的朋友指条路，首先在 linux clash 上的 配置得是：

```yml
allow-lan: true
bind-address: "*"
```
接着在 docker-compose.yml 文件中加入以下环境变量，这个 `172.17.0.1` 是你运行 `ifconfig` 中关于 docker 的地址

```yml
PROXY_PROTOCOL: http
PROXY_HOST: 172.17.0.1
PROXY_PORT: 7890
```

题外话，如果是其他容器也需要代理，就在 environment 中加入：

```yml
- HTTP_PROXY=http://172.17.0.1:7890
- HTTPS_PROXY=http://172.17.0.1:7890
```
