### ISSUE TITLE
艾瑞-周度市场观察 目标地址变更，无法更新

### ISSUE THREAD

**Issue by wym1ng** [DIYgod/RSSHub#14384]
### 路由地址

```routes
/iresearch/weekly/:category?
```

### 完整路由地址

```fullroutes
https://rsshub.app/iresearch/weekly
```

### 相关文档

https://docs.rsshub.app/routes/other#ai-rui-zhou-du-shi-chang-guan-cha

### 预期是什么？

希望大佬能修复路由，感谢

### 实际发生了什么？

原目标订阅地址「周度市场观察」从(https://www.iresearch.com.cn/report.shtml?type=3) 变改为 (https://www.iresearch.com.cn/report?type=3) ，导致订阅失败

### 部署

自建

### 额外信息

```shell
订阅失败
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Wym1ng** [comment]
@nczitzk 大佬打扰了，这个路由地址用官方服务或个人自建都可以正常打开，和之前一样，但内容只能读取到2023年第8周，实际一直更到到现在24年的，这个要怎么解决呢
