### ISSUE TITLE
【BUG】王者荣耀B站直播 信息读取错误

### ISSUE THREAD

**Issue by 9k001** [DIYgod/RSSHub#14386]
### Routes

```routes
/bilibili/live/room/:roomID
```

### Full routes

```fullroutes
/bilibili/live/room/:roomID
```

### Related documentation

https://docs.rsshub.app/routes/live#bi-li-bi-li-zhi-bo-zhi-bo-kai-bo

### What is expected?

预期为该直播间直播状态

### What is actually happening?

错误信息，即一直保持老旧信息.

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Docker

### Additional info

```shell
<description>
<![CDATA[ 哔哩哔哩王者荣耀赛事 直播间开播状态 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub) ]]>
</description>
<generator>RSSHub</generator>
<webMaster>i@diygod.me (DIYgod)</webMaster>
<language>zh-cn</language>
<lastBuildDate>Sat, 03 Feb 2024 09:52:16 GMT</lastBuildDate>
<ttl>5</ttl>
<item>
<title>
<![CDATA[ 【直播】杭州LGD.NBW vs 济南RW侠 2023-11-03 11:48:50 ]]>
</title>
<description>
<![CDATA[ 【直播】杭州LGD.NBW vs 济南RW侠<br> ]]>
</description>
<pubDate>Fri, 03 Nov 2023 03:48:50 GMT</pubDate>
<guid isPermaLink="false">https://live.bilibili.com/21144080 2023-11-03 11:48:50</guid>
<link>https://live.bilibili.com/21144080</link>
</item>
</channel>
</rss>
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/live/room/21144080
```

**Comment by Qixingchen** [comment]
/bilibili/live 系列路由返回使用最近一次开播时间,以便 rss 阅读器确认信息是否变动.这是预期行为

**Comment by 9k001** [comment]
> /bilibili/live 系列路由返回使用最近一次开播时间,以便 rss 阅读器确认信息是否变动.这是预期行为

目前来看，获取到的开播时间，从当前时间来看，是错误的。
我预计，可能是不是本身这个直播间的开播时间就是个错的，又或者是网站加了跳转 ？
目前来看，其他直播间没有出现相同的问题。

**Comment by Qixingchen** [comment]
> > /bilibili/live 系列路由返回使用最近一次开播时间,以便 rss 阅读器确认信息是否变动.这是预期行为
> 
> 目前来看，获取到的开播时间，从当前时间来看，是错误的。 我预计，可能是不是本身这个直播间的开播时间就是个错的，又或者是网站加了跳转 ？ 目前来看，其他直播间没有出现相同的问题。

跳到55直播间了,估计是这个原因.

**Comment by Qixingchen** [comment]
看了下 55直播间b站显示已经开播2651小时了,开播时间是 2023-11-03  没有错.

**Comment by 9k001** [comment]
> 看了下 55直播间b站显示已经开播2651小时了,开播时间是 2023-11-03 没有错.

那看起来 形式变成了 直播-录播-直播，然后循环不停的形式。
这种就不好做判断了
