### ISSUE TITLE
Error message: this route is empty, please check the original site or create an issue

### ISSUE THREAD

**Issue by slord399** [DIYgod/RSSHub#14398]
### Routes

```routes
/bluestacks/release/5
```

### Full routes

```fullroutes
/bluestacks/release/5
```

### Related documentation

https://docs.rsshub.app/

### What is expected?

Could load Bluestacks5 Changelog.

### What is actually happening?

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Looks like something went wrong

Route requested: /bluestacks/release/5

Error message: this route is empty, please check the original site or create an issue

Helpful Information to provide when opening issue:
Path: /bluestacks/release/5
Node version: v20.11.0
Git Hash: c93226c
        

If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/bluestacks/release/5
```

**Comment by TonyRL** [comment]
It works.
