### ISSUE TITLE
自托管bilibili路由，提示风控校验失败

### ISSUE THREAD

**Issue by isylhcq** [DIYgod/RSSHub#14399]
### Routes

```routes
/someroute/:bilibili
```

### Full routes

```fullroutes
/bilibili/user/video/1863500961
```

### Related documentation

https://rsshub-doc.pages.dev/social-media.html#bilibili

### What is expected?

自托管rsshub返回正确的rss信息

### What is actually happening?

![无标题](https://github.com/DIYgod/RSSHub/assets/158831181/8cccb84e-5c6a-4769-9ee4-ae7280e94086)
Got error code -352 while fetching: 风控校验失败

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

windows（docker desktop），Node version: v20.11.0，docker version： 25.0.2

### Additional info

```shell
Looks like something went wrong
Route requested: /bilibili/user/video/1863500961
Error message: Got error code -352 while fetching: 风控校验失败
Helpful Information to provide when opening issue:
Path: /bilibili/user/video/1863500961
Node version: v20.11.0
Git Hash: 23dfb6c
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by isylhcq** [comment]
不是所有的路由都无法匹配，而是在bilibili路由中[反爬严格]的路由无法使用，但是这是在自托管的情况下

**Comment by Minamoto25** [comment]
请问有解决办法了吗

**Comment by xiangshu168** [comment]
同求解决方案！

**Comment by rxlxr11** [comment]
https://github.com/DIYgod/RSSHub/issues/14124,我参考的这个，已解决

**Comment by rxlxr11** [comment]
参考https://github.com/DIYgod/RSSHub/issues/14124
