### ISSUE TITLE
instagram : Error message: GET /api/v1/feed/user/46250204949/ - 400 Bad Request; feedback_required

### ISSUE THREAD

**Issue by imTHAI** [DIYgod/RSSHub#14394]
### Routes

```routes
/instagram/:category/:key
```

### Full routes

```fullroutes
/instagram/user/hello.abandoned.world
/instagram/user/officialslystallone
/instagram/user/prendsunfruit
/instagram/user/timetotraveloftheworld
etc...
```

### Related documentation

https://docs.rsshub.app/routes/social-media#instagram-user-profile-hashtag-private-api

### What is expected?

Return the subscription file.

### What is actually happening?
```shell
Route requested: /instagram/user/hello.abandoned.world
Error message: GET /api/v1/feed/user/46250204949/ - 400 Bad Request; feedback_required
Helpful Information to provide when opening issue:
Path: /instagram/user/hello.abandoned.world
Node version: v20.11.0
Git Hash: b552dad
```
### Deployment information

Self-hosted

### Deployment information (for self-hosted)

docker (under unraid)

### Additional info

I've set my instagram's login & password.

It looks like more and more accounts return this error.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Login the same account on Instagram App/Web and make sure your account is not limited.

**Comment by imTHAI** [comment]
@TonyRL  I will start a second RSShub with another instagram login/password, and behind a different ip. I hope it will go better.
