### ISSUE TITLE
javdb empty route

### ISSUE THREAD

**Issue by 0x136253** [DIYgod/RSSHub#14423]
### 路由地址

```routes
/javdb/actors/:id/:filter?
```

### 完整路由地址

```fullroutes
/javdb/actors/Xa1G/d
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#javdb-zhu-ye

### 预期是什么？

返回正确结果

### 实际发生了什么？

实际显示this route is empty
![image](https://github.com/DIYgod/RSSHub/assets/39185568/11ee5c97-b8b9-42dc-9a7b-82b8fd80f788)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

docker  diygod/rsshub:chromium-bundled:latest

### 额外信息

```shell
none
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by 0x136253** [comment]
经测试，原因为javdb网站现在对部分功能要求先登录才可使用(上述路由中的/d)，可否增加类似配置以携带对应的认证信息

**Comment by hqwuzhaoyi** [comment]
我觉得可以手动加入cookie，我来测试下
