### ISSUE TITLE
从nitter间接获取Twitter推文

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#14439]
### 类型

社交媒体

### 网站地址

https://status.d420.de/

### 网站描述

不是所有的nitter instance都支持rss，且它的rss连接指向nitter而非Twitter

### 需要生成什么内容？

推文内容，推特连接

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by CXwudi** [comment]
这个可能跟问题无关, 但通过https://status.d420.de/获取带有RSS的nitter实例不是问题, 但问题是相同的推文在不同的nitter实例里生成的RSS是不一样的. 因为所有的图片链接都会指向nitter实例的链接, 这就会导致load balancing不可行, 因为TTRSS会认为这是不一样的两个推文

**Comment by 0x3f97** [comment]
现在有无订阅twitter rss的办法

**Comment by CXwudi** [comment]
@0x3f97 只能自建rsshub然后登陆小号了
