### ISSUE TITLE
twitter : Error message: Invalid twitter configs

### ISSUE THREAD

**Issue by imTHAI** [DIYgod/RSSHub#14447]
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/DIYgod
```

### Related documentation

https://docs.rsshub.app/routes/social-media#twitter

### What is expected?

xml output

### What is actually happening?

This error message:
Route requested: /twitter/user/DIYgod
Error message: Invalid twitter configs
Helpful Information to provide when opening issue:
Path: /twitter/user/DIYgod
Node version: v20.11.0
Git Hash: fc84c92

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

docker

### Additional info

```shell
I have tried other twitter usernames.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by spencer17x** [comment]
Me too.

**Comment by E1xP** [comment]
For the docker images tag 2024-02-15. Just  config username and password can get the Twitter feed.

**Comment by lanewu** [comment]
I tried image 2024-02-15 with username and password configured,
```
fail, retry attempt #1: HTTPError: Response code 404 (Not Found)
2024-02-20 10:19:52 error: Request https://api.twitter.com/graphql/...
```
