### ISSUE TITLE
Metacritic: new API root URL

### ISSUE THREAD

**Issue by moppman** [DIYgod/RSSHub#14474]
### Routes

```routes
/metacritic/tv/:sort?/:filter?
```

### Full routes

```fullroutes
/metacritic/tv/new/network=prime-video&genre=documentary
```

### Related documentation

https://docs.rsshub.app/routes/new-media#metacritic

### What is expected?

Obtain feed.

### What is actually happening?

```
Error message: Response code 404 (Not Found):
[snip]
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

It looks like Metacritic/Fandom changed their API root.

Old: `'https://fandom-prod.apigee.net'`
New: `'https://internal-prod.apigee.fandom.net'`

Relevant RSSHub code: https://github.com/DIYgod/RSSHub/blob/3c086f017df3999a22126ec5b537579a16a76f49/lib/v2/metacritic/index.js#L14

The new API root can be obtained by looking at browser network traffic.
Example URL: 
https://internal-prod.apigee.fandom.net/v1/xapi/games/metacritic/mario-vs-donkey-kong-2024/web?apiKey=1MOZgmNFxvmljaQR1X9KAij9Mo4xAY3u&componentName=product&componentDisplayName=Product&componentType=Product

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by nicotitopp** [comment]
Link is broken :c

other alternative?

https://internal-prod.apigee.fandom.net/v1/xapi/finder/metacritic/web?sortBy=-metaScore&productType=games&page=1&releaseYearMin=1958&releaseYearMax=2024&offset=0&limit=24&apiKey=1MOZgmNFxvmljaQR1X9KAij9Mo4xAY3u
