### ISSUE TITLE
Error message: This path is currently fetching, please come back later! at Bluestacks5

### ISSUE THREAD

**Issue by slord399** [DIYgod/RSSHub#14491]
### Routes

```routes
/bluestacks/release/5
```

### Full routes

```fullroutes
/bluestacks/release/5
```

### Related documentation

https://docs.rsshub.app/

### What is expected?

Could load Bluestacks5 Changelog.

### What is actually happening?

Error message: This path is currently fetching, please come back later!

seems not changed past few days since there is new release.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Looks like something went wrong

Route requested: /bluestacks/release/5

Error message: This path is currently fetching, please come back later!

Helpful Information to provide when opening issue:
Path: /bluestacks/release/5
Node version: v20.11.1
Git Hash: 8c077f9
        

If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/bluestacks/release/5
```

**Comment by TonyRL** [comment]
It works. Please note that the demo instances are heavily cached. If you desire a shorter cache duration, consider [deploying your own instance](https://docs.rsshub.app/install) of RSSHub.

**Comment by slord399** [comment]
yeah, true.
