### ISSUE TITLE
This path is currently fetching, please come back later!

### ISSUE THREAD

**Issue by spencer17x** [DIYgod/RSSHub#14549]
### Routes

```routes
/twitter/user/DIYgod
```

### Full routes

```fullroutes
/twitter/user/DIYgod
```

### Related documentation

https://docs.rsshub.app/zh/install#docker-compose-%E9%83%A8%E7%BD%B2

### What is expected?

Twitter can be accessed normally

### What is actually happening?

I deploy with docker-compose and then access the route, and I get an error when the proxy ip uses 127.0.0.1: 

![image](https://github.com/DIYgod/RSSHub/assets/32794413/a4dad317-58f2-4abf-b46f-3bb7af23cc2f)

If the proxy ip address is the container ip address: 
<img width="1060" alt="image" src="https://github.com/DIYgod/RSSHub/assets/32794413/5b84c48e-f8f7-4928-b218-a7c85b3b9be6">
<img width="860" alt="image" src="https://github.com/DIYgod/RSSHub/assets/32794413/49dc7aa1-8f84-421d-86be-67f522d6d5ca">

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Darwin 17a 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103 arm64

### Additional info

```shell
I deploy with docker-compose and then access the route, and I get an error when the proxy ip uses 127.0.0.1: 

![image](https://github.com/DIYgod/RSSHub/assets/32794413/a4dad317-58f2-4abf-b46f-3bb7af23cc2f)

If the proxy ip address is the container ip address: 
<img width="1060" alt="image" src="https://github.com/DIYgod/RSSHub/assets/32794413/5b84c48e-f8f7-4928-b218-a7c85b3b9be6">
<img width="860" alt="image" src="https://github.com/DIYgod/RSSHub/assets/32794413/49dc7aa1-8f84-421d-86be-67f522d6d5ca">
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please make sure your proxy is working properly. If you don't need to use proxy, you can remove related environment variables. Also, please give RSSHub a few seconds to fetch the data and do not refresh the page while fetching.

**Comment by spencer17x** [comment]
Then the ip of my proxy should be 127.0.0.1:7890 or the ip+7890 of the container
