### ISSUE TITLE
四月网  - 全球视野,中国情怀

### ISSUE THREAD

**Issue by kut2tjjj** [DIYgod/RSSHub#14553]
### 类型

传统媒体

### 网站地址

http://www.m4.cn/

### 网站描述

四月网前身是诞生于2008年4月的Anti-CNN网站，它是具有国际视野和文化自信的中国青年面对以CNN为代表的西方媒体的傲慢与偏见，捍卫事实真相和中国尊严的民间阵地。

### 需要生成什么内容？

首页
军事
要闻

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Closed in #14560
