### ISSUE TITLE
二十次幂来源抓取公众号，部分公众号404错误

### ISSUE THREAD

**Issue by CoCoThink** [DIYgod/RSSHub#14582]
### 路由地址

```routes
/wechat/ershicimi/:id
```

### 完整路由地址

```fullroutes
/wechat/ershicimi/PQDo1ojW
/wechat/ershicimi/YQXA8n3z
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#wei-xin-gong-zhong-hao-er-shi-ci-mi-lai-yuan

### 预期是什么？

返回公众号的rss。
呦呦鹿鸣公众号的二十次幂地址为：https://www.cimidata.com/account/detail?bid=PQDo1ojW
遇到同样错误的还有维舟 https://www.cimidata.com/account/detail?bid=YQXA8n3z

### 实际发生了什么？

Error message: Response code 404 (NOT FOUND): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /wechat/ershicimi/YQXA8n3z
Error message: Response code 404 (NOT FOUND): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /wechat/ershicimi/YQXA8n3z
Node version: v20.11.1
Git Hash: af87f6b
        
If you believe this is an error caused by RSSHub, please report on github
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 汇报
        
For online documentation and support please refer to docs.rsshub.app.

在线文档与支持，请访问 docs.rsshub.app。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
This route relies on `https://www.cimidata.com/a/:id`. Both `PQDo1ojW` and `YQXA8n3z` return a 404 error. Meanwhile, the example `813oxJOl` does not.
