### ISSUE TITLE
管理世界 学术活动的通知

### ISSUE THREAD

**Issue by fredericky123** [DIYgod/RSSHub#14590]
### 类型

科学期刊

### 网站地址

http://www.mwm.net.cn/web/xshd

### 网站描述

管理学顶级刊物

### 需要生成什么内容？

生成学术活动的通知

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #8384
