### ISSUE TITLE
v1 routes were depreciated for Fanbox

### ISSUE THREAD

**Issue by rakosi2** [DIYgod/RSSHub#14611]
### Routes

```routes
/fanbox/
```

### Full routes

```fullroutes
/fanbox/otomeoto
```

### Related documentation

https://docs.rsshub.app/zh/routes/social-media#pixivfanbox

### What is expected?

Fetch posts from artist

### What is actually happening?

shows:
Looks like something went wrong
Error message: wrong path

Tons of v1 routes were moved to [routes-deprecated](https://github.com/DIYgod/RSSHub/tree/master/lib/routes-deprecated) in [6f57c0](https://github.com/DIYgod/RSSHub/commit/6f57c02538bd2faefbe77566465c2c2c3f3caf3b)
Is there any way to continue using these routes?

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Debian, Docker version 25.0.3

### Additional info

```shell
Helpful Information to provide when opening issue:
Path: /fanbox/
Node version: v21.6.2
Git Hash: 9d980d7
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by rakosi2** [comment]
Yes GitHub Actions, that is exactly my issue, the route was moved to [routes-deprecated](https://github.com/DIYgod/RSSHub/tree/master/lib/routes-deprecated)

**Comment by rakosi2** [comment]
Any way to reopen this issue?

**Comment by rakosi2** [comment]
Do I need to make a new issue?

**Comment by rakosi2** [comment]
why did you just close it again?

**Comment by DIYgod** [comment]
The cost of supporting v1 is too high now, so if you need this route, please submit a PR to migrate it to the new route.
