### ISSUE TITLE
github files commits 路由工作异常

### ISSUE THREAD

**Issue by hour-keeper** [DIYgod/RSSHub#14623]
### 路由地址

```routes
/github/file/:user/:repo/:branch/:filepath+
```

### 完整路由地址

```fullroutes
/github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini
/github/file/DIYgod/RSSHub/master/docker-compose.yml
```

### 相关文档

https://docs.rsshub.app/zh/routes/programming#github-files-commits

### 预期是什么？

正常拉取指定文件的相关commits

### 实际发生了什么？

拉取了几乎所有的commits，或报错文件无法找到

### 部署

自建

### 部署相关信息

OS:Arch Linux, Docker: v25.0.3

### 额外信息

```shell
Route requested: /github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini

Error message: wrong path

Helpful Information to provide when opening issue:
Path: /github/file/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini
Node version: v21.6.2
Git Hash: 8171d92
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by yenfeng-shetiko** [comment]
官方实例上可以复现相同的报错

**Comment by ouuan** [comment]
经过测试，我确认这是由 #14295 引起的，hono 不支持该路由 `/file/:user/:repo/:branch/:filepath+` 中 `:filepath+` 的语法，如果将代码中的 `ctx.req.param('filepath')` 改为 `ctx.req.param('filepath+')` 则可以获取到正确的路径，只不过 `/` 必须写成 `%2F`。

**Comment by ouuan** [comment]
所有用了这个语法的应该都挂了。目前可以暂时回退到 2.28 前的版本。

**Comment by ouuan** [comment]
看起来需要将 `:filepath+` 改成 `:filepath{.+}`，不太确定 🤔
