### ISSUE TITLE
停电通知获取的是昨天停电日期的信息

### ISSUE THREAD

**Issue by zzzcpyy** [DIYgod/RSSHub#1463]
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by zzzcpyy** [comment]
以我所属的县市的这个定义地址为例，https://rsshub.app/tingdiantz/95598/3540810/35101，前两天刚开始用，推送的几次取得的都是昨天的信息

**Comment by DIYgod** [comment]
请确保按照模版提供信息
issue 将被关闭
