### ISSUE TITLE
打包Docker compose 本地安装，疑似路由不全

### ISSUE THREAD

**Issue by LeviTK** [DIYgod/RSSHub#14631]
### 路由地址

```routes
/qidian/chapter/:id
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
http://127.0.0.1:1200/qidian/chapter/1036761933  报错
https://rsshub.app/qidian/chapter/1036761933  OK
http://127.0.0.1:1200/bilibili/user/dynamic/2267573 OK
```

### 相关文档

https://docs.rsshub.app/routes/reading#qi-dian-zhang-jie

### 预期是什么？

本地搭建可以代替官方源，预计Docker包缺少路由，麻烦看下

### 实际发生了什么？

本地搭建的rsshub Docker，在部分RSS源下报错
<img width="1002" alt="image" src="https://github.com/DIYgod/RSSHub/assets/49050607/bc5cdfaa-e5bd-4a50-96b8-a4df6d4d2b67">
<img width="1121" alt="image" src="https://github.com/DIYgod/RSSHub/assets/49050607/ad15203e-a85d-4d4a-a74a-58955a23b18c">

### 部署

自建

### 部署相关信息

mac ，Docker version 24.0.5，node v21.6.2

### 额外信息

```shell
Looks like something went wrong
Route requested: /qidian/chapter/1036761933
Error message: Cannot read property 'vs' of undefined
Helpful Information to provide when opening issue: 
Path: /qidian/chapter/1036761933
Node version: v14.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Li-Jack** [comment]
路由无关，可能是Docker镜像问题，麻烦看下

**Comment by TonyRL** [comment]
Docker's base image had been updated from node 14 to ndde 16 in April 2022 https://github.com/DIYgod/RSSHub/commit/d8c00ec238cf9e21a6a9e3c5e82df9e6f47866e4
