### ISSUE TITLE
新榜-微信公众号 报错

### ISSUE THREAD

**Issue by bowencool** [DIYgod/RSSHub#14645]
### 路由地址

```routes
/newrank/wechat/:wxid
```

### 完整路由地址

```fullroutes
/newrank/wechat/coolapk_com
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#xin-bang-wei-xin-gong-zhong-hao

### 预期是什么？

正常返回内容

### 实际发生了什么？

Route requested: /newrank/wechat/coolapk_com

Error message: (intermediate value)(intermediate value)(intermediate value) is not iterable
Helpful Information to provide when opening issue:
Path: /newrank/wechat/coolapk_com
Node version: v21.6.2
Git Hash: cd6f2d9

### 部署

自建

### 部署相关信息

diygod/rsshub:chromium-bundled

### 额外信息

```shell
Route requested: /newrank/wechat/coolapk_com

Error message: (intermediate value)(intermediate value)(intermediate value) is not iterable
Helpful Information to provide when opening issue:
Path: /newrank/wechat/coolapk_com
Node version: v21.6.2
Git Hash: cd6f2d9
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SirM2z** [comment]
已提交 PR 修复：/pull/15702
