### ISSUE TITLE
route接收limit参数

### ISSUE THREAD

**Issue by machsix** [DIYgod/RSSHub#1470]
### 这是一个什么样的功能？

由`router`直接接收`?limit`参数

### 这个功能可以解决什么问题？

由`router`直接接收`?limit`参数， 降低服务器负载

### 额外描述

现有limit只是直接对items slice https://github.com/DIYgod/RSSHub/blob/5098b4bf38f60371d67364ee5bce6033a5cac76f/lib/routes/xgyw/hot.js##L47 

如果route本身抓取了上百个, 如这个https://github.com/DIYgod/RSSHub/tree/master/lib/routes/manhuagui 那么加不加limit并不会减轻服务器负载

比如我这个router
https://github.com/DIYgod/RSSHub/blob/5098b4bf38f60371d67364ee5bce6033a5cac76f/lib/routes/xgyw/hot.js##L4 就必须得用一个单独参数

我尝试了直接在`route`文件内使用`ctx.query.limit`，但发现如果我第一次请求是`?limit=30`， 第二次请求`?limit=50`的时候返回的rss文件内容是30条， 没大明白是什么原因造成的。。我用了redis

**Comment by HenryQW** [comment]
路由本身不应该抓取这么多个条目

**Comment by DIYgod** [comment]
路由有全局缓存，且缓存忽略 query 参数，所以会出现第二次返回了第一次的内容

limit 在中间件里做了统一处理，鉴于上述限制，不应该在路由里处理

RSS 自做获取更新用，路由本身不应该抓取过多条目
