### ISSUE TITLE
推特<description>内的推文内容显示不完整

### ISSUE THREAD

**Issue by mikuchu** [DIYgod/RSSHub#14704]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
http://localhost:1200/twitter/user/HaKoniwalily.json?filter_time=86000
```

### 相关文档

https://docs.rsshub.app/routes/social-media

### 预期是什么？

content_html 是完整的推特内容

### 实际发生了什么？

访问的时候content_html 里的内容有部分被省略成...了。并没有显示完整的推文
rss内容为：
![屏幕截图 2024-03-07 151317](https://github.com/DIYgod/RSSHub/assets/69282405/75d12029-99dc-4855-8981-a8b2a97e5589)
使用nitter的rss查看则是：

![屏幕截图 2024-03-07 151522](https://github.com/DIYgod/RSSHub/assets/69282405/a59386cc-3ba8-4d27-a15e-bccf38f49786)

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
无报错，无日志
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #12360
