### ISSUE TITLE
知乎用户关注时间线返回错误

### ISSUE THREAD

**Issue by REZ2O** [DIYgod/RSSHub#14719]
### 路由地址

```routes
/zhihu/timeline
```

### 完整路由地址

```fullroutes
/zhihu/timeline?key=mykey
```

### 相关文档

https://docs.rsshub.app/zh/install/config#%E7%9F%A5%E4%B9%8E%E7%94%A8%E6%88%B7

### 预期是什么？

正常返回关注列表

### 实际发生了什么？

Helpful Information

Error Message:

Cannot read properties of undefined (reading 'link')
Route: /zhihu/timeline

Full Route: /zhihu/timeline

Git Hash: unknown

Git Date:

### 部署

自建

### 部署相关信息

OS:Ubuntu 22.04;Node: v21.7.0;Podman:3.4.4

### 额外信息

```shell
Cookie问题？
已经按照文档将 GET /moments 中请求头包含的cookie值全部设置到环境变量中了啊
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #9485
