### ISSUE TITLE
有没有大神能做一个类似nitter-status的接口服务，能查看和获取公共实例的运行状态，实现流量均衡

### ISSUE THREAD

**Issue by mycfctech** [DIYgod/RSSHub#14712]
### 这是一个什么样的功能？

如题

### 这个功能可以解决什么问题？

流量均衡

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
Closed in https://github.com/DIYgod/RSSHub/commit/82cf5c745397ef10053709b47b621f0c11bab3ea
