### ISSUE TITLE
Cannot generate rss from http://home.xxx.xx:1200/mail/imap/xxx_gmail_com/inbox

### ISSUE THREAD

**Issue by FredNov** [DIYgod/RSSHub#14711]
### Routes

```routes
/mail/imap/:email/:folder{.+}?
```

### Full routes

```fullroutes
/mail/imap/xxx_gmail_com/inbox
```

### Related documentation

https://docs.rsshub.app/zh/routes/other#email-email-list

### What is expected?

Get rss from email

### What is actually happening?

get "Looks like something went wrong Helpful Information" page. No error presented there.

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

linux x86_64 Ubuntu 22.04.3 LTS, docker ver 24.0.7 (API: 1.43)

### Additional info

```shell
info: <-- GET /mail/imap/xxx_gmail_com/inbox

error: undefined

error: Error in /mail/imap/xxx_gmail_com/inbox: 

info: --> GET /mail/imap/xxx_gmail_com/inbox 503 233ms
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
It works on gmail. Make sure you use [app password](https://support.google.com/accounts/answer/185833) if you have 2FA enabled.

<details><summary>Screenshot</summary>

![Screenshot](https://github.com/DIYgod/RSSHub/assets/11386903/9e6fa362-34a9-4438-a9d3-dea5a52d71b3)
</details>
