### ISSUE TITLE
追新番失效

### ISSUE THREAD

**Issue by Jack-XHP** [DIYgod/RSSHub#14724]
### 路由地址

```routes
/fanxinzhui
```

### 完整路由地址

```fullroutes
/fanxinzhui
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#zhui-xin-fan-zui-jin-geng-xin

### 预期是什么？

显示最近更新列表

### 实际发生了什么？

Helpful Information

Error Message:

wrong path
Route: /fanxinzhui

Full Route: /fanxinzhui

Node Version: v21.7.0

Git Hash: unknown

Git Date:

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自从2024/02/28 之后追新番RSShub就失效了
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by cubroe** [comment]
Seemingly all those moved to `lib/routes-deprecated/` have stopped functioning.
