### ISSUE TITLE
微博部分图片链接没有被替换

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#14738]
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/6827625527
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E5%8D%9A%E4%B8%BB-1

### 预期是什么？

原数据

```
流浪猫<span class="url-icon"><img alt=[喵喵] src="https://h5.sinaimg.cn/m/emoticon/icon/others/d_miao-c1b3d563bd.png" style="width:1em; height:1em;" /></span> vs [吃瓜瓜]共济会，未曾料想的道路  <a  href="https://wx3.sinaimg.cn/large/007s41inly1hnkve3ggaej30690693z0.jpg" data-hide=""><span class='url-icon'><img style='width: 1rem;height: 1rem' src='https://h5.sinaimg.cn/upload/2015/01/21/20/timeline_card_small_photo_default.png'></span><span class="surl-text">查看图片</span></a> //<a href='/n/开水族馆的生物男'>@开水族馆的生物男</a>:<span class="url-icon"><img alt=[费解] src="https://h5.sinaimg.cn/m/emoticon/icon/default/d_feijie-c1df37ef03.png" style="width:1em; height:1em;" /></span>
```

其中`<a  href="https://wx3.sinaimg.cn/large/007s41inly1hnkve3ggaej30690693z0.jpg" data-hide="">`，应被添加`data-rsshub-image="href"`，用于被hotlink替换，参考https://github.com/DIYgod/RSSHub/pull/14354

### 实际发生了什么？

没有被替换

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by 9k001** [comment]
docker-compose 中 hub的环境变量中加入
```
- HOTLINK_TEMPLATE=https://i3.wp.com/$${host}$${pathname}
- HOTLINK_INCLUDE_PATHS='/weibo'
```

**Comment by ttttmr** [comment]
> docker-compose 中 hub的环境变量中加入
> 
> ```
> - HOTLINK_TEMPLATE=https://i3.wp.com/$${host}$${pathname}
> - HOTLINK_INCLUDE_PATHS='/weibo'
> ```

我设置了的，这个issue是因为微博匹配图片链接的正则过于宽泛，我在pr中修复了
