### ISSUE TITLE
请求支援【虎扑-步行街】的RSS

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#1474]
### 源站地址
https://bbs.hupu.com/bxj

### 需要生成什么内容？
就是将步行街的“主题”下的帖子生成rss，方便阅读器订阅。如果可能的话，将发帖人的帖子正文也抓出来一并生成。

### 额外描述
虎扑官方目前只提供一些新闻类的RSS，人气最旺的步行街的似乎没提供，所以请求支援一下。

**Comment by ruleroller** [comment]
@LogicJake  @DIYgod 感谢支持了步行街的rss。最近几天用下来，用的2“最新发帖”，似乎是因为步行街的发帖频率太高，而每次抓取的帖子少，往往一个缓存期时间过去，好多新帖子就因此没抓到。我自己搭建的设置到2分的缓存都无法抓全，可否考虑增加一次性抓取的条目数量。个人建议，30-50条左右为宜。（感觉发这里才能被看到？刚才发在pulls那里了，这里也贴一回吧，希望不要对大家产生困扰）

**Comment by ruleroller** [comment]
@LogicJake @DIYgod 我在本地将bxj.js里27行的10，改成30，运行成功，似乎满足了我个人的使用要求了。

**Comment by LogicJake** [comment]
> @LogicJake @DIYgod 我在本地将bxj.js里27行的10，改成30，运行成功，似乎满足了我个人的使用要求了。

本地改最好了，或者你也可以pr一下
