### ISSUE TITLE
获取不到「微博 - 博主」内容

### ISSUE THREAD

**Issue by LinxHex** [DIYgod/RSSHub#14741]
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/1959430477/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E5%8D%9A%E4%B8%BB-1

### 预期是什么？

正常获取内容。

### 实际发生了什么？

![image](https://github.com/DIYgod/RSSHub/assets/92703641/962871ac-eafd-4d68-97a5-3d522de0862c)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自建也是相同的情况。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by LeonXLee** [comment]
@KawausoJyou 
我也与你遇到了同样的问题，同样官方和自建都不能使用。
目前公共用例里，下面还可以临时替代下
https://rsshub.liumingye.cn/

**Comment by Rongronggg9** [comment]
应该并非路由本身问题，可能是 #14718 的迁移引起
