### ISSUE TITLE
Migration to next generation route registration method broke many routes

### ISSUE THREAD

**Issue by Rongronggg9** [DIYgod/RSSHub#14745]
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
NOROUTE
```

### Related documentation

N/A

### What is expected?

The migration shouldn't break these routes.
I filled `NOROUTE` above in order not to disturb route maintainers since I consider this is not their fault.

### What is actually happening?

Many routes, which have used `ctx.set('data', ...` for some time due to the previous migration to route v3 (#14295), now return empty feeds after #14718.

E.g.,
#14741
```
/iqiyi/user/video/2289191062
/phoronix/linux/KDE
```

If I am right, all `ctx.set('data', ...` should have been replaced with `return`. I've seen some were replaced[1] while some were not. If this is the case, I am willing to open a PR to fix this when I have more spare time (today or tomorrow?).
Or, @DIYgod, should `ctx.set('data', ...` also be a valid method to return feed data in your initial ideas in #14685 (but it was just forgotten to be implemented)?

[1]: It seems to be a batch replacement as it actually caused some code blocks to be unreachable... (e.g., https://github.com/DIYgod/RSSHub/blob/33e2f170558ae0f0b41dbabac5a417ad96d50ae6/lib/routes/qbittorrent/news.ts#L72-L82)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
I filled N/A here as it will be wrapped by a terrible code block, making any other markdown formatting unapplied. :-(
Words that should have been filled here are in the "What is actually happening?" section.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by DIYgod** [comment]
My expectation is that they should all be returned, but some were missed during the migration process. I would be very grateful if you are willing to fix them!
