### ISSUE TITLE
新版本 RSShub （c287d4e2fce8）无法获取 miniflux 路由

### ISSUE THREAD

**Issue by AntoineChn** [DIYgod/RSSHub#14749]
### 路由地址

```routes
/miniflux/all
```

### 完整路由地址

```fullroutes
/miniflux/all/starred=true
```

### 相关文档

https://docs.rsshub.app/zh/install/config#miniflux

### 预期是什么？

- 获取 miniflux 的订阅列表
- 获取 miniflux 的内容

### 实际发生了什么？

- 订阅 miniflux 的路由失效 (`/miniflux/all/starred=true`)
- 订阅 miniflux 的文档消失（在 https://docs.rsshub.app/ 中，找不到 miniflux 完整配置和使用文档了）

我部署了两个 rsshub 容器，分别是 
- 容器1：`diygod/rsshub:2024-02-27` （[597b24339ede](https://hub.docker.com/layers/diygod/rsshub/chromium-bundled-2024-02-27/images/sha256-597b24339edeb4ad36785a26d2a30d51990ad75b4eb89cb14d101550fe48e508?context=explore)）
- 容器2：`diygod/rsshub:latest` （即， `diygod/rsshub:2024-03-09` [c287d4e2fce8](https://hub.docker.com/layers/diygod/rsshub/latest/images/sha256-c287d4e2fce86fa36b2ebeb8b34c5fe7a4e106a072b8e54ae0413601081de525?context=explore)）

我发现

- 容器1 可以正确地返回 `/miniflux/all/starred=true` 的内容
- 容器2 则报错

### 部署

自建

### 部署相关信息

OS: Linux, Node: v21.7.0, Docker: v25.0.4

### 额外信息

```shell
Helpful Information

Error Message:

wrong path
Route: /miniflux/all/starred=true

Full Route: /miniflux/all/starred=true

Node Version: v21.7.0

Git Hash: unknown

Git Date:
```
```


### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Orokapei** [comment]
+1 找不到这个路由了

**Comment by Orokapei** [comment]
找了下 已经废弃了🥹 lib/routes-deprecated/miniflux

**Comment by AntoineChn** [comment]
> 找了下 已经废弃了🥹 lib/routes-deprecated/miniflux

由此，我有以下三个问题，我在文档中没有找到答案，特此求助：

## 问题1：未来开发者还可能支持 miniflux 么？

`routes-deprecated` 的意思是未来也不会再支持 miniflux 的意思是么？

## 问题2：miniflux 的替代品中，新版 RSShub 已经或将支持那哪些？

得益于旧版本的 RSShub 可以接入 miniflux，我利用 `/miniflux/all/starred=true`，将所有 miniflux 中加星（即，收藏）的内容，导入本地参考文献库。这是我想实现的功能。

是否有其他的（类似 miniflux）的订阅器，新版 RSShub 可以接入它们，以实现类似的功能么？比如 TinyTinyRSS ？FreshRSS？

## 问题3：我的一个迂回解决方案

我的计划是，
- 部署新旧两个 RSShub 容器。
- 如果某路由在旧版失效，那么则迁移到新版 RSShub 上面。
- 只要 miniflux 的开发者不大改接口，那么，旧版 RSShub 就应该能一直接入 miniflux。

大家觉得这种方案可行么？有什么可以优化的地方？

**Comment by Zebartin** [comment]
关于问题2，FreshRSS可以把指定条件的查询（比如已star）生成另外一个rss源，直接订阅就行。
[文档](https://freshrss.github.io/FreshRSS/en/users/user_queries.html)有点过时，但大概是这个意思

**Comment by AntoineChn** [comment]
> 关于问题2，FreshRSS可以把指定条件的查询（比如已star）生成另外一个rss源，直接订阅就行。 [文档](https://freshrss.github.io/FreshRSS/en/users/user_queries.html)

感谢。

我按照文档操作，但是 query 页面没有共享链接

## 我的配置

按照 FreshRSS 的文档

> A prerequisite is that the FreshRSS API(s) must be enabled in FreshRSS authentication settings.

我确认 FreshRSS API 已经被勾选（即， enabled）

## 遇到的问题

然而，创建了一个 query 后，我的 query 配置界面如下，（找不到共享链接）

<img width="723" alt="Screenshot 2024-03-11 at 17 09 21" src="https://github.com/DIYgod/RSSHub/assets/17791254/68424f0f-90ee-4c08-b853-1c8fa5e6a723">

## 期待的结果

我在网上搜索相关信息，我看到，这个配置界面本应包含 `Share this query by link` 字样。

![](https://private-user-images.githubusercontent.com/1008324/298420672-5da2a42c-d767-4a9e-bb99-a9df051a2281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzM3NTYsIm5iZiI6MTcxMDE3MzQ1NiwicGF0aCI6Ii8xMDA4MzI0LzI5ODQyMDY3Mi01ZGEyYTQyYy1kNzY3LTRhOWUtYmI5OS1hOWRmMDUxYTIyODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMTYxMDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUxNGQ5ZGMxMjM5YWFkODEyMjc4NDY1NDU3NTI5ODA5NGQxZDUzZTBiNTg4Y2UwMzJkYTBlMGE3ZDAzMTc4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qzhd-aylbkQ-icZeUQY9qm8Xu5d0RdC36k41hJZ-xd4)

## 未来尝试

- 尝试1: 我准备新部署一个 FreshRSS （用 FreshRSS/FreshRSS 或 linuxserver/freshrss 镜像）。从默认设置入手，我来研究研究则么开启 query 的 分享链接。
- 尝试2: 去 FreshRSS 的 issue 里面查一查其他人是否遇到过相同的问题。

**Comment by Zebartin** [comment]
> 这个功能会在 freshrss 1.24.0 发布，然而现在的稳定版是 1.23.1。

是的，目前稳定版可以用master token来分享，在文档最后一段deprecated部分，没有安全顾虑的话可以用这个

**Comment by DIYgod** [comment]
Fixed 0dc0f0a3e50351625eb258ccf5c4f327f73d2992
