### ISSUE TITLE
升级后，vercel部署报错：No Output Directory named "public" found after the Build completed

### ISSUE THREAD

**Issue by shenpvip** [DIYgod/RSSHub#14761]
### 路由地址

```routes
/someroute
```

### 完整路由地址

```fullroutes
/routes
```

### 相关文档

https://docs.rsshub.app/zh/install#%E4%B8%80%E9%94%AE%E9%83%A8%E7%BD%B2%E6%97%A0%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0-1

### 预期是什么？

Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

### 实际发生了什么？

升级后，vercel部署报错：No Output Directory named "public" found after the Build completed
![image](https://github.com/DIYgod/RSSHub/assets/10239097/fc198052-2e5f-4418-81d9-9e8a09b46f35)

### 部署

自建

### 额外信息

```shell
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #14622
