### ISSUE TITLE
使用 Dependabot 自动更新依赖

### ISSUE THREAD

**Issue by u3u** [DIYgod/RSSHub#148]
![0](https://marketplace-screenshots.githubusercontent.com/211/6a0dd0b2-a85f-11e7-9c4e-a5317838c3d7?auto=webp&format=jpeg&width=670&dpr=2)
![1](https://marketplace-screenshots.githubusercontent.com/211/8940f27a-a85f-11e7-9e45-aea6ddce9319?auto=webp&format=jpeg&width=670&dpr=2)
![2](https://marketplace-screenshots.githubusercontent.com/211/8e1ede38-a85f-11e7-85c7-28f3e585e1d2?auto=webp&format=jpeg&width=670&dpr=2)

Marketplace: https://github.com/marketplace/dependabot

**Comment by DIYgod** [comment]
Done.
