### ISSUE TITLE
xiaohongshu bug

### ISSUE THREAD

**Issue by nanjade** [DIYgod/RSSHub#14812]
### Routes

```routes
Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Node version: v20.11.1
Git Hash: unknown
```

### Full routes

```fullroutes
Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Node version: v20.11.1
Git Hash: unknown
```

### Related documentation

Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or  2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. Helpful Information to provide when opening issue: Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes Node version: v20.11.1 Git Hash: unknown

### What is expected?

Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Node version: v20.11.1
Git Hash: unknown

### What is actually happening?

Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Node version: v20.11.1
Git Hash: unknown

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

railway

### Additional info

```shell
Route requested: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Error message: Could not find Chrome (ver. 122.0.6261.69). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
Helpful Information to provide when opening issue:
Path: /xiaohongshu/user/5996b0e482ec390b658fbfb2/notes
Node version: v20.11.1
Git Hash: unknown
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
The error message has already mentioned that you are trying to subscribe to a route that requires puppeteer, but you are using a Docker image without puppeteer or haven't provided a puppeteer WebSocket endpoint.
