### ISSUE TITLE
Default pixiv image proxy https://i.pixiv.re not working

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#14813]
### Routes

```routes
/pixiv/user/illustfollows
```

### Full routes

```fullroutes
https://rsshub.app/pixiv/user/illustfollows
```

### Related documentation

https://docs.rsshub.app/install/config#pixiv

### What is expected?

image

### What is actually happening?

i.pixiv.re Host Error

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
i.pixiv.re Host Error
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
You can change the `PIXIV_IMG_PROXY` environment variable to any option available from https://pixiv.re/.
