### ISSUE TITLE
【中证网】一个参数的可以正常工作 后跟两个参数的全部反馈 wrong path

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#14835]
### 路由地址

```routes
/cs/:category?
```

### 完整路由地址

```fullroutes
https://rsshub.app/cs/cj2020
```

### 相关文档

https://docs.rsshub.app/routes/finance#%E6%A0%8F%E7%9B%AE-3

### 预期是什么？

正常工作

### 实际发生了什么？

cs后跟两个参数的全部反馈wrong path

https://rsshub.app/cs/xwzx/hg

一个参数的可以正常工作

https://rsshub.app/cs/cj2020 

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Helpful Information

Error Message:

wrong path
Route: /cs/xwzx/hg

Full Route: /cs/xwzx/hg

Node Version: v21.7.1

Git Hash: 2d4abeb9
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by JimenezLi** [comment]
`xwzx/hg` 把 `/` 当成了路径的一部分。

把 `/` 换成 `%2F`，用 `/cs/xwzx%2Fhg` 可以订阅。
