### ISSUE TITLE
BBC feed is not displaying videos correctly

### ISSUE THREAD

**Issue by lajiburner** [DIYgod/RSSHub#14855]
### Routes

```routes
/bbc/:site?/:channel?
```

### Full routes

```fullroutes
/bbc/world
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#bbc

### What is expected?

Get full text including all information. 

### What is actually happening?

For some stories like these:
https://www.bbc.com/news/av/world-europe-68596923
https://www.bbc.com/news/world-us-canada-68583149

There are 2 problems:
1. Videos are not displayed, instead, a "This video can not be played To play this video you need to enable JavaScript in your browser." warning is shown. Maybe they have anti crawl function, but BBC does allow the use of iframe to link videos. 
2. For https://www.bbc.com/news/av/world-europe-68596923, some captions are missing. 

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
N/A
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by lajiburner** [comment]
@HenryQW @DIYgod My apologies for manually pinging you guys. It seems that the github action workflow has failed "call maintainer" job.

**Comment by HenryQW** [comment]
We never supported videos on BBC as they require a JS library to load the video. The captions are also very tricky, we don't have the capacity to cover them 100%.
