### ISSUE TITLE
求个调试指导

### ISSUE THREAD

**Issue by ackerx** [DIYgod/RSSHub#14872]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app

### 预期是什么？

预期是能够正常使用。

### 实际发生了什么？

之前版本时我也写过，那时可以正常使用。本次大更新后，代码写好，在本地npm run dev下测试通过，可是docker部署到服务器后测试报错。页面提示wrong path，docker日志里就wrong path一句。另外，服务器上其他的route是能正常使用的。

请教，这种情况要怎么调试呢？在哪儿能看错误时的栈信息？查了配置说明，比如设置debug_level，设到debug后，正常的使用会多显示一些信息，但遇到的wrong path问题仍就是一句错误提示。

还请指教一二。

另，node版本都相同。

### 部署

自建

### 额外信息

```shell
Looks like something went wrong
Helpful Information
Error Message:
wrong path
Route: /my/test2
Full Route: /my/test2
Node Version: v21.7.1
Git Hash: e0beaad6
Git Date: Wed, 20 Mar 2024 01:08:16 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ackerx** [comment]
本地测试执行了build，能让新路由生效，docker里直接bind目录过去并不能让routes生效。变通方法是用存在的路由即可。

**Comment by machsix** [comment]
提供一个Vs code的debug设置， 不知道要不要include 在document里 @DIYgod 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "tsx",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/lib/index.ts",
            "args": [
                "--no-cache"
            ],
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/tsx",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "skipFiles": [
                "<node_internals>/**",
                "${workspaceFolder}/node_modules/**",
            ],
        }
    ]
}
```
