### ISSUE TITLE
"Transformation - JSON" wrong path

### ISSUE THREAD

**Issue by Orokapei** [DIYgod/RSSHub#14894]
### 路由地址

```routes
/rsshub/transform/json/:url/:routeParams
```

### 完整路由地址

```fullroutes
/rsshub/transform/json/https%3A%2F%2Fapi.github.com%2Frepos%2Fginuerzh%2Fgost%2Freleases/title=title%3DGost%20releases%26itemTitle%3Dtag_name%26itemLink%3Dhtml_url%26itemDesc%3Dbody
/rsshub/transform/json/https%3A%2F%2Fsearch.zongheng.com%2Fsearch%2Fbook%3Fkeyword%3D123/title%3D123%26item%3Dlist%26itemTitle%3Dname%26itemLink%3DbookId%26itemDesc%3Ddescription%26itemPubDate%3DupdateTime
```

### 相关文档

https://docs.rsshub.app/zh/routes/other#transformation-json

### 预期是什么？

生成rss

### 实际发生了什么？

Error Message:
`wrong path`

Route: `/rsshub/transform/json/https:/api.github.com/repos/ginuerzh/gost/releases/title=title=Gost%20releases&itemTitle=tag_name&itemLink=html_url&itemDesc=body`

Full Route: `/rsshub/transform/json/https:/api.github.com/repos/ginuerzh/gost/releases/title=title=Gost%20releases&itemTitle=tag_name&itemLink=html_url&itemDesc=body`

### 部署

自建

### 部署相关信息

Docker Version: v26.0.0-rc2 Node Version: v21.7.1  Git Hash: 8a04b529  Git Date: Wed, 20 Mar 2024 17:04:17 GMT

### 额外信息

```shell
docker env 已设置`ALLOW_USER_SUPPLY_UNSAFE_DOMAIN=true`
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/rsshub/transform/json/https%3A%2F%2Fapi.github.com%2Frepos%2Fginuerzh%2Fgost%2Freleases/title=title%3DGost%20releases%26itemTitle%3Dtag_name%26itemLink%3Dhtml_url%26itemDesc%3Dbody
```

**Comment by TonyRL** [comment]
/test
```routes
/rsshub/transform/json/https%3A%2F%2Fapi.github.com%2Frepos%2Fginuerzh%2Fgost%2Freleases/title=title%3DGost%20releases%26itemTitle%3Dtag_name%26itemLink%3Dhtml_url%26itemDesc%3Dbody
```

**Comment by TonyRL** [comment]
It works.

**Comment by Orokapei** [comment]
找到问题了 = = nginx反代的时候自动decode了
