### ISSUE TITLE
煎蛋所有图片无法访问

### ISSUE THREAD

**Issue by qiaomo** [DIYgod/RSSHub#14903]
### 路由地址

```routes
/jandan
```

### 完整路由地址

```fullroutes
https://rsshub.app/jandan/top
```

### 相关文档

https://docs.rsshub.app/routes/other#%E7%85%8E%E8%9B%8B

### 预期是什么？

保留原始图片域名：moyu.im

### 实际发生了什么？

https://github.com/DIYgod/RSSHub/pull/14874

这个 pr 里将 moyu.im 替换成了 sinaimg.cn 导致所有图片无法正常访问。

替换成 sinaimg.cn 没有解决这个 [issue](https://github.com/DIYgod/RSSHub/issues/11528)，爬取源的图片链接就是 moyu.im，我认为没有必要替换。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
图片无法访问
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
@bxb100

**Comment by bxb100** [comment]
1. #14874 doesn't fix issue #11528
2. `moyu.im` using referral check policy, and according to what I know, there none local RSS Reader specific set `Referer` header
3. `sinaimg.cn` not strict `Referer` header, but yes, in some Local Reader, they used WebView not using custom UA cause broke loading, but it's the reader problem
4. `moyu.im` is Sein's domain, frankly, I don't think he will be happy you guys use this for RSS
5. above all, I think there is no real way to fix this question yet `sinaimg.cn` is better than `moyu.im`

**Comment by qiaomo** [comment]
Hi @bxb100, Thanks for your reply.

When using `moyu.im`, I manually set the `Referer` header in the global proxy tool so that the image can be displayed properly.

Now after replacing it with `sinaimg.cn`, is it possible to get the image to display properly in a similar way?

I am using `inoreader` and now the image is not displaying correctly (403 Forbidden), I tested it and the image is not opening in browsers (Chrome, Firefox, Safari), do you know how to solve this problem?

Here are some test links:

https://wx1.sinaimg.cn/large/6d050af1ly1hnzj26hkxaj20u00lpmzj.jpg
https://wx3.sinaimg.cn/large/6d050af1ly1hnzgh80sa2j20u00pbgnt.jpg

![图片](https://github.com/DIYgod/RSSHub/assets/14953431/2cde22f7-23f9-4152-9218-3b4cc87dd950)

**Comment by TonyRL** [comment]
FYI, `sinaimg.cn` does referer check. #11096

**Comment by qiaomo** [comment]
@TonyRL OK, Thanks

**Comment by bxb100** [comment]
> I am using inoreader and now the image is not displaying correctly (403 Forbidden), I tested it and the image is not opening in browsers (Chrome, Firefox, Safari), do you know how to solve this problem?

don't forget to rewrite/remove `User-Agent`


```diff
curl --location 'https://wx1.sinaimg.cn/large/6d050af1ly1hnxu3u4vkwj20p01jy16u.jpg' \
- --header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
+ --header 'User-Agent: anything'
```

**Comment by qiaomo** [comment]
@bxb100 Okay, I'll try.
