### ISSUE TITLE
请对TWITTER_COOKIE的配置方式提供说明

### ISSUE THREAD

**Issue by karegyudon** [DIYgod/RSSHub#14910]
### 这是一个什么样的功能？

https://docs.rsshub.app/routes/social-media#twitter 此处的文档提到：
Currently supports two authentication methods:

Using TWITTER_COOKIE (recommended): Configure the cookies of logged-in Twitter Web, at least including the fields auth_token and ct0. RSSHub will use this information to directly access Twitter's web API to obtain data.

但是找不到任何如何设置该变量的说明或者提示，能否给出个具体点的操作方式或者配置案例？

如使用username和password的方式，每隔几个小时就会收到twitter的提示邮件，有客户端进行了登陆，根据文档的提示，长期如此的情况下可能触发风控机制限制账户。

### 这个功能可以解决什么问题？

可以方便在自行部署上配置推荐的方式以访问twitter。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by assassinliujie** [comment]
在docker-compose.yml environment下面，TWITTER_COOKIE: 'auth_token=yourtoken; ct0=yourkey'
