### ISSUE TITLE
新闻站 axios RSS 源需求

### ISSUE THREAD

**Issue by Wei-Xia** [DIYgod/RSSHub#1491]
### 源站地址
https://www.axios.com/

### 需要生成什么内容？

- [ ] 新闻全文输出

### 额外描述
经搜索发现，axios 这个新闻网站（非 HTTP client  😆）没有 rss 的功能，希望可以增加这个输出源。

**Comment by DIYgod** [comment]
有的 https://api.axios.com/feed/top/

**Comment by Wei-Xia** [comment]
@DIYgod 的确有。。。我搜了半天没搜出来，这个网站的 SEO 和那个 http client 的 SEO 重复率太高。。哈哈
