### ISSUE TITLE
Github User stars error

### ISSUE THREAD

**Issue by sherlcok314159** [DIYgod/RSSHub#14928]
### Routes

```routes
/github/starred_repos/:user
```

### Full routes

```fullroutes
/github/starred_repos/DIYgod
```

### Related documentation

https://docs.rsshub.app/routes/programming#user-starred-repositories

### What is expected?

The preview should be fine.

### What is actually happening?

<img width="1119" alt="image" src="https://github.com/DIYgod/RSSHub/assets/76043326/a7678883-3317-4986-82af-6c5c1dbb2f81">

And I failed to add it to FreshRSS.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Currently no
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/github/starred_repos/DIYgod
```
