### ISSUE TITLE
Bilibili UP主动态路由自建后仍因反爬失效

### ISSUE THREAD

**Issue by sliots** [DIYgod/RSSHub#14933]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/40366538
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

正常返回

### 实际发生了什么？

Unexpected option: transformResponse: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

### 部署

自建

### 部署相关信息

OS: Linux, Node: v21.7.1

### 额外信息

尝试了腾讯云VPS、自家的NAS部署都不能订阅

```shell
Unexpected option: transformResponse: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Route: /bilibili/user/dynamic/:uid/:routeParams?

Full Route: /bilibili/user/dynamic/40366538

Node Version: v21.7.1

Git Hash: 76bc7216

Git Date: Sat, 23 Mar 2024 04:42:17 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by sliots** [comment]
image: diygod/rsshub:2024-03-21 正常
image: diygod/rsshub:2024-03-22 异常
image: diygod/rsshub:2024-03-23 异常
image: diygod/rsshub:2024-03-24 正常

尝试重新部署了这几天的镜像
目前看最新的镜像问题似乎是已经解决了

**Comment by sliots** [comment]
> @sliots 可以麻烦尝试下31009079和5017882这两位UP主吗？ 更新镜像后其他已经可以了，但是这两个从上次失效前就一直不行，直接提示「HTTP ERROR 500」。 💕

我复现也有同样的问题，不过似乎和这个issue无关了，可以单独开一个问下

**Comment by lblbk** [comment]
> > @sliots 可以麻烦尝试下31009079和5017882这两位UP主吗？ 更新镜像后其他已经可以了，但是这两个从上次失效前就一直不行，直接提示「HTTP ERROR 500」。 💕
> 
> 我复现也有同样的问题，不过似乎和这个issue无关了，可以单独开一个问下

老哥 可以问一下 你是怎么自建的吗，我群晖docker跑的，现在只能进首页，其他任何路由都报错

**Comment by sliots** [comment]
> > > @sliots 可以麻烦尝试下31009079和5017882这两位UP主吗？ 更新镜像后其他已经可以了，但是这两个从上次失效前就一直不行，直接提示「HTTP ERROR 500」。 💕
> > 
> > 
> > 我复现也有同样的问题，不过似乎和这个issue无关了，可以单独开一个问下
> 
> 老哥 可以问一下 你是怎么自建的吗，我群晖docker跑的，现在只能进首页，其他任何路由都报错

Docker 部署，获取正常 ，你可以尝试用docker compose

Git Hash:[bed0ab87](https://github.com/DIYgod/RSSHub/commit/bed0ab87)
Git Date:Fri, 12 Apr 2024 11:47:59 GMT
