### ISSUE TITLE
提交新路由后的测试无法通过

### ISSUE THREAD

**Issue by cnkmmk** [DIYgod/RSSHub#14938]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/guide/

### 预期是什么？

通过PR自动测试

### 实际发生了什么？

测试失败

* Test / Build radar and maintainer on Node 21 (pull_request)
* Test / Build radar and maintainer on Node 20 (pull_request) 

两项无法通过测试

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
PR：#14925

在提交路由文件中，

categories: ['Programming'],
```
而更改为
```
categories: ['Blog'],
```
则正常通过测试
```


### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
None of them are correct. `categories` should start with [lower case](https://github.com/DIYgod/RSSHub/blob/master/scripts/workflow/data.ts).
