### ISSUE TITLE
B站获取UP主动态，多次失效

### ISSUE THREAD

**Issue by CMander02** [DIYgod/RSSHub#14935]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/dynamic/1320140761
https://rsshub.app/bilibili/user/dynamic/18706318
https://rsshub.app/bilibili/user/dynamic/414878461
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

正常返回

### 实际发生了什么？

Error: Error: Feed not recognized as RSS 1 or 2.
Loading...

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #14933
