### ISSUE TITLE
中国政策数据库rss请求

### ISSUE THREAD

**Issue by kaesahao** [DIYgod/RSSHub#14944]
### Category

New media

### Website URL

https://zhengceku.fun/database

### Website description

中国政策数据库包含政策库、智囊库和资讯库三个板块内容，每日更新，由notion驱动。

### What content should be included?

希望能够包含每日更新的最新内容

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Duplicate of #10871

**Comment by shuifeng100** [comment]
请问一下有没有最新的网址
