### ISSUE TITLE
NDSS route generated invalid feed

### ISSUE THREAD

**Issue by xtexChooser** [DIYgod/RSSHub#14940]
### Routes

```routes
/usenix/usenix-security-sympoium
/ndss-symposium/ndss
```

### Full routes

```fullroutes
/usenix/usenix-security-sympoium
/ndss-symposium/ndss
```

### Related documentation

https://docs.rsshub.app/zh/routes/journal#security-symposia

### What is expected?

A valid feed is generated.

### What is actually happening?

Firefox reported XML parsing error and Akregator reported no feed found.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
https://rsshub.app/usenix/usenix-security-sympoium
https://web.archive.org/web/20240324010239/https://rsshub.app/usenix/usenix-security-sympoium
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Possibly related #14863

**Comment by xtexChooser** [comment]
`/ndss-symposium/ndss` is still broken. pls reopen
cc. @TonyRL
