### ISSUE TITLE
掘金 rss 错误

### ISSUE THREAD

**Issue by LisonFan** [DIYgod/RSSHub#14943]
### 路由地址

```routes
/juejin/trending/:category/:type
```

### 完整路由地址

```fullroutes
/juejin/trending/all/monthly
```

### 相关文档

https://docs.rsshub.app/routes/programming#%E7%83%AD%E9%97%A8

### 预期是什么？

正常输出 rss

### 实际发生了什么？

报错

![image](https://github.com/DIYgod/RSSHub/assets/9424775/820d11fb-a09e-41b0-b083-9f2ae2638a2f)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
This page contains the following errors:
error on line 2842 at column 105: PCDATA invalid Char value 8
Below is a rendering of the page up to the first error.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #14940
