### ISSUE TITLE
哔哩哔哩用户动态部分无法获取内容

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#14952]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/31009079/disableEmbed=1
/bilibili/user/dynamic/5017882/disableEmbed=1
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

正常获取内容

### 实际发生了什么？

大部分UP主内容可以正常获取，部分报错HTTP ERROR 500

### 部署

自建

### 额外信息

```shell
经与其他RSSHub自建用户讨论，发现有同样的问题：
https://github.com/DIYgod/RSSHub/issues/14933#issuecomment-2017099481

只有少数这几个UP主才会出现这种情况。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by hirrao** [comment]
同出现问题，但是有三种情况，第一种，正常获取，第二种，获取成功但是UP主名字为空，第三种情况就是报错
Cannot read properties of null (reading 'map')

**Comment by SpriteOvO** [comment]
https://github.com/DIYgod/RSSHub/blob/a7053991e982ebf29d121ba3285a2f1ae55396be/lib/routes/bilibili/dynamic.ts#L120

It seems like `v1` is a deprecated API, and they removed it today. Replacing it with `v2` could get a valid response, but some data structures have changed.

```patch
- url: `https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=${uid}`, 
+ url: `https://api.vc.bilibili.com/dynamic_svr/v2/dynamic_svr/space_history?host_uid=${uid}`, 
```

**Comment by SpriteOvO** [comment]
I opened a PR #14957 for the fix but didn't test it, since I don't use RSSHub. It would be great if someone could help test it.

**Comment by CaoMeiYouRen** [comment]
> I opened a PR #14957 for the fix but didn't test it, since I don't use RSSHub. It would be great if someone could help test it.

将这个issue中提到的路由加到PR中的`路由地址示例`就能测试路由是否有效
```
/bilibili/user/dynamic/31009079/disableEmbed=1
/bilibili/user/dynamic/5017882/disableEmbed=1
/bilibili/user/dynamic/40366538
```

**Comment by a824355732** [comment]
同样问题，不定UP主的动态无法获取，错误503或者404

https://rsshub.app/bilibili/user/dynamic/731771
