### ISSUE TITLE
Bilibili UP主动态路由失效

### ISSUE THREAD

**Issue by sliots** [DIYgod/RSSHub#14990]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/199676483
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

正常返回

### 实际发生了什么？

Cannot read properties of null (reading 'map')

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Cannot read properties of null (reading 'map')
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by zxmengde** [comment]
我遇到了同样的问题，起初我怀疑是我的ip被封禁，然后更新了使用warp-socks的新版本，但是依然不行。之后我尝试了公共实例，都以失败告终。然后我尝试使用azure的新服务器ip地址，给出相同的错误。我大概能确定这不是ip的问题。最后我尝试了配置bilibili的COOKIE，但是显示一样的错误。我认为是我没有配置好bilibili登录配置，希望@DIYgod给出解决办法和示例。感谢！

**Comment by zxmengde** [comment]
/test

```
/bilibili/user/dynamic/199676483
```

**Comment by sqliuchang** [comment]
刚pull了最新的chromium-bundled版本还是有这个问题

**Comment by TonyRL** [comment]
/test
```routes
/bilibili/user/dynamic/199676483
```

**Comment by DIYgod** [comment]
The API `https://api.vc.bilibili.com/dynamic_svr/v2/dynamic_svr/space_history` of Bilibili is currently invalid.

**Comment by sliots** [comment]
/test
`/bilibili/user/dynamic/199676483`

**Comment by sliots** [comment]
> #14957 v1 api貌似还能工作

在 postman 尝试了下，v1 的 api 应该是需要携带 cookie 才能正常使用

**Comment by Darkluna999** [comment]
same problem

**Comment by a824355732** [comment]
same here

**Comment by THEWINDRUNNERLIFE** [comment]
same problem

**Comment by sliots** [comment]
我这边尝试在本地更换回 v1 接口，并在请求中加上了 cookie。可以正常返回内容了
不过我不太熟悉路由的开发，暂时就不瞎提PR了
@DIYgod @TonyRL

**Comment by sliots** [comment]
同时发现更换会v1后 log中仍然会提示触发风控，原因是

https://github.com/DIYgod/RSSHub/blob/5a7108c7abce06f557e99a9e3a6b75d295a2e52e/lib/routes/bilibili/dynamic.ts#L127

**Comment by mmmjie** [comment]
同样的问题
UP主动态不行
但使用CK的UP主关注可以正常访问

**Comment by CaoMeiYouRen** [comment]
> > #14957 v1 api貌似还能工作
> 
> 在 postman 尝试了下，v1 的 api 应该是需要携带 cookie 才能正常使用
> 
> 同时发现网页端似乎用了新的动态接口
> 
> `https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space?host_mid=`
> 
> @DIYgod @TonyRL

这个新的动态接口在第一次访问的时候会返回个 cookie ，后续使用这个 cookie 可以拿到动态。

但要是尝试多获取几次 cookie 的话，就会触发风控。

**Comment by DIYgod** [comment]
> 但要是尝试多获取几次 cookie 的话，就会触发风控。

@CaoMeiYouRen 但可以把 cookie 保存到缓存中，这样就不需要多次获取了，如果有配置自定义 cookie 还可以使用自定义 cookie，我觉得还是比 v1 接口更可靠

**Comment by CaoMeiYouRen** [comment]
> > 但要是尝试多获取几次 cookie 的话，就会触发风控。
> 
> @CaoMeiYouRen 但可以把 cookie 保存到缓存中，这样就不需要多次获取了，如果有配置自定义 cookie 还可以使用自定义 cookie，我觉得还是比 v1 接口更可靠

同意你的观点。

本人采用 #15011 的修复方案是因为要理清新的接口的逻辑太费时间了，我希望先修复路由，后续再改为新版的接口

**Comment by SpriteOvO** [comment]
FWIW, I have migrate to web API in my own project in commit https://github.com/SpriteOvO/closely/commit/4db4edcbf8519dd6af39253c1c110bfa9ff1fb28. You can reference the data structures there.

For cookies, I used headless Chrome to navigate to the web page once first to get a guest cookies, since the bilibili dynamics doesn't require login and can be accessed anonymously on the browser.

**Comment by CaoMeiYouRen** [comment]
> > > 但要是尝试多获取几次 cookie 的话，就会触发风控。
> > 
> > 
> > @CaoMeiYouRen 但可以把 cookie 保存到缓存中，这样就不需要多次获取了，如果有配置自定义 cookie 还可以使用自定义 cookie，我觉得还是比 v1 接口更可靠
> 
> 同意你的观点。
> 
> 本人采用 #15011 的修复方案是因为要理清新的接口的逻辑太费时间了，我希望先修复路由，后续再改为新版的接口

我准备基于新版网页端API(`https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space` )再进行一次修复，如果有其他人也在修复该路由的话，请回复。

**Comment by CaoMeiYouRen** [comment]
> > > > 但要是尝试多获取几次 cookie 的话，就会触发风控。
> > > 
> > > 
> > > @CaoMeiYouRen 但可以把 cookie 保存到缓存中，这样就不需要多次获取了，如果有配置自定义 cookie 还可以使用自定义 cookie，我觉得还是比 v1 接口更可靠
> > 
> > 
> > 同意你的观点。
> > 本人采用 #15011 的修复方案是因为要理清新的接口的逻辑太费时间了，我希望先修复路由，后续再改为新版的接口
> 
> 我准备基于新版网页端API(`https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space` )再进行一次修复，如果有其他人也在修复该路由的话，请回复。

fix(route): 迁移 bilibili 用户动态路由到新版 web 路由 #15031

**Comment by DIYgod** [comment]
> For cookies, I used headless Chrome to navigate to the web page once first to get a guest cookies, since the bilibili dynamics doesn't require login and can be accessed anonymously on the browser.

@SpriteOvO 你有不使用 headless browser 获取 cookie 的方法么，我按照 Web 的获取方法，先访问 `https://www.bilibili.com` 获得 buvid3，然后访问 `https://api.bilibili.com/x/frontend/finger/spi` 获得 buvid4，但是请求无效，不知道是哪里出了问题

**Comment by SpriteOvO** [comment]
> @SpriteOvO 你有不使用 headless browser 获取 cookie 的方法么，我按照 Web 的获取方法，先访问 `https://www.bilibili.com` 获得 buvid3，然后访问 `https://api.bilibili.com/x/frontend/finger/spi` 获得 buvid4，但是请求无效，不知道是哪里出了问题

它 Cookies 获取方式有点复杂的：

- 首先直接 `/x/frontend/finger/spi` 就可以获取到 `buvid3` 和 `buvid4`
- 但获取到的是没有权限的，还需要发 `/x/internal/gaia-gateway/ExClimbWuzhi` 请求来设置权限
- `/ExClimbWuzhi` 请求格式是经过混淆的，JSON payload 的 keys 全被替换过，并且里面应该有个参数是用于细粒度控制权限范围，比如访问首页拿到的访客 Cookies 不一定能用来获取动态，只有在动态页拿到的访客 Cookies 才能用

我前几天尝试了一下没成功了，有点懒得继续折腾，就直接 headless browser 了。更多细节可以参考 issue SocialSisterYi/bilibili-API-collect#933

**Comment by DIYgod** [comment]
@SpriteOvO 谢谢，看起来好复杂，我也用 headless browser 来搞好了...

**Comment by DIYgod** [comment]
Done 52481ce24d379a49a455bac62bc2c693dc7b7075

**Comment by DIYgod** [comment]
官方实例仍然无法获取可用的 cookie，怀疑有 IP 黑名单

**Comment by wb14123** [comment]
我用最新镜像 `chromium-bundled-2024-04-02` 自己部署的也出现错误：

```
Error Message:
Cannot read properties of undefined (reading 'name')

Route: /bilibili/user/dynamic/:uid/:routeParams?

Full Route: /bilibili/user/dynamic/427494870.atom

Node Version: v21.7.1

Git Hash: 82cbe3cc

Git Date: Tue, 02 Apr 2024 14:52:18 GMT
```
