### ISSUE TITLE
Twitter List - Error Message: Cannot read properties of undefined (reading 'list')

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#15007]
### 路由地址

```routes
/twitter/list/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/list/ladyleet/javascript
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#list-timeline

### 预期是什么？

成功显示 twitter list rss

### 实际发生了什么？

Error Message:
Cannot read properties of undefined (reading 'list')

![image](https://github.com/DIYgod/RSSHub/assets/10363328/c22adaf1-52a5-48d0-84a1-4f1b5ecba21e)

### 部署

自建

### 部署相关信息

windows10、Node Version: v20.11.1

### 额外信息

```shell
是 twitter list rss 不支持了吗？
twitter home 是可以成功显示 rss 的
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by read8873** [comment]
Got similar reply but it says ``Cannot read properties of undefined (reading &#39;att&#39;)``
