### ISSUE TITLE
Bilibili UP主动态路由停止更新

### ISSUE THREAD

**Issue by a824355732** [DIYgod/RSSHub#15020]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/346563107
```

### 相关文档

https://docs.rsshub.app/routes/social-media

### 预期是什么？

RSS更新停止于3/26，预期恢复更新推送

### 实际发生了什么？

RSS更新停止于3/26，预期恢复更新推送

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://rsshub.app/bilibili/user/dynamic/346563107
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KangodYan** [comment]
确实不能用了，我以为是服务站出问题，换了还是不行

**Comment by CaoMeiYouRen** [comment]
跟 #14990 重复了

**Comment by TonyRL** [comment]
Duplicate of #14990
