### ISSUE TITLE
🔴 GitHub Issue / Pull Request comments 错误

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#15048]
### 路由地址

```routes
/github/comments/:user/:repo/:number?
```

### 完整路由地址

```fullroutes
/github/comments/DIYgod/RSSHub/14990
```

### 相关文档

https://docs.rsshub.app/zh/routes/programming#issue-pull-request-comments

### 预期是什么？

- 正确抓取评论

### 实际发生了什么？

- [https://rsshub.app/github/comments/DIYgod/RSSHub/14990](https://rsshub.app/github/comments/DIYgod/RSSHub/14990)
- Cannot read properties of undefined (reading 'x-ratelimit-limit')
- 自建和官方演示均出现错误

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Helpful Information

Error Message:
Cannot read properties of undefined (reading 'x-ratelimit-limit')

Route: /github/comments/:user/:repo/:number?

Full Route: /github/comments/DIYgod/RSSHub/14990

Node Version: v21.7.1

Git Hash: unknown

Git Date:
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by oliroe** [comment]
I'm also seeing similar as well as a lot of rate limit errors

![image](https://github.com/DIYgod/RSSHub/assets/4500141/45698d92-3ca0-4b69-a27a-3df8712226eb)

Looks like the rate limit for unauthenticated users is only 60/hour. Is there any way for us to use our own access token?

![image](https://github.com/DIYgod/RSSHub/assets/4500141/6d51602a-5d40-49fc-9e35-2748c489344f)
