### ISSUE TITLE
【知乎 xhu】 自建报错 Cannot read properties of undefined (reading 'set-cookie')

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#15045]
### 路由地址

```routes
/zhihu/xhu/people/activities/:hexId
```

### 完整路由地址

```fullroutes
/zhihu/xhu/people/activities/:hexId
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#xhu-%E7%94%A8%E6%88%B7%E5%8A%A8%E6%80%81

### 预期是什么？

正常工作

### 实际发生了什么？

自建报错

但是官方的路由可以正常工作  https://rsshub.app/zhihu/xhu/people/activities/69a77a5a8c805446b86053da21a84c51

### 部署

自建

### 额外信息

```shell
Error Message:
Cannot read properties of undefined (reading 'set-cookie')

Route: /zhihu/xhu/people/activities/:hexId

Full Route: /zhihu/xhu/people/activities/69a77a5a8c805446b86053da21a84c51

Node Version: v21.7.1

Git Hash: unknown

Git Date:
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by hunter2030** [comment]
同样的问题，本来好好的能用，后来有个订阅没用，想着更新下。结果弄着弄着，又删了重新安装，就出现这问题了，尴尬。

**Comment by zcw159357** [comment]
应该是got改成ofetch导致的 ofetch默认没有给出response的header了

**Comment by zizhengwu** [comment]
有人依然遇到这个问题吗？如下图，自搭建 git 应该是包括了 fix，但还是

> TypeError: Cannot read properties of undefined (reading 'set-cookie')

https://rsshub.rssforever.com/zhihu/people/activities/limingyang666

![image](https://github.com/DIYgod/RSSHub/assets/2246655/bc0dbc0f-9cce-4777-9525-fa5c8258f633)
