### ISSUE TITLE
【国家气候中心】 title 乱码

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#15042]
### 路由地址

```routes
/ncc-cma/cmdp/image/:id{.+}?
```

### 完整路由地址

```fullroutes
/ncc-cma/cmdp/image/:id{.+}?
```

### 相关文档

https://docs.rsshub.app/zh/routes/other#unknown-100

### 预期是什么？

题目显示正常的中文或者数字

### 实际发生了什么？

变成了乱码

<title>齷� 2024-04-01</title>

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
感谢

https://docs.rsshub.app/zh/routes/other#unknown-100

变成了unknown
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/commit/7a259bf4941a80ecfcf311e94de2d0735a040b58

路由具体的参数

**Comment by layfu** [comment]
喷嚏图卦也有同样的乱码问题
Route: `/dapenti/tugua`
Doc: https://docs.rsshub.app/zh/routes/picture#图卦
