### ISSUE TITLE
希望增加好奇心日报分栏目RSS

### ISSUE THREAD

**Issue by wiagnes** [DIYgod/RSSHub#1505]
### 分栏目，全文

- [ 1 ] 长文章 http://www.qdaily.com/tags/1068.html
- [ 2 ] 10 个图 http://www.qdaily.com/tags/1615.html

### 好奇心日报本身提供RSS，但是信息多得如洪水猛兽一般，让人产生深深的畏惧。时间宝贵，应聚焦在那此值得的事情上。

**Comment by HenryQW** [comment]
考虑一下过滤参数：https://docs.rsshub.app/#%E5%86%85%E5%AE%B9%E8%BF%87%E6%BB%A4

**Comment by yefoenix** [comment]
@wiagnes 请问如何解决的？
