### ISSUE TITLE
ReadHub 出现问题

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#1508]
### 路由地址
- `/readhub/category/topic`
- `/readhub/category/daily`

### 预期是什么？
在本地无论是使用内存还是 Redis 都可以正常获取内容。

![image](https://user-images.githubusercontent.com/21376471/52038494-78ceea00-256d-11e9-9560-975d2a8bf75c.png)

### 实际发生了什么？
线上的 `https://rsshub.app/readhub/category/topic` 却发生错误：

![image](https://user-images.githubusercontent.com/21376471/52038569-a74cc500-256d-11e9-95f0-8be546b91e5f.png)

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    macOS 10.14           |
| Node version       |      v10.15         |
| if Docker, version |     redis:alpine on Docker 18.09.1          |

### 额外信息（日志、报错等）
Git Hash：9afa5049d0050201acf98dda7b5b4da2ee00b006

**Comment by HenryQW** [comment]
> 我猜测是线上 Redis 里缓存了 #1499 提到的问题版本中的错误数据。如果可以的话，清理一下相应的 Redis 缓存吧。

恭喜你猜对了

**Comment by cyy911** [comment]
现在问题还是会出现

**Comment by HenryQW** [comment]
应该是缓存原因，自建的正常

**Comment by DIYgod** [comment]
清了缓存还是有问题，需要排查下逻辑问题
