### ISSUE TITLE
GitHub rate limit

### ISSUE THREAD

**Issue by oliroe** [DIYgod/RSSHub#15106]
### Routes

```routes
NOROUTE
```

### Full routes

```fullroutes
All github routes
```

### Related documentation

https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

### What is expected?

Currently the GitHub route uses an unauthenticated API which has a rate limit of 60 requests per hour. As per the github documentation an authenticated user can use upto 5,000 requests per hour
[https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28](url)

### What is actually happening?

Constant 403 rate limit errors

![image](https://github.com/DIYgod/RSSHub/assets/4500141/ac43fc76-1cc8-46dc-853a-3c53d20e75b2)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Would it be possible to add a parameter to the docker compose so a Github personal access token can be used?
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
`/comments/:user/:repo/:number?` does use GitHub access token if you provide one.
https://github.com/DIYgod/RSSHub/blob/3ba4a634cf83f2217e2722832216d71c5d33e89b/lib/routes/github/comments.ts#L48-L56

**Comment by oliroe** [comment]
Hi

Apologies but I'm struggling to see where the token should be added and it's not mentioned in the documentation

![image](https://github.com/DIYgod/RSSHub/assets/4500141/3b709e34-dc79-48f7-812c-b6631b26e3e7)

Is this the GITHUB_ACCESS_TOKEN as mentioned under Notifications/Repo Stars/Trending/User starred repositories?

**Comment by oliroe** [comment]
Ignore me, I'm an idiot :)

Sorry
