### ISSUE TITLE
路透reuters不能用了

### ISSUE THREAD

**Issue by mycfctech** [DIYgod/RSSHub#15134]
### Routes

```routes
/reuters/business
```

### Full routes

```fullroutes
/reuters/business
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#reuters-%E8%B7%AF%E9%80%8F%E7%A4%BE

### What is expected?

能够正常返回路透内容

### What is actually happening?

报错，无法返回

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Error Message:
got(...).json is not a function

Route: /reuters/:category/:topic?

Full Route: /reuters/business

Node Version: v21.7.1

Git Hash: 71fa4096

Git Date: Wed, 03 Apr 2024 04:05:13 GMT
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by guierpiao** [comment]
好像还是用不了，无法更新最新的内容，这种情况已经一周多了
