### ISSUE TITLE
twitter user timeline is not working

### ISSUE THREAD

**Issue by read8873** [DIYgod/RSSHub#15149]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/username
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#list-timeline

### 预期是什么？

成功显示 twitter rss

### 实际发生了什么？

``Cannot read properties of undefined (reading &#39;att&#39;)``

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

会退到 c65475b5730794f4b522689558b4ed55b9e1cecf 后正常

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KenMercusLai** [comment]
experiencing the same issue with the latest version

**Comment by E1xP** [comment]
I am using docker to host Rsshub instance with twitter cookie. And about 8 timeline per 15min it working fine with the latest images.

**Comment by KenMercusLai** [comment]
> I am using docker to host Rsshub instance with twitter cookie (TWITTER_COOKIE). And about 8 timeline per 15min it working fine with the latest images.

This leads me to think the issue may be because I use TWITTER_USERNAME and TWITTER_PASSWORD. 

The docs recommend diff ways and the way of getting TWITTER_COOKIE seems to be missing
https://docs.rsshub.app/routes/social-media#twitter
https://docs.rsshub.app/deploy/config#twitter

**Comment by KenMercusLai** [comment]
just confirmed using TWITTER_COOKIE works fine.

the cookie can be found under the network tab of inspecting any twitter page after login

**Comment by read8873** [comment]
当 TWITTER_COOKIE 为空时，能否回退到早先版本？

**Comment by E1xP** [comment]
> 当 TWITTER_COOKIE 为空时，能否回退到早先版本？

实际上用户名和密码还能用，只是很容易触发风控；提供二步验证的那个好像有点问题

**Comment by read8873** [comment]
但早https://github.com/DIYgod/RSSHub/commit/c65475b5730794f4b522689558b4ed55b9e1cecf 一直能用，TWITTER_COOKIE大概一天就得换一次。

**Comment by zhusuner** [comment]
同じエラーがクッキーを設定した後に解決しましたので、試してみてください。

**Comment by E1xP** [comment]
> 但早[c65475b](https://github.com/DIYgod/RSSHub/commit/c65475b5730794f4b522689558b4ed55b9e1cecf) 一直能用，TWITTER_COOKIE大概一天就得换一次。

我这有多节点均衡负载Proxy，cookie已经稳定挂了有一个星期了

**Comment by E1xP** [comment]
> > > 但早[c65475b](https://github.com/DIYgod/RSSHub/commit/c65475b5730794f4b522689558b4ed55b9e1cecf) 一直能用，TWITTER_COOKIE大概一天就得换一次。
> > 
> > 
> > 我这有多节点均衡负载Proxy，cookie已经稳定挂了有一个星期了
> 
> 请教一下大佬，节点均衡负载Proxy是如何搭建的？求指路

使用这个项目搭的
https://github.com/v2rayA/v2rayA

**Comment by Wini1680** [comment]
> just confirmed using TWITTER_COOKIE works fine.
> 
> the cookie can be found under the network tab of inspecting any twitter page after login

Could you please show how to set cookie  to env？ Dose only need “auth_token” and “ct0”？

**Comment by Wini1680** [comment]
> just confirmed using TWITTER_COOKIE works fine.
> 
> the cookie can be found under the network tab of inspecting any twitter page after login

Could you please show how to set cookie  to env？ Dose only need “auth_token” and “ct0”？

**Comment by flameleaf** [comment]
> > just confirmed using TWITTER_COOKIE works fine.
> > the cookie can be found under the network tab of inspecting any twitter page after login
> 
> Could you please show how to set cookie to env？ Dose only need “auth_token” and “ct0”？

TWITTER_COOKIE='auth_token=your_auth_token; ct0=your_ct0' works fine for me

**Comment by KenMercusLai** [comment]
> > just confirmed using TWITTER_COOKIE works fine.
> > the cookie can be found under the network tab of inspecting any twitter page after login
> 
> Could you please show how to set cookie to env？ Dose only need “auth_token” and “ct0”？

On Chrome, Inspect -> Network, refresh the page
![image](https://github.com/DIYgod/RSSHub/assets/5419014/1df5b5c9-00e8-43ed-97d1-e5b468464f3e)

I simply copied all of them
