### ISSUE TITLE
自部署后，welcome页面正常显示，但是任何路由均无法使用

### ISSUE THREAD

**Issue by mind-dance** [DIYgod/RSSHub#15150]
### 路由地址

```routes
/douban/movie/later
```

### 完整路由地址

```fullroutes
/douban/movie/later
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E5%8D%B3%E5%B0%86%E4%B8%8A%E6%98%A0%E7%9A%84%E7%94%B5%E5%BD%B1

### 预期是什么？

返回相关的订阅

### 实际发生了什么？

error in RSSHub!

### 部署

自建

### 部署相关信息

OS: Linux，Node version: v21.6.2

### 额外信息

```shell
自部署地址：https://rsshub.friesport.ac.cn


Route requested: /douban/movie/later

Error message: Socks5 proxy rejected connection - HostUnreachable: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /douban/movie/later
Node version: v21.6.2
Git Hash: unknown
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by mind-dance** [comment]
我认为不是路由问题，而是我的自部署出错了，因为演示站的相同路由是可以使用的。我希望得到一些debug的指引。

**Comment by mind-dance** [comment]
关错了

**Comment by TonyRL** [comment]
Duplicate of #15096
