### ISSUE TITLE
官方doc中，作为 npm 包使用的js代码执行报错（NOROUTE）

### ISSUE THREAD

**Issue by lunat1cccc** [DIYgod/RSSHub#15152]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://rsshub-doc.pages.dev/usage.html#bian-xie-ding-yue-yuan

### 预期是什么？

使用官方示例代码运行

### 实际发生了什么？

执行报错：
\node_modules\rsshub\lib\pkg.ts:1
import { setConfig } from '@/config';
SyntaxError: Cannot use import statement outside a module

尝试解决：
package.json中添加type：module，并改为import导入
仍旧报错：TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for d:\Test\js\RSS\node_modules\rsshub\lib\pkg.ts

类似的issue：有一个类似的但是他是部署到vercel的时候报错，和安装rsshub包使用并不类似。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Windows：Node.js v20.10.0

### 额外信息

```shell
null
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lunat1cccc** [comment]
我应该使用哪一个版本或者分支

**Comment by TonyRL** [comment]
Duplicate of #14930

**Comment by lunat1cccc** [comment]
sorry，搜索报错的时候并没有找到这个issue，但是我看了这个issue，似乎还没有解决方法是吗
