### ISSUE TITLE
Gogs / Gitea 支持

### ISSUE THREAD

**Issue by wi24rd** [DIYgod/RSSHub#1517]
### 源站地址
各种依靠 Gogs/Gitea 的站点
### 需要生成什么内容？
可以参考另一个类似项目 RSS-Bridge/rss-bridge/issues/1012 里已经列出的信息。
### 额外描述
最后路由可以弄成例如 /{gitea,gogs}/foo.bar.tld/{issue,commit,release,author...}/:attribute[/http[s]] 这样子？
attribute 比如项目名或者id之类的。
然后不指定协议的话就默认 http。

**Comment by wi24rd** [comment]
同理还有其他一些用模板但是对 RSS 支持不怎么好的站点，比如 flarum 之类的管理员并没有安装 rss 插件的情况比较难受。（感觉不怎么可能实现还是不另外开 issue 了

**Comment by tgly307** [comment]
难就难在这个各种站点上……是指站点地址也通过参数传进去吗？
gogs和gitea本身提供的API还算丰富，理论上抓取这些信息应该不难

**Comment by HenryQW** [comment]
https://github.com/gogs/gogs/issues/2301#issuecomment-380522942

我就做了一个 ttrss 的[镜像 repo](https://github.com/HenryQW/tt-rss-mirror)，然后订阅 GitHub RSS。

**Comment by NeverBehave** [comment]
https://github.com/RSS-Bridge/rss-bridge/pull/1180 
There is one, closing as this is an old thread.
