### ISSUE TITLE
微博【博主（方案2）】中的 pubDate 不准确

### ISSUE THREAD

**Issue by Ice-Hazymoon** [DIYgod/RSSHub#1520]
### 路由地址

[https://rsshub.app/weibo/user2/5466307917?limit=1](https://rsshub.app/weibo/user2/5466307917?limit=1)

### 预期是什么？

同一条微博，每次更新时的发布时间`pubDate`字段内容相同

### 实际发生了什么？

同一条微博，每次抓取的时间都会有误差几秒钟

### 额外信息（日志、报错等）

![image](https://user-images.githubusercontent.com/25239977/52174812-994cad80-27d4-11e9-9a0a-72fca3bf9855.png)

![image](https://user-images.githubusercontent.com/25239977/52174822-b5e8e580-27d4-11e9-89b7-72d6fd98edb1.png)

顺便问下有什么好的方法来对比 rss 每次更新了哪些内容吗，像这种有误差的经常会推送多次

**Comment by HenryQW** [comment]
一般对比【新条目】都是用 guid，同一条目下内容更新采用的是 pubDate
