### ISSUE TITLE
the docs of cnblogs repeat many times

### ISSUE THREAD

**Issue by mind-dance** [DIYgod/RSSHub#15204]
### 路由地址

```routes
/cnblogs/aggsite/topdiggs
```

### 完整路由地址

```fullroutes
/cnblogs/aggsite/topdiggs
```

### 相关文档

https://docs.rsshub.app/zh/routes/blog#_10-%E5%A4%A9%E6%8E%A8%E8%8D%90%E6%8E%92%E8%A1%8C%E6%A6%9C

### 预期是什么？

only appear one times

### 实际发生了什么？

it repeat many times

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
----
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
Resolved.
