### ISSUE TITLE
【B站】官方路由报错The cookie has expired, please try again 

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#15205]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

正常工作

### 实际发生了什么？

有些id可以抓，有些报错cookies过期，有些报错正在抓取

正常：https://rsshub.app/bilibili/user/dynamic/2267573

The cookie has expired, please try again 或者  This path is currently fetching, please come back later!

https://rsshub.app/bilibili/user/dynamic/277302496

https://rsshub.app/bilibili/user/dynamic/14056545

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Qixingchen** [comment]
触发风控了,建议自建或重试等待cookie自动更新后解封

**Comment by KwToPA** [comment]
> 触发风控了,建议自建或重试等待cookie自动更新后解封

请问自建的命令应该如何写？我用docker部署的，B站的那个cookies应该写到哪儿？  @Qixingchen 

写在docker run -d 这句里面吗?

我当前就是自建，没加B站的cookies，B站的路由前几天刚正常抓过一次，如今全部都是 This path is currently fetching, please come back later!

**Comment by Qixingchen** [comment]
加 -e NAME=VALUE
currently fetching 应该隔一段时间去获取就可以了.但是如果你的缓存时间太短会导致每次都是currently fetching.
如果你需要很短的缓存时间,建议直接关断缓存

**Comment by KwToPA** [comment]
> 加 -e NAME=VALUE currently fetching 应该隔一段时间去获取就可以了.但是如果你的缓存时间太短会导致每次都是currently fetching. 如果你需要很短的缓存时间,建议直接关断缓存

BILIBILI_COOKIE_*, optional - 如果没有此配置，那么必须开启 puppeteer 支持；BILIBILI_COOKIE_{uid}: 用于用户关注动态系列路由，对应 uid 的 b 站用户登录后的 Cookie 值，{uid} 替换为 uid，如 BILIBILI_COOKIE_2267573

官方的这个没看明白

1、uid是本人账号的uid吗？
2、如果本人账号的uid为123456，那么 https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=0&type=8

应该改成这样吗？ https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=123456&type=8

3、dynamic_new?uid=0&type=8 在network，name栏中

4、我目前在https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=0&type=8 中找到了对应cookies，假设为 XXX

 -e NAME=VALUE 应该改成 -e BILIBILI_COOKIE_123456=XXX  吗？

谢谢  [Qixingchen](https://github.com/Qixingchen)

**Comment by Qixingchen** [comment]
2 不用,链接里面 uid 啥都可以,提示访问出错也无所谓
4 对的

**Comment by KwToPA** [comment]
> 2 不用,链接里面 uid 啥都可以,提示访问出错也无所谓 4 对的

请问-e BILIBILI_COOKIE_123456=XXX 能不能改成 -e BILIBILI_COOKIE_123456="XXX"  我怕XXX里面有&这种特殊字符

**Comment by Qixingchen** [comment]
可以,也建议这么写

**Comment by KwToPA** [comment]
我用自己的cookies，结果也触发 This path is currently fetching, please come back later!

现在应该重新获取cookies还是B站会自动解封？

谢谢
