### ISSUE TITLE
Nature is down

### ISSUE THREAD

**Issue by ImVictorCheng** [DIYgod/RSSHub#15208]
### 路由地址

```routes
/nature/research/:journal?
```

### 完整路由地址

```fullroutes
/nature/research/nature
```

### 相关文档

https://docs.rsshub.app/routes/journal#nature-journal

### 预期是什么？

返回rss订阅

### 实际发生了什么？

报错：
Looks like something went wrong

Error Message:
TypeError: Invalid URL

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Helpful Information

Error Message:
TypeError: Invalid URL

Route: /nature/research/:journal?

Full Route: /nature/research/nature

Node Version: v21.7.2

Git Hash: 4655e095

Git Date: Wed, 10 Apr 2024 19:35:55 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
Resolved. All routes should return normally.
