### ISSUE TITLE
Bilibili up主专栏 自建出错

### ISSUE THREAD

**Issue by Kevin6872** [DIYgod/RSSHub#15206]
### 路由地址

```routes
/bilibili/user/article/:uid
```

### 完整路由地址

```fullroutes
/bilibili/user/article/334958638
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E4%B8%93%E6%A0%8F

### 预期是什么？

正常显示

### 实际发生了什么？

使用 docker 部署时出现此错误

### 部署

自建

### 额外信息

```shell
Error Message:
Error: Could not find Chrome (ver. 123.0.6312.86). This can occur if either 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or 2. your cache path is incorrectly configured (which is: /app/node_modules/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

Route: /bilibili/user/article/:uid

Full Route: /bilibili/user/article/334958638

Node Version: v21.7.3

Git Hash: 0a87eaf4

Git Date: Thu, 11 Apr 2024 17:50:07 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Qixingchen** [comment]
可以看下 #15190

**Comment by Kevin6872** [comment]
更换chromium-bundled镜像已经解决了问题，请问这是因为触发了风控，还是这个路由必须使用chromium-bundled镜像

**Comment by Qixingchen** [comment]
> 更换chromium-bundled镜像已经解决了问题，请问这是因为触发了风控，还是这个路由必须使用chromium-bundled镜像

触发风控后需要用 Puppeteer 获取游客 cookie 来绕过风控

**Comment by Kevin6872** [comment]
明白了，感谢解答

**Comment by ladyrick** [comment]
@Qixingchen 请问如果不是在容器中部署的，是在电脑上直接 pnpm dev 起的，要怎么换 chrome 呢？
