### ISSUE TITLE
Twitter 源生成图片链接时地址错误

### ISSUE THREAD

**Issue by LolitaOT** [DIYgod/RSSHub#15254]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/twitter/user/houkaistarrail
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#user-timeline-4

### 预期是什么？

图片链接应该是：https://pbs.twimg.com/media/GLQtl4VaMAAtkUR?format=jpg&name=orig

### 实际发生了什么？

链接发生了错误的转义导致图片显示失败：https://pbs.twimg.com/media/GLQtl4VaMAAtkUR?format=jpg&amp;name=orig
\&amp; 为转义后的 &

### 部署

自建

### 部署相关信息

Docker: 今日拉取的 latest 版本

### 额外信息

```shell
无报错信息。
这应该是工具类的错误，不关路由的事情。
在 /lib/routes/twitter/utils.ts 中 getOriginalImg 的方法看着没什么问题，应该是向标签的属性中赋值的时候发生了转义？
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by LolitaOT** [comment]
这应该是工具类的错误，不关路由的事情

**Comment by LolitaOT** [comment]
![image](https://github.com/DIYgod/RSSHub/assets/32677256/c922345c-f82d-49b6-ba49-3ca8ee42a842)
这是部分 rss 的返回

**Comment by TonyRL** [comment]
You are supposed to read the feed content through RSS readers, not consume the raw RSS XML directly in the browser. I've tested it with [RSS Viewer](https://codebeautify.org/rssviewer) and [Fluent Reader](https://github.com/yang991178/fluent-reader), and both software can decode HTML entities properly.
