### ISSUE TITLE
`PROXY_URI` 不起作用

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub#15250]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/deploy/config#%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE

### 预期是什么？

设置环境变量 `PROXY_URI` 后请求应该走代理

### 实际发生了什么？

请求没有走代理
![image](https://github.com/DIYgod/RSSHub/assets/37261065/045b2acb-1a71-4217-8196-a392ad8a51b7)

但是回退几个版本就正常走代理，比如回退到`614f6dc12fe1a55aa6aeb86c6553ad778f755a95`
![image](https://github.com/DIYgod/RSSHub/assets/37261065/ed363ba8-14db-48b0-9722-03df5bf60d03)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
用的是http代理所以应该和#15096无关
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by xianghuawe** [comment]
这个问题 后面是怎么解决的呢
