### ISSUE TITLE
希望有对微博的新的(?)内容整合页也做成RSS

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#1528]
### 源站地址
https://weibo.com/a/hot/7544867331250177_1.html?type=new
https://weibo.com/a/hot/7562076604637185_1.html#
https://weibo.com/a/hot/7556443852019713_1.html?type=new

### 需要生成什么内容？

- [ ] 标题
- [ ] 图片x9
- [ ] 正文内容
- [ ] 源微博链接 

### 额外描述
这些页面应该与新浪旗下一个叫“鲜知”的app有关 这些页面按下关注按钮 并不会出现在web版 国际版微博 第三方微博客户端上 
看上去是授权了一些账号做内容整合？
有时候有些weibo也会有个按钮可以点入被收录的这些页面 
![image](https://user-images.githubusercontent.com/33424662/52465093-4dc14780-2bb8-11e9-90de-ec50858b1d6d.png)
https://weibo.com/a/hot/7565156181645313_1.html

不管怎么样 毕竟是整合好的内容  某些场合 比起逐个自己关注博主更有效率（毕竟有的人夹杂不少私人内容，rsshub里面也没法很好自动筛选“原创+图片”这样的方式）
希望有这个RSS
可以的话……

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
