### ISSUE TITLE
CNBC增补路由

### ISSUE THREAD

**Issue by benjaminyzhang** [DIYgod/RSSHub#15286]
### 这是一个什么样的功能？

`https://www.cnbc.com/banks/`页面没有Channel ID，无法生成RSS。希望RSSHub增补路由支持该类页面的标题和链接。

### 这个功能可以解决什么问题？

增补CNBC路由，支持`https://www.cnbc.com/banks/`，完善对CNBC的支持。

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
The official RSS of that page is https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000876

**Comment by benjaminyzhang** [comment]
Thanks!

> The official RSS of that page is https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000876
