### ISSUE TITLE
希望能够支持一些新闻媒体的订阅，如新加坡的联合早报等。

### ISSUE THREAD

**Issue by zhanghub** [DIYgod/RSSHub#153]
虽然说订阅新闻媒体的很少，但希望能够有机会考虑一下，联合早报虽然有微博账号，但并非每一条新闻都会推送到微博上，官网为zaobao.com。多谢。

**Comment by wenketel** [comment]
@zhanghub https://feedx.net/rss/zaobaotoday.xml   https://feedx.net/zaobaotoday

**Comment by zhanghub** [comment]
@wenketel 多谢
