### ISSUE TITLE
Improve Twitter

### ISSUE THREAD

**Issue by o11593304** [DIYgod/RSSHub#1530]
### What content should be included?

- [Filter direct messages ]
- [ Filter retweets]

### Additional description
Hello everyone!
I would like to request some parameters for Twitter. On the website [queryfeed](https://queryfeed.net) they offer the ability to filter direct messages and retweets, but unfortunately it doesn't work (at least for me, I've tried it several times in the last few months) and I couldn't find any other service that does.

It would be great if RSSHub added such a capability, trying to follow the content of some authors can be a real torment when they use the same account for other topics.
In the website mentioned above include a link to [Twitter API](https://developer.twitter.com/en/docs/api-reference-index) that may be helpful, I'm sorry I can not do more.

Have a nice day! :-)

**Comment by DIYgod** [comment]
https://docs.rsshub.app/en/#filtering

**Comment by o11593304** [comment]
Thank you for responding! Unfortunately these filters do not work, not even for the authors.

**Comment by HenryQW** [comment]
> Thank you for responding! Unfortunately these filters do not work, not even for the authors.

Please provide examples for us to investigate. Filtering by author only works if feed has an author, in twitter's case, it doesn't have one. Naturally when you subscribe to someone's tweets, the author is implicitly him/her.
```xml
<item>
<title>
<![CDATA[ Re @ch1oechao 新年快乐 ]]>
</title>
<description>
<![CDATA[ Re @ch1oechao 新年快乐 ]]>
</description>
<pubDate>Tue, 05 Feb 2019 15:50:51 GMT</pubDate>
<guid>
https://twitter.com/DIYgod/status/1092812807001624576
</guid>
<link>
https://twitter.com/DIYgod/status/1092812807001624576
</link>
</item>
```

Filtering of retweets can be achieved by `?filterout_title=Re%20@`

https://rsshub.app/twitter/user/DIYgod?filterout_title=Re%20@

**Comment by victor21813** [comment]
他說的應該是轉推(分享推文) 不是回覆
當訂閱的對象轉推別人的推文時，會一同與訂閱的對象所發的推文一起推送出來
目前看起來的確沒有辦法從filter濾除
