### ISSUE TITLE
哔哩哔哩用户动态失效，已经更新了最新版仍然有问题

### ISSUE THREAD

**Issue by xiaocainiao2020** [DIYgod/RSSHub#15315]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/37663924
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

恢复正常

### 实际发生了什么？

失效了，加载不出来。隔一段时间偶尔能成功，但是过一会儿就又不行了。

### 部署

自建

### 额外信息

```shell
Route requested: /bilibili/user/dynamic/37663924
Error message: Cannot read property '0' of null
Helpful Information to provide when opening issue: 
Path: /bilibili/user/dynamic/37663924
Node version: v14.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dangehub** [comment]
你设置cookie了吗，我光用puppeteer不够，设置了cookie就好了。

**Comment by xiaocainiao2020** [comment]
> 你设置cookie了吗，我光用puppeteer不够，设置了cookie就好了。

设置了也不管用，而且这个路由不需要puppeteer和cookies呀，之前都是可以直接获取的，最近就不行了。

**Comment by dangehub** [comment]
> > 你设置cookie了吗，我光用puppeteer不够，设置了cookie就好了。
> 
> 设置了也不管用，而且这个路由不需要puppeteer和cookies呀，之前都是可以直接获取的，最近就不行了。

你去看最新的文档，里面写了

**Comment by xiaocainiao2020** [comment]
> > > 你设置cookie了吗，我光用puppeteer不够，设置了cookie就好了。
> > 
> > 
> > 设置了也不管用，而且这个路由不需要puppeteer和cookies呀，之前都是可以直接获取的，最近就不行了。
> 
> 你去看最新的文档，里面写了

好的，现在可以了
