### ISSUE TITLE
Route "/theblockbeats" is down for months.

### ISSUE THREAD

**Issue by daringcalf** [DIYgod/RSSHub#15344]
### Routes

```routes
/theblockbeats/:channel?
```

### Full routes

```fullroutes
/theblockbeats/article
```

### Related documentation

https://docs.rsshub.app/routes/finance#%E5%BE%8B%E5%8A%A8

### What is expected?

Get content of theblockbeats.

### What is actually happening?

![image](https://github.com/DIYgod/RSSHub/assets/19504143/4692fcfd-425a-44ba-8bf0-999c0f8db562)

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
[GET] "https://api.theblockbeats.info/v5/Information/newsall": 404 Not Found: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by jameshih** [comment]
BlockBeats released an official RSS feed a while back.

RSS Feed Link
```
https://api.theblockbeats.news/v1/open-api/home-xml
```

And here is their official GitHub repo for the RSS feed
[BlockBeatsOfficial/RSS](https://github.com/BlockBeatsOfficial/RSS)
