### ISSUE TITLE
哔哩哔哩 用户关注动态 失效

### ISSUE THREAD

**Issue by chenyucheng0503** [DIYgod/RSSHub#15358]
### Routes

```routes
/bilibili/followings/dynamic/:uid/:disableEmbed?
```

### Full routes

```fullroutes
/bilibili/followings/dynamic/self_user_id
```

### Related documentation

https://docs.rsshub.app/social-media.html#bilibili

### What is expected?

自建，已经添加cookies，能够看到个人关注的动态

### What is actually happening?

已经运行好几个月了，但是前两周开始不再更新动态。访问提示`Error message: Cannot read properties of null (reading 'forEach')`

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
null
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by item0910** [comment]
一样的问题, 无法获取推送, 不能添加新源

**Comment by Vstory** [comment]
> 一样的问题, 无法获取推送, 不能添加新源

已经关注的可以获取推送，但是无法添加新源
