### ISSUE TITLE
关于telegram channel的RSS

### ISSUE THREAD

**Issue by enkiger** [DIYgod/RSSHub#15354]
### Routes

```routes
/telegram/channel/:username/:routeParams?
```

### Full routes

```fullroutes
/telegram/channel/Aliyun_4K_Movies/showMediaTagInTitle=0
```

### Related documentation

https://docs.rsshub.app/routes/social-media#channel

### What is expected?

订阅频道https://t.me/Aliyun_4K_Movies

### What is actually happening?

https://t.me/Aliyun_4K_Movies无法RSS

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
例如频道 https://t.me/Aliyun_4K_Movies
频道name是Aliyun_4K_Movies
app：reeder5
当name里面包含下划线的时候，会无法进行订阅
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by KarasuShin** [comment]
这个问题并不是因为下划线引起的。

有些频道开启了“Restrict Saving Content”，对于这类频道，通过分享链接访问时, https://t.me/s/Aliyun_4K_Movies 会被重定向至https://t.me/Aliyun_4K_Movies ，导致无法获取到频道的预览内容。
![CleanShot 2024-04-24 at 17 20 56@2x](https://github.com/DIYgod/RSSHub/assets/13167154/69bc9420-9243-447a-a12a-70b681631095)

**Comment by enkiger** [comment]
明白了，多谢。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: karasu ***@***.***>
发送时间: Wednesday, April 24, 2024 5:25:30 PM
收件人: DIYgod/RSSHub ***@***.***>
抄送: enkiger ***@***.***>; Author ***@***.***>
主题: Re: [DIYgod/RSSHub] 关于telegram channel的RSS (Issue #15354)


这个问题并不是因为下划线引起的。

有些频道开启了“Restrict Saving Content”，对于这类频道，通过分享链接访问时, https://t.me/s/Aliyun_4K_Movies 会被重定向至https://t.me/Aliyun_4K_Movies ，导致无法获取到频道的预览内容。
***@***.*** (view on web)<https://github.com/DIYgod/RSSHub/assets/13167154/69bc9420-9243-447a-a12a-70b681631095>

―
