### ISSUE TITLE
雪球股票信息出错

### ISSUE THREAD

**Issue by willsuatsz** [DIYgod/RSSHub#15360]
### 路由地址

```routes
/xueqiu/stock_info/:id
```

### 完整路由地址

```fullroutes
/xueqiu/stock_info/SH688408
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

最新的公告内容

### 实际发生了什么？

错误页面

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'set-cookie')

Route: /xueqiu/stock_info/:id/:type?

Full Route: /xueqiu/stock_info/SH688408

Node Version: v21.7.3

Git Hash: 4787b2c7

Git Date: Wed, 24 Apr 2024 11:17:18 GMT

Report
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by zhoukuncheng** [comment]
我也发现了
https://rsshub.app/xueqiu/stock_info/NVDA  
![image](https://github.com/DIYgod/RSSHub/assets/5327960/3523499a-84ed-4f87-af45-ca09ea87f864)

**Comment by zhoukuncheng** [comment]
我也发现了
https://rsshub.app/xueqiu/stock_info/NVDA  
```route
/xueqiu/stock_info/NVDA
```
![image](https://github.com/DIYgod/RSSHub/assets/5327960/3523499a-84ed-4f87-af45-ca09ea87f864)

**Comment by linkboy2007** [comment]
@zhoukuncheng   又挂了。包括 用户动态。
