### ISSUE TITLE
微博关键词路由大部分失效

### ISSUE THREAD

**Issue by sandingman** [DIYgod/RSSHub#15396]
### 路由地址

```routes
/weibo/keyword/:keyword/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/keyword/samsung
/weibo/keyword/vivo
```

### 相关文档

https://docs.rsshub.app/routes/weibo

### 预期是什么？

Get content of theblockbeats.

### 实际发生了什么？

![image](https://github.com/DIYgod/RSSHub/assets/86282861/2b851326-78f9-4a49-85c9-8a7678899c97)

### 部署

自建

### 部署相关信息

OS: Linux, Docker: v24.0.2

### 额外信息

```shell
Cannot read properties of undefined (reading 'created_at')
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by sandingman** [comment]
路由匹配 请重新审核

**Comment by EricYeoo** [comment]
我也遇到了相同的问题
