### ISSUE TITLE
Colamanga RSS : HTTP ERROR 500

### ISSUE THREAD

**Issue by cxheng315** [DIYgod/RSSHub#15397]
### 路由地址

```routes
/colamanga/:id
```

### 完整路由地址

```fullroutes
colamanga/manga-he35406
colamanga/manga-mr937429
```

### 相关文档

https://docs.rsshub.app/routes/anime#colamanga

### 预期是什么？

正常顯示 rss 內容

### 实际发生了什么？

瀏覽器
![image](https://github.com/DIYgod/RSSHub/assets/64959125/679bf36c-6834-4126-a86c-77dcf35bdf46)
RSS Hub Preview
![image](https://github.com/DIYgod/RSSHub/assets/64959125/3d33f040-4616-47c8-b10f-19378055e299)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
這個網頁無法正常運作rsshub.app 目前無法處理這項要求。
HTTP ERROR 500
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by machsix** [comment]
![image](https://github.com/DIYgod/RSSHub/assets/28209092/c2dcfb14-3fd3-464b-a329-a977484727d

我自己的节点没问题, rsshub.app刷新了两三次就好了,建议自建

**Comment by TonyRL** [comment]
/test
```routes
/colamanga/manga-he35406
/colamanga/manga-mr937429
```

**Comment by TonyRL** [comment]
It works.
