### ISSUE TITLE
抓取知乎存在pubdate错误

### ISSUE THREAD

**Issue by domonnss** [DIYgod/RSSHub#15400]
### 路由地址

```routes
/zhihu/posts/:usertype/:id
```

### 完整路由地址

```fullroutes
http://{selfhost}/zhihu/posts/people/pang-zi-qi-40
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-wen-zhang

### 预期是什么？

文章发表时间正确

### 实际发生了什么？

文章时间显示错误均为1970年1月20日

### 部署

自建

### 部署相关信息

OS:ubuntu20.04,node:v20.9.0,Docker:25.0.0-beta.1

### 额外信息

```shell
时间显示错误,用docker-compose部署,将镜像版本更换为diygod/rsshub:2024-03-23,问题解决
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/posts/people/pang-zi-qi-40
```

**Comment by TonyRL** [comment]
All articles listed have proper date.
