### ISSUE TITLE
希望增加掘金logo 作为掘金分类文章rss源的图标

### ISSUE THREAD

**Issue by Jinkeycode** [DIYgod/RSSHub#1542]
### 这是一个什么样的功能？
希望增加掘金logo 作为掘金分类文章rss源的图标，其他 rss 也希望可以增加 favicon 的提取作为  RSS 源图标

### 这个功能可以解决什么问题？
提高文章或者 RSS 源 在信息流中的辨识度，提高阅读效率

**Comment by DIYgod** [comment]
一般阅读器会使用 link 的 favicon 作为图标，Reeder Feedly Inoreader Tiny Tiny RSS 都是这样，指定 logo 感觉没什么必要

**Comment by HenryQW** [comment]
尝试换个阅读器吧，几乎所有阅读器都直接抓 root favicon


Reeder 订阅 https://rsshub.app/juejin/category/frontend.rss 的效果
![image](https://user-images.githubusercontent.com/5896343/53022995-49b4e580-3454-11e9-9b63-c8997353ce8c.png)

**Comment by Jinkeycode** [comment]
@DIYgod 如果自己部署，可以怎么指定 icon？

**Comment by HenryQW** [comment]
模版内置了对图标的支持，传入参数即可。见 [rss 2.0](https://github.com/DIYgod/RSSHub/blob/master/lib/views/rss.art) 及 [atom](https://github.com/DIYgod/RSSHub/blob/master/lib/views/rss.art)。

RSS 2.0 和 Atom 协议标准较为混乱，市面上绝大多数阅读器均不支持读取图标，而直接抓取站点 favicon，亲测 ttrss 以及 reeder。

![img_1380](https://user-images.githubusercontent.com/5896343/53029886-b2568f00-3461-11e9-83fb-87cfa5d58573.PNG)
