### ISSUE TITLE
Pixiv - User Activity 获取失败

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#15425]
### 路由地址

```routes
/pixiv/user/:id
```

### 完整路由地址

```fullroutes
/pixiv/user/2497307
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#user-activity

### 预期是什么？

正常获取内容

### 实际发生了什么？

自建并配置`PIXIV_REFRESHTOKEN`提示：`RejectError: Authentication failed. Access denied.`
[rsshub.app](https://rsshub.app/)提示`FetchError: [GET] "https://app-api.pixiv.net/v1/user/illusts?filter=for_ios&user_id=2497307": 403 Forbidden`
访问提示链接显示：
```
{
  "error": {
    "user_message": "",
    "message": "Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_request",
    "reason": "",
    "user_message_details": {

    }
  }
}
```

### 部署

自建

### 额外信息

```shell
None
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Can't reproduce. Please generate another and try again
<details><summary>Screenshot</summary>

![Screenshot](https://github.com/DIYgod/RSSHub/assets/11386903/a92fdd2d-7147-4abe-b287-a76b9e8c04fc)
</details>
