### ISSUE TITLE
EPIC免费游戏 item.description中的img标签不闭合

### ISSUE THREAD

**Issue by firstmeet1108** [DIYgod/RSSHub#15459]
### 路由地址

```routes
/epicgames/freegames/:locale?/:country?
```

### 完整路由地址

```fullroutes
/epicgames/freegames/zh-CN
```

### 相关文档

https://docs.rsshub.app/zh/routes/game#epic-games-store

### 预期是什么？

# item.description中的img标签可以自闭合

例如：
希望为
` <img src="..." /> `
而非
` <img src="..." > `

### 实际发生了什么？

# 表现

![image](https://github.com/DIYgod/RSSHub/assets/102291953/64310cf5-613d-470a-ae71-d0833272629b)

其中 `item.description` 中的 `img`标签为`<img src="https://cdn1.epicgames.com/spt-assets/af503dd7e8b64218b69c22a9003de268/orcs-must-die-3-1puow.jpg" referrerpolicy="no-referrer">`，未自闭合。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by JimenezLi** [comment]
img 标签不闭合是存在兼容性问题吗
description 里面的标签符号都处理成了 `&lt;` 和 `&gt;`，不算 XML 标签

**Comment by Candinya** [comment]
img 标签末尾的闭合斜杠是可选的，可以参见 [HTML 的 spec](https://html.spec.whatwg.org/multipage/syntax.html#start-tags):

>6. Then, if the element is one of the void elements, or if the element is a foreign element, then there **may** be a single U+002F SOLIDUS character (/), which on foreign elements marks the start tag as self-closing.

如果解析器不支持非闭合的 img 标签，那是解析器有兼容性问题，可以使用预处理工具格式化或更换兼容性更完整的解析器。
