### ISSUE TITLE
bilibili的动态rss出错

### ISSUE THREAD

**Issue by gjhuai** [DIYgod/RSSHub#15476]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/8969156
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

获取正常rss更新内容

### 实际发生了什么？

出错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Helpful Information

Error Message:
Error: The cookie has expired, please try again.

Route: /bilibili/user/dynamic/:uid/:routeParams?

Full Route: /bilibili/user/dynamic/8969156

Node Version: v21.7.3

Git Hash: 75d81525

Git Date: Sat, 04 May 2024 15:09:33 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by E1xP** [comment]
使用diygod/rsshub:chromium-bundled自建的项目有类似的问题

Error: The cookie has expired, please try again.

**Comment by Freddd13** [comment]
@E1xP 我之前也是，等一会就好了
