### ISSUE TITLE
cnpm install失败

### ISSUE THREAD

**Issue by booboom** [DIYgod/RSSHub#1547]
![image](https://user-images.githubusercontent.com/24515720/52760859-12a59500-304c-11e9-8478-e8c8ec2cdcbd.png)

nodeban b版本V8.11.3

**Comment by DIYgod** [comment]
日志不是写了么，connect ETIMEDOUT

**Comment by booboom** [comment]
。。。我不太会弄这个，启动成功了，但是怎么用啊这个？求教一下。

**Comment by yefoenix** [comment]
@booboom https://docs.rsshub.app/

**Comment by booboom** [comment]
@yefoenix 我看了，但是还是不知道在哪起手，是要吧这个当成API然后自己写页面么？。。。

**Comment by yefoenix** [comment]
@booboom 建议简单了解一下 RSS 是什么和怎么用

**Comment by booboom** [comment]
@yefoenix 好的，谢谢 。
