### ISSUE TITLE
fetching twitter media of a particular user leading to empty route

### ISSUE THREAD

**Issue by KenMercusLai** [DIYgod/RSSHub#15481]
### Routes

```routes
/twitter/media/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/media/gunsnrosesgirl3
```

### Related documentation

https://docs.rsshub.app/routes/social-media#user-media

### What is expected?

The fetch is expected as others 

### What is actually happening?

I have multiple rss feeds with the same route, like:
/twitter/media/BiancoDavinci
/twitter/media/Locati0ns
/twitter/media/TheFigen_

and all of them have been working fine except the following one
/twitter/media/gunsnrosesgirl3

which has been confirmed: https://twitter.com/gunsnrosesgirl3

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

linux

### Additional info

```shell
2024-05-06T04:32:24.725313253Z info: <-- GET /twitter/media/gunsnrosesgirl3
2024-05-06T04:32:26.378351662Z error: Error in /twitter/media/gunsnrosesgirl3: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
2024-05-06T04:32:26.380700188Z info: --> GET /twitter/media/gunsnrosesgirl3 503 2s
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
This user has only 1 media which is posted on 21 May 2024. That means this route is working as expected.
<details><summary>Screenshot</summary>

![Screenshot](https://github.com/DIYgod/RSSHub/assets/11386903/f12dbd79-d100-445b-ae51-ea1d5f8da4d8)
</details>
