### ISSUE TITLE
文档丢失PAC相关内容？

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#15496]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/deploy/config#proxy-configurations

### 预期是什么？

文档包含以下pr的内容：
https://github.com/DIYgod/RSSHub/pull/14218/files/f7470a69e7e7524aafd59e2cc087030ebb08aecc#diff-e8a4394167e6ec88b548237287b525db72b8f90c2b17385fc92f82d1c44e8318

### 实际发生了什么？

未出现：
https://docs.rsshub.app/deploy/config#proxy-configurations

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by DIYgod** [comment]
Duplicate with #15096, pac is not supported by fetch
