### ISSUE TITLE
环球科学 ; 《科学美国人》中文版

### ISSUE THREAD

**Issue by Whichbfj28** [DIYgod/RSSHub#15541]
### 类型

传统媒体

### 网站地址

https://www.huanqiukexue.com/

### 网站描述

环球科学 ; 《科学美国人》中文版

### 需要生成什么内容？

 图片跟文字

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://www.huanqiukexue.com/?feed=rss2

[RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar) is a browser extension that simplifies finding and subscribing RSS and RSSHub.
