### ISSUE TITLE
FetchError: [POST] "https://api.twitter.com/1.1/onboarding/task.json": 400 Bad Request

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#15556]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/Rikako_Aida
```

### 相关文档

https://docs.rsshub.app/routes/social-media#user-timeline-4

### 预期是什么？

用三月份的版本（没有记录具体commit）是可以正常抓取到twitter，但是那个版本微博抓取不到内容，更新之后微博恢复正常，但是twitter反而又没法使用了

### 实际发生了什么？

报错：

Looks like something went wrong

Helpful Information

Error Message:
FetchError: [POST] "https://api.twitter.com/1.1/onboarding/task.json": 400 Bad Request

Route: /twitter/user/:id/:routeParams?

Full Route: /twitter/user/Rikako_Aida

Node Version: v21.7.3

Git Hash: 8e7ec1f0

Git Date: Fri, 10 May 2024 17:08:08 GMT

### 部署

自建

### 额外信息

```shell
[31merror[39m: Error in /twitter/user/Rikako_Aida: FetchError: [POST] "https://api.twitter.com/1.1/onboarding/task.json": 400 Bad Request
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
<details><summary>Can't reproduce</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/6f81f8f4-1510-460b-8dfd-88f7aec0d959)
</details>
