### ISSUE TITLE
Reuters: 添加基于outboundfeed和wireapi的rss源

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#15554]
### 这是一个什么样的功能？

添加基于
https://www.reuters.com/arc/outboundfeeds/v4/mobile/section/world/?outputType=json
https://www.reuters.com/arc/outboundfeeds/v4/mobile/section/world/china/?outputType=json
的源。

### 这个功能可以解决什么问题？

增加更多获取方式。

### 额外描述

参考：
https://github.com/RSS-Bridge/rss-bridge/issues/3813
https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/ReutersBridge.php

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by dzx-dzx** [comment]
顺便解决这个：
https://github.com/DIYgod/RSSHub/issues/14034#issuecomment-1876737401

**Comment by pseudoyu** [comment]
added.
