### ISSUE TITLE
请求添加韭研公社文章rss

### ISSUE THREAD

**Issue by DudududududuSh** [DIYgod/RSSHub#15557]
### 这是一个什么样的功能？

将韭研公社文章转换为rss

### 这个功能可以解决什么问题？

获取最新财经资讯

### 额外描述

url：https://www.jiuyangongshe.com/study_publish

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by DudududududuSh** [comment]
抱歉，自建rsshub，一直没搞定，一直是NotFoundError: The route does not exist or has been deleted.，我不清楚具体是那步有问题，请求高人添加官方路由或者指点下

**Comment by TonyRL** [comment]
This is **indeed** a new RSS proposal. Please use the correct form instead.
