### ISSUE TITLE
知乎文章路由失效

### ISSUE THREAD

**Issue by sherlcok314159** [DIYgod/RSSHub#15566]
### Routes

```routes
/zhihu/posts/:usertype/:id
```

### Full routes

```fullroutes
/zhihu/posts/people/liustein
```

### Related documentation

https://docs.rsshub.app/routes/social-media#zhi-hu

### What is expected?

正常返回

### What is actually happening?

<img width="1168" alt="图片" src="https://github.com/DIYgod/RSSHub/assets/76043326/1d215f91-4f46-414e-96df-248ddc40c981">

### Deployment information

Self-hosted

### Additional info

```shell
No
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by domonnss** [comment]
同样问题 same issue

**Comment by Qeynos** [comment]
已更新最新版本尝试，同样的情况

**Comment by sherlcok314159** [comment]
@whtsky @Colin-XKL 如果你们两个都比较忙的话，希望其他社区相关的人可以帮忙进行修复~

**Comment by sherlcok314159** [comment]
最新的还是不行

<img width="1106" alt="image" src="https://github.com/DIYgod/RSSHub/assets/76043326/f317a9de-b84f-4dfc-83d7-afc57722c77d">
