### ISSUE TITLE
ehentai route wrong

### ISSUE THREAD

**Issue by domonnss** [DIYgod/RSSHub#15560]
### 路由地址

```routes
/ehentai/tag/:tag/:page?/:routeParams?
/ehentai/search/:params?/:page?/:routeParams?

/ehentai/favorites/:favcat?/:order?/:page?/:routeParams?
```

### 完整路由地址

```fullroutes
https://selfhost/ehentai/tag/language:chinese/0
https://selfhost/ehentai/tag/language:chinese/1
https://selfhost/ehentai/search/f_search=artist%3Amana%24/1

https://selfhost/ehentai/favorites/0/posted/1
```

### 相关文档

https://docs.rsshub.app/zh/routes/picture#e-hentai

### 预期是什么？

正常工作

### 实际发生了什么？

Looks like something went wrong

### tag与search
tag与search都是能够使用的,但是加上page参数就会出现错误,可能要更新page匹配算法
- http://selfhost/ehentai/tag/language:chinese 正常工作
- http://selfhost/ehentai/tag/language:chinese/0 报错
- http://selfhost/ehentai/tag/language:chinese/1 报错
- http://selfhost/ehentai/search/f_search=artist%3Amana%24 正常工作
- http://selfhost/ehentai/search/f_search=artist%3Amana%24/0 正常工作
- http://selfhost/ehentai/search/f_search=artist%3Amana%24/1 报错

### favorites
favorites不能正常使用
- http://selfhost/ehentai/favorites/0/posted 报错
- http://selfhost/ehentai/favorites/0/posted/0 报错
- http://selfhost/ehentai/favorites/0/posted/1 也报错
#14014 类似的错误,但他还能够抓取封面链接和画册地址

### 部署

docker-compose

### 部署相关信息

OS:ubuntu20.04,node:v20.9.0,Docker:25.0.0-beta.1

### 额外信息

```shell
none
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by yindaheng98** [comment]
https://github.com/DIYgod/RSSHub/issues/15492#issuecomment-2106551774

**Comment by TonyRL** [comment]
Duplicate of #15492
