### ISSUE TITLE
rsshub.app 知乎用户动态 “RSSHub 发生了一些意外”

### ISSUE THREAD

**Issue by eMUQI** [DIYgod/RSSHub#1559]
### 预期是什么？
![image](https://user-images.githubusercontent.com/32332228/52843744-f3873000-313d-11e9-8e9e-de5d210ccce8.png)
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/32332228/52843757-fc780180-313d-11e9-9485-9e6d2a9081a8.png)

**Comment by eMUQI** [comment]
本地部署的环境是可以的，但是rsshub.app上已经不行了

**Comment by LogicJake** [comment]
知乎反爬

**Comment by maboloshi** [comment]
知乎专栏也不行
