### ISSUE TITLE
希望增加《腾讯独家》，该内容分支包含腾讯大家等独占信息。

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#1560]
### 源站地址
https://new.qq.com/ch/ori/
### 需要生成什么内容？

- [ ] 将腾讯独家内容分离出文章内容，不要视频类

### 额外描述
我看rsshub有腾讯大家，其实它属于腾讯独家分类。腾讯独家好几个板块，包括大家，深网，谷雨等。我本来想用feed43临时用，但是需要正则表达式才能只分离出文章。希望有人能做出来，我确实搞不会rsshub 涉及的编程。

**Comment by HenryQW** [comment]
看着像一个聚合频道，还有新京报等其他外部媒体。并且对原文标题其实进行了修改，例如：
[学术世界是美好神话，翟天临才是生活的常态](http://dajia.qq.com/original/category/ldwx20190213.html)，内容无变动的情况下标题修改为了 [大家 | 翟天临事件对真正的学子是个暴击](https://new.qq.com/cmsn/20190213/20190213009319.html)。

并且貌似没有收录腾讯大家的所有文章，通过作者（腾讯原创）专栏链接给出的都是些[没营养的文章](https://new.qq.com/omn/author/orignal)。其他作者专栏链接较为正常，如[锵锵行天下](https://new.qq.com/omn/author/10210107)。

综上，个人认为不如分别抓取值得阅读的专栏子站点。


深网的 web 端已经停止更新很久了，建议订阅公众号 [瓦斯来源:腾讯深网](https://rsshub.app/wechat/wasi/5ba2744e244d4e646a0d618b)，[wemp来源:腾讯深网](https://rsshub.app/wechat/wemp/41311446-020a-4786-8050-ed72623ef530) 或 [雪球:腾讯深网](https://rsshub.app/xueqiu/user/9377502996)。


[谷雨](http://gy.qq.com/)可以单独开路由。
