### ISSUE TITLE
[RSS需求] 吾爱论坛的某些版块不支持rss，希望能支持

### ISSUE THREAD

**Issue by lolstudio** [DIYgod/RSSHub#1562]
### 源站地址
https://www.52pojie.cn/forum.php?mod=forumdisplay&fid=66&filter=author&orderby=dateline
### 需要生成什么内容？

支持查看最新的帖子

### 额外描述
吾爱论坛的大部分版块都有官方的rss，但部分版块没有，如【福利经验】区，希望能增加对这些版块的rss，如果有了这个rss需求后，其他论坛也是，有没有通用的方法解决此类问题，谢谢

**Comment by DIYgod** [comment]
提供的地址提示被删除，请提供一个可用地址

**Comment by lolstudio** [comment]
> 提供的地址提示被删除，请提供一个可用地址

刚试了下，如果未登录情况下打开这个版块链接会提示“抱歉，帖子涉嫌存在捆绑木马病毒、广告或其他违规行为，现已删除”，只有登录后才可以正常显示这个版块，这种rss还有办法做么？

**Comment by DIYgod** [comment]
@lolstudio 没办法
