### ISSUE TITLE
【小红书】用户笔记路由无 pubDate

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#15631]
### 路由地址

```routes
/xiaohongshu/user/:user_id/notes/fulltext
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/:user_id/notes/
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#unknown-3

### 预期是什么？

每一个 item 应该有 pubDate 属性

### 实际发生了什么？

item 无 pubDate 属性
![1716101606450_d](https://github.com/DIYgod/RSSHub/assets/8215230/29100ad4-ea76-45e3-957c-98e9f190b7f1)

### 部署

自建

### 额外信息

```shell
文档对于小红书路由的描述亦有问题
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #15232
