### ISSUE TITLE
Spotify TypeError

### ISSUE THREAD

**Issue by ttl97** [DIYgod/RSSHub#15648]
### Routes

```routes
/spotify/show/:id
```

### Full routes

```fullroutes
/spotify/show/:id
```

### Related documentation

https://docs.rsshub.app/zh/routes/multimedia#show

### What is expected?

should return correct rss content

### What is actually happening?

TypeError: got.post(...).json is not a function
![screenshot-20240521-183153](https://github.com/DIYgod/RSSHub/assets/30916718/94342908-9be2-4cc8-84e5-03b03af71fe6)

### Deployment information

Self-hosted

### Additional info

```shell
I noticed that the official method of sending http requests has been updated： https://docs.rsshub.app/joinus/new-rss/start-code#basic-code, maybe should change to utils/ofetch
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by caiohsramos** [comment]
The issue seem to be related to the `fakeGot` logic that doesn't implement the `.json()` method. It can be fixed using `.data` in the resolved Promise instead. This affects multiple routes, maybe the fix should be for all of them not just Spotify but we can fix it for now with something like:
```diff
-  const x = await got
-      .get(...)
-      .json();
+  const x = (
+      await got.get(...)
+  ).data;
```

**Comment by ttl97** [comment]
Yes, they deprecated got and used ofetch instead in this commit e5a9fd4. We might be able to use `ofetch` directly instead of `fakeGot`, and the updated document here https://docs.rsshub.app/joinus/new-rss/start-code#basic-code.
