### ISSUE TITLE
请求新增 番茄小说-更新提醒

### ISSUE THREAD

**Issue by rojer12** [DIYgod/RSSHub#15654]
### 这是一个什么样的功能？

用于订阅作者的更新，显示最新的5个章节名称及链接
举个栗子，https://fanqienovel.com/page/6621052928482348040
page/后面的数字应该是书本id，通过订阅这个id
获取  
1. 书名边上的最近更新和更新时间内容
2. 章节列表中最后5个章节的链接

### 这个功能可以解决什么问题？

用于订阅小说更新，主要是作者更新时间、频次不固定，实现链接直达

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
This is **indeed** a new RSS proposal. Please use the correct form instead.
