### ISSUE TITLE
vercel部署失败，提示Node.js Version: >=22

### ISSUE THREAD

**Issue by louyongjiu** [DIYgod/RSSHub#15681]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/deploy/

### 预期是什么？

使用vercel部署成功

### 实际发生了什么？

使用vercel部署失败，提示错误信息

### 部署

自建

### 部署相关信息

node:20

### 额外信息

```shell
Error: Found invalid Node.js Version: ">=22". Please set "engines": { "node": "20.x" } in your `package.json` file to use Node.js 20.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Vercel can't deploy the current version of RSSHub.
#14622
