### ISSUE TITLE
【建议】更新官网的 vuepress 版本

### ISSUE THREAD

**Issue by LeoSpark** [DIYgod/RSSHub#1568]
### 这是一个什么样的功能？
【建议】现在官网(https://docs.rsshub.app) 在 PC 查看文档，鼠标滚动很慢，体验很差，建议更新到最新版的[vuepress](https://github.com/vuejs/vuepress) 

![snipaste_2019-02-17_19-12-45](https://user-images.githubusercontent.com/16478463/52912194-fffbbc00-32e8-11e9-8739-3f55fe8d6bc0.png)

**Comment by ClarkeCheng** [comment]
原来不只我一个人卡

**Comment by DIYgod** [comment]
现在就是最新版，更新并不能解决问题，后续会拆分文档
