### ISSUE TITLE
主站多路由间歇性失效或更新不及时

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#15683]
### 路由地址

```routes
/thepaper/list/:id
/ifeng/feng/:id/:type
```

### 完整路由地址

```fullroutes
/thepaper/list/26878
/ifeng/feng/2583/doc
```

### 相关文档

https://docs.rsshub.app/routes/new-media#%E5%A4%A7%E9%A3%8E%E5%8F%B7

### 预期是什么？

正常返回

### 实际发生了什么？

经常出现`The operation is aborted`，即使能访问文章也非最新。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by DIYgod** [comment]
We made some adjustments, it should be much better now.
