### ISSUE TITLE
知乎路由Failed to extract `d_c0` from cookies

### ISSUE THREAD

**Issue by fenhaizi** [DIYgod/RSSHub#15710]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
zhihu/people/activities/247b240ccc5a586767395bbae0bdac30
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%94%A8%E6%88%B7%E5%8A%A8%E6%80%81-1

### 预期是什么？

获得rss信息，并用于freshrss（部署于同一物理机）

### 实际发生了什么？

Error: Failed to extract `d_c0` from cookies

### 部署

自建

### 部署相关信息

OS:Ubuntu Server Node:v21.7.3 Docker:24.0.5, build 24.0.5-0ubuntu1~22.04.1

### 额外信息

```shell
Helpful Information

Error Message:
Error: Failed to extract `d_c0` from cookies

Route: /zhihu/people/activities/:id

Full Route: /zhihu/people/activities/247b240ccc5a586767395bbae0bdac30

Node Version: v21.7.3

Git Hash: 85c40f9d

Git Date: Sat, 25 May 2024 11:58:23 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/247b240ccc5a586767395bbae0bdac30
```

**Comment by fenhaizi** [comment]
so, my IP are blacklisted?

but I can see the zhihu content (and corresponding user pages of almost any zhihu users, with a Windows 11 PC in the same LAN, without logging in, browser (ms edge) in privacy mode, with no logging in, no CAPTCHA occurred.

seems strange, but that's what I experienced

**Comment by fenhaizi** [comment]
it is (temporarily?) resolved and seems working smoothly when I replace the docker image diygod/rsshub with ghcr.io/diygod/rsshub.

not sure how long will it last
