### ISSUE TITLE
ft中文网显示 'NotFoundError: The route does not exist or has been deleted.'

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#15738]
### 路由地址

```routes
/ft/simplified/news
```

### 完整路由地址

```fullroutes
/ft/simplified/news
```

### 相关文档

https://docs.rsshub.app/routes/traditional-media#ft-%E4%B8%AD%E6%96%87%E7%BD%91

### 预期是什么？

正常输出rss

### 实际发生了什么？

显示 `NotFoundError: The route does not exist or has been deleted.`

### 部署

自建

### 额外信息

```shell
自建和rsshub.app都报此错误
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by RekiDunois** [comment]
现在文档里示例的路由也是报这个无法匹配，但是实际上这个路由应该没被删掉吧？

**Comment by TonyRL** [comment]
6e71b1a1019b416c17a2b3c2ad07d0294f35522b
