### ISSUE TITLE
【微信公众号】二十次幂来源的微信公众号内容，重复出现。

### ISSUE THREAD

**Issue by 9k001** [DIYgod/RSSHub#15753]
### 路由地址

```routes
/wechat/ershicimi/:id
```

### 完整路由地址

```fullroutes
/wechat/ershicimi/:id
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E5%85%AC%E4%BC%97%E5%8F%B7-%E4%BA%8C%E5%8D%81%E6%AC%A1%E5%B9%82%E6%9D%A5%E6%BA%90

### 预期是什么？

公众号内容输出

### 实际发生了什么？

抓取了两遍。其中:
1. 文章正文, 有标题;
2. 标题栏内容, 有标题.
而我通过ttrss进行调试，发现只抓取到一次，但是抓取结果呈现两遍(上述内容)
请问这个有没有解决办法

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by LLLLLFish** [comment]
哥们我也用这个二十次米的路由抓取公众号，你每天抓去到的推文都有图片吗，我抓每日豆瓣的只有第一篇有图片，后面三篇都是没有图片的

**Comment by 9k001** [comment]
> 哥们我也用这个二十次米的路由抓取公众号，你每天抓去到的推文都有图片吗，我抓每日豆瓣的只有第一篇有图片，后面三篇都是没有图片的

我观察一下，我抓取的 新潮沉思录 是有内容。
而其他的 比如 李建秋的世界，就只有标题，即标题配图中所包含的一句话。
其他有只有标题（大部分），有标题有内容（少部分）。
因为我最近以为我订阅的链接有问题，我重新订阅了。导致之前的文章全部没有了。
就近一两天的抓取结果来看，是上面我描述的情况。

**Comment by LLLLLFish** [comment]
> 我观察一下，我抓取的 新潮沉思录 是有内容。 而其他的 比如 李建秋的世界，就只有标题，即标题配图中所包含的一句话。 其他有只有标题（大部分），有标题有内容（少部分）。 因为我最近以为我订阅的链接有问题，我重新订阅了。导致之前的文章全部没有了。 就近一两天的抓取结果来看，是上面我描述的情况。

可以试一下在路由末尾添加?mode=fulltext 
我之前也有这个情况，加上之后就有内容了

**Comment by 9k001** [comment]
> > 我观察一下，我抓取的 新潮沉思录 是有内容。 而其他的 比如 李建秋的世界，就只有标题，即标题配图中所包含的一句话。 其他有只有标题（大部分），有标题有内容（少部分）。 因为我最近以为我订阅的链接有问题，我重新订阅了。导致之前的文章全部没有了。 就近一两天的抓取结果来看，是上面我描述的情况。
> 
> 可以试一下在路由末尾添加?mode=fulltext 我之前也有这个情况，加上之后就有内容了

这个方法能解决重复抓取和 只有标题，两个问题么？

**Comment by 9k001** [comment]
检查了一下数据库的数据
发现 微信公众号内容 出现了数据更新，标明了未读。即
ttrss_entries 表中 updated 与入库时间不同。可以看得出来ttrss认为该文章已经被更新。
