### ISSUE TITLE
Pixiv RSS is broken

### ISSUE THREAD

**Issue by Quintasan** [DIYgod/RSSHub#1575]
### Involved route

`/pixiv/ranking/:mode/:date?`

### What is expected?

Images should show up in my RSS feed

### What is actually happening?

I get no images. The problem is in https://github.com/DIYgod/RSSHub/blob/master/lib/routes/pixiv/bookmarks.js#L24. https://pixiv.cat
currently returns HTTP 106 Origin DNS error

**Comment by DIYgod** [comment]
It works here, please try it again

**Comment by Quintasan** [comment]
![image](https://user-images.githubusercontent.com/6539261/53000575-03965c80-3429-11e9-9749-f8ae2289ac7f.png)

But doesn't work here.

**Comment by DIYgod** [comment]
Sorry I can't help you, please concat the owner of pixiv.cat: https://pixiv.cat/about.html

**Comment by Quintasan** [comment]
@DIYgod You do realise I can't access that domain from where I'm located at?

**Comment by DIYgod** [comment]
@Quintasan Sorry, Email: contact@pixiv.cat

**Comment by Quintasan** [comment]
I'll give it a go then. Thanks.

**Comment by Quintasan** [comment]
```
<contact@pixiv.cat>: Host or domain name not found. Name service error for
    name=h.j0gn.ru type=AAAA: Host not found
```

There goes my mail

**Comment by DIYgod** [comment]
There is no other contact information in website, I can't help you more.

My DNS result for pixiv.cat is 209.141.32.94, you may try to add `209.141.32.94 pixiv.cat` to you local hosts

**Comment by jongcs** [comment]
@Quintasan 
I'm the owner of pixiv.cat.
My anycast GeoDNS server in europe was down. I've fixed it.
And also, The MX record for pixiv.cat was incorrect so your can't send me any email. I've fixed it too.

**Comment by DIYgod** [comment]
@jongcs Thanks for your wonderful website, it is really helpful.
