### ISSUE TITLE
X(Twitter) 用户时间线中的用户回复希望爬取被回复的内容

### ISSUE THREAD

**Issue by LAD021** [DIYgod/RSSHub#15751]
### 这是一个什么样的功能？

爬取被回复的全文，至少是上一条被回复内容

##### 不是这样
![image](https://github.com/DIYgod/RSSHub/assets/60390821/9f2aa071-1eda-4f59-af36-829a27443d3f)
![image](https://github.com/DIYgod/RSSHub/assets/60390821/488040fb-eb50-4fe6-98eb-573f3260cf91)

##### 而是这样
![image](https://github.com/DIYgod/RSSHub/assets/60390821/457ff8d3-c1da-43ce-9b78-217f7fd9d95e)

### 这个功能可以解决什么问题？

![image](https://github.com/DIYgod/RSSHub/assets/60390821/9f2aa071-1eda-4f59-af36-829a27443d3f)
在这样的回复推送中不需点开快速判断有没有阅读的必要。

针对一些大部分动态是给梗图回复一个"!"的名人如（[elonmusk](https://twitter.com/elonmusk)）

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by LAD021** [comment]
![image](https://github.com/DIYgod/RSSHub/assets/60390821/d728a96d-7bcb-4c4a-8f04-943946bae30b)
这种

**Comment by TonyRL** [comment]
Duplicate of #4077
