### ISSUE TITLE
大量路由不可用 TypeError: got(...).json is not a function

### ISSUE THREAD

**Issue by ouuan** [DIYgod/RSSHub#15763]
### 路由地址

```routes
/alistapart
/chaping/newsflash
/codeforces/contests
/codeforces/recent-actions/:minrating?
/dlnews/:category?
/gov/beijing/bphc/*
/grist
/luogu/user/blog/:name
/npm/package/:name{(@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*}
/twreporter/newest
```

### 完整路由地址

```fullroutes
/alistapart
/chaping/newsflash
/codeforces/contests
/codeforces/recent-actions
/dlnews
/gov/beijing/bphc/project
/grist
/luogu/user/blog/ouuan
/npm/package/rsshub
/twreporter/newest
```

### 相关文档

#14922

### 预期是什么？

正常返回结果

### 实际发生了什么？

`TypeError: got(...).json is not a function`

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

目前有若干单个路由的 issue 和修复（例如 #15648、#15207、#15107、#15134 ……），但仍有大量路由有这个问题，光是搜索 `got.*\.json\(` 就能搜到很多，可能还有别的。

可以考虑给 `fakeGot` 加上 `.json()` method，或者尽量全面地对各个路由都进行修复，而非报一个修一个，我上面列出的路由很可能还是不全。

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed in #15780
