### ISSUE TITLE
知乎相关路由未正确显示，未在文档中收录

### ISSUE THREAD

**Issue by chesha1** [DIYgod/RSSHub#15793]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/posts/people/:id
```

### 相关文档

https://docs.rsshub.app/routes/popular#%E7%9F%A5%E4%B9%8E

### 预期是什么？

查看相关代码，知乎某个用户的文章，回答等是有路由的，也能正常使用

1. RSSHub Radar 在某个用户首页（zhihu.com/people/:id），Radar 不能正常显示所有的路由，必须到专门的路径下，比如 zhihu.com/:usertype/:id/posts，Radar 才显示出路由。这与其他网站上的逻辑不同，比如对于 Github 仓库，在仓库根目录下就能看到 Issue，PR 等所有路由
2. 官网文档未显示所有和知乎有关的路由

### 实际发生了什么？

显示不全

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无报错
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
"Popular" by definition only shows popular routes, and showing every route doesn't fit the definition of popular. You need to visit the corresponding category to see all routes.
