### ISSUE TITLE
`/zhihu/xhu` 官方源乱码，自建源正常

### ISSUE THREAD

**Issue by JimenezLi** [DIYgod/RSSHub#15792]
### 路由地址

```routes
/zhihu/xhu/people/activities/:hexId
```

### 完整路由地址

```fullroutes
/zhihu/xhu/people/activities/246e6cf44e94cefbf4b959cb5042bc91
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#xhu-%E7%94%A8%E6%88%B7%E5%8A%A8%E6%80%81

### 预期是什么？

xhu 应该正常显示内容

### 实际发生了什么？

官方源存在乱码
![image](https://github.com/DIYgod/RSSHub/assets/75196426/ba5798d0-0fb6-453b-ab4a-723aabfe65fe)
自建源正常
![image](https://github.com/DIYgod/RSSHub/assets/75196426/77fbd2e0-bcef-4586-97e6-9a5a80e9378f)
由于无法在本地复现问题，且无报错，所以无法进行 debug

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无报错
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Can't repro.
<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/a7686f53-364e-42e0-988e-e25b464df8d2)
</details>
