### ISSUE TITLE
小宇宙的ssr现在只能有最近的15条了能否更新全部？

### ISSUE THREAD

**Issue by janeluyip** [DIYgod/RSSHub#15791]
### 这是一个什么样的功能？

使用的是
/xiaoyuzhou/podcast/:id
这个功能，但是发现只能抓取最近的15条信息，再早就没有了。

### 这个功能可以解决什么问题？

获取所有Episode的信息吗？

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
> 很多路由上限10条，无法增大。
> 
> 1. 消耗大量服务器资源。
> 2. 容易被反爬虫。
> 3. 绝大部分过时 feed 没有意义。

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416757360_

> RSS 是用来获取更新，增大条目无意义
> 
> 特殊需求请在相应模块里自行修改

_Originally posted by DIYgod in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416802920_

> rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

_Originally posted by yefoenix in https://github.com/DIYgod/RSSHub/issues/7291#issuecomment-809019525_

> You should not expect RSSHub to retrospectively retrieve every feed item.

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110077752_

> Do not expect it can provide you everything that happens since the stone age.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110091835_

> RSS 强调获取内容更新。若有“一次性获取全部条目”的需求，应设计针对该内容的爬虫。

_Originally posted by nczitzk in https://github.com/DIYgod/RSSHub/issues/9964#issuecomment-1157343694_
