### ISSUE TITLE
财联社feed显示不支持，validation failed

### ISSUE THREAD

**Issue by panshidong** [DIYgod/RSSHub#15796]
### 路由地址

```routes
https://rsshub.app/cls/hot
```

### 完整路由地址

```fullroutes
https://rsshub.app/cls/hot
```

### 相关文档

https://github.com/DIYgod/RSSHub/blob/master/lib/routes/cls/hot.ts

### 预期是什么？

之前一直可用

### 实际发生了什么？

outlook不识别，w3也fail
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frsshub.app%2Fcls%2Fhot

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
not a valid rss source
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Deyong888** [comment]
自部署的/cls/subject/1151现实不正常，官方实例/cls/subject/1151也是不正常的。
