### ISSUE TITLE
2048无法使用

### ISSUE THREAD

**Issue by wzzqq** [DIYgod/RSSHub#15811]
### 路由地址

```routes
/2048/:id?
```

### 完整路由地址

```fullroutes
/2048/15
```

### 相关文档

https://docs.rsshub.app/multimedia.html#_2048-he-ji-di

### 预期是什么？

正常使用

### 实际发生了什么？

Error Message:
TypeError: Invalid URL

### 部署

自建

### 部署相关信息

Node Version: v21.7.3 Git Hash: 5e2cbc1e  Git Date: Tue, 07 May 2024 16:11:58 GMT

### 额外信息

```shell
Error Message:
TypeError: Invalid URL
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Update your docker image.
