### ISSUE TITLE
豆瓣想读的书、在读的书、读过的书

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1581]
### 源站地址

想读的书：https://book.douban.com/people/62759792/wish

在读的书：https://book.douban.com/people/62759792/do

读过的书：https://book.douban.com/people/62759792/collect

### 需要生成什么内容？

- [ ] 想读的书
- [ ] 在读的书
- [ ] 读过的书

### 额外描述

订阅 DIYgod 想读的书，就可以第一时间知道该给 DIYgod 送什么书了

**Comment by HenryQW** [comment]
@DIYgod 拉稀， 出一个亚马逊 wishlist 吧

**Comment by yefoenix** [comment]
@DIYgod 或者可以合并到 豆瓣广播那个 issue，然后用rsshub的过滤器

**Comment by LogicJake** [comment]
@DIYgod https://www.douban.com/feed/people/62759792/interests
