### ISSUE TITLE
【不太灵影视】

### ISSUE THREAD

**Issue by palonnn** [DIYgod/RSSHub#15879]
### 类型

音视频

### 网站地址

https://www.6bt0.com/

### 网站描述

不太灵影视: 这是一个公益无广告的影视下载站，更新资源很全的BT站。最新电影，最新电视剧，最新动画，并且区分1080P和2160P资源。

### 需要生成什么内容？

最新资源列表的最新电视剧和最新电影。

### 额外描述

非常感谢！

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by hualiong** [comment]
试了一下，这网站好像反爬，不好搞。还是等大佬来试试吧😥

**Comment by hualiong** [comment]
#15946，应该可以关了吧 @TonyRL

**Comment by TonyRL** [comment]
Closed in #15946

**Comment by HuntJhone** [comment]
现在必须开VIP才能下载了吗

**Comment by palonnn** [comment]
> 现在必须开VIP才能下载了吗

不知道啊，好久没用了，玩pt了

**Comment by HuntJhone** [comment]
> > 现在必须开VIP才能下载了吗
> 
> 不知道啊，好久没用了，玩pt了

PT怎么玩,带带吧大佬

**Comment by palonnn** [comment]
> > > 现在必须开VIP才能下载了吗
> > 
> > 不知道啊，好久没用了，玩pt了
> 
> PT怎么玩,带带吧大佬
直接捐几个大站玩就行，或者找人求药，大站难求

**Comment by palonnn** [comment]
@HuntJhone 直接捐几个大站玩就行，或者找人求药，大站难求，可以先玩小站搞好数据

**Comment by HuntJhone** [comment]
> [@HuntJhone](https://github.com/HuntJhone) 直接捐几个大站玩就行，或者找人求药，大站难求，可以先玩小站搞好数据

@palonnn 大佬,有什么推荐的吗

**Comment by palonnn** [comment]
@HuntJhone 没什么推荐的，有钱就捐入大站，想先小站练手就去论坛找，很多人发

**Comment by HuntJhone** [comment]
> [@HuntJhone](https://github.com/HuntJhone) 没什么推荐的，有钱就捐入大站，想先小站练手就去论坛找，很多人发

@palonnn 好的大佬

**Comment by iakacer** [comment]
> > [@HuntJhone](https://github.com/HuntJhone) 没什么推荐的，有钱就捐入大站，想先小站练手就去论坛找，很多人发
> 
> [@palonnn](https://github.com/palonnn) 好的大佬

kpkuang看片狂人可以平替不太灵了，或者试试ext.to吧，国内资源少一些

**Comment by SylenY** [comment]
不太灵的 vip 屏蔽是纯前端的，在浏览器里把模糊删了就行，uBlock Lite 代码：
butailing.com##div.vip-gate-overlay
butailing.com##div[style*="filter: blur(5px)"]:style(filter: none !important; pointer-events: auto !important;)

**Comment by HuntJhone** [comment]
> 不太灵的 vip 屏蔽是纯前端的，在浏览器里把模糊删了就行，uBlock Lite 代码： butailing.com##div.vip-gate-overlay butailing.com##div[style*="filter: blur(5px)"]:style(filter: none !important; pointer-events: auto !important;)

佬,具体怎么操作啊,没太理解呢

**Comment by SylenY** [comment]
手动法：进网页检查器，选择元素，选择 vip 专属内容那个框，给它删掉，然后选中那一坨模糊的，上下找一下，有一个 div 里面有 style="filter: blur(5px); pointer-events: none; user-select: none;"，双击这个 style，把 "" 里面的全删掉，就好了
自动法：安装 uBlock Lite，在配置文件里面加上这个: 
web5.mukaku.com##div.vip-gate-overlay
web5.mukaku.com##div[style*="filter: blur(5px)"]:style(filter: none !important; pointer-events: auto !important;)

**Comment by HuntJhone** [comment]
> 手动法：进网页检查器，选择元素，选择 vip 专属内容那个框，给它删掉，然后选中那一坨模糊的，上下找一下，有一个 div 里面有 style="filter: blur(5px); pointer-events: none; user-select: none;"，双击这个 style，把 "" 里面的全删掉，就好了 自动法：安装 uBlock Lite，在配置文件里面加上这个: web5.mukaku.com##div.vip-gate-overlay web5.mukaku.com##div[style*="filter: blur(5px)"]:style(filter: none !important; pointer-events: auto !important;)

感谢大佬,我试试

**Comment by wabarabb** [comment]
> 手动法：进网页检查器，选择元素，选择 vip 专属内容那个框，给它删掉，然后选中那一坨模糊的，上下找一下，有一个 div 里面有 style="filter: blur(5px); pointer-events: none; user-select: none;"，双击这个 style，把 "" 里面的全删掉，就好了 自动法：安装 uBlock Lite，在配置文件里面加上这个: web5.mukaku.com##div.vip-gate-overlay web5.mukaku.com##div[style*="filter: blur(5px)"]:style(filter: none !important; pointer-events: auto !important;)

非常有用!

**Comment by SylenY** [comment]
之前的那个现在好像用不了了。但是我发现了一个脚本解决这个问题：https://greasyfork.org/zh-CN/scripts/540766-不太灵vip

**Comment by woshuaime** [comment]
为啥现在启动脚本，点击链接却仍然没法跳过vip登录和看到下载资源。
