### ISSUE TITLE
豆瓣豆列rss无法抓取类型为广播的条目

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1589]
### 路由地址
https://rsshub.app/douban/doulist/110405276
（源网页地址：https://www.douban.com/doulist/110405276/）
### 预期是什么？
豆瓣广播条目正常显示
### 实际发生了什么？
条目信息不正常，title、description、guid、link皆为空

### 额外信息（日志、报错等）
![qq 20190220114218](https://user-images.githubusercontent.com/8215230/53064996-d1f2c380-3504-11e9-9072-1efd195c63ae.png)

**Comment by CoderTonyChan** [comment]
路由地址

https://rsshub.app/douban/doulist/1641439
（源网页地址：https://rsshub.app/douban/doulist/1641439）

预期是什么？

豆瓣广播条目正常显示

实际发生了什么？

条目信息不正常，title、description、guid、link皆为空

豆列的信息比较杂 目前好似只实现了 豆瓣广播/豆瓣日记 

还有其他很多类型 比如 豆瓣读书评论/豆瓣小组/豆瓣电影/豆瓣读书/豆瓣 等等 

看官方实例好似 遇到豆瓣读书评论 后面的也没有输出了 

额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/16996753/55524026-42713080-56be-11e9-9cdd-18e9482c4939.png)

**Comment by CoderTonyChan** [comment]
我目前知道的类型 欢迎添加 
 https://www.douban.com/doulist/112825696/
