### ISSUE TITLE
【知乎专栏】知乎专栏抓取出现中文乱码

### ISSUE THREAD

**Issue by 9k001** [DIYgod/RSSHub#15913]
### 路由地址

```routes
/zhihu/zhuanlan/:id
```

### 完整路由地址

```fullroutes
/zhihu/zhuanlan/:id
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E4%B8%93%E6%A0%8F

### 预期是什么？

中文内容

### 实际发生了什么？

中文乱码

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
I don't think this is fixed: https://rsshub.app/zhihu/zhuanlan/crossborder
