### ISSUE TITLE
北极星风电网

### ISSUE THREAD

**Issue by fucao** [DIYgod/RSSHub#15924]
### Category

Social Media

### Website URL

https://fd.bjx.com.cn/

### Website description

国内专业的风电行业信息网站

### What content should be included?

要闻

政策

数据

市场

企业

招标

技术

报道

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by hualiong** [comment]
Existing route #9542
