### ISSUE TITLE
【北京价格】FetchError: [GET] "http://www.beijingprice.cn/jgzx/tzgg/": <no response> fetch failed

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#15923]
### 路由地址

```routes
/beijingprice/:category{.+}?
```

### 完整路由地址

```fullroutes
https://rsshub.app/beijingprice/jgzx/tzgg
```

### 相关文档

https://docs.rsshub.app/routes/government#%E5%8C%97%E4%BA%AC%E4%BB%B7%E6%A0%BC

### 预期是什么？

正常工作

### 实际发生了什么？

报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "http://www.beijingprice.cn/jgzx/tzgg/": <no response> fetch failed

Route: /beijingprice/:category{.+}?

Full Route: /beijingprice/jgzx/tzgg

Node Version: v22.3.0

Git Hash: 943ec2e7


感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ueiu** [comment]
是用 rsshub.app 访问的吗？好像被反爬了，是用本机访问路由或者用了一个别人搭的 rsshub 服务器都是能正常抓取的，考虑自建吧
本地访问：
![image](https://github.com/DIYgod/RSSHub/assets/39592269/aa54d8a8-13ae-4e27-bb8b-74cd41ae2082)
自建服务器访问：
![image](https://github.com/DIYgod/RSSHub/assets/39592269/5ede68ef-920a-4423-bd18-8ade908f3e46)

**Comment by KwToPA** [comment]
> 是用 rsshub.app 访问的吗？好像被反爬了，是用本机访问路由或者用了一个别人搭的 rsshub 服务器都是能正常抓取的，考虑自建吧 本地访问： ![image](https://private-user-images.githubusercontent.com/39592269/341520311-aa54d8a8-13ae-4e27-bb8b-74cd41ae2082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDYwMDYsIm5iZiI6MTcxODk0NTcwNiwicGF0aCI6Ii8zOTU5MjI2OS8zNDE1MjAzMTEtYWE1NGQ4YTgtMTNhZS00ZTI3LWJiOGItNzRjZDQxYWUyMDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA0NTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Mzc0NWM4OGU0YTVkNDI2NTliZmUzNGY3ZDBmZDBlNzQzM2JmNDFmNjA2ZjcxMTcyZjAzY2NkM2E2MDJjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tLSt9NUgbxgkfhqFKv8cPqYs2rU06MXY8ISEQJMzCos) 自建服务器访问： ![image](https://private-user-images.githubusercontent.com/39592269/341521760-5ede68ef-920a-4423-bd18-8ade908f3e46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDYwMDYsIm5iZiI6MTcxODk0NTcwNiwicGF0aCI6Ii8zOTU5MjI2OS8zNDE1MjE3NjAtNWVkZTY4ZWYtOTIwYS00NDIzLWJkMTgtOGFkZTkwOGYzZTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA0NTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZmJmZTFlYTc2ZGJlMWViZWI3NTI4NzEwMzU3YzY3MGI4OGMyOTRmNmI4MWU1NDZmYzBhZmNjZTRhZmNjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DkK4dJqJjrjSc_QJjmcZTg2RWbKasEqrICvY6BhFSv8)

看起来不是反爬，估计是北京发改委屏蔽了境外的IP
