### ISSUE TITLE
CNbeta route handler not configured

### ISSUE THREAD

**Issue by Maxinsomnia** [DIYgod/RSSHub#15939]
### 路由地址

```routes
/cnbeta/category/:id
```

### 完整路由地址

```fullroutes
/cnbeta/category/funny
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#cnbeta-com

### 预期是什么？

cnbeta funny channel subscribtion

### 实际发生了什么？

failed and error msg

### 部署

自建

### 部署相关信息

OS: Mac Apple Chip, Node: v22.3.0, Docker: V4.25.2

### 额外信息

```shell
no
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
It works on both official instance and self-host instance. Try again.
