### ISSUE TITLE
「知乎问题」抓取出现乱码

### ISSUE THREAD

**Issue by AntoineChn** [DIYgod/RSSHub#15944]
### 路由地址

```routes
/zhihu/question/:questionId
```

### 完整路由地址

```fullroutes
/zhihu/question/:questionId/:sortBy?
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E9%97%AE%E9%A2%98

### 预期是什么？

抓取结果无乱码

### 实际发生了什么？

抓取结果包含大量乱码

### 部署

自建

### 部署相关信息

Synology Linux 4.4.302+, Node: v20.9.0, Docker version 20.10.23

### 额外信息

```shell
Git Hash:95a40080
Git Date:Wed, 19 Jun 2024 15:00:17 GMT
Cache Duration:300s
Request Amount:33
Request Frequency:1.360 times/minute
Cache Hit Ratio:15.15%
ETag Matched Ratio:9.09%
Health:93.94%
Uptime:0.40 hour(s)
Hot Routes:21 /zhihu/question/:questionId/:sortBy?
3 /zhihu/people/activities/:id
2 /zhihu/collection/:id/:getAll?
1 /
1 /bilibili/user/dynamic/:uid/:routeParams?
1 /douban/people/:userid/status/:routeParams?
Hot Paths:5 /zhihu/question/59895982
3 /zhihu/question/658640368
3 /zhihu/question/656800983
2 /
2 /zhihu/question/657741887
2 /zhihu/question/657529597
2 /zhihu/collection/946001022
2 /zhihu/question/658337628
2 /zhihu/question/659077330
2 /zhihu/people/activities/jin-zhen-80-25
2 /favicon.ico
1 /bilibili/user/dynamic/208130286
1 /logo.png
1 /zhihu/question/659231439
1 /douban/people/271800820/status
1 /zhihu/people/activities/yi-zhi-zhu-ding-lou
1 /zhihu/question/652914428
Hot Error Routes:2 /zhihu/question/:questionId/:sortBy?
Hot Error Paths:2 /zhihu/question/657741887
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AntoineChn** [comment]
类似的乱码问题在 https://github.com/DIYgod/RSSHub/issues/15913

**Comment by eli-yip** [comment]
我也遇到了相同的问题

**Comment by eli-yip** [comment]
发现问题如下，使用知乎`/api/v4`API进行请求的时候，如果缺少：`__zse_ck`和`z_c0` `cookie`，则会返回形似中文的中文。

这两个参数在请求知乎时候并不会返回，应该是js生成的。实测并不是每次都更新的。

希望有大佬能找出破解的办法。

**Comment by 9k001** [comment]
> 乱码的原因是缺少`__zse_ck`这个cookie，获取的方式很简单，请求任意人的主页（不需要cookie和加密），在返回的`html`中搜索`__zse_ck`即可。
> 
> rsshub代码中包含了这部分逻辑：
> 
> https://github.com/DIYgod/RSSHub/blob/d99b18bd8ce7f948c4726cd29e347ca2621ebf68/lib/routes/zhihu/utils.ts#L67

感谢研究，，看起来 需要改代码了。。等修复把。

**Comment by monkey-hjy** [comment]
请问现在最新版的zse_ck应该怎么生成呀？好像都改成代码生成的了

**Comment by WindowsXp-Beta** [comment]
还有乱码这个问题，但我看 #16137 似乎已经修了？

**Comment by 9k001** [comment]
> 还有乱码这个问题，但我看 #16137 似乎已经修了？

看样子还在，最近发现又不行了
