### ISSUE TITLE
深圳市医疗器械行业协会

### ISSUE THREAD

**Issue by 520iloveu** [DIYgod/RSSHub#15953]
### Category

Uncategorized

### Website URL

https://www.samd.org.cn/home/newsList?typeId=441

### Website description

深圳市医疗器械行业协会成立于2003年，是由深圳及相关地区从事医疗器械研发、生产、经营、使用、维护、检测及教学的企业或机构，自愿联合组成的行业性非营利性社会团体。协会现有超700家会员，现任会长单位为深圳迈瑞科技有限公司，日常办事机构为秘书处，设行业服务部、展览服务部、技术服务部、信息咨询部、培训部等职能部门。

### What content should be included?

政策法规

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by 520iloveu** [comment]
@TonyRL 谢谢。可是很奇怪，还是无法订阅。。。

**Comment by hualiong** [comment]
> @TonyRL 谢谢。可是很奇怪，还是无法订阅。。。

会不会是路由写错了？
