### ISSUE TITLE
WeGene 微解读 和 最近更新

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#1601]
### 源站地址

微解读：https://www.wegene.com/crowdsourcing/

最近更新（接口）：https://www.wegene.com/contents/ajax/update/get_list/?htmlspecialchars_decode=true&page=1

### 需要生成什么内容？

- [ ] 最新的微解读
- [ ] 最近更新

**Comment by LogicJake** [comment]
最近更新的源地址是啥
