### ISSUE TITLE
BBC  403 Forbidden Edge 5

### ISSUE THREAD

**Issue by Yumega** [DIYgod/RSSHub#16032]
### 路由地址

```routes
/bbc/:site?/:channel?
```

### 完整路由地址

```fullroutes
/bbc/world-asia
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

bbc

### 实际发生了什么？

nothing

### 部署

自建

### 额外信息

```shell
stdout: [32minfo[39m: <-- GET /bbc/world-asia
stdout: [31merror[39m: Error in /bbc/world-asia: FetchError: [GET] "https://www.bbc.co.uk/news/articles/c25ln18zlvno": 403 Forbidden Edge 5
stdout: [32minfo[39m: --> GET /bbc/world-asia [31m503[0m 3s
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Candinya** [comment]
可以在您部署的服务器上使用 curl 等工具手动发起请求尝试一下吗，如果是服务器的出口 IP 被拦截那么不属于软件能解决的问题
