### ISSUE TITLE
抓取路由提示redis无法持久化到硬盘

### ISSUE THREAD

**Issue by JamYiz** [DIYgod/RSSHub#16036]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/routes

### 预期是什么？

正常抓取

### 实际发生了什么？

所有路由失效，无法抓取。重启后恢复一小段时间继续报错
![图片](https://github.com/DIYgod/RSSHub/assets/44351690/291629c5-f2ea-40c9-9098-5149baf5ef8b)

### 部署

自建

### 部署相关信息

Node Version: v22.3.0

### 额外信息

```shell
报错：Error Message:
ReplyError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lucky13820** [comment]
你后来怎么修好的这个？就重启自己就好了吗？

**Comment by JamYiz** [comment]
> 你后来怎么修好的这个？就重启自己就好了吗？

好像最后发现自己的服务器硬盘满了😂

**Comment by lucky13820** [comment]
哈哈，我好像也是，我弄了个 cron job，定期清理一下 docker
