### ISSUE TITLE
 【政务消息】https://docs.rsshub.app/  页面样式出错

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#16041]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/routes/government#%E5%9B%BD%E5%AE%B6%E7%BB%9F%E8%AE%A1%E5%B1%80-%E9%80%9A%E7%94%A8

### 预期是什么？

正常

### 实际发生了什么？

TIP栏的范围扩大

![image](https://github.com/DIYgod/RSSHub/assets/16444568/cf9ffe24-31fc-4189-bb1f-4da30f947038)

![image](https://github.com/DIYgod/RSSHub/assets/16444568/1a0f427d-a755-4543-8c52-c81e8586d2c6)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
[希望能够给出](https://docs.rsshub.app/zh/routes/government#%E4%B8%8A%E6%B5%B7%E5%B8%82%E5%8F%91%E5%B1%95%E5%92%8C%E6%94%B9%E9%9D%A9%E5%A7%94%E5%91%98%E4%BC%9A-1)

这两个重复了

**Comment by TonyRL** [comment]
Closed in https://github.com/DIYgod/RSSHub/commit/c1071356f6b226e207c1813293efeea3e9f66409
