### ISSUE TITLE
#15563的问题未完全修复

### ISSUE THREAD

**Issue by agczsz** [DIYgod/RSSHub#16076]
### 路由地址

```routes
/newrank/wechat/:wxid
```

### 完整路由地址

```fullroutes
/newrank/wechat/U9baoku
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E6%96%B0%E6%A6%9C

### 预期是什么？

正确返回RSS

### 实际发生了什么？
![image](https://github.com/DIYgod/RSSHub/assets/121206519/3ec88bc4-fb59-4f33-aad6-a7c654e34418)

WeChatMpError: wechat-mp: deleted by author: 该内容已被发布者删除 微信公众平台运营中心 ： ，...: https://mp.weixin.qq.com/s?__biz=MzkwNjUxNjk4MQ==&mid=2247534826&idx=1&sn=cbf19fe213125d788415620bf4ac0398

Route: /newrank/wechat/:wxid

Full Route: /newrank/wechat/U9baoku

Node Version: v22.4.0

Git Hash: d8ae8d8d

Git Date: Wed, 03 Jul 2024 12:02:04 GMT

### 部署

自建

### 额外信息

```shell
参考#15563

对于有删除文章的公众号，该路由无法正确工作。无删除的公众号可以正确工作
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by agczsz** [comment]
不是我这路由从wiki复制的：/newrank/wechat/:wxid，怎么显示“如果所有路由都无法匹配，issue 将会被自动关闭。”？？

**Comment by TonyRL** [comment]
Duplicate of #15874
