### ISSUE TITLE
sealos 中的 rsshub 无法正常使用

### ISSUE THREAD

**Issue by linchen1987** [DIYgod/RSSHub#16079]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
-
```

### 相关文档

-

### 预期是什么？

在 seslos 部署后访问节点，像访问 https://rsshub.app/ 一样

### 实际发生了什么？

在 seslos 部署后访问节点，页面中看到 no healthy upstream , 应用状态一直是 waiting 
<img width="1224" alt="image" src="https://github.com/DIYgod/RSSHub/assets/11010275/c8938d27-302d-40dd-8b22-a864cdcb9080">

### 部署

自建

### 部署相关信息

sealos ( https://template.cloud.sealos.io/deploy?templateName=rsshub )

### 额外信息

```shell
-
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Could you provide the log output as well?

**Comment by bxy4543** [comment]
Maybe you should submit an issue to sealos. The reason is that the default resource size of sealos cloud deployment is too small, which leads to OOM. Close this issue and I will adjust the default size to solve the problem.
