### ISSUE TITLE
Twitter User Timeline  got 503，<no response> fetch failed

### ISSUE THREAD

**Issue by PanosKwork** [DIYgod/RSSHub#16083]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/RSSHub
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#user-timeline-4

### 预期是什么？

用户Timeline路由正常

### 实际发生了什么？

用户Timeline路由错误，返回 `503，<no response> fetch failed`
```
FetchError: [GET] "https://x.com/i/api/graphql/k5XapwcSikNsEsILW5FvgA/UserByScreenName?features={"hidden_profile_likes_enabled":true,"hidden_profile_subscriptions_enabled":true,"responsive_web_graphql_exclude_directive_enabled":true,"verified_phone_label_enabled":false,"subscriptions_verification_info_is_identity_verified_enabled":true,"subscriptions_verification_info_verified_since_enabled":true,"highlights_tweets_tab_ui_enabled":true,"responsive_web_twitter_article_notes_tab_enabled":true,"creator_subscriptions_tweet_preview_api_enabled":true,"responsive_web_graphql_skip_user_profile_image_extensions_enabled":false,"responsive_web_graphql_timeline_navigation_enabled":true}&fieldToggles={"withAuxiliaryUserLabels":false}&variables={"screen_name":"RSSHub","withSafetyModeUserFields":true}": <no response> fetch failed
```
![image](https://github.com/DIYgod/RSSHub/assets/32182514/774d9ec4-5e8a-4806-9635-b8eaaaba6dea)

### 部署

自建

### 部署相关信息

OS:debian 5.10.0-23-amd64; NODE:v22.3.0; DOCKER: 27.0.1

### 额外信息

```shell
none
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Could you confirm that the instance can visit Twitter without any issues?

**Comment by PanosKwork** [comment]
> Could you confirm that the instance can visit Twitter without any issues?

Thanks a lot, it is indeed an proxy issue.
