### ISSUE TITLE
纽约时报添加英语和中英对照版本

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [DIYgod/RSSHub#1609]
### 源站地址
https://cn.nytimes.com/

### 需要生成什么内容？
大部分工作已于 #1100 中完成，希望能在此基础上添加以下语言选项：

- 英语
- 中英对照

### 构想 API
比如对于全球纵览，可以有

- https://rsshub.app/nytimes?language=cn
- https://rsshub.app/nytimes?language=en
- https://rsshub.app/nytimes?language=both

**Comment by LogicJake** [comment]
某一篇中文文章有对应的英文版吗

**Comment by CaptainYukinoshitaHachiman** [comment]
> 某一篇中文文章有对应的英文版吗

一般都有，因为纽约时报中文网的绝大部分文章都是纽约时报英文官网翻译过来的，只有少数是中文原创
<img width="1285" alt="cleanshot 2019-02-23 at 13 07 45 2x" src="https://user-images.githubusercontent.com/25654046/53281964-061bed80-376c-11e9-98f4-88f669211ec5.png">
