### ISSUE TITLE
Twitter/X status page

### ISSUE THREAD

**Issue by write3371** [DIYgod/RSSHub#16139]
### Category

Social Media

### Website URL

https://x.com/xxxx/status/yyyy

### Website description

Twitter/X status page yyyy of user xxxx

### What content should be included?

first thread and its replies, formatted like normal user timeline

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
https://docs.rsshub.app/routes/social-media#tweet-details
