### ISSUE TITLE
知乎：Failed to extract `d_c0` from cookies

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#16133]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/ning-nan-zuo-hou
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E7%9F%A5%E4%B9%8E

### 预期是什么？

正常获取

### 实际发生了什么？

获取失效，报错如上

### 部署

自建

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed in #16137

**Comment by dzx-dzx** [comment]
自动获取`__zse_ck`等也许还是可能的：
https://www.52pojie.cn/thread-1968832-1-1.html
https://www.52pojie.cn/thread-1970885-1-1.html
