### ISSUE TITLE
Twitter/X status doesn't work if the user name startwith _

### ISSUE THREAD

**Issue by write3371** [DIYgod/RSSHub#16145]
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/_abcd
```

### Related documentation

https://docs.rsshub.app/routes/social-media#x-twitter

### What is expected?

return correct response

### What is actually happening?

 this route is empty, please check the original site 

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
twitter/x
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Can't repro.

<details><summary>Screenshot</summary>

![image](https://github.com/DIYgod/RSSHub/assets/11386903/4f916726-09f7-4bbf-bb9e-35709178f1a5)
</details>
