### ISSUE TITLE
Support User timeline of Misskey like Mastodon

### ISSUE THREAD

**Issue by write3371** [DIYgod/RSSHub#16159]
### What feature is it?

Support User timeline of Misskey like Mastodon

### What problem does this feature solve?

follow a specific user instead of the whole instance

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
This is **indeed** a new RSS proposal. Please use the correct form instead.
