### ISSUE TITLE
FashionNetwork中国 路由出错

### ISSUE THREAD

**Issue by MrLIUXY** [DIYgod/RSSHub#16162]
### 路由地址

```routes
/fashionnetwork/cn/lists/:id?
```

### 完整路由地址

```fullroutes
/fashionnetwork/cn/lists/0
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#fashionnetwork-%E4%B8%AD%E5%9B%BD

### 预期是什么？

正常返回RSS

### 实际发生了什么？

所有路由均报错
![screen](https://github.com/user-attachments/assets/e6d50d28-ee67-4ea5-a33a-4d999d971f14)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://fashionnetwork.cn/lists/0": 416 Requested Range Not Satisfiable
Route: /fashionnetwork/cn/lists/:id?
Full Route: /fashionnetwork/cn/lists/0
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Can you visit `https://fashionnetwork.cn/lists/0` ? RSS is only available when the website works.
