### ISSUE TITLE
最新`diygod/rsshub:chromium-bundled`镜像无法正常抓取`/twitter/home`

### ISSUE THREAD

**Issue by aaro-n** [DIYgod/RSSHub#16163]
### 路由地址

```routes
/twitter/home/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/home
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#home-timeline

### 预期是什么？

最新版`diygod/rsshub:chromium-bundled`镜像可以正常抓取/twitter/home

### 实际发生了什么？

镜像`diygod/rsshub:chromium-bundled-2024-07-13`,`diygod/rsshub:chromium-bundled-2024-07-14`,`diygod/rsshub:chromium-bundled-2024-07-15`都无法正常抓取/twitter/home

镜像`diygod/rsshub:chromium-bundled-2024-07-10`,`diygod/rsshub:chromium-bundled-2024-07-11`,`diygod/rsshub:chromium-bundled-2024-07-12`可以正常抓取/twitter/home

### 部署

自建

### 部署相关信息

docker镜像最新版

### 额外信息

```shell
最新镜像日志：

Helpful Information

Error Message:
TypeError: api.getHomeTimeline is not a function

Route: /twitter/home/:routeParams?

Full Route: /twitter/home

Node Version: v22.4.1

Git Hash: e0519171

Git Date: Sun, 14 Jul 2024 15:28:23 GMT
```
```


### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
I assume you've set `TWITTER_COOKIE` which has been removed in 1db30b3ad1f8ff79da986f4c6c792b4dbc286480. You need to set `TWITTER_AUTH_TOKEN` instead, which its value can also be found from the cookie string.

**Comment by aaro-n** [comment]
不要回复，现在已经可以正常使用路由`/twitter/home/:routeParams?`
# 环境变量变更如下：
`TWITTER_COOKIE=auth_token=1234567; ct0=aaaaaaaaaaaaaaaaaaaaaaa`
改为
`TWITTER_AUTH_TOKEN=1234567`
