### ISSUE TITLE
Pull Requests Server Error 500

### ISSUE THREAD

**Issue by nsnans** [DIYgod/RSSHub#16177]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

无

### 预期是什么？

我添加了一个pr，作用是指定掘金用户文章展示数量。
但出现Pull Requests Server Error 500，我想询问下怎么解决去合并这个pr。
因为其他议题都和这个无关，只能提到这里

### 实际发生了什么？

https://github.com/DIYgod/RSSHub/pull/16165

Pull Requests Server Error 500

![image](https://github.com/user-attachments/assets/72264ec0-9693-47b4-a9bc-e306c5a4388a)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by DIYgod** [comment]
This issue is not related to RSSHub, and we cannot resolve it. Please submit a ticket to GitHub at: https://support.github.com/request

**Comment by DIYgod** [comment]
I don't know, and I can't open it either.

**Comment by DIYgod** [comment]
But as a side note, you shouldn't specify the display quantity, RSS is just for getting updates.

**Comment by DIYgod** [comment]
You should only modify the fetch quantity when the update frequency is so fast that it is impossible to get all updates in one RSS refresh cycle.

**Comment by Candinya** [comment]
或许可以试试调用 GitHub API 拉取 PR 信息 / 关闭能不能行？

**Comment by TonyRL** [comment]
I can't view that PR either, even in incognito mode. I can close it from PR list though.
