### ISSUE TITLE
X (Twitter) 路由缺少 TWITTER_AUTH_TOKEN 配置的文档说明

### ISSUE THREAD

**Issue by CaoMeiYouRen** [DIYgod/RSSHub#16184]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/twitter/home
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#x-twitter

### 预期是什么？

应当存在 TWITTER_AUTH_TOKEN 配置项的文档说明。

### 实际发生了什么？

目前底层配置从 TWITTER_COOKIE 切换到 TWITTER_AUTH_TOKEN 后，没有修改相应的文档，无法了解如何配置 TWITTER_AUTH_TOKEN 

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
null
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by aaro-n** [comment]
最新的`diygod/rsshub:chromium-bundled`镜像即使将环境变量`TWITTER_COOKIE`改为`TWITTER_AUTH_TOKEN`，路由`/twitter/home/:routeParams?`也是不可用的，当当前拉取请求合并到主线后，问题未修复，我将再次提交问题。
相关问题：#16163
# 介绍
我是将`diygod/rsshub:chromium-bundled`部署在fly.io上，TWITTER_COOKIE获取方式为https://github.com/DIYgod/RSSHub/discussions/14956#discussioncomment-8947667 ，TWITTER_COOKIE在`diygod/rsshub:chromium-bundled-2024-07-12`可用,使用最新镜像，将`TWITTER_COOKIE`改为`TWITTER_AUTH_TOKEN`后，路由`/twitter/home/:routeParams?`不可用。
# 环境变量
`TWITTER_COOKIE`=`auth_token=zzz; ct0=vvvv` 改为
`TWITTER_AUTH_TOKEN`=`auth_token=zzz; ct0=vvvv`（不可用）和
`TWITTER_AUTH_TOKEN`=`auth_token=zzz`（不可用）
# 最新镜像的错误日志
```
Helpful Information

Error Message:
FetchError: [GET] "https://x.com/i/api/graphql/k3YiLNE_MAy5J-NANLERdg/HomeTimeline?features=%7B%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Atrue%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22c9s_tweet_anatomy_moderator_badge_enabled%22%3Atrue%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22responsive_web_twitter_article_tweet_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Atrue%2C%22rweb_video_timestamps_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Atrue%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D&variables=%7B%22count%22%3A20%2C%22includePromotedContent%22%3Atrue%2C%22latestControlAvailable%22%3Atrue%2C%22requestContext%22%3A%22launch%22%2C%22withCommunity%22%3Atrue%7D": 403 Forbidden

Route: /twitter/home/:routeParams?

Full Route: /twitter/home

Node Version: v22.4.1

Git Hash: ad135816

Git Date: Tue, 16 Jul 2024 15:24:55 GMT
```

**Comment by aaro-n** [comment]
不要回复，现在已经可以正常使用路由`/twitter/home/:routeParams?`
# 环境变量变更如下：
`TWITTER_COOKIE=auth_token=1234567; ct0=aaaaaaaaaaaaaaaaaaaaaaa`
改为
`TWITTER_AUTH_TOKEN=1234567`

**Comment by optlee** [comment]
> 不要回复，现在已经可以正常使用路由`/twitter/home/:routeParams?`
> 
> # 环境变量变更如下：
> `TWITTER_COOKIE=auth_token=1234567; ct0=aaaaaaaaaaaaaaaaaaaaaaa` 改为 `TWITTER_AUTH_TOKEN=1234567`

配置了有效果，但是
rsshub回复我的token是not valid，但是在浏览器内还能用
