### ISSUE TITLE
哔哩哔哩 UP 主投稿的 disableEmbed 参数似乎不起作用

### ISSUE THREAD

**Issue by lianginx** [DIYgod/RSSHub#16195]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
https://rsshub.app/bilibili/user/video/2267573/abc
```

### 相关文档

https://docs.rsshub.app/zh/routes/popular#up-%E4%B8%BB%E6%8A%95%E7%A8%BF

### 预期是什么？

按照文档描述 `disableEmbed` 参数可以为空，默认为空时开启内嵌视频，传入任意值则关闭；

### 实际发生了什么？

但传入 `disableEmbed` 参数后会使订阅报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Reworked in #16956
