### ISSUE TITLE
微博(方案2)近期转发信息图片标签周围br异常

### ISSUE THREAD

**Issue by jzwalk** [DIYgod/RSSHub#1620]
### 路由地址

我的微博RSS演示(方案2)：https://rsshub.app/weibo/user2/1201930965

### 预期是什么？

大约几天前所有图片前后换行还是单纯正常的，现在却出现大量多余空行影响了排版。

### 实际发生了什么？

经查RSS中转发信息的图标标签周围代码如下：

`...直接拿下影帝。 ​  <br>                                         <br>                                                                                <br><a href="http://weibo.com/1201930965/HiiOY7CdI" target="_blank"><br>                                                                                        <img src="http://ww4.sinaimg.cn/large/6c7cbd31ly1g0iq2f9bruj20v9136ahn.jpg" class="wgt_img"><br>                                                                                    </a><br>                                                                                                                        <br>转发理由：...`

可见多余br和空格充斥在img标签前后甚至a标签内。因为之前都是正常的，信息内容来自不同博主却都呈现同样的标签异常，应该是抓取源或RSSHub的处理问题？不知能否在程序上过滤下，多谢！

### 额外信息（日志、报错等）

想查看方案1是否有同样情况时发现无法访问：https://rsshub.app/weibo/user/1201930965
提示错误如下——
RSSHub 发生了一些意外:
Error: Request failed with status code 418
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

如果是方案1服务故障，希望能尽快恢复。

**Comment by DIYgod** [comment]
#1522 导致的，可以再优化下

方案1是因为反爬，建议自建
