### ISSUE TITLE
zhihu个人动态响应403 Forbidden

### ISSUE THREAD

**Issue by YukiSou** [DIYgod/RSSHub#16206]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/jamesaslan
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E7%94%A8%E6%88%B7%E5%8A%A8%E6%80%81-1

### 预期是什么？

响应成功

### 实际发生了什么？

响应失败

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://www.zhihu.com/api/v3/moments/jamesaslan/activities?limit=7&desktop=true": 403 Forbidden

Route: /zhihu/people/activities/:id

Full Route: /zhihu/people/activities/jamesaslan

Node Version: v22.4.1

Git Hash: a1a3ab42

Git Date: Thu, 18 Jul 2024 11:03:22 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ovo-Tim** [comment]
公共路由确实有这个问题，自建的就没问题。另外 XHU 是正常的

**Comment by TdlifePeng** [comment]
> 公共路由确实有这个问题，自建的就没问题。另外 XHU 是正常的

小白在免费docker上一键部署的已经2个星期经常性d_c0报错了。偶尔能突然正常个把小时。请问知道原因吗？被封锁了？
