### ISSUE TITLE
【程序变的越来越大，越来越臃肿了】

### ISSUE THREAD

**Issue by Whichbfj28** [DIYgod/RSSHub#16213]
### 这是一个什么样的功能？

作者好像在更新rsshub的架构。这种使用新技术的能力让人佩服。但是能不能考下程序变的臃肿的问题。以及新东西未必是好的。服务器程序不出问题别折腾。

### 这个功能可以解决什么问题？

![image](https://github.com/user-attachments/assets/34e51d88-ee95-4c02-b9e5-1ed0ff45cfae)
![image](https://github.com/user-attachments/assets/a84fadae-10b0-46a0-900d-229a17c9ebb2)

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by Whichbfj28** [comment]
legacy-2024-05-24             264MB
2024-07-18                         869MB
如果经典版跟最新的普通版对比869 VS 264 .直接**膨胀329%**。。

**Comment by DIYgod** [comment]
Size is not the only measure of quality. If you have extreme size requirements, consider submitting a PR to improve it.

**Comment by Whichbfj28** [comment]
> Size is not the only measure of quality. If you have extreme size requirements, consider submitting a PR to improve it.

确实不是唯一的标准。但是他让vps带动rsshub越来越费劲。。部署的时候需要越来越多的资源。

**Comment by DIYgod** [comment]
The previous small size was due to the maintainers spending a lot of time on optimization, but it has always been a low-priority issue. Unless it becomes severe enough to affect most people.

Now, we don't have enough manpower to continue this optimization work after the architecture change, nor are we willing to invest a lot of time and cost into this area. However, if there are PRs, we are certainly happy to accept them.

**Comment by DIYgod** [comment]
There are some key reasons:

1. Its size will not have significant continuous expansion in the future.
2. WeChat is a commercial product that makes a lot of money, don't compare it with open-source projects.
3. The current size is an acceptable level for me, you should consider expanding your VPS.

**Comment by Whichbfj28** [comment]
> There are some key reasons:
> 
> 1. Its size will not have significant continuous expansion in the future.
> 2. WeChat is a commercial product that makes a lot of money, don't compare it with open-source projects.
> 3. The current size is an acceptable level for me, you should consider expanding your VPS.

谢谢你的回复。我打算部署回legacy版本。vps带新版本确实比较费劲。而高配置vps需要支出更多的钱。

**Comment by KwToPA** [comment]
不知道这个有没有用

https://stackoverflow.com/questions/69428179/how-to-reduce-puppeteer-size

How to reduce Puppeteer size
Here's a few steps I've followed:

Install with NPM playwright-chromium to only download Chromium.

Set PLAYWRIGHT_BUILDPACK_BROWSERS env variable to chromium in Heroku to only install Chromium dependencies.

Put this buildpack before Node.js buildpack in Heroku.

With [/puppeteer-extra/issues/454#issuecomment-917437212](https://github.com/berstend/puppeteer-extra/issues/454#issuecomment-917437212) you can use most of the of stuff from puppeteer-stealth.

If you want, you can block resources like in Puppeteer:

**Comment by ihfserkm** [comment]
看看
[ ](https://github.com/idajr/ufdtk/issues/10) [ ](https://github.com/idajr/ydsj/issues/5) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/2) [ ](https://github.com/idajr/ydsj/issues/1) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/2) [ ](https://github.com/ttssYI/udsjc/issues/1) [ ](https://github.com/idajr/ydsj/issues/5) [ ](https://github.com/yjldkd/tdsdj6/issues/9) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/idajr/ufdtk/issues/4) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/5) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/yjldkd/tdsdj6/issues/3) [ ](https://github.com/yjldkd/tdsdj6/issues/2) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/yjldkd/tdsdj6/issues/7) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/idajr/ufdtk/issues/6) [ ](https://github.com/idajr/ydsj/issues/2) [ ](https://github.com/yjldkd/ufdsuju/issues/8) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/idajr/ydsj/issues/3) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/idajr/ydsj/issues/6) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/ttssYI/udsjc/issues/6) [ ](https://github.com/idajr/ydsj/issues/1) [ ](https://github.com/idajr/ydsj/issues/1) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/ttssYI/udsjc/issues/8) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/10) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/6) [ ](https://github.com/idajr/ufdtk/issues/1) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/7) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/10) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/7) [ ](https://github.com/idajr/ydsj/issues/8) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/yjldkd/tdsdj6/issues/4) [ ](https://github.com/ttssYI/udsjc/issues/5) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/7) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/yjldkd/tdsdj6/issues/3) [ ](https://github.com/idajr/ufdtk/issues/3) [ ](https://github.com/idajr/ydsj/issues/10) [ ](https://github.com/yjldkd/ufdsuju/issues/8) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/ttssYI/udsjc/issues/10) [ ](https://github.com/yjldkd/ufdsuju/issues/10) [ ](https://github.com/yjldkd/tdsdj6/issues/9) [ ](https://github.com/yjldkd/tdsdj6/issues/6) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/9) [ ](https://github.com/yjldkd/ufdsuju/issues/6) [ ](https://github.com/idajr/ydsj/issues/4) [ ](https://github.com/idajr/ydsj/issues/5) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/3) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/idajr/ydsj/issues/1) [ ](https://github.com/ttssYI/udsjc/issues/3) [ ](https://github.com/idajr/ufdtk/issues/5) [ ](https://github.com/idajr/ufdtk/issues/3) [ ](https://github.com/idajr/ydsj/issues/7) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/5) [ ](https://github.com/idajr/ufdtk/issues/1) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/2) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/3) [ ](https://github.com/idajr/ufdtk/issues/2) [ ](https://github.com/idajr/ufdtk/issues/8) [ ](https://github.com/idajr/ydsj/issues/2) [ ](https://github.com/yjldkd/tdsdj6/issues/2) [ ](https://github.com/yjldkd/tdsdj6/issues/10) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/4) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/idajr/ufdtk/issues/10) [ ](https://github.com/idajr/ufdtk/issues/5) [ ](https://github.com/idajr/ufdtk/issues/6) [ ](https://github.com/yjldkd/tdsdj6/issues/2) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/8) [ ](https://github.com/yjldkd/tdsdj6/issues/7) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/8) [ ](https://github.com/g64dhjhjdss/nnfdfh/issues/8) [ ](https://github.com/yjldkd/ufdsuju/issues/2) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/idajr/ydsj/issues/3) [ ](https://github.com/idajr/ufdtk/issues/9) [ ](https://github.com/ttssYI/udsjc/issues/6) [ ](https://github.com/ttssYI/udsjc/issues/8) [ ](https://github.com/yjldkd/ufdsuju/issues/5) [ ](https://github.com/ttssYI/udsjc/issues/9) [ ](https://github.com/yjldkd/tdsdj6/issues/6)
