### ISSUE TITLE
B站的视频投稿能否订阅后在标题的链接下发送单独的一个链接

### ISSUE THREAD

**Issue by pipiepig** [DIYgod/RSSHub#1622]
### 这是一个什么样的功能？
希望能订阅B站单独视频链接
### 这个功能可以解决什么问题？
由于一直使用的是telegram里面的rssbot，所以看到B站的视频链接在telegram里面的链接快照还不错，所以希望能反馈一个单独的链接，这样既可以看到UP主的视频描述还可以直接跳转出telegram，不需要点击标题链接时跳出的二级确认菜单。

**Comment by DIYgod** [comment]
@pipiepig 没看懂

**Comment by pipiepig** [comment]
> @pipiepig 没看懂
就是下面这两种区别：
1、![image](https://user-images.githubusercontent.com/25378948/53394772-36b58e80-39db-11e9-9df9-4d5966665592.png)
2、
![image](https://user-images.githubusercontent.com/25378948/53394802-4df47c00-39db-11e9-8513-76da7d798843.png)

**Comment by imlonghao** [comment]
@pipiepig 这是你所使用的 RSSBot 的锅，RSSHub 这边没什么能做的

**Comment by DIYgod** [comment]
请 https://github.com/iovxw/rssbot/issues
