### ISSUE TITLE
知乎，获取的内容不完整

### ISSUE THREAD

**Issue by fenhaizi** [DIYgod/RSSHub#16260]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/12cc8f31c86df523717b159f5075b9d3
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media

### 预期是什么？

获取到完整内容

### 实际发生了什么？

获取到的内容（只要是稍微长一点的）被截断，只能看到最前面很少一部分。

### 部署

自建

### 额外信息

```shell
没有明确的错误代码，但是获取的内容严重缺失
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
看起来需要补一个`z_c0`的cookie。

**Comment by harryqchen** [comment]
我也遇到同样问题

**Comment by 9k001** [comment]
> 看起来需要补一个`z_c0`的cookie。

我测试了新版的 rsshub。查询镜像，发现相关代码已经合并。
但是这个问题依旧没有解决。
rsshub 已经添加 ZHIHU_COOKIES 环境变量，
更新容器中，
代码截图
![image](https://github.com/user-attachments/assets/34e77d92-b944-4c02-b7be-dfea4df7b20d)
环境变量已加载
![image](https://github.com/user-attachments/assets/e9102b0a-6feb-4c27-b760-ecc875dab504)
上述环境变量中含有 “z_c0”
需注意，上述cookie所属账号未关注所需采集的答主。

**Comment by dzx-dzx** [comment]
@9k001 其它环境变量设置正常吗？

**Comment by 9k001** [comment]
> @9k001 只留下`z_c0`呢？

你的意思是 zhihu_cookies="z_c0:xxxxx'
是这个格式么？

**Comment by dzx-dzx** [comment]
@9k001

```
z_c0=xxxxx
```

这样。

**Comment by 9k001** [comment]
> @9k001
> 
> ```
> z_c0=xxxxx
> ```
> 
> 这样。

如果我没理解错，是在环境变量中配置"z_c0=xxxxxxxx"???
。。这变量如何保证rsshub中只有zhihu的路由用 z_c0 ????

**Comment by dzx-dzx** [comment]
> 保证rsshub中只有zhihu的路由用 z_c0

确实不能。

**Comment by 9k001** [comment]
> > 保证rsshub中只有zhihu的路由用 z_c0
> 
> 确实不能。

已经进行测试，依旧无法解决读取不完整的问题

**Comment by dzx-dzx** [comment]
能运行一个[开发环境](https://docs.rsshub.app/zh/joinus/new-rss/prerequisites)吗？在utils这里加个断点试试。

**Comment by 9k001** [comment]
> 能运行一个[开发环境](https://docs.rsshub.app/zh/joinus/new-rss/prerequisites)吗？在utils这里加个断点试试。

这个我确实不会。

**Comment by UniSpaceX** [comment]
<img width="1604" alt="截屏副本" src="https://github.com/user-attachments/assets/232435a7-6dd6-4a60-8be1-75854a4bcd52">
我的自建rsshub知乎内容也被截断了，断点打出来，zc0是undefined。
环境变量没有指定zc0，知乎网页版控制台document.cookie打印出来没有这个变量。

**Comment by dzx-dzx** [comment]
@UniSpaceX 网页版上你登陆了吗？

**Comment by UniSpaceX** [comment]
<img width="1610" alt="截屏2024-07-31 16 26 52" src="https://github.com/user-attachments/assets/d886dabd-030d-4c5e-8ff8-7670e98e3a08">
我在账号通知中心打印出来cookies也没有……

**Comment by dzx-dzx** [comment]
这是`httpOnly`的Cookie，需要从Storage-Cookies中拷。

**Comment by UniSpaceX** [comment]
<img width="1792" alt="截屏2024-08-01 15 25 46" src="https://github.com/user-attachments/assets/b8294587-e70c-4036-bb65-86c8884dd61a">
<img width="1792" alt="截屏2024-08-01 15 26 14" src="https://github.com/user-attachments/assets/cf8a3ffa-ac12-4808-b543-b70582ec4e0a">
<img width="529" alt="截屏2024-08-01 15 30 46" src="https://github.com/user-attachments/assets/f2b8380e-b897-4651-910f-b689c0f6a0f3">
从浏览器里面拷贝z_c0到.env之后，utils.ts断点处能读到cookie值，但是报错401 Authorization Required。去掉cookies环境变量能正常响应，但是内容被截断了。

**Comment by UniSpaceX** [comment]
从浏览器里面拷贝z_c0到.env之后，utils.ts断点处能读到cookie值，但是报错401 Authorization Required。去掉cookies环境变量能正常响应，但是内容被截断了。
z_c0 debug断点读出来开头多了=，但.env文件里key=value;这样配应该没问题吧。
<img width="840" alt="截屏2024-08-01 15 39 05" src="https://github.com/user-attachments/assets/1f5500ce-58eb-46c7-a7ac-1aa4408f212d">
<img width="529" alt="截屏2024-08-01 15 30 46" src="https://github.com/user-attachments/assets/46d26efd-c77a-4f38-b766-bb69d9dafe5d">
<img width="1792" alt="截屏2024-08-01 15 25 46" src="https://github.com/user-attachments/assets/db4fd5ed-0d6a-4c92-aa01-16c98f80f78b">
<img width="1792" alt="截屏2024-08-01 15 26 14" src="https://github.com/user-attachments/assets/19581ea0-5d62-4282-af66-882e2d06ecaa">

**Comment by dzx-dzx** [comment]
@UniSpaceX https://github.com/DIYgod/RSSHub/pull/16320 试下这个。

**Comment by UniSpaceX** [comment]
TypeError: import_config.config.zhihu.cookies?.split(...).find(...).map is not a function at getSignedHeader

**Comment by UniSpaceX** [comment]
类型“string”上不存在属性“map”。TypeError: import_config.config.zhihu.cookies?.split(...).find(...).map is not a function at getSignedHeader

**Comment by UniSpaceX** [comment]
类型“string”上不存在属性“map”。
TypeError: import_config.config.zhihu.cookies?.split(...).find(...).map is not a function at getSignedHeader

我改成 node v22再试一下，我用的v20 LTS。

**Comment by UniSpaceX** [comment]
error: Error in /zhihu/people/activities/catchen: TypeError: config.zhihu.cookies?.split(...).find(...).map is not a function
Error Message:
TypeError: config.zhihu.cookies?.split(...).find(...).map is not a function
Route: /zhihu/people/activities/:id
Full Route: /zhihu/people/activities/catchen
Node Version: v22.5.1

    const zc0 = config.zhihu.cookies
         ?.split(';')
         .find((e) => e.includes('z_c0'))
         .map((e) => e.trim())
         ?.slice('z_c0='.length);
         
.map()好像用不了

**Comment by dzx-dzx** [comment]
……代码写错了，再试一次。

**Comment by UniSpaceX** [comment]
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">...</rss>
好了，OK

**Comment by 9k001** [comment]
感谢两位大佬 @dzx-dzx @UniSpaceX  请问新修改的代码合入了么？

**Comment by harryqchen** [comment]
已经添加 ZHIHU_COOKIES 环境变量 报错401 请问是什么原因
![Snipaste_2024-08-11_02-12-00](https://github.com/user-attachments/assets/5719e982-df72-4612-999f-81680ef62333)
![Snipaste_2024-08-11_02-12-26](https://github.com/user-attachments/assets/49262c24-b0b9-4b00-8826-59b3bb251c3a)
![Snipaste_2024-08-11_02-12-45](https://github.com/user-attachments/assets/3525e9cd-7712-4c25-b21e-71a3cb46c7b2)

**Comment by dzx-dzx** [comment]
@harryqchen https://github.com/DIYgod/RSSHub/issues/16260#issuecomment-2258282993

**Comment by harryqchen** [comment]
@dzx-dzx 解决了 感谢

**Comment by 9k001** [comment]
> @dzx-dzx 解决了 感谢

你现在长文推送没问题了？。。
是怎么更新的？

**Comment by dzx-dzx** [comment]
@9k001 
你确定你设置的环境变量的语句形如
```
ZHIHU_COOKIES=z_c0=xxx
```
吗？

**Comment by dzx-dzx** [comment]
@9k001 
你确定你设置的环境变量的语句形如
```
ZHIHU_COOKIES=z_c0=xxx
```
吗？

**Comment by 9k001** [comment]
> @9k001 你确定你设置的环境变量的语句形如
> 
> ```
> ZHIHU_COOKIES=z_c0=xxx
> ```
> 
> 吗？

是这样的模式？ 直接 'z_c0=xxx'
我测试一下反馈

**Comment by 9k001** [comment]
> @9k001 你确定你设置的环境变量的语句形如
> 
> ```
> ZHIHU_COOKIES=z_c0=xxx
> ```
> 
> 吗？

我现在是 ZHIHU_COOKIES='z_c0=xxx' 测试发现依旧有截断
是不是要 ZHIHU_COOKIES=z_c0=xxx

**Comment by dzx-dzx** [comment]
@9k001 容器的话，是用docker还是docker compose？

**Comment by 9k001** [comment]
> @9k001 容器的话，是用docker还是docker compose？

两者没有本质区别

**Comment by dzx-dzx** [comment]
@9k001 就……你启动容器的完整命令/方式是什么？

**Comment by 9k001** [comment]
> @9k001 就……你启动容器的完整命令/方式是什么？

docker-compose -f xxx.yml up -d

**Comment by dzx-dzx** [comment]
环境变量设置在yml里面吗？

**Comment by 9k001** [comment]
> @9k001 环境变量设置在yml里面吗？

我确认环境变量已经引入到容器里面了 "ZHIHU_COOKIES=z_c0=2|1:0|10: xxx"

**Comment by Entropy273** [comment]
我配置了环境变量 `ZHIHU_COOKIES="z_c0=..."`后，在路由 `/zhihu/people/activities/:id` 可以正常获得回答和文章的全文，但在路由 `/zhihu/people/answers/:id` 却始终只能获得截断的回答。

我检查了源代码，发现 `/zhihu/people/answers/:id` 代码中，并没有从本地读取并使用 `z_c0` ，这就导致即使配置了环境变量，在该路由下也无法获取回答的全文。

造成这个疏忽的原因，可能是因为 `activities` 的相关接口用到了知乎的签名算法，会调用 `getSignedHeader`，这个函数读取了本地Cookie。但 `answers` 路由中并不需要用这个算法，没调函数，自然也就漏掉了环境变量中的Cookie

加上读环境变量的代码，就正常了。晚些时候我提一个mr.

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/3d858817-7a7c-48c5-9dd6-1c61dd299e51">

<img width="1242" alt="image" src="https://github.com/user-attachments/assets/3975d2bb-66f9-405b-b7fa-5f268014cdc3">

**Comment by 9k001** [comment]
> > > @9k001 环境变量设置在yml里面吗？
> > 
> > 
> > 我确认环境变量已经引入到容器里面了 "ZHIHU_COOKIES=z_c0=2|1:0|10: xxx"
> 
> 我配置了环境变量 `ZHIHU_COOKIES="z_c0=..."`后，在路由 `/zhihu/people/activities/:id` 可以正常获得回答和文章的全文，但在路由 `/zhihu/people/answers/:id` 却始终只能获得截断的回答。
> 
> 我检查了源代码，发现 `/zhihu/people/answers/:id` 代码中，并没有从本地读取并使用 `z_c0` ，这就导致即使配置了环境变量，在该路由下也无法获取回答的全文。
> 
> 造成这个疏忽的原因，可能是 `activities` 的相关接口用到了知乎的签名算法，会调用 `getSignedHeader`，这个函数读取了本地Cookie。但 `answers` 路由中并不需要用这个算法，没调函数，自然也就漏掉了环境变量中的Cookie
> 
> 加上读环境变量的代码，就正常了。晚些时候我提一个mr.
> 
> <img alt="image" width="1089" src="https://private-user-images.githubusercontent.com/32487745/358898130-3d858817-7a7c-48c5-9dd6-1c61dd299e51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzYyNjgsIm5iZiI6MTcyMzk3NTk2OCwicGF0aCI6Ii8zMjQ4Nzc0NS8zNTg4OTgxMzAtM2Q4NTg4MTctN2E3Yy00OGM1LTlkZDYtMWM2MWRkMjk5ZTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEwMTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDUxNmU1M2RlZmVjZDYwNTdkMjc5YTZiMTBiZGMwMWFkZjI1ODQ1ZDc3NGM4NzVkZmI1NGMwNjE3YzMyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEaUdr5DEuoFwkKmCn93KyY-PQ_44MU5Lpvm_oQaw-E"> <img alt="image" width="1242" src="https://private-user-images.githubusercontent.com/32487745/358898427-3975d2bb-66f9-405b-b7fa-5f268014cdc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzYyNjgsIm5iZiI6MTcyMzk3NTk2OCwicGF0aCI6Ii8zMjQ4Nzc0NS8zNTg4OTg0MjctMzk3NWQyYmItNjZmOS00MDViLWI3ZmEtNWYyNjgwMTRjZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEwMTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NDNmZjQyOTJhM2FmOTM3YzhiOTBjNjMwZmYwNGM0MzFhNDZjNzBhZjExNTMyNWIxYzBkMzcxOTk3YmE1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqjbkhJbZDsS3NbmnmAnQMXNma9SOWALgM7nuT7ZbSo">

感谢大佬
