### ISSUE TITLE
Pixiv User Novels Resolve Failed

### ISSUE THREAD

**Issue by Transwarpcom** [DIYgod/RSSHub#16270]
### Routes

```routes
/pixiv/user/novels/:id
```

### Full routes

```fullroutes
/pixiv/user/novels/76824263
```

### Related documentation

https://docs.rsshub.app/zh/routes/social-media#pixiv

### What is expected?

Resolve success

### What is actually happening?

FetchError: [GET] "https://www.pixiv.net/ajax/user/76824263/profile/novels?": 400 Bad Request

Node Version: v20.16.0

Git Hash: 1728ea5b

Git Date: Fri, 26 Jul 2024 10:42:46 GMT

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Linux, Node :20.16.0, Manual Deployment, All cookies or ANY other token are ALL OK

### Additional info

```shell
Helpful Information

Error Message:
FetchError: [GET] "https://www.pixiv.net/ajax/user/76824263/profile/novels?": 400 Bad Request

Route: /pixiv/user/novels/:id

Full Route: /pixiv/user/novels/76824263

Node Version: v20.16.0

Git Hash: 1728ea5b

Git Date: Fri, 26 Jul 2024 10:42:46 GMT
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
https://www.pixiv.net/en/users/76824263

This user doesn't have any novels.
