### ISSUE TITLE
知乎获取的内容仍然不完整

### ISSUE THREAD

**Issue by yqZhang4480** [DIYgod/RSSHub#16308]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/kvxjr369f
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media

### 预期是什么？

获取到完整内容

### 实际发生了什么？

原文中如有图片，则只能获取到图片之前的文字部分；图片、图片后文字均未呈现。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by wujieli0207** [comment]
这个问题看起来是知乎返回的数据就是截断的，和图片无关，比如这面这条数据

https://www.zhihu.com/question/264373660/answer/1710187984

返回的 content 最后部分是 `<p data-pid="yRQcD60x">我之所以觉得丢出来是值得的，是因为我</p>`，相比原内容做了截断

**Comment by yqZhang4480** [comment]
> 这个问题看起来是知乎返回的数据就是截断的，和图片无关，比如这面这条数据
> 
> https://www.zhihu.com/question/264373660/answer/1710187984
> 
> 返回的 content 最后部分是 `<p data-pid="yRQcD60x">我之所以觉得丢出来是值得的，是因为我</p>`，相比原内容做了截断

两种情况都存在。比如下面是在图片前截断的情况。
![Screenshot_20240805_204510_com microsoft emmx](https://github.com/user-attachments/assets/f58714fd-bce8-4a5f-842c-84af73fdf996)
![Screenshot_20240805_204520_com zhihu android](https://github.com/user-attachments/assets/1814e0fb-496a-4faf-b8ea-9235aa73139f)

**Comment by yqZhang4480** [comment]
另外，issue中提及的路由地址内容似乎存在遗漏，较新内容没有抓取出来。

**Comment by 9k001** [comment]
这个问题依旧没有解决，
从 [fix(route/zhihu): Trim characters while extracting cookies](https://github.com/DIYgod/RSSHub/pull/16320)
来看似乎是cookie问题。
但是还是从根本上解决这个问题。

**Comment by yqZhang4480** [comment]
按最新的多个feed来看，图片处未发现截断，但仍然存在在文字中间莫名其妙截断的现象。

**Comment by 9k001** [comment]
> 按最新的多个feed来看，图片处未发现截断，但仍然存在在文字中间莫名其妙截断的现象。

这个问题已经修复了
[#16473 ](https://github.com/DIYgod/RSSHub/pull/16473)

**Comment by TonyRL** [comment]
Duplicate of #16260
