### ISSUE TITLE
【RSS需求】希望支持数英网rss

### ISSUE THREAD

**Issue by lolstudio** [DIYgod/RSSHub#1633]
### 需要生成什么内容？

- [ ] 最新文章（希望支持rsshub的内容过滤）
- [ ] 分类文章，如【文章】、【项目】

### 额外描述
源站支持rss，但不支持分类，会有大量多余的招聘信息不需要，希望能支持

**Comment by yefoenix** [comment]
@DIYgod 可以关闭了
