### ISSUE TITLE
segmentfault 用户订阅报错

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#16353]
### 路由地址

```routes
/segmentfault/user/:name
```

### 完整路由地址

```fullroutes
/segmentfault/user/chinesehuazhou
```

### 相关文档

https://docs.rsshub.app/zh/routes/programming#%E7%94%A8%E6%88%B7-1

### 预期是什么？

RSS正常

### 实际发生了什么？

报错
Error Message:
Error: incorrect header check

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
Error: incorrect header check
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
fixed.
