### ISSUE TITLE
Bilibili embedded videos cannot play in TT-RSS

### ISSUE THREAD

**Issue by LucunJi** [DIYgod/RSSHub#16369]
### Routes

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### Full routes

```fullroutes
/bilibili/user/dynamic/4676168
```

### Related documentation

https://rsshub.netlify.app/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### What is expected?

The video embedded in iframe can play.

### What is actually happening?

(Only tested in TT-RSS) the video cannot load and play.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
(See comments)
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by LucunJi** [comment]
## My workaround

run this in console or via a TamperMonkey script:
``` js
let tmp_iframe = document.getElementsByTagName('iframe')[0];
// it becomes sandbox="allow-scripts allow-same-origin"
tmp_iframe.sandbox.add('allow-same-origin');
// reload iframe
tmp_iframe.src = tmp_iframe.src;
```

Then the video starts play normally, although there're still some errors in console.

**Comment by TonyRL** [comment]
Use either https://github.com/DIYgod/ttrss-plugin-remove-iframe-sandbox or https://github.com/tribut/ttrss-videoframes. You should contact the author of the RSS software instead, since it's the software to decide whether to show you iframe content or not.
