### ISSUE TITLE
建议用机器学习自动生成rss，未识别的网站再手动整理

### ISSUE THREAD

**Issue by neo4dev** [DIYgod/RSSHub#1637]
### What feature is it?
通过机器学习自动生成rss
### What problem does this feature solve?
不用一个个人工添加规则了
### Additional description
最近使用后裔采集器（一个有图形界面的爬虫），新增了一个AI自动识别要爬取的数据，还有翻页，就不用手动设定复杂的规则，确实大部分网页都能识别出来。

**Comment by xkungfu** [comment]
推测不是什么AI，AI只是一个名字，本质还是一系列的规则。
