### ISSUE TITLE
小黑盒用户动态只获取最近50条

### ISSUE THREAD

**Issue by Bliod-Cook** [DIYgod/RSSHub#16373]
### 路由地址

```routes
/xiaoheihe/user/:id
```

### 完整路由地址

```fullroutes
/xiaoheihe/user/30664023
```

### 相关文档

https://docs.rsshub.app/zh/routes/game#%E7%94%A8%E6%88%B7%E5%8A%A8%E6%80%81

### 预期是什么？

获取所有历史动态

### 实际发生了什么？

只获取了最近50条

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
如https://rsshub.app/xiaoheihe/user/62241928
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by tssujt** [comment]
> rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

https://github.com/DIYgod/RSSHub/issues/7291#issuecomment-809019525
