### ISSUE TITLE
🔴 BUG：拷贝漫画抓取错误

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#16380]
### 路由地址

```routes
/copymanga/comic/:id/:chapterCnt?
```

### 完整路由地址

```fullroutes
/copymanga/comic/dianjuren/5
```

### 相关文档

https://docs.rsshub.app/zh/routes/anime#%E6%BC%AB%E7%94%BB%E6%9B%B4%E6%96%B0-3

### 预期是什么？

- 正常抓取漫画更新

### 实际发生了什么？

- [https://rsshub.app/copymanga/comic/dianjuren/5](https://rsshub.app/copymanga/comic/dianjuren/5)

<img width="863" alt="image" src="https://github.com/user-attachments/assets/85a814b2-9f0c-4f67-b4d0-6591b4343994">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://api.copymanga.site/api/v3/comic/dianjuren/group/default/chapters?limit=500&offset=0": <no response> fetch failed

Route: /copymanga/comic/:id/:chapterCnt?

Full Route: /copymanga/comic/dianjuren/5

Node Version: v22.5.1

Git Hash: d44ade21

Git Date: Mon, 05 Aug 2024 01:25:13 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed in #16383
