### ISSUE TITLE
weibo/group: TypeError: responseData.statuses.map is not a function

### ISSUE THREAD

**Issue by qaz075115961** [DIYgod/RSSHub#16385]
### 路由地址

```routes
/weibo/group/:gid/:gname?/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/group/:gid/:gname?/:routeParams?
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E7%BB%84

### 预期是什么？

获取本人在微博上的自定义分组

### 实际发生了什么？

返回错误信息
TypeError: responseData.statuses.map is not a function

### 部署

自建

### 部署相关信息

Windows10专业版 22H2；Docker Desktop 4.32.0 (157355)

### 额外信息

```shell
2024-08-07 00:14:07 info: <-- GET /weibo/group/5063994840712249
2024-08-07 00:14:08 error: Error in /weibo/group/5063994840712249: TypeError: responseData.statuses.map is not a function
2024-08-07 00:14:08 info: --> GET /weibo/group/5063994840712249 503 247ms
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by qaz075115961** [comment]
/weibo/group/:gid/:gname?/:routeParams?

**Comment by wujieli0207** [comment]
看起来像是 WEIBO_COOKIES cookie 设置的问题，或者是 cookie 过期了
