### ISSUE TITLE
使用 Netlify 自动部署静态文档

### ISSUE THREAD

**Issue by u3u** [DIYgod/RSSHub#164]
## 功能

- [ ] master 分支更新时自动部署文档
- [ ] 自动预览 PR 或分支
- [ ] 部署通知

example: [https://github.com/u3u/RSSHub/pull/2 ](https://github.com/u3u/RSSHub/pull/2)

**Comment by DIYgod** [comment]
@u3u 现在用 CI 是因为 js.org 只支持 github pages，不过可以考虑换个域名 docs.rsshub.app 之类的

**Comment by u3u** [comment]
@DIYgod 搜噶，不过可以先弄一个 PR 预览，这样有问题也能及时发现

**Comment by DIYgod** [comment]
Done. https://docs.rsshub.app
