### ISSUE TITLE
关于KindleEar无法读取订阅源

### ISSUE THREAD

**Issue by wallfacertony** [DIYgod/RSSHub#1640]
kindleear是一款可以部署在GAE上的kindle推送服务，它可以将rss链接制作为mobi文件并推送到kindle。
但是在我使用RSSHub生成的rss地址进行订阅时，却无法识别（应该是的，发送的数据量始终是0k）。但是其他的网站自带的rss却可以正常订阅（纽约时报什么的）
我的kindleEar部署在:http://kindle-216509.appspot.com/ 帐号: test 密码: 123456
（需要代理）

感谢😊

**Comment by HenryQW** [comment]
@wallfacertony 这个 issue 应该开去 https://github.com/cdhigh/KindleEar

**Comment by SettingDust** [comment]
@wallfacertony 你可以确认是哪里的问题吗？服务器可以访问到rsshub？

**Comment by wallfacertony** [comment]
@HenryQW
那儿人少啊😂

**Comment by HenryQW** [comment]
隔壁住着很多老王也解决不了张三老婆不孕的问题啊。。。 

所有阅读器和 RSS 服务，目前都没有遇到无法识别 RSSHub 源的问题。

粗略地看一下，你确定 KindleEar 设置开对了吗？

![image](https://user-images.githubusercontent.com/5896343/53573351-321ce180-3b65-11e9-95bd-69801904a2ab.png)
![image](https://user-images.githubusercontent.com/5896343/53573363-377a2c00-3b65-11e9-9924-76fd2f8a0403.png)

**Comment by yefoenix** [comment]
@wallfacertony issue可以关闭了
