### ISSUE TITLE
[RSS Wanted]12306列车动态公告

### ISSUE THREAD

**Issue by AgFlore** [DIYgod/RSSHub#1642]
### 源站地址
https://www.12306.cn/mormhweb/zxdt/index_zxdt.html
https://www.12306.cn/mormhweb/1/%路局编号%/index_fl.html
### 需要生成什么内容？
关于列车加开停运等的信息

**Comment by AgFlore** [comment]
Thanks very much!
What an amazing speed!

**Comment by AgFlore** [comment]
以及建议在文档里把这个路由从“其他”给移入“出行旅游”的分类里= =

**Comment by LogicJake** [comment]
@AgFlore 可以
