### ISSUE TITLE
微博博主路由失效

### ISSUE THREAD

**Issue by mengx8** [DIYgod/RSSHub#16441]
### 路由地址

```routes
/weibo/user/1195230310
```

### 完整路由地址

```fullroutes
https://rsshub.app/weibo/user/1682075684/readable=1
```

### 相关文档

https://docs.rsshub.app/routes/popular#%E5%BE%AE%E5%8D%9A

### 预期是什么？

正确返回结果

### 实际发生了什么？

TypeError: Cannot read properties of undefined (reading 'tabs')
![image](https://github.com/user-attachments/assets/0a816cc2-9fd8-4654-a806-8d84765183c1)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
TypeError: Cannot read properties of undefined (reading 'tabs')

Route: /weibo/user/:uid/:routeParams?

Full Route: /weibo/user/1682075684/readable=1

Node Version: v22.6.0

Git Hash: 7a4cb041

Git Date: Mon, 12 Aug 2024 16:04:51 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by eli-yip** [comment]
我遇到了相同的问题，报错和楼上是一致的。

**Comment by soyaine** [comment]
相同问题+1
