### ISSUE TITLE
求出一个 最右 的路由

### ISSUE THREAD

**Issue by a-painting** [DIYgod/RSSHub#16456]
### 这是一个什么样的功能？

最右 app ，希望能获取它的帖子

### 这个功能可以解决什么问题？

最右的帖子质量挺高的

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
This is **indeed** a new RSS proposal. Please use the correct form instead.
