### ISSUE TITLE
Ways of Gracefully Rewriting Complex RSSHub Radar Path

### ISSUE THREAD

**Issue by chesha1** [DIYgod/RSSHub#16509]
### What feature is it?

Regarding the RSS feeds for Zhihu, we currently have two implementations:

1. Under `/routes/zhihu`, we use the official Zhihu API with the path `/people/:name`.
2. Under `/routes/zhihu/xhu`, we utilize a third-party service `zhihuvvv.workers.dev` with the path `/people/:hexID`.

However, in RSSHub Radar, there is only one target, and all requests are directed to the first implementation mentioned above. The second implementation is not being utilized unless manually getting hexID.

Since the second implementation requires the path `/people/:hexID`, we need to run a function that converts a user's apparent name to their hexID. Our current method of transforming the source to the target path can only perform simple replacements and cannot execute external functions.

I’m wondering if there is an graceful way to execute an external function when rewriting the source path to the target in RSSHub Radar, or if we need to develop a new feature when generating all rules to achieve this.

### What problem does this feature solve?

NOP

### Additional description

NOP

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
https://github.com/DIYgod/RSSHub/blob/a3a2fe8d3a3c4f5d09c3915fff1c1096c2905649/lib/types.ts#L268-L288

The type info and the linked issue should address some points here.

**Comment by chesha1** [comment]
Here's a simple example passing a function as value of `target`, but it didn't work expectedly.
```typescript
radar: [
        {
            source: ['www.zhihu.com/people/:id'],
            target: (params: any, url: string): string => {
                const a = '/xhu/people/activities/abc';
                return a;
            },
        },
    ],
```

And the target shown in rsshub radar is `http://localhost:1200/zhihu(params,url)=%3E%7Bconst%20a=%22/xhu/people/activities/example%22;return%20a%7D`

Could you please tell me the proper way of using function in `target`?

**Comment by TonyRL** [comment]
Using `target` as a function is **deprecated** in RSSHub-Radar 2.0.19

**Comment by wrobelda** [comment]
> Using `target` as a function is **deprecated** in RSSHub-Radar 2.0.19

Is there any alternative to using target as a function? The discussion around the format seems to have stopped as of 2022: https://github.com/DIYgod/RSSHub-Radar/issues/692
