### ISSUE TITLE
东财个股研报

### ISSUE THREAD

**Issue by weixiewen** [DIYgod/RSSHub#16504]
### Category

Finance

### Website URL

https://rsshub.app/eastmoney/report/stock.jshtml

### Website description

看路由上已有  https://rsshub.app/eastmoney/report/industry  及另外三类，期望有大佬能改一下适应新类型
目标地址，https://data.eastmoney.com/report/stock.jshtml
相关的接口  https://reportapi.eastmoney.com/report/list2
![image](https://github.com/user-attachments/assets/af80d6e3-4f9b-4ac8-950c-6c576d3b8ed6)

### What content should be included?

期望收纳：代码，简称，标题，作者，时间，评级，机构，盈利预测，行业，PDF链接
![image](https://github.com/user-attachments/assets/f83d1a06-4d8b-49a8-b742-256c626fb18a)

### Additional description

已看@syzq 提交的关于东财这块的代码，准备入门JavaScript 

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by ueiu** [comment]
具体效果如下图：
![image](https://github.com/user-attachments/assets/552e577b-85ab-4016-9c5f-11ae9ae7edad)
