### ISSUE TITLE
请求支援【虎扑BBS火箭专区】的RSS

### ISSUE THREAD

**Issue by wyhhr07** [DIYgod/RSSHub#1654]
源站地址
https://bbs.hupu.com/rockets

需要生成什么内容？
就是将火箭专区的“主题”下的帖子生成rss，方便阅读器订阅。如果可能的话，将发帖人的帖子正文也抓出来一并生成。

额外描述
虎扑官方目前只提供一些新闻类的RSS，人气很旺的球队论坛火箭专区似乎没提供，所以请求支援一下。

**Comment by LogicJake** [comment]
已有：https://rsshub.app/hupu/bxj/rockets/2
