### ISSUE TITLE
联合早报 即时

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#16580]
### 路由地址

```routes
/zaobao/realtime/:section?
```

### 完整路由地址

```fullroutes
/zaobao/realtime/china
/zaobao/realtime/world
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#%E8%81%94%E5%90%88%E6%97%A9%E6%8A%A5

### 预期是什么？

联合早报 即时

### 实际发生了什么？

Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
Error Message:
Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

Route: /zaobao/realtime/:section?

Full Route: /zaobao/realtime/world

Node Version: v22.7.0

Git Hash: 84243eb7

Git Date: Thu, 29 Aug 2024 01:06:48 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
https://github.com/DIYgod/RSSHub/blob/master/lib/routes/zaobao/util.ts#L41

can be changed to 

```js
    let data = /realtime/.test(sectionUrl) ? $('.card-listing .card') : $('.article-list').find('.article-type');
```
