### ISSUE TITLE
the.bi路由停止更新

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#16626]
### 路由地址

```routes
/the/:filter{.+}?
```

### 完整路由地址

```fullroutes
/the
```

### 相关文档

https://docs.rsshub.app/routes/new-media#%E5%88%86%E7%B1%BB-2

### 预期是什么？

持续更新

### 实际发生了什么？

停止更新

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/the
```

**Comment by dzx-dzx** [comment]
Fixed in https://github.com/DIYgod/RSSHub/pull/16663
