### ISSUE TITLE
picnob/user fails if username includes "."

### ISSUE THREAD

**Issue by Willow-Zero** [DIYgod/RSSHub#16643]
### Routes

```routes
/picnob/user/:id
```

### Full routes

```fullroutes
/picnob/user/decolonizing.love
```

### Related documentation

https://docs.rsshub.app/routes/social-media#user-profile-picnob

### What is expected?

https://www.instagram.com/decolonizing.love/
this account is the target, and its posts should be provided in rss format

### What is actually happening?

the feed returns a server side error

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Linux, Arch

### Additional info

```shell
using thunderbird as my rss reader
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Willow-Zero** [comment]
another account with a . works. unclear why this one doesnt, may open a new issue if i figure out why

**Comment by TonyRL** [comment]
/test
```routes
/picnob/user/decolonizing.love
```
