### ISSUE TITLE
雪球路由貌似不能用了，麻烦大佬帮忙看看，谢谢

### ISSUE THREAD

**Issue by hww-png** [DIYgod/RSSHub#16641]
### 路由地址

```routes
Route: /xueqiu/user/:id/:type?
```

### 完整路由地址

```fullroutes
Full Route: /xueqiu/user/3058599833
```

### 相关文档

https://rsshub.app/xueqiu/user/3058599833

### 预期是什么？

能打开3058599833主页

### 实际发生了什么？

无法访问

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
NA
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by linkboy2007** [comment]
的确挂了。。好像没人修了。。
