### ISSUE TITLE
【极客公园】能否恢复极客公园的route

### ISSUE THREAD

**Issue by hxhac** [DIYgod/RSSHub#16651]
### 这是一个什么样的功能？

目前极客公园的route是可用的，但是被放到routes-deprecated文件夹下了

[RSSHub/lib/routes-deprecated/geekpark/breakingnews.js at master · DIYgod/RSSHub](https://github.com/DIYgod/RSSHub/blob/master/lib/routes-deprecated/geekpark/breakingnews.js)

### 这个功能可以解决什么问题？

...

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
#14611

**Comment by hxhac** [comment]
thx
