### ISSUE TITLE
Javbus 因 avgle api 原因导致无法完成抓取

### ISSUE THREAD

**Issue by yamayyama** [DIYgod/RSSHub#16653]
### 路由地址

```routes
/javbus/:path{.+}?
```

### 完整路由地址

```fullroutes
/javbus/star/uc0
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#javbus

### 预期是什么？

avgle api 不影响显示抓取信息

### 实际发生了什么？

抓取请求因 avgle api 返回 522 导致无法抓取失败

### 部署

自建

### 额外信息

```shell
warn: Request https://api.avgle.com/v1/jav/HBAD-577/0 with error 522 remaining re try attempts: 5
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #14199
