### ISSUE TITLE
pnpm build提示punycode已被废弃

### ISSUE THREAD

**Issue by Dz3yu** [DIYgod/RSSHub#16668]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/deploy/#%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2

### 预期是什么？

正常build成功

### 实际发生了什么？

提示punycode模块已被废弃

### 部署

自建

### 部署相关信息

ubuntu22.04-docker26

### 额外信息

```shell
root@VM-24-11-ubuntu:/home/ubuntu/RSSHub# pnpm build

> rsshub@1.0.0 build /home/ubuntu/RSSHub
> tsx scripts/workflow/build-routes.ts

(node:278611) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
This is just a warning. It doesn't indicate the build is failed.
