### ISSUE TITLE
twitter路由显示ConfigNotFoundError

### ISSUE THREAD

**Issue by Dz3yu** [DIYgod/RSSHub#16662]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/_tioone_
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#user-timeline-5

### 预期是什么？

预期正常获取twitter user内容

使用docker-compose部署
配置了环境变量
TWITTER_USERNAME:  “_tioone_”
TWITTER_PASSWORD: ""
TWITTER_AUTHENTICATION_SECRET: ""
PROXY_URI: "127..0.0.1:20171" （使用v2rayA配置代理）

### 实际发生了什么？

Error Message:
ConfigNotFoundError: Invalid twitter configs: _tioone_

### 部署

自建

### 部署相关信息

Ubuntu22.04-Docker26

### 额外信息

```shell
Error Message:
ConfigNotFoundError: Invalid twitter configs: _tioone_
Route: /twitter/user/:id/:routeParams?
Full Route: /twitter/user/_tioone_
Node Version: v22.8.0
Git Hash: afa85c64
Git Date: Sat, 07 Sep 2024 16:53:29 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #16533

**Comment by Dz3yu** [comment]
The problem was solved by switching to pnpm self-compilation, but there is still a problem with docker-compose.
