### ISSUE TITLE
X (Twitter): list timeline not found

### ISSUE THREAD

**Issue by bossanovaorca** [DIYgod/RSSHub#16678]
### Routes

```routes
/twitter/list/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/list/:id/:routeParams?
```

### Related documentation

https://docs.rsshub.app/routes/social-media#list-timeline

### What is expected?

should load list timeline

### What is actually happening?

TypeError: api.getList is not a function

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
I'm trying to fetch a list and the example in the docs is not working (/twitter/list/ladyleet/javascript) so I'm unsure how to use this method
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
docs/route fixed and implemented in web-api, should use list id like `1502570462752219136`, you can find it in the url when you open the list in twitter.

refer to https://docs.rsshub.app/routes/popular#list-timeline
