### ISSUE TITLE
javbus的封面图不显示

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#1669]
### 路由地址
https://rsshub.app/javbus/home
### 预期是什么？
显示封面图和预览图片
### 实际发生了什么？
封面图不显示，预览图片正常显示

**Comment by yefoenix** [comment]
看了一下这个路由编写的时候就没准备显示封面吧

**Comment by tomatomash** [comment]
> 看了一下这个路由编写的时候就没准备显示封面吧

前段时间是有会显示封面的，目前的状况是，inoreader上看不到，但在feedly里能加载出封面的缩略图，但点进去后是不显示的，如我截图所示，https://imgchr.com/i/kOkHrF

**Comment by DIYgod** [comment]
图片有防盗链，inoreader 把 `referrerpolicy="no-referrer"` 去掉了，无解
