### ISSUE TITLE
Google Scholar RSS not working

### ISSUE THREAD

**Issue by wortmanncallejon** [DIYgod/RSSHub#16692]
### Routes

```routes
/google/scholar/:query
```

### Full routes

```fullroutes
/google/scholar/data+visualization
```

### Related documentation

-

### What is expected?

An RSS feed.

### What is actually happening?

No RSS feed is generated. It works with single word queries, I assume it is some issue with how the queries are processed and transferred to Scholar

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
-
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/google/scholar/data+visualization
```

**Comment by TonyRL** [comment]
It works

**Comment by wortmanncallejon** [comment]
Weird, it didn't work for me earlier. Thanks for fixing it ?!
