### ISSUE TITLE
WEMP 路由对于含有「阅读原文」的微信文章链接解析错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1670]
### 路由地址
https://rsshub.app/wechat/wemp/;id
例：https://rsshub.app/wechat/wemp/17dcf281-51bd-40fe-ae8d-0e62b1c19099
### 预期是什么？
正确显示文章链接
### 实际发生了什么？

如上述例子「三联生活周刊」，由于文章设定了「阅读原文」链接，链接错误显示为有赞链接

**Comment by DIYgod** [comment]
#1656
