### ISSUE TITLE
Bilibili 用户关注视频动态无法正常工作

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#16719]
### 路由地址

```routes
/bilibili/followings/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/followings/video/2949856
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%94%A8%E6%88%B7%E5%85%B3%E6%B3%A8%E8%A7%86%E9%A2%91%E5%8A%A8%E6%80%81

### 预期是什么？

正常工作

### 实际发生了什么？

TypeError: Cannot read properties of undefined (reading 'cards')

### 部署

自建

### 额外信息

```shell
Error Message:
TypeError: Cannot read properties of undefined (reading 'cards')

Route: /bilibili/followings/video/:uid/:disableEmbed?

Full Route: /bilibili/followings/video/2949856

Node Version: v22.8.0

Git Hash: e6d53dc6

Git Date: Thu, 05 Sep 2024 15:07:53 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by curly210102** [comment]
试试看用整段 Cookie 配置`BILIBILI_COOKIE_{uid}`，我这边只拿 `SESSDATA` 的值是会出现这个错
