### ISSUE TITLE
酷安图片无法加载

### ISSUE THREAD

**Issue by yitong2333** [DIYgod/RSSHub#16715]
### 路由地址

```routes
/coolapk/huati/:tag
/coolapk/dyh/:dyhId
/coolapk/hot/:type?/:period?
/coolapk/toutiao/:type?
/coolapk/user/:uid/dynamic
```

### 完整路由地址

```fullroutes
/coolapk/huati/:tag
/coolapk/dyh/:dyhId
/coolapk/hot/:type?/:period?
/coolapk/toutiao/:type?
/coolapk/user/:uid/dynamic
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E9%85%B7%E5%AE%89

### 预期是什么？

希望在rss查看器里能看到预览的图片

### 实际发生了什么？

图片显示为损坏状态，且无法加载
![QQ_1726125964606](https://github.com/user-attachments/assets/26d1ae98-ff03-4d09-bba5-ef8a57e22ff2)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by yitong2333** [comment]
我已经更新了Issue

**Comment by xizeyoupan** [comment]
`Request`头中`Accept`字段需要包含`image`且不能以`image`开头

**Comment by MuXia-0326** [comment]
遇到这个问题很久了，不知道什么时候能修复

**Comment by yitong2333** [comment]
俺也一样

Mossia ***@***.***> 于 2024年10月10日周四 11:27写道：

**Comment by pseudoyu** [comment]
still exists? or do you try in different RSS reader?

i found image link in `/coolapk` is in the format like `http://image.coolapk.com/feed/2024/1019/11/1080570_80352763_7676_4085_695@2160x3780.jpeg` and it's valid.

**Comment by xizeyoupan** [comment]
目前的一个解决办法是将`ALLOW_USER_HOTLINK_TEMPLATE`环境变量设置为`true` ，然后配置`image_hotlink_template` 。见[多媒体处理](https://docs.rsshub.app/guide/parameters#multimedia-processing)。这里提供一个转换[工具](https://github.com/xizeyoupan/simple-image-proxy)，仅对上述路由测试，建议自行部署。使用时对订阅链接加上参数即可。

例如 `/coolapk/hot?image_hotlink_template=http://your-proxy-url/api?url=${href_ue}`
