### ISSUE TITLE
西南科技大学教务处罢工事件

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#1673]
### 路由地址
https://rsshub.app/swust/jwc/news
https://rsshub.app/swust/jwc/notice
https://rsshub.app/swust/cs

### 预期是什么？
不被教务处开除

### 实际发生了什么？
没有收到通知，错过重大事件，惨遭开除

@lengthmin 没有一条路由可用。

**Comment by lengthmin** [comment]
收到

**Comment by lengthmin** [comment]
求求issue名字不要这么惊悚
测试了一下 自搭没问题

**Comment by HenryQW** [comment]
原来是屏蔽了国外 IP
