### ISSUE TITLE
端传媒网页改版后无法获取最新的数据

### ISSUE THREAD

**Issue by lucky13820** [DIYgod/RSSHub#16762]
### 路由地址

```routes
/theinitium/follow/articles/:language?
```

### 完整路由地址

```fullroutes
/theinitium/channel/latest/zh-hans
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E7%AB%AF%E4%BC%A0%E5%AA%92

### 预期是什么？

可以看到 11 号改版后的新文章

### 实际发生了什么？

11 号改版之后新网站不再使用以前的 api 了，所以现在路由里只能看到 10 号之前的文章

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
尝试自己更新下路由，但是没有找到能获取文章全文的 api，可能只能用 Puppeteer 了。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by quiniapiezoelectricity** [comment]
api 的部分可以用 app.theinitium.com 的 api 例如:
https://app.theinitium.com/timelines.json
https://app.theinitium.com/editionfeed/3/pugpig_atom_contents.json
https://app.theinitium.com/editionfeed/1976/pugpig_atom_contents.json
但是代码应该要全部重写

**Comment by lucky13820** [comment]
感谢

**Comment by prnake** [comment]
great job!
