### ISSUE TITLE
希望增加对国家食药监的RSS

### ISSUE THREAD

**Issue by dabingar** [DIYgod/RSSHub#1678]
希望增加食药监RSS，
比如
药品召回http://www.nmpa.gov.cn/WS04/CL2060/
安全警示http://www.nmpa.gov.cn/WS04/CL2172/

**Comment by DIYgod** [comment]
[RSS 需求模板](https://github.com/DIYgod/RSSHub/issues/new?template=rss_request_zh.md)

**Comment by dabingar** [comment]
### http://www.nmpa.gov.cn/WS04/CL2060/

**### 召回标题文本**

- [ 1 ] 勃林格殷格翰公司主动召回特定批次盐酸氨溴索注射液 (2017-11-27)
- [ 2 ] 广东本草药业集团有限公司主动召回其代理的意大利贝斯迪大药厂细菌溶解物（商品名：兰菌净） (2016-11-14)

### 额外描述（无）

### http://www.nmpa.gov.cn/WS04/CL2172/

**### 安全警戒标题文本**

- [ 1 ] 药物警戒快讯 第12期（总第188期）
- [ 2 ] 药物警戒快讯 第11期（总第187期） (2018-11-23)

### 额外描述（无）

### http://www.nmpa.gov.cn/WS04/CL2168/

### 监管动态标题文本

- [ 1 ] 治疗肾性贫血新药罗沙司他胶囊获批上市 (2018-12-18)
- [ 2 ] 用于治疗乳腺癌的帕妥珠单抗注射液获批上市 (2018-12-17)

### 额外描述（无）

**Comment by tailaijin** [comment]
同希望，希望了解相关证照的发放状况，具体信息可以在：
[http://sc.foodmate.net/](url)
查询到
