### ISSUE TITLE
rsshub.app often times out for GitHub

### ISSUE THREAD

**Issue by BoD** [DIYgod/RSSHub#16796]
### Routes

```routes
/github/pull/:user/:repo/:state?/:labels?
```

### Full routes

```fullroutes
github/pull/apollographql/apollo-kotlin
```

### Related documentation

https://docs.rsshub.app/routes/programming#repo-pull-requests

### What is expected?

The list of pull requests

### What is actually happening?

The page loads for several minutes, nothing is ever returned. Sometimes, this works as expected.

Note: I have the same issue with /github/issues

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
For instance, go to https://rsshub.app/github/pull/apollographql/apollo-kotlin

This used to work perfectly at least a few months ago. But I've noticed these timeouts for quite a while now.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
this route works well but the official instance are responding slowly or failed, please consider use other [public instances](https://docs.rsshub.app/guide/instances) or deploy yourself to resolve this issue.
