### ISSUE TITLE
求大佬给我的博客加一下RSS👉Oct0pu5.cn

### ISSUE THREAD

**Issue by Octopus058** [DIYgod/RSSHub#16804]
### 类型

博客

### 网站地址

https://oct0pu5.cn/

### 网站描述

我的个人博客

### 需要生成什么内容？

标题，时间，全文（保留格式）

### 额外描述

我自己写了一点代码，不知道对不对，烦请大佬指正，球球了orz

代码在我的仓库，lib/routes/oct0pu5，非常感谢！😘

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by wiketool** [comment]
放一个传送门 https://github.com/Octopus058/RSSHub/tree/master/lib/routes/oct0pu5

**Comment by wiketool** [comment]
你的博客似乎无法访问

**Comment by huanfe1** [comment]
你可以用 hexo 自带的 rss 插件

**Comment by Octopus058** [comment]
感谢大佬！！我第一次写RSS的代码，怕写的不对就没PR🙃

**Comment by wiketool** [comment]
> 感谢大佬！！我第一次写RSS的代码，怕写的不对就没PR🙃

你的代码整体写的挺好的，我修正了其中的一些错误，可以到 https://github.com/DIYgod/RSSHub/pull/16809 查看 @Octopus058

**Comment by Octopus058** [comment]
🙏🙏大佬，再次感谢，我会认真学习的
