### ISSUE TITLE
某路由对应学院改名，换了域名

### ISSUE THREAD

**Issue by RayHY** [DIYgod/RSSHub#1680]
### 路由地址

https://docs.rsshub.app/#%E5%8D%8E%E4%B8%AD%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6

### 预期是什么？

正常工作

### 实际发生了什么？

由于学院网站更换域名，报[DNS错误](https://rsshub.app/hust/auto/notice/0)

### 额外信息（日志、报错等）

这个路由原本是为了爬取华中科技大学自动化学院的通知，但最近自动化学院改名，相应地，网址由原来的auto.hust.edu.cn改变为aia.hust.edu.cn，网站结构未发生改变。

这个路由是我写的(jinxiapu是我原来的GitHub id)，我可以将其改正，但现在有一个问题，由于学院从
auto变为了aia，路由地址需要改变吗？(即`/hust/auto/notice/0` -> `/hust/aia/notice/0` )
还是维持原路由地址不变？

发个issue讨论一下，有了结论后我会提交PR。

**Comment by LogicJake** [comment]
我觉得既然已经报错我还没人提issue，说明使用该rss的人不算多，改路由地址也没什么

**Comment by SettingDust** [comment]
建议做好向下兼容 保留原路由 但是文档中隐藏 再加一个新的路由

**Comment by RayHY** [comment]
rsshub.app 后台有数据吗？我估摸着除了我自己没人用，我个人是想换为aia的，aia是符合惯例的。

**Comment by DIYgod** [comment]
新增 `/hust/aia/notice/:type?`，文档里也改成 `/hust/aia/notice/:type?`

旧路由 `/hust/auto/notice/:type?` 建议保留
