### ISSUE TITLE
🔴 Telegram 部分频道无法获取最新信息

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#16824]
### 路由地址

```routes
/telegram/channel/:username/:routeParams?
```

### 完整路由地址

```fullroutes
https://rsshub.app/telegram/channel/NewlearnerChannel
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#channel

### 预期是什么？

- 正常获取频道信息

### 实际发生了什么？

- [https://t.me//NewlearnerChannel](https://t.me//NewlearnerChannel)

- [https://rsshub.app/telegram/channel/NewlearnerChannel](https://rsshub.app/telegram/channel/NewlearnerChannel)

- 无法获取频道的最新信息

<img width="1484" alt="image" src="https://github.com/user-attachments/assets/fc7632f7-1107-4330-999f-b56d6b446ddc">

<img width="749" alt="image" src="https://github.com/user-attachments/assets/f6cace26-7d5a-4c48-9844-f9f40df8ed3c">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
None
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/telegram/channel/NewlearnerChannel
```

**Comment by TonyRL** [comment]
Looks like Telegram has flagged this channel recently, which remove web preview.
