### ISSUE TITLE
Twitter media problem with specific account

### ISSUE THREAD

**Issue by Octelly** [DIYgod/RSSHub#16826]
### Routes

```routes
/twitter/media/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/media/Cute_Morbidly
```

### Related documentation

https://docs.rsshub.app/routes/social-media#x-twitter

### What is expected?

Media feed for twitter@Cute_Morbidly

### What is actually happening?

`TypeError: Cannot read properties of undefined (reading 'user_result')`

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

NixOS 24.05; Docker version 25.0.6, build v25.0.6

### Additional info

``docker compose logs`` does not provide any additional information

authenticated via ``TWITTER_AUTH_TOKEN``

https://github.com/DIYgod/RSSHub/issues/15523 seems related, issue was discarded

Pulling the latest version did not resolve the issue.

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
self-host RSSHub requires `TWITTER_AUTH_TOKEN`, if it's invalid or have limited access to the twitter web (like a new twitter account or some other reasons), the error may occur.

**Comment by Octelly** [comment]
Far from an old account and it's an account I did at least use to use. This did not address my issue at all... oh well
