### ISSUE TITLE
编程-Hellogithub-月刊 重复

### ISSUE THREAD

**Issue by Octopus058** [DIYgod/RSSHub#16838]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/routes/hellogithub/month,/volume
```

### 相关文档

https://docs.rsshub.app/zh/routes/programming#%E6%9C%88%E5%88%8A-1

### 预期是什么？

应该只有一个“月刊”

### 实际发生了什么？

多了一个“月刊-1”
![QQ图片20240920230448](https://github.com/user-attachments/assets/7fdbf373-7497-4d2b-9e17-f7539ce51a20)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

OS: Windows 11, node 20.17.0

### 额外信息

```shell
如上
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Octopus058** [comment]
抱歉刚才填错了

**Comment by ueiu** [comment]
这好像是说明你可以用 /month 或者 /volume 访问，但是文档生成应该是认为是两个路由所以生成两份了😂

**Comment by Octopus058** [comment]
那应该咋修改_(:з」∠)_

**Comment by ueiu** [comment]
不是路由bug我也不会 我看了下貌似很多通用路由都会产生两份文档说明

**Comment by pseudoyu** [comment]
Adjusted the doc generation script to keep only one route statement for the same route (also show two routes' paths in the format of `/hellogithub/month,/volume`
