### ISSUE TITLE
juejin RSS 失效

### ISSUE THREAD

**Issue by fz6m** [DIYgod/RSSHub#16849]
### Routes

https://rsshub.app/juejin/tag/JavaScript 会发生 502

https://rsshub.app/juejin/trending/frontend/monthly 会发生 `Looks like something went wrong`

https://rsshub.app/juejin/category/frontend 会得到旧的数据，不是最新当天的，已经挂了好多天了

### Full routes

```fullroutes
-
```

### Related documentation

https://docs.rsshub.app/routes/programming#%E6%8E%98%E9%87%91

### What is expected?

-

### What is actually happening?

-

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
试了下其他 rsshub instance ，可以正常使用，好像是 RSSHUB 官方的 ip 被 juejin 限制了。
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
The official demo instances are for demonstration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability.
