### ISSUE TITLE
【Research Briefing & Data dashboards 英国下议院图书馆】

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#16845]
### 类型

政务消息

### 网站地址

https://commonslibrary.parliament.uk/

### 网站描述

Our job is to provide a range of research and information services for MPs and MPs’ staff. Our work helps MPs scrutinise legislation, prepare for debates, develop policies and support their constituents.

We are a team of researchers, statisticians, librarians, indexers, communications and customer service professionals, working together to provide an impartial and trusted service.

我们的工作是为国会议员和国会议员的工作人员提供一系列研究和信息服务。 我们的团队由研究员、统计员、图书馆员、索引员、通信和客户服务专业人员组成，共同提供公正可信的服务。

https://commonslibrary.parliament.uk/about-us/#heading-2

### 需要生成什么内容？

Research Briefing  https://commonslibrary.parliament.uk/type/research-briefing/

Data dashboards  https://commonslibrary.parliament.uk/type/data-dashboard/

### 额外描述

感谢

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by AntiKnot** [comment]
Take, work in process.

**Comment by KwToPA** [comment]
感谢 [AntiKnot](https://github.com/AntiKnot)  哥
