### ISSUE TITLE
feat: 实时视频代理

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#16857]
### 这是一个什么样的功能？

rss中嵌入的视频链接可能是有时效的，例如微博视频，爬取的视频链接过一段时间就失效了，导致无法在RSS中直接观看视频

目前的多媒体处理功能也无法解决这个问题，这里提供一个可行的方案

例，有原网页地址：`https://a.com/p/123`

可以在网页中获取视频信息，如
视频id：v4567，地址：`https://a.com/xxx/1.mp4`

拼接得到代理地址：`https://rsshub/video-proxy/?u=https://a.com/p/123&vid=v4567`

后端根据网址和视频id获取视频地址，实现代理

### 这个功能可以解决什么问题？

RSS中视频链接有时效，导致无法播放，这样可以得到一个相对长效可用的视频地址

### 额外描述

算是一个通用的解决时效资源的方案，但没想好怎么做的更加通用并加到RSSHub里，提出来看看各位的看法

可行性的话目前已有实现的例子，代理微信视频可以预览
```
https://wechat2rss.xlab.app/video-proxy/?k=8861a8fd&u=https%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzUzNjE3NzQ3Nw%3D%3D%26mid%3D2247492925%26idx%3D1%26sn%3Dcd2f8750565f5c5a1173b4e0e43b2fc1%26subscene%3D0&v=wxv_3389374447063433223
```

如果配合现有的多媒体处理功能，需要增加更多的参数信息，比如当前RSS item的地址（即例子中的网页地址），以及一个动态的map用来描述网页中的视频唯一标识

代理服务也需要根据网站进行适配，因为每个获取视频地址的方式都不一样

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
> Out of scope. You may use multimedia processing parameters instead.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/issues/8315#issuecomment-1193018384_

**Comment by TonyRL** [comment]
Duplicate of #8315.

**Comment by ttttmr** [comment]
但是现有的多媒体处理功能处理不了这个情况，地址过期了还是会播放不了

这个功能希望能丰富一些多媒体处理的参数

> 配合现有的多媒体处理功能，需要增加更多的参数信息，比如当前RSS item的地址（即例子中的网页地址），以及一个动态的map用来描述网页中的视频唯一标识
