### ISSUE TITLE
预报预警-停水通知-南京市可以修改为可筛选的

### ISSUE THREAD

**Issue by 4O4NtFd** [DIYgod/RSSHub#16861]
### 这是一个什么样的功能？

将/tingshuitz/nanjing.ts的const url = `${HOME_PAGE}portal/10000013`;修改为${HOME_PAGE}search?keyWords=
可以达到搜索的功能

### 这个功能可以解决什么问题？

新增南京市停水通知的搜索功能

### 额外描述

第一次提issue求大佬请喷

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by ueiu** [comment]
[filter 内容过滤](https://docs.rsshub.app/zh/guide/parameters#%E5%86%85%E5%AE%B9%E8%BF%87%E6%BB%A4) 这个会不会就能满足你的需求呢🤔

**Comment by 4O4NtFd** [comment]
谢谢大佬，以前从来没注意过这个参数
