### ISSUE TITLE
百度新闻热榜 down

### ISSUE THREAD

**Issue by EaglePPP** [DIYgod/RSSHub#16865]
### 路由地址

```routes
/baidu/top/:board?
```

### 完整路由地址

```fullroutes
/baidu/top/:board?
```

### 相关文档

https://rsshub.app/baidu/top

### 预期是什么？

返回热榜新闻

### 实际发生了什么？

超时
返回了最晚18号的rss

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
尚无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/baidu/top
```

**Comment by TonyRL** [comment]
It works.
