### ISSUE TITLE
希望支持购物党历史最低价商品rss订阅

### ISSUE THREAD

**Issue by wyhhr07** [DIYgod/RSSHub#1686]
### 源站地址
https://www.gwdang.com/crc64/promotion/price/00000000-0-list-update_time-desc-1---.html?keyword=&query=

### 需要生成什么内容？
（类似什么值得买）
- [ ] 历史最低价商品订阅
- [ ] 商品关键词订阅

### 额外描述

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
