### ISSUE TITLE
某些微博无法订阅

### ISSUE THREAD

**Issue by Byhaise** [DIYgod/RSSHub#1687]
### 路由地址

http://********.herokuapp.com/weibo/user/*******

### 预期是什么？

正确显示微博用户内容

### 实际发生了什么？

RSSHub 发生了一些意外:
TypeError: Cannot read property 'screen_name' of undefined
    at module.exports (/app/lib/routes/weibo/user.js:15:55)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

### 部署相关信息
Heroku 
Master分支最新版

### 额外信息（日志、报错等）

已知非反爬原因，其他微博显示正常

**Comment by DIYgod** [comment]
该用户登录可见，无法获取数据

**Comment by Byhaise** [comment]
@DIYgod 原来如此，谢谢解答
