### ISSUE TITLE
虎嗅 路由 抓取失败。

### ISSUE THREAD

**Issue by Teda9** [DIYgod/RSSHub#16873]
### 路由地址

```routes
/huxiu/moment
/huxiu/article,/channel/:id?
```

### 完整路由地址

```fullroutes
/huxiu/moment
/huxiu/channel/120
/huxiu/channel/106
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E8%99%8E%E5%97%85

### 预期是什么？

正常抓取。

### 实际发生了什么？

Helpful Information

Error Message:
FetchError: [POST] "https://api-article.huxiu.com/web/channel/articleList": <no response> fetch failed

Route: /huxiu/channel/:id?

Full Route: /huxiu/channel/106

Node Version: v22.9.0

Git Hash: a9de2028

Git Date: Fri, 20 Sep 2024 16:49:42 GMT

Helpful Information

Error Message:
FetchError: [POST] "https://api-article.huxiu.com/web/channel/articleList": <no response> Number of requests reached it's maximum 500

Route: /huxiu/channel/:id?

Full Route: /huxiu/channel/120

Node Version: v22.9.0

Git Hash: 2072a633

Git Date: Sun, 22 Sep 2024 11:30:17 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Helpful Information

Error Message:
FetchError: [POST] "https://api-article.huxiu.com/web/channel/articleList": <no response> Number of requests reached it's maximum 500

Route: /huxiu/channel/:id?

Full Route: /huxiu/channel/120

Node Version: v22.9.0

Git Hash: 2072a633

Git Date: Sun, 22 Sep 2024 11:30:17 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/huxiu/moment
/huxiu/channel/120
/huxiu/channel/106
```

**Comment by TonyRL** [comment]
It works.
