### ISSUE TITLE
rsshub.app 官方实例 调取虎嗅失败 用公共实例能调取成功。

### ISSUE THREAD

**Issue by Teda9** [DIYgod/RSSHub#16887]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
rsshub.app/huxiu/channel/120
rsshw.win/huxiu/channel/120
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E8%99%8E%E5%97%85

### 预期是什么？

官方实例 也能调取成功。

### 实际发生了什么？

https://rsshub.app/huxiu/channel/120 官方实例调取失败，

Helpful Information
Error Message:
FetchError: [POST] "https://api-article.huxiu.com/web/channel/articleList": <no response> Number of requests reached it's maximum 500
Route: /huxiu/channel/:id?
Full Route: /huxiu/channel/120
Node Version: v22.9.0
Git Hash: 2072a633
Git Date: Sun, 22 Sep 2024 11:30:17 GMT

http://rsshw.win/huxiu/channel/120  公共实例能调取成功。
![image](https://github.com/user-attachments/assets/c48bd8f1-e336-4768-9019-d8bac648faa5)

![image](https://github.com/user-attachments/assets/fd1ce3b9-f6fb-4851-84d1-54f6d34069c9)
看文档介绍是严格反爬的会失效，不过虎嗅这个没看到 严格反爬标志。不清楚是否是反爬虫导致的。

![image](https://github.com/user-attachments/assets/6be652d8-11c3-4d33-b8f8-df6c80ad7a0a)

看错误提示，不确定是否是 status code 403 同类提示，如果是的话，该bug应该就是反爬虫导致。可以关闭

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
https://rsshub.app/huxiu/channel/120 官方实例调取失败，

Helpful Information
Error Message:
FetchError: [POST] "https://api-article.huxiu.com/web/channel/articleList": <no response> Number of requests reached it's maximum 500
Route: /huxiu/channel/:id?
Full Route: /huxiu/channel/120
Node Version: v22.9.0
Git Hash: 2072a633
Git Date: Sun, 22 Sep 2024 11:30:17 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
> The official demo instances are for demonstration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability. 

Duplicate of #16849.

**Comment by TonyRL** [comment]
Duplicate of #16849
