### ISSUE TITLE
Github comment issue

### ISSUE THREAD

**Issue by fewensa** [DIYgod/RSSHub#16890]
### 路由地址

```routes
/github/comments/:user/:repo/:number?
```

### 完整路由地址

```fullroutes
/github/comments/DefiLlama/defillama-app/1752
```

### 相关文档

https://docs.rsshub.app/routes/programming#issue-pull-request-comments

### 预期是什么？

github issue content xml 

### 实际发生了什么？

Error Message:
FetchError: [GET] "https://api.github.com/repos/DefiLlama/defillama-app/issues/1752": <no response> fetch failed

Route: /github/comments/:user/:repo/:number?

Full Route: /github/comments/DefiLlama/defillama-app/1752

Node Version: v22.9.0

Git Hash: 4be28ac2

Git Date: Mon, 23 Sep 2024 08:46:57 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://api.github.com/repos/DefiLlama/defillama-app/issues/1752": <no response> fetch failed

Route: /github/comments/:user/:repo/:number?

Full Route: /github/comments/DefiLlama/defillama-app/1752

Node Version: v22.9.0

Git Hash: 4be28ac2

Git Date: Mon, 23 Sep 2024 08:46:57 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/github/comments/DefiLlama/defillama-app/1752
```

**Comment by TonyRL** [comment]
It works
