### ISSUE TITLE
使用 SSRF 防护，取消 ALLOW_USER_SUPPLY_UNSAFE_DOMAIN

### ISSUE THREAD

**Issue by ttttmr** [DIYgod/RSSHub#16906]
### 这是一个什么样的功能？

ALLOW_USER_SUPPLY_UNSAFE_DOMAIN 本意应该是预防 SSRF 问题，也会导致公开实例上难以开启相关路由

可以使用 SSRF 防护，屏蔽私有地址

### 这个功能可以解决什么问题？

公开实例上可以安全开启全部路由

### 额外描述

参考：https://github.com/hanover-computing/got-ssrf

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by TonyRL** [comment]
> Please take a deep look at GHSA-64wp-jh9p-5cg2 and GHSA-3p3p-cgj7-vgw3. It's talking about **arbitrary** targets not just those inside internal network.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/pull/16908#pullrequestreview-2326046657_

> Again, this hasn't addressed the concern of allowing visiting arbitrary targets.
>
> Consider an attacker asks RSSHub (which is hosted in a typical data centre) to visit `https://example.com/VERY_LARGE_FILE`, even with request timeout of 30s, it is still wasting unnecessary bandwidth and memory of ~3GB (assuming a gigabit here but most basic $5/mo servers can reach more than a gigabits).

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/pull/16908#pullrequestreview-2382826589_
