### ISSUE TITLE
wise汇率的pubDate不会更新

### ISSUE THREAD

**Issue by SlightDust** [DIYgod/RSSHub#16905]
### 路由地址

```routes
/wise/pair/:source/:target
```

### 完整路由地址

```fullroutes
/wise/pair/:source/:target
```

### 相关文档

https://docs.rsshub.app/zh/routes/other#fx-pair-yesterday

### 预期是什么？

内容更新时，pubDate字段也更新

### 实际发生了什么？

pubDate字段未更新

### 部署

自建

### 部署相关信息

Docker20.10.21

### 额外信息

```shell
<item>
<title>USD/CNY 📈 @7.26665 0.0509%</title>
<description><h3>USD to CNY</h3><table><tbody><tr><th align="left" style="border:1px solid #000">Date</th><th align="left" style="border:1px solid #000">Rate</th></tr><tr><td style="border:1px solid #000">2024-09-23</td><td style="border:1px solid #000">7.26665</td></tr><tr><td style="border:1px solid #000">2024-09-22</td><td style="border:1px solid #000">7.26295</td></tr></tbody></table></description>
<link>https://wise.com/tools/exchange-rate-alerts/</link>
<guid isPermaLink="false">wise:rates:USD-CNY-2024-09-23</guid>
<pubDate>Thu, 27 Jun 2024 00:00:00 GMT</pubDate>
</item>
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ueiu** [comment]
看了下代码，`pubDate` 字段是用的 wise 接口返回的最新一天的 `time` 字段填入的，你 23 号的汇率就应该是 23 号的 `pubDate` 吧，怎么你贴进来的是 27 的日期呢？

**Comment by SlightDust** [comment]
> 看了下代码，`pubDate` 字段是用的 wise 接口返回的最新一天的 `time` 字段填入的，你 23 号的汇率就应该是 23 号的 `pubDate` 吧，怎么你贴进来的是 27 的日期呢？

6月27号。之后pubDate再也没更新过

**Comment by SlightDust** [comment]
忽然发现汇率也不对，查到的结果也是6月27号的汇率。wise那边可能改接口了

**Comment by SlightDust** [comment]
哎刚刚好像忽然正常更新了，先close了
