### ISSUE TITLE
演示站的“大学通知”模块，好多挂了

### ISSUE THREAD

**Issue by hyxxsfwy** [DIYgod/RSSHub#1690]
### 路由地址
比如这三个：

`/universities/uestc/jwc/:type?`
[https://rsshub.app/uestc/jwc/student](https://rsshub.app/uestc/jwc/student)

`/universities/swust/jwc/notice/:type?`
[https://rsshub.app/uestc/jwc/student](https://rsshub.app/uestc/jwc/student)

`/buaa/news/:type`
[https://rsshub.app/buaa/news/zonghe](https://rsshub.app/buaa/news/zonghe)

### 预期是什么？
返回正确的 XML

### 实际发生了什么？
各种类型的报错……

**Comment by HenryQW** [comment]
很多大学在某些会议期间屏蔽境外 IP，RSSHub demo 服务器位于境外。

**Comment by DIYgod** [comment]
信了 Henry 的鬼 af1df7f1788aa9070f48170b8a844cc8ddaaa2d5
