### ISSUE TITLE
rsshub pixiv not working anymore - fetcherror

### ISSUE THREAD

**Issue by ILudw1g** [DIYgod/RSSHub#16903]
### Routes

```routes
/pixiv/user/:id
```

### Full routes

```fullroutes
/pixiv/user/29268484
```

### Related documentation

https://docs.rsshub.app/routes/social-media#pixiv

### What is expected?

rss feed to show and able to add to rss feeds. but i'm not able to do this because of this issue

furthermore the pixiv rss feeds already added are not returning items to feed anymore.

getting: 
FetchError: [POST] "https://oauth.secure.pixiv.net/auth/token": <no response> Number of requests reached it's maximum 500

### What is actually happening?

the pixiv rss feeds already added are not returning items to feed anymore.
and i am not able to add more to the rss feed because of this fetch error

getting:
FetchError: [POST] "https://oauth.secure.pixiv.net/auth/token": <no response> Number of requests reached it's maximum 500

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
FetchError: [POST] "https://oauth.secure.pixiv.net/auth/token": <no response> Number of requests reached it's maximum 500

the pixiv rss feeds already added are not returning items to feed anymore.
and i am not able to add more to the rss feed because of this fetch error
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
It works.

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/6580f0eb-d9d9-4bcc-8eaf-fe5cdb3475eb)
</details>

**Comment by ILudw1g** [comment]
its still not working for me it seems 
![image](https://github.com/user-attachments/assets/674392d9-bcda-415c-95a2-dd22a1577159)
