### ISSUE TITLE
Cannot convert argument to a ByteString because the character at index 364 has a value of 8220 which is greater than 255.

### ISSUE THREAD

**Issue by lz37** [DIYgod/RSSHub#16924]
### 路由地址

```routes
/bilibili/hot-search
```

### 完整路由地址

```fullroutes
/bilibili/hot-search?key=xxx
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%83%AD%E6%90%9C

### 预期是什么？

正常处理unicode

### 实际发生了什么？

未正常处理unicode

debug info:

```markdown
Git Hash:[d5f7821d](https://github.com/DIYgod/RSSHub/commit/d5f7821d)
Git Date:Tue, 24 Sep 2024 07:25:20 GMT
Cache Duration:300s
Request Amount:1
Request Frequency:12.892 times/minute
Cache Hit Ratio:0.00%
ETag Matched Ratio:0.00%
Health:100.00%
Uptime:0.00 hour(s)
Hot Routes:
Hot Paths:1 /
Hot Error Routes:
Hot Error Paths:
```

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

docker: chromium-bundled-2024-09-25

### 额外信息

```shell
info: Redis connected.
info: 🎉 RSSHub is running on port 1200! Cheers!
info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/sponsor>
info: 🔗 Local: 👉 http://localhost:1200>
info: 🔗 Network: 👉 http://10.244.3.151:1200>
info: 🔗 Network: 👉 http://[::]:1200>
info: <-- GET /bilibili/hot-search
error: Error in /bilibili/hot-search: TypeError: Cannot convert argument to a ByteString because the character at index 364 has a value of 8220 which is greater than 255.
info: --> GET /bilibili/hot-search 503 2s
info: <-- GET /logo.png
info: --> GET /logo.png 200 4ms
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by CaoMeiYouRen** [comment]
无法复现这个问题。
可能是热搜中存在问题的字符已经不在了，如果下次再遇到，可以尝试记录下热搜的具体内容，以排查问题。

**Comment by Mynanase** [comment]
奇怪，我也有一样的问题，重新登陆 b 站后，填入新生成 cookies 一切正常了

**Comment by la1den** [comment]
我也有同样的问题，从Firefox复制cookies填到 `BILIBILI_COOKIE_data` 环境变量中会出现这样的问题，但是chromium是正常的。
```
rsshub-1       | (node:47) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
rsshub-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
rsshub-1       | info: Redis connected.
rsshub-1       | info: 🎉 RSSHub is running on port 1200! Cheers!
rsshub-1       | info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/sponsor
rsshub-1       | info: 🔗 Local: 👉 http://localhost:1200
rsshub-1       | info: 🔗 Network: 👉 http://172.18.0.5:1200
rsshub-1       | info: 🔗 Network: 👉 http://[::]:1200
browserless-1  | 2024-10-06T06:55:52.412Z browserless:hardware Checking overload status: CPU 5% Memory 14%
rsshub-1       | info: <-- GET /bilibili/user/video/4184067
rsshub-1       | error: Error in /bilibili/user/video/4184067: TypeError: Cannot convert argument to a ByteString because the character at index 512 has a value of 8230 which is greater than 255.
```

**Comment by XiXiLocked** [comment]
> 我也有同样的问题，从Firefox复制cookies填到 `BILIBILI_COOKIE_data` 环境变量中会出现这样的问题，但是chromium是正常的。
> 
> ```
> rsshub-1       | (node:47) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> rsshub-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
> rsshub-1       | info: Redis connected.
> rsshub-1       | info: 🎉 RSSHub is running on port 1200! Cheers!
> rsshub-1       | info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/sponsor
> rsshub-1       | info: 🔗 Local: 👉 http://localhost:1200
> rsshub-1       | info: 🔗 Network: 👉 http://172.18.0.5:1200
> rsshub-1       | info: 🔗 Network: 👉 http://[::]:1200
> browserless-1  | 2024-10-06T06:55:52.412Z browserless:hardware Checking overload status: CPU 5% Memory 14%
> rsshub-1       | info: <-- GET /bilibili/user/video/4184067
> rsshub-1       | error: Error in /bilibili/user/video/4184067: TypeError: Cannot convert argument to a ByteString because the character at index 512 has a value of 8230 which is greater than 255.
> ```
> 
> 估计是Firefox的cookies不能给puppeteer用

感谢，要不是这个回复我还在找代码的问题。
另外并不是不能用，是复制时的操作问题。

Firefox会在*显示*的时候会缩略过长的cookie，中间就会有类似`…`的东西。鼠标选取cookie然后复制，此时复制到的是缩略的cookie，就会有上述问题。
解决方法是不要鼠标划取选cookie，而是要右键 `复制值`，这样才能拿到完整的cookie。
