### ISSUE TITLE
rsshub.app演示站小宇宙路由失效

### ISSUE THREAD

**Issue by IwfWcf** [DIYgod/RSSHub#16920]
### 路由地址

```routes
/xiaoyuzhou/podcast/:id
```

### 完整路由地址

```fullroutes
/xiaoyuzhou/podcast/6021f949a789fca4eff4492c
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#%E5%B0%8F%E5%AE%87%E5%AE%99

### 预期是什么？

提供小宇宙播客的rss

### 实际发生了什么？

展示的是错误页面

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://www.xiaoyuzhoufm.com/podcast/6021f949a789fca4eff4492c": <no response> Number of requests reached it's maximum 500

Route: /xiaoyuzhou/podcast/:id

Full Route: /xiaoyuzhou/podcast/6021f949a789fca4eff4492c

Node Version: v22.9.0

Git Hash: 4be28ac2

Git Date: Mon, 23 Sep 2024 08:46:57 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/xiaoyuzhou/podcast/6021f949a789fca4eff4492c
```

**Comment by IwfWcf** [comment]
> /test
> 
> ```
> /xiaoyuzhou/podcast/6021f949a789fca4eff4492c
> ```

这里指的是 rsshub.app 演示站里的错误

https://rsshub.app/xiaoyuzhou/podcast/6021f949a789fca4eff4492c

**Comment by TonyRL** [comment]
Duplicate of #16849.

**Comment by TonyRL** [comment]
> The official demo instances are for demonstration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability.
