### ISSUE TITLE
知乎专栏404

### ISSUE THREAD

**Issue by zWingz** [DIYgod/RSSHub#1693]
### 路由地址
https://rsshub.app/zhihu/zhuanlan/diygod

### 预期是什么？
返回正确的xml

### 实际发生了什么？
返回404

**Comment by yefoenix** [comment]
知乎反爬严重，需要自建服务

**Comment by zWingz** [comment]
@yefoenix 好的

**Comment by lilydjwg** [comment]
这个专栏本来就不存在吧。
