### ISSUE TITLE
【中华网-滚动新闻】pubDate有误

### ISSUE THREAD

**Issue by katfionn** [DIYgod/RSSHub#16959]
### 路由地址

```routes
/china/news/:category?
```

### 完整路由地址

```fullroutes
/china/news/news100
```

### 相关文档

https://docs.rsshub.app/routes/new-media#news-and-current-affairs-%E6%97%B6%E4%BA%8B%E6%96%B0%E9%97%BB

### 预期是什么？

pubDate的值与文章实际发布时间对应上

## 时间都变成了当天0点

如下图
![image](https://github.com/user-attachments/assets/eb064d00-c94d-4524-bca7-d15e5a5f4d75)

按图中，`Sat, 28 Sep 2024 16:00:00 GMT`解析为时区是上海的、格式是ISO9075的，解析结果是：2024-09-29 00:00:00
![image](https://github.com/user-attachments/assets/974d9ae2-e99b-4075-af86-219df8f36063)

我使用python的dateutil库解析，结果也是一样的

而查看实际网页可得知，文章的实际发布时间是当天11点05分40秒

### 部署

自建

### 部署相关信息

OS：Linux Docker：v24.08.23

### 额外信息

```shell
安装rsshub时一起安装的
puppeteer版本：1-puppeteer-10.4.0
redis版本：7.4.0-alpine
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AntiKnot** [comment]
For this issue, `route /china/news/new100`.
The element in the list page can only obtain **date** information. The accurate **datetime** information only exists in the detail page.

So, it's okay `timezone +8`, `Sat, 28 Sep 2024 16:00:00 GMT`.

**Comment by katfionn** [comment]
> For this issue, `route /china/news/new100`. The element in the list page can only obtain **date** information. The accurate **datetime** information only exists in the detail page.
> 
> So, it's okay `timezone +8`, `Sat, 28 Sep 2024 16:00:00 GMT`.

I see, thanks
