### ISSUE TITLE
请求 Unity Connect 的 RSS

### ISSUE THREAD

**Issue by Latias94** [DIYgod/RSSHub#1698]
### 源站地址
源站：[https://connect.unity.com/](https://connect.unity.com/)
希望抓取的专栏示例：[https://connect.unity.com/t/59700e200909150016f02e3a/column](https://connect.unity.com/t/59700e200909150016f02e3a/column)

### 需要生成什么内容？

- [ ] 标题和摘要
- [ ] 文章地址

### 额外描述
https://connect.unity.com/t/59700e200909150016f02e3a/column 中 59700e200909150016f02e3a 是专栏 id
网页用 React 构建，文章地址数据存在 window.__props__ 里面

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
