### ISSUE TITLE
douyin   RSS

### ISSUE THREAD

**Issue by hhxy11** [DIYgod/RSSHub#17003]
### 类型

新媒体

### 网站地址

www.douyin.com

### 网站描述

china 's  tiktok，it‘s  old  RSS  doesn't  work nowaday

### 需要生成什么内容？

抖音直播，抖音收藏视频，老的RSS源无法使用

### 额外描述

国内版的抖音

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #12029
