### ISSUE TITLE
RSS需求：下厨房系列rss

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1701]
### 源站地址
https://www.xiachufang.com
### 需要生成什么内容？

- [ ] 菜谱分类，如 https://www.xiachufang.com/category/40073/
- [ ] 个人动态（概况/ 菜谱/ 作品），如 https://www.xiachufang.com/cook/10021396/
- [ ] 探索推荐：本周最受欢迎/新秀菜谱/月度最佳等，见 https://www.xiachufang.com/explore/
### 额外描述
移动站点 http://m.xiachufang.com 供参考

**Comment by yefoenix** [comment]
不好意思，刚才 doc 卡了没搜到……

**Comment by ushuz** [comment]
Duplicate #303
