### ISSUE TITLE
【微博】博主和超话两个路由失效

### ISSUE THREAD

**Issue by mengx8** [DIYgod/RSSHub#17017]
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
/weibo/super_index/:id/:type?/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/5117510254
/weibo/super_index/100808c0f7ece6136c4ef41c3818f21c82a1ee/sort_time
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E5%8D%9A%E4%B8%BB-1

### 预期是什么？

正常输出内容

### 超话路由不存在
`Error Message:
Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

Route: /weibo/super_index/:id/:type?/:routeParams?

Full Route: /weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time

Node Version: v22.9.0

Git Hash: 77bf780b

Git Date: Sun, 06 Oct 2024 18:08:31 GMT`

### 博主路由报错
`Error Message:
TypeError: Cannot read properties of undefined (reading 'userInfo')

Route: /weibo/user/:uid/:routeParams?

Full Route: /weibo/user/5117510254

Node Version: v22.9.0

Git Hash: 77bf780b

Git Date: Sun, 06 Oct 2024 18:08:31 GMT`

### 部署

自建

### 额外信息

```shell
超话路由不存在
`Error Message:
Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

Route: /weibo/super_index/:id/:type?/:routeParams?

Full Route: /weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time

Node Version: v22.9.0

Git Hash: 77bf780b

Git Date: Sun, 06 Oct 2024 18:08:31 GMT`

博主路由报错
`Error Message:
TypeError: Cannot read properties of undefined (reading 'userInfo')

Route: /weibo/user/:uid/:routeParams?

Full Route: /weibo/user/5117510254

Node Version: v22.9.0

Git Hash: 77bf780b

Git Date: Sun, 06 Oct 2024 18:08:31 GMT`
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/weibo/user/5117510254
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time
```

**Comment by TonyRL** [comment]
It works.

**Comment by leenacl** [comment]
你好，我也出现了这个问题。请问你的之后恢复了吗

**Comment by YsMox** [comment]
/test
```
/weibo/user/5204548725
```

**Comment by YsMox** [comment]
/test

```
/weibo/user/5204548725
/weibo/user/5117510254
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time
```

**Comment by Summerrrr2n** [comment]
Auto-Reply
 感谢你的邮件，我已经收到~
