### ISSUE TITLE
华中科技大学研究生院路由失效无法连接

### ISSUE THREAD

**Issue by ProudBenzene** [DIYgod/RSSHub#17032]
### 路由地址

```routes
/hust/gs/:category{.+}?
```

### 完整路由地址

```fullroutes
/hust/gs/tzgg
```

### 相关文档

https://docs.rsshub.app/zh/routes/university#%E7%A0%94%E7%A9%B6%E7%94%9F%E9%99%A2-6

### 预期是什么？

希望能正常抓取到学院通知 #16595 

### 实际发生了什么？

RSSHub无法连接该路由：

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/f6814d7e-ab9f-44c5-92c3-edc4a1f0b1e0">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://gs.hust.edu.cn/tzgg.htm": <no response> Number of requests reached it's maximum 5000

Route: /hust/gs/:category{.+}?

Full Route: /hust/gs/tzgg

Node Version: v22.9.0

Git Hash: 00d66286

Git Date: Mon, 07 Oct 2024 14:37:15 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nczitzk** [comment]
你好，请尝试自建 RSSHub 或使用其他 [公共实例](https://docs.rsshub.app/zh/guide/instances) 订阅该路由。另外，请按分类订阅 [通知公告](https://gs.hust.edu.cn/tzgg/kcjksap.htm)：

- 课程及考试安排：`/hust/gs/tzgg/kcjksap`
- 国际交流：`/hust/gs/tzgg/gjj`
- 学位工作：`/hust/gs/tzgg/xwgz`
- 同济医学院：`/hust/gs/tzgg/tjyxy`
- 其他：`/hust/gs/tzgg/qt`

**Comment by ProudBenzene** [comment]
明白了，谢谢您的帮助！！
