### ISSUE TITLE
IT之家的路由“标签”，订阅出错

### ISSUE THREAD

**Issue by April-BOY** [DIYgod/RSSHub#17076]
### 路由地址

```routes
/ithome/tag/:name
```

### 完整路由地址

```fullroutes
https://rsshub.app/ithome/tag/5g
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E6%A0%87%E7%AD%BE

### 预期是什么？

希望可以正常订阅

### 实际发生了什么？

浏览器直接访问订阅地址 https://rsshub.app/ithome/tag/5g 时可以获取到内容，但是使用RSS客户端订阅时提示如下：
IT之家 - 5g标签: https://rsshub.app/ithome/tag/5g 多次抓取失败，建议取消订阅 Request failed with status code 429 Too Many Requests

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
IT之家 - 5g标签: https://rsshub.app/ithome/tag/5g 多次抓取失败，建议取消订阅 Request failed with status code 429 Too Many Requests
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/ithome/tag/5g
```

**Comment by TonyRL** [comment]
It works.
