### ISSUE TITLE
Twitter route stopped working? (Username+password login)

### ISSUE THREAD

**Issue by D0peCrack** [DIYgod/RSSHub#17089]
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
twitter/user/elonmusk/readable=0&authorNameBold=0&showAuthorInTitle=1&showAuthorInDesc=0&showSymbolForRetweetAndReply=0&showRetweetTextInTitle=0&addLinkForPics=1&&heightOfPics=200
```

### Related documentation

normal rsshub docs

### What is expected?

return elon musk twitter info

### What is actually happening?

Error Message:
FetchError: [POST] "https://api.x.com/1.1/onboarding/task.json": 403 Forbidden

Route: /twitter/user/:id/:routeParams?

### Deployment information

Self-hosted

### Additional info

```shell
Could anyone check it. 
My setup worked like 2 weeks ago. 
i signup via username and password
currently it doesnt work
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by D0peCrack** [comment]
and my ip is not blocked and i can sign in to my account with no problem

**Comment by murichazuke** [comment]
The 403 error came from AccountDuplicationCheck, and it looks like LoginEnterPassword now returns tokens. I made some changes, and the login was successful.

```diff
diff --git a/lib/routes/twitter/api/mobile-api/login.ts b/lib/routes/twitter/api/mobile-api/login.ts
index 1e4c4570f..7aceffb53 100644
--- a/lib/routes/twitter/api/mobile-api/login.ts
+++ b/lib/routes/twitter/api/mobile-api/login.ts
@@ -133,6 +133,11 @@ async function login({ username, password, authenticationSecret }) {
                     },
                 });
                 logger.debug('Twitter login 4 finished: LoginEnterPassword.');
+                for (const subtask of task3.data?.subtasks || []) {
+                    if (subtask.open_account) {
+                        return subtask.open_account;
+                    }
+                }
```
