### ISSUE TITLE
配置 ACCESS_KEY 导致 healthcheck 失败

### ISSUE THREAD

**Issue by bestlzk** [DIYgod/RSSHub#17090]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/healthz
```

### 相关文档

null

### 预期是什么？

rsshub-rsshub-1健康检查应该是正常的

### 实际发生了什么？

由于配置了 ACCESS_KEY，健康检查请求 /healthz 路径会报错，需要取消 /healthz 路径的 ACCESS_KEY 校验

### 部署

自建

### 额外信息

```shell
rsshub-rsshub-1       | info: <-- GET /healthz
rsshub-rsshub-1       | error: Error in /healthz: RejectError: Authentication failed. Access denied.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by bxb100** [comment]
docker healthz 加上 `?key=你的 key`

**Comment by bestlzk** [comment]
> docker healthz 加上 `?key=你的 key`

手动配置后没有问题了
