### ISSUE TITLE
财新网 内容更新提醒失效

### ISSUE THREAD

**Issue by fengjychn** [DIYgod/RSSHub#17094]
### 路由地址

```routes
/caixin/latest
```

### 完整路由地址

```fullroutes
https://rsshub.app/caixin/latest
```

### 相关文档

https://docs.rsshub.app/routes/traditional-media

### 预期是什么？

正常工作，获取财新网最新更新内容

### 实际发生了什么？

最新更新内容一直停留在18/9/2024.
![截图_20241012092813](https://github.com/user-attachments/assets/97b92635-52d2-4ff4-958e-df9bdf4a8e3f)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/caixin/latest
```

**Comment by TonyRL** [comment]
It works with the latest content returned.
