### ISSUE TITLE
【UK Parliament】只能抓到3条内容，网页上单页15条

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#17106]
### 路由地址

```routes
/parliament.uk/commonslibrary/type/:topic?
```

### 完整路由地址

```fullroutes
/parliament.uk/commonslibrary/type/:topic?
```

### 相关文档

https://docs.rsshub.app/routes/government#uk-parliament

### 预期是什么？

能够抓取更多的内容，按照时间倒序排列

### 实际发生了什么？

1、只能抓3条，Commonlibrary 和 House of Lords Library 都是这样
2、路由对应页面错误，两院全部都是 https://commonslibrary.parliament.uk/type ，指向type 这个错误页面

路由的内容摘录如下
```
<link>https://commonslibrary.parliament.uk/type</link>
<atom:link href="http://rsshub.app/parliament.uk/commonslibrary/type/data-dashboard" rel="self" type="application/rss+xml"/>
```

应该是https://commonslibrary.parliament.uk/type/data-dashboard/  ， https://commonslibrary.parliament.uk/type/research-briefing/  和 https://lordslibrary.parliament.uk/type/research-briefing/

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

麻烦 @AntiKnot 哥

在网页中，我通过查看源代码，发现对应每个超链接的结构如下，搜``` <div class="l-box l-box--no-border card__text">``` 能搜到15个结果

```shell
<div class="l-box l-box--no-border card__text">

                                <p class="card__type">Data dashboards</p>

                    <h2 class="card__heading font-size-epsilon">
                <a class="card__link" href="https://commonslibrary.parliament.uk/constituency-data-lgbt-people-2021-census/">Constituency data: LGBT+ people</a>
            </h2>
        

        <p class="card__date">
            <time datetime="2024-09-20">Friday, 20 September, 2024</time>
        </p>
```

还有
```
    <div class="l-box l-box--no-border card__text">
        <h2 class="card__heading font-size-gamma">
            <a class="card__link" href="https://commonslibrary.parliament.uk/research-briefings/sn07158/">City Deals</a></h2>
        <p class="card__date"><time datetime="2024-10-11" >Friday, 11 October, 2024</time></p>
```
```


### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AntiKnot** [comment]
@KwToPA 

1. 头版消息和历史消息，我没有进行解析拼接处理，只处理了最新的头版3条信息。
2. 现有路由通过了测试，请给出相关的path，需要更详细的信息。
3. 如果有type相关的错误，请给出相关信息。

本地正常 http://localhost:1200/parliament.uk/commonslibrary/type/data-dashboard 
follow正常 rsshub://parliament.uk/commonslibrary/type/data-dashboard

**Comment by KwToPA** [comment]
> @KwToPA
> 
> 1. 头版消息和历史消息，我没有进行解析拼接处理，只处理了最新的头版3条信息。
> 2. 现有路由通过了测试，请给出相关的path，需要更详细的信息。
> 3. 如果有type相关的错误，请给出相关信息。
> 
> 本地正常 http://localhost:1200/parliament.uk/commonslibrary/type/data-dashboard follow正常 rsshub://parliament.uk/commonslibrary/type/data-dashboard

这三个路由

https://rsshub.app/parliament.uk/commonslibrary/type/research-briefing

https://rsshub.app/parliament.uk/commonslibrary/type/data-dashboard

https://rsshub.app/parliament.uk/lordslibrary/type/research-briefing

对应两个链接 ```<link>https://lordslibrary.parliament.uk/type</link>```和```<link>https://commonslibrary.parliament.uk/type</link>``` 

其中一个例子见截图
![image](https://github.com/user-attachments/assets/b0501745-2f18-42ba-ae78-105ff7fa102e)


实际的对应网页应该是这三个

https://commonslibrary.parliament.uk/type/data-dashboard/ 

https://commonslibrary.parliament.uk/type/research-briefing/ 

https://lordslibrary.parliament.uk/type/research-briefing/

这个type网站打不开
![image](https://github.com/user-attachments/assets/a1f411fb-796e-4639-969b-fdf823f24351)

我用ttrss订阅，有个右键打开路由对应的网页，本来应该是打开上面三个，结果是后缀为type的这个网页。

另外 单页15个内容，只抓了三条，网页上应该只有样式的分别，不是历史内容和头版内容的分别，见图

![image](https://github.com/user-attachments/assets/038e789b-e1e7-46d8-a4f3-718fe9951cf0)
