### ISSUE TITLE
希望小红书路由可以拉取到笔记正文

### ISSUE THREAD

**Issue by ProudBenzene** [DIYgod/RSSHub#17107]
### 路由地址

```routes
/xiaohongshu/user/:user_id/:category
```

### 完整路由地址

```fullroutes
https://rsshub.app/xiaohongshu/user/593032945e87e77791e03696/notes
```

### 相关文档

https://docs.rsshub.app/zh/routes/popular#%E7%94%A8%E6%88%B7%E7%AC%94%E8%AE%B0

### 预期是什么？

希望小红书路由可以拉取到笔记的正文。

### 实际发生了什么？

目前仅能拉取到首图与标题。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
这条需求可能与路由作者的意见并不相通。如果作者您觉得这条需求没有必要的话，请忽视这条issue。

感谢作者的无私奉献！
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #16300

**Comment by hujh818** [comment]
+1 现在是基于浏览器的方案 希望能切换到基于cookie的方案
