### ISSUE TITLE
Vercel部署RSSHub报错

### ISSUE THREAD

**Issue by imrayyu** [DIYgod/RSSHub#17118]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

NOROUTE

### 预期是什么？

NOROUTE

### 实际发生了什么？

NOROUTE

### 部署

自建

### 额外信息

```shell
Error: Found invalid Node.js Version: ">=22". Please set "engines": { "node": "20.x" } in your `package.json` file to use Node.js 20.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #14622
