### ISSUE TITLE
联合早报不更新了

### ISSUE THREAD

**Issue by jfdnet** [DIYgod/RSSHub#17119]
### 类型

传统媒体

### 网站地址

www.zaobao.com.sg

### 网站描述

联合早报 即时新闻

### 需要生成什么内容？

现有源不更新了

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
This is not an RSS proposal.
