### ISSUE TITLE
dribble 不能获取用户的rss

### ISSUE THREAD

**Issue by dddaniel1** [DIYgod/RSSHub#17110]
### 路由地址

```routes
/dribbble/user/:name
```

### 完整路由地址

```fullroutes
https://rsshub.app/dribbble/user/google
```

### 相关文档

https://docs.rsshub.app/zh/routes/design#user-or-team

### 预期是什么？

获取到rss

### 实际发生了什么？

FetchError: [GET] "https://dribbble.com/shots/24896753": 429 Too Many Requests

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://dribbble.com/shots/17008018": 429 Too Many Requests

Route: /dribbble/user/:name

Full Route: /dribbble/user/google

Node Version: v22.9.0

Git Hash: 471d146d

Git Date: Mon, 07 Oct 2024 00:54:44 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
![CleanShot 2024-10-19 at 22 22 33@2x](https://github.com/user-attachments/assets/472f5c42-2fd3-45a4-bcc0-65376146e9d0)

Dribble has strict rate limit even for real user using browser, will try to find ways to resolve it.
