### ISSUE TITLE
BBC only updated since 18th Sep

### ISSUE THREAD

**Issue by cufezhusy** [DIYgod/RSSHub#17111]
### Routes

```routes
/bbc/:site?/:channel?
```

### Full routes

```fullroutes
/bbc/:site?/:channel?
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#news-2

### What is expected?

The RSS feed not updated since 18th Sep, if looking at the raw BBC feed, it got updated accordingly.

[https://feeds.bbci.co.uk/news/world/asia/rss.xml](url)

### What is actually happening?

RSS feed not updated since 18th Sep.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
If deploy RSS hub locally, can see it got updated. Looks like the issue is on the server side.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
this route works well but the official instance are responding slow or failed, please consider use other [public instances](https://docs.rsshub.app/guide/instances) or deploy yourself to resolve this issue.
