### ISSUE TITLE
Some Telegram channels not working

### ISSUE THREAD

**Issue by regystro** [DIYgod/RSSHub#17112]
### Routes

```routes
/telegram/channel/:username/:routeParams?
```

### Full routes

```fullroutes
/telegram/channel/chollodomotica
```

### Related documentation

https://docs.rsshub.app/routes/social-media#telegram

### What is expected?

The channel feed rendered as always.

### What is actually happening?

Error: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/chollodomotica

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
https://rsshub.app/telegram/channel/chollodomotica throws same error.

In my self-hosted instance, it worked until 27th of september:
Route: /telegram/channel/:username/:routeParams?
Full Route: /telegram/channel/chollodomotica
Node Version: v22.9.0
Git Hash: 9376572d
Git Date: Sat, 12 Oct 2024 20:09:59 GMT

The URL https://t.me/s/chollodomotica works perfectly. I can browse the channel, and see it from https://web.telegram.org/ without problems.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please do read the tips in the docs 

> Due to Telegram restrictions, some channels involving pornography, copyright, and politics cannot be subscribed. You can confirm by visiting `https://t.me/s/:username`.

and the error message carefully.

> Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: [t.me/s/chollodomotica](https://t.me/s/chollodomotica)

`t.me/s/chollodomotica` **does not** return any message preview.

`https://t.me/s/awesomeRSSHub` this is what a subscribable channel and message preview will look like.
`https://t.me/awesomeRSSHub` this is what a non-subscribable channel will look like.

**Comment by regystro** [comment]
I never saw a preview like https://t.me/s/awesomeRSSHub and hence I thought it was working OK. Thanks for the clarification.
