### ISSUE TITLE
希望添加小说网站（笔趣阁/UU看书/...）的全文输出

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#1712]
### 这是一个什么样的功能？

RT

### 这个功能可以解决什么问题？

You see.

### 额外描述

That's all.

**Comment by HenryQW** [comment]
希望支持正版, you see, piracy hurts, that's it.

**Comment by ifwangs** [comment]
用tg的rss机器人啊+即时预览吧

**Comment by aka-rin** [comment]
> 用tg的rss机器人啊+即时预览吧

嘘 小声（
