### ISSUE TITLE
中国知网rsshub链接超限，海外链接无法访问知网，可否在rsshub radar中增加https://rss.cnki.net/kns/rss.aspx?Journal=Name&Virtual=knavi格式链接？

### ISSUE THREAD

**Issue by yzy1228682367** [DIYgod/RSSHub#17146]
### 路由地址

```routes
/cnki/journals/:name
```

### 完整路由地址

```fullroutes
/cnki/journals/:name
```

### 相关文档

https://docs.rsshub.app/routes/journal

### 预期是什么？

预期正确订阅期刊。

### 实际发生了什么？

实际未正确订阅期刊。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

macos

### 额外信息

```shell
https://rss.cnki.net/kns/rss.aspx?Journal=Name&Virtual=knavi
以上文链接形式可以正确订阅期刊，name是期刊缩写，可以在网址中得到。
```
![CleanShot 2024-10-15 at 21 01 02@2x](https://github.com/user-attachments/assets/ca2c4a2d-80d5-4498-81d7-015cd5ef35c1)
![CleanShot 2024-10-15 at 21 01 51@2x](https://github.com/user-attachments/assets/00a1addc-70c8-4b3d-8031-6c7d501b16bd)

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
Fixed.

1. use `https://rss.cnki.net/kns/rss.aspx?Journal=Name&Virtual=knavi` and now the cnki journal route works.
2. added to rsshub radar.
