### ISSUE TITLE
知乎她挂了，APP辣么难用还不让RSS，啊啊啊啊啊

### ISSUE THREAD

**Issue by XHZ25** [DIYgod/RSSHub#1715]
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/54078069-d74c5e00-42b9-11e9-9c90-9efd4f349849.png)
有这个标记的路由，想要稳定请自建。

**Comment by XHZ25** [comment]
谢谢你哈，我学一下自建。

________________________________
发件人: Henry Wang <notifications@github.com>
发送时间: Sunday, March 10, 2019 6:23:07 AM
收件人: DIYgod/RSSHub
抄送: XH ZHOU; Author
主题: Re: [DIYgod/RSSHub] 知乎她挂了，APP辣么难用还不让RSS，啊啊啊啊啊 (#1715)


[image]<https://user-images.githubusercontent.com/5896343/54078069-d74c5e00-42b9-11e9-9c90-9efd4f349849.png>
有这个标记的路由，想要稳定请自建。

―
