### ISSUE TITLE
Enhance PR Testing Process: Implement Retry Mechanism and Expand `/test` Command Functionality

### ISSUE THREAD

**Issue by NekoAria** [DIYgod/RSSHub#17151]
### What feature is it?

Improve the PR testing process, specifically:

1. Implement a retry mechanism for Puppeteer routes that are likely to time out after 30 seconds.
2. Enhance the `/test` command to be applicable for testing changes in PRs, not just the master branch.

### What problem does this feature solve?

1. Currently, Puppeteer routes often time out after 30 seconds, resulting in 503 errors. There are no subsequent attempts to retest after such failures, leading to unreliable test results.
2. The `/test` command is currently limited to testing the RSSHub running status of the master branch in the current repository. This doesn't allow for effective testing of changes proposed in PRs.

### Additional description

Implementing these features would significantly improve the reliability and efficiency of our testing process.
It would reduce false negatives in our CI pipeline and allow contributors to more effectively test their changes before merging.

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
The `/test` command does not cover PRs since one can trigger it by an empty commit or editting the PR title/description, which IMHO much faster than typing `/test` and copy pasting the `\`\`\`routes\`\`\`` section.

**Comment by NekoAria** [comment]
> The `/test` command does not cover PRs since one can trigger it by an empty commit or editting the PR title/description, which IMHO much faster than typing `/test` and copy pasting the ```routes``` section.

However, this method doesn't support testing specific routes only, such as when previous test results returned 503 errors. Specifically, I'm referring to the situation I encountered in my previous PR: #17131.

Currently, if I only want to test the following routes, it's not possible to do so.

```routes
/picuki/profile/stefaniejoosten/tagged
/picuki/profile/stefaniejoosten/tagged/0
```

**Comment by NekoAria** [comment]
Additionally, this is the testing process I conducted in my forked repository: https://github.com/NekoAria/RSSHub/pull/2.
This should give you a clear understanding of why I believe this feature is meaningful.
