### ISSUE TITLE
飞客路由访问不了

### ISSUE THREAD

**Issue by hack2012** [DIYgod/RSSHub#17165]
### Routes

```routes
/flyert/creditcard/:bank
```

### Full routes

```fullroutes
/flyert/creditcard/creditcard
```

### Related documentation

https://docs.rsshub.app/zh/routes/travel#%E4%BF%A1%E7%94%A8%E5%8D%A1

### What is expected?

在群晖上使用docker部署，访问时返回403，不知是否和飞客域名变化有关，但是[rssfor](https://rsshub.rssforever.com/)这个又可以，不知道是怎么配置的

### What is actually happening?

![403](https://github.com/user-attachments/assets/fdeac63b-b89e-44c7-a6a9-ebcedb53e4b3)
![WX20241017-104955@2x](https://github.com/user-attachments/assets/8fbf7b9d-52bb-4d49-9af7-1b5e87e0621e)

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Node Version: v22.9.0，群晖7.2.2

### Additional info

```shell
services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - "1200:1200"
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis          # 缓存类型，支持 memory 和 redis
            CACHE_EXPIRE: 600          # 路由缓存过期时间，秒
            CACHE_CONTENT_EXPIRE: 600  # 内容缓存过期时间，秒
            REQUEST_RETRY: 5           # 请求失败重试次数
            REQUEST_TIMEOUT: 30000     # 请求超时毫秒数
            # UA:                      # 指定 User-Agent，默认随机
            REDIS_URL: 'redis://redis:6379/'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:1200/healthz"]
            interval: 3600s
            timeout: 10s
            retries: 3
        depends_on:
            - redis
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
You may try to pull latest RSSHub image? It works on my instance without any related configs.

**Comment by hack2012** [comment]
I am using the latest mirror image. It is still the same problem. Please help me take a look.
And the domain name of the original station changed, is it related to this?

**Comment by hack2012** [comment]
Before I installed it on my home Synvision, it was not available. Today I also pulled the latest image on my company computer, but it was also inaccessible. Please confirm.

![WX20241024-155434@2x](https://github.com/user-attachments/assets/7e9b85eb-923e-4403-9af7-ae2039713636)

**Comment by hack2012** [comment]
一直无法使用，现在返回493错误。
