### ISSUE TITLE
PIXIV_IMG_PROXY is not work

### ISSUE THREAD

**Issue by dycwuxing** [DIYgod/RSSHub#17161]
### 路由地址

```routes
/pixiv/user/:id
```

### 完整路由地址

```fullroutes
/pixiv/user/13591863
```

### 相关文档

https://docs.rsshub.app/deploy/config#route-specific-configurations

### 预期是什么？

Able to recognize images normally through image proxy

### 实际发生了什么？

Unable to open "img src="https://pixiv.re/img-original/img/2023/12/18/01/36/49/114322178_p0.png"
Open in the browser prompt "Cannot GET /img-original/img/2023/12/18/01/36/49/114322178_p0.png"
If you manually switch to use a proxy, everything is normal "https://pixiv.re/114322178.png"

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
<item>
<title>🌸</title>
<description>お久しぶりです<br><p>画师：すうぇたー - 阅览数：579 - 收藏数：110</p><p><img src="https://pixiv.re//img-original/img/2023/12/18/01/36/49/114322178_p0.png" width="3712" height="4928" referrerpolicy="no-referrer"></p></description>
<link>https://www.pixiv.net/artworks/114322178</link>
<guid isPermaLink="false">https://www.pixiv.net/artworks/114322178</guid>
<pubDate>Sun, 17 Dec 2023 16:36:49 GMT</pubDate>
<author>すうぇたー</author>
<category>女の子</category>
<category>オリジナル</category>
<category>少女</category>
<category>AIart</category>
</item>
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by NekoAria** [comment]
This is your own issue. The document clearly states that the default is `i.pixiv.re`, but the domain in the address you provided is `pixiv.re`.

If the domain is `i.pixiv.re`, the complete address is:

`https://i.pixiv.re/img-original/img/2023/12/18/01/36/49/114322178_p0.png`

It can be opened normally.
