### ISSUE TITLE
豆瓣话题失效

### ISSUE THREAD

**Issue by haowenwu** [DIYgod/RSSHub#17186]
### 路由地址

```routes
/douban/topic/:id/:sort?
```

### 完整路由地址

```fullroutes
/douban/topic/48823
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#话题

### 预期是什么？

有内容

### 实际发生了什么？

无内容

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
failed
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
fixed.
