### ISSUE TITLE
Github Trending Rss feeds not working

### ISSUE THREAD

**Issue by KAGEYAM4** [DIYgod/RSSHub#17247]
### Routes

```routes
/github/trending/:since/:language/:spoken_language?
```

### Full routes

```fullroutes
rsshub.app/github/trending/monthly/any
```

### Related documentation

https://docs.rsshub.app/routes/programming#trending

### What is expected?

working rss feed

### What is actually happening?

```
FetchError: [GET] "https://github.com/trending/?since=monthly&spoken_language_code=": <no response> Number of requests reached it's maximum 5000
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

Found -->
https://github.com/DIYgod/RSSHub/issues/16849
https://github.com/DIYgod/RSSHub/issues/16853

Is problem still the same?

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
This route requires GitHub API Token and uses GitHub REST API. It has rate limit of 5000 requests per hour.

Our official instance has too many requests and will be easily reach the rate limit. It's recommended that you may request later or deploy your own instance with personal API Token to have stable service.

refer: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28
