### ISSUE TITLE
「知乎日报」获取失败

### ISSUE THREAD

**Issue by LinxHex** [DIYgod/RSSHub#17325]
### 路由地址

```routes
/zhihu/daily
```

### 完整路由地址

```fullroutes
/zhihu/daily
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%9F%A5%E4%B9%8E%E6%97%A5%E6%8A%A5

### 预期是什么？

正常获取内容。

### 实际发生了什么？

内容获取失败。

### 部署

自建

### 部署相关信息

OS: Linux, Node: v22.10.0, Docker: 27.3.1

### 额外信息

```shell
Git Hash: 5f6d5752
Git Date: Sat, 26 Oct 2024 11:59:37 GMT

FetchError: [GET] "https://news-at.zhihu.com/api/4/news/latest": <no response> fetch failed
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
Yes it use `https://news-at.zhihu.com/api/` api and now it's down. I fixed the `zhihu/daily` route by directly fetching contents from website.
