### ISSUE TITLE
聯合新聞網 修复

### ISSUE THREAD

**Issue by EnterMan123** [DIYgod/RSSHub#17364]
### 路由地址

```routes
/udn/news/breakingnews/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/udn/news/breakingnews/99
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#%E5%8D%B3%E6%99%82%E6%96%B0%E8%81%9E-1

### 预期是什么？

使其恢复可用，所有的分类

### 实际发生了什么？

目前不可用，无法获取最新的资讯，信息更新停滞在几个月前

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
X
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/udn/news/breakingnews/99
```

**Comment by EnterMan123** [comment]
Sorry bro, I didn't check it properly, it's working at the moment
