### ISSUE TITLE
《联合早报》部分失效

### ISSUE THREAD

**Issue by EnterMan123** [DIYgod/RSSHub#17379]
### 路由地址

```routes
/zaobao/realtime/:section?
```

### 完整路由地址

```fullroutes
rsshub://zaobao/realtime/world
rsshub://zaobao/realtime/zfinance
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#%E5%8D%B3%E6%97%B6%E6%96%B0%E9%97%BB

### 预期是什么？

使其可用

### 实际发生了什么？

收不到新文章

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
X
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/zaobao/realtime/world
/zaobao/realtime/zfinance
```

**Comment by TonyRL** [comment]
/test
```routes
/zaobao/realtime/world
```

**Comment by TonyRL** [comment]
It does return the latest content.

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/8d4715f1-be70-4c30-bdbb-fc3a63993912)


</details>

**Comment by EnterMan123** [comment]
![image](https://github.com/user-attachments/assets/76cb7091-63d7-4e00-82b0-746cd320d4a9)
![image](https://github.com/user-attachments/assets/06895964-c1b2-48cb-8dc8-8926c44b707a)
![image](https://github.com/user-attachments/assets/c2c19fd3-5801-450e-95aa-50ecb6ee7fb8)

30 and 10 days ago, respectively.

**Comment by EsuRt** [comment]
《联合早报》的路由确实存在问题，我这边经常无法正常抓取，有时抓取成功的最新文章也是9月份的。
用的路由是/zaobao/realtime/china

提示的错误：
```
Error Message:
RequestInProgressError: This path is currently fetching, please come back later!
Route: /zaobao/realtime/china
Full Route: /zaobao/realtime/china
Node Version: v22.11.0
Git Hash: 79d2c7f8
Git Date: Wed, 30 Oct 2024 12:33:41 GMT
```

9月份的文章：
![1](https://github.com/user-attachments/assets/7387e404-3457-48ef-8c68-b42f016381d4)
