### ISSUE TITLE
ABC not parsing URLs

### ISSUE THREAD

**Issue by jstride** [DIYgod/RSSHub#17411]
### Routes

```routes
/abc/:category{.+}?
```

### Full routes

```fullroutes
/abc/wa
```

### Related documentation

https://docs.rsshub.app/routes/traditional-media#abc-news

### What is expected?

URL should be URL of article

### What is actually happening?

URL is abc.net.au/undefined

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
As above
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pseudoyu** [comment]
Thank you for your feedback. Fixed now.

**Comment by jstride** [comment]
@pseudoyu  I have just noticed the example on the doc site is incorrect - https://docs.rsshub.app/routes/traditional-media#abc-news it should be https://rsshub.app/abc/wa
