### ISSUE TITLE
Medium无法使用

### ISSUE THREAD

**Issue by jdysya** [DIYgod/RSSHub#17476]
### 路由地址

```routes
/medium/list/:user/:catalogId
```

### 完整路由地址

```fullroutes
/medium/list/imsingee/f2d8d48096a9
```

### 相关文档

https://docs.rsshub.app/routes/blog#list

### 预期是什么？

正常输出

### 实际发生了什么？

FetchError: [GET] "https://towardsdatascience.com/why-i-signed-the-pause-giant-ai-experiments-petition-e9711f672d18": <no response> fetch failed

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
在自建的服务器上也无法使用
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ImSingee** [comment]
经过我的测试，RSSHub 官方实例的该路由确实不可用，但是我本地和我自己的实例是可以用的，因此我倾向于该问题是 Medium 的安全策略导致的问题

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0141e734-481a-4628-a102-cb35e710cd39">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/8d212c25-72bc-481e-ab00-5262f04ccf90">
