### ISSUE TITLE
提供`node-network-debugger`关闭选项

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#17496]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

`node-network-debugger`可在不需要时关闭。

### 实际发生了什么？

只要在开发情况下 https://github.com/DIYgod/RSSHub/blob/8ea3ee37609ff93f60c407ccd10b7a1441a09205/lib/utils/ofetch.ts#L6 一定执行，自动启动chrome且在关闭后不断输出`[node-network-debugger]:  waiting for chrome to open`。

### 部署

自建

### 额外信息

```shell
.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AiraNadih** [comment]
我觉得默认关闭更好，而不是目前的强制开启

**Comment by GrinZero** [comment]
Thank you for your feedback. I will fix this issue in version v1.0.24.
