### ISSUE TITLE
[煎蛋-无聊图] img 标签 src 属性值乱码

### ISSUE THREAD

**Issue by windcode** [DIYgod/RSSHub#175]
如题

**Comment by Xuanwo** [comment]
`<img referrerpolicy="no-referrer" src="http:¸²m?Ì@T^+ÑëïQ`±°ïN¯S¢hÈ?r³=Äí%Hù-¦FhçB0ef§y">
`

可能是煎蛋换算法了，我周末的时候看看

**Comment by bmeng** [comment]
就是换算法了，求更新
