### ISSUE TITLE
`/freecomputerbooks/` stopping updating

### ISSUE THREAD

**Issue by cubroe** [DIYgod/RSSHub#17502]
### Routes

```routes
/freecomputerbooks/:category?
```

### Full routes

```fullroutes
/freecomputerbooks/
```

### Related documentation

https://docs.rsshub.app/routes/reading#free-computer-books

### What is expected?

- The feed's `<lastBuildDate>` element should be with today's datetime (or lagged behind by one sync. interval) as value.
- **No** articles should contain `<pubDate>` elements (since I've removed the publish date generation as per #17475).

### What is actually happening?

- The feed's `<lastBuildDate>` element contains `Wed, 18 Sep 2024 05:43:48 GMT` as value (already nearly 2 months have elapsed, and in fact the source Web page has kept updating over the past 2 months).
- The articles, as of what I've just checked when writing down this report, still contain the `<pubDate>` elements.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info
_https://rsshub.app/freecomputerbooks/_ seems to take long time to load.

The issue should not be about the code of the route. It seems to relate to the deployment of _https://rsshub.app_ instance (some caching or extra filtering seems to make trouble in the middle).

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by cubroe** [comment]
@TonyRL Could please help check why the issue report keeps being closed by the bot?

I don't think [`/freecomputerbooks/`](https://rsshub.app/freecomputerbooks/) doesn't exist (note that even with the trailing `/` removed the issue would also be closed; see #17501). Confusing...😵‍💫

**Comment by TonyRL** [comment]
If you look at the issue form carefully while filling it in, it said

>  ...copied directly from the docs "route" field...

**Comment by cubroe** [comment]
By the way, @TonyRL, do you happen to know if such an issue report would probably be pending indefinitely, as the reporter is the route's maintainer themself? After all, an ordinary route maintainer can do nothing about the deployment and online troubleshooting again the _https://rsshub.app_ instance.

**Comment by TonyRL** [comment]
/test
```routes
/freecomputerbooks
```

**Comment by TonyRL** [comment]
It works
