### ISSUE TITLE
MIT科技评论

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#17524]
### 类型

阅读

### 网站地址

https://www.mittrchina.com/

### 网站描述

《麻省理工科技评论》（MIT Technology Review）于1899年在美国麻省理工学院创刊，是世界上历史最悠久、影响力最大的技术商业类杂志。内容覆盖广泛，涉及互联网、通讯、计算机技术、能源、新材料、生物医学和商务科技几大领域。
《麻省理工科技评论》中文网是《麻省理工科技评论》在中国唯一官方授权网站。

### 需要生成什么内容？

生成首页资讯和快讯的最新文章。

### 额外描述

原先RSShub有MIT科技评论的路由，现在文档中找不到了。

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/routes/new-media#%E9%BA%BB%E7%9C%81%E7%90%86%E5%B7%A5%E7%A7%91%E6%8A%80%E8%AF%84%E8%AE%BA
