### ISSUE TITLE
格隆汇无法抓取最新文章

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#17523]
### 路由地址

```routes
/gelonghui/home/:tag?
```

### 完整路由地址

```fullroutes
/gelonghui/home/web_home_page
```

### 相关文档

https://docs.rsshub.app/zh/routes/finance#%E6%A0%BC%E9%9A%86%E6%B1%87

### 预期是什么？

能拉取最新文章。

### 实际发生了什么？

无法拉取到最新文章。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://www.gelonghui.com/api/channels/web_home_page/articles/v8": <no response> fetch failed

Route: /gelonghui/home/:tag?

Full Route: /gelonghui/home/web_home_page

Node Version: v22.10.0

Git Hash: abed9a05

Git Date: Sun, 27 Oct 2024 15:06:44 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/gelonghui/home/web_home_page
```

**Comment by TonyRL** [comment]
It works
