### ISSUE TITLE
产业研究报告无法拉取文章

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#17526]
### 路由地址

```routes
/iresearch/report
```

### 完整路由地址

```fullroutes
/iresearch/report
```

### 相关文档

https://docs.rsshub.app/routes/other#%E4%BA%A7%E4%B8%9A%E7%A0%94%E7%A9%B6%E6%8A%A5%E5%91%8A

### 预期是什么？

能正常拉取文章。

### 实际发生了什么？

无法拉取文章。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:
FetchError: [GET] "https://www.iresearch.com.cn/api/products/GetReportList?fee=0&date=&lastId=&pageSize=20": <no response> fetch failed

Route: /iresearch/report

Full Route: /iresearch/report

Node Version: v22.11.0

Git Hash: 5f256bf9

Git Date: Sat, 09 Nov 2024 18:51:14 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/iresearch/report
```

**Comment by EsuRt** [comment]
测试后，疑似官方屏蔽了国外ip访问。
