### ISSUE TITLE
Inspire-hep订阅无法更新且失效

### ISSUE THREAD

**Issue by dualer** [DIYgod/RSSHub#17554]
### 路由地址

```routes
/inspirehep/authors/:id
/inspirehep/literature/:q
```

### 完整路由地址

```fullroutes
/inspirehep/authors/:id
/inspirehep/literature/:q
```

### 相关文档

https://docs.rsshub.app/routes/journal#inspire

### 预期是什么？

订阅长期有效, 并且能够定期更新订阅

### 实际发生了什么？

不能定期更新订阅, 订阅也失效了, 如图所示:
![image](https://github.com/user-attachments/assets/dab7e162-171a-4c98-89c1-8dbec59a1d6c)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
暂无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/inspirehep/literature/witten
/inspirehep/literature/maldacena
/inspirehep/literature/susskind
/inspirehep/literature/strominger
```

**Comment by TonyRL** [comment]
It works with the latest content being returned.

**Comment by dualer** [comment]
不是，我的意思是 可以return内容，但是过段时间订阅就会失效
