### ISSUE TITLE
Add support vk.com

### ISSUE THREAD

**Issue by Peloxerat** [DIYgod/RSSHub#17563]
### Category

Social Media

### Website URL

https://vk.com/

### Website description

VK is a Russian online social media and social networking service like facebook

### What content should be included?

similar to x/twitter, facebook, instagram, telegram

### Additional description

thx

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by matar3** [comment]
+1 Up
