### ISSUE TITLE
[今日头条-关键词] 中文关键词出错

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#176]

**Comment by DIYgod** [comment]
Fixed. 6dc8a360bc50587bace5dc7f35c51b02c38f1886

**Comment by jiey2016** [comment]
> Fixed. [6dc8a36](https://github.com/DIYgod/RSSHub/commit/6dc8a360bc50587bace5dc7f35c51b02c38f1886)

目前又出现问题了，不论是中文还是英文关键词都出错。
