### ISSUE TITLE
[小红书 - 用户笔记]无pubDate导致部分阅读器无法正常获取内容

### ISSUE THREAD

**Issue by KawausoJyou** [DIYgod/RSSHub#17602]
### 路由地址

```routes
/xiaohongshu/user/:user_id/:category
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/6552fa8600000000020352e3/notes
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%94%A8%E6%88%B7%E7%AC%94%E8%AE%B0

### 预期是什么？

包含pubDate

### 实际发生了什么？

无pubDate
![image](https://github.com/user-attachments/assets/a4106b27-e2a2-4f1d-832d-03e77ba6d397)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
我已经搜索了现有 issue，已被报告但被关闭。

<item>
<title>🏐排球少年！！垃圾场决战🏐</title>
<description><img src="http://sns-webpic-qc.xhscdn.com/202411171046/b032184fd6759b1e5a58bd3de2397f0c/1040g008313ffdg9e08505paiva30mkn32780m18!nc_n_webp_mw_1" referrerpolicy="no-referrer"><br>🏐排球少年！！垃圾场决战🏐</description>
<link>https://www.xiaohongshu.com/user/profile/6552fa8600000000020352e3/</link>
<guid isPermaLink="false">🏐排球少年！！垃圾场决战🏐</guid>
<author>MingYueSLife</author>
</item>
<item>
<title>海洋奇缘2＆淘麦VIP稀有款限定电子纪念票根•已全齐</title>
<description><img src="http://sns-webpic-qc.xhscdn.com/202411171046/974798d936b17d51505ce30b570789cf/1040g2sg31a8v35f76o2g5paiva30mkn3fh9d3to!nc_n_webp_mw_1" referrerpolicy="no-referrer"><br>海洋奇缘2＆淘麦VIP稀有款限定电子纪念票根•已全齐</description>
<link>https://www.xiaohongshu.com/user/profile/6552fa8600000000020352e3/</link>
<guid isPermaLink="false">海洋奇缘2＆淘麦VIP稀有款限定电子纪念票根•已全齐</guid>
<author>MingYueSLife</author>
</item>
<item>
<title>海洋奇缘2＆零点场•拿下</title>
<description><img src="http://sns-webpic-qc.xhscdn.com/202411171046/072aaf14cda73d27d8445e30bb5f4268/1040g2sg31a8v35f76o005paiva30mkn3q29n6q0!nc_n_webp_mw_1" referrerpolicy="no-referrer"><br>海洋奇缘2＆零点场•拿下</description>
<link>https://www.xiaohongshu.com/user/profile/6552fa8600000000020352e3/</link>
<guid isPermaLink="false">海洋奇缘2＆零点场•拿下</guid>
<author>MingYueSLife</author>
</item>
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
Yes currently we can't retrieve post time throught xiaohongshu website so the final rss doesn't contain `pubDate`. Still wait for/find out other ways.

**Comment by pseudoyu** [comment]
yes then we can have a pubDate but maybe the history items' `pubDate` will also be updated to new date every time we fetch/refetch. So it may be always on the top in your reader?

**Comment by pseudoyu** [comment]
> > yes then we can have a pubDate but maybe the history items' `pubDate` will also be updated to new date every time we fetch/refetch. So it may be always on the top in your reader?
> 
> Yes, I think this is acceptable because most RSS readers currently have the functionality to filter duplicate content, which is sufficient to temporarily address this issue.

okay i will add the `pubDate` field soon.

**Comment by pseudoyu** [comment]
resolved.
