### ISSUE TITLE
🔴「拷贝漫画」抓取错误

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#17651]
### 路由地址

```routes
/copymanga/comic/:id/:chapterCnt?
```

### 完整路由地址

```fullroutes
https://rsshub.app/copymanga/comic/lanxiang/5
```

### 相关文档

https://docs.rsshub.app/zh/routes/anime#%E6%8B%B7%E8%B4%9D%E6%BC%AB%E7%94%BB

### 预期是什么？

- 正常抓取

### 实际发生了什么？

- 官方演示和自建均出现抓取错误

- 最近有些漫画由于版权原因下架了，但那些没下架的漫画也无法正常抓取

- [https://mangacopy.com/comic/lanxiang](https://mangacopy.com/comic/lanxiang)

- [https://rsshub.app/copymanga/comic/lanxiang/5](https://rsshub.app/copymanga/comic/lanxiang/5)

<img width="865" alt="image" src="https://github.com/user-attachments/assets/43db4b31-57b0-4315-94d1-21534f796144">

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error Message:

FetchError: [GET] "https://api.copymanga.tv/api/v3/comic/lanxiang/group/default/chapters?limit=500&offset=0": <no response> fetch failed

Route: /copymanga/comic/:id/:chapterCnt?

Full Route: /copymanga/comic/lanxiang/5

Node Version: v22.11.0

Git Hash: 8a9a3b35

Git Date: Tue, 26 Nov 2024 05:49:07 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/copymanga/comic/lanxiang/5
```

**Comment by TonyRL** [comment]
It works.

**Comment by yan12125** [comment]
> ##### Searching for maintainers:
> 
>     * `/copymanga/comic/:id/:chapterCnt?`: @btdwv @marvolo666 @yan12125
> 
> 
> > To maintainers: if you are not willing to be disturbed, list your username in `scripts/workflow/test-issue/call-maintainer.js`. In this way, your username will be wrapped in an inline code block when tagged so you will not be notified.
> 
> If all routes can not be found, the issue will be closed automatically. Please use `NOROUTE` for a route-irrelevant issue or leave a comment if it is a mistake. 如果所有路由都无法匹配，issue 将会被自动关闭。如果 issue 和路由无关，请使用 `NOROUTE` 关键词，或者留下评论。我们会重新审核。

May I be removed from maintainers of this route? I regret contributing for websites involving piracy like copymanga.

**Comment by TonyRL** [comment]
> TonyRL
> 
> * I'm sorry, but there's really something wrong
> 
> * [mangacopy.com/comic/lanxiang](https://mangacopy.com/comic/lanxiang)
> * [rsshub.app/copymanga/comic/lanxiang/5](https://rsshub.app/copymanga/comic/lanxiang/5)
> 

Please note that the demo instance https://rsshub.app is purely for illustration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability.

**Comment by TonyRL** [comment]
Make sure the instance can access `copymanga.tv` and `api.copymanga.tv` without any issues.
