### ISSUE TITLE
豆瓣用户广播失效

### ISSUE THREAD

**Issue by mondain-dev** [DIYgod/RSSHub#17663]
### 路由地址

```routes
/douban/people/:userid/status/:routeParams?
```

### 完整路由地址

```fullroutes
/douban/people/75118396/status
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E7%94%A8%E6%88%B7%E5%B9%BF%E6%92%AD

### 预期是什么？

获取并显示用户广播RSS

### 实际发生了什么？

用户广播失效

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
FetchError: [GET] "https://m.douban.com/rexxar/api/v2/status/user_timeline/75118396": <no response> fetch failed
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/douban/people/75118396/status
```

**Comment by TonyRL** [comment]
It works.

**Comment by mondain-dev** [comment]
@TonyRL Maybe works on your localhost. Not working on rsshub.app:

<img width="951" alt="Screenshot 2024-11-27 at 7 12 23 PM" src="https://github.com/user-attachments/assets/d2b1bc35-13fd-4569-b45c-08795b0aede8">

**Comment by TonyRL** [comment]
The above tests do not run in my local environment, it runs on GitHub's infrastructures (Azure to be specific) instead, as you can see from the [generated log](https://github.com/DIYgod/RSSHub/actions/runs/12029954029/job/33536330807).

Please note that the demo instance https://rsshub.app is purely for illustration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability.
