### ISSUE TITLE
Who’s Hacked? Latest Data Breaches And Cyberattacks

### ISSUE THREAD

**Issue by fatmeat** [DIYgod/RSSHub#17664]
### Category

News

### Website URL

https://cybersecurityventures.com/intrusion-daily-cyber-threat-alert/#

### Website description

Cybersecurity Ventures is the world’s leading researcher and Page ONE for the global cyber economy, and a trusted source for cybersecurity facts, figures, and statistics.

### What content should be included?

If you scroll down a little bit, inside the TODAY section, it will show the latest breached company, cyber incident. I would like to have the below 5 field included in the feed and as the time writing, latest record was shown below, thank you!!

`Date` 11/21/2024
`Title` Finastra Data Breach: 400GB of Sensitive Client Data Exposed and Sold on Dark Web
`Description` London-based Finastra, one of the largest financial technology companies in the world, is investigating a data breach involving the unauthorized access and exfiltration of over 400 gigabytes of data from its internal file transfer platform. On Nov. 7, Finastra's security team detected suspicious activity on its internally hosted file transfer platform. The following day, a cybercriminal using the alias "abyss0" began selling large volumes of files allegedly stolen from Finastra's systems on the dark web. The data purportedly includes sensitive information from some of Finastra's largest banking clients. Finastra employs over 7,000 people and serves around 8,100 financial institutions globally, processing [massive volumes](https://dataconomy.com/2024/11/20/finastra-investigates-data-breach-affecting-client-files/) of digital files tied to financial transactions, according to Dataconomy.
`Source Link`
`Source`

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by fatmeat** [comment]
@KarasuShin Thank you for the help! But I think the feeds for TODAY section it's not working?

**Comment by KarasuShin** [comment]
@fatmeat I have tested it on my local instance and it works fine. Have you tried to consider hosting your own instance? https://rsshub.app is just a demo instance and cannot guarantee continuous normal operation.

**Comment by KarasuShin** [comment]
From [#16849 (comment)](https://github.com/DIYgod/RSSHub/issues/16849#issuecomment-2365381824)
> The official demo instances are for demonstration purposes and under heavy loads. Consider [host your own instance](https://docs.rsshub.app/deploy/) for higher stability.

maybe you can try other [public instances](https://docs.rsshub.app/guide/instances#public)

**Comment by fatmeat** [comment]
Thank you @KarasuShin, I spin up my own instance and worked perfectly!
