### ISSUE TITLE
Kemono FetchError

### ISSUE THREAD

**Issue by patricksykes** [DIYgod/RSSHub#17687]
### Routes

```routes
/kemono/:source?/:id?
```

### Full routes

```fullroutes
/kemono/patreon/48610247
```

### Related documentation

https://docs.rsshub.app/routes/anime#posts

### What is expected?

target URL is available, so RSSHub should return the data as an RSS feed.

### What is actually happening?

FetchError: [GET] "https://kemono.su/api/v1/patreon/user/48610247": <no response> fetch failed

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Helpful Information

Error Message:
FetchError: [GET] "https://kemono.su/api/v1/patreon/user/48610247": <no response> fetch failed

Route: /kemono/:source?/:id?

Full Route: /kemono/patreon/48610247

Node Version: v22.11.0

Git Hash: d78a47ec

Git Date: Thu, 21 Nov 2024 17:41:11 GMT
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/kemono/patreon/48610247
```

**Comment by TonyRL** [comment]
It works.
