### ISSUE TITLE
什么值得买 好文榜单有问题

### ISSUE THREAD

**Issue by kerhbal** [DIYgod/RSSHub#1772]
### 路由地址
/smzdm/ranking/haowen/yc/720
### 预期是什么？
与官方月榜单一致或接近 https://post.smzdm.com/hot_30/
### 实际发生了什么？
无论时间是720小时（30天）还是1000小时，返回的结果都和官方日榜单高度接近 https://post.smzdm.com/hot_1/
从简单的信息也可看出：月榜的收藏基本是五位数的，而通过rsshub抓出来的文章收藏都只有三位数。
### 部署相关信息（经测试 https://rsshub.app 部署下有同样问题）

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        ubuntu18.04       |
| Node version       |               |
| if Docker, version |     刚刚重新pull的 ，不知道怎么查看版本         |

**Comment by LogicJake** [comment]
这是因为 rsshub 抓取的是 https://www.smzdm.com/top/ 下的好文排行榜，这个地方的api好文没有日期跨度选择，所以显示的是你所说的单日榜的数据。

**Comment by kerhbal** [comment]
@LogicJake 多谢如此迅速解答！不知好文榜单如果改为从 https://post.smzdm.com 抓取的话难度大不大？因为现在这样没有日期跨度的话信息量太大了，起不到精选的作用。

**Comment by LogicJake** [comment]
@kerhbal 可以等待一个有缘人

**Comment by leesum** [comment]
原创频道自带   https://post.smzdm.com/feed
