### ISSUE TITLE
机核网无法抓取

### ISSUE THREAD

**Issue by cyy911** [DIYgod/RSSHub#1775]
### 路由地址
https://rsshub.app/gcores/category/栏目的数字
### 预期是什么？
RSS内容
### 实际发生了什么？
RSSHub 发生了一些意外:

ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)

**Comment by DIYgod** [comment]
已恢复
