### ISSUE TITLE
RSSBud/radar 支持 m.bilibili.com域名

### ISSUE THREAD

**Issue by finch71** [DIYgod/RSSHub#17777]
### 这是一个什么样的功能？

RSSBud/radar 支持 m.bilibili.com域名

### 这个功能可以解决什么问题？

目前只支持www开头的

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by pseudoyu** [comment]
Resolved.
