### ISSUE TITLE
新浪滚动新闻  修复

### ISSUE THREAD

**Issue by EnterMan123** [DIYgod/RSSHub#17787]
### 路由地址

```routes
/sina/rollnews/:lid?
```

### 完整路由地址

```fullroutes
https://rsshub.app/sina/rollnews
```

### 相关文档

https://docs.rsshub.app/routes/new-media#%E6%BB%9A%E5%8A%A8%E6%96%B0%E9%97%BB

### 预期是什么？

修复，使其恢复可用。

全部修复工作量太大，选择性修复即可。
必要的修复项：

- 国内
- 国际
- 军事

补充：
我发现源地址已经停止更新，新浪现在在这个网址更新新闻 → https://news.sina.com.cn/china/

![image](https://github.com/user-attachments/assets/fc3cac18-b92a-435e-a639-78ef986998ea)

### 实际发生了什么？

目前不可用，信息是陈旧的。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
X
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/sina/rollnews
```

**Comment by TonyRL** [comment]
The feed and the [source site](https://news.sina.com.cn/roll/) both works fine.

**Comment by EnterMan123** [comment]
我填写错误了，我想表达的是以下链接

rsshub://sina/rollnews/2514
rsshub://sina/rollnews/2510
rsshub://sina/rollnews/2511
