### ISSUE TITLE
Subfolder support 

### ISSUE THREAD

**Issue by Samppady** [DIYgod/RSSHub#17791]
### What feature is it?

Configuration for subfolder support in RSSHub.

### What problem does this feature solve?

Enables support for subfolders in RSSHub, improving feed structure and organization for users with complex setups.

### Additional description

It would be helpful if the docker-compose file allowed defining a subfolder using the BASE_URL variable. 
Additionally, images like logos should work within a subfolder. 

Currently, a simple fix would be to update the logo path from /logo.png to ./logo.png

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
Logo path is fixed, you need to reverse proxy like [nginx](https://github.com/DIYgod/RSSHub/issues/8254#issuecomment-927284082) to support subdirectory routing.
