### ISSUE TITLE
Ceph blog route doesn't work

### ISSUE THREAD

**Issue by ca5ua1** [DIYgod/RSSHub#17816]
### Routes

```routes
/ceph/blog/:topic?
```

### Full routes

```fullroutes
/ceph/blog
/ceph/blog/a11y
```

### Related documentation

https://docs.rsshub.app/routes/blog#blog-1

### What is expected?

i get rss

### What is actually happening?

i get error

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Error Message:
FetchError: [GET] "https://ceph.io/en/news/blog/": <no response> fetch failed

Route: /ceph/blog/:topic?

Full Route: /ceph/blog/a11y

Node Version: v22.12.0

Git Hash: db18c561

Git Date: Thu, 05 Dec 2024 23:54:20 GMT
```
```


### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by pandada8** [comment]
It works on my local rsshub instance.  Perhaps you could try hosting it yourself?
