### ISSUE TITLE
Fail to fetch bilibili user videos

### ISSUE THREAD

**Issue by EricGao-Byte** [DIYgod/RSSHub#17824]
### Routes

```routes
/bilibili/user/video/:uid/:embed?
```

### Full routes

```fullroutes
/bilibili/user/video/63231
```

### Related documentation

https://docs.rsshub.app/routes/social-media#bilibili

### What is expected?

The bilibili user video list is fetched

### What is actually happening?

Error Message:
FetchError: [GET] "https://api.bilibili.com/x/space/wbi/arc/search?mid=63231&ps=30&tid=0&pn=1&keyword=&order=pubdate&platform=web&web_location=1550101&order_avoided=true&dm_img_list=[{\"x\":6308,\"y\":-1464,\"z\":0,\"timestamp\":30,\"type\":0}]&dm_img_str=bm8gd2ViZ2&dm_cover_img_str=bm8gd2ViZ2&dm_img_inter={\"ds\":[{\"t\":2,\"c\":\"Y2xlYXJmaXggZy1zZWFyY2ggc2VhcmNoLWNvbnRhaW5lcg\",\"p\":[1858,36,531],\"s\":[70,532,556]},{\"t\":2,\"c\":\"d3JhcHBlcg\",\"p\":[915,41,1305],\"s\":[424,4403,3900]}],\"wh\":[5318,3781,86],\"of\":[266,532,266]}&w_webid=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcG1faWQiOiIwLjAiLCJidXZpZCI6IjlBMTgzRTU5LUIxNDItNjBGOC1DMkVCLTE1RTg5OTM3Q0Y2Mzc3MjcyaW5mb2MiLCJ1c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTRfNSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc1LjAuMzc3MC4xMDAgU2FmYXJpLzUzNy4zNiIsImJ1dmlkX2ZwIjoiMmUxODc0YWI3NTkxZWI5OWRlNWQ4ZGNkZmE5OTFiYWMiLCJiaWxpX3RpY2tldCI6Ijc2MGI3NzY2YTJiOTg4YTQyOWZjNWM4NDZkNjMxMDQzIiwiY3JlYXRlZF9hdCI6MTcyNjE1NDgxNCwidHRsIjo4NjQwMCwidXJsIjoiLzMyNjA2ODc5IiwicmVzdWx0Ijoibm9ybWFsIiwiaXNzIjoiZ2FpYSIsImlhdCI6MTcyNjE1NDgxNH0.RN290KgdYZ30kBGpsMSj8WW1iAipfYOrUqRcNQaV6NHvEsLDdIhDvr3aDZgZ2Rdk9yHDPGiw1KDucNLBQ6RU13iMYrnxYFmpk3AXd7gxRiGuJl22FB0ZsiD4tBbxjC6AwumRVJkAawbR-ApqLl113IOYA-5RJ8CiM2e8Q1wD-GhyBFs2yCCO_DYvSOWJzBAHtn2JLf582lFONlvKuQhz7BGd6B4yBcXaZWsBWs_5wKxDNIUoutE1SyloYzgdk0jtWoe31lD1PYWy8noOwjChIapzYHpbBXgy0TjpAAi_lpZQz1ODPNV7iT1jb9bQ1eTgBnG2_8K8BTjhYUpK312u5A&w_rid=f76214056fdb32644aa6c3a338789bb6&wts=1733632643": <no response> fetch failed

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Error Message:
FetchError: [GET] "https://api.bilibili.com/x/space/wbi/arc/search?mid=63231&ps=30&tid=0&pn=1&keyword=&order=pubdate&platform=web&web_location=1550101&order_avoided=true&dm_img_list=[{\"x\":6308,\"y\":-1464,\"z\":0,\"timestamp\":30,\"type\":0}]&dm_img_str=bm8gd2ViZ2&dm_cover_img_str=bm8gd2ViZ2&dm_img_inter={\"ds\":[{\"t\":2,\"c\":\"Y2xlYXJmaXggZy1zZWFyY2ggc2VhcmNoLWNvbnRhaW5lcg\",\"p\":[1858,36,531],\"s\":[70,532,556]},{\"t\":2,\"c\":\"d3JhcHBlcg\",\"p\":[915,41,1305],\"s\":[424,4403,3900]}],\"wh\":[5318,3781,86],\"of\":[266,532,266]}&w_webid=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzcG1faWQiOiIwLjAiLCJidXZpZCI6IjlBMTgzRTU5LUIxNDItNjBGOC1DMkVCLTE1RTg5OTM3Q0Y2Mzc3MjcyaW5mb2MiLCJ1c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTRfNSkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzc1LjAuMzc3MC4xMDAgU2FmYXJpLzUzNy4zNiIsImJ1dmlkX2ZwIjoiMmUxODc0YWI3NTkxZWI5OWRlNWQ4ZGNkZmE5OTFiYWMiLCJiaWxpX3RpY2tldCI6Ijc2MGI3NzY2YTJiOTg4YTQyOWZjNWM4NDZkNjMxMDQzIiwiY3JlYXRlZF9hdCI6MTcyNjE1NDgxNCwidHRsIjo4NjQwMCwidXJsIjoiLzMyNjA2ODc5IiwicmVzdWx0Ijoibm9ybWFsIiwiaXNzIjoiZ2FpYSIsImlhdCI6MTcyNjE1NDgxNH0.RN290KgdYZ30kBGpsMSj8WW1iAipfYOrUqRcNQaV6NHvEsLDdIhDvr3aDZgZ2Rdk9yHDPGiw1KDucNLBQ6RU13iMYrnxYFmpk3AXd7gxRiGuJl22FB0ZsiD4tBbxjC6AwumRVJkAawbR-ApqLl113IOYA-5RJ8CiM2e8Q1wD-GhyBFs2yCCO_DYvSOWJzBAHtn2JLf582lFONlvKuQhz7BGd6B4yBcXaZWsBWs_5wKxDNIUoutE1SyloYzgdk0jtWoe31lD1PYWy8noOwjChIapzYHpbBXgy0TjpAAi_lpZQz1ODPNV7iT1jb9bQ1eTgBnG2_8K8BTjhYUpK312u5A&w_rid=f76214056fdb32644aa6c3a338789bb6&wts=1733632643": <no response> fetch failed
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Konano** [comment]
Bilibili has anti-crawling measures, which may cause the interfaces on rsshub.app to be unstable. It is recommended to set up your own instance.
