### ISSUE TITLE
希望能够增强过滤功能的书写方法，提供英文大小写不敏感的功能。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#1782]
### 这是一个什么样的功能？
增加一个大小写不敏感的规则写法。现在是大小写敏感的，比如 top 、tOp 、TOP等共8种都是不一样的，想一次性过滤所有这8种情况的话要写好长，所以希望增加一种不敏感的功能，无论用这8种的哪一种都能过滤掉全部8种情况。
### 这个功能可以解决什么问题？
增强书写过滤规则便利性和容错性。
### 额外描述
敏感的写法有些情况也有它的用处，所以请不要直接拿掉敏感的写法，以增加一种不敏感的写法为宜。

**Comment by DIYgod** [comment]
@ruleroller 建议这样写 [Tt][Oo][Pp]

**Comment by ruleroller** [comment]
@DIYgod 即便如此，单词长了写起来也还是挺难受的。😄

**Comment by DIYgod** [comment]
@ruleroller 用处不大，还要多加一个参数，不想做🤔

**Comment by yefoenix** [comment]
@ruleroller 过滤的工作也可以交给阅读器来处理
