### ISSUE TITLE
什么值得买年热门有问题

### ISSUE THREAD

**Issue by Cyiming** [DIYgod/RSSHub#17869]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
https://rsshub.app/smzdm/haowen/365
```

### 相关文档

https://docs.rsshub.app/zh/routes/shopping#%E5%A5%BD%E6%96%87

### 预期是什么？

参数选择365后 应该是年热门 数量很少

### 实际发生了什么？

实际最近每天会更新近一千条 周热门月热门反而没那么多

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
We return a subset of 50 items per request rather than the entire one to reduce requests to original sites.

**Comment by Cyiming** [comment]
> We return a subset of 50 items per request rather than the entire one to reduce requests to original sites.

The problem is that the updated quantities for the parameters of 30 days and 7 days are far lower than that for 365 days. This is illogical. The quantity for 365 days should be even less instead.

**Comment by pseudoyu** [comment]
Yes I found the problem. We has

- daily hot: https://post.smzdm.com/hot_1/
- weekly hot: https://post.smzdm.com/hot_7/
- monthly hot: https://post.smzdm.com/hot_30/

on the smzdm site but no yearly hot so the yearly hot is the same as the daily one by default. I will remove it from route for now.
