### ISSUE TITLE
所有sinaweibo都不返回内容

### ISSUE THREAD

**Issue by jimmy-walker** [DIYgod/RSSHub#1786]
### 路由地址
https://rsshub.app/weibo/user2/1402400261
### 预期是什么？
预期会有今天的微博内容
### 实际发生了什么？
实际没有返回内容
### 部署相关信息
```html
<rss version="2.0">
<channel>
<title>
<![CDATA[ 爱可可-爱生活的微博 ]]>
</title>
<link>http://weibo.com/1402400261/</link>
<description>
<![CDATA[
爱可可-爱生活的微博 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)
]]>
</description>
<generator>RSSHub</generator>
<webMaster>i@diygod.me</webMaster>
<language>zh-cn</language>
<lastBuildDate>Tue, 19 Mar 2019 13:40:10 GMT</lastBuildDate>
<ttl>900</ttl>
</channel>
</rss>
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
现在有，可能网络抽风，忽略
