### ISSUE TITLE
知乎用户动态rss失效

### ISSUE THREAD

**Issue by Crx416** [DIYgod/RSSHub#17872]
### 路由地址

```routes
/zhihu/xhu/people/activities/:hexId
```

### 完整路由地址

```fullroutes
/zhihu/xhu/people/activities/77b195f4016956a60304aefb3961ca36
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%9F%A5%E4%B9%8E

### 预期是什么？

包含z_c0的Cookies至环境变量ZHIHU_COOKIES后应该能够获取用户动态

### 实际发生了什么？

FetchError: [GET] "https://api.zhihuvvv.workers.dev/guests/token": 401 Unauthorized

Route: /zhihu/xhu/people/activities/:hexId

### 部署

自建

### 部署相关信息

Node Version: v22.12.0

### 额外信息

```shell
Helpful Information

Error Message:
FetchError: [GET] "https://api.zhihuvvv.workers.dev/guests/token": 401 Unauthorized

Route: /zhihu/xhu/people/activities/:hexId

Full Route: /zhihu/xhu/people/activities/77b195f4016956a60304aefb3961ca36

Node Version: v22.12.0
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #17581
