### ISSUE TITLE
想支援发现微信支付/支付宝二维码已失效

### ISSUE THREAD

**Issue by stariveer** [DIYgod/RSSHub#1788]
### 路由地址
https://docs.rsshub.app/support/
### 预期是什么？
显示支付宝微信支付/二维码
### 实际发生了什么？
图床挂了
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
好像被墙了
