### ISSUE TITLE
Fix ali213

### ISSUE THREAD

**Issue by EnterMan123** [DIYgod/RSSHub#17891]
### 路由地址

```routes
/ali213/news/:category?
```

### 完整路由地址

```fullroutes
rsshub://ali213/news/game
rsshub://ali213/news/comic
```

### 相关文档

https://docs.rsshub.app/zh/routes/game#%E6%B8%B8%E4%BE%A0%E7%BD%91

### 预期是什么？

修复

### 实际发生了什么？

在follow上获取不到新文章

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
在follow上获取不到新文章
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/ali213/news/game
/ali213/news/comic
```

**Comment by TonyRL** [comment]
RSSHub can fetch the content without any issues. It's not RSSHub's fault if other instances can't fetch the content.
