### ISSUE TITLE
FetchError: <no response> fetch failed

### ISSUE THREAD

**Issue by hidezember** [DIYgod/RSSHub#17900]
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/1341767645/readable=1&authorNameBold=0&showAuthorInTitle=0&showAuthorInDesc=0&showAuthorAvatarInDesc=0&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showTimestampInDescription=1&heightOfPics=150
```

### 相关文档

https://rsshub.app/weibo/user/1341767645/readable=1&authorNameBold=0&showAuthorInTitle=0&showAuthorInDesc=0&showAuthorAvatarInDesc=0&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showTimestampInDescription=1&heightOfPics=150

### 预期是什么？

可以读取RSS

### 实际发生了什么？

RSS返回错误

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
FetchError: [GET] "https://m.weibo.cn/api/container/getIndex?type=uid&value=1341767645": <no response> fetch failed
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Konano** [comment]
Bilibili has anti-crawling measures, which may cause the interfaces on rsshub.app to be unstable. It is recommended to set up your own instance.

**Comment by TonyRL** [comment]
/test
```routes
/weibo/user/1341767645/readable=1&authorNameBold=0&showAuthorInTitle=0&showAuthorInDesc=0&showAuthorAvatarInDesc=0&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showTimestampInDescription=1&heightOfPics=150
```

**Comment by TonyRL** [comment]
It works.
