### ISSUE TITLE
小红书笔记有时报错503

### ISSUE THREAD

**Issue by PetrusZ** [DIYgod/RSSHub#17912]
### 路由地址

```routes
/xiaohongshu/user/:user_id/:category/:routeParams?
```

### 完整路由地址

```fullroutes
/xiaohongshu/user/60059f2500000000010054b0/notes
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E5%B0%8F%E7%BA%A2%E4%B9%A6

### 预期是什么？

正常返回

### 实际发生了什么？

有时可以正常返回，然而有时就报错：error: Error in /xiaohongshu/user/60059f2500000000010054b0/notes: TargetCloseError: Waiting for selector `div.reds-tab-item:nth-child(2)` failed: Protocol error (Runtime.callFunctionOn): Target closed

### 部署

自建

### 额外信息

```shell
已设置cookie
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dddaniel1** [comment]
小红书反爬严格，不建议使用cookie，有封号风险。

**Comment by PetrusZ** [comment]
ok thx

**Comment by pseudoyu** [comment]
This error 503 occurs when encountering Xiaohongshu's CAPTCHA verification page (with or without cookies). The issue typically resolves itself after waiting, or you can reduce your request frequency to prevent it.
