### ISSUE TITLE
获取抖音RSS报错

### ISSUE THREAD

**Issue by mh4u** [DIYgod/RSSHub#1791]
### 路由地址
/douyin/user/:id
### 预期是什么？
返回正常数据
### 实际发生了什么？
报错：
Error: Failed to launch chrome!
/usr/local/soft/RSSHub/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/soft/RSSHub/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/usr/local/soft/RSSHub/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by DIYgod** [comment]
应该恢复了，再试试？

**Comment by ruleroller** [comment]
@DIYgod 同样的问题，抖音 无法使用。用的是最新的commit e02b58c 。

> `RSSHub 发生了一些意外:
> Error: Failed to launch chrome!
> /root/RSSHub/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
> 
> 
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> 
>     at onClose (/root/RSSHub/node_modules/puppeteer/lib/Launcher.js:342:14)
>     at Interface.helper.addEventListener (/root/RSSHub/node_modules/puppeteer/lib/Launcher.js:331:50)
>     at Interface.emit (events.js:194:15)
>     at Interface.close (readline.js:379:8)
>     at Socket.onend (readline.js:157:10)
>     at Socket.emit (events.js:194:15)
>     at endReadableNT (_stream_readable.js:1125:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by Mr-Phone** [comment]
你服务器上chrome没有装好
如果是centos 7 参看https://www.cnblogs.com/lenmom/p/9195581.html

**Comment by wanfangmiao** [comment]
无法获取用户id
