### ISSUE TITLE
Fetch more weibo when using rsshub://weibo/user/xxxx

### ISSUE THREAD

**Issue by TChengZ** [DIYgod/RSSHub#17927]
### What feature is it?

everytime i fech the rss from weibo, such as rsshub://weibo/user/xxxx, it only return 10 weibos, can i control the number of weibo, like 20 30 even more

### What problem does this feature solve?

return the number of rss the user want.

### This is not a duplicated feature request or new RSS proposal

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested and this is not a [new RSS proposal](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_en.yml).

**Comment by TonyRL** [comment]
> 很多路由上限10条，无法增大。
> 
> 1. 消耗大量服务器资源。
> 2. 容易被反爬虫。
> 3. 绝大部分过时 feed 没有意义。

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416757360_

> RSS 是用来获取更新，增大条目无意义
> 
> 特殊需求请在相应模块里自行修改

_Originally posted by DIYgod in https://github.com/DIYgod/RSSHub/issues/572#issuecomment-416802920_

> rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

_Originally posted by yefoenix in https://github.com/DIYgod/RSSHub/issues/7291#issuecomment-809019525_

> You should not expect RSSHub to retrospectively retrieve every feed item.

_Originally posted by HenryQW in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110077752_

> Do not expect it can provide you everything that happens since the stone age.

_Originally posted by TonyRL in https://github.com/DIYgod/RSSHub/issues/9633#issuecomment-1110091835_

> RSS 强调获取内容更新。若有“一次性获取全部条目”的需求，应设计针对该内容的爬虫。

_Originally posted by nczitzk in https://github.com/DIYgod/RSSHub/issues/9964#issuecomment-1157343694_
