### ISSUE TITLE
微博 RSS 内容显示不完整

### ISSUE THREAD

**Issue by Ice-Hazymoon** [DIYgod/RSSHub#1794]
### 路由地址

http://rsshub.app/weibo/user2/2060888642

### 预期是什么？

![image](https://user-images.githubusercontent.com/25239977/54684441-4d20b700-4b4f-11e9-8b19-21357036840c.png)

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/25239977/54684473-675a9500-4b4f-11e9-88f7-f747e2c511f9.png)

内容抓取不完整

**Comment by HenryQW** [comment]
数据来源不支持长微博，见：
http://service.weibo.com/widget/widget_blog.php?uid=2060888642
