### ISSUE TITLE
[Github] Issue / Pull Request comments seems not working

### ISSUE THREAD

**Issue by deathmaz** [DIYgod/RSSHub#17951]
### Routes

```routes
/github/comments/:user/:repo/:number?
```

### Full routes

```fullroutes
https://rsshub.app/github/comments/DIYgod/RSSHub/8116
```

### Related documentation

https://rsshub.app/github/comments/DIYgod/RSSHub/8116

### What is expected?

no error

### What is actually happening?

Getting `fetch failed` error

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Error Message:
FetchError: [GET] "https://api.github.com/repos/DIYgod/RSSHub/issues/8116": <no response> fetch failed

Route: /github/comments/:user/:repo/:number?

Full Route: /github/comments/DIYgod/RSSHub/8116

Node Version: v22.12.0

Git Hash: f5fc827b

Git Date: Thu, 19 Dec 2024 18:26:15 GMT
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by FliegendeWurst** [comment]
Works for me. Maybe rsshub.app demo instance is overloaded. Try this one: `https://rsshub.fliegendewurst.eu/github/comments/DIYgod/RSSHub/8116`

**Comment by TonyRL** [comment]
/test
```routes
/github/comments/DIYgod/RSSHub/8116
```

**Comment by TonyRL** [comment]
It works.
