### ISSUE TITLE
希望对youtube的community提供支持

### ISSUE THREAD

**Issue by hzc54188** [DIYgod/RSSHub#17989]
### 这是一个什么样的功能？

youtube的community其实相当于bilibili的动态！

### 这个功能可以解决什么问题？

1.我用bilibili用户欣小萌举例，下述链接可以成功订阅欣小萌的动态！
rsshub://bilibili/user/dynamic/8366990
2.切换到youtube使用场景，下述两个链接订阅的都是视频，无法订阅到社区！
rsshub://youtube/user/@欣小萌-i9j
rsshub://youtube/user/@欣小萌-i9j/community

### 额外描述

很有细分的必要，官网热门路由里没有明确的规则来订阅社区！https://docs.rsshub.app/zh/routes/popular#youtube

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

**Comment by hzc54188** [comment]
![image](https://github.com/user-attachments/assets/a5c5ad59-4f64-4a7e-83bf-a20b81b997c8)
![image](https://github.com/user-attachments/assets/840e0cd8-2e63-4143-bb08-7c426df70c01)
如图所示：欣小萌社区和欣小萌视频明显承载的信息内容 明显不一样

**Comment by TonyRL** [comment]
Duplicate of #7706

**Comment by hzc54188** [comment]
通过阅读代码 @https://github.com/DIYgod/RSSHub/blob/master/lib/routes/youtube/community.ts ，我成功订阅了欣小萌!虽然已经被关闭，但是还是有必要作出说明！
订阅规则如下：
rsshub://youtube/community/@欣小萌-i9j
