### ISSUE TITLE
【中国疾病预防控制中心】全球传染病事件风险评估报告栏目下标题抓不到，抓到的是1970-01-01 00:00:00

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#18003]
### 路由地址

```routes
/chinacdc/:category{.+}?
```

### 完整路由地址

```fullroutes
/chinacdc/jksj/jksj03
```

### 相关文档

https://docs.rsshub.app/routes/government#%E9%80%9A%E7%94%A8-4

### 预期是什么？

全球传染病事件风险评估报告栏目下抓每个内容的正确标题

### 实际发生了什么？

标题抓不到，抓到的是1970-01-01 00:00:00

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
# 感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
fixed.
