### ISSUE TITLE
需求收录百度百家号

### ISSUE THREAD

**Issue by wskxjtzq** [DIYgod/RSSHub#1806]
### 源站地址
https://baijiahao.baidu.com/u?app_id=1572165046650737
### 需要生成什么内容？

生成各用户最新发布的文章标题，如果有内容更好。

### 额外描述

这个网站是百度的百家号。名声不好，但慢慢还是有些人在用了，因此需要。

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
