### ISSUE TITLE
一个 RSS 订阅源显示 Application error

### ISSUE THREAD

**Issue by QIanGua** [DIYgod/RSSHub#1815]
### 路由地址
/universities/zju/physics/:type
e.g. 
https://rsshub.app/zju/physics/1
### 预期是什么？
至少能用 Reeder 搜到 并订阅这条 RSS 
### 实际发生了什么？
打开网址 https://rsshub.app/zju/physics/1 显示
「 An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail. 」
本地部署的路由可以正常抓取。
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Mac OS   v10.14.3          |
| Node version       |      v11.12.0         |

**Comment by QIanGua** [comment]
补充下，本地部署的路由可以正常抓取

**Comment by DIYgod** [comment]
源站超时，应该是 URL 改了
