### ISSUE TITLE
支持输入 RSS 源吗？RSSHub仅做为中转 加上过滤

### ISSUE THREAD

**Issue by waldens** [DIYgod/RSSHub#1818]
已经在文档和issue中搜索了关键词“pip”“rss源”“筛选”等，没找到相关信息，才发帖问

现在已有个RSS源：`https://www.reddit.com/r/HumansBeingBros/new/.rss`
（这个链接仅仅是举例子）
单纯想为它做过滤，不知道RSSHub是否支持？如果目前还不支持，那么有PR的话，是否愿意接受？

例如，有个RSS中转路由，类似这样：
`https://rsshub.app/rss/https://www.reddit.com/r/HumansBeingBros/new/.rss?filter_title=dog|cat|hero`

**Comment by yefoenix** [comment]
过滤的需求，可以由阅读器来解决吧

**Comment by ruleroller** [comment]
#122
