### ISSUE TITLE
南航研究生院-demo与自建抓取结果不同

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub#1837]
### 路由地址
/nuaa/yjsy/latest.atom
### 预期是什么？
demo站与自建抓取内容相同
### 实际发生了什么？
demo站没有返回原文内容，自建拥有原文内容(memory, redis下均有原文内容)。
### 部署相关信息

git hash:  aa96364

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  win10, ubuntu16.04  |
| Node version       |   v10.15.2     |
| if Docker, version |               |

**Comment by junfengP** [comment]
在heroku上建立app时发现同样问题，页面缺少<content>字段。
已排除heroku app 无法访问详细页面的情况。

**Comment by DIYgod** [comment]
看了下现在已经好了
