### ISSUE TITLE
请求Stage1st的RSS

### ISSUE THREAD

**Issue by shidaixingzhi** [DIYgod/RSSHub#1840]
源站地址

https://bbs.saraba1st.com/2b/thread-1746039-1-1.html

 需要生成什么内容？

每当帖子有更新的时候，抓取最后一层楼的内容

 额外描述

无

**Comment by yefoenix** [comment]
@shidaixingzhi https://bbs.saraba1st.com/2b/thread-1746039-1-1.html?mod=rss
