### ISSUE TITLE
SixthTone 全文RSS

### ISSUE THREAD

**Issue by abc1763613206** [DIYgod/RSSHub#1856]
### 源站地址
http://www.sixthtone.com/
### 需要生成什么内容？

- [ ] 全文RSS

### 额外描述
站点已经提供文章更新的RSS    
http://www.sixthtone.com/rss    

想要一个全文的     

**fivefilters家的没法生成**

**Comment by yefoenix** [comment]
@abc1763613206 已有RSS的再处理不属于rsshub的工作范围，可以交由阅读器处理

**Comment by abc1763613206** [comment]
> @abc1763613206 已有RSS的再处理不属于rsshub的工作范围，可以交由阅读器处理

？？？纽约日报貌似也给了个官方优化啊   
而且这个好像用fulltextrss好像也没法正常处理   
（FreshRSS用户表示很无奈）

**Comment by yefoenix** [comment]
@abc1763613206 欢迎pr
