### ISSUE TITLE
[热门IP] Nginx 代理后 热门 IP 显示错误

### ISSUE THREAD

**Issue by mritd** [DIYgod/RSSHub#1857]
### 路由地址

`/`

### 预期是什么？

主页显示正常的热门 IP

### 实际发生了什么？

Nginx 反向代理后，热门 IP 显示为内网 IP，**已经传递 `X-Real-IP` http 头**

### 部署相关信息

docker compose 部署，nginx 独立

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    Ubuntu 18.04           |
| Node version       |     node 10.15.3          |
| if Docker, version |     18.09.1          |

### 额外信息（日志、报错等）

- nginx.conf

``` sh
    location / {

        log_not_found on;

        proxy_pass http://rsshub;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_redirect off;

        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP         $remote_addr;

    }
```

**Comment by DIYgod** [comment]
不知道，给你我的配置参考吧

```
  location / {
    proxy_pass http://localhost:1200/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
    proxy_set_header Host $host;
  }
```
