### ISSUE TITLE
RSSHub 发生了一些意外: TypeError: Cannot read property 'screen_name' of undefined

### ISSUE THREAD

**Issue by saresam** [DIYgod/RSSHub#187]
打开这个的时候
https://rsshub.app/weibo/user/3092590931
出现：RSSHub 发生了一些意外: TypeError: Cannot read property 'screen_name' of undefined

**Comment by tgly307** [comment]
额……这个用户是不是注销了，微博上都找不到，叫什么？
https://api.prprpr.me/weibo/rss/3092590931 这里面已经没有用户的名字了
