### ISSUE TITLE
新发微博的时间格式有问题

### ISSUE THREAD

**Issue by footair** [DIYgod/RSSHub#1870]
### 路由地址
/weibo/user

### 预期是什么？
发布1分钟之内的微博也能给出标准时间格式的时间

### 实际发生了什么？
发布1分钟之内的微博，发布时间为<pubDate>刚刚</pubDate>
实测将\lib\utils\date.js的判断后面加上下图的代码可以解决此问题
![image](https://user-images.githubusercontent.com/19180083/55398911-3ed59080-557c-11e9-8f19-41e4aab1e5ea.png)

**Comment by SettingDust** [comment]
@footair 为什么不PR呢= =

**Comment by yefoenix** [comment]
@footair 欢迎pr
