### ISSUE TITLE
 希望增加工業設計类网站 RSS

### ISSUE THREAD

**Issue by leesum** [DIYgod/RSSHub#1875]
### 源站地址
https://www.idsketch.cn/

### 需要生成什么内容？

- [ ] 全文：标题+内容
- [ ] 分类：标题+内容

### 额外描述
https://www.idsketch.cn/分类/文章ID.html

**Comment by yefoenix** [comment]
https://www.idsketch.cn/feed
使用WordPress搭建的网址自带rss输出……
