### ISSUE TITLE
知乎专栏挂掉了。

### ISSUE THREAD

**Issue by miaoyuxinbaby** [DIYgod/RSSHub#1877]
### 路由地址
https://rsshub.app/zhihu/zhuanlan/googledevelopers
### 预期是什么？
ok
### 实际发生了什么？
no ok
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |              |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

RSSHub 发生了一些意外:
TypeError: Cannot read property 'map' of undefined
    at module.exports (/app/lib/routes/zhihu/zhuanlan.js:37:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

自建的：
Error in /zhihu/zhuanlan/phodal: Error: write EPROTO 4351382976:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by miaoyuxinbaby** [comment]
自建的也挂掉了

**Comment by tgly307** [comment]
我自建的没问题，是不是你自建的订阅太多被反爬了

**Comment by miaoyuxinbaby** [comment]
@tgly307  今天刚出的问题，2天加起来我才请求了不到10次

**Comment by miaoyuxinbaby** [comment]
Request https://zhuanlan.zhihu.com/api/columns/phodal/articles fail, retry attempt #2: Error: write EPROTO 4351382976:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by tgly307** [comment]
我刚试了确定没问题，换个IP试一下吧，有可能是所在的IP段被封了
