### ISSUE TITLE
广州天气预警

### ISSUE THREAD

**Issue by LimeZky** [DIYgod/RSSHub#1882]
### 源站地址
http://www.tqyb.com.cn/
### 需要生成什么内容？
- [1] 突发性天气提示（http://www.tqyb.com.cn/gz/weatherAlarm/suddenWeather/）
- [2] 广东省内城市预警信号（http://www.tqyb.com.cn/gz/weatherAlarm/otherCity/）

**Comment by kt286** [comment]
突发天气   http://tqyb.com.cn/data/gzWeather/weatherTips.js
短时天气   http://tqyb.com.cn/data/shorttime/gz_shorttime.js
省内城市预警  http://tqyb.com.cn/data/gzWeather/otherCityAlarm.js
