### ISSUE TITLE
纽约时报“每日简报”错误输出为“官方RSS”的路由

### ISSUE THREAD

**Issue by springspace** [DIYgod/RSSHub#1886]
路由地址
https://rsshub.app/nytimes/morning_post

预期是什么？
获取 纽约时报 每日简报，RSS输出如下
title: 纽约时报 每日简报
link: https://m.cn.nytimes.com/morning-brief/

实际发生了什么？
错误获取为 “纽约时报 官方RSS” 的路由，RSS输出如下
title: 纽约时报中文网
link: https://cn.nytimes.com

部署相关信息
Heroku

**Comment by xyqfer** [comment]
<img width="587" alt="WX20190408-115718@2x" src="https://user-images.githubusercontent.com/5186792/55697812-b3358700-59f5-11e9-8768-b2688fcf4578.png">

这里的路由冲突了...... 详见 fac1541ae6cc0263b0323bc9cbbf7dcfbed18349
顺便 @HenryQW ，要不外面再加一层 /lang/:lang ？

**Comment by HenryQW** [comment]
@xyqfer 这样可以避免现有路由失效，也减少了代码量。缺点是每日简报应该抓不到几天前的了，好像也不影响？
