### ISSUE TITLE
希望增加对少数派:关注作者、专栏的支持

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#1890]
### 源站地址:
例如：
https://sspai.com/column/104
https://sspai.com/user/705956/updates

### 需要生成什么内容？

- [ ] 标题
- [ ] 正文内容
- [ ] 用户动态

**Comment by zsakvo** [comment]
已有部分
https://docs.rsshub.app/other.html#%E5%B0%91%E6%95%B0%E6%B4%BE-sspai

**Comment by sunshinenny** [comment]
作者的支持 已经写好提交了,最近应该就可以用得上了

**Comment by yefoenix** [comment]
可以关闭了 @DIYgod 
 #2185 #2122 #1977
