### ISSUE TITLE
希望增加对天涯论坛的支持

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#1891]
### 源站地址
http://bbs.tianya.cn/

### 需要生成什么内容？
帖子正文、主题动态、用户动态
- [ 标题] 内容一 
- [ 内容全文带图片] 内容二 
 
### 额外描述 
路由按id生成rss

**Comment by LogicJake** [comment]
@ZhuningS 地址都不舍得给？

**Comment by ZhuningS** [comment]
给了
