### ISSUE TITLE
希望支持收趣热门

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#1892]
### 源站地址
http://shouqu.me/hot.html

### 需要生成什么内容？

- [ ] 文章列表
- [ ] 文章正文

**Comment by yefoenix** [comment]
http://api.shouqu.me/api_service/api/v1/daily/dailyMarkV2?beginTime=1556611200&osv=7.1.1&imei=0000&userId=&isAuto=0&mac=0000&appChannel=yingyongbao&endTime=1556625600&apv=2.5.8&isLoadmore=0&os=android&model=

**Comment by yefoenix** [comment]
发现 可以通过 今日热榜路由订阅
https://rsshub.app/tophub/Jb0vmWGeB1

**Comment by kt286** [comment]
@DIYgod 这个issue可以关了
