### ISSUE TITLE
【刷屏】最新示例404

### ISSUE THREAD

**Issue by evansmile** [DIYgod/RSSHub#1895]
### 路由地址
/weseepro/newest
### 预期是什么？
抓取内容
### 实际发生了什么？
自2019-04-08早上10点开始 报错404

**Comment by xyqfer** [comment]
试了下似乎是源站地址在海外解析不出来，国内没问题......

**Comment by yefoenix** [comment]
@evansmile 我自建也挂了。好像是被反爬了，接口看了一下还是有的……

**Comment by xyqfer** [comment]
@yefoenix 试下直连/非直连访问这个地址试下：https://www.weseepro.com/api/v1/message/ground/spam?pageNumber=1&pageSize=20

不清楚是不是他们的海外解析出问题了还是说设置成如此了......

**Comment by evansmile** [comment]
> @yefoenix 试下直连/非直连访问这个地址：https://www.weseepro.com/api/v1/message/ground/spam?pageNumber=1&pageSize=20
> 
> 不清楚是不是他们的海外解析出问题了还是说设置成如此了......

这个地址能访问，我这里依据示例建的爬取，不知道这里会不会有修复 如果不是反扒的话

**Comment by xyqfer** [comment]
@evansmile 感觉是源站的问题了......

**Comment by evansmile** [comment]
> @evansmile 感觉是源站的问题了......

那有可能是反扒了?  要做ip资源池了么 +_-..

**Comment by xyqfer** [comment]
> > @evansmile 感觉是源站的问题了......
> 
> 那有可能是反扒了? 要做ip资源池了么 +_-..

应该不是反爬，海外地址解析不出来......

**Comment by yefoenix** [comment]
ca.com 试了ping全挂，应该是解析问题

**Comment by evansmile** [comment]
> > > @evansmile 感觉是源站的问题了......
> > 
> > 
> > 那有可能是反扒了? 要做ip资源池了么 +_-..
> 
> 应该不是反爬，海外地址解析不出来......

默默期待修复

**Comment by evansmile** [comment]
> ca.com 试了ping全挂，应该是解析问题

谢谢~一起等修复^_^
