### ISSUE TITLE
即刻主题里的图片不显示

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#1897]
### 路由地址
https://rsshub.app/jike/topic/58c361475217740015d3f701
### 预期是什么？
有图片显示
### 实际发生了什么？
没有图片显示

**Comment by DIYgod** [comment]
Reeder 正常，建议换个阅读器

**Comment by tomatomash** [comment]
> Reeder 正常，建议换个阅读器

DIYgod大佬，其实是我浏览器打开图片（比如https://cdn.ruguoapp.com/f5f5cb57728397d1f09667af3fb5a95b?imageMogr2/auto-orient/），是ERROR: ACCESS DENIED，
不过把“/auto-orient/”去掉之后（https://cdn.ruguoapp.com/f5f5cb57728397d1f09667af3fb5a95b?imageMogr2）就可以显示图片了，
请问一下图片链接去掉“/auto-orient/”是否可行？感谢！

**Comment by xyqfer** [comment]
这是由于你的操作触发了图片防盗链设置，可以试着按着下面的步骤测试下：

如果是直接在上面的图片链接右键**在新标签页打开**的话，请求头里会带上 referer，触发防盗链。可参考下面两张图：

<img width="762" alt="WX20190409-144226@2x" src="https://user-images.githubusercontent.com/5186792/55778815-873e0280-5ad6-11e9-8424-054ece2cc66d.png">

<img width="1285" alt="WX20190409-144333@2x" src="https://user-images.githubusercontent.com/5186792/55778836-9624b500-5ad6-11e9-81ad-094a74ea24ae.png">

但是**手动复制地址**在新打开的 tab 页里打开是没有问题的，因为请求头里没有 referer ，不会触发防盗链。可参考下面的图：

<img width="1260" alt="WX20190409-144435@2x" src="https://user-images.githubusercontent.com/5186792/55778961-edc32080-5ad6-11e9-9e30-a2f493d56a97.png">

至于去掉`/auto-orient/`之后可以打开，如果你的操作是在第一步之后继续的（也就是在第一步的浏览器导航栏里直接删掉`/auto-orient/`），这个时候对浏览器来说其实是新的一个请求了，跟第二步类似的（不会带 referer）。所以这个时候可以正常打开。

这可以通过一个简单的方式来验证。可以用下图的方式来打开第二个链接，按理说应该也是被拦截掉的：

<img width="726" alt="WX20190409-145355@2x" src="https://user-images.githubusercontent.com/5186792/55779389-d6d0fe00-5ad7-11e9-83bd-c7ad4895fe91.png">

**注意：以上各步操作间均需要清除缓存！**

所以，如果某些阅读器不能打开，应该是请求图片时带上了 referer 导致的，可以手动抓包测试下。

综上，这应该不是即刻本身链接地址的问题。（欢迎反馈）

**Comment by tomatomash** [comment]
的确我手动复制地址，即使包括/auto-orient/，也是能够打开图片的。
所以这种情况下，怎么让它不带上referer呢？

**Comment by xyqfer** [comment]
建议换个阅读器 🌚

**Comment by tomatomash** [comment]
> 建议换个阅读器 🌚

大佬，我尝试了3个浏览器（cent，chrome，edge）分别用inoreader和feedly订阅，结果都不显示。。。chrome最多能显示预览图，点开后还是没有。
![2019-04-09_172542](https://user-images.githubusercontent.com/43887440/55789688-6339eb80-5aed-11e9-852d-21608e10b606.jpg)
这应该，不是阅读器的锅吧

**Comment by DIYgod** [comment]
@tomatomash 阅读器不是浏览器，inoreader 和 feedly 会画蛇添足删掉图片的 referrer 属性

**Comment by tomatomash** [comment]
> @tomatomash 阅读器不是浏览器，inoreader 和 feedly 会画蛇添足删掉图片的 referrer 属性

emmmm，谢谢大佬！（其实你这句话启发到我了），我下了个referer control，设置内容（default referer for all other sites：设为“Block”，Context Menu entry：设为“Off”，其余默认）
，结果就显示了，简直不要太开心！

**Comment by yefoenix** [comment]
本issue可以关掉了
