### ISSUE TITLE
Telegram RSS wanted

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#190]
- [x] channel
- [x] group（放弃）
- [x] sticker

**Comment by MaekawaMiku** [comment]
https://rsshub.app/telegram/channel/MikuRelayStation Test please.
测试一下，bot 在里头

**Comment by lzjluzijie** [comment]
channel 能不能做到不需要bot在里面呢

**Comment by DIYgod** [comment]
Done. e73f80bc7a5662df5599ecc2dbef89ed3a80c381
