### ISSUE TITLE
Matters.News - 作者 路由抓取错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1902]
### 路由地址
http://rsshub.app/matters/author/935593258
### 预期是什么？
正常抓取内容
### 实际发生了什么？
item 没有 title 和 description
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/55785107-73999880-5ae4-11e9-9c96-bb9b19206390.png)

**Comment by cerebrater** [comment]
Matters 在我的 pull request 被接受前頁面有些許調整，我昨日已經提交新的 pull request （#1903 ）以修復此問題。
