### ISSUE TITLE
请求支持苹果认证翻新官网产品上新提示

### ISSUE THREAD

**Issue by nageshuizeii** [DIYgod/RSSHub#1906]
### 这是一个什么样的功能？
提示苹果认证翻新官网有新的翻新产品上新了
### 这个功能可以解决什么问题？
可以及时购买
### 额外描述
https://www.apple.com/cn/shop/refurbished

**Comment by nageshuizeii** [comment]
神奇网站，感谢推荐

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: Henry Wang <notifications@github.com>
发送时间: 星期二, 四月 9, 2019 9:32 下午
收件人: DIYgod/RSSHub
抄送: nageshuizeii; Author
主题: Re: [DIYgod/RSSHub] 请求支持苹果认证翻新官网产品上新提示 (#1906)


推荐：https://refurb-tracker.com/

―

**Comment by HenryQW** [comment]
可以关闭 issue。
