### ISSUE TITLE
是否考虑增加非新闻媒体的订阅

### ISSUE THREAD

**Issue by leoskey** [DIYgod/RSSHub#191]
比如女朋友的微博情绪监控 、被封禁的 hosts 列表。

**Comment by Ir1d** [comment]
被封禁的hosts列表是啥

**Comment by leoskey** [comment]
被 GFW 禁止访问的域名。当然，不仅仅是被禁止访问的域名，也可以是微博数据分析。

这个想法来源与这个项目[https://phinx.herokuapp.com](https://phinx.herokuapp.com)。

**Comment by Qixingchen** [comment]
@leoskey 收集整理信息应该不在本项目范围内，如果你已经有信息源了应该是可以加的

**Comment by DIYgod** [comment]
情绪监控需要付费 API，没有赞助的话暂不考虑； 收集数据不在本项目范围内
