### ISSUE TITLE
[Feather Request] 通用配置型路由 增加抓取全文功能

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1912]
### 这是一个什么样的功能？
使通用配置型路由能抓取条目全文
### 这个功能可以解决什么问题？
目前通用配置型路由（/utils/common-config）只能抓取条目标题，description 过于简陋

**Comment by xyqfer** [comment]
感觉 description 这块可以用 [mercury-parser](https://github.com/postlight/mercury-parser) 来搞。
Reeder 4 用的好像是 [readability](https://github.com/mozilla/readability)，但是依赖 [jsdom](https://github.com/jsdom/jsdom)，总觉得这玩意挺重的样子...

**Comment by yefoenix** [comment]
@xyqfer Mercury 好像也挺重……

**Comment by yefoenix** [comment]
鉴于rsshub 实现了 Mercury Fulltext，本 issue 关闭
