### ISSUE TITLE
【功能需求】为Youtube 路由增加音频连接，使之可以成为Podcast源

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1913]
### 这是一个什么样的功能？
为 Youtube 路由提供音频链接，使之可以成为 Podcast 源
### 这个功能可以解决什么问题？
使泛用性 Podcast 软件可以直接订阅 Youtube 内容
### 额外描述
可考虑利用第三方API获取item的音频链接，如 https://download-api.com/download-audio-from-youtube/

**Comment by HenryQW** [comment]
感觉要开一个 PodcastHub

**Comment by cxumol** [comment]
https://podsync.net/

**Comment by xyqfer** [comment]
https://www.easy-youtube-mp3.com/ 感觉可以用这个试试，不过有个问题是路由要怎么加参数....

**Comment by DIYgod** [comment]
> [easy-youtube-mp3.com](https://www.easy-youtube-mp3.com/) 感觉可以用这个试试，不过有个问题是路由要怎么加参数....

参数类似之前的 embed 参数就可以

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭
