### ISSUE TITLE
希望增加游民福利的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#1920]
### 源站地址
https://www.gamersky.com/ent/xz/
### 需要生成什么内容？

- [标题] 内容一
- [全文包括图片] 内容二

**Comment by tomatomash** [comment]
大佬，这个分类是正在进行中吗？只有简介输出，全文/图片没有
![2019-04-13_155703](https://user-images.githubusercontent.com/43887440/56076555-67277f80-5e05-11e9-99a5-4890379c504f.jpg)
![2019-04-13_155731](https://user-images.githubusercontent.com/43887440/56076558-6c84ca00-5e05-11e9-896b-03020b07a8c5.jpg)

**Comment by LogicJake** [comment]
![image](https://user-images.githubusercontent.com/20673460/56076894-94c1f800-5e08-11e9-9b5e-a876a813e894.png)
从何说起？

**Comment by LogicJake** [comment]
![image](https://user-images.githubusercontent.com/20673460/56076960-013cf700-5e09-11e9-9ac5-0e1c1b5fc67f.png)
你看错路由了
