### ISSUE TITLE
[Zhihu Video Issue] The video cannot play

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#1922]
### Involved route
zhihu

### What is expected?
The zhihu video works and can play well.

### What is actually happening?
The zhihu video cannot play.

### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### Additional info (logs errors etc)
This is the [RSS Feed](https://rsshub.app/zhihu/people/activities/lisanshui1230?filter_title=%E5%8F%91%E5%B8%83%E4%BA%86%E6%83%B3%E6%B3%95) and the video link didn't work.

![image](https://user-images.githubusercontent.com/10363328/56018563-0b8dc100-5d35-11e9-9640-c454a8655a96.png)

![image](https://user-images.githubusercontent.com/10363328/56018583-1b0d0a00-5d35-11e9-9330-ae9d6a49becd.png)

**Comment by LogicJake** [comment]
It works well in inoreader.

**Comment by xyqfer** [comment]
@DerekTso 我怀疑是那些奇怪的空格(下图)导致某些阅读器解析失败了，稍等我提个 PR 还请麻烦测试下：

<img width="1200" alt="WX20190413-165300@2x" src="https://user-images.githubusercontent.com/5186792/56077283-f1271680-5e0c-11e9-9697-890b9cdf18f5.png">

**Comment by xyqfer** [comment]
> @DerekTso 我怀疑是那些奇怪的空格(下图)导致某些阅读器解析失败了，稍等我提个 PR 还请麻烦测试下：
> 
> <img alt="WX20190413-165300@2x" width="1200" src="https://user-images.githubusercontent.com/5186792/56077283-f1271680-5e0c-11e9-9697-890b9cdf18f5.png">

好吧，应该是标签没闭合......= =

**Comment by DerekTso** [comment]
@xyqfer 

the issue remains after your fix.
I checked that the video urls are different.
// [testing rss feed](https://rsshub.app/zhihu/people/activities/mali?filter_title=发布了想法)

**zhihu webpage url**
https://vdn1.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=com&expiration=1555222620&auth_key=1555222620-0-0-4931a4585a6698f22fde591d76f8589a&f=mp4&v=hw

**rss feed url (with 403 error)**
https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=lens&expiration=1555169264&auth_key=1555169264-0-0-1c6afdd88efc76d3390ca046ad5c247a&f=mp4&v=ali&auth_key=1555169264-0-0-1c6afdd88efc76d3390ca046ad5c247a&expiration=1555169264&v=ali&bu=com&f=mp4&disable_local_cache=0

![image](https://user-images.githubusercontent.com/10363328/56088668-2d638100-5eb8-11e9-9630-9188ff56a598.png)

**Comment by DerekTso** [comment]
@xyqfer 

I guess it should be the issue of the RSS Reader parsing logic.

I tried one **parsed** video url and it works.

FROM:
https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=lens&expiration=1555169264&auth_key=1555169264-0-0-1c6afdd88efc76d3390ca046ad5c247a&f=mp4&v=ali&auth_key=1555169264-0-0-1c6afdd88efc76d3390ca046ad5c247a&expiration=1555169264&v=ali&bu=com&f=mp4&disable_local_cache=0

TO (parse "&" to "\&amp;"):
https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&amp;bu=lens&amp;expiration=1555222080&amp;auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&amp;f=mp4&amp;v=ali&amp;auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&amp;expiration=1555222080&amp;v=ali&amp;bu=com&amp;f=mp4&amp;disable_local_cache=0

Is it ok to fix this ?

**Comment by LogicJake** [comment]
Actually, this video url has changed to:
https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=lens&expiration=1555222080&auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&f=mp4&v=ali&auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&expiration=1555222080&v=ali&bu=com&f=mp4&disable_local_cache=0
and it is works well and don't return 403. Maybe ZHIHU's video url is not permanent, and the old will be invalid if a new one replace the old one.

**Comment by LogicJake** [comment]
> Actually, this video url has changed to:
> https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=lens&expiration=1555222080&auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&f=mp4&v=ali&auth_key=1555222080-0-0-ee07a0249dc131b7d668d0f2e0bc011e&expiration=1555222080&v=ali&bu=com&f=mp4&disable_local_cache=0
> and it works well and don't return 403. Maybe ZHIHU's video url is not permanent, and the old one will be invalid if a new one replaces the old one.

Now, the new video url has changed to:
https://vdn.vzuu.com/LD/d182cd4e-5df6-11e9-81fe-0a580a44c112.mp4?disable_local_cache=1&bu=lens&expiration=1555229982&auth_key=1555229982-0-0-bd4490d9ee0d6652a82a44ea70484b34&f=mp4&v=ali&auth_key=1555229982-0-0-bd4490d9ee0d6652a82a44ea70484b34&expiration=1555229982&v=ali&bu=com&f=mp4&disable_local_cache=0
take notice of the value of auth_key.

**Comment by DerekTso** [comment]
@LogicJake that's to say, we should not get the URL with auth_key ? or replace it with **&v=hw** as on the original webpage.

**Comment by LogicJake** [comment]
@DerekTso 不清楚 你可以尝试一下 这个地址是从api直接获取的

**Comment by LogicJake** [comment]
@DerekTso 视频地址中有一个参数为expiration，所以应该是临时地址。。。
