### ISSUE TITLE
微信公众号 wemp 路由在新增公众号时会出现程序错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#1929]
对于之前没抓取过的公众号，rsshub大概率出现报错，过一段时间后恢复正常。
### 路由地址
https://rsshub.app/wechat/wemp/;id

### 预期是什么？
正常抓取
### 实际发生了什么？
报错 Application Error
### 部署相关信息
官方 Demo 及自建，均基于 Heroku
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/56077294-12880280-5e0d-11e9-9568-f4ad633a395b.png)

**Comment by yefoenix** [comment]
这个 issue 为啥一直没有 label ……

**Comment by DIYgod** [comment]
目测是因为源站太慢了超时了
