### ISSUE TITLE
有空格的的youtube用户名无法被订阅

### ISSUE THREAD

**Issue by cooldsf** [DIYgod/RSSHub#1934]
### 路由地址
/youtube/user/:username/:embed?
### 预期是什么？
输入用户名应该会抓取成功，比如这个（https://rsshub.app/youtube/user/Mariana's Study Corner/）
### 实际发生了什么？
出现了这个：
>RSSHub 发生了一些意外:TypeError: Cannot read property 'contentDetails' of undefined
    at module.exports (/app/lib/routes/youtube/user.js:7:103)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by yefoenix** [comment]
这不是个 Channel 吗？https://rsshub.app/youtube/channel/UCEHp_b02I0GvTYCBPX_0w1g
