### ISSUE TITLE
希望添加几个图书相关的网站

### ISSUE THREAD

**Issue by winglight** [DIYgod/RSSHub#1943]
### 源站地址
https://coderprog.com/
https://sobooks.cc/
http://mebook.cc/

### 需要生成什么内容？

- [x] 每日更新

**Comment by yefoenix** [comment]
https://feeds.feedburner.com/coderprog
https://sobooks.cc/feed
http://mebook.cc/feed

**Comment by winglight** [comment]
@yefoenix so fast!
