### ISSUE TITLE
一周精选_好奇心日报 抓取失败

### ISSUE THREAD

**Issue by BM1893** [DIYgod/RSSHub#1946]
**路由地址**
https://rsshub.app/qdaily/column/51

**Comment by DIYgod** [comment]
无法复现，可能网络波动，issue 将被关闭

**Comment by LogicJake** [comment]
@DIYgod 是有问题 内容都是空的

**Comment by bianwenbo** [comment]
好奇心日报的抓取都是失败状态。订阅以后显示的源地址都是 [https://github.com/DIYgod/RSSHub](https://github.com/DIYgod/RSSHub )

**Comment by emdoe** [comment]
> 好奇心日报的抓取都是失败状态。订阅以后显示的源地址都是 https://github.com/DIYgod/RSSHub

啊喂…都是失败状态？这个…没有的吧…？

**Comment by bianwenbo** [comment]
> > 好奇心日报的抓取都是失败状态。订阅以后显示的源地址都是 https://github.com/DIYgod/RSSHub
> 
> 啊喂…都是失败状态？这个…没有的吧…？

我刚刚复查了一下应该是我服务器那边的问题，使用 rsshub.app 订阅的都 OK，但是自己服务器搭建的有问题，我再研究下。
