### ISSUE TITLE
rss 需求：观察者网

### ISSUE THREAD

**Issue by Byhaise** [DIYgod/RSSHub#1949]
### 源站地址
https://www.guancha.cn/
### 需要生成什么内容？

- [ ] 首页及分栏目文章 rss （https://www.guancha.cn/internation
- [ ] 子栏目（https://www.guancha.cn/GuoJi%C2%B7ZhanLue/list_1.shtml
- [ ] 风闻·个人文章 （https://user.guancha.cn/user/personal-homepage?uid=248180
- [ ] 风闻·话题（https://user.guancha.cn/topic/attention-topic?follow-topic-id=127

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭

**Comment by Byhaise** [comment]
这个 issue 被关闭了，请问什么条件下可以重新开启？或者我可以重开一个观察者网的 issue 吗？ @DIYgod

**Comment by DIYgod** [comment]
> 这个 issue 被关闭了，请问什么条件下可以重新开启？或者我可以重开一个观察者网的 issue 吗？ @DIYgod

可以，但这个都半年了，重开估计也没人做...
