### ISSUE TITLE
Instagram RSS Issue - Error: Request failed with status code 404

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#195]
> RSSHub 发生了一些意外: Error: Request failed with status code 404

e.g.
[k.dappe instagram rss](https://rsshub.app/instagram/user/k.dappe)

[kyoko.takezawa instagram rss](https://rss.now.sh/instagram/user/kyoko.takezawa)

**Comment by Qixingchen** [comment]
不支持私密账户

https://www.instagram.com/k.dappe/

这是私密帐户
必须关注用户才能看到照片和视频。

**Comment by DIYgod** [comment]
404 fixed. b12e45fa2a0a20464094db03c83edd94b4977790

私密账户的问题无解
