### ISSUE TITLE
git 了最新的库 但是api/routes没有twitter pixiv等routes

### ISSUE THREAD

**Issue by ezmini** [DIYgod/RSSHub#1952]
### 实际发生了什么？
git 了最新的库 但是api/routes没有twitter pixiv等routes

### 部署相关信息
`root@vultr:~/RSSHub# git config --lis
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/DIYgod/RSSHub.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master

root@vultr:~/RSSHub# git branch -r
  origin/HEAD -> origin/master
  origin/feature/proxy
  origin/gh-pages
  origin/master
  origin/renovate/docker-redis-5.x
  origin/snyk-fix-hhoabs
root@vultr:~/RSSHub# git branch -l
* master

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
@ezmini https://docs.rsshub.app/install/#%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE

**Comment by ezmini** [comment]
root@vultr:~# cd RSSHub
root@vultr:~/RSSHub# cd lib
root@vultr:~/RSSHub/lib# cd routes
root@vultr:~/RSSHub/lib/routes# cd twitter
root@vultr:~/RSSHub/lib/routes/twitter# ls
likes.js  list.js  user.js  utils.js
root@vultr:~/RSSHub/lib/routes/twitter# 


文件是有的 但是api/routes里边就没有twitter相关的
********/api/routes/twitter
{"status":0,"data":{},"message":"request returned 0 route"}

**Comment by yefoenix** [comment]
twitter pixiv 等路由需要进行配置

**Comment by DIYgod** [comment]
https://docs.rsshub.app/install/#%E9%83%A8%E5%88%86-rss-%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE
