### ISSUE TITLE
关于Konachan路由问题

### ISSUE THREAD

**Issue by Clackz** [DIYgod/RSSHub#1965]
### 路由地址
https://rsshub.app/konachan/post/popular_recent.atom
### 预期是什么？
抓取图片的file_url
### 实际发生了什么？
在一些情况下，无法正确的抓取到图片的file_url，如[此图](https://konachan.com/post/show/282337)的file_url为
> https://konachan.com/jpeg/0ef4133c651b0b3825a033d1061f3147/Konachan.com%20-%20282337%20close%20deadnooodles%20idolmaster%20idolmaster_cinderella_girls%20yumemi_riamu.jpg

而抓取到的地址为
> https://konachan.com/image/0ef4133c651b0b3825a033d1061f3147/Konachan.com%20-%20282337%20close%20deadnooodles%20idolmaster%20idolmaster_cinderella_girls%20yumemi_riamu.png

此情况只在订阅格式为atom时发生。

**Comment by DIYgod** [comment]
url 是接口返回的

你发的两个链接都能打开，有什么影响么

**Comment by Clackz** [comment]
> url 是接口返回的
> 
> 你发的两个链接都能打开，有什么影响么

奇怪，我昨天打开第二个地址的时候是重定向到图片所在的页面去了，而不是图片的地址，导致了我在查看的时候无法显示图片。
