### ISSUE TITLE
微信瓦斯源添加失败

### ISSUE THREAD

**Issue by Aaloone** [DIYgod/RSSHub#1966]
### 路由地址
https://wx.qnmlgb.tech/authors/5c432fcb497ff46ab500a382
https://rsshub.app/wechat/wasi/5c432fcb497ff46ab500a382
### 预期是什么？
获取订阅
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
RSSHub 发生了一些意外:
TypeError: Cannot read property 'author' of undefined
    at module.exports (/app/lib/routes/tencent/wechat/wasi.js:25:30)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by jiey2016** [comment]
@DIYgod 通过瓦斯阅读订阅公众号全面失效
![image](https://user-images.githubusercontent.com/19381978/56464768-470a4880-6423-11e9-8957-91ab9396dd4f.png)

**Comment by Derekmini** [comment]
的确如上所述，我昨天pull了最新的docker镜像，通过瓦斯阅读订阅的公众号源，也遇到相同问题。

**Comment by xyqfer** [comment]
好像是接口变动了，返回的都是空的。。。
![image](https://user-images.githubusercontent.com/5186792/56468139-93bd4600-645a-11e9-97a2-d58966fac858.png)

**Comment by DIYgod** [comment]
Done. a99c1b1fbb290757e54d04dfd2eb1f96dfbeafb4
