### ISSUE TITLE
趣财经网资讯频道，求RSS制作

### ISSUE THREAD

**Issue by JoeJiao123** [DIYgod/RSSHub#1971]
### 源站地址
https://www.qcaijing.com/news
### 需要生成什么内容？

- [标题 ] 内容一
- [链接 ] 内容二

### 额外描述
摘要信息

**Comment by JoeJiao123** [comment]
FEED自制工具无法成功，求厉害的人赐教帮助

**Comment by yefoenix** [comment]
https://www.qcaijing.com/news/feed

**Comment by JoeJiao123** [comment]
@yefoenix 辛苦啦，非常感谢，希望向您学习自制feed的技能

**Comment by yefoenix** [comment]
@JoeJiao123 我只是先看了一下有没有官方RSS输出😂

**Comment by JoeJiao123** [comment]
@yefoenix  我是有RSS Feed Reader插件的，可是我查不到是否存在官方输出，求教您的方式
