### ISSUE TITLE
mp4ba rss 地址报404错误

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#1982]
### 路由地址
https://rsshub.app/mp4ba/1
https://rsshub.app/mp4ba/2
等
### 预期是什么？
出现相关条目
### 实际发生了什么？
404
### 部署相关信息
无论是官方或者自建都404了。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/56671909-0f7ff280-66e8-11e9-9e01-a75527f3c8b9.png)

**Comment by qiwihui** [comment]
这个站地址进行了改版，旧站地址变成了 ww.mp4ba.com。但是旧站上次更新是2019.04.19，估计已经不更新，需要重新对新站进行rss解析。
