### ISSUE TITLE
希望增加pleasure room网站的rss

### ISSUE THREAD

**Issue by Clackz** [DIYgod/RSSHub#1985]
### 源站地址
http://pr.reactor.cc/
### 需要生成什么内容？

- [ ] 投稿图片

### 额外描述
希望能增加[最佳投稿](http://pr.reactor.cc/best)，[最新投稿](http://pr.reactor.cc/new)等子路由

**Comment by kt286** [comment]
官方源 http://joyreactor.cc/rss
