### ISSUE TITLE
如何在树莓派（raspberry）上安装RSSHub？

### ISSUE THREAD

**Issue by industriousonesoft** [DIYgod/RSSHub#1988]
能否在树莓派（32bit）上安装RSSHub？

 我的思路是先在树莓派上安装Docker，然后在Docker运行RSSHub。目前为止Docker已经安装成功，但是使用部署文档中的方法安装和运行RSSHub时报错且直接退出。根据错误信息和Google结果是树莓派32位的系统不支持RSSHub。这也是我困惑的原因。

**Comment by junfengP** [comment]
官方自带镜像是 X86_X64架构的，而树莓派是ARM架构的。
所以官方镜像是无法运行在树莓派上的。
我这里在docker hub上搜索到了别人制作的树莓派rsshub镜像：
https://hub.docker.com/r/jie211/rpi-rsshub

我没有做过测试，不保证能运行。

**Comment by industriousonesoft** [comment]
> 官方自带镜像是 X86_X64架构的，而树莓派是ARM架构的。
> 所以官方镜像是无法运行在树莓派上的。
> 我这里在docker hub上搜索到了别人制作的树莓派rsshub镜像：
> https://hub.docker.com/r/jie211/rpi-rsshub
> 
> 我没有做过测试，不保证能运行。

谢谢！！

**Comment by HenryQW** [comment]
@industriousonesoft dumb-init 没换成 arm 架构的，应该运行不了吧

**Comment by junfengP** [comment]
自己做了个ARM32V7的镜像
https://hub.docker.com/r/pjf1996/rpi-rsshub

docker pull pjf1996/rpi-rsshub:1.0
docker run --name rsshub -d -p 1200:1200 pjf1996/rpi-rsshub:1.0
```
pi@raspberrypi:~/rpi-rsshub $ docker logs rsshub

> rsshub@0.0.1 start /app
> node lib/index.js

warn: pixiv RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Disqus RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Twitter RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Youtube RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Telegram RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: GitHub Repos RSS is disabled due to the lack of token, api key or relevant config in config.js.
info:  RSSHub start! Cheers!
info: Listening Port 1200
pi@raspberrypi:~/rpi-rsshub $ 
```
不过镜像里头没有下PUPPETEER，有的路由可能用不了。
因为我的树莓派处于一个不方便科学上网的地方，所以就下不了这些。

**Comment by industriousonesoft** [comment]
@HenryQW 对的，如果直接在树莓派上根据官方文档安装docker是运行不了的。后面我直接使用的Hypriot系统，里面内嵌了Docker

**Comment by industriousonesoft** [comment]
> 官方自带镜像是 X86_X64架构的，而树莓派是ARM架构的。
> 所以官方镜像是无法运行在树莓派上的。
> 我这里在docker hub上搜索到了别人制作的树莓派rsshub镜像：
> https://hub.docker.com/r/jie211/rpi-rsshub
> 
> 我没有做过测试，不保证能运行。

试了一下，运行不了，根据错误日志应该也是架构方面的错误，打算自己创建一个docker镜像

**Comment by tgly307** [comment]
树莓派的话，可以直接跑node应用。这样可以避免处理器兼容问题

**Comment by XdpAreKid** [comment]
@junfengP 试了一下，可以运行
