### ISSUE TITLE
简书 的 每周热门 和 每月热门 都无内容输出。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2001]
### 路由地址
https://rsshub.app/jianshu/trending/weekly
https://rsshub.app/jianshu/trending/monthly
### 预期是什么？
有相关条目
### 实际发生了什么？
无内容输出
### 部署相关信息
官方demo和自建都无内容。

之前订阅过每周热门，阅读器上查询到的上次内容输出是在3月28日，接近一个月都没内容了。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by LogicJake** [comment]
你如果去源网站查看一下的话，会发现是源网站没更新。

**Comment by ruleroller** [comment]
@LogicJake 

。。。
那我关issue了。

**Comment by LogicJake** [comment]
@ruleroller 恩 貌似简书自己还没解禁
