### ISSUE TITLE
旅法师营地rss部分分区报错

### ISSUE THREAD

**Issue by zs-river** [DIYgod/RSSHub#2008]
### 路由地址

https://rsshub.app/lfsyd/

### 预期是什么？

根据不同的订阅分区编号显示旅法师营地内不同分区的资讯。

### 实际发生了什么？

部分分区（已知包括游戏王（编号16），影之诗（编号17），昆特牌（编号14））报错，浏览器直接访问显示Application error页面。

**Comment by DIYgod** [comment]
源站超时导致的，过一会再刷新一下就好了

**Comment by yefoenix** [comment]
源站超时这个有没有办法解决一下？wemp 也有类似问题

**Comment by DIYgod** [comment]
> 源站超时这个有没有办法解决一下？wemp 也有类似问题

建议找源站优化国外访问速度，或者自建
