### ISSUE TITLE
Github Issue 支持过滤 creator

### ISSUE THREAD

**Issue by xiaosongxiaosong** [DIYgod/RSSHub#2015]
### What feature is it?
GitHub Issues 支持支持过滤 creator

### What problem does this feature solve?
使用 Giihub Issue 做博客管理系统的问题在于没法限制其他人不能新开 issue，增加过滤 creator 功能能够有效减少其他无关人员的干扰

### Additional description
使用 query 参数进行过滤
![image](https://user-images.githubusercontent.com/2703455/56863744-c46a2600-69ec-11e9-8961-fa919f6c3a25.png)

使用方式如下：
http://127.0.0.1:1200/github/issue/mqyqingfeng/Blog?creator=mqyqingfeng

效果对比：
1. 过滤前：
![image](https://user-images.githubusercontent.com/2703455/56863775-18750a80-69ed-11e9-9550-7ee49f25b7d2.png)

2. 过滤后
![image](https://user-images.githubusercontent.com/2703455/56863771-08f5c180-69ed-11e9-8124-2e655a4e2937.png)

**Comment by yefoenix** [comment]
把 creater 写到<author></author>里，然后用 filter_author 就好了，欢迎pr
