### ISSUE TITLE
Instagram application error

### ISSUE THREAD

**Issue by maXity** [DIYgod/RSSHub#2022]
### Involved route
https://rsshub.app/instagram/user/93.minho
### What is expected?
RSS feed
### What is actually happening?
Application error
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
Fixed.

**Comment by bramschulting** [comment]
Would it be possible to reopen this? The Instagram feed seems to throw an error again.
