### ISSUE TITLE
微信小程序上出现了同款

### ISSUE THREAD

**Issue by Moreki** [DIYgod/RSSHub#2023]
如图，不知道是不是由您开发
![Screenshot_20190430-015703](https://user-images.githubusercontent.com/14026143/56916461-80117f80-6aeb-11e9-9ae9-c47d8d90a68a.png)

**Comment by HenryQW** [comment]
@Moreki RSSHub 社区用户很活跃嘛

**Comment by yefoenix** [comment]
![S90430-062245](https://user-images.githubusercontent.com/8215230/56930909-d0e79f00-6b10-11e9-81cf-7b0a138148dc.jpg)
什么鬼……

**Comment by DIYgod** [comment]
@Moreki 被蹭热点了🙊
