### ISSUE TITLE
龙腾的规则坏了，求修复

### ISSUE THREAD

**Issue by dunkeng** [DIYgod/RSSHub#2024]
### 路由地址
https://rsshub.app/cctv/world
### 预期是什么？
正常抓取 http://www.ltaaa.com/wtfy.html 的内容更新
### 实际发生了什么？
没内容

**Comment by yefoenix** [comment]
这个路由地址不是CCTV吗？

**Comment by dunkeng** [comment]
> 这个路由地址不是央视吗？

我的天，，，我怎么复制了CCTV了，应该是：
https://rsshub.app/ltaaa
而且龙腾的使用说明在docs.rsshub.app也没有了，同时丢失说明的还有smzdm

**Comment by xyqfer** [comment]
@dunkeng 我怀疑你的页面没有自动滚动上去....
https://docs.rsshub.app/social-media.html#%E9%BE%99%E8%85%BE%E7%BD%91

![WX20190504-171637](https://user-images.githubusercontent.com/5186792/57176895-7e034400-6e90-11e9-9db8-8b2bbbd78a65.png)

**Comment by dunkeng** [comment]
@xyqfer 我换了个浏览器试了下，确实能找到龙腾，我去查一下是扩展还是哪个脚本有问题。
但龙腾的RSS确实不行，你的可以？

**Comment by xyqfer** [comment]
> @xyqfer 我换了个浏览器试了下，确实能找到龙腾，我去查一下是扩展还是哪个脚本有问题。
> 但龙腾的RSS确实不行，你的可以？

似乎是龙腾网站改了，每周每月全年的好像找不到了...
