### ISSUE TITLE
希望增加香港明报的rss

### ISSUE THREAD

**Issue by tratratratra** [DIYgod/RSSHub#2030]
### 需要生成什么内容？

- [ ] 内容一
- [ ] 内容二

**Comment by xtaodada** [comment]
@tratratratra 源站地址呢qwq

**Comment by yefoenix** [comment]
@tratratratra 提issue请遵循模板，提供所需信息

**Comment by tratratratra** [comment]
> @tratratratra 提issue请遵循模板，提供所需信息

已修改，请求重新审查

**Comment by yefoenix** [comment]
https://news.mingpao.com/php/rss.php

**Comment by LogicJake** [comment]
> https://news.mingpao.com/php/rss.php

是个狠人

**Comment by tratratratra** [comment]
> https://news.mingpao.com/php/rss.php
看到了，谢谢！

**Comment by DarkAge2018** [comment]
明报虽然有RSS，可不是输出全文的，这样不能够提交issue吗

**Comment by yefoenix** [comment]
@DarkAge2018 抓取全文请交给阅读器来处理
