### ISSUE TITLE
B站排行榜503

### ISSUE THREAD

**Issue by MXWXZ** [DIYgod/RSSHub#2038]
### 路由地址
https://rsshub.app/bilibili/ranking/119/3
https://rsshub.app/bilibili/ranking/4/3
还有其他一些也是的

### 预期是什么？
B站排行RSS

### 实际发生了什么？
服务器返回503

**Comment by xyqfer** [comment]
本地最新代码试了是好的，目测需要 @DIYgod 看下了....

**Comment by MXWXZ** [comment]
> 本地最新代码试了是好的，目测需要 @DIYgod 看下了....

是的本地自建的是可以，公共的炸了

**Comment by yueyericardo** [comment]
https://rsshub.app/bilibili/bangumi/media/md26360655
进击的巨人更新 也炸了

**Comment by DIYgod** [comment]
> [rsshub.app/bilibili/bangumi/media/md26360655](https://rsshub.app/bilibili/bangumi/media/md26360655)
> 进击的巨人更新 也炸了
> 
> 我想了一下，是不是因为这个bilibili区域限制了？

链接写错了，去掉 md

**Comment by DIYgod** [comment]
已修复

**Comment by yueyericardo** [comment]
> > [rsshub.app/bilibili/bangumi/media/md26360655](https://rsshub.app/bilibili/bangumi/media/md26360655)
> > 进击的巨人更新 也炸了
> > 我想了一下，是不是因为这个bilibili区域限制了？
> 
> 链接写错了，去掉 md

okok, 十分感谢！
