### ISSUE TITLE
演示地址rsshub.app中抓取wemp公众号挂了几天了

### ISSUE THREAD

**Issue by by8** [DIYgod/RSSHub#2041]
### 路由地址
我使用的是`演示地址`.

示例地址:
https://rsshub.app/wechat/wemp/36836fbe-bdec-4758-8967-7cc82722952d

尝试抓取时用的路由:
https://rsshub.app/wechat/wemp/af43023d-b385-40ed-84a5-7fff454cade5

### 预期是什么？
正常抓取
### 实际发生了什么？
对于已经抓取过(上面的示例地址)的，打不开
![image](https://user-images.githubusercontent.com/48942740/57177110-52358d80-6e93-11e9-8966-f442f2bb5fae.png)

对于之前未收录的，无法抓取
![image](https://user-images.githubusercontent.com/48942740/57177112-67122100-6e93-11e9-8cba-eb14608a6197.png)

**Comment by yefoenix** [comment]
基本确认是wemp封锁了AWS上的服务器的访问

**Comment by DIYgod** [comment]
这边做不了什么，issue 将被关闭
