### ISSUE TITLE
简书的规则挂了？求修复

### ISSUE THREAD

**Issue by justlad** [DIYgod/RSSHub#2042]
如该作者主页：https://www.jianshu.com/u/d0df8f74c800
作者ID为：d0df8f74c800

应用到规则RSS链接为：https://rsshub.app/jianshu/user/d0df8f74c800
打开该链接显示：Application error

换了好几个作者测试都是一样的情况，专题的规则也是一样的问题。

**Comment by LogicJake** [comment]
demo问题 现已正常
