### ISSUE TITLE
请求支持国家住建部政务信息

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [DIYgod/RSSHub#2045]
### 源站地址：中华人民共和国住房和城乡建设部 - <p>政策发布</p>
http://www.mohurd.gov.cn/wjfb/index.html

### 需要生成什么内容？

- [ ] 内容一：标题
- [ ] 内容二：文章内容。

### 额外描述
感谢！

**Comment by DIYgod** [comment]
请补充源站地址后 reopen

**Comment by asnfohsdgfbkxcv** [comment]
>请补充源站地址后 reopen

@DIYgod 已补充源站地址，谢谢！
http://www.mohurd.gov.cn/wjfb/index.html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
