### ISSUE TITLE
Telegram RSS doesn`t work

### ISSUE THREAD

**Issue by squromiv** [DIYgod/RSSHub#2046]
### Involved route
Telegram->RSS
### What is expected?
To get RSS from "awesomeDIYgod" telegram channel.
### What is actually happening?
The RSSHub is successfully installed and working.
![screen1](https://user-images.githubusercontent.com/15985877/57178378-5b146800-6e6f-11e9-98e4-95477a1e2568.png)

![screen2](https://user-images.githubusercontent.com/15985877/57178092-ed1a7180-6e6b-11e9-9dc7-021fe0abab48.png)
But as a result
![screen3](https://user-images.githubusercontent.com/15985877/57178100-1f2bd380-6e6c-11e9-9eb5-1546ab396813.png)

### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Windows          |
| Node version       |   10.15.0.0            |
| if Docker, version |               |

**Comment by DIYgod** [comment]
Refer to: https://docs.rsshub.app/en/#telegram

**Comment by squromiv** [comment]
Unfortunately, i don`t understand what is my mistake. Would you be so kind to specify?

**Comment by DIYgod** [comment]
You must add your telegram bot as an channel(which you want to subscibe) admin
