### ISSUE TITLE
能增加Github特定文件的commit吗

### ISSUE THREAD

**Issue by MisterGlasses** [DIYgod/RSSHub#2051]
### 源站地址
https://github.com/lhie1/Rules/commits/master/Quantumult/Quantumult.conf
### 需要生成什么内容？
Github特定文件的commit，目前github官方只能订阅整个仓库的commit。

### 额外描述
在inoreader中，订阅源中填入Github特定文件的commit网址，会被自动换为整个仓库的commit地址

**Comment by yefoenix** [comment]
https://docs.rsshub.app/programming.html#github

已经有了……

**Comment by MisterGlasses** [comment]
我眼花了 麻烦你了


________________________________
发件人: Jonathan Gongye <notifications@github.com>
发送时间: 星期日, 五月 5, 2019 20:05
收件人: DIYgod/RSSHub
抄送: Mr.Glasses; Author
主题: Re: [DIYgod/RSSHub] 能增加Github特定文件的commit吗 (#2051)


https://docs.rsshub.app/programming.html#github

已经有了……

―

**Comment by Geeyun-JY3** [comment]
挖个坟，现在 GitHub 好像已经有原生的特定文件或文件夹的 commit 的 Atom feed 了，如
- https://github.com/DIYgod/RSSHub/commits/master/lib/router.js.atom
- https://github.com/DIYgod/RSSHub/commits/master/lib.atom

也不知道什么时候增加的。
不如把这也写进文档？
