### ISSUE TITLE
【RSS需求】单读APP内容

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2058]
### 源站地址

http://app.owspace.com/owsapppc.html
（网页版仅有文章页，无索引页面，须抓取app内容

### 需要生成什么内容？

- [ ] 首页文章feed
- [ ] 分栏目文章feed

**Comment by HenryQW** [comment]
我发现接口需要一个实时 token

**Comment by yefoenix** [comment]
@HenryQW 相关讨论 ：

https://t.me/rsshub/90458
https://t.me/rsshub/87377

**Comment by yefoenix** [comment]
solved by #2809 #2822
