### ISSUE TITLE
[Telegram 频道订阅] html 转义符输出问题

### ISSUE THREAD

**Issue by YKilin** [DIYgod/RSSHub#206]
html 转义符会被原样输出而不是转义后的内容，例如 https://rsshub.app/telegram/channel/SometimesNaiveReporter

就是比如原本应该是单引号`'`，会变成转义后的`&#39;`输出，而不是输出单引号

不知道是不是所有的都有这个问题还是仅仅是 Telegram 频道订阅有这个问题……

**Comment by hufan-akari** [comment]
模版有一些问题, 先用 atom 格式吧
https://rsshub.app/telegram/channel/SometimesNaiveReporter.atom

**Comment by DIYgod** [comment]
Fixed. 25cf4fcd9a98b02f29e67bdfdb677a6995586f35

**Comment by YKilin** [comment]
感谢，已经解决
