### ISSUE TITLE
部分rss不能用 如B站 YouTube 推特 微博

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#2061]
### 路由地址
https://rsshub.app/bilibili/user/video/2577874

### 预期是什么？
https://rsshub.app/bilibili/user/video/2267573
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/33424662/57250062-1c51fe00-7079-11e9-9da3-95f2dc44a764.png)
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by jimmy-walker** [comment]
早上也发现了相同的情况。

**Comment by DIYgod** [comment]
Fixed
