### ISSUE TITLE
增加路由内缓存（全文缓存）过期时间配置项

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#2065]
### 这是一个什么样的功能？

现在全文缓存的缓存时间都是每个路由自行设置的时间，改成由外部配置

### 这个功能可以解决什么问题？

允许部署者自己取舍减少请求还是减少内存占用

**Comment by howel52** [comment]
目前我看缓存时间是在 lib/config.js 中通过 process.env.CACHE_EXPIRE || 5 * 60 获取的，「改由外部获取」指的是 ？

**Comment by DIYgod** [comment]
> 目前我看缓存时间是在 lib/config.js 中通过 process.env.CACHE_EXPIRE || 5 * 60 获取的，「改由外部获取」指的是 ？

不是全局缓存时间，比如 https://github.com/DIYgod/RSSHub/blob/e72f82e98375b3bff6d440827f2b0b36ee14a1cf/lib/routes/3dm/news_center.js#L46

**Comment by DIYgod** [comment]
Done. a0333fbd7e9604d724abaafc45cc7e4fe3f427ac c2a687a2f79f4037515dd0597bab8cc3cee16a4f

**Comment by smilingpoplar** [comment]
如果CACHE_EXPIRE设为5分钟，CACHE_CONTENT_EXPIRE设为1天，5分钟后的刷新还是会把请求发往rss源吧？CACHE_CONTENT_EXPIRE只是限制内存用的？

**Comment by hack2012** [comment]
同求解释一下，Docker部署中要不要加这个配置？
