### ISSUE TITLE
更多的支持请求

### ISSUE THREAD

**Issue by hifocus** [DIYgod/RSSHub#207]
RT，希望支持 腾讯云+ 社区，example: https://cloud.tencent.com/developer/article/1136437

还有一个想法，匹配博客系统，应用 Restful API 实现类似于 FeedBurner 这样的 RSS烧录效果（比如 https://rsshub.app/wp/tech.hxco.de 这样）。不过这个可能会造成滥用。

**Comment by hifocus** [comment]
还有 Back Of China 汇率支持：http://www.bankofchina.com/sourcedb/whpj/

中国银联汇率：http://www.kuaiyilicai.com/uprate/gbp.html

**Comment by MaekawaMiku** [comment]
@hifocus view-source:http://www.kuaiyilicai.com/bank/rmbfx/b-boc.html?v=o 看一下(

**Comment by hifocus** [comment]
@MaekawaMiku 啥？没听懂 ==

**Comment by MaekawaMiku** [comment]
@hifocus 抱歉，回复错误(

**Comment by hifocus** [comment]
但是我还是没有听懂你的意思 @MaekawaMiku

**Comment by MaekawaMiku** [comment]
@hifocus 看下html源代码(

**Comment by hifocus** [comment]
@MaekawaMiku 我看了下，比较蠢，没发现啥（

**Comment by tgly307** [comment]
如果对汇率实时性要求较高的话，使用RSS这种形式感觉有点偏了。如果一天更新一次当新闻看的话还可以
