### ISSUE TITLE
淘股吧论坛请求！

### ISSUE THREAD

**Issue by mephisX** [DIYgod/RSSHub#2085]
### 源站地址
https://www.taoguba.com.cn/index
https://www.taoguba.com.cn/blog/252069
### 需要生成什么内容？

- [ ] 内容一
追踪论坛按发帖时间更新
- [ ] 内容二
追踪论坛用户博客更新

**Comment by KwToPA** [comment]
@emode

作者 您好，我按照[文档提供的方法](https://docs.rsshub.app/other.html#%E7%94%A8%E6%88%B7%E5%8D%9A%E5%AE%A2-2)，在rsshub的服务器和我自建的vps上都没有抓取成功。

都返回
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<description>
<![CDATA[
undefined - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)
]]>
```

**Comment by KwToPA** [comment]
例如：

[https://www.taoguba.com.cn/moreReply?userID=25148](https://www.taoguba.com.cn/moreReply?userID=25148)

[https://rsshub.app/taoguba/user/25148](https://rsshub.app/taoguba/user/25148)

请问 /taoguba/user/ID 的功能，是否可以看到此id的最新跟帖

最新跟帖的url：[https://www.taoguba.com.cn/moreReply?userID=25148](https://www.taoguba.com.cn/moreReply?userID=25148)

**Comment by emdoe** [comment]
> 在rsshub的服务器和我自建的vps上都没有抓取成功
请问你的用例是 `https://rsshub.app/taoguba/user/25148` 吗？但好像我看 `https://www.taoguba.com.cn/blog/25148` 确实没有 post？

以及，请问最新跟帖那个是不是需要登录之后才能看？

**Comment by yefoenix** [comment]
这个路由写明了是博客更新，不是跟帖啊。如果有抓取跟帖的需求，请看文档提issue

**Comment by emdoe** [comment]
@yefoenix 啊…？是不是 at 错人咧，这个路由当初是我顺手做的…

**Comment by yefoenix** [comment]
@emdoe 抱歉，应该是 @KwToPA

**Comment by KwToPA** [comment]
> > 在rsshub的服务器和我自建的vps上都没有抓取成功
> 
> 请问你的用例是 `https://rsshub.app/taoguba/user/25148` 吗？但好像我看 `https://www.taoguba.com.cn/blog/25148` 确实没有 post？
> 
> 以及，请问最新跟帖那个是不是需要登录之后才能看？

我换成别的ID也不行，例如文档中的实例

[https://rsshub.app/taoguba/user/252069](https://rsshub.app/taoguba/user/252069)

[https://www.taoguba.com.cn/blog/252069](https://www.taoguba.com.cn/blog/252069)

最新跟帖的确需要 登陆

**Comment by emdoe** [comment]
> > > 在rsshub的服务器和我自建的vps上都没有抓取成功
> > 
> > 
> > 请问你的用例是 `https://rsshub.app/taoguba/user/25148` 吗？但好像我看 `https://www.taoguba.com.cn/blog/25148` 确实没有 post？
> > 以及，请问最新跟帖那个是不是需要登录之后才能看？
> 
> 我换成别的ID也不行，例如文档中的实例
> 
> https://rsshub.app/taoguba/user/252069
> 
> https://www.taoguba.com.cn/blog/252069
> 
> 最新跟帖的确需要 登陆。 我使用三方登陆（微博账号）

看了一下，我这边 https://rsshub.app/taoguba/user/252069 是可以正常访问 + 抓取的诶…
以及关于新的需求，我也建议再另开一个 issue 呢

**Comment by KwToPA** [comment]
> > > > 在rsshub的服务器和我自建的vps上都没有抓取成功
> > > 
> > > 
> > > 请问你的用例是 `https://rsshub.app/taoguba/user/25148` 吗？但好像我看 `https://www.taoguba.com.cn/blog/25148` 确实没有 post？
> > > 以及，请问最新跟帖那个是不是需要登录之后才能看？
> > 
> > 
> > 我换成别的ID也不行，例如文档中的实例
> > https://rsshub.app/taoguba/user/252069
> > https://www.taoguba.com.cn/blog/252069
> > 最新跟帖的确需要 登陆。 我使用三方登陆（微博账号）
> 
> 看了一下，我这边 https://rsshub.app/taoguba/user/252069 是可以正常访问 + 抓取的诶…
> 以及关于新的需求，我也建议再另开一个 issue 呢

几周前， https://rsshub.app/taoguba/user/252069  这个id，可以通过这个链接抓取，但今天我在chrome上打开就是denied ，当时在我自建的rsshub上 taoguba/user/252069 和今天一样无法生效。

好。已经提交新的issue

谢谢

**Comment by emdoe** [comment]
所以说 [https://rsshub.app/taoguba/user/252069 ](https://rsshub.app/taoguba/user/252069) 这个报错不是之前说的 `undefined`？方便提供一下具体的信息 / 截图嘛？

**Comment by KwToPA** [comment]
> 所以说 [https://rsshub.app/taoguba/user/252069 ](https://rsshub.app/taoguba/user/252069) 这个报错不是之前说的 `undefined`？方便提供一下具体的信息 / 截图嘛？

不好意思 打错了是 undefined，和 https://github.com/DIYgod/RSSHub/issues/2085#issuecomment-497907530 一样
