### ISSUE TITLE
新华网

### ISSUE THREAD

**Issue by mephisX** [DIYgod/RSSHub#2086]
### 源站地址
http://www.news.cn/
### 需要生成什么内容？

- [ ] 内容一
各个一级板块，如：时政、国际
- [ ] 内容二
各个二级板块，如：时政-新观察、时政-热点专题

### 额外描述
新华网更权威，新华的稿件代表国家态度，国家重大新闻，无论政府高层还是重大政策，都是新华通稿为准，人民网也只有转载的份。

**Comment by kt286** [comment]
qc.wa.news.cn/nodeart/list?nid=113352&pgnum=1&cnt=10&tp=1&orderby=1

接口是这样的
主要是 nid 和每个分类的对应规则不知道

**Comment by fasheng** [comment]
官方rss供参考：
http://www.xinhuanet.com/linktous.htm

**Comment by kt286** [comment]
> 官方rss供参考：
> http://www.xinhuanet.com/linktous.htm

牛皮 这都能找到

**Comment by Maecenas** [comment]
> > 官方rss供参考：
> > http://www.xinhuanet.com/linktous.htm
> 
> 牛皮 这都能找到

一般 HTML 的 `<head>` 里可能会带 RSS 地址，这种就要手动找了。
