### ISSUE TITLE
freebuf

### ISSUE THREAD

**Issue by ttxs69** [DIYgod/RSSHub#2105]
### 源站地址
https://www.freebuf.com/
### 需要生成什么内容？

- [ ] 首页
- [ ] 分类

**Comment by lengthmin** [comment]
@ttxs69 https://www.freebuf.com/feed

**Comment by yefoenix** [comment]
https://www.freebuf.com/sectool/feed

**Comment by ttxs69** [comment]
不好意思，我之前没找到，谢谢了
