### ISSUE TITLE
获取Bilibili用户关注视频动态出错

### ISSUE THREAD

**Issue by tomyang001** [DIYgod/RSSHub#2113]
### 路由地址
/bilibili/followings/video/:uid

### 预期是什么？
获取Bilibili用户关注视频动态 

### 实际发生了什么？
RSSHub 发生了一些意外:
TypeError: Cannot read property 'map' of undefined
    at module.exports (/home/tomyang/RSSHub/lib/routes/bilibili/followings_video.js:25:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    Ubuntu 19.04           |
| Node version       |  10.15.2             |

**Comment by DIYgod** [comment]
文档里更新了 cookie 获取方式

**Comment by NavePnow** [comment]
<img width="722" alt="Screen Shot 2019-05-13 at 00 38 30" src="https://user-images.githubusercontent.com/39482599/57585225-a38af000-7517-11e9-8013-113fc7da6797.png">
# 网址参数有问题？

**Comment by DIYgod** [comment]
> <img alt="Screen Shot 2019-05-13 at 00 38 30" width="722" src="https://user-images.githubusercontent.com/39482599/57585225-a38af000-7517-11e9-8013-113fc7da6797.png">
> 
> # 网址参数有问题？

可以忽视
