### ISSUE TITLE
Bank of China Exchange Rate RSS Typesetting Issue

### ISSUE THREAD

**Issue by sukiko789** [DIYgod/RSSHub#2121]
Hey! I am very happy to see that this RSS is completed.
But I think it is not friendly to mobile users.
When I receive it from Rssbot, I need some time to find what I need.
It's show as below:
港币 现汇买入价：87.42 现钞买入价：86.72 现汇卖出价：87.77 现钞卖出价：87.77 中行折算价：86.58
美元 现汇买入价：686.16 现钞买入价：680.58 现汇卖出价：689.07 现钞卖出价：689.07 中行折算价：679.54

Would you kindly check if can be set to display as shown below:
港币
现汇买入价：87.42
现汇卖出价：87.77
中行折算价：86.58
现钞买入价：86.72
现钞卖出价：87.77

美元
现汇买入价：686.16
现汇卖出价：689.07
中行折算价：679.54
现钞买入价：680.58
现钞卖出价：689.07

Thanks for your develop, and waiting for your good news. 😊

**Comment by DIYgod** [comment]
@sukiko789 一般阅读器标题都无法换行

**Comment by sukiko789** [comment]
> @sukiko789 一般阅读器标题都无法换行

May I know if you mean this RSS' title is not "Bank of China Exchange Rate"?
