### ISSUE TITLE
 NEW ENGLAND RSS

### ISSUE THREAD

**Issue by gusiyulalalulu** [DIYgod/RSSHub#2124]
### 源站地址
https://www.nejm.org/oncology-hematology?query=main_nav_lg
### 需要生成什么内容？
rss
- [ ] 内容一
- [ ] 内容二

**Comment by kt286** [comment]
所有分类的订阅地址都在这里
https://www.nejm.org/action/showPodcastsFeeds

你要的那个是
http://search.nejm.org/search?cnt=20&start_month=6&start_year=2009&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:2

需要账号密码

**Comment by gusiyulalalulu** [comment]
非常感谢，回去试一下


发自我的iPhone

------------------ Original ------------------
