### ISSUE TITLE
色花堂中文板块高清rss

### ISSUE THREAD

**Issue by myhloli** [DIYgod/RSSHub#2132]
### 源站地址
https://www.dsndsht23.com/forum-103-1.html
### 需要生成什么内容？

- [ ] 内容一
帖子标题
如：[有码] MIDE-650 父母都出去旅游的女友七泽美亚邀请还是处男的我到她家住宿[高清中文字幕]  
- [ ] 内容二
磁力链接
如：magnet:?xt=urn:btih:1F7FAFC276B3C9445A2CF634D74860A2C7D37587
### 额外描述
最好写成适用群晖downloadstation能直接识别的格式，方便直接下载，谢谢

**Comment by junfengP** [comment]
没有老司机开车吗

**Comment by tgly307** [comment]
老司机把车停在了网站上，自己下了车

**Comment by qiwihui** [comment]
群晖 downloadstation 能识别什么样的格式？ @myhloli

**Comment by MySadCaptain** [comment]
@junfengP 色花堂的路由现在似乎用不了，在群晖中尝试加入feed时提示"下载RSS文件时发生错误，请确认您的网络设置与下载链接是否正确“，在Reeder里测试了也不行
