### ISSUE TITLE
希望Hpoi 手办维基 能够获取所有手办的更新消息

### ISSUE THREAD

**Issue by kosserYN** [DIYgod/RSSHub#2133]
### 这是一个什么样的功能？
在RSS中获取所有更新信息
### 这个功能可以解决什么问题？
方便眼缘
### 额外描述
原网站的https://www.hpoi.net/rss 失效

**Comment by howel52** [comment]
「所有手办」指的是 https://www.hpoi.net/user/home?type=all 该路由下的内容么？

**Comment by kosserYN** [comment]
> 「所有手办」指的的英文https://www.hpoi.net/user/home?type=all该路由下的内容么？

https://www.hpoi.net/user/home?type=info&subType=

这里的

**Comment by sanmmm** [comment]
@DIYgod 
已经在pr #2760 里面提供了
