### ISSUE TITLE
pixiv rss 500

### ISSUE THREAD

**Issue by whtsky** [DIYgod/RSSHub#214]
https://rsshub.app/pixiv/user/11
https://rsshub.app/pixiv/user/bookmarks/19316994

> RSSHub 发生了一些意外: InternalServerError: Internal Server Error

**Comment by DIYgod** [comment]
现在好了，有时候 pixiv 会登录失败，我需要检查下重试机制有没有生效

**Comment by DIYgod** [comment]
重试机制正常，猜测是 pixiv 封了 heroku 某些机器的 IP，暂时无解

**Comment by MaekawaMiku** [comment]
@DIYgod 换服务器吧(大雾
