### ISSUE TITLE
免添加 bot 的 Telegram 频道消息获取

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#2140]
### 这是一个什么样的功能？

通过 user 接口获取消息

### 这个功能可以解决什么问题？

user 可以直接获取消息，不再需要频道主添加 bot 为管理员才能订阅相应频道

### 额外描述

目测自己实现难度较大，可能需要第三方库：

https://github.com/LonamiWebs/Telethon

https://github.com/zerobias/telegram-mtproto

**Comment by Arler2016** [comment]
@DIYgod 可以用 @junction_bot 将不同频道内容转发到同一个群或频道，然后加 RSS机器人来实现

**Comment by DIYgod** [comment]
@DIYgod 忽略上面，用 https://t.me/s/awesomeDIYgod

**Comment by yefoenix** [comment]
可以 close 咯
