### ISSUE TITLE
[rss 需求] 飞地APP内容

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2147]
### 源站地址
https://www.enclavebooks.cn
（APP内容）
### 需要生成什么内容？

- [ ] 首页内容
- [ ] 分栏目内容

### 额外描述
首页API：http://app.enclavebooks.cn//v2/index?page=1&timeStamp=1557712745
栏目列表：https://app.enclavebooks.cn/v2/discovery
栏目文章列表：https://app.enclavebooks.cn/v1_9/getCategoryList?cateId=15&page=1&userId=0
文章内容：https://app.enclavebooks.cn/v2/article?id=21311&userId=0

**Comment by LogicJake** [comment]
强
