### ISSUE TITLE
tg Channel 中，带说明的图片推送的图片会有缺失

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2153]
### 路由地址
https://rsshub.app/telegram/channel/PicACG
### 预期是什么？
正常显示条目图片
### 实际发生了什么？
对于带说明的图片推送，如 https://t.me/PicACG/568 ，图片会有缺失
### 部署相关信息
demo
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/57900138-433adc00-7892-11e9-8ce6-d8d67f049501.png)

**Comment by DIYgod** [comment]
Fixed. 81622bb3d6ddbbe1e3424e3801e2cb2218782461
