### ISSUE TITLE
通知模版

### ISSUE THREAD

**Issue by wsqstar** [DIYgod/RSSHub#2164]
### 源站地址
jwc.某大学.edu.cn
### 需要生成什么内容？

- [ ] 就是看一下通知就好啦
- [ ] 希望可以填写自己大学简称 

### 额外描述
这样可以提高易用性，推广rsshub，增强鲁棒性，同时可以提防挂掉

**Comment by DIYgod** [comment]
@wsqstar 没看懂

**Comment by wsqstar** [comment]
![image](https://user-images.githubusercontent.com/24500520/57931064-33e77d00-78ea-11e9-971a-07d7b93a190a.png)
大学通知算是比较多的路由了，但是很多大学都使用了同样/相似的网页结构，甚至都是使用了同样的正方教务系统。
很想要一个整合的路由，可以选择自己订阅的一系列大学的通知（对于收取保研/学术通知是非常有帮助的），这样也就不用写一大堆路由了。只需要修改几个参数就OK～ 
感谢DIYgod回复！

**Comment by DIYgod** [comment]
@wsqstar 通知一般不是用的正方教务系统吧，每个大学都不一样没法整合啊

**Comment by yefoenix** [comment]
@wsqstar 看一下文档的「通用配置型路由」部分
