### ISSUE TITLE
希望增加对一览订阅的支持

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#2165]
一览阅读中非常多的订阅无法导出，希望像支持今日热榜、即刻那样支持一览。
### 源站地址
http://www.yilan.io/

http://www.yilan.io/search/?searchText=%E5%BB%96%E9%9B%AA%E5%B3%B0&searchType=site
### 需要生成什么内容？
- [ ] 站点订阅
- [ ] 主题订阅
- [ ] 文章订阅
- [ ] 用户订阅
- [ ] 一览内的RSS源转换成公共可用订阅
- [ ] 优酷

**Comment by DIYgod** [comment]
时间过长，issue 将被关闭

源站地址也打不开了
