### ISSUE TITLE
微博抓取博主（方案 2）失效

### ISSUE THREAD

**Issue by zby1234** [DIYgod/RSSHub#2169]
### 路由地址
https://rsshub.app/weibo/user2/1195230310
### 预期是什么？
抓取微博
### 实际发生了什么？
方案2无法抓取
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Ubuntu             |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
源站失效：http://service.weibo.com/widget/widget_blog.php?uid=1195230310

如果过几天还是没有恢复此路由将被删除

**Comment by DIYgod** [comment]
路由已移除
