### ISSUE TITLE
能否制作一下 t66y.com （草榴社区）总站全部帖子以及各分区帖子的RSS。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#217]
草榴站点上写着rss的地方不少，但点进去都是404，不知道是不是我打开方式不对，所以还是希望rsshub能支持掉它。

^_^

**Comment by tgly307** [comment]
这种……有能力还是自娱自乐吧。域名有可能变动，而且内容也不合适做成通用的。

**Comment by ruleroller** [comment]
@tgly307 野生复制草榴是为了给墙内的人看做的，真正的草榴社区的域名一直是t66y.com ，[维基](https://zh.wikipedia.org/wiki/%E8%8D%89%E6%A6%B4%E7%A4%BE%E5%8C%BA)。

就针对这个网址做，其它的copy网站不用做。

**Comment by tgly307** [comment]
**内容也不合适**，不建议。

**Comment by tgly307** [comment]
如果twitter也是色情论坛，当然不合适。

**Comment by DIYgod** [comment]
合法网站都没什么问题，但这种内容优先级低，没有pr的话可能要等很久才会做

**Comment by DIYgod** [comment]
重复 https://github.com/DIYgod/RSSHub/issues/2

**Comment by vanxv** [comment]
@DIYgod DIY小王子你怎么懂这么多.可以可以.
带我写点code呗.我想搞站做seo
