### ISSUE TITLE
anigamer的new_anime.js

### ISSUE THREAD

**Issue by penjune** [DIYgod/RSSHub#2171]
RSSHub/lib/routes/anigamer/new_anime.js
### 这是一个什么样的功能？
将原版第18行修改为 : 
link: `https://ani.gamer.com.tw/animeVideo.php?sn=${item.video_sn}`,

### 这个功能可以解决什么问题？
原版的link: `https://ani.gamer.com.tw/animeRef.php?sn=${item.anime_sn}`,
只能跳转至该番剧的第一集，修改后可以连结至番剧的最新集数

### 额外描述

**Comment by yefoenix** [comment]
欢迎pr
