### ISSUE TITLE
Twitter  Instagram 用户没有更新 rsshub 会推送更新

### ISSUE THREAD

**Issue by 1oe** [DIYgod/RSSHub#2178]

**Comment by yefoenix** [comment]
提issue请遵循模板

**Comment by 1oe** [comment]
@DIYgod 

### 路由地址
<https://rsshub.app/twitter/user/vousmevoyez>
### 预期是什么？
正常推送
### 实际发生了什么？
重复推送
### 部署相关信息



| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

**Comment by DIYgod** [comment]
RSS 没问题，请自行检查你的推送服务
