### ISSUE TITLE
希望支持少数派专题topic的支持(不是专栏)

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#2183]
希望支持少数派专题topic的支持(不是专栏)
### 源站地址
https://sspai.com/topics
https://sspai.com/topic/252
### 需要生成什么内容？

- [x] 专题广场新专题监控
- [x]  #特定专题下新文章

**Comment by HenryQW** [comment]
https://github.com/DIYgod/RSSHub/pull/2185 增加了专题支持。

https://docs.rsshub.app/other.html#%E4%B8%93%E9%A2%98-2

https://docs.rsshub.app/other.html#%E4%B8%93%E9%A2%98%E5%86%85%E6%96%87%E7%AB%A0%E6%9B%B4%E6%96%B0
