### ISSUE TITLE
iOS的软件更新路由在ifttt里订阅后，不能触发。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2191]
### 路由地址
/appstore/update/:country/:id
### 预期是什么？
我在ifttt里使用的是RSS to mail，订阅了Telegram的更新链接 https://rsshub.app/appstore/update/us/id686449807 ，和其它一些软件的更新，可像Telegram更新好几回了，一次都未能触发过。自己在使用rssbot时倒是能触发，不知问题出在哪里，还是提个issue。
### 实际发生了什么？
软件更新后，ifttt不能触发。
### 部署相关信息
官方demo、自建都如此。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
订阅的软件更新，没一个能触发的……

**Comment by DIYgod** [comment]
RSS 没发现问题，建议找 IFTTT 方面寻求帮助

**Comment by SettingDust** [comment]
@DIYgod 多半是不过ifttt的rss的验证

**Comment by ruleroller** [comment]
@DIYgod @SettingDust 猜测是ifttt那边的验证rss是否更新的机制导致的吧。我同样用ifttt订阅了一些人的微博，都能顺利触发的，可iOS软件更新却不行。我仔细观察了下生成的RSS内容，iOS软件更新的路由，每次更新后，始终只有最新的一条，或许就是这个原因导致ifttt在识别上发生故障，认为没有更新故而不触发。
