### ISSUE TITLE
语雀-知识库 路由 item 时间和链接错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2206]
### 路由地址
/yuque/doc/102804
### 预期是什么？
正常抓取
### 实际发生了什么？
item时间和链接错误
### 部署相关信息
自建heroku
已配置语雀token
主线 master 分支最新版 RSSHub

### 额外信息（日志、报错等）
![S90522-222440](https://user-images.githubusercontent.com/8215230/58183918-bdc88900-7ce2-11e9-9a37-334b72d8a5bd.jpg)
如上图，2019/05/17 内容pubdate为20190327，且链接item打开返回404

**Comment by DIYgod** [comment]
@aha2mao 貌似链接都是 404

**Comment by aha2mao** [comment]
> @aha2mao 貌似链接都是 404

链接问题已修复

**Comment by aha2mao** [comment]
@DIYgod 链接问题已修复

**Comment by aha2mao** [comment]
@yefoenix  时间取自语雀返回的created_at字段 你是希望取published_at？
https://www.yuque.com/api/v2/repos/102804/docs/1436492

**Comment by yefoenix** [comment]
@aha2mao 阮一峰这个每周分享，5月17号的内容显示为3.27您觉得合适么……
pubdate 的意思 就是 publish date 不是么

**Comment by aha2mao** [comment]
@yefoenix 已修复 待merge

**Comment by yefoenix** [comment]
@aha2mao 谢谢～
