### ISSUE TITLE
How to deploy docker image using https?

### ISSUE THREAD

**Issue by CarlosEvo** [DIYgod/RSSHub#2218]
### What feature is it?

Deploying RSSHub docker image using https with self-signed certificate.

### What problem does this feature solve?

Traffic integrity via SSL.

### Additional description

Is there a way to serve RSSHub docker image on https? It is not mentioned in the documentations, but I wish to have more control over my traffics.

**Comment by DIYgod** [comment]
Please Google: nginx + proxy
