### ISSUE TITLE
豆瓣 v2 API 失效

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2221]
### 路由地址

`/douban/*` 里的大部分？

### 原因

直接访问显示 `invalid_apikey`。

### 可能的解决方案

1. 使用移动端 API（似乎需要移动端 User-Agent），比如影院热映: `https://m.douban.com/rexxar/api/v2/subject_collection/movie_showing/items?os=ios&for_mobile=1&callback=?` 
2. 使用反向代理: https://github.com/zce/douban-api-proxy

**Comment by DIYgod** [comment]
重复 #1781
