### ISSUE TITLE
动漫狂 cartoonmad 失效

### ISSUE THREAD

**Issue by Maecenas** [DIYgod/RSSHub#2223]
### 路由地址

<https://rsshub.app/cartoonmad/comic/1221>，或该路由的任意地址

### 预期是什么？

正常抓取页面

### 实际发生了什么？

```
RSSHub 发生了一些意外:
Error: write EPROTO 139840106727232:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
```

### 部署相关信息

演示地址（rsshub.app）

### 额外信息（日志、报错等）

看了一下报错发生在 `axios` 这里：

https://github.com/DIYgod/RSSHub/blob/2b80b7eb502fc6b2111f4ef18da5405b9e186765/lib/routes/cartoonmad/comic.js#L33-L39

错误信息 SSL Unsupported Protocol，网站最高支持 TLS v1.0（用 Chrome Dev Tool、`openssl` 也可以看）

[![SSL Labs](https://user-images.githubusercontent.com/26927236/58298965-64627600-7e18-11e9-9deb-7dbd8ab0caf2.png)](https://www.ssllabs.com/ssltest/analyze.html?d=www.cartoonmad.com&hideResults=on)

`axios` 对于 TLS 的处理是[封装了 `Node.js` 的原生库 `http`、`https`](https://github.com/axios/axios/blob/master/lib/adapters/http.js)，而本地 Node.js 12 可以复现这个问题，同时使用 Dockerfile 部署的 `node:10.15-slim`（是不是用 `10-slim`、`lts-slim` 更好点）能够正常抓取。查文档发现 Node.js v11.4.0 增加了 [tls.DEFAULT_MIN_VERSION](https://nodejs.org/api/tls.html#tls_tls_default_min_version)，默认值 `TLS v1.2`，而代替了 Node.js v10.x [默认对最低版本 `TLS v1.0` 的支持](https://nodejs.org/docs/latest-v10.x/api/tls.html)。

另外，这个站应该是最近逐渐迁移到 HTTPS 的，等站长升级到至少 `TLS v1.2` 问题就自动解决了，在此之前用自建的就可以。

**Comment by zengxs** [comment]
node 启动时加上 `--tls-min-v1.0` 参数应该就可以解决这个问题

**Comment by DIYgod** [comment]
> node 启动时加上 `--tls-min-v1.0` 参数应该就可以解决这个问题

demo 加上参数了，已恢复
