### ISSUE TITLE
多公众号聚合的 tg channnel 路由抓取错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2225]
### 路由地址
https://rsshub.app/wechat/tgchannel/wemps
### 预期是什么？
正常抓取
### 实际发生了什么？
item的 title/guid/link 为空
### 部署相关信息
官方 demo
### 额外信息（日志、报错等）
https://t.me/s/wemps 这个频道是同时聚合了多个公众号，输出格式与一对一绑定的稍有不同。建议将公众号名称加到title或author中。
![image](https://user-images.githubusercontent.com/8215230/58303187-93311a00-7e21-11e9-9041-8568f31b02b3.png)

**Comment by LogicJake** [comment]
一并在 #2208 解决了

**Comment by yefoenix** [comment]
> 一并在 #2208 解决了

用上了 ，谢谢 @LogicJake
