### ISSUE TITLE
「文档有误」Docker 环境变量配置多于一个时， 要有多个 -e

### ISSUE THREAD

**Issue by fengkx** [DIYgod/RSSHub#223]
`docker run -d --name rsshub -p 1200:1200 -e CACHE_EXPIRE=600 GITHUB_ACCESS_TOKEN=gitHubToken77d4a3thisIsAnExmaple  diygod/rsshub`

> docker: invalid reference format: repository name must be lowercase.

-e 实际环境下，-e 参数要于环境变量一一对应
`docker run -d --name rsshub -p 1200:1200 -e CACHE_EXPIRE=600 -e GITHUB_ACCESS_TOKEN=gitHubToken00d877d4a36thisIsAnExmaple  diygod/rsshub`

sucess

**Comment by DIYgod** [comment]
Fixed. aff366edc7c9cab3846c4af3f2f78e953c63899a
