### ISSUE TITLE
希望增加财新网要闻的订阅

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#2239]
目前有财新网的rss，但需要根据板块和板块下的目录来订阅，这样订阅的数量会比较多。财新网有提供各板块要闻的api，可以直接使用，希望能增加下。

![20190526_211301](https://user-images.githubusercontent.com/15177069/58382459-f7f49c00-7ffc-11e9-9182-2555d40ad9e1.jpg)

### 源站地址
以经济板块为例，其下全部要闻的channel为129，api地址为：http://tag.caixin.com/news/homeInterface.jsp?channel=129&start=1&count=21&picdim=_145_97&callback=jQuery17209699614940338102_1558876262708&_=1558876466974 ，其中start为新闻的开始条数，count为输出新闻的数量

### 需要生成什么内容？

- [ ] 新闻标题
- [ ] 新闻摘要

**Comment by hello532** [comment]
顶起。不错的。也需要。
