### ISSUE TITLE
希望支持AI研习社

### ISSUE THREAD

**Issue by harrylyx** [DIYgod/RSSHub#2248]
### 源站地址
https://ai.yanxishe.com/
### 需要生成什么内容？

- [ ] 最新内容
- [ ] 最热内容

**Comment by kt286** [comment]
最热内容涉及到时间线的问题 同一篇文章可能会多次显示 没弄
最新内容差不多了，你再等等

**Comment by lyh404** [comment]
最近貌似都不可用。
