### ISSUE TITLE
且听风吟福利吧没有内容

### ISSUE THREAD

**Issue by Clackz** [DIYgod/RSSHub#2256]
### 路由地址
https://rsshub.app/qtfyfl/latest
### 预期是什么？
抓取文章内容
### 实际发生了什么？
![0UC(H($J0}MN_ZJ8MCI098](https://user-images.githubusercontent.com/42225208/58541765-cbc06180-822e-11e9-8bb8-8e5f339c6cb5.png)

**Comment by kt286** [comment]
自建木有问题 应该是网络问题

**Comment by kt286** [comment]
原网站貌似废了   现在变成了一个乱七八糟的玩意

**Comment by DIYgod** [comment]
源站问题无法解决
