### ISSUE TITLE
修改 feed icon 的功能

### ISSUE THREAD

**Issue by fengkx** [DIYgod/RSSHub#2258]
### 这是一个什么样的功能？
已有的路由能够通过 querystring 或者其他方式修改 feed 中有关图标的 field

新路由增加一个域可以设置生成的 feed 中相关的的 field

## 这个功能可以解决什么问题？
在支持的阅读器里面订阅源的图标不会清一色是 RSSHub

### 额外描述

相关的 field：
atom:icon：https://tools.ietf.org/html/rfc4287#section-4.2.5
atom:logo: https://tools.ietf.org/html/rfc4287#section-4.2.8

rss:image: https://validator.w3.org/feed/doc/rss2.html#ltimagegtSubelementOfLtchannelgt

参考：https://snook.ca/archives/rss/add_logo_to_feed

**Comment by DIYgod** [comment]
可以通过 image 参数实现：https://github.com/DIYgod/RSSHub/blob/master/lib/views/rss.art#L17

不应该由外部自定义
