### ISSUE TITLE
快递的路由似乎出问题了，显示“查无结果”，或其它莫名其妙的信息。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2261]
### 路由地址
https://rsshub.app/express/shentong/<申通快递单号，大家试试自己的申通单号>
### 预期是什么？
正常显示快递更新信息
### 实际发生了什么？
显示“查无结果”，用机器人订阅，会刷出莫名其妙的结果。
![image](https://user-images.githubusercontent.com/3047708/58578007-5da18c00-827a-11e9-97b9-2dcc9f485d3d.png)

### 部署相关信息
demo的最新版

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
我在kuaidi100网站查询是正常显示结果的，淘宝那里的显示也是正常的。
之前用汇通的也是出现各种奇怪的结果，或许是kuaidi100那儿有更改，导致路由失灵？
除此之外，未测试其它的快递公司的信息是否正常显示。

**Comment by summersonmer** [comment]
尝试了一下，似乎现在的请求里面必须包含 temp 参数和 cookie ，temp 参数生成方式未知，且一个 temp 参数有有限次的请求次数，超过次数会返回“查无结果”，偶尔会随机返回其他快递信息，不知道是不是 api 有变更

**Comment by DIYgod** [comment]
快递路由将被移除

**Comment by NeverBehave** [comment]
> 尝试了一下，似乎现在的请求里面必须包含 temp 参数和 cookie ，temp 参数生成方式未知，且一个 temp 参数有有限次的请求次数，超过次数会返回“查无结果”，偶尔会随机返回其他快递信息，不知道是不是 api 有变更

From: https://cdn.kuaidi100.com/js/page/sz/query_v5.js?version=201911051510

![image](https://user-images.githubusercontent.com/17120571/74684556-3be68d00-519a-11ea-942b-7d9fdbc95eec.png)

由此得出，temp其实是无所谓的

我测试的结果是如果Cookie中没有合法的`WWWID`，会导致结果无效。
获得的方法是正常访问一次，从`set-cookie`中定时获取新的cookie，构造query即可
