### ISSUE TITLE
希望添加 sky sports 的足球栏目

### ISSUE THREAD

**Issue by budaobu** [DIYgod/RSSHub#2263]
### 源站地址

[天空体育足球](https://www.skysports.com/football)
[球队：AC米兰赛果](https://www.skysports.com/ac-milan-results)
[球队：亚特兰大新闻](https://www.skysports.com/atalanta-news)

### 需要生成什么内容？

- [ ] 球队新闻
- [ ] 球队赛果

**Comment by TonyRL** [comment]
Closed in #7968
