### ISSUE TITLE
知乎专栏又挂了

### ISSUE THREAD

**Issue by KenWuqianghao** [DIYgod/RSSHub#2268]
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/58637855-5ebed180-82eb-11e9-8232-f25764912d17.png)
![image](https://user-images.githubusercontent.com/5896343/58637855-5ebed180-82eb-11e9-8232-f25764912d17.png)
![image](https://user-images.githubusercontent.com/5896343/58637855-5ebed180-82eb-11e9-8232-f25764912d17.png)

**Comment by KenWuqianghao** [comment]
当然知道反爬严格，所以才要及时汇报

**Comment by yefoenix** [comment]
@KenWuqianghao 反爬严格的意思是，Demo被ban 不可用是常态，需要自建才能解决。
