### ISSUE TITLE
增加文档：「参与我们」开发部分描述 cache

### ISSUE THREAD

**Issue by Maecenas** [DIYgod/RSSHub#2275]
### 这是一个什么样的功能？

增加「参加我们」开发部分的文档，对 [`config.cache`](https://github.com/DIYgod/RSSHub/blob/master/lib/config.js#L15-L19) 介绍一二

### 这个功能可以解决什么问题？

在开发时由于 `routeExpire`、`contentExpire` 等设置不当，路由的输出命中缓存，结果不合预期

### 额外描述

不知道内存缓存 `lru-cache` 实现是不是有持久化操作，使用默认配置后未能显示出最新开发结果，重启电脑后缓存仍未清除。

**Comment by DIYgod** [comment]
一般并不需要设置 `routeExpire`、`contentExpire` 啊，什么情况会用到？

`lru-cache` 不是持久化操作，重启程序缓存会消失

**Comment by Maecenas** [comment]
> `lru-cache` 不是持久化操作，重启程序缓存会消失

本地开发调试的时候，配置全部用默认，不知道是不是 `routeExpire` 的原因，路由返回结果（Chrome v72 隐私模式+强制创新）没有刷新。尝试过重启进程/关闭进程/重启电脑，Run 和 Debug 都是用的 WebStorm IDE 跑 `npm run dev`。环境信息是 macOS v10.14.4、Node v12.3.1。

怀疑过有可能是浏览器缓存的问题，但是试了本地 Reeder 和 Postman 也是一样的结果。后面换了台机器跑起来，才确定开发结果是正确的，本地有奇怪的缓存。

**Comment by DIYgod** [comment]
不应该啊，debug 下 [cache.js](https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/cache.js) 看看原因

**Comment by Maecenas** [comment]
> 不应该啊，debug 下 [cache.js](https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/cache.js) 看看原因

不能准确复现（但是我遇到不止一次了），下次遇到了看一下。这个 Issue 要先关掉吗？

**Comment by DIYgod** [comment]
我这边没能复现，下次遇到可以看看中间件的 cache 有没有 get 到数据，那 issue 先关掉了
