### ISSUE TITLE
【淘股吧论坛】新功能请求——追踪用户的最新跟帖

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2281]
### 源站地址

[https://www.taoguba.com.cn/](https://www.taoguba.com.cn/)

### 需要生成什么内容？

- [ ] 追踪用户的最新跟帖

url ：https://www.taoguba.com.cn/moreReply?userID=ID号码

例如 

管理员账号 [https://www.taoguba.com.cn/moreReply?userID=2](https://www.taoguba.com.cn/moreReply?userID=2)

### 额外描述

最新跟帖页面，登陆可见。

三方登陆有：微信，微博，QQ

@emdoe   谢谢

**Comment by DIYgod** [comment]
没有公开可访问页面的话会很困难
