### ISSUE TITLE
希望增加saraba1st论坛外野板块的rss

### ISSUE THREAD

**Issue by matthewdphilip** [DIYgod/RSSHub#2282]
源站地址：https://bbs.saraba1st.com/2b/forum-75-1.html
生成内容：

- [ ] 最新帖子

额外描述：看到rsshub文档页面有针对s1论坛具体帖子的rss，但是没有外野板块的，希望能增加

**Comment by DIYgod** [comment]
没有公开可访问页面会很困难

**Comment by TonyRL** [comment]
https://docs.rsshub.app/bbs.html#saraba1st
