### ISSUE TITLE
新需求——【互动易】股票的动态更新

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2287]
### 源站地址

互动易：[http://irm.cninfo.com.cn/](http://irm.cninfo.com.cn/)

### 需要生成什么内容？

- [ ] 更新某股票的【动态】

例如，股票002732

http://irm.cninfo.com.cn/ircs/company/companyDetail?stockcode=002732

- [ ] 更新综合资讯--勾选问答--只看已回复

http://irm.cninfo.com.cn/ircs/index

### 额外描述

无

**Comment by HenryQW** [comment]
珍爱生命，远离 A 股。
