### ISSUE TITLE
NGA的路由失效

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2295]
### 路由地址
https://rsshub.app/nga/forum/459
https://rsshub.app/nga/post/15939161
### 预期是什么？
生成内容
### 实际发生了什么？
第一个路由，报以下错误。
![image](https://user-images.githubusercontent.com/3047708/58811764-fce7ca00-8652-11e9-95d3-3b08581d241e.png)

第二个路由，403
![image](https://user-images.githubusercontent.com/3047708/58812384-569cc400-8654-11e9-8b5f-84dc12311868.png)

### 部署相关信息
官方demo和自建都类似错误

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
似乎是在6月3日11时之后发生的错误。还在使用axios的旧版倒是没报错，只是无内容，如下图：
![image](https://user-images.githubusercontent.com/3047708/58812045-96af7700-8653-11e9-9500-3d565cd344e7.png)

啊，写到这里，打开nga论坛一看，发现现在需要登录才能查看帖子，或许失效是因为这个原因吧。。

**Comment by DIYgod** [comment]
got 的问题修复了，还存在没数据的问题待解决

**Comment by DIYgod** [comment]
目前全站登录可见，不知道过了这段敏感时期会不会恢复，保持关注

**Comment by ruleroller** [comment]
@DIYgod NGA现已恢复不登录就能看贴。

在旧版的axios下，自建的rsshub能正常获取更新。

新got版，在你修复后，无论是demo还是自建，仍旧出错，错误信息请见图片：
![image](https://user-images.githubusercontent.com/3047708/59051302-1c832a80-88bf-11e9-94b2-bb57c8b72d93.png)

**Comment by DIYgod** [comment]
#2342
