### ISSUE TITLE
Mp4ba 更新 URL

### ISSUE THREAD

**Issue by 1oe** [DIYgod/RSSHub#2298]
### 路由地址
https://rsshub.app/mp4ba/1
### 预期是什么？
新 url 地址 <http://m.mp4ba.com>
### 实际发生了什么？
- URL 错误 
- 所有内容都是同一张图片
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
无法复现，且源站本来就有很多重复内容
