### ISSUE TITLE
关于单页应用内容的抓取？

### ISSUE THREAD

**Issue by huruji** [DIYgod/RSSHub#23]
查了一下，只查到使用 [phantomjs](https://github.com/ariya/phantomjs) 、[puppeteer](https://github.com/GoogleChrome/puppeteer) 这类Headless Browser模拟浏览器行为，大家有啥经验或者解决方案吗？orz

**Comment by DIYgod** [comment]
有类似 issue https://github.com/DIYgod/RSSHub/issues/3

但这种方式效率较低，暂时也没遇到必须要用 headless browser 的情况，以后遇到再加
