### ISSUE TITLE
微博 - 超话 路由抓取错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2302]
### 路由地址
https://rsshub.app/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9
### 预期是什么？
正常抓取
### 实际发生了什么？
报错
### 部署相关信息
官方 Demo
### 额外信息（日志、报错等）
（未更新的）heroku 自建没有问题，可正常抓取。
报错信息：
>RSSHub 发生了一些意外:
>TypeError: Cannot read property 'indexOf' of undefined
>    at got.extend.hooks.afterResponse (/data/wwwroot/rsshub.app/lib/utils/got.js:62:54)
>    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:39:23)
>    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by DIYgod** [comment]
Fixed. 907d7498ca13f614e382b1882f3778a7334f2025
