### ISSUE TITLE
好奇怪-首页 路由抓取失败

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2303]
### 路由地址
https://rsshub.app/qdaily/notch/posts
### 预期是什么？
正常抓取
### 实际发生了什么？
 报错
### 部署相关信息
官方 Demo.
（未更新的）heroku 自建没有问题，可正常抓取。
### 额外信息（日志、报错等）
报错：
![image](https://user-images.githubusercontent.com/8215230/58846249-1caddb00-86b1-11e9-95b5-766ea79a4866.png)

**Comment by DIYgod** [comment]
Fixed 2bd3b39fcd3af322d332ad810480301b165aa8e0
