### ISSUE TITLE
36Kr - 搜索文章 路由抓取错误

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2304]
### 路由地址
https://rsshub.app/36kr/search/article/8%E7%82%B91%E6%B0%AA
### 预期是什么？
正常抓取
### 实际发生了什么？
报错
### 部署相关信息
官方 Demo 及 Heroku 自建均报错
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/58847369-479a2e00-86b5-11e9-9cce-7f2866f92e2b.png)

**Comment by LogicJake** [comment]
接口改成post了，且有token验证。
