### ISSUE TITLE
微信公众号瓦斯阅读失效

### ISSUE THREAD

**Issue by William96911** [DIYgod/RSSHub#2312]
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
请按模板要求提供具体信息，目前 demo 示例没有问题 https://rsshub.app/wechat/wasi/5b575db858e5c4583338db11

**Comment by xyqfer** [comment]
应该就是链接不对吧。。。

**Comment by William96911** [comment]
部分失效，如
https://rsshub.app/wechat/wasi/5b5ada9e58e5c4583338e9fe

**Comment by xyqfer** [comment]
![image](https://user-images.githubusercontent.com/5186792/58868424-ec852d00-86ee-11e9-9fe0-209de9315991.png)
