### ISSUE TITLE
电商在线、westore 两个路由报错 

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2315]
### 路由地址
https://rsshub.app/imaijia/category/xls
https://rsshub.app/westore/new
### 预期是什么？
正常抓取
### 实际发生了什么？
报错
### 部署相关信息
官方 Demo
（未更新的）heroku 自建没有问题，可正常抓取。
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/58865440-22271780-86e9-11e9-83b8-e87181ca872a.png)

**Comment by xyqfer** [comment]
神奇了。。。post body 居然是空的。。= =

**Comment by xyqfer** [comment]
![image](https://user-images.githubusercontent.com/5186792/58869207-5fdb6e80-86f0-11e9-8b52-02847482bbc8.png)

@DIYgod post json 要这样写配置项才行。。。= =（中间件又要改了

**Comment by DIYgod** [comment]
Fixed. ea508b8bc2b9866a289f2ccec367a486b325fa76
