### ISSUE TITLE
Bing - 每日壁纸路由报错

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2322]
### 路由地址
https://rsshub.app/bing
### 预期是什么？
正常抓取
### 实际发生了什么？
报错
### 部署相关信息
官方 demo 报错，
未更新的 heroku 正常
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/58923886-3106dc00-8774-11e9-8434-72dee4804a3e.png)

**Comment by DIYgod** [comment]
Fixed. a47f2bd329444717ece5d6ec812932ddc3466104
