### ISSUE TITLE
针对 路由空内容 增加提示功能

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub#2326]
### 这是一个什么样的功能？
提示用户该路由故障，无法获取更新内容。以便用户前往源站阅览信息，同时提出issue。

### 这个功能可以解决什么问题？
路由获取信息为空，可能的原因有网站改版，页面布局改动等。这些问题导致路由内容为空，tiny tiny rss并不会将其归纳为错误(其他阅读器不了解)。
更新内容频繁的路由，用户可能会察觉到。
更新内容缓慢的路由，用户可能无法察觉。
例如[#2320](https://github.com/DIYgod/RSSHub/issues/2320)

### 额外描述
1. config.js 内增加功能选项，默认关闭该功能。有需要可自行开启。
2. 当路由内容为空时，中间件进行处理，增加一条item
    - guid: 当日0时 时间戳
    - title: 路由内容为空
    - description: 该路由目前获取内容为空，请检查源站情况。或前往https://github.com/DIYgod/RSSHub/issues ，反馈该问题。

这只是我的一个想法，如有更好地办法，欢迎各位大佬来指点。

**Comment by DIYgod** [comment]
路由报错也不容易察觉，也可以使用同样方式提示

开启关闭应该由订阅者决定，所以使用通用参数而不是 config 会更好
