### ISSUE TITLE
路由健康状况统计

### ISSUE THREAD

**Issue by josherich** [DIYgod/RSSHub#2332]
### 这是一个什么样的功能？

路由健康状况统计
1. 在 middleware/onerror.js 中记录每个路由最近的请求错误
2. 在路由目录中显示当前路由状况

### 这个功能可以解决什么问题？

目前有不少报错路由，缺少统计和实时的状态显示

**Comment by DIYgod** [comment]
Done. f7e8682ba8f434fb79e00e85dd1be80a5c3a9e3a
