### ISSUE TITLE
Heroku部署后如何修改RSS配置信息？（i.e., 各类平台key值）

### ISSUE THREAD

**Issue by cqcn1991** [DIYgod/RSSHub#2333]
### 这是一个什么样的功能？
如果一键部署到heroku的话，初始化时，是可以填RSS各模块的key值的. 

比如DISQUS_API_KEY, TWITTER_CONSUMER_KEY

后续如何修改呢？我查了下文档，好像没看到相关的内容
需要修改手动配置文件, git push后重新部署吗？

**Comment by yefoenix** [comment]
@cqcn1991 settings/Config Vars

**Comment by cqcn1991** [comment]
@yefoenix 所以是没办法通过在线地址去编辑的，得改代码是吧？

**Comment by yefoenix** [comment]
@cqcn1991 不是。

**Comment by cqcn1991** [comment]
@yefoenix 那请问是怎么在线编辑? 我部署后也就是一个这样的页面, https://rsshub.app

**Comment by yefoenix** [comment]
@cqcn1991 ……heroku 后台 settings/Config Vars

**Comment by cqcn1991** [comment]
@yefoenix 卧槽原来是这样... 感谢！
