### ISSUE TITLE
PROXY_AUTH设置格式

### ISSUE THREAD

**Issue by sqliuchang** [DIYgod/RSSHub#2346]
docker 部署设置环境变量PROXY_AUTH，总是407验证失败。
文档中说
> PROXY_AUTH: 给代理服务器的身份验证凭证，Proxy-Authorization: Basic ${process.env.PROXY_AUTH}

这里需要自己BASE64编码吗？
但是我实际测试下来，http和socks5无论是明文user:password还是经过BASE64编码，都返回407错误。

> RSSHub 发生了一些意外:
> RequestError: tunneling socket could not be established, statusCode=407
>     at ClientRequest.request.once.error (/app/node_modules/got/source/request-as-event-emitter.js:178:14)
>     at Object.onceWrapper (events.js:277:13)
>     at ClientRequest.emit (events.js:194:15)
>     at ClientRequest.origin.emit.args (/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
>     at ClientRequest.onConnect (/app/node_modules/tunnel/lib/tunnel.js:157:23)
>     at Object.onceWrapper (events.js:277:13)
>     at ClientRequest.emit (events.js:189:13)
>     at Socket.socketOnData (_http_client.js:475:11)
>     at Socket.emit (events.js:189:13)
>     at addChunk (_stream_readable.js:284:12)

不设置验证的http和socks5工作正常。
我是用frp内网穿透搭建的http和socks5代理，经过电脑IDM和手机adguard测试，均可正常工作，如有需要可以提供代理测试。

**Comment by DIYgod** [comment]
RSSHub 只是加一个 Proxy-Authorization header，最后验证是否成功取决于 frp 的验证方式，建议向 ftp 方面寻求帮助

**Comment by sqliuchang** [comment]
> RSSHub 只是加一个 Proxy-Authorization header，最后验证是否成功取决于 frp 的验证方式，建议向 ftp 方面寻求帮助

emmm，主要是因为其他软件使用frp搭建的代理没问题，所以在这里发issue。还有就是没回答我最主要的问题啊，需要自己BASE64编码吗？
