### ISSUE TITLE
建议提供一个为小白制作路由的方式

### ISSUE THREAD

**Issue by Mabbs** [DIYgod/RSSHub#2349]
### 这是一个什么样的功能？
用类似于配置文件的方式生成路由

### 这个功能可以解决什么问题？
让小白也能轻易添加路由（毕竟不是所有人都会NodeJS）

### 额外描述
预期格式如下（yaml）
```
title: #写一个正则
link: #还是一个正则
pubDate: #除了正则还可以是一个常量
……
```

**Comment by HenryQW** [comment]
我觉得相比这个需求被满足的速度，可能还是小白们学会 node 比较快 XD

**Comment by Mabbs** [comment]
> 我觉得相比这个需求被满足的速度，可能还是小白们学会 node 比较快 XD

不过那只是一个小白的速度，想想未来还会出现更多的小白～(￣▽￣～)~

**Comment by HenryQW** [comment]
> > 我觉得相比这个需求被满足的速度，可能还是小白们学会 node 比较快 XD
> 
> 不过那只是一个小白的速度，想想未来还会出现更多的小白～(￣▽￣～)~

想太多了。。。看 issue 数量 😂

**Comment by yefoenix** [comment]
https://docs.rsshub.app/joinus/#步骤-1-编写脚本 
4.使用通用配置型路由

**Comment by DIYgod** [comment]
简单逻辑的路由可以用楼上的方法，逻辑稍微复杂点就很难弄了，做起来性价比很低
