### ISSUE TITLE
twitter 部分用户RSS订阅失败

### ISSUE THREAD

**Issue by weidongzhou1994** [DIYgod/RSSHub#2350]
订阅部分用户，如MaxCRoser的RSS，会出现下述错误信息，是反爬策略导致的失败吗?
![image](https://user-images.githubusercontent.com/40510496/59154449-fdde8880-8aa4-11e9-818e-3dfe51a7c545.png)

**Comment by DIYgod** [comment]
demo 申请到的 Twitter token 有限额，再次申请一直不给通过

谁有多余的 token 可以联系我

**Comment by weidongzhou1994** [comment]
用heroku部署的rsshub需要什么样的操作才能制作rss呢？也是需要申请这个token吗？

**Comment by DIYgod** [comment]
> 用heroku部署的rsshub需要什么样的操作才能制作rss呢？也是需要申请这个token吗？

https://docs.rsshub.app/install/#%E9%85%8D%E7%BD%AE
