### ISSUE TITLE
瓦斯微信公众号抓取错误

### ISSUE THREAD

**Issue by SimFar** [DIYgod/RSSHub#2361]
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by lumyuto** [comment]
我这里也有这个问题 从昨天晚上10点钟左右就有了

**Comment by saury** [comment]
@DIYgod 
本地跑一点问题也没，看来是hub主服务器的问题。

**Comment by DIYgod** [comment]
反爬过于严格，瓦斯阅读将被移除

**Comment by jiey2016** [comment]
> @DIYgod
> 本地跑一点问题也没，看来是hub主服务器的问题。

我自己在heroku搭建，也同样出了问题，估计访问频率过高导致。还是瓦斯反爬的原因。
