### ISSUE TITLE
bilibili的“用户关注视频动态”路由失效，可能是cookie过期。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2365]
### 路由地址
https://rsshub.app/bilibili/followings/video/2267573
### 预期是什么？
出现项目
### 实际发生了什么？
报错，如下图。
![image](https://user-images.githubusercontent.com/3047708/59203333-f1574e80-8bd0-11e9-999b-5a78bf94ad7b.png)

### 部署相关信息
demo和自建都是最新commit

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
我自建的重新获取一次cookie，设置好就又能工作了。

感觉这个路由倒是亟需失效报错的那种提示。。

**Comment by LogicJake** [comment]
@ruleroller 奇怪，官方demo怎么会有这个人的cookie

**Comment by ruleroller** [comment]
@LogicJake 这个人是 @DIYgod 啊。。

**Comment by LogicJake** [comment]
@ruleroller 😂😂😂原来如此

**Comment by ruleroller** [comment]
@LogicJake 😄，这个issue，diy大佬能很快解决。

大佬您有空能帮忙pr这个么， #2359 ，希望得到您的帮助。😭

**Comment by LogicJake** [comment]
@ruleroller 有空康康

**Comment by ruleroller** [comment]
@LogicJake “康康”是看看的意思吗？那先行叩谢了！静候佳音~~~~~~👍👍👍

**Comment by yefoenix** [comment]
> @LogicJake 😄，这个 issue，diy 大佬能很快解决。
> 
> 大佬您有空能帮忙 pr 这个么， #2359 ，希望得到您的帮助。😭

哈哈为啥说着 diy 大佬能解决，同时圈了 LogicJake

**Comment by ruleroller** [comment]
@yefoenix 我是说 @DIYgod 能处理当前这个bilibili的问题，圈 logic 大佬是想请他有空帮忙pr直播吧论坛。

**Comment by DIYgod** [comment]
Fixed
