### ISSUE TITLE
【汇通网7x24小时快讯】RSS WANTED——希望生成源站更新的快讯

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2375]
### 源站地址
[https://kx.fx678.com/](https://kx.fx678.com/)
### 需要生成什么内容？

- [ ] 希望生成源站更新的快讯

### 额外描述

无

**Comment by occupy5** [comment]
#2069

**Comment by KwToPA** [comment]
@occupy5  您好， [https://docs.rsshub.app/](https://docs.rsshub.app/) 上面搜不到汇通

**Comment by KwToPA** [comment]
搜到  [https://docs.rsshub.app/other.html#_7x24-%E5%B0%8F%E6%97%B6%E5%BF%AB%E8%AE%AF-2](7x24 小时快讯) 建议补充关键字

**Comment by KwToPA** [comment]
自建ip:port/fx678/kx 可以看到推送内容，但是添加到mac reeder3中就推送失败。 有没有用reeder3 的，能帮忙测试下吗？ 谢谢

**Comment by occupy5** [comment]
我使用的是官方的[演示地址](https://rsshub.app/fx678/kx)，mac上reeder3推送失败，android上inoreader推送正常。

![image](https://user-images.githubusercontent.com/16299493/59320822-4777df00-8d02-11e9-9d17-05f6a94f49d7.png)

**Comment by DIYgod** [comment]
> 我使用的是官方的[演示地址](https://rsshub.app/fx678/kx)，mac上reeder3推送失败，android上inoreader推送正常。
> 
> ![image](https://user-images.githubusercontent.com/16299493/59320822-4777df00-8d02-11e9-9d17-05f6a94f49d7.png)

缺少 link 字段，是 bug

**Comment by KwToPA** [comment]
reeder 3的bug?

**Comment by occupy5** [comment]
@KwToPA 是我之前路由写的有问题，已经修复了。文档也补充了『汇通网』关键字。

**Comment by KwToPA** [comment]
@occupy5  感谢🙏

不过我这边还是不行。我按照[https://docs.rsshub.app/other.html#_7x24-%E5%B0%8F%E6%97%B6%E5%BF%AB%E8%AE%AF](这个)
