### ISSUE TITLE
中国银行外汇牌价 希望添加英文简称

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2396]
英文版直接用货币简称比较方便XD

PS: 如果有人做一下银联的最新汇率就好了……一个数据源: https://www.kuaiyilicai.com/huilv

### 源站地址

http://www.boc.cn/sourcedb/whpj/enindex.html

### 需要生成什么内容？

类似 https://rsshub.app/boc/whpj/

### 额外描述

`Ctrl+D`

**Comment by aka-rin** [comment]
看了一下英文版已经一个星期没更新了
改成添加英文简称好了 下面是对应表：

```json
{
    "阿联酋迪拉姆": "AED",
    "澳大利亚元": "AUD",
    "巴西里亚尔": "BRL",
    "加拿大元": "CAD",
    "瑞士法郎": "CHF",
    "丹麦克朗": "DKK",
    "欧元": "EUR",
    "英镑": "GBP",
    "港币": "HKD",
    "印尼卢比": "IDR",
    "印度卢比": "INR",
    "日元": "JPY",
    "韩国元": "KRW",
    "澳门元": "MOP",
    "林吉特": "MYR",
    "挪威克朗": "NOK",
    "新西兰元": "NZD",
    "菲律宾比索": "PHP",
    "卢布": "RUB",
    "沙特里亚尔": "SAR",
    "瑞典克朗": "SEK",
    "新加坡元": "SGD",
    "泰国铢": "THB",
    "土耳其里拉": "TRY",
    "新台币": "TWD",
    "美元": "USD",
    "南非兰特": "ZAR"
}
```

**Comment by sukiko789** [comment]
#2847 Sorry to step in, if you need English Version for Exchange Rate, I hope you can open an issue to request add a new RSS Route, rather than rude to let developers simply add words to the title so that RSS feeds can't display long titles that cause incomplete reading, thanks.
