### ISSUE TITLE
请教一个问题，RSS源的内容解析是放在docker容器内的么？

### ISSUE THREAD

**Issue by SuperNG6** [DIYgod/RSSHub#2402]
自己部署的rsshub会自动更新路由表么？（docker容器下的/app/lib/routes/ 目录?）
我自己部署的rsshub不能够显示nga论坛图片，而官方的rsshub站点可以正常显示nga论坛图片，如果GitHub上更新了路由表是否需要删除容器后重新部署？

**Comment by kt286** [comment]
需要

**Comment by SuperNG6** [comment]
我写了一个脚本，来定时更新routes，写的比较粗糙
希望可以更新支持自动检查并更新routes
````
mkdir -p ~/rsshub cd ~/rsshub && vi new_routes.sh
# 添加如下内容，wq保存
````

````
#!/bin/sh

if [ -d "/tmp/RSSHub" ]; then
	echo '存在/tmp/RSSHub，删除/tmp/RSSHub'
	rm -rf /tmp/RSSHub
fi
cd /tmp
echo '开始下载DIYgod/RSSHub'
git clone https://github.com/DIYgod/RSSHub.git

echo '拷贝新路由表到/app/lib/routes'
docker cp /tmp/RSSHub/lib/routes rsshub_service.rsshub_1:/app/lib/
echo '清理下载文件'
rm -rf /tmp/RSSHub
````

````
chmod +x /root/rsshub/new_routes.sh
sh /root/rsshub/new_routes.sh
````

添加定时任务
````
crontab -e
# 每120分钟执行一次
*/120     *       *       *       *      ~/rsshub/new_routes.sh
````

**Comment by DIYgod** [comment]
可以使用 [watchtower](https://github.com/containrrr/watchtower) 之类的工具自动更新

issue 将被关闭

**Comment by SuperNG6** [comment]
> 可以使用 [watchtower](https://github.com/containrrr/watchtower) 之类的工具自动更新
> 
> issue 将被关闭

这么做VPS流量也吃不消，我用谷歌云，流量实在太贵了

**Comment by Qixingchen** [comment]
@SuperNG6 入站流量又不收费（

**Comment by SuperNG6** [comment]
感谢各位，已解决，问个问题tiny rss是不是不能一个订阅同时存在于两个文件夹

**Comment by SettingDust** [comment]
@SuperNG6 Let me 🔎 Google that for you:
🔎 how to search with google
