### ISSUE TITLE
成都信息工程大学路由报错，无法正常工作。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2408]
### 路由地址
https://rsshub.app/cuit/cxxww/1
https://rsshub.app/cuit/cxxww/2
等其它
### 预期是什么？
正确生成条目
### 实际发生了什么？
报错，如下截图：
![image](https://user-images.githubusercontent.com/3047708/59522648-ca1abd00-8f01-11e9-809f-dc359a884a99.png)

### 部署相关信息
demo和自建都是最新版，都报类似错误。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by kt286** [comment]
自建没有问题
![1](https://user-images.githubusercontent.com/10684972/59545654-e9dad100-8f53-11e9-9111-ed1179344660.png)
