### ISSUE TITLE
笔趣阁乱码啦

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2409]
### 路由地址

https://rsshub.app/novel/biquge/52_52542

### 预期是什么？

咕咕咕

### 实际发生了什么？

？？？

### 额外信息（日志、报错等）

555..不想吃豆腐..

**Comment by Maecenas** [comment]
不止是这一个路由的问题，所有 GBK 编码的路由都挂了。想手动看一下 commit history 的，结果 `feature/got` 在和 `master` 同步开发时没有用 `git rebase`，看不出实际引入了哪些提交……不行只能 `git bisect` 了。

**Comment by DIYgod** [comment]
Fixed 59bb15e76110345aa3e35c7106a99ae0a9336412
