### ISSUE TITLE
草榴部分分区内容乱码

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#2412]
### 路由地址
https://rsshub.app/t66y/7
https://rsshub.app/t66y/22
### 预期是什么？
正常显示文字
### 实际发生了什么？
所有文字乱码
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
Fixed 59bb15e76110345aa3e35c7106a99ae0a9336412
