### ISSUE TITLE
希望添加CHH论坛

### ISSUE THREAD

**Issue by SuperNG6** [DIYgod/RSSHub#2419]
如题，希望能够添加CHH论坛
https://www.chiphell.com/forum.php

**Comment by kt286** [comment]
https://www.chiphell.com/forum.php?mod=rss
官方就有啊

**Comment by SettingDust** [comment]
> 如题，希望能够添加CHH论坛
> https://www.chiphell.com/forum.php

请按照模板提交issue

**Comment by SuperNG6** [comment]
官方那个无法选择板块
在 2019年6月16日 +0800 PM9:11，Cloud <notifications@github.com>，写道：

**Comment by kt286** [comment]
https://www.chiphell.com/forum.php?mod=rss&fid=53&auth=0

fid就是板块id

**Comment by SettingDust** [comment]
@DIYgod Close 官方已有
