### ISSUE TITLE
飞客茶馆「优惠」频道

### ISSUE THREAD

**Issue by howel52** [DIYgod/RSSHub#2423]
### 源站地址
https://www.flyertea.com/forum.php?mod=forumdisplay&sum=all&fid=all&catid=322
### 需要生成什么内容？

- [ ] 内容一 活动名称与链接
- [ ] 内容二 活动剩余时间

**Comment by kt286** [comment]
找到个官方的  貌似所有参数都不管用 直接输出全站
https://www.flyertea.com/forum.php?mod=rss
