### ISSUE TITLE
天则经济研究所 新闻提醒

### ISSUE THREAD

**Issue by BenfenYU** [DIYgod/RSSHub#2424]
### 源站地址
> <http://unirule.cloud/index.php>
### 需要生成什么内容？

- [ ] 内容一：《中评周刊的更新通知》
- [ ] 内容二：《天则观点的文章通知》

### 额外描述
> RSS里如果能看全文当然是最好的~~~

**Comment by kt286** [comment]
@BenfenYU 链接打开报错，修改链接或者关闭 issue
