### ISSUE TITLE
希望提供金色财经这类7X24小时滚动新闻的rss功能

### ISSUE THREAD

**Issue by gyppk** [DIYgod/RSSHub#243]
https://www.jinse.com/lives
希望可以有类似这种及时新闻滚动rss
自己搞了半天没搞定

**Comment by yangkghjh** [comment]
调用

https://api.jinse.com/v4/live/list?limit=20&reading=false&flag=up

就可以获取最新的20条，limit 就是条数限制

**Comment by gyppk** [comment]
一堆参数啊 我小白 大神能帮忙做个·rss出来吗

**Comment by DIYgod** [comment]
长时间无 pr，issue 暂时关闭
