### ISSUE TITLE
提议增加【乐赏】论坛

### ISSUE THREAD

**Issue by SuperNG6** [DIYgod/RSSHub#2434]
### 源站地址
http://www.gscq.me
### 需要生成什么内容？

- [ ] 内容一
希望增加乐赏论坛支持
- [ ] 内容二
希望增加论坛板块分类选择，和关键词支持
### 额外描述
我觉得乐赏论坛是国内最好的国产剧集压制、分享论坛，压制的视频没有广告没有水印，质量很高，希望能够增加支持

**Comment by TonyRL** [comment]
Target site seems unrelated
