### ISSUE TITLE
earthquake 地震路由 失效。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2436]
### 路由地址

https://rsshub.app/earthquake
### 预期是什么？
正常显示条目
### 实际发生了什么？
报403错，如下截图：
![image](https://user-images.githubusercontent.com/3047708/59704181-1a5d8c00-922e-11e9-8897-f45c1437954a.png)
### 部署相关信息
demo和最新自建，都报错。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by kt286** [comment]
自建没问题  服务器被反爬限制了吧

**Comment by ruleroller** [comment]
@kt286 我可能自建技术没你精湛。

我的自建是有403报错的：
![image](https://user-images.githubusercontent.com/3047708/59728840-531d5580-926e-11e9-8632-ac2d5c8a489d.png)

**Comment by SettingDust** [comment]
@ruleroller 403多半就是反爬

**Comment by ruleroller** [comment]
@kt286 @SettingDust 反爬一般是爬多了才403吧？我刚用另一台服务器的RSSHub新打开这个路由，同样是403唉。

**Comment by SettingDust** [comment]
@ruleroller 检查ua cookies等 尝试curl

**Comment by kt286** [comment]
@ruleroller 你的服务器访问原网站可以吗？

![image](https://user-images.githubusercontent.com/10684972/59729247-1e120280-9270-11e9-89bc-c41dc3ee73e9.png)

**Comment by ruleroller** [comment]
直接访问源站 cea.gov.cn，提示：
https://www.dropbox.com/s/qpi6c0isfvi4dsk/Screenshot%202019-06-19%2009.03.20.png?dl=0
![image](https://user-images.githubusercontent.com/3047708/59729444-2fa7da00-9271-11e9-9f4a-e01fdb85962c.png)

IP被这网站屏蔽了，两个都试过，都如此提示。

@kt286 你是不是用的国内vps？我怀疑国外的IP都被它屏蔽了。

**Comment by kt286** [comment]
@ruleroller 我用的是普通pc  本地搭建的😂
