### ISSUE TITLE
希望能增加个泛科学的简体中文rss

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#2440]
### 源站地址
网站：https://pansci.asia/
官方rss：https://pansci.asia/feed

### 需要生成什么内容？
将官方rss中的繁体中文转换成简体中文，方便阅读。

**Comment by DIYgod** [comment]
@EsuRt https://ttrss.henry.wang/zh/#opencc-%E7%B9%81%E7%AE%80%E8%BD%AC%E6%8D%A2

**Comment by EsuRt** [comment]
> @EsuRt https://ttrss.henry.wang/zh/#opencc-%E7%B9%81%E7%AE%80%E8%BD%AC%E6%8D%A2

这个是要用Tiny Tiny RSS吗？我用的是inoreader。

**Comment by DIYgod** [comment]
不应该由 RSSHub 来做，issue 将被关闭
