### ISSUE TITLE
topys

### ISSUE THREAD

**Issue by msongz** [DIYgod/RSSHub#2441]
### 源站地址
https://www.topys.cn
### 需要生成什么内容？

category 下的分支

**Comment by kt286** [comment]
官方有个全部的   https://www.topys.cn/rss

你要的分开的找到个接口
https://www.topys.cn/ajax/article/get_article_list

needloginpage: 2
islogin: 0
module: article
column: 7
timestape: 1561164851
token: d68a59efb59ee3198addc5f1efaafb7ffdf09571
offset: 0
size: 12
page: 0
type: column
need_count: true

**Comment by msongz** [comment]
@kt286 谢谢，那用官方的就可以咯！
