### ISSUE TITLE
自建Pixiv路由时常报错HTTP 400

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub#2446]
### 路由地址
/pixiv/ranking/day_male
/pixiv/ranking/week

### 预期是什么？
正常输出

### 实际发生了什么？
自建经常报错
```
HTTPError: Response code 400 (Bad Request)
    at EventEmitter.emitter.on (/root/RSSHub/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
重启RSSHub服务后又正常，不久之后又变成 400错误

### 部署相关信息
git hash:  1b632a3

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   CentOS Linux release 7.6.1810 (Core)   |
| Node version       |     v10.15.3          |
| Yarn version  |      1.16.0    |

**Comment by junfengP** [comment]
最近把这个路由切换到了demo，然后发现demo也有这问题
![image](https://user-images.githubusercontent.com/15406392/59958934-e9f14880-94e0-11e9-8d2a-80248f3d7d90.png)

**Comment by kidonng** [comment]
AFAIW, this problem has been existing for a month 😢 
Related #2341

**Comment by junfengP** [comment]
我觉得并不是网络问题。
1. 自建时，出现400错误后，就一直是400错误，直到重启后恢复正常。
2. demo合并pr后会自动重新构建，相当于重启。

**Comment by junfengP** [comment]
17:10分重启自建， 至17:15分之间不停刷新没有故障。
18:37再次访问，出现400错误，期间没有访问过该路由。

![image](https://user-images.githubusercontent.com/15406392/60091998-70738780-9778-11e9-9aa4-ce9e3727dcdd.png)

**Comment by junfengP** [comment]
> 17:10分重启自建， 至17:15分之间不停刷新没有故障。
> 18:37再次访问，出现400错误，期间没有访问过该路由。
> 
> ![image](https://user-images.githubusercontent.com/15406392/60091998-70738780-9778-11e9-9aa4-ce9e3727dcdd.png)

手动设置了缓存时间1s，因为不知道设置 export CACHE_TYPE='null' 有没有效果

**Comment by ciskonc** [comment]
我也有这个情况 自建服务器 时间一长 就会 400错误  只能被迫重启rsshub
RSSHub 发生了一些意外:
HTTPError: Response code 400 (Bad Request)
    at EventEmitter.emitter.on (/app/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by BrightSphere** [comment]
```
rsshub                 | (node:18) UnhandledPromiseRejectionWarning: TypeError: logger.err is not a function
rsshub                 |     at tokenLoop (/app/lib/routes/pixiv/token.js:87:24)
rsshub                 |     at process._tickCallback (internal/process/next_tick.js:68:7)
rsshub                 | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
rsshub                 | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

看了一下，似乎是pixiv的refresh token某次失败后（或者刷新方式变了？），然后log那句又有个typo，于是整个循环就崩了。

**Comment by kidonng** [comment]
> ```
> rsshub                 | (node:18) UnhandledPromiseRejectionWarning: TypeError: logger.err is not a function
> rsshub                 |     at tokenLoop (/app/lib/routes/pixiv/token.js:87:24)
> rsshub                 |     at process._tickCallback (internal/process/next_tick.js:68:7)
> rsshub                 | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> rsshub                 | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> 看了一下，似乎是pixiv的refresh token某次失败后（或者刷新方式变了？），然后log那句又有个typo，于是整个循环就崩了。

Yes, [it](https://github.com/DIYgod/RSSHub/blob/acb6682c5c5a97639778fff7c2f8139abe0e4aff/lib/routes/pixiv/token.js#L87) should use [`logger.error`](https://github.com/winstonjs/winston#using-logging-levels) instead.
