### ISSUE TITLE
请求熊猫直播、龙珠直播、中国体育直播的房间开播提醒

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#245]
https://www.panda.tv/
http://longzhu.com/
http://www.zhibo.tv/

**Comment by HenryQW** [comment]
rss 是被动获取信息，为啥需要时效性的开播提醒

**Comment by DIYgod** [comment]
开播提醒时效性要求不高，其实挺好用的，比如斗鱼 https://docs.rsshub.app/#%E6%96%97%E9%B1%BC

**Comment by ruleroller** [comment]
@HenryQW 请理解一下关注喜欢的主播的心情呀。目前斗鱼、熊猫的开播提醒就很好用，就差常用的longzhu和zhibo.tv平台了。

**Comment by DIYgod** [comment]
熊猫有了 https://docs.rsshub.app/#%E7%86%8A%E7%8C%AB%E7%9B%B4%E6%92%AD

超时，issue 暂时关闭
