### ISSUE TITLE
【证监会要闻】RSS wanted——希望支持推送证监会要闻

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2455]
### 源站地址

[http://www.csrc.gov.cn/pub/newsite/zjhxwfb/xwdd/](http://www.csrc.gov.cn/pub/newsite/zjhxwfb/xwdd/)

### 需要生成什么内容？

- [ ] 希望支持推送证监会要闻

### 额外描述

无

**Comment by KwToPA** [comment]
@chinobing  谢谢这位大哥

**Comment by kt286** [comment]
issue 可以关了

**Comment by KwToPA** [comment]
> issue 可以关了

您好，已经有大佬写完了吗？？？ https://docs.rsshub.app/ 上搜不到 证监会

**Comment by chinobing** [comment]
> > issue 可以关了
> 
> 您好，已经有大佬写完了吗？？？ https://docs.rsshub.app/ 上搜不到 证监会
https://rsshub.app/csrc/news 证监会要闻

https://rsshub.app/csrc/fashenwei 发审委公告

**Comment by KwToPA** [comment]
> csrc/news

谢谢 
![https://i.imgur.com/6npoc80.png](https://i.imgur.com/6npoc80.png)
