### ISSUE TITLE
YouTube Playlist 只有 5 个视频

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2460]
### 路由地址

https://rsshub.app/youtube/playlist/PL4fGSI1pDJn4-UIb6RKHdxam-oAUULIGB

### 预期是什么？

https://youtube.com/playlist?list=PL4fGSI1pDJn4-UIb6RKHdxam-oAUULIGB

### 实际发生了什么？

CloudFlare Error 502 Bad Gateway

### 额外信息（日志、报错等）

没有哦

**Comment by kt286** [comment]
你的网络问题吧

**Comment by aka-rin** [comment]
现在好了，但是只有5个视频……

**Comment by DIYgod** [comment]
RSS 只保证获取最新一条
