### ISSUE TITLE
[中国政府网站]【关键字搜索—搜索结果时间倒序更新等参数传递】RSS Wanted——希望支持中国政府网站关键字搜索，结果按时间倒序更新 谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2463]
### 源站地址
[http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=search_key_words&andpro=&notpro=&inpro=search_key_words&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1](http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=search_key_words&andpro=&notpro=&inpro=search_key_words&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1)

### 需要生成什么内容？

- [ ] 希望支持中国政府网站内搜索结果时间倒序更新
- [ ] 希望能支持[http://sousuo.gov.cn/a.htm?t=govall](http://sousuo.gov.cn/a.htm?t=govall) 高级搜索中的传递关键字参数
- [ ] 希望支持设置搜索的时间范围

### 额外描述

需要把 search_key_words按需改成搜索关键字

谢谢

**Comment by KwToPA** [comment]
和[https://docs.rsshub.app/government.html#%E6%9C%80%E6%96%B0%E6%96%87%E4%BB%B6](# 最新文件) 类似

**Comment by KwToPA** [comment]
@ciaranchen  望大佬有空看看

**Comment by KwToPA** [comment]
@EsuRt

**Comment by KwToPA** [comment]
群里Free Magico大佬说‘赞助可破’，
请问接受【Q币或者礼品卡（各种亚马逊，itunes，Google play）充值码】吗？

如果可以我直接发在这边。（因为经测试issue上的消息不到2秒就转到群里了）谢谢

**Comment by KwToPA** [comment]
DIY大哥，因为之前被大佬吐槽骚扰了。

**Comment by KwToPA** [comment]
我在群里，只不过不想暴露账号。

【 itunes 美国】
5美金：XFV25LTN2DT8K3RN
5美金：X7WQWPGR3YPW839T

**Comment by ciaranchen** [comment]
@KwToPA 

目前 `# 最新文件` 的 `http://sousuo.gov.cn/list.htm` 和你提出的 `http://sousuo.gov.cn/s.htm` 没有什么区别。以`555`代替你给的例子中的`search_key_words`：

- [http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=555&andpro=&notpro=&inpro=555&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1](http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=555&andpro=&notpro=&inpro=555&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1)
- [http://sousuo.gov.cn/list.htm?q=&n=10&t=govall&sort=pubtime&advance=true&orpro=555&andpro=&notpro=&inpro=555](http://sousuo.gov.cn/list.htm?q=&n=10&t=govall&sort=pubtime&advance=true&orpro=555&andpro=&notpro=&inpro=555)

且其中参数已经包含按时间倒序排列`sort=pubtime&sortType=1`。

你指的是

- 添加一个必选参数：类型分类，可以为`信息稿件govall` `国务院文件paper` `国务院公报bulletin` `图片搜索image` 和 `视频搜索video` ，以代替默认的 `t=paper`
- 通过高级搜索的选项`orpro` `andpro` `notpro` `inpro` 来传递关键字参数

吗？

**Comment by KwToPA** [comment]
> * 高级搜索

感谢大佬回复。 # 最新文件 s.htm 那个我也订阅了，但似乎有问题。 

希望能支持2，[http://sousuo.gov.cn/a.htm?t=govall](http://sousuo.gov.cn/a.htm?t=govall) 高级搜索中的传递关键字参数。其中govall 是信息稿件吗？ 我还以为是全部-栏目，advance=true 应该是高级搜索吧？

请问其他参数可以支持吗

pubmintimeMonth=1&pubmintimeDay=1 时间范围

searchfield=title 搜索范围 标题

timetype=timeqb 这个条件不清楚筛选的是什么，去掉不影响搜索结果

**Comment by KwToPA** [comment]
@ciaranchen  您好

目前我点击[#最新文件](https://docs.rsshub.app/government.html#%E6%9C%80%E6%96%B0%E6%96%87%E4%BB%B6)跳转到 http://new.sousuo.gov.cn/500.htm  

请问文档中的参数:
pcodeJiguan, 可选 - 文种分类。 国令; 国发; 国函; 国发明电; 国办发; 国办函; 国办发明电; 其他

应该怎么填？ 我直接填中文或者%开头的不灵啊 ，我按照 公文种类分类[http://www.gov.cn/zhengce/content/node_330.htm](http://www.gov.cn/zhengce/content/node_330.htm)填的[https://rsshub.app/gov/zhengce/wenjian/%E5%9B%BD%E5%8F%91](https://rsshub.app/gov/zhengce/wenjian/%E5%9B%BD%E5%8F%91)  国发

**Comment by xtaodada** [comment]
@KwToPA 测试没有问题的说 
参数直接中文就行的说 
可能是亲的网络或者浏览器问题的说
https://tlgur.com/d/gje2EE3G

**Comment by KwToPA** [comment]
@xtaodada  谢谢，可能刚才网络出现了问题。

@ciaranchen 
我刚刚想用[https://docs.rsshub.app/parameter.html#%E5%86%85%E5%AE%B9%E8%BF%87%E6%BB%A4](# 内容过滤)中的```filter_title```来实现 orpro /andpro/ notpro/ inpro  的功能，

经测试rsshub.app 无效，返回
```
没有访问权限. Access denied. 
```
估计ip被封。 

自建的rsshub，对于某些关键字有效
```
自建ip:port/gov/zhengce/wenjian?filter_title=关于
```
等同于高级搜索中对标题的搜索。但别的关键字就不行，例如

```
自建ip:port/gov/zhengce/wenjian?filter_title=习近平
```
返回
```
<![CDATA[
最新文件 - 中国政府网 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)
]]>
```
无法实现高级搜索的效果[http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&andpro=&notpro=&inpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1
](http://sousuo.gov.cn/s.htm?q=&n=10&p=0&t=govall&advance=true&orpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&andpro=&notpro=&inpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&pubmintimeMonth=1&pubmintimeDay=1&searchfield=title&colid=&timetype=timeqb&sort=pubtime&sortType=1)

高级搜索得到的结果最近的一条是，发布时间：2019.07.09

**Comment by xtaodada** [comment]
@KwToPA gov.cn 的搜索是全局搜索而您
'/gov/zhengce/wenjian'的路由是 http://www.gov.cn/zhengce/ 搜索不到任何习近平标题自然返回
'<![CDATA[ 
最新文件 - 中国政府网 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub) 
]]> '
[只显示标题有'关于'的中国政府网文件](https://rsshub.app/gov/zhengce/wenjian?filter_title=关于)

**Comment by KwToPA** [comment]
> @KwToPA gov.cn 的搜索是全局搜索而您
> `/gov/zhengce/wenjian`的路由是 http://www.gov.cn/zhengce/ 搜索不到任何习近平标题自然返回
> 
> ```
> 最新文件 - 中国政府网 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub) 
> ]]> 
> ```
> 
> [只显示标题有_关于_的中国政府网文件](https://rsshub.app/gov/zhengce/wenjian?filter_title=%E5%85%B3%E4%BA%8E)

请问```最新文件``` 中有路由支持全局搜索吗？还是只能搜zhengce 下的内容？ 谢谢。

因为作者@ciaranchen 之前说
```
目前 # 最新文件 的 http://sousuo.gov.cn/list.htm 和你提出的 http://sousuo.gov.cn/s.htm 没有什么区别。
```
我以为 zhengce相当于高级搜索

**Comment by xtaodada** [comment]
@KwToPA 测试好像是只能zhengce下的内容
您可以再联系一下作者的说

**Comment by ciaranchen** [comment]
`最新文件` 中的就是全局搜索，但是搜索的类型只确定了是`t=paper`，也就是只搜索`国务院文件`。

`最新政策` 是只搜索 `zhengce` 分类下的内容。 

目前尚没有搜索 `govall` 的路由。

另外 高级搜索对于每种分类的选项是不一样的。参见：

- http://sousuo.gov.cn/a.htm?t=paper
- http://sousuo.gov.cn/a.htm?t=zhengce
- http://sousuo.gov.cn/a.htm?t=govall

所以我觉得如我之前所说的 在一个路由内添加每个分类的高级搜索，是很难做到的。

我可以先尝试添加一个 `govall` 的路由，并添加只针对`govall`这种分类的高级搜索选项…

**Comment by KwToPA** [comment]
@ciaranchen  了解。 感谢🙏

**Comment by KwToPA** [comment]
@ciaranchen  
vps上 刚刚更新了rsshub

因为[中国政府-信息稿件](https://docs.rsshub.app/government.html#%E4%B8%AD%E5%9B%BD%E6%94%BF%E5%BA%9C)的```举例```和```参数```里面，两个参数```search_field```和```searchfield```都有，所以全部测试，结果失败

自建ip:port/gov/zhengce/govall/orpro=习近平&allpro=习近平&search_field=title
和
自建ip:port/gov/zhengce/govall/orpro=习近平&allpro=习近平&searchfield=title

查看log

第一个反馈
```
RSSHub 发生了一些意外:
ReferenceError: URLSearchParams is not defined
    at module.exports (~/RSSHub/lib/routes/gov/zhengce/govall.js:7:20)
    at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
    at next (~/RSSHub/node_modules/koa-compose/index.js:45:18)
    at ~/RSSHub/node_modules/koa-router/lib/router.js:346:16
    at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
    at ~/RSSHub/node_modules/koa-compose/index.js:36:12
    at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at cache (~/RSSHub/lib/middleware/cache.js:260:15)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

第二个反馈
```
RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (~/RSSHub/lib/middleware/parameter.js:7:15)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

/gov/zhengce/govall 也无效
```
RSSHub 发生了一些意外:
ReferenceError: URLSearchParams is not defined
    at module.exports (~/RSSHub/lib/routes/gov/zhengce/govall.js:7:20)
    at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
    at next (~/RSSHub/node_modules/koa-compose/index.js:45:18)
    at ~/RSSHub/node_modules/koa-router/lib/router.js:346:16
    at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
    at ~/RSSHub/node_modules/koa-compose/index.js:36:12
    at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at cache (~/RSSHub/lib/middleware/cache.js:260:15)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

用Tor换IP测试，
```
https://rsshub.app/gov/zhengce/govall/orpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&allpro=%E4%B9%A0%E8%BF%91%E5%B9%B3&search_field=title
```
无效，反馈和上面一样

```
https://rsshub.app/gov/zhengce/govall/
```
部分IP有效，部分IP失效
