### ISSUE TITLE
中国地震台网速报

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2467]
最近地震有点多，默认的地震局反爬又严格……

### 源站地址

http://news.ceic.ac.cn/index.html

### 需要生成什么内容？

时间/震级/地点/经纬度/深度/新闻链接

### 额外描述

nil

**Comment by yefoenix** [comment]
http://www.ceic.ac.cn/speedsearch

源站地址应该用这个

**Comment by yefoenix** [comment]
@aka-rin 直接订阅他的官方微博 @中国地震台网速报 就好

**Comment by kt286** [comment]
http://www.ceic.ac.cn/ajax/speedsearch?num=1&&page=1&&callback=jQuery180011189479298784022_1561250872515&_=1561254792852
