### ISSUE TITLE
vue vlog 路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2468]
### 源站地址
https://m.vuevideo.net/share/user/:id
例：https://m.vuevideo.net/share/user/971924215514
### 需要生成什么内容？

博主的vlog列表

### 额外描述
最好能像抖音一样带着「应用内查看」的链接

**Comment by kt286** [comment]
啥叫应用内查看  意思是点一下跳转到APP？还是直接在阅读器里边播放

**Comment by yefoenix** [comment]
@kt286 跳转app
