### ISSUE TITLE
微信公众号-优读app渠道路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2478]
### 源站地址
https://uread.ai/ （APP内容）
### 需要生成什么内容？

- [ ] 公众号推送内容列表

### 额外描述
API：http://119.29.146.143:8080/reading/subscription/account/recent?uid={id}&
{id} 为公众号id，仅支持app预置的那些公众号
例：http://119.29.146.143:8080/reading/subscription/account/recent?uid=shensing&
（公众号行者慎思）

**Comment by GH74138** [comment]
握草，这个必须顶啊。把那个付费添加公众号rss破解一下就好了
