### ISSUE TITLE
建筑师必看的archdaily.cn

### ISSUE THREAD

**Issue by bsharkl** [DIYgod/RSSHub#2481]
### 项目完整文章，及文末的完整图库。

- [ ] 完整文章
- [ ] 文末的完整图库

**Comment by yefoenix** [comment]
提供官方feed的站点，抓取全文功能可以由RSS阅读器实现，不必通过rsshub

**Comment by bsharkl** [comment]
> 提供官方feed的站点，抓取全文功能可以由RSS阅读器实现，不必通过rsshub

您指的RSS阅读器是啥？官方RSS在freshrss阅读器里试过，没法看，然后还用feedex强制全文输出依然达不到效果。

**Comment by bsharkl** [comment]
> 提供官方feed的站点，抓取全文功能可以由RSS阅读器实现，不必通过rsshub

我用freshrss阅读器的CSS选择器进行筛选，也只能实现第一个功能全文，第二个工作完整相册无法实现，还有就是有时候文章内嵌视频，CSS选择器也无法实现。
