### ISSUE TITLE
豆瓣正在上映的高分电影，暂无评分的会被认为是10分

### ISSUE THREAD

**Issue by cky917** [DIYgod/RSSHub#2489]
### 路由地址
https://rsshub.app/douban/movie/playing/7.5
### 预期是什么？
暂无评分的不返回
### 实际发生了什么？
暂无评分的电影返回了而且评分是10分

**Comment by liufangpu** [comment]
看下源代码就知道了，读不到分数默认10

**Comment by cky917** [comment]
@liufangpu 所以需要改一下- - 只想要大于7.5分的电影 现在什么碟仙之类的都返回了 😂
