### ISSUE TITLE
建筑师必看的谷德设计网

### ISSUE THREAD

**Issue by bsharkl** [DIYgod/RSSHub#2492]
### 前MAD建筑事务所的某人建的网站，主要涉及项目专辑介绍，建筑师访谈，深度文章，建筑师招聘

- [ ] 专辑内容
- [ ] 专业分类
- [ ] 最新项目对接信息
- [ ] 部分文章内嵌视频

**Comment by yefoenix** [comment]
https://dashboard.gooood.cn/feed

**Comment by bsharkl** [comment]
> https://dashboard.gooood.cn/feed
> 
> https://dashboard.gooood.cn/category/type/landscape/feed

![image](https://user-images.githubusercontent.com/17378745/60105526-0a95f880-9796-11e9-9eb9-459b1a32a7be.png)
你觉得这个feed能阅读吗？

**Comment by bsharkl** [comment]
> https://dashboard.gooood.cn/feed
> 
> https://dashboard.gooood.cn/category/type/landscape/feed

如果用feedex全文转换输出，文章是可以全文了，但是图片全都是灰色的。
![image](https://user-images.githubusercontent.com/17378745/60106110-32399080-9797-11e9-8415-3f6d9ea99993.png)
