### ISSUE TITLE
貌似抓取的微博不能刷新

### ISSUE THREAD

**Issue by iTribal** [DIYgod/RSSHub#25]
就第一次可以抓取到最近的10条微博，然后以后不管如何刷新，都再也抓取不到了

**Comment by u3u** [comment]
缓存五分钟

**Comment by iTribal** [comment]
缓存5分钟的意思是只能抓取一次吗？那怕在RSS阅读器里设置成12小时刷新一次都没用了？

**Comment by u3u** [comment]
不是呀，就是五分钟内获取的是旧数据
你确定你订阅的博主微博有更新么？

**Comment by DIYgod** [comment]
请提供具体URL

**Comment by iTribal** [comment]
之前我是把rss URL放在gReader里作为本地源的，昨晚试了下将URL放feedly和inoreader里，今天发现这2个网页版有读取到昨天最新的3条微博了，晚上回家后我再看看放本地的能正常读取到不
