### ISSUE TITLE
bug on instagram user feed

### ISSUE THREAD

**Issue by bluecombats** [DIYgod/RSSHub#2500]
### Involved route
checked the instagram feed https://www.instagram.com/hrjoe_photography/?hl=en
and then copied in the user name to the rsshub feed https://rsshub.app/instagram/user/hrjoe_photography and got an error

### What is expected?
a page displaying a xml tree like https://rsshub.app/instagram/user/diygod

### What is actually happening?
RSSHub 发生了一些意外:
HTTPError: Response code 429 (-)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  chrome, windows 10             |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
「 Error 429 Too Many Requests」means that the rsshub.app server is banned by instagram. You can run a private rsshub service instead.

**Comment by yefoenix** [comment]
@yefoenix which means 「反爬了，请自建」

**Comment by bluecombats** [comment]
so if it's banned why does it work on https://rsshub.app/instagram/user/diygod ?

**Comment by bluecombats** [comment]
I see from mozilla it means it hit the rate limit https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by DIYgod** [comment]
Source website limit
