### ISSUE TITLE
请求增加3dm游戏的最新资讯

### ISSUE THREAD

**Issue by AronLL** [DIYgod/RSSHub#251]
3dm原址：http://www.3dmgame.com/
如《底特津变人》的最新动态：http://www.3dmgame.com/games/detroitbecomehuman/

**Comment by yangkghjh** [comment]
每个专题会包含新闻、攻略、下载。最新动态整合这些消息。

**Comment by yangkghjh** [comment]
需要全文抓取吗

**Comment by AronLL** [comment]
我其实希望有新闻就够了，毕竟RSS作用本就如此，攻略、下载还是留在论坛自己去看吧~
不过作为伸手党，不好要求这么多，dalao看着办就行~.~
此外，看了一下各位的代码，感觉只有几行的样子，不知道我这种只学了C的普通大学生容不容易学习。

**Comment by yangkghjh** [comment]
已 pr 新闻和攻略，计划周日实现下载

**Comment by yangkghjh** [comment]
https://rsshub.app/3dm/dota2/news

doat2的新闻会直接报错，本地是没问题，@DIYgod 帮忙拿一下错误日志

**Comment by DIYgod** [comment]
@yangkghjh 的确是缓存的问题，对象需要 stringify 之后保存字符串

https://github.com/DIYgod/RSSHub/blob/master/routes/3dm/news.js#L104
https://github.com/DIYgod/RSSHub/blob/master/routes/3dm/news_center.js#L63

**Comment by zhboner** [comment]
news_center里的确用的是字符串作的key，测试也没问题

**Comment by DIYgod** [comment]
改了缓存也不行....暂时不知道什么原因

**Comment by yangkghjh** [comment]
https://rsshub.app/3dm/watchdogs2/news

这个地址有的undefined有的能抓到

**Comment by yangkghjh** [comment]
内存占用问题？对文章数量设限就好了？

**Comment by zhboner** [comment]
https://github.com/DIYgod/RSSHub/blob/c9f8d37bdf975995d15f92a570b6829bc14f4df9/routes/3dm/news_center.js#L26
假如没有缓存，JSON.parse()会不会报错

**Comment by yangkghjh** [comment]
应该不是缓存问题。本地运行都没问题的。最有可能的是性能限制。代码需要优化内存占用。

**Comment by DIYgod** [comment]
@yangkghjh 可能是 Redis 的性能问题，减到 5 条现在好了
