### ISSUE TITLE
请求填加酷狗音乐人最新音乐发布信息RSS

### ISSUE THREAD

**Issue by linewoo** [DIYgod/RSSHub#2510]
### 源站地址
http://m.kugou.com/singer/info/554471
### 需要生成什么内容？
最新歌曲发布清单
- [ ] 内容一：歌曲名称
- [ ] 内容二：试听地址或下载地址

### 额外描述
歌曲清单默认为最热歌曲再上面，理论上最新发布的都在最下面
如果能支持任意歌手订阅就更好了

**Comment by kt286** [comment]
https://wwwapi.kugou.com/yy/index.php?r=play/getdata&callback=jQuery19109953539336776482_1565704078456&hash=58870C9501FA51B98EF66AA980283710&album_id=22930720&dfid=4VuHuc1dYUXH0LhRVY3h9c51&mid=ae23152b76b29c125793003c50dddd70&platid=4&_=1565704078471
dfid 和 mid在cookie里边

mp3地址是变化的，建议关闭 issue
