### ISSUE TITLE
Pixiv RSS出错

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#2537]
路由地址
https://rsshub.bgme.me/pixiv/8654380
预期是什么？
返回数据

实际发生了什么？
返回
![image](https://user-images.githubusercontent.com/33424662/60506148-ce174f00-9cf7-11e9-9728-de05f2b3ce3b.png)
![image](https://user-images.githubusercontent.com/33424662/60506180-e12a1f00-9cf7-11e9-8c06-9855d8fa0c7a.png)

**Comment by DIYgod** [comment]
路由错误
