### ISSUE TITLE
RSS from Chuansongmen is invalid

### ISSUE THREAD

**Issue by tsihyoung** [DIYgod/RSSHub#2541]
### 路由地址
wechat/csm/diqiuzhishiju
### 预期是什么？
通过Feed Validation Service检测。
### 实际发生了什么？
能抓取到传送门RSS，但不能通过Feed Validation检测。
[https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frsshub.app%2Fwechat%2Fcsm%2Fdiqiuzhishiju](url)

**Comment by DIYgod** [comment]
使用有什么问题么？

**Comment by tsihyoung** [comment]
> 使用有什么问题么？

使用IFTTT将RSS推送到Pocket时提示提示链接无效。

**Comment by yefoenix** [comment]
@DIYgod 可以关闭了
