### ISSUE TITLE
部分twitter路由Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by xfause** [DIYgod/RSSHub#2558]
### 路由地址
https://rsshub.app/twitter/user/xfause

### 预期是什么？
返回tweet信息

### 实际发生了什么？
TypeError: Cannot read property 'user' of undefined

### 额外信息（日志、报错等）
但是访问其他twitter id的时候就可以正常返回结果 
比如https://rsshub.app/twitter/user/846kizuQ

**Comment by DIYgod** [comment]
内容为空无法订阅
