### ISSUE TITLE
npm run format 报错

### ISSUE THREAD

**Issue by dodying** [DIYgod/RSSHub#2561]
安装依赖时，报错，原因是 没有安装 node-gyp

npm run format

log里的错误信息
```
```

然后，所有的js文件末尾不知道是少了还是多了空白字符

**Comment by kt286** [comment]
安装时候依赖报错是因为没安装VS编译工具、编译nodejieba的时候找不到报错了吧

format报错信息说了  你定义了变量 但是没用到  删了就行

`所有的js文件末尾不知道是少了还是多了空白字符` 
这个是因为Windows下的git pull代码的时候会把换行转成CRLF   但是源文件是LF  执行一下  ` git config --global core.autocrlf input `重新clone一份代码就好了

**Comment by dodying** [comment]
多谢，执行`git config --global core.autocrlf input`后就正常了
