### ISSUE TITLE
【上证债券信息网-可转换公司债券公告】Rss Wanted

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2562]
### [http://bond.sse.com.cn/disclosure/announ/convertible/#](http://bond.sse.com.cn/disclosure/announ/convertible/#)

上证债券信息网，可转换公司债券公告

### 需要生成什么内容？

- [ ] 希望支持可转换公司债券公告按照时间线生成
- [ ] 希望可以支持参数传递，

公告标题 | 证券代码： | 日期范围

### 额外描述

无

**Comment by kt286** [comment]
http://query.sse.com.cn/infodisplay/queryBulletinKzzTipsNew.do?&jsonCallBack=jsonpCallback53044&isPagination=true&pageHelp.pageSize=20&flag=0&beginDate=2018-08-18&endDate=2019-08-18&companyCode=603283&title=%E8%82%A1%E4%BB%BD&_=1566133476726

**Comment by KwToPA** [comment]
> http://query.sse.com.cn/infodisplay/queryBulletinKzzTipsNew.do?&jsonCallBack=jsonpCallback53044&isPagination=true&pageHelp.pageSize=20&flag=0&beginDate=2018-08-18&endDate=2019-08-18&companyCode=603283&title=%E8%82%A1%E4%BB%BD&_=1566133476726


>```jsonpCallback53044({"jsonCallBack":"jsonpCallback53044","success":"false","error":"系统繁忙...","errorType":"ExceptionInterceptor"})```

It can not be convert to rss right ?

**Comment by KwToPA** [comment]
@kt286 谢谢
