### ISSUE TITLE
传送门 路由中的图片缺失 referrerpolicy="no-referrer"

### ISSUE THREAD

**Issue by fbigun** [DIYgod/RSSHub#2563]
### 路由地址

wechat/csm/diqiuzhishiju

### 预期是什么？

阅读器及feedly网站上均无图片显示

### 实际发生了什么？

订阅 xml 文件关于 `img` 标签里面缺失属性  `referrerpolicy="no-referrer“`

**Comment by fbigun** [comment]
还是有部分的`img`标签没有这个属性
基于`https://github.com/kt286/RSSHub/tree/patch-1`构建的测试站`https://teset-rsshub.herokuapp.com/wechat/csm/huxiu_com` 有部分错误。 @kt286

**Comment by kt286** [comment]
1.没加上属性的截图
2.部分错误的截图
