### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by jacky2001114** [DIYgod/RSSHub#257]
我在制作uu看书的rss但遇到有部分的章节会出现错误
“Uncaught TypeError: Cannot read property 'addEventListener' of null”
内容也没有包在标签内
如图：https://i.imgur.com/tJogW5u.png

**Comment by DIYgod** [comment]
看起来像某个浏览器插件导致的，跟 RSSHub 无关
