### ISSUE TITLE
enhance: 希望微博的视频可以直接播放

### ISSUE THREAD

**Issue by iplusx** [DIYgod/RSSHub#2572]
### 这是一个什么样的功能？
微博的视频可以直接播放。

### 这个功能可以解决什么问题？
免去跳转原文才能观看微博视频的烦恼。可以像Twitter一样，将视频放在\<video\>里直接播放。

### 额外描述
可能需要其他微博解析工具的支持，会稍微影响性能，编码的时候需要注意下，起码不是视频微博就不解析。

**Comment by DIYgod** [comment]
视频地址会过期，无法使用直链

**Comment by zizhengwu** [comment]
请问自动播放有相应配置吗？例如自动播放但默认静音，或者不自动播放。因为现在打开，声音💥吓一跳。
