### ISSUE TITLE
Mp4Ba 获取出错

### ISSUE THREAD

**Issue by abc1763613206** [DIYgod/RSSHub#2574]
### 路由地址
https://rsshub.app/mp4ba/1
### 预期是什么？
正常获取
### 实际发生了什么？
```
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
```
### 部署相关信息
官方演示源
### 额外信息（日志、报错等）
似乎route所获取的[临时站点](http://ww.mp4ba.com)已经停用，可以考虑换到 www 主站。

**Comment by kt286** [comment]
已有相同问题 #2432   此isuse关闭
