### ISSUE TITLE
请求添加 "网易轻松一刻" "开眼视频",每天笑一笑,每天开眼界 万分感谢

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#2588]
### 需要生成什么内容？

- [x] 内容一  请求添加 网易轻松一刻  网址:https://3g.163.com/touch/exclusive/subchannel/qsyk/
- [x] 内容二 请求添加 开眼 (一个精品短视频网站) 网址举例:https://www.eyepetizer.net/detail.html?vid=155708

- [x] 内容三:请求添加 维基百科里的 历史上的今天

 万分感谢!!!!

**Comment by yefoenix** [comment]
1. https://baobab.kaiyanapp.com/api/v1/feed?udid=3e7ee30c6fc0004a773dc33b0597b5732b145c04 （需要看一下udid的生成和适用方式？）
2. https://3g.163.com/touch/reconstruct/article/list/BD21K0DLwangning/0-10.html
3. https://zh.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom （自带rss）

**Comment by kt286** [comment]
https://baobab.kaiyanapp.com/api/v4/video/related?id=155708&f=iphone&vc=4800&udid=

udid可以空

**Comment by yefoenix** [comment]
> https://baobab.kaiyanapp.com/api/v4/video/related?id=155708&f=iphone&vc=4800&udid=
> 
> udid 可以空

但是这个api不能用啊，是某个视频的相关视频

**Comment by currencyporter** [comment]
> 
> 
> > https://baobab.kaiyanapp.com/api/v4/video/related?id=155708&f=iphone&vc=4800&udid=
> > udid 可以空
> 
> 但是这个api不能用啊，是某个视频的相关视频

辛苦了谢谢!! 我也不知道怎么弄,我是小白,开眼官网是这个:https://www.kaiyanapp.com/

**Comment by currencyporter** [comment]
> 
> 
>     1. https://baobab.kaiyanapp.com/api/v1/feed?udid=3e7ee30c6fc0004a773dc33b0597b5732b145c04 （需要看一下udid的生成和适用方式？）
> 
>     2. https://3g.163.com/touch/reconstruct/article/list/BD21K0DLwangning/0-10.html
> 
>     3. https://zh.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom （自带rss）

谢谢你,这给的这个我不知道怎么弄到rss里面去

**Comment by yefoenix** [comment]
@currencyporter 维基百科历史今天的是自带rss

**Comment by sunshinenny** [comment]
开眼精选制作完毕，等审核通过ing [Feat:开眼首页](https://github.com/DIYgod/RSSHub/pull/2699)

**Comment by currencyporter** [comment]
谢谢各位!!!

**Comment by rsyqvthv** [comment]
请问 网易轻松一刻 有路由了吗?

https://3g.163.com/touch/reconstruct/article/list/BD21K0DLwangning/0-10.html

非常感谢.
