### ISSUE TITLE
npm部署报错

### ISSUE THREAD

**Issue by Porlockzzz** [DIYgod/RSSHub#2592]
root@localhost:/usr/soft/RSSHub# npm start

> rsshub@0.0.1 start /usr/soft/RSSHub
> node lib/index.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/soft/RSSHub/lib/index.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! rsshub@0.0.1 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsshub@0.0.1 start script 'node lib/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rsshub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rsshub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rsshub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/soft/RSSHub/npm-debug.log

部署在vps上

**Comment by tgly307** [comment]
依赖装过了吗

**Comment by nkinos** [comment]
```
$ npm install
$ npm start
```

**Comment by Porlockzzz** [comment]
> ```
> $ npm install
> $ npm start
> ```

感谢，应该是这个问题
