### ISSUE TITLE
订阅twitter返回wrong path

### ISSUE THREAD

**Issue by Porlockzzz** [DIYgod/RSSHub#2594]
在vps（美国）上部署好了docker版的rsshub
测试官方文档的bilibili订阅等都没问题，
然后尝试推特的时候，任意用户都无法成功，返回错误为：
RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (/app/lib/middleware/parameter.js:7:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Porlockzzz** [comment]
尝试的是用户时间线：https://rsshub.app/twitter/user/DIYgod

**Comment by Porlockzzz** [comment]
我尝试的地址是http://xx.xx.xx.xx:1200/twitter/user/DIYgod/
格式应该无误，
至于服务器部分，直接访问http://xx.xx.xx.xx:1200返回正常页面

**Comment by Azureki** [comment]
所以问题是什么，已经解决了吗？
为什么这就close了？

**Comment by DIYgod** [comment]
@Azureki https://docs.rsshub.app/install/#%E9%83%A8%E5%88%86-rss-%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE

**Comment by Azureki** [comment]
明白了。
之前只在`用户关注时间线`下看到了注意，`用户时间线`下没有，还以为后者不需要。

**Comment by Porlockzzz** [comment]
是的，

> 明白了。
> 之前只在`用户关注时间线`下看到了注意，`用户时间线`下没有，还以为后者不需要。

是的，现在加上key就可以了
