### ISSUE TITLE
求助:通用参数怎么过滤多个条件,请点进来

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#2596]
### 需要生成什么内容？

- [ ] 内容一
- [ ] 内容二

### 额外描述
例如:我订阅的是7x24小时快讯:https://rsshub.app/fx678/kx.
然后我想 不接收标题里含有关键字 :"刚刚触及","现报","夜盘","涨幅达到","跌幅达到","涨幅扩大","跌幅扩大"的标题.  该怎么用通用参数过滤掉?  只要标题包含以上任意一组关键字,就过滤掉不接收该消息. 万能的rsshub,请帮助我吧!!! 万分感谢

**Comment by xtaodada** [comment]
@currencyporter 请仔细阅读[文档](https://docs.rsshub.app/)查找帮助
下面是一个例子
[过滤后的网页地址](https://rsshub.app/fx678/kx?filterout_title=%E5%88%9A%E5%88%9A%E8%A7%A6%E5%8F%8A%7C%E7%8E%B0%E6%8A%A5%7C%E5%A4%9C%E7%9B%98%7C%E6%B6%A8%E5%B9%85%E8%BE%BE%E5%88%B0%7C%E8%B7%8C%E5%B9%85%E8%BE%BE%E5%88%B0%7C%E6%B6%A8%E5%B9%85%E6%89%A9%E5%A4%A7%7C%E8%B7%8C%E5%B9%85%E6%89%A9%E5%A4%A7)

**Comment by currencyporter** [comment]
> 
> 
> @currencyporter 请仔细阅读[文档](https://docs.rsshub.app/)查找帮助
> 下面是一个例子
> [过滤后的网页地址](https://rsshub.app/fx678/kx?filterout_title=%E5%88%9A%E5%88%9A%E8%A7%A6%E5%8F%8A%7C%E7%8E%B0%E6%8A%A5%7C%E5%A4%9C%E7%9B%98%7C%E6%B6%A8%E5%B9%85%E8%BE%BE%E5%88%B0%7C%E8%B7%8C%E5%B9%85%E8%BE%BE%E5%88%B0%7C%E6%B6%A8%E5%B9%85%E6%89%A9%E5%A4%A7%7C%E8%B7%8C%E5%B9%85%E6%89%A9%E5%A4%A7)

非常感谢!!! 我仔细阅读了文档,然后自己弄了这个
"https://rsshub.app/fx678/kx?filterout_title=刚刚触及|现报|夜盘|涨幅达到|跌幅达到|涨幅扩大|跌幅扩大|收盘上涨"
但是在ifttt里面不能订阅,请问你那个网址是怎么转化出来的,???

**Comment by xtaodada** [comment]
@currencyporter Url的编码格式采用的是ASCII码，而不是Unicode，这也就是说你不能在Url中包含任何非ASCII字符。所以|需要转义为%7C

**Comment by DIYgod** [comment]
node v12.2.0 修复了 `|` 转义的问题：https://github.com/nodejs/node/pull/27578

demo 已更新

**Comment by xtaodada** [comment]
@DIYgod 震惊 DIYgod 居然不坐等网友解决issue了
