### ISSUE TITLE
香水时代网站RSS需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#2597]
### 网站地址
https://www.nosetime.com

### 网站描述
香水时代是最重要的中文香水社区

### 需要生成什么内容？

- [ ] 新鲜事 https://www.nosetime.com/perfume.php
- [ ] 用户一句话香评，例： https://www.nosetime.com/member/member_comment.php?id=59247733&type=short&o=new
- [ ] 用户香评，例： https://www.nosetime.com/member/member_comment.php?id=59247733&type=discuss&o=new

### 额外描述

**Comment by yefoenix** [comment]
[1] https://www.nosetime.com/app/smart.php?page=1&type=discovery

**Comment by kt286** [comment]
[2] POST https://www.nosetime.com/app/user.php
{"method":"getwebshort","id":"59247733","orderby":"new","page":1}

[3] POST https://www.nosetime.com/app/user.php
{"method":"getwebdiscuss","id":"59247733","orderby":"new","page":1}
