### ISSUE TITLE
Instagram组图只显示第一张图片

### ISSUE THREAD

**Issue by august22** [DIYgod/RSSHub#260]
Instagram订阅的内容，一条信息中如果包含多张图片只显示第一张图片，不知道能否显示出所有图片

**Comment by sgrjyb** [comment]
@DIYgod  Instagram组图只获取第一张图片 , 强迫症受不了

**Comment by DIYgod** [comment]
Done. 9a730ccf0d4bc8065483b0349d7cd75fca60ffa9
