### ISSUE TITLE
【巨潮资讯网-个股公告】RSS Wanted谢谢——http://www.cninfo.com.cn

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2611]
### 网站地址

[http://www.cninfo.com.cn](http://www.cninfo.com.cn)

### 网站描述

看公告，快人一步

### 需要生成什么内容？

- [ ] 个股公告推送，以个股的代码作为keywords

### 额外描述

例如 个股000410

[http://www.cninfo.com.cn/new/disclosure/stock?plate=szse&stockCode=000410](http://www.cninfo.com.cn/new/disclosure/stock?plate=szse&stockCode=000410)

**Comment by KwToPA** [comment]
@LogicJake  大哥，最新的路由 [公司公告-A 股港股](https://docs.rsshub.app/other.html#%E5%85%AC%E5%8F%B8%E5%85%AC%E5%91%8A-a-%E8%82%A1%E6%B8%AF%E8%82%A1) 里面的category一共有哪些啊？ 

还有如果只填code是不是效果和这个路由一样？

谢谢

**Comment by hillerliao** [comment]
@KwToPA 没有列全，支持：

![图片](https://user-images.githubusercontent.com/5266745/64611139-5a827400-d403-11e9-8afd-d508faad2a9e.png)

具体映射关系，稍晚点我更新下文档。

**Comment by hillerliao** [comment]
![图片](https://user-images.githubusercontent.com/5266745/64612173-be0da100-d405-11e9-97ca-7545d7191728.png)

```
### 公司公告-A 股港股

<Route author="LogicJake hillerliao" example="/cninfo/announcement/002024/gqjl" path="/cninfo/announcement/:code/:category?" :paramsDesc="['股票代码, 若不指定公司则填 all', '公告分类，对A股有效如 gqjl 表示 股权激励 分类']"/>
```

我的说明在文档里没体现出来  / @DIYgod

**Comment by KwToPA** [comment]
> ![图片](https://user-images.githubusercontent.com/5266745/64612173-be0da100-d405-11e9-97ca-7545d7191728.png)
> 
> ```
> ### 公司公告-A 股港股
> 
> <Route author="LogicJake hillerliao" example="/cninfo/announcement/002024/gqjl" path="/cninfo/announcement/:code/:category?" :paramsDesc="['股票代码, 若不指定公司则填 all', '公告分类，对A股有效如 gqjl 表示 股权激励 分类']"/>
> ```
> 
> 我的说明在文档里没体现出来 / @DIYgod

你这个路由的链接没了，昨天刚更新的时候还有 
https://docs.rsshub.app/other.html#%E5%85%AC%E5%8F%B8%E5%85%AC%E5%91%8A-a-%E8%82%A1%E6%B8%AF%E8%82%A1

**Comment by KwToPA** [comment]
股票代码, 若不指定公司则填 all', '公告分类，对A股有效如 gqjl 表示 股权激励 分类  

这段昨天能看到

**Comment by KwToPA** [comment]
> @KwToPA 没有列全，支持：
> 
> ![图片](https://user-images.githubusercontent.com/5266745/64611139-5a827400-d403-11e9-8afd-d508faad2a9e.png)
> 
> 具体映射关系，稍晚点我更新下文档。

能否提供这个界面的链接？ 谢谢

**Comment by hillerliao** [comment]
巨潮的公告搜索界面，`http://www.cninfo.com.cn/new/commonUrl?url=disclosure/list/notice`  右上角「公告搜索」
