### ISSUE TITLE
中央纪委国家监委网站----审查调查 RSS输出

### ISSUE THREAD

**Issue by dai640** [DIYgod/RSSHub#2613]
### 网站地址
 http://www.ccdi.gov.cn/scdc/

### 网站描述
中央纪委国家监委网站----审查调查

### 需要生成什么内容？
 在审查调查栏目下面有3个分类，分别是中管干部，中央一级党和国家机关、国企和金融单位干部，省管干部，这3个分类并且都包含相同的2个下一级分类，叫做：执纪审查，党纪政务处分。需要把这个审查调查下的3个栏目下的2个小分类，制作成全文输出RSS服务。
- [ ] 中管干部
 1.执纪审查
 2.党纪政务处分

- [ ] 中央一级党和国家机关、国企和金融单位干部
1.执纪审查
2.党纪政务处分

- [ ] 省管干部
 1.执纪审查
 2.党纪政务处分

### 额外描述
第一次发布需求，希望能成功满足。谢谢各位

**Comment by dai640** [comment]
太感谢各位朋友了，已经完美达到要求。

**Comment by KwToPA** [comment]
自建报错
```
RSSHub 发生了一些意外:
HTTPError: Response code 403 (Forbidden)
    at EventEmitter.emitter.on (~/RSSHub/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by LogicJake** [comment]
@KwToPA 反爬，等一会
