### ISSUE TITLE
LISTEN_INADDR_ANY 设置为0 不起作用

### ISSUE THREAD

**Issue by PyGroot** [DIYgod/RSSHub#2621]
LISTEN_INADDR_ANY 设置为0 仍然可以通过”IP+端口号“的方式访问，请问怎么样可以禁止”IP+端口号“的访问方式？

**Comment by DIYgod** [comment]
这个参数是是否允许公网连接，不是是否允许 IP 连接

什么场景需要禁止 IP 访问

**Comment by PyGroot** [comment]
尴尬，我以为这个参数是关闭 ip+端口 的方式访问。原本打算用nginx反向代理，通过域名访问，然后关掉 ip+端口号的访问方式
