### ISSUE TITLE
B站up更新和投硬币RSS失效了吗，我使用inoreader不显示最新内容，IFTTT则是创建成功但是触发失败（我设置的是给自己发邮件

### ISSUE THREAD

**Issue by Sherry720** [DIYgod/RSSHub#2626]
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
请提供详细信息，此 issue 将被关闭

**Comment by xtaodada** [comment]
@Sherry720 没有问题的说 自建和demo都正常

**Comment by Sherry720** [comment]
j好的，那应该是我的问题，我再试试，谢谢

**Comment by xtaodada** [comment]
@Sherry720 No thanks=-=
