### ISSUE TITLE
【天涯论坛tianya.cn】Rss Wanted——望支持推送用户的回帖，谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2629]
### 网站地址

[tianya.cn](tianya.cn)

### 网站描述

网络论坛

### 需要生成什么内容？

- [ ] 内容一

望支持推送用户的回帖，谢谢

### 额外描述

例如天涯用户[苕木匠](http://www.tianya.cn/11488997/bbs)的主页```http://www.tianya.cn/11488997/bbs```，ID是```11488997```，在主页-他的帖子-更多，可查看所有的回帖，希望能支持推送用户的回帖[http://www.tianya.cn/11488997/bbs?t=reply](http://www.tianya.cn/11488997/bbs?t=reply)。 谢谢

---

搜过issue，虽然已存在2个天涯相关的请求，但一个没细节[1891](https://github.com/DIYgod/RSSHub/issues/1891)，一个超时[539](https://github.com/DIYgod/RSSHub/issues/539)，因此重提issue

**Comment by yefoenix** [comment]
#1891 依然是 open 状态，直接在下面补充细节即可，具体实现还要等一个有缘人，不必重复开issue

**Comment by KwToPA** [comment]
@a14907   大鸽，能不能支持推送用户的回复？
---
### 谢谢

**Comment by a14907** [comment]
> ## @a14907 大鸽，能不能支持推送用户的回复？
> ### 谢谢

可以，不过需要时间实现

**Comment by a14907** [comment]
> ## @a14907 大鸽，能不能支持推送用户的回复？
> ### 谢谢

到pull requests下面提具体要求，不然忘了
