### ISSUE TITLE
請幫忙製作 Lancet endocrinology and diabetes 糖尿病內分泌最重要期刊的 RSS

### ISSUE THREAD

**Issue by zinojeng** [DIYgod/RSSHub#2635]
### 需要生成什么内容？

- [ ] 内容一：  **Current issue：https://www.thelancet.com/journals/landia/issues**

(https://www.thelancet.com/journals/landia/issue/vol7no8/PIIS2213-8587(19)X0008-X
https://www.thelancet.com/journals/landia/issue/vol7no7/PIIS2213-8587(19)X0007-8
https://www.thelancet.com/journals/landia/issue/vol7no6/PIIS2213-8587(19)X0006-6
..
..
https://www.thelancet.com/journals/landia/issue/vol7no2/PIIS2213-8587(19)X0002-9
https://www.thelancet.com/journals/landia/issue/vol7no1/PIIS2213-8587(18)X0013-8
... and so on...)

- [ ] 内容二： **Online first： https://www.thelancet.com/journals/landia/onlineFirst**

### 额外描述  Thank you very much

**Comment by SettingDust** [comment]
https://www.thelancet.com/content/rss
