### ISSUE TITLE
BBC，纽约时报不能通过代理抓取

### ISSUE THREAD

**Issue by XSpark91** [DIYgod/RSSHub#2647]
### 路由地址
路由: /bbc/:channel?
路由: /nytimes/index/:lang?

### 预期是什么？
希望能走代理成功订阅到BBC和纽约时报

### 实际发生了什么？
无法订阅。
反馈信息为：
Error: connect ETIMEDOUT 31.13.72.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

### 部署相关信息
我是MacBook本地部署，
代理的配置是通过.env设置的
PROXY_PROTOCOL=http
PROXY_HOST=127.0.0.1
PROXY_PORT=1087
PROXY_URL_REGEX=(.*\.)?(facebook|instagram|bbc|co|economist|nytimes)\.(uk|com)(/.*)?
成功订阅了instagram等，唯独BBC和纽约时报抓取不了，即使PROXY_URL_REGEX=.*也不行

### 额外信息（日志、报错等）
上边是.env的代理设置，下边是终端出现的信息

<img width="526" alt="whynoproxy" src="https://user-images.githubusercontent.com/41989335/61445836-ba6b1a00-a980-11e9-9aab-a8d69da8b7c8.png">

**Comment by heckerl** [comment]
同问

**Comment by kt286** [comment]
测试没问题啊
```
PROXY_PROTOCOL=socks
PROXY_HOST=127.0.0.1
PROXY_PORT=1080
PROXY_URL_REGEX=.*
```
![image](https://user-images.githubusercontent.com/10684972/62669855-c9fbe280-b9c3-11e9-96a8-671baaba8830.png)

会不会是你代理的问题

**Comment by DIYgod** [comment]
Fixed in 08878e1
