### ISSUE TITLE
【证监会-行政处罚决定】Rss Wanted—— 希望支持推送 “行政处罚决定” 谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2652]
### 网站地址
[http://www.csrc.gov.cn/pub/newsite/xzcfw/xzcfjd/](http://www.csrc.gov.cn/pub/newsite/xzcfw/xzcfjd/)
### 网站描述
中国证券监督管理委员会
### 需要生成什么内容？

- [ ] 内容一
【证监会-行政处罚决定】Rss Wanted—— 希望支持推送 “行政处罚决定” 谢谢
### 额外描述
[证监会-市场禁入决定](https://github.com/DIYgod/RSSHub/issues/2653)

**Comment by KwToPA** [comment]
@LogicJake 谢谢

**Comment by LogicJake** [comment]
@KwToPA 会自动关的

**Comment by KwToPA** [comment]
@LogicJake  [#证监会消息](https://docs.rsshub.app/government.html#%E8%AF%81%E7%9B%91%E4%BC%9A%E6%B6%88%E6%81%AF)无作者，举例，路由，参数
```
证监会消息
"连接']" />
```

**Comment by LogicJake** [comment]
@KwToPA 最新的pr修正了
