### ISSUE TITLE
config.js中的blacklist无效

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2663]
### 路由地址
无
### 预期是什么？
blacklist生效
### 实际发生了什么？
blacklist无效，我修改了```config.js```后```yarn```

```
blacklist: process.env.BLACKLIST && process.env.BLACKLIST.split('ip_1,ip_2')
```
但是通过查看页面```ip:port```中的热门IP发现，黑名单中的ip依然出现
```
热门IP: 次数 ::ffff:ip_1
```

若blacklist生效，是不是热门IP就不会出现被封的ip？
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    centos 7           |
| Node version       |      v10.16.0         |
| if Docker, version |       none        |

### 额外信息（日志、报错等）

无

**Comment by DIYgod** [comment]
blacklist 也会被统计进去，只是请求会被 reject
