### ISSUE TITLE
希望能加入 The long read | News | The Guardian 的RSS

### ISSUE THREAD

**Issue by aoaim** [DIYgod/RSSHub#2665]
### 需要生成什么内容？

- [ ] 正标题和副标题、作者/来源、题图和正文全文。

**Comment by yefoenix** [comment]
@aoaim 你可以考虑赞助项目或附上一张你自己的女装照来获得更快的 issue 响应速度

**Comment by kt286** [comment]
https://www.theguardian.com/news/series/the-long-read/rss

**Comment by aoaim** [comment]
我试过这个，这个并不是全文输出…很不方便阅读

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
