### ISSUE TITLE
似乎相关filter功能无法过滤#这个符号。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#2667]
### 路由地址
https://rsshub.app/weibo/user/1575168515?filterout=#
https://rsshub.app/weibo/user/1575168515?filter=#
### 预期是什么？
过滤掉含#的内容
### 实际发生了什么？
未能成功过滤，什么变化都没发生。
### 部署相关信息
已更新到目前最新commit

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
尝试过转义，https://rsshub.app/weibo/user/1575168515?filterout=\# ，直接报错。
也就是说无法对含#这个符号的字符串进行过滤操作。

所以，这是bug吗？是的话，能否修复一下呢？如果不是，那该如果实现过滤的效果呢？

**Comment by yefoenix** [comment]
@ruleroller #的转义为%23
