### ISSUE TITLE
请求 fix 微博 emoji 表情问题

### ISSUE THREAD

**Issue by lzsdodo** [DIYgod/RSSHub#267]
当用户发送或转发内容仅有单个 emoji 表情时，title 标签无显示内容。
`<title> <![CDATA[]]> </title>`

**Comment by Ir1d** [comment]
有例子吗？无法复现

**Comment by DIYgod** [comment]
你可能指的是微博的表情而不是 emoji ？

微博表情是图片，标题中无法显示图片

**Comment by lzsdodo** [comment]
原微博：
![image](https://user-images.githubusercontent.com/9102444/40933612-daf29848-67e6-11e8-9dc1-b88cf081df84.png)
RSS_Bot：
![image](https://user-images.githubusercontent.com/9102444/40933915-e8fd94b4-67e7-11e8-87df-0ee498e83658.png)

我是自己部署 RSSHub 以及 RSSBot 来订阅的。
这种情况，就是纯表情不显示图片或其他内容，无法直接进入该页面。
如果标题中无法显示图片，是否可以生成对应的文字，如 [哈哈] 之类，来作为超链的载体？
我的想法是，诸如此类的图片，如果不容易实现 '表情<=>文字' 的匹配，可以用一个通用的 "[表情]" / "[图片]" 来直接插入在标题中。
个人认为超链带来的易用性比表情-文字匹配的正确性更为重要。
（另外，并不知道纯粹微博表情转发的频率的高低）
