### ISSUE TITLE
人民日报重要言论库

### ISSUE THREAD

**Issue by dai640** [DIYgod/RSSHub#2672]
### 网站地址
http://opinion.people.com.cn/GB/8213/49160/index.html

### 网站描述
人民日报重要言论库

### 需要生成什么内容？
生成对应地址的最新社评的全文输出

- [ ] 内容一
- [ ] 内容二

### 额外描述
相对来说，这个地址下的rss每天输出的频率不算高频，可能有10来条新闻。
感谢你们一直以来无私，大爱的奉献精神，给我们这些还在坚持利用RSS服务，来获取信息渠道的用户们提供最完善，免费的，高效的，共享的精神。向你们致敬！

**Comment by kt286** [comment]
https://rsshub.app/people/opinion/40604

**Comment by dai640** [comment]
这效率太高了，难以言表的激动，无论多华丽的词藻都形容不了对你们的谢意。谢谢，谢谢！
