### ISSUE TITLE
请求添加http://www.10000link.com/的RSS辛苦了

### ISSUE THREAD

**Issue by strivekai** [DIYgod/RSSHub#2674]
### 需要生成什么内容？

- [ ] 内容一 行业动态
- [ ] 内容二 物流企业

**Comment by yefoenix** [comment]
行业动态、物流企业的页面链接请提供一下

**Comment by strivekai** [comment]
非常感谢您，能够帮助我
行业动态 ：http://info.10000link.com/newslists.aspx?chid=My01
物流企业：http://info.10000link.com/newslists.aspx?chid=My02

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jonathan Gongye <notifications@github.com>
发送时间: Tuesday, July 23, 2019 12:38:34 PM
收件人: DIYgod/RSSHub <RSSHub@noreply.github.com>
抄送: strivekai <zhangkai0823@outlook.com>; Author <author@noreply.github.com>
主题: Re: [DIYgod/RSSHub] 请求添加http://www.10000link.com/的RSS辛苦了 (#2674)


行业动态、物流企业的页面链接请提供一下

―
