### ISSUE TITLE
虎扑篮球新闻

### ISSUE THREAD

**Issue by kxshu** [DIYgod/RSSHub#2687]
### 网站地址
https://voice.hupu.com/generated/voice/news_nba.xml
### 网站描述
虎扑篮球新闻
### 需要生成什么内容？

- [ ] 已经是现成的RSS地址了，怎么集成？
- [ ] 如何能支持tiny tiny rss ?

**Comment by kt286** [comment]
这 issue 是来搞笑的嘛

**Comment by kxshu** [comment]
有什么问题？ @kt286

**Comment by kxshu** [comment]
为什么要关？
rsshub上现在的确没有支持这个地址。
如果是格式不对，可以留言说格式不对，我换个格式就是了。

**Comment by DIYgod** [comment]
RSSHub 是给不支持 RSS 的内容生成 RSS 用的，没看懂你想要做什么

**Comment by kxshu** [comment]
@DIYgod 感谢回复，是我没看懂rsshub关于虎扑的rss配置，已经重新阅读，解决问题了。
