### ISSUE TITLE
贴吧帖子全文输出

### ISSUE THREAD

**Issue by mengx8** [DIYgod/RSSHub#269]
贴吧帖子列表增加精品过滤

**Comment by u3u** [comment]
你指的是只显示精品帖子吗？

**Comment by mengx8** [comment]
@u3u 对的

**Comment by yingziwu** [comment]
@Qixingchen 
读取精品列表的确是没这个问题。
我只是觉的精品过滤这种东西和RSS气质不太相符。

另外发现百度贴吧并不是全文输出，感觉这一点可以想办法改进一下。

**Comment by u3u** [comment]
@yingziwu 因为百度贴吧并没有提供接口

**Comment by mengx8** [comment]
@yingziwu 主要是有这方面的需求。例如我比较关注oricon吧的精品贴，因为吧内的资源下载贴都会被加精，其他帖子我并不关注，我只要跟踪精品贴就好了

**Comment by u3u** [comment]
@yingziwu 
这样的话请求太频繁了，并且稳定性也会下降，还有被封的风险。
一旦其中一个全文查询失败了，整个请求就浪费了。

**Comment by yingziwu** [comment]
@u3u
可以加缓存，加数据库来解决这个问题。
因为百度贴吧的贴子发出后便无法修改，所以每个贴子只获取首楼的话，一个贴子只需要最开始请求一次，之后的请求直接从缓存/从数据库里读就可以了，不会太多的增加请求压力。

我之前爬取v2ex新贴的项目，基本思路就是：
从 [latest api](https://www.v2ex.com/api/topics/latest.json) 获得部分新贴内容及最新的topic id  ====>  使用最新的topic id比对当前数据库，生成需请求的topic列表 ====> 调用另一线程，请求相应topic，处理后存入数据库

对于百度贴吧也可以这样搞：
请求贴吧首页，获得首页id列表 ====> 将此id列表与缓存/数据库比对（若缓存/数据库中无相应id全文，则将该id加入请求列表），获得待请求id列表 ====> 请求列表中的贴子，获取全文，处理后存入缓存/数据库 ====> 输出带全文输出的Feed
这样的话，只是在第一次抓取时请求会多一点，之后只需要请求首页和新贴就可以了。而且这样，也不会出现“一个全文查询失败了，整个请求就浪费了”的情况。

**Comment by yingziwu** [comment]
@u3u 
感觉这种二次请求的情景挺多的，论坛类的网站、小说站点都适用于这种模式。
现在的问题是，这种缓存应当如何实现？

**Comment by Qixingchen** [comment]
@yingziwu 缓存已经有了啊 https://github.com/DIYgod/RSSHub/tree/master/docs/joinus#%E4%BD%BF%E7%94%A8%E7%BC%93%E5%AD%98

https://github.com/DIYgod/RSSHub/blob/master/routes/bilibili/cache.js 这里也有使用 cache 的代码

**Comment by yingziwu** [comment]
@Qixingchen 
傻了傻，之前看文档不仔细呀！
丢人了，逃~~
