### ISSUE TITLE
抖音订阅失效

### ISSUE THREAD

**Issue by zhongwangninja** [DIYgod/RSSHub#2701]
### 路由地址

https://rsshub.app/douyin/user/61608272917

### 预期是什么？

希望得到抖音的 rss 结果
这是抖音的分享页面 https://www.douyin.com/share/user/61608272917

### 实际发生了什么？

无 rss 返回，页面报错
```
RSSHub 发生了一些意外:
[object Object]
```

rsshub 文档 抖音的示例链接也出现如上报错 https://rsshub.app/douyin/user/93610979153

**Comment by yefoenix** [comment]
@zhongwangninja 抓取抖音比较消耗资源，官方服务难以保持稳定，建议自建

**Comment by zhongwangninja** [comment]
了解了，多谢
