### ISSUE TITLE
Docker使用改进

### ISSUE THREAD

**Issue by soulteary** [DIYgod/RSSHub#271]
@DIYgod 这个项目很赞，最近在寻找替换掉老PHP RSS的项目，看到了你的项目，使用之后感觉还真不错。

我个人重新封装了一个Dockerfile，以及配套的docker-compose.yml 相比较现在使用的文件和配置有一些改进：

1. 进程管理交托docker-compose去管理，这样来有几个好处
  1. 镜像是瘦镜像，未来如果有scale需求，相对轻松很多。
  2. 精简掉没必要使用的pm2，环境更干净，也更容易升级到标准的Node LTS Base 镜像。
2. 镜像 Base 替换为更小巧的 Node v10 LTS
3. 包管理工具回归npm v6（node v10 LTS中默认使用）
  1. 速度和yarn相比毫不逊色
  2. 当然也可以继续使用yarn，只不过我在初始化的过程中遇到了一些麻烦，感觉还不如就使用官方默认kit靠谱。
4. 配置文件隔离，使用compose管理
  1. 方便进行项目版本升降，隔离用户配置和应用程序。
 

如果你感兴趣的话，我会fork一份，提一个PR给你，不感兴趣的话，我就关闭掉这个issue自娱自乐了，:D

**Comment by DIYgod** [comment]
@soulteary 要！听起来很棒

**Comment by soulteary** [comment]
done.

多啰嗦几句，对于普通用户来讲，直接存储到共享卷里足够，但是如果未来考虑数据打包迁移的话：

1. 做Redis主从的高级玩家可以忽略这个情况
2. 想扩容或者迁移rdb的玩家，从共享卷里拷文件，或许不如把rdb映射出来，做aof

另外，如果你愿意接下来对项目结构做一个调整的话，非源码相关的文件可以很好的和源码隔离开...
