### ISSUE TITLE
RSSHub的指南里pixiv排行榜rss说明未填写

### ISSUE THREAD

**Issue by SayaSS** [DIYgod/RSSHub#2728]
###
快速访问地址:
https://docs.rsshub.app/social-media.html#%E6%8E%92%E8%A1%8C%E6%A6%9C-2
### 路由地址应为
/pixiv/ranking/:参数
### 预期是什么？
应有说明
### 实际发生了什么？
说明未填写

**Comment by yefoenix** [comment]
@SayaSS 跟ssr什么关系？

**Comment by SayaSS** [comment]
> @SayaSS 跟ssr什么关系？

手胡。。😅
