### ISSUE TITLE
国家发改委 - 政策发布中心

### ISSUE THREAD

**Issue by dai640** [DIYgod/RSSHub#2730]
### 网站地址
http://www.ndrc.gov.cn/zcfb  （这个地址实际上是跳转到另外一个子目录，从逻辑上判断的话这个是母目录，下面的分类，暂且就按这个url）
### 网站描述
国家发改委 - 政策发布中心
### 需要生成什么内容？
对应的全文输出，官方有rss输出服务，但是只有标题。
- [ ] 内容一
发展改革委令 ：http://www.ndrc.gov.cn/zcfb/zcfbl/
- [ ] 内容二
规范性文件 ：http://www.ndrc.gov.cn/zcfb/gfxwj
- [ ] 内容三
公告 ：	http://www.ndrc.gov.cn/zcfb/zcfbgg
- [ ] 内容四
通知 ：http://www.ndrc.gov.cn/zcfb/zcfbtz

### 额外描述
如果生成的RSS全文内容可以只用一个url来解释输出的话就最好了。再次感谢你们背后无私的奉献。

**Comment by yefoenix** [comment]
rsshub  不接受已有RSS的全文抓取需求，如有能力自行编写路由，rsshub 可接受pr。
全文抓取可以由阅读器来解决。
