### ISSUE TITLE
请问配置时的"对应 id 的 Twitter token"这个id指的是啥

### ISSUE THREAD

**Issue by SayaSS** [DIYgod/RSSHub#2731]
### 这个功能可以解决什么问题？
帮助部署完成

**Comment by Felix2yu** [comment]
TWITTER_ACCESS_TOKEN中减号前的那串数字

**Comment by kt286** [comment]
文档说的那么清楚  好好看  
issue 关闭

**Comment by Rixcloudllnll** [comment]
@Felix2yu @kt286 两位好，我配置twitter的.env也不成功，[https://github.com/DIYgod/RSSHub/issues/5234](https://github.com/DIYgod/RSSHub/issues/5234) 请问是哪里出问题了吗？  谢谢
