### ISSUE TITLE
Dalton Maag Blog 抓取需求

### ISSUE THREAD

**Issue by BravoCiao** [DIYgod/RSSHub#2740]
### 网站地址
https://blog.daltonmaag.com
### 网站描述
字体公司 Blog
### 需要生成什么内容？

- [ ] 博文

**Comment by yefoenix** [comment]
@BravoCiao https://blog.daltonmaag.com/feed

**Comment by BravoCiao** [comment]
> @BravoCiao https://blog.daltonmaag.com/feed

太谢谢了，我自己直接用网址订阅似乎是不成功的咦咦咦
