### ISSUE TITLE
剑来小说  抓取需求

### ISSUE THREAD

**Issue by destincc** [DIYgod/RSSHub#2746]
### 网站地址
http://www.jianlaixiaoshuo.com/
### 网站描述
剑来 小说
### 需要生成什么内容？

- [ ] 章节内容

**Comment by ActonGen** [comment]
> ### 网站地址
> http://www.jianlaixiaoshuo.com/
> 
> ### 网站描述
> 剑来 小说
> 
> ### 需要生成什么内容？
> * [ ]  章节内容
> 
> ### 额外描述

已经有很多小说网站可以订阅剑来了呀

**Comment by destincc** [comment]
这个网站更新的及时，而且排版好多了

**Comment by CROXIE** [comment]
😢 還有什麼網站可以訂閱小說嗎，之前用的筆趣閣給掛了，現在都不知道用啥

**Comment by Maecenas** [comment]
X-Y问题。订阅 <https://rsshub.app/novel/wenxuemi/22/22572/> 就可以了，看了下你说的网站还有屏蔽词。
