### ISSUE TITLE
pixiv 自己关注的画师的新作品

### ISSUE THREAD

**Issue by ClarkeCheng** [DIYgod/RSSHub#2750]
### 网站地址
[https://www.pixiv.net/bookmark_new_illust.php](https://www.pixiv.net/bookmark_new_illust.php)
### 网站描述
关注的新作品

### 需要生成什么内容？
针对自己关注的所有画师生成RSS，无论是谁有了新作品，都会通过这个RSS提醒

**Comment by SettingDust** [comment]
@ClarkeCheng 建议自己fork添加，不具有适用性，造成压力也很大
