### ISSUE TITLE
国家药品审评网站www.cde.org.cn

### ISSUE THREAD

**Issue by alex20180206** [DIYgod/RSSHub#2759]
### 网站地址
www.cde.org.cn

### 网站描述
这是国家药品审评网站，在该网站国家会公布对药品审评审批的相关信息，确保广大人民群众，用药的可及性及安全性

### 需要生成什么内容？

- [ ] 内容一
1 .工作动态
  了解目前国家药品监督管理局，目前的动态，及时了解药品上市信息及相关安全信息
- [ ] 内容二
2 法规与规章
  国家局公布的一些法律法规，为药品从业人员提供相应指导
-[] 内容三
3.信息公开
及时了解信息

### 额外描述
  已在feed43进行相关RSS创制，发现为非法url，被拒绝访问
所以有此次issue提交，谢谢各位

**Comment by NeverBehave** [comment]
稍微看了一下，这个页面有个很奇怪的混淆，但是可以通过首次访问获取cookie后附带cookie访问绕过

如果有人接下来有兴趣的话可以参考一下
