### ISSUE TITLE
【BUG提交】抖音、微博用户抓取全部失败

### ISSUE THREAD

**Issue by linewoo** [DIYgod/RSSHub#2765]
### 网站地址
抖音、微博
### 网站描述
抖音用户、微博用户抓取全部失效
报错信息：
RSSHub 发生了一些意外:
[object Object]

**Comment by yefoenix** [comment]
微博反爬严格，抖音抓取资源消耗极大，rsshub.app 作为Demo服务无法保证稳定，这两个网站的抓取建议使用自建服务。
另外 提issue请遵循模板提供完整信息。

**Comment by SettingDust** [comment]
@yefoenix 请仔细阅读文档，自行关闭issue

**Comment by chouj** [comment]
> ### 网站地址
> 抖音、微博
> 
> ### 网站描述
> 抖音用户、微博用户抓取全部失效
> 报错信息：
> RSSHub 发生了一些意外:
> [object Object]

微博我是用的这两家自建RSShub的

https://uneasy.win/rss/
https://rsshub.mabutou.me

**Comment by yefoenix** [comment]
@chouj 这种公开的自建用的人多了一样也会被反爬啊
