### ISSUE TITLE
[Feature Request] Use photon CDN to anti hotlink-protection

### ISSUE THREAD

**Issue by SukkaW** [DIYgod/RSSHub#2769]
### What feature is it?

Using Photon Image CDN to anti hotlink-protection.

### What problem does this feature solve?

RT.

### Additional description

Photon CDN is part of a WordPress Plugin `Jetpack by WordPress`, but currently it is available for all the domain even without WordPress installed.

Usage:

```
https://i0.wp.com/docs.rsshub.app/logo.png
https://i1.wp.com/blog.skk.moe/img/suka-favicon.png
https://i2.wp.com/rixcloud.com/static/img/hulu-comment.8038550.png
https://i3.wp.com/i.loli.net/2019/04/23/5cbeb7e41414c.png
```

**Comment by aka-rin** [comment]
也可以考虑 DuckDuckGo 啦: https://proxy.duckduckgo.com/iu/?u=https://docs.rsshub.app/logo.png

**Comment by SukkaW** [comment]
@aka-rin https://images.weserv.nl is definitely a better option since `proxy.duckduckgo.com` is GFWed. But `i0.wp.com` `i1.wp.com` `i2.wp.com` `i3.wp.com` is shorter and faster.

**Comment by NeverBehave** [comment]
应该可以关闭了
https://github.com/DIYgod/RSSHub/commit/cde5d9af45c6e7383f48ab3ced3de60b2e310db1

**Comment by xuxanwan** [comment]
docker-compose作为environment设置时,由于${xxxx}默认会被docker-compse解析,需要配置两个$$,具体如下:
```
    environment:
        HOTLINK_TEMPLATE: 'https://images.weserv.nl/?url=$${protocol}//$${host}$${pathname}'
```
