### ISSUE TITLE
微信公众号获取失败，但其他的都没问题。

### ISSUE THREAD

**Issue by fucao** [DIYgod/RSSHub#2771]
**网站地址**
微信公众号
**网站描述**
不知道如何描述，如下图；
有梯子

![image](https://user-images.githubusercontent.com/15061002/62433791-88bbc680-b768-11e9-816f-417812c52609.png)
![image](https://user-images.githubusercontent.com/15061002/62433797-8f4a3e00-b768-11e9-93a9-b6117fcbe54b.png)

**Comment by kt286** [comment]
有梯子么？？

**Comment by yefoenix** [comment]
提 issue 请遵循模板

**Comment by DIYgod** [comment]
https://docs.rsshub.app/install/#%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE
