### ISSUE TITLE
docker 镜像增加版本号 tag

### ISSUE THREAD

**Issue by ibrother** [DIYgod/RSSHub#2774]
### 这是一个什么样的功能？

docker 部署时可以用 tag 指定版本

### 这个功能可以解决什么问题？

目前发布的 docker tag 只有默认的 latest，有些时候需要部署特定的版本，方便升级，回滚

**Comment by DIYgod** [comment]
目前没有分版本，更新频繁，不可能每个 commit 都保留一个镜像

**Comment by ibrother** [comment]
不是每个 commit 保留一个镜像，只是建议以后分版本，打 tag 的时候，docker 镜像也 tag 下

**Comment by yefoenix** [comment]
@ibrother 可以自己构建image

**Comment by ibrother** [comment]
@yefoenix 是的，官方暂时没有的话，自己打 tag 也是一个办法
