### ISSUE TITLE
某皮肤学家网站内容求扒拉

### ISSUE THREAD

**Issue by BravoCiao** [DIYgod/RSSHub#2778]
### 网站地址
https://knowledge.ulprospector.com/author/george-deckner/

### 网站描述
皮肤科学家的个人专栏

### 需要生成什么内容？

- [ ] 博文

**Comment by yefoenix** [comment]
……
https://knowledge.ulprospector.com/author/george-deckner/feed/

**Comment by BravoCiao** [comment]
> ……
> https://knowledge.ulprospector.com/author/george-deckner/feed/

这都是在哪儿找到的呢？是简单地在 url 后面加 fee/ 就可以吗？

**Comment by yefoenix** [comment]
Ctrl+U 或者用扩展 RSSHub-Radar 都可以……

**Comment by BravoCiao** [comment]
> Ctrl+U 或者用扩展 RSSHub-Radar 都可以……

好哒，为我的无常识画上六个大句点。。。。。。
