### ISSUE TITLE
防止更新时 `config.js` 冲突

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#279]
1. `config.js` 改名 `config.example.js`
1. 要求用户自行创建 `config.js`
1. 没有 `config.js` 时使用 `config.example.js`

**Comment by soulteary** [comment]
其实还好啦，有两个模式你可以参考下：

1. 除了dotfiles全部扔 {src, test, scripts, ...}目录，根目录就腾出来了，相对大的工程。
2. config目录甩$HOME下，完结撒花，参考各种目录结构不好调整的项目。
