### ISSUE TITLE
路由挂了 <一觉醒来世界发生了什么 - 即刻主题精选> 

### ISSUE THREAD

**Issue by cryzlasm** [DIYgod/RSSHub#2790]
### 路由地址
https://rsshub.app/jike/topic/553870e8e4b0cafb0a1bef68
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/20424580/62669186-3e139780-b97e-11e9-8b0b-50c3affabfc8.png)

**Comment by yefoenix** [comment]
@cryzlasm 即刻源站都暂停服务了

**Comment by cryzlasm** [comment]
> @cryzlasm 即刻源站都暂停服务了

我不知道, 不好意思
