### ISSUE TITLE
发布时间相同时播客排序不正确

### ISSUE THREAD

**Issue by gh02817560** [DIYgod/RSSHub#2795]
### 路由地址
https://rsshub.app/ximalaya/album/3544633/all
### 预期是什么？
在iOS系统的播客上通过URL添加此内容，并且把播放顺序调整为从旧到新，播客上的播放顺序与实际集数一致
### 实际发生了什么？
由于发布日期和时间都相同，造成了播客上的排序混乱，应该是1,2,3,4.......339的顺序变成了23,22,21......1,42,41,40.....24,86,85.......这样的顺序
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by kt286** [comment]
这个是你博客软件的bug吧

**Comment by lengthmin** [comment]
调整软件里的排序 应该可以吧..
---
我这边用的 pocketcast 试着调整了一下，能恢复正常顺序。
![image](https://user-images.githubusercontent.com/13938334/62682185-1a883580-b9ee-11e9-822d-202d841fddec.png)
![image](https://user-images.githubusercontent.com/13938334/62682195-1fe58000-b9ee-11e9-8841-da8af55dee20.png)

**Comment by lengthmin** [comment]
源顺序是没问题的。
![image](https://user-images.githubusercontent.com/13938334/62682268-54593c00-b9ee-11e9-8cf5-3d0543cdb722.png)

**Comment by gh02817560** [comment]
> 这个是你博客软件的bug吧
用的就是iPhone自带的那个播客软件，看了下源的顺序确实是没问题的，他把上传时间相同的单集做了倒叙排列，所以无论是从最新到最旧还是从最旧到最新，顺序都是不对，然后新建电台和节目还都没有按照节目名称排列这个功能

**Comment by gh02817560** [comment]
> ## 调整软件里的排序 应该可以吧..
> 我这边用的 pocketcast 试着调整了一下，能恢复正常顺序。
> ![image](https://user-images.githubusercontent.com/13938334/62682185-1a883580-b9ee-11e9-822d-202d841fddec.png)
> ![image](https://user-images.githubusercontent.com/13938334/62682195-1fe58000-b9ee-11e9-8841-da8af55dee20.png)

用的就是iPhone自带的那个播客软件，看了下源的顺序确实是没问题的，他把上传时间相同的单集做了倒叙排列，所以无论是从最新到最旧还是从最旧到最新，顺序都是不对，然后新建电台和节目还都没有按照节目名称排列这个功能

**Comment by gh02817560** [comment]
> 源顺序是没问题的。
> ![image](https://user-images.githubusercontent.com/13938334/62682268-54593c00-b9ee-11e9-8cf5-3d0543cdb722.png)

用的就是iPhone自带的那个播客软件，看了下源的顺序确实是没问题的，他把上传时间相同的单集做了倒叙排列，所以无论是从最新到最旧还是从最旧到最新，顺序都是不对，然后新建电台和节目还都没有按照节目名称排列这个功能

**Comment by gh02817560** [comment]
并且在overcast上也试过了，也是同样的问题

**Comment by lengthmin** [comment]
@DIYgod 并不是 rsshub 的问题，其实可以 close 的...
出现这个问题的原因：
这个小说的所有章节在喜马拉雅上的发布时间是相同的，所以部分播客可能无法正确处理这些相同时间发布播客的顺序。

**Comment by DIYgod** [comment]
@lengthmin 但正常情况是新的是在上面的，时间相同时播客软件这样排序也没什么问题

**Comment by lengthmin** [comment]
@DIYgod 噢 有道理

**Comment by gh02817560** [comment]
所以。。。这算是一个BUG么。。。确实原因是由于软件不支持按照名称排序造成的，但是体验在iPhone的播客上还有overcast上确实不怎么好

**Comment by lengthmin** [comment]
是一个没有注意过的 bug，#2804 已经修复了。

**Comment by gh02817560** [comment]
> 是一个没有注意过的 bug，#2804 已经修复了。

是要从新获取路由么。。。。刚才试了一下，在iPhone的播客上删除这个节目，从新通过URL获取，结果排序依然不正常

**Comment by lengthmin** [comment]
要等这个修复的提交被合并(merge)到了主分支之后才能用。

gh02817560 <notifications@github.com> 于2019年8月9日周五 下午1:51写道：
