### ISSUE TITLE
希望增加饭否RSS

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#2800]
饭否
### 网站地址
http://fanfou.com/
### 需要生成什么内容？

- [ ]各种热点
- [ ] 话题

**Comment by yefoenix** [comment]
https://github.com/FanfouAPI/FanFouAPIDoc/wiki/trends.list
https://github.com/FanfouAPI/FanFouAPIDoc/wiki/search.public-timeline

**Comment by yefoenix** [comment]
应该比微博的api还简单，有没有人搞下这个……

**Comment by yefoenix** [comment]
solved by #3427 
可以关闭了 @DIYgod
