### ISSUE TITLE
爱思想排行榜无法添加订阅rss

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#2801]
### 路由地址
https://rsshub.app/aisixiang/ranking/11/7
### 预期是什么？
正常添加订阅
### 实际发生了什么？
ttrss等都无法添加rss源
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by kt286** [comment]
这个是反爬  自建的也是时好时坏
