### ISSUE TITLE
Docker 部署出现问题

### ISSUE THREAD

**Issue by mr-cn** [DIYgod/RSSHub#281]
在Docker1.7.1与Docker17.10.0-ce两个Docker版本的机器上均不能成功部署

在启动后数秒内容器就会`Exited(0)`且日志没有任何输出

使用的是`diygod/rsshub:latest`镜像

启动命令是`docker run -d --name rsshub -p 1200:1200 diygod/rsshub`

**Comment by Jasonzj521** [comment]
同样问题

**Comment by fengkx** [comment]
同样问题，没有任何日志。用回上一版tag，latest不行。

**Comment by mintisan** [comment]
docker 17.09.0-ce  同样不成功

**Comment by ihcbbs** [comment]
同样。docker18.03.1-ce，@debian9.3，4.15PVE内核。

**Comment by mr-cn** [comment]
#299 尝试修复了一下
