### ISSUE TITLE
希望增加微问数据订阅RSS

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#2810]
### 网站地址
http://wewen.io/library
### 网站描述
微问数据，非常好的公众号订阅来源
### 需要生成什么内容？

- [ ] 公众号文章
- [ ] 文章更新提醒

**Comment by LogicJake** [comment]
这个文章都不是最新的吧

**Comment by TonyRL** [comment]
`wewen.io` is dead.
