### ISSUE TITLE
源的合并输出

### ISSUE THREAD

**Issue by josherich** [DIYgod/RSSHub#283]
对于一些新闻类，和ID，话题类的订阅，似乎源的合并输出是一个不错的功能。实现来说，可以在 url 参数中加入以逗号分隔的路由列表，合并排序后输出即可。

**Comment by Misaka2623** [comment]
同希望合并，现在很多rss阅读器都限制了订阅上限，如果合并输出的话可选择的阅读器就会非常多了

**Comment by HenryQW** [comment]
你们这一届的 [rss 阅读器](http://reederapp.com)不行啊。。。

**Comment by niu541412** [comment]
我也希望一个这样的功能，这样就间接可以订阅B站的更新动态了。
