### ISSUE TITLE
Docker Compose 部署 # 安装 创建 volume 持久化 Redis 缓存失败

### ISSUE THREAD

**Issue by Tenstu** [DIYgod/RSSHub#2851]
你好，请求帮助，查询不到错误原因

### 部署相关信息
Docker Compose 部署，使用sh
# 安装问题，创建volume 持久化 Redis 缓存失败,提示bash: docker: command not found，详情见图，第一步，docker-compose.yml已成功
| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/54093040/62996449-53655600-be97-11e9-9eb5-024bddd038db.png)

谢谢

**Comment by kt286** [comment]
你是来搞笑的么？

**Comment by Tenstu** [comment]
> 你是来搞笑的么？

![image](https://user-images.githubusercontent.com/54093040/62996477-709a2480-be97-11e9-80e0-7fd4de0d7919.png)
没有编程基础，不太懂，百度了也没有答案，要设置什么变量吗
