### ISSUE TITLE
Bilibili 用户关注视频动态路由

### ISSUE THREAD

**Issue by StubbornYang** [DIYgod/RSSHub#2855]
### 路由地址
/bilibili/followings/video/:uid
### 预期是什么？
抓取到相关信息
### 实际发生了什么？
> RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (/app/lib/middleware/parameter.js:11:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
|           OS          | Ubuntu 18.04.2 LTS |
| Docker-Compose version |1.24.1|

### 额外信息（日志、报错等）
使用最新的Cookies获取方式，服务器IP与获取Cookies的IP相同，部署方式为Docker Compose，系统为Ubuntu

**Comment by DIYgod** [comment]
无法复现，请确保部署为最新版本
