### ISSUE TITLE
【全文提取失效】bug report—— 对象 Al Jazeera English

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2861]
### 路由地址
[https://www.aljazeera.com/xml/rss/all.xml](https://www.aljazeera.com/xml/rss/all.xml)
### 预期是什么？
全文提取
### 实际发生了什么？
全文提取失效
### 部署相关信息
无

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      centos 7         |
| Node version       |    10.17           |
| if Docker, version |               |

### 额外信息（日志、报错等）

aljazeera的路由中也没有全文提取，是不是需要提 rss wanted? 谢谢

**Comment by yefoenix** [comment]
@KwToPA rsshub 暂不接受已有RSS feed 抓取全文的 issue，如有能力可自行编写路由后进行pr. 更简单的方式是把全文抓取任务交给阅读器。

**Comment by KwToPA** [comment]
@yefoenix  是指ttrss中的mercury fulltext plugins吗？  试了下 也不行

**Comment by KwToPA** [comment]
@HenryQW 大鸽，半岛新闻台全文提取有兴趣吗？ 谢谢
