### ISSUE TITLE
demo站的wangyin的pubDate仅部分文章生成

### ISSUE THREAD

**Issue by SkiTiSu** [DIYgod/RSSHub#2870]
### 路由地址
https://rsshub.app/blogs/wangyin

### 预期是什么？
我在#2777 为blogs/wangyin添加了pubDate，并且在官方demo站合并进后的一段时间可以正常运行，每一篇文章都有了pubDate

### 实际发生了什么？
但是现在仅部分文章有pubDate，我自己本地和自己服务器搭建无此问题，是否是缓存问题呢？
![image](https://user-images.githubusercontent.com/8959735/63208349-709f5c00-c105-11e9-8ba5-c288e9113ba8.png)

### 额外信息（日志、报错等）
因为是官方demo站，无从知晓细节，但是希望能够找到问题所在并修复:)

**Comment by DIYgod** [comment]
是缓存，现在已经好了
