### ISSUE TITLE
希望增加『电击Online（電撃オンライン）』新闻记事的RSS

### ISSUE THREAD

**Issue by LoneFireBlossom** [DIYgod/RSSHub#2881]
### 网站地址
https://dengekionline.com/
### 网站描述
以游戏资讯速报为中心，也包括APP、动画资讯的综合网站。
ゲーム速報を中心に、アプリ、アニメの情報も発信する総合エンタメサイト。ニュース、レビュー、インタビュー、動画などを通じて、最新のゲーム情報を毎日発信。
### 需要生成什么内容？
- [ ] 内容一
“最新記事”一栏的新闻，新闻应该是都在这个栏里

### 额外描述
谢谢RSSHUB
我找来找去没找到这个网站有rss，日本好多新闻网站都有的，感觉有点奇怪。

**Comment by cssxsh** [comment]
是否需要读取部分正文？
