### ISSUE TITLE
请求增加mcbbs论坛各大板块rss，对单个帖子更新追踪，全文支持

### ISSUE THREAD

**Issue by Zeng-JianWen** [DIYgod/RSSHub#2890]
###https://www.mcbbs.net/forum.php

### 需要生成什么内容？

- [ ] 论坛各大板块中的新贴
- [ ] 帖子的更新
- [ ] 楼主的更新

### 额外描述
最好能附上每条消息的时间戳

**Comment by yefoenix** [comment]
@DIYgod 这个已经解决 可以关闭了

**Comment by Zeng-JianWen** [comment]
谢谢开发者
