### ISSUE TITLE
新需求——【集思录】个人动态、帖子楼主回复、新帖

### ISSUE THREAD

**Issue by OwlWinter** [DIYgod/RSSHub#2899]
## 网站地址
广场：
https://www.jisilu.cn/explore/
个人页面：
https://www.jisilu.cn/people/luckzpz
帖子：
https://www.jisilu.cn/question/273614

### 网站描述
【集思录】投资论坛

### 需要生成什么内容？

- [ ] 内容一
广场页面，按照【最新】、【热门】、【发表时间】订阅。
- [ ] 内容二
个人页面，按照【主题】、【回复】订阅。
- [ ] 内容三
帖子，订阅【最新回复】或者【楼主回复】（需要登录才能做到）

**Comment by TonyRL** [comment]
Closed in #8541
