### ISSUE TITLE
自己部署生成的feed不能被Inoreader识别

### ISSUE THREAD

**Issue by StringXD** [DIYgod/RSSHub#290]
我是用SSH手动部署vps的方法部署的
![image](https://user-images.githubusercontent.com/22393259/41212507-0345b976-6d71-11e8-9158-b814fbbd608e.png)
用浏览器打开页面也成功生成了与RSSHub.app相同的XML
![image](https://user-images.githubusercontent.com/22393259/41212554-76d94740-6d71-11e8-9c5f-1bbfc76d2865.png)
但是在Inoreader中添加订阅源时输入订阅源URL为https://rsshub.app/weibo/user/3306934123 可以成功订阅，而输入 http://45.77.147.34:1200/weibo/user/3306934123 则提示未找到订阅源。
求大佬指点问题出在哪里？

**Comment by Qixingchen** [comment]
@StringXD 你部署的地址无法被打开，请确认防火墙等设置

**Comment by StringXD** [comment]
@Qixingchen 现在应该可以打开了，但是这个地址貌似需要科学上网才能打开

**Comment by Qixingchen** [comment]
使用代理目前依旧无法访问

**Comment by DIYgod** [comment]
同打不开

**Comment by StringXD** [comment]
@Qixingchen @DIYgod 现在用代理应该可以打开，但是我不知道怎么把这个服务挂在后台，所以时间长了可能会打不开

**Comment by GoodbyeNJN** [comment]
@StringXD 如果你的代理和rsshub在同一台机器上，那可能是可以打开的。

**Comment by StringXD** [comment]
@GoodbyeNJN 我的代理确实和rsshub在同一台机器上的，这个意思是说只有我自己才能打开吗？还是说有什么问题？

**Comment by StringXD** [comment]
![image](https://user-images.githubusercontent.com/22393259/41228593-78da6ba2-6dab-11e8-827d-763c001f4a38.png)
现在启动的时候偶尔还有这个错误

**Comment by GoodbyeNJN** [comment]
@StringXD 因为你机器的防火墙没放行1200端口，外网直连会被拦截，而通过你机器上的代理去连接，就相当于本机访问本地端口，这不经过防火墙。这个问题其实和rsshub毫无关系。
ps. 直接暴露ip地址可能会带来一些风险

**Comment by StringXD** [comment]
@GoodbyeNJN 开放1200端口后问题解决，感谢！
