### ISSUE TITLE
希望添加：rarbg.to 的分类rss

### ISSUE THREAD

**Issue by grinor** [DIYgod/RSSHub#2911]
### Website URL
rarbg.to

### Website description
https://rarbg.to

### What content should be included?
- [title] content one
- [magnet link ] content two
- [item link ] content two

### Additional description
虽然rarbg.to 本身有rss但是会漏很多源，似乎可以借助api来实现更完整的条目抓取，https://github.com/banteg/rarbg 这个项目似乎有类似的功能但是用起来不太稳定，希望能把rarbg的相关条目整合到rsshub中，非常感谢！🙏

**Comment by DIYgod** [comment]
The website is no longer accessible
