### ISSUE TITLE
抖音脚本失效

### ISSUE THREAD

**Issue by sswwqqb** [DIYgod/RSSHub#2916]
### 路由地址
/douyin/user/

### 预期是什么？
抖音用户动态

### 实际发生了什么？
RSSHub 发生了一些意外:
[object Object]

**Comment by Mr-Phone** [comment]
看一下失效的用户有没有作品。
无作品的用户会显示以下信息

RSSHub 发生了一些意外:
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/root/RSSHub/lib/middleware/parameter.js:11:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by yefoenix** [comment]
@sswwqqb [Object Object] 一般是没头浏览器问题，建议自建

**Comment by DIYgod** [comment]
已恢复
