### ISSUE TITLE
IP block or something else?

### ISSUE THREAD

**Issue by BGFR** [DIYgod/RSSHub#2918]
rsshub.app is a very nice thing. I set it up on my website for instagram feed. But sometimes it works sometimes it does not. My website is on shared hosting and i cannot understand if there are too many people with this same IP using rsshub or there is something else.
If that is the reason what can do to keep on using it?

**Comment by DIYgod** [comment]
Nope, it’s subject to instagram’s anti-crawler policy, the only thing you can do is to change IP frequently or [use proxy](https://docs.rsshub.app/en/install/#application-settings)

**Comment by BGFR** [comment]
ok but since the script looks like this 
$rss->load('https://rsshub.app/instagram/user/xxxx?limit=3');
What is the type of proxy i need to use. Should i add additional script or just soemthing before the http like $rss->load('https://rsshub.app/proxyservice:urll=https://rsshub.app/instagram/user/xxxx?limit=3');

**Comment by DIYgod** [comment]
The proxy is located in RSSHub, configurated by envionment variables, refer to [docs](https://docs.rsshub.app/en/install/#application-settings)
