### ISSUE TITLE
希望有大佬能帮忙添加RF技术社区文章列表的Feedly RSS源

### ISSUE THREAD

**Issue by Goodfellashxm** [DIYgod/RSSHub#2919]
### 网站地址
https://rf.eefocus.com/article/list-all
### 网站描述
RF技术社区文章
### 需要生成什么内容？

- [标题] 内容一
- [文章简介] 内容二
- [文章内容和图片] 内容三

### 额外描述

在Feedly中点开文章之前显示标题和简介，点开以后显示文字内容和相应位置的图片

**Comment by yefoenix** [comment]
feedly 有什么专属的格式规范吗？

**Comment by Goodfellashxm** [comment]
应该没有吧，一般RSSHub上发布的订阅源都可以用
