### ISSUE TITLE
对现有支持列表进行整理

### ISSUE THREAD

**Issue by idealclover** [DIYgod/RSSHub#293]
随着现在RSS源的不断增多，首页和文档中显示的RSS源越来越多，是否可以进行一些整理或者进一步推出相应的查找工具

**Comment by DIYgod** [comment]
@idealclover 我也意识到了这个问题，有什么好想法么

**Comment by yingziwu** [comment]
其实我觉得没有必要进行太多的整理，有目录、有网站域名就可以了。用的时候直接拿域名搜索就可以了。如果要整理的话，可以按网站类型大致分一下。

**Comment by idealclover** [comment]
@yingziwu 嗯嗯~感觉按网站类型大致分一下是个好主意！比如说emmm新闻类可以单独归个档，像看到的上海海事大学可以单独归一个大学类的专题？（因为也有打算开发自己学校的hhhh，其他的暂时还没想好QAQ

**Comment by DerekTso** [comment]
@DIYgod it seems the router list of the [rss docs](https://docs.rsshub.app) are not synced yet, some latest routers are missed.

**Comment by DIYgod** [comment]
@DerekTso 可能是半个月前删掉的 service worker 阴魂不散，手动清一下缓存吧

**Comment by DerekTso** [comment]
@DIYgod yes, after clearing those data, it's synced.

**Comment by ShimotsukiH** [comment]
想到一个方法 能不能像 http://jianshu.milkythinking.com/ 那样 直接输入想抓的页面 转换返回rss地址呢？（在此之上加上几个勾选筛选规则的按钮）遇到还不资瓷的地方 后台记录域名 再判断要不要开通新的 这样大家看好不好？

**Comment by yangkghjh** [comment]
有好用的域名解析库或者域名解析正则表达式吗

**Comment by HenryQW** [comment]
@ShimotsukiH 得先归档一下现有路由的命名，很枯燥的工作= =

**Comment by yangkghjh** [comment]
我的想法是解析 markdown 文档，将文档解析成源地址转换规则。

提供一个输入框让用户输入地址，用转换规则去匹配和转换。

**Comment by idealclover** [comment]
#468 chrome插件不错，另外其实现在的也可以大致按类别分一下了（比如新闻类可以单独归个档？

**Comment by HenryQW** [comment]
应该先做个本地网页版的 粘贴 --》匹配，到时候写插件可以共用很多逻辑

**Comment by DIYgod** [comment]
related project https://github.com/SevenOutman/rsshub.js

**Comment by DIYgod** [comment]
已经在 dc02466edf4a333ef5b4b019cafbc7d571a2588e 整理得很清晰了，issue 将被关闭

Shout out to @HenryQW
