### ISSUE TITLE
头条主页 RSS需求

### ISSUE THREAD

**Issue by dxmpalb** [DIYgod/RSSHub#2930]
### 网站地址
eg: https://www.toutiao.com/c/user/55226209342/#mid=1563849143119873 
其中mid通常是个时间戳，且为必须参数。

### 网站描述
头条主页，基本上涵盖了热门公众号内容。
有json接口。eg：https://www.toutiao.com/c/user/article/?page_type=1&user_id=5768092861&max_behot_time=0&count=20&_signature=GxT4YhAQRnoSWIJ3jgLP-BsU-H 其中_signature的计算方法在网页脚本上面好像有。

### 需要生成什么内容？

- [ ] 内容一 文章标题
- [ ] 内容二 文章全文输出
- [ ] 内容三（可选） 文章标签（在全文页面中）

### 额外描述
头条主页用户搜索：https://www.toutiao.com/search/?keyword=%E6%9E%9C%E5%A3%B3

**Comment by kt286** [comment]
#2811 #1887

**Comment by xuansir1** [comment]
在楼主举例的页面，通常都会出现文章、视频、微头条三个tab，希望能按照时间顺序，显示三个tab里的内容。

**Comment by xuansir1** [comment]
这么多天了，怎么都没更新呢 😂

**Comment by yefoenix** [comment]
@xuansir1 需要等一个有缘人，你也可以考虑赞助项目或附上一张你自己的女装照来获得更快的 issue 响应速度。

**Comment by xuansir1** [comment]
> @xuansir1 需要等一个有缘人，你也可以考虑赞助项目或附上一张你自己的女装照来获得更快的 issue 响应速度。

那有没有其它办法呢？

**Comment by yefoenix** [comment]
@xuansir1 自学 JS 自己上？

**Comment by xuansir1** [comment]
> @xuansir1 自学 JS 自己上？

一般几年能学成？

**Comment by SettingDust** [comment]
@xuansir1 3-7天左右
