### ISSUE TITLE
Pixiv "Everyone" / Safe illustration only

### ISSUE THREAD

**Issue by salieri-as** [DIYgod/RSSHub#2932]
### Additional description
just would like to have the safe-rating pixiv feed option, and probably separated NSFW/R+18 only as well, so people can choose according to their needs.

thanks in advance, this project really helps!

**Comment by SettingDust** [comment]
Regarding feed and bookmarks
	For NSFW filtering the two relevant JSON strings are "sanity_level" and "x_restrict"
		sanity_level
			2 -> Completely SFW
			4 -> Moderately ecchi e.g. beach bikinis, slight upskirts
			6 -> Very ecchi e.g. more explicit and suggestive themes
		 x_restrict
			1 -> R18 e.g. nudity and penetration
		In this code x_restrict is treated as a level 8 sanity_level
	For manga filtering, the value of the "type" string is checked for either "manga" or "illust"
Regarding rankings
	NSFW filtering is performed by checking the value of the "sexual" JSON string
	Manga filtering is performed by checking the value of the "illust_type" JSON string
