### ISSUE TITLE
Hpoi 手办维基 情报不完善

### ISSUE THREAD

**Issue by kosserYN** [DIYgod/RSSHub#2933]
路由地址
https://rsshub.app/hpoi/info/all

预期是什么？
可以看见手办预览图 点击链接可以进入网站

实际发生了什么？
看不见图片
rss提供的网址为http://www.hpoi.net/user/hobby/53002?type=info&catType=all
实际为http://www.hpoi.net/hobby/53002?type=info&catType=all

**Comment by kt286** [comment]
@DIYgod  这个issue应该可以关了吧
