### ISSUE TITLE
请问如何才能筛选带图片的信息呢？ 

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#294]
您好 我想通过rss关注twitter上的画师 但不巧他们有的都是话痨 
想起即刻关注微博可以筛选是否原创+是否带图片 （所以微博上的我都是先在即刻上做好主题然后再通过rss集合到我的阅读器）
不过twitter就只能用rss了

请问筛选代码是？

**Comment by GoodbyeNJN** [comment]
@ShimotsukiH https://docs.rsshub.app/

**Comment by GoodbyeNJN** [comment]
@ShimotsukiH 不好意思，没仔细看你的需求，似乎现在不支持筛选原创

**Comment by ShimotsukiH** [comment]
谢谢~~

DIYgod <notifications@github.com>于2018年6月13日周三 上午11:26写道：

**Comment by ShimotsukiH** [comment]
![image](https://user-images.githubusercontent.com/33424662/41836082-3fcc0604-788c-11e8-82e9-02ffc0daf7a4.png)
您好 我吧这个过滤规则用在微博上 出来的结果还是带各种转发呢?

**Comment by nageshuizeii** [comment]
因为这是推特的标准转发格式，微博是不存在标准转发的

**Comment by ShimotsukiH** [comment]
那我应该用“//”代替“RT  ”是不是也能过滤转发？ 还是说有别的在微博过滤非原创内容的方法？

nageshuizeii <notifications@github.com>于2018年6月25日周一 下午4:07写道：
