### ISSUE TITLE
请问可以有tumblr 的rss么？

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#295]
RT 
顺带一提 p站的rss好像坏了？

**Comment by ShimotsukiH** [comment]
http://ni02.tumblr.com/ ←有的画师主要用tumblr来更新……

**Comment by wydwww** [comment]
http://ni02.tumblr.com/rss

Tumblr 本身就支持 RSS

**Comment by ShimotsukiH** [comment]
大 大意了~

那 请问 pixiv那边是怎么了……今天上午rss不了任何人 日排行也不工作了……

Yiding <notifications@github.com> 于2018年6月13日周三 下午9:04写道：

**Comment by DIYgod** [comment]
部署问题，已修复
