### ISSUE TITLE
Bilibili投稿内容支持输出为html5播放器链接

### ISSUE THREAD

**Issue by jiansing** [DIYgod/RSSHub#2964]
### 网站地址
https://www.bilibili.com/
### 网站描述
哔哩哔哩弹幕网
### 需要生成什么内容？

- [ ] up投稿内容输出为html5播放器链接

### 额外描述
如
https://www.bilibili.com/video/av63194546/
的html5链接为
https://player.bilibili.com/player.html?aid=63194546&cid=109744733&page=1

**Comment by SettingDust** [comment]
@jiansing 功用？

**Comment by jiansing** [comment]
简化看视频的过程
原来的过程是：1.点击阅读器的项目 2 .跳转网页视图 3.跳转客户端（这里有时候还要手动跳转）
现在：1.点击阅读器的项目 2 .跳转网页视图并播放

**Comment by SettingDust** [comment]
@jiansing https://api.bilibili.com/x/player/pagelist?aid=60225694
可请求到cid，等一个有缘人，记得缓存（

**Comment by DIYgod** [comment]
@jiansing 对PC端来说跳转单独播放器页肯定是不能接受的，播放页样式更舒服还包括评论等内容
移动端跳转客户端不是必须的，而且网页体验远不如客户端，所以不觉得是个好办法
