### ISSUE TITLE
希望添加 github 用户的 stars

### ISSUE THREAD

**Issue by guanguans** [DIYgod/RSSHub#2968]
### 网站地址

https://github.com/:user?tab=stars

eg：

https://github.com/DIYgod?tab=stars

### 需要生成什么内容？

- [ ] star 的仓库名
- [ ] star 的仓库描述
- [ ] star 的仓库语言类型
- [ ] star 的仓库stars数

### 额外描述

可参考仓库的这些信息

![image](https://user-images.githubusercontent.com/22309277/64061771-abc78200-cc11-11e9-809c-e53cb384827b.png)

**Comment by LanceZhu** [comment]
已经添加了 [传送门](https://docs.rsshub.app/programming.html#用户-starred-repositories)

**Comment by guanguans** [comment]
@LanceZhu 谢谢 ❤️

**Comment by guanguans** [comment]
@LanceZhu @DIYgod 报错了，可否查看下什么问题。

![image](https://user-images.githubusercontent.com/22309277/65228932-f005be00-dafd-11e9-9f9a-dc299fc8bd93.png)
