### ISSUE TITLE
Protect

### ISSUE THREAD

**Issue by Bottleface** [DIYgod/RSSHub#2971]
### What feature is it?
The ability to put all paths behind basic authentication.

### What problem does this feature solve?
I would like to run this on a server on my network but expose it to the outside world.  I don't want any one to be able to use this instance of RSSHub, so I would like to put basic auth on every path.

### Additional description
I thought that this would already be possible because of the [protected routes feature](https://docs.rsshub.app/en/install/#user-authentication) but I can't seem to make it work.  Perhaps this is more of a question that a feature request, I don't know.  I'm not familiar with koa-router, so maybe I'm just doing it wrong.

![image](https://user-images.githubusercontent.com/9113058/64068446-7876fa00-cbf5-11e9-8600-7d567e7dbc9b.png)

To me the line shown above would indicate that all routes require basic auth, but that isn't happening.  I can access all routes without auth.  Is this a bug or am I doing something wrong?  Guessing the latter.

**Comment by HenryQW** [comment]
@Bottleface Basic auth will only work with the client sending the authentication fields in request header. It seems to be broken for a while. See https://github.com/DIYgod/RSSHub/issues/2668#issuecomment-525972301

**Comment by Bottleface** [comment]
@HenryQW Thank you for answering so quickly, that's what I was afraid of.  I saw [#2668](https://github.com/DIYgod/RSSHub/issues/2668#issuecomment-525972301) but I think the meaning was lost in translation.  I will monitor for a fix.  I will likely just leave the auth open for now and monitor traffic closely.  Thank you.

**Comment by bordusko** [comment]
Any updates about this auth problem? I'm looking for a fix too...

**Comment by DIYgod** [comment]
Maybe we should make a env configuration

**Comment by HenryQW** [comment]
@bordusko 

There is no fix for this atm, I guess rss isn't really designed with auth in mind. If the client(your rss reader) does not send the authorization fields there is no way for basic auth to authenticate, not I'm aware of.

**Comment by bordusko** [comment]
> I've translated my comment in [#2668 (comment)](https://github.com/DIYgod/RSSHub/issues/2668#issuecomment-525972301)
> with a test case using Postman.

Ok, thanks for the answer.

**Comment by lardissone** [comment]
One way to "fix" this would be to obscure server a little, hiding the homepage and using a custom hash in the URLs. Something like: `domain.com/WdgN0zid3hOKQrkhsfN9/instagram/user/nytimes`. 
It's not secure, but at least it's harder to guess.

**Comment by HenryQW** [comment]
Or maybe use a parameter-based approach `domain.com/instagram/user/nytimes?key=WdgN0zid3hOKQrkhsfN9`, the simplest way I can think of to implement is to use a static key defined in env, since RSSHub already has a list of parameters working that way.

**Comment by rbelem** [comment]
Hi Everyone,
I added a HTTP Basic authentication through traefik and here are my changes to the docker-compose.yml

```
From cec8bc56a7f6a1712d305c85921c4eb7fa835064 Mon Sep 17 00:00:00 2001
From: Rodrigo Belem <me@rclb.dev>
Date: Sun, 3 May 2020 20:44:46 +0000
Subject: [PATCH] Enable traefik with basicauth

---
 docker-compose.yml | 38 +++++++++++++++++++++++++++++++++++---
 1 file changed, 35 insertions(+), 3 deletions(-)

diff --git a/docker-compose.yml b/docker-compose.yml
index 238c7e35..b941192d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -4,6 +4,19 @@ services:
     rsshub:
         image: diygod/rsshub
         restart: always
+        labels:
+            - "traefik.enable=true"
+            - "traefik.http.services.webapp.loadbalancer.server.port=1200"
+            - "traefik.http.routers.webapp-web.rule=Host(`${WEBAPP_HOST}`)"
+            - "traefik.http.routers.webapp-web.entrypoints=web"
+            - "traefik.http.routers.webapp-web.middlewares=traefik-redirectscheme"
+            - "traefik.http.middlewares.traefik-redirectscheme.redirectscheme.scheme=https"
+            - "traefik.http.routers.webapp-websecure.rule=Host(`${WEBAPP_HOST}`)"
+            - "traefik.http.routers.webapp-websecure.entrypoints=websecure"
+            - "traefik.http.routers.webapp-websecure.tls=true"
+            - "traefik.http.routers.webapp-websecure.tls.certresolver=le"
+            - "traefik.http.routers.webapp-websecure.middlewares=traefik-auth"
+            - "traefik.http.middlewares.traefik-auth.basicauth.users=username:$$htpasswd"
         ports:
             - '1200:1200'
         environment:
@@ -23,7 +36,26 @@ services:
         image: redis:alpine
         restart: always
         volumes:
-            - redis-data:/data
+            - /srv/rsshub/data/redis:/data
 
-volumes:
-    redis-data:
+    traefik:
+      image: "traefik:v2.2"
+      container_name: "traefik"
+      command:
+        - "--api.insecure=true"
+        - "--providers.docker=true"
+        - "--providers.docker.exposedbydefault=false"
+        - "--entrypoints.web.address=:80"
+        - "--entrypoints.websecure.address=:443"
+        - "--certificatesresolvers.le.acme.httpchallenge=${ACME_ENABLE}"
+        - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
+        - "--certificatesresolvers.le.acme.email=${ACME_EMAIL}"
+        - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
+      ports:
+        - "80:80"
+        - "443:443"
+        - "8080:8080"
+      restart: always
+      volumes:
+        - "${ACME_STORAGE_PATH}:/letsencrypt"
+        - "/var/run/docker.sock:/var/run/docker.sock:ro"
-- 
2.25.1
```

And the password I generated using this oneliner
```
echo $(htpasswd -nbB myusername "mypassword") | sed -e s/\\$/\\$\\$/g
```

Hope this help some lost souls :sweat_smile:

**Comment by HenryQW** [comment]
@rbelem does that work well in RSS readers like TTRSS, Reeder, etc. ?

**Comment by rbelem** [comment]
@HenryQW, yep! I'm using it with newsblur and tested with liferea as well.
