### ISSUE TITLE
Question - Other scrappers

### ISSUE THREAD

**Issue by PeterPorzuczek** [DIYgod/RSSHub#2976]
Hi,

My question is:
Can we use other libs to scrape data like [`scrape-it`](https://www.npmjs.com/package/scrape-it) instead of `cheerio`? Will it work and could it be approved in pull request?

Also it would be cool if you could create template for questions. Great project :)

**Comment by HenryQW** [comment]
It’s definitely a great library to use, however I personally think it would add another dependency and also increase the maintenance complexity. I think cheerio provides more flexibility in this case, many websites require complicated logics to scrap.

Please do not hesitate to submit PRs, we do need more English routes to improve RSSHub’s exposure and usability to non-Chinese users.

**Comment by PeterPorzuczek** [comment]
Good, thanks for quick reply :)

**Comment by HenryQW** [comment]
@HenryQW There is something similar to what scrap-it does, you might want to take a look. It would be interesting to see how scrap-it can achieve the similar functionality, we can definitely use that as it doesn’t require the level of flexibility in site-specific routes.
https://github.com/DIYgod/RSSHub/blob/master/lib/utils/common-config.js

**Comment by SettingDust** [comment]
@PeterPorzuczek It's a configurable route. There is a demo https://github.com/DIYgod/RSSHub/blob/master/lib/routes/uraaka-joshi/
