### ISSUE TITLE
Pixiv 获取错误

### ISSUE THREAD

**Issue by Quorafind** [DIYgod/RSSHub#2982]
### 路由地址
https://rsshub.app/pixiv/ranking/day
### 预期是什么？
获取当日排行榜的图片的链接
### 实际发生了什么？
pixiv not login

**Comment by SettingDust** [comment]
@Quorafind 阅读文档 自行关闭issue

**Comment by DIYgod** [comment]
https://github.com/upbit/pixivpy/issues/83

**Comment by DaRealFreak** [comment]
X-Client-Time and X-Client-Hash header are now required and validated server side
X-Client-Time: RFC3339 converted timestamp
X-Client-Hash: md5([X-Client_Time]+28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c)

so f.e. with X-Client-Time: 2019-09-02T20:51:57+02:00
the X-Client-Hash is: md5(2019-09-02T20:51:57+02:0028c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c)
--> 5bb0b1ec0b6e1a86d7dc18dbea2c80bf

the authentication works with these headers as usual, other values didn't get any additional validation

**Comment by DIYgod** [comment]
@DaRealFreak Updated in ac801640997c09ed33016f44782cb387d0b2200d, thanks!
