### ISSUE TITLE
类似于bilibili 的视频更新是否可以支持iPhone的播客

### ISSUE THREAD

**Issue by gh02817560** [DIYgod/RSSHub#2985]
### 这是一个什么样的功能？
类似于bilibili网站的视频更新是否可以支持iOS的播客
### 这个功能可以解决什么问题？
大部分RSS阅读器都是针对文字阅读进行开发的，视频类的推送还要跳转一下页面，体验不是很好

现有的RSS比较好的APP类似快知（个人认为）不支持历史发布的抓取
### 额外描述
iOS上的播客要是能追视频更新的话那边是极极极极极极极极极极极好的呢，终于不用看广告和人工智障推荐啦，世界就安静了

**Comment by DIYgod** [comment]
播客不是只能播音频么..

**Comment by gh02817560** [comment]
> 播客不是只能播音频么..

不是的 ，播客是支持视频的，昨天还在上面看了一个苹果的视频

**Comment by gh02817560** [comment]
> 播客不是只能播音频么..

https://podcasts.apple.com/cn/podcast/apple-keynotes-1080p/id509310064

**Comment by DIYgod** [comment]
学到了...
但是解析视频直链成本很高而且风险很大，暂不考虑

没有弹幕的 bilibili 也没有灵魂
