### ISSUE TITLE
enhance: 支持任意rss源获取全文

### ISSUE THREAD

**Issue by kt286** [DIYgod/RSSHub#2993]
### 这是一个什么样的功能？
支持任意rss源获取全文

### 这个功能可以解决什么问题？
之前有不少issue都是想要获取现有RSS全文的，这个功能可以堵住他们的嘴

### 额外描述
路由类似
/fulltext/:rssaddress?mode=fulltext

**Comment by yefoenix** [comment]
@kt286 这不是rsshub该做的……

**Comment by yefoenix** [comment]
@kt286 想要全文自己搭Mercury就好了，支持这功能会让Demo服务器爆掉的。

**Comment by kt286** [comment]
可以写好路由  加个开关  demo不开，叫他们自建

**Comment by DIYgod** [comment]
https://docs.rsshub.app/parameter.html#quan-wen-shu-chu
