### ISSUE TITLE
[Bug Report] Redirecting to Google Error 404 page when subscribing new Instagram feed

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#2994]
### Involved route
Instagram User

### What is expected?
Subscribing Instagram User Feed successfully.

### What is actually happening?
Adding Instagram User Feed, it redirects to google 404 page.

### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### Additional info (logs errors etc)
rss feed url: [diygod](https://rsshub.app/instagram/user/diygod)

![image](https://user-images.githubusercontent.com/10363328/64224441-16c2d280-cf0a-11e9-9eec-6c478121ab53.png)

**Comment by riley-martine** [comment]
+1 - existing feeds also broken

**Comment by DIYgod** [comment]
It's because `rsshub.app/instagram/*` was forwarded to `google.com/404` temporarily, now the forwarding is canceled.

BTW, Instagram routes have very worse usability for Instagram's strict anti-crawler policy.
