### ISSUE TITLE
重磅原创-每经网

### ISSUE THREAD

**Issue by Newmanpan** [DIYgod/RSSHub#2998]
### 网站地址
http://www.nbd.com.cn/columns/332
### 网站描述
新闻决定影响力，国内最具影响力的主流财经全媒体之一
### 需要生成什么内容？

- [ ] 内容一 标题
- [ ] 内容二 全文
- [ ] 内容二 发布时间

### 额外描述
希望此RSS能:
1. 使用通用参数-内容过滤的"?filter="
2. 能通过W3C验证，以便给IFTTT/ZAPIER/BLOGTROTTR等自动化协作平台使用，W3C验证网址：https://validator.w3.org/feed/

非常感谢！！！

**Comment by lisxray** [comment]
Closed by #3197
