### ISSUE TITLE
当请求对应的数据源不存在时，不应该返回 500 状态码 ，而应该返回 404 状态码

### ISSUE THREAD

**Issue by benpigchu** [DIYgod/RSSHub#30]
比如： https://rss.now.sh/zhihu/zhuanlan/donotexist 返回的状态码是 500，尽管从报错内容来看是因为原专栏不存在

**Comment by DIYgod** [comment]
暂时不太好处理，现在是内部错误都会返回 500，因为不好判断是数据不存在 还是 抓取失败 还是 抓取脚本出了 bug

issue 可以保持 open
