### ISSUE TITLE
类似dedecms这类的论坛系统有什么好的抓取思路？

### ISSUE THREAD

**Issue by shishuo365** [DIYgod/RSSHub#3005]
### 网站地址
http://www.rosoo.net/

### 网站描述
专业的音视频内容博客

### 需要生成什么内容？

- [ ] 音视频技术频道文章订阅 http://www.rosoo.net/a/index_av.html
- [ ] 音视频编解码栏目文章订阅 http://www.rosoo.net/a/list_53_1.html

### 额外描述
主要是征集讨论一下好的抓取思路，其他网站有api接口的相对比较简单，CMS是直接输出内容，感觉上有点麻烦，因为不太了解CMS内部的工作原理

**Comment by yefoenix** [comment]
@shishuo365 RTFM https://docs.rsshub.app/joinus/#%E6%AD%A5%E9%AA%A4-1-%E7%BC%96%E5%86%99%E8%84%9A%E6%9C%AC

**Comment by shishuo365** [comment]
方法可行，感谢
