### ISSUE TITLE
需求 金色财经 7*24快讯

### ISSUE THREAD

**Issue by wskxjtzq** [DIYgod/RSSHub#3007]
网站地址
https://www.jinse.com/lives

网站描述
这是区块链行业的核心媒体，该页面展示行业即时快讯。

需要生成内容
需要快讯的标题，内容，以及链接。

额外描述
不是普通的HTML网页，内容是JS生成的，需要技术水平才能行。

**Comment by SettingDust** [comment]
@wskxjtzq https://api.jinse.com/v4/live/list?limit=20&reading=false&source=web&sort=&flag=down&id=0

**Comment by hillerliao** [comment]
前一阵子加了 巴比特 快讯，和 金色财经 比，哪家的快讯更好？

**Comment by KwToPA** [comment]
> 前一阵子加了 巴比特 快讯，和 金色财经 比，哪家的快讯更好？

大鸽，A股的快讯有兴趣吗？ 这个 https://github.com/DIYgod/RSSHub/issues/2840

**Comment by wskxjtzq** [comment]
> https://api.jinse.com/v4/live/list?limit=20
> 
> 另：这样才容易

谢谢你，但这解出来的字，好像还得继续处理。用什么办法处理啊？
[],"created_at":1585116080,"attribute":"","up_counts":50,"down_counts":28,"zan_status":"","readings":[],"extra_type":0,"extra":null,"prev":null,"next":null,"word_blocks":[{"type":"coin","data":{"symbol":"ETC","slug":"ethereum-classic","change_24h":0.00900867}}],"is_show_comment":1,"is_forbid_comment":0,"comment_count":0,"analyst_user":null},{"id":156169,"content":"\u3010BTC\u7a81\u78346700\u7f8e\u5143\u3011\u706b\u5e01\u5168\u7403\u7ad9\u6570\u636e\u663e\u793a\uff0cBTC\u77ed\u7ebf\u4e0a\u6da8\uff0c\u7a81\u78346700\u7f8e\u5143\u5173\u53e3\uff0c\u73b0\u62a56704\u7f8e\u5143\uff0c\u65e5\u5185\u6da8\u5e451.71%\uff0c\u884c\u60c5\u6ce2\u52a8\u8f83\u5927\uff0c\u8bf7\u505a\u597d\u98ce\u9669\u63a7\u5236\u3002","content_prefix":null,"link_name":"","link":"","grade":5,"sort":"","highlight_color":"","images":
