### ISSUE TITLE
微博rss输出可以出一版title为空的吗？

### ISSUE THREAD

**Issue by gyppk** [DIYgod/RSSHub#301]
微博输出标题和概述是重复的 输出的时候出现重复情况 
所以可以做一个版本可以自动将titile输出为空或者一个空格 的版本吗？

例如：【转发了ING直播的微博：【直击#高考首日南方台风...】转发了ING直播的微博：【直击#高考首日南方台风北方高温# 】#高考#首日华北、黄淮一带将出现35-38℃、局地40℃的高温天气。广东、广西、海南等地考生将面临7-8级、局地10… O网页链接 ​​​​

**Comment by Ir1d** [comment]
title为空的话阅读器里面还能点进去不？

**Comment by DIYgod** [comment]
建议调整输出格式
