### ISSUE TITLE
代码小白部署了 没看懂配置

### ISSUE THREAD

**Issue by Jeason0228** [DIYgod/RSSHub#3012]
### 路由地址
随意访问了 http://127.0.0.1:1200/lib/routes/3dm/game.js
### 实际发生了什么？
Error: wrong path
    at module.exports (C:\Users\jeason\RSSHub\lib\middleware\parameter.js:10:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
### 部署相关信息
http://127.0.0.1:1200/

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |         win      |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![企业微信截图_20190906172135](https://user-images.githubusercontent.com/44083849/64417022-e5453500-d0ca-11e9-8e40-d66e1aeee3c6.png)

**Comment by kt286** [comment]
这不是看不懂配置 这是看不懂人话

**Comment by Jeason0228** [comment]
> 这不是看不懂配置 这是看不懂人话

我不是学代码的，但是我想参考下已有的rss 去改一个自己的，可能吗？
我装了git，node，然后npm克隆了仓库到本地，start运行， http://127.0.0.1:1200/可以访问。
接着我就不知道该怎么去本地测试?
我按照添加配置 只添加了那两行。 但是不知道在**哪个文件**里面 替换掉所有的路由指向本地？

**Comment by kt286** [comment]
例如这个
![image](https://user-images.githubusercontent.com/10684972/64417647-17a36200-d0cc-11e9-840b-6cd97d28512b.png)

demo的    https://rsshub.app/github/repos/DIYgod 
替换了以后
你自己的  http://127.0.0.1:1200/github/repos/DIYgod

很难理解么

**Comment by Jeason0228** [comment]
不难理解。。但是我访问http://127.0.0.1:1200/github/repos/DIYgod 这个的时候 就会报错

Error: wrong path
at module.exports (C:\Users\jeason\RSSHub\lib\middleware\parameter.js:10:15)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Jeason0228** [comment]
![企业微信截图_20190906173838](https://user-images.githubusercontent.com/44083849/64418235-30604780-d0cd-11e9-94c1-4266331fb310.png)

**Comment by Jeason0228** [comment]
tunneling socket could not be established, cause=write EPROTO 37996:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by DIYgod** [comment]
看起来是网络问题，请确认是否可以访问目标网站

提交路由需要代码基础，请参考文档：https://docs.rsshub.app/joinus

issue 将被关闭
