### ISSUE TITLE
雪球专栏

### ISSUE THREAD

**Issue by yiwiz** [DIYgod/RSSHub#3019]
### 网站地址
https://xueqiu.com

### 网站描述
投资信息平台

### 需要生成什么内容？

- [ ] 雪球用户的专栏文章

### 额外描述
rsshub已经提供了雪球的一些信息支持了，但是专栏文章似乎还没有，希望能支持

**Comment by SettingDust** [comment]
> ### 网站地址
> https://xueqiu.com
> 
> ### 网站描述
> 投资信息平台
> 
> ### 需要生成什么内容？
> * [ ]  雪球用户的专栏文章
> 
> ### 额外描述
> rsshub已经提供了雪球的一些信息支持了，但是专栏文章似乎还没有，希望能支持

请提供专栏链接，给出例子

**Comment by yiwiz** [comment]
@SettingDust 
比如，这个是用户
https://xueqiu.com/u/9962554712
这个是它的专栏
https://xueqiu.com/9962554712/column
目前是一个用户只能有一个专栏

**Comment by SettingDust** [comment]
@yiwiz https://xueqiu.com/statuses/original/timeline.json?user_id=9962554712

**Comment by yiwiz** [comment]
@SettingDust 爬虫当然是可以爬的，如果rss hub支持就最好了。

**Comment by SettingDust** [comment]
@yiwiz 我只是提供api，方便别人写

**Comment by hillerliao** [comment]
可以用 user 那个的 长文 筛选条件，得到的结果基本差不多。

**Comment by yiwiz** [comment]
@hillerliao , 你说的是/xueqiu/user/:id/:type?吧，结果差很多，任何发的言论都会出现在这个链接中，会有很多噪音

**Comment by hillerliao** [comment]
@yiwiz 你把type设置为2

**Comment by yiwiz** [comment]
@hillerliao type设置为2后，效果好了不少，多谢！
