### ISSUE TITLE
The Batch, a new weekly newsletter from deeplearning.ai

### ISSUE THREAD

**Issue by wydwww** [DIYgod/RSSHub#3023]
### Website URL
https://www.deeplearning.ai/thebatch/
### Website description
Welcome to The Batch, a new weekly newsletter from deeplearning.ai! The Batch presents the most important AI events and perspective in a curated, easy-to-read report for engineers and business leaders. Every Wednesday, The Batch highlights a mix of the most practical research papers, industry-shaping applications, and high-impact business news.
### What content should be included?

- [ ] The weekly newsletter

**Comment by SettingDust** [comment]
https://www.deeplearning.ai/WPCore/wp-admin/admin-ajax.php?action=hubspot_reader_the_batch&offset=0&limit=5

**Comment by NightMachinary** [comment]
Has the URL stopped working?
