### ISSUE TITLE
有赞店铺路由 Channel Title 的两个Bug

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3027]
### 路由地址
例子：https://rsshub.app/youzan/goods/13328377
### 预期是什么？
Channel Title 在一行内显示，不换行；
Channel Title 为店铺名称；
### 实际发生了什么？
Channel Title 有折行
抓取了店铺的促销
### 部署相关信息
DEMO
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/8215230/64497772-6840d800-d2e3-11e9-88c6-21647a173f29.png)

**Comment by kt286** [comment]
![image](https://user-images.githubusercontent.com/10684972/64500650-a42e6a00-d2f0-11e9-89e3-213c1983a302.png)

这样的？？

**Comment by yefoenix** [comment]
@kt286 是的，店铺的正确名称是「企鹅市集」

**Comment by kt286** [comment]
不想截字符串了  最终效果是这样

![image](https://user-images.githubusercontent.com/10684972/64501111-91b53000-d2f2-11e9-9848-9360d1078ad2.png)
