### ISSUE TITLE
豆瓣发现的失效

### ISSUE THREAD

**Issue by suance** [DIYgod/RSSHub#3033]
### 路由地址
https://rsshub.app/douban/explore/column/2

### 实际发生了什么？
Looks like something went wrong

### 补充
貌似现在启用了新的域名
以豆瓣发现--旅游，为例：
https://www.douban.com/channel/30169152/

**Comment by DIYgod** [comment]
无法复现问题

**Comment by yefoenix** [comment]
@DIYgod 我看了一下，明白了他的意思
之前豆瓣发现板块 https://www.douban.com/explore/
对于「旅行」的内容有一个专门的子页面 https://www.douban.com/explore/column/2
但是现在发现页的「旅行」入口直接指向了 https://www.douban.com/channel/30169152 这个频道页面，原来的 column  链接我不确定还有没有更新。
所以现在我去提一个豆瓣豆瓣频道的 rss Request issue

**Comment by suance** [comment]
> 无法复现问题

感觉这个是时灵时不灵，确实如 @yefoenix 所说，我也不知道现在column是否还在更新

![捕获](https://user-images.githubusercontent.com/46291489/64512556-45c9b180-d319-11e9-8a4c-fcc064683f0b.JPG)
