### ISSUE TITLE
【RSS需求】品途网一个优质内容网站

### ISSUE THREAD

**Issue by restofworld** [DIYgod/RSSHub#3035]
### 网站地址
www.pintu360.com
### 网站描述
品途商业评论是深扎智能科技,文娱,新零售,新消费,创业投资,大健康等创新产业的评论型媒体,是新经济,新商业,新产业的风向标;致力用媒体激发产业创新,赋能相关产业。
### 需要生成什么内容？

- [ ] 推荐文章
- [ ] 各个的产业的文章（该网站是按照产业不同划分内容的）
- [ ] 智库下面的内容

**Comment by DIYgod** [comment]
Done. 2ae32eac80309fe48dfbb7dfc5db093f4b59d71c

智库基本都是年更，RSS 貌似没什么必要
