### ISSUE TITLE
【/cninfo/announcement/】Bug Report——filter_title传递失败

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3038]
### 路由地址
/cninfo/announcement/   公司公告-A 股港股
### 预期是什么？
filter_title能够正常传递
### 实际发生了什么？
传递失败，详见额外信息
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |         centos7       |
| Node version       |    10.17           |
| if Docker, version |               |

### 额外信息（日志、报错等）

路由 /cninfo/announcement/all 

https://rsshub.app 反馈 Application error，自建成功，但搜索 ```年度权益分派实施公告``` 失败。

巨潮资讯上搜 对应关键词可以搜到内容，[年度权益分派实施公告](http://www.cninfo.com.cn/new/fulltextSearch?keyWord=%E5%B9%B4%E5%BA%A6%E6%9D%83%E7%9B%8A%E5%88%86%E6%B4%BE%E5%AE%9E%E6%96%BD%E5%85%AC%E5%91%8A&sortName=pubdate&sortType=desc)

自建 ```/cninfo/announcement/all?filter_title=年度权益分派实施公告``` ，反馈
```最新-公告-巨潮资讯 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)```

似乎没搜到内容。

---

### 谢谢

**Comment by KwToPA** [comment]
机器人有问题，但搜索 后面的内容 消失

```
年度权益分派实施公告 失败。
```

**Comment by kt286** [comment]
![image](https://user-images.githubusercontent.com/10684972/64598230-f56e5480-d3e9-11e9-8608-ac0b06649ce1.png)

**Comment by kt286** [comment]
你是不是误会 `filter_title` 的含义了

**Comment by KwToPA** [comment]
> 你是不是误会 `filter_title` 的含义了

filter_title: 过滤标题 , 查看一楼的[官方链接](http://www.cninfo.com.cn/new/fulltextSearch?keyWord=%E5%B9%B4%E5%BA%A6%E6%9D%83%E7%9B%8A%E5%88%86%E6%B4%BE%E5%AE%9E%E6%96%BD%E5%85%AC%E5%91%8A&sortName=pubdate&sortType=desc) 反馈的搜索结果，标题中包含 关键字 ```年度权益分派实施公告```，例如 ```凯乐科技：2018年年度权益分派实施公告```

请问你能否在rsshub.app 上搜到 ```年度权益分派实施公告``` ？

我自建，路由 .../all 在chrome上这样 

[https://i.imgur.com/zarFKCz.png](https://i.imgur.com/zarFKCz.png)

但一加filter_title 就什么都搜不到，没有<item> <title> 这部分

**Comment by KwToPA** [comment]
更新：青山纸业搜不到，但  .../all 最前的内容可以搜到，比如最新一条是 ```华能国际: 关于超短期融资券发行的公告``` ，那么``` /cninfo/announcement/all?filter_title=华能国际 ``` 可以搜到

前文```凯乐科技：2018年年度权益分派实施公告``` 发布时间是2019-08-22

**Comment by KwToPA** [comment]
机器人会丢失 夹在第一个引用符号和倒数第二个之间的所有内容，只剩下最后一个引用符号中的内容

**Comment by DIYgod** [comment]
filter_title 只是对 RSS 内容过滤，不是对源站所有文章过滤

**Comment by KwToPA** [comment]
> filter_title 只是对 RSS 内容过滤，不是对源站所有文章过滤

明白，那我订阅这个，到2020年分红的时候，估计能推送19年的年度权益分派实施公告
