### ISSUE TITLE
请求增加 码农周刊 & issue templates

### ISSUE THREAD

**Issue by lzsdodo** [DIYgod/RSSHub#304]
1. 请求增加订阅源 [码农周刊](https://weekly.manong.io/)，目前仅支持邮件订阅。
    - 诸如此类，转换邮件订阅成 RSS 源。
2. 可以增加 issue templates 放在根目录的 `.github` 上，规范 issue 提交格式，[参考模板](https://github.com/stevemao/github-issue-templates)。

**Comment by HenryQW** [comment]
都看这玩意了还不自己把轮子补齐了

**Comment by lzsdodo** [comment]
实话说我自己是写了一个 py 版本的，直接调 gmail api 提取邮件内容然后直接生成就好，基本所有邮件订阅只要不提供 rss 都可以这么干了。就是没有计划投入时间去学 js。当然你们可以根据我的源码改一下补充到 rsshub 上就更好了。我再稍微再改改这周末发上来。

**Comment by DIYgod** [comment]
感觉转换这个页面就行了 https://weekly.manong.io/issues/

全文就是每期内容

**Comment by HenryQW** [comment]
可以尝试用 mercury 提取全文，成功率不是100🤪

**Comment by HenryQW** [comment]
目标网站证书链不全（目测没有指向 fullchain），详见：
https://www.ssllabs.com/ssltest/analyze.html?d=weekly.manong.io

导致 nodejs 无法验证证书：
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
```

联系下站长吧。

自行部署 RSSHub 可以通过关闭 SSL 验证来完成请求 `npm config set strict-ssl false`.

代码见：https://github.com/HenryQW/RSSHub/tree/route/manong

**Comment by HenryQW** [comment]
@DIYgod pls close this.

**Comment by CoderTonyChan** [comment]
访问这个网站https://vol.moe/list/all,all,all,lastupdate,all,all,none/
同样有这个问题 是因为我在开发模式下吗?
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
```

**Comment by HenryQW** [comment]
> 访问这个网站[vol.moe/list/all,all,all,lastupdate,all,all,none](https://vol.moe/list/all,all,all,lastupdate,all,all,none/)
> 同样有这个问题 是因为我在开发模式下吗?
> 
> ```
> Error: unable to verify the first certificate
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
>     at TLSSocket.emit (events.js:182:13)
>     at TLSSocket.EventEmitter.emit (domain.js:442:20)
>     at TLSSocket._finishInit (_tls_wrap.js:628:8)
> ```

看楼上 https://github.com/DIYgod/RSSHub/issues/304#issuecomment-416678710

**Comment by CoderTonyChan** [comment]
> > 访问这个网站[vol.moe/list/all,all,all,lastupdate,all,all,none](https://vol.moe/list/all,all,all,lastupdate,all,all,none/)
> > 同样有这个问题 是因为我在开发模式下吗?
> > ```
> > Error: unable to verify the first certificate
> >     at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
> >     at TLSSocket.emit (events.js:182:13)
> >     at TLSSocket.EventEmitter.emit (domain.js:442:20)
> >     at TLSSocket._finishInit (_tls_wrap.js:628:8)
> > ```
> 
> 看楼上 [#304 (comment)](https://github.com/DIYgod/RSSHub/issues/304#issuecomment-416678710)

我有看那个网站的报告
![image](https://user-images.githubusercontent.com/16996753/52684997-16211980-2f83-11e9-9bcf-2c05a95a7233.png)
但是还是不明白网站证书链不全 
然后代码是403

**Comment by HenryQW** [comment]
我猜测站长配置服务器的时候，直接把 chain 当成了证书，而没使用 cert。

对安全没要求的话，设置环境变量 NODE_TLS_REJECT_UNAUTHORIZED = 0 可以绕过这个问题
