### ISSUE TITLE
优恪网 OKOer RSS wanted

### ISSUE THREAD

**Issue by wydwww** [DIYgod/RSSHub#305]
https://www.okoer.com
https://www.okoer.com/about

优恪网隶属于北京优恪科技有限公司。由传媒人罗昌平带领新锐互联网团队于 2014 年组建，优恪品牌源于德国独立测评机构 ÖKO-TEST，是国际消费者研究与测试机构（ICRT）成员，由数十家经德国认证认可委员会（DAkkS）认可的第三方实验室提供科学支持，北京优恪科技有限公司负责运营。

**Comment by kn007** [comment]
意义不明，建议关闭

**Comment by DIYgod** [comment]
长时间无 pr，issue 暂时关闭
