### ISSUE TITLE
【/cctv/china】Bug Report——央视新闻0905起改版了，4日之后的都推送失败

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3050]
### 路由地址
/cctv/china
### 预期是什么？
正常推送
### 实际发生了什么？
央视新闻0905起改版了，4日之后的都推送失败
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |          centos7     |
| Node version       |    10.17           |
| if Docker, version |               |

### 额外信息（日志、报错等）
无

**Comment by KwToPA** [comment]
@idealclover @xyqfer

**Comment by yefoenix** [comment]
@KwToPA @这两位是什么意思？

**Comment by KwToPA** [comment]
> @KwToPA @这两位是什么意思？

这边 https://docs.rsshub.app/traditional-media.html#%E4%B8%93%E9%A2%98  写了作者，我就试试能不能把这个问题提交给作者

**Comment by yefoenix** [comment]
@KwToPA 你可以考虑赞助项目或附上一张你自己的女装照来获得更快的 issue 响应速度。
