### ISSUE TITLE
求蜻蜓FM的内容需求

### ISSUE THREAD

**Issue by gh02817560** [DIYgod/RSSHub#3057]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3057)

### 网站地址
https://www.qingting.fm/
### 网站描述
类似于喜马拉雅的音频网站
### 需要生成什么内容？
支持iOS播客订阅的RSS内容
- [ ] 内容一
- [ ] 内容二

### 额外描述

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($1.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by slowmande** [comment]
+1

**Comment by springspace** [comment]
+1

**Comment by Shane-Meng** [comment]
蜻蜓很多的源是独有的，希望能制作一个

**Comment by yefoenix** [comment]
对于频道 https://www.qingting.fm/channels/222320/
其 api 为 
https://i.qingting.fm/capi/channel/222320/programs/20178d487ed5fe5014b39eec2e20b204?curpage=1&pagesize=30&order=asc

20178d487ed5fe5014b39eec2e20b204 这一段不知是怎么来的以及是否固定

**Comment by Maecenas** [comment]
> 对于频道 https://www.qingting.fm/channels/222320/
> 其 api 为
> https://i.qingting.fm/capi/channel/222320/programs/20178d487ed5fe5014b39eec2e20b204?curpage=1&pagesize=30&order=asc
> 
> 20178d487ed5fe5014b39eec2e20b204 这一段不知是怎么来的以及是否固定

API返回值中这一字段是 `$.data.version`，应该不是固定的。可以从 `https://i.qingting.fm/capi/v3/channel/${id}` 返回值中的 `$.data.v` 中取得。

**Comment by yefoenix** [comment]
严格说的话这个 issue 还没完成，目前输出的只是普通feed，不是 podcast 格式。
@DIYgod

**Comment by TonyRL** [comment]
#11061
