### ISSUE TITLE
【RSS 需求】小红书用户动态路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3080]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3080)

### 网站地址
https://www.xiaohongshu.com/
### 网站描述
小红书是年轻人的生活方式平台和消费决策入口，由毛文超和瞿芳于 2013 年在上海创立，致力于让全世界的好生活触手可及。
### 需要生成什么内容？
- [ ] 用户笔记 例：https://www.xiaohongshu.com/user/profile/593032945e87e77791e03696
- [ ] 用户收藏专辑 例：https://www.xiaohongshu.com/board/5db6f79200000000020032df
### 额外描述
小红书还活着……

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($5.00)

### Submitted pull Requests
- [#4162 fix: #3080 【RSS 需求】小红书用户动态路由需求](https://issuehunt.io/r/DIYgod/RSSHub/pull/4162)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by xyqfer** [comment]
话说我点开上面两个链接就遇到滑块验证了...

**Comment by yefoenix** [comment]
@xyqfer 这么狠吗😂
我倒是还没遇到过，不知跟 referer 或者 UA 有没有关系

**Comment by yefoenix** [comment]
更新了一下失效的链接示例……有没有人搞一下😂

**Comment by lotosbin** [comment]
SSR同构直出的页面 ，
window.__INITIAL_SSR_STATE__
可以直接得到数据

**Comment by lotosbin** [comment]
小红书有用户指纹的逻辑，这个应该需要走 puppeteer 之类的无头浏览器做一次渲染才可以，
可以考虑部署 puppeteer 服务 例如 https://www.browserless.io/
来支持渲染网页，然后解析
@DIYgod

**Comment by yefoenix** [comment]
@lotosbin rsshub是支持通过puppeteer渲染网页的，可参见抖音路由

**Comment by DIYgod** [comment]
@lotosbin 用户指纹的逻辑是指什么？为什么 puppeteer 就可以解决

**Comment by lotosbin** [comment]
页面逻辑是检查cookie是否已经有指纹的值，如果没有页面上的脚本会生成一个放在cookie中，然后reload页面，
puppeteer的方案，是打开后等待1s，让页面生成指纹reload，就可以获取到实际的内容了，

指纹是根据 浏览器类型版本 ip 等很多参数 根据一个算法生成的，用来区分用户或者设备的，

**Comment by DIYgod** [comment]
issuehunt 挂了，暂时没法打钱了，明天再看看

**Comment by yefoenix** [comment]
@DIYgod  issuehunt 恢复了，可以打钱了
