### ISSUE TITLE
阅读器中sehuatang图片不显示

### ISSUE THREAD

**Issue by dabo-t** [DIYgod/RSSHub#3082]
### 路由地址
dsndsht23/yzwmyc
### 预期是什么？
显示图片
### 实际发生了什么？
图片不显示
### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/9606042/64918186-72744200-d7cd-11e9-9a81-eff4434357cd.png)

**Comment by DIYgod** [comment]
https://docs.rsshub.app/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by dabo-t** [comment]
> https://docs.rsshub.app/#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

我感觉是<ignore_js_op>造成的不显示

**Comment by DIYgod** [comment]
Reeder 测试正常

**Comment by dabo-t** [comment]
> Reeder 测试正常

![image](https://user-images.githubusercontent.com/9606042/64937207-fdb40d00-d88b-11e9-8b7c-43d8c8aeeee7.png)
