### ISSUE TITLE
【/fx678/kx】汇通网_快讯 Bug Report——部分条目提取正文失败，标题只推送了发布时间，内容为空

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3088]
### 路由地址
/fx678/kx
### 预期是什么？
正常推送
### 实际发生了什么？
部分条目提取正文失败，标题只推送了发布时间，内容为空
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       centos7        |
| Node version       |  10.17             |
| if Docker, version |               |

### 额外信息（日志、报错等）
阅读器是ttrss，
https://kx.fx678.com/201909160458412479.shtml   这条推送题目和正文都正常
https://kx.fx678.com/201909160459202471.shtml 这条 推送的题目为 2019-09-15 21:11:22 ，正文无内容，实际上 该条的题目为 共享经济告别“野蛮生长” 纷纷跨入“涨价时代”，正文引用省略

---

**Comment by kt286** [comment]
无法复现  可能是当时原网站发的就是那个  你看到的时候已经改成正确的了
