### ISSUE TITLE
豆瓣 wanted

### ISSUE THREAD

**Issue by Democookie** [DIYgod/RSSHub#309]
豆列、个人日志

**Comment by Democookie** [comment]
豆列🌰：https://www.douban.com/doulist/33658645/
日志：https://www.douban.com/people/sophiechou/notes

**Comment by hondajojo** [comment]
日志rss有的 https://www.douban.com/feed/people/sophiechou/notes

**Comment by DIYgod** [comment]
长时间无 pr，issue 暂时关闭
