### ISSUE TITLE
【RSS 需求】绿洲 APP 用户动态路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3100]
### 网站地址
https://oasis.weibo.cn/v1/h5/share?uid=:id
例：https://oasis.weibo.cn/v1/h5/share?uid=1563926367
### 网站描述
「绿洲」是微博出品的生活时尚社交产品。
### 需要生成什么内容？
用户动态 feed

**Comment by dabo-t** [comment]
+1

**Comment by yefoenix** [comment]
补充：带视频的用户动态
https://oasis.weibo.cn/v1/h5/share?uid=1990895721
