### ISSUE TITLE
微博消息缺失

### ISSUE THREAD

**Issue by shaomingbo** [DIYgod/RSSHub#312]
微博信息流如果设置了可见性，比如仅粉丝可见，RSS 爬取就会失效。
比如这个账户20180625的[微博](https://weibo.com/chinaetfs)，有4条，但[爬取的](https://rsshub.app/weibo/user/5687069307)只有3条。

**Comment by DIYgod** [comment]
@shaomingbo 无解

**Comment by RikkaBlue** [comment]
再次遇到了这个问题。

比如用户：[https://weibo.com/7499841383](https://weibo.com/7499841383)，最新的是 14日 的一条相簿。
但是 RSS 输出没有此条，[https://rsshub.app/weibo/user/7499841383](https://rsshub.app/weibo/user/7499841383)，自建的也没有。
