### ISSUE TITLE
api 接口支持输出为 json 格式

### ISSUE THREAD

**Issue by ishowman** [DIYgod/RSSHub#3124]
### 这是一个什么样的功能？
我希望 api 接口支持输出为 json 格式（记得以前是支持，现在砍掉了？）
### 这个功能可以解决什么问题？
json 格式更通用

**Comment by yefoenix** [comment]
@ishowman rsshub 不是一个爬虫程序，他是为「RSS订阅」这个需求服务的，在这个语境下，通用的格式就是RSS/atom的一系列标准格式。

**Comment by DIYgod** [comment]
@ishowman 可以使用 npm 包自行输出 https://docs.rsshub.app/usage.html#作为-npm-包使用
