### ISSUE TITLE
[Feature Request]pubDate格式统一

### ISSUE THREAD

**Issue by zodiacg** [DIYgod/RSSHub#3133]
### 这是一个什么样的功能？

统一目前发布的rss中各路由项的pubDate格式。

目前各路由的pubDate格式由各route自行决定，有UTCString，也有直接使用信息源的格式或其它格式，并不统一。

1.能否在最后的生成模板中使用Date对象再次重新解析日期，提供统一的时间格式。（可能带来额外无用功）
2.或在接受贡献代码时建议pubDate的格式以保持一致。（现有route更新任务繁重）

### 这个功能可以解决什么问题？

解决利用rss解析的下游应用对pubDate格式处理不健全的情况。
如我当前使用的[酷Q插件](https://cqp.cc/t/44984)，对于部分格式的pubDate（如明日方舟新闻）不能正确的解析其时间戳，导致不能识别消息更新因此不推送消息。

**Comment by kt286** [comment]
正因为返回的时间类型太多太杂，所以生成模板的时候没法统一处理，只能具体问题具体修改

**Comment by DIYgod** [comment]
@kt286 其实是可以的，`new Date(item.date).toUTCString()` 就行了，就是显得有点多余

**Comment by kt286** [comment]
主要是怕有的路由直接返回 “1天以前” ‘2019年11月’ 这样的日期

**Comment by SettingDust** [comment]
@kt286 让路由去死，太不规范了吧，DIY肯定不给过的

**Comment by DIYgod** [comment]
Done addd22c113d1af89beb02d0d138f3c0a5c53b98e
