### ISSUE TITLE
【RSS 需求】少数派 sspai 按标签更新文章的RSS

### ISSUE THREAD

**Issue by TigerDen96** [DIYgod/RSSHub#3136]
### 网站地址
https://sspai.com/tag/RSS
### 网站描述
少数派是一家新媒体网站，致力于更好地运用数字产品或科学方法,帮助用户提升工作效率和生活品质...
### 需要生成什么内容？

- [ ] 显示特定标签内的新文章

### 额外描述
以便更高效地获取特定的信息

**Comment by sunshinenny** [comment]
最近少数派可能由旧版升级为新版，最近做的路由可能不适配。
所以等到新版上线后帮忙实现
下面是挖掘到的API「可能」
https://beta.sspai.com/api/v1/article/tag/hot/page/get?limit=30&offset=0&tag=iPad

**Comment by Jeason0228** [comment]
恩 刚看了也有这个参考
https://sspai.com/api/v1/articles?offset=0&limit=50&has_tag=1&tag=sketch&include_total=false
