### ISSUE TITLE
科创板项目动态

### ISSUE THREAD

**Issue by chinobing** [DIYgod/RSSHub#3141]
### 网站地址
http://kcb.sse.com.cn/renewal/
### 网站描述
科创板项目动态
### 需要生成什么内容？
按更新日期获取项目的动态，包括发行人全称 和 审核状态

**Comment by Jeason0228** [comment]
@kt286 请教一下像这个页面找到了大概的api
http://query.sse.com.cn/statusAction.do?jsonCallBack=jsonpCallback49403&isPagination=true&sqlId=SH_XM_LB&pageHelp.pageSize=20&offerType=&commitiResult=&registeResult=&csrcCode=&currStatus=&order=updateDate%7Cdesc&keyword=&auditApplyDateBegin=&auditApplyDateEnd=&_=1569477148681

怎样才能拿到数据呢....网页访问是正常的

```  const pageUrl = 'http://kcb.sse.com.cn/renewal/';
    const host = 'http://www.sse.com.cn';
    const callbackid=Math.floor(Math.random() * (100000 + 1));
    const callbacktime=new Date().getTime();
    console.log(callbackid);
    console.log(callbacktime);
    const response = await got({
        
        method: 'get',
        url: 'http://query.sse.com.cn/statusAction.do?jsonCallBack=jsonpCallback${callbackid}&isPagination=true&sqlId=SH_XM_LB&pageHelp.pageSize=20&offerType=&commitiResult=&registeResult=&csrcCode=&currStatus=&order=&keyword=&auditApplyDateBegin=&auditApplyDateEnd=&_=${new Date().getTime()}',
        headers: {
            Referer: pageUrl,
        },
    });

```

**Comment by kt286** [comment]
@Jeason0228 你可以试试在 `headers` 里边加上这三个
```
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
```

**Comment by Jeason0228** [comment]
@kt286 没什么作用呢
请问一下
[可转换公司债券公告   https://rsshub.app/sse/convert/beginDate=2018-08-18&endDate=2019-08-18&companyCode=603283&title=股份]( https://rsshub.app/sse/convert/beginDate=2018-08-18&endDate=2019-08-18&companyCode=603283&title=股份)

这里面的URL  能够直接通过参数拼接...直接用浏览器访问,拿到数据吗?
我试了下也是返回失败的
null({"jsonCallBack":"null","success":"false","error":"系统繁忙...","errorType":"ExceptionInterceptor"})

```
const query = ctx.params.query || ''; // beginDate=2018-08-18&endDate=2019-08-18&companyCode=603283&title=股份
    const pageUrl = 'http://bond.sse.com.cn/disclosure/announ/convertible/#';
    const host = `http://www.sse.com.cn`;

    const response = await got({
        method: 'get',
        url: `http://query.sse.com.cn/infodisplay/queryBulletinKzzTipsNew.do?isPagination=true&pageHelp.pageSize=2&flag=0&_=${new Date().getTime()}&${query.replace(/([\u4e00-\u9fa5])/g, (str) => encodeURIComponent(str))}`,
        headers: {
            Referer: pageUrl,
        },
    });
```

**Comment by kt286** [comment]
直接访问报错是没有 `Referer` 。`Referer` 地址一定要写对
科创版的是 `http://kcb.sse.com.cn/renewal/`
可转换那个是 `http://bond.sse.com.cn/disclosure/announ/convertible/#`

PS 还有别的问题的话最好在群里说吧，issue 聊天不太合适
