### ISSUE TITLE
最近ip被封，无法连接国内站点的rss，有碰到相同情况的网友请入内留言，谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3145]
### 路由地址
/egsea/flash
### 预期是什么？
能够成功订阅
### 实际发生了什么？
无法订阅
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      centos7         |
| Node version       |  1.17             |
| if Docker, version |               |

### 额外信息（日志、报错等）
自建的rsshub version

###  155ea080658dd81093b36fdded1f4a336a61dc41
---
[https://rsshub.app/egsea/flash](https://rsshub.app/egsea/flash) 这个可以打开，但是自建的 ip:port/egsea/flash 无法打开。

报错
```
{"message":"Error in /egsea/flash: connect ETIMEDOUT 47.106.48.167:443: target website might be blocking our access, you can <a href=\"https://docs.rsshub.app/install/\">host your own RSSHub instance</a> for a better usability.","level":"error"}
{"message":"Request https://www.egsea.com/news/flash-list?per-page=30 fail, retry attempt #2: RequestError: connect ETIMEDOUT 47.106.48.167:443","level":"error"}
```

ttrss订阅跳出反馈，
```
Couldn't download the specified URL: ; 28 Operation timed out after 45000 milliseconds with 0 bytes received
```

直接在chrome上打开 ip:port/egsea/flash   这条，一直在转圈 didn’t send any data

**Comment by DIYgod** [comment]
目测网络问题，可以试下这个能不能打开：https://github.com/DIYgod/RSSHub/blob/master/lib/routes/egsea/flash.js#L6

**Comment by KwToPA** [comment]
> 目测网络问题，可以试下这个能不能打开：https://github.com/DIYgod/RSSHub/blob/master/lib/routes/egsea/flash.js#L6

我装rsshub的机器的ip最近被封了，是这个原因吗？可是其他国内站点的rss还能用

**Comment by KwToPA** [comment]
好像就是这个原因，我开了台能ping通的。该路由可以打开，阿里云是不是跟土啬有关系

**Comment by KwToPA** [comment]
> 目测网络问题，可以试下这个能不能打开：https://github.com/DIYgod/RSSHub/blob/master/lib/routes/egsea/flash.js#L6

https://github.com/DIYgod/RSSHub/pull/3143

天涯路由出现相同的报错

connect ETIMEDOUT 天涯的ip

在控制台上 curl www.tianya.cn/11488997/bbs
```
failed connect to url:80; connection time out
```

别的墙外站点的路由可以，例如 裏垢女子まとめ 

有没有好心网友，用最近刚被ban ip的机器帮忙测试下 

 ### 谢谢

**Comment by KwToPA** [comment]
经过mtr测试，反馈如下

```
  9.|-- 202.97.12.2                0.0%    10  215.7 215.7 215.5 216.8   0.0
 10.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
```

ping www.zhihu.com ，得到的IP是 23.10.97.42 可以ping 通

**Comment by DIYgod** [comment]
out of
