### ISSUE TITLE
苹果固件包下载

### ISSUE THREAD

**Issue by MisterGlasses** [DIYgod/RSSHub#3159]
### 网站地址
https://ipsw.me/iPhone11,8
### 网站描述
提供苹果设置备固件包下载 目测全网最快
### 需要生成什么内容？

- [ ] 内容一
当网站固件更新时 rss能及时推送
- [ ] 内容二
点击推送时，能方便得获取下载链接
- [ ] 内容三
能自定义机型
### 额外描述
非常感谢

**Comment by Jeason0228** [comment]
https://ipsw.me/timeline.rss

**Comment by MisterGlasses** [comment]
谢谢 我之前没有找到


________________________________
发件人: Jeason0228 <notifications@github.com>
发送时间: 星期一, 九月 30, 2019 13:41
收件人: DIYgod/RSSHub
抄送: Mr.Glasses; Author
主题: Re: [DIYgod/RSSHub] 苹果固件包下载 (#3159)


https://ipsw.me/timeline.rss

―
