### ISSUE TITLE
增加bilibili分区 “纪录片” 谢谢作者们

### ISSUE THREAD

**Issue by yijinbandouya** [DIYgod/RSSHub#316]
谢谢

**Comment by DIYgod** [comment]
文档已补充：https://docs.rsshub.app/#%E5%88%86%E5%8C%BA%E8%A7%86%E9%A2%91

**Comment by yijinbandouya** [comment]
再次对你们所做的工作表示感谢，以后挣钱了赞助你们一些。希望你们坚持下去谢谢！

**Comment by Xuanwo** [comment]
@yijinbandouya 关键词：`以后` ， 坚持
