### ISSUE TITLE
【RSS Request】獲取Webtoon漫畫最新話更新

### ISSUE THREAD

**Issue by Yusei-StarDust** [DIYgod/RSSHub#3164]
### 网站地址
[https://www.webtoons.com/zh-hant/](url)
### 网站描述
引自官方：全球數位漫畫服務平臺，LINE WEBTOON提供每日更新超過200個線上免費漫畫，可同時在iPhone，iPad，Kindle Fire，安卓，Windows等多種流覽器中進行閱讀。
### 需要生成什么内容？

- [ ] 能獲取某一漫畫最新一話的更新通知

### 额外描述
應該照咚漫的feed抓取依樣畫葫蘆(?就好了，因為咚漫是Line webtoon簡體中文版本。有些漫畫在該語言平台是獨創內容，不互通的
雖然說將漫畫網址如https://www.webtoons.com/en/romance/subzero/list?title_no=1468
的list改成rss，也可以獲取rss連接(可能是官方提供的?)，但是除了英文版外，其他版本如繁體中文顯示的post順序被打亂了，所以希望可以做一個新的版本
順帶一題，咚漫的網址其實也可以直接將list改成rss來獲取feed，不過章節顯示順序也是亂的就是了，相較於此rssHub提供的則能顯示正確的章節順序
不過，章節亂序的問題好像不是在每個Rss Reader都會發生的樣子就是了

**Comment by SettingDust** [comment]
> ### 网站地址
> [https://www.webtoons.com/zh-hant/](url)
> 
> ### 网站描述
> 引自官方：全球數位漫畫服務平臺，LINE WEBTOON提供每日更新超過200個線上免費漫畫，可同時在iPhone，iPad，Kindle Fire，安卓，Windows等多種流覽器中進行閱讀。
> 
> ### 需要生成什么内容？
> * [ ]  能獲取某一漫畫最新一話的更新通知
> 
> ### 额外描述
> 應該照咚漫的feed抓取依樣畫葫蘆(?就好了，因為咚漫是Line webtoon簡體中文版本。有些漫畫在該語言平台是獨創內容，不互通的
> 雖然說將漫畫網址如https://www.webtoons.com/en/romance/subzero/list?title_no=1468
> 的list改成rss，也可以獲取rss連接(可能是官方提供的?)，但是除了英文版外，其他版本如繁體中文顯示的post順序被打亂了，所以希望可以做一個新的版本
> 順帶一題，咚漫的網址其實也可以直接將list改成rss來獲取feed，不過章節顯示順序也是亂的就是了，相較於此rssHub提供的則能顯示正確的章節順序
> 不過，章節亂序的問題好像不是在每個Rss Reader都會發生的樣子就是了

没有发现顺序问题，应该是阅读器的问题，而且rss的话有顺序问题也没什么影响

**Comment by machsix** [comment]
繁体中文在ttrss上就会有顺序问题，因为`pubDate`是中文，ttrss可能对中文日期排序有bug，只能在rsshub端解决。
咚漫原本是从网页直接拉取的日期，所以没有问题。

**Comment by Yusei-StarDust** [comment]
原來如此，那各位當無事發生好了，那麼看要不要把webtoon的feed記錄在rssHub上？
