### ISSUE TITLE
软件更新 RSS

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#317]
- [x] App Store
- [x] Mac App Store
- [ ] Google Play
- [ ] 酷安
- [ ] npm
- [x] GitHub Releases

**Comment by tgly307** [comment]
咦？这是要计划出app了么？

**Comment by ShimotsukiH** [comment]
![image](https://user-images.githubusercontent.com/33424662/42130915-4770301c-7d26-11e8-9a99-54b6bcb54923.png)
为何miui更新放在停水通知里面那么草

**Comment by cielpy** [comment]
https://github.com/DIYgod/RSSHub/pull/472 添加了 App Store 和  Mac App Store 支持

**Comment by DIYgod** [comment]
@ShimotsukiH  你可能需要清下缓存

**Comment by Geeyun-JY3** [comment]
现在 Google Play 和酷安还会做吗……

**Comment by HenryQW** [comment]
酷安已经完成了，Play就要等有缘人了。依照谷歌的尿性，估计反爬也很严重。

**Comment by Geeyun-JY3** [comment]
> 酷安已经完成了

指的是应用更新吗……为什么我目前在文档和 PR 中看到的只有图文话题动态等……
