### ISSUE TITLE
获取浙江大学官网学术板块更新

### ISSUE THREAD

**Issue by zwbao** [DIYgod/RSSHub#3173]
### 网站地址

http://www.zju.edu.cn/xs/list.htm

### 网站描述

浙江大学官网学术板块

### 需要生成什么内容？

- [ ] 标题，日期
- [ ] 学术报告内容

**Comment by Jeason0228** [comment]
@zwbao 等待合并

**Comment by zwbao** [comment]
@Jeason0228 感谢大佬~
