### ISSUE TITLE
求大麦网rss

### ISSUE THREAD

**Issue by PaulHerrero** [DIYgod/RSSHub#3180]
### 网站地址
https://www.damai.cn/
### 网站描述
大麦网-全球演出赛事官方购票平台-100%正品,安全快捷,为您提供演唱会、音乐会、话剧、体育比赛等多种门票在线订购服务,让您享受优质的购票体验!
### 需要生成什么内容？
城市
演出类别
标题
活动地点
价格
演出简介

**Comment by yefoenix** [comment]
@PaulHerrero issue模板套错了……请根据issue request 模板补充必要信息

**Comment by PaulHerrero** [comment]
> @PaulHerrero issue模板套错了……请根据issue request 模板补充必要信息

不好意思，已修改

**Comment by Jeason0228** [comment]
https://api-gw.damai.cn//search.html?cat=6&destCity=%E6%B7%B1%E5%9C%B3&_ksTS=1570083786498_129&callback=jsonp130

**Comment by lisxray** [comment]
> https://api-gw.damai.cn//search.html?cat=6&destCity=%E6%B7%B1%E5%9C%B3&_ksTS=1570083786498_129&callback=jsonp130

深圳的结果里有珠海和东莞😂

官网的接口似乎不是这个？

**Comment by yefoenix** [comment]
https://search.damai.cn/searchajax.html?keyword=&cty=深圳&ctl=演唱会&sctl=&tsg=0&st=&et=&order=1&pageSize=30&currPage=1&tn=


这个呢
