### ISSUE TITLE
【RSS Request】Bilibili 用户关注的“所有”动态

### ISSUE THREAD

**Issue by tomyang001** [DIYgod/RSSHub#3187]
### 网站地址
https://t.bilibili.com/

### 网站描述
b站

### 需要生成什么内容？
用户关注的**所有**动态
- [ ] 内容一
- [ ] 内容二

### 额外描述
可否在目前已有的“ 用户关注视频动态”和“ 用户关注专栏”基础上，升级为可以获取用户关注所有动态，即涵盖路由 /bilibili/user/dynamic/:uid 所能获取的所有内容。

**Comment by ClarkeCheng** [comment]
这个可以实现，登录B站后，打开
[https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=0&type=268435455](https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?uid=0&type=268435455)
里面有最新20条动态，但是谁来做呢？

**Comment by DIYgod** [comment]
https://docs.rsshub.app/social-media.html#yong-hu-guan-zhu-shi-pin-dong-tai

**Comment by LogicJake** [comment]
@DIYgod 他要的应该是视频加专栏
