### ISSUE TITLE
【中国海关-拍卖信息】RSS wanted 希望支持按时间线推送，谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3190]
### 网站地址
[http://www.customs.gov.cn/customs/302249/2476857/302309/index.html](http://www.customs.gov.cn/customs/302249/2476857/302309/index.html)
### 网站描述
中国海关-拍卖信息
### 需要生成什么内容？

- [ ] 希望支持按时间线推送

### 谢谢

**Comment by Jeason0228** [comment]
@KwToPA 
我看rsshub域名可以生成成功了。不需要自建了
https://rsshub.app/gov/customs/list/fagui
https://rsshub.app/gov/customs/list/paimai

**Comment by KwToPA** [comment]
我自建的也生效了，估计是国庆的原因

**Comment by Jeason0228** [comment]
恩,可能是吧...开网了
