### ISSUE TITLE
【/weibo/user/id】But Report——某些链接无法提取全文，参数mode=fulltext失效，把内容当作标题推送，内容栏为空

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3195]
### 路由地址
/weibo/user/id
### 预期是什么？
推送全文
### 实际发生了什么？
推送部分内容
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
出错的是这条：[https://weibo.com/6646798696/I9YI7yfQ7](https://weibo.com/6646798696/I9YI7yfQ7)

**Comment by yefoenix** [comment]
首先，Mercury  从原理上来讲就做不到各种路由网页的全文全部准确识别和抓取，只是一种辅助的手段；
其次，rsshub 没有 fulltext=1 这种写法。

**Comment by KwToPA** [comment]
抱歉，搞错了。我用mode=fulltext测试，没有结果。因为新订阅只推送最近的9-10条，刚好https://weibo.com/6646798696/I9YI7yfQ7 在推送范围外面

**Comment by KwToPA** [comment]
fulltext后 加 ```&limit=20``` 无效

**Comment by SettingDust** [comment]
@KwToPA Rss只是用来获取更新的

**Comment by KwToPA** [comment]
> @KwToPA Rss只是用来获取更新的

抱歉，抱歉，忘记了。

---


我又找了条测试 https://weibo.com/2948854920/I9VdkvSKP ， /weibo/user/2948854920 ，这条倒是可以全文提取

有两个问题

1、两个博主我都没有加后缀 fulltext，若重新订阅，一个推送9条，一个推送7条，请问这是微博服务器决定的还是rsshub决定的？

2、自建ip:port/weibo/user/2948854920?mode=fulltext  ，得到的反馈是

### 把内容当作标题推送，内容有太多，只能推送部分，以...省略号结尾。 内容部分为空

rsshub 版本号 cff9aa549b2bc22c4f95cd4c352fdf75c8e2de2e

我估计这条 https://weibo.com/6646798696/I9YI7yfQ7 是在太长，mercury 只能缩略了。

**Comment by KwToPA** [comment]
@DIYgod  麻烦加个 bug 标签，谢谢

**Comment by yefoenix** [comment]
@KwToPA 引入 Mecury 只是一个辅助手段，它并没有也不能保证一定抓取成功——这就不是个Bug

**Comment by KwToPA** [comment]
> @KwToPA 引入 Mecury 只是一个辅助手段，它并没有也不能保证一定抓取成功——这就不是个Bug

我标题改了，最新的反馈 https://github.com/DIYgod/RSSHub/issues/3195#issuecomment-538610596
 
现在是参数传递的问题

**Comment by KwToPA** [comment]
> @KwToPA 引入 Mecury 只是一个辅助手段，它并没有也不能保证一定抓取成功——这就不是个Bug

你的意思 mode=fulltext 是通过mercury实现的？

**Comment by yefoenix** [comment]
#2738
