### ISSUE TITLE
请求增加一剑浣春秋av女优专栏文章

### ISSUE THREAD

**Issue by Whale69** [DIYgod/RSSHub#3203]
### 网站地址
http://www.playno1.com/
举例该专栏文章：http://www.playno1.com/article-31145-1.html#.XZsiR-czbOQ
### 网站描述
著名的日本色情片评论家及AV专栏作者。 至今撰文累积超过5,000篇，多次投稿于今日新闻网等报章杂志。 因熟悉日本AV文化及产业，文章中具体分析并报导AV的时事新闻，颇受佳评，因而被网友称为“AV达人”
### 需要生成什么内容？
- [ ] 不同的栏目文章更新提醒，例如最新女优动态

### 额外描述
尽量全文抓取，因为挂代理访问网址总会出现Error 1020，This website is using a security service to protect itself from online attacks.

**Comment by Whale69** [comment]
AV No.1 Blog http://feeds.feedburner.com/avnoone

一劍渙春秋，劍大的博客，全文輸出。不要跟我說你不知道，專門介紹AV資訊的站，相當牛逼，相當專業。這個RSS源不是博客官方提供的，是網友燒錄，強烈推薦。

**Comment by LinEvil** [comment]
@Whale69 ？
