### ISSUE TITLE
请求更新华南理工大学教务通知

### ISSUE THREAD

**Issue by daxiang123456** [DIYgod/RSSHub#3211]
### 网站地址
http://jw.scut.edu.cn/zhinan/cms/toPosts.do?category=0
### 网站描述
华南理工大学教务通知
### 需要生成什么内容？

- [ ] 内容一
通知公告的“全部”

### 额外描述
教务网页改版，之前的RSS源连续很多天拉取出错（HTTP 404），求大佬更新下！

**Comment by Jeason0228** [comment]
https://rsshub.app/scut/jwc/notice/all
访问正常...只是少了一条..可能是刚发布
