### ISSUE TITLE
「iCity - 用户动态」RSS 支持请求

### ISSUE THREAD

**Issue by imjoeyli** [DIYgod/RSSHub#3214]
### 网站地址
https://icity.ly/u/sai
(仅作举例，sai 是用户 id）

### 网站描述
iCity - 用户动态

### 需要生成什么内容？

- [ ] 更新的帖子（带图片）
- [ ] 帖子发表的时间

### 额外描述
- 不登录只能查看最近几条动态
- 希望可以查看全部动态（支持输入自己的账户密码）

**Comment by hoilc** [comment]
RSS本来就只需要支持最近动态😂

**Comment by imjoeyli** [comment]
> RSS本来就只需要支持最近动态😂

没错，但印象里 RSS 最多是可以输出最近 20 条。但是 iCity 没有登录的话只能看最近 3 条，更理想的是可以输入账号密码登录来抓取更多动态。

**Comment by DIYgod** [comment]
> 没错，但印象里 RSS 最多是可以输出最近 20 条。但是 iCity 没有登录的话只能看最近 3 条，更理想的是可以输入账号密码登录来抓取更多动态。

会很麻烦且没必要

**Comment by imjoeyli** [comment]
> > 没错，但印象里 RSS 最多是可以输出最近 20 条。但是 iCity 没有登录的话只能看最近 3 条，更理想的是可以输入账号密码登录来抓取更多动态。
> 
> 会很麻烦且没必要

是会变麻烦。

但也有两点顾虑：一是如果用户短时间内发布大于 3 条动态（小于抓取频率），那未登录则会出现漏抓；二是防患未然，应对网站取消未登录用户查看最近用户动态的可能。

所以请求还是考虑一下。
