### ISSUE TITLE
请求lmmpic的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#3216]
### 网站地址
https://www.lmmpic.com/cosplay/
https://www.lmmpic.com/entertainment/
### 网站描述
https://www.lmmpic.com/cosplay/
https://www.lmmpic.com/entertainment/
### 需要生成什么内容？

- [ ] 内容一
全文

### 额外描述
求全文，如果全文不行就封面也行

**Comment by yefoenix** [comment]
https://www.lmmpic.com/cosplay/feed
