### ISSUE TITLE
求教Description输出导致xml格式错误?

### ISSUE THREAD

**Issue by Jeason0228** [DIYgod/RSSHub#3217]
### 路由地址
http://127.0.0.1:1200/sspai/tag/apple
for #3136 
### 预期是什么？
正常的xml格式显示
## description全文输出，导致错乱的格式
![企业微信截图_20191009102041](https://user-images.githubusercontent.com/44083849/66446869-ce558200-ea7e-11e9-9e5e-1594166a520b.png)

## 注释description则正常显示
![企业微信截图_20191009102302](https://user-images.githubusercontent.com/44083849/66446872-d31a3600-ea7e-11e9-9b56-e7fb22535d16.png)

### 部署相关信息
```
const got = require('@/utils/got');
const cheerio = require('cheerio');

module.exports = async (ctx) => {
    const keyword = ctx.params.keyword;
    const api_url = `https://sspai.com/api/v1/articles?offset=0&limit=50&has_tag=1&tag=${keyword}&include_total=false`;
    const host = `https://beta.sspai.com/tag/${keyword}`;
    const resp = await got({
        method: 'get',
        url: api_url,
        headers: {
            Referer: host,
        },
    });
    const data = resp.data.list;
    const items = await Promise.all(
        data.map(async (item) => {
            const link = `https://sspai.com/post/${item.id}`;
            let description = ``;
            const key = item.id;
            const value = await ctx.cache.get(key);
            if (value) {
                description = value;
            } else {
                const response = await got({ method: 'get', url: link });
                const $ = cheerio.load(response.data);
                description = $('div.content.wangEditor-txt.clock').html();
                ctx.cache.set(key, description);
            }
            return {
                title: item.title.trim(),
                //description: `\r\n` + description + `\r\n`,
                link: link,
                pubDate: new Date(item.released_at * 1000).toUTCString(),
                author: item.author.nickname,
            };
        })
    );
    ctx.state.data = {
        title: `#${keyword} - 少数派`,
        link: host,
        description: `${keyword} 更新推送 `,
        item: items,
    };
};

```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |           win    |
| Node version       |      v10.16.3         |
| if Docker, version |               |

**Comment by Jeason0228** [comment]
虽然不影响订阅，但是这个格式有点不能忍0 0

**Comment by yefoenix** [comment]
为什么要在浏览器里直接看rss内容？

**Comment by Jeason0228** [comment]
> 为什么要在浏览器里直接看rss内容？

也不是在浏览器里看rss内容...而是感觉正常生成出来的rss 应该是有格式的...而不是直接以html格式显示，之前也遇到这种情况。后来调试完就解决了，但是不太明白问题出在哪里。
给description换过 ·· 或者“” 或者 '' 符号来尝试也没有变化

**Comment by DIYgod** [comment]
浏览器打开 `view-source:http://127.0.0.1:1200/sspai/tag/apple`，然后把内容贴进来看看

**Comment by yefoenix** [comment]
其实可能是电脑配置不够，浏览器还没渲染完，多等一会儿看看……

**Comment by Jeason0228** [comment]
> 其实可能是电脑配置不够，浏览器还没渲染完，多等一会儿看看……
> 浏览器打开 `view-source:http://127.0.0.1:1200/sspai/tag/apple`，然后把内容贴进来看看

回头重启...又好了= = 然后刷新又失败了...可能真的全文太长了...渲染不行
![企业微信截图_20191009102302](https://user-images.githubusercontent.com/44083849/66449665-7d4a8b80-ea88-11e9-80e4-7893d63851d5.png)

**Comment by yefoenix** [comment]
可以 close 了
