### ISSUE TITLE
观察者网rss需求

### ISSUE THREAD

**Issue by Byhaise** [DIYgod/RSSHub#3225]
### 源站地址

https://www.guancha.cn/

### 网站描述

观察者网（www.guancha.cn）携手上海春秋发展战略研究院，旨在为全球华人读者提供集新鲜、热点、深度、趣味于一体的时政资讯。
### 需要生成什么内容？

- [x] 首页及分栏目文章 rss （ https://www.guancha.cn/internation
- [ ] 子栏目（ https://www.guancha.cn/GuoJi%C2%B7ZhanLue/list_1.shtml
- [x] 风闻·个人文章 （ https://user.guancha.cn/user/personal-homepage?uid=248180

### 额外描述

#1949 需求被关闭，请示管理员后重开一个

**Comment by Jeason0228** [comment]
首页 和 子栏目 涉及的内容太多了0 0
要不你再详细描述 具体是哪些模块的内容吧。

**Comment by wuhgit** [comment]
@Byhaise 
@DIYgod 
@Jeason0228 

给你们提供一点帮助吧，希望有用：

观察者网：

个人文章页面：
https://app.guancha.cn/user/get-published-list?page_size=20&page_no=1&uid=用户数字ID

专栏作者文章页面：
https://api.guancha.cn/Appdata/NewsList/?newstype=0&size=10&page=1&type=2&id=专栏作者英文ID

返回数据均为 JSON 格式，其中个人文章页面网址参数中的 page_size 属性实测无效。

我也是一名 RSS 重度依赖者，但目前还没有开始使用 RSSHub 来生成 RSS ，不是很清楚如何利用这个来制作相关路由，提供这几个接口希望能有所帮助，也很希望这个项目能够长期进行下去。

**Comment by Jeason0228** [comment]
看了下好处理呀，pagesize固定20了，用page翻页，不过改这里没有啥意义

**Comment by Jeason0228** [comment]
首页找到了
https://www.guancha.cn/api/new_gundong.htm
 https://www.guancha.cn/api/member.htm
https://www.guancha.cn/api/redian.htm

**Comment by yefoenix** [comment]
@DIYgod  这个issue还没完全解决，只完成了第三项

**Comment by Jeason0228** [comment]
首页RSS #3306 等待合并
router:
/guanchazhe/index/all
新闻汇总：默认home输出头条+3列新闻,others则为滚动新闻+热点+观察者付费,all则包括以上
![企业微信截图_20191021202328](https://user-images.githubusercontent.com/44083849/67205742-ef38b280-f442-11e9-8ae0-37fcbdf844ae.png)
首页信息太多...没有必要不做首页了....我也就练练手和逻辑思维,也许写了很多弯路

**Comment by Byhaise** [comment]
感谢各位大佬 @wuhgit @Jeason0228 @yefoenix

**Comment by nullnullnullnull0** [comment]
只有个人文章,没有专栏作者文章阿
