### ISSUE TITLE
Acfun番剧源失效

### ISSUE THREAD

**Issue by Garrise** [DIYgod/RSSHub#3227]
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
TypeError: Cannot read property '1' of null
    at module.exports (/app/lib/routes/acfun/bangumi.js:14:98)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kt286** [comment]
@DIYgod close it
