### ISSUE TITLE
Unity

### ISSUE THREAD

**Issue by chihanjiang** [DIYgod/RSSHub#3231]
### 需要生成什么内容？

- [ ] 用户投稿

**Comment by Jeason0228** [comment]
新鲜事，尽在此
 下面的post 是用户投稿..也是rss想要的内容?

**Comment by SettingDust** [comment]
请规范格式并提供详细需生成RSS的地址

**Comment by TonyRL** [comment]
[Unity Connect shutting down - Jobs coming back to forum!](https://forum.unity.com/threads/unity-connect-shutting-down-jobs-coming-back-to-forum.1008901/)

**Comment by Jeason0228** [comment]
Latest from Unity
@chihanjiang 这个部分？
