### ISSUE TITLE
[RSS Request] Support Quanta Magazine

### ISSUE THREAD

**Issue by emdoe** [DIYgod/RSSHub#3236]
### 网站地址

[https://www.quantamagazine.org](https://www.quantamagazine.org)

### 网站描述

A well-known site for popular science. Though it already provides an [RSS feed: https://www.quantamagazine.org/feed](https://www.quantamagazine.org/feed), the output of the images is missing. 

### 需要生成什么内容？

- [x] Full-text article containing the images (including the enclosures)
- [x] Hide unuseful information, including `.hide-on-print` and `.print-text-border`.

**Comment by yefoenix** [comment]
rsshub 暂不接受已有 RSS feed 抓取全文的 issue，如有能力可自行编写路由后进行 pr. 
更简单的方式是把全文抓取任务交给阅读器。

**Comment by Jeason0228** [comment]
https://api.quantamagazine.org/feed/

@emode Try this, is the problem solved?

**Comment by emdoe** [comment]
> https://api.quantamagazine.org/feed/
> 
> @emode Try this, is the problem solved?

Thanks for your help and my answer would be, probably not. Actually I've tried all feeds for quanta magazine before (including this one).

> 更简单的方式是把全文抓取任务交给阅读器。

@yefoenix Thanks for your suggestion. That may be not a simple task to get the full text. Actually, as I mentioned before, the weakness of the official one is that it cannot display the images in articles. Besides, I don't find any RSS reader could perfectly do this job. Of course, I will try to implement it if I have more free time. But thanks anyway.

**Comment by Jeason0228** [comment]
ya. you can try to be a Rsshub contributor. I learn to dev. this just one or two days. 
you can read this. it's easy to install. https://docs.rsshub.app/install/
and easy to dev the rss https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze

**Comment by emdoe** [comment]
Thank you, @Jeason0228! I've already contributed some silly codes to this wonderful project 😂.

Could you send me a screenshot of [Cell Bacteria Mergers ....]? I'm interested in the full-text output of it. Or is it Foxmail just provided a web browser to view the page?

**Comment by Jeason0228** [comment]
you can install "Reeder"、“Leaf”、“Foxmail” or other software which can support Rss Read function。
then you change  to view the feed by web browser
![企业微信截图_27c9caf0-7dbe-4b01-98b6-a5e7701e0e50(1)](https://user-images.githubusercontent.com/44083849/66699024-cbc08a00-ed15-11e9-858e-b01314b2d2d6.png)
Reedar above;

![企业微信截图_042c8855-ac22-4585-97f1-58c459d1da40(1)](https://user-images.githubusercontent.com/44083849/66699027-d549f200-ed15-11e9-9c22-9242a86340f0.png)
Leaf above;

**Comment by Jeason0228** [comment]
@emdoe  is the problem solved? then close this issue

**Comment by emdoe** [comment]
No. I've said maybe I will do it later.
