### ISSUE TITLE
本地部署，询问正确的代理配置方式？

### ISSUE THREAD

**Issue by librix** [DIYgod/RSSHub#3246]
### 路由地址
http://127.0.0.1:1200/t66y/4
### 预期是什么？
200 ok
### 实际发生了什么？
404 error 

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     windows10        |
| Node version       |     v12.10.0         |

### 额外信息（日志、报错等）

配置代理：
```
 TCP    0.0.0.0:1080           0.0.0.0:0              LISTENING
```

配置 .env 文件：
```
	配置方式一：
	PROXY_PROTOCOL=socks5
	PROXY_HOST=127.0.0.1
	PROXY_PORT=1080

	配置方式二：
	PROXY_PROTOCOL=http
	PROXY_HOST=127.0.0.1
	PROXY_PORT=1080
```
错误信息：
```
info: /t66y/4, user IP: ::ffff:127.0.0.1
info: Proxy for http://www.t66y.com/thread0806.php?fid=4&search=today
connect ETIMEDOUT 69.63.176.143:80: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

info: Proxy for http://www.t66y.com/thread0806.php?fid=7&search=today
error: Error in /t66y/7: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>

info: Proxy for http://www.t66y.com/thread0806.php?fid=4&search=today
   error: Request http://www.t66y.com/thread0806.php?fid=4&search=today fail, retry attempt #2: RequestError: connect ETIMEDOUT 173.252.73.48:80
```

使用浏览器访问 http://www.t66y.com/thread0806.php?fid=4&search=today 的网站，可访问。电脑防火墙、杀毒软件均关闭。

询问：
1. 应当被代理的程序？
2. 正确的代理使用方式

**Comment by Jeason0228** [comment]
我是直接安装了profixer(软件)里面设置代理....但是路由里没有写过代理相关的代码

**Comment by librix** [comment]
> 我是直接安装了profixer(软件)里面设置代理....但是路由里没有写过代理相关的代码

可以问一下你的配置格式吗？我试了 profixer 依然是类似的错误提示。

理想的使用方式是正则表达式捕获url在使用时，先接入上游代理服务器，然后发送获取数据的请求。正则表达式未捕获的url直接发送获取数据的请求。
目前的使用方式是在SocksCap64中全局代理一个bat文件。使用起来不太好。
![image](https://user-images.githubusercontent.com/10742127/66702358-6a121700-ed39-11e9-8627-96772753186e.png)
目前遇到的问题是，`.env`设置rsshub环境变量的代理服务器无法连接，不知道是哪里的问题。我只看懂[这里](https://github.com/DIYgod/RSSHub/blob/1199a988c4e324927573f557f6b660acc815c9ef/lib/utils/request-wrapper.js#L51)写了是要使用代理，之后怎么使用看不懂了。

**Comment by Jeason0228** [comment]
你的路由目标对象需要使用到代理吗，一般情况下都不需要去设置这个配置文件。只是支持代理服务器，没有一定要使用代理才可以部署
