### ISSUE TITLE
装备前线

### ISSUE THREAD

**Issue by glacjay** [DIYgod/RSSHub#3252]
### 网站地址

https://www.zfrontier.com/

### 网站描述

客制化键盘和其他电脑外设相关的一个用户社区

### 需要生成什么内容？

- [ ] 内容一：首页的最新贴子列表

### 额外描述

无

**Comment by Jeason0228** [comment]
这网站有毒...在network里 看到 过一段时间 就给我下载一张键盘图...卧槽
类似https://img.zfrontier.com/banner/mykb/3098.png

**Comment by glacjay** [comment]
说的应该是首页第四篇文章下面的那个轮播图？而且也没有一直下载吧，那几个循环完一遍之后就没有新的了吧？😂️

**Comment by Jeason0228** [comment]
![企业微信截图_20191016135412](https://user-images.githubusercontent.com/44083849/66891758-83a6ad80-f01c-11e9-92bd-72784a69fb91.png)

是不是轮播我不知道....反正我也没动页面....就停留着
你按F12 进入network 选img标签  你会发现 很有规律下载 不重名的键盘图...我也是服了

**Comment by luffy9412** [comment]
> ![企业微信截图_20191016135412](https://user-images.githubusercontent.com/44083849/66891758-83a6ad80-f01c-11e9-92bd-72784a69fb91.png)
> 
> 是不是轮播我不知道....反正我也没动页面....就停留着
> 你按F12 进入network 选img标签 你会发现 很有规律下载 不重名的键盘图...我也是服了

就是轮播，数组定义了一个图片对象，定时器轮询数组每张图片
![123](https://user-images.githubusercontent.com/16608185/66896056-c2416580-f026-11e9-9093-b1fc5bd28680.png)
