### ISSUE TITLE
抖音抓取不了

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#3259]
### 路由地址
https://rsshub.app/douyin/user/58612314858
### 实际发生了什么？
抖音抓取不了
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
@currencyporter 目前看抓取正常，如有问题请给出具体报错信息

**Comment by Jeason0228** [comment]
> @currencyporter 目前看抓取正常，如有问题请给出具体报错信息

Looks like something went wrong
[object Object]

**Comment by kt286** [comment]
反爬了吧，自建试试

**Comment by currencyporter** [comment]
那我的rss 都更新不了,没有内容

**Comment by DIYgod** [comment]
Fixed
