### ISSUE TITLE
想要“端媒体”的订阅源

### ISSUE THREAD

**Issue by EverGroot** [DIYgod/RSSHub#3260]
### 网站地址
https://theinitium.com/

### 网站描述

折腾了一会儿还是不太会，希望大佬们能帮我制作一个端媒体的订阅源
端媒体是香港的一家媒体，里面的观点属于不左不右，算是一个很好了解香港和台湾真实情况的地方。所以希望能帮我做一个订阅源。
现有的端媒体订阅都不是全文
还有如果能抓取简体字是更好的，因为官方网站是有简体版本的。

### 需要生成什么内容？
端媒体热点
端媒体深度

万分感谢

**Comment by yefoenix** [comment]
rsshub 暂不接受已有 RSS feed 抓取全文的 issue，如有能力可自行编写路由后进行 pr.
更简单的方式是把全文抓取任务交给阅读器。

**Comment by Felix2yu** [comment]
端传媒的RSS是全文的，看不到全文的都是付费内容。

**Comment by Jeason0228** [comment]
@EverGroot 是全文的呀
http://feeds.initium.news/theinitium

**Comment by MikeyWei** [comment]
试试 https://rsshub.app/theinitium/app
就像 @Felix2yu 说的，端是一个有付费墙的媒体，看不到全文很正常。
