### ISSUE TITLE
希望有x-mol的文章订阅

### ISSUE THREAD

**Issue by Roy-yu-sdu** [DIYgod/RSSHub#3265]
### 网站地址
https://www.x-mol.com

### 网站描述
X-MOL化学资讯平台，由北京衮雪科技有限公司创办，对化学工作者免费开放。（from 官网）
总之是生物，物理，化学等学科的文献综合整合类平台。

### 需要生成什么内容？

- [ ]  行业资讯栏目的新闻更新，标题+摘要（https://www.x-mol.com/news/[编号]）
- [ ] 对应的某一期刊的最新内容更新，期刊标题+文章标题+摘要+附图（https://www.x-mol.com/paper/[分类号]/[文献编号]） 
- [ ]  x-mol招聘（非必须） （https://www.x-mol.com/recruitment/jobs）

### 额外描述
需要RSS的原因是有些期刊本身的RSS地址非常难连接……
比如ACS旗下的各大期刊，使用的feeds.feedburner.com的订阅源国内很难连上
另外既然有整合性的平台，那就干脆懒一点不是更好吗x

**Comment by Roy-yu-sdu** [comment]
另外给个提示的话就行……我会自力更生试一下（

**Comment by yefoenix** [comment]
@Roy-yu-sdu http://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze
