### ISSUE TITLE
部分 ’站酷个人主页‘ 无法订阅

### ISSUE THREAD

**Issue by XSpark91** [DIYgod/RSSHub#3272]
### 路由地址

路由: /zcool/user/:uname

举例: https://rsshub.app/zcool/user/baiyong

参数:
uname, 必选 - 个性域名前缀

例如: 站酷的个人主页 https://baiyong.zcool.com.cn 对应 rss 路径 /zcool/user/baiyong

### 预期是什么？

所有 站酷的个人主页 都能订阅

### 实际发生了什么？

只有部分个人主页能够订阅

原因是：
部分 个人主页 的地址并不是这种格式 [https://baiyong.zcool.com.cn/](https://baiyong.zcool.com.cn/) ，而是 [https://www.zcool.com.cn/u/568339](https://www.zcool.com.cn/u/568339)

另外，
第二种格式中的 数字ID 可以在 审查元素 中的 data-id 获得

**Comment by SettingDust** [comment]
https://api.zcool.com.cn/v2/api/u/568339
