### ISSUE TITLE
发布时间相同时播客排序不正确 不小心关闭了

### ISSUE THREAD

**Issue by fangpidedongsun** [DIYgod/RSSHub#3287]
### 路由地址
https://rsshub.app/ximalaya/album/12581994/all
https://rsshub.app/ximalaya/album/220565/all
https://rsshub.app/ximalaya/album/20665610/all
https://rsshub.app/ximalaya/album/11830493/all
https://rsshub.app/ximalaya/album/18666936/all
https://rsshub.app/ximalaya/album/16716447/all
https://rsshub.app/ximalaya/album/16580039/all
https://rsshub.app/ximalaya/album/16642710/all

https://rsshub.app/ncm/djradio/350331992
https://rsshub.app/ncm/djradio/1787001
https://rsshub.app/ncm/djradio/978035

### 预期是什么？
在iOS系统的播客上通过URL添加此内容，并且把播放顺序调整为从旧到新，播客上的播放顺序与实际集数一致

### 实际发生了什么？
和issue #2795 出现的问题一样
由于发布日期和时间都相同，造成了播客上的排序混乱，应该是1,2,3,4.......339的顺序变成了23,22,21......1,42,41,40.....24,86,85.......这样的顺序

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
播客app的问题，rsshub 做不了什么
