### ISSUE TITLE
「抖音 标签」RSS 需求

### ISSUE THREAD

**Issue by XSpark91** [DIYgod/RSSHub#3298]
### 网站地址

https://www.iesdouyin.com/share/challenge/1592824105719812/

### 网站描述

抖音按 标签 生成内容的页面

### 需要生成什么内容？

希望能订阅到 标签页面 里的内容

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
