### ISSUE TITLE
1draw  #深夜の真剣お絵描き60分一本勝負

### ISSUE THREAD

**Issue by BAKAOLC** [DIYgod/RSSHub#3304]
### 网站地址
http://1draw.aqn.jp/0

### 网站描述
推特午夜绘画60min的tag（#深夜の真剣お絵描き60分一本勝負）投稿一览

### 需要生成什么内容？

- [ ] 投稿列表

### 额外描述
网站地址最后的0是距今的日期数，为0即为当天的投稿一览页，为1即为上一日的投稿一览页，最大支持到6

**Comment by Jeason0228** [comment]
数据资源http://1draw.aqn.jp/1

网站地址最后的0是距今的日期数，为0即为当天的投稿一览页，为1即为上一日的投稿一览页，最大支持到6

![企业微信截图_20191021204624](https://user-images.githubusercontent.com/44083849/67206262-e2688e80-f443-11e9-8d5f-88dde08dfd2e.png)

**Comment by BAKAOLC** [comment]
该项目是日本时间每天晚上10点开始的，数据页0通常会在此时间后才开始更新，所以0也是有一定需求的

**Comment by Jeason0228** [comment]
@BAKAOLC 这是只输出0最新的就好了吧?

**Comment by Jeason0228** [comment]
@yefoenix @kt286 @DIYgod 有什么方法可以把页面html里的js 直接转成可用的数据吗?(eval?)
我之前处理szse的都是当字符串然后用正则去匹配...感觉方法比较笨

**Comment by BAKAOLC** [comment]
> @BAKAOLC 这是只输出0最新的就好了吧?

嗯，只有0也已经满足需求了

**Comment by cssxsh** [comment]
> @yefoenix @kt286 @DIYgod 有什么方法可以把页面html里的js 直接转成可用的数据吗?(eval?)
> 我之前处理szse的都是当字符串然后用正则去匹配...感觉方法比较笨

正则匹配就够用了吧，最多将js里的函数实例化 new Function(funcparam, ...,  bodystring)
bodystring是**函数体**里面的内容

**Comment by DIYgod** [comment]
不如直接做 Twitter tag 的 RSS...

**Comment by BAKAOLC** [comment]
但是推特api对于大部分人来说现在完全申请不出，如果本地部署的话推特api基本无用，直接通过RSSHub服务器的话效果太差
