### ISSUE TITLE
[Suggestion] Avoid adding tags not directly related to the feature of this project

### ISSUE THREAD

**Issue by Plausible0Bug** [DIYgod/RSSHub#3308]
Hi, I would like to first thank you for contributing such a great project, it had been proven quite helpful during my researching on specific topic.

One thing does come to my attention is this repo had been labeled with a lot of tags not directly related with its use cases(feature wise), although there seemed to be some unofficial support going on in the issue tracker.

To avoid further confusion, I personally would suggest you remove those irrelavent tags.

To gain more attraction and become widely awared of, would you please kindly try prompt the project via Wikipedia, Reddit, StackOverflow or even YouTube and GitHub yellow pages such as https://github.com/awesome-selfhosted/awesome-selfhosted ?

**Comment by DIYgod** [comment]
Thanks for your suggestion.

But after checking those tags, I really think those tags are all directly related to this project, and I don't understand what does `unofficial support` means.

For example:
`twitter` is related to https://github.com/DIYgod/RSSHub/tree/master/lib/routes/twitter https://docs.rsshub.app/en/social-media.html#twitter
`instagram` is related to https://github.com/DIYgod/RSSHub/tree/master/lib/routes/instagram https://docs.rsshub.app/en/social-media.html#instagram
