### ISSUE TITLE
【东方财富网-营业部历史交易明细】Rss Wanted——希望支持推送营业部数据的更新

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3313]
### 网站地址
http://data.eastmoney.com/stock/lhb/yyb/营业部id.html，
例如
 [西藏东方财富证券股份有限公司拉萨团结路第二证券营业部](https://data.eastmoney.com/stock/lhb/yyb/80463351.html) ，id是 80463351
### 网站描述
东方财富网 > 数据中心 > 龙虎榜单 > 营业部历史交易明细
### 需要生成什么内容？

- [ ] 希望支持推送营业部数据的更新

### 额外描述

希望推送的参数为

序号 | 代码 | 名称 | 相关 | 日期 | 营业部买入额(万) | 营业部卖出额(万) | 买卖净额(万) | 上榜原因
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by hillerliao** [comment]
这种结构化数据，不太适合用rss来浏览啊。

**Comment by KwToPA** [comment]
> tushare

tushare 没用过啊。rss支持定时推送，这点比较好
