### ISSUE TITLE
【南京航空航天大学】HTTP 412

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub#3317]
### 路由地址
/nuaa/jwc/all
/nuaa/yjsy/latest
南京航空航天大学下的全部路由

### 预期是什么？
正常工作

### 实际发生了什么？
返回HTTP 412错误

### 部署相关信息
Demo与自建均HTTP412

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
使用VPS(校内、国内、国外)进行 curl http://www.graduate.nuaa.edu.cn/ (南航研究生院的网址) 同样返回 http 412 错误。
Chrome F12开发者模式下，在校外网络访问时发现网站返回HTTP 412时，浏览器执行了一段js代码后，浏览器重新跳转到HTTP200。随后刷新访问均是HTTP 200。
使用POSTMAN模拟时，发现请求头携带了cookies，一旦修改请求头参数，使得cookies失效后，Chrome浏览器就会重新出现HTTP412错误。
因为本人技术水平有限，这个BUG修不来，求大佬支援。

**Comment by junfengP** [comment]
[pr3337](https://github.com/DIYgod/RSSHub/pull/3337)使用chromeheadless修复该问题
但demo https://rsshub.app/nuaa/jwc/all 以及使用docker-compose自建均显示下图
<br>
demo:
![demo](https://user-images.githubusercontent.com/15406392/70434843-46144d00-1ac0-11ea-842b-c041b9ad847f.png)
<br>
docker-compose自建：
![docker-compose自建](https://user-images.githubusercontent.com/15406392/70434862-56c4c300-1ac0-11ea-99b4-7a795d9a60de.png)

**Comment by seiry** [comment]
目测是waf又升级了 （但是这次又赶上了1212咋就这么敲呢，搞完大促有空看下吧

**Comment by junfengP** [comment]
> 目测是waf又升级了 （但是这次又赶上了1212咋就这么敲呢，搞完大促有空看下吧

其实半个月前就试了demo一次，就不行。怕是管理员盯上pr了。

**Comment by seiry** [comment]
> > 目测是waf又升级了 （但是这次又赶上了1212咋就这么敲呢，搞完大促有空看下吧
> 
> 其实半个月前就试了demo一次，就不行。怕是管理员盯上pr了。

emmmmm 有个很玄学的问题，我本地虚拟机，国内阿里云，国外轻骚跑了一圈，都是没问题的（除了轻骚会偶尔超时以外 
![image](https://user-images.githubusercontent.com/4397354/71304747-9dda7e80-2405-11ea-9dea-b80bf0709ab4.png)

**Comment by seiry** [comment]
> > 目测是waf又升级了 （但是这次又赶上了1212咋就这么敲呢，搞完大促有空看下吧
> 
> 其实半个月前就试了demo一次，就不行。怕是管理员盯上pr了。

主站https://rsshub.app/nuaa/jwc/default会挂也不是因为waf的原因，貌似是部署的问题导致的chromeheadless出了啥问题，我本地复现不了

**Comment by junfengP** [comment]
> > > 目测是waf又升级了 （但是这次又赶上了1212咋就这么敲呢，搞完大促有空看下吧
> > 
> > 
> > 其实半个月前就试了demo一次，就不行。怕是管理员盯上pr了。
> 
> 主站[https://rsshub.app/nuaa/jwc/default会挂也不是因为waf的原因，貌似是部署的问题导致的chromeheadless出了啥问题，我本地复现不了](https://rsshub.app/nuaa/jwc/default%E4%BC%9A%E6%8C%82%E4%B9%9F%E4%B8%8D%E6%98%AF%E5%9B%A0%E4%B8%BAwaf%E7%9A%84%E5%8E%9F%E5%9B%A0%EF%BC%8C%E8%B2%8C%E4%BC%BC%E6%98%AF%E9%83%A8%E7%BD%B2%E7%9A%84%E9%97%AE%E9%A2%98%E5%AF%BC%E8%87%B4%E7%9A%84chromeheadless%E5%87%BA%E4%BA%86%E5%95%A5%E9%97%AE%E9%A2%98%EF%BC%8C%E6%88%91%E6%9C%AC%E5%9C%B0%E5%A4%8D%E7%8E%B0%E4%B8%8D%E4%BA%86)

部署方式是： docker-compose

**Comment by junfengP** [comment]
> [pr3337](https://github.com/DIYgod/RSSHub/pull/3337)使用chromeheadless修复该问题
> 但demo https://rsshub.app/nuaa/jwc/all 以及使用docker-compose自建均显示下图
> 
> 
> demo:
> ![demo](https://user-images.githubusercontent.com/15406392/70434843-46144d00-1ac0-11ea-842b-c041b9ad847f.png)
> 
> 
> docker-compose自建：
> ![docker-compose自建](https://user-images.githubusercontent.com/15406392/70434862-56c4c300-1ac0-11ea-99b4-7a795d9a60de.png)

仔细看了一下，原来教务处的默认参数改了，自建访问教务处已经没有问题，但是研究生院和计算机学院依然报错。
打开代码看了一下
`lib/routes/universities/nuaa/utils/pypasswaf.js`
```
const host = 'http://aao.nuaa.edu.cn/'; 
```
绕过WAF的代码写死了host，实际使用时研究生院和计算机学院的网站并不是这个，猜测是这个原因。

@seiry

**Comment by junfengP** [comment]
在阿里云16G自建，就一切正常， 可能是我国外的VPS内存太小了吧。就这样吧，不折腾了。
