### ISSUE TITLE
【RSS Request】请求收录树莓派实验室

### ISSUE THREAD

**Issue by mrguowei** [DIYgod/RSSHub#3322]
### 网站地址
http://shumeipai.nxez.com
### 网站描述
一个树莓派相关内容的网站
### 需要生成什么内容？

- [ 1 ] 首页文章收录

### 额外描述
- [ Optional ] 热门导航和入门教程分类里面有更多的文章分类，可以加入依据标签的RSS流

**Comment by yefoenix** [comment]
@mrguowei http://shumeipai.nxez.com/tag/software/feed
http://shumeipai.nxez.com/feed

**Comment by mrguowei** [comment]
不好意思，原来人家自己有做feed，我用Reeder自带的搜索了一下没搜到，网页上也没看到有rss标志以为他们没做feed。
