### ISSUE TITLE
【深圳证券交易所-问询函件】Rss wanted- 望支持推送 关注函 谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3323]
### 网站地址
[http://www.szse.cn/disclosure/supervision/inquire/](http://www.szse.cn/disclosure/supervision/inquire/)
### 网站描述
证券交易所

### 需要生成什么内容？

主板 中小企业板 创业板的关注函希望能够按日期推送。

### 额外描述

主板 http://www.szse.cn/disclosure/supervision/inquire/?tabkey=tab1
中小板 http://www.szse.cn/disclosure/supervision/inquire/?tabkey=tab2
创业板 http://www.szse.cn/disclosure/supervision/inquire/?tabkey=tab3

**Comment by Jeason0228** [comment]
资源api
http://www.szse.cn/api/report/ShowReport/data?SHOWTYPE=JSON&CATALOGID=main_wxhj&TABKEY=【tab1】&random=0.19028832310461863

【tab1】: tab2 tab3
