### ISSUE TITLE
【上海证券交易所-监管问询】Rss wanted- 望支持推送 关注函 谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3324]
### 网站地址
http://www.sse.com.cn/disclosure/credibility/supervision/inquiries/
### 网站描述
证券交易所
### 需要生成什么内容？

关注函希望能够按日期推送。

### 谢谢

**Comment by Jeason0228** [comment]
api资源

http://query.sse.com.cn/commonSoaQuery.do?jsonCallBack=jsonpCallback20309&siteId=28&sqlId=BS_KCB_GGLL&extGGLX=&stockcode=&channelId=10743%2C10744%2C10012&extGGDL=&order=createTime%7Cdesc%2Cstockcode%7Casc&isPagination=true&pageHelp.pageSize=15&pageHelp.pageNo=1&pageHelp.beginPage=1&pageHelp.cacheSize=1&pageHelp.endPage=5&type=&_=1572002115736
