### ISSUE TITLE
演示地址 pixiv 不可用

### ISSUE THREAD

**Issue by Jeffz615** [DIYgod/RSSHub#3325]
### 额外信息（日志、报错等）
Url: https://rsshub.app/pixiv/ranking/day

错误信息：pixiv not login

**Comment by DIYgod** [comment]
看起来相同的问题又出现了 https://github.com/DIYgod/RSSHub/issues/2982 和 https://github.com/upbit/pixivpy/issues/83

**Comment by Jeffz615** [comment]
> 看起来相同的问题又出现了 #2982 和 [upbit/pixivpy#83](https://github.com/upbit/pixivpy/issues/83)

是日期时间的格式问题。
pixivpy3\api.py的local_time改成
`local_time = datetime.utcnow().strftime( '%Y-%m-%dT%H:%M:%S+00:00' )`
就能正常登陆了

同理，把 lib/routes/pixiv/token.js 的 localTime 格式改下应该就可以了

**Comment by Mikubill** [comment]
ref: https://github.com/upbit/pixivpy/issues/92#issuecomment-546011823

**Comment by anadano** [comment]
蹲着等更新

**Comment by ivone-liu** [comment]
求大神更新 ;)

**Comment by DIYgod** [comment]
Fixed. 感谢 @Jeffz615 @Mikubill
