### ISSUE TITLE
Nature、PNAS和eLife的rss请求

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#3331]
### 网站地址
https://www.nature.com/nature/research
### 网站描述
Nature Latest Research
### 需要生成什么内容？

标题+简介

**Comment by emdoe** [comment]
想请教一下，作者的格式会希望是怎样呢？

**Comment by tomatomash** [comment]
> 想请教一下，作者的格式会希望是怎样呢？

感谢，其实平常浏览的时候都没在意过作者，所以其实不显示也行hhh。
现在可以再增加一个Nature Neuroscience（https://www.nature.com/neuro/research）的rss吗？

**Comment by emdoe** [comment]
> 现在可以再增加一个Nature Neuroscience（ https://www.nature.com/neuro/research ）的rss吗？

No problem. 有时间我做一下这两个，会争取把作者的显示效果做好

**Comment by emdoe** [comment]
> ### 需要生成什么内容？
> 标题+简介

我个人觉得不如 *标题 + 作者 + 摘要*，简介过于简略了。或者 *标题 + 作者 + 简介 + 摘要* 也好，但是我看了一下 Machine Intelligence 的做法，我个人觉得用 RSS 看全篇 Paper 恐怕效果并不好（所以是否有必要将原文中 LaTeX 转换成公式的图片呢？）

是否可以分享一下你的看法？

**Comment by tomatomash** [comment]
我平常浏览的话，习惯上会这样，标题+作者+简介+摘要，全文其实不必，rss搞得简洁明了才像rss，纯文字即可，图片也不必。谢谢大佬

**Comment by emdoe** [comment]
以及，是否需要 eLife 呢？

**Comment by tomatomash** [comment]
好呀好呀，大佬是做主页的还是某一领域？我是神经方向的( https://elifesciences.org/subjects/neuroscience  )

**Comment by emdoe** [comment]
> 做主页的还是某一领域？
大佬不敢当，综合和细分方向的 RSS 都会做的。

**Comment by emdoe** [comment]
话说你也许可以考虑修改一下标题？这次总共做了 Nature, PNAS, 和 eLife。其中像 Nature Neuroscience 这样的应该可以直接修改成更普适一点的——但我没去看各个子刊是不是显示效果都一样（如果有需要可以 check 一下），也不确定希望订阅各个子刊的朋友是否需要都是一样的效果（比如 Machine Intelligence 那边就希望全文输出？），所以就没有适配。

另外需要说明的是，比如 eLife 和 Nature 我个人觉得有简介和 abstract 同时存在的时候如果 abstract 字太大会很干扰，所以把相应的 abstract 的字体都有修小，并且居中显示，这只是我个人调整过后觉得看起来比较舒服的方案，如有别的想法也欢迎提供建议。

**Comment by LogicJake** [comment]
@emdoe machine intelligence是因为我拿自己电脑开发的时候，发现学校ip可以看全文，所以写的时候按照全文爬的。后来部署才发现不行

**Comment by emdoe** [comment]
@LogicJake 
> 学校ip可以看全文，所以写的时候按照全文爬的。后来部署才发现不行
呃呃，我也偷懒没有在服务器上部署测试…摘要讲道理应该是能爬到的吧 😂？

所以之前那个还需要保留爬全文的设置吗？或者是否干脆提供两个选项给大家(摘要 / 全文输出)？（尽管我觉得用 RSS 看全文这个主意并不好）

另外你的全文输出没有处理 LaTeX 公式，你也许可以考虑利用 `https://latex.codecogs.com/{format}.latex?{formula}` 这个地址来生成图片去替换无法渲染的公式。其中 `{format}` 比如可以替换成 `png` 或者 `gif`。

以及，我有考虑过要不要在文章末尾或者提供一个版本直接将网址指向 sci-hub，但个人觉得这种 piracy 行为可能还是欠妥？

**Comment by LogicJake** [comment]
@emdoe 都看不到全文了，还考虑啥latex😂😂

**Comment by emdoe** [comment]
也许会有人在校园网内部署 🤔️？

**Comment by tomatomash** [comment]
> 以及，我有考虑过要不要在文章末尾或者提供一个版本直接将网址指向 sci-hub，因为我猜即使我不这么做有些人可能未来还是会提交类似这种 pull request…但个人觉得这种 piracy 行为可能还是欠妥？

其实我觉得没太大必要，而且不是所有文章都能用sci-hub搜到。这工作就像滚雪球一样，然而基本需求只是快速获取资讯，而不是又被信息海洋淹没

**Comment by emdoe** [comment]
> 然而基本需求只是快速获取资讯，而不是又被信息海洋淹没

你可能误会我的意思啦，这个与信息是否过载应该是无关的。我那段主要在说我不添加的考量（即使我猜测以后可能会有人去添加，希望到时候可以参考或者再讨论咯）
