### ISSUE TITLE
央视新闻获取不了更新

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#3332]
### 路由地址
https://rsshub.app/cctv/china
### 实际发生了什么？
thunderbird 收不到文章了.
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by KwToPA** [comment]
类似问题，我把更新时间设置成30分钟，但基本上是在一天内某个时刻（不一致）成功刷新，一次更新好几十条。

**Comment by Jeason0228** [comment]
我是npm/yarn 自建的 2019年10月30日13:22:18测试还是可以正常获取.
![企业微信截图_20191030132254](https://user-images.githubusercontent.com/44083849/67831216-68f22f80-fb18-11e9-8718-3eab4965699e.png)

**Comment by DIYgod** [comment]
目测网络问题，已恢复
