### ISSUE TITLE
lofter路由BUG，一直无法访问

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#3342]
### 路由地址
https://rsshub.app/lofter/tag/100%E4%B8%AA%E5%9F%8E%E5%B8%82%E6%8B%8D%E6%91%84%E5%9B%BE%E9%89%B4/total.rss
### 预期是什么？
正常访问、订阅
### 实际发生了什么？
lofter路由BUG，一直无法访问。Error 504 Ray ID: 52caaa2ece6e983f • 2019-10-28 05:57:08 UTC
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
已恢复
