### ISSUE TITLE
智联的路由似乎有问题

### ISSUE THREAD

**Issue by fucao** [DIYgod/RSSHub#3343]
### 路由地址
https://rsshub.app/zhilian/%E5%8F%B0%E5%B7%9E/JavaScript
### 预期是什么？
返回正确内容
### 实际发生了什么？
错误提示
### 部署相关信息
docker compose 部署
第一个是官网的，第二个是我自己的（刚刚更新的）

![image](https://user-images.githubusercontent.com/15061002/67658731-64513e00-f995-11e9-9344-042492040ec2.png)
![image](https://user-images.githubusercontent.com/15061002/67658747-716e2d00-f995-11e9-8d4a-958f3882cc0e.png)

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by Jeason0228** [comment]
npm /yarn 自建正常
![企业微信截图_20191030132254](https://user-images.githubusercontent.com/44083849/67831263-a787ea00-fb18-11e9-868f-add22187b775.png)

**Comment by ivone-liu** [comment]
本地NPM同样遇到问题

> error: Request https://fe-api.zhaopin.com/c/i/city-page/user-city?ipCity=%E5%8C%97%E4%BA%AC fail, retry attempt #1: RequestError: socket hang up
> 
> error: Request https://fe-api.zhaopin.com/c/i/city-page/user-city?ipCity=%E5%8C%97%E4%BA%AC fail, retry attempt #2: RequestError: socket hang up
> 
> error: Error in /zhilian/%E5%8C%97%E4%BA%AC/JavaScript: socket hang up: target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.

但是如果用浏览器和postman请求地址，能得到正确返回值

![postman返回](https://i.loli.net/2019/11/04/dqFGymNpjPLfO1V.png)

**Comment by fucao** [comment]
有人能解决下吗。。。。
