### ISSUE TITLE
vol.moe路由问题

### ISSUE THREAD

**Issue by anadano** [DIYgod/RSSHub#3350]
### 路由地址
https://rsshub.app/vol/finsh
### 预期是什么？
显示vol.moe的完结漫画
### 实际发生了什么？
实际出现了连载中漫画

**Comment by anadano** [comment]
@CoderTonyChan 
大佬，求助

**Comment by CoderTonyChan** [comment]
> @CoderTonyChan
> 大佬，求助

文档不小心写错了 应该是https://rsshub.app/vol/finish 

https://github.com/DIYgod/RSSHub/pull/3352
