### ISSUE TITLE
PT开放注册邀请码

### ISSUE THREAD

**Issue by fucao** [DIYgod/RSSHub#3357]
### 网站地址
http://www.ptyqm.com/category/kfyqzc/
### 网站描述
PT网站开放注册邀请
### 需要生成什么内容？
最新的PT网站免费注册邀请

**Comment by yefoenix** [comment]
http://www.ptyqm.com/category/kfyqzc/feed/

**Comment by LakeishaKowalczyk** [comment]
@DIYgod 
可不可以智能检测未知的源，像这种直接在链接里插入 /feed  /feeds 的家伙直接秒

在「( ´･･)ﾉ(._.`) 当前页面没有检测到 RSS」后面加一个「开启 X 光透视扫描模式」按钮

**Comment by DIYgod** [comment]
> [http://www.ptyqm.com/category/kfyqzc/feed](http://www.ptyqm.com/category/kfyqzc/feed/)

这个是在哪找到的...

**Comment by LakeishaKowalczyk** [comment]
> 
> 
> > [http://www.ptyqm.com/category/kfyqzc/feed](http://www.ptyqm.com/category/kfyqzc/feed/)
> 
> 这个是在哪找到的...
可能是审查代码搜索 feed，或者是用这个网站的老司机，或者 RSS 老司机暴力破解

**Comment by yefoenix** [comment]
@DIYgod 看一眼页面源码是基于WordPress的，直接加 /feed/ 验证一下就行了，大部分都不关feed输出

**Comment by LakeishaKowalczyk** [comment]
> 
> 
> > 可不可以智能检测未知的源，像这种直接在链接里插入 /feed /feeds 的家伙直接秒
> > 在「( ´･･)ﾉ(._.`) 当前页面没有检测到 RSS」后面加一个「开启 X 光透视扫描模式」按钮
> 
> 这种按钮平时应该不会有人去点的，默认的话消耗又太大了，这种情况很少感觉没有必要

多啊多啊，就是把 RSS 老司机多年的经验，转换成规则，用代码实现，给小白和懒人用，比如我这种

**Comment by DIYgod** [comment]
> 多啊多啊，就是把 RSS 老司机多年的经验，转换成规则，用代码实现，给小白和懒人用，比如我这种

也可以吧，然后还可以加上 https://github.com/DIYgod/RSSHub-Radar/issues/30#issuecomment-520210533 的结果

可以到 RSSHub-Radar 仓库提交一个 issue：https://github.com/DIYgod/RSSHub-Radar/issues

**Comment by LakeishaKowalczyk** [comment]
> 
> 
> > 多啊多啊，就是把 RSS 老司机多年的经验，转换成规则，用代码实现，给小白和懒人用，比如我这种
> 
> 也可以吧，然后还可以加上 [DIYgod/RSSHub-Radar#30 (comment)](https://github.com/DIYgod/RSSHub-Radar/issues/30#issuecomment-520210533) 的结果
> 
> 可以到 RSSHub-Radar 仓库提交一个 issue：https://github.com/DIYgod/RSSHub-Radar/issues

HHH，你说得对

**Comment by fucao** [comment]
TTRSS里没法订阅怎么办？
![image](https://user-images.githubusercontent.com/15061002/67861073-67e1f200-fb5a-11e9-9527-c45e60f4ec51.png)

**Comment by fucao** [comment]
TTRSS无法订阅，inoreader也不行
![image](https://user-images.githubusercontent.com/15061002/67862719-99a88800-fb5d-11e9-9601-501d88ce9a1a.png)

**Comment by cssxsh** [comment]
> TTRSS无法订阅，inoreader也不行
> ![image](https://user-images.githubusercontent.com/15061002/67862719-99a88800-fb5d-11e9-9601-501d88ce9a1a.png)
inoreader可以阿

**Comment by DIYgod** [comment]
Reeder 也不行

**Comment by yefoenix** [comment]
把 http://www.ptyqm.com/category/kfyqzc/feed/ 这个链接放到 W3C 的 Feed validator 去检测，提示「It looks like this is a web page, not a feed.」，但是把页面上的文字内容拷贝过去直接检测，其实是能通过检测的。
这能是什么情况呢……Headers 的问题？

**Comment by NeverBehave** [comment]
> 把 http://www.ptyqm.com/category/kfyqzc/feed/ 这个链接放到 W3C 的 Feed validator 去检测，提示「It looks like this is a web page, not a feed.」，但是把页面上的文字内容拷贝过去直接检测，其实是能通过检测的。
> 这能是什么情况呢……Headers 的问题？

确实是网页：
`curl http://www.ptyqm.com/category/kfyqzc/feed/`
```
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, post-check=0, pre-check=0"/><meta http-equiv="Connection" content="Close"/><script type="text/javascript">function stringToHex(str){var val="";for(var i = 0; i < str.length; i++){if(val == "")val = str.charCodeAt(i).toString(16);else val += str.charCodeAt(i).toString(16);}return val;}function YunSuoAutoJump(){ var width =screen.width; var height=screen.height; var screendate = width + "," + height;var curlocation = window.location.href;if(-1 == curlocation.indexOf("security_verify_")){ document.cookie="srcurl=" + stringToHex(window.location.href) + ";path=/;";}self.location = "/category/kfyqzc/feed/?security_verify_data=" + stringToHex(screendate);}</script><script>setTimeout("YunSuoAutoJump()", 50);</script></head><!--2020-03-01 10:48:50--></html>
```

会跳转到：http://www.ptyqm.com/category/kfyqzc/feed/?security_verify_data=313434302c393030

应该是web防火墙的问题
