### ISSUE TITLE
【RSS Request】王者荣耀 - 新闻列表

### ISSUE THREAD

**Issue by hifocus** [DIYgod/RSSHub#3370]
### 网站地址
https://pvp.qq.com/web201706/newsindex.shtml

### 网站描述
王者荣耀新闻、公告、活动、赛事发布

### 需要生成什么内容？
- [ ] 新闻
- [ ] 公告
- [ ] 活动
- [ ] 赛事

**Comment by Jeason0228** [comment]
https://apps.game.qq.com/wmp/v3.1/?p0=18&p1=searchNewsKeywordsList&order=sIdxTime&r0=cors&type=iTarget&source=app_news_search&pagesize=12&page=1&id=1760


对应data-channelid
<div class="art_tabtitle clearfix" id="tab">
<a href="javascript:;" class="item curr" title="热门" data-newsid="hot" data-channelid="1760">热门</a>
<a href="javascript:;" class="item" title="新闻" data-newsid="655" data-channelid="1761">新闻</a>
 <a href="javascript:;" class="item" title="公告" data-newsid="656" data-channelid="1762">公告</a>
<a href="javascript:;" class="item" title="活动" data-newsid="1139" data-channelid="1763">活动</a>
   <a href="javascript:;" class="item" title="赛事" data-newsid="658" data-channelid="1764">赛事</a>
          </div>
