### ISSUE TITLE
PMCAFF 精选 RSS 需求

### ISSUE THREAD

**Issue by sfyumi** [DIYgod/RSSHub#3373]
### 网站地址
https://coffee.pmcaff.com/

### 网站描述
互联网产品社区
### 需要生成什么内容？
- [ ] PMCAFF 精选

### 额外描述
PMCAFF 已经提供了 rss 输出，但是她们提供的输出格式有问题，内容里混杂了 HTML 代码，阅读体验很不好，RSSHub 可以输出格式良好的 rss

![image](https://user-images.githubusercontent.com/1942488/68065057-887a9980-fd5e-11e9-8dd7-82670b8a41d9.png)

**Comment by Jeason0228** [comment]
Request URL: https://coffee.pmcaff.com/list
Request Method: POST

FORM DATApage=1&feed_sum=15&type=2&times=0&user_id=0

**Comment by sfyumi** [comment]
> Request URL: https://coffee.pmcaff.com/list
> Request Method: POST
> 
> FORM DATA
> page=1&feed_sum=15&type=2&times=0&user_id=0

RSS 阅读器很少支持 post 的吧，我还没见过。

**Comment by Jeason0228** [comment]
> > Request URL: https://coffee.pmcaff.com/list
> > Request Method: POST
> > FORM DATA
> > page=1&feed_sum=15&type=2&times=0&user_id=0
> 
> RSS 阅读器很少支持 post 的吧，我还没见过。

有的.你在vscod里 搜索整个工程的routerjs文件...也有不少post....比如36kr article

**Comment by yefoenix** [comment]
@sfyumi 楼上写的这个是编写路由用的，不是直接放阅读器里


@Jeason0228 他说直接贴阅读器里确实没有支持的……

**Comment by Jeason0228** [comment]
> @sfyumi 楼上写的这个是编写路由用的，不是直接放阅读器里
> 
> @Jeason0228 他说直接贴阅读器里确实没有支持的……

恩是的哈，我发的post是方便编写路由用的，不是For阅读器的
这个网站的feed的确有点奇怪

**Comment by sfyumi** [comment]
@Jeason0228 @yefoenix  明白了，多谢
