### ISSUE TITLE
instagram user路由 无法爬取

### ISSUE THREAD

**Issue by tmdjiuji** [DIYgod/RSSHub#3375]
### 路由地址
https://rsshub.app/instagram/user/diygod
### 预期是什么？
显示diygod的instagram的rss信息
### 实际发生了什么？
直接跳转到google的404错误页面
无报错信息

### 额外信息（日志、报错等）
无

**Comment by yefoenix** [comment]
@tmdjiuji Instagram反爬严格，自建服务可以降低被反爬的几率。

提issue之前请先进行搜索，查看已有issue……
