### ISSUE TITLE
RSSHub Selector — 制作一个 RSS 源不应该这么难

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [DIYgod/RSSHub#3377]
对 RSS 最完美的设想之一就是，随见随划，随划随收．只需小手一抖，视野所见的一切内容，瞬间收进 RSS 囊中

请问可不可以增加基于 Xpath 或 CSS 之类的元素选择器，鼠标点划一下，就可以制作一些简单的，或者辅助制作复杂的订阅源．类似 [Distill Web Monitor](https://addons.mozilla.org/en-US/firefox/addon/distill-web-monitor-ff/) 或 ABP

做了一个动图示意，以这个  https://github.com/DIYgod/RSSHub/issues/3353 为例
（动图有点大（6M）加载估计有点慢）
![xx](https://user-images.githubusercontent.com/14090545/68082699-b3e2ae80-fe5a-11e9-85cd-fbccf582cfa4.gif)

![2019-11-03_164400](https://user-images.githubusercontent.com/14090545/68082715-decd0280-fe5a-11e9-93c9-b47b57b412f9.png)

**Comment by SettingDust** [comment]
@LakeishaKowalczyk 我做了啊？？？看看文档？？？

**Comment by LakeishaKowalczyk** [comment]
@SettingDust 
你是指的什么，DLsite 的中文作品源，还是「元素选择器」？

**Comment by Jeason0228** [comment]
我看diydog的标题是 "RSSHub Radar — 订阅一个 RSS 源不应该这么难"
咋你截图是篡改过吗"RSSHub Radar — 【制作】一个 RSS 源不应该这么难"

**Comment by yefoenix** [comment]
https://docs.rsshub.app/joinus/#tian-jia-jiao-ben-lu-you
