### ISSUE TITLE
Dockerfile.arm32v7：建议alpine使用国内的镜像源

### ISSUE THREAD

**Issue by Lennox-Elaphurus** [DIYgod/RSSHub#3381]
Dockerfile.arm32v7中的第8行

RUN apk add dumb-init git python vips-dev fftw-dev build-base --update-cache --repository https://alpine.global.ssl.fastly.net/alpine/edge/community/ --repository https://alpine.global.ssl.fastly.net/alpine/edge/main

https://alpine.global.ssl.fastly.net国内难以正常访问，建议使用清华大学的镜像源https://mirrors.tuna.tsinghua.edu.cn/

即改为

RUN apk add dumb-init git python vips-dev fftw-dev build-base --update-cache --repository https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/community/ --repository https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/main

**Comment by SettingDust** [comment]
@Lennox-Elaphurus 不止国内用，请自行修改构建image

**Comment by Lennox-Elaphurus** [comment]
谢谢提醒。
