### ISSUE TITLE
自定义调试信息

### ISSUE THREAD

**Issue by eMUQI** [DIYgod/RSSHub#3383]
### 这是一个什么样的功能？
自定义调试信息
### 这个功能可以解决什么问题？
调试信息有可能会泄露部分隐私。
### 额外描述
希望能提供关闭hot paths:和hot ip的选项。

**Comment by yefoenix** [comment]
RTFM https://docs.rsshub.app/install/#qi-ta-ying-yong-pei-zhi

**Comment by iFwu** [comment]
希望能默认关闭debug信息@DIYgod
目前发现一些自有部署节点通过DEBUG信息泄露了IP地址。
