### ISSUE TITLE
半岛中文网，木有女装 =。=

### ISSUE THREAD

**Issue by onlyone-lee** [DIYgod/RSSHub#3384]
### 网站地址
https://chinese.aljazeera.net/
### 网站描述
新闻
### 需要生成什么内容？
全文以及图片
- [ ] 内容一
- [ ] 内容二

**Comment by hoilc** [comment]
https://feedx.co/rss/aljazeera.xml

feedx站长提供，在RSSHub没有添加前，可以先用这个

**Comment by onlyone-lee** [comment]
谢谢你啦😀
