### ISSUE TITLE
Javlibrary RSS Wanted

### ISSUE THREAD

**Issue by syhsyh9696** [DIYgod/RSSHub#34]
# 能否支持[Javlibrary](http://www.javlibrary.com)

包括不限于  
- 热门影片
- 最近讨论
- 高评价
- 演员排行榜

(逃

**Comment by biezhi** [comment]
大兄弟，这个。。。。

**Comment by capparun** [comment]
High priority! YES!

**Comment by coderfox** [comment]
I have written a simple parser for JAVLibrary list and video page:

<https://gist.github.com/coderfox/3c2e2edbe42c75aa73151b80a8389145>

**Comment by coderfox** [comment]
@DIYgod 

There is a problem to settle: 

Based on the fact that

- Either image or publish date can be retrieved through one request to JavLibrary
- For AV details, each AV requires a request to JavLibrary

Server pressure should be considered when building feed with AV details,

So which level of information below should the feed provide:

- only title and date ( 1 request )
- title, image and date ( 2 requests )
- title, image, date and details ( 10+ requests )

**Comment by coderfox** [comment]
Besides, for the following types of feed:

-  新い話題
- 最近追加
- 最欲しかった
- 最高評価

No detailed date can be retrieved on first sight of the page,

So each AV requires a request to JavLibrary.

Should these pages be supported?

**Comment by DIYgod** [comment]
先获取列表，然后获取每个项的内容并缓存下来

列表需要每次获取（一个请求），如果出现新项就缓存下来（每个新项一个请求）

**Comment by oklong** [comment]
High priority到现在也没有动静啊

**Comment by oklong** [comment]
> 先获取列表，然后获取每个项的内容并缓存下来
> 
> 列表需要每次获取（一个请求），如果出现新项就缓存下来（每个新项一个请求）

High priority到现在也没有动静啊

**Comment by MegrezZhu** [comment]
噗……JavLib还行 :joy:
不过我访问都是 Cloudflare 的503错误提示…不知道是不是我的代理ip被ban了还是它down掉了…不然本来想助人为乐一下的 :joy:

**Comment by syhsyh9696** [comment]
> 噗……JavLib还行 😂
> 不过我访问都是 Cloudflare 的503错误提示…不知道是不是我的代理ip被ban了还是它down掉了…不然本来想助人为乐一下的 😂

因为javlibrary在前几个月被攻击过，现在已经上了CF的防护，你的IP被ban了
