### ISSUE TITLE
希望增加立場新聞的rss

### ISSUE THREAD

**Issue by ariesardonyx** [DIYgod/RSSHub#3408]
### 网站地址
https://thestandnews.com/book/
https://thestandnews.com/art/
https://thestandnews.com/philosophy/
### 网站描述
立場新聞：書評、藝術、哲學 板塊
### 需要生成什么内容？
書評、藝術、哲學
- [ ] 内容一 書評rss
- [ ] 内容二 藝術rss
- [ ] 内容三 哲學rss

### 额外描述
希望可以全文輸出

**Comment by Jeason0228** [comment]
网站自带
https://thestandnews.com/book/rss/
https://thestandnews.com/art/rss/
https://thestandnews.com/philosophy/rss/
