### ISSUE TITLE
闲鱼账号上新 rss 需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3411]
### 网站地址
用户宝贝上新，例： https://market.m.taobao.com/app/idleFish-F2e/IdleFishWeexPersonalPage/PersonalHome?userid=2201514131600
### 网站描述
淘宝旗下二手闲置交易服务
### 需要生成什么内容？
宝贝图片、标题、价格

**Comment by DIYgod** [comment]
刷新一下就要登录了...

**Comment by yefoenix** [comment]
实现过于困难，关闭
