### ISSUE TITLE
[feat] 报错页面增加一个快速生成 issue 的按钮

### ISSUE THREAD

**Issue by lengthmin** [DIYgod/RSSHub#3412]
### 这是一个什么样的功能？
报错页面添加一个按钮，快速将当前报错路由地址，信息，时间等填写到 issue 输入框中。
 github issue 有这个功能：
可以点击下面这个链接试一下：
[点我生成报错信息Issue](https://github.com/DIYgod/RSSHub/issues/new?title=%5B错误报告%5D%20%2Fcyzone%2Flabel%2F创业邦周报%20路由报错&body=%3C%21--%0APlease%20ensure%20you%20have%20read%20%5Bdocumentation%5D%28https%3A%2F%2Fdocs.rsshub.app%2Fen%29%2C%20and%20provide%20all%20the%20information%20required%20by%20this%20template.%0AOtherwise%20the%20issue%20will%20be%20closed%20immediately.%0ADue%20to%20the%20anti-crawling%20of%20the%20source%20website%2C%20some%20RSS%20of%20the%20demo%20will%20return%20status%20code%20403.%20Please%20do%20not%20repeat%20the%20issue.%0A--%3E%0A%0A%23%23%23%20Involved%20route%0Ahttps%3A%2F%2Frsshub.app%2Fcyzone%2Flabel%2F%25E5%2588%259B%25E4%25B8%259A%25E9%2582%25A6%25E5%2591%25A8%25E6%258A%25A5%0A%23%23%23%20What%20is%20expected%3F%0A%0A%23%23%23%20What%20is%20actually%20happening%3F%0A%0A%23%23%23%20Self-deployed%20information%0A%0A%3C%21--%0ADelete%20this%20section%20if%20you%20are%20using%20%5BRSSHub%20demo%5D%28https%3A%2F%2Frsshub.app%29.%0APlease%20ensure%20you%20have%20deployed%20the%20%5Bmaster%20branch%5D%28https%3A%2F%2Fgithub.com%2FDIYgod%2FRSSHub%2Ftree%2Fmaster%29%20of%20RSSHub.%0A--%3E%0A%0A%7C%20Env%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Value%20%20%20%20%20%20%20%20%20%7C%0A%7C%20------------------%20%7C%20-------------%20%7C%0A%7C%20OS%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20Node%20version%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20if%20Docker%2C%20version%20%7C%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%0A%0A%23%23%23%20Additional%20info%20%28logs%20errors%20etc%29%0A%60%60%60%0ATypeError%3A%20Cannot%20read%20property%20%27startsWith%27%20of%20undefined%0A%20%20%20%20at%20Node.%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Froutes%2Fcyzone%2Flabel.js%3A35%3A34%29%0A%20%20%20%20at%20initialize.exports.each%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Fnode_modules%2Fcheerio%2Flib%2Fapi%2Ftraversing.js%3A300%3A24%29%0A%20%20%20%20at%20Node.%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Froutes%2Fcyzone%2Flabel.js%3A31%3A47%29%0A%20%20%20%20at%20processTicksAndRejections%20%28internal%2Fprocess%2Ftask_queues.js%3A85%3A5%29%0A%20%20%20%20at%20async%20Promise.all%20%28index%203%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Froutes%2Fcyzone%2Flabel.js%3A11%3A17%29%0A%20%20%20%20at%20async%20cache%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fcache.js%3A203%3A9%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fparameter.js%3A8%3A5%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Ftemplate.js%3A15%3A5%29%0A%20%20%20%20at%20async%20%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fapi-response-handler.js%3A143%3A9%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fapi-template.js%3A2%3A5%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Futf8.js%3A4%3A5%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fdebug.js%3A14%3A5%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Faccess-control.js%3A29%3A13%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fheader.js%3A20%3A5%29%0A%20%20%20%20at%20async%20module.exports%20%28%2Fdata%2Fwwwroot%2Frsshub.app%2Flib%2Fmiddleware%2Fonerror.js%3A20%3A9%29%0A%60%60%60)

https://github.com/DIYgod/RSSHub/issues/new?title=xxx&body=xxx
title 和 body 传入 uri encode 后的内容即可。

### 这个功能可以解决什么问题？
报错页面一键导航至issue 页面
https://github.com/DIYgod/RSSHub/blob/master/lib/views/error.art#L43
点击按钮直接填写好报错

### 额外描述
Inspired by:
https://new-issue.vuejs.org/?repo=vuejs/vue
https://new-issue.ant.design/

**Comment by lengthmin** [comment]
&assignees=lengthmin
指派

&labels=bug
加上 label

**Comment by SettingDust** [comment]
补充 https://github.com/DIYgod/RSSHub/issues/new?template=bug_report_zh.md
