### ISSUE TITLE
古诗文网——首页推荐 添加作者信息

### ISSUE THREAD

**Issue by WEAIceNTer** [DIYgod/RSSHub#3415]
**### **这是一个什么样的功能？****
古诗文网——首页推荐中rss订阅后输出内容缺少作者，希望能够添加

**Comment by hoilc** [comment]
本地和RSSHub都正常输出

![image](https://user-images.githubusercontent.com/9067094/69130252-23a79900-0aeb-11ea-8658-99b16eea2932.png)

**Comment by WEAIceNTer** [comment]
![image](https://user-images.githubusercontent.com/10004058/69130648-d37d0680-0aeb-11ea-9ce3-af52473660c8.png)
我是自建的miniflux订阅的
手机客户端用的feedme

**Comment by hoilc** [comment]
ttrss+feedme
![图片](https://user-images.githubusercontent.com/9067094/69132310-ce6d8680-0aee-11ea-8478-72a0f3919fd3.jpg)

考虑是miniflux问题

**Comment by hoilc** [comment]
瞄了眼miniflux代码，似乎强制要求`author`元素有子元素`name`

使用atom格式(`https://rsshub.app/gushiwen/recommend.atom`)，理论上就能正确读到作者了

**Comment by WEAIceNTer** [comment]
问题解决，非常感谢
