### ISSUE TITLE
Nintendo Switch RSS

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#3417]
### 网站地址

以下

### 网站描述

Nintendo Switch

### 需要生成什么内容？

- [x] 本体更新情報：https://www.nintendo.co.jp/support/switch/system_update/index.html
- [ ] 资讯：https://www.nintendo.com.hk/topics/index_sc.html
- [ ] 游戏发售：https://store.nintendo.com.hk/games

### 额外描述

我的神秘代码: SW-3404-1126-5044

**Comment by HFO4** [comment]
国航来了，可以顺便把国内官网的新闻和游戏软件加上。
https://www.nintendoswitch.com.cn/software
https://www.nintendoswitch.com.cn/topics

**Comment by NeverBehave** [comment]
> 国行来了，可以顺便把国内官网的新闻和游戏软件加上。
> https://www.nintendoswitch.com.cn/software
> https://www.nintendoswitch.com.cn/topics

国内用的框架是NUXT，应该可以直接parse一下`__NUXT__`object试试看

**Comment by NeverBehave** [comment]
发现nuxt这个还真有点麻烦，来问一下有没有除了eval以外的解决方案？搜了一圈没找到

```
window.__NUXT__=(function(a){return {layout:"default",data:[{sliderData:[],newsData:[{id:"7341a73c-b4f8-4fa2-ae26-33c670743293",title:"《新 超级马力欧兄弟U 豪华版》1月15日实体游戏卡带发售",imgUrl:"\u002F\u002Fswitch-cn.gtgres.com\u002Fglobal-images\u002F05b83870-31cc-11ea-8066-7beee849b0db.png",releaseTime:1578456319000,category:a},{id:"a9bd477a-bf95-4322-843f-0a11f67ac6b0",title:"腾讯引进Nintendo Switch™今日正式发售 让更多中国用户感受“随心切换，一起趣玩”的快乐",imgUrl:"\u002F\u002Fswitch-cn.gtgres.com\u002Fglobal-images\u002F26200e90-1afb-11ea-8066-7beee849b0db.jpg",releaseTime:1575951104000,category:a},{id:"f3f6d30c-184b-47ab-8425-594b8f2595f4",title:"《新 超级马力欧兄弟U 豪华版》12月10日正式发售",imgUrl:"\u002F\u002Fswitch-cn.gtgres.com\u002Fglobal-images\u002F7ed4fd20-1a8d-11ea-8066-7beee849b0db.jpg",releaseTime:1575948867000,category:a},{id:"e3b047c1-8abb-4657-a0f7-e3f242279d82",title:"“随心切换，一起趣玩” 腾讯引进Nintendo Switch公布正式发售信息",imgUrl:"\u002F\u002Fswitch-cn.gtgres.com\u002Fglobal-images\u002F86893910-1631-11ea-9b40-236e671bca9e.jpg",releaseTime:1575431840000,category:a},{id:"6250778e-a52f-44f9-b43c-fdb82500c249",title:"《新 超级马力欧兄弟U 豪华版》将于12月10日发售",imgUrl:"\u002F\u002Fswitch-cn.gtgres.com\u002Fglobal-images\u002Feb7bbdc0-1500-11ea-9b40-236e671bca9e.png",releaseTime:1575400771000,category:a}],total:5,currentTime:1583033917000}],error:null,serverRendered:true}}("Nintendo Switch"));
```

**Comment by HenryQW** [comment]
```
	const { JSDOM } = jsdom;

    const dom = new JSDOM(response.data, {
        runScripts: 'dangerously',
    });

    const data = dom.window.__NUXT__.data[0];
```
见 https://github.com/DIYgod/RSSHub/blob/70b333c4004c909a2f2bfef5cf285608f383c0b2/lib/routes/dongqiudi/utils.js#L64-L69

**Comment by hoilc** [comment]
@NeverBehave 或者用正则把id匹配出来，拼出URL，标题内容都去详情页拿

**Comment by NeverBehave** [comment]
@hoilc 详情页也是nuxt诶……

**Comment by hoilc** [comment]
> @hoilc 详情页也是nuxt诶……

正常的元素都有啊，只是列表页没法直接取详情链接吧

![image](https://user-images.githubusercontent.com/9067094/75619497-78ad7d80-5bb7-11ea-8774-2bac869d8c87.png)

![image](https://user-images.githubusercontent.com/9067094/75619505-92e75b80-5bb7-11ea-9537-dadae5326d5f.png)

**Comment by NeverBehave** [comment]
@hoilc 尝试view-source看一下，元素是浏览器渲染后的效果

**Comment by DIYgod** [comment]
JSDOM  +1

**Comment by NeverBehave** [comment]
> 见
> 
> https://github.com/DIYgod/RSSHub/blob/70b333c4004c909a2f2bfef5cf285608f383c0b2/lib/routes/dongqiudi/utils.js#L64-L69

我一开始想的是

```
const func = Function(`return ${scripts[nuxt]}`);
const data = func();
return data;
```

不过`jsdom`也没有foolproof，但统一用`jsdom`也好

介于`nuxt`用的还很多，要不要考虑做成global的utils，以后有更好的方案直接替代
