### ISSUE TITLE
heroku能否设置更新时间间隔

### ISSUE THREAD

**Issue by ydx1013** [DIYgod/RSSHub#3426]
### What feature is it?
heroku能否设置更新时间间隔
### What problem does this feature solve?
自用不要太高频率，每月550小时不够用。一小时更新一次就足够了
### Additional description

**Comment by hoilc** [comment]
更新时间间隔是客户端行为吧？

**Comment by ydx1013** [comment]
> 更新时间间隔是客户端行为吧？

我也不太懂，这个不更新，客户端更新好像也没数据吧？

**Comment by hoilc** [comment]
> > 更新时间间隔是客户端行为吧？
> 
> 我也不太懂，这个不更新，客户端更新好像也没数据吧？

RSSHub默认不更新  客户端请求更新时才会去抓取RSS

**Comment by DIYgod** [comment]
heroku 行为，与 RSSHub 无关
