### ISSUE TITLE
pixiv排行榜无法按标题顺序排行，排名数字前面#号使得消息无法按照真实排名rank排列

### ISSUE THREAD

**Issue by oreme2** [DIYgod/RSSHub#3432]
排名数字前面#号使得消息无法按照真实排名rank排列
![image](https://user-images.githubusercontent.com/38098761/68994540-13ab7180-08bf-11ea-8d37-230e893dd8ff.png)

**Comment by DIYgod** [comment]
你看这顺序，显然不是 # 造成的
