### ISSUE TITLE
建议P站搜索增加过滤R18功能

### ISSUE THREAD

**Issue by BiliDzOfficial** [DIYgod/RSSHub#3447]
### 这是一个什么样的功能？
在P站搜索结果中过滤R18
### 这个功能可以解决什么问题？
P站搜索结果可能会出现R18内容
### 额外描述
因为我要收集P站图片转载到B站上，而且我也不想看R18
PS：永远记住中国人一律当未成年处理的铁律

**Comment by yefoenix** [comment]
@BiliDzOfficial 提 issue 请遵循模板

**Comment by DIYgod** [comment]
Duplicate of #2932
Duplicate of #1333

**Comment by BiliDzOfficial** [comment]
> Duplicate of #2932
> Duplicate of #1333

我不是要看R18，我只是想在搜索结果中过滤R18

**Comment by BiliDzOfficial** [comment]
> Duplicate of #2932
> Duplicate of #1333

**Comment by DIYgod** [comment]
#2932 就是过滤 R18，而且过滤和过滤出都是一样的功能

**Comment by BiliDzOfficial** [comment]
> #2932 就是过滤 R18，而且过滤和过滤出都是一样的功能

我的意思是我想订阅P站上关于某个角色的内容，但是不想订阅R18内容
