### ISSUE TITLE
RSS 需求: 好队友 远程工作职位

### ISSUE THREAD

**Issue by lotosbin** [DIYgod/RSSHub#3448]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3448)

### 网站地址
https://ourwork.nework360.com/job/list
### 网站描述
好对友是国内领先的自由职业者远程工作平台，提供人才匹配、工作证明、支付结算等服务，为企业减轻人力成本，解决人力困扰；让更多上班族和自由职业者实现自己的财务自由。
### 需要生成什么内容？
- [ ] 标题
- [ ] 详细内容
- [ ] 职位发布时间

### 额外描述

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/221294?v=4' alt='lotosbin' width=24 height=24> lotosbin](https://issuehunt.io/u/lotosbin) ($2.00)

### Submitted pull Requests
- [#3455 feat: add 好队友 rss](https://issuehunt.io/r/DIYgod/RSSHub/pull/3455)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by SettingDust** [comment]
https://ourwork-api.nework360.com/needs/listHotJobs?pageNum=1&limit=20

都是相当简单的呢，有缘人了解一下哦~

**Comment by RookieZoe** [comment]
api 貌似挂了, api 返回这个:

```json
{"code":8001,"desc":"未登录|session过期"}
```

**Comment by lotosbin** [comment]
@RookieZoe 
https://docs.rsshub.app/other.html#hao-dui-you
https://rsshub.app/network360/jobs

**Comment by RookieZoe** [comment]
@lotosbin 

我用的就是这个路由，可能我表述的有问题，我的意思是，这个路由使用的 API 挂了：

``` bash
curl https://ourwork-api.nework360.com/needs/listHotJobs\?pageNum\=1\&limit\=100
{"code":8001,"desc":"未登录|session过期"}%
```
应该是官方做了限制。

**Comment by lotosbin** [comment]
#3593
