### ISSUE TITLE
RSS 需求: 电鸭 远程职位

### ISSUE THREAD

**Issue by lotosbin** [DIYgod/RSSHub#3449]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3449)

### 网站地址
https://eleduck.com/?category=5

### 网站描述
电鸭社区是互联网创意工作者们交流充电的聚集地，我们倡导「只工作，不上班」的工作心态。

### 需要生成什么内容？

- [ ] 标题
- [ ] 内容
- [ ] 职位发布时间

### 额外描述

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/221294?v=4' alt='lotosbin' width=24 height=24> lotosbin](https://issuehunt.io/u/lotosbin) ($2.00)

### Submitted pull Requests
- [#3453 fead: add 电鸭社区](https://issuehunt.io/r/DIYgod/RSSHub/pull/3453)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by SettingDust** [comment]
https://svc.eleduck.com/api/v1/posts?category=5&page=1
