### ISSUE TITLE
微博个人时间线显示问题

### ISSUE THREAD

**Issue by NavePnow** [DIYgod/RSSHub#3454]
### 这是一个什么样的功能？
微博个人时间线显示完整内容
### 这个功能可以解决什么问题？
不需要跳转到微博查看详细信息
### 额外描述
Reeder显示效果
<img width="576" alt="screenshot 2019-11-20 at 19 32 50" src="https://user-images.githubusercontent.com/39482599/69235536-963c7580-0bcc-11ea-826b-1d672978ff62.png">

**Comment by DIYgod** [comment]
没看懂，图里不是完整内容么？

**Comment by Azureki** [comment]
1. 图里已经是完整内容了。那个链接是少数派网址，不是微博。
2. 我不明白你所说的「跳转」是什么意思，现在TL的所有 item 的 link 都是 `https://weibo.com` ，你是无法跳转到对应的源微博的。
3. 不过非要说「完整」的话， `timeline` 路由确实没有 `user` 路由完善。如果关注者转发微博的话，只有关注者发的微博，没有被转发的源微博。

-----

BTY， `timeline` 路由中的图片可以用大图，而不是缩略图吗？
