### ISSUE TITLE
虎嗅网 wanted

### ISSUE THREAD

**Issue by msongz** [DIYgod/RSSHub#346]
虎嗅网
https://www.huxiu.com/

**Comment by wydwww** [comment]
http://feeds2.feedburner.com/huxiurss

**Comment by DIYgod** [comment]
https://docs.rsshub.app/#%E8%99%8E%E5%97%85

**Comment by h6fYe34KFSiH** [comment]
> https://docs.rsshub.app/#%E8%99%8E%E5%97%85

/huxiu/tag/:id 这个id是从哪里找的？

**Comment by HenryQW** [comment]
还不够明显吗。。。。
![image](https://user-images.githubusercontent.com/5896343/54744992-5d24af00-4bc0-11e9-8dce-aa519b7b148a.png)
