### ISSUE TITLE
RSS 需求： 远程.work

### ISSUE THREAD

**Issue by lotosbin** [DIYgod/RSSHub#3460]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3460)

### 网站地址
https://yuancheng.work/

### 网站描述
远程.work是远程工作招聘网站,帮助企业和团队找到远程工作员工,为远程工作者寻找远程工作。

### 需要生成什么内容？

- [ ] 标题
- [ ] 内容

### 额外描述
可以默认全部也可以可以按照分类和性质筛选

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/221294?v=4' alt='lotosbin' width=24 height=24> lotosbin](https://issuehunt.io/u/lotosbin) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by EYHN** [comment]
https://yuancheng.work/feed
