### ISSUE TITLE
【RSS需求】今日热榜

### ISSUE THREAD

**Issue by heylogo1** [DIYgod/RSSHub#3461]
### 网站地址
今日热榜官网：https://tophub.today

### 网站描述
今日热榜提供各站热榜聚合：微信、今日头条、百度、知乎、V2EX、微博、贴吧、豆瓣、天涯、虎扑、Github、抖音...追踪全网热点、简单高效阅读。

### 需要生成什么内容？

- [ ] 内容一
对于形如  https://tophub.today/n/(*)  的热榜页面（如知乎热榜https://tophub.today/n/mproPpoq6O ），获取当日热榜中每条内容的 **标题**与**链接**。（当然能够获取到条目对应内容肯定更好了，但我估计比较难，就不浪费大佬时间了 2333）
（注：只需要当日热榜，列表中历史热榜内容太多了）

### 额外描述
谢谢！

**Comment by yefoenix** [comment]
https://docs.rsshub.app/new-media.html#jin-ri-re-bang

close this pls

**Comment by heylogo1** [comment]
> https://docs.rsshub.app/new-media.html#jin-ri-re-bang
> 
> close this pls

啊？早已经有了吗？对不起对不起，我见这网站是新网站以为肯定没有没去查找就直接发需求了，不好意思！
