### ISSUE TITLE
电子书相关（1个）

### ISSUE THREAD

**Issue by winglight** [DIYgod/RSSHub#3470]
### 网站地址
https://www.letmeread.net/
### 网站描述
IT类电子书下载
### 需要生成什么内容？
按Category或者全站生成最新发布内容即可
- [ ] Minecraft Construction For Dummies（书名）/2014-11-03（出版日期）
- [ ] 内容二

**Comment by yefoenix** [comment]
@winglight https://www.letmeread.net/feed

**Comment by winglight** [comment]
奇怪呀，为什么我在网站上没找到这个feed呢？

**Comment by DIYgod** [comment]
Related to https://github.com/DIYgod/RSSHub-Radar/issues/104
