### ISSUE TITLE
饭否路由 提示 302

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#3474]
### 路由地址
自建的fanfou/user_timeline/wangxing
### 预期是什么？
出现rss条目
### 实际发生了什么？
提示 FanfouError: 302 Found
### 部署相关信息
自建最新版

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
是不是因为没通过审核不能用这个key和secret导致的呢？

![饭否路由 302 2019-11-23 130337](https://user-images.githubusercontent.com/3047708/69473708-358e8200-0df2-11ea-9800-44bf0da16e6b.png)

**Comment by yefoenix** [comment]
@ruleroller 貌似饭否的API服务出问题了，有饭等其他应用也有挂掉的

**Comment by yefoenix** [comment]
Demo的也挂了，怀疑是
「不允许用户名+密码」的问题
@junbaor 能否看一下采用新的认证方式？

![S91123-13583549-01](https://user-images.githubusercontent.com/8215230/69474256-d92f6080-0df9-11ea-9c4e-9d7a8cbf6563.jpeg)

**Comment by ruleroller** [comment]
@yefoenix 饭否网页端，我尝试搜索，随便几个关键字，要么没有结果，要么只有一个结果。估计是系统哪儿出问题了，还没处理好吧。

**Comment by sfyumi** [comment]
饭否全站迁移成 HTTPS 了，之前的 sdk 里用的是 HTTP

**Comment by sfyumi** [comment]
可以在初始化饭否客户端的时候把 protocol 设置成 https 试试

**Comment by yefoenix** [comment]
可以关闭了 @DIYgod
