### ISSUE TITLE
饭否私密账号用户动态报错

### ISSUE THREAD

**Issue by junbaor** [DIYgod/RSSHub#3476]
### 路由地址
/fanfou/user_timeline/(任意已关注的私密账号用户名)
出于隐私, 暂不方便公开用户名

/fanfou/home_timeline 路由也可复现此问题

### 预期是什么？
正常抓取

### 实际发生了什么？
报错显示签名错误

### 部署相关信息
基于此版本(暂未合并) : https://github.com/DIYgod/RSSHub/pull/3475

**Comment by junbaor** [comment]
刚才在 @yefoenix  的配合下大致查了下，问题如下：

[签名算法](https://github.com/FanfouAPI/FanFouAPIDoc/wiki/Oauthsignature) 中需要用到 `base_url`, RSSHub 改为 `https` 计算签名后饭否服务端校验规则依然采用 `http` 协议的 `base_url` 导致签名校验失败。

解决方案：
1、给 [fanfou-sdk-node](https://github.com/fanfoujs/fanfou-sdk-node) 提 Issues 等待修复
2、报告给 fanfou 官方（暂无渠道, 且年老失修, 动代码几率不大）

目前好像没有更优雅的方案，@DIYgod  可以讨论一下

**Comment by yefoenix** [comment]
@junbaor 饭否上 @FF小网管 是官方运维账号，应该可以向他们反馈一下

**Comment by junbaor** [comment]
@yefoenix 嗯，已经圈 小网管和 .rex , 看他们怎么说

**Comment by junbaor** [comment]
### 最小复现 demo :

```
const Fanfou = require('fanfou-sdk');
let envs = process.env;

const ff = new Fanfou({
    consumerKey: envs.FANFOU_CONSUMER_KEY,
    consumerSecret: envs.FANFOU_CONSUMER_SECRET,
    username: envs.FANFOU_USERNAME,
    password: envs.FANFOU_PASSWORD,
    protocol: 'https:',
});

ff.xauth().then(res => {
    ff.get('/statuses/home_timeline')
        .then(res => console.log(res))
        .catch(err => console.log(err));
}).catch(err => console.log(err));

```
### 异常：
```
Debugger attached.
{ FanfouError: Authorization is not defined
    at Fanfou.get (/Users/junbaor/Project/RSSHub/node_modules/fanfou-sdk/src/index.js:95:10)
    at ff.xauth.then.res (/Users/junbaor/Project/RSSHub/fanfou_node.js:13:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'FanfouError',
  err:
   ReferenceError: Authorization is not defined
       at Fanfou.get (/Users/junbaor/Project/RSSHub/node_modules/fanfou-sdk/src/index.js:87:6)
       at ff.xauth.then.res (/Users/junbaor/Project/RSSHub/fanfou_node.js:13:8)
       at process._tickCallback (internal/process/next_tick.js:68:7),
  message: 'Authorization is not defined' }
Waiting for the debugger to disconnect...
```

如果把  fanfou-sdk-node 的 index.js 的 85 行左右改为下面这样, 问题就不存在了。
```
const signUrl = 'http://' + url.substr(8);
const { Authorization } = this.o.toHeader(this.o.authorize({ url: signUrl, method: 'GET' }, token));
```

**Comment by junbaor** [comment]
### 动态更新
官方是有打算更新的，但无具体日期。

<img width="548" alt="WX20191124-202349@2x" src="https://user-images.githubusercontent.com/10198622/69494584-7e306300-0ef8-11ea-8379-64cb2221bb2a.png">
<img width="542" alt="WX20191124-202416@2x" src="https://user-images.githubusercontent.com/10198622/69494585-7ec8f980-0ef8-11ea-8e8a-28b7af563dec.png">
