### ISSUE TITLE
饭否 fanfou 的 trends 路由报错，无法使用

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#3483]
### 路由地址
https://rsshub.app/fanfou/trends
### 预期是什么？
正常显示条目
### 实际发生了什么？
报错
### 部署相关信息
demo和自建最新都这样

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
错误提示如图：
![批注 2019-11-25 133339](https://user-images.githubusercontent.com/3047708/69515162-9f409480-0f88-11ea-8b82-73981a61e63c.png)

**Comment by junbaor** [comment]
饭否目前没有热门话题所致。
