### ISSUE TITLE
饭否 fanfou 的 home_time 自建报错，demo倒是好的。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#3484]
### 路由地址
/fanfou/home_timeline
### 预期是什么？
正常显示条目
### 实际发生了什么？
报错
### 部署相关信息
自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
demo可用，我自建的倒是不行。已执行过npm install。
自建错误的提示如图：
![ht 2019-11-25 135131](https://user-images.githubusercontent.com/3047708/69515922-11b27400-0f8b-11ea-8de1-a711a1b79e3a.png)

**Comment by ruleroller** [comment]
卧槽，发完这个issue，突然想到，可能是我自己没发过饭否的原因，所以是empty！希望空的也不报错，开发者能改进一下吗，那样更友好一些。  @junbaor

**Comment by yefoenix** [comment]
这个路由是你关注的所有用户的发言信息流，跟自己发没发过没关系

**Comment by ruleroller** [comment]
> 这个路由是你关注的所有用户的发言信息流，跟自己发没发过没关系

啊，大佬所言极是，是我理解错了。而我的确是没关注任何人！

![批注 2019-11-25 140429](https://user-images.githubusercontent.com/3047708/69516433-98b41c00-0f8c-11ea-8e85-8e3d12c1cc5f.png)

**Comment by ruleroller** [comment]
没关注任何人的情况比较少见， @junbaor 大佬随意处置吧。issue先关了。
