### ISSUE TITLE
希望增加 虛詞 RSS

### ISSUE THREAD

**Issue by ariesardonyx** [DIYgod/RSSHub#3485]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3485)

### Website URL
https://p-articles.com/
### Website description
藝文網站——虛詞
### What content should be included?

- [ ] RSS https://p-articles.com/works/
- [ ] RSS https://p-articles.com/critics/
- [ ] RSS https://p-articles.com/issues/
- [ ] RSS https://p-articles.com/heteroglossia/

### Additional description
全文輸出

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($2.00)

### Submitted pull Requests
- [#3984 feat: add 虛詞](https://issuehunt.io/r/DIYgod/RSSHub/pull/3984)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by yefoenix** [comment]
以及
子分类，例：https://p-articles.com/critics/art/
作者，例：https://p-articles.com/contributors/%E6%9C%97%E5%A4%A9
