### ISSUE TITLE
用户关注视频动态路由 /bilibili/followings/video/XXXXX 失效了

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#3489]
### 路由地址
/bilibili/followings/video/XXXXX
### 预期是什么？
正常显示
### 实际发生了什么？
报错
### 部署相关信息
自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
是否是 e71ed5fafaf20bb70bc9ce0ed2e144009d7c857b 或 6c84eb496c7c3b8c21bdd3b59eea998755aa3f11 的commit修改造成的呢？24号我自建的都还可以用的。我尝试更新了下cookie，也报同样的错误。 

报错截图：
![个人关注 2019-11-26 014942](https://user-images.githubusercontent.com/3047708/69565443-f3329400-0fef-11ea-9108-3716e8f05d08.png)

**Comment by DIYgod** [comment]
demo 无法复现：https://rsshub.app/bilibili/user/followings/2267573

**Comment by ruleroller** [comment]
@DIYgod 大佬，估计夜深了，你也看迷糊了。我说的路由，和你给的无法复现的那个路由是不一样的！

@LogicJake 逻辑杰克大佬有空也看看？

**Comment by ruleroller** [comment]
@DIYgod 更新后，能刷新出条目了。可在ttrss里，视频还是不能播放，还是得跳到bili。
另外，为什么标题和视频缩略图之间现在会多一大块的空白（如图），有办法搞一下么，大佬？

![空白 2019-11-26 191604](https://user-images.githubusercontent.com/3047708/69625379-67694800-1081-11ea-9392-d180dec528b8.png)

**Comment by DIYgod** [comment]
@ruleroller https://github.com/DIYgod/RSSHub/commit/58e7db97b48a570f792039683334de4ff21c14b3

**Comment by ruleroller** [comment]
@DIYgod ttrss刚有更新，好像去掉了视频播放相关的一些东西。我更新ttrss后，也装上了ttrss-plugin-remove-iframe-sandbox的插件，然后变成了这样（请见附图），似乎还是不正常，正常情况是不是应该在那个大方框中，可以直接点击播放视频的呢？
![批注 2019-11-28 021539](https://user-images.githubusercontent.com/3047708/69749519-a1237700-1185-11ea-9d35-1c4f722ab38b.png)

**Comment by ruleroller** [comment]
@DIYgod 现在附上ttrss的那个[更新链接](https://git.tt-rss.org/git/tt-rss/commit/d15f0349bf1671d3b3704f728372b7fb3f4045bd
)。

**Comment by DIYgod** [comment]
@ruleroller 插件更新了，更新下插件再试试

**Comment by ruleroller** [comment]
@DIYgod 枯了。rsshub和插件都已更新到最新，还是有大块空白滴（请见附图）。百思不得其解，难道是因为我用默认的主题的原因么。。

![批注 2019-11-29 111734](https://user-images.githubusercontent.com/3047708/69841443-15e7d580-129a-11ea-95aa-da63a58f5b5a.png)

**Comment by DIYgod** [comment]
@ruleroller 控制台看下 iframe 元素是什么样的，贴到这里一起看下

**Comment by ruleroller** [comment]
@DIYgod 呃，请教下，怎么看这个 iframe 元素啊？就是，简单说一下步骤……

![批注 2019-11-29 112723](https://user-images.githubusercontent.com/3047708/69841734-5e53c300-129b-11ea-8c82-e33e09fde75b.png)

**Comment by DIYgod** [comment]
@ruleroller 点控制台左上角的选择按钮，然后鼠标移到 iframe 的位置；或者 ⌘ + F 搜索 <iframe

**Comment by ruleroller** [comment]
@DIYgod 这样行不？
![批注 2019-11-29 142156](https://user-images.githubusercontent.com/3047708/69848014-c0202700-12b3-11ea-909a-464c17615f7f.png)
![批注 2019-11-29 142226](https://user-images.githubusercontent.com/3047708/69848016-c0202700-12b3-11ea-817f-d7a1efd1f1a5.png)

**Comment by DIYgod** [comment]
@ruleroller 看起来插件生效了，不知道为什么没加载出来，consle 有报错么？新窗口打开这个 iframe 地址能加载出来么？

**Comment by ruleroller** [comment]
@DIYgod consle有报错的。
![批注 2019-11-29 142757](https://user-images.githubusercontent.com/3047708/69848272-9adfe880-12b4-11ea-824c-a9337e4f6cc1.png)

**Comment by ruleroller** [comment]
@DIYgod 点击iframe的地址，新标签页下，能打开，打开后，也能点击播放。
![批注 2019-11-29 143006](https://user-images.githubusercontent.com/3047708/69848357-df6b8400-12b4-11ea-9fba-68b5fecf991c.png)

**Comment by DIYgod** [comment]
@ruleroller Google 得知，有可能是你浏览器设置的问题：chrome://settings/content/cookies

**Comment by ruleroller** [comment]
@DIYgod 我的是这样设置的，怎样才对呢。。
![批注 2019-11-29 144002](https://user-images.githubusercontent.com/3047708/69848878-3160d980-12b6-11ea-8493-e59457ff1e09.png)

**Comment by DIYgod** [comment]
@ruleroller 关掉阻止第三方 cookie

**Comment by ruleroller** [comment]
@DIYgod 可以啦！谢谢！
![批注 2019-11-29 150721](https://user-images.githubusercontent.com/3047708/69850345-0d9f9280-12ba-11ea-8bea-5b75e66cd25c.png)
