### ISSUE TITLE
The Economist 杂志每周更新epub mobi格式的FTP服务器

### ISSUE THREAD

**Issue by toyqiu** [DIYgod/RSSHub#3491]
### 网站地址
http://www.cgx01.xyz/te/

### 网站描述
The Economist 杂志每周更新epub mobi格式的FTP服务器
### 需要生成什么内容？
需要生成可供下载的RSS源
- [ ] 内容一
- [ ] 内容二

**Comment by ImSingee** [comment]
首先这个域名到期了，其次这是盗版吧……

**Comment by toyqiu** [comment]
> 首先这个域名到期了，其次这是盗版吧……

嗯，提醒所有者了。是calibre从economist官网上抓的，不是破解的杂志电子书。不知道算不算盗版
