### ISSUE TITLE
希望可以支持 PubSubHubbub 协议

### ISSUE THREAD

**Issue by ImSingee** [DIYgod/RSSHub#3497]
### 这是一个什么样的功能？

利用 [PubSubHubbub 协议](https://code.google.com/p/pubsubhubbub/) 实现类似于 [阮一峰的网络日志](http://www.ruanyifeng.com/blog/) 的一旦更新可以直接使得 RSS 订阅服务获取到更新情况

### 这个功能可以解决什么问题？

增强实时性、减少无意义请求

**Comment by yefoenix** [comment]
PubSubHubbub 协议已经更新为 WebSub (https://www.w3.org/TR/websub/), 不过现在支持的地方也很少。

**Comment by yefoenix** [comment]
想了一下原理，实现了 rsshub ↔阅读器之间的 webhub 好像对实时性的提升意义不大，因为源页面 ↔ rsshub 之间是没有webhub的。而且在现在的实现原理上，如果没有阅读器发来的请求 rsshub 是不会主动去抓取源页面的。就是说，阅读器等rsshub给更新信号，rsshub 等阅读器来抓取……互相干等着？

**Comment by DIYgod** [comment]
RSSHub 是一个中转服务，本身带有缓存不是实时的，使用 pubsubhubbub 也不会对即时性有任何提升（延迟仅取决于缓存时间）

而且由于缓存和 CDN 的存在，减少无意义请求也不会带来很明显的好处

但作为一项实验性特性还是挺有意思的，也没什么坏处，issue 可以保留着~
