### ISSUE TITLE
个人有点小建议，顺便有个rss需求

### ISSUE THREAD

**Issue by iyzh635428** [DIYgod/RSSHub#3502]
尊敬的开发团队，听你们说rss需求滞消，可我却已经回不去了，我离不开rsshub。如果你们实在快支持不下去了，那就不要开源，开始收费，一个月10块，20块都好，我第一个支持你们。不要学习“金山快盘”的毛病，体验最好的网盘说关就关，说白了就是没钱，手里有颗摇钱树，却不懂得变钱，简直就是愚蠢。
rsshub对于精准获取信息是极其重要的，有了它，我的世界变得更丰富多彩了好几倍，相当美妙。比如，我可以更高效的刷微博，即时收到github更新，第一时间看到京东的优惠信息。请不要毁掉我的生活。
最后，请把这个网址做个订阅源：https://www.yrxitong.com/h-col-107.html

**Comment by Jemair** [comment]
简直就是愚蠢

**Comment by yefoenix** [comment]
@iyzh635428 感谢你的鼓励，你也可以通过捐赠的方式来支持项目发展。

另外，提RSS需求issue请遵循模板，提供必要信息。

**Comment by iyzh635428** [comment]
> @iyzh635428 感谢你的鼓励，你也可以通过捐赠的方式来支持项目发展。
> 
> 另外，提RSS需求issue请遵循模板，提供必要信息。

我的本意就是不希望rsshub停止开发，我也从来不认为一个项目能靠捐赠发展下去，就算我愿意花钱，也要钱有所值，比如，因为我交钱了，能第一时间获得一定限度的支持，因为我交钱了，我能获得更好的服务，因为很多人和我一样交钱了，项目可以更健康地向前发展。所以，单我个人捐赠，就算我一年捐赠一千元，情况也不会有任何变化，交钱不交钱一个样，你们多一千元，少一千元，还是一个样。所以，我不可能捐赠。我只会交vip会员钱。

**Comment by iyzh635428** [comment]
> @iyzh635428 感谢你的鼓励，你也可以通过捐赠的方式来支持项目发展。
> 
> 另外，提RSS需求issue请遵循模板，提供必要信息。

我顺便告诉你我在rss订阅上花了多少钱，为了稳定，我自建了一个rsshub服务器，服务器每年250元，为了订阅微信公众号，每年交100元，只能订阅32个微信公众号，为了更好的体验，我每年花300元买了inoreader订阅的会员。所以，如果要我在rsshub项目上花钱，我想你应该想办法帮我省钱。

**Comment by tgly307** [comment]
省钱办法简单啊，停止订阅ino会员即可节省300。下个微信客户端，节省100。但这和本项目有什么关系

**Comment by DIYgod** [comment]
@iyzh635428 回应你上面所说的：“请不要毁掉我的生活”
你觉得你每个月的生活值多少钱，就请每个月赞助多少钱，我保证在你赞助期间 RSSHub 不会停止开发

**Comment by SettingDust** [comment]
@iyzh635428 Issuehunt

**Comment by ruleroller** [comment]
emmm.

大千世界，无奇不有。

**Comment by iyzh635428** [comment]
> @iyzh635428 回应你上面所说的：“请不要毁掉我的生活”
> 你觉得你每个月的生活值多少钱，就请每个月赞助多少钱，我保证在你赞助期间 RSSHub 不会停止开发

尊敬DIYgod：
1、网上的文章总喜欢用“付费习惯”来解释大家为什么要付费，实际上跟”习惯“半毛钱关系都没有，我更没有习惯去赞助某个项目，因为我赞不赞助都是一样的。是那些平台通过某些手段让我们不得不花钱。我相信你这种技术大咖，总会有手段让我们不得不花钱的，而且花得心甘心愿的。
2、凤凰网首页的某部分新闻标题，是我每天必看的，如果为我单独做个订阅源？要多少钱？我标题发的那个网址的某个部分，如果为我单独做个订阅源，要多少钱？要等多久？这是我愿意花钱的地方。

**Comment by abc1763613206** [comment]
@iyzh635428 再来认真说明一下：
第一，您可能混淆了所谓开源的概念，开源项目没有商业大公司的支撑，确实是要社区支持才能继续存活，在这里赞助有无就会产生显著影响，甚至可能会影响项目作者的积极性。
第二，如果您确实需要这个RSS的话，还请使用规范的格式重新提交。
不过这种网页订阅似乎也没什么价值......
