### ISSUE TITLE
【/sse/inquire】Bug Report——推送pdf地址缺冒号，无法打开

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3506]
### 路由地址
/sse/inquire 上海证券交易所——监管问询
### 预期是什么？
推送内容能正常打开
### 实际发生了什么？
推送pdf地址缺冒号，无法打开，例如

公司代码 :	600093
公司简称 :	易见股份
发函日期 :	2019-11-27 21:34:06
监管问询类型 :	问询函
标题 :	关于易见供应链管理股份有限公司的问询函

推送的地址是 http//www.sse.com.cn/disclosure/credibility/supervision/inquiries/enquiry/c/8137567518131329.pdf ，缺了冒号，应该是[http://www.sse.com.cn/disclosure/credibility/supervision/inquiries/enquiry/c/8137567518131329.pdf](http://www.sse.com.cn/disclosure/credibility/supervision/inquiries/enquiry/c/8137567518131329.pdf)

**Comment by hoilc** [comment]
无法复现

![image](https://user-images.githubusercontent.com/9067094/70038740-ba984900-15f3-11ea-8fdf-4c024591889b.png)

**Comment by KwToPA** [comment]
通过更新rsshub 修复。
