### ISSUE TITLE
求站酷文章的RSS

### ISSUE THREAD

**Issue by morgancheung** [DIYgod/RSSHub#3515]
### Website URL
 [https://www.zcool.com.cn/](url)
### Website description
ZCOOL站酷，2006年创立于北京，致力于为设计创意从业者、爱好者提供学习、展示、交流、就业、交易、创业等服务，为设计师和企业的成长提供版权解决方案和立体的视觉服务。
### What content should be included?
- [ ] 文章榜单
[https://www.zcool.com.cn/top/article.do?rankType=8&rankId=140](url)
- [ ] 文章首页推荐
[https://www.zcool.com.cn/discover/0!8!0!0!0!!!!3!-1!1](url)
### Additional description
感谢Rsshub🙏

**Comment by Jeason0228** [comment]
@junbaor 求大佬优化下
https://rsshub.app/zcool/top请求的是作品总榜，最好能自定义输入切换
https://www.zcool.com.cn/top/index.do

文章首页推荐
https://docs.rsshub.app/design.html#zhan-ku

**Comment by Qxt-circle** [comment]
同求
文章榜首
https://www.zcool.com.cn/top/article.do?rankType=8&rankId=140
文章首页推荐
https://www.zcool.com.cn/discover/0!8!0!0!0!!!!3!-1!1
