### ISSUE TITLE
巴哈姆特小屋内容 RSS源生成请求

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#3520]
### 网站地址

https://home.gamer.com.tw/

### 网站描述

台湾的一家以ACG内容为主题的资讯站。https://home.gamer.com.tw/ 为内容作者的创作大厅。

### 需要生成什么内容？
希望能针对单独一个内容作者的创作内容及其分类生成 RSS Feed。
- [ ] 为内容作者的所有创作内容生成 RSS Feed
- [ ] 根据内容作者的作品文件夹分类生成 RSS Feed

### 额外描述
作者 ID 应该是在 url 中的 `owner` 参数，例如 `https://home.gamer.com.tw/homeindex.php?owner=tpesamguo` 这位作者的小屋首页中，他的 ID 就应该是 `tpesamguo`. 

而作品文件夹分类则是在参数 `c` 中，例如 `https://home.gamer.com.tw/creationCategory.php?owner=tpesamguo&c=338592` 这个文件夹分类，参数 `c` 为 `338592`，且 url 目录为 `https://home.gamer.com.tw/creationCategory.php` 

作品文件夹指的是：

![image](https://user-images.githubusercontent.com/23435534/69933537-0ff82b80-150a-11ea-9cce-7943c24c91a6.png)

**Comment by tomatomash** [comment]
### 网站地址
https://home.gamer.com.tw/index.php?k1=4&k2=0&vt=2&sm=2
### 网站描述
https://home.gamer.com.tw/index.php?k1=4&k2=0&vt=2&sm=2
### 需要生成什么内容？

- [ ] 标题
- [ ] 全文

### 额外描述
顺便请求一下cosplay的封面或全文
