### ISSUE TITLE
Bilibili 专栏文集在增加全文输出参数后无法抓取到图片

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#3522]
### 路由地址
https://rsshub.app/bilibili/user/article/9717562?mode=fulltext
### 预期是什么？
和普通模式下一样，应该输出图片，例如：https://rsshub.app/bilibili/user/article/9717562

![image](https://user-images.githubusercontent.com/23435534/69952734-c839ca00-1532-11ea-8dad-8c413a3893e4.png)

### 实际发生了什么？

在增加全文输出参数 ?mode=fulltext 后，文章内容里的 `<img>` 标签不见了。

![image](https://user-images.githubusercontent.com/23435534/69952766-d5ef4f80-1532-11ea-91bf-4e4e58246be1.png)

### 部署相关信息

使用 https://docs.rsshub.app/install/#bu-shu-dao-heroku 文档此处的 heroku 链接部署

**Comment by yefoenix** [comment]
@RekiDunois fulltext 模式使用 Mercury 服务实现，仅作为辅助的全文手段，无法也不需保证抓取效果

**Comment by hoilc** [comment]
如果你用的是ttrss，feediron规则供参考

```
"www.bilibili.com\/read\/cv": {
	"type": "xpath",
	"xpath": "div[@class='article-holder']",
	"modify": [{
			"type": "replace",
			"search": [
				"data-src"
			],
			"replace": [
				"src"
			]
		},
		{
			"type": "replace",
			"search": [
				"\"\/\/"
			],
			"replace": [
				"\"http:\/\/"
			]
		}
	]
}
```

**Comment by RekiDunois** [comment]
@hoilc 多谢，我去试试看
