### ISSUE TITLE
抖音都不能抓取了?

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#3523]
### 路由地址
https://rsshub.app/douyin/user/64269185197
### 实际发生了什么？
抖音全都不能抓取了,获取不到消息
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
已恢复
