### ISSUE TITLE
关于pixiv用户收藏路由

### ISSUE THREAD

**Issue by Uzibird** [DIYgod/RSSHub#3524]
Pixiv的用户收藏路由可以找到我收藏的图，但是它的顺序并不是按照我收藏的时间排序的，这就导致我用的阅读器并不能正确的增量更新（大部分都只是搜到上次更新的位置而已而不是一一对比吧？）

如果可以按照用户收藏时间排序就完美了，可以ifttt再直接传入onedrive。

如果可以解决就太棒了，如果不行也只好找别的方法了。

我不确定这个应不应该算在错误报告里。。。

感谢。

**Comment by DIYgod** [comment]
接口并没有返回收藏时间，需求无法满足

另外正常的阅读器是根据 guid 判断更新的，不会受时间影响

**Comment by Uzibird** [comment]
不会受时间影响吗?Inoreader  feedly 的展示/检索顺序都是根据rss页面的顺序来的呀，而RSS页面的图片顺序是根据<pubDate>排序的。不是因为这样才导致图片的更新检测不到吗？

多谢回答。

**Comment by DIYgod** [comment]
@Uzibird 显示是根据时间来排序，但是检测更新不是根据时间来检测，是根据 guid

**Comment by Uzibird** [comment]
那还有解决办法吗? 比如去掉pubdate 另加一个新的时间（比如检测到的时间？）以此来将排序大致以收藏时间顺序来排列

**Comment by yefoenix** [comment]
@Uzibird 所以有什么问题需要解决？

**Comment by Uzibird** [comment]
@yefoenix  让Pixiv用户收藏的路由可以按照收藏顺序排列，我用feedly inoreader用目前的路由都无法正常增量更新。
