### ISSUE TITLE
电影天堂不能更新了?

### ISSUE THREAD

**Issue by currencyporter** [DIYgod/RSSHub#3534]
### 路由地址
https://rsshub.app/dytt
### 实际发生了什么？
不能更新
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by Soauki** [comment]
能修复一下吗？显示报错。

**Comment by shawn8888** [comment]
源地址好象改成 `https://www.dy2018**.com**`
以前的是**.net**
应该很容易修复吧？

**Comment by mayerui** [comment]
根据https://github.com/DIYgod/RSSHub/pull/3517
2019.12.2 源地址被改成https://www.ygdy8.net
该订阅源目前还是无法正常使用

**Comment by shawn8888** [comment]
> 
> 
> 根据#3517
> 2019.12.2 源地址被改成https://www.ygdy8.net
> 该订阅源目前还是无法正常使用

.net打不开，.cc可以：
https://www.ygdy8.cc/

早点修复吧，down了这么久了

**Comment by mayerui** [comment]
我在本地尝试搭建服务尝试修复，发现本地服务是可以正常订阅的。
目前该问题有两种情况：
1. https://rsshub.app 并未部署最新版本的程序
2. 部署https://rsshub.app 的服务器访问不到 https://www.ygdy8.net

附上本地成功订阅并更新的截图
![78F36463690BDE6574754FBE71AB8164](https://user-images.githubusercontent.com/25812837/72659365-6d343780-39f9-11ea-9d07-384eee3b1eb4.png)

**Comment by mayerui** [comment]
今天试了一下，订阅已经恢复，这个issue可以关闭了。 @currencyporter
