### ISSUE TITLE
Youtube List 不能更新

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [DIYgod/RSSHub#3536]
### 路由地址
/youtube/playlist/:id/:disableEmbed?

### 预期是什么？
订阅 Youtube 播放列表

### 实际发生了什么？
RSS 不更新

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

测试地址与RSS
https://www.youtube.com/playlist?list=PLr0JU8OOrK4gA_bHqevU96IlKZTZygOhz
https://rsshub.app/youtube/playlist/PLr0JU8OOrK4gA_bHqevU96IlKZTZygOhz

![图片](https://user-images.githubusercontent.com/14090545/70126779-a9634100-16b4-11ea-83ac-6d96d300ac6c.png)

**Comment by yefoenix** [comment]
貌似是由于 playlist 的排序方式引起的，新视频排在下面了

**Comment by DIYgod** [comment]
RSSHub 按照日期排序，并没有缺失

**Comment by LakeishaKowalczyk** [comment]
@DIYgod 
???
是这个 Feed 不输出内容，不是排序问题
你看图，图中一个月一个更新都没有，实际上 3 天左右作者都会更新一个视频

**Comment by DIYgod** [comment]
@LakeishaKowalczyk 你 打开 RSS 好好看看，RSS 有缺么

**Comment by LakeishaKowalczyk** [comment]
@DIYgod 
有缺

![图片](https://user-images.githubusercontent.com/14090545/70430179-2d526a00-1ab5-11ea-815a-449d03478435.png)

**Comment by LakeishaKowalczyk** [comment]
为了方便查看，放了一个测试用的 Feed

这是 Feed 输出的最后一个视频
https://www.youtube.com/watch?v=dx2HICu5I3c

这是作者更新的最新的视频
https://www.youtube.com/watch?v=s_h54CVQTX0&list=PLr0JU8OOrK4gA_bHqevU96IlKZTZygOhz&index=55&t=0s

**Comment by DIYgod** [comment]
没看懂你在说什么，但是

https://rsshub.app/youtube/playlist/PLr0JU8OOrK4gA_bHqevU96IlKZTZygOhz
https://www.youtube.com/playlist?list=PLr0JU8OOrK4gA_bHqevU96IlKZTZygOhz

前 5 个都有，只是顺序不一样，并没有缺

**Comment by LakeishaKowalczyk** [comment]
@DIYgod 
最新的视频的在最下面（见图），前 5 个是最早发布的视频


![图片](https://user-images.githubusercontent.com/14090545/70733689-c3042880-1d45-11ea-9c4a-4907f8421463.png)
