### ISSUE TITLE
chiphell wanted

### ISSUE THREAD

**Issue by msongz** [DIYgod/RSSHub#355]
https://www.chiphell.com/

**Comment by u3u** [comment]
[`?mod=rss`](https://www.chiphell.com?mod=rss)

**Comment by msongz** [comment]
https://www.chiphell.com/portal.php?mod=rss&catid=1

我这打开的rss只有两个项目

而且是2013年

**Comment by SilverBut** [comment]
https://www.chiphell.com/forum.php?mod=rss&catid=1

**Comment by DIYgod** [comment]
长时间无 pr，issue 暂时关闭
