### ISSUE TITLE
电影天堂源报错

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#3553]
### 路由地址
https://rsshub.app/dytt
### 预期是什么？
正确RSS源返回
### 实际发生了什么？
出现报错

### 额外信息（日志、报错等）
Looks like something went wrong
Hostname/IP does not match certificate's altnames: Host: www.ygdy8.net. is not in the cert's altnames: DNS:do.rsshub.app, DNS:rsshub.app: target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by yefoenix** [comment]
duplicated
 #3534
