### ISSUE TITLE
能否支持下广告门和梅花网

### ISSUE THREAD

**Issue by god-hu** [DIYgod/RSSHub#3567]
### 网站地址：1、广告门 https://www.adquan.com/
                          2、梅花网 https://www.meihua.info/

### 网站描述：广告门持续关注营销传播产业的动态，每日发布由头条+深度文章8-12篇，内容包含业界重大事件、案例分享、人物访谈等，开门以来的原创内容容量>10,000篇，并于年终进行行业盘点。网站每日独立IP约6万，日均访问量30万。

                        梅花网自身已有RSS，但都需要跳转网页原文。希望能看看是否可以支持下全文输出的RSS。

### 需要生成什么内容？

- [ ] RSS 全文输出
- [ ] 内容二

**Comment by yefoenix** [comment]
sshub 暂不接受已有 RSS feed 抓取全文的 issue，如有能力可自行编写路由后进行 pr.
更简单的方式是把全文抓取任务交给阅读器。

**Comment by god-hu** [comment]
梅花网全文抓取不了，返回原网页在在安卓上又经常会打不开。试过抓取全文的转换，都不好用。
广告门没有RSS feed

**Comment by laampui** [comment]
#4690

**Comment by TonyRL** [comment]
Closed this in #4690 and #5208
