### ISSUE TITLE
今日头条头条号rss订阅

### ISSUE THREAD

**Issue by zhuqq029** [DIYgod/RSSHub#3568]
https://www.toutiao.com/c/user/62346190847/#mid=1570886079353858
能够订阅今日头条头条号的rss或者某一频道的rss不知道哪里有

**Comment by yefoenix** [comment]
请确保 [文档](https://docs.rsshub.app) 和 [issue](https://github.com/DIYgod/RSSHub/issues) 中没有相关内容，且源站没有提供 RSS，并按照模版提供信息
否则 issue 将被立即关闭

duplicate #1887 #2930
