### ISSUE TITLE
生成的RSS包含追踪内容？

### ISSUE THREAD

**Issue by juking** [DIYgod/RSSHub#3569]
### 路由地址
[https://rsshub.app/infzm/2](https://rsshub.app/infzm/2)

### 预期是什么？
麻烦解释或移除

### 实际发生了什么？
生成的内容包含
`<iframe width="1px" height="1px" src="https://log.diygod.me"></iframe>`

![image](https://user-images.githubusercontent.com/4278193/70519143-6acafc00-1b76-11ea-87d7-879370b18fb7.png)

**Comment by DIYgod** [comment]
你可以自建
