### ISSUE TITLE
希望支持 亿邦动力网

### ISSUE THREAD

**Issue by Flokiiiii** [DIYgod/RSSHub#3571]
### 网站地址
http://ebrun.com/ 
### 网站描述
电商信息平台
### 需要生成什么内容？

- [ ] 电商数据版块
- [ ] 移动电商版块
- [ ] 零售电商版块

### 额外描述
大佬们制作的电商rss不多，能否照顾下我们电商人，如果可以的话

**Comment by TonyRL** [comment]
Couldn't find those pages
