### ISSUE TITLE
抖音用户动态在快知RSS上不工作

### ISSUE THREAD

**Issue by leenacl** [DIYgod/RSSHub#3584]
### 路由地址
https://rsshub.app/douyin/user/93610979153
### 预期是什么？
可以正常抓取相关用户视频
### 实际发生了什么？
使用快知RSS机器人时，显示地址错误！询问快知开发人员反馈是路由问题，但是此链接在其他RSS软件中可正常抓取。
### 部署相关信息
使用自己部署得RSSHub依然无法工作。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
路由看起来没什么问题，在快知里试了一下也正常，可能网络问题？你再试试

**Comment by leenacl** [comment]
> 路由看起来没什么问题，在快知里试了一下也正常，可能网络问题？你再试试

是的，因为我在别的客户端里可以正常接收，就是快知里不行。很玄学，我把链接输入进去之后它已经可以解析到链接得名称，可就是审核后给我报错。请问你在快知里这个地址正常工作了吗？

**Comment by DIYgod** [comment]
审核后报错是什么意思？我这里可以顺利创建主题，后面就没试了
