### ISSUE TITLE
希望增加 reddit 分版块订阅

### ISSUE THREAD

**Issue by gelmannt** [DIYgod/RSSHub#359]
https://www.reddit.com

**Comment by wydwww** [comment]
[What RSS features does reddit have?](https://www.reddit.com/wiki/rss)

> In most cases, you can create an RSS feed by adding ".rss" to the end of an existing reddit URL:
> 
> Front page: http://www.reddit.com/.rss
> A subreddit: http://www.reddit.com/r/news/.rss
> A user: http://www.reddit.com/user/alienth/.rss
> A multireddit: http://www.reddit.com/r/news+wtf.rss (note that the slash is optional).
> The comments on a specific reddit post: http://www.reddit.com/r/technology/comments/1uc9ro/wearing_a_mind_controlled_exoskeleton_a_paralyzed/.rss
> Submissions from a domain: http://www.reddit.com/domain/microsoft.com/.rss
> /u/pathogendavid has created an extensive guide, "RSS, reddit, and you".

**Comment by gelmannt** [comment]
Thanks
