### ISSUE TITLE
Nei.st 新闻聚合网站(包含端传媒,bloomberg,财新期刊,WSJ,NYTIMES等中文文章)

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#3590]
### 网站地址
需要翻墙，https://nei.st/  
### 网站描述
新发现 一个新闻聚合网站，Nei.st。没有任何网站介绍，但全是各种期刊的文章聚合，不需要会员，不要登录。但是没有所有文章列表目录，网站本身采用google搜索方式查询最新文章。自身网址又乱，没有规则。希望有人能做一个，内容很好
https://www.google.com/search?q=site:nei.st&newwindow=1&tbs=qdr:d
### 需要生成什么内容？
及时，全面的rss，不是网站给的简陋过时，缺少文章的那个列表

**Comment by PumpkinSin** [comment]
https://nei.st/2019/
这个链接可以看到文章列表

**Comment by geerda123** [comment]
这个链接不全，而且不及时。你看看我给的第二个链接

cherio <notifications@github.com> 于 2019年12月16日周一 22:18写道：

**Comment by prnake** [comment]
事实上网站提供的列表才是正确的，“缺少文章”的原因很可能是Google重新收录了几天前的文章（因此通过google实现订阅很不可靠）或者是网站缓存更新不及时。
nei.st用了一个及其愚蠢的时间流，但由于用的是wordpress所以feed信息很完善。
比如https://nei.st/feed的<pubDate>为文章发布时间。
https://nei.st/2019/feed应该是时间归档页面，同样还可以获取https://nei.st/2019/12/feed和https://nei.st/2019/12/17/feed。
此外网站的category标记十分完整，比如WSJ：https://nei.st/category/medium/wsj/feed，另外支持的参数还有caixin, initium, nytimes, economist, bloomberg, lifeweek, natgeo

**Comment by geerda123** [comment]
@prnake 
https://www.google.com/search?q=site%3Anei.st&newwindow=1&sxsrf=ACYBGNRQjK8gEckMkadR0k1HYEXQ8GedKA%3A1576662933641&source=lnt&tbs=cdr%3A1%2Ccd_min%3A12%2F17%2F2019%2Ccd_max%3A12%2F17%2F2019&tbm=
  这是2019.12.17当日搜索出来的。https://nei.st/2019/ 根本就没有google的搜索的一些文章

**Comment by prnake** [comment]
> @prnake
> https://www.google.com/search?q=site%3Anei.st&newwindow=1&sxsrf=ACYBGNRQjK8gEckMkadR0k1HYEXQ8GedKA%3A1576662933641&source=lnt&tbs=cdr%3A1%2Ccd_min%3A12%2F17%2F2019%2Ccd_max%3A12%2F17%2F2019&tbm=
> 这是2019.12.17当日搜索出来的。https://nei.st/2019/ 根本就没有google的搜索的一些文章

比如第一篇「殊死格斗」的feed
https://nei.st/medium/economist/mortal-kombat/feed
它的发布时间是 Thu, 05 Dec 2019 06:44:20 +0000

**Comment by geerda123** [comment]
> > @prnake
> > https://www.google.com/search?q=site%3Anei.st&newwindow=1&sxsrf=ACYBGNRQjK8gEckMkadR0k1HYEXQ8GedKA%3A1576662933641&source=lnt&tbs=cdr%3A1%2Ccd_min%3A12%2F17%2F2019%2Ccd_max%3A12%2F17%2F2019&tbm=
> > 这是2019.12.17当日搜索出来的。https://nei.st/2019/ 根本就没有google的搜索的一些文章
> 
> 比如第一篇「殊死格斗」的feed
> https://nei.st/medium/economist/mortal-kombat/feed
> 它的发布时间是 Thu, 05 Dec 2019 06:44:20 +0000
> 这并非最新的文章，你可以在 https://nei.st/2019/page/10 找到它。

确实这样，看了网页代码，查时间才发现。谢谢关注！

**Comment by cunboy** [comment]
能不能rss呢？

**Comment by geerda123** [comment]
看上面feed地址

cunboy <notifications@github.com> 于 2019年12月20日周五 16:21写道：

**Comment by cunboy** [comment]
http://nei.st/category/medium/wsj/feed
http://nei.st/category/medium/caixin/feed
http://nei.st/category/medium/initium/feed
http://nei.st/category/medium/nytimes/feed
http://nei.st/category/medium/economist/feed
http://nei.st/category/medium/lifeweek/feed
http://nei.st/category/medium/natgeo/feed

**Comment by cunboy** [comment]
停更了吗？

**Comment by geerda123** [comment]
不知道

cunboy <notifications@github.com> 于 2020年1月4日周六 09:38写道：

**Comment by hello532** [comment]
还有没相同类似的网站啊。谢谢。

**Comment by geerda123** [comment]
不知道，偶然发现的

hello532 <notifications@github.com> 于 2020年1月4日周六 09:49写道：

**Comment by geerda123** [comment]
> 停更了吗？

https://nei.st/2020/feed
