### ISSUE TITLE
warn: Twitter RSS is disabled for lacking config

### ISSUE THREAD

**Issue by hoky** [DIYgod/RSSHub#360]
![2018-07-15 13_30_29-h-ds](https://user-images.githubusercontent.com/1546319/42730861-62681502-8833-11e8-9850-0d49b7b12f3c.png)

这是什么问题？我在群晖Docker里面使用，缺少什么配置呢?

**Comment by Ir1d** [comment]
https://docs.rsshub.app/install/#%E9%83%A8%E5%88%86-rss-%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE

**Comment by jackqk** [comment]
我也有同样的问题，楼主怎么解决的！

**Comment by yefoenix** [comment]
@jackqk 文档里写得很清楚了……
