### ISSUE TITLE
我该怎么配置我的RSShub?

### ISSUE THREAD

**Issue by xiehengjian** [DIYgod/RSSHub#3600]
我在按照官网的教程在阿里云服务器上用Docker安装了RSShub，我希望利用它来检测我的Gamil邮箱的收件箱，我在官网的路由中的邮箱路由里看到需要进行一些如账号密码的配置，可是我不知道我应该去哪儿配置，我试图去寻找一个config.js的文件，但是这个文件不止一个，而且里面的格式和官网的示例也不同，或者利用环境变量来配置，但我并不知道用什么命令可以做到，我在官网上也没有找到相关的说明，请问我应该怎么做呢？或者说RSShub可以订阅Gmail吗？

**Comment by yefoenix** [comment]
@xiehengjian 建议认真学习docker的相关知识

**Comment by xiehengjian** [comment]
> @xiehengjian 建议认真学习docker的相关知识

可是我只是想快速解决邮箱订阅问题，没有精力去学习docker或者别的什么理论知识

**Comment by SettingDust** [comment]
@xiehengjian 那就别配置了

**Comment by xiehengjian** [comment]
> @xiehengjian 那就

> @xiehengjian 那就别配置了

为什么
