### ISSUE TITLE
多维新闻不能更新

### ISSUE THREAD

**Issue by lychichem** [DIYgod/RSSHub#3604]
### 路由地址
多维新闻（/dwnews/yaowen/:region?）
### 预期是什么？
能够正常更新
### 实际发生了什么？
无法正常更新，返回404
### 额外信息（日志、报错等）
已知多维新闻近期进行了改版，而无法更新也从12月18日开始

**Comment by kt286** [comment]
GET
https://prod-site-api.dwnews.com/v2/feed/zone/10000120?offset=99999999994&bucketId=00000

**Comment by suil1128** [comment]
还是不能用啊啊啊~！！！

**Comment by lychichem** [comment]
很奇怪，把rsshub doc里实例的源地址喂feedly的话，feedly似乎还是去请求未更新前的旧版源了，但是如果用第三方阅读器订阅是正常的，怀疑feedly有什么缓存策略

**Comment by lychichem** [comment]
现在倒是feedly缓存也刷新了，但有个问题，这个新的源无论拿什么阅读器订阅都不显示图片，估计对楼上贴的那个json解析成xml的时候把图片链接过滤了，不知哪位大佬能修一下

**Comment by DarkAge2018** [comment]
@HenryQW 多维要闻的更新还是停留在12月底，其他则正常
![多维要闻](https://user-images.githubusercontent.com/4428897/74430409-bf9d3280-4e97-11ea-883f-3a02a1ae50e1.png)

**Comment by lychichem** [comment]
从2月1日期又出现了不能更新的问题，请求reopen一下 @DIYgod

**Comment by lychichem** [comment]
从2月1日起又出现了不能更新的问题，请求reopen一下 @DIYgod

**Comment by lychichem** [comment]
@DIYgod 定位到#3842 的修改疑似删除了路由的pubdate字段处理，可能是导致日期解析错误的原因

**Comment by hoilc** [comment]
> @DIYgod 定位到#3842 的修改疑似删除了路由的pubdate字段处理，可能是导致日期解析错误的原因

#3842 只是取到的时间戳没转毫秒，首页没更新应该还是因为api有改动，我提了PR，希望短时间内不需要再打开这个issue😂

**Comment by lychichem** [comment]
> > @DIYgod 定位到#3842 的修改疑似删除了路由的pubdate字段处理，可能是导致日期解析错误的原因
> 
> #3842 只是取到的时间戳没转毫秒，首页没更新应该还是因为api有改动，我提了PR，希望短时间内不需要再打开这个issue😂

不是API有改动，你去访问下上面贴出来的API的json，数据是有更新的，而且时间也是正确的，然后再看一下rsshub的路由页面，数据其实也是新的只是时间打错了，我看完全是因为时间戳没转换对然后一些多事客户端判定成了陈年旧货的原因

**Comment by hoilc** [comment]
@lychichem 不是説时间没有问题，而是有两回事

时间戳没有正确转换，影响所有类型

api地址环境换了，影响首页要闻，之前的api的确停留在12月了，而这个issue本来解决的就是这个问题
