### ISSUE TITLE
音悦Tai 音悦V榜

### ISSUE THREAD

**Issue by shawn8888** [DIYgod/RSSHub#3606]
### 网站地址
http://vchart.yinyuetai.com/vchart/v?area=ALL

### 网站描述
音悦Tai是一家中国高清MV分享网站

### 需要生成什么内容？
音悦V榜 周榜单

- [ ] 内容一
歌曲名称等信息

- [ ] 内容二
MV链接地址，比如：
http://v.yinyuetai.com/video/3396605

**Comment by SiqingYu** [comment]
音悦台这家公司已经倒闭了。

最前线 | 音悦台：辉煌一时，曲终人散？_36氪
https://36kr.com/p/5272702

**Comment by shawn8888** [comment]
可惜了...
