### ISSUE TITLE
【阿里拍卖】Rss Wanted——望支持推送拍卖标的内容

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3623]
### 网站地址
[https://sf.taobao.com/](https://sf.taobao.com/)
### 网站描述
阿里拍卖
### 需要生成什么内容？

- [ ] 望支持推送拍卖标的内容
- [ ] 望支持参数传递：标的物类型，标的物所在地，拍卖状态，开拍时间

### 额外描述
例如标的物类型：股权，拍卖状态：即将开始
[https://sf.taobao.com/item_list.htm?category=125088031&sorder=1](https://sf.taobao.com/item_list.htm?category=125088031&sorder=1)

**Comment by DIYgod** [comment]
反爬很严格，不用费力气了

**Comment by KwToPA** [comment]
> 反爬很严格，不用费力气了

请问 4小时推送一次或者12小时推送一次 这种频率 也会被封吗？
