### ISSUE TITLE
可否出一个开源的RSS阅读器 ios版

### ISSUE THREAD

**Issue by 97wow** [DIYgod/RSSHub#3624]
### 这是一个什么样的功能？
可否出一个RSS的阅读器，ios版，总觉得倚天剑和屠龙刀才配

### 这个功能可以解决什么问题？
以后就可以用万物可RSS团队的阅读器了，一站式服务
### 额外描述
我应该可以代表一部分这方面需求的人表达心声。 或者 推荐一个不错的rss阅读器

**Comment by yefoenix** [comment]
https://docs.rsshub.app/faq.html

**Comment by SettingDust** [comment]
钞能力 谢谢

**Comment by tgly307** [comment]
否

**Comment by RekiDunois** [comment]
你如果说windows什么的就算了，ios reeder 它不香吗

**Comment by 97wow** [comment]
ios reeder 又不开源

**Comment by yefoenix** [comment]
@97wow 不开源 又怎样呢？

**Comment by 97wow** [comment]
@yefoenix 你想表达什么？

**Comment by yefoenix** [comment]
@97wow 你想表达什么呢？不开源有什么问题吗?

**Comment by 97wow** [comment]
很明显 我在表达我想找一个开源的RSS

**Comment by SettingDust** [comment]
@97wow 建议关闭issue
