### ISSUE TITLE
【RSS需求】求大神帮忙生成老牌论坛 dvbbs （动网论坛）RSS源

### ISSUE THREAD

**Issue by 97wow** [DIYgod/RSSHub#3638]
### 网站地址
www.kc0011.net
### 网站描述
这是国内最大到收藏品交易平台
### 需要生成什么内容？
可否生成每个板块到新帖子，最好是包含帖子到回复数。
- [ ] 内容一
- [ ] 内容二

### 额外描述
可有偿服务
weichat:13901677000
万分感谢

**Comment by hoilc** [comment]
动网BBS不是自带RSS么，而且就算是手写一般也不会包含回复数

http://www.kc0011.net/rssfeed.asp?rssid=4&boardid=5

**Comment by 97wow** [comment]
哦哦 这样呀，因为这是行业的论坛，我看别的app 带了回复数，所以特来请教一下。

**Comment by DIYgod** [comment]
因为有自带 RSS 所以 issue 将被关闭
