### ISSUE TITLE
无法获取界面新闻生活频道的文章

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#3645]
### 路由地址
https://rsshub.app/jiemian/list/135
### 预期是什么？
返回界面新闻生活频道的文章
### 实际发生了什么？
提示403错误码。与此同时其他界面新闻的订阅源仍能正常使用（如商业频道https://rsshub.app/jiemian/list/2）

**Comment by SChen1024** [comment]
[界面新闻-生活 135](https://www.jiemian.com/lists/135.html) 页面改版了, 跟之前的区域不兼容了, 需要改动界面,

**Comment by nczitzk** [comment]
实测该路由等一系列界面新闻频道订阅源在自建 RSSHub 服务上可以正常工作。
