### ISSUE TITLE
RSSHub如何支持私有RSS的编写

### ISSUE THREAD

**Issue by shawn8888** [DIYgod/RSSHub#3646]
### 这是一个什么样的功能？
用户可以编写定制私有RSS，不需要提交给官方，可以本地保存，不会被新版本更新覆盖

### 这个功能可以解决什么问题？
有些网站可能很小众，无需公开，自己编写，自己使用

### 额外描述
对于小众网站，或者有私人密码的网站，如果自己有能力学习编写RSS，应该可以自编自用。无需提交，也无需公开。就象Huginn一样，但多一个选择。
如果可以的话，可以吸引更多的人用RSSHub，也会有更多的人编写RSS路由。
没有在官方文档中找到方法，请指教。

**Comment by Jeason0228** [comment]
你自建一份就好了吧...也不需要更新 和合并

**Comment by shawn8888** [comment]
> 你自建一份就好了吧...也不需要更新 和合并

RSSHub不自动更新的话，新的官方路由岂不是全部放弃？

**Comment by Jeason0228** [comment]
或者你开个单独的分支 存放你代码....master跟随更新，分支要更新的话好像可以rebase master

**Comment by shawn8888** [comment]
> 或者你开个单独的分支 存放你代码....master跟随更新，分支要更新的话好像可以rebase master

说实话，没做过，不会... 当然，不会可以学。
但重点是，我希望RSSHub可以支持保存自建代码。比如在docker里设个local code映射目录到外部，这样自己建的路由不会被更新覆盖。这样不是更方便吗？而且会激励更多开发者写自己的路由。写的多了，说不定会帮别人fill request。一举多得，多好？

**Comment by hoilc** [comment]
> > 或者你开个单独的分支 存放你代码....master跟随更新，分支要更新的话好像可以rebase master
> 
> 说实话，没做过，不会... 当然，不会可以学。
> 但重点是，我希望RSSHub可以支持保存自建代码。比如在docker里设个local code映射目录到外部，这样自己建的路由不会被更新覆盖。这样不是更方便吗？而且会激励更多开发者写自己的路由。写的多了，说不定会帮别人fill request。一举多得，多好？

按你的需要，现在也不是不可以啊

Docker映射`protected_route.js`即可，还自带密码保护

**Comment by shawn8888** [comment]
> 按你的需要，现在也不是不可以啊
> 
> Docker映射`protected_route.js`即可，还自带密码保护

原来已经有这个功能了？文档没有提啊
有空试试，谢谢！
