### ISSUE TITLE
request for extended example

### ISSUE THREAD

**Issue by IdoMagal** [DIYgod/RSSHub#3647]
Would it be possible to extend the provided example 

```
const RSSHub = require('rsshub');

RSSHub.init({
    // config
});

RSSHub.request('/youtube/user/JFlaMusic')
    .then((data) => {
        console.log(data);
    })
    .catch((e) => {
        console.log(e);
    });

```
to demonstrate how one would wrap the data into a valid feed? I need to manipulate the data before returning it and It's not clear how to do that given the existing documentation.

**Comment by DIYgod** [comment]
It's a npm package, you need to handle the data yourself.

As for generating RSS feed, please read the source code.
