### ISSUE TITLE
微博某一位博主无法订阅

### ISSUE THREAD

**Issue by allanpk716** [DIYgod/RSSHub#3656]
### 路由地址
https://myrsshub.IP/weibo/user/1735918992
### 预期是什么？
正常订阅
### 实际发生了什么？
提示无法订阅，博主的地址是 https://weibo.com/huangzhangjinster，应该是博主设置了不使用数字ID作为地址。希望能够支持此类博主地址的订阅。
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
这个账号被限制了只登录可见，无解

**Comment by allanpk716** [comment]
thx
