### ISSUE TITLE
酒云网 网站改版 路由报错

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3660]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/3660)

### 路由地址
 /wineyun/:category
例：https://rsshub.app/wineyun/home
### 预期是什么？
正常抓取
### 实际发生了什么？
报错如下
### 部署相关信息
Demo 及Heroku/Docker自建
### 额外信息（日志、报错等）
![Screenshot 2020-01-02 at 13 50 27](https://user-images.githubusercontent.com/8215230/71653367-e2034280-2d66-11ea-8ee5-860581cc8be9.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($2.00)

### Submitted pull Requests
- [#3732 fix: #3660 酒云网 网站改版 路由报错](https://issuehunt.io/r/DIYgod/RSSHub/pull/3732)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by yefoenix** [comment]
@lotosbin 你要不要在 issuehunt 推一下这个pr，现在这样好像没办法打钱给你

**Comment by lotosbin** [comment]
@yefoenix 确认完成是仓库所有者操作的
