### ISSUE TITLE
请为空气质量RSS添加城市子站的 实时 AQI

### ISSUE THREAD

**Issue by XSpark91** [DIYgod/RSSHub#3662]
### 网站地址
http://aqicn.org/city/guangdong/shantou/chenghaizizhan/
### 网站描述
空气质量，实时 AQI
### 需要生成什么内容？
- [ ] 内容一
目前的rss只能做到城市的实时AQI，希望能生成当前城市**子站的实时AQI**
- [ ] 内容二
如果可以的话，增加一个选择，是否显示污染物（如 PM2.5等）的指数
### 原路由地址
实时 AQI
作者: @xapool
举例: https://rsshub.app/aqicn/beijing
路由: /aqicn/:city
参数:
city, 必选 - 城市拼音或地区 ID，详见aqicn.org

**Comment by xapool** [comment]
城市子站 ID 获取方法：右键显示网页源代码，搜索 "idx" （带双冒号），后面的 ID 就是子站的 ID，如你给的链接 ID 是 4258，RSS 地址就是 https://rsshub.app/aqicn/4258

**Comment by XSpark91** [comment]
> 城市子站 ID 获取方法：右键显示网页源代码，搜索 "idx" （带双冒号），后面的 ID 就是子站的 ID，如你给的链接 ID 是 4258，RSS 地址就是 https://rsshub.app/aqicn/4258

谢谢🙏
能否加上内容二的需求，方便的话
