### ISSUE TITLE
BT之家

### ISSUE THREAD

**Issue by shawn8888** [DIYgod/RSSHub#3670]
### 网站地址
当前可用域名（HTTP）:
http://www.88btbtt.com

当前可用域名（HTTPS）:
https://www.btbtt.us
https://www.88btbtt.com

### 网站描述
影视爱好者的聚集地的~BT电影天堂之家

### 需要生成什么内容？
- [ ] 内容一
资源内容介绍

- [ ] 内容二
资源下载地址 (.torrent文件)

### 额外描述
谢谢！！！

**Comment by zhang-wangz** [comment]
响应太慢了..

**Comment by zhang-wangz** [comment]
网站响应太慢了...所以最多只做到8个最新的同时订阅,请注意查收～

**Comment by zhang-wangz** [comment]
已提交pr

**Comment by zhang-wangz** [comment]
似乎响应慢是因为访问量太大的缘故,晚上加载的时候没有感到十分的延迟- -

**Comment by shawn8888** [comment]
响应慢是因为GFW
墙外ping 延时 2ms

**Comment by zhang-wangz** [comment]
做的时候使用的就是墙外的环境…

**Comment by shawn8888** [comment]
这个路由还没有发布？

**Comment by zhang-wangz** [comment]
已经发布了

**Comment by Rick-Ji5** [comment]
这几个好像都用不了了？
