### ISSUE TITLE
Dockerfile无法正常安装chrome

### ISSUE THREAD

**Issue by sqliuchang** [DIYgod/RSSHub#3671]
`  && apt-get purge --auto-remove -y wget\`
这里导致chrome的共享库都被remove了，删除后可以正常安装运行chrome
不清楚有没有更好的解决办法

**Comment by DIYgod** [comment]
puppeteer 属于外部依赖，不应该在容器里安装，可以使用 [Docker Compose 部署](https://docs.rsshub.app/install/#docker-compose-bu-shu)
