### ISSUE TITLE
[Feature Request] 在文档中注明是否源是全文

### ISSUE THREAD

**Issue by TTTPOB** [DIYgod/RSSHub#3687]
### 这是一个什么样的功能？
我了解到现在有一个全局选项是`mode=fulltext`但其实很多源默认就是全文，希望能在文档中标注出来（过往的源放着不注明也行）

**Comment by DIYgod** [comment]
没想出来有什么用...

**Comment by TTTPOB** [comment]
有道理，其实也是，我打开看一下就好了

其实我提这个是因为kindleEar上有个选项让你选是否是全文
