### ISSUE TITLE
什么值得买rsshub没有全文

### ISSUE THREAD

**Issue by laerhu** [DIYgod/RSSHub#369]
非常感谢作者提供这个利器！
问题：什么值得买网站官方订阅源和rsshub方法生成的订阅不同，官方有全文而rsshub没有
环境：https://rsshub.app/smzdm/ranking/haowen/yc/5，网站官方的订阅源是在inoreader搜索到的
原因：rsshub没有获取content数据项
附件：阅读效果对比和请求返回内容对比

![smzdm_rss_dif_inoreader](https://user-images.githubusercontent.com/26965450/42855526-82c6d116-8a73-11e8-91d8-6d432f4d2c6e.jpg)
![smzdm_rss_dif_uri](https://user-images.githubusercontent.com/26965450/42855589-c6e1f6a0-8a73-11e8-9ff3-8d5576d4eed9.jpg)

**Comment by DIYgod** [comment]
没有统一的接口，每个单独请求消耗很大，暂不考虑

**Comment by laerhu** [comment]
目前发现inoreader安卓版提供的 下拉获取全文 功能可以获取全文
