### ISSUE TITLE
希望支持csdn博客

### ISSUE THREAD

**Issue by zhezh** [DIYgod/RSSHub#37]
博客在 https://blog.csdn.net
以上是官方推荐页面,个人博客的地址通常是https://blog.csdn.net/<用户名>,例如https://blog.csdn.net/sunhf_csdn (随便点的一个博客)

**Comment by jjeejj** [comment]
@zhezh  这个 csdn 官方有 RSS的. 不能满足你的需求呢？

**Comment by zhezh** [comment]
@jjeejj 官方博客没有找到rss订阅,可以给个地址或示例吗

**Comment by zhezh** [comment]
@jjeejj 果然..我之前找了好久没找到,也尝试了自己在url后加rss,feed,也不行.
不知道是最近才有的,还是我眼花没发现...
