### ISSUE TITLE
日经中文网 + 路透中文网 全文 RSS

### ISSUE THREAD

**Issue by m1dor1** [DIYgod/RSSHub#3707]
### 网站地址

- 日经中文网: https://cn.nikkei.com/
- 路透中文网: https://cn.reuters.com/

### 网站描述

因为 FeedX 又挂掉了😭

这两个网站内容都比较多，做起来挺麻烦的……

### 需要生成什么内容？

个人需要的话：

- [x] 日经中文网的 [官方 RSS](https://cn.nikkei.com/rss.html) 全文
- [ ] 日经中文网的 HotNews
- [ ] 路透中文网的 [实时资讯](https://cn.reuters.com/theWire)

### 额外描述

--

**Comment by yefoenix** [comment]
RSSHub 不接受已有 RSS feed 抓取全文的需求，如有能力可自行编写路由后进行 pr.
更简单的方式是把全文抓取任务交给阅读器

**Comment by mashirozx** [comment]
路透的官方RSS feed关闭了
