### ISSUE TITLE
优化 bilibili 番剧 seasonid 获取方式

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#371]
现在 URL 中找到不到了

**Comment by Ancientwood** [comment]
@DIYgod 301 Moved Permanently

**Comment by DIYgod** [comment]
window.__INITIAL_STATE__.mediaInfo.param.season_id

**Comment by DIYgod** [comment]
Done. af80d4643a2c4006473f45b32f21ba58fb76fcab
