### ISSUE TITLE
请求提供Nature子刊和Cell及子刊的RSS

### ISSUE THREAD

**Issue by zorroscell** [DIYgod/RSSHub#3737]
### 网站地址
https://www.nature.com/siteindex#journals-N
https://www.cell.com/#main-menu

### 网站描述
这是两个顶级科学期刊网站。
请求提供Nature 子刊： Nature Medicine, Nature Methods, Nature Genetics, Nature Biotechnology , Nature Reviews Drug Discovery的RSS链接。
请求提供Cell Press旗下刊物：Cell、Neuron、Molecular Cell这三本刊物的RSS。

### 需要生成什么内容？

- [ ] 内容一 ，Nature 子刊：能抓取『Latest Research』的所有文章，包括标题、作者、上线时间和摘要
- [ ] 内容二 Cell Press旗下刊物，能抓取『Online Now』的所有文章，标题、作者、上线时间和摘要

### 额外描述
希望能提供这两个网站的子刊rss生成格式和步骤，从而可以效仿。

不胜感谢！

**Comment by MitsuhaMiyamizu** [comment]
附议

另外请求一并加上Nature Computational biology and bioinformatics:

http://www.nature.com/subjects/computational-biology-and-bioinformatics.rss

**Comment by yefoenix** [comment]
@MitsuhaMiyamizu 这不是已经有RSS了么

**Comment by zorroscell** [comment]
> @MitsuhaMiyamizu 这不是已经有RSS了么

前面的确有人提供了nature和nature neuroscience。但是根据这个修改，来抓取其它nature子刊未果。cell及其子刊更是不会抓取。。。求支援，谢谢

**Comment by tomatomash** [comment]
> > @MitsuhaMiyamizu 这不是已经有RSS了么
> 
> 前面的确有人提供了nature和nature neuroscience。但是根据这个修改，来抓取其它nature子刊未果。cell及其子刊更是不会抓取。。。求支援，谢谢

其实，通过x-mol的rss来订阅Cell、Neuron、Molecular Cell是可行的，我现在就用着cell 和neuron的，（ https://rsshub.app/x-mol/paper/0/97 ） 和 （ https://rsshub.app/x-mol/paper/0/356 ）

**Comment by MitsuhaMiyamizu** [comment]
> > > @MitsuhaMiyamizu 这不是已经有RSS了么
> > 
> > 
> > 前面的确有人提供了nature和nature neuroscience。但是根据这个修改，来抓取其它nature子刊未果。cell及其子刊更是不会抓取。。。求支援，谢谢
> 
> 其实，通过x-mol的rss来订阅Cell、Neuron、Molecular Cell是可行的，我现在就用着cell 和neuron的，（ https://rsshub.app/x-mol/paper/0/97 ） 和 （ https://rsshub.app/x-mol/paper/0/356 ）

仿佛发现新大陆，issue closed, thanks

**Comment by carryunm** [comment]
> https://rsshub.app/x-mol/paper/0/97

mark
