### ISSUE TITLE
萌妹子网rss请求

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#3744]
### 网站地址
https://moemzi.com/
### 网站描述
最新萌妹子图
### 需要生成什么内容？

- [ ] 首页各封面
- [ ] 全文（如果可行）

### 额外描述
主要是多图的时候，得一页一页的翻，所以来看能不能一次全部拔下来。

**Comment by luyuhuang** [comment]
能全部拔下来, 但是可能会有点费.

**Comment by tomatomash** [comment]
> 能全部拔下来, 但是可能会有点费.

放个10张以内的出来也行

**Comment by luyuhuang** [comment]
https://moemzi.com/feed
这个网站其实是有 RSS 的

**Comment by tomatomash** [comment]
> https://moemzi.com/feed
> 这个网站其实是有 RSS 的

哇。。。（我在源代码搜rss或者feed都没有，还以为就没有了呢）感谢帮助！
