### ISSUE TITLE
微信公众号 二十次幂页面屏蔽rsshub,自建或者更换ip无效

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#3752]
### 路由地址
https://www.ershicimi.com/a/6070
 https://rsshub.app/wechat/wemp/d90d4bb0-5a9e-4c9e-86ac-eb76c281f1e8

### 实际发生了什么？
二十次幂完全屏蔽了rsshub抓取，用对应ip网页浏览页面没事。比如以上页面。我已经更换了5个ip，只要抓取一次就无效，美国ip自建rsshub
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     debian          |
| Node version       |        v13.6.0       |
| if Docker, version |        no       |

### 额外信息（日志、报错等）
Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by zoenglinghou** [comment]
你用的路由有误：
https://rsshub.app/wechat/ershicimi/2070

**Comment by geerda123** [comment]
> 你用的路由有误：
> https://rsshub.app/wechat/ershicimi/2070

无语，把wemp地址看成二十次幂了
