### ISSUE TITLE
即刻能否抓取真实链接地址？

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#376]
例如 https://web.okjike.com/topic/56d2fabe7cb3331100467e2b/official 这个主题，能否用文章地址直接作为条目地址？

**Comment by wydwww** [comment]
duplicated https://github.com/DIYgod/RSSHub/issues/135

**Comment by yefoenix** [comment]
@wydwww 我是想说，现在即刻抓取到的每个  Item 的的链接，都是类似 https://web.okjike.com/message-detail/5b51c6b07e84360017c6899d/officialMessage 这样的中间页，能否改为抓取每个条目的实际网址 ？比如上面这个条目大家实际想看的是 https://mp.weixin.qq.com/s/YxWEgmVKNNx5V685zt50lg

**Comment by tianzhijiexian** [comment]
估计这个得解析一下了。其实它这个做法挺不好的，自己爬别人的信息，然后自己添加了一个中间页面来做DAU的数据 @yefoenix

**Comment by DIYgod** [comment]
Done.
