### ISSUE TITLE
CNU 的图片抓取只有推荐分类下生效

### ISSUE THREAD

**Issue by SharonOlds** [DIYgod/RSSHub#3761]
### 路由地址
https://rsshub.app/cnu/selected
https://rsshub.app/cnu/discovery/hot
https://rsshub.app/cnu/discovery/recent
https://rsshub.app/cnu/discovery/recommend

### 预期是什么？
抓取图片
### 实际发生了什么？
以上地址只有recommend成功抓取了图片。刚好recommend分类是目前CNU官网隐藏了的，所以可能要更新下地址
### 部署相关信息
rsshub.app和自建服务器都试了是一样的结果

**Comment by yefoenix** [comment]
@SharonOlds 提issue 请遵循模板提供必要信息

**Comment by SharonOlds** [comment]
> @SharonOlds 提issue 请遵循模板提供必要信息

刚才手滑写一半先发出来了
