### ISSUE TITLE
【Discuz通用路由】Wrong Path错误

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub#3773]
### 路由地址
/discuz/http%3a%2f%2fwww.u-share.cn%2fforum.php%3fmod%3dforumdisplay%26fid%3d56
### 预期是什么？
正常输出
### 实际发生了什么？
自建正常，demo提示wrong path， 怀疑可能是node版本问题，但看不到demo的node版本
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  ubuntu16.04    |
| Node version       | v13.6.0   |

### 额外信息（日志、报错等）

![image](https://user-images.githubusercontent.com/15406392/72674842-c7470280-3ab6-11ea-82fd-2bab00692c24.png)

**Comment by DIYgod** [comment]
demo 是 node v12.6.0

**Comment by DIYgod** [comment]
更新至 v12.14.1 还是没有解决

**Comment by junfengP** [comment]
> 更新至 v12.14.1 还是没有解决

我一会儿试试12版本的node，如果不行就让url中的`/`替换成`|`

**Comment by junfengP** [comment]
> 更新至 v12.14.1 还是没有解决

![image](https://user-images.githubusercontent.com/15406392/72707202-de5f2080-3b9a-11ea-9a9a-3071f0896a10.png)
![image](https://user-images.githubusercontent.com/15406392/72707232-eae37900-3b9a-11ea-8a01-562c52a3f0ec.png)

搞不明白....

**Comment by junfengP** [comment]
> 更新至 v12.14.1 还是没有解决

![image](https://user-images.githubusercontent.com/15406392/72707389-43b31180-3b9b-11ea-9f40-7850d4a18bc3.png)
![image](https://user-images.githubusercontent.com/15406392/72707425-59c0d200-3b9b-11ea-97d8-19214101f0e8.png)

看来不是node版本问题，只好用`|` 替换`/`了

**Comment by DIYgod** [comment]
fixed in 19b981f4d3098afa3a7ce06938358e50bbc5370d

**Comment by DIYgod** [comment]
> fixed in [19b981f](https://github.com/DIYgod/RSSHub/commit/19b981f4d3098afa3a7ce06938358e50bbc5370d)

可能是 nginx 的问题，koa 获取到的 path 是 `http:/www.u-share.cn/forum.php%3fmod%3dforumdisplay%26fid%3d56` 所以有了上述更改
