### ISSUE TITLE
丁香园-新型肺炎实时动态rss请求

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#3780]
### 网站地址
https://3g.dxy.cn/newh5/view/pneumonia?scene=2&clicktime=1579583949&enterid=1579583949&from=timeline&isappinstalled=0
### 网站描述
新型肺炎实时动态
### 需要生成什么内容？

- [ ] 疫情地图病例情况
- [ ] 实时播报

**Comment by DIYgod** [comment]
@tomatomash https://docs.rsshub.app/other.html#wu-han-fei-yan-yi-qing-xin-wen-dong-tai
