### ISSUE TITLE
Display domain of instance in homepage

### ISSUE THREAD

**Issue by liyishuai** [DIYgod/RSSHub#3783]
### What feature is it?
Add a paragraph in self-hosted instance homepage, _e.g._:
> Server domain: https://rsshub-instance.herokuapp.com/
### What problem does this feature solve?
Say that I'm sharing my server with friends via Weibo, where URLs are hidden. It'll be nice to have the domain visible without hacking the app-embedded browser.
### Additional description
In terms of sharing servers, is it worth building a pool of servers where everyone can contribute their spare server hours? I can foresee some concerns about anti-DoS policy for pool users though.

**Comment by liyishuai** [comment]
Also, is it expected to see "git hash: unknown" in debug messages?
I'm deploying from my GitHub fork.

**Comment by lisxray** [comment]
You can use the `NODE_NAME` variable as a workaround.

And if RSSHub runs from your git repo directly, the `git hash` field will show current git commit.

**Comment by hoilc** [comment]
You can use the NODE_NAME variable as a workaround.

And if RSSHub runs from your git repo directly, the git hash field will show current git commit.

**Comment by liyishuai** [comment]
`NODE_NAME` makes my domain indeed visible on homepage. Ideally the homepage should document some basic usages for users who are new to RSS.

`git hash: unknown` still appears on my instance, I'm deploying with steps in #3789.

**Comment by HenryQW** [comment]
`NODE_NAME` is in the doc, it's dev-related knowledge don't think it has anything to do with RSS.
