### ISSUE TITLE
Deploy: easiest practice

### ISSUE THREAD

**Issue by liyishuai** [DIYgod/RSSHub#3789]
### What feature is it?
Expand the "Heroku Deployment" section with a no-brainer way to have a self-hosted instance:
1. Fork this repository.
2. Create a new Heroku app that automatically deploys from your fork.
3. Keep your fork up to date with [Pull](/apps/pull) app.
4. Enjoy!

### What problem does this feature solve?
With these documented, newcomers won't need to re-explore this path like I did.

**Comment by HenryQW** [comment]
欢迎 PR。
