### ISSUE TITLE
关于笔趣阁feed

### ISSUE THREAD

**Issue by ciaranchen** [DIYgod/RSSHub#379]
（没写过几次issue。格式不对希望原谅。

我是在用 [笔趣阁的小说章节](https://docs.rsshub.app/#%E5%B0%8F%E8%AF%B4%E7%AB%A0%E8%8A%82) 这个feed的时候有一些问题。

1. 首先是我在谷歌搜索的时候出现了很多个名为“笔趣阁”的网站：我不知道`https://www.biquge5200.com/`是否是唯一正确的笔趣阁网址。事实上我在查看`chapter.js`之前我完全没法弄对正确的小说id。我觉得这是可以在文档中声明的。

2. 在`chapter.js`文件中，我想可能使用map函数类似

```
let chapter_item = list.find('a').map((i, el) => {
    return {
      title: el.text(),
      link: el.attr('href')
    }
  });
```

这样会比直接push要高效一些。

**Comment by DIYgod** [comment]
可以直接提 pr~
