### ISSUE TITLE
邮箱配置失败

### ISSUE THREAD

**Issue by wf09** [DIYgod/RSSHub#3793]
### 路由地址
/mail/imap/20930036@zju.edu.cn
### 预期是什么？
返回邮件信息
### 实际发生了什么？
报错
### 部署相关信息
docker run -d --name rsshub -p 1200:1200 -e EMAIL_CONFIG_20930036.zju.edu.cn="password=******&host=imap.zju.edu.cn&port=143" diygod/rsshub

| Env   EMAIL_CONFIG_20930036.zju.edu.cn | Value   "password=******&host=imap.zju.edu.cn&port=143"|
| ------------------ | ------------- |
| OS  Ubuntu 16.04.6 LTS  |               |
| Node version       |               |
| if Docker, version |   Docker version 19.03.5, build 633a0ea838 |

### 额外信息（日志、报错等）
Error: please config email password, host, port in .env file
    at module.exports (/app/lib/routes/mail/imap.js:20:15)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/@koa/router/lib/router.js:353:16
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/koa-compose/index.js:34:12
    at dispatch (/app/node_modules/@koa/router/lib/router.js:358:31)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at cache (/app/lib/middleware/cache.js:203:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
![1EBxnP.png](https://s2.ax1x.com/2020/01/23/1EBxnP.png)
### docker env
root@fa073dc0c7c2:/app# env
YARN_VERSION=1.21.1
TZ=Asia/Shanghai
HOSTNAME=fa073dc0c7c2
EMAIL_CONFIG_20930036.zju.edu.cn=password=********&host=imap.zju.edu.cn&port=143
NODE_ENV=production
PWD=/app
HOME=/root
NODE_VERSION=10.18.1
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

感谢您的回答

**Comment by hoilc** [comment]
RSSHub的基础镜像为Debian, sh默认链接到dash, dash不支持传递带有`.`的非POSIX标准的环境变量

![image](https://user-images.githubusercontent.com/9067094/73160227-62795100-4123-11ea-85b4-2b0580e0f8a0.png)


建议切换为bash

**Comment by wf09** [comment]
万分感谢，新年快乐！

**Comment by wf09** [comment]
1
