### ISSUE TITLE
南方周末 unable to verify the first certificate

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#3807]
### 路由地址

https://rsshub.app/infzm/3

### 预期是什么？

返回南方周末新闻

### 实际发生了什么？

unable to verify the first certificate

**Comment by lisxray** [comment]
www.infzm.com 证书链配置不全

参见 https://www.ssllabs.com/ssltest/analyze.html?d=www.infzm.com

![image](https://user-images.githubusercontent.com/21187489/73157198-4e315600-411b-11ea-8164-0eb0fd5efa66.png)

**Comment by hoilc** [comment]
www.infzm.com 证书链配置不全

参见 https://www.ssllabs.com/ssltest/analyze.html?d=www.infzm.com

![image](https://user-images.githubusercontent.com/21187489/73157198-4e315600-411b-11ea-8164-0eb0fd5efa66.png)

**Comment by lisxray** [comment]
忘了说了，自建实例的话，设置环境变量`NODE_TLS_REJECT_UNAUTHORIZED`为`0`应该可以跳过

**Comment by hoilc** [comment]
忘了说了，自建实例的话，设置环境变量`NODE_TLS_REJECT_UNAUTHORIZED`为`0`应该可以跳过

**Comment by HenryQW** [comment]
#304 😂
