### ISSUE TITLE
twitter user timeline feed: 去除reply, 去除retweet

### ISSUE THREAD

**Issue by cqcn1991** [DIYgod/RSSHub#3808]
### What feature is it?
twitter user timeline rss feed (https://docs.rsshub.app/social-media.html#yong-hu-shi-jian-xian-2)
支持
- 去除reply
- 去除retweet

### What problem does this feature solve?
能简化rss的内容，提高内容质量

### Additional description
我看了rsshub 这块的实现，是基于twitter api做的
看了twitter api的文档 (https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline), 是支持去除reply, retweet的
![图片](https://user-images.githubusercontent.com/2425141/73134379-d0b10b80-4070-11ea-9a40-38ea3742d426.png)

可能在此之上还要支持选择时间、count, 不然可能数据拿到的量不多？

我自己拿twitter api试验了，这2个参数都是可用的

![图片](https://user-images.githubusercontent.com/2425141/73134396-fccc8c80-4070-11ea-9913-3dc0ae5ab394.png)

**Comment by EYHN** [comment]
@cqcn1991 那我来实现了

**Comment by yefoenix** [comment]
加两个过滤参数就可以了……

**Comment by EYHN** [comment]
原本没有转推
