### ISSUE TITLE
pixiv报错

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3812]
### Involved route
pixiv/ranking/day_male_r18
### What is expected?
正常抓取
### What is actually happening?
![image](https://user-images.githubusercontent.com/44609485/73155639-4327f700-4116-11ea-9512-fe0d501ae9da.png)
显示错误的网关，还有将前面的地址换成自己的后还是不行，radar没反应
![image](https://user-images.githubusercontent.com/44609485/73155804-cba69780-4116-11ea-8246-f9b463ef09f7.png)

### Self-deployed information
自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by hoilc** [comment]
确认pixiv源没有问题，可能只是公用实例短暂不可用

![image](https://user-images.githubusercontent.com/9067094/73156939-62c11e80-411a-11ea-9e09-6b7098b179f3.png)

**Comment by 222YEDONG** [comment]
> 确认pixiv源没有问题，可能只是公共实例短暂不可用
> 
> ![图片](https://user-images.githubusercontent.com/9067094/73156939-62c11e80-411a-11ea-9e09-6b7098b179f3.png)
嗯。。。昨天 用插件又试了几次 才订阅成功了，不是公共实例的问题，我直接修改的地址栏的链接 订阅 试了几次后才成功的
