### ISSUE TITLE
需要javbus论坛的rss源

### ISSUE THREAD

**Issue by x1a0xv4n** [DIYgod/RSSHub#3818]
### 网站地址

[老司機福利討論區 - 老司機論壇](https://www.javbus.com/forum/forum.php?mod=forumdisplay&fid=2&filter=author&orderby=dateline)

[求福利帶帶我 - 老司機論壇](https://www.javbus.com/forum/forum.php?mod=forumdisplay&fid=36&filter=author&orderby=dateline)

### 网站描述

javbus论坛

### 需要生成什么内容？

- [ ] 按照发帖时间排序的rss源；
- [ ] 只需要标题列表即可；（当然最好有帖子详情）

**Comment by yefoenix** [comment]
https://docs.rsshub.app/bbs.html#discuz

**Comment by x1a0xv4n** [comment]
> https://docs.rsshub.app/bbs.html#discuz

其他discuz的论坛是可以使用这个rss规则的，但是这个网站不能用，已经试过了；

https://rsshub.app/discuz/https%3A%2F%2Fwww.javbus.com%2Fforum%2Fforum.php%3Fmod%3Dforumdisplay%26fid%3D36

**Comment by DIYgod** [comment]
Duplicate of #3837
