### ISSUE TITLE
需要第一版主的rss源

### ISSUE THREAD

**Issue by x1a0xv4n** [DIYgod/RSSHub#3819]
### 网站地址
[第一版主网_正版_最全版主小说_版主网_荷包网_书包网小说_搜书吧](http://www.dybz9.net/)

### 网站描述

一个小说网站

### 需要生成什么内容？

- [ ] 某本小说的章节列表
- [ ] 某章详情

**Comment by x1a0xv4n** [comment]
#3916

**Comment by hoilc** [comment]
@x1a0xv4n 666 g2不放假系列
