### ISSUE TITLE
吾爱破解论坛-最新精华 RSS请求

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3825]
### Website URL
https://www.52pojie.cn/forum.php?mod=guide&view=digest
### Website description
吾爱破解 导读 最新精华：
![image](https://user-images.githubusercontent.com/44609485/73260585-2ae2d580-4205-11ea-9023-e2d1a849f8cc.png)
### What content should be included?
- [ ] content one：标题 版块群组 作者
- [ ] content two： 回复/查看 最后发表时间
- [ ] content three： 大致内容

### Additional description
虽然有订阅的符号但是显示是这样的：
此XML文件似乎没有与之关联的任何样式信息，文档树如下所示：无法订阅到ttrss
![image](https://user-images.githubusercontent.com/44609485/73260736-7a290600-4205-11ea-939f-918cf2dbe737.png)
是否需要自己来编辑xml 文件添加样式ranho然后就能订阅了？目前还不会搞这个啊。。。
![image](https://user-images.githubusercontent.com/44609485/73261162-7ba6fe00-4206-11ea-93f6-09194e25caa9.png)

**Comment by DIYgod** [comment]
https://www.52pojie.cn/forum.php?mod=guide&view=digest&rss=1 测试可以订阅
