### ISSUE TITLE
【国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 通知公告】Rss wanted

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3830]
### 网站地址
[http://www.nhc.gov.cn/xcs/zhengcwj/list_gzbd.shtml](http://www.nhc.gov.cn/xcs/zhengcwj/list_gzbd.shtml)
### 网站描述
国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 通知公告
### 需要生成什么内容？

国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 通知公告

### 额外描述

无

**Comment by DIYgod** [comment]
https://docs.rsshub.app/other.html#wu-han-fei-yan-yi-qing-xin-wen-dong-tai

**Comment by KwToPA** [comment]
@DIYgod 您好， /coronavirus/nhc 是疫情通报 和 这个不同，这个是 通知公告 。

申请重开，谢谢

**Comment by DIYgod** [comment]
不好意思，重开了
