### ISSUE TITLE
【国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 疫情通报】Rss wanted

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3831]
### 网站地址
[http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml](http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml)
### 网站描述
国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 疫情通报
### 需要生成什么内容？

国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 疫情通报

### 额外描述

无

**Comment by yefoenix** [comment]
#3826

**Comment by KwToPA** [comment]
路由是 

### /nhc/list_gzbd
