### ISSUE TITLE
国家卫健委的疫情通报报错

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#3834]
### 路由地址
https://rsshub.app/coronavirus/nhc
### 预期是什么？
有条目
### 实际发生了什么？
demo上是正常的，自建出错（如图）。自建的，一开始更新后是可以用的，刷新了几次，就报错了。后面再测试，时好时坏，有时又能刷新出条目的，更多时候是报错。
### 部署相关信息
已更新到最新，其它肺炎相关的都可以用，唯独今天下午新增的有点问题。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![批注 2020-01-29 155625](https://user-images.githubusercontent.com/3047708/73337930-5ff83200-42b0-11ea-8b46-3fcd933d916f.png)

**Comment by HenryQW** [comment]
卫健委的网站经常抽风，以及对国外IP相当不友好。
