### ISSUE TITLE
Discuz 通用路由在某些论坛抓取异常

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3837]
### 路由地址
https://rsshub.app/discuz/www.hi-pda.com%2fforum%2fforumdisplay.php%3ffid%3d7
### 预期是什么？
正常抓取
### 实际发生了什么？
item 内容为空
### 部署相关信息
官方 Demo 及 Docker 最新镜像自建
### 额外信息（日志、报错等）
![Screenshot 2020-01-30 at 00 09 06](https://user-images.githubusercontent.com/8215230/73374252-dfa7f000-42f4-11ea-87b7-6e2a0f61abd9.png)

**Comment by yefoenix** [comment]
感觉 Discuz 被各种魔改，统一适配会经常出问题，比如 #3818 也是

**Comment by junfengP** [comment]
URL需要填写`HTTP(S):// ` 

上述正确路由:
https://rsshub.app/discuz/http%3a%2f%2fwww.hi-pda.com%2fforum%2fforumdisplay.php%3ffid%3d7


关于 #3818 ，我看了他的论坛链接，需要登录才可以访问。

**Comment by yefoenix** [comment]
@junfengP 带了http也是空的啊……

**Comment by junfengP** [comment]
看了一下这个论坛的页面，抓取`ITEM`的语句是可以的，但是`TITLE`, `LINK` 这些元素的CSS路径变化了。

**Comment by yefoenix** [comment]
@junfengP 另外#3818至少在我这里访问是不需要登录的

**Comment by junfengP** [comment]
> @junfengP 另外#3818至少在我这里访问是不需要登录的

我访问的是这个链接，自动跳转至登录页面。
https://www.javbus.com/forum/forum.php?mod=forumdisplay&fid=36

本ISSUE的链接抓取不到是因为 Discuz 7.X 页面改版了。我刚刚找了个discuz 7.0的论坛看了一下，与你发的链接布局一致。

后续我会分析一下各个版本的discuz，做出不同版本的路由进行适配。

不过需要登录的，我就没招了。
