### ISSUE TITLE
【国家卫健委-新型冠状病毒感染的肺炎疫情防控 > 疫情通报/coronavirus/nhc】Bug Report——无法抓取正文

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3840]
### 路由地址
/coronavirus/nhc
### 预期是什么？
正常工作
### 实际发生了什么？
标题即正文
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

无

**Comment by HenryQW** [comment]
可能是源站挂了，我这里打不开 http://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml

**Comment by KwToPA** [comment]
@HenryQW  你在英国吗？ 我国内ip可以打开卫健委网站，用美国ip抓时灵时不灵。不过第一次添加到ttrss上能成功，等抓完，ttrss相应的条目立马变红，报错。

**Comment by KwToPA** [comment]
现在凤凰城，新加坡ip可以秒开，之前很卡。估计抽风了

**Comment by HenryQW** [comment]
`标题即正文`
这个路由就是 @DIYgod 这么写的，没毛病。
国外ip访问这个网站超时非常严重，如果提供正文可能根本没法使用了。

**Comment by yefoenix** [comment]
@KwToPA 全文让阅读器来解决吧

**Comment by KwToPA** [comment]
@yefoenix 我已经在ttrss上开启了mercury_fulltext，ver.2
