### ISSUE TITLE
申请为“Nature Structual & Molecular Biology”制作RSS订阅源

### ISSUE THREAD

**Issue by Little-Ghost** [DIYgod/RSSHub#3851]
### 网站地址
https://www.nature.com/nsmb/
### 网站描述
分子生物学研究期刊，Nature的子刊
### 需要生成什么内容？

- [x] 内容一
论文标题和Abstract
- [x] 内容二
doi或者论文连接
### 额外描述
类似于RSShub里面已经有的关于Nature和Nature Neuroscience的推送方式

**Comment by yefoenix** [comment]
https://rsshub.app/x-mol/paper/journal/406 这个够用吗？
