### ISSUE TITLE
Piapro recent by user feed

### ISSUE THREAD

**Issue by trejkaz** [DIYgod/RSSHub#3852]
### Website URL

https://piapro.jp

### Website description

Piapro is a content-sharing website run by Crypton Future Media, Inc. for users to share content related to the company's vocal synthesiser characters.

### What content should be included?

    /piapro/user/[id] -> https://piapro.jp/my_page/?view=content&pid=[id]

e.g. https://piapro.jp/my_page/?view=content&pid=shine_longer

### Additional description

This one is going to have to be an HTML scrape.

Container for items:

```
<div id="itemcont" class="clearfix">
```

Sound / music item:

```
  <div id="_item_3t9anjkzsmiw6sud" class="item _item">
    <div class="i_main">
      <div class="i_sound_card">
        <a href="#" class="jacket-cover-hz trim card-chara-empty" style="background-image: url(/images/card_chara/card-miku.png?20130625);"></a>
        <div class="cover" >
          <div class="_item" onclick="return playCard(0, '3t9anjkzsmiw6sud', '20190902050124');">
            <a href="/t/vUul" class="btn_play _item_play">
              <img src="/images/sprite.png?20130625" width="67" height="67">
            </a>
          </div>
          <div class="title">
            <a href="/t/vUul">Add one me - 初音ミク</a>
          </div>
        </div>
      </div>
      <div class="clearfix i_info">
        <p class="post">閲覧数:3,074</p>                                          <p class="post">2019/09/02 05:01</p>
      </div>
    </div>
  </div>
```

Illustration item:

```
  <div id="_item_6ksucr271gueyvfu" class="item _item">
    <div class="i_main _illust">
      <a class="i_image" href="/t/bzet" style="background:url(//cdn.piapro.jp/thumb_i/6k/6ksucr271gueyvfu_20101203234745_0150_0150.jpg) no-repeat center;">
        <span class="thumb_over">おめでとー</span>
      </a>
      <div class="clearfix i_info">
        <p class="post">閲覧数:2515</p>                                          <p class="post">2010/12/03 23:47</p>
      </div>
    </div>
  </div>
```

Text item:

```
  <div id="_item_mojcttaful29n8d5" class="item _item">
    <div class="i_main i_reading">
      <a class="i_text" href="/t/g_Bq">
        <div>
          <p class="title">居場所</p>
          <p class="opening">背中越しから　やわらかな風<br />
目を閉じてみれば　ささやかな音<br />
同じ空色　いつもの日和<br />
眠そうなあなたは　私に微笑む<br />
空のコップに水を注ぎ　一息入れる<br />
</p>
        </div>
      </a>
      <div class="clearfix i_info">
        <p class="post">閲覧数:850</p>              <p class="post">2008/05/15 01:11</p>
      </div>
    </div>
  </div>
```

Getting descriptions requires going to the item page itself so it might be out of the question. :(

There are global feeds as well... but the structure is a bit awful so I don't know a good way to structure it all and personally I wouldn't be using them anyway. URLs included here for reference but page structure is different to the user pages.

* Music top: https://piapro.jp/music/
* Music tag + category: https://piapro.jp/music/?tag=miku&categoryId=2
* Illustrations top: https://piapro.jp/illust/
* Illustrations tag + category: https://piapro.jp/illust/?tag=miku&categoryId=9
* Text top: https://piapro.jp/text/
* Text tag + category: https://piapro.jp/text/?tag=miku&categoryId=7
* 3D model top: https://piapro.jp/illust/?tag=&3dm=1
* 3D model tag: https://piapro.jp/illust/?tag=miku&3dm=1

**Comment by hoilc** [comment]
`3D model` seems to be included in `Illustrations`, so I ignored it.
