### ISSUE TITLE
提供一个种子站：https://thepiratebay.org/

### ISSUE THREAD

**Issue by tailaijin** [DIYgod/RSSHub#3853]
### 需要生成什么内容？

- [ ] 内容一：Top100 或者定制化top定期更新RSS
- [ ] 内容二：过滤搜索相应片子（这个我觉得直接下载种子用就挺方便的……）

### 额外描述
比那些各种要求做种的BT网站方便很多

**Comment by yefoenix** [comment]
@tailaijin 提issue请遵循模板，提供必要信息

**Comment by DIYgod** [comment]
https://thepiratebay.org/rss
