### ISSUE TITLE
微信公众号 wemp.app 来源失效

### ISSUE THREAD

**Issue by realVEct0r** [DIYgod/RSSHub#3856]
### 路由地址

rsshub: https://rsshub.app/wechat/wemp/36836fbe-bdec-4758-8967-7cc82722952d

### 预期是什么？

成功订阅 rss。

### 实际发生了什么？

rsshub 提示 403 Forbidden，并且自建服务也一样提示 403

**Comment by yefoenix** [comment]
@realVEct0r 反爬了

**Comment by realVEct0r** [comment]
> @realVEct0r 反爬了

考虑后续更新绕过么

**Comment by yefoenix** [comment]
@realVEct0r 如有绕过方案欢迎pr
