### ISSUE TITLE
公开的 Google 相册影集 RSS

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#3860]
# 网站地址

https://photos.app.goo.gl/msFFnAzKmQmWj76EA

### 网站描述

公开的 Google 相册影集

### 需要生成什么内容？

- [ ] 涩图

**Comment by hoilc** [comment]
老哥再传一点涩图我就提PR😉

**Comment by hoilc** [comment]
居然是DIYgod提的issue...

**Comment by DIYgod** [comment]
@hoilc 更新了这两天存的大概 1000 张涩图

**Comment by hoilc** [comment]
@DIYgod 😳666 深感一次取50张太保守
