### ISSUE TITLE
Hpoi手办维基网站无法正确生成订阅地址

### ISSUE THREAD

**Issue by THU-Pieris** [DIYgod/RSSHub#3867]
### 路由地址
https://rsshub.app/hpoi/charactar/1246512
### 预期是什么？
得到对应角色/work的手办信息
### 实际发生了什么？
只有演示地址
https://rsshub.app/hpoi/charactar/1246512
可以订阅成功。

但是：说明文档里面没有详细说明**角色/作品 ID**应该从哪里取得，我理解为**hpoi的URL**里取得。但是演示地址订阅的角色“零二”在hpoi官网的URL为
https://www.hpoi.net/charactar/57561
，并不是“1246512”。请求解答

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
打开角色关联手办的列表页，看一下URL

**Comment by THU-Pieris** [comment]
> 打开角色关联手办的列表页，看一下URL

知道了，十分感谢！！！
