### ISSUE TITLE
腾讯新闻较真查证平台查证者

### ISSUE THREAD

**Issue by Winton1988** [DIYgod/RSSHub#3874]
### 路由地址
https://rsshub.app/factcheck
### 网站描述
腾讯新闻较真查证平台，最新辟谣
### 需要生成什么内容？

- [ ] 内容一
   保留原有的内容基础上＋ 查证者的名字   比如-查证者：谢望时  药理学硕士，知贝儿科药师。我需要“谢望时”这个内容

### 额外描述
原本路由是可以的，今天路由好像修改了。
![dfa803acc9a3b4ea5045950abdea029](https://user-images.githubusercontent.com/44358249/73643780-11330980-46af-11ea-8860-8f8685cda44c.png)

**Comment by DIYgod** [comment]
fixed in 4be7802b27e26da0d45b5aae66ec9c768c3616cf

description 里加上了 查证者，来源是页面

author 里也有，来源是接口，但是发现有的条目接口只返回了作者描述，即只有 `药理学硕士，知贝儿科药师`

**Comment by Winton1988** [comment]
@DIYgod 谢谢啦，我吃完饭再去试一下看看

**Comment by Winton1988** [comment]
@Winton1988 刚刚观察了一段时间发现author 里有的条目有的时候可以返回作者，有的时候不可以。如果是这样的话保证summary 里有就行了。author 里改回原来的只有作者描述。
谢谢啦🙏

**Comment by Winton1988** [comment]
@DIYgod 刚刚观察了一段时间发现author 里有的条目有的时候可以返回作者，有的时候不可以。如果是这样的话保证summary 里有就行了。author 里改回原来的只有作者描述。
谢谢啦🙏

**Comment by DIYgod** [comment]
你用的时候可以只用 summary 里的，author 还是保持这样好了

**Comment by Winton1988** [comment]
@DIYgod 我想把作者和作者描述分开来使用用，author 字段内容不固定的话，我很难从summary 里提取出作者的名字😢
