### ISSUE TITLE
GitChat  rss 无法使用

### ISSUE THREAD

**Issue by Mei-jing** [DIYgod/RSSHub#3881]
### Involved route
/gitchat/newest
### What is expected?
输出内容
### What is actually happening?
无法使用
### Self-deployed information
自建的也无法使用

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       centos        |
| Node version       |       v12.14.1        |
| if Docker, version |               |

### Additional info (logs errors etc)
Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by hoilc** [comment]
网站似乎改版了，你这边有之前订阅的消息的截图吗？
