### ISSUE TITLE
People's Republic of China Degree Certificate Search

### ISSUE THREAD

**Issue by sukiko789** [DIYgod/RSSHub#3882]
### Website URL
http://www.chinadegrees.com.cn/help/unitSwqk44.html

### Website description
People's Republic of China Degree Certificate Search
Progress of Degree Certificates Online for Degree-granting Units in Guangdong Province

### What content should be included?

- [ ] Degree-granting unit name
- [ ] Latest Internet Batch

### Additional description
Want to support filtering "degree-granting unit names"
Title should include "### What content should be included?"

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/95657527-d8381800-0b0c-11eb-8db3-43000511262c.png)
我想去null大学
