### ISSUE TITLE
JavLib 用户在论坛内的发言抓取不到

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3896]
### 路由地址
https://rsshub.app/javlibrary/users/mangudai/userposts
### 预期是什么？
正常完整抓取用户文章
### 实际发生了什么？
用户在论坛内的发言抓取不到
### 部署相关信息
官方 Demo 及 Docker 自建
### 额外信息（日志、报错等）
http://www.javlibrary.com/cn/userposts.php?u=mangudai 列表内前两项内容为用户在论坛内的发言，比如这条
![Screenshot 2020-02-06 at 10 19 59](https://user-images.githubusercontent.com/8215230/73900337-65660580-48ca-11ea-96c3-c98708375d89.png)

**Comment by junfengP** [comment]
老司机看的这么认真，一定是个博学的司机，不留下你的神秘代码吗
