### ISSUE TITLE
低端影视 各作品列表页面路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3897]
### 网站地址
https://ddrk.me/
### 网站描述
低端影视是著名的影视剧在线播放网站
### 需要生成什么内容？
- [ ] 首页作品列表
- [ ] 某个 tag 页面的作品列表，例：https://ddrk.me/tag/recommend/
- [ ] 某个 category 页面的作品列表，例：https://ddrk.me/category/drama/kr-drama/
### 额外描述
低端影视站点以 Wordpress 建站，但是关闭了自带的rss输出。其各个分类/栏目都是 Wordpress 的 category 或 tag, 结构高度一致。需要注意的是，category 可以有两级。

**Comment by hoilc** [comment]
之前单部影视更新在直接`/ddrk`下，我给扔到`/ddrk/update`下了

如果之前有使用，请注意更新URL

BTW，可以多试试Radar规则，看看是不是有什么地方识别不正确

**Comment by hiddys** [comment]
您好，

目前低端影视的旧域名（ddrk.me / ddrk旧域名）已经无法访问，站点已重新上线并启用新地址：
[https://ddys.io/](https://ddys.io/)

如果后续仍有相关路由、规则或抓取需求，建议以新的域名进行适配。
新站结构更简洁，页面也更稳定，匹配起来会相对容易一些。

感谢当时为低端影视提供的路由支持。

**Comment by ddysdev** [comment]
Hi @hoilc 和 @DIYgod，

非常感谢两位在几年前对 `ddrk.me` 路由的贡献和维护，解决了当时很多用户的追剧信息聚合需求。

随着时间推移，原 `ddrk.me` 的情况也在不断变化，可能给 RSS 抓取带来新的挑战。

我这边一直在优化和维护 **[低端影视](https://ddys.io/)** 这个项目，可以算是对这类资源的**新一代体验优化**。我们的站点路由和结构也力求简洁清晰，目的是方便后续的抓取和维护。

除了站点的性能和纯净度，我们还开发了两款提升用户体验的浏览器插件：一个可以**联动豆瓣/IMDb**，另一个是**在线播放广告净化工具**。

如果您或社区还在关注这类站点的 RSS 维护或数据聚合，或许可以看看我们站点的结构，如果需要新的 RSS 路由，我们会很乐意提供协助或反馈。

再次感谢各位对 RSSHub 的贡献！
