### ISSUE TITLE
豆瓣用户广播-头像图片链接订阅部分是不是有问题？

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3903]
### 路由地址
路由: douban/people/:userid/status
### 预期是什么？
修改RSSHub 文档中错误的部分。
### 实际发生了什么？
应该不是ul，就只有一个u才对【还是说豆瓣最近改了？】，订阅看理想的广播的时候按照他那个怎么也不对，我还以为去掉两位，把那个1也去掉了，就怎么也不对，就去掉u就行了，我的尝试过程，示例如下：

![image](https://user-images.githubusercontent.com/44609485/73932685-d1ba2680-4915-11ea-91f5-cdd5e42d7f39.png)
---
![image](https://user-images.githubusercontent.com/44609485/73932795-fca47a80-4915-11ea-9a1d-06a4da0637b7.png)
这个地方的是不是写错了：https://docs.rsshub.app/social-media.html#dou-ban
![image](https://user-images.githubusercontent.com/44609485/73932953-5f961180-4916-11ea-9c5e-8c67378db6ae.png)
### 部署相关信息
用的别人的服务器 以及定义域名，所以这部分不是很清楚。。。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by 222YEDONG** [comment]
![image](https://user-images.githubusercontent.com/44609485/73933590-bb14cf00-4917-11ea-916b-4d1fc390ab14.png)
我发现有的源 订阅好了之后 名字就是网页上的那个名字，自动搞好了，有的就不行，是数字，还得重命名一下。。。不知道将来换了自定义域名会怎样？上回别人的域名过期了，换了新的，导出opml 文件 在atom里全替换掉再订阅到inoreader里发现 列表里很多源名字 变成数字了，就像上面的 图里的那样，名字是数字，有点麻烦，全得手动搞一遍。

**Comment by 222YEDONG** [comment]
通过图片ID来订阅的源，才几分钟，凉了
![image](https://user-images.githubusercontent.com/44609485/73936114-0da4ba00-491d-11ea-9752-dcf51443a350.png)

**Comment by lisxray** [comment]
1. 头像有不同尺寸，个人主页右侧的头像就是`ul158560793-4.jpg`，忽略开头的字母就行

2. 每个源都是独立的，不存在说名字应该符合什么规范，看开发的心情

**Comment by hoilc** [comment]
1. 头像有不同尺寸，个人主页右侧的头像就是`ul158560793-4.jpg`，忽略开头的字母就行

2. 每个源都是独立的，不存在说名字应该符合什么规范，看开发的心情

**Comment by 222YEDONG** [comment]
@hoilc
好的，感谢回应，之前另外一个人提醒我，设置 更新间隔为4小时，但是 我主要平台是inoreader【调整间隔不方便，ttrss可以直接设置】 ttrss备用，**一时没有想起来 赶紧去设置好**，等我看ttrss里面的内容时候，源已经红了。
![image](https://user-images.githubusercontent.com/44609485/73999933-45554580-49a1-11ea-86f0-5e0d8e79e396.png)
inoreader好像只能点击 那个图标 去增强 ，_不好调整_，我过阵子发邮件给官方反馈一下
![image](https://user-images.githubusercontent.com/44609485/74000028-9bc28400-49a1-11ea-8605-54d678c18688.png)
inoreader里豆瓣源都没红，ttrss红一个【 tt里面另外的豆瓣源也没事】假如可以优化的话就优化吧，**随缘了，我只反馈一下 这个问题**，douban/people/:userid/status 字母型的 id  比其豆列 小组等的路由 更容易挂掉 @alfredcai  
![image](https://user-images.githubusercontent.com/44609485/74000076-b98fe900-49a1-11ea-9654-63cf7bfcd1e2.png)

**Comment by hoilc** [comment]
反爬策略是豆瓣内部的事，确认时间间隔放长点，第二天看看再说

也许是广播的限制比其它更严，但不太可能说字母型的 id更容易触发反爬

API响应里应该有用户名，稍等会，我提个PR把标题改了
