### ISSUE TITLE
奶牛关（CowLevel） rss请求

### ISSUE THREAD

**Issue by Qxt-circle** [DIYgod/RSSHub#3905]
### 网站地址
https://wx.zsxq.com/dweb2/

### 网站描述
奶牛关是一个游戏狂热者的分享问答社区

### 需要生成什么内容？
 奶牛精选

### 额外描述
奶牛关注册登陆有点门槛，不知道能不能实现这个rss

**Comment by hoilc** [comment]
https://cowlevel.net/element/1370

https://cowlevel.net/featured

不需要登录
