### ISSUE TITLE
路由 "国家卫健委 - 疫情通报" 失效

### ISSUE THREAD

**Issue by luyuhuang** [DIYgod/RSSHub#3906]
### 路由地址

/coronavirus/nhc

### 预期是什么？

正常生成 RSS

### 实际发生了什么？

源站返回错误 412.

> ## Looks like something went wrong
>
> Response code 412 (Precondition Failed): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

---

国家卫健委网站似乎做了反爬处理: 如果你的请求没有带上 cookie, 必然返回 412 和一个带有 js 的空页面, 并 Set-Cookie. 之后要立刻重发一条带上正确 cookie 的请求才能取得页面. 我并不太清楚其中的原理, 希望有大佬能解答下我的疑问, 以及是否有很好的解决办法.

**Comment by lhy1024** [comment]
可以复现，目前仍是如此

**Comment by lhy1024** [comment]
建议可以通过北京市人民政府的疫情通告链接获取，会定期更新北京和全国的，过滤掉北京的就可以了，曲线救国

**Comment by HenryQW** [comment]
应该是正常了
![Uploading image.png…]()
