### ISSUE TITLE
智联招聘 失效

### ISSUE THREAD

**Issue by Qxt-circle** [DIYgod/RSSHub#3907]
### 路由地址
`/zhilian/:city/:keyword`
### 预期是什么？
订阅职位推荐
### 实际发生了什么？
理论上若无该城市数据，则会报错，但是我用举例的地址 https://rsshub.app/zhilian/台州/JavaScript 也会报错，无法订阅
![IMG_9628](https://user-images.githubusercontent.com/26061932/73944550-c07d1400-492d-11ea-8992-6a230a898ddb.PNG)
测试软件：reeder 3
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by hoilc** [comment]
与 #3649 重复，等待有缘人解决
