### ISSUE TITLE
起点的路由是不是凉了啊？或者说只有我的凉了？

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3920]
### Involved route
起点
#章节
作者: @Chingyat @Chingyat 
举例: https://rsshub.app/qidian/chapter/1010400217
**路由: /qidian/chapter/:id**
参数:
id, 必选 - 小说 id, 可在对应小说页 URL 中找到
### What is expected?
_假如可以确定是路由出问题的话，希望可以早日修复_
### What is actually happening?
使用radar 插件刷新网页 没有反应，订阅不了，我用quicker动作 再编辑了一下 结果还是不行，如下：
![image](https://user-images.githubusercontent.com/44609485/74049412-0a89f680-4a0f-11ea-821f-d25cc9ce25d6.png)
代码如下：
好像出了点问题
错误：错误的路径
    在module.exports（/app/lib/middleware/parameter.js:14:15）
    在process._tickCallback（内部/进程/next_tick.js:68:7）
Error: wrong path
    at module.exports (/app/lib/middleware/parameter.js:14:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
### Self-deployed information
---
![image](https://user-images.githubusercontent.com/44609485/74049799-db27b980-4a0f-11ea-93ed-ea87f3c20f0b.png)
前些天我就订了一个 神圣罗马帝国，今天准备订其他的，发现ttrss里面起点的源也凉了

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
第一个截图的路由链接是错的。
罗马神圣帝国 这个路由，请提供 浏览器打开后的报错信息或TTRSS的具体报错信息。
如果是 28 Operation timed out XXXX 并不影响使用。

**Comment by yefoenix** [comment]
https://rsshub.app/qidian/chapter/1010400217 这个路由实测没有问题

**Comment by 222YEDONG** [comment]
@yefoenix 我发的那个截图上链接是饲养全人类,哦，对，发现问题了，少了前面的起点，多谢提醒，quicker动作把那个 qidian也给替换掉了，感谢提醒，我说怎么老不对呢。。。
过阵子我把那个动作再完善些就分享出来。要是我学会正则表达式 就好了，文本处理部分就好弄些。
文本的处理模块：https://getquicker.net/KC/Help/Doc/text-process

**Comment by yefoenix** [comment]
@222YEDONG 欢迎分享～如没有别的问题，本 issue 可以关闭了

**Comment by 222YEDONG** [comment]
怎么把 quicker 和 RSSHub结合起来，没有头绪
【虽然有http请求模块 可以调用API但是我不会用，RSSHub可以调用API吗？也不太清楚】，quicker 处理 网址比 radar检测 再添加 要快。这个是我在用的动作的一部分步骤截取下来的，目前还很不完美，不知道有没有quicker群的群友在，感兴趣的可以试下。
https://getquicker.net/sharedaction?code=c0a926b2-7ba7-4f9d-340a-08d7ac3d38fb
---
没用过的可以用**我的推荐码   9620-7065 注册**：
![image](https://user-images.githubusercontent.com/44609485/74088774-e264cb00-4ad4-11ea-96f6-dff8c2f0c3c2.png)
这个markdown渲染咋回事，上面部分全粗了
