### ISSUE TITLE
Facebook pages not working

### ISSUE THREAD

**Issue by jtagcat** [DIYgod/RSSHub#3921]
### Involved route
https://rss.c7.ee/facebook/page/kspace.ee
### What is actually happening?
`this route is empty`, facebook.com/kspace.ee exists
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | CentOS 7              |
| if Docker, version | version 19.03.5, build 633a0ea     |

### Additional info (logs errors etc)
![image](https://user-images.githubusercontent.com/38327267/74067157-7d37a980-49f0-11ea-8af9-1a8f709598cf.png)

**Comment by Rupthya** [comment]
官方或自建都報錯；自建錯誤如上，官方的有些許不同。
