### ISSUE TITLE
想要一个windows下小白都能GUI部署的程序？

### ISSUE THREAD

**Issue by shishirong** [DIYgod/RSSHub#3937]
### 这是一个什么样的功能？
在windows下也能轻松地部署。
### 这个功能可以解决什么问题？
windows普通用户的的痛点。
### 额外描述
linux/服务器什么的毕竟太麻烦了，对于普通用户来说可能就在本机windows中直接双击就能安装和运行的来的更方便，自己在后台运行着，如果订阅的东西很重要不关机就行了。甚至可以把RssHub与一个RSS阅读器集成到一起，也省得大家到处去找用的顺手的阅读器。

**Comment by junfengP** [comment]
那windows下安装docker，根据RSSHub文档中 docker部署方式，一句命令即可部署至本机。
