### ISSUE TITLE
Discuz 通用路由下 mcbbs.net 报错

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#3950]
### 路由地址
https://rsshub.app/discuz/https%3a%2f%2fwww.mcbbs.net%2fforum-texture-1.html
### 预期是什么？
抓取输出为 rss feed
### 实际发生了什么？
报错
```
Looks like something went wrong
Error: 不支持当前Discuz版本.
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/discuz/discuz.js:115:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
### 部署相关信息
官方 Demo
### 额外信息（日志、报错等）
论坛版本为 Discuz! X3.4
本问题解决后可关闭 issue #2890

**Comment by yefoenix** [comment]
发现 #2890 已经被 #3294 解决了，本 issue 关闭

**Comment by junfengP** [comment]
看了一下，是因为mcbbs把脚标的powered by discuz! X3.4 给移除了，所以导致识别不到版本。

**Comment by yefoenix** [comment]
> 看了一下，是因为mcbbs把脚标的powered by discuz! X3.4 给移除了，所以导致识别不到版本。

所以 head 里面的 <meta name="generator" content="Discuz! X3.4" /> 是更稳定的识别标准？

**Comment by junfengP** [comment]
> > 看了一下，是因为mcbbs把脚标的powered by discuz! X3.4 给移除了，所以导致识别不到版本。
> 
> 所以 head 里面的 meta name="generator" content="Discuz! X3.4" 是更稳定的识别标准？

是的，准备这么改。
