### ISSUE TITLE
自动命名的问题，是只有我一个人，有这个问题嘛？

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3957]
### 路由地址
路由: /zhihu/topic/:topicId   
### 预期是什么？
自动改源的名。随缘改进吧，我只报告 一直都有这个情况 @xyqfer
### 实际发生了什么？
部分订阅后发现没有自动命名，都是 链接上的数字。
![image](https://user-images.githubusercontent.com/44609485/74235310-a9fa0280-4d09-11ea-80df-ba8fd1ec93ed.png)
有时候自动搞好了，有时候又不行，和上回订阅时候豆瓣一样。
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by lisxray** [comment]
「有时候自动搞好了，有时候又不行，和上回订阅时候豆瓣一样。」

你确定有时候可以？🤔

**Comment by xyqfer** [comment]
刚才看了下代码，确实是用 `topicId`（数字）代替了实际的话题名称，因为 `feeds` 的接口没有返回当前话题名称。要改的话需要加多一个请求去获取当前 `topicId` 对应的话题名称，感觉会加大被反爬的几率...

**Comment by yefoenix** [comment]
@xyqfer 感觉没必要改，阅读器一般都有重命名功能
