### ISSUE TITLE
需要增加豆瓣用户订阅RSS-豆列等

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#3963]
### 网站地址
https://www.douban.com/
### 需要生成什么内容？
豆瓣用户动态豆列

- [ ] 内容一
豆瓣用户豆列 https://www.douban.com/doulist/113399777/

- [ ] 内容二

**Comment by yefoenix** [comment]
@skycloudly 不是都有了吗 麻烦看一下文档
