### ISSUE TITLE
微博又有新的干扰icon了……

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#397]
![image](https://user-images.githubusercontent.com/33424662/43374709-9e8c41b4-93e3-11e8-856d-de276a1fe44a.png)
![image](https://user-images.githubusercontent.com/33424662/43374716-a7a94134-93e3-11e8-93a9-405718b34dfd.png)
对应微博：https://weibo.com/2958679095/GshLL5RsM?type=comment#_rnd1532917620689

**Comment by visayafan** [comment]
这就是个无底洞，最好的解决办法就是不要用卡片视图，改成列表视图。

**Comment by visayafan** [comment]
我说的列表模式不显示缩略图
![image 3](https://user-images.githubusercontent.com/1766538/44011683-91c01fdc-9eec-11e8-854b-42fea9745348.png)

**Comment by ShimotsukiH** [comment]
大哥，我用rss都是看图为主……纯文字的列表模式非但没解决问题还把问题加大了……这不就是每个图片类信息我都得点一遍么？那我还用个毛线rss，直接到p站 behind 追波点点点不好……

**Comment by DIYgod** [comment]
Fixed. 32aa8e56caa0c29660737bec7b051ce4c50e64a6
