### ISSUE TITLE
全民K歌RSS

### ISSUE THREAD

**Issue by shishirong** [DIYgod/RSSHub#3971]
### 网站地址
https://kg.qq.com/
### 网站描述
全民K歌
### 需要生成什么内容？

- [ ] 用户动态
- [ ] 作品评论动态

**Comment by yefoenix** [comment]
请给出用户动态和作品动态的具体页面事例

**Comment by shishirong** [comment]
@yefoenix  网页上看不到，只有客户端里面才能看到

**Comment by martinwu42** [comment]
@yefoenix @shishirong 同求，有网页版

https://node.kg.qq.com/personal?uid=639a9a86272c308e33

https://node.kg.qq.com/play?s=OhXHMdO1VxLWQOOm
