### ISSUE TITLE
自建抖音报错

### ISSUE THREAD

**Issue by dabo-t** [DIYgod/RSSHub#3977]
### 路由地址
douyin/user
### 预期是什么？
正常生成数据
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/9606042/74504604-b2cc1d80-4f2f-11ea-8592-741596a5d413.png)

缓存时间设置了15分钟，不清楚是不是反爬了。

**Comment by yingfawong** [comment]
路由为空，是不是网页的路径写错了

**Comment by dabo-t** [comment]
> 路由为空，是不是网页的路径写错了

没有写错，之前一直正常工作的

**Comment by langrenfengzi** [comment]
还未fix吗

**Comment by jiey2016** [comment]
@DIYgod 抖音已经失效很久了

**Comment by DIYgod** [comment]
应该是抖音屏蔽了 puppeteer 抓取方式，暂时没有解决方案，可能会考虑删除抖音路由

**Comment by xiaodfeng** [comment]
请问现在这个问题解决了吗？可以订阅抖音吗？
