### ISSUE TITLE
少数派 sspai 按作者

### ISSUE THREAD

**Issue by Pcrab** [DIYgod/RSSHub#3979]
### 这是一个什么样的功能？
现在在作者页面找不到id，现在好像用的是slug，在api页面看得到slug，但是不知道怎么筛选

### 这个功能可以解决什么问题？
通过作者订阅更方便

### 额外描述
slug在https://sspai.com/api/v1/article中，"author":{..."slug":"author's slug"...}

**Comment by 222YEDONG** [comment]
这个我也想过提issues，不过后来放弃了，就关注了少数的那么几个人，直接用quiker记录一下网址就行了。自动化神器推荐：quicker 官网：https://getquicker.net/ 
鲲鹏的推荐码：9620-7065 
使用方法 https://getquicker.net/KC/Help/Doc/recommend-code
被推荐人在注册后30天内购买专业版可获赠3个月（90天）使用时长，从各渠道购买均可。
专业版功能概述：https://www.yuque.com/quicker/help/pro-version

**Comment by yefoenix** [comment]
@222YEDONG 广告不止一次了吧，这手法是六学传人啊……
