### ISSUE TITLE
武昌首义学院-学校要闻的RSS需求

### ISSUE THREAD

**Issue by 222YEDONG** [DIYgod/RSSHub#3981]
### 网站地址
http://www.wsyu.edu.cn/info/iList.jsp?cat_id=10307
### 网站描述
武昌首义学院新闻中心-要闻
### 需要生成什么内容？

- [ ] 内容一 
方框内的内容
![image](https://user-images.githubusercontent.com/44609485/74519975-ae186100-4f51-11ea-9fd0-7d00e4d6624f.png)

- [ ] 内容二

**Comment by 222YEDONG** [comment]
不知道能不能搞，之前虽然捐过一点钱，但是财力非常有限，计划等毕业工作后开始RSSHub还有谷氨酸的anki插件的周期性赞助，之前多次把项目的链接与相关情况介绍等发送到信科院QQ群，计算机专业群，互助群、还有班上群等等，希望可以号召更多人来参与这个项目【或者干脆有计算机的大神来弄】，无奈本人影响力≈0，所以没人鸟我，今天在几个群里又发了一次，感觉还是=白说。准备等会儿写个推荐RSSHub的动作类似于这个：https://getquicker.net/sharedaction?code=b37fde4d-f1da-4458-d5ea-08d7a134ade8，可以少打点字，时不时几个群发一下

**Comment by hoilc** [comment]
@222YEDONG 其实吧😂安利过度反而给人的观感不好 有点像打广告

**Comment by 222YEDONG** [comment]
@hoilc 那怎么安利好啊？，b（￣▽￣）d　，又没人教我，你们完全可以出个安利教程啊，或者写个quicker动作提交上去。

**Comment by hoilc** [comment]
@hoilc 女装！
