### ISSUE TITLE
武昌首义学院-就业信息网

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#3982]
### 网站地址
https://wsyu.91wllm.com/campus
### 网站描述
武昌首义学院就业信息网 招聘公告
### 需要生成什么内容？

- [ ] 内容一工作城市 以及单位行业
![image](https://user-images.githubusercontent.com/44609485/74526389-474d7480-4f5e-11ea-81ce-0390ea19248a.png)

- [ ] 内容二招聘人数 专业要求
![image](https://user-images.githubusercontent.com/44609485/74526397-4c122880-4f5e-11ea-85fe-7b8a0a0a242d.png)
因为第二项，我把后面的几页的那些内容都大致看了一下，不是固定的内容，所以完全随缘

**Comment by jeasonlau** [comment]
@222YEDONG 你这是需求学校网站全家桶啊 🤣
