### ISSUE TITLE
RSS from links in file

### ISSUE THREAD

**Issue by jtagcat** [DIYgod/RSSHub#3986]
### Website URL
Local file or remote file
### Website description
Have a file (local or [remote](https://pb.c7.ee/raw/f053)) what's URL-s is made in to RSS.
### What content should be included?
 - Website preview (like in chat apps)
### Additional description
Great addition for bookmarks.

_Recurring donors will be rewarded via express issue response, patreon:rasmuskallas_

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/blob/master/assets/radar-rules.js
