### ISSUE TITLE
Facebook Groups

### ISSUE THREAD

**Issue by jtagcat** [DIYgod/RSSHub#3987]
### Website URL
https://www.facebook.com/groups/*
### Website description
Get public groups, maybe via API also private groups.
### What content should be included?

- Posts in the group
    - Images / Videos
    - Embedded links (preview)
![image](https://user-images.githubusercontent.com/38327267/74563083-e4f77280-4f63-11ea-8bf4-08bd6982e251.png)

**Comment by HenryQW** [comment]
需求不太现实，FB需API才可以，现在都不好申请了。
