### ISSUE TITLE
草榴的Rss不好用了

### ISSUE THREAD

**Issue by 11can** [DIYgod/RSSHub#3988]
### Involved route
草榴
### What is actually happening?
不在抓取
### Self-deployed information

Looks like something went wrong

Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by yefoenix** [comment]
@11can Demo服务器被草榴封锁，如需使用请自建rsshub服务

**Comment by DIYgod** [comment]
befd42d2a8c935dbf8fec1323868d8293b767d09
