### ISSUE TITLE
南方周末不能抓取全文的文章(需要付费订阅的文章)，有个人订阅账户的前提下怎么抓取全文

### ISSUE THREAD

**Issue by yingfawong** [DIYgod/RSSHub#3992]
### 这是一个什么样的功能？
南方周末有个人订阅账户的前提下进行全文抓取
### 这个功能可以解决什么问题？
有订阅账户的前提下抓取全文
### 额外描述
就是怎么用账户密码登录后去抓取全文

**Comment by hoilc** [comment]
目前应该不接受全文请求吧？况且还是这种有门槛的...

**Comment by HenryQW** [comment]
账户密码登录后抓取全文，肯定行不通了。
