### ISSUE TITLE
RSS需求：xueqiu.com

### ISSUE THREAD

**Issue by William-Sun** [DIYgod/RSSHub#3996]
### 网站地址
https://xueqiu.com/?_=1581773479183&category=financial_management

### 网站描述

雪球网是提供沪深港美股票实时行情、实战交流、实盘交易等的投资社区，基金板块是其子话题，主要更新一些基金方面的投资心得。

### 需要生成什么内容？

- [ ] 内容一  文章标题
- [ ] 内容二  更新时间
- [ ] 内容三  文章内容（包含图片）

### 额外描述
希望这个网站能使用RSSHub一键订阅

**Comment by TonyRL** [comment]
closed in #2984
