### ISSUE TITLE
KING KONG直播通知RSS無效

### ISSUE THREAD

**Issue by rayno0723** [DIYgod/RSSHub#3998]
### 路由地址
https://www.kingkong.com.tw/
### 预期是什么？
正常訂閱RSS
### 实际发生了什么？
無法訂閱 顯示路徑失敗
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by hoilc** [comment]
wrong path 是因为你路径输错了，不过未开播直接报错不太合理

**Comment by rayno0723** [comment]
我路徑是用 https://rsshub.app/kingkong/room/ID  
來源是這裡https://docs.rsshub.app/live.html
但測試時顯示該路徑無效
