### ISSUE TITLE
腾讯大家首页RSS失效

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#4001]
### 路由地址
/dajia

### 预期是什么？
文章每天更新

### 实际发生了什么？
最新文章时间为2019年12月，实际最新文章时间为2020年2月

### 额外信息（日志、报错等）
腾讯大家首页可能在2020年经过了改版，查看了下2019年的文章，文章的版面与2020年有所区别，2020年的文章链接到了腾讯新闻，非以往的腾讯大家页面。另外，腾讯大家手机页面与PC页面也有所区别，PC页面更新及时，手机页面的最新文章仍停留在2019年10月。

**Comment by StrollStars** [comment]
同上，发现RSS最新内容只到去年12月12日。

**Comment by hoilc** [comment]
@StrollStars 这个产品是不是被放弃了...

**Comment by StrollStars** [comment]
@hoilc 应该没有，不过随着维护量上去，人手不够压力会增大的。

**Comment by hoilc** [comment]
@StrollStars 啊？我是说腾讯大家 手机端不更新了 网页端更新很少还有重复 链接也都跳转到腾讯新闻

**Comment by StrollStars** [comment]
@hoilc 我腾讯新闻也没看到比原大家更多文章，公众号就多了一天的文章，如果不是因为疫情暂停，那么可能是停更了。

**Comment by ruleroller** [comment]
![image](https://user-images.githubusercontent.com/3047708/75100868-a3736100-560e-11ea-97e5-d6414bd538f1.png)

关闭了，可以考虑是否该移除相关路由了，唉。
