### ISSUE TITLE
【Google Site】博客 Rss wanted

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4007]
### 网站地址
https://sites.google.com/site/ID/ ，例如[https://sites.google.com/site/outlierseconomics/](https://sites.google.com/site/outlierseconomics/)，其ID为outlierseconomics
### 网站描述
谷歌的博客？
### 需要生成什么内容？

- [ ] 根据网站ID，按时间顺序生成文章推送

**Comment by zoenglinghou** [comment]
It seems rather impossible, given various forms and/or domains the sites could take.

I am looking at examples enlisted on this [website](https://www.sitebuilderreport.com/google-sites-examples). If I am misguided, please let us know.

看起来 Google Sites 能做成很多不同的样子，甚至还有自定域名，很难写出一个通用的脚本...

**Comment by hoilc** [comment]
> It seems rather impossible, given various forms and/or domains the sites could take.
> 
> I am looking at examples enlisted on this [website](https://www.sitebuilderreport.com/google-sites-examples). If I am misguided, please let us know.
> 
> 看起来 Google Sites 能做成很多不同的样子，甚至还有自定域名，很难写出一个通用的脚本...

找了几个Sites没发现通用模板或API，似乎有可选的RSS功能，不过很少有启用。

建议关闭。

**Comment by KwToPA** [comment]
我找到了这个地址，不知对生成rss有没有帮助
[https://sites.google.com/site/博客ID/system/app/pages/sitemap/list](https://sites.google.com/site/博客ID/system/app/pages/sitemap/list)

可以找到全部的帖子.
@zoenglinghou  @hoilc I found this url maybe this will help

**Comment by KwToPA** [comment]
上面这个链接是按时间轴排列的

**Comment by KwToPA** [comment]
弄错了，是这个
[https://sites.google.com/site/博客ID/system/app/pages/sitemap/hierarchy](https://sites.google.com/site/博客ID/system/app/pages/sitemap/hierarchy)

**Comment by hoilc** [comment]
> 我找到了这个地址，不知对生成rss有没有帮助
> [https://sites.google.com/site/博客ID/system/app/pages/sitemap/list](https://sites.google.com/site/%E5%8D%9A%E5%AE%A2ID/system/app/pages/sitemap/list)
> 
> 可以找到全部的帖子.
> @zoenglinghou @hoilc I found this url maybe this will help

看起来是通用的，我再瞧瞧

`list`时间正序，`hierarchy`有层级了

**Comment by hoilc** [comment]
没找到通用的时间显示，只能给你保证时间顺序了

**Comment by KwToPA** [comment]
> 没找到通用的时间显示，只能给你保证时间顺序了

大哥牛逼，谢谢大哥
