### ISSUE TITLE
Instagram no longer working?

### ISSUE THREAD

**Issue by BoD** [DIYgod/RSSHub#4012]
### Involved route
On [the documentation](https://docs.rsshub.app/en/social-media.html#instagram) you can see a sample Instagram link: https://rsshub.app/instagram/user/diygod

### What is expected?
An RSS feed of the posts

### What is actually happening?
A `404` error

**Comment by KenMizz** [comment]
Deploy on your own server and try it again

**Comment by DIYgod** [comment]
https://docs.rsshub.app/en/faq.html
