### ISSUE TITLE
Dcard报错

### ISSUE THREAD

**Issue by Rtc73v** [DIYgod/RSSHub#4021]
### 路由地址
/dcard/posts/popular
### 预期是什么？
正常使用
### 实际发生了什么？

Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
For online documentation and support please refer to docs.rsshub.app.

前几天是能正常使用的昨天更新后就发现不能用了。

**Comment by ruleroller** [comment]
![image](https://user-images.githubusercontent.com/3047708/74847165-a64f2700-536c-11ea-980d-af0a47645c5b.png)

有相同问题。
