### ISSUE TITLE
B站马前卒的睡前消息可以制作为订阅源吗？

### ISSUE THREAD

**Issue by 820239854** [DIYgod/RSSHub#4065]
https://space.bilibili.com/54992199/channel/detail?cid=82529

这是睡前消息是up主的其中一个播放列表，可以抓取up主特定的播放列表吗？

**Comment by yefoenix** [comment]
1.提issue请正确选择并遵循模板格式
![Screenshot 2020-02-22 at 21 35 37](https://user-images.githubusercontent.com/8215230/75093343-c0cb0f80-55bb-11ea-8603-1b0d1a43b909.png)
2.提issue请先认真阅读提示
![Screenshot 2020-02-22 at 21 35 54](https://user-images.githubusercontent.com/8215230/75093361-ddffde00-55bb-11ea-8c2a-c011ff625119.png)
