### ISSUE TITLE
Google Podcasts RSS 需求

### ISSUE THREAD

**Issue by stinkerfly** [DIYgod/RSSHub#4067]
### 网站地址
https://podcasts.google.com/
如 https://podcasts.google.com/?feed=aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1ZzbU1wM0F1ZGlvRmlsZXM&ved=0CAAQ4aUDahcKEwiglP7Tu-XnAhUAAAAAHQAAAAAQAQ&hl=en-GB
### 网站描述
谷歌旗下的播客集中营，类似于苹果自带的 Podcasts, 提供五花八门的播客内容。
### 需要生成什么内容？

- [对播客内容提供 RSS 输出，并于正常的（即支持 RSS）的播客客户端可用。 ] 内容一
- [对新增播客栏目的标题按类别提供 RSS 输出。 ] 内容二

### 额外描述
举个例子，比如说 [VSM: Mp3 audio files](https://podcasts.google.com/?feed=aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1ZzbU1wM0F1ZGlvRmlsZXM&ved=0CAAQ4aUDahcKEwiglP7Tu-XnAhUAAAAAHQAAAAAQAQ&hl=en-GB)，
根据 `?feed=aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1ZzbU1wM0F1ZGlvRmlsZXM` 
对应生成 `/googlepodcasts/aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL1ZzbU1wM0F1ZGlvRmlsZXM` ,
而 `&ved=0CAAQ4aUDahcKEwiglP7Tu-XnAhUAAAAAHQAAAAAQAQ&hl=en-GB` 没用。

### 多谢！

**Comment by hoilc** [comment]
Google Podcasts 本身就是采集的RSS，不是很有必要再过RSSHub一手吧，被缓存了反而更新不及时

**Comment by stinkerfly** [comment]
> 
> 
> Google Podcasts 本身就是采集的RSS，不是很有必要再过RSSHub一手吧，被缓存了反而更新不及时

不全是这样，比如上面所举的音乐播客，[源站](https://www.virtualsheetmusic.com/news.rss) **不**提供音频输出。我也搞不明白谷歌在哪抓取的。

**Comment by hoilc** [comment]
> > Google Podcasts 本身就是采集的RSS，不是很有必要再过RSSHub一手吧，被缓存了反而更新不及时
> 
> 不全是这样，比如上面所举的音乐播客，[源站](https://www.virtualsheetmusic.com/news.rss) **不**提供音频输出。我也搞不明白谷歌在哪抓取的。

http://feeds.feedburner.com/VsmMp3AudioFiles

查看源代码，搜索`data-feed`

![image](https://user-images.githubusercontent.com/9067094/75114054-cc870680-568d-11ea-978b-8c48dc6f69a9.png)

**Comment by stinkerfly** [comment]
多谢，明白了！
