### ISSUE TITLE
好奇怪rss 源不能正常更新

### ISSUE THREAD

**Issue by caoyu-yiyue** [DIYgod/RSSHub#4084]
### 路由地址

https://rsshub.app/qdaily/notch/posts

### 预期是什么？

正常获取更新

### 实际发生了什么？

最后一次的信息是2020-02-14，之后无法再从rss 获取信息。但[好奇心日报网站](http://www.qdaily.com/) 一直还在更新。

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by HenryQW** [comment]
很遗憾，好奇怪 app 已经打不开了

**Comment by hoilc** [comment]
> 很遗憾，好奇怪 app 已经打不开了

所以我们应该移除它，就像腾讯大家？

也许我们可以有个`retired`分类😜

**Comment by caoyu-yiyue** [comment]
> > 很遗憾，好奇怪 app 已经打不开了
> 
> 所以我们应该移除它，就像腾讯大家？
> 
> 也许我们可以有个`retired`分类😜

但是好奇怪App 实际上一直在更新好奇心日报网站的内容，而网站一直在正常更新，看起来问题不是腾讯大家遇到的那样。
所以是不是可以将这个rss 源合并为“好奇心日报”，继续更新网站上的信息呢？

**Comment by HenryQW** [comment]
好奇怪和好奇心更新的内容其实是一样的，不太容易合并，大家直接订阅好奇心吧。

**Comment by caoyu-yiyue** [comment]
> 好奇怪和好奇心更新的内容其实是一样的，不太容易合并，大家直接订阅好奇心吧。

OK，了解了！感谢维护！
