### ISSUE TITLE
App Store iOS 应用更新 的路由 出岔子

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4095]
### 路由地址
https://rsshub.app/appstore/update/us/id1406710800
### 预期是什么？
我订阅的是iOS的Stardew Valley，所以应该是显示 "for iOS"
### 实际发生了什么？
变成了 "for macOS".
### 部署相关信息
官方demo和自建都如此。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/75391296-bf377980-5924-11ea-9583-cc77e809bda5.png)

@HenryQW 作者是否能看看呀？

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/75399976-b8454280-58f5-11ea-9df5-5737bf32ffa5.png)
我这没问题。

**Comment by ruleroller** [comment]
呃，时好时坏的，暂时又好了。
