### ISSUE TITLE
吹牛部落 专栏列表路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#4101]
### 网站地址
http://chuiniu.duanshu.com/#/list/column
### 网站描述
临高启明更新站点之一的新专栏列表
### 需要生成什么内容？

- [ ] 新专栏列表 rss

**Comment by hoilc** [comment]
基于短书，似乎可以做个通用路由

同平台有 https://e.yeslicake.com/

**Comment by LogicJake** [comment]
> 基于短书，似乎可以做个通用路由
> 
> 同平台有 https://e.yeslicake.com/

接口好像不太一样
