### ISSUE TITLE
小米有品每日上新更新错误

### ISSUE THREAD

**Issue by richartli** [DIYgod/RSSHub#4108]
### 路由地址
https://rsshub.app/mi/youpin/new
### 预期是什么？
获取每日上新商品信息
### 实际发生了什么？
网站每日上新商品不能全部获取，同时有可能获取到的是很久之前的商品信息
### 部署相关信息
官方地址

### 额外信息（日志、报错等）
目标地址：https://m.xiaomiyoupin.com/w/newproduct?_rt=weex&pageid=1605

**Comment by hoilc** [comment]
关注的上新页面不一样吧

https://home.mi.com/newproduct?pageid=4
