### ISSUE TITLE
rss源无法添加到feed上

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#411]
RSSHub已经部署在vps上，
```
npm start &

> rsshub@0.0.1 start /RSSHub
> node index.js
warn: pixiv RSS is disabled for lacking config.
warn: Disqus RSS is disabled for lacking config.
warn: Twitter RSS is disabled for lacking config.
warn: Youtube RSS is disabled for lacking config.
warn: Telegram RSS is disabled for lacking config.
warn: GitHub Repos RSS is disabled for lacking config.
info: 🎉 RSSHub start! Cheers!
info: Listening Port 1200
```
127.0.0.1:1200能打开，知乎用户的动态能通过rss读取。不过好像和我vps上的无关，我把node index.js 终止后，https://rsshub.app/zhihu/people/activities/ 也能被正常读取(我是通过https://feedly.com/ 这个看的)。

请问如何能够使用自己vps上部署的rssHub？ 谢谢

**Comment by KwToPA** [comment]
我挂着ss，把https://rsshub.app/链接换成http://vps_ip:1200/zhihu/people/activities/xx 后，浏览器可以正常打开，但是feedly无法识别，而且用本地ip无法打开上述链接。

**Comment by Qixingchen** [comment]
@KwToPA 请配置 VPS 防火墙允许外部网络访问 1200 端口

**Comment by KwToPA** [comment]
谢谢 成功了

**Comment by KwToPA** [comment]
之前用https://rsshub.app/  作为rss源添加时，虽然也出现过error 404，但添加成功

**Comment by makttub** [comment]
我遇到了同样的问题，解决方案是购买一个域名绑定到 vps，开启 https 后，问题得以解决。

**Comment by renzhexigua** [comment]
Find a similar issue here: [Feedly.com not accepting it](https://github.com/jpmonette/feed/issues/62)

> Feedly does not currently let you add feeds with **non-standard ports** (e.g. 3322). It finds the feed via search just fine. When you try to add it to your feeds you will get a 404 error and the "dead or invalid feed" message. I had to **change to the standard 80/443** to get my valid feed accepted by feedly.

Post the solution here as it suits my case.

**Comment by RainyH2O** [comment]
提供一下通过反向代理解决的方案，安装nginx，增加如下配置到server_name与部署环境域名或IP相同的server块下：
```
    location = /rss {
        return 301 http://$server_name$request_uri/;
    }
    location /rss/ {
        proxy_pass http://localhost:1200/;
    }
```
然后把订阅链接`http://${server_name}:1200/${router_uri}`换成`http://${server_name}/rss/${router_uri}`就可以通过Feedly订阅了。
