### ISSUE TITLE
T66Y无法获取版面新发布的帖子

### ISSUE THREAD

**Issue by Tao-kun** [DIYgod/RSSHub#4121]
### 路由地址

`/t66y/16`

### 实际发生了什么？

T66Y目前因为反爬的原因限定爬取前25条，但是`/t66y/16`长期有大量（超过25条）顶置贴，会导致更新十分困难，获取不到新发布的非顶置贴

我尝试将`.slice(0, 25)`修改为原来的`.slice(0, -1)`，但是触发了反爬

### 预期是什么？

**除**顶置贴外能够得到部分非顶置的新发布帖子（这些帖子的发布时间不被标记为`Top-marks`）

### 部署相关信息

Docker Hub上的最新版本（d7b54a1a8527）

**Comment by hoilc** [comment]
这个比较麻烦欸🤔那置顶帖到底是要还是不要呢？

**Comment by Tao-kun** [comment]
顶置贴和更新帖（部分）应该都要的吧，但是不知道触发反爬的阈值是多少，根本不好确定范围🤐

或者将顶置贴存在缓存中，有较长的有效期，多次获取时只更新非顶置贴？

**Comment by hoilc** [comment]
那么就是第一次获取置顶帖后，一定时间后刷新再获取非置顶帖？体验比较奇怪，考虑到置顶帖已经大于反爬阈值，且阈值未知，逻辑会比较复杂。

我觉得还不如考虑分散去抓1024的镜像站，反扒策略按道理是独立的。

**Comment by Tao-kun** [comment]
403是从源站发出的，所以被反爬后访问那些反向代理的镜像站也会403

我找些别的方法好了

**Comment by IMLR** [comment]
遇到跟你一样的问题，之前改成了50调，也触发了反爬。
我现在的操作是复制了一个路由，这个路由只访问25-50条的内容
