### ISSUE TITLE
【路由需求】Github repo Issues by Label 路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#4145]
### 网站地址
例：https://github.com/DIYgod/RSSHub/labels/RSS%20wanted
or
https://github.com/DIYgod/RSSHub/issues?q=is%3Aopen+is%3Aissue+label%3A%22RSS+wanted%22
### 网站描述
Gayhub
### 需要生成什么内容？

- [ ] 为 github 仓库 增加特定标签的 issue 的路由

**Comment by hoilc** [comment]
https://rsshub.app/github/issue/DIYgod/RSSHub/open/RSS%20wanted

#3766 已添加，国外老哥没有更新中文文档
