### ISSUE TITLE
instagram抓取出错

### ISSUE THREAD

**Issue by jiey2016** [DIYgod/RSSHub#4149]
### 路由地址
https://rsshub.app/instagram/user/rupaulofficial

### 预期是什么？
正常使用

### 实际发生了什么？
报错：
TypeError: Cannot read property '0' of undefined
at module.exports (/app/lib/routes/instagram/user.js:15:45)
at process._tickCallback (internal/process/next_tick.js:68:7)

### 部署相关信息
![image](https://user-images.githubusercontent.com/19381978/75670907-97476d80-5cb8-11ea-8525-75fdf11c80d9.png)

### 额外信息（日志、报错等）
instagram反爬严格，之后采用了多个自建地址依然出现此错误！跟反爬无关！

**Comment by yefoenix** [comment]
@jiey2016 我自建抓取没问题，
如果自建的抓取频率过高，同样可能被反爬。

**Comment by dabo-t** [comment]
我这自建没有问题。
我这目前测试下来，建议24小时内，访问不要超过288次。自建建议延长缓存时间。
