### ISSUE TITLE
希望增加下关闭FT中文网评论的功能

### ISSUE THREAD

**Issue by EsuRt** [DIYgod/RSSHub#4170]
### 这是一个什么样的功能？
关闭FT中文网RSS中的文章评论

### 这个功能可以解决什么问题？
FT中文网文章出现评论的频率较低，RSS中每篇文章都出现评论模块有点影响阅读体验，希望能完善下。

### 额外描述
可以在路由中增加一个参数，方便用户进行选择。

**Comment by hoilc** [comment]
评论不是服务器渲染的，实际评论通过接口获取，所以移除
