### ISSUE TITLE
自建的RSSHub BBC Chinese报错

### ISSUE THREAD

**Issue by jerrywcy** [DIYgod/RSSHub#4183]
### 路由地址
139.196.180.51:1200
### 预期是什么？
返回内容
### 实际发生了什么？
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
![image](https://user-images.githubusercontent.com/34678939/76067178-ed265900-5fc9-11ea-8635-d955f6b3bc36.png)

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |         CentOS 8.0.1905      |
| Node version       |      v10.9.0         |
| if Docker, version |               |

### 额外信息（日志、报错等）
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)

**Comment by hoilc** [comment]
@jerrywcy bbc被墙了吧？需要代理
