### ISSUE TITLE
YouTube多api支持

### ISSUE THREAD

**Issue by Quan666** [DIYgod/RSSHub#4188]
### 这是一个什么样的功能？
这是一个可以使用多个YouTube api的功能，和推特的路由类似
### 这个功能可以解决什么问题？
可以解决单个api每日调用达到上限后无法调用的问题
### 额外描述
可以在一个api调用次数达到上限后转另一个api
api达到上线的提示信息：
Error: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=824879364250
    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by DIYgod** [comment]
寻求一枚 YOUTUBE_KEY

**Comment by Quan666** [comment]
请将邮箱发给我，我发送key给你。

**Comment by Quan666** [comment]
我已经将key发送到您的邮箱了，请注意查收

**Comment by DIYgod** [comment]
Done aadb6ba0e5a1b2d7d200fc104d36a5018eed921c
