### ISSUE TITLE
对同一域名下的多个分类/栏目整合成一个订阅源

### ISSUE THREAD

**Issue by kevin7lou** [DIYgod/RSSHub#4192]
### 这是一个什么样的功能？
对同一域名下的多个分类/栏目整合成一个订阅源。举个例子，我喜欢看好奇心日报，但不希望所有的栏目和频道都在一个源里。可能我会选择两三个专栏和分类，比如：
* https://rsshub.app/qdaily/column/29
* https://rsshub.app/qdaily/column/4
* https://rsshub.app/qdaily/category/18
能否将以上三个源整合成一个，比如：https://rsshub.app/qdaily/{category,column}/{18,29,4}
### 这个功能可以解决什么问题？
1. 大多数的RSS阅读器基础版都有订阅源限制的要求，这样整合节省了资源占用
2. 对订阅源的内容更加精细化管理

### 额外描述
similar issue: [源的合并输出](https://github.com/DIYgod/RSSHub/issues/283)

**Comment by yefoenix** [comment]
参考 #514 的讨论，鉴于
1. 需求非常小众；
2. 实现难度较高；
3. 已有现存合并服务可用（自行搜索 "rss combine" 等关键词），
不建议在 rsshub 增加此功能

**Comment by hoilc** [comment]
真的意义不大

> 参考 #514 的讨论，鉴于
> 
> 1. 需求非常小众；
> 2. 实现难度较高；
> 3. 已有现存合并服务可用（自行搜索 "rss combine" 等关键词），
> 
> 不建议在 rsshub 增加此功能

Agree，意义不大

**Comment by DIYgod** [comment]
描述里说的都是应该阅读器做的事情，并不是合理的 RSS 需求，如果没有其他补充，issue 将被关闭
