### ISSUE TITLE
紳士漫畫RSS抓取

### ISSUE THREAD

**Issue by Quan666** [DIYgod/RSSHub#4196]
### 网站地址
https://wnacg.org/albums.html
### 网站描述
漫画网站
### 需要生成什么内容？

- [ ] 内容一 标题
- [ ] 内容二 封面
- [ ] 内容三 漫画链接

### 额外描述
万分感谢

**Comment by KenMizz** [comment]
我试试

**Comment by Quan666** [comment]
> 我试试

加油

**Comment by junfengP** [comment]
看了一下页面`head`，里面有`<meta name="generator" content="MeiuPic 2.2.0">` 
有没有可能做成通用的，以后遇到其他基于MeiPic的图片站可以直接套用。

**Comment by KenMizz** [comment]
我也看了一下，看来紳士漫畫本身是有rss的，这样会方便许多
![image](https://user-images.githubusercontent.com/16635884/76446080-dfdbe680-639c-11ea-8c06-ada8e320b5bf.png)

**Comment by KenMizz** [comment]
@Quan666 它这个有自己的rss，要不你试试？
https://wnacg.org/feed.html

**Comment by Quan666** [comment]
> @Quan666 它这个有自己的rss，要不你试试？
> https://wnacg.org/feed.html

能整合到rsshub一起吗？我不是很会nodejs

**Comment by KenMizz** [comment]
@Quan666 行

**Comment by Quan666** [comment]
> @Quan666 行

万分感谢

**Comment by KenMizz** [comment]
@Quan666 吼了 #4241

**Comment by Quan666** [comment]
> @Quan666 吼了 #4241
感谢

**Comment by Quan666** [comment]
> @Quan666 吼了 #4241
建议给图片加上标签，方便订阅软件获取图片。
<img src="" referrerpolicy="no-referrer">

**Comment by Quan666** [comment]
@KenMizz 抓取不到正确的图片链接了，图片链接都返回的是 https://wnacg.orgloading.jpg
rsshub 地址 https://rsshub.app/ssmh
