### ISSUE TITLE
How to debug docs?

### ISSUE THREAD

**Issue by sgqy** [DIYgod/RSSHub#4198]
I want to add a locale module into `docs/.vuepress/components`.
I have no knowledge in vue.js, so 99% in my time is getting `<!---->`.
All I get in console is `[clear screen] \n success [22:27:59] Build b60b01 finished in 218 ms! ( http://localhost:8080/ )`.
I need verbose debug message, to know why it is wrong. What should I do?

**Comment by DIYgod** [comment]
Please refer to https://github.com/vuejs/vuepress

**Comment by DIYgod** [comment]
BTW, what component do you want to add
