### ISSUE TITLE
希望支持微博全文展示功能

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#42]
![image](https://user-images.githubusercontent.com/10363328/39079145-9afc863e-4547-11e8-9e57-253ba925478a.png)

**Comment by DIYgod** [comment]
接口限制，暂时无解

**Comment by DerekTso** [comment]
不太明白有什么限制? 我的理解是把 `全文` 的链接URL 再发一个 request, 然后将返回的 `response.data.data.text` 做为最终的结果。难道我理解错了?

**Comment by DIYgod** [comment]
即使可以，每篇文章都需要额外调用接口，代价太大

**Comment by wydwww** [comment]
这个项目可以输出全文
https://github.com/zgq354/weibo-rss
