### ISSUE TITLE
希望增加电影电视剧bt下载网站 https://btbtt.us 的rss

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4203]
### 网站地址
https://btbtt.us/  [其实还有其它许多的域名](http://btbtt.me/thread-index-fid-2-tid-4495126.htm)
### 网站描述
这个不是bt之家（logo 是 btbtt），是仿品（logo 是 btbbt，和域名有差别），页面格式也都和bt之家十分相似，里面的电影剧集也不少。
### 需要生成什么内容？

- [ ] 主页。
- [ ] 各分类：电影、剧集、高清电影、动漫、等其它有意义的本站分类

### 额外描述
是个电影剧集rss的好补充，恳请bt之家rss的作者 @zhang-wangz 或者其它高手有空时能补充一下。多谢啦！

**Comment by junfengP** [comment]
这个网站是基于修罗开源论坛搭建的
从页面`head`中可以看到`<meta name="generator" content="Xiuno BBS">`

建议做一个通用的，未雨绸缪

**Comment by ruleroller** [comment]
楼上的提议，那是最好不过的啦，兹糍。

**Comment by zhang-wangz** [comment]
@ruleroller 你好，域名btbbt.us和88btbtt.com是同一家网站运维的，内容是一致的，区别是根据不同区域，访问的速度有些不同

**Comment by zhang-wangz** [comment]
@junfengP 你好，我所写的rss就是根据这个generator写的..目前只发现两种不同的生成类型，欢迎补充

**Comment by ruleroller** [comment]
@zhang-wangz 一样的么，但我粗看页面上的内容似乎有差别的。那我先关了吧。
