### ISSUE TITLE
基于建筑设计方向上下游咨询网站集合，一个人做不完，寻找同伴一起爬

### ISSUE THREAD

**Issue by AprRapheal** [DIYgod/RSSHub#4205]
### 网站地址
https://allthearchitects.com/
https://www.contemporist.com/
https://www.easyrender.com/
https://www.lifeofanarchitect.com/
https://www.busyboo.com/
https://architizer.com/
https://divisare.com/
https://archinect.com/
### 网站描述
基于建筑设计方向上下游的工具交流信息网站
### 需要生成什么内容？

- [ ] 内容一
图片加载
- [ ] 内容二
文字排版
- [ ] 内容三
连接跳转

**Comment by yefoenix** [comment]
https://www.contemporist.com/feed/
https://www.busyboo.com/feed/

随便点了三个，两个是自带rss输出的……

**Comment by yefoenix** [comment]
https://archinect.com/feed/home

**Comment by TonyRL** [comment]
https://www.lifeofanarchitect.com/feed/podcast/
https://divisare.com/publications/11/feed
