### ISSUE TITLE
少数派 专题内文章更新订阅失败

### ISSUE THREAD

**Issue by Jessie722** [DIYgod/RSSHub#4210]
### 路由地址

https://rsshub.app/sspai/topic/:id
包括演示地址也不能订阅
例如：https://rsshub.app/sspai/topic/279

### 预期是什么？
订阅成功
### 实际发生了什么？
订阅源无效

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by sunshinenny** [comment]
经过测试 API未发生变化。理论上可以订阅。

你可以尝试一下自建 看看有没有问题

**Comment by DIYgod** [comment]
目前看起来没问题，可能网络波动
