### ISSUE TITLE
Linux环境下服务器不处理请求

### ISSUE THREAD

**Issue by JokeNeverSoke** [DIYgod/RSSHub#4213]
### 路由地址
route: `"/*"`
（全部）

### 预期是什么？
请求正常返回数据

### 实际发生了什么？
服务器显示收到请求，不作处理。
把dotenv移除后对dotenv有需求的路由没有报错。
客户端测试一直等待中（python-requests，reeder）
同样配置下mac OS没有问题
npm+yarn start都会出现

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Ubuntu 18.04 bionic          |
| Node version       |      v13.10.1         |
| 部署方式 |    git + npm/yarn start           |
| git | commit ` 4f70770d685113610c5704341b6ce2df7645fe95`|

### 额外信息（日志、报错等）
无

**Comment by DIYgod** [comment]
看下日志？

**Comment by JokeNeverSoke** [comment]
logs/combined.log
```json
{"message":"Listening Port 1200","level":"info"}
{"message":"🎉 RSSHub start! Cheers!","level":"info"}
{"message":"/rsshub/routes, user IP: ::ffff:14.219.237.76","level":"info"}
{"message":"/bilibili/weekly/, user IP: ::ffff:14.219.237.76","level":"info"}
{"message":"/bilibili/followings/video/152156332, user IP: ::ffff:14.219.237.76","level":"info"}
{"message":"/bilibili/followings/article/152156332, user IP: ::ffff:14.219.237.76","level":"info"}
{"message":"/bilibili/user/bangumi/152156332, user IP: ::ffff:14.219.237.76","level":"info"}
```
这里的`bilibili/following/article/XXX`所需的cookie是被移除状态

logs/error.log为空

**Comment by DIYgod** [comment]
日志看起来没问题，我也不知道
