### ISSUE TITLE
【约翰霍普金斯大学-新型冠状病毒感染的肺炎全球病例追踪】

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#4214]
网站地址
https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

网站描述
霍普金斯大学制作的全球病例追踪

需要生成什么内容？

- [ ] 疫情病例情况
- [ ] 实时播报

额外描述
[数据可以获取自他们的GitHub](https://github.com/CSSEGISandData/COVID-19)
[Row data](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv)

**Comment by BrandNewLifeJackie26** [comment]
大概看了一下 数据量比较大，不太容易在一个页面里面用表格显示。如果有更详细的内容或者格式需求最好。要不然就强制输入省份和国家来减少数据展示量。
