### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by jtagcat** [DIYgod/RSSHub#4216]
### Website URL
https://vimeo.com/
### Website description
Vimeo is an ad-free video platform, providing free video viewing services as a competitor to YouTube.
### What content should be included?
- [ ] videos in channels
   - [ ] channel name
   - [ ] video title
   - [ ] video release date
   - [ ] link to video

### Additional description
Currently, in conversation with Vimeo. They used to support RSS, but discontinued due to low demand. Asked for resources of their previous implementation, or for a more parsable page.

**Comment by jtagcat** [comment]
note to self: might attempt to add it myself (but due to major lack of time, will probably be delayed 3-6 months)
https://docs.rsshub.app/en/joinus/#submit-new-rss-rule
@jtagcat

**Comment by hoilc** [comment]
https://vimeo.com/channels/staffpicks/videos/rss

It seems worked as expected.

**Comment by jtagcat** [comment]
> https://vimeo.com/channels/staffpicks/videos/rss
> 
> It seems worked as expected.

I'm surprised, I didn't find it myself and their staff told that they removed RSS support entirely.
