### ISSUE TITLE
部署后能正常访问订阅源，但会出现额外的报错

### ISSUE THREAD

**Issue by EdgeStar** [DIYgod/RSSHub#4219]
出现的错误似乎并不影响正常使用，我是今天才第一次部署使用，想询问一下这是正常现象还是什么地方出了问题，有无解决方法
报错内容：error: Redis error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379,"stack":"Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)"}
报错截图：
![image](https://user-images.githubusercontent.com/58938653/76405593-555aad80-63c3-11ea-871e-eeed07888be9.png)

**Comment by junfengP** [comment]
@EdgeStar 连接不上redis, 要么部署redis，要么根据部署文档，设置缓存为空

**Comment by EdgeStar** [comment]
> @EdgeStar 连接不上redis, 要么部署redis，要么根据部署文档，设置缓存为空

我根据部署文档，设置缓存为空后，之前的频繁重复报错不再出现了，但是偶尔会出现新的报错，内容为“  Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)”，这是因为什么地方设置错误了吗，另外，RSS部署期间是否不能关闭cmd.exe-yarn start命令框，我发现在我的电脑关闭此命令框后就无法获取RSS了，有无其他的替代解决方法，非常感谢您能抽时间回答我的问题

**Comment by junfengP** [comment]
@EdgeStar 可能是网络问题。

正常来说是不能关闭`cmd.exe`的，可以百度`BAT脚本后台运行`等内容。
脚本内容
```bat
cd /path/to/rsshub
yarn start
```

**Comment by EdgeStar** [comment]
> @EdgeStar 可能是网络问题。
> 
> 正常来说是不能关闭`cmd.exe`的，可以百度`BAT脚本后台运行`等内容。
> 脚本内容
> 
> ```batchfile
> cd /path/to/rsshub
> yarn start
> ```

好的，非常感谢
