### ISSUE TITLE
NGA 支持子分区

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#4224]
### 网站地址

分区: https://nga.178.com/thread.php?fid=616

子分区: https://nga.178.com/thread.php?stid=20496737

### 网站描述

知名游戏论坛

### 需要生成什么内容？

- [ ] 分区内容 `/nga/forum/fid/616`
- [ ] 子分区内容 `/nga/forum/stid/20496737`

### 额外描述

现有 nga 路由只支持分区 `/nga/forum/616`，希望支持子分区并对它们做出区分

**Comment by ruleroller** [comment]
大佬是太忙么，应该先实践一下的。
![批注 2020-03-12 131254](https://user-images.githubusercontent.com/3047708/76489477-6e1aa000-6463-11ea-8a2b-7fd27b1df088.png)

**Comment by DIYgod** [comment]
还能这样？代码里明明传的是 fid，难道 fid 和 stid 是互相兼容的？
