### ISSUE TITLE
RSS Wanted: Jikipedia (小鸡词典)

### ISSUE THREAD

**Issue by SharonOlds** [DIYgod/RSSHub#4232]
### 网站地址
jikipedia.com
### 网站描述
首页随机，不按时间线排列
### 需要生成什么内容？

- [ ] 最新或热门的词条内容

如果抓取不了首页的话：
- [ ] 收录请求页的最新请求
- [ ] 关键词的搜索结果页的更新
- [ ] 用户时间线

**Comment by DIYgod** [comment]
最新或热门的词条内容 在哪

**Comment by SharonOlds** [comment]
> 最新或热门的词条内容 在哪

目前来看比较可行的是抓取用户时间线
https://jikipedia.com/definitions/user/{:userid}
以及特定标签的内容
https://jikipedia.com/definitions/tag/{:tagid}

**Comment by ringcrl** [comment]
同求，或者类似的热词 RSS

**Comment by TonyRL** [comment]
They have ceased their business
