### ISSUE TITLE
Github repo contributor 路由需求

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#4238]
### 网站地址
Github.com
例： https://github.com/DIYgod/RSSHub/graphs/contributors
### 网站描述
Gayhub
### 需要生成什么内容？

- [ ] New Contributors Feed
- [ ] Top XXX Contributors Feed

**Comment by hoilc** [comment]
https://developer.github.com/v3/repos/#list-contributors

并没有新贡献者的API

**Comment by zoenglinghou** [comment]
@holic 其实可以实现的吧？把user id设为uid。
我试一下~

**Comment by zoenglinghou** [comment]
现在这个是按commit数量升降序的，大致可以实现需求...

**Comment by hoilc** [comment]
对的，API只有Top X贡献者
