### ISSUE TITLE
zimuzu/resource 的某些影视没有显示磁力的资源链接

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4239]
### 路由地址
https://rsshub.app/zimuzu/resource/
### 预期是什么？
每个条目应该都含有magnet的磁力链
### 实际发生了什么？
其中一些没有magnet的磁力链，请见附图中的“这不是柏林”的相关条目。此为一例。
### 部署相关信息
官方和自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![批注 2020-03-13 190730](https://user-images.githubusercontent.com/3047708/76616080-3e03f780-655e-11ea-88b1-ad21367f3b91.png)

**Comment by hoilc** [comment]
http://rss.rrys.tv/rss/feed/0

源RSS既是如此，并不是所有资源都有磁力链接，有些只有百度盘

![image](https://user-images.githubusercontent.com/9067094/76755072-33e03400-67be-11ea-84b4-1accb17c39f9.png)

**Comment by ruleroller** [comment]
是不是可以再改造一下，将只提供百度盘的链接也弄到description里呢？

**Comment by hoilc** [comment]
> 是不是可以再改造一下，将只提供百度盘的链接也弄到description里呢？

可以啊，给你全列出来吧

**Comment by hoilc** [comment]
> 是不是可以再改造一下，将只提供百度盘的链接也弄到description里呢？

我看了下，RSS里只给了百度盘链接，然而没有提取码，所以没什么意义

**Comment by ruleroller** [comment]
@hoilc 那算了，就保持这样吧。：）
