### ISSUE TITLE
星島日報 [溫哥華/繁體版] 首頁新聞更新 RSS 生成請求

### ISSUE THREAD

**Issue by bdel** [DIYgod/RSSHub#4243]
### Website URL
https://www.singtao.ca/vancouver/?variant=zh-hk

### Website description
星島日報溫哥華繁體版首頁新聞更新RSS全文輸出

### What content should be included?

- [ ] 標題
- [ ] 新聞內文

### Additional description
謝謝

**Comment by yefoenix** [comment]
http://api.singtao.ca/counter/genpopularlist.php?tag=singtao_ca_van

**Comment by hoilc** [comment]
https://www.singtao.ca/feed/

**Comment by groundcat** [comment]
https://www.singtao.ca/feed/ 已无法访问。
