### ISSUE TITLE
leboncoin feed doesn't work

### ISSUE THREAD

**Issue by karousn** [DIYgod/RSSHub#4244]
### Involved route
https://docs.rsshub.app/en/shopping.html#leboncoin

### What is expected?
rss data for the leboncoin result
### What is actually happening?

the given example  : https://rsshub.app/leboncoin/ad/category=10&locations=Paris_75015 give **Looks like something went wrong
Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.**

**Comment by karousn** [comment]
i think it related to @Platane work ( thanks for the effort btw )

**Comment by hoilc** [comment]
> i think it related to @Platane work ( thanks for the effort btw )

The anti-crawler policy is triggered as a result of lack of the common header `accept`.

**Comment by Platane** [comment]
thanks for reporting on that issue. And thanks @hoilc for the fix :+1:
