### ISSUE TITLE
提一个跟rss无关的问题

### ISSUE THREAD

**Issue by raining1123** [DIYgod/RSSHub#4248]
![image](https://user-images.githubusercontent.com/17892238/76704018-17d28900-6711-11ea-8a36-fd52bd4ea184.png)

为什么贵网站在windows10 edge、chrome上字体显示如此奇怪
据查应该是什么少女体，本汉子从未装过该字体
现在只能用dark reader这个插件来改过来，求问有什么一劳永逸的办法不？

**Comment by yefoenix** [comment]
@raining1123 F12 看一下当前的 CSS 吧……应当是你浏览器环境的问题，检查一下有没有奇怪的扩展
