### ISSUE TITLE
Javlibrary 两个路由增加新的模式

### ISSUE THREAD

**Issue by Byhaise** [DIYgod/RSSHub#4252]
### 网站地址
http://www.javlibrary.com/cn/tl_bestreviews.php?&mode=2&
http://www.javlibrary.com/cn/vl_bestrated.php?&mode=2&
### 网站描述
老司机图书馆
### 需要生成什么内容？
- [ ] 最佳评论 - 全部
- [ ] 评价最高的影片 - 全部
### 额外描述
现有的
https://rsshub.app/javlibrary/videos/bestrated
https://rsshub.app/javlibrary/bestreviews
都是现实上个月的内容，没有全部内容

**Comment by junfengP** [comment]
@Byhaise 首先要明确rss的目的，是抓取更新。
如果是全部内容，按照排序性质可分为时间排序和评分排序。
时间排序与上月内容无差别，评分排序的缺点是可能结果集长期不变化。

请分清楚rss和爬虫的区别。
