### ISSUE TITLE
PMCAFF 作者文章页 RSS 需求

### ISSUE THREAD

**Issue by queenie1818** [DIYgod/RSSHub#4259]
### 网站地址
https://www.pmcaff.com/user/profile/Oak7mqnEQJ

### 网站描述
互联网产品作者文章页
### 需要生成什么内容？
rss作者文章
- [ ] 内容一
- [ ] 内容二

**Comment by SChen1024** [comment]
已经添加了, 可以去看 https://docs.rsshub.app/new-media.html#pmcaff
