### ISSUE TITLE
快递100 封锁 demo ip

### ISSUE THREAD

**Issue by NeverBehave** [DIYgod/RSSHub#4262]
### 路由地址
/kuaidi100/*

### 预期是什么？
正确获取信息

### 实际发生了什么？

请求时链接被rst，预计demo地址将完全不可用

### 额外信息（日志、报错等）

经 playwithdocker 验证路由可用

**Comment by lisxray** [comment]
标记为反爬严格吧

**Comment by NeverBehave** [comment]
> 标记为反爬严格吧

但是demo如果没有更换ip的话，这个api算是废了
然而全部走代理又很浪费流量（lambda动态ip算流量很费）
有部分项目走代理的计划吗？

**Comment by DIYgod** [comment]
代理太贵了，暂时没这个计划...这种情况还是建议自建

**Comment by DIYgod** [comment]
发现不是反爬，应该是网络不稳定，do02 节点是好的：https://do02.rsshub.app/kuaidi100/track/shunfeng/SF1007896781640/0383

**Comment by NeverBehave** [comment]
> 发现不是反爬，应该是网络不稳定，do02 节点是好的：https://do02.rsshub.app/kuaidi100/track/shunfeng/SF1007896781640/0383

i了i了，国内这个链接有点头疼

**Comment by DIYgod** [comment]
发现是因为 do01 节点的 IP 被墙了（不是 RSSHub 的原因，一开始就是被墙的），现在换了个新 IP，应该不会出现类似问题了
