### ISSUE TITLE
WEEX 一起交易 RSS 抓取请求 

### ISSUE THREAD

**Issue by DeepestAbyss** [DIYgod/RSSHub#4263]
### 网站地址
https://weexcn.com/news/newest
### 网站描述
华尔街见闻旗下全球投资线上品牌
### 需要生成什么内容？

- [ ] 标题 
- [ ] 链接
- [ ] 正文 

### 额外描述
Thx lot :-p

**Comment by SChen1024** [comment]
已经加入了, 可以查看,  https://docs.rsshub.app/finance.html#weex-hua-er-jie-jian-wen-qi-xia-quan-qiu-tou-zi-xian-shang-pin-pai
