### ISSUE TITLE
希望可以增加抓取xda论坛

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#4282]
已确保 [文档](https://docs.rsshub.app) 和 [issue](https://github.com/DIYgod/RSSHub/issues) 中没有相关内容，源站提供的RSS只有主页信息流，没有单独的机型板块。

### 网站地址
forum.xda-developers.com
### 网站描述
XDA Developers（也简称为XDA）是一个移动软件开发社区，主要围绕Android展开，也是全世界最大的安卓刷机论坛。
### 需要生成什么内容？
生成每个机型对应的板块
- [ ] Forum
- [ ] ROMs
- [ ] Kernels
### 额外描述
举个例子，比如追踪 Redmi K20 Pro机型的Forum板块，即https://forum.xda-developers.com/k20-pro/development#subForums

**Comment by yefoenix** [comment]
提issue请遵循模板，提供必要信息

**Comment by Alphabet1226** [comment]
> 提issue请遵循模板，提供必要信息

很抱歉之前没有注意，已重新编辑如下：

已确保 [文档](https://docs.rsshub.app) 和 [issue](https://github.com/DIYgod/RSSHub/issues) 中没有相关内容，源站提供的RSS只有主页信息流，没有单独的机型板块。

### 网站地址
forum.xda-developers.com
### 网站描述
XDA Developers（也简称为XDA）是一个移动软件开发社区，主要围绕Android展开，也是全世界最大的安卓刷机论坛。
### 需要生成什么内容？
生成每个机型对应的板块
- [ ] Forum
- [ ] ROMs
- [ ] Kernels
### 额外描述
举个例子，比如追踪 Redmi K20 Pro机型的Forum板块，即https://forum.xda-developers.com/k20-pro/development#subForums

**Comment by cijiugechu** [comment]
提issue之前可以先搜索网页的head，比如xda就自带了rss，在网址后加上 /feed 即可生成

**Comment by Alphabet1226** [comment]
> 提issue之前可以先搜索网页的head，比如xda就自带了rss，在网址后加上 /feed 即可生成

源站提供的RSS只有主页信息流，没有单独的机型板块

**Comment by 10362227** [comment]
https://www.xda-developers.com/tag/honor9x/feed/
