### ISSUE TITLE
微信公众号爬取：通过“今天看啥”抓取的新方案

### ISSUE THREAD

**Issue by Abinthur** [DIYgod/RSSHub#4304]
### Website URL
http://www.jintiankansha.me/
### Website description
公众号间接抓取
### What content should be included?
目前方案多数都已经失效了。
wemp.app/传送门/等，通过“今天看啥”抓取似乎是不错的方案。个人曾无奈用今天看啥配合fetchrss抓取效果还行，可是免费用户ip和数量均有限制，希望github能一次性解决。谢谢
- [ ] content one
- [ ] content two

**Comment by tomatomash** [comment]
同请求今天看啥/专栏 BioArt 和 半佛仙人 
http://www.jintiankansha.me/column/uRbAcCYKay?type=recent
http://www.jintiankansha.me/column/uHr6p54M8i?type=recent

**Comment by jeasonlau** [comment]
@tomatomash 该网站原生支持RSS订阅，注册账号后可以得到专属RSS链接。

**Comment by tomatomash** [comment]
> @tomatomash 该网站原生支持RSS订阅，注册账号后可以得到专属RSS链接。

尝试过注册账号+订阅，免费用户只能订阅2个，更新周期也不稳定，rss 10天失效，所以比较鸡肋

**Comment by jeasonlau** [comment]
> > @tomatomash 该网站原生支持RSS订阅，注册账号后可以得到专属RSS链接。
> 
> 尝试过注册账号+订阅，免费用户只能订阅2个，更新周期也不稳定，rss 10天失效，所以比较鸡肋

嗯嗯，我刚写好了，等等发`pull request`

**Comment by DIYgod** [comment]
既然这个网站提供了付费 RSS，就不应该再做一个第三方的出来了...

@jeasonlau 抱歉让你的工作白费了，不过可以留着自己用😘
