### ISSUE TITLE
田间小站

### ISSUE THREAD

**Issue by jingyucx** [DIYgod/RSSHub#4307]
### 网站地址
https://www.tianfateng.cn/
### 网站描述
英语翻译学习及资源下载分享
### 需要生成什么内容？

- [ ] 内容一
- [ ] 内容二

**Comment by yefoenix** [comment]
@jingyucx https://www.tianfateng.cn/feed

**Comment by jingyucx** [comment]
哇，哭了，感谢~

**Comment by jingyucx** [comment]
> @jingyucx https://www.tianfateng.cn/feed

哇，哭了，感谢~

**Comment by yefoenix** [comment]
@jingyucx 本issue请close一下
