### ISSUE TITLE
bilibili 路由 aid -> bvid

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#4319]
### 这是一个什么样的功能？

https://www.bilibili.com/blackboard/activity-BV-PC.html

- [x] 部分 bilibili 路由传参支持 bvid
- [ ] 返回链接改用 bvid 链接

### 这个功能可以解决什么问题？

配合源站改版

### 额外描述

传参需要兼容现存的 aid 方式

guid 优先使用 aid，避免已订阅 RSS 出现大量旧内容

**Comment by fengkx** [comment]
Should be closed 158edd177ae35bedc3403b1d1fdc9d3793fbf163

**Comment by DIYgod** [comment]
> Should be closed [158edd1](https://github.com/DIYgod/RSSHub/commit/158edd177ae35bedc3403b1d1fdc9d3793fbf163)

1. 部分 bilibili 路由传参支持 bvid

2. 返回链接改用 bvid 链接

现在只好了 1
