### ISSUE TITLE
[功能建议]网站方官方的RSS功能增加内容过滤功能/RSS自动转rsshubRSS

### ISSUE THREAD

**Issue by 2220209876** [DIYgod/RSSHub#4329]
### 这是一个什么样的功能？
网站方官方的RSS功能增加内容过滤功能/RSS自动转rsshubRSS
### 这个功能可以解决什么问题？
比如A网站自带RSS功能，但是RSSHUB没有A网站的rsshub 的rss内容，这样只能订阅A网站自带的rss，不能过滤出想需要的内容。

**Comment by jeasonlau** [comment]
@2220209876 如果源站的rss不全面，例如只提供了首页rss，通常的解决办法是自行实现子版块的rss而不是内容过滤（因为往往没有明确的过滤规则  🤣

**Comment by yefoenix** [comment]
rss内容的过滤是阅读器该做的工作，rsshub 暂不接受相关需求。
Duplicate of #1818

**Comment by 2220209876** [comment]
> rss内容的过滤是阅读器该做的工作，rsshub 暂不接受相关需求。
> Duplicate of #1818
rsshub已经做了一部分阅读器该做的工作了
内容过滤
可以使用以下 URL query 过滤内容, 支持正则

filter 选出想要的内容

filter: 过滤标题和描述

filter_title: 过滤标题

filter_description: 过滤描述

filter_author: 过滤作者

filter_time: 过滤时间，仅支持数字，单位为秒。返回指定时间范围内的内容。如果条目没有输出pubDate或者格式不正确将不会被过滤

举例 1: https://rsshub.app/bilibili/user/coin/2267573?filter=微小微|赤九玖|暴走大事件 举例 2: https://rsshub.app/nga/forum/485?filter_time=600

filterout 去掉不要的内容

filterout: 过滤标题和描述
