### ISSUE TITLE
项目域名受到DNS污染

### ISSUE THREAD

**Issue by lychichem** [DIYgod/RSSHub#4330]
### 路由地址
所有，包括文档页面
### 预期是什么？
可以正常访问
### 实际发生了什么？
无法正常访问，浏览器显示“连接被重置”或“找不到IP地址”
### 部署相关信息
无

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/9316590/77607425-3fb5be00-6f55-11ea-85f2-1840f37e9915.png)
ISP：陕西电信，在hosts里写入正确的IP后可以正常访问，目前来看应该仅上了DNS污染，但要小心后续上TLS RST的可能

**Comment by RtYkk** [comment]
rsshub这种情况是被连坐了还是目标就是它？除了些墙外内容的rss，也没啥啊

**Comment by lychichem** [comment]
> rsshub这种情况是被连坐了还是目标就是它？除了些墙外内容的rss，也没啥啊

个人认为不像连坐吧……现在用的ip是cf的不敢随便连坐，而且干扰方式是dns污染，应该就是被盯上了，可能是项目抓了太多国外新闻rss和黄站rss吧

**Comment by zcx1218029121** [comment]
正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受

**Comment by RtYkk** [comment]
> 正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受

[选择"海外"](http://ping.chinaz.com/rsshub.app)
看了看，还有几个没被污染的

**Comment by tgly307** [comment]
> 正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受

目前看起来是 104.26.12.87

**Comment by lychichem** [comment]
> > 正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受
> 
> 
> 
> 目前看起来是 104.26.12.87

尽量别直接贴ip，多贴找ip方法，不然多少ip都不够你封的

**Comment by tgly307** [comment]
> > > 正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受
> > 
> > 
> > 目前看起来是 104.26.12.87
> 
> 尽量别直接贴ip，多贴找ip方法，不然多少ip都不够你封的

每次rsshub重新部署都会换IP，确实贴IP用处不大。
不过找IP方法不是一抓一大把……找ping工具的海外结果就好了嘛

**Comment by lychichem** [comment]
> > > > 正确的ip地址是什么来着，我也改一下host。rss一下子不能用非常难受
> 
> > > 
> 
> > > 
> 
> > > 目前看起来是 104.26.12.87
> 
> > 
> 
> > 尽量别直接贴ip，多贴找ip方法，不然多少ip都不够你封的
> 
> 
> 
> 每次rsshub重新部署都会换IP，确实贴IP用处不大。
> 
> 不过找IP方法不是一抓一大把……找ping工具的海外结果就好了嘛

重点是直接贴ip可能被秒封…以前传出过某物盯着几个项目的更新封的，比较不放心

**Comment by mangoscn** [comment]
自建 RSSHub 服务吧，使用了几个月了，挺好的
只是自建服务会碰到被网站拉黑的可能，比如 Matters，我的自建服务就已经无法抓取了，幸好就只被这一个站封了
后来使用演示站订阅的 Matters，可惜现在 https://rsshub.app 在全国貌似都打不开了

**Comment by lychichem** [comment]
> 自建 RSSHub 服务吧，使用了几个月了，挺好的
> 只是自建服务会碰到被网站拉黑的可能，比如 Matters，我的自建服务就已经无法抓取了，幸好就只被这一个站封了
> 后来使用演示站订阅的 Matters，可惜现在 https://rsshub.app 在全国貌似都打不开了

也可以使用一个中间服务商去订阅，比如inoreadr，这个是我认为目前比较好用的，也可以搜索也没墙，就是免费版的网页上广告有点大。feedly倒也可以，就是cdn似乎有干扰导致部分图片无法显示

**Comment by mangoscn** [comment]
> > 自建 RSSHub 服务吧，使用了几个月了，挺好的
> > 只是自建服务会碰到被网站拉黑的可能，比如 Matters，我的自建服务就已经无法抓取了，幸好就只被这一个站封了
> > 后来使用演示站订阅的 Matters，可惜现在 https://rsshub.app 在全国貌似都打不开了
> 
> 也可以使用一个中间服务商去订阅，比如inoreadr，这个是我认为目前比较好用的，也可以搜索也没墙，就是免费版的网页上广告有点大。feedly倒也可以，就是cdn似乎有干扰导致部分图片无法显示

inoreader 之前一直在用，可惜速度实在太慢，浪费太多时间在等待中，所以自建了 feed 服务器，自建的用起来就一个字 爽，现在看 rss 简直就是一种享受~

**Comment by zwb124** [comment]
inoreader也挂了，目前在用newsblur

**Comment by RtYkk** [comment]
> inoreader也挂了，目前在用newsblur

看来就是针对RSS这种东西的。大部分RSS服务在国内估计都💊，RSSHub不是第一个，也不是最后一个。

**Comment by QuantumGhost** [comment]
确实是针对 RSS 的 

https://en.greatfire.org/https/www.feedly.com

https://twitter.com/Inoreader/status/1245659240326238209

**Comment by 10362227** [comment]
看了看，用的是cf ip，cf ip很泛滥，和谐了不少，但绝大多数丢包，勉强可用。可以试试自己找cf ip，修改hosts解决和谐问题
