### ISSUE TITLE
支持Now.sh 一键部署

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#4334]
### 这是一个什么样的功能？
类似 Heroku, now.sh 可以提供一键的 serverless 部署服务，自带cdn和SSL，且支持绑定自有域名，使用限制也比 Heroku 更少。
### 这个功能可以解决什么问题？
增加一种普通用户可以实施的一键自建服务。
### 额外描述
相关文档：
https://zeit.co/docs/v2/build-step
https://zeit.co/docs/v2/git-integrations/zeit-now-for-github
https://zeit.co/docs/v2/more/deploy-button
（目前已知有人在 now.sh 上成功部署了 rsshub. ）

**Comment by HenryTSZ** [comment]
@yefoenix 大佬能告诉在哪里看到的吗

**Comment by yefoenix** [comment]
@HenryTSZ 看到什么？

**Comment by coffiner** [comment]
没必要，其实。直接用git部署一次就行了。一劳永逸！~

**Comment by NeverBehave** [comment]
经过查找，目前发现 https://rsshub.now.sh 是目前正在运行的now实例
找到对应的博客：https://www.yjk.im/posts/rsshub-in-now-sh/

但是，这个博客是在18年写的，now已经弃用其Docker支持

参考：https://github.com/zeit/now/issues/2120

zeit同时也移除对`express`一类应用的支持，即无法按照`lambda`导出目录，或者至少按照目前的应用配置无法使用。会超过免费额度

顺带一提，https://github.com/DIYgod/RSSHub/pull/4324 配置是错误的

**Comment by HenryTSZ** [comment]
> 没必要，其实。直接用git部署一次就行了。一劳永逸！〜

求教如何使用 git 部署

**Comment by coffiner** [comment]
> > 没必要，其实。直接用git部署一次就行了。一劳永逸！〜
> 
> 求教如何使用 git 部署

第一步，下载源码到指定位置，比如bt面板是/www/wwwroot/下：
cd /www/wwwroot （直接复制进去就行，然后回车）。
git clone https://github.com/DIYgod/RSSHub.git（这一步是复制代码到/www/wwwroot/RSSHub）
cd RSSHub（这一步是直接到RSSHub这目录下）。
npm install（这一步比较慢，如果是国内的服建议把源换成淘宝的。）

（这步是国内安装慢可以换成淘宝的npm源
npm install --registry=https://registry.npm.taobao.org
这是用一次淘宝的源，用完会自动恢复到原来的源。比较方便
或者用bt面板上的pm2管理器增加环境变量的全局支持库。
支持库在RSSHub/package.json这个上面。如果出现错误，请在bt面板的pm2管理器上的模块管理加上全局就行了。）国外的服不需要此操作。大概5~20分钟就可以安装完，如果报错，请找到那个模块加上去就行了。

然后运行
pm2 start lib/index.js --name rsshub（这个是运行rsshub，运行后，ip:1200就行了。bt面板打开pm2管理器，然后找到rsshub，找到映射，输入你要反向代理的域名。当然ngnix，apache也可以自行添加反向代理，代理的地址是127.0.0.1:1200。win下比较复杂，自行百度。）

此为安装和部署。

更新部署也是一样
cd /www/wwwroot/rsshub
pm2 stop（关掉nodejs  pm2服务）
git pull（更新代码）
npm install（安装模块，如果模块版本低会提示修复）
pm2 start lib/index.js --name rsshub（运行）
后面的反向代理不需要操作，因为是ngnix或者apache的代理。只需要重启下就行了。


ok，敲几行代码就能安装。为什么觉得非常难呢 ？

**Comment by yefoenix** [comment]
@coffiner 可是您这个跟 now.sh 没啥关系啊……

**Comment by yefoenix** [comment]
Done!

**Comment by god-hu** [comment]
部署不了啊，试了好多次都不行。各种问题。不懂语言的老人家很是痛苦
ERROR: Failed to update repository: Repository size exceeded limit (< 1000 files)

咋办呢。指导指导。难不成还是要整个收费的才行

**Comment by HenryTSZ** [comment]
@god-hu 
1. 
![1](https://user-images.githubusercontent.com/55341525/82623442-c9f76700-9c12-11ea-974e-52b262b1cc78.png)
![2](https://user-images.githubusercontent.com/55341525/82623455-ce238480-9c12-11ea-8184-e7211ab87a58.png)
![3](https://user-images.githubusercontent.com/55341525/82623462-d11e7500-9c12-11ea-897a-44def169649f.png)
![4](https://user-images.githubusercontent.com/55341525/82623469-d4196580-9c12-11ea-8ef2-28ad0791854c.png)
![5](https://user-images.githubusercontent.com/55341525/82623486-d976b000-9c12-11ea-9bd8-f4008787eaf2.png)
![6](https://user-images.githubusercontent.com/55341525/82623494-de3b6400-9c12-11ea-9d00-05d0088f8d01.png)
![7](https://user-images.githubusercontent.com/55341525/82623502-e1ceeb00-9c12-11ea-903a-31bae1cb833a.png)

**Comment by god-hu** [comment]
@HenryTSZ  哦，可以了。难道是不能使用“import a third party project的原因。

十分感谢，工作原因，需要用rss收集素材又不懂技术，都是照着教程弄。

再次感谢！

**Comment by coffiner** [comment]
> 部署不了啊，试了好多次都不行。各种问题。不懂语言的老人家很是痛苦
> ERROR: Failed to update repository: Repository size exceeded limit (< 1000 files)
> 
> 咋办呢。指导指导。难不成还是要整个收费的才行

见我上面的回答

**Comment by HenryTSZ** [comment]
@god-hu 不客气, 这个是我自己摸索出来的方法, 不知道有没有更好的部署方式. 

还是要感谢大神 @NeverBehave 提供的这个功能: [RSSHub Lambdaize 让RSSHub更方便的部署到云函数平台 · Issue #4560 · DIYgod/RSSHub](https://github.com/DIYgod/RSSHub/issues/4560)

**Comment by NeverBehave** [comment]
> @god-hu 不客气, 这个是我自己摸索出来的方法, 不知道有没有更好的部署方式.
> 
> 还是要感谢大神 @NeverBehave 提供的这个功能: [RSSHub Lambdaize 让RSSHub更方便的部署到云函数平台 · Issue #4560 · DIYgod/RSSHub](https://github.com/DIYgod/RSSHub/issues/4560)

@fengkx

**Comment by HenryTSZ** [comment]
竟然 @ 错人了吗? 尴尬

**Comment by HenryTSZ** [comment]
@NeverBehave , @fengkx 大佬, 我想问一下, 我部署到 now 后, 使用 Reeder 本地订阅后, 有的订阅只有 5 篇文章, 比如订阅的掘金前端分类, 每天打开就只有 5 篇文章: https://rsshub.tsz.now.sh/juejin/category/frontend

以前使用官方订阅源有很多文章的呀, 是需要配置什么吗

**Comment by fengkx** [comment]
@HenryTSZ 你都订阅掘金前端了，这段js还是能看懂的吧。
https://www.github.com/DIYgod/RSSHub/tree/master/lib%2Froutes%2Fjuejin%2Fcategory.js

**Comment by HenryTSZ** [comment]
> @HenryTSZ 你都订阅掘金前端了，这段js还是能看懂的吧。
> https://www.github.com/DIYgod/RSSHub/tree/master/lib%2Froutes%2Fjuejin%2Fcategory.js

哦, 原来在这里, 感谢大佬. 我还在外面的配置中找了半天, 以为是全局配置的

**Comment by NeverBehave** [comment]
> @NeverBehave , @fengkx 大佬, 我想问一下, 我部署到 now 后, 使用 Reeder 本地订阅后, 有的订阅只有 5 篇文章, 比如订阅的掘金前端分类, 每天打开就只有 5 篇文章: https://rsshub.tsz.now.sh/juejin/category/frontend
> 
> 以前使用官方订阅源有很多文章的呀, 是需要配置什么吗

可是，阅读器应该是可以处理这个情况的
你也只需要5个不断更新记录就好了

**Comment by HenryTSZ** [comment]
> > @NeverBehave , @fengkx 大佬, 我想问一下, 我部署到 now 后, 使用 Reeder 本地订阅后, 有的订阅只有 5 篇文章, 比如订阅的掘金前端分类, 每天打开就只有 5 篇文章: https://rsshub.tsz.now.sh/juejin/category/frontend
> > 以前使用官方订阅源有很多文章的呀, 是需要配置什么吗
> 
> 可是，阅读器应该是可以处理这个情况的
> 你也只需要5个不断更新记录就好了

不知道啊, 现在打开就只有当天的, 无法获取以前的. 我现在把刷新设置成每小时试试, 以前是手动刷新
