### ISSUE TITLE
能不能拜托大佬们做一个国家四六级考试通知的RSS呀，真的很实用！

### ISSUE THREAD

**Issue by NBholmes** [DIYgod/RSSHub#4335]
### 网站地址
http://cet.neea.edu.cn/html1/category/16093/1124-1.htm
### 网站描述
国家四六级考试安排通知
### 需要生成什么内容？
就只需要提供这个页面的通知信息就好啦

**Comment by yefoenix** [comment]
neea.edu.cn 网站还包括了[更多类型的考试信息](http://www.neea.edu.cn/html1/folder/16103/1271-1.htm)，页面结构一致，似乎可以做成通用路由，不独 CET.

**Comment by NBholmes** [comment]
那就更好了呀，我自己做不来只能拜托大佬们了，这个我相信应该需要参加国家考试的人都需要吧，是非常非常实用的！

发自我的iPhone
