### ISSUE TITLE
Bilibili关注视频动态停止工作

### ISSUE THREAD

**Issue by AgFlore** [DIYgod/RSSHub#4336]
### 路由地址
`/bilibili/followings/video/:uid`
### 预期是什么？
返回我关注的视频动态
### 实际发生了什么？
自3月18日晚起停止工作。重换了新Cookie后没有用，刚才去PWD上拉取最新版本的repo试跑也不工作。
`TypeError: Cannot read property 'map' of undefined
    at module.exports (/app/lib/routes/bilibili/followings_video.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

### 部署相关信息
（我就填pwd的版本了）
| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Alpine Linux v3.10  |
| Node version       | 这是啥() |
| if Docker, version | 19.03.4 |

### 额外信息（日志、报错等）
报错信息：
`TypeError: Cannot read property 'map' of undefined
    at module.exports (/app/lib/routes/bilibili/followings_video.js:27:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`
配置文件里我填的COOKIE大约如下：
`BILIBILI_COOKIE_nnnnnnn: '{"_uuid":"xxx", ..... ,"stardustvideo":"-1"}'`

**Comment by AgFlore** [comment]
@AgFlore 是我提的（）难道是我Cookie的抓取姿势不对吗

**Comment by YanWQ-monad** [comment]
填 `key1=value1; key2=value2; ...` 格式的 cookie

**Comment by AgFlore** [comment]
> 填 `key1=value1; key2=value2; ...` 格式的 cookie

啊你说得对！立马就解决了
感谢

**Comment by brandon0824** [comment]
@AgFlore 你好 我也遇到了一样的问题还是没搞定 请问cookie应该怎么写才算正确 我的环境变量是
BILIBILI_COOKIE_nnnnnnnn: key1=value1; key2=value2; ...; key_n=value_n;
应该怎么改
