### ISSUE TITLE
求大佬整个e绅士的订阅

### ISSUE THREAD

**Issue by 2ciyv** [DIYgod/RSSHub#4344]
### 网站地址
https://exhentai.org/
### 网站描述
不健全漫画的大图书馆
### 需要生成什么内容？
希望能够订阅tag特别是作者tag，eh虽然自带订阅功能但是有100个订阅上限

**Comment by ctaaronsan** [comment]
e站的feed内容已经包含tag信息了，用阅读器的filter筛选一下不就行了吗

**Comment by LALALA099** [comment]
> e站的feed内容已经包含tag信息了，用阅读器的filter筛选一下不就行了吗

我是小白，用的是feedly，请问具体该怎么做呢？
