### ISSUE TITLE
RSSHub不支持Win10应用商店的Nextgen Reader（一款RSS阅读器）吗？

### ISSUE THREAD

**Issue by dukinyu** [DIYgod/RSSHub#435]
Nextgen Reader是Win10应用商店的一款RSS阅读器（可在应用商店搜索），发现RSSHub生成的RSS地址，在Nextgen Reader里无法添加。是不支持这款阅读器吗？

**Comment by HenryQW** [comment]
https://github.com/DIYgod/RSSHub/tree/master/docs#%E8%BE%93%E5%87%BA%E6%A0%BC%E5%BC%8F

> RSSHub 同时支持 RSS 2.0、Atom 和 JSON Feed 输出格式，在路由末尾添加 .rss .atom 或 .json 即可请求对应输出格式，缺省为 RSS 2.0

**Comment by dukinyu** [comment]
我添加了微博关键词“魅族”的RSS地址，但这款阅读器显示没有源，其他阅读器正常。是这个阅读器的bug吗？

https://rsshub.app/weibo/keyword/%E9%AD%85%E6%97%8F

这里不知道怎么上传图片，我把截图发到微博相册了。

地址：http://wx1.sinaimg.cn/mw690/620a8fdbly1fu2jg0zc96j21070q4jue.jpg

**Comment by HenryQW** [comment]
试试 https://rsshub.app/weibo/keyword/%E9%AD%85%E6%97%8F.atom
或者我看它是基于 feedly，去 feedly 添加试试看。
