### ISSUE TITLE
pixiv not login

### ISSUE THREAD

**Issue by ctaaronsan** [DIYgod/RSSHub#4356]
### 路由地址
/pixiv/user/illustfollows

### 预期是什么？
正常抓取rss

### 实际发生了什么？
提示 pixiv not login

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    Debian           |
| Node version       |               |
| if Docker, version |    19.03.8           |

**Comment by hoilc** [comment]
自建需要配置账号密码

https://docs.rsshub.app/install/#bu-fen-rss-mo-kuai-pei-zhi

**Comment by ctaaronsan** [comment]
解决了，`PIXIV_USERNAME`要填邮箱，用用户名反而不行
