### ISSUE TITLE
在测试中加入W3C Feed Validation Test

### ISSUE THREAD

**Issue by kastnerorz** [DIYgod/RSSHub#4373]
### 这是一个什么样的功能？

在测试中加入[W3C Feed Validation Test](https://validator.w3.org/feed/)

### 这个功能可以解决什么问题？

IFTTT 的 RSS 解析比较严格，现有的一些 RSS（例如bilibili） 无法解析导致 Trigger Failed

**Comment by DIYgod** [comment]
测试没法覆盖所有路由，具体是哪个不能通过 Test？

**Comment by kastnerorz** [comment]
@DIYgod 比如这个http://rsshub.app/bilibili/user/video/7552204/disableEmbed
<img width="996" alt="Screen Shot 2020-04-14 at 9 53 20 PM" src="https://user-images.githubusercontent.com/26199342/79232637-5e470f00-7e9a-11ea-84bb-ba2c0d5b1f68.png">

**Comment by DIYgod** [comment]
这个字段在阅读器使用并没有问题，这里没法改成 email，也不想去除它，所以这个问题这边无能为力
