### ISSUE TITLE
sis001 RSS请求

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#4377]
### 网站地址
https://www.sis001.com

### 网站描述
文字 `类t66y/20`
### 需要生成什么内容？
https://www.sis001.com/forum/index.php?gid=398

https://www.sis001.com/forum/index.php?gid=303

### 额外描述
👽

**Comment by reov** [comment]
还需要生成
http://sis001.com/forum/forum-322-1.html
http://sis001.com/forum/forum-383-1.html
