### ISSUE TITLE
rsshub.app不用vpn就不能获取内容

### ISSUE THREAD

**Issue by god-hu** [DIYgod/RSSHub#4380]
### 路由地址
https://rsshub.app 
### 预期是什么？
获取内容
### 实际发生了什么？
不用vpn无法获取内容。使用vpn正常
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
是被墙了吗？

**Comment by QuantumGhost** [comment]
https://en.greatfire.org/search/all/rsshub

被墙了

**Comment by wft44maqb** [comment]
https://rsshub.netlify.app/

![image](https://user-images.githubusercontent.com/86122516/148042210-53b41122-60cf-4122-a40f-965810637f34.png)
