### ISSUE TITLE
用有线网或者wifi都打不开。。用流量能打开

### ISSUE THREAD

**Issue by zhrq95** [DIYgod/RSSHub#4386]
比如：https://rsshub.app/36kr/newsflashes
用有线网或者wifi都打不开。。用流量可以打开
笔记本连手机热点能打开

**Comment by MysteryMulberry** [comment]
被墙了。。。

**Comment by yefoenix** [comment]
Duplicate of #4380

**Comment by wft44maqb** [comment]
https://rsshub.netlify.app/

![image](https://user-images.githubusercontent.com/86122516/148042210-53b41122-60cf-4122-a40f-965810637f34.png)
