### ISSUE TITLE
https://docs.rsshub.app 无法访问了

### ISSUE THREAD

**Issue by yunlong0928** [DIYgod/RSSHub#4388]
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by tgly307** [comment]
官方demo应该是被墙了，RSSHub及文档建议自建或者挂代理

**Comment by MysteryMulberry** [comment]
> 
> 
> 官方demo应该是被墙了，RSSHub及文档建议自建或者挂代理

可对于多数普通人来说，自建实在太难为他们了，更没有精力去研究自建。要知道，绝多数人连看代码的能力都没有。
rss在国内又要凉啊。。。

**Comment by jeasonlau** [comment]
@MysteryMulberry 害，谁不想让用户用得简单方便呢？但是墙这种不可抗因素，咱再咋不愿意也无能为力啊  🤣

**Comment by yunlong0928** [comment]
我搭了梯子也访问不了哎

**Comment by deepwormm** [comment]
rsshub上也没啥反动信息，为啥这也不让用了呢

**Comment by yefoenix** [comment]
Duplicate of #4380

**Comment by fanhexin** [comment]
我日常用的feedly也被墙了，最近瞄准了各种rss服务。

**Comment by xingye168** [comment]
跟墙没关系吧，有梯子能正常访问谷歌油管和推特，照样进不了

**Comment by xiaorong61** [comment]
> 我日常用的feedly也被墙了，最近瞄准了各种rss服务。

以防万一，我已经用 emacs 看 rss 了。。。

**Comment by wft44maqb** [comment]
https://rsshub.netlify.app/

![image](https://user-images.githubusercontent.com/86122516/148042210-53b41122-60cf-4122-a40f-965810637f34.png)
