### ISSUE TITLE
Github提供了官方的rss订阅地址了

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#4396]
GitHub provides several timeline resources in Atom format. That’s how I get latest info about projects that I follow and their fixed bugs and new features. Some of official RSS feeds are:

/* Repo releases */

https://github.com/:owner/:repo/releases.atom

/* Repo commits */

https://github.com/:owner/:repo/commits.atom

/* Private feed (You can find Subscribe to your news feed in dashboard page after login) */

https://github.com/:user.private.atom?token=:secret

/* Repo tags */

https://github.com/:user/:repo/tags.atom

/* User activity */

https://github.com/:user.atom

**Comment by Konano** [comment]
这不是早就写在文档里了么……

**Comment by pcwuyu** [comment]
噗。。不好意思没注意到
