### ISSUE TITLE
instagram rss wanted

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#44]
features:
- [ ] instagram image post ( support more than two images)
- [ ] instagram video post

e.g. /instagram/user/:username

not sure why instagram rss not issued as **"RSS Wanted"** yet, when twitter rss and youtube rss did already.

commercial issue related?

**Comment by DIYgod** [comment]
标签是由我手动加上去的，已加

**Comment by DIYgod** [comment]
Done. b1f73772517d275022355e7f9ade98cb5c3072b5

**Comment by DerekTso** [comment]
thanks for this feature.

one suggestion:
could we make a tag or sth like that in the rss item **title**, to make it easier to recognize this's a video post or this's a "multiple-images" post ?

maybe sth like this: 

[多图] original title
[视频] original title

or 

[M] original title
[V] original title

M for multiple images post
V for video post

**Comment by DIYgod** [comment]
@DerekTso Done. 1cc0a6f4ca968cb4ff5da666ae31b03e44c04e6e
