### ISSUE TITLE
希望能够提供掘金一周/本月/历史热门的rss

### ISSUE THREAD

**Issue by sharkrice** [DIYgod/RSSHub#440]
- 一周最热
https://timeline-merger-ms.juejin.im/v1/get_entry_by_period?period=week&src=web&limit=20&category=all
- 本月最热
https://timeline-merger-ms.juejin.im/v1/get_entry_by_period?period=month&src=web&limit=20&category=all
- 历史最热
https://timeline-merger-ms.juejin.im/v1/get_entry_by_hot?src=web&limit=20&category=all

**Comment by DIYgod** [comment]
Done. bd7d3396bd2338b5d3376f4129d811235ae3f80a
