### ISSUE TITLE
希望能获得推文中链接的真实地址

### ISSUE THREAD

**Issue by ypocc** [DIYgod/RSSHub#441]
很高兴 RSSHub 支持了推特，我尝试从 TwitRSS.me 切换。

我遇到了一些问题
- 正文链接没有 `<a>` 标签，访问不太方便
- 链接地址不是真实地址

举个例子：

这是 [RSSHub](https://rsshub.app/twitter/user/medscape) 的输出

    Medical groups applaud CMS for easing the administrative burden through a new rule on hospital payments. https://t.co/wzHvpG2tNm

可以看到链接没有 `<a>` 标签，链接地址是 推特的短链接地址。

这是 [TwitRSS.me](https://twitrss.me/twitter_user_to_rss/?user=medscape) 的输出

    Medical groups applaud CMS for easing the administrative burden through a new rule on hospital payments. [http://ms.spr.ly/6012rfVdm](http://ms.spr.ly/6012rfVdm)

- 上面 `[foo](bar)` 意味着这里是链接，实际上应该是 HTML 形式的。
- TwitRSS.me 偶尔会有 5XX 或 XML 无效 之类的问题。如果遇上了，等一会 或 从浏览器访问试试。

---------------------------------------------------

还有个需求不知是不是合适

希望给个选项，允许将推特链接从 [twitter.com](https://twitter.com/medscape/status/1027348147041959936) 改成 [mobile.twitter.com](https://mobile.twitter.com/medscape/status/1027348147041959936)。它相对干净，坏处是有些网络会遇到推文加载不出来的问题。

**Comment by DIYgod** [comment]
Done. 144296f1f46cc390fc90be181d12e3d74315dca3

**Comment by DIYgod** [comment]
@ypocc 简介里有链接是正常的，推主简介里本来就有链接
回复的这条 tweet 已经找不到了，暂时没有发现其他有出现这种情况

**Comment by ypocc** [comment]
@DIYgod 抱歉，推特的内容我订阅得少。这种情况很稀有，一时间没有找到。不过捕捉到了新的情况。

链接：

```
https://rsshub.app/twitter/user/chenshaoju
```

内容：

```
“山竹”台风来临，惠州市博罗中学强制学生留校https://t.co/GeaIjvK9rk<a href="https://zhuanlan.zhihu.com/p/44669715" target="_blank"></a><a href="https://weibo.com/2608775311/GzEIfzf0e" target="_blank"></a>
```

备份：

传了个文件上来，后缀名需要改为`xml`。

[chenshaoju.log](https://github.com/DIYgod/RSSHub/files/2387083/chenshaoju.log)

**Comment by DIYgod** [comment]
尝试修了一下，应该是可以了 dcea9e29fac397cbd1d5ec9507e807f6db2be149

**Comment by ypocc** [comment]
@DIYgod  https://github.com/DIYgod/RSSHub/issues/441#issuecomment-421846146 提到了两个问题，我应该描述一下的。

---

描述：

``` HTML
<a href="foobar">不知道这里叫什么，所以上次没有描述。现况是内容缺失，请下载备份文件搜索「</a>」。</a>
```

补充：
- [bd210c9](https://github.com/DIYgod/RSSHub/commit/bd210c9788c7344394b44216fd8a6bcff619b4aa "在评论时是最新版")
- [链接](https://rsshub.app/twitter/user/firefox "Firefox 的 Twitter")
- [备份](https://github.com/DIYgod/RSSHub/files/2390503/firefox.log "备份有点麻烦耶，如果 archive 能存就好了")
