### ISSUE TITLE
gdut/news路由失效

### ISSUE THREAD

**Issue by RezaFeng** [DIYgod/RSSHub#4422]
### 路由地址
https://rsshub.app/gdut/news
### 预期是什么？
能返回xml信息
### 实际发生了什么？
提示route empty

**Comment by hoilc** [comment]
确认路由正常，应该是触发反爬，建议自建实例使用

![image](https://user-images.githubusercontent.com/9067094/79043600-aebc3380-7c32-11ea-884b-49f80c973ea9.png)
