### ISSUE TITLE
求大神加个网易lofter的RSS模块

### ISSUE THREAD

**Issue by coldseleno** [DIYgod/RSSHub#4423]
### 网站地址
https://lofter.com

### 网站描述
网易博客

### 需要生成什么内容？
生成包含：文字、图片、链接、外链视频等内容

### 额外描述
之前网站是自带rss功能的，但三月时这个功能就被关闭了，阅读起来超不方便，求大神能够添加进来
(原网站自带的RSS链接为：https://ID.lofter.com/rss，目前已无法工作。

**Comment by hoilc** [comment]
https://bianhuakai55304.lofter.com/

https://qiangtoucaoyijingsanbaizhanggaole.lofter.com/

看了下貌似没有统一模板
