### ISSUE TITLE
知乎日报路由失效

### ISSUE THREAD

**Issue by StrollStars** [DIYgod/RSSHub#4426]
### 路由地址
https://rsshub.app/zhihu/daily
https://rsshub.app/zhihu/daily/section/2

### 预期是什么？
能打开知乎日报和知乎日报瞎扯的网页

### 实际发生了什么？
404: Not Found

### 部署相关信息

**Comment by xizeyoupan** [comment]
自建测试可用

**Comment by hoilc** [comment]
确认自建可用，demo实例返回为403，而非404，建议关闭issue

![image](https://user-images.githubusercontent.com/9067094/79043518-3e151700-7c32-11ea-9924-78b593b34645.png)

**Comment by StrollStars** [comment]
似乎是我这边的问题，问题关闭。
