### ISSUE TITLE
豆瓣图片不显示的问题

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#4427]
### 路由地址
路由: douban/people/:userid/status
### 预期是什么？
inoreader里面显示图片
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/44609485/79032896-81dd3180-7bdc-11ea-9375-86d129a8c11a.png)
只有我有这个问题嘛？豆瓣广播的图片老是不显示，好早就有这个问题了
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by Olivercoco** [comment]
![image](https://user-images.githubusercontent.com/39828052/79039476-12833400-7c14-11ea-8066-cc6872bccd92.png)
