### ISSUE TITLE
Mastodon, individual users

### ISSUE THREAD

**Issue by catatonik** [DIYgod/RSSHub#4430]
### What feature is it?
Mastodon per-user RSS feeds

### What problem does this feature solve?
Allows you to follow individual users instead of an entire instance timeline

### Additional description
The example becomes:
https://rsshub.app/mastodon/timeline/pawoo.net/@pawoo_support/true
(shows pawoo.net/@pawoo_support timeline only)
from:
https://rsshub.app/mastodon/timeline/pawoo.net/true
(shows pawoo.net timeline)

This would be an expansion of https://github.com/DIYgod/RSSHub/pull/3537

**Comment by hoilc** [comment]
Mastodon provides the official support for per-user RSS feeds, e.g.,

https://pawoo.net/users/pawoo_support.atom or https://pawoo.net/users/pawoo_support.rss

I will update the RSSHub documentation to mention it later.

**Comment by catatonik** [comment]
> 
> Mastodon provides the official support for per-user RSS feeds, e.g.,
> 

It doesn't support :only_media? which is why i asked :)
