### ISSUE TITLE
请求ja.hentai-cosplay.com的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#4439]
### 网站地址
最新内容：
https://ja.porn-image-xxx.com/search/
https://ja.hentai-cosplay.com/search/
搜索标签：
https://ja.hentai-cosplay.com/search/tag/swimsuit/
https://ja.porn-image-xxx.com/search/tag/gravure/
### 网站描述
看妹子
### 需要生成什么内容？
标题，封面，内容（图）
### 额外描述
其实在feed43用了好几个月了，但最近突然回复 Tried to load source page, but remote server reported "403 Forbidden", 无奈了跑来求助大佬

**Comment by tomatomash** [comment]
感谢大佬们，不过还是403了
https://rsshub.app/hentai-cosplays/tag/swimsuit
https://rsshub.app/porn-images-xxx/tag/jk
Response code 403 (Forbidden)

**Comment by prnake** [comment]
需要自建
