### ISSUE TITLE
Amazon Kindle Firmware update reminder

### ISSUE THREAD

**Issue by Novite5** [DIYgod/RSSHub#4443]
### 网站地址
https://www.amazon.cn/gp/help/customer/display.html?nodeId=GKMQC26VQQMM8XSW

### 网站描述
Kindle 固件下載頁面
### 需要生成什么内容？
Kindle 固件有更新。

**Comment by HenryQW** [comment]
压泡面不需要最新固件，不用来压泡面应该会自动更新。
