### ISSUE TITLE
自建一段时间后Error: this route is empty, please check the original site 

### ISSUE THREAD

**Issue by EvenCu** [DIYgod/RSSHub#4462]
### 路由地址
FB粉专
### 预期是什么？
正常抓取
### 实际发生了什么？
使用一段时间后Error: this route is empty, please check the original site 
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     debian10          |
| Node version       |      v10.19.0         |
| if Docker, version |        -       |

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/home/RSSHub/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by DIYgod** [comment]
反爬
