### ISSUE TITLE
使用代理时报错：RequestError: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by wyzane** [DIYgod/RSSHub#4471]
### 预期是什么？
在centos上，自己搭建的RSSHub服务，按照说明文档，已配置了代理的环境变量PROXY_PROTOCOL，PROXY_HOST，PROXY_PORT；请求url时未能正确发送请求

### 实际发生了什么？
主要报错信息为：RequestError: tunneling socket could not be established, cause=read ECONNRESET

具体错误信息如下：
[wangzan@mesport-app-001 RSSHub]$ npm start

> rsshub@0.1.1 start /home/wangzan/projects/rsshub/RSSHub
> node lib/index.js

info: Listening Port 1200
info:  RSSHub start! Cheers!
(node:16433) ExperimentalWarning: The fs.promises API is experimental
info: /weibo/user/2803301701, user IP: ::ffff:10.10.10.12
info: Proxy for https://m.weibo.cn/api/container/getIndex?type=uid&value=2803301701
error: Request undefined fail, retry attempt #1: RequestError: tunneling socket could not be established, cause=read ECONNRESET
info: Proxy for https://m.weibo.cn/api/container/getIndex?type=uid&value=2803301701
error: Request undefined fail, retry attempt #2: RequestError: tunneling socket could not be established, cause=read ECONNRESET
info: Proxy for https://m.weibo.cn/api/container/getIndex?type=uid&value=2803301701
error: Error in /weibo/user/2803301701: tunneling socket could not be established, cause=read ECONNRESET: target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    CentOS 6.9           |
| Node version       |      v10.9.0         |
| if Docker, version |               |

**Comment by junfengP** [comment]
应该是你代理配置的不正确，贴出具体内容，外网IP请打码。

**Comment by wyzane** [comment]
环境变量配置如下：
export PROXY_PROTOCOL=http
export PROXY_HOST=*******
export PROXY_PORT=*******

请帮忙看一下，感谢！

**Comment by junfengP** [comment]
我本地测试了一下http代理，是正常可用的。

你再检查一下HTTP代理是否可以正常使用。

**Comment by wyzane** [comment]
我试了还是不行？是跟我这边的node版本，或者使用的代理ip有关系吗？我这边使用的代理ip是在网上随便找的

**Comment by junfengP** [comment]
@wyzane 你确定这个代理能正常使用？

**Comment by wyzane** [comment]
58.218.92.87:18351
58.218.92.168:12491
58.218.214.144:16162
58.218.92.170:15186
58.218.214.134:17067
58.218.214.143:17622
58.218.92.81:12890
58.218.214.145:18295
58.218.214.154:12462
58.218.214.139:14737

上面是我在网上找的一些代理ip，麻烦你试一下能不能使用，感谢！

**Comment by junfengP** [comment]
@wyzane 你可以百度一下，浏览器代理设置，然后自行使用浏览器测试这些代理可用性。 网上找的一般都不稳定或者失效了

**Comment by wyzane** [comment]
好的，应该是我这边代理ip的问题，谢谢！
