### ISSUE TITLE
希望gdut news可以添加公告公示栏

### ISSUE THREAD

**Issue by RezaFeng** [DIYgod/RSSHub#4477]
### Website URL
http://news.gdut.edu.cn/ArticleList.aspx?category=5
### Website description
广东工业大学新闻通知公告公示
### Additional description
与原本的/gdut/news没什么区别，只是category=5

**Comment by Palucho99** [comment]
Megustaria saber más

**Comment by TonyRL** [comment]
Looks like news.gdut.edu.cn no longer works
