### ISSUE TITLE
BOF 的路由失效

### ISSUE THREAD

**Issue by MrLIUXY** [DIYgod/RSSHub#4489]
### 路由地址
/bof/home

### 预期是什么？
正常更新

### 实际发生了什么？
不再更新
*原文链接应指向中文网cn.businessoffashion.com，非国际版www.businessoffashion.com

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by coffiner** [comment]
没问题呢~！我的正常
