### ISSUE TITLE
Github Topics

### ISSUE THREAD

**Issue by askDing** [DIYgod/RSSHub#4496]
### 在rsshub.com添加一个类似trending的Rss
 举例: https://rsshub.app/github/topics/awosome

路由: /github/topics/:awosome

参数:

    awosome, 必选 -为topics

### 额外描述
https://rsshub.app/github/topics/security

**Comment by hoilc** [comment]
Refer to https://docs.rsshub.app/programming.html#sou-suo-jie-guo

https://rsshub.app/github/search/topic:security/bestmatch/desc
