### ISSUE TITLE
私有部署的服务在feedly上订阅不了

### ISSUE THREAD

**Issue by Dec-F** [DIYgod/RSSHub#4504]
### 预期是什么？
feedly可以正常订阅
### 实际发生了什么？
正常外网访问。

不能正常订阅
![image](https://user-images.githubusercontent.com/20250430/79740584-828b6b80-8332-11ea-8eda-b59b8f94ffa6.png)

但是直接打开是可以的
![image](https://user-images.githubusercontent.com/20250430/79740600-8ae3a680-8332-11ea-9513-ae92d11c0c00.png)

### 部署相关信息
docker部署最新版的，浏览器可以正常打开，但是feedly报错

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       群晖类Linux        |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
由于是家用NAS，地址打码了，需要更多信息，我发邮件补充

**Comment by Dec-F** [comment]
我在Rss Reader上试了一下，发现是可以的。有人遇到feedly这种问题吗？

**Comment by yefoenix** [comment]
feedly 只能接受 80/443 接口的 feed，加个反代吧

**Comment by Echardwang** [comment]
> 我在Rss Reader上试了一下，发现是可以的。有人遇到feedly这种问题吗？

我的也是 Feedly用不了 其他可以 有没有解决办法？
