### ISSUE TITLE
Instagram偶尔出现Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by RezaFeng** [DIYgod/RSSHub#4506]
### 路由地址
/instagram/user/:id
### 预期是什么？
能够成功刷新到xml页面
### 实际发生了什么？
偶尔能刷新出，有时候网页报错，提示Hostname/IP does not match certificate's altnames
### 部署相关信息
阿里云香港服务器docker方式部署。
使用caddy进行代理，caddy的配置如下

http://www.xxxxx.top {
  redir https://www.xxxxx.top{url}
}

www.xxxxx.top:1201 {
  tls xxxxx@gmail.com
  log /root/caddy/rsshub.log
  proxy /  127.0.0.1:1200 {
	websocket
	header_upstream -Origin
  }
  header / Strict-Transport-Security "max-age=31536000;"
  gzip
}

### 额外信息（日志、报错等）
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- error: Error in /instagram/user/aragakiyui_fanspage: Hostname/IP does not match certificate's altnames: Host: www.instagram.com. is not in the cert's altnames: DNS:*.facebook.com, DNS:*.facebook.net, DNS:*.fb.com, DNS:*.fbcdn.net, DNS:*.fbsbx.com, DNS:*.messenger.com, DNS:facebook.com, DNS:fb.com, DNS:messenger.com, DNS:*.m.facebook.com, DNS:*.xx.fbcdn.net, DNS:*.xy.fbcdn.net, DNS:*.xz.fbcdn.net: target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.
- info: /instagram/user/tarankaaa, user IP: xx.xx.xx.xx
- info: /instagram/user/kasumi_arimura.official, user IP: xx.xx.xx.xx
- info: /instagram/user/fishleong616, user IP: xx.xx.xx.xx
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- error: Request undefined fail, retry attempt #1: RequestError: connect ETIMEDOUT 69.171.232.21:443
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx
- info: /instagram/user/aragakiyui_fanspage, user IP: xx.xx.xx.xx

**Comment by hoilc** [comment]
与caddy无关，建议给RSSHub添加环境变量`NODE_TLS_REJECT_UNAUTHORIZED = 0`，保持观察

**Comment by RezaFeng** [comment]
> 与caddy无关，建议给RSSHub添加环境变量`NODE_TLS_REJECT_UNAUTHORIZED = 0`，保持观察

设置之后直接提示400了

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-645761284
