### ISSUE TITLE
安装扩展后，规则更新失败

### ISSUE THREAD

**Issue by xuejianxianzun** [DIYgod/RSSHub#4508]
### 路由地址
无

### 预期是什么？
安装后没有规则，显示 `440953小时46分钟前更新，-440949小时13分钟后自动更新`。手动点击更新，更新失败

### 实际发生了什么？

```
options.js:1 
GET https://raw.githubusercontent.com/DIYgod/RSSHub/master/assets/radar-rules.js
net::ERR_EMPTY_RESPONSE
```
| Env                | Value         |
| ------------------ | ------------- |
| OS                 | win10              |

chrome 80

已经科学上网，可以正常访问 github

### 额外信息（日志、报错等）
更新失败截图：

![更新失败](https://s1.ax1x.com/2020/04/21/J3rfqe.png)

**Comment by junfengP** [comment]
@xuejianxianzun 就是翻墙不彻底导致的，浏览器访问那个网址，复制里面代码到规则列表

**Comment by xuejianxianzun** [comment]
> @xuejianxianzun 就是翻墙不彻底导致的，浏览器访问那个网址，复制里面代码到规则列表

我可以打开这个规则文件 `https://github.com/DIYgod/RSSHub/blob/master/assets/radar-rules.js`，但是点 `raw` （也就是更新规则请求的网址）打不开。
现在我下载了这个文件，到那时规则列表里没有输入规则的地方，不知道怎么办，如图：
![](https://s1.ax1x.com/2020/04/21/J3cLfs.png)

**Comment by junfengP** [comment]
> > @xuejianxianzun 就是翻墙不彻底导致的，浏览器访问那个网址，复制里面代码到规则列表
> 
> 我可以打开这个规则文件 `https://github.com/DIYgod/RSSHub/blob/master/assets/radar-rules.js`，但是点 `raw` （也就是更新规则请求的网址）打不开。
> 现在我下载了这个文件，但是规则列表里没有输入规则的地方，不知道怎么办，如图：
> ![](https://camo.githubusercontent.com/eb3a56e99dc484fbdafa33359dffbb46f17318f7/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f32312f4a33634c66732e706e67)

右边有这么几行字
```
此处用于开发中的规则调试，非战斗人员请迅速撤离

编辑内容随时可能被自动更新的规则覆盖，请保证本地有备份

使用 设置-立即更新 可以立即恢复远程规则
```
下面有填写框。但是你图示这几行字很透明，我估计没有填写框。

你打不开raw，就说明你的翻墙不彻底，开全局翻墙试试。

**Comment by xuejianxianzun** [comment]
> > > @xuejianxianzun 就是翻墙不彻底导致的，浏览器访问那个网址，复制里面代码到规则列表
> > 
> > 
> > 我可以打开这个规则文件 `https://github.com/DIYgod/RSSHub/blob/master/assets/radar-rules.js`，但是点 `raw` （也就是更新规则请求的网址）打不开。
> > 现在我下载了这个文件，但是规则列表里没有输入规则的地方，不知道怎么办，如图：
> > ![](https://camo.githubusercontent.com/eb3a56e99dc484fbdafa33359dffbb46f17318f7/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f32312f4a33634c66732e706e67)
> 
> 右边有这么几行字
> 
> ```
> 此处用于开发中的规则调试，非战斗人员请迅速撤离
> 
> 编辑内容随时可能被自动更新的规则覆盖，请保证本地有备份
> 
> 使用 设置-立即更新 可以立即恢复远程规则
> ```
> 
> 下面有填写框。但是你图示这几行字很透明，我估计没有填写框。
> 
> 你打不开raw，就说明你的翻墙不彻底，开全局翻墙试试。

页面上有这些小字，但是小字下方是一个转圈的loading图，没有输入框。

梯子是全局代理，换了几个节点都一样，看来现在没法用了。谢谢你的帮助。
