### ISSUE TITLE
希望增加MoeTV

### ISSUE THREAD

**Issue by haig233** [DIYgod/RSSHub#4509]
### 网站地址
https://moetv.live/
### 网站描述
MoeTV
### 需要生成什么内容？
每天影视更新以及播放地址

**Comment by SettingDust** [comment]
所谓 `每天影视更新` 在哪里？需求请描述清楚

**Comment by haig233** [comment]
> 所谓 `每天影视更新` 在哪里？需求请描述清楚

https://moetv.live/list/?1.html
https://moetv.live/list/?2.html
https://moetv.live/list/?3.html
https://moetv.live/list/?4.html
有影片更新，内容会新增
