### ISSUE TITLE
有没有可能添加一个订阅列表的推荐功能，按官方demo的路由访问量做排名 或 手动添加推荐

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#4522]
### 这是一个什么样的功能？

- 一个订阅列表的推荐功能，按官方demo的路由访问量做排名 或 手动添加推荐（或像Hacker News一样投票）。

### 这个功能可以解决什么问题？

- 可以让大家发现更多更好的订阅源
- 推荐自己喜欢的订阅源可以让推荐者和源作者更开心

### 额外描述

无

**Comment by yefoenix** [comment]
@pcwuyu Demo首页就有路由排名啊

**Comment by pcwuyu** [comment]
> @pcwuyu Demo首页就有路由排名啊

左侧只有列表啊

**Comment by junfengP** [comment]
![image](https://user-images.githubusercontent.com/15406392/79994016-033f9880-84e8-11ea-8d24-ad9de0ab7705.png)

**Comment by Origami404** [comment]
我认为其实没啥参考价值... 大部分人都是自建, 并且有些带参数的路由一订阅就是一串, 比如榜首的twitter, 不可能只关注一个人的推吧...
