### ISSUE TITLE
南京市人民政府 失效

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#4524]
### 路由地址
https://rsshub.app/gov/city/nanjing/department
https://rsshub.app/gov/city/nanjing/news

### 实际发生了什么？
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports 
```

### 额外信息（日志、报错等）
![department](https://user-images.githubusercontent.com/6291329/79975768-15144200-84ce-11ea-8968-40cf67b86ff5.png)

![news](https://user-images.githubusercontent.com/6291329/79975797-1d6c7d00-84ce-11ea-9b19-abb7c8f23406.png)

**Comment by black-desk** [comment]
南京政府的网站我都打不开 [链接](http://www.nanjing.gov.cn/)

**Comment by hoilc** [comment]
確認自建正常，考慮網絡問題，建議關閉issue

![image](https://user-images.githubusercontent.com/9067094/80311739-fbe3fc00-8813-11ea-90c0-7775fdae8bf5.png)

![image](https://user-images.githubusercontent.com/9067094/80311742-00a8b000-8814-11ea-8ffa-169b2ef91807.png)
