### ISSUE TITLE
江苏省人民政府 省政府及办公厅文件 打开网址错误

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#4529]
### 路由地址
`/gov/province/jiangsu/documentation`

### 预期是什么？
举例：
- 预期：http://www.jiangsu.gov.cn/art/2020/4/20/art_46143_9050188.html

### 实际发生了什么？
举例：
- 实际：http://www.jiangsu.gov.cnhttp//www.jiangsu.gov.cn/art/2020/4/20/art_46143_9050188.html

### 额外信息（日志、报错等）

- 网址前面多了`http://www.jiangsu.gov.cn`
- http//www.jiangsu.gov.cn中http后面没有冒号

**Comment by black-desk** [comment]
http://www.jiangsu.gov.cn/art/2020/4/20/art_46143_9050188.html 这个链接我这里打不开 合理怀疑是政府的服务器的问题

**Comment by pcwuyu** [comment]
![image](https://user-images.githubusercontent.com/6291329/80274307-03b87900-870c-11ea-9c1c-b55d38113240.png)
我这边打开正常，江苏联通宽带和广西联通4G都可以

**Comment by DIYgod** [comment]
现在测试是好的

**Comment by black-desk** [comment]
> 现在测试是好的

是我修的（
