### ISSUE TITLE
[需求] 希望能添加网易LOFTER

### ISSUE THREAD

**Issue by HowardWang-HT** [DIYgod/RSSHub#4547]
### 这是一个什么样的功能？
希望能添加网易LOFTER的路由。虽然RSSRadar显示RSS，但在inoreader中打开订阅源不可用。

### 这个功能可以解决什么问题？、
网易LOFTER的RSSHub路由

### 额外描述
一个case地址：https://subblognteswjqm66.lofter.com/

**Comment by mengx8** [comment]
已经有实现了
https://docs.rsshub.app/social-media.html#lofter
建议先查一下文档

**Comment by HowardWang-HT** [comment]
Hi mengx8,

好的，感谢提醒。之前是在https://docs.rsshub.app直接搜索LOFTER，没有显示。刚刚试了逐字输入是有搜索提示的。
感谢帮助。RSSHub和RSSHub Radar都很棒 😀

希望今后也能编写订阅源，为大家做贡献。
