### ISSUE TITLE
Facebook粉絲專頁的貼文不會自動刷新 需要重啟RSSHUB才會刷新

### ISSUE THREAD

**Issue by SakurajimaMai-1202** [DIYgod/RSSHub#4552]
### 路由地址
/facebook/page/bh3tw
### 预期是什么？
當Facebook粉絲專頁發文會自動抓取RSS源不需手動重開刷新
### 实际发生了什么？
不會自動刷新，需要手動重啟才會刷新最新貼文
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |            |
| Node version       |               |
| if Docker, version |               |

**Comment by nczitzk** [comment]
RSSHub 需要以足够短的时间间隔请求 Facebook 的页面，才能足够及时地收到来自 Facebook 消息推送。供参考，[rsshub.app](https://rsshub.app/) 的缓存时间为20分钟，即每隔20分钟会进行请求更新。如没有完成指定的时间周期，RSSHub 服务并不会从 RSS 源获取数据。根据 RSSHub 不同的 [部署方式](https://docs.rsshub.app/install/)，你可以缩短 RSS 的缓存时间从而相应提升 RSSHub 的更新频率。

值得注意的是，减少 RSSHub 的缓存时间从而追求较及时的数据会一定程度地加重系统的负担。同时，[指南](https://docs.rsshub.app/social-media.html#facebook) 中对于 Facebook 标注了 [反爬严格](https://docs.rsshub.app/faq.html) 的标签。这意味着 Facebook 对于高频率的请求是警惕的，此时 RSSHub 的请求可能无效，这也会导致 RSSHub 服务的不稳定。

因此，RSSHub 无法满足 Facebook 贴文一更新就刷新的需求，但可以通过指定稍短一些的缓存时间以实现较为及时的推送。当然，如果对及时性的要求很高，还是使用 Facebook 提供的服务更佳 😃

**Comment by SakurajimaMai-1202** [comment]
是的 我知道無法及時去做到刷新的需求，我可能表示的不明白，抱歉!
目前的狀況是當粉絲團已經發文過了好幾個小時甚至是一天 ，但RSS都沒更新需要去手動重啟RSShub才會更新。

如圖:崩壞3的粉絲團最新貼文已經是5小時前
![註解 2020-04-24 233341](https://user-images.githubusercontent.com/56517823/80230464-91508600-8684-11ea-9b11-1ac0a06cd85b.png)

如圖:但RSS仍然沒更新
![註解 2020-04-24 233408](https://user-images.githubusercontent.com/56517823/80230627-c78e0580-8684-11ea-912e-f60701d3875e.png)

**Comment by nczitzk** [comment]
原来是这样子 😂 

我观察到第二张图中 lastBuildDate 似乎和你 comment 的时间相近。RSSHub 应该是正常工作的，但出于某些原因从缓存中获取 Facebook 的页面内容，而该页面来自重启后第一次写入的缓存，所以内容保持始终如一，呈现出不会自动刷新的状态。或许检查一下部署时有没有变更 [内容缓存过期时间](https://docs.rsshub.app/install/#pei-zhi) 这一配置项？

我刚才在 [rsshub.app](https://rsshub.app/) 上尝试了该路由。节选结果如下所示，title 和 description 没有被正常获取到，但是获取到了 link。不过这就是另一个问题了 😭
```xml
<item>
    <title>
        <![CDATA[ ]]>
    </title>
    <description>
        <![CDATA[ ]]>
    </description>
    <guid isPermaLink="false">
        https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
    </guid>
    <link>
        https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
    </link>
</item>
```

**Comment by 10362227** [comment]
这种常用的社交网站或简单的网站建议用网上现成的php，搜索就有，不占资源，用rsshub实在浪费。就比如我，也不会用Huginn去搞FB，直接找php代码

**Comment by SakurajimaMai-1202** [comment]
> 原来是这样子 😂
> 
> 我观察到第二张图中 lastBuildDate 似乎和你 comment 的时间相近。RSSHub 应该是正常工作的，但出于某些原因从缓存中获取 Facebook 的页面内容，而该页面来自重启后第一次写入的缓存，所以内容保持始终如一，呈现出不会自动刷新的状态。或许检查一下部署时有没有变更 [内容缓存过期时间](https://docs.rsshub.app/install/#pei-zhi) 这一配置项？
> 
> 我刚才在 [rsshub.app](https://rsshub.app/) 上尝试了该路由。节选结果如下所示，title 和 description 没有被正常获取到，但是获取到了 link。不过这就是另一个问题了 😭
> 
> ```
> <item>
>     <title>
>         <![CDATA[ ]]>
>     </title>
>     <description>
>         <![CDATA[ ]]>
>     </description>
>     <guid isPermaLink="false">
>         https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
>     </guid>
>     <link>
>         https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
>     </link>
> </item>
> ```
真的挺奇怪的，[rsshub.app](url)上是有抓到新的，但是自建的會卡住無法刷新， 内容缓存过期时间這個我倒是都沒動過

**Comment by Rupthya** [comment]
> 这种常用的社交网站或简单的网站建议用网上现成的php，搜索就有，不占资源，用rsshub实在浪费。就比如我，也不会用Huginn去搞FB，直接找php代码

請問有更多指路的資料或字眼供搜索？外星人單憑 PHP 和 RSS 這些字眼搜索不到相關教學或資料；

感謝。

**Comment by 10362227** [comment]
> > 这种常用的社交网站或简单的网站建议用网上现成的php，搜索就有，不占资源，用rsshub实在浪费。就比如我，也不会用Huginn去搞FB，直接找php代码
> 
> 請問有更多指路的資料或字眼供搜索？外星人單憑 PHP 和 RSS 這些字眼搜索不到相關教學或資料；
> 
> 感謝。

如果是通用的，[RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge)、[createfeed](http://createfeed.fivefilters.org/) 和[rssbox](https://github.com/stefansundin/rssbox) 前两个是php写的，自己搭建（第二个付费），免费php服务器实在太多了。谷歌搜索RSS-Bridge运气好可能能直接搜索到别人搭建的，直接用就可以。高级一点的还有和[huginn](https://github.com/huginn/huginn/issues) 要会懂一点点代码，都可以免费使用，huginn和rssbox注册heroku一键安装，

**Comment by aa900031** [comment]
> 原来是这样子 😂
> 
> 我观察到第二张图中 lastBuildDate 似乎和你 comment 的时间相近。RSSHub 应该是正常工作的，但出于某些原因从缓存中获取 Facebook 的页面内容，而该页面来自重启后第一次写入的缓存，所以内容保持始终如一，呈现出不会自动刷新的状态。或许检查一下部署时有没有变更 [内容缓存过期时间](https://docs.rsshub.app/install/#pei-zhi) 这一配置项？
> 
> 我刚才在 [rsshub.app](https://rsshub.app/) 上尝试了该路由。节选结果如下所示，title 和 description 没有被正常获取到，但是获取到了 link。不过这就是另一个问题了 😭
> 
> ```
> <item>
>     <title>
>         <![CDATA[ ]]>
>     </title>
>     <description>
>         <![CDATA[ ]]>
>     </description>
>     <guid isPermaLink="false">
>         https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
>     </guid>
>     <link>
>         https://www.facebook.com/story.php?story_fbid=2589015361313464&id=1863143773900630
>     </link>
> </item>
> ```

看來是沒有正確抓到 titile, desc ，若有人可以修就先修吧
不然我就再找時間修掉
