### ISSUE TITLE
discuz论坛cookie一大串以什么格式添加？

### ISSUE THREAD

**Issue by abisso** [DIYgod/RSSHub#4557]
在RRShub源文件路径vi .env
添加DISCUZ_COOKIE_{01}=chrome浏览器控制台里一大串带分号和等号的cookie值
总是提醒：Error: 缺少对应论坛的cookie.
我是手动部署的

**Comment by junfengP** [comment]
`DISCUZ_COOKIE_01=将chrome内的cookie完整复制进来`

**Comment by abisso** [comment]
成功了，谢谢大佬

**Comment by iSteveyang** [comment]
我是Firefox 打开出来一堆
大佬我有下面几个问题
1. 选哪个做cookie，填到 `const discuz_cookies = {};`这里？
2. lib/config.js中在这里` discuz_cookies[cid] = envs[name];` 填自己设的 cid吗？
3. 我就知道这两个设置还要设哪个吗？谢谢

<img width="200" alt="image" src="https://user-images.githubusercontent.com/20753221/112762986-24343600-9035-11eb-8551-0c63712bb938.png">

**Comment by junfengP** [comment]
@iSteveyang 
`.env`文件添加下列信息，此处`cid`以`01`表示
```
DISCUZ_COOKIE_01='key1=value1; key2=value2;.....; keyn=valuen'
```
你图示中的信息是firefox解析后的，原格式按上述自己拼接

**Comment by iSteveyang** [comment]
好的谢谢大佬，但我好像还是失败了

> 缺少对应论坛的cookie

我本意是想订阅某discuz论坛中需要权限才能阅读的版区，但现在产生了怀疑，用cookie能实现吗？

**Comment by junfengP** [comment]
> 好的谢谢大佬，但我好像还是失败了
> 
> > 缺少对应论坛的cookie
> 
> 我本意是想订阅某discuz论坛中需要权限才能阅读的版区，但现在产生了怀疑，用cookie能实现吗？

可以，需要你登录账号后的cookie

另外配置`.env`文件后需要重新启动项目才会生效

**Comment by iSteveyang** [comment]
大佬，我配置.env也重启了，但是还是报错：
`Error in /discuz/x/01/https%3A%2F%2Fwww.XXX.com%2Fforum.php%3Fmod%3Dforumdisplay%26fid%3D46: Error: this route is empty, `
是cookie不对吗？
