### ISSUE TITLE
自建RSSHub Twitter 设置问题

### ISSUE THREAD

**Issue by shawn8888** [DIYgod/RSSHub#4561]
认真读了文档，但设置还是有问题。
http://mydomain:1200/twitter/followings/mytwitter_Username

出现错误：
`Error: lacking twitter token for user mytwitter_Username
    at module.exports (/app/lib/routes/twitter/followings.js:10:15)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/@koa/router/lib/router.js:368:16
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/koa-compose/index.js:34:12
    at dispatch (/app/node_modules/@koa/router/lib/router.js:373:31)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at cache (/app/lib/middleware/cache.js:203:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

在docker container里的变量，我设了三个：

```
TWITTER_CONSUMER_KEY: 1
TWITTER_CONSUMER_SECRET: 2
TWITTER_TOKEN_(3里的Token ID): 1,2,3,4

```
请问哪里设错了？

谢谢！

![Twitter Settings 1](https://user-images.githubusercontent.com/8271101/80293976-94a24b00-8732-11ea-9387-3780edd473ba.png)

**Comment by shawn8888** [comment]
![image](https://user-images.githubusercontent.com/8271101/80296158-9d9d1780-8746-11ea-833b-e4bdb9f013fa.png)

**Comment by yefoenix** [comment]
TWITTER_TOKEN_{id} 这里是用户的 ID ，不是 Token-ID，就是你用来@用户的那个id

**Comment by shawn8888** [comment]
> 
> 
> TWITTER_TOKEN_{id} 这里是用户的 ID ，不是 Token-ID，就是你用来@用户的那个id

成功！
多谢多谢！

**Comment by Rixcloudllnll** [comment]
@shawn8888  @yefoenix  两位好，我配置twitter的.env也不成功，https://github.com/DIYgod/RSSHub/issues/2731 这边说是TWITTER_ACCESS_TOKEN中减号前的那串数字

TWITTER_TOKEN_{id} 两者我都试过了，Access token中的数字和我的用户名（@ 后面的字符）

我的提问：#5234 

.env里我配置的白名单也失败，.env文件格式
```
WHITELIST=id
TWITTER_CONSUMER_KEY=API key
TWITTER_CONSUMER_SECRET=API secret key
TWITTER_TOKEN_用户名id=API key,API secret key,Access token,Access token secret
```

.env 文件位置为/RSSHub/.env ，这个位置有问题吗？

谢谢

**Comment by HenryQW** [comment]
Twitter API 太难申请了，长什么格式都不知道

**Comment by hotsymbol** [comment]
是啊，为什么不直接抓取呢，非要用api
