### ISSUE TITLE
instagram抓取bug

### ISSUE THREAD

**Issue by cronmoon** [DIYgod/RSSHub#4565]
尝试了好几个搭建好的网站，抓取in上其它用户都没有问题，但是对于某个用户测试了两个貌似都有这个问题：
https://rss.shab.fun/instagram/user/yun.jj
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

https://uneasy.win/rss/instagram/user/yun.jj
TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dabo-t** [comment]
私密帐户，无法抓取

**Comment by cronmoon** [comment]
多谢大佬指点，还有个问题想请教下大佬：
官网的配置文档，里面对于代理配置这块：
PROXY_PROTOCOL: 使用代理，支持 socks，http，https
PROXY_HOST: 代理服务器域名或 IP
PROXY_PORT: 代理服务器端口
PROXY_AUTH: 给代理服务器的身份验证凭证，Proxy-Authorization: Basic ${process.env.PROXY_AUTH}
PROXY_URL_REGEX: 启用代理的 URL 正则表达式，默认全部开启 .*
我自己有一个国外的机场，搭建了SSR服务能否配合使用，如果能够使用的话，上面的配置规则怎么写？身份验证凭证和URL 正则表达式这两个地方，我自己尝试了很多遍也不行，大佬能否指点一下



1580874151@qq.com
 
发件人： Double
发送时间： 2020-04-26 14:01
收件人： DIYgod/RSSHub
抄送： cronmoon; Author
主题： Re: [DIYgod/RSSHub] instagram抓取bug (#4565)
私密帐户，无法抓取

**Comment by hoilc** [comment]
不直接支持SSR，需要配合SSR客戶端

**Comment by 10362227** [comment]
试试装XX-NET，而且XX-NET使用的是谷歌ip，和IG一家
