### ISSUE TITLE
希望添加github 官方源 RSS2.0支持

### ISSUE THREAD

**Issue by Haocen2004** [DIYgod/RSSHub#4579]
### 这是一个什么样的功能？
github官方只有atom格式RSS的导致我所使用的qq机器人RSS插件读取不了
### 这个功能可以解决什么问题？
对github官方rss源添加RSS2.0格式支持
### 额外描述
读取重写应该挺简单的吧  
（不会js）  
这是第三个issues  
其他两个分别是github官方和机器人插件  
那个先好用那个kok

**Comment by yefoenix** [comment]
@Haocen2004 用feedburner 烧一下就好了……

**Comment by Haocen2004** [comment]
awa不好意思，对于RSS方面我还是个小白，给您添麻烦了
