### ISSUE TITLE
Twitter 订阅失败

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#4580]
### 路由地址
twitter

### 预期是什么？
成功订阅

### 实际发生了什么？
订阅地址打开失败
比如: [https://rsshub.app/twitter/user/DIYgod](https://rsshub.app/twitter/user/DIYgod)
![image](https://user-images.githubusercontent.com/10363328/80381348-68720000-88d3-11ea-8df5-9fe22245abb3.png)

**Comment by junfengP** [comment]
demo被墙，需要科学上网，该路由一切正常。

**Comment by DerekTso** [comment]
@junfengP 已经科学了，推特也可以上，但就是打不开这个RSS链接，需要特殊的设置吗

**Comment by junfengP** [comment]
> @junfengP 已经科学了，推特也可以上，但就是打不开这个RSS链接，需要特殊的设置吗

你开个全局科学试试
