### ISSUE TITLE
[Feature Request] 支持已经有 RSS Feed 的站点

### ISSUE THREAD

**Issue by Xuanwo** [DIYgod/RSSHub#46]
## 原因

很多网站自带了 RSS Feed 源，但是有些 feed 源比较难找，比如 Issue： https://github.com/DIYgod/RSSHub/issues/22 。

## 实现

支持该 Feature 基本没有什么开发量，直接抓取源站的 Feed 并返回即可。

## 预期作用

让用户不需要自己再去网站上找 RSS feed 的链接，直接使用 RSSHub 即可。

**Comment by benpigchu** [comment]
@Xuanwo 【那么，你打算怎么自动地找到对应的链接（】

**Comment by Xuanwo** [comment]
这个部分是需要自己的写的

**Comment by wenketel** [comment]
`  <link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="http://feeds.feedburner.com/CssTricks">`
这个网站不难吧，网页源码有相关代码，火狐的订阅功能都可以识别，就算某些不标准的自己猜下也能猜到。
感觉这个功能偏离RSSHub的初衷了。

**Comment by Xuanwo** [comment]
Closed for not implemented.
