### ISSUE TITLE
游戏时光新闻 路由的图片在自建的tiny rss阅读器里不能显示了。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4604]
### 路由地址
https://rsshub.app/vgtime/news
### 预期是什么？
图片正常显示
### 实际发生了什么？
无法正常显示，只有个“now loading”
### 部署相关信息
自建最新commit的rsshub

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
感觉是源站有变化导致的？

![批注 2020-04-29 115413](https://user-images.githubusercontent.com/3047708/80559794-50a09600-8a11-11ea-80f7-5a5720e740bf.png)

**Comment by DIYgod** [comment]
RSSHub 返回和我的 ttrss 测试都没问题

**Comment by ruleroller** [comment]
@DIYgod 奇怪。刚更新了几则条目，有的可以显示，有的就是now loading。我ttrss最近也没动过啊，昨天都还好的。

![image](https://user-images.githubusercontent.com/3047708/80569625-e9dca600-8a2b-11ea-8e59-f2835ea0ff8e.png)

**Comment by ruleroller** [comment]
貌似自动好了，不知是什么原因。先关闭了。
