### ISSUE TITLE
联合早报 即时中国 无法获取最新新闻

### ISSUE THREAD

**Issue by zhanghub** [DIYgod/RSSHub#4631]
### 路由地址
/zaobao/realtime/:type?
### 预期是什么？
在inoreader中下拉刷新获取最新的信息，已经科学上网。
### 实际发生了什么？
无法获取最新新闻，仍然是两天前的新闻。

**Comment by lei2rock** [comment]
一样的问题：

- 自建的情况下提示

![](https://user-images.githubusercontent.com/19180725/80789059-7b2f5200-8bbd-11ea-9277-f723142bf256.jpg)

- 用演示demo的rsshub.app会提示

![](https://user-images.githubusercontent.com/19180725/80789044-6eaaf980-8bbd-11ea-9930-b7eef11ffb55.jpg)

**Comment by sparereal** [comment]
附议。是网站反爬吗，请高手解惑。

**Comment by MittWillson** [comment]
这是一个依赖库 got 的重定向bug，等待got后续更新修复
