### ISSUE TITLE
docs.rsshub.app is showing desktop site in Firefox Preview

### ISSUE THREAD

**Issue by ksy36** [DIYgod/RSSHub#4633]
### Involved route
Visit https://docs.rsshub.app/ in Firefox Preview or in Responsive design mode in Firefox desktop
### What is expected?
The mobile version of the site is shown
### What is actually happening?
Site loads as mobile at first, but switches to desktop within a second
### Additional info (logs errors etc)
We've diagnosed the issue and looks like this is happening due to `viewport` tag being removed. More information can be found in this comment https://github.com/webcompat/web-bugs/issues/52296#issuecomment-621474789

**Comment by NeverBehave** [comment]
This issue seems to relate to an upstream implementation:

https://github.com/vuejs/vuepress/blob/01cd096307b55c920f6eb2eb1af9e0f8f2b153ac/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js#L62

It looks like the current header it not kept. Further investigation required.

**Comment by NeverBehave** [comment]
https://github.com/vuejs/vuepress/issues/2359

I have successfully reproduced this behavior and opened an issue regard this.

**Comment by ksy36** [comment]
Thanks for looking into this :)

**Comment by NeverBehave** [comment]
https://github.com/vuejs/vuepress/issues/2332

Looks like this issue has been opened 11 days ago and a fix already provided, but no one does the review.

**Comment by NeverBehave** [comment]
status: workaround applied.
