### ISSUE TITLE
GitHub Issue RSS 中部分 html 标签被转义

### ISSUE THREAD

**Issue by whtsky** [DIYgod/RSSHub#465]
e.g. 
https://rsshub.app/github/issue/sorrycc/blog

`<p>&lt;img src=&quot;https://gw.alipayobjects.com/zos/rmsportal/bacFVBmyGFoXlEVtxgKE.gif&quot; width=&quot;200&quot; /&gt;</p>`

这里的 `<img>` 标签被转义了，导致显示错误

**Comment by HenryQW** [comment]
推荐把文内 html 转成 markdown, 转换都是npm包自动的, nothing we can do here.

**Comment by whtsky** [comment]
> 推荐把文内 html 转成 markdown

这个文内 HTML 看起来是可以在 GitHub 里正常显示的： https://github.com/sorrycc/blog/issues/68 

> 转换都是npm包自动的

看起来是可以关的： https://markdown-it.github.io/markdown-it/#MarkdownIt.new ，但是可能要再过一遍 sanitizer
