### ISSUE TITLE
Add a more beginner friendly guide.

### ISSUE THREAD

**Issue by Crazierinzane** [DIYgod/RSSHub#4661]
### What feature is it?
Someone, like me, who doesn't know how to use any of this tech aside from following the officially posted guides cannot successfully use the software. Specifically, launching RSSHub locally on Windows in Docker to create an RSS feed for Pixiv keywords. 

### What problem does this feature solve?
Being able to use the software.

### Additional description
First time using Docker. I can launch RSSHub on Docker and see the localhost test easily enough, but there is nothing telling me how to change it from there. Parameters, routes, and environment variables all feel like they skipped over some major instructions from there.

**Comment by HenryQW** [comment]
https://docs.rsshub.app/en/

The doc has everything you just asked, parameters, routes, and environment variables.

I honestly think we can simplify this any further.
