### ISSUE TITLE
Fulltext 模式失效

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#4663]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/4663)

### 路由地址
例：
https://rsshub.app/guanchazhe/personalpage/243983?mode=fulltext
https://rsshub.app/weseepro/newest-direct?mode=fulltext
https://rsshub.app/kzfeed/topic/AXZaJq3Av40kp?mode=fulltext
### 预期是什么？
抓取到全文
### 实际发生了什么？
无法抓取
### 部署相关信息
官方 Demo 及 heroku、vercel 自建最新版服务
### 额外信息（日志、报错等）
已知以上三个路由在之前都是可以抓到全文的，我用 docker 自建的旧版本服务目前依然可以正常抓取。

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($1.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by DIYgod** [comment]
试了下没发现异常，可能只是网络问题？

**Comment by yefoenix** [comment]
我先关掉再观察一下
