### ISSUE TITLE
steamdb 路由都失效了

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4669]
### 路由地址
https://rsshub.app/steamdb/free
https://rsshub.app/steamdb/free/keep
### 预期是什么？
正常显示条目
### 实际发生了什么？
报错
### 部署相关信息
官方demo和自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/81040447-f6ef0e80-8edd-11ea-94a7-468ce43cc51a.png)

感觉还是因为那个Cloudflare。

**Comment by DIYgod** [comment]
#4538
