### ISSUE TITLE
推特高级搜索订阅地址无效

### ISSUE THREAD

**Issue by Amanoki** [DIYgod/RSSHub#4670]
推特带多个条件的高级搜索的RSS订阅链接有几率返回错误：

例1：搜索推号@DIYGod中包含“RSS”的推文，搜索关键词是RSS (from:DIYGod)，
生成订阅链接为 https://rsshub.app/twitter/keyword/RSS%20(from:DIYGod) ，
链接打开是一个错误页面。

例2：搜索包含关键词且最少两条回复的推文，
关键词为“RSS”，https://rsshub.app/twitter/keyword/RSS%20min_replies:2 ，这个链接是错误页面。
关键词为“test”，https://rsshub.app/twitter/keyword/test%20min_replies:2 ，这个链接又能正常打开。（更新：第二个链接后来打开又报错了，似乎是一时一时的。能打开的时候可以正常订阅，报错时就订阅不了）

除了高级搜索外似乎是关键词带空格都会有几率不行？比如“keyword/RSS DIY”链接就正常，而”keyword/RSS DIYGod“就错误。

错误信息：
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by MittWillson** [comment]
调试了一下这个错误，实际上是因为API没有返回任何推文导致抛出来的异常
然后我去查了一下 Twitter 关于 twitter/search 的接口，它关于 until 的描述是这样的
`
Returns tweets created before the given date. Date should be formatted as YYYY-MM-DD. Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.
`
也就是说由于RSSHub使用的是 Twitter 官方提供的API, 所以官方限制大于7天的推文是不会被搜索到的，7天以上的推文属于历史推文，目前我知道的是只有提供给企业的API可以获取，所以这个应该不属于BUG

@DIYgod 是否应该在文档中标注一下

**Comment by Amanoki** [comment]
> 调试了一下这个错误，实际上是因为API没有返回任何推文导致抛出来的异常
> 然后我去查了一下 Twitter 关于 twitter/search 的接口，它关于 until 的描述是这样的
> `Returns tweets created before the given date. Date should be formatted as YYYY-MM-DD. Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.`
> 也就是说由于RSSHub使用的是 Twitter 官方提供的API, 所以官方限制大于7天的推文是不会被搜索到的，7天以上的推文属于历史推文，目前我知道的是只有提供给企业的API可以获取，所以这个应该不属于BUG
> 
> @DIYgod 是否应该在文档中标注一下
> 
> 尴尬.. RSS from:DIYgod 这个确实有包含因为7天限制，因为DIY在7天内并没有任何RSS相关关键字的推文，高级搜索好像是被错误 encodeURIComponent 了, 已提交PR等待合并修复

你好，请问你的意思是高级搜索除了7天限制之外确实是有其他问题导致了错误吗？因为像例2里“RSS min_replies:2”这个搜索条件在一天内有蛮多新推的，应该不属于7天限制，但打开依然错误了。

另外对于7天没有新搜索结果这种情况，如果RSS链返回错误的话就会无法订阅，请问是否有可能返回一个空的、可以订阅的RSS链，当某天有新搜索结果时仍然能够接收到更新？

**Comment by MittWillson** [comment]
> > 调试了一下这个错误，实际上是因为API没有返回任何推文导致抛出来的异常
> > 然后我去查了一下 Twitter 关于 twitter/search 的接口，它关于 until 的描述是这样的
> > `Returns tweets created before the given date. Date should be formatted as YYYY-MM-DD. Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.`
> > 也就是说由于RSSHub使用的是 Twitter 官方提供的API, 所以官方限制大于7天的推文是不会被搜索到的，7天以上的推文属于历史推文，目前我知道的是只有提供给企业的API可以获取，所以这个应该不属于BUG
> > @DIYgod 是否应该在文档中标注一下
> > 尴尬.. RSS from:DIYgod 这个确实有包含因为7天限制，因为DIY在7天内并没有任何RSS相关关键字的推文，高级搜索好像是被错误 encodeURIComponent 了, 已提交PR等待合并修复
> 
> 你好，请问你的意思是高级搜索除了7天限制之外确实是有其他问题导致了错误吗？因为像例2里“RSS min_replies:2”这个搜索条件在一天内有蛮多新推的，应该不属于7天限制，但打开依然错误了。
> 
> 另外对于7天没有新搜索结果这种情况，如果RSS链返回错误的话就会无法订阅，请问是否有可能返回一个空的、可以订阅的RSS链，当某天有新搜索结果时仍然能够接收到更新？

是的，我已经修复并提交了PR，等待合并，你可以关注一下 #4713
