### ISSUE TITLE
探测当前页面 RSS 的 Chrome 插件

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#468]
- 探测 `application/rss+xml` `application/atom+xml` link
- 匹配 RSSHub 规则
- 一键订阅到 Feedly、Inoreader、Tiny Tiny RSS 等
- 类似 [rss-feed-reader](https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp) [rss-subscription-extensio](https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd)

**Comment by tgly307** [comment]
Chrome插件是不是只针对页面内容？类似于半自动的cheerio？

**Comment by DIYgod** [comment]
@tgly307 是；只获取 RSS 地址，不是 RSS 内容

**Comment by htfei** [comment]
这个我写出来了，不过我是自学的js，代码很low，可以看看：
https://github.com/htfei/chrome_exts/tree/master/RssPlus

**Comment by JackEggie** [comment]
https://github.com/shevabam/get-rss-feed-url-extension

这个chrome插件还不错。

**Comment by DIYgod** [comment]
相关 issue #293 #135

**Comment by idealclover** [comment]
https://github.com/idealclover/Easy-to-RSS
做了一个小demo，以后会进一步完善

**Comment by Maecenas** [comment]
@ttttmr（[Ⓙ透明T](https://web.okjike.com/user/1e7479ee-7c5e-4319-9b40-9ca9d70f3177/)） 写的[小书签](https://gist.github.com/ttttmr/577acf8a7ddf97c8972a6132a15e238a)

https://tmr.js.org/p/dd73704/
