### ISSUE TITLE
Konachan Yande rss exist

### ISSUE THREAD

**Issue by SettingDust** [DIYgod/RSSHub#469]
The post RSS is exist. 
https://rsshub.app/konachan/post/panties+rating%3Asafe
https://konachan.com/post/piclens?tags=panties+rating%3Asafe
yandere is same to konachan

**Comment by DIYgod** [comment]
看起来差不多，如果 @hufan-akari 没有异议就删掉了

**Comment by DIYgod** [comment]
Done. ee51eada51e0eb9bc9868a0f0ab68f0b07d0fc82
