### ISSUE TITLE
RSS Request: The Atlantic

### ISSUE THREAD

**Issue by subokuleen** [DIYgod/RSSHub#4694]
### Website URL
https://www.theatlantic.com
### Website description
An independent news website
一个独立新闻网站
### What content should be included?
Title and contents of articles
文章标题和内容
### Additional description
Inoreader has a feed-burner feed of The Atlantic: 
Inoreader上The Atlantic的feed-burner源：
https://feeds.feedburner.com/TheAtlantic

**Comment by MisteryMonster** [comment]
inoreader按 'W' 是可以获取全文的啊，甚至[官方的 RSS 源](https://www.theatlantic.com/feed/all/)就和feedburner的一样。

**Comment by subokuleen** [comment]
> 
> 
> inoreader按 'W' 是可以获取全文的啊，甚至[官方的 RSS 源](https://www.theatlantic.com/feed/all/)就和feedburner的一样。

谢谢提供官方源，就是希望内网也可以浏览

**Comment by MisteryMonster** [comment]
@subokuleen RSSHub只是负责生成订阅源，不太理解“内网也可以浏览”是什么意思，如果是指越过防火墙我觉得你需要的是一个代理。

**Comment by yefoenix** [comment]
https://www.theatlantic.com/feed/all/

提 issue 请确认源站没有提供 RSS.
can be closed
@DIYgod
