### ISSUE TITLE
文章遍历中有条目返回404的处理

### ISSUE THREAD

**Issue by MisteryMonster** [DIYgod/RSSHub#4710]
### 这是一个什么样的功能？

在遇到 404 时尽可能返回可用的条目。

### 这个功能可以解决什么问题？

可以解决在遍历时一遇到 404 就终止输出 RSS。

### 额外描述

可以统一一个 404 的模板：

```
Title: RSSHub 找不到页面
Description: 请查看原站[链接](url)
```

条目抓取返回404结果，但前提是要有抓取成功的条目。

**Comment by MittWillson** [comment]
需要提供一下反馈的路由

404页面通常是不应该被抓取的

**Comment by MisteryMonster** [comment]
这是我在[调试](https://rsshub.app/apnews/topics/apf-topnews)的时候发现的，但是现在路由的抓取都是正常的。
404 的页面当然不应该抓取，但是页面在遍历条目获取文章内容时，会遇到文章失效但是页面没有把失效的链接从列表中移除，导致整个路由返回 404。也许这个不是很好解决？因为要区分是获取文章内容还是获取页面。

**Comment by hoilc** [comment]
手动try catch就是了，已有的路由中很多例子
