### ISSUE TITLE
河大rss订阅

### ISSUE THREAD

**Issue by Tmjz** [DIYgod/RSSHub#4720]
» 网站网址

» 网站描述

应包含哪些内容？

• 附加说明

**Comment by hoilc** [comment]
What does "河大" mean?

**Comment by yefoenix** [comment]
提issue请遵循模板，提供必要信息

**Comment by MisteryMonster** [comment]
建议关闭

**Comment by Tmjz** [comment]
不好意思，请问这个东西怎么关闭，我不小心弄开了，不知道怎么关闭

**Comment by Tmjz** [comment]
我只是希望河南大学的rss订阅重新开始提供服务

**Comment by MisteryMonster** [comment]
http://wz.henu.edu.cn/

**Comment by MittWillson** [comment]
@Tmjz  Comment 按钮旁边那个就是关闭issue的，如果是不能正常订阅你应该描述清楚一点，包括你访问的路由，报错以及期望结果，还有确定源是否正常，是否有数据
