### ISSUE TITLE
Hpoi手办wiki 排序问题

### ISSUE THREAD

**Issue by Pzzzzz5142** [DIYgod/RSSHub#4765]
### What feature is it?

希望Hpoi路由抓取的Hpoi源是按照时间排序的，目前我是在本地采用爬取link中的最后修改时间，并将其转换为时间后排序，但是这样会导致本地程序会花费较大的时间处理页面请求等操作。如果rsshub能像其他源一样按照时间排序返回结果，这无疑是非常好的。

同时，如果觉得这样做比较麻烦的话，能不能把整个页面信息放置在summary中，这样的话也能节省本地程序请求页面的时间。

由于我不会js（QwQ），所以迫不得已提出这个issue。当然目前来说这个源也是能用的，只不过会花费大概15s的时间处理时间排序的问题。

其中时间的标签是位于页面下的如下位置
```html
<div class="left-item-content">
Sun Feb 09 09:22:30 CST 2020 创建
</div>
```

大致使用的两种时间格式如果用python表示则是`datetime.datetime.strptime(content[:16], "%Y-%m-%d %H:%M")`和`datetime.datetime.strptime(content, "%a %b %d %H:%M:%S %Z %Y 创建")`，前者是更新页面的时间戳，后者应该是创建页面时自动生成的时间格式。

### What problem does this feature solve?

本地程序不需要再花费额外的时间爬取页面内容获取时间再重新排序，以提升阅读体验和程序效率。

**Comment by yefoenix** [comment]
这是什么本地阅读器还能处理修改feed内容？

**Comment by Pzzzzz5142** [comment]
> 这是什么本地阅读器还能处理修改feed内容？

自己写的qq bot。。。。

feedparser 读出来之后就是乱序的。。。

**Comment by hoilc** [comment]
具体哪个路由哪个页面？

**Comment by Pzzzzz5142** [comment]
hpoi/info 下的所有选项无时间元素。

<img width="675" alt="image" src="https://user-images.githubusercontent.com/31173671/82007787-aaee5780-969d-11ea-9d93-e31c058ec5cd.png">

这是feedparse获取的第一项。

<img width="593" alt="image" src="https://user-images.githubusercontent.com/31173671/82007808-c5c0cc00-969d-11ea-8689-5408ce46d884.png">

这是hpoi手办页面的前三项。

**Comment by Pzzzzz5142** [comment]
同时 gcores/category/news 这个路由也没有时间标记，但是返回的值是按照时间排序的。大致看了一下源码，可能是因为这个路由的消息都是从首页爬的然后自己生成的？

**Comment by hoilc** [comment]
> 同时 gcores/category/news 这个路由也没有时间标记，但是返回的值是按照时间排序的。大致看了一下源码，可能是因为这个路由的消息都是从首页爬的然后自己生成的？

并没有，估计是你用的`feedparser `在没有时间信息的情况下，默认按链接排序了，gcore顺序，而hopi是乱序的，这个是客户端行为，建议修改`feedparser`代码

hopi列表页只有`X小时前`时间，不值得为了精确时间便利每个页面

**Comment by Pzzzzz5142** [comment]
啊，原来如此，那麻烦问一下能够实现`当前时间-x小时/分钟前`给出时间吗？（如果不能我就默默的关掉这个issue了。。。

**Comment by hoilc** [comment]
> 啊，原来如此，那麻烦问一下能够实现`当前时间-x小时/分钟前`给出时间吗？（如果不能我就默默的关掉这个issue了。。。

可以的，稍等我提个pr

**Comment by Pzzzzz5142** [comment]
多泄！🙏
