### ISSUE TITLE
https://rsshub.app/telegram/channel/APTLeak route is empty

### ISSUE THREAD

**Issue by Ralfikus** [DIYgod/RSSHub#4797]
Hi.

Bad telegram channel rss.

https://rsshub.app/telegram/channel/APTLeak route is empty

**Comment by MittWillson** [comment]
APTLeak is not a channel, it's a group

**Comment by linzzzzllll** [comment]
https://rsshub.app/telegram/channel/qixinscience
https://rsshub.app/telegram/channel/good991199
why it doesn't work
