### ISSUE TITLE
pixiv.cat某些图片不能显示

### ISSUE THREAD

**Issue by wenketel** [DIYgod/RSSHub#48]
https://rss.now.sh/pixiv/user/6210796 
https://pixiv.cat/67809158.jpg
可以更换为 [pixiv.moe](https://github.com/LoveLiveSunshine/pixiv.moe)的api
前提是 @kokororin  同意

**Comment by jongcs** [comment]
你好 我是pixiv.cat的作者
前幾天似乎因為瞬間讀取的量太大了 導致伺服器崩潰 所以已經升級伺服器配置了

另外也有反向代理可以使用
把 `i.pximg.net` 換成 `i.pixiv.cat` 就可以使用了

**Comment by kokororin** [comment]
[反代](https://api.pixiv.moe/v2/image/i.pximg.net/img-original/img/2018/04/26/17/09/44/68412494_p0.jpg)可以随意使用

**Comment by DIYgod** [comment]
感谢 @jongcs 和 @kokororin ，问题已解决，本 issue 将被关闭
