### ISSUE TITLE
豆瓣图书、豆瓣音乐 RSS wanted

### ISSUE THREAD

**Issue by yfzhe** [DIYgod/RSSHub#480]
豆瓣的 RSS 现在支持电影和小组，希望可以增加对图书和音乐部分的支持：最近出版的图书、最近发行的音乐（华语/欧美/日韩等等）。

**Comment by einverne** [comment]
豆瓣有一个新书速递，大概可以从这里搞一搞

https://book.douban.com/latest?icn=index-latestbook-all
