### ISSUE TITLE
Slugify 生成重复的锚点

### ISSUE THREAD

**Issue by NeverBehave** [DIYgod/RSSHub#4803]
由于 Slugify 生成锚点时仅使用当前标题
在文档中, 部分分类中的二级标题由于类型一致会导致生成相同的锚点

Related: 
- https://github.com/DIYgod/RSSHub/pull/4786
- https://github.com/DIYgod/RSSHub/pull/4790

## 建议

唯一化锚点, 用remark走一下语法树，slugify单独使用1-2级标题生成

## 相关项目

https://github.com/remarkjs/remark-slug

**Comment by NeverBehave** [comment]
https://markdown-it.github.io/
https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md

markdown-it 并不是生成AST, 这样子的话相关功能实现起来会有点困难

**Comment by NeverBehave** [comment]
@DIYgod 研究了一下, 现在有两种u解决方案

1. 在文档`.md`中添加`id`

类似与排版, 直接给需要做层级判断的文档生成对应的id标签, vuepress生成的时候将直接采用指定的id

2. markdown-it 插件

重新实现一套 https://github.com/valeriangalliat/markdown-it-anchor

目前我手里有一个完成的版本, 但是没有处理用户手动制定的部分, 有点耦合到本项目

**Comment by NeverBehave** [comment]
顺便提一下, netlify 生成文档的preview应当保留 (看了一下检查, 似乎是被移除了)
方便检查新pr文档内容的问题和针对docs类修订的审核

**Comment by hoilc** [comment]
试了下，看起来没什么问题，辛苦～

**Comment by DIYgod** [comment]
> 顺便提一下, netlify 生成文档的preview应当保留 (看了一下检查, 似乎是被移除了)
> 方便检查新pr文档内容的问题和针对docs类修订的审核

配额不够了，不关要扣 7 刀了

**Comment by NeverBehave** [comment]
@DIYgod https://www.netlify.com/legal/open-source-policy/
考虑过这个吗 @diygod
给文档页脚加上netlify的标志，配上一个code of conduct应该就能过了
