### ISSUE TITLE
本地手动部署无法访问 instagram

### ISSUE THREAD

**Issue by j1406493495** [DIYgod/RSSHub#4804]
#4486 

### 路由地址
http://localhost:1200/instagram/user/diygod

### 预期是什么？
本地部署能够成功刷新到xml页面

### 实际发生了什么？
Unable to Subscribe
Reeder could not find a feed at the specified location.

### 部署相关信息
MacBook 手动部署
yarn start 成功访问 http://127.0.0.1:1200/

.env 配置如下：
PROXY_PROTOCOL=socks
PROXY_HOST=127.0.0.1
PROXY_PORT=1200
PROXY_URL_REGEX=.*

### 额外信息（日志、报错等）

info: /instagram/user/diygod.com, user IP: ::1
info: Proxy for https://www.instagram.com/diygod.com/
error: Error in /instagram/user/diygod.com: Received invalid Socks5 initial handshake (invalid socks version): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.

https://www.instagram.com/diygod.com/ 去除用户名后的.com 即https://www.instagram.com/diygod 网页访问成功。

手动部署访问 instagram 需要哪些需要添加的东西？目前我只添加了 .env 文件。

**Comment by junfengP** [comment]
`PROXY_PORT` 不对吧， 1200已经被rsshub占用了，如果你用ssr，默认端口应该是1080

**Comment by j1406493495** [comment]
我用的 clash 代理软件，代理端口为：
export https_proxy=http://127.0.0.1:7890 
http_proxy=http://127.0.0.1:7890 
all_proxy=socks5://127.0.0.1:7891

PROXY_PORT 我修改为 7891 后报错如下：

info: /instagram/user/diygod.com, user IP: ::1
info: Proxy for https://www.instagram.com/diygod.com/
error: Request undefined fail, retry attempt #1: HTTPError: Response code 404 (Not Found)
info: Proxy for https://www.instagram.com/diygod.com/
error: Request undefined fail, retry attempt #2: HTTPError: Response code 404 (Not Found)
info: Proxy for https://www.instagram.com/diygod.com/
error: Error in /instagram/user/diygod.com: Response code 404 (Not Found): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.

**Comment by hoilc** [comment]
![image](https://user-images.githubusercontent.com/9067094/82222354-bb2f5c80-9953-11ea-8492-b89fe367bc8f.png)

并没有问题

**Comment by j1406493495** [comment]
在家里试可以了，中午在公司不行，奇怪
