### ISSUE TITLE
bilibili数码分区-近期投稿-三日排行

### ISSUE THREAD

**Issue by lfscqk67** [DIYgod/RSSHub#4807]
网站地址
https://www.bilibili.com/ranking/all/188/1/3

网站描述
已发布的订阅中别的分区都有，就差数码分区没有，此处所指分区是大分区的数码，不知道是不是这个分区刚独立出来

需要生成什么内容？
三日/周/月排行

额外描述
无

**Comment by hoilc** [comment]
https://rsshub.app/bilibili/ranking/188/3/1

只是没列出来，填下分区ID就行

**Comment by lfscqk67** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hoilc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上10:02
收件人:&nbsp;"DIYgod/RSSHub"<RSSHub@noreply.github.com&gt;;
抄送:&nbsp;"秦坤"<1442782714@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DIYgod/RSSHub] bilibili数码分区-近期投稿-三日排行 (#4807)





 
https://rsshub.app/bilibili/ranking/188/3/1
 
只是没列出来，填下分区ID就行
