### ISSUE TITLE
bilibili分区-近期投稿-三日排行问题

### ISSUE THREAD

**Issue by lfscqk67** [DIYgod/RSSHub#4809]
路由地址
https://rsshub.app/bilibili/ranking/188/3/1

预期是什么？
能不能设置下rss订阅是排行榜前十名，也就是b站首页右侧那一列，感觉前一百名太多了，而且似乎失去了rss筛选资讯的意义

实际发生了什么？
实际上是前一百名的视频都会推送，质量不高而且量有点大

**Comment by MisteryMonster** [comment]
https://rsshub.app/bilibili/ranking/188/3/1?limit=10
