### ISSUE TITLE
果壳bug

### ISSUE THREAD

**Issue by Vergil999** [DIYgod/RSSHub#4841]
果壳const channelMap = {
    calendar: 'pac',
    institute: 'predator',
    foodlab: 'predator',
    pretty: 'beauty',
};
 pretty: 'beauty',映射错了 应该是 beauty: 'beauty', 之前抓不到数据 改了之后可以

**Comment by hoilc** [comment]
这个映射只是做兼容的。

请提供详细信息。

**Comment by DIYgod** [comment]
pr welcome

**Comment by NeverBehave** [comment]
缺少必要路由等信息, 暂时关闭
