### ISSUE TITLE
哔哩哔哩漫画更新 RRS 提案

### ISSUE THREAD

**Issue by ambiguoustexture** [DIYgod/RSSHub#4847]
### 网站地址
https://manga.bilibili.com
### 网站描述
哔哩哔哩漫画网页版。
### 需要生成什么内容？
特定漫画的更新提醒。

**Comment by prnake** [comment]
+1
大概看了一下请求api
`curl 'https://manga.bilibili.com/twirp/comic.v2.Comic/ComicDetail?device=pc&platform=web' \
  -H 'content-type: application/json;charset=UTF-8' \
  --data-binary '{"comic_id":26009}' \
  --compressed`
