### ISSUE TITLE
经济学人下载站，希望能写成支持下载的RSS

### ISSUE THREAD

**Issue by toyqiu** [DIYgod/RSSHub#4861]
### 网站地址
http://www.cgx02.xyz/index.php?dir=/te
### 网站描述
每周五自动抓取更新《经济学人》mobi、PDF、epub格式的web文件管理网站
### 需要生成什么内容？
需要生成支持下载器订阅后能自动下载的RSS

**Comment by yefoenix** [comment]
@toyqiu 有阅读器支持自动下载enclosure附件的吗？

**Comment by toyqiu** [comment]
> @toyqiu 有阅读器支持自动下载enclosure附件的吗？

阅读器没有能自动下载的。支持RSS订阅的下载器只要RSS源编写正确，什么格式都可以自动下载。

**Comment by yefoenix** [comment]
@toyqiu 明白了
