### ISSUE TITLE
instagramn自建及公开站都有部分用户无法生成RSS

### ISSUE THREAD

**Issue by tjsky** [DIYgod/RSSHub#4863]
### 路由地址
/instagram/user/yifei_cc
### 预期是什么？
正常生成订阅源
### 实际发生了什么？
无法生成RSS，报错。
就很奇怪，其他人都能正常生成RSS，就她这一个人不行
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      Ubuntu16.04         |
| Node version       |        12.16.2       |
| if Docker, version |    19.03.9           |

### 额外信息（日志、报错等）
```TypeError: Cannot read property '0' of undefined
    at Promise.all.list.map (/app/lib/routes/instagram/user.js:61:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by OverZealous** [comment]
I'm having the same issue with this Instagram user, been having it for a while:

`/instagram/user/nathanwpylestrangeplanet`

```
TypeError: Cannot read property '0' of undefined
    at Promise.all.list.map (/home/phil/RSSHub/lib/routes/instagram/user.js:47:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm not running in Docker.

**Comment by sidelux** [comment]
Same here from the docker version:
```
TypeError: Cannot read property '0' of undefined
    at Promise.all.list.map (/app/lib/routes/instagram/user.js:47:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sidelux** [comment]
Ok i found that now multiple images in a post and video post needs instagram credentials...
So for a temporary fix i edited tag.js (users.js and other could be edited in same way) to get only single images: https://gist.github.com/sidelux/fb302544e4299ac8d31bc9735da702d2

Waiting for a permanent fix (if possible) :(

**Comment by sidelux** [comment]
Ok i found that now multiple images in a post and video post needs instagram credentials...
So for a temporary fix i edited tag.js (users.js and other could be edited in same way) to get only single images: https://gist.github.com/sidelux/fb302544e4299ac8d31bc9735da702d2

Waiting for a permanent fix (if possible) :(

**Comment by guodong2019** [comment]
i deployed on ubuntu manually, but can not get any rss xml data for any instagram user.
![image](https://user-images.githubusercontent.com/46913819/83394813-cc846880-a42b-11ea-8058-7e65e371c118.png)
Is there anything else settings?

**Comment by bruceguodong** [comment]
I deployed on ubuntu 18.04 manually, but I can not get any rss xml data for any instagram username (curl http://127.0.0.1:8090/instagram/user/barackobama).
![image](https://user-images.githubusercontent.com/5039482/83395268-8ed40f80-a42c-11ea-9fce-84c787412e20.png)

Is there need anything else settings?
only yifei_cc you can not get right rss data?

**Comment by sidelux** [comment]
@bruceguodong with my installation it works well, what i the error with `instagram/user/barackobama`? Screenshot is not from that query.
Anyway please create another issue since this is a separate problem.

**Comment by bruceguodong** [comment]
Sorry , the Screenshot I post above is wrong.
![image](https://user-images.githubusercontent.com/5039482/83515176-81d81e80-a507-11ea-98da-4da407d84bfb.png)

when I execute command(`curl http://127.0.0.1:1200/instagram/user/barackobama`), it response error.
Is my host ip was blocked. Have you encounter this? Please give  me some advices, thank you so much.

**Comment by sidelux** [comment]
It's the error described 3 comments up, there is a temporary fix provided by me, if you need for user.js you should make the same edits.

**Comment by rbelem** [comment]
Something changed in the response

In the file lib/routes/instagram/user.js:15
```
if (data.entry_data.ProfilePage[0].graphql.user.is_private) {
```

It tries to access "ProfilePage" that is not available.
```
  "entry_data": {
    "LoginAndSignupPage": [
      {
        "captcha": {
          "enabled": false,
          "key": ""
        },
        "gdpr_required": true,
        "tos_version": "eu",
        "username_hint": ""
      }
    ]
  },
```

**Comment by sidelux** [comment]
Sometimes it does not load profile page, but if you try after some minutes should works well.

**Comment by rbelem** [comment]
@sidelux I tried with your patch and no luck, but just tried a few times. I will leave it running more time now. Thx :-)

**Comment by rbelem** [comment]
@sidelux It is not working :'(

**Comment by sidelux** [comment]
@rbelem send me your file and your error...

**Comment by rbelem** [comment]
I just download your file and placed it  at lib/routes/instagram/tag.js and the error is
```
TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sidelux** [comment]
But you are executing the _user.js_, that file should be updated like [this](https://gist.github.com/sidelux/d344ee3c37711ed7146318076c24e8f2).

**Comment by rbelem** [comment]
Ah! that's true! :sweat_smile: I just updated it and will try it again. thx @sidelux

**Comment by OverZealous** [comment]
> But you are executing the _user.js_, that file should be updated like [this](https://gist.github.com/sidelux/d344ee3c37711ed7146318076c24e8f2).

The error we're seeing occurs before the image lookups. For some reason, I'm never getting `data.entry_data.ProfilePage` in the results, which is why the error occurs at line 15:

```js
    if (data.entry_data.ProfilePage[0].graphql.user.is_private) {
```
I've been trying on-and-off again for the last week or so, and it just never gives me a result. Here's what `data` looks like for me:

````js
{ config:
   { csrf_token: '0WYQ68YA2t3nzxCtPnpq5NpJoPUGKwKs',
     viewer: null,
     viewerId: null },
  country_code: 'US',
  language_code: 'en',
  locale: 'en_US',
  entry_data: { LoginAndSignupPage: [ [Object] ] },
  hostname: 'www.instagram.com',
  is_whitelisted_crawl_bot: false,
  deployment_stage: 'c2',
  platform: 'web',
  nonce: 'MQy0k9M+SqTfTBbgOzA66A==',
  mid_pct: 92.0442,
  zero_data: {},
  cache_schema_version: 3,
  server_checks: {},
  knobx:
   { '4': false,
     '17': false,
     '20': true,
     '22': true,
     '23': true,
     '24': true,
     '25': true,
     '26': true,
     '27': true,
     '28': true,
     '29': true,
     '30': true },
  to_cache:
   { gatekeepers:
      { '4': true,
        '5': false,
        '6': false,
        '7': false,
        '8': false,
        '9': false,
        '10': false,
        '11': false,
        '12': false,
        '13': true,
        '14': true,
        '15': true,
        '16': true,
        '18': true,
        '19': false,
        '23': false,
        '24': false,
        '26': true,
        '27': false,
        '28': false,
        '29': true,
        '31': false,
        '32': true,
        '34': false,
        '35': false,
        '38': true,
        '40': true,
        '41': false,
        '43': true,
        '59': true,
        '61': false,
        '62': false,
        '63': false,
        '64': false,
        '65': false,
        '67': true,
        '68': false,
        '69': true,
        '71': false,
        '72': true,
        '73': false,
        '74': false,
        '75': true,
        '77': true,
        '78': true,
        '79': false,
        '81': false,
        '82': true,
        '84': false,
        '86': false,
        '88': true,
        '91': false,
        '95': true,
        '97': false,
        '99': false,
        '100': false,
        '101': true,
        '102': true,
        '103': true,
        '104': true,
        '105': true,
        '106': true,
        '107': false,
        '108': true,
        '109': false,
        '111': false,
        '112': false,
        '113': true,
        '114': true,
        '116': true,
        '117': true,
        '119': false,
        '120': false,
        '123': false },
     qe:
      { '0': [Object],
        [...] // snipped out a bunch of the same idea
        '124': [Object],
        app_upsell: [Object],
        igl_app_upsell: [Object],
        notif: [Object],
        onetaplogin: [Object],
        felix_clear_fb_cookie: [Object],
        felix_creation_duration_limits: [Object],
        felix_creation_fb_crossposting: [Object],
        felix_creation_fb_crossposting_v2: [Object],
        felix_creation_validation: [Object],
        post_options: [Object],
        sticker_tray: [Object],
        web_sentry: [Object] },
     probably_has_app: false,
     cb: false },
  device_id: 'D7A9F0CB-A1D0-478F-8E2D-9D91DC09EDD9',
  encryption:
   { key_id: '75',
     public_key:
      '604ff4e00ae8467f6d30f4aa04ce2740b4acd77419c03655c032a77b643e126e',
     version: '10' },
  is_dev: false,
  rollout_hash: '01b761449ae2',
  bundle_variant: 'metro',
  is_canary: false,
  frontend_env: 'prod' }
````

**Comment by OverZealous** [comment]
I just checked the full page result, and I'm getting the login page. I also get this when trying to directly wget the page from the server, so I'm guessing Instagram has actually blocked my server. (I already had my RSS reader set to only check every 12 hours.)

**Comment by rbelem** [comment]
@OverZealous I got the same json output.

> I just checked the full page result, and I'm getting the login page. I also get this when trying to directly wget the page from the server, so I'm guessing Instagram has actually blocked my server. (I already had my RSS reader set to only check every 12 hours.)

That explains! Maybe a better way to work with instagram is to implement using an instagram account.

**Comment by sidelux** [comment]
The issue behind all is that ([#](https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-636313981)) now video and multi images pages are protected with an authentication, so now work only for single image.

The other problem explained by @rbelem is that sometimes also the single image page is protected (maybe there are some sorts of bot protections, idk) so i need to refresh page after minutes to get work.

**Comment by OverZealous** [comment]
Ah, I see it now. I wasn't trying to click on the specific page locally. Terrible decision by IG, since many people simply will stop visiting pages. Thank you for explaining, @sidelux, I wasn't understanding the specifics.

**Comment by DIYgod** [comment]
Instagram banned unlogged access, there is no way to get Instagram data now, so Instagram have been removed from RSSHub. 8f9371a9188b7e35e13a10a5263de6f6f9c2c5d8

**Comment by jtagcat** [comment]
Anyone looking at this with a sad face, see https://github.com/cloudrac3r/bibliogram/

**Comment by rbelem** [comment]
> Anyone looking at this with a sad face, see https://github.com/cloudrac3r/bibliogram/

I'm not sure... https://github.com/cloudrac3r/bibliogram/issues/77
I think that the solution would be implementing an instagram client for rsshub using the authenticated instagram api.

**Comment by DerekTso** [comment]
Could it be an alternative?
https://www.veryins.com/

**Comment by rbelem** [comment]
> Could it be an alternative?
> https://www.veryins.com/

Is there an English version? :-)

**Comment by DerekTso** [comment]
> > Could it be an alternative?
> > https://www.veryins.com/
> 
> Is there an English version? :-)

no luck for English one right now.

But it's okay to check the html resource and make up the feed xml info, without getting thru the language.

one example page: https://www.veryins.com/nuneworanuch

**Comment by lingnand** [comment]
I'm not sure if someone has already noticed it - but it appears to me that the 'authentication requirement' is something that can be bypassed?

Take https://www.instagram.com/nathanwpylestrangeplanet/ which is mentioned in the thread as an example:

1. go to that link
2. for any post in that page, right click: copy link location
3. paste in URL bar and go

I'm not logged in, but I can see all the images, including videos? The log-in prompt seems to be a js hoax that pops out only if you left click on those posts?

NOTE: I haven't looked into the actual scraper code, so what I observed might not be relevant after all.

**Comment by DerekTso** [comment]
> > Could it be an alternative?
> > https://www.veryins.com/
> 
> Is there an English version? :-)

Try this one: https://bibliogram.art/

**Comment by rbelem** [comment]
> > > Could it be an alternative?
> > > https://www.veryins.com/
> > 
> > 
> > Is there an English version? :-)
> 
> Try this one: https://bibliogram.art/

Cool! Just installed on my server and it works really well! Thanks @DerekTso

**Comment by jtagcat** [comment]
> Anyone looking at this with a sad face, see https://github.com/cloudrac3r/bibliogram/

> > > Could it be an alternative?
> > > https://www.veryins.com/
> > 
> > 
> > Is there an English version? :-)
> 
> Try this one: https://bibliogram.art/

That one has RSS feeds off. Anyone is welcome to use my instance: https://b.c7.ee
