### ISSUE TITLE
Pixiv路由的畫師個人頁面部分只穫取到插畫的部分，未見漫畫的部分包含在rss feed

### ISSUE THREAD

**Issue by galvn** [DIYgod/RSSHub#4866]
### 路由地址
pixiv/user/2774416

### 预期是什么？
穫取到近日更新的內容

### 实际发生了什么？
只抓到插畫的部分

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Heroku|
| Node version       |不明|

### 额外信息（日志、报错等）
演示地址與我deploy版本穫取的結果相同

Pixiv頁面位置:
[https://www.pixiv.net/users/2774416](https://www.pixiv.net/users/2774416)

**Comment by NeverBehave** [comment]
Close due to missing information and staled
