### ISSUE TITLE
用PM2运行程序，每天凌晨进程就自动消失了

### ISSUE THREAD

**Issue by 399425353** [DIYgod/RSSHub#487]
RT

**Comment by 399425353** [comment]
用的Appnode面板，Node.js版本10.8.0，PM2版本3.0.3
创建进程之后，每天早晨起来就发现挂掉，PM2中也看不到进程，无论之前是否保存过进程
在命令行下查看Logs，提示不存在

**Comment by ruich97** [comment]
@399425353 大概是没保存进程

**Comment by DIYgod** [comment]
非 RSSHub 问题
