### ISSUE TITLE
Instagram Stories: 404

### ISSUE THREAD

**Issue by jtagcat** [DIYgod/RSSHub#4877]
Related: #1188
Maybe related: #4863 
(Jump to relevant docs.](https://docs.rsshub.app/en/social-media.html#instagram-stories)
### Involved route
Instagram stories: `/instagram/story/instagram`
### What is expected?
An RSS feed.
### What is actually happening?
[404](https://http.cat/404)
### Self-deployed information
With docker-compose, behind Traefik, no specific credentials (not required according to the docs).
Docker image version: `4f8f937e09e1`

**Comment by jtagcat** [comment]
cc @Maecenas

**Comment by junfengP** [comment]
related: https://github.com/DIYgod/RSSHub/issues/4805
still broken

**Comment by DIYgod** [comment]
Duplicate of #4863

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-645761284
