### ISSUE TITLE
多个filter同时使用时过滤逻辑存在问题

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#4880]
### 路由地址
https://rsshub.app/boc/whpj/zs?filter_title=%E7%BE%8E%E5%85%83

https://rsshub.app/boc/whpj/zs?filter_title=%E7%BE%8E%E5%85%83&filter_description=71\d\.

### 预期是什么？
第一个地址是过滤出标题含”美元“的，第二个链接本意是想在第一个的基础上再过滤出描述里价格有71\d的。
### 实际发生了什么？
用第二个链接地址时，会将其它描述里含 71\d 的内容，但标题里并没有”美元“的项目也加入了进来，似乎两个filter之间用的是”或“的关系，导致产生这个问题。

### 部署相关信息
demo 和 最新版自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

![image](https://user-images.githubusercontent.com/3047708/83321475-90fa6a80-a282-11ea-8dfa-6bd95fb22852.png)

![image](https://user-images.githubusercontent.com/3047708/83321377-d1a5b400-a281-11ea-84de-9c793615d1d2.png)

![image](https://user-images.githubusercontent.com/3047708/83321710-06b30600-a284-11ea-8b2f-45ec2bfeb0d7.png)

**Comment by ruleroller** [comment]
@DIYgod 超过我的修复能力了，请作者看看啊，这是bug吗？

**Comment by junfengP** [comment]
`https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/parameter.js`
143~145行
![image](https://user-images.githubusercontent.com/15406392/83345496-4c380780-a346-11ea-821e-89cbe830db67.png)
143行：若标题满足正则表达式，则`isFilter = false`，将取消过滤内容和作者
若不满足标题过滤则继续过滤内容和作者，故出现上述问题。
当前运算逻辑为：或运算

如需修改为：与运算
```js
ctx.query.filterout_title && (isFilter = isFilter && title.match(makeRegex(ctx.query.filterout_title)));
ctx.query.filterout_description && (isFilter = isFilter && description.match(makeRegex(ctx.query.filterout_description)));
ctx.query.filterout_author && (isFilter = isFilter && author.match(makeRegex(ctx.query.filterout_author)));
return isFilter !== null;
```

![image](https://user-images.githubusercontent.com/15406392/83345829-e3eb2500-a349-11ea-861a-510862f0c6d3.png)

**Comment by ruleroller** [comment]
@junfengP 那应该是与还是或啊？老哥贴这个是让我自己按需求修改吗，其他人不需要修改？老哥可以直接发pr啊，如果这是一个bug的话。。

**Comment by junfengP** [comment]
我感觉这是一个八阿哥，目前win10没装`rsshub`环境，不好写pr，供给方便的兄弟来写了。

**Comment by ruleroller** [comment]
@junfengP filterout那几个呢，也需要改吗？

**Comment by junfengP** [comment]
我觉得filterout 应该是或逻辑运算

**Comment by ruleroller** [comment]
的确，或运算目前没问题。但我仔细想了下，与运算，似乎也没关系？就是担心filter和filterout合在一起会不会有什么bug。

**Comment by junfengP** [comment]
我觉得filterout使用或运算比较合适，更复杂的过滤功能还是交给阅读器来。

我认为
筛选信息应该是：严格获取有用信息，而宽松过滤无用信息

filter与filterout是串行工作的，应该不会有bug

**Comment by ruleroller** [comment]
@junfengP 你在3楼给的修改的内容，怎么都是filterout系列的，143-145行都是filter啊，是不是搞错了？

**Comment by junfengP** [comment]
> @junfengP 你在3楼给的修改的内容，怎么都是filterout系列的，143-145行都是filter啊，是不是搞错了？

```js
ctx.query.filter_title && (isFilter = isFilter && title.match(makeRegex(ctx.query.filter_title)));
ctx.query.filter_description && (isFilter = isFilter && description.match(makeRegex(ctx.query.filter_description)));
ctx.query.filter_author && (isFilter = isFilter && author.match(makeRegex(ctx.query.filter_author)));
return isFilter !== null;
```

复制错代码了，不好意思
