### ISSUE TITLE
RSSHub主站和文档均无法访问

### ISSUE THREAD

**Issue by daze456** [DIYgod/RSSHub#4889]
### 路由地址
RSSHub主站（rsshub.app）和文档(docs.rsshub.app)
### 预期是什么？
Welcome to RSSHub!
### 实际发生了什么？
rsshub.app 的服务器响应时间过长。

**Comment by hoilc** [comment]
GFWed.

**Comment by daze456** [comment]
那会有人修复这个bug吗？
或者，提供一下pdf格式的文档？

**Comment by daze456** [comment]
没事，我已经看到[文档](https://github.com/DIYgod/RSSHub/tree/master/docs)了
