### ISSUE TITLE
自建草榴论坛 盖达尔的旗帜交流區板块不能抓取当日内容

### ISSUE THREAD

**Issue by 11can** [DIYgod/RSSHub#4890]
### 路由地址

https://rsshub.app/t66y/16

### 预期是什么？

正常工作

### 实际发生了什么？

不能更新除置顶以外的帖子信息

### 部署相关信息

其他板块更新正常

**Comment by DIYgod** [comment]
rsshub.app/t66y/16 没看到有什么问题

**Comment by roisel** [comment]
> rsshub.app/t66y/16 没看到有什么问题

首次添加没有问题，但添加后不再更新新的帖子，一直是之前的

**Comment by ycycorona** [comment]
确实后续不能更新 看起来抓取回来的 pubdate 是未来时间
例如 
 <pubDate>Tue, 01 Dec 2020 08:03:00 GMT</pubDate>

**Comment by NeverBehave** [comment]
https://t66y.com/thread0806.php?fid=16
看了一眼, 似乎api改版了

**Comment by newtao** [comment]
> https://t66y.com/thread0806.php?fid=16 看了一眼, 似乎api改版了

rsshub-lpu0x3a5v-diy.vercel.app  这个可以用不知道是谁建的

**Comment by TonyRL** [comment]
Fixed in https://github.com/DIYgod/RSSHub/pull/8763
