### ISSUE TITLE
知乎已认证的官方帐号

### ISSUE THREAD

**Issue by alldataback-com** [DIYgod/RSSHub#4898]
### 网站地址
https://www.zhihu.com/org/hei-ma-cheng-xu-yuan

### 网站描述
知乎

### 需要生成什么内容？
需要获取认证的官方帐号的所有动态

### 额外描述
最好可以像用户一样可以获取认证官方帐号的动态，回答，想法，文章等等

**Comment by hoilc** [comment]
目前就可以，和普通用户一样使用

![image](https://user-images.githubusercontent.com/9067094/83966588-a8260180-a8ed-11ea-9af1-f26e2a3d2fd3.png)
