### ISSUE TITLE
希望改进一下知乎日报的格式

### ISSUE THREAD

**Issue by amozom** [DIYgod/RSSHub#491]
瞎扯栏目里有时候是一个问题，多个回答。

但是在同一个问题下不同答主的简介和回答都是同一个格式，有时候看内容有点困惑，而且想跳到下一个回答的时候找起来有点麻烦。

希望能将答主的简介行和回答改为不同格式。

【例子】
**钢铁侠违反物理学吗？**
淇宝宝
牛顿：他充钱了。
地心引力：明白！

知乎用户，不要问了！这把开双！
我就想知道他会不会夹到腋毛。
查看知乎原文

**你家的猫做过哪些不可思议的事？**
黄怡猫，一匹猫
每逢我洗澡，猫都会在门口撕心裂肺地叫以及疯狂地抓门（上厕所不会），那种感觉就是：它特别想欣赏一下沐浴的我……每次我都忍不住会开门一下，而每次，门开后，它都是盯一眼，然后嗷呜一声，扭头走开。

什么意思？这种行为是要告诉我什么？我身材很烂？

如果不想爱我，你何必表白？

愛簡潔，唱歌/读书/画画/摄影
印象特别深刻！

上小学的时候，有一次，我妈煮了米粉汤给我吃，我那时候也准备洗澡了，衣服都脱光了，坐在饭桌边（这画面真是_(:з」∠)_），准备吃完米粉汤就洗澡。小时候皮，不好好吃饭，吃着吃着把米粉汤全撒了，撒了一地，我妈气不打一处来，就开始揍我这个脱光了的熊孩子ヽ（・＿・；)ノ

我被我妈打得在地上打滚求饶……

然后……

揍着揍着，我家老母猫也过来帮我妈揍我了，出爪子就把我给挠了，边挠还边哈气！揍我顺便教育我是不？（我让你不好好吃饭！我让你不好好吃饭！）

就因为平时一直都是我妈喂的她！我妈疼她！

我特么？？？？？

人猫混合双打？？？？？

当时哭得更惨了……

**Comment by tgly307** [comment]
诶，我记得日报的原文里是有头像链接的，靠那个能区分出来。我去看看作者部分有没有单独的标记

**Comment by DIYgod** [comment]
Done. f227f0b8da10e41d82729344fea4648d79d6707c
