### ISSUE TITLE
not loading all open issues \ pull requests

### ISSUE THREAD

**Issue by infominer33** [DIYgod/RSSHub#4923]
### Involved route

Github
Repo Pull Requests
Repo Issues

### What is expected?

RSSHub will put all open issues or pull requests into a feed.

### What is actually happening?

[bitcoin/bips/pulls](https://github.com/bitcoin/bips/pulls) has 92 open, but I get only 27
[bitcoin/bitcoin/issues](https://github.com/bitcoin/bitcoin/issues) has 512 open, but I get 11
[bitcoin/bitcoin/pulls](https://github.com/bitcoin/bitcoin/pulls) has 385 open, but I get 26

https://reader.bitcoinfo.xyz
^^^ see feeds here if you want

### Self-deployed information

I got the same results from the demo version as self-hosting

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        Ubuntu       |
| Node version       |               |
| if Docker, version |         19.03.6, build 369ce74a3c      |

### Additional info (logs errors etc)

Maybe this is expected behavior... It would be nice to get all open issues\pull requests, but even if not all of them, I'd at least like to understand what is happening.

**Comment by hoilc** [comment]
Yes, it's expected behavior. RSSHub fetches recently created issues from GitHub API.

After all, RSS is used for getting update instead of clawing all contents.

**Comment by infominer33** [comment]
I don't find anywhere in [the route](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/github/pulls.js) that limits how many items are gathered.

upon further exploration, it's not even listing current pull-requests... but only old ones that were active in 2018-19.
