### ISSUE TITLE
澎湃新闻 不可用 

### ISSUE THREAD

**Issue by lhy1024** [DIYgod/RSSHub#4930]
### 路由地址
https://rsshub.app/thepaper/featured

### 预期是什么？
可以添加订阅

### 实际发生了什么？
![image](https://user-images.githubusercontent.com/19542290/83961551-e65bfa80-a8c6-11ea-8d37-dbc69d57ea10.png)

**Comment by yefoenix** [comment]
澎湃新闻又出现不可以了，依然是 empty， @DIYgod
