### ISSUE TITLE
Telegram Blog RSS from documentation doesn't work

### ISSUE THREAD

**Issue by sherlock440** [DIYgod/RSSHub#4944]
When you click on a [link from the official RSSHub site](https://docs.rsshub.app/en/social-media.html#telegram-telegram-blog) to the Telegram Blog RSS, an error is displayed:
![image](https://user-images.githubusercontent.com/63901545/84002187-b23d1400-a970-11ea-9497-bddba9819dca.png)

You cannot manually add this link to RSS either

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/blob/3173e5e21642da8e59a0051fa8f9dd0e5a261b8a/lib/routes/telegram/blog.js#L11

They changed style from `h1` to `h4` @fengkx 

Please follow the issue template next time, thank you.
