### ISSUE TITLE
即刻 RSS

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#4962]
### 网站地址

https://www.okjike.com/

### 网站描述

青春回来啦

### 需要生成什么内容？

- [ ] 用户动态 https://m.okjike.com/users/3EE02BC9-C5B3-4209-8750-4ED1EE0F67BB
- [ ] 圈子动态 https://m.okjike.com/topics/5701d10d5002b912000e588d

### 额外描述

[原接口](https://github.com/DIYgod/RSSHub/commit/228313fc3e4279fd530769891cf2cbe9dbb51017)已失效

**Comment by prnake** [comment]
@DIYgod 下午考完试看看
