### ISSUE TITLE
can't get weibo rss feed

### ISSUE THREAD

**Issue by yxd0018** [DIYgod/RSSHub#4977]
sample weibo home page is : 
https://www.weibo.com/u/1957965552

But none of the rss feed are valid:
https://rsshub.app/weibo/user/1957965552
https://rssfeed.today/weibo/rss/1957965552

**Comment by NeverBehave** [comment]
![Screenshot_20200613_144437](https://user-images.githubusercontent.com/17120571/84576662-7517be00-ad84-11ea-9d1d-8771596a1b7a.png)
PWD 确认路由有效

**Comment by NeverBehave** [comment]
@DIYgod 可以关了

**Comment by yxd0018** [comment]
> ![Screenshot_20200613_144437](https://user-images.githubusercontent.com/17120571/84576662-7517be00-ad84-11ea-9d1d-8771596a1b7a.png)
> PWD 确认路由有效

我用的RSSHUB链接从美国寻址也还是无效，这是否是个已知问题？

**Comment by NeverBehave** [comment]
对于反爬严格的路由，请在反馈的时候使用文档 [Play with Docker](https://docs.rsshub.app/install/#play-with-docker) 的部署方式进行测试
