### ISSUE TITLE
Dribbble 全部不能用了

### ISSUE THREAD

**Issue by m1dor1** [DIYgod/RSSHub#4985]
### 路由地址

- https://rsshub.app/dribbble/popular/week
- https://rsshub.app/dribbble/keyword/player
- https://rsshub.app/dribbble/user/google

### 实际发生了什么？

Error: this route is empty, please check the original site or create an issue.

**Comment by maoyoumu** [comment]
我也遇到的同样的问题～

**Comment by m1dor1** [comment]
可能因为 Dribbble 网页改版了，简单看了一下，把 [util.js#L82](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/dribbble/utils.js#L82) 里的 `li.group` 换成 `li` 应该就好了。另外：

- views 数据看不到了，所以 L22,L28 大概可以删掉？
- 给定时间范围的话，[popular.js](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/dribbble/popular.js#L5) url 里的 `/shots/popular` 要删掉。
