### ISSUE TITLE
品葱推荐热门

### ISSUE THREAD

**Issue by SiqingYu** [DIYgod/RSSHub#4989]
### 网站地址

https://pincong.rocks/

### 网站描述

政治时事讨论社区。

### 需要生成什么内容？

精选：https://pincong.rocks/hot/

推荐： https://pincong.rocks/recommend-1

热门当天：https://pincong.rocks/sort_type-hot__day-2

热门7天：https://pincong.rocks/sort_type-hot__day-7

热门30天：https://pincong.rocks/sort_type-hot__day-30

### 额外描述

与 #996 不重复。

**Comment by zlrs** [comment]
敏感网站，无法访问的，不建议添加到公共库里。（并且里面的内容，估计没几个人愿意看吧...）

**Comment by HenryQW** [comment]
> 敏感网站，无法访问的，不建议添加到公共库里。（并且里面的内容，估计没几个人愿意看吧...）

不存在的网站还嫌少吗？RSSHub本身就404🤪

**Comment by zlrs** [comment]
> > 敏感网站，无法访问的，不建议添加到公共库里。（并且里面的内容，估计没几个人愿意看吧...）
> 
> 不存在的网站还嫌少吗？RSSHub本身就404🤪

原来RSSHub也是404的？我觉得主要是这个网站仇恨的内容比较多。
