### ISSUE TITLE
东莞教研网rss路径不对

### ISSUE THREAD

**Issue by jy53655** [DIYgod/RSSHub#4993]
该网站不能使用境外ip访问，我是用nas搭建的hubrss访问，提示路径错误，麻烦更新一下，感谢。
<img width="554" alt="2020-06-15_191321" src="https://user-images.githubusercontent.com/60148857/84651397-755ab980-af3c-11ea-8568-1359fec302a1.png">

**Comment by nczitzk** [comment]
自建测试后 `/dgjyw/news` 、 `/dgjyw/announcement` 、 `/dgjyw/notice` 都可以正常工作。请问你使用的路由是什么呢？

**Comment by jy53655** [comment]
我用了两个地址测试，都不行，这两个地址分别是：
http://192.168.1.199:32768/dgjyw/announcement
http://rsshub.canglangzihshui.com/dgjyw/announcement
<img width="635" alt="2020-06-16_104712" src="https://user-images.githubusercontent.com/60148857/84726656-fc04aa80-afbf-11ea-9864-0eefb3cff756.png">
<img width="688" alt="2020-06-16_104720" src="https://user-images.githubusercontent.com/60148857/84726659-fdce6e00-afbf-11ea-93e1-7616b3235a77.png">
<img width="608" alt="2020-06-16_105206" src="https://user-images.githubusercontent.com/60148857/84726662-feff9b00-afbf-11ea-9edb-cc8e47184ab5.png">
<img width="600" alt="2020-06-16_105210" src="https://user-images.githubusercontent.com/60148857/84726664-ff983180-afbf-11ea-94c6-8b9da8c50bd4.png">

**Comment by nczitzk** [comment]
从你的运行时间来看，你似乎没有更新到添加了 `/dgjyw/announcement` 路由后的 RSSHub 版本。如果你使用的是更新路由前的版本的话，该路由是不存在的。所以你应该需要更新一下 RSSHub。

**Comment by jy53655** [comment]
通过更新到最新版rsshub，问题已经解决，感谢！！

DIYgod <notifications@github.com> 于 2020年6月18日周四 11:47写道：
