### ISSUE TITLE
Instagram Profile RSS from documentation doesn't work

### ISSUE THREAD

**Issue by sherlock440** [DIYgod/RSSHub#5003]
When you click on a link from the official RSSHub site to the [Instagram Profile RSS](https://docs.rsshub.app/en/social-media.html#instagram-user), an error is displayed:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/63901545/84736049-9f988f80-afad-11ea-9e1f-f341ca2ebdaa.png">

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-645761284
