### ISSUE TITLE
VPS上docker显示运行中，在浏览器访问却无结果

### ISSUE THREAD

**Issue by dutry** [DIYgod/RSSHub#5010]
VPS：阿里云国际版（香港）
安装方法：按照官方指南（docker安装）：
```
docker pull diygod/rsshub
docker run -d --name rsshub -p 1200:1200 diygod/rsshub
```
docker显示正在运行：
<img width="969" alt="Screen Shot 2020-06-17 at 6 03 03 PM" src="https://user-images.githubusercontent.com/17509207/84884908-e331ed00-b0c4-11ea-88c4-757d83873d53.png">
然而在浏览器使用[服务器IP]:1200访问却显示无结果（ERR_EMPTY_RESPONSE）

**Comment by junfengP** [comment]
阿里云VPS需要在官网手动开放端口，具体教程百度吧。

**Comment by dutry** [comment]
问题解决了！
