### ISSUE TITLE
IT之家 无法更新

### ISSUE THREAD

**Issue by WolfLee-red** [DIYgod/RSSHub#5012]
### 路由地址

https://rsshub.app/ithome/it

### 预期是什么？

RSS 正常更新网站内容。

### 实际发生了什么？

最后的更新时间是 `Thu, 18 Jun 2020 02:42:12 GMT`。此后该 RSS 地址无法更新 [IT之家](https://www.ithome.com/) 的最新内容。

### 额外信息（日志、报错等）

无

**Comment by lychichem** [comment]
5号起就不更新内容了，不过IT之家自己有RSS源，不行用官方的吧

**Comment by WolfLee-red** [comment]
> 5号起就不更新内容了，不过IT之家自己有RSS源，不行用官方的吧

官方的 RSS 是没有分类的……每天几百条信息几乎要爆炸，这就失去 RSS 订阅的本意了。

**Comment by prnake** [comment]
@WolfLee-red 访问ithome获取到的是缓存，有人知道知道是为什么吗？

**Comment by luyuhuang** [comment]
感觉是 it 之家的问题. 我部署在国外主机的 rsshub 输出是这样的:

![image](https://user-images.githubusercontent.com/10300685/85269136-0e904f80-b4aa-11ea-890b-52327670cfe0.png)

然后我发现, 我在国外主机和本地执行 `curl https://soft.ithome.com` , 得到的结果是不一样的.

国外主机执行 curl 得到的:

![image](https://user-images.githubusercontent.com/10300685/85269049-edc7fa00-b4a9-11ea-8bfe-17fa5738728c.png)

本地 curl 得到的:

![image](https://user-images.githubusercontent.com/10300685/85268900-b5c0b700-b4a9-11ea-8362-8d5664f3f128.png)

**Comment by prnake** [comment]
@luyuhuang 试试curl https://soft.ithome.com/?

**Comment by luyuhuang** [comment]
> 试试curl https://soft.ithome.com/?

你是让我在 URL 后面加个 `/` 吗? 结果是一样的.

**Comment by prnake** [comment]
@luyuhuang 加个问号...

**Comment by luyuhuang** [comment]
> 加个问号...

跟本地一样了. 这是什么原因?

**Comment by prnake** [comment]
curl应该是不带缓存的，而运行RSSHub的环境访问ithome得到的是缓存内容，感觉是CDN服务商做了缓存。但是 https://soft.ithome.com/?2333 这种参数构造是被禁止的，不清楚缓存原理想不到解决办法。

**Comment by gkl1368** [comment]
这个问题什么时候可以解决啊？

**Comment by prnake** [comment]
@gkl1368 issue 滞销，帮帮我们

**Comment by luyuhuang** [comment]
> 这个问题什么时候可以解决啊？

这个是 it 之家海外缓存的问题, rsshub 作为请求方很难解决这个问题. 最简单的办法就是在国内部署 rsshub

**Comment by gkl1368** [comment]
> > 这个问题什么时候可以解决啊？
> 
> 这个是 it 之家海外缓存的问题, rsshub 作为请求方很难解决这个问题. 最简单的办法就是在国内部署 rsshub

最新版没有这个路由了

**Comment by luyuhuang** [comment]
> 最新版没有这个路由了

https://rsshub.app//ithome/it
https://rsshub.app/ithome/ranking/24h

都有啊, 这两个地址都能访问

**Comment by gkl1368** [comment]
docker 最新版 提示hot error paths: 1  /ithome/it

**Comment by gkl1368** [comment]
> https://rsshub.app//ithome/it

第一个地址已经不存在了

**Comment by luyuhuang** [comment]
> > https://rsshub.app//ithome/it
> 
> 第一个地址已经不存在了

网页改版了, 需要修. 你可以先开个 issue

**Comment by HenryQW** [comment]
#5727 should have fixed this.
