### ISSUE TITLE
外接大脑订阅微信公众号bug

### ISSUE THREAD

**Issue by zznature** [DIYgod/RSSHub#5013]
### 路由地址
外接大脑
举例: https://rsshub.app/wechat/wjdn/5d5e683c82339df472988f59
路由: /wechat/wjdn/:id
### 预期是什么？
成功抓取
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/11894344/84978346-41131300-b15f-11ea-9e14-814594da4be7.png)
Thanks! @BugWriter2 
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |           ubuntu    |
| Node version       |               |
| if Docker, version |               |

**Comment by BugWriter2** [comment]
你好，我试了试是可以正常访问的：

<img width="400" alt="图片" src="https://user-images.githubusercontent.com/26344199/84979217-7d477300-b161-11ea-94f2-e9244f9cef30.png">

请问出现错误的公众号id是哪个啊？

**Comment by zznature** [comment]
多谢！我也试了即刻公众号（5d5e683c82339df472988f59），出现我上面同样的错误。。。
我的订阅链接哪里出问题了吗？
http://***.com:1200/wechat/wjdn/5d5e683c82339df472988f59

**Comment by BugWriter2** [comment]
请问你是不是没有更新代码啊？这个路径是最新添加的。代码更新之后再部署试试？

**Comment by zznature** [comment]
感觉是的，docker部署成功后就没更新过，多谢啦！晚点我再更新试试~

**Comment by zznature** [comment]
多谢！docker更新后正常运行啦
