### ISSUE TITLE
You are ddosing SteamDB

### ISSUE THREAD

**Issue by xPaw** [DIYgod/RSSHub#5014]
By querying RenderAppHover unratelimited you are essentially causing a DDoS on our server since there are a bunch of free demos.

I won't even question using the script to bypass cloudflare integrity check, but I have banned all the offending IPs running this.

**Comment by DIYgod** [comment]
Sorry to hear that, SteamDB have been removed from RSSHub https://github.com/DIYgod/RSSHub/commit/7718d3460d0785d8f8435b47a2d046de794e585a

BTW, we were not querying RenderAppHover unratelimited, we cached all querying result indefinitely by default. https://github.com/DIYgod/RSSHub/blob/8f9371a9188b7e35e13a10a5263de6f6f9c2c5d8/lib/routes/steam/steamdb/free.js#L44

**Comment by xPaw** [comment]
The amount of requests in logs does not seem to indicate that they were cached.
