### ISSUE TITLE
facebook粉絲專頁抓取有问题

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#5016]
### 路由地址
https://rsshub.app/facebook/page/SonetPCR
### 预期是什么？
抓取动态全文，包括图片
### 实际发生了什么？
抓取内容不全，抓取的内容大多只有个标题“（未知标题）”，无正文。偶尔有正文，图片也不能加载。

**Comment by DIYgod** [comment]
反爬严格，建议自建
