### ISSUE TITLE
[Feature Requset] Email Subscriptions to RSS

### ISSUE THREAD

**Issue by iFwu** [DIYgod/RSSHub#502]

**Comment by DIYgod** [comment]
无法获取每个人的 Email 数据

**Comment by iFwu** [comment]
Is this project aimed to deploy on the user's VPS? So it's possible via running an email client to do so.

**Comment by iFwu** [comment]
Or it should be another project, maybe it's beyond the purpose.

**Comment by DIYgod** [comment]
@iFwu It aims public subscriptions, private Email is beyond the purpose

**Comment by iFwu** [comment]
OK, thanks for replying. But there're some sites only offering email subscriptions, maybe I'll fork and make it possible for me.
