### ISSUE TITLE
喷嚏 无法全文输出

### ISSUE THREAD

**Issue by Sliverala** [DIYgod/RSSHub#5025]
### 路由地址
https://rsshub.app/dapenti/tugua
https://rsshub.app/dapenti/subject/184
### 预期是什么？
正常全文输出文章
### 实际发生了什么？
路由无法正常全文输出文章，只能输出标题
如果添加fulltext参数，则会输出乱码

**Comment by prnake** [comment]
原来是路由挂了...

**Comment by HenryQW** [comment]
#5022 已经修复了
