### ISSUE TITLE
求ieee author新发表文章的rss

### ISSUE THREAD

**Issue by Hanpride** [DIYgod/RSSHub#5038]
### 网站地址
如https://ieeexplore.ieee.org/author/37283006000、https://ieeexplore.ieee.org/author/37085497446等
### 网站描述
电子类学术网站
### 需要生成什么内容？
最新发表的论文题目（如果能加上联合作者和期刊名称更好）
### 额外描述
无

**Comment by queensferryme** [comment]
(#5059) 没有提供期刊名称，因为发表方式包含会议、期刊、杂志等难以统一，官方 API 中也没有找到相应字段~
