### ISSUE TITLE
不知可否提供medium的rss

### ISSUE THREAD

**Issue by JackEggie** [DIYgod/RSSHub#504]
[medium](https://medium.com/)

**Comment by imlonghao** [comment]
本身就有。

https://medium.com/feed/@username

**Comment by JackEggie** [comment]
好的。谢谢。打扰了。

**Comment by magictomagic** [comment]
RSShub Radar上没有显示，可以在https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-radar-gui-ze-bian-xie-gui-ze 提交新的规则，让它显示。
