### ISSUE TITLE
Twitter RSS is disabled due to the lack of relevant config

### ISSUE THREAD

**Issue by jimmy-walker** [DIYgod/RSSHub#5045]
### 路由地址
/twitter/keyword/:keyword
### 预期是什么？
返回内容
### 实际发生了什么？
Looks like something went wrong
Twitter RSS is disabled due to the lack of relevant config
请问是否twitter不能用了？
### 部署相关信息
heroku docker自建，rsshub git bash 3413a3b

### 额外信息（日志、报错等）
/twitter/keyword/shanghai
```
Looks like something went wrong
Twitter RSS is disabled due to the lack of relevant config
```

**Comment by zoenglinghou** [comment]
有申请推特的 API 吗？

具体设置看[这里](https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi)

**Comment by jimmy-walker** [comment]
@zoenglinghou 感谢你的回复。奇怪的是，前两天按照文档订阅的twitter的其他keyword仍然可以正常运行。

我感觉我的国内手机号应该通不过twitter的开发验证。囧rz

**Comment by zoenglinghou** [comment]
可能有些 API 不需要验证...关注用户是要 API 验证的，其他不太清楚，具体要看源码

**Comment by DIYgod** [comment]
缺少 key 理论上不存在可以正常运行的情况
