### ISSUE TITLE
[bug] 部分路透路由 bug

### ISSUE THREAD

**Issue by prnake** [DIYgod/RSSHub#5051]
### 网站地址
https://www.reuters.com/
https://cn.reuters.com/

### 网站描述
路透社官方不再支持 RSS feed 
[Confirmed: Reuters is officially killing off RSS support](https://www.reddit.com/r/rss/comments/hf2fjx/confirmed_reuters_is_officially_killing_off_rss/)

### 需要生成什么内容？
不同板块内容，[实时资讯](https://cn.reuters.com/theWire)、[深度分析](https://cn.reuters.com/news/analyses)等

### 额外描述
移动版 http://cn.mobile.reuters.com/ 或许更加好抓取，但不支持https

**Comment by black-desk** [comment]
#5080 只写了个实时资讯

**Comment by duguyipiao** [comment]
频道好像没有成功，示例的cn分站
https://rsshub.app/reuters/channel/cn/analyses
显示error， us分站的也不行，但uk分站的好像没有问题。

**Comment by HenryQW** [comment]
有空我再看一下

**Comment by HenryQW** [comment]
貌似是缓存出现了问题，看看 #5317 能不能修复。

**Comment by HenryQW** [comment]
@duguyipiao @wb14123 应该是修复了？

**Comment by duguyipiao** [comment]
@HenryQW 好像是正常了，谢谢了！
