### ISSUE TITLE
我想做一个我们大学的通知RSS订阅，但是文档看不太懂，求大佬教一下

### ISSUE THREAD

**Issue by LengMingxuan** [DIYgod/RSSHub#5054]
### 网站地址
https://www.lyu.edu.cn
### 网站描述
临沂大学官网
### 需要生成什么内容？
需要通过RSS订阅实时获取校园新闻

**Comment by 276562578** [comment]
#5183 可以看我的这个  刚写完的   我也是照着抄的

**Comment by LengMingxuan** [comment]
> #5183 可以看我的这个 刚写完的 我也是照着抄的

谢谢
