### ISSUE TITLE
自建微博抓取报错，显示this route is empty

### ISSUE THREAD

**Issue by Mordiggian** [DIYgod/RSSHub#5055]
### 路由地址
/weibo/user/1862695480
### 实际发生了什么？
其他所有微博用户都正常，只有这一个无法正常抓取
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   centos 7.3           |
| Node version       |      13.13.0         |
| if Docker, version |               |

**Comment by DIYgod** [comment]
https://m.weibo.cn/u/819711115 这个用户被限制了未登录访问，无解
