### ISSUE TITLE
picuki substitute Instagram

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [DIYgod/RSSHub#5058]
### Website URL
https://www.picuki.com/profile/vousmevoyez

### Website description
Browse Instagram stories, profiles, followers, posts and tags online

### What content should be included?
Same as instagram

**Comment by amir32** [comment]
picuki is also not working on [paklix](https://www.paklix.com) but i also found a way to make a [nice popcorn using fryer](https://www.paklix.com/2022/02/corn-airfryer-recipes.html). can you guide what to do.

**Comment by marthasimons8888** [comment]
Reallyappreciate this issue report! This link might add some value: <a href="https://rickycasino3.com/">https://rickycasino3.com/</a>
Great work!
