### ISSUE TITLE
UP 主动态有问题

### ISSUE THREAD

**Issue by muyuqingqiu** [DIYgod/RSSHub#5062]
### 路由地址
/bilibili/user/dynamic/:uid/:disableEmbed?
### 预期是什么？
up主动态中引用了投稿或其他动态时，抓取到的是引用的内容，而不是动态内容啊
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
无法复现，请提供具体链接

**Comment by muyuqingqiu** [comment]
https://rsshub.app/bilibili/user/dynamic/420711844

比如这里有个动态时up主引用了一个视频，动态内容是 “好 妈 妈”
但是抓到的是视频的简介

**Comment by chenxuan353** [comment]
已查证
视频动态 存在“dynamic”属性标识动态内容，可作为修复参考
