### ISSUE TITLE
推特关键词不支持tag么？

### ISSUE THREAD

**Issue by muyuqingqiu** [DIYgod/RSSHub#5063]
### 路由地址
/twitter/keyword/:keyword
### 预期是什么？
订阅tag时候发现会抓到很多重复的内容，如https://rsshub.app/twitter/keyword/%23%E6%9C%89%E6%A0%96%E3%81%AE%E7%B5%B5%E6%9C%AC.atom
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DerekTso** [comment]
I have the same issue, maybe we could add a new route for twitter hashtag

### hashtag
https://twitter.com/hashtag/GPT3

### search
https://twitter.com/search?q=GPT3

**Comment by simoin** [comment]
可以添加过滤参数 `#GPT3 -filter:retweets`  [https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/guides/standard-operators](url)
