### ISSUE TITLE
nhentai torrent模式无法使用

### ISSUE THREAD

**Issue by muyuqingqiu** [DIYgod/RSSHub#5064]
### 路由地址
/nhentai/:key/:keyword/:mode
### 预期是什么？
注册了账号，反复验证了账号密码可用，但是访问路由始终报错
Invalid username (or email) or password for nhentai torrent download
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by hoilc** [comment]
是因为n站最近启用了reCAPTCHA认证，天知道谷歌为什么会给本子网站提供服务😂

可以添加cookie支持，不过单个session只有14天有效期，犹豫中🤔

**Comment by yefoenix** [comment]
@hoilc 有没有可能cookie过期后自动重新登录并获取cookie？

**Comment by hoilc** [comment]
> @hoilc 有没有可能cookie过期后自动重新登录并获取cookie？

现在就是配置账号密码，自动登录获取cookie，然鹅...

我有个好像很缺德的主意...

**Comment by muyuqingqiu** [comment]
如果加cookie的话，能不能把cookie放到路由参数传递。。。每次改rsshub服务配置好麻烦

**Comment by HenryQW** [comment]
可以考虑少看一点。
