### ISSUE TITLE
邮件订阅报错

### ISSUE THREAD

**Issue by madordie** [DIYgod/RSSHub#5083]
### 路由地址

`/mail/imap/45*****36@qq.com`

### 预期是什么？

获取到`邮件列表`

### 实际发生了什么？

> Error: please config email password, host, port in .env file

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     CentOS          |
| Node version       |         v10.21.0      |
| Docker, version |         Docker version 19.03.11, build 42e35e61f3      |

### 额外信息（日志、报错等）

```log
$ cat docker-compose.yml | grep EMAIL_CONFIG
        - EMAIL_CONFIG_45*****36.qq.com='password=ab*********hgj&host=imap.qq.com&port=993'
$ docker logs -f rsshub

> rsshub@0.1.1 start /app
> node lib/index.js

info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: /mail/imap/45*****36@qq.com, user IP: 140.238.**.***
error: Error in /mail/imap/45*****36@qq.com: Error: please config email password, host, port in .env file
    at module.exports (/app/lib/routes/mail/imap.js:20:15)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/@koa/router/lib/router.js:363:16
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/node_modules/koa-compose/index.js:34:12
    at dispatch (/app/node_modules/@koa/router/lib/router.js:368:31)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at cache (/app/lib/middleware/cache.js:203:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by DIYgod** [comment]
https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

**Comment by madordie** [comment]
@DIYgod  指的是`EMAIL_CONFIG_{email}`? 我在日志的第一行已经输出了我的这个相关配置,就是配置之后依旧报错.

**Comment by zsbai** [comment]
一样，配置为：
EMAIL_CONFIG_xxxxxx.qq.com
password=xxxxxxxxxxx&host=imap.qq.com&port=993
仍然报错

**Comment by zsbai** [comment]
一样，配置完成后仍然报错，楼主找到解决办法了嘛？

**Comment by madordie** [comment]
> 一样，配置完成后仍然报错，楼主找到解决办法了嘛？

并没有，我已经放弃了😭

**Comment by kt286** [comment]
docker-compose.yml 中应该用 : 分隔吧
```
environment:
   - EMAIL_CONFIG_45*****36.qq.com    :   'password=ab*********hgj&host=imap.qq.com&port=993'

**Comment by HenryQW** [comment]
> docker-compose.yml 中应该用 : 分隔吧
> 
> ```
> environment:
>    - EMAIL_CONFIG_45*****36.qq.com    :   'password=ab*********hgj&host=imap.qq.com&port=993'
> ```

是用`=`的

**Comment by HenryQW** [comment]
找到问题了，我更新下文档
