### ISSUE TITLE
维修谷歌相册的公开影集

### ISSUE THREAD

**Issue by xiaogangHM** [DIYgod/RSSHub#5084]
### **网站地址**

https://photos.app.goo.gl/

### **网站描述**

谷歌相册里的公开影集功能

### **需要生成什么内容？**

 修复这个路由，获取到影集里面的图片流

### **额外描述**

谢谢大佬的帮助

**Comment by yefoenix** [comment]
@xiaogangHM 提issue请选择正确模板，提供必要信息
