### ISSUE TITLE
请求增加新榜网站订阅

### ISSUE THREAD

**Issue by lliu357** [DIYgod/RSSHub#5088]
### 这是一个什么样的功能？
爬取微信公众号、抖音号、快手号的内容
### 这个功能可以解决什么问题？
新榜[https://www.newrank.cn](https://www.newrank.cn)对于微信公众号、抖音号、快手号收录比较全，即使没有也可以提交文章链接进行收录。
### 额外描述
需要登录。

**Comment by DIYgod** [comment]
没找到，请提供具体链接，并使用这个模板 https://github.com/DIYgod/RSSHub/issues/new?template=rss_request_zh.md
