### ISSUE TITLE
微博用户id1865990891运行错误

### ISSUE THREAD

**Issue by willie91** [DIYgod/RSSHub#5094]
### 路由地址
https://rsshub.app/weibo/user/1865990891
### 预期是什么？
微博博主更新
### 实际发生了什么？
Looks like something went wrong
### 部署相关信息
demo出错，我自行部署也报同样的错误

**Comment by yefoenix** [comment]
提issue请遵循模板，提供必要信息

**Comment by willie91** [comment]
> 提issue请遵循模板，提供必要的信息

已修改

**Comment by madordie** [comment]
@willie91  你的`自行部署`报错信息是啥? 我的是

```log
info: /weibo/user/1195230310, user IP: 180.xxx.xx.163
error: Request undefined fail, retry attempt #1: RequestError: connect ETIMEDOUT 36.51.254.xxx:443
```

**Comment by willie91** [comment]
> @willie91 你的`自行部署`报错信息是啥? 我的是
> 
> ```
> info: /weibo/user/1195230310, user IP: 180.xxx.xx.163
> error: Request undefined fail, retry attempt #1: RequestError: connect ETIMEDOUT 36.51.254.xxx:443
> ```

![image](https://user-images.githubusercontent.com/32695308/86320647-e521b180-bc69-11ea-8b16-8ff767d3a435.png)
我出现的这个- -。demo好像是被反扒了

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/commit/e0d544be9b1a5c7c238291a60754cfbe02b948e6#diff-39602971d8baa6e936a5cd8dbf8168e4R783
