### ISSUE TITLE
【路由需求】新榜(newrank.cn) 作为新的微信公众号来源

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#5107]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/5107)

### 网站地址
https://www.newrank.cn/
### 网站描述
作为中国首先提供微信公众号内容数据价值评估的第三方机构，新榜已遍历超过2000万个微信公众号，截至2020年3月，对超过110万个有影响力的优质账号实行每日固定监测，即使没有也可以提交文章链接进行收录。
### 需要生成什么内容？

- [ ] 公众号推送链 feed

### 额外描述
作为一个附带功能，新榜的公众号原文链接藏得比较深，以公众号「知味葡萄酒杂志」为例：
在此公众号的内容页面 https://www.newrank.cn/new/readDetial?account=tastespiritmag 上，
公众号推送原文包括两种，
等待更新数据的四篇最新推送，链接获取方式如下：
![微信图片_20200702142649](https://user-images.githubusercontent.com/8215230/86324412-24073580-bc71-11ea-8d93-c508ecfcb2c5.png)
已有数据的推送链接，
![微信图片_20200702143501](https://user-images.githubusercontent.com/8215230/86324591-5b75e200-bc71-11ea-98c2-f25781ec8e84.png)

**（以上页面都需要在登录状态下查看）**

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1.00)

- [<img src='https://avatars3.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($1.00)

### Submitted pull Requests
- [#5254 Add 新榜(newrank.cn)](https://issuehunt.io/r/DIYgod/RSSHub/pull/5254)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by lliu357** [comment]
其实右边的标题也是原文链接

**Comment by lliu357** [comment]
这个网站也有抖音和快手，缺账号的话，提交后基本一天就有了。

**Comment by lessmoe** [comment]
造了个python能跑，看看这周能不能抽空改一下

**Comment by lessmoe** [comment]
#5254

**Comment by yefoenix** [comment]
可以关闭了 @HenryQW
