### ISSUE TITLE
lofter官方给的用户rss不能用了，希望能新增lofter用户的rss

### ISSUE THREAD

**Issue by BUNO19** [DIYgod/RSSHub#5108]
### 这是一个什么样的功能？
lofter官方给的用户rss不能用了，希望能新增lofter用户的rss

### 这个功能可以解决什么问题？
新增lofter的rss

### 额外描述
无

**Comment by yefoenix** [comment]
提issue请选择正确模板，提供必要信息

**Comment by yefoenix** [comment]
https://docs.rsshub.app/social-media.html#lofter
