### ISSUE TITLE
希望能增加soomal.com的rss订阅

### ISSUE THREAD

**Issue by geochemistry** [DIYgod/RSSHub#5120]
### Website URL
http://www.soomal.com/search/101_0001.doc/%E5%8F%A4%E5%85%B8%E5%85%A5%E9%97%A8.htm

### Website description
一个古典音乐类杂谈和乐评网站

### What content should be included?
希望能添加rss订阅

**Comment by zoenglinghou** [comment]
网站结构挺乱的，有些类别在 ./search 下面，有些在 ./doc 下面
目前打算只做首页那几个大类别，有别的需求可以提一下...
