### ISSUE TITLE
The China NGO Project

### ISSUE THREAD

**Issue by oppilate** [DIYgod/RSSHub#5124]
### Website URL
https://www.chinafile.com/ngo
### Website description
The China NGO Project is a community-driven platform from ChinaFile focused on non-governmental organizations (NGOs) working in China since the implementation of 2017’s Foreign NGO Law. We welcome—and rely on—feedback from readers; our contact information can be found on our About page and throughout the site.
### What content should be included?
The timeline in https://www.chinafile.com/ngo/latest

**Comment by yefoenix** [comment]
https://feeds.feedburner.com/chinafile/ngo

**Comment by oppilate** [comment]
I know. But they don't provide full-text output. I'll complete this later.
