### ISSUE TITLE
China File 中参馆

### ISSUE THREAD

**Issue by oppilate** [DIYgod/RSSHub#5125]
### Website URL
https://www.chinafile.com/
### Website description
 China File is an online magazine publishing, showcasing, and contributing to the best reporting and commentary on China published by Asia Society's Center on U.S.-China Relations .Find China News, Analysis, Culture, Environment, Media on this website 
### What content should be included?
* A feed for all articles.
* Feeds for every category appears in the header.
### Additional description
It provides a feed for all articles in that site: http://www.chinafile.com/feeds.xml. But it doesn't have full-text output. In addition, no categorized feed is given.

**Comment by yefoenix** [comment]
RSSHub 暂不接受已有官方 Feed 的获取全文的issue，如有能力可自行编写路由进行pr.
或者更简单的方式是把抓取全文的工作交给阅读器。

**Comment by oppilate** [comment]
Sure. Just list it here. I'll make a pr later,
