### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Light--** [DIYgod/RSSHub#5161]
- Involved route
    `/zhihu/people/posts/mikeyuan`
- What is expected
get rss feed news
- What is actually happening
invalid rss feed
- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- Additional info (logs errors etc)
```
    Response code 403 (Forbidden)
```

**Comment by HenryQW** [comment]
Due to the anti-crawling of certain source website, some RSS of the demo will return status code 403. This is not an issue caused by RSSHub and please do not report it.

提交 issue 的时候请仔细查看说明。
