### ISSUE TITLE
哔嘀影视 bde4

### ISSUE THREAD

**Issue by shaonwu** [DIYgod/RSSHub#5181]
### 网站地址

https://bde4.cc

### 网站描述

哔嘀影视，热门影视剧下载站

### 需要生成什么内容？

网站上影视剧的种子列表或下载地址（磁力链接、电驴链接）

### 额外描述

最好能按照网站左侧标签提供的影视类型（新电影、新剧集、国产剧、港台剧、动漫剧、欧美剧、日韩剧等）进行细分；

RSSHub 上提供的支持 BT 下载的 mp4ba 网站已经停止更新一个多月了，原因不详，不知道何时会恢复更新，希望有这么一个支持 BT 下载的影视剧网站。

**Comment by nhmtusr** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
迟短聊和抠遣黑赴痉啦吠瘫队狭纺泌刈绽何托

**Comment by CasperYC** [comment]
Any new links?
