### ISSUE TITLE
可有vercel安装步骤?

### ISSUE THREAD

**Issue by q409640976** [DIYgod/RSSHub#5191]
在vercel安装失败

**Comment by Apocalypsor** [comment]
这个我会
fork本项目，然后直接在vercel去import就完事了，其他的配置用环境变量添加

**Comment by q409640976** [comment]
哥们，方便不方便加个qq，409640946教教我，非常感谢

**Comment by q409640976** [comment]
> 这个我会
> fork本项目，然后直接在vercel去import就完事了，其他的配置用环境变量添加

哥们，方便不方便加个qq，409640946教教我，非常感谢

**Comment by Apocalypsor** [comment]
> > 这个我会
> > fork本项目，然后直接在vercel去import就完事了，其他的配置用环境变量添加
> 
> 哥们，方便不方便加个qq，409640946教教我，非常感谢

nop
tg可以，同名
