### ISSUE TITLE
twitter配置.env的问题：报错 Twitter RSS is disabled due to the lack of relevant config

### ISSUE THREAD

**Issue by Rixcloudllnll** [DIYgod/RSSHub#5234]
- 路由地址
/twitter/user/id
- 预期是什么
正常工作
- 实际发生了什么
反馈Twitter RSS is disabled due to the lack of relevant config
- 部署相关信息

自建RSSHub，其他路由正常工作。已申请到了：
1、API key 
2、API secret key  
3、Access token 
4、Access token secret 
5、Bearer token

按照[文档](https://docs.rsshub.app/install/#%E9%83%A8%E5%88%86-rss-%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE)
```
TWITTER_CONSUMER_KEY: Twitter Consumer Key，支持多个 key，用英文逗号 , 隔开

TWITTER_CONSUMER_SECRET: Twitter Consumer Secret，支持多个 key，用英文逗号 , 隔开，顺序与 key 对应

TWITTER_TOKEN_{id}: 对应 id 的 Twitter token，{id} 替换为 id，值为 consumer_key consumer_secret access_token access_token_secret 用逗号隔开，即：{consumer_key},{consumer_secret},{access_token},{access_token_secret}
```
我生成了/RSSHub/.env文件
```
TWITTER_CONSUMER_KEY=1
TWITTER_CONSUMER_SECRET=2
TWITTER_TOKEN_id=1,2,3,4
```
其中1，2，3，4对应值见已申请部分，id为3中-前面的数字。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
之前试过把id设置成我的账户@后面的字符，但同样报错。后来看到[https://github.com/DIYgod/RSSHub/issues/2731](https://github.com/DIYgod/RSSHub/issues/2731)改成了3中-前面的数字。

/RSSHub/lib/config.js 中带有twitter的部分
```
    const twitter_tokens = {};

} else if (name.startsWith('TWITTER_TOKEN_')) {
            const id = name.slice(14);
            twitter_tokens[id] = envs[name];

        twitter: {
            consumer_key: envs.TWITTER_CONSUMER_KEY,
            consumer_secret: envs.TWITTER_CONSUMER_SECRET,
            tokens: twitter_tokens,
        },
```

**Comment by a08381** [comment]
你的小作文是怎么写的？我的推特api申请怎么被拒绝了？

**Comment by hotsymbol** [comment]
好麻烦，为什么不能直接抓取，需要申请api

**Comment by simoin** [comment]
@a08381 地区可以选hk，use case 选个人用，其他都关了，申请就写学习用。

@Rixcloudllnll `Twitter RSS is disabled due to the lack of relevant config` 这个错误应该是没读到 .env。如果系统是windows的话，可能是隐藏了扩展名后缀导致的
