### ISSUE TITLE
国家统计局-最新发布页面 路由请求

### ISSUE THREAD

**Issue by WPSG** [DIYgod/RSSHub#5236]
### 网站地址
[国家统计局-最新发布](http://www.stats.gov.cn/tjsj/zxfb/)
### 网站描述
国家统计局发布的最新统计数据信息
### 需要生成什么内容？
最新发布的文章内容

**Comment by MisteryMonster** [comment]
http://www.stats.gov.cn/tjsj/zxfb/rss.xml
