### ISSUE TITLE
昨日汇率变动数据问题

### ISSUE THREAD

**Issue by Caelestrasz** [DIYgod/RSSHub#5239]
- 路由地址
/transferwise/pair/:source/:target

- 预期是什么
![0724-08 54 44](https://user-images.githubusercontent.com/25895906/88352144-5c3ef700-cd8b-11ea-9572-c3bc28b5aa0b.png)

- 实际发生了什么
![0724-08 51 10](https://user-images.githubusercontent.com/25895906/88352016-dd49be80-cd8a-11ea-9fc1-d7e4fb3e92ed.png)

@HenryQW

**Comment by HenryQW** [comment]
数据没有错，汇市是二十四小时的，每天第一次更新今日价格时 TW 会更新昨天价格，导致昨天看到的“今日价格”和今天看到的“昨日价格”不一致。

今日价格的数据也是波动的，获取数据的时间也影响到生成的内容。![image](https://user-images.githubusercontent.com/5896343/88354928-790f0680-cd5a-11ea-8d57-07a699cf80f8.jpeg)![image](https://user-images.githubusercontent.com/5896343/88354930-7b716080-cd5a-11ea-9544-487f4c017112.jpeg)

**Comment by Caelestrasz** [comment]
啊不好意思再傻一下，24小时变动我懂，但过了那一天之后不应该会停在一个值上吗，收盘价？因为仔细看了一下每天的第一个数值我都能在TW图上找到对应的历史数据，所以1.27155、1.2726这些值到底是什么时间点的？

而且好反直觉，昨天23号明明看图美元兑人民币是上涨，消息却告诉我下跌😂

**Comment by HenryQW** [comment]
我有空看看，可能返回的数据顺序变化了
