### ISSUE TITLE
每日生猪价格更新问题

### ISSUE THREAD

**Issue by Caelestrasz** [DIYgod/RSSHub#5240]
**- 路由地址**
/pork-price

**- 预期是什么**
每日只抓取一次

**- 实际发生了什么**
重复抓取了一次前天数据当作昨日数据
![0724-09 01 36](https://user-images.githubusercontent.com/25895906/88352479-76c5a000-cd8c-11ea-863f-6382c76c1557.png)

@importcjj

**Comment by MisteryMonster** [comment]
阅读器的问题吧，你可以把阅读器获取订阅的间隔为每日，然后rsshub输出加上参数`limit=1`就可以了。

**Comment by Caelestrasz** [comment]
我用的inoreader，没法设置这个订阅间隔😨
