### ISSUE TITLE
IT之家改版，路由地址失效

### ISSUE THREAD

**Issue by tastypear** [DIYgod/RSSHub#5244]
路由：/ithome/ranking/:type
问题：IT之家改版，该路由失效

**Comment by mashirozx** [comment]
@luyuhuang
@immmortal
艾特一下路由作者大佬

**Comment by luyuhuang** [comment]
已提 pr. 注意原来的 1, 2, 3, 4 被改成了 `24h`, `7days` 和 `monthly`.

| 24h           | 7days    | monthly |
| ------------- | -------- | ------- |
| 24 小时阅读榜 | 7 天最热 | 月榜    |
