### ISSUE TITLE
财联社电报和深度rss通过部署后通过127.0.0.1:1200访问仍然不成功,是否rss源失效?

### ISSUE THREAD

**Issue by flowerhood** [DIYgod/RSSHub#5246]
![abc](https://user-images.githubusercontent.com/59557764/88375960-1e63c200-cdcf-11ea-9687-4dada9502b60.png)

**Comment by MisteryMonster** [comment]
路由是好的。提交 issue 的时候请按照格式。

**Comment by flowerhood** [comment]
> 路由是好的。提交 issue 的时候请按照格式。

你好,现在确实可以访问了,抱歉,还有个问题向您请教下,本地地址http://127.0.0.1:1200/cls/telegraph可以访问,但是无法将这个地址导入到inoreader阅读器解析,只能打开源码,有什么其他工具可以解析本地的rss源文件吗?

**Comment by MisteryMonster** [comment]
127.0.0.1 是本地保留IP，公网无法直接访问,你可以搜索端口映射把本地的 rsshub 服务暴露到公网。但是直接用 [https://rsshub-diygod.now.sh/cls/telegraph](https://rsshub-diygod.now.sh/cls/telegraph) 更方便。

________________________________

**Comment by flowerhood** [comment]
> 127.0.0.1 是本地保留IP，公网无法直接访问,你可以搜索端口映射把本地的 rsshub 服务暴露到公网。但是直接用 https://rsshub-diygod.now.sh/cls/telegraph 更方便。
你好,谢谢,可以访问了,之前微信公众号外接大脑来源可以通过127.0.0.1:1200访问和外网rss访问,现在两者都失效了,是否http://www.waijiedanao.com/官网已经作了严格的反扒限制,有一个多星期已经无法访问了
