### ISSUE TITLE
Bilibili 用户追番列表 出错

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#5248]
- 路由地址

https://rsshub.app/bilibili/user/bangumi/208259

- 预期是什么

- 实际发生了什么

- 部署相关信息

- 额外信息（日志、报错等）

![image](https://user-images.githubusercontent.com/22500116/88419468-d917b280-ce17-11ea-846e-b3c5c7ec4ae8.png)

**Comment by JokeNeverSoke** [comment]
出现同样错误
