### ISSUE TITLE
IT之家热榜挂了

### ISSUE THREAD

**Issue by mashirozx** [DIYgod/RSSHub#5261]
- 路由地址
https://rsshub.app/ithome/ranking/1

- 预期是什么

- 实际发生了什么
![Screenshot_2020-07-26-19-27-44-587_com android chrome](https://user-images.githubusercontent.com/16148054/88477889-4c373b00-cf76-11ea-930f-82c615ab2065.jpg)

- 部署相关信息
rsshub.app

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by mashirozx** [comment]
@immmortal 艾特大佬，IT之家页面改版了

**Comment by luyuhuang** [comment]
已提 pr. 注意原来的 1, 2, 3, 4 被改成了 `24h`, `7days` 和 `monthly`.

| 24h           | 7days    | monthly |
| ------------- | -------- | ------- |
| 24 小时阅读榜 | 7 天最热 | 月榜    |

**Comment by mashirozx** [comment]
@luyuhuang 好像24h热榜又挂了😂

**Comment by luyuhuang** [comment]
#5271 这个 pr 把我的代码改回去了... @sabuaka18 @HenryQW @DIYgod

**Comment by prnake** [comment]
@luyuhuang 最近pr比较乱，估计误删了一些代码😂

**Comment by HenryQW** [comment]
我的锅，堆积的 PR 太多了开了好多个 tab，估计是点错了。。。

**Comment by mashirozx** [comment]
@luyuhuang hi，热榜标题乱码了~

**Comment by luyuhuang** [comment]
> @luyuhuang hi，热榜标题乱码了~

它们又改编码了, 之前是 gb2312, 现在又改回 uft-8 了. 你可以开一个 issue
