### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zwb124** [DIYgod/RSSHub#5273]
- Involved route
    `/tophub/Om4ejxvxEN`
- What is expected

- What is actually happening

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- Additional info (logs errors etc)
```
    connect ETIMEDOUT 101.32.29.92:443
```

**Comment by HenryQW** [comment]
测试过了，原站反爬措施导致，自建可以解决这个问题。

![Uploading image.png…]()
