### ISSUE TITLE
需要实现.json功能

### ISSUE THREAD

**Issue by vicdorke** [DIYgod/RSSHub#5293]
### 这是一个什么样的功能？
需要实现.json功能
### 这个功能可以解决什么问题？
我准备架设一个长毛象实例，通过rsshub抓取twitter，instagram的内容，创建镜像账号，rss格式转换太麻烦了。可是rsshub之前移除了这个功能，希望能有一个变量，可以控制生成.json文件的开关。

**Comment by HenryQW** [comment]
之前的 JSON 滥用太多，不考虑支持了。可以自己造轮子，不难。

**Comment by vicdorke** [comment]
我把设置改回去了，🙂。

**Comment by vicdorke** [comment]
欢迎大家一起来爬我的json数据https://rsshub985.herokuapp.com/

**Comment by datatube-owner** [comment]
https://datatube.dev/ 另一个支持 JSON 输出的节点
