### ISSUE TITLE
路由： 微信公众号 （外接大脑） 失效，求修复

### ISSUE THREAD

**Issue by gerrampard** [DIYgod/RSSHub#5296]
公众号 (外接大脑来源)

作者: @BugWriter2 
举例: https://rsshub.app/wechat/wjdn/5d5e683c82339df472988f59
路由: /wechat/wjdn/:id

7月29日还可以，30日失效了。

**Comment by HenryQW** [comment]
原站的SSL证书过期了，与RSSHub无关。

**Comment by cryzlasm** [comment]
> 原站的SSL证书过期了，与RSSHub无关。

那如何跳过这个SSL证书警告呢?
