### ISSUE TITLE
申请为BBC中文版里的科技健康频道制作RSS源

### ISSUE THREAD

**Issue by WoodC2011** [DIYgod/RSSHub#5302]
网站地址
https://www.bbc.com/zhongwen/simp/science
网站描述
BBC中文版的子频道名称有更新，之前的部分RSS不能用我试过

需要生成什么内容？

公告的标题
公告的时间
公告的内容

**Comment by HenryQW** [comment]
[官方 RSS](https://www.bbc.com/zhongwen/simp/services/2009/09/000000_rss) 没有更新该频道，无法支持。
已添加其他子频道的支持。
