### ISSUE TITLE
Short video support for Bilibili dynamic feeds

### ISSUE THREAD

**Issue by ericworks** [DIYgod/RSSHub#5306]
- Involved route
  
  Bilibili user dynamic at https://rsshub.app/bilibili/user/dynamic/

- What is expected

  Bilibili users can now publish short videos in their posts. The user dynamic feed will report `TypeError` if a user published a short video recently. 

- What is actually happening

  ```
  TypeError: Cannot convert object to primitive value
    at getImgs (/data/wwwroot/do02.rsshub.app/lib/routes/bilibili/dynamic.js:111:47)
    at /data/wwwroot/do02.rsshub.app/lib/routes/bilibili/dynamic.js:120:24
    at Array.map ()
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/bilibili/dynamic.js:84:20)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  ```

  The JSON object structure has changed (a new post format not supported by previous feed script) , which can lead to a fatal crash if a user recently published any short videos.  
  e.g. (https://rsshub.app/bilibili/user/dynamic/14837663) This feed will not work since the `item.data` for short video is actually a JSON object, rather than image url.

- Self-deployment information

  It could be reproduced on any platform.

- Additional info (logs errors etc)

**Comment by HenryQW** [comment]
#5307 closes this.
