### ISSUE TITLE
微博长文经常显示不全

### ISSUE THREAD

**Issue by Mordiggian** [DIYgod/RSSHub#5308]
- 路由地址
微博

- 预期是什么
微博长文能完全显示

- 实际发生了什么
有的长文能完全显示，有的并不能：
https://weibo.com/6526109246/JdIYqdYSK
https://weibo.com/6526109246/JdJRl7YSI
同一个博主的微博，第一条长文就可以全文显示，但第二条就不行，第一条字数还要多一些......

![chrome_CrBEkrCTfK](https://user-images.githubusercontent.com/9401088/89026295-081fae00-d35b-11ea-815e-a88af407b02c.png)

![chrome_U478C69QOp](https://user-images.githubusercontent.com/9401088/89026270-f938fb80-d35a-11ea-9535-3ed7bda0827c.png)

- 部署相关信息
自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   centos 7.3            |
| Node version       |    node13.13.0           |
| if Docker, version |         no      |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
麻烦提供路由地址

**Comment by Mordiggian** [comment]
> 麻烦提供路由地址

/weibo/user

**Comment by HenryQW** [comment]
请提供完整路由地址，包括微博号

**Comment by Mordiggian** [comment]
> 请提供完整路由地址，包括微博号

/weibo/user/6526109246

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/95656612-7aed9800-0b07-11eb-9f9b-0c0b7e1503ae.png)
微博都是官方接口统一返回的，如果没有全文，RSSHub也无能为力。
