### ISSUE TITLE
掘金-沸点RSS订阅链接失效

### ISSUE THREAD

**Issue by 2PoL** [DIYgod/RSSHub#5309]
沸点
作者: @xyqfer
举例: https://rsshub.app/juejin/pins
路由: /juejin/pins
出现错误：
**无法从指定的网址下载:HTTP/1.1 404 Not Found**

**Comment by HenryQW** [comment]
应该是掘金的 graphql 参数改动了，凉凉看一下@xyqfer？

**Comment by xyqfer** [comment]
果然大改了接口，丢掉 graphql 了。。。
