### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ggwazh** [DIYgod/RSSHub#5320]
- 完整路由地址，包含所有必选与可选参数
    `/t66y/25`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 403 (Forbidden)
```

**Comment by monsterxcn** [comment]
返回 403 Forbidden 而且文档中写了该接口 **反爬严格** ，所以只是预料之中的。还是考虑自建接口吧，我这边自建接口返回正常。

另外你提 issue 之前没有读文档吧，[常见问题](https://docs.rsshub.app/faq.html) 已经说明了：

> Q: 演示地址可以用么？
> 
> A: 演示地址为 rsshub.app , 缓存时间 20 分钟，可以随意使用。但如果你看到路由有 **反爬严格** 标记，如微博、知乎等，意味着目标网站有严重的反爬策略，demo 无法确保可用性，建议自建来提高稳定性。

**Comment by murphysking** [comment]
自建现在也不稳定了,我自建也就5天，就我自己用，也被屏蔽了
