### ISSUE TITLE
希望可以增加对 wxnmh.com 的 rss 支持

### ISSUE THREAD

**Issue by ArsenicX** [DIYgod/RSSHub#5324]
### 网站地址
官网：https://www.wxnmh.com/
随便举例的公众号页面：https://www.wxnmh.com/user-7.htm

### 网站描述
一个微信公众号搜录的网站

### 需要生成什么内容？
相关公众号的文章

### 额外描述
无

**Comment by lessmoe** [comment]
这网站咋区分公众号？

**Comment by ArsenicX** [comment]
> 这网站咋区分公众号？

貌似是数字代码，https://www.wxnmh.com/user-7.htm里面的 7 代表「人民日报」，换成 61 就是「科技每日推送」

**Comment by luokai2000** [comment]
这个由路由了么？？
