### ISSUE TITLE
希望能支持 西瓜视频 ixigua.com 的RSS，才发现这个视频网站资源好丰富啊~

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#5326]
### 网站地址
https://www.ixigua.com/
### 网站描述
是字节跳动旗下的一个视频网站，很大，资源很丰富。
### 需要生成什么内容？
- 主页的频道分类RSS，例如“电影”、“电视剧”、“影视”、“游戏”、“音乐”、“农人”等十几个分类
- 视频上传者的分类RSS。例如 https://www.ixigua.com/home/2334957050792539 ， 他下面的“最新”、“热门”、“ta的小视频”等分类
### 额外描述
哎呀， @hoilc 老哥，近期有空吗……  ^_^

也欢迎其他有空的老哥来弄一下啊。

先谢过啦。

**Comment by raybateman-sys** [comment]
支持，希望能添加西瓜视频RSS~

**Comment by SettingDust** [comment]
作者视频：https://www.ixigua.com/api/videov2/author/video?author_id=2334957050792539&type=video

> 主页的频道分类RSS，例如“电影”、“电视剧”、“影视”、“游戏”、“音乐”、“农人”等十几个分类
基本无意义
