### ISSUE TITLE
[BUG]掘金无法访问

### ISSUE THREAD

**Issue by gd4Ark** [DIYgod/RSSHub#5332]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/juejin/category/frontend
- 预期是什么
正常访问
- 实际发生了什么
无法访问
![image](https://user-images.githubusercontent.com/27952659/89115216-4f6f8100-d4b8-11ea-9b62-69121fcf7fe1.png)

**Comment by HenryQW** [comment]
应该是掘金 API 改动所致 @xyqfer

**Comment by xyqfer** [comment]
是的，貌似全都改了。。= =
