### ISSUE TITLE
discuz 缺少对应论坛的cookie.

### ISSUE THREAD

**Issue by mikudate** [DIYgod/RSSHub#5333]
配置
CACHE_TYPE=redis
CACHE_EXPIRE=600
DISCUZ_COOKIE_01= 复制过来的完整cookie
报错提示Error: 缺少对应论坛的cookie.
#4557 的已经解决了，但我这边全部网站依旧都没无法生效
https://bbs.yamibo.com/forum-30-1.html
https://bbs.kafan.cn/forum-4-1.html
https://www.saraba1st.com/2b/forum-75-1.html
是bug还是我没配置好？@junfengP

**Comment by junfengP** [comment]
你调用的路由是什么？配置的COOKIE_{ID} 需要和路由上调用的ID配对

**Comment by mikudate** [comment]
> 你调用的路由是什么？配置的COOKIE_{ID} 需要和路由上调用的ID配对

路由http://127.0.0.1:1200/discuz/x/01/该页面
配置DISCUZ_COOKIE_01=该页面cookie

**Comment by junfengP** [comment]
我这本地测试正常
路由地址： `/discuz/x/01/https%3A%2F%2Fbbs.kafan.cn%2Fforum-4-1.html`
配置文件：`DISCUZ_COOKIE_01=XXXXXXXXXXXXXXXXXXXXXX`
![image](https://user-images.githubusercontent.com/15406392/89120057-8a3bde00-d4e5-11ea-9304-542037bd2288.png)

**Comment by mikudate** [comment]
> 我这本地测试正常
> 路由地址： `/discuz/x/01/https%3A%2F%2Fbbs.kafan.cn%2Fforum-4-1.html`
> 配置文件：`DISCUZ_COOKIE_01=XXXXXXXXXXXXXXXXXXXXXX`
> ![image](https://user-images.githubusercontent.com/15406392/89120057-8a3bde00-d4e5-11ea-9304-542037bd2288.png)

糊涂了，kafan的cookie好像是可以直接用，重试后正常打开了

saraba1st的不能直接复制，头部多一段_uab_collina，去掉后正常打开

yamibo的请求有段__cfduid=; 试了半天无解，不知道能绕过去吗？

**Comment by mikudate** [comment]
DISCUZ_COOKIE_{ID}   
设置id生效后再修改需要重启。
重启后基本都能打开了。
