### ISSUE TITLE
希望增加贴吧用户的更新动态订阅

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#5343]
### 网站地址
https://tieba.baidu.com/
用户页面比如：https://tieba.baidu.com/home/main?un=%E5%85%B3%E6%B3%A8%E6%9C%8B%E6%9C%8B
### 网站描述
贴吧用户主页动态
### 需要生成什么内容？
贴吧用户动态更新

**Comment by kunpeng9** [comment]
还是别想这个了，以前起过和你一样的念头。建议：趁早！ 越早跑路越好，早点放弃贴吧。
![image](https://user-images.githubusercontent.com/44609485/89651315-54886200-d8f6-11ea-8a39-acf1ee294fd0.png)
看看这个反馈网页。希望贴吧早点凉。百度早点倒闭。

**Comment by ZhuningS** [comment]
其实还可以吧，百度公司不好，贴吧的很多用户还是不错的。
