### ISSUE TITLE
bug 河北移动贴吧导入失败

### ISSUE THREAD

**Issue by baizhi1989** [DIYgod/RSSHub#5345]
- 完整路由地址，包含所有必选与可选参数
导入地址 
https://rsshub.app/tieba/forum/河北移动
- 预期是什么
导入成功
- 实际发生了什么
导入失败
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        web       |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/89207317-73af8880-d5b2-11ea-888b-85fb0373082f.png)
我这边没有问题，URL 中的中文字符需要转义。

https://rsshub.app/tieba/forum/%E6%B2%B3%E5%8C%97%E7%A7%BB%E5%8A%A8

**Comment by baizhi1989** [comment]
谢谢🙊
