### ISSUE TITLE
199IT分类tag全文输出出错

### ISSUE THREAD

**Issue by Caelestrasz** [DIYgod/RSSHub#5346]
首先感谢大佬制作，但今天全文输出似乎出了点问题

- 完整路由地址，包含所有必选与可选参数
 @nczitzk

举例: https://rsshub.app/199it/category/199itdata

路由: /199it/category/:caty

参数:
caty, 必选 - 分类, 可在分类页 URL 中找到

分类为单一路径，如 http://www.199it.com/archives/category/199itdata 则路由为 /199it/category/199itdata.

分类包含多重路径，如 http://www.199it.com/archives/category/emerging/5g 则替换 / 为 |，即路由为 /199it/category/emerging|5g.

#标签
作者: @nczitzk

举例: https://rsshub.app/199it/tag/数据早报

路由: /199it/tag/:tag

参数:
tag, 必选 - 标签, 可在标签页 URL 中找到

- 预期是什么
图片和文章全文输出

- 实际发生了什么
![0803-21 48 20](https://user-images.githubusercontent.com/25895906/89190587-407df100-d5d4-11ea-97b5-bb415cd3dcad.png)
![0803-21 48 37](https://user-images.githubusercontent.com/25895906/89190599-4542a500-d5d4-11ea-9563-28c37149444c.png)

**Comment by HenryQW** [comment]
我测了一下本地没有问题，貌似是缓存出了问题。

![image](https://user-images.githubusercontent.com/5896343/89207183-42cf5380-d5b2-11ea-9660-859904e3285e.png)

**Comment by Caelestrasz** [comment]
那这个缓存有解决办法吗，因为现在每次也都是要等好一会儿它才会变成全文输出

**Comment by nczitzk** [comment]
看了一下可以正常全文输出。如果还发现有这种情况，建议自建服务试试呢。

![image](https://user-images.githubusercontent.com/42264778/89748484-0e99ec80-daf6-11ea-9080-1a2422233eae.png)

**Comment by Caelestrasz** [comment]
前面那几个没有，只有最后一个有
![0810-22 23 18](https://user-images.githubusercontent.com/25895906/89793244-3752ce00-db58-11ea-9fe8-a439d0dc44d1.png)

**Comment by nczitzk** [comment]
我收到提醒了。刚试了 rsshub.app 上该路由是存在文章丢失的情况 😭 正如 HenryQW 所述应该是缓存的问题。而自建服务可以稳定输出全文。
