### ISSUE TITLE
端传媒全文获取

### ISSUE THREAD

**Issue by NeverBehave** [DIYgod/RSSHub#5376]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/initium/feature/zh-hans

- 预期是什么

- 实际发生了什么

- 部署相关信息

- 额外信息（日志、报错等）

使用 [@chotamreaderbot](https://t.me/chotamreaderbot) 可以在 Instant view 内看到全文, 测试可用
测试链接 https://theinitium.com/article/20200807-mainland-coronavirus-medical-staff-ptsd/
生成链接 https://telegra.ph/%E9%9D%A0%E8%BF%91%E5%8C%BB%E9%99%A2%E5%8F%8C%E8%85%BF%E5%B0%B1%E6%AD%A2%E4%B8%8D%E4%BD%8F%E9%A2%A4%E6%8A%96%E4%B8%AD%E5%9B%BD%E5%8C%BB%E6%8A%A4%E7%96%AB%E6%83%85%E5%90%8E%E5%BF%83%E7%90%86%E5%8F%97%E5%88%9B%E8%B0%83%E6%9F%A5%E7%AB%AF%E4%BC%A0%E5%AA%92-Initium-Media-08-08

也许使用搜索引擎的UA可以获得全文, 如果有人可以确认的话

消息来源: https://www.zhihu.com/question/65080751/answer/1152190810

**Comment by NeverBehave** [comment]
https://webcache.googleusercontent.com/search?q=cache:TCstLX_D4UcJ:https://theinitium.com/article/20200807-mainland-coronavirus-medical-staff-ptsd/+&cd=1&hl=en&ct=clnk&gl=us&client=firefox-b-1-d

Google Cache可以获取到全文

**Comment by prnake** [comment]
Google Bot 的 User-Agent: 
`Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
直接请求新闻页面可以获取到繁体全文

**Comment by prnake** [comment]
@prnake 现在端传媒用api+token读的，可以增加网页读取的方法

**Comment by prnake** [comment]
curl获取简体测试成功：
```bash
curl 'https://theinitium.com/article/20200807-evening-brief/' \
        -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.92 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' \
        -H 'Accept-Language: zh-hans;q=0.9' \
        --compressed
```
大概需要在/lib/route/initium/full.js中加这么一段：
```javascript
if (data.paywall_enabled) {
            const google_bot_ua = 'Mozilla / 5.0(Linux; Android 6.0.1; Nexus 5X Build / MMB29P) AppleWebKit / 537.36(KHTML, like Gecko) Chrome / 80.0.3987.92 Mobile Safari / 537.36(compatible; Googlebot / 2.1; +http://www.google.com/bot.html)';
            const accept_language = language + ';q=0.9';
            const pay_part = await got({
                method: 'get',
                url: `https://theinitium.com/article/${slug}`,
                headers: {
                    'user-agent': google_bot_ua,
                    'accept-language': accept_language,
                },
            })
            const $ = cheerio.load(pay_part.body);
            const pay_content = $('div.paywall').html();
            if (pay_content) {
                content += pay_content;
            }
        }
```
但是我遇到了各种各样的问题，包括频率过快导致404错误、无法返回简体...
等一个有缘人来解决

**Comment by notofoe** [comment]
@prnake 

限制一次获取的数量应该就足够了，像这样：
```
const items = await Promise.all(
        articles
            .slice(0, 12)
            .map(async (item) => ({
                title: item.article.headline,
                description: await getFullText(item.article.slug),
                link: resolve_url('https://theinitium.com', item.article.url),
                pubDate: item.article.date,
            }))
    );
```

另外不知道为什么，每次获取时，这样的 log `info: Proxy for https://theinitium.com/article/20200807-technology-india-banned-china-app` 会出现两次。

**Comment by prnake** [comment]
解决了，感谢
