### ISSUE TITLE
百度指定帖子 RSS

### ISSUE THREAD

**Issue by stroop566** [DIYgod/RSSHub#538]
请问能否用RSSHub订阅 百度贴吧的某个指定帖子的更新，包括只看楼主。
比如：
只看楼主：https://tieba.baidu.com/p/5853240586?see_lz=1
不只看楼主：https://tieba.baidu.com/p/5853240586
谢谢了！
@u3u

**Comment by lengthmin** [comment]
![image](https://user-images.githubusercontent.com/13938334/44616675-b1fc8300-a886-11e8-8150-9c6af4bb0af3.png)
是这个功能吗？

**Comment by stroop566** [comment]
yes，just close it.
