### ISSUE TITLE
RSSBud | iOS 平台的 RSSHub Radar

### ISSUE THREAD

**Issue by Cay-Zhang** [DIYgod/RSSHub#5395]
[RSSBud](https://github.com/Cay-Zhang/RSSBud) 是 **Apple 生态** 中 [RSSHub](https://github.com/DIYgod/RSSHub) 的辅助 App。和 [RSSHub Radar](https://github.com/DIYgod/RSSHub-Radar) 类似，他可以帮助你快速发现和订阅网站的 RSS。

🚧 该项目目前处于初期开发阶段，但基础功能已经可用。

[Telegram 群](https://t.me/RSSBud_Discussion) | [Telegram 频道](https://t.me/RSSBud)

<img src="https://github.com/Cay-Zhang/RSSBud/blob/main/Readme%20Assets/RSSBud.jpg?raw=true" align=center width="375" align=center>

**Comment by DIYgod** [comment]
TODO：加个 Related Projects

**Comment by HenryQW** [comment]
可以自行在 doc PR 相关项目😉
