### ISSUE TITLE
掘金节点挂了很久了，是否会修复。

### ISSUE THREAD

**Issue by hzlzh** [DIYgod/RSSHub#5402]
掘金节点挂了很久了，是否会修复。
https://rsshub.app/juejin/trending/ios/monthly

**Comment by xyqfer** [comment]
抱歉最近在找工作鸽的有点久 🌚

**Comment by hzlzh** [comment]
> 抱歉最近在找工作鸽的有点久 🌚
原来如此。对了要不要来微信

**Comment by HenryQW** [comment]
https://github.com/DIYgod/RSSHub/pull/5432
https://github.com/DIYgod/RSSHub/pull/5433
应该是修复了大部分了，还有哪部分没修复？

**Comment by xyqfer** [comment]
看起来只差分享了

**Comment by syfxlin** [comment]
> 看起来只差分享了

@xyqfer 【分享】和【专栏】合并成了【文章】，我觉得应该不用修复分享了吧 🤣

![image](https://user-images.githubusercontent.com/28844480/90596638-f0cd3580-e221-11ea-8d6a-09725ac8fe63.png)

**Comment by hzlzh** [comment]
https://timeline-merger-ms.juejin.im/v1/get_entry_by_rank?src=web&limit=10&category=all
这个接口也挂了，现在还有什么接口拉到文章？

**Comment by xyqfer** [comment]
> > 看起来只差分享了
> 
> @xyqfer 【分享】和【专栏】合并成了【文章】，我觉得应该不用修复分享了吧 🤣
> 
> ![image](https://user-images.githubusercontent.com/28844480/90596638-f0cd3580-e221-11ea-8d6a-09725ac8fe63.png)

话说我能理解成现在的【动态】等同于之前的【分享】吗 🤣

**Comment by xyqfer** [comment]
> https://timeline-merger-ms.juejin.im/v1/get_entry_by_rank?src=web&limit=10&category=all
> 这个接口也挂了，现在还有什么接口拉到文章？

如果说的是 trending 的话等这个 [PR](https://github.com/DIYgod/RSSHub/pull/5433/files) 合并了应该就可以了
