### ISSUE TITLE
半岛新闻网 不可用

### ISSUE THREAD

**Issue by lhy1024** [DIYgod/RSSHub#5413]
- The involved route, with all required and optional parameters
https://rsshub.app/aljazeera/news
- What is expected
成功订阅
- What is actually happening
![image](https://user-images.githubusercontent.com/19542290/90168241-658e1300-ddcf-11ea-833a-b5dba507e094.png)

**Comment by nczitzk** [comment]
这边试了一下可以正常工作

![image](https://user-images.githubusercontent.com/42264778/90197937-cdaa1c80-de02-11ea-8bbb-482cf6102878.png)

**Comment by lhy1024** [comment]
那可能是昨晚出了些问题 close了
