### ISSUE TITLE
海关总署不可用

### ISSUE THREAD

**Issue by lhy1024** [DIYgod/RSSHub#5414]
- The involved route, with all required and optional parameters
https://rsshub.app/gov/customs/list/paimai
- What is expected
成功订阅
- What is actually happening

![image](https://user-images.githubusercontent.com/19542290/90170965-5e690400-ddd3-11ea-8d63-0b18d3e4e077.png)

**Comment by HenryQW** [comment]
从海外访问 http://www.customs.gov.cn/customs/302249/2476857/302309/index.html 特别慢，导致超时。部署在境内会好一些。
