### ISSUE TITLE
西南交通大学交通运输与物流学院新闻公告

### ISSUE THREAD

**Issue by qizidog** [DIYgod/RSSHub#5431]
Website URL
https://ctt.swjtu.edu.cn/xwdt.htm

Website description
西南交通大学交通运输与物流学院新闻公告

What content should be included?
获取西南交通大学交通运输与物流学院新闻公告，方便获取最新通知

Additional description
这是我用feed43制作的订阅，但是不知道怎么引进到rssHub，所以，麻烦了！
https://feed43.com/4562875104314855.xml

**Comment by zoenglinghou** [comment]
我提了个pr，在等合并

其实我看你 feed43 做得挺好的，改一改就可以写出 RSSHub 路由来了😄️ 这个网页挺简单，我都是直接在文档的示例代码上随便改改。你有机会可以自己试一下😄️

**Comment by qizidog** [comment]
好的，第一次做，现在在学spring，日后有能力一定多多贡献。现在rsshub订阅要梯子，今天可把我折腾坏了😂

发自我的iPhone

**Comment by zoenglinghou** [comment]
要是你是专业的说不定将来写得比我还好😂️ 我就现学现卖而已（面向 stockoverflow 编程）

现在是 [rsshub.app](https://rsshub.app) 被 dns 污染了。最简单的方法除了梯子之外应该是用别的服务器，[这里](https://github.com/AboutRSS/ALL-about-RSS#rsshub) 列了几个第三方服务器。自建的话用国内云厂商在香港的服务器好像也不贵...

**Comment by qizidog** [comment]
我现在是读研期间自学转行😂 向前辈们看齐，早点休息，注意身体😎

发自我的iPhone
