### ISSUE TITLE
阿里云服务器安装rsshub后feed not found，如何解决？

### ISSUE THREAD

**Issue by tripolar2020** [DIYgod/RSSHub#5434]
aliyun ubuntu 16
install rsshub using docker ,  
安装后访问https://服务器地址：1200 可以显示welcome to rsshub 界面，按网上一些说明是安装好了

但同样的订阅源，放在rsshub.app之后就可以用，放在我自己的服务器地址后就feed not found
也就是把“rsshub.app”换成“服务器地址：1200”后就不可用

比如 https://rsshub.app/sciencemag/current/science  就可以
        https://服务器地址:1200/sciencemag/current/science   就找不到订阅源

请问如何解决？多谢

**Comment by junfengP** [comment]
https? 改成http试试

**Comment by zsbai** [comment]
去端口号

**Comment by HenryQW** [comment]
没有做反代的话需要加上端口号
https需要部署SSL证书

**Comment by WQ-Peng** [comment]
我试了下，将“https://rsshub.app”整体换成“服务器IP:1200”是ok的，带上“https://”就不行了

**Comment by HenryQW** [comment]
没有部署证书是不可能通过 https 访问的。。。只能通过 http 域名或者 IP 地址
