### ISSUE TITLE
知乎 - 话题 => 能不能一个问题在24小时内只出现一次？

### ISSUE THREAD

**Issue by honjiaxuan** [DIYgod/RSSHub#5442]
### 这是一个什么样的功能？
知乎的话题， https://docs.rsshub.app/social-media.html#zhi-hu-hua-ti
能不能同一个问题的不同回答，在24小时内只收到一次。

### 这个功能可以解决什么问题？
追踪了一个话题， 但是同一个话题下一天可能有五十个答案，全部都会在RSS里收到，太多了

**Comment by HenryQW** [comment]
这不就是话题的目的所在吗？
