### ISSUE TITLE
维基百科action=featuredfeed 中没有找到信息源。

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#5460]
- 完整路由地址，包含所有必选与可选参数
路由: /wikipedia/mainland
https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5
- 预期是什么
正常订阅
- 实际发生了什么
![image](https://user-images.githubusercontent.com/44609485/90589859-a93ead80-e211-11ea-8e77-8d69d1be223a.png)
点击插件弹出的那个订阅到ttrss之后出现=在 https://zh.wikipedia.org/w/api.php?action=featuredfeed 中没有找到信息源。
![image](https://user-images.githubusercontent.com/44609485/90590088-32ee7b00-e212-11ea-870d-2f91c9ce4e14.png)
插件弹出了5个，没有一个可以通过插件方便的订阅到ttrss，都是上面的那个错误提示。
https://zh.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom【这个feedformat=atom又是怎么回事，是atom编辑器才能订阅吗？通过里面的那个插件？以前想过通过atom订阅，后来没怎么用这个软件了。】
![image](https://user-images.githubusercontent.com/44609485/90590157-5dd8cf00-e212-11ea-926d-a27586c91988.png)

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by hoilc** [comment]
与RSSHub无关，右转 https://github.com/DIYgod/RSSHub-Radar

暂时手动订阅即可

**Comment by kunpeng9** [comment]
@HenryQW ,这个右转是指，到那边提交吗？好的，我去试下。
