### ISSUE TITLE
Support videos in picuki

### ISSUE THREAD

**Issue by lingnand** [DIYgod/RSSHub#5470]
### What feature is it?

Tried picuki as a replacement for the now defunct instagram RSS endpoints. It's pretty good! However... Videos don't seem to be displayed - although if I follow the link into picuki website I can see the videos just fine.

### What problem does this feature solve?

Adding video support to picuki.

**Comment by hoilc** [comment]
To avoid triggering the anti-crawler policy, the embedding video is disabled by default.
