### ISSUE TITLE
知乎热榜RSS延迟太多

### ISSUE THREAD

**Issue by auauauto** [DIYgod/RSSHub#5482]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/zhihu/hotlist
- 预期是什么
抓取最新的知乎热榜消息

- 实际发生了什么
[延迟太久了，抓取了八个月前的信息
![image](https://user-images.githubusercontent.com/67296564/90873810-4d228780-e3d1-11ea-832b-ab37a06d87d5.png)

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
需要更多数据, 目前看来没有问题
