### ISSUE TITLE
ニコニコchannel生放送的rss生成

### ISSUE THREAD

**Issue by Kennnnnnji** [DIYgod/RSSHub#5489]
### 这是一个什么样的功能？
抓取频道的生放送信息。

### 这个功能可以解决什么问题？
提醒观看下一次直播，避免错过。

### 额外描述
比如：https://ch.nicovideo.jp/yoshikiofficial/live 这个频道，可以抓取放送予定、過去の放送两部分内容。
RSSHub在这个页面上会有识别到：https://ch.nicovideo.jp/yoshikiofficial/live?rss=2.0 ，但是加入feedly订阅会失败。

**Comment by HenryQW** [comment]
这就是feedly的问题了
