### ISSUE TITLE
贴吧列表rss重复推送

### ISSUE THREAD

**Issue by LuzMasonj** [DIYgod/RSSHub#5505]
- 完整路由地址，包含所有必选与可选参数
举例: https://rsshub.app/tieba/forum/女图
路由: /tieba/forum/:kw
参数:kw, 必选 - 吧名

#

- 预期是什么
贴吧中用户按发贴时间推送rss
- 实际发生了什么
贴吧中各个贴子中有人回复时，rss会重复推送之前的贴子

**Comment by MisterGlasses** [comment]
@u3u 你好，请问贴吧列表重复推送是bug还是本意如此呀？可不可以按发贴顺序排列后每贴只推送一次呀？

**Comment by eret9616** [comment]
和楼煮有相同问题

**Comment by MisterGlasses** [comment]
> 和楼煮有相同问题 比如说用户在7号发了一个回复 ，然后在14号的另一个楼层发了一个回复， rsshub可以抓到14号有新动态，但是显示的是7号的回复

贴吧默认按回复排序 网页端甚至都不提供按发贴时间排序的选项 感觉解决的可能性不大
