### ISSUE TITLE
网易云电台的rss，部分播客软件无法订阅

### ISSUE THREAD

**Issue by niu541412** [DIYgod/RSSHub#551]
https://music.163.com/song/media/outer/url?id=${song_id}.mp3
网易云的这个接口不是实际的音频地址，会跳转。有些播客软件比如itunes，无法解析这种地址。会导致订阅后无条目显示。

比如下面的音频：
`var req = new XMLHttpRequest();`
`req.open('GET', 'http://music.163.com/song/media/outer/url?id=1301561546.mp3', false);`
`req.send(null);`
`req.getResponseHeader('location');`

输出的才是实际地址：
`http://m10.music.126.net/20180827205953/6eeee6927df63af7b6038aea783153a9/ymusic/85dc/7dbf/676d/61f3a501c149db1ad6d2cb74d437cb08.mp3`
感觉ios和mac上应该多数人用自带的itunes订阅播客，希望能有方法修复

**Comment by DIYgod** [comment]
实际地址是会变的，暂时没有什么办法

**Comment by lengthmin** [comment]
http://getpodcast.xyz

这里有个很棒的播客集合, 看下有没有需要的可以用一下

**Comment by lengthmin** [comment]
ios 播客测试可以播放。

可能是上个版本rsshub的网易云电台没有弄好，现在再试试呗

**Comment by lengthmin** [comment]
@magic-akari 要不用getpodcast的链接把这个issue先close掉？
