### ISSUE TITLE
酷安话题RSS推送的标题与作者颠倒

### ISSUE THREAD

**Issue by MisterGlasses** [DIYgod/RSSHub#5511]
- 完整路由地址，包含所有必选与可选参数
话题 - 图文 & 动态
作者: @xizeyoupan
举例: https://rsshub.app/coolapk/huati/酷安夜话
路由: /coolapk/huati/:tag
参数:tag, 必选 - 话题名称

#

- 预期是什么

- 实际发生了什么
酷安话题RSS推送的标题与作者颠倒
![D7308973-9EB2-405F-9237-1A16BF1366D4](https://user-images.githubusercontent.com/27768847/90983690-95dd6a80-e5a2-11ea-92c7-a136c28c0650.png)

**Comment by xizeyoupan** [comment]
众所周知，酷安的动态是没有标题的，所以每条动态的标题我都设为了“xxx的动态”，你有什么建议吗😃

**Comment by MisterGlasses** [comment]
> 众所周知，酷安的动态是没有标题的，所以每条动态的标题我都设为了“xxx的动态”，你有什么建议吗😃

原来是这样，主要是无法通过“xxx的动态”这种标题来判断推送内容是不是想看的。有没有可能把动态内容或部份动态内容作为标题？这样感觉不错，不知道实际怎么样？

**Comment by HenryQW** [comment]
直接用动态的前XX个字符吧
