### ISSUE TITLE
[BUG] Bilibili User Channel RSS return 412 code

### ISSUE THREAD

**Issue by kaizcn** [DIYgod/RSSHub#5512]
- 完整路由地址，包含所有必选与可选参数
    `bilibili/user/channel/54992199/82529`
- 预期是什么
    show user's channel video contents
- 实际发生了什么
   Response code 412 (Precondition Failed)

- 额外信息（日志、报错等）
```
    Response code 412 (Precondition Failed)
``` 
![image](https://user-images.githubusercontent.com/68529721/91014689-b4416700-e59e-11ea-8320-328898a9116a.png)

**Comment by tgly307** [comment]
demo被B站反爬了，自建没问题
