### ISSUE TITLE
请问怎样查看语雀的ID呢？

### ISSUE THREAD

**Issue by ma3252788** [DIYgod/RSSHub#5515]
### What feature is it?
获取语雀ID
### What problem does this feature solve?
抱歉没有看懂文档，不明白`/api/books/${repo_id}/docs`请求怎样看

**Comment by HenryQW** [comment]
好像网站改版了，ID的确不容易找了。看[语雀文档](https://www.yuque.com/yuque/developer/repo#4a6c3a3b)应该是可以通过 repo/book 来获取了，需要略微改动一下相关路由逻辑

**Comment by ma3252788** [comment]
> 好像网站改版了，ID的确不容易找了。看[语雀文档](https://www.yuque.com/yuque/developer/repo#4a6c3a3b)应该是可以通过 repo/book 来获取了，需要略微改动一下相关路由逻辑。
> 
> ![image](https://user-images.githubusercontent.com/5896343/91043746-0b315580-e60c-11ea-9ce4-87a0a8e3ee71.png)

您好，谢谢您的回复。我按照上面的指点，试着找了一下，[https://g.yuque.com/fly51fly](https://g.yuque.com/fly51fly)这是目标网页，我在控制台没有找到book/id，然后我打开页面源码，也没有发现book/id在哪里，请问是不是我找错了，还是说只有专栏可以？

**Comment by HenryQW** [comment]
语雀的文档我真是理解不能，结构没看错的话，应该是 user/repo/doc。专栏只是这个book的名字，book对应的应该是repo？
book ID 的确不太好找，console搜索到的 `enable_catalog_nodes%22%3Atrue%2C%22id%22%3A【266412】%2C%22space_id`，`enable_catalog_nodes`后的`id`值

相关路由应该通过语雀API获取对应id

`GET /repos/fly51fly/gvl1ma`

**Comment by kunpeng9** [comment]
语雀真不好订阅，好久之前就不能用了，用了一阵就红了，不能更新，最近干脆是直接就不能用了。

**Comment by ma3252788** [comment]
> 语雀的文档我真是理解不能，结构没看错的话，应该是 user/repo/doc。专栏只是这个book的名字，book对应的应该是repo？
> book ID 的确不太好找，console搜索到的 `enable_catalog_nodes%22%3Atrue%2C%22id%22%3A【266412】%2C%22space_id`，`enable_catalog_nodes`后的`id`值
> 
> 相关路由应该通过语雀API获取对应id
> 
> `GET /repos/fly51fly/gvl1ma`

好的，谢谢，我试试~

**Comment by ma3252788** [comment]
> 语雀真不好订阅，好久之前就不能用了，用了一阵就红了，不能更新，最近干脆是直接就不能用了。

我试试，要是不稳定就不用啦~~

**Comment by cye18** [comment]
最近也想订阅一个语雀的专栏，想问一下这个id后来有没有找到？稳定吗？谢谢🙏

**Comment by AbyssiniaCat** [comment]
当前能订阅的单位是 知识库，network-Fetch/XHR 内的bookid就是
