### ISSUE TITLE
Proposal about subscribe RSS in Discord channels

### ISSUE THREAD

**Issue by jerryblues** [DIYgod/RSSHub#5536]
### Website URL
some channels in https://discord.com/,
such as:
https://discord.com/channels/578361075439894530/578721995202625557

### Website description
a space where people can publish message or chat with friends.

### What content should be included?
title, content, picture, link

**Comment by HenryQW** [comment]
Nice suggestion.

However I think the RSS will explode if the channel is popular.

**Comment by searchableguy** [comment]
I think the problem of the explosion can be solved through grouping pieces of conversation into threads and some filtering using text classification. You could for example get all the links posted in a channel instead of messages. That would limit the items in a feed a lot. There are a lot of things we can do here. 

I could work on this if no one else is up.

**Comment by jerryblues** [comment]
> I think the problem of the explosion can be solved through grouping pieces of conversation into threads and some filtering using text classification. You could for example get all the links posted in a channel instead of messages. That would limit the items in a feed a lot. There are a lot of things we can do here. 
> 
> I could work on this if no one else is up.

May I know if there is some progress?

**Comment by HenryQW** [comment]
> > I think the problem of the explosion can be solved through grouping pieces of conversation into threads and some filtering using text classification. You could for example get all the links posted in a channel instead of messages. That would limit the items in a feed a lot. There are a lot of things we can do here. 
> > 
> > I could work on this if no one else is up.
> 
> May I know if there is some progress?

Don't think so.
