### ISSUE TITLE
[BUG]新榜公众号抓取挂了

### ISSUE THREAD

**Issue by Cyberpuncrush** [DIYgod/RSSHub#5538]
- 完整路由地址，包含所有必选与可选参数
/newrank/wechat/mrscience100

- 预期是什么
正确抓取公众号内容

- 实际发生了什么
持续两天无法抓取并报错，在服务器和本地都报错，且错误类型不同于之前出现过的token限制错误：
Response code 500 (Internal Server Error): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

如果您认为 RSSHub 导致了该错误，请在 GitHub 报告。

If you believe this is an error caused by RSSHub, please report me on GitHub

- 部署相关信息
服务器和本地部署均报错，rsshub最新版本

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
Response code 500 (Internal Server Error): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

如果您认为 RSSHub 导致了该错误，请在 GitHub 报告。

If you believe this is an error caused by RSSHub, please report me on GitHub

**Comment by lessmoe** [comment]
新榜登录用验证码了，我改下登录方式

**Comment by lessmoe** [comment]
好烦(┬＿┬)

**Comment by Cyberpuncrush** [comment]
> 好烦(┬＿┬)

是不是被新榜盯上了🙏🏻
