### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by flowerhood** [DIYgod/RSSHub#5548]
- 完整路由地址，包含所有必选与可选参数
    `127.0.0.1:1200/newrank/wechat/sybgkp888`
- 预期是什么
能正常访问rss源程序爬取的rss地址
- 实际发生了什么
从前天开始,已经无法访问,出现500返回错误
- 部署相关信息
手动部署,通过npm start手工启动本地模式,已在.env正常部署用户名和密码2个变量,之前应用正常

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v14.4.0     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 500 (Internal Server Error): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
```

**Comment by HenryQW** [comment]
重复 #5538
