### ISSUE TITLE
希望优先使用 WebP 格式的图片

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#555]
```
https://pbs.twimg.com/media/$1?format=webp
```

**Comment by ypocc** [comment]
我要关掉这个 issue 了。

提 issue 的时候没有意识到阅读器的安全机制暂时还不支持新的 HTML 标签和属性。

等哪个阅读器支持了，再重新打开它吧。

**Comment by HenryQW** [comment]
@ypocc /jike/dev 已经加入了 WebP 支持，#697 也是，with fallback to JPEG。我测试过在 chrome 中打开的 web rss 阅读器中会有效果。

**Comment by ypocc** [comment]
[Feedbro](https://chrome.google.com/webstore/detail/mefgmmbdailogpfhfblcnnjfmnpnmdfa) 证实可行。

![screenshot](https://user-images.githubusercontent.com/41885716/45597508-650f5680-b9c5-11e8-82f5-8620f7a0f89e.png)

@HenryQW 可以介绍下你测试的 web rss 阅读器吗。Feedbro 不过滤属性（虽然什么都没发生），我不敢用它。

**Comment by lengthmin** [comment]
@ypocc henry用的貌似是自己搭的ttrss配上fever插件 ios用reeder

**Comment by HenryQW** [comment]
@ypocc #697 应该已经解决了这个问题。
@DIYgod pls close this.

**Comment by DIYgod** [comment]
@HenryQW Twitter 还没改 WebP

**Comment by HenryQW** [comment]
https://github.com/DIYgod/RSSHub/pull/697#discussion_r217677352
![image](https://user-images.githubusercontent.com/5896343/45663666-92f8b600-baff-11e8-8c52-ff84d5716880.png)

**Comment by ypocc** [comment]
@HenryQW @Andiedie 即刻的 WebP 支持是有问题的，当遇到 GIF 格式的图片时，图会挂掉。

测试链接（有趣的GIF动图 - 即刻主题广场）：

```
https://rsshub.app/jike/topic/square/5aa0c90f8e88bd00164daa3b
```

文档里提到：

> WebP 不支持动图

我在一楼补充了文档链接。

---

推特是假 GIF，实为使用 MP4 容器的视频，不用顾虑这个。

**Comment by HenryQW** [comment]
@ypocc 所以我那个时候开的 /jike/dev, 因为需要很多主题的测试才能适配所有可能出现的情况。我没订阅有动图的gif = =
