### ISSUE TITLE
[BUG]bilibili动态获取BUG

### ISSUE THREAD

**Issue by chenxuan353** [DIYgod/RSSHub#5551]
- 完整路由地址，包含所有必选与可选参数
/bilibili/user/dynamic/406805563
- 预期是什么
200OK
- 实际发生了什么
BOOM
![image](https://user-images.githubusercontent.com/48858695/91573426-7b780800-e979-11ea-9206-2c4081234b71.png)

- 部署相关信息
docker pull 的最新版本，之前几个版本没有这个问题

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    centos7       |
| Node version       |               |
| if Docker, version |       Docker version 19.03.8, build afacb8b7f0        |

- 额外信息（日志、报错等）
TypeError: Cannot convert object to primitive value
    at ctx.state.data.item.data.map (/app/lib/routes/bilibili/dynamic.js:169:74)
    at Array.map ()
    at module.exports (/app/lib/routes/bilibili/dynamic.js:84:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by black-desk** [comment]
实测没问题
![https://rsshub.app/bilibili/user/dynamic/406805563](https://i.loli.net/2020/10/08/9lnXpfOkA6FmtJH.png)

**Comment by HenryQW** [comment]
测试可用。
