### ISSUE TITLE
【功能需求】过滤字段而不屏蔽文章

### ISSUE THREAD

**Issue by SeanChengN** [DIYgod/RSSHub#556]
目前功能：
使用filter或filterout会把包含字段的文章整篇过滤。

期望功能：
新的过滤参数，可以屏蔽文章中的指定字段（广告之类的），而不屏蔽整篇文章。

**Comment by DIYgod** [comment]
广告一般不会加到内容里面去的，这个功能的具体作用是什么？

如果是特殊需求更推荐在客户端完成

**Comment by SeanChengN** [comment]
比如说小草里面的广告图片
![_20180828173701](https://user-images.githubusercontent.com/20624068/44714882-0141ee00-aae9-11e8-87a6-6f1c04f73abb.png)

**Comment by DIYgod** [comment]
在对应模块里做过滤应该更好，pr welcome

**Comment by SeanChengN** [comment]
嗯，好吧
