### ISSUE TITLE
Xmind的思维导图更新

### ISSUE THREAD

**Issue by skycloudly** [DIYgod/RSSHub#5568]
希望增加Xmind的思维导图分享更新
### 网站地址
https://www.xmind.net/share/?category=zh
### 网站描述
Xmind的思维导图在线分享
### 需要生成什么内容？
Xmind的思维导图分享更新
### 额外描述
写了一段代码，但是提示类型错误。。。不知道是哪里的错？
``
const got = require('@/utils/got');
const cheerio = require('cheerio');

module.exports = async (ctx) => {
    const response = await got({  // 发起 HTTP GET 请求
        method: 'get',
        url: 'https://www.xmind.net/share/?category=zh',
    });

    const data = response.data;  // response.data 为 HTTP GET 请求返回的 HTML，也就是简书首页的所有 HTML

    const $ = cheerio.load(data);  // 使用 cheerio 加载返回的 HTML
    const listtmp = $('div[data-next="7j2B-1554775679000"]');
    let list = listtmp[0];

    let itemPicUrl;

    ctx.state.data = {
        title: 'Mindmap Gallery - XMind - Mind Mapping Software',
        link: 'https://www.xmind.net/share/?category=zh',
        item:
            list &&
            list
                .map((index, item) => {  //使用 map 遍历数组，解析出每一个 item 的结果
                    item = $(item);
                    itemPicUrl = `${item.find('div.share-gallery > div:nth-child(1) > a > div > img').attr('src')}`;
                    return {
                        title: item
                            .find('div[1] > div > a')
                            .text(),
                        link: 'https://www.xmind.net/' + item.find('div > a').attr('href'),
                    };
                })
                .get(),
    };
};

``

**Comment by xyqfer** [comment]
有接口的：`https://www.xmind.net/_api/share/featured-maps?lang=zh&limit=12`

**Comment by nczitzk** [comment]
稍微改了一下，下面这段代码应是可用的，可以给你参考一下 😊

但是 XMind Mindmap Gallery 提供了 API，所以使用 API 会好一些，如 #5572

```js
const got = require('@/utils/got');
const cheerio = require('cheerio');

module.exports = async (ctx) => {
    const response = await got({
        method: 'get',
        url: 'https://www.xmind.net/share/?category=zh',
    });

    const data = response.data;

    const $ = cheerio.load(data);
    const listtmp = $('div.share-gallery__map');
    const list = listtmp;

    ctx.state.data = {
        title: 'Mindmap Gallery - XMind - Mind Mapping Software',
        link: 'https://www.xmind.net/share/?category=zh',
        item:
            list &&
            list
                .map((index, item) => {
                    item = $(item);
                    const a = item.find('a[title]');
                    return {
                        title: a.text(),
                        link: `https://www.xmind.net${a.attr('href')}`,
                    };
                })
                .get(),
    };
};
```

**Comment by kunpeng9** [comment]
电报群里发现最近思维导图社区，有不少消息，感谢你们这些人，我之前好像也有想过这个，提交关于几个思维导图网页的相关issues，添加了任务然后不知道安排到滴答清单哪个清单去了，任务太多了，找不到了，又可以删几个任务了。 @skycloudly
