### ISSUE TITLE
GitHub 仓库 wiki 特定 page

### ISSUE THREAD

**Issue by Geeyun-JY3** [DIYgod/RSSHub#5578]
### 网站地址
https://github.com/:owner/:repo/wiki/*
### 网站描述
GitHub 仓库 wiki 特定 page
### 需要生成什么内容？
GitHub 仓库 wiki 特定 page 的更新 RSS
### 额外描述
顺便提醒：GitHub 官方的 RSS 其实还支持仓库 wiki，和仓库 releases、commits 类似，即 `https://github.com/:owner/:repo/wiki.atom`，标题为「repo: Recent Wiki Updates」。
建议写入 [文档相应位置](https://docs.rsshub.app/programming.html#github)。

**Comment by Geeyun-JY3** [comment]
是不是搞错了🤣？应该是 #5599 吧

**Comment by prnake** [comment]
啊这…再开一次吧😂

**Comment by Geeyun-JY3** [comment]
@HenryQW 能不能再抢救一下🤦🏻‍♂️

**Comment by HenryQW** [comment]
那为什么不直接用官方的？
