### ISSUE TITLE
Google news not working

### ISSUE THREAD

**Issue by gianfrappe** [DIYgod/RSSHub#5582]
- https://rsshub.app/google/news/Headlines/hl=en-US&gl=US&ceid=US:en

- Return the "Headlines" feed

- I get the following error message
```
Looks like something went wrong

ReplyError: ERR wrong number of arguments for 'get' command
    at parseError (/data/wwwroot/do02.rsshub.app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/data/wwwroot/do02.rsshub.app/node_modules/redis-parser/lib/parser.js:302:14)

For online documentation and support please refer to docs.rsshub.app.
```

- Using the official instance

**Comment by HenryQW** [comment]
@zoenglinghou

**Comment by zoenglinghou** [comment]
Alright I will take a look

**Comment by zoenglinghou** [comment]
@HenryQW it seems to be a redis/anti-bot related issue. The router runs ok locally on my computer and on my vps. Could you give me some suggestions into where to look/debug?

**Comment by HenryQW** [comment]
Does 't look like a redis related issue to me, if it's google's anti-crawling policy there is nothing we can do.

**Comment by zoenglinghou** [comment]
@gianfrappe you can try self-hosting an RSSHub server. Sorry we can't solve your issue for the time being.
