### ISSUE TITLE
订阅少数派，中文标签，失败

### ISSUE THREAD

**Issue by forgmissyou** [DIYgod/RSSHub#5589]
不太确定放Bug合不合适，如果错了请见谅。

- 完整路由地址，包含所有必选与可选参数

少数派标签订阅，作者: @Jeason0228
举例: https://rsshub.app/sspai/tag/apple
路由: /sspai/tag/:keyword
参数:
keyword, 必选 - 关键词

- 预期是什么
订阅“一周派评”，https://rsshub.app/sspai/tag/一周派评
网址： https://sspai.com/tag/一周派评

- 实际发生了什么
订阅不了，可能是因为中文的原因

**Comment by skycloudly** [comment]
**还是别想这个了，以前起过和你一样的念头。建议：趁早，越早远离越好，早点放弃垃圾sspai。**
**https://www.zhihu.com/question/270077126**
**https://www.zhihu.com/question/269997378**

**Comment by forgmissyou** [comment]
> **还是别想这个了，以前起过和你一样的念头。建议：趁早，越早远离越好，早点放弃垃圾sspai。**
> 
> **如何看待少数派给锤子写的软文不给评论？- https://www.zhihu.com/question/270077126**
> **如何看待少数派的这篇征文？- https://www.zhihu.com/question/269997378**

一般不看文章的，只看看有什么新的应用或者更新，软文遍地都是，得靠自我辨识　(Ｔ＿Ｔ)

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/92312539-9c63dd00-efb9-11ea-9398-b0d00087f012.png)
失败？
顺便提一句，官方自带全文RSS，所以这里不提供

**Comment by forgmissyou** [comment]
> ![image](https://user-images.githubusercontent.com/5896343/92312539-9c63dd00-efb9-11ea-9398-b0d00087f012.png)
> 失败？
> 顺便提一句，官方自带全文RSS，所以这里不提供

知道原因了，app没有自动urlencode，所以失败
