### ISSUE TITLE
自建rsshub如何调整路由抓取频率及每次抓取数量？

### ISSUE THREAD

**Issue by tyhunter** [DIYgod/RSSHub#5590]
路由地址
https://rsshub.app/dsndsht23/yzymyc

预期是什么？
自定义抓取频率和最大抓取数量

实际发生了什么？
现在默认为1小时抓取1次，只抓取最新10条

额外信息
采用flexget+rsshub自动采集sehuatang每日更新的资源到aria2c下载，但发现现在默认抓取频率为1小时1次（更新频率？），在flexget端设置为每10分钟update一次，但还是只有1小时才能get到新资源，因为sehuatang更新速度较快，1小时抓取1次有时候会漏掉比较多的资源，想问下如何调整才能自定义抓取频率和最大抓取数量（例如max 30）

**Comment by TonyRL** [comment]
https://docs.rsshub.app/install/#pei-zhi-huan-cun-pei-zhi

`CACHE_CONTENT_EXPIRE`
