### ISSUE TITLE
酷安话题有两个路由抓取失败

### ISSUE THREAD

**Issue by qingsongya** [DIYgod/RSSHub#5591]
### 完整路由地址，包含所有必选与可选参数

- 举例: https://rsshub.app/coolapk/huati/酷安夜话
- 路由：
 `/coolapk/huati/:tag`
- 参数：
tag, 必选 - 话题名称

### 预期是什么
订阅抓取以下两个路由
https://rsshub.app/coolapk/huati/二手交易
https://rsshub.app/coolapk/huati/酷安自贸区

### 实际发生了什么
这两个无法抓取，提示
**错误：这个话题还没有被创建或现在没有图文及动态内容。**
这两个话题是存在的，为什么会有这样的问题呢？

**Comment by xizeyoupan** [comment]
本来~~懒得做~~觉得交易类有延迟就没做，不过既然提了就加上吧
