### ISSUE TITLE
微博带有视频的内容从第十一条开始就不能加载视频

### ISSUE THREAD

**Issue by willie91** [DIYgod/RSSHub#5610]
- 完整路由地址，包含所有必选与可选参数

- 预期是什么

- 实际发生了什么
能抓到视频封面，但不能加载视频
- 部署相关信息
自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
重新刷新页面的话又可以重新加载10个视频，如此反复。

**Comment by HenryQW** [comment]
没有示例，看不懂你在说什么

**Comment by MisterGlasses** [comment]
> 没有示例，看不懂你在说什么

![D3AAF279-02BC-4992-BC1F-0CFD7521896D](https://user-images.githubusercontent.com/27768847/93845180-771de100-fcd2-11ea-843f-329fb563794a.png)
@iplusx @HenryQW 视频显示这样 点击后无法播放变成下图
![E28BAE08-5321-468A-BFCA-EEB67B8A1C49](https://user-images.githubusercontent.com/27768847/93845202-8ef56500-fcd2-11ea-8f81-ca470c3d8d11.png)

经测试可能是视频链接参数有点问题
rss中不可播放链接：http://f.video.weibocdn.com/O0btvw5Ilx07GBIjuboA01041200vZ3S0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=62b30a3f061b162e421008955c73f536&ori=0&ps=1CwnkDw1GXwCQx&Expires=1600745647&ssig=gOaboZQKwJ&KID=unistore,video 
网页中可播放链接：http://f.video.weibocdn.com/O0btvw5Ilx07GBIjuboA01041200vZ3S0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=62b30a3f061b162e421008955c73f536&Expires=1600753678&ssig=Wbq1SFyTI0&KID=unistore,video

**Comment by MisterGlasses** [comment]
@HenryQW 这个是修了嘛

**Comment by HenryQW** [comment]
> @HenryQW 这个是修了嘛

#2584 没有解决吗？

**Comment by MisterGlasses** [comment]
> > @HenryQW 这个是修了嘛
> 
> #2584 没有解决吗？

没有 那个是19年的pr 我只是过去问了问作者 没人回复我

**Comment by HenryQW** [comment]
我看视频cdn链接带一个过期的时间戳，一旦过期就无法播放了。视频链接是微博接口返回的，RSSHub这边是做不了什么了。

**Comment by MisterGlasses** [comment]
> 我看视频cdn链接带一个过期的时间戳，一旦过期就无法播放了。视频链接是微博接口返回的，RSSHub这边是做不了什么了。

是 我之前发的能用的链接 现在也无法播放了 一段时间就过期

**Comment by HenryQW** [comment]
所以在 RSSHub 抓去的时候，视频是可以播放的，但是过期之后就没有办法了。RSSHub 没有办法再去刷新视频链接了。
