### ISSUE TITLE
如何自建文档？

### ISSUE THREAD

**Issue by Uncle-Four** [DIYgod/RSSHub#5620]
目前是用docker部署的rsshub，用lnmp做的nginx反代

想自建文档，git了项目，运行`npm run docs:dev ` 报错

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'docs:dev' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'predocs:dev', 'docs:dev', 'postdocs:dev' ]
5 info lifecycle rsshub@1.0.0~predocs:dev: rsshub@1.0.0
6 silly lifecycle rsshub@1.0.0~predocs:dev: no script for predocs:dev, continuing
7 info lifecycle rsshub@1.0.0~docs:dev: rsshub@1.0.0
8 verbose lifecycle rsshub@1.0.0~docs:dev: unsafe-perm in lifecycle true
9 verbose lifecycle rsshub@1.0.0~docs:dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/wwwroot/docs.rss.zhang.cn/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle rsshub@1.0.0~docs:dev: CWD: /home/wwwroot/docs.rss.zhang.cn
11 silly lifecycle rsshub@1.0.0~docs:dev: Args: [ '-c', 'vuepress dev docs' ]
12 info lifecycle rsshub@1.0.0~docs:dev: Failed to exec docs:dev script
13 verbose stack Error: rsshub@1.0.0 docs:dev: `vuepress dev docs`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid rsshub@1.0.0
15 verbose cwd /home/wwwroot/docs.rss.zhang.cn
16 error Linux 5.8.1-1.el7.elrepo.x86_64
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "docs:dev"
18 error node v6.17.1
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error rsshub@1.0.0 docs:dev: `vuepress dev docs`
24 error spawn ENOENT
25 error Failed at the rsshub@1.0.0 docs:dev script 'vuepress dev docs'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the rsshub package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     vuepress dev docs
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs rsshub
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls rsshub
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

求有没有更详细一点教程，感谢。

**Comment by tuzi3040** [comment]
> `18 error node v6.17.1`

更新一下nodejs到v12 lts看看

**Comment by Uncle-Four** [comment]
> > `18 error node v6.17.1`
> > `25 error Make sure you have the latest version of node.js and npm installed.`
> 
> 更新一下nodejs到v12 lts看看

搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？

**Comment by tuzi3040** [comment]
> > > `18 error node v6.17.1`
> > > `25 error Make sure you have the latest version of node.js and npm installed.`
> > 
> > 
> > 更新一下nodejs到v12 lts看看
> 
> 搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？

可以的

**Comment by Uncle-Four** [comment]
> > > > `18 error node v6.17.1`
> > > > `25 error Make sure you have the latest version of node.js and npm installed.`
> > > 
> > > 
> > > 更新一下nodejs到v12 lts看看
> > 
> > 
> > 搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？
> 
> 可以的

因为不是程序员，刚刚研究了一下也没找到在哪里改，求指教。

**Comment by tuzi3040** [comment]
> > > 搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？
> > 
> > 
> > 可以的
> 
> 因为不是程序员，刚刚研究了一下也没找到在哪里改，求指教。

这个不用手动改，你访问的时候直接把 rsshub.app 改为自己的域名即可

**Comment by Uncle-Four** [comment]
> > > > 搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？
> > > 
> > > 
> > > 可以的
> > 
> > 
> > 因为不是程序员，刚刚研究了一下也没找到在哪里改，求指教。
> 
> 这个不用手动改，你访问的时候直接把 rsshub.app 改为自己的域名即可。
> 只是如果没有修改端口的话，需要访问1200端口而不是 http 默认的80。
> 部署可以参考[文档](https://docs.rsshub.app/install/)。

感谢，最后请教，如何通过pm2 运行docs? 通过`npm run docs:dev` 运行关闭终端后就停止服务了，rsshub按照教程通过pm2运行成功了

**Comment by tuzi3040** [comment]
> > > > > 搞定了，谢谢，不过想问，文档里的rsshub.app可以改成自己自建的rss地址吗？
> > > > 
> > > > 
> > > > 可以的
> > > 
> > > 
> > > 因为不是程序员，刚刚研究了一下也没找到在哪里改，求指教。
> > 
> > 
> > 这个不用手动改，你访问的时候直接把 rsshub.app 改为自己的域名即可。
> > 只是如果没有修改端口的话，需要访问1200端口而不是 http 默认的80。
> > 部署可以参考[文档](https://docs.rsshub.app/install/)。
> 
> 感谢，最后请教，如何通过pm2 运行docs? 通过`npm run docs:dev` 运行关闭终端后就停止服务了，rsshub按照教程通过pm2运行成功了

`pm2 start npm --interpreter <shell> [--name <service name>] -- run docs:dev`
`<shell>`换成你的shell，`<service name>`换成自定义的，[]内内容可选。macos yarn测试通过。

**Comment by tuzi3040** [comment]
如果没有别的问题，可以先关了，有问题再开。
