### ISSUE TITLE
Suggestion: Replace product hunt feed with the official feed.

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#5624]
The product hunt feed wasn't working for me today. Facing the same issue listed here: https://github.com/DIYgod/RSSHub/issues/5162

I searched around for the feed and I found that product hunt has an official feed with more features (category) and author's comment available [here](https://help.producthunt.com/en/articles/484970-does-product-hunt-have-an-rss-feed). I propose that we redirect product hunt feed to the main one instead of building our own through extracting from the page for compatibility reasons.

I am willing to implement this. Just need a heads up!

**Comment by NeverBehave** [comment]
Close due to deleted account.
