### ISSUE TITLE
眾新聞

### ISSUE THREAD

**Issue by lawsoom** [DIYgod/RSSHub#5626]
### 网站地址

https://www.hkcnews.com/

### 网站描述

《眾新聞》無黨無派，熱愛香港，希望推動公共參與，一同維繫香港自由開放、多元包容等核心價值。我們不設既定政治立場或政策傾向。只願一點燭光，點燃一片燭海，一同發光發熱。

### 需要生成什么内容？
眾聞 最新內文全文https://www.hkcnews.com/news

**Comment by dfpoon** [comment]
眾新聞 RSS 已停止更新超過六天，是不是有甚麼問題？
