### ISSUE TITLE
For ATFD, support airport codes in the URL

### ISSUE THREAD

**Issue by notpushkin** [DIYgod/RSSHub#564]
Shouldn't be too hard, but will need some kind of a database that maps airports to city names (looking into it, the closest I've found so far is the [`airports`](https://www.npmjs.com/package/airports) package on npm)

**Comment by HenryQW** [comment]
@notpushkin Been there. All the up-to-date database providers aren’t free. You can try scraping them from IATA website.

**Comment by notpushkin** [comment]
There is this internal API provided by Aviasales:

```
https://places.aviasales.ru/v2/places.json?locale=en&max=7&types[]=city&types[]=airport&term={QUERY}
```

It's not really good to depend on it, but it might be useful for scraping. It also extends the IATA list with codes for cities with multiple airports as well (i. e. LON for London and MOW for Moscow) – not sure about the source they use though.
