### ISSUE TITLE
孔夫子旧书网抓取错误

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#5646]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/kongfz/people/5032170
https://rsshub.app/kongfz/shop/20995/cat_8
- 预期是什么
正常抓取
- 实际发生了什么
1、加上分类参数后提示：
Looks like something went wrong
Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
2、抓取用户动态无法显示详情
![image](https://user-images.githubusercontent.com/38108376/92935942-10035f80-f47c-11ea-9964-69bbd35a6c75.png)

- 部署相关信息

**Comment by nczitzk** [comment]
店铺上架加上分类应为 /kongfz/shop/20995/8 而非 /kongfz/shop/20995/cat_8
