### ISSUE TITLE
有没有可能做出一个哔哩哔哩分区调整动态的 RSS

### ISSUE THREAD

**Issue by Geeyun-JY3** [DIYgod/RSSHub#5648]
### 网站地址
https://www.bilibili.com/
### 网站描述
哔哩哔哩
### 需要生成什么内容？
哔哩哔哩分区调整动态，即新增分区、减少分区、分区移动、二级分区变为一级分区等的动态
### 额外描述
纯粹开脑洞，如无法实现可直接关闭本 issue。

**Comment by ueiu** [comment]
貌似官方没有一个统一发布分区调整的链接 都是由各个账号在各个专栏自行发布的

**Comment by Geeyun-JY3** [comment]
> 貌似官方没有一个统一发布分区调整的链接 都是由各个账号在各个专栏自行发布的

那有没有可能根据 API 或主站首页变化等（我不懂啊）来生成 RSS 呢？

**Comment by HenryQW** [comment]
除非有接口不然没必要

**Comment by Geeyun-JY3** [comment]
> 除非有接口不然没必要

好的吧

**Comment by imxiaoxp** [comment]
bilibili的up主投稿失效好久了，怎么办

**Comment by Geeyun-JY3** [comment]
> bilibili的up主投稿失效好久了，怎么办

建议另开一个 issue 反馈。
