### ISSUE TITLE
增加几个学校学术活动rss

### ISSUE THREAD

**Issue by Hanpride** [DIYgod/RSSHub#566]
上交电院学术动态http://www.seiee.sjtu.edu.cn/seiee/list/683-1-20.htm
上海科技大学学术动态http://sist.shanghaitech.edu.cn/cn/News.asp?mid=102
东南大学学术动态http://radio.seu.edu.cn/_s29/15986/list.psp
中科院微系统所学术动态http://www.sim.cas.cn/xwzx2016/xshd2016/
谢谢！

**Comment by HenryQW** [comment]
on the way.
大佬同修4学位，膜拜。

**Comment by Hanpride** [comment]
支持了一下
谢谢老哥们
