### ISSUE TITLE
Youtube失效

### ISSUE THREAD

**Issue by KenWuqianghao** [DIYgod/RSSHub#5664]
Youtube Chanel 和 User 都失效了。 
![Screen Shot 2020-09-14 at 19 55 42](https://user-images.githubusercontent.com/20444505/93120872-4c290100-f6c4-11ea-99ec-52a59b5fff7d.png)

**Comment by KenWuqianghao** [comment]
---
name: 🐛 Bug 报告
about: 早起的小可爱有虫抓
---



- 完整路由地址，包含所有必选与可选参数
http://127.0.0.1:1200/youtube/channel/UCK7KZHH2Cs3jaWjI8RJR-lA

- 预期是什么
生成youtube channel rss

- 实际发生了什么
未生成

- 部署相关信息



| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Mac OS        |
| Node version       | v13.11.0      |
| if Docker, version | 19.03.12      |

- 额外信息（日志、报错等）

**Comment by TristenChenTao** [comment]
me too

**Comment by HenryQW** [comment]
貌似是demo的API key出了问题，我自建没有问题
![Uploading image.png…]()
