### ISSUE TITLE
求一个CGTN的RSS源

### ISSUE THREAD

**Issue by Chen294** [DIYgod/RSSHub#5666]
### 网站地址
https://www.cgtn.com/
### 网站描述
中国国际电视台
### 需要生成什么内容？
网站上的头条新闻等
### 额外描述
CGTN是国内还算比较快的可以看英文新闻的网站

**Comment by Chen294** [comment]
It does not work
![image](https://user-images.githubusercontent.com/41291485/93601796-51ec5280-f9f4-11ea-91ed-c374d2df270e.png)
![image](https://user-images.githubusercontent.com/41291485/93601824-5f094180-f9f4-11ea-8269-fd3d1747deb7.png)

**Comment by pky2006** [comment]
有欧洲的
https://www.cgtn.com/rss/europe/rss.xml
