### ISSUE TITLE
 我使用的mac reeder 添加的时候 rsshub的地址全部超时,请问是为啥

### ISSUE THREAD

**Issue by AHPirate** [DIYgod/RSSHub#5670]
- 完整路由地址，包含所有必选与可选参数
![image](https://user-images.githubusercontent.com/38470946/93302158-1acb4500-f82c-11ea-8c50-328b70bf98ab.png)
我使用的mac reeder 添加的时候 rsshub的地址全部超时,请问是为啥
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by PyGroot** [comment]
我也是

**Comment by PyGroot** [comment]
直接用浏览器访问，全部 504 Gateway Time-out

**Comment by ueiu** [comment]
正常访问阿
![image](https://user-images.githubusercontent.com/39592269/93367437-13815700-f87f-11ea-9cb0-3356de13f3b8.png)

**Comment by AHPirate** [comment]
是这样的,我试过,我开全局翻就可以在 reeder上使用,我浏览器是一直翻着,所以可以直接打开

我的目的就是想问问这个问题
最后发现是被墙了
这就没办法了
所以这个可以关了
