### ISSUE TITLE
是不是挂了，所有访问都是超时

### ISSUE THREAD

**Issue by pierwzw** [DIYgod/RSSHub#5673]
- 完整路由地址，包含所有必选与可选参数

- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by ueiu** [comment]
刚随便试了一个，正常
![image](https://user-images.githubusercontent.com/39592269/93367437-13815700-f87f-11ea-9cb0-3356de13f3b8.png)

**Comment by junfengP** [comment]
demo被屏蔽了，需要科学上网 or 自建
