### ISSUE TITLE
输出可验证的RSS

### ISSUE THREAD

**Issue by leegang** [DIYgod/RSSHub#5678]
### 这是一个什么样的功能？

现在的RSs输出无法通过W3C验证。
无法使用一些要求严格的订阅器，比如IFTTT 和 zapier

验证结果如下 ：
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmidrss.herokuapp.com%2Fwechat%2Fcsm%2FQbitAI

### 这个功能可以解决什么问题？
可以支持zapier 和 IFTTT

**Comment by HenryQW** [comment]
这要求author必须为email，太扯了
