### ISSUE TITLE
tiny  tiny rss 通过docker 容器IP+端口号的方式订阅，总是返回错误

### ISSUE THREAD

**Issue by PyGroot** [DIYgod/RSSHub#5682]
是我打开方式不对吗？求助，ttrss和rsshub都安装在一个vps，不通过域名，使用ip+端口号的方式，怎么订阅rsshub的源

**Comment by MoonBegonia** [comment]
@PyGroot 你试试127.0.0.1和映射出来的端口号？

**Comment by PyGroot** [comment]
> @PyGroot 你试试127.0.0.1和映射出来的端口号？

使用 http://127.0.0.1:1200/dapenti/tugua 这样的方式订阅，TTRSS返回错误：无法从指定的网址下载:false

**Comment by PyGroot** [comment]
在命令行中 curl http://127.0.0.1:1200/dapenti/tugua 是可以获取到订阅内容的

**Comment by HenryQW** [comment]
学习一下docker networks吧，容器之间的通信除非是bridge，不然无法通过127.0.0.1。直接上docker name resolution 不香吗

**Comment by PyGroot** [comment]
> 学习一下docker networks吧，容器之间的通信除非是bridge，不然无法通过127.0.0.1。直接上docker name resolution 不香吗

没有用docker，ttrss和rsshub都是手动部署的

**Comment by HongPig** [comment]
@PyGroot 这个问题我也遇到了，然后现在的解决方案是用Nginx反代去掉端口号，这样就可以订阅了

**Comment by HenryQW** [comment]
ttrss 禁止了非80和443端口。

https://git.tt-rss.org/fox/tt-rss/commit/4efc3d7b3f6465a23d5e1c1415ec74e80cc7562d

**Comment by PyGroot** [comment]
> ttrss 禁止了非80和443端口。
> 
> https://git.tt-rss.org/fox/tt-rss/commit/4efc3d7b3f6465a23d5e1c1415ec74e80cc7562d
太感谢了，我去试试

**Comment by johnrosen1** [comment]
@PyGroot 请使用NGINX反向代理
