### ISSUE TITLE
知乎用户文章

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#5702]
- 完整路由地址，包含所有必选与可选参数
路由: /zhihu/people/posts/:id
- 预期是什么
可以自己订阅自己的文章
- 实际发生了什么
无法订阅https://www.zhihu.com/people/kunpeng9.serious/posts

https://ttrss.kunpeng9.cn/public.php?op=subscribe&feed_url=https://rss.kunpeng9.cn/zhihu/people/posts/kunpeng9.serious

之后显示这个
![image](https://user-images.githubusercontent.com/44609485/93893519-4a90b600-fd20-11ea-8874-9b92473f3e5f.png)，哪里出了问题，为啥我不能订阅自己？上周还是啥时候来着，试过了一次，今天试了一次还是不行。
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by kunpeng9** [comment]
订阅动态可以，订阅文章为啥就是不行，老是报错，我还以为偶尔会出的，结果试了一下，都不行。
[(3 封私信) King咔 - 知乎](https://www.zhihu.com/people/liu_svip/posts)
![image](https://user-images.githubusercontent.com/44609485/94150143-5eb4ee80-feab-11ea-97c4-f79b4ddd8404.png)
![image](https://user-images.githubusercontent.com/44609485/94150163-64aacf80-feab-11ea-9f10-30f496985f86.png)
![image](https://user-images.githubusercontent.com/44609485/94150205-6bd1dd80-feab-11ea-9c83-b1fda095fa0d.png)

**Comment by HenryQW** [comment]
用户文章的接口一直返回错误10002，我看别人直接爬页面，数据都在`js-initialData`里，期待有缘人。

**Comment by kunpeng9** [comment]
![image](https://user-images.githubusercontent.com/44609485/94440771-94701500-01d4-11eb-9220-06229417ef64.png)
-
![image](https://user-images.githubusercontent.com/44609485/94440973-c8e3d100-01d4-11eb-87fc-4bca3926a6ac.png)
-
![image](https://user-images.githubusercontent.com/44609485/94441053-de58fb00-01d4-11eb-8581-7b6978d389ad.png)
文章不行，动态还是不行，是因为zi-zai-zheng-nian-53这里面有-导致的吗？

**Comment by Colin-XKL** [comment]
已修复，见PR #6760。
顺带支持了机构账号文章的订阅
