### ISSUE TITLE
知乎收藏夹

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#5708]
- 完整路由地址，包含所有必选与可选参数
路由: /zhihu/collection/:id
参数:
id, 必选 - 收藏夹 id, 可在收藏夹页面 URL 中找到
- 预期是什么
可以正常订阅
- 实际发生了什么
[关学总论合集 - 收藏夹 - 知乎](https://www.zhihu.com/collection/505828536 )怎么回事，知乎文章还有收藏都不成功。。。
![image](https://user-images.githubusercontent.com/44609485/94003287-9e0d0d80-fdcd-11ea-8f41-01cfa351102a.png)
正常显示，接着
![image](https://user-images.githubusercontent.com/44609485/94003318-aa916600-fdcd-11ea-884b-90051fd1791f.png)
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
无法下载信息源的 URL。

**Comment by Colin-XKL** [comment]
补充信息：
经测试，知乎收藏夹的路由均失效，公共的rsshub.app和自建的实例均不能正常使用，返回信息为：
> Looks like something went wrong
> Route requested: /zhihu/collection/114061818
> Error message: this route is empty, please check the original site or create an issue

**Comment by Colin-XKL** [comment]
已修复，见PR #6815
