### ISSUE TITLE
怎么增大输出的条目数呢？

### ISSUE THREAD

**Issue by sealionking** [DIYgod/RSSHub#572]
我看在路由里面默认设置都是0-10，试着增加到100，但是rss输出并没有也增加到100条。

**Comment by HenryQW** [comment]
很多路由默认10条，无法增大。

1. 消耗大量服务器资源。
2. 容易被反爬虫。
3. 绝大部分过时 feed 没有意义。

**Comment by lengthmin** [comment]
@sealionking 在每个源的js文件中设置抓取数量

**Comment by sealionking** [comment]
@lengthmin 你是说每个路由的js文件么？
@HenryQW 只是自己架设一个内部用的服务器，不是对外开放的，资源这块不会有太大限制。

**Comment by lengthmin** [comment]
@sealionking 几乎都是在js源中规定抓取数量的

**Comment by DIYgod** [comment]
RSS 是用来获取更新，增大条目无意义

**Comment by nokaka** [comment]
> RSS 是用来获取更新，增大条目无意义
> 
> 特殊需求请在相应模块里自行修改

能否，新的订阅，第一次抓取全部，往后每次只抓取10条以获取更新
