### ISSUE TITLE
GitHub 仓库 wiki 特定 page 更新 RSS（重开 #5578）

### ISSUE THREAD

**Issue by Geeyun-JY3** [DIYgod/RSSHub#5726]
### 网站地址
https://github.com/:owner/:repo/wiki/*
### 网站描述
GitHub 仓库 wiki 特定 page
### 需要生成什么内容？
GitHub 仓库 wiki 特定 page 的更新 RSS
### 额外描述
（原 issue 里 [反馈](https://github.com/DIYgod/RSSHub/issues/5578#issuecomment-696570441) 没反应，群里喊也没人理，只能再开个新的了）
顺便提醒：GitHub 官方的 RSS 其实还支持仓库 wiki，和仓库 releases、commits 类似，即 `https://github.com/:owner/:repo/wiki.atom`，标题为「repo: Recent Wiki Updates」。
建议写入 [文档相应位置](https://docs.rsshub.app/programming.html#github)。

**Comment by HenryQW** [comment]
那为什么不直接用官方的？

**Comment by Geeyun-JY3** [comment]
官方的做不到特定 page 吧

**Comment by HenryQW** [comment]
如果没有官方接口，这个很难做

**Comment by NeverBehave** [comment]
这个感觉可以用filter做, 但是要proxy一次
