### ISSUE TITLE
使用ttrss，只能添加订阅rsshub.app开头的地址，而不能添加订阅自己主机开头的地址。

### ISSUE THREAD

**Issue by stefaneliu** [DIYgod/RSSHub#5728]
- The involved route, with all required and optional parameters

- What is expected：在自己的群晖或者其它主机上部署rsshub，并且在ttrss上正确订阅

- What is actually happening：ttrss可以正确添加rsshub.app开头的订阅地址，但无论是我的群晖docker还是外面的一台centos以docker安装的rsshub生成的地址均无法被ttrss正确识别并添加。

举例：同一个纽约时报订阅源：
下图是添加rsshub.app开头地址调试的结果：
[https://i.loli.net/2020/09/25/kvZRjX6KQxHEFWU.png](url)

下图是地址是我的centos主机调试的结果：
[https://i.loli.net/2020/09/25/Buew1qSYyP9spdg.png](url)

谢谢！

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    centos7           |
| Node version       |               |
| if Docker, version |      19.03.13         |

- Additional info (logs errors etc)

**Comment by yefoenix** [comment]
@stefaneliu Ttrss 在最近的更新中关闭了对80/443以外端口地址的feed的支持，需要将自建rsshub服务的默认端口通过修改配置文件或者增加反代等方式更改80/443

**Comment by johnrosen1** [comment]
@stefaneliu 你可以参考我的方案
https://github.com/johnrosen1/vpstoolbox

**Comment by stefaneliu** [comment]
感谢各位

**Comment by yefoenix** [comment]
@stefaneliu issue可以关闭了
