### ISSUE TITLE
建议收集一些大牛的博客添加进来

### ISSUE THREAD

**Issue by tomoya92** [DIYgod/RSSHub#573]

**Comment by Chingyat** [comment]
大牛的博客一般自带rss

**Comment by DIYgod** [comment]
只接受通用的 RSS，比如 [Next 主题](https://docs.rsshub.app/#next-%E4%B8%BB%E9%A2%98)

**Comment by tomoya92** [comment]
呃，我的意思就是在文档里开一个静态的页面，上面给一些大牛的博客rss地址，不用rsshub服务器处理的，就只作展示

**Comment by lengthmin** [comment]
@tomoya92 所以跟rsshub木有关系呀

**Comment by idealclover** [comment]
https://github.com/idealclover/Easy-to-RSS
如果博客自带RSS的话会识别出来哒
