### ISSUE TITLE
无法订阅服务器上生成的rss源链接

### ISSUE THREAD

**Issue by SheepAndWolf** [DIYgod/RSSHub#574]
服务器1200端口已经打开，用feedly可以搜索到rss源，但是点进去查看详情时显示：
This feed does not have any entries at the moment.
点击flowing会显示404错误

**Comment by lengthmin** [comment]
@SheepAndWolf 直接访问网址有加载出东西吗?

**Comment by SheepAndWolf** [comment]
加载出一个xml文件




| |
施晖@BUPT
|
|
邮箱：sugerman_1995@163.com
|

签名由 网易邮箱大师 定制

在2018年08月29日 10:49，Artin 写道：

@SheepAndWolf 直接访问网址有加载出东西吗?

**Comment by lengthmin** [comment]
网址里的内容item是不是为空? 
检查一下路由是不是输错了?
可以截个图吗?

**Comment by SheepAndWolf** [comment]
![image](https://user-images.githubusercontent.com/18346756/44770010-242bdb00-ab99-11e8-91aa-c893c01f1486.png)

**Comment by DIYgod** [comment]
feedly 有时候显示不出来旧内容，换个服务试试

**Comment by hstdt** [comment]
貌似是因为feedly不接受80/443端口之外的数据
