### ISSUE TITLE
Miniflux RSS Proposal

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#5744]
### Website URL

https://miniflux.app/

### Website description

Miniflux is a minimalist and opinionated feed reader.

### What content should be included?

- [ ] Starred entries
- [ ] Subscription list

### Additional description

Need 2 envionment variables: Endpoint Token

**Comment by xizeyoupan** [comment]
所以是把这个RSS服务里的内容提取出来给另一个服务来订阅？这种套娃行为意义何在😅

**Comment by yefoenix** [comment]
> 所以是把这个 RSS 服务里的内容提取出来给另一个服务来订阅？这种套娃行为意义何在😅

内容的再发布，很有用。这是我没办法从ttrss转其他产品的主要原因……

**Comment by emdoe** [comment]
> * Started entries

请问这个是指 starred entries？

> * Subscription list

请问这个是什么意思呢？

> Need 3 envionment variables: Endpoint Username Password

是否可以考虑变为 endpoint & api_key？

有作一个雏形出来，但是肯定还不完美，因为 Miniflux 那边并未 exposes the api of shared link，所以现阶段可以把 content 提取出来，但是（暂时恐怕依然会选择）指向原始链接。

**Comment by DIYgod** [comment]
@emdoe 是的..
订阅列表
哦刚看到有 API token，用 token 更好一些
我觉得用原始链接挺好的

**Comment by emdoe** [comment]
> 订阅列表

这个的意思是输出其中一些（或全部）订阅源的内容对么？而 **不是** 单要订阅的源的地址（就类似于导出的 OPML 那样）？

> 我觉得用原始链接挺好的

暂时会这么处理，但我理想的处理方式是:
```
url: miniflux.instance.com/share/share_code
description: '//original contents <p>☍ source</p>'
```

**Comment by DIYgod** [comment]
> 这个的意思是输出其中一些（或全部）订阅源的内容对么？而 不是 单要订阅的源的地址（就类似于导出的 OPML 那样）？

哦不是，我的意思就是 OPML 那样的，输出订阅了哪些源

**Comment by emdoe** [comment]
唔，可不可以分享一个使用场景之类的呀？以及，这样做和直接调用 API 去 export OPML 的差别是什么…？是希望更精细的控制输出哪些订阅源？

**Comment by yefoenix** [comment]
> 唔，可不可以分享一个使用场景之类的呀？以及，这样做和直接调用 API 去 export OPML 的差别是什么…？是希望更精细的控制输出哪些订阅源？

比如，配合 RSS bot 就可以在DIY的tg 频道里看到「DIY订阅了Feed：XXX」

**Comment by emdoe** [comment]
> 配合 RSS bot 就可以...

诶抱歉我没用过…方便的话可以推个链接之类的给我么？或者我这样的理解对不对，输出的内容是：
1.  ```
     url: link.for.subscription.xml
     link: feed_title
     ```
2. 或者
    ```
    url: this.feed.com
    link: feed_title
    ```
此外 description 希望是什么呢？

（注意 Miniflux 的接口[不提供](https://miniflux.app/docs/api.html#endpoint-get-feeds)关于某个 RSS Feed 本身的描述信息）

---

此外，我还有一个问题想征求一下大家的意见：

1. 希望对获取到的 feed 的默认操作是？变为已读还是不改动状态？
2. 之后如果可以输出分享链接的时候，我可以默认选用分享链接么？
3. 我现阶段的方案并不是（也似乎没有很大的动力来）支持所有 EndPoint。特别的，我只关心根据规则来获取全部或指定的 feed(s) 的内容，不知道这个方案是否是大家想要的？
4. 当然，3 的一个附带作用是，可以利用这个来实现 https://github.com/DIYgod/RSSHub/pull/514, https://github.com/DIYgod/RSSHub/issues/4192, https://github.com/DIYgod/RSSHub/issues/283 所说的需求，但是
    1. 大家需要首先有一个 Miniflux Instance（我不知道是否有免费公用的 instance？），所以恐怕这个方案并不是非常的方便
    2. 这毕竟只是只是一个顺带实现的功能，所以暂不支持非常精细的合并操作（e.g., 控制合并的输出中 feed1 的 limit 为 3，feed2 为 7。我现阶段的方案只是共用相同的 limit value），而且我也没有很有动力去支持这些

**Comment by emdoe** [comment]
（备忘）暂时不关是因为：

1. 也许可能会修改输出 subscription 的格式
2. 希望等 Miniflux 的 API支持 生成 share link

**Comment by DIYgod** [comment]
https://docs.rsshub.app/routes/other#miniflux
