### ISSUE TITLE
微博“仅粉丝可见内容”有办法获取吗？

### ISSUE THREAD

**Issue by Mordiggian** [DIYgod/RSSHub#5753]
- 完整路由地址，包含所有必选与可选参数
/weibo/user/1862695480
- 预期是什么
能够获取：仅粉丝可见内容
- 实际发生了什么
只能获取无限制内容
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
没有
