### ISSUE TITLE
Twitter Favorites/Retweets Filter

### ISSUE THREAD

**Issue by mergesort** [DIYgod/RSSHub#576]
Hi there. Just came across your service and it looks perfect for a person who lives in RSS like I do.

I was hoping it would be possible to add the ability to filter tweets by likes/retweets, that way I could take the tweets of high volume tweeters and only see their high signal tweets.

Thanks a lot!

**Comment by DIYgod** [comment]
All new tweets have no likes and retweets, we can't filter in this way.

**Comment by mergesort** [comment]
Ah, ok. I figured the tweets might be stored in a database and updated periodically. Feel free to close the issue if it's not possible then.

Thanks!

**Comment by DIYgod** [comment]
It need handle Twitter's data, it's more complex and it's a little beyond this project's purpose.

But if you want to do it, pr welcome anyway.

Thanks.
