### ISSUE TITLE
Is it possible to get RSS feed of things that I've personally stared?

### ISSUE THREAD

**Issue by bonelifer** [DIYgod/RSSHub#5763]
### What feature is it?
Is it possible to get RSS feed of things that I've personally stared?

### What problem does this feature solve?
Gives an RSS feed of projects that you've personally starred.

**Comment by HenryQW** [comment]
What exactly are you trying to say?

**Comment by bonelifer** [comment]
I want to get a feed of things I've personally starred on Github.

**Comment by notofoe** [comment]
https://docs.rsshub.app/en/programming.html#github-user-starred-repositories

**Comment by bonelifer** [comment]
Thanks for trying, but that gives the stars other people have given to a specific REPO. I was looking for the STARS that I've given ANY REPO.  :(

**Comment by HenryQW** [comment]
PLEASE READ THE DOC.
PLEASE READ THE DOC.
PLEASE READ THE DOC. https://rsshub.app/github/starred_repos/:user will display all repos a user have starred.
