### ISSUE TITLE
为期刊网站设立rss订阅

### ISSUE THREAD

**Issue by fredericky123** [DIYgod/RSSHub#5767]
不太会编程，大佬们能为学术期刊设置一个rss订阅网址吗
https://journals.aom.org/toc/amr/0/ja

**Comment by hang333** [comment]
请参照 [RSS 提案模板](https://github.com/DIYgod/RSSHub/blob/master/.github/ISSUE_TEMPLATE/rss_request_zh.md) 修改

**Comment by fredericky123** [comment]
网站地址：https://journals.aom.org/toc/amr/0/ja
网站描述：美国管理学会评论最新发表文章
需要生成什么内容？生产包含文章标题、作者、发表时间和详情链接的RSS
额外描述：无

再次谢谢！
