### ISSUE TITLE
RSSHub用得越久就越占内存

### ISSUE THREAD

**Issue by ClarkeCheng** [DIYgod/RSSHub#577]
原本刚启动时是不占多少内存的，但是用久了，占的内存就越来越多。我是没有开缓存的，可以回收一下内存吗？
![](https://user-images.githubusercontent.com/17330505/44794839-eac88f00-abdb-11e8-8ddd-82a40802f528.png)

**Comment by HenryQW** [comment]
初步断定凶手是它https://github.com/DIYgod/RSSHub/blob/8325cc5a8339bd787f2b47ca03a5a95e58e9263d/routes/pixiv/token.js#L77-L89

可以通过 cron 来解决，我没有 pixiv 账号，等待有缘人吧

**Comment by jiey2016** [comment]
@DIYgod
