### ISSUE TITLE
BBC中文未获取到图片

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#5780]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/bbc/chinese/business
- 预期是什么
获取每篇文章包含的图片
- 实际发生了什么
仅获取全文内容，无图片
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |debian 10      |
| Node version       |v12.18.4       |
| if Docker, version |               |

- 额外信息（日志、报错等）
视频内容获取也不正常

**Comment by HenryQW** [comment]
BBC改版太频繁了。。。
