### ISSUE TITLE
笔趣阁凉了

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#5788]
- 完整路由地址，包含所有必选与可选参数
https://www.biquge5200.com/
路由: /novel/biquge/:id
参数:
id, 必选 - 小说 id, 可在对应小说页 URL 中找到
- 预期是什么
可以获得最新的小说章节
- 实际发生了什么
失效了有一阵了，全红，很少数的不是红的。
![image](https://user-images.githubusercontent.com/44609485/94992991-5b62e680-05c0-11eb-9c1c-a4b235c1b6b3.png)
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
测试路由都没有，怎么修？

**Comment by kunpeng9** [comment]
@HenryQW 啥测试路由？怎么搞？
