### ISSUE TITLE
GitHub 用户 Followers 和 仓库 Stars 数据有误

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#579]
解决方法：

1. 请求 https://api.github.com/users/:user/followers，`Link` 中可以找到最后一页的页码
1. 请求 https://api.github.com/users/:user/followers?page=x，x 为上一步找到的页码
1. 最后一页数据不足（小于 5）时，再请求上一页的数据

**Comment by HenryQW** [comment]
Reported:
https://platform.github.community/t/first-and-last-arguments-for-followerconnection-dont-work-as-intended/7074

**Comment by DIYgod** [comment]
仓库 Stars 已经好了，用户 Followers 变成了首字母倒序🌚

**Comment by HenryQW** [comment]
@DIYgod 目前解决办法: follower 可以通过过滤 (started following you) 自己的 private feed 实现， star 可以通过过滤 (starred DIYgod/)  实现
