### ISSUE TITLE
Implement support for github topics

### ISSUE THREAD

**Issue by tylerssn** [DIYgod/RSSHub#5803]
### Website URL

https://github.com/topics/[TOPIC]

example: https://github.com/topics/framework

### What content should be included?

Topic section content.

### More info

Curious if this is possible. I'm new to RSSHub and would like to contribute, however, not sure how soon I could get around to it.

**Comment by NeverBehave** [comment]
No official support, I didn't find any official API as well. Scrape Webpage may be required
