### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yunau** [DIYgod/RSSHub#5804]
- 完整路由地址，包含所有必选与可选参数
    `/ithome/it`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 404 (Not Found)
```

**Comment by nczitzk** [comment]
请更新 RSSHub 到最新，在 3d52739 之后版本的 ithome 相关路由可以正常工作
