### ISSUE TITLE
希望每个RSS Item可以自动加入发布时间

### ISSUE THREAD

**Issue by dawnyesky** [DIYgod/RSSHub#5812]
如果没有在每个Item里放置时间信息，希望系统可以把爬取时的时间戳加入。因为RSS流里如果有重复的Item但是不是在同一个时间出现，那么将无法区分这两个Item，如果应用考虑时间维度的话将会导致信息丢失。具体是
在每个<item></item>里设置默认的<pubDate>系统时间</pubDate>

目前在用 @sakamossan 的 https://rsshub.app/twitter/trends 以及 @xyqfer 的 https://rsshub.app/weibo/search/hot

**Comment by notofoe** [comment]
或许可以将 `guid` 设置成这样：`twitter-trends/20201006/#TrumpIsNotAmerica`

**Comment by dawnyesky** [comment]
> 或许可以将 `guid` 设置成这样：`twitter-trends/20201006/#TrumpIsNotAmerica`

其实我主要是希望可以获取带有时间维度的数据作时序分析，设置guid可以大致区分开，不过如果要进行不同时间粒度的数据分析就不够灵活了，能够有时间戳属性会更好

**Comment by HenryQW** [comment]
每一个 feed 其实本身有一个 lastBuildDate
