### ISSUE TITLE
微博会遗漏一小部分

### ISSUE THREAD

**Issue by 10362227** [DIYgod/RSSHub#5813]
完整路由地址，包含所有必选与可选参数 https://rsshub.app/weibo/user/2698087403

预期是什么
获取每篇文章

实际发生了什么
会遗漏文章

部署相关信息
Env | Value
-- | --
OS | Centos7
Node version | v12.18.4
if Docker, version |  

完整路由地址：https://rsshub.app/weibo/user/2698087403
比如第二条博文rss就没有显示。主页：https://weibo.com/u/2698087403?profile_ftype=1&is_all=1#_0

这个问题很早发现了，概率不高，如果某个博主更新频率很高，一天总会发现一两条遗漏

**Comment by elonj** [comment]
遇到同样问题，有微博遗漏
完整路由地址：https://rsshub.app/weibo/user/1644101945/1
主页：https://weibo.com/p/1005051644101945/home?from=page_100505&mod=TAB&is_all=1#place
比如博文 “1月24日 14:32 来自 iPad Pro 奥巴马在当选之前戴豪雅表” 就没有显示。

Docker version date: 1/24/2021
ENV NODE_VERSION=10.23.1
ENV YARN_VERSION=1.22.5

**Comment by 10362227** [comment]
> 遇到同样问题，有微博遗漏
> 完整路由地址：https://rsshub.app/weibo/user/1644101945/1
> 主页：https://weibo.com/p/1005051644101945/home?from=page_100505&mod=TAB&is_all=1#place
> 比如博文 “1月24日 14:32 来自 iPad Pro 奥巴马在当选之前戴豪雅表” 就没有显示。
> 
> Docker version date: 1/24/2021
> ENV NODE_VERSION=10.23.1
> ENV YARN_VERSION=1.22.5

开发者已经回复过我，这是微博api接口本身的bug，无法解决。不过可以自己添加微博cookie，这样就正常了，只是cookie会过一段时间失效，要经常更换
