### ISSUE TITLE
alltheflightdeals - keep case sensitivity?

### ISSUE THREAD

**Issue by faelsoto** [DIYgod/RSSHub#582]
Hello, first of all great tool!

I'm trying to subscribe to alltheflightdeals for my city, but it keeps returning no items. I'm thinking it's because the city name's is capital cased:

Even though I write `Mexico_City`

```https://rsshub.app/atfd/mx+Mexico_City```

The RSS feed URL is `https://alltheflightdeals.com/deals/mx/Mexico_city` (notice the lowercase `c` in `city`)

In this case, alltheflightdeals' website turns [0 results for this URL](https://alltheflightdeals.com/deals/mx/Mexico_city). However with this URL it shows them correctly: https://alltheflightdeals.com/deals/mx/Mexico_City

Thanks!

**Comment by HenryQW** [comment]
Try https://rsshub.app/atfd/mx+mexico%20city instead

**Comment by faelsoto** [comment]
Great, thanks!

I guess the issue is closed, then.
