### ISSUE TITLE
Twitter list timeline

### ISSUE THREAD

**Issue by ScaonE** [DIYgod/RSSHub#5821]
---
name: 🐛 Bug Report
about: Twitter list timeline
---

- The current example for Twitter list timeline is not working
`https://rsshub.app/twitter/list/ladyleet/javascript`

- What is expected : Output = XML file

- What is actually happening :
> TypeError: Cannot read property 'id' of undefined

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Win 7        |

**Comment by ScaonE** [comment]
Sorry, I edited the post and tried my best to follow the template

**Comment by HenryQW** [comment]
It's hard to debug twitter routes since I do not have a twitter API key. You will have to wait for someone has it.

**Comment by simoin** [comment]
The name of list is case sensitive now due to #5630, so the link in docs should be replaced with [https://rsshub.app/twitter/list/ladyleet/Javascript](https://rsshub.app/twitter/list/ladyleet/Javascript). I will create a PR immediately.

**Comment by ScaonE** [comment]
> The name of list is case sensitive now due to #5630, so the link in docs should be replaced with https://rsshub.app/twitter/list/ladyleet/Javascript. I will create a PR immediately.

Nice, https://rsshub.app/twitter/list/ladyleet/Javascript is working !

I still don't manage to make it work for me. I try to do this from a list of mine named "Symbiose".
I am following the "List timeline" recipe, i.e. "/twitter/list/:id/:name"

Here are the relevant infos from my twitter [account](https://twitter.com/e_scaon) : [Screenshot](https://ibb.co/QQw4BB3)
Thus, id = e_scaon & name = Symbiose

https://rsshub.app/twitter/list/e_scaon/Symbiose
Still yields : 
> TypeError: Cannot read property 'id' of undefined

Any tips ?

**Comment by simoin** [comment]
The code works on my machine. Maybe the cached key is duplicated in other routes.

**Comment by ScaonE** [comment]
> The code works on my machine. Maybe the cached key is duplicated in other routes.

This code ? https://rsshub.app/twitter/list/e_scaon/Symbiose

Because it's not working for my colleagues either.

**Comment by simoin** [comment]
I mean self-hosted.

![](https://i.imgur.com/TIw8Thh.png)

Anyway, I will update the cache key to ensure it's unique.

@HenryQW This bug only reiterates in the production environment for me. Can you merge PR first and see if it's solved?

**Comment by HenryQW** [comment]
I hope #5859 clears things up?

**Comment by ScaonE** [comment]
Same behavior for me with https://rsshub.app/twitter/list/e_scaon/Symbiose
> TypeError: Cannot read property 'id' of undefined

**Comment by simoin** [comment]
@ScaonE it works now

![](https://i.imgur.com/L6QmHKh.png)

**Comment by ScaonE** [comment]
@simoin (and all people involved), thanks a lot !

**Comment by ScaonE** [comment]
Another question :
I just created another [list ](https://ibb.co/3NW7QHz) (same account, list is also public).

https://rsshub.app/twitter/list/e_scaon/Microbiome

Which is yielding the previous error at the moment. Is there some delay to be expected before it works, or should it work right after the list is created ?

**Comment by simoin** [comment]
I see.

Because your all lists have been cached, a new list would not be hit. You can wait a while for cache expiration. 

I will update cache strategy later.

**Comment by ScaonE** [comment]
Okay, again, thanks a lot for the explanation.
(Can I reset my cache manually ?)

**Comment by NeverBehave** [comment]
> Okay, again, thanks a lot for the explanation.
> (Can I reset my cache manually ?)

By default, Cache is in memory, restart your instance. Redis please remove all pairs.
