### ISSUE TITLE
Please support behance appreciated and collection

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#5828]
### 网站地址
https://www.behance.net/
### 网站描述
Behance是一款Adobe旗下用于展示并发现创意作品的在线平台。 
### 需要生成什么内容？
目前可以RSShub只能输出某人的作品（Work），希望此外还可以输出某人的好评/点赞（appreciated）以及收藏夹/情绪板（collection）。
Appreciated示例：https://www.behance.net/a6241295564077/appreciated
collection示例：https://www.behance.net/collection/169327161/Product

**Comment by HenryQW** [comment]
#5835
