### ISSUE TITLE
微博比较严重的Bug！不容易发现，希望早点修复

### ISSUE THREAD

**Issue by 10362227** [DIYgod/RSSHub#5836]
完整路由地址，包含所有必选与可选参数 https://rsshub.app/weibo/user/2698087403

预期是什么
获取每篇文章

实际发生了什么
会遗漏文章

部署相关信息
Env | Value
-- | --
OS | Centos7
Node version | v12.18.4
if Docker, version |  

完整路由地址：https://rsshub.app/weibo/user/2698087403
比如第二条博文rss就没有显示。主页：https://weibo.com/u/2698087403?profile_ftype=1&is_all=1#_0

这个问题很早发现了，一些特定文案的文章不会在rss显示（把这遗漏的文章文案用自己的号发，一样不会在rss显示，例如：https://weibo.com/2698087403/Jo0wQurzG?from=page_1005052698087403_profile&wvr=6&mod=weibotime ），如果某个博主更新频率很高，每天总会发现有遗漏。

这算比较大的bug吧，遗漏文章还是很严重的，还是在大的社交网站，而且不太容易发现，因为偶尔才会发生。希望能尽快修复

**Comment by Look960** [comment]
github-actions[bot] <notifications@github.com> 于 2020年10月10日周六 00:52写道：

**Comment by HenryQW** [comment]
应该是只有关注可见的微博，所以没有出现

**Comment by 10362227** [comment]
> 应该是只有关注可见的微博，所以没有出现

不是啊，你仔细看我的描述，而且我举例了，你点进去看就知道。甚至你可以你把这条博文（https://weibo.com/2698087403/Jo0wQurzG?from=page_1005052698087403_profile&wvr=6&mod=weibotime ）用你自己的微博号发，rss一样不会显示的

**Comment by HenryQW** [comment]
当前微博已经是通过移动端接口返回的数据了，如果有误就是微博接口的问题，与RSSHub无关

**Comment by 10362227** [comment]
@HenryQW  是游客不能看到一些特定文案的微博，添加cookie就可以了

**Comment by jimmy-walker** [comment]
@10362227 你好，请问该如何添加cookie呢？是将自己的微博登陆cookie值填在config.js中吗？

**Comment by 10362227** [comment]
@jimmy-walker 

/lib/routes/weibo/user.js

第24行
        headers: {
            Referer: `https://m.weibo.cn/u/${uid}`,
            'MWeibo-Pwa': 1,
            'X-Requested-With': 'XMLHttpRequest',
            'Cookie': 'XXXXXXXXXXXXXXXXXX',
        },

**Comment by shunf4** [comment]
这是微博登录墙的锅，有很多微博（可能是因为涉敏感内容）都需要登录才能看。

**Comment by 10362227** [comment]
@shunf4  不是。但敏感内容包括其中，还包括推广、一些特定词（特定词并未涉及敏感内容，还能上热搜，很迷）等等。感觉不准确，很多正常的微博也看不到
