### ISSUE TITLE
使用IFTTT把RSSHUB生成的RSS Feed发送给Pocket的时候只发送Feed的URL，不发送FEED文章内容

### ISSUE THREAD

**Issue by lunear** [DIYgod/RSSHub#5863]
- 完整路由地址，包含所有必选与可选参数
ifttt.com
- 预期是什么
把RSS的文章发送给Pocket
- 实际发生了什么
只发送RSS FEED文件的URL， 比如https://rsshub.app/wenxuecity/news， 而不显示文章内容
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by prnake** [comment]
@lunear Pocket只收url，ifttt也只发url

**Comment by lunear** [comment]
> @lunear Pocket只收url，ifttt也只发url

我用CNBETA的官方RSS测试，IFTTT是可以发送文章到Pocket的。

**Comment by yefoenix** [comment]
首先，路由地址填写不对；
> * 完整路由地址，包含所有必选与可选参数
>   ifttt.com
其次，这个应该先去问 ifttt和pocket，看pocket的接口标准是什么，ifttt是怎么取内容推过去的
……

**Comment by lunear** [comment]
> 首先，路由地址填写不对：
> 
> > * 完整路由地址，包含所有必选与可选参数
> >   ifttt.com
> 
> 其次，这个应该先去问 ifttt和pocket，看pocket的接口标准是什么，ifttt是怎么取内容推过去的

ifttt没有参数设置。只需要连接Pocket账号，然后添加RSS的URL就可以了。我也试了Zapier，一个跟IFTTT类似的多聚合服务网站，结果也是一样。貌似IFTTT不解析https://rsshub.app这个域名。

**Comment by HenryQW** [comment]
根据过往经验，IFTTT的rss标准就是个谜，我强烈怀疑问题出在它身上

**Comment by emdoe** [comment]
@lunear 抱歉我没有尝试过，想请问一下有没有试过指定 rsshub 生成 `atom` 之类的？（方法可见[文档](https://docs.rsshub.app/parameter.html#shu-chu-ge-shi)）
