### ISSUE TITLE
添加中参馆

### ISSUE THREAD

**Issue by NodeBE4** [DIYgod/RSSHub#5882]
### 网站地址
http://chinafile.org/
### 网站描述
美中关系中心的一个项目，有很多时事话题的圆桌讨论、观点和报告、新书发布等
### 需要生成什么内容？
按照网站栏目生成rss流，例如
观点和报告：https://www.chinafile.com/reporting-opinion
对话：https://www.chinafile.com/conversation
图书：https://www.chinafile.com/library
多媒体： https://www.chinafile.com/multimedia
### 额外描述
网站本身有[rss](https://feeds.feedburner.com/chinafile/All)，但不是全文

**Comment by yefoenix** [comment]
RSSHub 暂不接受已有 RSS feed 抓取全文的提案，如有能力可自行编写路由 PR 至本 Repo.
更简单的解决方式，是被抓取全文的工作交给RSS阅读器。
