### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dihambo** [DIYgod/RSSHub#5889]
- 完整路由地址，包含所有必选与可选参数
    `/bilibili/user/article/334958638`
- 预期是什么
xml地址
- 实际发生了什么
总是502
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 412 (Precondition Failed)
```

**Comment by HenryQW** [comment]
标题不写全是没有人会点进来看的。
