### ISSUE TITLE
windows npm 手动直接部署最新版本，安装 opencc 一直报错，无法完成部署

### ISSUE THREAD

**Issue by Sharewithyou** [DIYgod/RSSHub#5902]
![图片](https://user-images.githubusercontent.com/23255790/96083823-89b1c180-0ef0-11eb-92d6-3fbe62a719a1.png)

- 预期是什么

npm install  可以完成安装

- 实际发生了什么

opencc 下载安装遇到问题，导致部署失败

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   win2016 数据中心版           |
| Node version       |       12.10.0        |
| if Docker, version |        手动部署       |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
https://github.com/DIYgod/RSSHub/issues/4514
