### ISSUE TITLE
[BUG] 无法正常获取微博订阅

### ISSUE THREAD

**Issue by Leskur** [DIYgod/RSSHub#5903]
- 完整路由地址，包含所有必选与可选参数
    `/weibo/user/3518111501`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 418 (I'm a Teapot)
```

**Comment by shunf4** [comment]
这是新浪微博的反爬彩蛋，和 RSSHub 无关
