### ISSUE TITLE
微信>公众号 (二十次幂来源)

### ISSUE THREAD

**Issue by RaccoonXiaoxin** [DIYgod/RSSHub#5904]
二十次幂 网站的 URL 更换了，导致订阅链接失效

**Comment by Cay-Zhang** [comment]
这……不一直是 www.ershicimi.com 嘛

**Comment by RaccoonXiaoxin** [comment]
> 这......[[www.ershicimi.com]](http://www.ershicimi.com)

公众号对应 ID 换成 8 位的了
