### ISSUE TITLE
Twitter list RSS failed

### ISSUE THREAD

**Issue by jerryblues** [DIYgod/RSSHub#5906]
Twitter list changed, from:
https://rsshub.app/twitter/list/ladyleet/javascript
to:
https://twitter.com/i/lists/1058238584837173249

RSS failed

**Comment by TonyRL** [comment]
/twitter/list/ladyleet/**J**avascript still works
https://twitter.com/i/lists/1058238584837173249 can be subscribed using `/twitter/list/holmesforhs/hearthstone`
