### ISSUE TITLE
[BUG]【 中华人民共和国海关总署】源失效

### ISSUE THREAD

**Issue by allblue** [DIYgod/RSSHub#5914]
- 完整路由地址，包含所有必选与可选参数
    `/gov/customs/list/fagui`
- 预期是什么
  海关法规清单
- 实际发生了什么
 Response code 412 (Precondition Failed): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
- 部署相关信息
 rsshub.app演示服务器

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 412 (Precondition Failed)
```

**Comment by laampui** [comment]
`headers: {
  cookie: ''
}` 动态 cookie，需要使用 puppeteer 来请求了，后来人可以参考一下
