### ISSUE TITLE
pixiv订阅相关

### ISSUE THREAD

**Issue by woblitent** [DIYgod/RSSHub#5916]
- 完整路由地址，包含所有必选与可选参数
/pixiv/user/355065
/pixiv/user/illustfollows
- 预期是什么
正常抓取
- 实际发生了什么
Response code 400 (Bad Request): target website might be blocking our access
重启rsshub服务后，变为
pixiv not login

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | CentOS 7 -x86_64 |
| Node version       |v10.22.0|
| if Docker, version |               |

- 额外信息（日志、报错等）
看到有人说pixiv最近登陆端口强制走cloudflare机器人验证，不知是否有关

**Comment by ToffeeNeko** [comment]
问题相同，盯一下

**Comment by kuk111111** [comment]
+1

**Comment by prnake** [comment]
估计得换成 cookie 登录了

**Comment by jianfei96** [comment]
同样问题

**Comment by KaguraSenya** [comment]
同样问题

**Comment by qsdaqsdafqr** [comment]
相同问题，mark一下

**Comment by RJCooLEST** [comment]
ranking/day 也不工作，应该是加强了反爬措施。

**Comment by Azureki** [comment]
我也遇到了这个问题。
话说，pixiv 反爬和 ip 地址是否有关？如果是日本 ip 会更好吗？

**Comment by EHfive** [comment]
When login failed, it responds following HTML with code 403. I saved it and opening it in browser.

![Screenshot_20201020_115302](https://user-images.githubusercontent.com/24871166/96538302-d4ee1a80-12ca-11eb-8d37-ab7167d3c215.png)

A Cloudflare hCaptcha.
![Screenshot_20201020_115205](https://user-images.githubusercontent.com/24871166/96538312-dae3fb80-12ca-11eb-8f7f-bf08ae40786e.png)

**Comment by HinataKato** [comment]
同样问题，自建且已在环境里面加入账号密码一样是pixiv notlogin

**Comment by EHfive** [comment]
#5952 合并了， 使用最新版并添加 `PIXIV_BYPASS_CDN=1`可以解决/缓解此问题，详见最新中文文档https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 中的 `PIXIV_BYPASS_CDN`、`PIXIV_BYPASS_HOSTNAME`配置说明。

**Comment by jianfei96** [comment]
> #5952 合并了， 使用最新版并添加 `PIXIV_BYPASS_CDN=1`可以解决/缓解此问题，详见最新中文文档https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 中的 `PIXIV_BYPASS_CDN`、`PIXIV_BYPASS_HOSTNAME`配置说明。

感谢，已经好了

**Comment by Quan666** [comment]
我配置了`PIXIV_BYPASS_CDN=1`还是提示pixiv notlogin

**Comment by EHfive** [comment]
> 我配置了`PIXIV_BYPASS_CDN=1`还是提示pixiv notlogin

试试将DNS换成1.1.1.1? 似乎在国内 public-api.secure.pixiv.net 还是解析到 Cloudflare

**Comment by Quan666** [comment]
> > 我配置了`PIXIV_BYPASS_CDN=1`还是提示pixiv notlogin
> 
> 试试将DNS换成1.1.1.1? 似乎在国内 public-api.secure.pixiv.net 还是解析到 Cloudflare
> 或者将 PIXIV_BYPASS_HOSTNAME 设置为 public-api.secure.pixiv.net 通过1.1.1.1解析出的IP
设置`PIXIV_BYPASS_HOSTNAME=210.140.131.223`成功了

**Comment by EHfive** [comment]
> > > 我配置了`PIXIV_BYPASS_CDN=1`还是提示pixiv notlogin
> > 
> > 
> > 试试将DNS换成1.1.1.1? 似乎在国内 public-api.secure.pixiv.net 还是解析到 Cloudflare
> > 或者将 PIXIV_BYPASS_HOSTNAME 设置为 public-api.secure.pixiv.net 通过1.1.1.1解析出的IP
> 
> 设置`PIXIV_BYPASS_HOSTNAME=210.140.131.223`成功了

看来是DNS问题，我在准备一个DoH的修复

**Comment by HinataKato** [comment]
![image](https://user-images.githubusercontent.com/57648531/97092974-da58b580-167a-11eb-9298-12a65610ff40.png)
好像还是有问题 我也不知道是不是因为缓存

**Comment by MiTereKun** [comment]
I live on the Russian coast of the Japanese Sea, just 700 km from Japan, I have at least 3 trunk cables directly to the Japanese remains. But since all my ip's fall into the European zone, they also forcibly turned on cloudflare for me, which made pixiv noticeably slower. And recently, on the eve of the September elections, the authorities began to break the cloudflare itself and the Internet floor, and yesterday the pictures were loaded so slowly. I felt like a citizen of China
