### ISSUE TITLE
饭否 fanfou/home_timeline 返回 FanfouError: Invalid consumer

### ISSUE THREAD

**Issue by HaitianLiu** [DIYgod/RSSHub#5926]
- 完整路由地址，包含所有必选与可选参数
/fanfou/home_timeline
- 预期是什么
正常返回结果
- 实际发生了什么
返回报错
```
FanfouError: Invalid consumer
    at Fanfou.xauth (/Users/liuhaitian/Code/RSSHub/node_modules/fanfou-sdk/src/index.js:108:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       linux        |
| Node version       |       10.13.0        |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by yefoenix** [comment]
@HaitianLiu 是否正确配置了相关变量？

**Comment by HaitianLiu** [comment]
> @HaitianLiu 是否正确配置了相关变量？

应该是配置正确了，我这里的应用在饭否开发者平台显示未审核，是原因吗？

**Comment by junbaor** [comment]
> > @HaitianLiu 是否正确配置了相关变量？
> 
> 应该是配置正确了，我这里的应用在饭否开发者平台显示未审核，是原因吗？

饭否前一阵收紧了 api 权限，需要开发者的身份信息，具体说明见 https://fanfou.com/statuses/uWVZZ0PAFv4

**Comment by NeverBehave** [comment]
后续如果还有问题请重新打开issue
