### ISSUE TITLE
Twitter 抓取的用户推文正文格式乱了

### ISSUE THREAD

**Issue by mashirozx** [DIYgod/RSSHub#5927]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/twitter/user/googledoodles

- 预期是什么
原本的description类似下面的格式：

> `<description><![CDATA[流程图工具 Excalidraw 可以做出下面这样的图示效果，可 惜中文没有手写效果。<a href="https://excalidraw.com/" target="_blank" rel="noopener noreferrer">https://excalidraw.com/</a><br><img src="https://pbs.twimg.com/media/EZJh5RPUMAEz4aS?format=jpg&name=orig" referrerpolicy="no-referrer">]]></description>`

- 实际发生了什么
现在（大概今天中午开始出现的问题）抓取到的包括了头像信息和许多多余的HTML标签

> `<description><![CDATA[<a href="https://twitter.com/GoogleDoodles"><img align="left" src="https://pbs.twimg.com/profile_images/1274058266981494784/lfPByEvt_normal.jpg" hspace="8" vspace="8" referrerpolicy="no-referrer"><strong>Google Doodles</strong></a>:  A #GoogleDoodle for Indian dancer & actress Zohra Segal, one of the country's first actresses to be recognized internationally 🎥<br><br>🎨 by guest artist Parvati Pillai →<br><a href="http://goo.gle/2CavFeW" target="_blank" rel="noopener noreferrer">http://goo.gle/2CavFeW</a><br clear="both"><div style="clear: both"></div><a href="https://pbs.twimg.com/media/EjGVMXyXkAAsK0S?format=jpg&name=orig"><img hspace="4" vspace="8" src="https://pbs.twimg.com/media/EjGVMXyXkAAsK0S?format=jpg&name=orig" referrerpolicy="no-referrer"></a><hr><small>9/30/2020, 1:21:04 AM</small>]]></description>`

- 部署相关信息
rsshub.app

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by shunf4** [comment]
#5886 正在讨论
