### ISSUE TITLE
雪球RSS不能用了

### ISSUE THREAD

**Issue by chongxu-bc** [DIYgod/RSSHub#5931]
路由地址
/xueqiu/user/:id/:type?
/xueqiu/user_stock/:id
/xueqiu/snb/:id

预期是什么？
获取雪球动态、自选、组合的更新

实际发生了什么？
出现错误：Looks like something went wrong
TypeError: Cannot read property 'stocks' of undefined
TypeError: Cannot read property 'filter' of undefined
Error: wrong path
不能显示订阅列表

部署相关信息
官方地址
额外信息（日志、报错等）
目标地址：https://rsshub.app/xueqiu/user/8152922548
https://rsshub.app/xueqiu/user_stock/1247347556
https://rsshub.app/xueqiu/p/ZH1288184

**Comment by HenryQW** [comment]
估计是demo缓存出了问题，本地没有问题
![image](https://user-images.githubusercontent.com/5896343/96378841-c26ac880-1186-11eb-8102-bcccbbc506ce.png)
![image](https://user-images.githubusercontent.com/5896343/96378848-c8f94000-1186-11eb-8994-05c80196ef81.png)


https://rsshub.app/xueqiu/p/ZH1288184 没发现相关路由

**Comment by chongxu-bc** [comment]
那要怎么解决啊

**Comment by chongxu-bc** [comment]
那要咋办啊，大佬，静静等服务器恢复正常？

> 估计是demo缓存出了问题，本地没有问题
> 
> ![image](https://user-images.githubusercontent.com/5896343/96378841-c26ac880-1186-11eb-8102-bcccbbc506ce.png)
> 
> ![image](https://user-images.githubusercontent.com/5896343/96378848-c8f94000-1186-11eb-8994-05c80196ef81.png)
> 
> 
> 
> 
> 
> https://rsshub.app/xueqiu/p/ZH1288184 没发现相关路由
