### ISSUE TITLE
成功运行但不读取.ENV文件内的内容

### ISSUE THREAD

**Issue by Liangyu-G** [DIYgod/RSSHub#5937]
- 完整路由地址，包含所有必选与可选参数
/twitter/user/:id/:type?
- 预期是什么
正常拉取
- 实际发生了什么
RSSHUB没有读取.env文件，导致没有配置代理，拉取失败
- 部署相关信息
正常运行，但不读配置文件

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by Liangyu-G** [comment]
> * 完整路由地址，包含所有必选与可选参数
>   /twitter/user/:id/:type?
> * 预期是什么
>   正常拉取
> * 实际发生了什么
>   RSSHUB没有读取.env文件，导致没有配置代理，拉取失败
> * 部署相关信息
>   正常运行，但不读配置文件
> 
> Env	Value
> OS	Windows Sever 2019
> Node version	6.13.4
> if Docker, version	
> * 额外信息（日志、报错等）
PS C:\Users\Administrator\Desktop\Rsshub\RSSHub-master> npm start

> rsshub@1.0.0 start C:\Users\Administrator\Desktop\Rsshub\RSSHub-master
> node lib/index.js

info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!

**Comment by HenryQW** [comment]
ENV格式错误？https://docs.rsshub.app/install/#pei-zhi-dai-li-pei-zhi

**Comment by Liangyu-G** [comment]
>  ENV格式错误？https://docs.rsshub.app/install/#pei-zhi-dai-li-pei-zhi

不是的，之前是有用的，但现在不知道怎么回事，突然不行了，什么都没改

**Comment by HenryQW** [comment]
相关代码没改动过，我自建没问题

**Comment by Liangyu-G** [comment]
已解决，重新搭建了一次
