### ISSUE TITLE
[BUG] 公众号 (二十次幂来源) 的 RSS 源再次无法打开

### ISSUE THREAD

**Issue by RaccoonXiaoxin** [DIYgod/RSSHub#5941]
以“差评”公众号为例，https://rsshub.app/wechat/ershicimi/zNjpAbQB ，
会提示“Error 502 Ray ID: 5e4999782b49fce5 • 2020-10-19 09:51:15 UTC”，试过其他的公众号也会产生类似问题，请安排检查，谢谢

**Comment by Cay-Zhang** [comment]
自建正常
