### ISSUE TITLE
[BUG]【雪球-用户自选动态】订阅失败

### ISSUE THREAD

**Issue by iewgnaw** [DIYgod/RSSHub#5947]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/xueqiu/user_stock/1247347556

- 预期是什么
   该用户的自选股票

- 实际发生了什么
![image](https://user-images.githubusercontent.com/8124296/96527695-58037680-12b3-11eb-84d5-fe00f549213f.png)

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
目标链接可用
