### ISSUE TITLE
lofter 官方的 RSS 已经没有了，rsshub 最新官方文档中也没有用户的rss路由

### ISSUE THREAD

**Issue by Sharewithyou** [DIYgod/RSSHub#5978]
- 完整路由地址，包含所有必选与可选参数

官方提供了用户主页 RSS: http://:username.lofter.com/rss 不可用了，rsshub 文档没相关路由

- 预期是什么

返回用户的RSS

- 实际发生了什么

官方的返回为空，RSSHUB 官方文档中也没有相关的路由

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

![image](https://user-images.githubusercontent.com/23255790/96967323-eab94500-1541-11eb-8c9d-41a0b2fc9d50.png)

**Comment by HenryQW** [comment]
你的文档版本太久了，右下角没有提示刷新吗？
![image](https://user-images.githubusercontent.com/5896343/97024531-d4fe4c80-154e-11eb-96e0-5dbc251c4b7a.png)

**Comment by Sharewithyou** [comment]
谢谢 不过 文档没有提示刷新

**Comment by RosaDai** [comment]
> 你的文档版本太久了，右下角没有提示刷新吗？
> ![image](https://user-images.githubusercontent.com/5896343/97024531-d4fe4c80-154e-11eb-96e0-5dbc251c4b7a.png)

现在这个也用不了了，请问你的还可以用吗
