### ISSUE TITLE
提供开关以关闭访问控制验证失败时的调用栈信息输出

### ISSUE THREAD

**Issue by SylleoYr** [DIYgod/RSSHub#5982]
### 这是一个什么样的功能？

当开启 `ACCESS_KEY` 后，不添加 Key 或者用错误的 Key 访问路由时，提示 `Access denied` 的同时输出了调用栈信息，`DEBUG_INFO` 设置为 0 只关闭了首页输出信息。希望在访问控制验证失败的时候可以只提示 `Access denied`并返回 403，而不是输出整个调用栈信息。

### 这个功能可以解决什么问题？

没有具体深入了解 RSSHub 的实现方式，但一般来说，生产环境中应当避免输出此类信息，避免被利用（尽管这是一个开源项目 😝）。希望可以提供选项以控制关闭和开启该输出。

**Comment by HenryQW** [comment]
有例子吗
