### ISSUE TITLE
RSS 全文代理

### ISSUE THREAD

**Issue by linsui** [DIYgod/RSSHub#6003]
### 这是一个什么样的功能？
代理网站提供的 rss，并可选择通过 rsshub 的全文输出功能转换为全文输出。路由可设置为 `/rss/:url` 或 `/feed/:url`。类似 [morss](https://github.com/pictuga/morss)。

### 这个功能可以解决什么问题？
很多网站提供了 rss 但未提供全文。其中一部分可以通过 rsshub 的全文输出功能自动抓取全文而无需创建新的路由。

**Comment by hoilc** [comment]
建议使用RSS阅读器实现

**Comment by linsui** [comment]
请问您说的阅读器指的是 feedly 等服务吗？可以说明一下不实现此功能的原因吗？谢谢！

**Comment by emdoe** [comment]
> 可以说明一下不实现此功能的原因吗？

我个人没有太看懂您的需求，是希望 RSSHub 将一个不能输出全文的 RSS 订阅源输出全文么？

**Comment by HenryQW** [comment]
> 请问您说的阅读器指的是 feedly 等服务吗？可以说明一下不实现此功能的原因吗？谢谢！

全文输出都是通过类似[mercury](https://github.com/postlight/mercury-parser)实现的，会呈指数级增加RSSHub的依赖以及资源需求，所以不考虑增加该功能。

**Comment by emdoe** [comment]
BTW 我个人的想法是，如果是希望全文输出某一个网站的内容——为其专门来制作 RSS，显然显示效果更好。但是否去做，则很大程度上取决于信息本身的价值：更多的朋友认可该网站所提供内容的价值，更有可能会有贡献者来做；如果您认为该信息对您非常有价值，我建议您可以考虑自己来制作，有问题可以大家来讨论。

但如果希望的是通用性质的，让 RSSHub 全文输出所有不能提供全文的 RSS 源，我作为旁观者（？）也会觉得这个要求有些未免太高了。除去 @HenryQW 提及的之外，一方面有您提及的，专门来做这样工作的项目，另一方面，输出效果难免也不及现在更「手动」的方法的成品。

以上想法谨供您参考，若我最初就误解了您的需要，还请指正。

**Comment by linsui** [comment]
> 我个人没有太看懂您的需求，是希望 RSSHub 将一个不能输出全文的 RSS 订阅源输出全文么？

是的，包括直接代理。

> 全文输出都是通过类似mercury实现的，会呈指数级增加RSSHub的依赖以及资源需求，所以不考虑增加该功能。

了解了，谢谢。

**Comment by linsui** [comment]
> 
> 
> BTW 我个人的想法是，如果是希望全文输出某一个网站的内容——为其专门来制作 RSS，显然显示效果更好。但是否去做，则很大程度上取决于信息本身的价值：更多的朋友认可该网站所提供内容的价值，更有可能会有贡献者来做；如果您认为该信息对您非常有价值，我建议您可以考虑自己来制作，有问题可以大家来讨论。
> 
> 但如果希望的是通用性质的，让 RSSHub 全文输出所有不能提供全文的 RSS 源，我作为旁观者（？）也会觉得这个要求有些未免太高了。除去 @HenryQW 提及的之外，一方面有您提及的，专门来做这样工作的项目，另一方面，输出效果难免也不及现在更「手动」的方法的成品。
> 
> 以上想法谨供您参考，若我最初就误解了您的需要，还请指正。

是的，自动提取效果不如手动。不过 RSSHub 使用 js 脚本而非配置文件的方法制作订阅源，对于很多人有些门槛。而已有的提取全文的功能正好满足了这一需求，所以我提出了这一请求，不过没有考虑到资源等问题。谢谢您的说明。

**Comment by emdoe** [comment]
我更建议直接提出您现阶段希望输出全文的源是什么，这样更可能有朋友来帮助，若源本身即为聚合性的源，那恐怕就爱莫能助了…

**Comment by emdoe** [comment]
> 不过 RSSHub 使用 js 脚本而非配置文件的方法制作订阅源，对于很多人有些门槛。而已有的提取全文的功能正好满足了这一需求，所以我提出了这一请求

@HenryQW 我觉得也许确实有必要改善一下文档，更进一步降低上手难度…？

**Comment by linsui** [comment]
> 
> 
> 我更建议直接提出您现阶段希望输出全文的源是什么，这样更可能有朋友来帮助，若源本身即为聚合性的源，那恐怕就爱莫能助了…

我一直想要贡献几个订阅源，自己动手丰衣足食嘛。只是最近时间不多。:joy:

**Comment by shunf4** [comment]
现有的服务不少，只是操作逻辑和你所说有差异，不能把要代理的 URL 放在 RSSHub 的 URL 上：
https://www.google.com/search?q=rss+to+full+text

我个人在用自建的 https://f43.me

**Comment by HenryQW** [comment]
> > 不过 RSSHub 使用 js 脚本而非配置文件的方法制作订阅源，对于很多人有些门槛。而已有的提取全文的功能正好满足了这一需求，所以我提出了这一请求
> 
> @HenryQW 我觉得也许确实有必要改善一下文档，更进一步降低上手难度…？

很难写出一个从零到精通的教程，基本上就相当于写一本《node.js 从开始到放弃》

**Comment by emdoe** [comment]
> 很难写出一个从零到精通的教程

唔…我个人的想法天真一点——因为我觉得可以提新路由 request 的朋友大致包括两种：

1. 已经对项目有一定熟悉程度，或者完全能自己写的朋友，提 issue 的目的是标记，自己会稍后来实现
2. 对项目不熟悉的，或暂时没有能力来完成的，这一部分最大的困难是，不知道先有的文档哪里还不够清楚，所以会不知道如何进一步来改善文档

所以针对 2，我个人的想法（建议）是现阶段也许可以进一步改善 issue 的 template，鼓励大家首先去看文档，并自己来尝试制作（毕竟每个人的时间都很宝贵，~~当然依传统（？）发女装照可以豁免这一项~~），在提 issue 的同时写出自己卡在文档哪里（比如不知道如何安装？还是不知道应该选用哪一种方式抓取？），这样通过 issue 也许可以更有针对性的改善文档。

**Comment by linsui** [comment]
> 我个人在用自建的 https://f43.me

谢谢分享，我前面也提到了相似的服务。不过它们部署比 RSSHub 更加困难。

> 很难写出一个从零到精通的教程，基本上就相当于写一本《node.js 从开始到放弃》

使用脚本灵活性很高但门槛也很高。从我的角度来讲，对于非程序员学习 js 本身就有难度。我给 [Scoop](https://github.com/ScoopInstaller) 项目写过不少安装清单，因为它是以 json 为主，上手很容易，同时嵌入 ps 脚本做一些复杂的工作应对特殊情况。说起来，Scoop 和 RSSHub 的作用差不多，都是监视更新提取内容。:joy: 如果 RSSHub 采用配置文件和脚本结合的方式，或许会对非程序员更友好。目前的方式，js 的门槛绕不过去。

**Comment by shunf4** [comment]
可以看看 ftr-site-config 这种针对各大网站配置文件集合（简单，类似 yaml，使用 XPath，可以可视化生成，但碰到需要 JavaScript 生成主要内容的网站就没用了）， graby 和 f43.me 都在用，如果需要实现类似功能可以参考使用。（或者有更全更好的规则配置集？）

**Comment by HenryQW** [comment]
> > 很难写出一个从零到精通的教程
> 
> 唔…我个人的想法天真一点——因为我觉得可以提新路由 request 的朋友大致包括两种：
> 
> 1. 已经对项目有一定熟悉程度，或者完全能自己写的朋友，提 issue 的目的是标记，自己会稍后来实现
> 2. 对项目不熟悉的，或暂时没有能力来完成的，这一部分最大的困难是，不知道先有的文档哪里还不够清楚，所以会不知道如何进一步来改善文档
> 
> 所以针对 2，我个人的想法（建议）是现阶段也许可以进一步改善 issue 的 template，鼓励大家首先去看文档，并自己来尝试制作（毕竟每个人的时间都很宝贵，~当然依传统（？）发女装照可以豁免这一项~ [1]），在提 issue 的同时写出自己卡在文档哪里（比如不知道如何安装？还是不知道应该选用哪一种方式抓取？），这样通过 issue 也许可以更有针对性的改善文档。
> 
> [1] BTW 我觉得发掘出「优质内容」的也可以豁免，这样更有分工的感觉。~换而言之，我可能反倒希望，可以稍稍减少一些单纯希望别人来方便自己的朋友。~

针对2，不可避免的，有时候review新手代码的时间比自己完成这个PR更久。。

采摘自《RSSHub维护者的自白：通往删库的基情之路》

**Comment by emdoe** [comment]
😂😂😂 拍…下次碰到这种情况请一定要 @ 我一下！
