### ISSUE TITLE
哔哩哔哩-用户关注动态

### ISSUE THREAD

**Issue by TigerWolfDen** [DIYgod/RSSHub#6011]
### 网站地址
https://www.bilibili.com/
### 网站描述
视频网站
### 需要生成什么内容？
当前用户关注的全部动态内容
### 额外描述
与Rsshub目前已有的 “用户关注视频动态” 和 “用户关注专栏” 路由类似，但我希望能够显示我关注的所有动态内容，而不仅仅是视频动态和专栏动态等。也就是输出 https://t.bilibili.com/ 下的所有动态内容。

**Comment by ruleroller** [comment]
同需要，不过不要破坏目前的 “用户关注视频动态” 和 “用户关注专栏” 的已有路由，另开一个路由为宜。
