### ISSUE TITLE
[BUG]大部分NGA帖子RSS都报错，演示帖子以及部分帖子RSS有效

### ISSUE THREAD

**Issue by antitail** [DIYgod/RSSHub#6073]
- 完整路由地址，包含所有必选与可选参数
    `/nga/post/22662212`
- 预期是什么
    能够正常显示xml
- 实际发生了什么
    Error message: connect ETIMEDOUT 125.77.154.35:443: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
- 部署相关信息

- 额外信息（日志、报错等）
```
    connect ETIMEDOUT 125.77.154.35:443
```

**Comment by totorowechat** [comment]
> * NGA BBS 用于获取帖子内文
>   * NGA_PASSPORT_UID: 对应 cookie 中的 ngaPassportUid.
>   * NGA_PASSPORT_CID: 对应 cookie 中的 ngaPassportCid.

https://github.com/DIYgod/RSSHub/blob/b9e3a6d5751b0283ad3e9a67b0c2d93b225b624d/lib/config.js#L167-L170

加上你自己cookie 中的cid和uid应该就可以了。
