### ISSUE TITLE
希望能增加 黑白直播 https://www.heibaizhibo.com 的主播们直播间的开播提醒

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#6092]
### 网站地址
https://www.heibaizhibo.com
### 网站描述
这是一个体育赛事直播网站
### 需要生成什么内容？
主播们直播间的开播提醒

直播间举例：https://www.heibaizhibo.com/anchorLive/195976
### 额外描述
恳请有余力的大佬们能做一下，对追一些赛事很有帮助的！谢谢啦！

**Comment by ruleroller** [comment]
@laampui 大佬大佬，有空做一下吗，和猎趣的比较像的。：）

**Comment by laampui** [comment]
这周晚点看看
