### ISSUE TITLE
Not having Weibo ID, only Weibo screen name?

### ISSUE THREAD

**Issue by typesoshee** [DIYgod/RSSHub#6095]
If I have a Weibo screen name but no ID, it seems that I can't get a RSS feed. For example, https://rsshub.app/weibo/user/1833141401
works but what if I only have the screen name, like this:
https://weibo.com/geinchina
I wouldn't be able to do 
https://rsshub.app/weibo/user/geinchina

For example, I have this screen name:
https://weibo.com/TeradaRanze
How would I get the ID? 

### What feature is it?
Perhaps the feature can be a way to use the screen name, like this:
https://rsshub.app/weibo/user/geinchina
or
https://weibo.com/TeradaRanze

### What problem does this feature solve?
Having a Weibo screen name but no weibo ID.

### Additional description
Thank you!

**Comment by typesoshee** [comment]
Actually, I found one way to do this, though it depends on another website. Go here:
https://rssfeed.today/weibo/
paste in the URL of the weibo account that has a screen name (without a weibo ID), and the RSS feed URL that it produces will have the weibo ID number in it.

**Comment by Cay-Zhang** [comment]
RSSHub Radar can also generate the correct user ID.

**Comment by Geeyun-JY3** [comment]
See [doc](https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu)
![image](https://user-images.githubusercontent.com/49396421/98234707-c62a8780-1f9b-11eb-8435-13720be0e870.png)

**Comment by typesoshee** [comment]
Thank you very much for your replies and help!
