### ISSUE TITLE
【Bug report】|巨潮资讯|  网站改版导致报错，rsshub.app报错Error message: wrong path

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#6102]
- 完整路由地址，包含所有必选与可选参数

/cninfo/announcement/:column/:code/:orgId/:category?

 参数:

    column, 必选 -

    szse 深圳证券交易所; sse 上海证券交易所; third 新三板; hke 港股; fund 基金
    code, 必选 -

    股票或基金代码
    orgId, 必选 -

    orgId 组织 id
    category, 可选 -

    公告分类，A 股及新三板 

column 为 szse 或 sse 时可选的 category:

一季报 | 三季报 | 业绩预告 | 权益分派 | 董事会 | 监事会 | 股东大会 | 日常经营 | 公司治理 | 中介报告 | 首发 | 增发 | 股权激励 | 配股 | 解禁 | 公司债 | 可转债 | 其他融资 | 股权变动 | 补充更正 | 澄清致歉 | 风险提示 | 特别处理和退市 | 退市整理期
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
category_ndbg_szsh | category_bndbg_szsh | category_yjdbg_szsh | category_sjdbg_szsh | category_yjygjxz_szsh | category_qyfpxzcs_szsh | category_dshgg_szsh | category_jshgg_szsh | category_gddh_szsh | category_rcjy_szsh | category_gszl_szsh | category_zj_szsh | category_sf_szsh | category_zf_szsh | category_gqjl_szsh | category_pg_szsh | category_jj_szsh | category_gszq_szsh | category_kzzq_szsh | category_qtrz_szsh | category_gqbd_szsh | category_bcgz_szsh | category_cqdq_szsh | category_fxts_szsh | category_tbclts_szsh | category_tszlq_szsh

column 为 third 时可选的 category:

临时公告 | 定期公告 | 中介机构公告 | 持续信息披露 | 首次信息披露
-- | -- | -- | -- | --
category_lsgg | category_dqgg | category_zjjg | category_cxpl | category_scpl

- 预期是什么

正常推送

- 实际发生了什么

例子：[https://rsshub.app/cninfo/stock_announcement/szse/000002/gssz0000002/category_ndbg_szsh](https://rsshub.app/cninfo/stock_announcement/szse/000002/gssz0000002/category_ndbg_szsh)

 rsshub.app报错
```
Error message: wrong path
```
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

###
谢谢

**Comment by KwToPA** [comment]
@nczitzk 您好，依然反馈
```
Looks like something went wrong

Route requested: /cninfo/stock_announcement/szse/000002/gssz0000002/category_ndbg_szsh

Error message: wrong path
```
应该是网站最近的一次改版导致的问题，不单是rsshub的例子出错。

### 谢谢

**Comment by KwToPA** [comment]
@HenryQW  您好，相同问题依然报错，申请重开这个问题，谢谢

**Comment by HenryQW** [comment]
路径变了 

https://rsshub.app/cninfo/announcement/szse/000002/gssz0000002/category_ndbg_szsh

**Comment by nczitzk** [comment]
> @nczitzk 您好，依然反馈
> 
> ```
> Looks like something went wrong
> 
> Route requested: /cninfo/stock_announcement/szse/000002/gssz0000002/category_ndbg_szsh
> 
> Error message: wrong path
> ```
> 
> 应该是网站最近的一次改版导致的问题，不单是rsshub的例子出错。
> 
> ### 谢谢

你好，关于这个路由的变更情况是这样的：

@laampui 在 9fb1455 中修复了因该网站样式变更带来的错误，合并 /stock_announcement 和 /fund_announcement 到 /announcement，并且提供了更完整的参数表 🎉

于是，原路由 `/cninfo/stock_announcement/:code` 是不可用的，现路由应是 `/cninfo/announcement/:column/:code/:orgId/:category?/:search?`，所以 `/cninfo/announcement/szse/000002/gssz0000002/category_ndbg_szsh` 才是现在可用的路由。

**Comment by KwToPA** [comment]
@HenryQW ,@nczitzk  抱歉，没仔细看。 已经正常工作了，谢谢二位。
