### ISSUE TITLE
【RSS-Wanted】建议增加得到、知识城邦RSS

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#6110]
### 网站地址
得到以及旗下知识城邦:
https://www.dedao.cn/knowledge
https://www.igetget.com
### 网站描述
强烈推荐！！！
高端知识学习平台
得到APP，旨在为用户提供“省时间的高效知识服务”，由罗辑思维团队出品。
搜索感兴趣的知识，学习相关课程、电子书、听书。罗振宇·罗辑思维、武志红·心理学等100多位专家学者的独家课程
### 需要生成什么内容？
得到以及旗下知识城邦RSS：
1、知识城邦话题：https://www.dedao.cn/knowledge/topic/rQ0yp9avlBpGYRjbdp3mD1ELxJomg4
2、用户主页动态 :https://m.igetget.com/share/user/pBAjReY3wKd1aYl3mjP1g47m5ZyDrE
3、首页,比如自然科学分类：https://www.igetget.com/list/%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6/73luADt8fjcn
4、得到大事件（包括新闻、人物故事）：https://www.igetget.com/news
5、最新视频：https://www.igetget.com/video

**Comment by ZhuningS** [comment]
含有API等：
https://www.dedao.cn/pc/ledgers/topic/notes/list
https://www.dedao.cn/pc/ledgers/topic/detail

**Comment by HenryQW** [comment]
https://docs.rsshub.app/new-media.html#de-dao-zhi-shi-cheng-bang
