### ISSUE TITLE
【rss-bug】什么值得买-好文分类出现无法抓取

### ISSUE THREAD

**Issue by longlegmax** [DIYgod/RSSHub#6111]
- 完整路由地址，包含所有必选与可选参数
 https://rsshub.app/smzdm/haowen/fenlei/shenghuodianqi
- 预期是什么
什么值得买的好文分类出现无法抓取
应该是什么值得买网站更新导致，原来分类使用的是https://post.smzdm.com/fenlei/zuixin/
现在改成
https://post.smzdm.com/tab/zuixin/
- 实际发生了什么
导致无法抓取好文分类
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by HenryQW** [comment]
本地与demo均可用。

![image](https://user-images.githubusercontent.com/5896343/98413478-96e64a00-2071-11eb-9236-51673ed078af.png)

![image](https://user-images.githubusercontent.com/5896343/98413505-a1084880-2071-11eb-966a-019d9baf9e26.png)
