### ISSUE TITLE
建议将OpenCC改为Optional Dependency

### ISSUE THREAD

**Issue by RtYkk** [DIYgod/RSSHub#6112]
安装方式：源码+npm
        不得不说，OpenCC是整个安装过程中的最大阻碍。我个人就遇到了两次问题，而并不是每个人都有R繁体内容的需求，也并不是每个人都希望做简繁转换。
        第一次，我全新安装时，直接就报错了，就是这该死的OpenCC，搜了下才知道是缺编译库了OpenCC要自行编译，装了个编译库才解决，反复好几次…还要反复删除```node_modules```文件夹。
        第二次，几个月没更新了，git pull开开心心准备更新，又又又报错了！仔细一看还是OpenCC，告诉我nodejs的版本不对，和编译的时候不是一个版本，我真是吐血。还好我用```nvm```管理nodejs版本我才快速切换到了正确的版本来解决问题…
        虽然两次我都解决了，但是花费了我一定的时间和精力，体验并不好。而且不得不说，OpenCC并不是一个强依赖，不装也能用，而且RSSHub的其他部分好像并没有类似问题，一个```npm install```就可以完美安装，为了这样一个非必须依赖实在是…得不偿失
        因此，我建议，将OpenCC作为可选安装项（目前的安装方式好像不支持这样？）或者剥离出去让用户单独自行安装（P.S. 在文档内写出安装方法，使用配置文件控制OpenCC的开关）

附：
https://t.me/rsshub/187649
https://t.me/rsshub/188812
https://t.me/rsshub/189731
https://t.me/rsshub/190208

谢谢，Developer辛苦了。

**Comment by HenryQW** [comment]
有一种部署叫做容器🐳

**Comment by TigerWolfDen** [comment]
> 有一种部署叫做容器🐳

开发的时候还是需要手动部署（例如调试自己编写的新路由）

**Comment by ruleroller** [comment]
删掉模块文件夹重新安装一次就行了，之后就没什么问题了。

选配安装的话，你不知道别人搭建的是不是装了，更是平添麻烦啊。

**Comment by raiots** [comment]
> 第一次，我全新安装时，直接就报错了，就是这该死的OpenCC，搜了下才知道是缺编译库了OpenCC要自行编译，装了个编译库才解决，反复好几次…还要反复删除`node_modules`文件夹。

可以详细说一下自行编译opencc后怎样在npm中安装吗，快被opencc搞崩了😭

当前进度：已编译完成opencc，并添加至系统变量。

谢谢！

**Comment by RtYkk** [comment]
@raiots 自行编译你是指单独编译了[这个](https://github.com/BYVoid/OpenCC)吗？似乎你方向错了。
1、安装编译依赖

> CentOS
> `yum install gcc* automake zlib-devel libjpeg-devel giflib-devel freetype-devel
yum -y install make gcc-c++ cmake bison-devel ncurses-devel`

> Debian/Ubuntu
> `sudo apt-get install zlib1g-dev libbz2-dev libssl-dev libncurses5-dev libsqlite3-dev libreadline-dev tk-dev libgdbm-dev libdb-dev libpcap-dev xz-utils libexpat-dev`

[Reference](https://www.jianshu.com/p/edd3b1b4ac6b)，具体需要的我也不知道是哪个，反正我装了一串。
2、进入RSSHub文件夹
3、删除`node_modules`
4、再来一次`npm install --production`

大概就能解决了，我上次好像就是这样的……

**Comment by raiots** [comment]
解决了！
非常感谢ヾ(•ω•`)o

**Comment by HenryQW** [comment]
啥都没做，macOS 下直接 yarn 没有报错。

node v14.12.0
npm 6.14.8
yarn 1.22.10

**Comment by casprwang** [comment]
遇到过类似问题，不同platform的环境不同；node.js版本也会有影响，我的经验：

如果是Linux distribution, eg. Ubuntu
1. 尽量使用 Node 10
2. `apt-get update` + `sudo apt-get install build-essential`
3. 尽量使用 yarn

**Comment by RtYkk** [comment]
既然更改无望，我把报错信息贴上来供后人解决类似问题。
`Error: The module '/root/RSSHub/node_modules/opencc/build/Release/opencc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1126:18)
at Module.load (internal/modules/cjs/loader.js:940:32)
at Function.Module._load (internal/modules/cjs/loader.js:781:14)
at Module.require (internal/modules/cjs/loader.js:964:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/root/RSSHub/node_modules/opencc/node/opencc.js:31:17)
at Module._compile (internal/modules/cjs/loader.js:1075:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
at Module.load (internal/modules/cjs/loader.js:940:32)
at Function.Module._load (internal/modules/cjs/loader.js:781:14)
at Module.require (internal/modules/cjs/loader.js:964:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/root/RSSHub/lib/middleware/parameter.js:4:16)
at Module._compile (internal/modules/cjs/loader.js:1075:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
at Module.load (internal/modules/cjs/loader.js:940:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsshub@1.0.0 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsshub@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-10-31T11_40_16_248Z-debug.log`
