### ISSUE TITLE
docker build镜像的时候报这个错

### ISSUE THREAD

**Issue by a14907** [DIYgod/RSSHub#6122]
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code ENOMEM
npm ERR! syscall spawn
npm ERR! errno ENOMEM
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/postlight/browser-request.git
npm ERR! 
npm ERR! undefined
npm ERR! spawn ENOMEM

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-07T05_05_54_780Z-debug.log

我换成 npm install --production 还是提示错误，看了日志，是这样的：

20797 warn @postlight/mercury-parser@2.2.0 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
20798 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
20799 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20800 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20800 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20800 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20800 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20801 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
20802 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20803 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20803 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20803 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20803 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20804 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@vuepress/core/node_modules/chokidar/node_modules/fsevents):
20805 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20806 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20806 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20806 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20806 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20807 warn notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.4.0","npm":"6.14.5"})
20808 warn notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
20809 verbose notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
20809 verbose notsup Required: {"node":"<8.10.0"}
20809 verbose notsup Actual:   {"npm":"6.14.5","node":"14.4.0"}
20810 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
20811 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20812 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20812 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20812 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20812 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20813 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
20814 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
20815 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
20815 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
20815 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
20815 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
20816 warn acorn-jsx@5.3.1 requires a peer of acorn@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
20817 warn optional SKIPPING OPTIONAL DEPENDENCY: http-headers@3.0.2 (node_modules/@postlight/mercury-parser/node_modules/http-headers):
20818 warn optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'type' of undefined
20819 verbose stack Error: opencc@1.1.1 install: `node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild`
20819 verbose stack Exit status 1
20819 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
20819 verbose stack     at EventEmitter.emit (events.js:315:20)
20819 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
20819 verbose stack     at ChildProcess.emit (events.js:315:20)
20819 verbose stack     at maybeClose (internal/child_process.js:1051:16)
20819 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
20820 verbose pkgid opencc@1.1.1
20821 verbose cwd /root/code/RSSHub
20822 verbose Linux 3.10.0-1127.10.1.el7.x86_64
20823 verbose argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "install" "--production"
20824 verbose node v14.4.0
20825 verbose npm  v6.14.5
20826 error code ELIFECYCLE
20827 error errno 1
20828 error opencc@1.1.1 install: `node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild`
20828 error Exit status 1
20829 error Failed at the opencc@1.1.1 install script.
20829 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by HenryQW** [comment]
说实话你这什么系统环境都没贴出来，没人可以帮你。

我在本地macos以及树莓派build都没有问题。
