### ISSUE TITLE
[Bug]按文档在网易号文章页面无法找到网易号 ID

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#6133]
- 完整路由地址，包含所有必选与可选参数
比如果壳 https://dy.163.com/v2/media/T1374539968172.html
- 预期是什么
正常运行
- 实际发生了什么

打开网易号文章页面后，通过浏览器控制台执行 $('#contain').dataset.wemediaid，执行失败，无法找到网易号 ID。

- 额外信息（日志、报错等）
chrome控制台提示：VM245:1 Uncaught TypeError: Cannot read property 'dataset' of null
    at <anonymous>:1:14

**Comment by HenryQW** [comment]
#6128 修复了这个问题
