### ISSUE TITLE
服务器端 puppeteer 浏览器进程报错

### ISSUE THREAD

**Issue by trojanyao** [DIYgod/RSSHub#6137]
- 完整路由地址，包含所有必选与可选参数

`/prestige-av/series/:mid/:sort?`

| 人气    | 最新 | 发售日期 | 标题顺序 | 价格升序 | 价格降序 |
| ------- | ---- | -------- | -------- | -------- | -------- |
| popular | near | date     | title    | low      | high     |

- 预期是什么

返回正确的 XML 文件，可在 RSS 阅读器中正常访问。

- 实际发生了什么
 
服务器端 puppeteer 浏览器进程报错。

- 额外信息（日志、报错等）
 
<img width="1178" alt="Xnip2020-11-10_09-43-00" src="https://user-images.githubusercontent.com/22811809/98617397-e068ba80-2339-11eb-9c8a-a8a1b93b0b7c.png">

**Comment by NeverBehave** [comment]
问题依然存在吗? 可以给一个测试路由吗?

**Comment by minimalistrojan** [comment]
依然存在。测试路由：https://rsshub.app/prestige-av/series/847

**Comment by NeverBehave** [comment]
似乎是缺失依赖导致: https://community.gitpod.io/t/using-puppeteer-libnss3-no-file-or-directory-issue-on-gitpod/1762/5

以下是官方依赖:

```bash
sudo apt-get install libnspr4 libnss3 libnss3-nssdb libnss3-tools
```

/cc @DIYgod

**Comment by minimalistrojan** [comment]
也就是说需要 @DIYgod 在 rsshub.com 的服务器上装下依赖是吗？

**Comment by NeverBehave** [comment]
> 也就是说需要 @DIYgod 在 rsshub.com 的服务器上装下依赖是吗？

应该是的, 但是可以的话可以在PWD里面跑跑看能不能解决问题

**Comment by TonyRL** [comment]
Fixed in https://github.com/DIYgod/RSSHub/commit/990cf92167afbdf1687b9c3310328132e3782771

It should now work with self-hosted instances.
