### ISSUE TITLE
Pixiv登录失败

### ISSUE THREAD

**Issue by Liangyu-G** [DIYgod/RSSHub#6141]
- 完整路由地址，包含所有必选与可选参数
/pixiv/user/illustfollows
- 预期是什么
正常访问
- 实际发生了什么
Error message: pixiv not login
- 部署相关信息
服务器用Chrome可以正常访问登录Pixiv。
RSSHub为最新版（今天刚下载的），部署正常，其余路由可以正常访问（比如YouTube之类的）。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Windows Sever2019 Datacenter|
| Node version       |12.16.1|
| if Docker, version |               |

- 额外信息（日志、报错等）
已经按照部署文档配置了PIXIV_BYPASS_CDN与PIXIV_BYPASS_HOSTNAME但依然登录失败。
info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: Proxy for https://1.1.1.1/dns-query?name=public-api.secure.pixiv.net&type=A
(node:7356) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:7356) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
info: Proxy for https://210.140.131.223/auth/token
error: Pixiv login fail.

**Comment by poly000** [comment]
因为pixiv现在需要通过谷歌验证登录。
希望可以手动验证解决。

**Comment by poly000** [comment]
https://www.itranslater.com/qa/details/2325786776591401984

**Comment by poly000** [comment]
现在我登录没有遇到reCHAPTCHA验证要求
但是验证机制应该是换了
