### ISSUE TITLE
优设网热门频道 RSS

### ISSUE THREAD

**Issue by Geeyun-JY3** [DIYgod/RSSHub#6163]
### 网站地址
https://www.uisdc.com/

### 网站描述
优设是国内极具人气的设计师平台，2012 年成立至今，一直专注于设计师的学习成长交流。 我们通过优设网、优优教程网沉淀优质设计知识的同时，更率先试水新媒体领域。目前旗下媒体矩阵包括：微博@优秀网页设计、微信公众号@优秀网页设计、抖音号@优设PS大神、@优设AI大神等，全网粉丝量过千万。

### 需要生成什么内容？
优设网热门频道的 RSS，不是 #2620 提到的 https://www.uisdc.com/archives 所有文章的 RSS。
如 [细节猎人](https://www.uisdc.com/hunters)、[优设读报](https://www.uisdc.com/news)、[行业新闻](https://www.uisdc.com/category/hangye)，[设计专题](https://www.uisdc.com/zt)、[设计话题](https://www.uisdc.com/talk) 好像底下还能继续细分，[优设琅琊榜](https://www.uisdc.com/gallery) 感觉没必要。

**Comment by ueiu** [comment]
我试了一下 优设自己已经搞了很多rss 大部分你只需要在地址栏获取参数然后拼接：/feed 就可以了

例如：
优设读报：https://www.uisdc.com/news/feed
细节猎人：https://www.uisdc.com/hunters/feed
细节猎人 -> 输入：https://www.uisdc.com/topic/输入/feed
行业新闻：https://www.uisdc.com/category/hangye/feed
行业新闻 -> 活动赛事https://www.uisdc.com/category/hangye/events-activity/feed

具体的展现形式：
![1605952653673](https://user-images.githubusercontent.com/39592269/99874448-0f790900-2c23-11eb-845f-64993d1c6037.jpg)

**Comment by ueiu** [comment]
@Geeyun-JY3 你可以去尝试一下 你说的细分我也提供了例子 都是可用的

**Comment by Geeyun-JY3** [comment]
试了一下，问题不少啊：
1. [优设读报](https://www.uisdc.com/news/feed)、[细节猎人](https://www.uisdc.com/topic/*/feed) 的细分要全文解析，而且我在 Inoreader 测试解析内容都是不完整的
2. [细节猎人](https://www.uisdc.com/hunters/feed) 直接没有任何内容。
3. [设计专题](https://www.uisdc.com/zt/*/feed) 的细分、[设计话题](https://www.uisdc.com/talk/feed) 在 Inoreader  看不到具体文章，最多有个标题，也没办法解析全文。
4. 能正常用的：[设计专题](https://www.uisdc.com/zt/feed)（新增专题 RSS）、[行业新闻](https://www.uisdc.com/category/hangye/feed) 及其细分。

（不过现在好像都已经被大佬实现了🤣

**Comment by ueiu** [comment]
😂我也觉得他们的 rss 设计有点怪 内容全部不返回 估计还是想引流回自己网站吧 有大佬实现就好
