### ISSUE TITLE
morning brew 每日 brew

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#6168]
### 网站地址

https://www.morningbrew.com/

### 网站描述

morning brew 每日早晨通过邮件提供聚合性资讯

### 需要生成什么内容？

https://www.morningbrew.com/archive 页面下有四个栏目

- MORNING
- EMERGING TECH
- RETAIL
- MARKETING

### 额外描述

采用next.js渲染，内容存储在 `<script id="__NEXT_DATA__" type="application/json">` 中，与现有路由 [hedwig-pub](https://docs.rsshub.app/blog.html#hedwig-pub) 以及 [多闻](https://docs.rsshub.app/traditional-media.html#duo-wei-xin-wen-wang)类似。

但是由于内容排版针对email，生成 description 这一步的排版比较麻烦。

**Comment by zoenglinghou** [comment]
这页面有 CloudFlare 5 秒 DDoS 保护，爬起来很困难吧

**Comment by HenryQW** [comment]
那看来是没戏了，之前是没有 CF 的。
