### ISSUE TITLE
说实话你这什么系统环境都没贴出来，没人可以帮你。

### ISSUE THREAD

**Issue by a14907** [DIYgod/RSSHub#6179]
说实话你这什么系统环境都没贴出来，没人可以帮你。

我在本地macos以及树莓派build都没有问题。

_Originally posted by @HenryQW in https://github.com/DIYgod/RSSHub/issues/6122#issuecomment-727576130_

系统是centos7。Docker打镜像

**Comment by HenryQW** [comment]
麻烦按照模板提交issue，不要浪费维护着的时间，

**Comment by a14907** [comment]
> 麻烦按照模板提交issue，不要浪费维护者的时间

呵呵，都说docker了，你还问什么环境！！

**Comment by KotoriK** [comment]
可以先去百度一下npm报的ENOMEM是什么意思

**Comment by a14907** [comment]
> 可以先去百度一下npm报的ENOMEM是什么意思

这位朋友给的建议一针见血，谢谢
