### ISSUE TITLE
南京邮电大学获取失败

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#619]
最新的 `南京邮电大学学籍政策宣讲` 这篇文章的链接是一个 ppt，导致获取失败 @shaoye

**Comment by kawhicurry** [comment]
现在又获取失败了，我应该开个新issue还是就在这里提醒？

**Comment by shaoye** [comment]
> 

我看下

**Comment by shaoye** [comment]
> 现在又获取失败了，我应该开个新issue还是就在这里提醒？

我看下
