### ISSUE TITLE
Instagram路由错误

### ISSUE THREAD

**Issue by willie91** [DIYgod/RSSHub#6204]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/instagram/user/fearythanyarat.id
(我没用rsshub提供的，我是自建的.只是把我的域名换成了rsshub

- 实际发生了什么
Route requested: /instagram/user/fearythanyarat.id
Error message: Cannot read property 'candidates' of undefined
- 部署相关信息
docker 最新镜像，已经加了账号密码

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by snipersteve** [comment]
我也遇到类似情况，docker部署的，环境变量里写了帐号密码，但还是提示没登录
Route requested: /instagram/user/tiffanyyoungofficial
Error message: GET /api/v1/users/search/?timezone_offset=28800&q=tiffanyyoungofficial&count=30 - 403 Forbidden; login_required

**Comment by YunhaoJiang** [comment]
遇到同样情况，log提示登陆成功，但一直提示Cannot read property 'candidates' of undefined

**Comment by HenryQW** [comment]
可能是carousel的问题 #6353应该修复了

**Comment by YunhaoJiang** [comment]
> 可能是carousel的问题 #6353 应该修复了

经部署测试似乎还是有些问题，merge之前的版本log会提示Instagram登陆成功，但merge之后的版本log里就没有了。

**Comment by HenryQW** [comment]
> > 可能是carousel的问题 #6353 应该修复了
> 
> 经部署测试似乎还是有些问题，merge之前的版本log会提示Instagram登陆成功，但merge之后的版本log里就没有了。

我这里本地可以用，一直会收到ins给我发邮件提示异常登录

**Comment by HenryQW** [comment]
需要登陆ins客户端，点击 "this was me" 来验证异地登陆，如果不验证，之后的登陆大概率会被要求验证码。通过 RSS 提交你的验证码比较麻烦，所以需要确认几次异地登陆，我这里确认了3次之后，就没有被弹过了。
