### ISSUE TITLE
即刻部分热门主题生成的内容格式有问题

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#621]
如：
一觉醒来发生了什么
https://rsshub.app/jike/topic/553870e8e4b0cafb0a1bef68.json

**Comment by Andiedie** [comment]
由于即刻的消息只有正文没有标题，因此推荐使用默认文字作为rss标题，然后消息正文作为rss的description。

另外，需要解决换行的问题。

**Comment by Andiedie** [comment]
另外一些消息如果是只有链接没有内容的，则解析结果就是空的

![image](https://user-images.githubusercontent.com/21376471/44952975-ec85a180-aebe-11e8-983c-fc156787c001.png)

经常出现在：
值得一看的长文章 https://web.okjike.com/topic/56d2fabe7cb3331100467e2b/official

**Comment by HenryQW** [comment]
换行我看了一觉醒来有`\n`

**Comment by Andiedie** [comment]
我在reeder中浏览时，/n似乎并不会起换行作用
毕竟在description中已经是html了，将/n换为<br/>似乎比较合理？

**Comment by HenryQW** [comment]
regex直接换br吧，没尝试

**Comment by HenryQW** [comment]
见 #637 说明

**Comment by Andiedie** [comment]
即刻的消息由以下内容组成：
- 纯文字
    [即刻夜谈会](https://web.okjike.com/topic/58a5773cae113d0015bb7ef6/official)和[产品经理日常](https://web.okjike.com/topic/563a2995306dab1300a32227/official)包括了大量这样的纯文字消息
- 图片
    例如 [小姐姐Cosplay摄影](https://web.okjike.com/topic/58c361475217740015d3f701/official)
- 音频
    例如 [晚安歌曲](https://web.okjike.com/topic/55483ddee4b03ccbae843925/official)
- 视频
    例如 [值得一看的短视频](https://web.okjike.com/topic/56fd0b78bdc8981200998418/official) 并且有用户推送的和官方推送两种消息格式
- 外链
    例如 [值得一看的长文章](https://web.okjike.com/topic/56d2fabe7cb3331100467e2b/official) 即刻包括两种外链，一种是消息主题就是链接；另一种是消息的来源链接

建议：
- 即刻部分消息是没有内容的或者内容非常长，直接使用内容字段作为标题会造成有些rss的item没有标题或者标题非常长。**建议截取内容的前20字符作为标题，内容为空时fallback到一个默认值。**
- 目前对于外链的支持不佳。
- 目前完全不支持视频和音频。
- 虽然听过`/topic/text`可以在纯文字上有较好的表现，但是还是希望可以整合到一起

**Comment by HenryQW** [comment]
这个其实很棘手，因为可能出现的情况实在太多了，给的几个例子我都看了一下。不修改现有路由而新增子路由是为了避免现有的订阅崩掉，所以我认为现在的解决方案只能是不断新增子路由，来覆盖已知的情况。

## TL;DR

### 外链 可以当作纯文字来处理，然而纯文字也分很多类型
`产品经理日常`其实很推特很像，但偶尔会出现外链。**正文内容到底该被用作标题吗**？如果不用作标题，那每条 feed 的标题难道就是 `产品经理日常有更新`？

最容易处理的是类似于`一觉醒来发生了什么`这类没有概括性标题的纯文字内容
![screen shot 2018-09-13 at 20 39 50](https://user-images.githubusercontent.com/5896343/45511570-462a7d80-b795-11e8-97b1-1e14da876470.png)

### 纯外链+图片缩略图
`小姐姐Cosplay摄影` 我看了下是纯微博外链+缩略图，我觉得这类消息归类于`图片`就有点牵强了。可以通过输出缩略图作为正文，外链作为 feed 的链接，后续自行处理。

### 纯音频/视频外链
音频/视频外链作为 feed 的链接，后续自行处理。

## 总结
基于目前即刻 API 返回的数据，我觉得任何外链的处理目前只有两种出路：
1. 作为 feed 的链接
2. 在正文中作为一个超链接出现
如果想获取外链的内容，我觉得不属于 RSSHub 应该处理的任务，应该后续自行处理。

**Comment by HenryQW** [comment]
#694 需要更多的主题来测试

**Comment by DIYgod** [comment]
貌似没什么问题了，issue 将被关闭
