### ISSUE TITLE
[BUG]哔哩哔哩的地址均无法获取

### ISSUE THREAD

**Issue by Radcliffe-Bai** [DIYgod/RSSHub#6213]
- 完整路由地址，包含所有必选与可选参数
    `/bilibili/user/video/254463269`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v10.23.0     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 412 (Precondition Failed)
```

**Comment by moelody** [comment]
我也是这个问题，时好时坏的

**Comment by NeverBehave** [comment]
可能是反爬, 需要更多数据点

**Comment by MelonPP** [comment]
自去年8月开始遇到同样的问题，报错412，v10.23.1

**Comment by queensferryme** [comment]
参见 #5984 

目前看来应该就是官方 demo 被哔哩哔哩反爬了，我的自建实例就没有问题。
建议：
1. 在文档中说明 _**反爬严格**_，建议用户自建；
2. 如果能有官方 demo 服务器上的日志的话，才能对这个问题进一步 debug。

**Comment by NeverBehave** [comment]
@queensferryme 文档可以更新一下吗？
