### ISSUE TITLE
【RSS-Wanted】建议增加幕布精选

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#6226]
### 网站地址
https://mubu.com/explore#16
### 网站描述
幕布精选，思维导图与大纲笔记分享社区。
### 需要生成什么内容？

- [ ] 需要按标签分类，抓取导图更新

**Comment by kunpeng9** [comment]
@ZhuningS  【幕布好像不太合适用rss来。。】【导图太粗略了一点，很容易就少来很多的细节】之前有想过提一个，模糊的想法，但是感觉又不是很合适，就没有搞了，好像把那个任务删除了；
我是这样的，幕布精选-标题关键字里面，搜索系统、体系，我略看，前阵子看完了搜索结果里所有的精选内容，只看标题，不看内容，感兴趣的统一保存到自己的幕布，不用收藏【多数情况99%一次都不看，也没法儿加工】
![image](https://user-images.githubusercontent.com/44609485/100313918-8251fd80-2ff0-11eb-840a-4c0add6b3317.png)

![image](https://user-images.githubusercontent.com/44609485/100313970-97c72780-2ff0-11eb-898f-05f18b94729c.png)
【不知道为啥有时候那个快点的动作抓不到标题，难道是因为我开的标签页太多，没有加载完的原因？】
还保存着上回搜索使用到的词语【谷歌浏览器的自动填充功能记录】
![image](https://user-images.githubusercontent.com/44609485/100314239-26d43f80-2ff1-11eb-88ae-2d851b3097e8.png)
系统 体系 文献 roam anki 学术
