### ISSUE TITLE
请问自己部署和使用官方订阅源的区别是？

### ISSUE THREAD

**Issue by dongdongdu** [DIYgod/RSSHub#624]
如题哈~
虽然自己单独Docker部署实践了一下，但是没理解自己部署和使用官方源的区别是？ 

https://rsshub.app/

**Comment by lengthmin** [comment]
@dongdongdu 自己部署可以修改config里的东西.

**Comment by lengthmin** [comment]
@dongdongdu 官方设置的是十分钟的缓存, 自己可以调低或调高一点.

**Comment by dongdongdu** [comment]
@lengthmin 请问通常设置多少合适？ 一天的？ 我翻文档，这个好像没有详细的介绍；
通常是24小时吗？谢谢！

**Comment by lengthmin** [comment]
@dongdongdu 看需求吧 十分钟的缓存就是同一个源十分钟内多次访问不更新, 调的越低更新的越快, 十分钟已经够了

**Comment by dongdongdu** [comment]
@lengthmin 谢谢！
