### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cuiweigeng** [DIYgod/RSSHub#6243]
- The involved route, with all required and optional parameters
    `/bilibili/user/video/8372353`
- What is expected

- What is actually happening

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v10.23.0     |
| if Docker, version |               |

- Additional info (logs errors etc)
```
    Response code 412 (Precondition Failed)
```

**Comment by laampui** [comment]
duplicate #6213
