### ISSUE TITLE
RSS 提案：HostLoc 全球主机交流

### ISSUE THREAD

**Issue by imByteCat** [DIYgod/RSSHub#6265]
### 网站地址

`https://www.hostloc.com/forum.php`

### 网站描述

「全球主机交流论坛」

### 需要生成什么内容？

按板块生成 RSS 内容，如：`https://www.hostloc.com/forum-45-1.html`。

### 额外描述

该论坛基于 Discuz，但开启了 js 验证，导致自带的 RSS 并不生效，如：`https://www.hostloc.com/forum.php?mod=rss&fid=45`。

**Comment by imByteCat** [comment]
可按发帖降序排列：`https://www.hostloc.com/forum.php?mod=forumdisplay&fid=45&filter=author&orderby=dateline`

**Comment by lonelykid** [comment]
hostloc用的discuz吧，已经有了。
https://rsshub.app/discuz/https%3a%2f%2fwww.hostloc.com%2fforum.php%3fmod%3dforumdisplay%26fid%3d45%26filter%3dauthor%26orderby%3ddateline
