### ISSUE TITLE
科技星球显示404 not found

### ISSUE THREAD

**Issue by lengthmin** [DIYgod/RSSHub#627]
![image](https://user-images.githubusercontent.com/13938334/44953883-a46d7b80-aecc-11e8-9f2b-05ecc5af1134.png)

**Comment by HenryQW** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/5896343/45084426-33111100-b0f6-11e8-94c4-cb0f53c6c1d4.png">
科技星球网站自己跑路了

**Comment by lengthmin** [comment]
@HenryQW 删掉路由咯？

**Comment by HenryQW** [comment]
可能过几天就回来了

**Comment by DIYgod** [comment]
5天了，科技星球路由将被删除

**Comment by HenryQW** [comment]
diygay即将抹杀一颗星球
