### ISSUE TITLE
Scientific American 60-Second, wrong path

### ISSUE THREAD

**Issue by somedevreally** [DIYgod/RSSHub#6286]
getting this error for Scientific American 60-Second science

```
error: Error in /60s-science/transcript: wrong path,

Route requested: /60s-science/transcript
Error message: wrong path
```

**Comment by nczitzk** [comment]
You might want to request [/60s-science](https://rsshub.app/60s-science) if the transcripts are what you expect to get 🤝

**Comment by somedevreally** [comment]
ok that worked, earlier it was `/60s-science/transcript`

thanks
