### ISSUE TITLE
荔枝FM无法完全抓取所有条目

### ISSUE THREAD

**Issue by huLter** [DIYgod/RSSHub#6344]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/lizhi/user/405?limit=20
https://rsshub.app/lizhi/user/332?limit=20

- 预期是什么
抓取前20个条目

- 实际发生了什么
无论怎么调整参数，只能抓取5个条目

**Comment by NeverBehave** [comment]
对的, 默认页面是载入5条, 页面是后续通过API载入
这个参数只在源获取数量超过限制的时候有效
但是说实话我觉得应该没有太多必要一次性载入太多, 理论上虽然是可以全部载入
