### ISSUE TITLE
Error message: pixiv not login

### ISSUE THREAD

**Issue by Ruriko** [DIYgod/RSSHub#6348]
These 2 specific keywords don't work it just gives Error message: pixiv not login
https://rsshub.app/pixiv/search/naruto/other/1
https://rsshub.app/pixiv/search/%E8%A3%8F%E4%B8%96%E7%95%8C%E3%83%94%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF/other/1

**Comment by HenryQW** [comment]
pixiv is self-host only, rsshub.app will not work.
