### ISSUE TITLE
【bug】即刻主题输出内容中的“\n”被模板引擎弄没了

### ISSUE THREAD

**Issue by sharkrice** [DIYgod/RSSHub#635]
订阅即刻主题：553870e8e4b0cafb0a1bef68

输出的rss中并没有原生输出，原api中的\n换行符不见了

![image](https://user-images.githubusercontent.com/7795038/44973781-44400d80-af90-11e8-9f06-61d1a0c99e78.png)

导致文本没有换行，连在一起
![image](https://user-images.githubusercontent.com/7795038/44973938-bdd7fb80-af90-11e8-96aa-935f0e6fe044.png)

不仅仅是即刻主题，其它的有\n的都被模板引擎给弄没了

**Comment by lengthmin** [comment]
@sharkrice 而且标题跟内容一样！！

**Comment by HenryQW** [comment]
@lengthmin #621
