### ISSUE TITLE
【Rss Bug】中国人民银行-沟通交流

### ISSUE THREAD

**Issue by Chen-Runze** [DIYgod/RSSHub#6367]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/pbc/goutongjiaoliu

- 预期是什么
能够正常抓取html内容

- 实际发生了什么
Error message: this route is empty, please check the original site or create an issue

- 部署相关信息

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
fixed in #9324
