### ISSUE TITLE
请求 禁忌书屋 rss

### ISSUE THREAD

**Issue by pikawindy** [DIYgod/RSSHub#6368]
### 网站地址
https://www.cool18.com/bbs4/
### 网站描述
小说论坛
### 需要生成什么内容？
小说目录

**Comment by resol341** [comment]
This is the same request as in #3496

**Comment by australianpokies** [comment]
Thanks for the detailed issue! Hope it resolves soon.
[![Image](https://github.com/user-attachments/assets/3e73c1b5-4Great job on this issue! Thanks for raising this.
[![Image](https://github.com/user-attachments/assets/3e73c1b5-4016-477e-90e3-6084e649b092)](https://robycasino.pokiesreal.money/)016-477e-90e3-6084e649b092)](https://rickycasino3.com/)
