### ISSUE TITLE
rsshub 官网证书错误

### ISSUE THREAD

**Issue by oe** [DIYgod/RSSHub#6372]
rsshub 官网  https://rsshub.app/ 和 https://docs.rsshub.app/ 因证书错误无法正常访问

---
这个问题存在好久了, 没人发现么? 难道是地域问题?

**Comment by RtYkk** [comment]
![Screenshot_20201207-205008](https://user-images.githubusercontent.com/45971730/101352951-d650c200-38cd-11eb-907c-c5cdbe0d01f5.png)
应该是你一个人的问题，建议详细看看证书显示什么。

**Comment by oe** [comment]
人在深圳, 刚多方尝试了下:
 使用电脑(Mac/Ubuntu) : 中国电信宽带无法访问, 天威宽带也无法访问.
 使用手机: 中国移动能正常访问, 中国电话无法访问

Ubuntu 在 电信宽带下的截图
![image](https://user-images.githubusercontent.com/1655294/101354188-b6220280-38cf-11eb-9037-f59adf131bf4.png)

Mac 在电信宽带下的截图
![image](https://user-images.githubusercontent.com/1655294/101354328-ecf81880-38cf-11eb-9804-b4af94f117a6.png)

**Comment by RtYkk** [comment]
…那跟证书错误没关系
https://t.me/awesomeRSSHub/234
![Screenshot_20201207-211003](https://user-images.githubusercontent.com/45971730/101354806-b242b000-38d0-11eb-88e3-798a77a81e67.png)
这条消息已经 pin 了超过半年，没记错的话是 DNS 污染，建议修改 hosts 或使用抗污染 DNS 。
IP 可以为任意一个 Cloudflare 的 Anycast IP

**Comment by oe** [comment]
额, 没有关注这个channel. 这样一个工具类的应用也要被认证🤷‍♂️

感谢你的解答.
