### ISSUE TITLE
vercel use limitation报错

### ISSUE THREAD

**Issue by walterjobs** [DIYgod/RSSHub#6381]
rsshub部署在vercel上了，没想到收到了邮件，提示use limitation warning

We're getting in touch to let you know that your Personal Account, has consumed over 100% of the resources allocated to it during the current 30 day usage period, as per the Fair Use Policy.

Serverless Function Execution - 377.095 GB-Hours / 100 GB-Hours (377.1%)

大佬们遇到过么

**Comment by HenryQW** [comment]
看看你的rsshub首页的请求数量，是不是有路由请求太频繁
