### ISSUE TITLE
微博部分博主抓取失败

### ISSUE THREAD

**Issue by lbkyx** [DIYgod/RSSHub#6389]
![uTools_1607507476381](https://user-images.githubusercontent.com/26920288/101613806-269f5f80-3a47-11eb-865f-f02e1f002ae8.png)

- 完整路由地址，包含所有必选与可选参数

/weibo/user/5393135816

- 预期是什么

微博抓取#博主

- 实际发生了什么

Looks like something went wrong
Route requested: /weibo/user/5393135816
Error message: Cannot read property 'screen_name' of undefined

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   centos7.6    |
| Node version       |               |
| if Docker, version |  官网Docker Compose 部署   |

- 额外信息（日志、报错等）

**Comment by typesoshee2** [comment]
I have encountered the same issue.

Name: Issue or bug report
About: Some Weibo accounts cause an "Error message: Cannot read property 'screen_name' of undefined" error.

I'm using a version deployed on Heroku.

路由地址（不包含参数）
/weibo/user/2955461920

完整路由地址，包含所有必选与可选参数
/weibo/user/2955461920/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweet=0&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1

相关文档地址
https://docs.rsshub.app/social-media.html#wei-bo

预期是什么
A successful RSS feed to the Weibo account

实际发生了什么
Error message: Cannot read property 'screen_name' of undefined

**Comment by TonyRL** [comment]
![image](https://user-images.githubusercontent.com/11386903/160171893-1db4da46-239c-4718-a2b1-a14a3515edbe.png)

See https://github.com/DIYgod/RSSHub/issues/9245
