### ISSUE TITLE
能订阅微信公众号吗？

### ISSUE THREAD

**Issue by jing8263xiao** [DIYgod/RSSHub#64]

**Comment by DIYgod** [comment]
技术难度较大，暂不考虑

**Comment by ocbear** [comment]
可以考虑python爬虫不

**Comment by HenryQW** [comment]
@ocbear 参考下 https://github.com/wonderfulsuccess/weixin_crawler。 但是这类基本活不了多久就会被封

**Comment by ocbear** [comment]
@HenryQW 既然有这么多志愿者，代理IP肯定有，要不行的话，还有万能的tor啊··

**Comment by HenryQW** [comment]
@ocbear 现有路由已经提供了文章直链，请自行发挥想象力。

**Comment by ocbear** [comment]
@HenryQW wemp.app 来源的只是指向这个网站，还要自己深挖一层才到腾讯，毕竟原始链接体验会好很多。
