### ISSUE TITLE
Incorrect link in the Instagram route

### ISSUE THREAD

**Issue by igor-akhmetov** [DIYgod/RSSHub#6409]
The link to Instagram at https://github.com/DIYgod/RSSHub/blob/master/lib/routes/instagram/index.js#L65 is incorrect, should be 'https://www.instagram.com' instead of 'https://www.intagram.com'.

@HenryQW, @oppilate Guys, thanks a lot for your work on the Instagram route! Could you please update the URL?

**Comment by oppilate** [comment]
Already fixed: https://github.com/DIYgod/RSSHub/blob/50f2651f9779da908c61804c1c86565f86d07805/lib/routes/instagram/index.js#L85

**Comment by igor-akhmetov** [comment]
@oppilate Your link points to line 85, mine to line 65 which still says "www.intagram.com" in master.

**Comment by oppilate** [comment]
You're right. Have sent a PR.
