### ISSUE TITLE
幕布RSS未显示分类的标签名字

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#6416]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/mubu/explore/46
- 预期是什么
RSS标题 显示分类的标签名字
- 实际发生了什么
![image](https://user-images.githubusercontent.com/38108376/101849923-ab978f80-3b93-11eb-9940-1b490940bb7e.png)

**Comment by laampui** [comment]
![Screenshot_20201211-225020169](https://user-images.githubusercontent.com/15785343/101917523-4bd8cd00-3c03-11eb-9182-13993c732126.jpg)

你想显示什么标题，加在 RSS link 里面就行了
