### ISSUE TITLE
阿斯麦半导体

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6420]
### 网站地址
https://www.asml.com/en/news
### 网站描述
阿斯麦（ASML Holding N.V.）是在荷兰费尔德霍芬的半导体设备制造商。公司同时在欧洲和美国NASDAQ上市。从业员工20,000多名。在世界16个国家和地区有60个子公司和生产据点。阿斯麦公司的主要产品是用来生产大规模积体电路的核心设备曝光机。在世界同类产品中有90%的市占率，在10奈米节点以下有100%的市占率。
阿斯麦公司为半导体生产商提供光刻机及相关服务，TWINSCAN系列是目前世界上精度最高，生产效率最高，应用最为广泛的高端光刻机型。目前全球绝大多数半导体生产厂商，都向ASML采购TWINSCAN机型，例如英特尔、三星、海力士、台积电、联电、格罗方德及其它台湾十二吋半导体厂。
### 需要生成什么内容？
![image](https://user-images.githubusercontent.com/44609485/101874038-13190380-3bc3-11eb-8aa5-2986cb4e63e4.png)
https://www.asml.com/en/news/press-releases?page=3&sortBy=relevance
news实际上只有这个有内容。
### 额外描述
很少很少访问，一大堆格子，不是很习惯。
![image](https://user-images.githubusercontent.com/44609485/101874442-dbf72200-3bc3-11eb-9fc1-75e543283851.png)
荷兰公司本国男性露脸，一个美国黑人男性【留着胡子】，一个中国女性【戴着眼镜】，其他国家日韩台湾全部穿着防尘服，不露脸，虽然这些国家在半导体生产中起到了不可或缺的作用，日本的材料、韩国的内存、台湾地区半导体先进制程处领先地位，晶圆代工、封装测试产值全球第一，IC设计全球第二。。
将超级英雄这个视频转成了文字，人类科技的大成之作光刻机也不能远离政治正确，_亚洲人、柔弱的黄种人女性最后要扑向狂野的、强大的、充满男性气息的美国男人的怀抱。_ 
政治正确=虽然黑人长期受歧视，教育落后，对半导体产业真没啥贡献，但必须要有黑人出现。

[超级英雄电影，其实就是封建遗留的新时代映像【范勇鹏|余亮】【茶话会·老同志看电影】_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://www.bilibili.com/video/BV1ji4y15798) 
![image](https://user-images.githubusercontent.com/44609485/101877612-3cd52900-3bc9-11eb-997a-8ee548e60010.png)
亚洲人打kiss轻吻一下，抗议，怎么能这样？实在是太过分了，必须剪掉！
![image](https://user-images.githubusercontent.com/44609485/101878611-d6510a80-3bca-11eb-9ab7-67acc4026357.png)

**Comment by HenryQW** [comment]
麻烦开issue不要扯一些没用的话题

```
政治正确=虽然黑人长期受歧视，教育落后，对半导体产业真没啥贡献，但必须要有黑人出现。
```

冒犯性很强，凸显了你毫无素质与教养。
