### ISSUE TITLE
即刻话题下的图片URL 错误 / Broken Image URL of Jike Topic RSS

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#6429]
- The involved route, with all required and optional parameters
jike topic

- What is expected
image url not correct
https://cdn.jellow.site/FggZCa0mb5cuCebxb2mrg0YtvQvX.jpg/strip/format/webp

- What is actually happening
it should remove those "**/strip/format/webp**" at the end of the image url
https://cdn.jellow.site/FggZCa0mb5cuCebxb2mrg0YtvQvX.jpg

- Self-deployment information
e.g. Jike Topic RSS
https://rsshub.app/jike/topic/556688fae4b00c57d9dd46ee

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- Additional info (logs errors etc)

**Comment by DerekTso** [comment]
close

**Comment by Rongronggg9** [comment]
I consider this is not really a bug since this is a standard implementation of image fallback, but that's OK to "fix" this.

```html
<picture>
	  <source srcset="https://cdn.jellow.site/Fn69vlg2vIXNwjkhAH9BjRceXQ2kv3.jpg/strip/format/webp" type="image/webp">
	  <source srcset="https://cdn.jellow.site/Fn69vlg2vIXNwjkhAH9BjRceXQ2kv3.jpg" type="image/jpeg">
	  <img referrerpolicy="no-referrer" src="https://cdn.jellow.site/Fn69vlg2vIXNwjkhAH9BjRceXQ2kv3.jpg">
</picture>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture
