### ISSUE TITLE
知乎抓取出现bug

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#6468]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/zhihu/people/activities/xia-bingying
- 预期是什么
锚文本链接与源网站保持一致。
- 实际发生了什么
锚文本链接出现了重大偏差。
- 额外信息（日志、报错等）
RSS
![image](https://user-images.githubusercontent.com/51783873/102452032-9e3b4300-4074-11eb-8e6f-2793ac5e4e33.png)
出现错误的抓取（inoreader客户端）
![image](https://user-images.githubusercontent.com/51783873/102452037-a1363380-4074-11eb-929d-e9f4cf4e5654.png)
原文章
![image](https://user-images.githubusercontent.com/51783873/102452084-b317d680-4074-11eb-9de1-1079b09d371f.png)

**Comment by laampui** [comment]
`xmlMode`改为 `false`即可解决，但怕影响到其他地方
https://github.com/DIYgod/RSSHub/blob/e735aef8a7a3787e2f7991c989de255ecae146fa/lib/routes/zhihu/utils.js#L9

**Comment by NeverBehave** [comment]
> `xmlMode`改为 `false`即可解决，但怕影响到其他地方
> 
> https://github.com/DIYgod/RSSHub/blob/e735aef8a7a3787e2f7991c989de255ecae146fa/lib/routes/zhihu/utils.js#L9

知乎这个感觉是标签闭合有问题啊, a标签没有闭合
他这个会不会是其他地方处理的有问题

**Comment by NeverBehave** [comment]
> `xmlMode`改为 `false`即可解决，但怕影响到其他地方
> 
> https://github.com/DIYgod/RSSHub/blob/e735aef8a7a3787e2f7991c989de255ecae146fa/lib/routes/zhihu/utils.js#L9

要不要尝试先这样做一个pr测试一下？
