### ISSUE TITLE
漫画柜规则更新

### ISSUE THREAD

**Issue by wdssmq** [DIYgod/RSSHub#6473]
```js
  let chapters;

  if ($("#__VIEWSTATE").length > 0) {
    const LZString = require("lz-string"); //问题是要不要在项目中预置这个依赖 
    console.log(typeof LZString);
    $2 = cheerio.load(LZString.decompressFromBase64($("#__VIEWSTATE").val()));
    chapters = getChapters($2);
  } else {
    chapters = getChapters($);
  }
```

**Comment by NeverBehave** [comment]
是否提交一个完整PR并说明一下原因?

**Comment by wdssmq** [comment]
> 是否提交一个完整PR并说明一下原因?

一些限制级的漫画会将章节目录以加密压缩的方式输出到html，浏览时需要确认提示后查看查看：

https://www.manhuagui.com/comic/29332/

用的库是这个↓

pieroxy/lz-string: LZ-based compression algorithm for JavaScript
https://github.com/pieroxy/lz-string

我目前是并不需要的，也有能力自建解决

`npm install -g lz-string`

**Comment by NeverBehave** [comment]
这样，如果你愿意提交更新的话是欢迎的😉

**Comment by wdssmq** [comment]
> 这样，欢迎提交更新😉，如果可以的话

这种感觉只有一两个站需要用的东西(╯▽╰)。。。代码到是不难，

**Comment by NeverBehave** [comment]
库的大小还好，按需载入依赖后续还是有办法解决的

**Comment by NeverBehave** [comment]
#6631 解决
