### ISSUE TITLE
微博时间线部署 400，请求帮助

### ISSUE THREAD

**Issue by RikkaBlue** [DIYgod/RSSHub#6479]
目前已经在微博开发平台通过了开发者认证，部署后能够成功输出例如 `/weibo/search/hot`  的路由，但是无法输出个人时间线 `/weibo/timeline/`  ，提示 `400`
`rsshub         | error: Error in /weibo/timeline/5368951823: Response code 400 (Bad Request): target website might be blocking our access,`

奇怪的是 `LOGGER_LEVEL` 为 `DEBUG` 的情况下也是如此的输出，在本地直接安装也是如此。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |      19.03.12         |
-------
谢谢了。

-----
**补充** 不知道微博开发者平台的应用来源审核对于这个路由是否是必须的，应用没有通过来源审核
![image](https://user-images.githubusercontent.com/46104879/102696849-64cd2800-426c-11eb-99ac-370d94e155d3.png)

我了解到的是这个 [`https://api.weibo.com/2/statuses/public_timeline.json`](https://open.weibo.com/wiki/2/statuses/home_timeline) 是普通接口，不需要审核获得高级接口权限。

**Comment by RikkaBlue** [comment]
还有就是对于[文档](https://open.weibo.com/wiki/2/statuses/home_timeline) 这句话也比较疑惑。。。
>只返回授权用户的微博，非授权用户的微博将不返回；
例如一次调用total_number是50，但其中授权用户发的只有10条，则实际只返回10条微博；
使用官方移动SDK调用，可多返回30%的非授权用户的微博；

**Comment by NeverBehave** [comment]
timeline 用的链接是 `https://api.weibo.com/2/statuses/home_timeline.json`
