### ISSUE TITLE
How to auto start rsshub on boot?

### ISSUE THREAD

**Issue by Ruriko** [DIYgod/RSSHub#6484]
If my server reboot I want it to auto run rsshub. How can I do this?

**Comment by HenryQW** [comment]
I think [this](https://www.google.com/search?newwindow=1&rls=en&sxsrf=ALeKk0231PPhY6izMIP6Z-2eKd0bTXlQLg%3A1608750235587&ei=m5TjX4yZI_OF1fAP1Ly0wAs&q=start+node+project+on+boot&oq=start+node+project+on+boot&gs_lcp=CgZwc3ktYWIQAzoECAAQRzoHCCMQsAIQJ1C_GFidHGDRHWgAcAJ4AIABRIgBvQGSAQEzmAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwjM0svS5eTtAhXzQhUIHVQeDbgQ4dUDCAw&uact=5) helps.
