### ISSUE TITLE
Get direct link of image on pixiv using own server

### ISSUE THREAD

**Issue by Ruriko** [DIYgod/RSSHub#6488]
I see that RSSHub uses pixiv.cat service to get direct link of images on pixiv.net but is it possible to make it use your own local server to grab direct links cause pixiv.cat isn't reliable to use since you sometimes get dead images due to api rate limit. I think it's best to use own server cause there be no api rate limit

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/search?q=pixiv.cat

Extracting parameters and put it as part of the config, writing the docs.

contributions are welcome!

**Comment by TonyRL** [comment]
You can host your own proxying service use it on your own RSSHub instance by setting env `PIXIV_IMG_PROXY`
docs: https://docs.rsshub.app/en/install/#configuration-route-specific-configurations
