### ISSUE TITLE
轉角國際 挂了

### ISSUE THREAD

**Issue by lawsoom** [DIYgod/RSSHub#6498]
- The involved route, with all required and optional parameters

https://rsshub.app/udn/global/newest

- What is expected

抓取最新文章

- What is actually happening

A feed could not be found at this link. 
“Status down” shown in rsshub

**Comment by ahxxm** [comment]
matters也挂了
错误提示一样
https://rsshub.app/matters/author/hi176
<img width="850" alt="image" src="https://user-images.githubusercontent.com/1286225/102886296-ce794c00-448f-11eb-95d3-b5b7c281e48e.png">

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/issues/6504

已经修复，可以关闭了
