### ISSUE TITLE
Bilibili抓取用户关注动态返回emoji相关错误

### ISSUE THREAD

**Issue by huLter** [DIYgod/RSSHub#6503]
- 完整路由地址，包含所有必选与可选参数
/bilibili/followings/dynamic/219510

- 预期是什么
抓取用户关注动态

- 实际发生了什么
返回错误信息
Error message: Cannot read property 'emoji_info' of undefined

- 部署相关信息
部署于heroku，commit e735aef8a7a3787e2f7991c989de255ecae146fa 

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TigerWolfDen** [comment]
抱歉我这里运行正常，无法重现问题，望其他有能力的小伙伴解决一下谢谢了。

**Comment by huLter** [comment]
好像这个问题并不会经常出现，附上出现问题时动态的json
[dynamic_new.zip](https://github.com/DIYgod/RSSHub/files/5864234/dynamic_new.zip)

**Comment by kumiko-desu** [comment]
我这里出现了同样的问题，目测也是由番剧卡片导致的。

**Comment by TigerWolfDen** [comment]
已修复，如果问题仍然出现，请告知。
