### ISSUE TITLE
[bot] 请不要让机器人自动更新依赖 — Cheerio

### ISSUE THREAD

**Issue by NeverBehave** [DIYgod/RSSHub#6504]
- 完整路由地址，包含所有必选与可选参数

所有使用cheerio的路由

- 预期是什么

Cheerio 版本应当PIN在最后的稳定版 0.22 

- 实际发生了什么

Dependabot 自动更新到了rc版本，这些版本通常有大量Bug或者未经说明的Breaking Change

由于cheerio是大部分路由依赖的包，更新到不稳定版本很可能导致大批路由失效

例如：furstar 路由由于最新rc5的bug无法使用 https://github.com/cheeriojs/cheerio/issues/1577

- 部署相关信息

- 额外信息（日志、报错等）

官方相关issue：

https://github.com/cheeriojs/cheerio/issues/1261

**Comment by DIYgod** [comment]
1. 把 `cheerio` 重置到了之前一直在使用的 `1.0.0-rc.3`
2. 让 dependabot 忽略了 `cheerio` 更新
3. v1.0 正式版看起来快发布了，等正式版再尝试更新
