### ISSUE TITLE
轻芒杂志

### ISSUE THREAD

**Issue by prnake** [DIYgod/RSSHub#6515]
### 网站地址
[轻芒杂志 · 订阅一切，马克一切](https://play.google.com/store/apps/details?id=com.wandoujia&hl=zh&gl=US)
### 网站描述
支持订阅**任意公众号**，以及轻芒精选的内容。（以及RSS）
### 需要生成什么内容？
个人时间线和单独微信公众号内容和栏目。
### 额外描述
轻芒APP api 的 url 长期可用，暂不清楚有无反扒措施。
类似[这个]( https://api.qingmang.me/v2/user.subscription.exploreEvents?userId=1)，具体有待探索。

**Comment by mapoio** [comment]
给的订阅url好像只有图片和摘要，阅读不了全文

**Comment by prnake** [comment]
已倒闭
