### ISSUE TITLE
无法正常部署

### ISSUE THREAD

**Issue by Fat-Panda1** [DIYgod/RSSHub#6541]
- 如何正确部署
- 根据官方文档使用npm install无法下载依赖包，也尝试过yarn

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        Win       |
| Node version       |       v14.15.3        |
| if Docker, version |         none      |

![image](https://user-images.githubusercontent.com/30423976/103159603-3a4c1380-4806-11eb-85af-93aabc0d0bc0.png)
![image](https://user-images.githubusercontent.com/30423976/103159607-446e1200-4806-11eb-8b4c-3d9e8edfbb7e.png)
![image](https://user-images.githubusercontent.com/30423976/103159618-5c459600-4806-11eb-9f7a-9951fb7da62e.png)

**Comment by Fat-Panda1** [comment]
@Fat-Panda1 我电脑上装了3.6

**Comment by Fat-Panda1** [comment]
@Fat-Panda1 还是不行一样会报错，是不是对python版本有要求！

**Comment by HenryQW** [comment]
删除node_modules重试，墙内记得用cnpm

**Comment by Fat-Panda1** [comment]
使用cnpm后依然会报错，我也配置了npm的python路径
![image](https://user-images.githubusercontent.com/30423976/103421845-705c0f80-4bd9-11eb-9558-1422fd746793.png)
