### ISSUE TITLE
美国半导体行业协会

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6562]
### 网站地址
https://www.semiconductors.org/news-events/latest-news/
### 网站描述

sia是Semiconductor Industry Association美国半导体产业协会的简称。
Semiconductor Industry Association美国半导体产业协会
https://www.semiconductors.org/resources/?fwp_resource_types=policy-reports 政策报告
### 需要生成什么内容？
https://www.semiconductors.org/news-events/latest-news/ 最新消息
https://www.semiconductors.org/category/blog/ 博客
https://www.semiconductors.org/resources/?fwp_resource_types=policy-reports政策
https://www.semiconductors.org/resources/ 
https://www.semiconductors.org/resources/?fwp_resource_types=policy-reports
### 额外描述
http://www.csia.net.cn/Index.asp 不知道为啥这个网页两边有这么大的空白，字体有点小了。
![image](https://user-images.githubusercontent.com/44609485/103272667-6dee8f80-49f8-11eb-982f-08fea7b8640d.png)

**Comment by HenryQW** [comment]
你这需求也太多了，RSSHub 都快成你私人开发团队了，没这么多精力一个个满足你。
