### ISSUE TITLE
阿卜杜勒 · 拉蒂夫 · 贾米尔扶贫行动实验室【J-PAL】分类

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6563]
### 网站地址
https://www.povertyactionlab.org/
### 网站描述
阿卜杜勒 · 拉蒂夫 · 贾米尔扶贫行动实验室(J-PAL)是一个全球研究中心，致力于通过确保政策得到科学证据的支持来减少贫困。通过随机的影响评估来回答与贫困作斗争中的关键问题，并与政府、非政府组织、捐助者和其他人建立伙伴关系来产生新的研究、分享知识和扩大有效的项目。[1]截至2018年，通过 J-PAL 分支机构的研究发现，超过4亿人已经接触到了大量有效的项目。
https://www.povertyactionlab.org/updates/j-pal-co-founders-abhijit-banerjee-and-esther-duflo-awarded-nobel-memorial-prize-0
### 需要生成什么内容？
https://www.povertyactionlab.org/blog
https://www.povertyactionlab.org/news
![image](https://user-images.githubusercontent.com/44609485/103273616-b60eb180-49fa-11eb-85d0-f9b12804dca6.png)
只想看东亚的。
### 额外描述
https://www.povertyactionlab.org/news.xml 插件识别不了。
https://economics.mit.edu/faculty/banerjee/papers 论文
https://www.amazon.cn/dp/B07NZZ6Q8Y
2019年10月14日，阿比吉特·班纳吉获得2019年诺贝尔经济学奖。
2011年，由阿比吉特·班纳吉和埃斯特·迪弗洛合作出版《贫穷的本质：我们为什么摆脱不了贫穷》，18年偶然在大学临时书摊上买到了这本书，感觉太晚了一点。

**Comment by zoenglinghou** [comment]
我在实现爬虫的时候遇到了 `HPE_HEADER_OVERFLOW` 的错误，RSSHub 显示的是网站反爬，但是我用 `curl` 和 `wget` 下载都没有问题

**Comment by zoenglinghou** [comment]
@HenryQW 所以以后遇到header太长的都是不能做吗

**Comment by NeverBehave** [comment]
> @HenryQW 所以以后遇到header太长的都是不能做吗

具体什么地方出错?

**Comment by zoenglinghou** [comment]
`HPE_HEADER_OVERFLOW`，似乎是头太长，parse不了

**Comment by NeverBehave** [comment]
> `HPE_HEADER_OVERFLOW`，似乎是头太长，parse不了

那是什么链接会有这个问题？

**Comment by zoenglinghou** [comment]
https://www.povertyactionlab.org/blog
