### ISSUE TITLE
pixiv登录失败：ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by poly000** [DIYgod/RSSHub#6584]
- 完整路由地址，包含所有必选与可选参数
无
- 预期是什么
正常登录pixiv
- 实际发生了什么
pixiv登录失败
- 部署相关信息
```
sudo docker run -d --name rsshub --net host -p 1200:1200 \
-e CACHE_EXPIRE=7200 \
-e CACHE_CONTENT_EXPIRE=86400 \
-e PROXY_URI=http://127.0.0.1:30000 \
-e PIXIV_BYPASS_CDN=1 \
-e LOGGER_LEVEL=debug diygod/rsshub
# USERNAME和PASSWORD已省略
```

已确保部署的是docker latest。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   archlinux|
| Node version       |  v15.5.0  |
| if Docker, version |       20.10.1        |

- 额外信息（日志、报错等）
```

> rsshub@1.0.0 start /app
> node lib/index.js

info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: Proxy for https://1.1.1.1/dns-query?name=public-api.secure.pixiv.net&type=A
info: Proxy for https://210.140.131.223/auth/token
error: Pixiv login fail.
debug: undefined {"name":"RequestError","code":"ERR_TLS_CERT_ALTNAME_INVALID","timings":{"start":1609526409522,"socket":1609526409524,"lookup":1609526409524,"connect":1609526409524,"error":1609526410018,"phases":{"wait":2,"dns":0,"tcp":0,"total":496}}}

```

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/issues/6141 Related, 这个问题看来是一个比较久远的问题了
https://github.com/DIYgod/RSSHub/blob/dd9bb40c798c2fcab3bc60d1dbbd749dac14cd99/lib/routes/pixiv/pixiv-got.js#L48
https://github.com/sindresorhus/got/issues/477 可以通过手动忽略证书解决, 但是有一定的安全隐患

#5962

**Comment by poly000** [comment]
> #6141 Related, 这个问题看来是一个比较久远的问题了
> 
> https://github.com/DIYgod/RSSHub/blob/dd9bb40c798c2fcab3bc60d1dbbd749dac14cd99/lib/routes/pixiv/pixiv-got.js#L48
> 
> [sindresorhus/got#477](https://github.com/sindresorhus/got/issues/477) 可以通过手动忽略证书解决, 但是有一定的安全隐患
> 
> #5962

--env NODE_TLS_REJECT_UNAUTHORIZED 0
这样可以吗？
