### ISSUE TITLE
微博user2 api 发布时间时区不正确

### ISSUE THREAD

**Issue by MiracleXYZ** [DIYgod/RSSHub#659]
在微博user2 api中，如果一条新微博的发布时间是北京时间18:00，`item`的`pubDate`目前显示为`18:00:00 GMT`而不是`10:00:00 GMT`，出现了8个小时的时间差。

**Comment by HenryQW** [comment]
GMT 时间为格林威治标准时间，中国所在时区为 GMT+8。
`10:00:00 GMT` = `18:00:00 GMT+8`

**Comment by MiracleXYZ** [comment]
但是在RSS Feed里面直接写成了
`<pubDate>Fri, 07 Sep 2018 18:00:00 GMT</pubDate>`

**Comment by HenryQW** [comment]
例子？我随便找了个微博用户试了一下，我这边是正确的时间

**Comment by HenryQW** [comment]
发现了，相对时间是正确，绝对时间是错误的。

**Comment by MiracleXYZ** [comment]
是这样的。所以我把这个feed用ifttt同步到谷歌日历的时候就出现了问题。

**Comment by HenryQW** [comment]
Bug to fix:
https://github.com/DIYgod/RSSHub/blob/2e25749e0b518e87c5573f357d0c5f92de3b846f/routes/weibo/utils.js#L58
