### ISSUE TITLE
[功能需求] 对Telegram channel 订阅的改进

### ISSUE THREAD

**Issue by BeautyYuYanli** [DIYgod/RSSHub#6612]
### 功能需求:
能否使用消息的第一行内容作为标题?
### 面向问题:
现有的Telegram channel订阅会将整条消息截取前一部分作为标题 这导致rss客户端看到的消息标题非常粗陋.

**Comment by notofoe** [comment]
如果单纯的拿第一行，这些频道的文章标题就不剩什么了：https://t.me/s/NewlearnerChannel , https://t.me/s/nCoV2019

**Comment by BeautyYuYanli** [comment]
或者可以加一个参数规定如何生成标题? 的确不同频道的维护者习惯都不同

**Comment by NeverBehave** [comment]
> 或者可以加一个参数规定如何生成标题? 的确不同频道的维护者习惯都不同

除非能够出一个消息的规范, 否则不是很适合在RSShub这一层进行抽象(要求过于宽泛)

**Comment by BeautyYuYanli** [comment]
我想"从第x行到第y行为标题"这样的规则可以覆盖大多数需求了 毕竟标题一般要单独起一行的吧. 例如上面提到的那两个频道 都是以"第二个非空行"作为标题

**Comment by dumprop** [comment]
"Sorry

This feed does not validate."

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frsshub.app%2Ftelegram%2Fchannel%2FBugBounty
