### ISSUE TITLE
字幕组路由失效

### ISSUE THREAD

**Issue by Trim21** [DIYgod/RSSHub#6618]
- 完整路由地址，包含所有必选与可选参数

https://rsshub.app/zimuzu/resource/36162

- 预期是什么

正常输出rss

- 实际发生了什么

```text
Route requested: /zimuzu/resource/36162
Error message: Unable to parse XML.
```

- 部署相关信息

rsshub.app

**Comment by shaonwu** [comment]
这是人人影视字幕组网站自行清理资源导致的，并非 RSSHub 的 bug 所致，如图
![Screenshot_20210111-113037002](https://user-images.githubusercontent.com/12139963/104145086-b2b6f500-5400-11eb-8510-f3e50b538fb9.jpg)

**Comment by NeverBehave** [comment]
> 这是人人影视字幕组网站自行清理资源导致的，并非 RSSHub 的 bug 所致，如图
> ![Screenshot_20210111-113037002](https://user-images.githubusercontent.com/12139963/104145086-b2b6f500-5400-11eb-8510-f3e50b538fb9.jpg)

Cool, thanks for the feedback!
