### ISSUE TITLE
小红书抓取失败

### ISSUE THREAD

**Issue by wutea7** [DIYgod/RSSHub#6622]
- 完整路由地址，包含所有必选与可选参数

/xiaohongshu/user/5c8889770000000016003acb/notes

- 预期是什么

有抓取结果

- 实际发生了什么

报错 `Execution context was destroyed, most likely because of a navigation`

也偶有报错 `Cannot read property '1' of null` 的时候

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                       |CentOS 7.9               |
| Node version       |               |
| if Docker, version | 20.10.1              |

**Comment by NeverBehave** [comment]
destroy是超时，可以尝试使用 PlayWithDocker 测试一下效果吗？

**Comment by wutea7** [comment]
在 PlayWithDocker 测试后表现与 issue 描述相同，依然是 destroy

**Comment by queensferryme** [comment]
我在本地测试，无法复现该问题。
![image](https://user-images.githubusercontent.com/41495669/104982529-b8dc4100-59bf-11eb-9fc6-4ab06b3cd605.png)

**Comment by RubinTry** [comment]
我这边也一样，用RSSHub的服务去抓取也是失败，而且一直是destroyed，其他方式还没试过

**Comment by BinkZhu** [comment]
有人可以修复一下吗？感谢！ @queensferryme  @NeverBehave

**Comment by TonyRL** [comment]
Routes using puppeteer is working again on demo instance.

**Comment by TonyRL** [comment]
Reopen as this issue seems does not relate to puppeteer on demo instance
