### ISSUE TITLE
[BUG]picuki profile id有字符无法读取

### ISSUE THREAD

**Issue by colinyn428** [DIYgod/RSSHub#6623]
- 完整路由地址，包含所有必选与可选参数
    `/picuki/profile/jun.amaki`
- 预期是什么
希望添加订阅到Feeder
- 实际发生了什么
报错，Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
不知道是否跟id有特殊字符「.」有关系？我添加了一些不带特殊字符的id是OK的。
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v12.14.1     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 403 (Forbidden)
```

**Comment by NeverBehave** [comment]
可以提供不报错的路由实例吗?

**Comment by colinyn428** [comment]
比如 
https://rsshub.app/picuki/profile/minchen333
https://rsshub.app/picuki/profile/epoint2016
不过我刚才试了一下之前报错的链接，又可以添加了，我再观察看看吧，多谢！
