### ISSUE TITLE
现有源直接转换

### ISSUE THREAD

**Issue by thedogb** [DIYgod/RSSHub#6627]
### What feature is it?
将网站现有的rss原样输出

### What problem does this feature solve?
我自建了一个ttrss服务器，但是在国内，有些国外的rss源无法订阅。但是我同时自建了一个rsshub服务器在国外，如果rsshub能够抓取网站已有的rss源，直接原样输出/进行一定的过滤转换，那么对于这种情况就无需设置代理，可以方便使用。除此之外，通过这种方式，也可以对一些rss利用到rsshub的繁简转换、全文提取等功能。

**Comment by NeverBehave** [comment]
对已有的RSS处理这个其实有过一些想法, 但是这个部分的度不好把握, 需要更多反馈

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/discussions/6671
