### ISSUE TITLE
Atom格式问题

### ISSUE THREAD

**Issue by lifegpc** [DIYgod/RSSHub#6628]
格式不规范，content的type为html时必须对内容进行编码并且不能有子元素
https://tools.ietf.org/html/rfc4287#section-4.1.3
现在的返回格式（https://rsshub.app/twitter/user/stang_wm/.atom ）：
```xml
<content type="html" src="https://twitter.com/stang_wm/status/1345874312050352128">
<![CDATA[ Re @KatoHinata233 有那种生理性的过敏…吃香菜的都是什么神人啊（<br><img style src="https://pbs.twimg.com/media/Eq2BjRVUYAAdImL?format=jpg&name=orig" referrerpolicy="no-referrer"> ]]>
</content>
```

**Comment by NeverBehave** [comment]
是只有这一个路由有这个问题吗?

**Comment by lifegpc** [comment]
全部都有问题

**Comment by NeverBehave** [comment]
那看起来可能需要改动lib处理的部分, 我暂时没有对规范太了解
目前有导致不能使用的场景吗?

**Comment by lifegpc** [comment]
我自己写的bot已经加了适配代码，所以现在暂时没有问题，不过最好还是遵守规范吧

**Comment by NeverBehave** [comment]
抱歉, 目前缺少人手, 如果可以欢迎PR

**Comment by queensferryme** [comment]
Atom Feed 的模板位于 `lib/views/atom.art`，去除 `@` 就能开启 HTML 转义。

```diff
         {{ if $e.content }}
-        <content type="html" src="{{ $e.link }}"><![CDATA[{{@ $e.content.html || $e.content.text }}]]></content>
+        <content type="html" src="{{ $e.link }}"><![CDATA[{{ $e.content.html || $e.content.text }}]]></content>
         {{ else if $e.description }}
-        <content type="html" src="{{ $e.link }}"><![CDATA[{{@ $e.description }}]]></content>
+        <content type="html" src="{{ $e.link }}"><![CDATA[{{ $e.description }}]]></content>
         {{ /if }}
```

至于子元素的话，`<![CDATA[]]>` 算是子元素吗？我在 RFC 4287 中没有看到相关说明。

**Comment by lifegpc** [comment]
> Atom Feed 的模板位于 `lib/views/atom.art`，去除 `@` 就能开启 HTML 转义。
> 
> ```diff
>          {{ if $e.content }}
> -        <content type="html" src="{{ $e.link }}"><![CDATA[{{@ $e.content.html || $e.content.text }}]]></content>
> +        <content type="html" src="{{ $e.link }}"><![CDATA[{{ $e.content.html || $e.content.text }}]]></content>
>          {{ else if $e.description }}
> -        <content type="html" src="{{ $e.link }}"><![CDATA[{{@ $e.description }}]]></content>
> +        <content type="html" src="{{ $e.link }}"><![CDATA[{{ $e.description }}]]></content>
>          {{ /if }}
> ```
> 
> 至于子元素的话，`<![CDATA[]]>` 算是子元素吗？我在 RFC 4287 中没有看到相关说明。

我使用的xml解析器将该元素识别成了一个子元素

**Comment by queensferryme** [comment]
我在本地使用 [Newsboat](https://newsboat.org/) 和 [Reeder 4](https://reederapp.com/4/) 进行了测试，都可以正常解析。

**Comment by lifegpc** [comment]
我使用的是python3的xml.dom.minidom，解析的结果是被当成一个子节点。

**Comment by NeverBehave** [comment]
Should work, let me know if anything still breaks.

**Comment by lifegpc** [comment]
I will test it.

**Comment by lifegpc** [comment]
LGTM.
