### ISSUE TITLE
instagram标题的长度能否限制下

### ISSUE THREAD

**Issue by brilon** [DIYgod/RSSHub#663]
instagram文字描述经常包含大量标签，生成订阅源后，描述变成了RSS标题，经常出现把RSS阅读器版面撑爆的情况。

建议：只截取一定长度作为RSS标题，完整的放到RSS描述里面。

**Comment by HenryQW** [comment]
有例子吗， 方便我测试。还有你觉得多少长度合适，60个字节？

**Comment by brilon** [comment]
@HenryQW 可以参考RSSHUB微博的标题是截取26个字符，加上省略号。不过我觉得50个字符比较合适。

inoreader里面现在预览instagram的标题：
![snipaste_2018-09-09_04-38-15](https://user-images.githubusercontent.com/60318/45258448-3bb16200-b3ea-11e8-9a40-73b3df71a349.png)

**Comment by HenryQW** [comment]
@brilon 给个例子啊。。。懒得自己找

**Comment by brilon** [comment]
@HenryQW  https://rsshub.app/instagram/user/kcbelford

**Comment by DIYgod** [comment]
我觉得可以加个全局的标题字数限制

**Comment by ruleroller** [comment]
希望不要加限制，微博的rss我都自己后修改成全文显示的。难道你们的rsshub都是只拿来当提醒用的吗，我是直接拿来看的，再点一次进原网页多遭罪啊，正文里有"..."已经很难受了，标题还这样，那就太难看了吧。

如果真的一定要加的话，希望能提供设置选项，也请考虑下那些希望一眼就看完标题的人。

**Comment by HenryQW** [comment]
@ruleroller 限制标题长度是标准做法，标题不应该被拿来做全文显示。

![image](https://user-images.githubusercontent.com/5896343/45266259-2e2ec300-b450-11e8-9e77-81d2740b38b0.png)

**Comment by ruleroller** [comment]
@HenryQW 很奇怪的标准说，可能你和其他部分人喜欢限制标题的长度，那也不能就说是“标准”的吧。所以，我另外补充说如果非要限制标题长度，那行行好，给加个选项吧，喜欢限制的可以自行限制。

**Comment by ruleroller** [comment]
不知道“标准”里限制多长才算符合“标准”，每个人估计又不一样了。

**Comment by DIYgod** [comment]
@ruleroller 你不应该在标题里看全文...

**Comment by ruleroller** [comment]
@DIYgod 你为什么要阻止我喜欢在标题里看尽全文...

你的“全文”是指包含正文部分的意思吗？不管我有没有会错意，我想表达的意思，原内容里标题无论有多长，就让它显示好了，原原本本地显示，也没说要把description里的正文都放在标题里看啊。

真的要限制，如果可能，请提供选项吧，每个人都有自己的喜好，没什么应该不应该的...

**Comment by DIYgod** [comment]
@ruleroller https://baike.baidu.com/item/%E6%A0%87%E9%A2%98 标题（title，head），读音biāotí，是标明文章、作品等内容的简短语句，一般分为总标题、副标题、分标题。常言道：看书先看皮，看报先看题，标题可以使读者了解到文章的主要内容和主旨。

**Comment by DIYgod** [comment]
@ruleroller 标题过长本来就是不正常的现象，想看完整内容完全可以看 description，不然 title 和 description有什么区别

**Comment by HenryQW** [comment]
@ruleroller 开源项目，没有人阻止你自己 fork 部署非常规的东西，但是总体而言限制标题长度是所有软件的做法。你可以试试看开一个2000字标题的 issue。

**Comment by ruleroller** [comment]
@DIYgod 那也顶多体现了元内容的作者“不正常”。我只是单纯地觉得一个工具，修改太多原来它存在的内容，有些越俎代庖了。行吧，你们在Telegram群里都讨论限制多少了，我也不说了，你们开心就好。

**Comment by DIYgod** [comment]
@ruleroller 微博 Twitter Instagram 本身是没有标题的，不存在修改原来内容的情况

**Comment by DIYgod** [comment]
@ruleroller 全部，但长度限制会设置到尽量不影响正常标题，正常标题不会有太长的
