### ISSUE TITLE
求添加Animen的RSS推送

### ISSUE THREAD

**Issue by YunhaoJiang** [DIYgod/RSSHub#664]
根据群里大佬的建议仿照sspai的js写了一个 但很奇怪的是和sspai都一样 在自己服务器上显示Not Found
实在没有能力只好在这里求添加Animen的RSS了
下面是自己写的js内容 但没有测试过...
网址：https://www.animen.com.tw/animen_web/web/news_index
麻烦了！谢谢！

以下为向router.js添加的内容
//Animen新闻
router.get('/animen/news',require('./routes/animen/news'));

以下为RSSHub/routes/animen/news.js的内容
const cheerio = require('cheerio');
const url = require('url');

module.exports = async (ctx) => {
    const getPage = await require('../../utils/puppeteer');
    const page = await getPage();

    const link = 'https://www.animen.com.tw/animen_web/web/news_index';

    await page.goto(link);

    // eslint-disable-next-line no-undef
    const html = await page.evaluate(() => document.querySelector('div.new-series-wrapper').innerHTML);

    const $ = cheerio.load(html);
    const list = $('div.col-md-6 col-sm-6 col-xs-12 one_listbox');

    ctx.state.data = {
        title: 'Animen 动漫新闻',
        link,
        description: 'Animen 动漫新闻',
        item: list
            .map((i, item) => ({
                title: $(item)
                    .find('.title a')
                    .text()
                    .trim(),
                link: url.resolve(
                    link,
                    $(item)
                        .find('.title a')
                        .attr('href')
                ),
               /* author: $(item)
                    .find('.item-author')
                    .text()
                    .trim(), */
            }))
            .get(),
    };
};

**Comment by HenryQW** [comment]
`const html = await page.evaluate(() => document.querySelector('div.new-series-wrapper').innerHTML);` 中的 selector 明显不对

**Comment by YunhaoJiang** [comment]
@HenryQW 好 感谢提醒 我去看一下

**Comment by HenryQW** [comment]
另外，如果网站不需要渲染，可以直接用`axios`提高性能，参照其他任意路由。

**Comment by YunhaoJiang** [comment]
经过修改抓出来的还是不对...应该说是没有内容
方便的话您可以看一看嘛
https://www.animen.com.tw/animen_web/web/news_index
[news.zip](https://github.com/DIYgod/RSSHub/files/2363352/news.zip)

**Comment by HenryQW** [comment]
没有内容说明 CSS selector 错误

**Comment by YunhaoJiang** [comment]
@HenryQW  已经找到错误 目前可以抓到link了 但有个问题是 内页的内容无法抓到 这个怎么解决呢 用Innoreader载入网站的话内容会重复标题 但选择载入网页的话却是正常载入 这个怎么解决呢

**Comment by HenryQW** [comment]
看看 axios 返回的 html 有没有包含你的需要的内容。如果没有说明页面需要渲染，尝试看看能不能找到网站的接口，直接获取数据而不用爬 html。

**Comment by YunhaoJiang** [comment]
@HenryQW 好 非常感谢

**Comment by SettingDust** [comment]
https://www.animen.com.tw/animen_web/api/getNews?keyword=&news_category_id=&news_subcategory_id=&rank=&order_type=&history_date=&page=1&perPage=30
