### ISSUE TITLE
b站自建出错，提示“缺少对应 uid 的 Bilibili 用户登录后的 Cookie 值”

### ISSUE THREAD

**Issue by raining1123** [DIYgod/RSSHub#6668]
- https://rsshub.raining1123.work:1123/bilibili/followings/video/411330?BILIBILI_COOKIE_411330=3270EE0E-008E-EAD8-7507-B12DBBBA9CDC49798infoc

- 严格按照说明来配置的呀，411330是我自己的B站id，3270EE0E-008E-EAD8-7507-B12DBBBA9CDC49798infoc是获取的cookie

- 还是提示“缺少对应 uid 的 Bilibili 用户登录后的 Cookie 值”，是没写对吗？

- docker部署，其他都能正常跑

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
https://docs.rsshub.app/install/
请仔细阅读配置说明, 这类配置需要需要使用环境变量而不是参数
同时, 由于github删除/修改issue仍然会保留日志, 建议您立即推出帐号重新配置: Cookie可以用于登录你的帐号,
