### ISSUE TITLE
《bilibili 用户关注视频动态路由》Cookie值格式问题

### ISSUE THREAD

**Issue by raining1123** [DIYgod/RSSHub#6675]
- /bilibili/followings/video/411330

- 文档里要求在环境变量里配置“对应 uid 的 b 站用户登录后的 Cookie 值”，"点击 dynamic_new 请求，找到 Cookie"

- 如图……，并不知道要复制哪一段出来到环境变量“BILIBILI_COOKIE_{uid}”里

![Snipaste_2021-01-12_09-38-39](https://user-images.githubusercontent.com/17892238/104258465-92e40780-54ba-11eb-8be8-1dd716b2dd62.png)

**Comment by Felix2yu** [comment]
SESSDATA=xxx

**Comment by NeverBehave** [comment]
> SESSDATA=xxx

https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 看起来可以顺便加一下文档

**Comment by NeverBehave** [comment]
9706aff done.

**Comment by ruleroller** [comment]
全部啊，很长的那段都复制过去。难道现在又变化了？

**Comment by EnderAvaritia** [comment]
> 全部啊，很长的那段都复制过去。难道现在又变化了？

可以给个例子吗？

**Comment by hfqi** [comment]
同问，获取cookie后填入格式是怎么样的
