### ISSUE TITLE
增加底部备案号功能

### ISSUE THREAD

**Issue by sfyumi** [DIYgod/RSSHub#6677]
### 这是一个什么样的功能？
在 rsshub 首页底部增加 ICP 备案号，指向工信部官网 https://beian.miit.gov.cn

### 这个功能可以解决什么问题？
国内网站需要对网站备案，并且在底部展示备案号，点击可以跳转到工信部官网。

### 额外描述
阿里云要求添加工信部备案号的文档
https://help.aliyun.com/document_detail/146190.html?&msctype=email&mscareaid=cn&mscsiteid=cn&mscmsgid=3620121010601630465&&spm=a2c4k.11721615.zh-cnc.13&#title-1oz-nkb-91m

**Comment by NeverBehave** [comment]
建议将RSShub监听设置在本地端口, 使用Nginx做反代解决
可以增加相关Nginx配置说明文档

**Comment by sfyumi** [comment]
> 建议将RSShub监听设置在本地端口, 使用Nginx做反代解决
> 可以增加相关Nginx配置说明文档

```
location / {
    proxy_pass http://rsshub;
    sub_filter '<details>' '<p><a href="https://beian.miit.gov.cn/">京ICP备xxxxx号-1</a></p> <details>';
    sub_filter_once on;
}
```
