### ISSUE TITLE
知乎用户动态statusdown

### ISSUE THREAD

**Issue by yche0214** [DIYgod/RSSHub#6686]
- 完整路由地址，包含所有必选与可选参数
    zhihu/people/activities/diygod
- 预期是什么
    有抓取结果
- 实际发生了什么
    this route is empty, please check the original site or create an issue
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        CentOS 7.9       |
| Node version       |               |
| if Docker, version |    20.10.1          |

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
知乎反爬严重，如果是非demo站测试仍然失败请重新开启本issue

**Comment by lincolnguang** [comment]
我这里自建的同样失效了
输出如下信息：

```
Route requested: /zhihu/people/activities/xuan-yuan-87-18
Error message: TypeError: Cannot read property 'actor' of undefined
    at module.exports (/root/RSSHub/lib/routes/zhihu/activities.js:20:27)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/root/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/root/RSSHub/lib/middleware/parameter.js:9:5)
    at async module.exports (/root/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/root/RSSHub/lib/middleware/template.js:15:5)
    at async /root/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/root/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/root/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/root/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/root/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/root/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/root/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/root/RSSHub/lib/middleware/onerror.js:20:9)
```

**Comment by NeverBehave** [comment]
#6468 Related

**Comment by Liu-Guang** [comment]
同样的问题
Error message: TypeError: Cannot read property 'actor' of undefined

**Comment by yche0214** [comment]
自建，非demo，已失效。Error message: TypeError: Cannot read property 'actor' of undefined

**Comment by OdinZhang** [comment]
自建也失效了，docker，用的docker-compose

**Comment by Colin-XKL** [comment]
原有的自建失效，本来以为是服务器IP被知乎禁了，后面又换了一台新的，结果还是403。初步测试知乎用户文章、回答的路由的RSS都失效了

**Comment by KwToPA** [comment]
发现rsshub.app 的用户回答
```
/zhihu/people/answers/:id
```
正常工作。自建的亦如是

**Comment by RekiDunois** [comment]
> 发现 rsshub.app 的用户回答
> 
> ```
> /zhihu/people/answers/:id
> ```
> 
> 正常工作。自建的亦如是

怕不是知乎修改用户动态而导致的？

**Comment by wayoungofustc** [comment]
---
name: 🐛 Bug 报告
about: zhihu people/activities/id ERROR 2021.01.15
---

- 完整路由地址，包含所有必选与可选参数
    - Localhost:1200/zhihu/people/activities/diygod
- 预期是什么
    - The webpage can return a xml page as rss format
- 实际发生了什么
    - The webpage return
 ```
TypeError: Cannot read property 'actor' of undefined
    at module.exports (/app/lib/routes/zhihu/activities.js:20:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
- 部署相关信息
> Using https://docs.rsshub.app/install/#docker-compose-bu-shu-an-zhuang

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Linux 4.4.59+ x86_64|
| Node version       |               |
| if Docker, version |Docker version 18.09.8, build bfed4f5|

- 额外信息（日志、报错等）
 ```
TypeError: Cannot read property 'actor' of undefined
    at module.exports (/app/lib/routes/zhihu/activities.js:20:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gin3715** [comment]
> > 发现 rsshub.app 的用户回答
> > ```
> > /zhihu/people/answers/:id
> > ```
> > 
> > 
> > 正常工作。自建的亦如是
> 
> 怕不是知乎修改用户动态而导致的？

网页版知乎的动态请求的API是"https://www.zhihu.com/api/v3/moments/${id}/activities"，可能是API地址改了？

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/6686#issuecomment-761261366
我不太清楚，以用户[https://www.zhihu.com/people/excited-vczh](https://www.zhihu.com/people/excited-vczh)为例子，api看起来是
```
https://www.zhihu.com/api/v3/moments/excited-vczh/activities?limit=7&session_id=一串数字&after_id=一串数字&desktop=true
```

**Comment by buzhangjiuzhou** [comment]
也遇到了同样的情况

**Comment by Azureki** [comment]
自建是用的哪里的服务？有没有可能是知乎禁了ip段？

**Comment by buzhangjiuzhou** [comment]
> 自建是用的谁家的服务？有没有可能是知乎禁了ip段？

我用的是BuyVM家的，应该不是被知乎ban了ip，我用知乎订阅日报专栏都还可以用。

**Comment by gin3715** [comment]
https://github.com/DIYgod/RSSHub/issues/6686#issuecomment-761725048

我fork了一份把url改成了`https://www.zhihu.com/api/v3/moments/${id}/activities?limit=7&desktop=true`，测试下来应该可以正常使用。https://github.com/gin3715/RSSHub/commit/098bceb13f3633a801822baf219b341b338006b0

**Comment by buzhangjiuzhou** [comment]
> [#6686 (comment)](https://github.com/DIYgod/RSSHub/issues/6686#issuecomment-761725048)
> 
> 我fork了一份把url改成了`https://www.zhihu.com/api/v3/moments/${id}/activities?limit=7&desktop=true`，测试下来应该可以正常使用。[gin3715@098bceb](https://github.com/gin3715/RSSHub/commit/098bceb13f3633a801822baf219b341b338006b0)

你可以pull 一个request到这里吗？我用的是docker 部署的，自己其实也不太懂其中的操作，我刚刚试了一次想在docker容器内修改，但是没接触过js，所以最后也没搞明白。

**Comment by Adam-Teng** [comment]
知乎其他路由正常，用户动态shutdown
RSSHub站点报错信息如下：
Route requested: /people/activities/diygod
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /people/activities/diygod
Node version: v16.3.0
Git Hash: 159775e
自建站点和本地手动部署同样报错

**Comment by gin3715** [comment]
试了下，好像是必须在http headers中包括`x-zse-93`, `x-zse-96`, `x-zst-81`这几项进行校验，具体算法不清楚

**Comment by KwToPA** [comment]
> 看样子是x-zse-93这套被拿到用户动态上了 https://github.com/DIYgod/RSSHub/blob/master/lib/v2/zhihu/question.js#L45 可能要把这套搬过来

https://github.com/DIYgod/RSSHub/issues/9917#issuecomment-1150133498
