### ISSUE TITLE
希望增加《央视每周质量报告》

### ISSUE THREAD

**Issue by hailangorz** [DIYgod/RSSHub#669]
地址：http://tv.cctv.com/lm/mzzlbg/videoset/index.shtml
个人用FEED43做了一个，但不是很理想。这个栏目挺不错的。

**Comment by DIYgod** [comment]
Done. a33e29b6d598ac3a14b5f365343a4d4c6c71e20c

**Comment by hailangorz** [comment]
> 完成。[a33e29b](https://github.com/DIYgod/RSSHub/commit/a33e29b6d598ac3a14b5f365343a4d4c6c71e20c)

感谢。
