### ISSUE TITLE
dcard 相关路由全都不能用了，403 错误。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#6697]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/dcard/posts/popular
https://rsshub.app/dcard/funny/popular
- 预期是什么
正常现实条目
- 实际发生了什么
![image](https://user-images.githubusercontent.com/3047708/104567374-ae513d00-5689-11eb-8cef-19bad39556da.png)

- 部署相关信息
官方demo和自建最新。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
官方demo和自建的都报403。

是不是api失效了？
或是RSSHub被反爬屏蔽了呢？

不知道如果用以前的旧方法直接抓网页能不能抢救回来？  #4041

**Comment by scholar9453** [comment]
所以現在Dcard不能爬蟲了嗎?
包含api或一般網頁bs4都不給爬=  =

**Comment by geerda123** [comment]
自建无效，需要修复

**Comment by ruleroller** [comment]
似乎好了，暂时先关闭此issue了，如果复现，再重开吧。

**Comment by geerda123** [comment]
@ruleroller 又不行了

**Comment by ruleroller** [comment]
@geerda123 好像是这样的。不知道是dcard那边主动还是被动的限制了。

换成 #4014 之前的模式不知道行不行。不然总感觉以后就算好了，也会再坏掉。

issue重开，请有空的大佬们看看，是否能修复一下
