### ISSUE TITLE
Bug report】|知乎| 自建和rsshub.app报均错TypeError: Cannot read property 'actor' of undefined

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#6698]
- 完整路由地址，包含所有必选与可选参数
/zhihu/people/activities/
- 预期是什么
正常运作
- 实际发生了什么
自建和rsshub.app报均错TypeError: Cannot read property 'actor' of undefined
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        centos 7       |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

从昨天开始无法运行

##  谢谢

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/issues/6686
