### ISSUE TITLE
知乎live 上新rss制作难度大吗

### ISSUE THREAD

**Issue by WaldoLife** [DIYgod/RSSHub#67]
知乎live里面有一些还不错的，例如（关于医学方面的）（马虫医生，美国哈佛大学医学院博士后，《一本书读懂前列腺》作者。超过 2 万名听众曾参与他开展的性医学系列讲座。
https://www.zhihu.com/lives/954406975631540224?utm_medium=social&utm_source=ZHShareTargetIDMore）平时打开知乎检查它有没有更新太麻烦，希望作者可以考虑下

**Comment by DIYgod** [comment]
付费内容无法获取
