### ISSUE TITLE
微博图片只能获取九张

### ISSUE THREAD

**Issue by Clackz** [DIYgod/RSSHub#6701]
- **完整路由地址，包含所有必选与可选参数**
https://rsshub.app/weibo/user/3949671123
- **预期是什么**
https://weibo.com/3949671123/JDc8IpR4A
这条微博中一共有18张图片，获取到18张图片
- **实际发生了什么**
实际上只获取到9张图片，后面的图片就看不到了。

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/pull/9067
