### ISSUE TITLE
色花堂没提供magnet连结的文章无法下载

### ISSUE THREAD

**Issue by tmrsm** [DIYgod/RSSHub#6702]
### 路由地址
https://rsshub.app/dsndsht23/103/480

### 预期是什么？
有码高清的全部文章都能透过Flexget或者Synology的Download Station下载。

### 实际发生了什么？
没提供magnet连结的文章无法下载。

### 额外信息（日志、报错等）
---2021/1/17---
查看色花堂的路由得知抓的是以下内容，
const enclosureUrl = postMessage.find('div.blockcode li').text();
但特定发布者的文章blockcode无资料，或者blockcode的内容为片片资讯，以至导出的enclosureUrl错误。

因此是否能改为优先侦测blockcode的内容是否带有magnet连结，若无则改提供附件的.torrent。

或者enclossureUrl直接抓取附件的.torrent。

@junfengP 大佬，能请您协助查看下吗？谢谢。

---2021/1/15---
[这篇文章](https://www.sehuatang.net/forum.php?mod=viewthread&tid=443297&extra=page%3D1%26filter%3Dtypeid%26typeid%3D480)导出的下载连结是
https://www.sehuatang.net/forum.php?mod=viewthread&tid=443297&extra=page%3D1%26filter%3Dtypeid%26typeid%3D480
以至下载的会是forum.php。

[这篇文章](https://www.sehuatang.net/forum.php?mod=viewthread&tid=442559&extra=page%3D2%26filter%3Dtypeid%26typeid%3D480)导出的下载连结是
General Unique ID                      : 71335113643678085749467464322699868043(...后略)
会跳错误，无法下载。

**Comment by junfengP** [comment]
做了如下改动，因为手边没有开发环境 所以测试不了
```
--- a/lib/routes/dsndsht23/index.js
+++ b/lib/routes/dsndsht23/index.js
@@ -1,5 +1,6 @@
 const got = require('@/utils/got');
 const cheerio = require('cheerio');
+const url = require('url');
 
 const host = 'https://www.sehuatang.net/';
 
@@ -90,15 +91,17 @@ module.exports = async (ctx) => {
                 }
             }
             const description = (postMessage.html() || '抓取原帖失败').replace(/ignore_js_op/g, 'div');
-            const enclosureUrl = postMessage.find('div.blockcode li').text();
 
+            const magnet = postMessage.find('div.blockcode li').text();
+            const isMag = magnet.startsWith("magnet");
+            const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));
             const single = {
                 title: title,
                 link: itemUrl,
                 description: description,
                 pubDate: new Date(date).toUTCString(),
                 enclosure_url: enclosureUrl,
-                enclosure_type: 'application/x-bittorrent',
+                enclosure_type: isMag? 'application/x-bittorrent': 'application/octet-stream',
             };
             if (description !== '抓取原帖失败') {
                 ctx.cache.set(itemUrl, JSON.stringify(single));
```

执行`npm run format`提示如下：
```
/root/RSSHub/lib/routes/dsndsht23/index.js
  97:100  error  Unnecessary escape character: \.  no-useless-escape
  97:105  error  Unnecessary escape character: \?  no-useless-escape
  97:110  error  Unnecessary escape character: \=  no-useless-escape
  97:142  error  Unnecessary escape character: \=  no-useless-escape
```
> 因为我是在`chrome`的控制台测试的CSS选择器，所以需要对这些字符转义，不知道在nodejs中不转义是否正常

`application/octet-stream`是从`torrent`文件下载的响应头中获取的，不知道Flexget或者Synology的Download Station能否解析

**Comment by tmrsm** [comment]
感谢大佬协助确认，我rsshub是在synology上自建的，但是我没有编程的基础，不知怎麽协助测试，

看是您申请合并，我反馈测试结果，或是我再摸索看看自建的rsshub可不可以修改跟怎麽修改色花堂的路由。

**Comment by junfengP** [comment]
> 感谢大佬协助确认，我rsshub是在synology上自建的，但是我没有编程的基础，不知怎麽协助测试，
> 
> 看是您申请合并，我反馈测试结果，或是我再摸索看看自建的rsshub可不可以修改跟怎麽修改色花堂的路由。

用SSH连接群晖，执行`docker exec -it RSSHUB容器名 sh`, 然后用`vi` 修改对应路由，最后重启容器

**Comment by tmrsm** [comment]
感谢协助，目前已修改完毕，待有该发布者的新文章，我再来回馈状况。

**Comment by tmrsm** [comment]
> const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));

今天的文章都有磁力连结，所以我在const enclosureUrl测试删去这段"isMag? magnet : "，看是不是直接会取得附件的连结，但跳以下的错误，不知道仅有附件时是不是仍会出错，或是原始写法需要修正。

SyntaxError: Malformed attribute selector: href^=forum.php?mod=attachment]:not([href$=nothumb=yes])
    at parseSelector (/app/node_modules/css-what/index.js:159:12)
    at parse (/app/node_modules/css-what/index.js:82:13)
    at compileUnsafe (/app/node_modules/css-select/lib/compile.js:31:14)
    at select (/app/node_modules/css-select/index.js:18:49)
    at CSSselect (/app/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/app/node_modules/cheerio/lib/api/traversing.js:40:21)
    at Promise.all.list.map (/app/lib/routes/dsndsht23/index.js:104:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by junfengP** [comment]
> > const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum.php?mod=attachment]:not([href$=nothumb=yes])").attr("href"));
> 
> 今天的文章都有磁力连结，所以我测试在const enclosureUrl删去这段"isMag? magnet : "，看是不是直接会取得附件的连结，但跳以下的错误，不知道仅有附件时是不是仍会出错，或是原始写法需要修正。
> 
> SyntaxError: Malformed attribute selector: href^=forum.php?mod=attachment]:not([href$=nothumb=yes])
> at parseSelector (/app/node_modules/css-what/index.js:159:12)
> at parse (/app/node_modules/css-what/index.js:82:13)
> at compileUnsafe (/app/node_modules/css-select/lib/compile.js:31:14)
> at select (/app/node_modules/css-select/index.js:18:49)
> at CSSselect (/app/node_modules/css-select/index.js:41:9)
> at initialize.exports.find (/app/node_modules/cheerio/lib/api/traversing.js:40:21)
> at Promise.all.list.map (/app/lib/routes/dsndsht23/index.js:104:64)
> at process._tickCallback (internal/process/next_tick.js:68:7)

那就是说转义是必须的
```
const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));
```

**Comment by junfengP** [comment]
`npm run format`时可以使用下面的注释跳过检查
`//eslint-disable-line` on the line to disable warnings.
`//eslint-disable-next-line` to line before to disable warnings.

**Comment by tmrsm** [comment]
> `npm run format`时可以使用下面的注释跳过检查
> `//eslint-disable-line` on the line to disable warnings.
> `//eslint-disable-next-line` to line before to disable warnings.

资讯量有点大，我要找找用docker的话要在哪里输入npm run format，还有转义相关。

**Comment by junfengP** [comment]
> 资讯量有点大，我要找找用docker的话要在哪里输入npm run format，还有转义相关。

你不用管这个，我只是写在这，哪天有开发环境了再提交代码，写在这提示我自己。
你就用这行代码试试
```
const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));
```

**Comment by tmrsm** [comment]
> > 資訊量有點大，我要找找用docker的話要在哪裡輸入npm run format，還有轉義相關。
> 
> 你不用管這個，我只是寫在這，哪天有開發環境了再提交代碼，寫在這提示我自己。
> 你就用這行代碼試試
> 
> ```
> const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));
> ```

收到！我等没有磁力连结的文章再来反馈。

**Comment by tmrsm** [comment]
现在高清中文字幕的第3页有不含磁力连结的文章，因此我修改色花路由這句，尾端加入&page=3。
``const link = `${host}forum.php?mod=forumdisplay&fid=${subformId}${typefilter}&page=3`;``

同样会有以下错误
SyntaxError: Malformed attribute selector: href^=forum.php?mod=attachment]:not([href$=nothumb=yes])
at parseSelector (/app/node_modules/css-what/index.js:159:12)
at parse (/app/node_modules/css-what/index.js:82:13)
at compileUnsafe (/app/node_modules/css-select/lib/compile.js:31:14)
at select (/app/node_modules/css-select/index.js:18:49)
at CSSselect (/app/node_modules/css-select/index.js:41:9)
at initialize.exports.find (/app/node_modules/cheerio/lib/api/traversing.js:40:21)
at Promise.all.list.map (/app/lib/routes/dsndsht23/index.js:104:64)
at process._tickCallback (internal/process/next_tick.js:68:7)

我尝试修改到其他页(ex:p17)，可以正常抓取，因此可以肯定这种写法只要遇到有不含磁力连结的文章便会跳错。
`const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=forum\.php\?mod\=attachment]:not([href$=nothumb\=yes])").attr("href"));`

**Comment by junfengP** [comment]
@tmrsm 用\\替换代码中的\

**Comment by tmrsm** [comment]
不知道你的反斜线有没有需要特殊按法，我试了几种方式都是同样的错误。
1. 复制你的反斜线，删除旧的，贴上。
2. 复制你的反斜线，在notepad用取代。
3. 自己打键盘上的反斜线。

**Comment by tmrsm** [comment]
如果是反斜线的问题，我测试把反斜线都删除的话
`const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href^=attachment]:not([href$=nothumb])").attr("href"));`

错误会改跳如下
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at urlParse (url.js:148:13)
    at Url.resolve (url.js:663:29)
    at Object.urlResolve [as resolve] (url.js:659:40)
    at Promise.all.list.map (/app/lib/routes/dsndsht23/index.js:104:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by tmrsm** [comment]
错误理解^跟$了，我把他修改如下，目前没发现其他问题，再观察看看了，感谢大佬提供的各种协助。
`const enclosureUrl = isMag? magnet : url.resolve(host, postMessage.find("a[href*=attachment]:not([href*=nothumb])").attr("href"));`

**Comment by junfengP** [comment]
> 不知道你的反斜线有没有需要特殊按法，我试了几种方式都是同样的错误。
> 
> 1. 复制你的反斜线，删除旧的，贴上。
> 2. 复制你的反斜线，在notepad用取代。
> 3. 自己打键盘上的反斜线。

我的错，我用TG BOT回复的，我回复的内容是 用`\\`替换`\`，估计被TG BOT转义了

**Comment by tmrsm** [comment]
> > 不知道你的反斜线有没有需要特殊按法，我试了几种方式都是同样的错误。
> > 
> > 1. 复制你的反斜线，删除旧的，贴上。
> > 2. 复制你的反斜线，在notepad用取代。
> > 3. 自己打键盘上的反斜线。
> 
> 我的错，我用TG BOT回复的，我回复的内容是 用`\\`替换`\`，估计被TG BOT转义了

可行可行!!!用大佬的写法还是踏实多了，基本测试没问题了。
有磁力抓磁力，没磁力抓附件，妥妥的。
