### ISSUE TITLE
AP News RSS Error

### ISSUE THREAD

**Issue by wb14123** [DIYgod/RSSHub#6706]
## The involved route, with all required and optional parameters
/apnews/topics/:topic

## What is expected

`https://rsshub.app/apnews/topics/apf-topnews/` can get the RSS feed

## What is actually happening

Reports error:

```
Route requested: /apnews/topics/apf-topnews

Error message: (intermediate value) is not iterable
```

## Additional info (logs errors etc)

May because of this PR: https://github.com/DIYgod/RSSHub/pull/6573

`/apnews/topics/apf-topnews` already provides top news, why #6573 add another router?

**Comment by NeverBehave** [comment]
Reverted https://github.com/DIYgod/RSSHub/pull/6707

**Comment by NeverBehave** [comment]
@zphw

**Comment by zphw** [comment]
> @zphw

My PR didnt change anything in the /apnews/topics/ route, n as you can see after reverting /apnews/topics/apf-topnews/ still doesnt work.

**Comment by NeverBehave** [comment]
@wb14123 anything else to add here? 
@zphw if there is an existing one could you merge these two routes?

**Comment by TonyRL** [comment]
`/apnews/topics/apf-topnews` works as of replying.
