### ISSUE TITLE
虎扑得到的routes和文档不一致

### ISSUE THREAD

**Issue by PHenryy** [DIYgod/RSSHub#6709]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/api/routes/hupu
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/api/routes/hupu
```

#### 相关文档地址

- https://docs.rsshub.app/bbs.html#hu-pu

#### 预期是什么
路由返回结果与文档一致

#### 实际发生了什么
缺少了"/hupu/bxj/:id/:order?"的文档说明

**Comment by queensferryme** [comment]
参见 Pull Request #1664，当时出于兼容性目的保留了旧的路由 `/hupu/bxj/:id/:order?`，实际上 `/hupu/bbs/:id/:order?` 与 `/hupu/bxj/:id/:order?` 是同一个路由。

解决方案有两个：
1. 在文档中添加 legacy 说明，建议用户使用新路由 `/hupu/bxj/:id/:order?`
2. 直接移除该路由，据我观察在 Feedly 上大约有个位数用户仍在使用旧的 `/hupu/bbs/:id/:order?`

**Comment by queensferryme** [comment]
我在尝试修改文档 `docs/bbs.md`，做了一个简单的修改：

```diff
 ### 虎扑 BBS 论坛
 
-<Route author="LogicJake" example="/hupu/bbs/bxj/2" path="/hupu/bbs/:id/:order?" :paramsDesc="['板块 id，可在板块 URL 找到', '排序方式，1最新回帖（默认），2最新发帖，3精华帖']"/>
+<Route author="LogicJake" example="/hupu/bbs/bxj/2" path="/hupu/bbs/:id/:order?" :paramsDesc="['板块 id，可在板块 URL 找到', '排序方式，1最新回帖（默认），2最新发帖，3精华帖']">
+
+此路由与旧的 `/hupu/bxj/:id/:order?` 等价，但推荐使用 `/hupu/bbs/:id/:order?`，旧路由可能会在未来被删除。
+
+</Route>
```

但是 `npm run docs:dev` 出来结果是这样空白的：
![image](https://user-images.githubusercontent.com/41495669/105272651-aa705f80-5b4e-11eb-940d-a0e3ae42680a.png)

好像不是个例，我之前也有过这样的情况，但是忘了怎么修好的了😅 。请求帮助～

**Comment by NeverBehave** [comment]
@queensferryme 看一下控制台

**Comment by queensferryme** [comment]
> @queensferryme 看一下控制台

已解决，详见 6577388。
