### ISSUE TITLE
微信-二十次幂自建rsshub有些可以订阅，有些显示blocked，请问有谁知道怎么回事？

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#6710]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/wechat/ershicimi/
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/wechat/ershicimi/l3w1xRjb
```

#### 实际发生了什么
自建rsshub，二十次次幕有些可以获取rss，有些不能显示Response code 404，比如https://www.ershicimi.com/a/l3w1xRjb 可以在自建中查看rss，但https://www.ershicimi.com/a/nQ7LDN37 就不行
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   debian      |
| Node version       |     lastest          |
| if Docker, version |      no         |

**Comment by NeverBehave** [comment]
源路由的问题不在rss解决范围内

请下次issue遵守模版提供对应路由文档链接
