### ISSUE TITLE
Cannot read property 'anchorInfo' of undefined for 喜马拉雅

### ISSUE THREAD

**Issue by Shane-Meng** [DIYgod/RSSHub#6727]
#### 路由地址（不包含参数）

```
/ximalaya
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub-git-rssbud-rules.diy.vercel.app/ximalaya/album/15668441/all
https://rsshub.app/ximalaya/album/15668441/all
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
返回可以订阅到播客软件的文件
#### 实际发生了什么
西马可能改了什么，造成RSSHub不能正确抓取信息了，错误信息见最后
#### 部署相关信息

不懂怎么看，所以找了Issues里某个大神的测试网站，我树莓派上返回的错误是一样的，树莓派各个软件都更新到最新版本了

- 额外信息（日志、报错等）
Looks like something went wrong

Route requested: /ximalaya/album/15668441/all
Error message: Cannot read property 'anchorInfo' of undefined

**Comment by garywill** [comment]
也发现这几天官方的xml有些404了，有些album却可用，奇怪

**Comment by baygixu** [comment]
> 也发现这几天官方的xml有些404了，有些album却可用，奇怪

官方的xml取决于主播是不是托管到podcast，才会生成rss

**Comment by lengthmin** [comment]
@NeverBehave @HenryQW @DIYgod  assign 给我吧 我在写了

**Comment by baygixu** [comment]
> @NeverBehave @HenryQW @DIYgod assign 给我吧 我在写了

谢谢大神
