### ISSUE TITLE
路由中关于 pubDate 的时区问题

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#673]
很多路由中的 `pubDate` 没有按照实际情况就直接采用了`toUTCString()`，其实很多网页返回的都是不包含时区信息的绝对北京时间 (GMT+8)，这样造成了源中生成的时间（GMT+0）永远比网页实际时间落后8小时。

如果确认网页返回的是绝对北京时间，应该使用`dayjs`进行处理。或者考量到部署服务器所在时区，稳妥的做法：
```js
const dayjs = require('dayjs');

const serverOffset = new Date().getTimezoneOffset() / 60; 

dayjs(date)
         .add(( -8 - serverOffset ), 'hour')
         .toISOString();
```

或无依赖的做法：

https://github.com/DIYgod/RSSHub/blob/94434c10bee70a6515f47b2b7fe29cdf00ac1639/routes/weibo/utils.js#L42-L43

**Comment by lengthmin** [comment]
诸位有发现时间错误的路由贴链接在这个issue下呗

**Comment by august22** [comment]
appstore/xianmian里的时间有问题
![xianmian](https://user-images.githubusercontent.com/19642615/45726322-41c8ef00-bbf1-11e8-86f0-74c1a71c9606.png)

**Comment by arjenzhou** [comment]
https://github.com/DIYgod/RSSHub/pull/4280
