### ISSUE TITLE
通信新闻网站RSS订阅更新

### ISSUE THREAD

**Issue by luokai2000** [DIYgod/RSSHub#6730]
网站地址：
https://www.telecompaper.com/

网站描述：
全球通信新闻汇总

需要生成什么内容？
https://www.telecompaper.com/international/news/mobile

问题：原路由将2020年改成2021年后，理由失效，可否将2020这个年份条件去掉？
/telecompaper/news/mobile/2020/China/News

能够按照国家和关键字订阅RSS路由

比如：
按关键字：https://www.telecompaper.com/search/index.aspx?search=Nokia

哎呀， @hoilc 老哥，近期有空吗…… ^_^

也欢迎其他有空的老哥来弄一下啊。

先谢过啦。

**Comment by nczitzk** [comment]
在 rsshub.app 上 [/telecompaper/news/mobile/2021/China/News](https://rsshub.app/telecompaper/news/mobile/2021/China/News) 是正常的呢。

另外，如果想去掉年份的限制，将年份修改为 `all` 即可，如 [/telecompaper/news/mobile/all/China/News](https://rsshub.app/telecompaper/news/mobile/all/China/News) 🤝
