### ISSUE TITLE
无法输出豆瓣广播的全部内容

### ISSUE THREAD

**Issue by aruku7230** [DIYgod/RSSHub#6742]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/douban/people/xxxxxxxx/status/
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/douban/people/xxxxxxxx/status/
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#dou-ban-yong-hu-guang-bo

#### 预期是什么

当用户的广播内容超过了140字，Description 仍然能输出广播的全部内容。

#### 实际发生了什么

当用户的广播内容超过了140字，Description 只能输出前137字（加上...为140字）。

例如：

![original_status](https://user-images.githubusercontent.com/12474218/105176953-4e670480-5b69-11eb-895d-2abb4fed2a8d.png)

![rss_item](https://user-images.githubusercontent.com/12474218/105176969-558e1280-5b69-11eb-9dfe-188e87cf86fd.png)

**Comment by shunf4** [comment]
RSSHub 用的相关接口是 `https://m.douban.com/rexxar/api/v2/`，这个接口本来就拉不到完整数据。如果需要完整数据，可能需要像微博用户个人 RSS 一样逐条请求。

RSS 中能看到的内容应该和豆瓣移动网页端（如 https://m.douban.com/people/156428620/statuses ）是一致的。

**Comment by aruku7230** [comment]
关注的豆瓣友邻的广播有一大部分的内容长度稍微超过140字，不得不要点击原始链接才能查看完整内容，有些不方便（有时会被审查被删，从而再也无法看到完整内容），也降低了阅读效率。请求有时间的话，请考虑改善一下这个RSS路由，使其能够取得广播完整内容。
