### ISSUE TITLE
MIT 科技评论 路由为空

### ISSUE THREAD

**Issue by gth7754125** [DIYgod/RSSHub#6744]
#### 路由地址（不包含参数）

```
https://rsshub.app/mittrchina
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/mittrchina/article
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
.
#### 实际发生了什么
无法访问，
#### 部署相关信息
```script
Route requested: /mittrchina/article
Error message: this route is empty, please check the original site or create an issue
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      ubuntu         |
| Node version       |        latest       |
| if Docker, version |      latest       |

**Comment by NeverBehave** [comment]
请按照格式填写所有必要信息

**Comment by queensferryme** [comment]
MIT 科技评论网站版面有较大变化，原路由已经不再适用。

现在首页主要有两个板块：
- 首页资讯 http://i.mittrchina.com/information/index?limit=10
- 本周热门 http://i.mittrchina.com/information/hot?limit=10

可能需要把原路由 `/mittrchine/article` 拆分成两个路由 `/mittrchina/index` 和 `/mittrchina/hot`。
