### ISSUE TITLE
pixiv: 404 Not Found

### ISSUE THREAD

**Issue by zhihaofans** [DIYgod/RSSHub#675]
pixiv发生了404错误

相关链接 :[https://rsshub.app/pixiv/user/11](https://rsshub.app/pixiv/user/11)

![https://i.v2ex.co/9Z4113w0.png](https://i.v2ex.co/9Z4113w0.png)

**Comment by DIYgod** [comment]
bug，错误处理失效

**Comment by DIYgod** [comment]
Done. 27371c4bc8d21d7d5d4601e45f19e78e8b2557ca
