### ISSUE TITLE
NEW字幕组返回内容的标题与bt磁力链接不对应的问题

### ISSUE THREAD

**Issue by shaonwu** [DIYgod/RSSHub#6759]
#### 路由地址（不包含参数）

```
/newzmz
```

#### 完整路由地址，包含所有必选与可选参数

```
路由: 
/newzmz/:category?

参数:
category, 可选 - 分类，见下表，默认为最近更新
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
返回内容的标题与bt磁力链接一一对应

#### 实际发生了什么
实际返回内容的标题与bt磁力链接并非一一对应，存在偶发性错误，例如2020年1月22日更新的内容，返回的标题是：S0E03 旺达幻视 WandaVision，对应的bt磁力链接下载内容确实 S01E02 的内容，已查看过[原网页](https://ysfx.tv/view/d8e9m7eA.html)的内容，对应关系是没有问题的。

- 额外信息（日志、报错等）
无

**Comment by nczitzk** [comment]
这边测试 2020年1月22日 更新的 S01E03 旺达幻视 WandaVision 返回的是 S01E03 的磁力链接。

对于该路由，每次抓取时都会返回目标页面中最新更新的磁力链接，并非根据标题进行匹配。也许是一开始字幕组更新了 S01E03 标题，同时更新了 S01E03 其他类型的下载链接（如百度网盘等），但此时最新的磁力链接仍为 S01E02，所以返回的就是 S01E02 的磁力链接了 😂

**Comment by shaonwu** [comment]
> 这边测试 2020年1月22日 更新的 S01E03 旺达幻视 WandaVision 返回的是 S01E03 的磁力链接。
> 
> 对于该路由，每次抓取时都会返回目标页面中最新更新的磁力链接，并非根据标题进行匹配。也许是一开始字幕组更新了 S01E03 标题，同时更新了 S01E03 其他类型的下载链接（如百度网盘等），但此时最新的磁力链接仍为 S01E02，所以返回的就是 S01E02 的磁力链接了 😂

原来是这样，感谢解答，谢谢。
