### ISSUE TITLE
[BUG] 知识分子 （/zhishifenzi/news） Response code 500

### ISSUE THREAD

**Issue by resol341** [DIYgod/RSSHub#6767]
- 完整路由地址，包含所有必选与可选参数
    `/zhishifenzi/news/`
- 预期是什么
“参数置空（/zhishifenzi/news）获取所有类别”
- 实际发生了什么
Error message: Response code 500 (Internal Server Error): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
但是路由里面如果加上type参数 （例如/zhishifenzi/news/biology）就没问题
官方和自建都能复现这个错误

- 额外信息（日志、报错等）
```
    Response code 500 (Internal Server Error)
```

**Comment by NeverBehave** [comment]
可能是反爬或者是网站错误，需要更多信息

**Comment by resol341** [comment]
如果是反爬的话是不是应该所有路由都打不开？例如/zhishifenzi/news/biology 就没有问题，只是不加type参数的时候才会Response code 500。 网站看起来是没有问题，请麻烦告知需要什么信息

**Comment by queensferryme** [comment]
官方 demo 和我自建的似乎都没有问题，@resol341 你能再确认一下吗？

![image](https://user-images.githubusercontent.com/41495669/106280406-b87b4b80-61f2-11eb-9f2c-356503aa2926.png)

**Comment by resol341** [comment]
是的，确实没问题了，可能之前只是网站有问题。谢谢！

**Comment by kitaev-chen** [comment]
知识分子还缺少两个比较重要的子版块没有做RSS
http://zhishifenzi.com/column
http://zhishifenzi.com/topic

预期希望能有: 
https://rsshub.app/zhishifenzi/column
https://rsshub.app/zhishifenzi/topic

@yech1990

**Comment by yech1990** [comment]
Hi @kitaev-chen, I will add this two sections once I have time. Thank you for your suggestion.
