### ISSUE TITLE
即刻rss server error

### ISSUE THREAD

**Issue by MisterGlasses** [DIYgod/RSSHub#677]
https://github.com/idealclover/Easy-to-RSS/issues/2#issuecomment-419845726
麻烦请看下这个

**Comment by MisterGlasses** [comment]
另外我发现 提示error 的消息 好象都是个人发布的内容（被收入某个主题） 神秘的完全一致图即刻主题的消息内容没有标题 纯图片 这个主题里的消息基本都是error

**Comment by HenryQW** [comment]
见 #621

**Comment by MisterGlasses** [comment]
我看过那个issue 但是没看懂 有解决办法没有

**Comment by HenryQW** [comment]
@MisterGlasses 解决办法就是针对每一种可能性写一个逻辑
