### ISSUE TITLE
建议twitter不要抓取回复的推文

### ISSUE THREAD

**Issue by brilon** [DIYgod/RSSHub#678]
比如：
https://rsshub.app/twitter/user/yo929_tse

把对话的推文都给抓取了，其实没必要。
再说，如果对话的双方你都没关注，也不会出现在你推特的时间线。

**Comment by ruleroller** [comment]
这应该就是抓取用户发的“所有推文”来用的，自行过滤吧。

**Comment by ruleroller** [comment]
@brilon https://docs.rsshub.app/#%E9%80%9A%E7%94%A8%E5%8F%82%E6%95%B0

**Comment by brilon** [comment]
@ruleroller 这种方式没办法区分回复和推文。如果按@ 字符过滤，那么这类推文都会被过滤掉：

分享类的：
![snipaste_2018-09-10_23-34-47](https://user-images.githubusercontent.com/60318/45307649-248d8400-b552-11e8-8750-0880a107ede4.png)

手工@ 的：
![snipaste_2018-09-10_23-36-43](https://user-images.githubusercontent.com/60318/45307761-6fa79700-b552-11e8-8497-f974e6a59f2b.png)
