### ISSUE TITLE
opencc@1.1.1 install failed

### ISSUE THREAD

**Issue by SiqingYu** [DIYgod/RSSHub#6785]
- The involved route, with all required and optional parameters

This is a known issue from opencc 1.1.1

See: https://github.com/BYVoid/OpenCC/issues/544

- What is expected

`npm install` and `yarn install` should succeed

- What is actually happening

Neither succeed

- Self-deployment information

Bare-metal Linux server

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    Debian GNU/Linux 10 (buster)       |
| Node version       |      v10.23.1         |
| if Docker, version |               |

- Additional info (logs errors etc)

GCC: version 8.3.0 (Debian 8.3.0-6)

Excerpt:

```
gyp ERR! command "/usr/bin/node" "/root/code/RSSHub/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/root/code/RSSHub/node_modules/opencc/build/Release/opencc.node" "--module_name=opencc" "--module_path=/root/code/RSSHub/node_modules/opencc/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
```

**Comment by NeverBehave** [comment]
Should have included in the manual, you need some toolchains to compile this:

For debian based system:

```bash
apt install build-essential -y
```

As there are pre-compiled binary, I haven't tested if the above include all necessary tools. Please let me know if it is working and I will update the manual accordingly. Thank you!

**Comment by SiqingYu** [comment]
@NeverBehave `build-essential` is required to build opencc, but what caused the build to fail is opencc@1.1.1, downgrading to 1.0.6 works for me. Note that this is a problem from an external package, not RSSHub itself. But I think RSSHub should avoid opencc@1.1.1 and wait for opencc to solve its problem.

**Comment by NeverBehave** [comment]
Okay, this one brothers me as well :(. We should really separate these functions I think.

**Comment by hoilc** [comment]
Refer to https://github.com/BYVoid/OpenCC/issues/533#issuecomment-774650316

```
CFLAGS="-O2" CXXFLAGS="-O2" npm install
```

**Comment by BYVoid** [comment]
https://github.com/BYVoid/OpenCC/commit/cd89a3349cf7fc731d6622b4c4ddb3c813695eec might fix the problem.

**Comment by z1429170900** [comment]
> Okay, this one brothers me as well :(. We should really separate these functions I think.



> Should be included in the manual, you need some toolchains to compile this:
> 
> For debian based system:
> 
> ```shell
> apt install build-essential -y
> ```
> 
> As there are pre-compiled binary and I don't have debian env in hands, I haven't tested if the above include all necessary tools. Please let me know if it is working and I will update the manual accordingly. Thank you!

我的系统是centos7 我运行了yum groupinstall "Development Tools" "Development Libraries"
安装opencc成果了
**// 安装结果 start**
[root@localhost RSSHub-master]# npm i opencc@1.1.1 -D

added 4 packages, and audited 2392 packages in 19s

5 vulnerabilities (2 moderate, 3 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
**// 安装结果 end**

但是运行依然有问题
**// 运行开始 start**
[root@localhost RSSHub-master]# npm run start

> rsshub@1.0.0 start
> node lib/index.js

node:internal/modules/cjs/loader:1167
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/local/project/RSSHub-master/node_modules/opencc/build/Release/opencc.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/project/RSSHub-master/node_modules/opencc/node/opencc.js:31:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/project/RSSHub-master/lib/middleware/parameter.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'ERR_DLOPEN_FAILED'
}
npm ERR! code 1
npm ERR! path /usr/local/project/RSSHub-master
npm ERR! command failed
npm ERR! command sh -c node lib/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-11T02_08_09_733Z-debug.log
**// 运行结束 end**

**Comment by NeverBehave** [comment]
目前已经替换opencc，请使用最近分支尝试一下

**Comment by NeverBehave** [comment]
目前正在处理相关打包的问题，重新开启一下

**Comment by z1429170900** [comment]
我这里不只是opencc的问题，我在package里将它去掉了依然安装不成功，环境也装了，能解释一下原因吗┭┮﹏┭┮
[root@localhost RSSHub-master]# npm i
npm ERR! code 1
npm ERR! path /usr/local/project/RSSHub-master/node_modules/re2
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory `/usr/local/project/RSSHub-master/node_modules/re2/build'
npm ERR!   CXX(target) Release/obj.target/re2/lib/addon.o
npm ERR! make: Leaving directory `/usr/local/project/RSSHub-master/node_modules/re2/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.8.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI

**Comment by NeverBehave** [comment]
替换到更方便处理的环境了，如果有问题欢迎反馈，谢谢！
