### ISSUE TITLE
docker版rsshub，youtube订阅报错

### ISSUE THREAD

**Issue by joyous-coder** [DIYgod/RSSHub#6813]
---
name: 🐛 Bug 报告
about: youtube 抓取失败
---

#### 路由地址（不包含参数）

```
/youtube/user/JFlaMusic/
```

#### 实际发生了什么
使用docker进行更新，更到最新版后，抓取youtube上的内容报错。

其他如bilibili，github等网站订阅正常

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  ubuntu 18             |
| Node version       |      v10.19.0        |
| if Docker, version |      20.10.2          |

- 额外信息（日志、报错等）

```
Error message: YouTube RSS is disabled due to the lack of relevant config
```

**Comment by junfengP** [comment]
看部署文档，需要设置`Youtube Key`

**Comment by joyous-coder** [comment]
前天也没做什么配置，直接不好服务就用，youtube也可以抓啊

**Comment by joyous-coder** [comment]
> 看部署文档，需要设置`Youtube Key`

配置了YOUTUBE_KEY，又报了另一个错误：
```
Route requested: /youtube/user/JFlaMusic/
Error message: Cannot read property 'data' of undefined
```
![屏幕截图 2021-01-31 183439](https://user-images.githubusercontent.com/42910684/106381370-2e4e0580-63f3-11eb-85f8-1663b072ffe6.png)

**Comment by NeverBehave** [comment]
主站目前可用，需要更多数据

**Comment by joyous-coder** [comment]
今天有重新申请了一个api密钥，又可以用了 😅,  辛苦了，谢谢
