### ISSUE TITLE
 pixiv 订阅希望可以订阅推荐作品

### ISSUE THREAD

**Issue by poly000** [DIYgod/RSSHub#6850]
### 这是一个什么样的功能？

pixiv首页推荐作品订阅

地址： https://www.pixiv.net/
登录帐号后显示“推荐作品”

**Comment by NeverBehave** [comment]
请提供更多信息：实例地址，具体需要获取什么信息

**Comment by poly000** [comment]
推荐作品很难用于订阅，因为每次获取都会更新……
