### ISSUE TITLE
Problem w/ telegram channel (needs mtproto api)

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#6853]
- The involved route, with all required and optional parameters
https://rsshub.app/telegram/channel/lsh_potok

- What is expected
Fetched data from https://t.me/lsh_potok

- What is actually happening
Looks like something went wrong
Route requested: /telegram/channel/lsh_potok
Error message: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/lsh_potok

- Additional info (logs errors etc)
Because some channels have no preview ( https://t.me/s/lsh_potok redirects to https://t.me/lsh_potok, but channel is valid)
So, looks like tip from doc: "Due to Telegram restrictions, some channels involving pornography, copyright, and politics cannot be subscribed." (but there nothing like this)
Maybe is possible to deal w/ that channels? Maybe using telegram api (like telethon)

**Comment by NeverBehave** [comment]
In the documentation, there is a tips section mentioned about this possible error as well. If you would like to ask for a new feature, please open a separate issue.
