### ISSUE TITLE
请求抓取91porn的今日排行

### ISSUE THREAD

**Issue by jy53655** [DIYgod/RSSHub#6859]
### 网站地址
http://www.91porn.com/index.php
### 网站描述
http://www.91porn.com/index.php
### 需要生成什么内容？
今日排行
### 额外描述
中文rss

**Comment by dumprop** [comment]
http://www.91porn.com/index.php/rss/new/
They already have a rss feed

**Comment by NeverBehave** [comment]
请提供更多信息：截图说明具体栏目

**Comment by SekiBetu** [comment]
91porn反爬严重，一个域名爬几次就被block了，我建议删除对91porn的支持，没有任何意义
