### ISSUE TITLE
草榴社区 t66y 相关路由全都无法使用了

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#6861]
#### 路由地址（不包含参数）

https://rsshub.app/t66y/

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/t66y/7
https://rsshub.app/t66y/16
https://rsshub.app/t66y/post/3286088
等其它

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
正常显示条目
#### 实际发生了什么
![image](https://user-images.githubusercontent.com/3047708/107110207-fe828000-6880-11eb-8b73-014cdf4bd829.png)

#### 部署相关信息
官方demo 和最新自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
烦请作者们看看，是否能抽空修复一下呢？ @zhboner @cnzgray

**Comment by Aiaid** [comment]
Index 的部分解决了， 是因为t66y改了tag的名字。
post的部分还没有解决，看起来是因为改了样式所以提取uid的部分出问题了。 平时不用js所以不确定怎么改。

**Comment by ZXCASD854** [comment]
[>>>>老司机在线看片你懂的](http://618sss.com)

[>>>>老司机在线看片你懂的](http://618sss.com)

[>>>>老司机在线看片你懂的](http://618sss.com)

[>>>>老司机在线看片你懂的](http://618sss.com)

[>>>>老司机在线看片你懂的](http://618sss.com)
