### ISSUE TITLE
[Feature Request]希望增加it之家的rss

### ISSUE THREAD

**Issue by 0312birdzhang** [DIYgod/RSSHub#687]
* 新闻列表: `https://api.ithome.com/xml/newslist/news.xml` 
* 文章详情: `"https://api.ithome.com/xml/newscontent/"+ newsid.toString().slice(0,3) +"/"+newsid.toString().slice(3,6)+".xml"`
如 `https://api.ithome.com/xml/newscontent/350/412.xml`

**Comment by DIYgod** [comment]
你发的不就是 RSS 么

**Comment by 0312birdzhang** [comment]
哈哈，对的。 只是希望可以集成在RSSHub中，这个rss不是所有人都知道的，特别是详情，这个是id要计算的。

**Comment by 0312birdzhang** [comment]
好吧，那我关了
