### ISSUE TITLE
【Bug Report】/weibo/user/id 抓取最大图片数为九，超过限制无法抓取，需要去原博对应条目观看

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#6876]
#### 路由地址（不包含参数）

```
/weibo/user/id
```

#### 完整路由地址，包含所有必选与可选参数

```
/weibo/user/id

```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
抓取原博该条目的全部图片
#### 实际发生了什么
抓取最大图片数为九
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

复现地址：[https://weibo.com/2668890641/K11MEiW0U](https://weibo.com/2668890641/K11MEiW0U)

### 谢谢

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/issues/6701
