### ISSUE TITLE
Pixiv 用户动态 Error

### ISSUE THREAD

**Issue by kumikos** [DIYgod/RSSHub#6879]
#### 路由地址（不包含参数）

```
/pixiv/user/
```

#### 完整路由地址，包含所有必选与可选参数

```
/pixiv/user/46125815
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#pixiv-yong-hu-dong-tai

#### 预期是什么
加载 RSS

#### 实际发生了什么
error: Error in /pixiv/user/46125815: Cannot read property 'user' of undefined

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Synology              |
| Node version       |      v10.23.2         |
| if Docker, version |     19.03.13          |

- 额外信息（日志、报错等）
试过别的用户 ID 都能正确加载, 同一个 ID 下的用户收藏也没问题
默认 demo 好像也有一样问题

**Comment by Azureki** [comment]
https://github.com/upbit/pixivpy/issues/158#issuecomment-776333406
似乎 pixiv 又改了验证方式，原来的登录方法不行了。

**Comment by NeverBehave** [comment]
所以这个问题是和登录有关的吗？

**Comment by xb2016** [comment]
大概看了一下，这个用户的投稿类型全部为 `manga`，而 RSSHub 获取的类型是 `illust`
请尝试将 `/lib/routes/pixiv/api/getIllusts.js:22` 中的 `illust` 改为 `all` 后进行测试
