### ISSUE TITLE
Incorrect format of twitter RSS feed 

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#6886]
- The involved route, with all required and optional parameters
https://rsshub.app/twitter/user/REhints

- What is expected
Valid RSS feed

- What is actually happening
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frsshub.app%2Ftwitter%2Fuser%2FREhints
"This feed does not validate.

    line 35, column 39: Invalid email address: REhints (20 occurrences) ["

Same bug on https://rsshub.app/twitter/user/BugsChromium

**Comment by NeverBehave** [comment]
It is impossible to acquire the real author email at this point. We may do a fake email here but it doesnt make any sense.

If there is anything I missed please let me know.
