### ISSUE TITLE
猎趣TV失效

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#6890]
#### 路由地址（不包含参数）
https://rsshub.app/liequtv/room/
```routes
```

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/liequtv/room/175435

#### 相关文档地址

- https://docs.rsshub.app/live.html#lie-qu-tv-zhi-bo-jian-kai-bo

#### 预期是什么
正常显示
#### 实际发生了什么
![image](https://user-images.githubusercontent.com/3047708/107618063-e8fbc480-6c8b-11eb-8979-e4479b7b618e.png)

#### 部署相关信息
官方demo和最新自建 

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
@laampui 大佬能抽空帮忙看看咋回事吗，拜谢啦，新年快乐呀！

**Comment by laampui** [comment]
反爬了，自建吧

**Comment by ruleroller** [comment]
> 反爬了，自建吧

哎，我自建也被反爬了，估计是反整个rsshub啥的。
