### ISSUE TITLE
中华全国总工会

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6899]
### 网站地址
https://www.acftu.org/xwdt/ghyw/?7OkeOa4k=qAkHcArxmXHMCWSeutOj5uLJd2EQGyK8NlzMISs1aR0qqDFO_yJ6qAqq5a
### 网站描述
中华全国总工会，简称全国总工会、全总，是中华人民共和国境内唯一全国性工会联合会。中国共产党领导下的中华全国总工会是“参加中国人民政治协商会议的人民团体”之一，是免于在民政部登记的社会团体[1]。
### 需要生成什么内容？
工会要闻等
### 额外描述
中国为什么劳动生产率这么低？ - ok不提交的回答 - 知乎
https://www.zhihu.com/question/294731762/answer/523723124
我之前就想提来着。很多时候这个工会不起作用，主要活动可能是收钱然后逢年过节发点油之类的礼品？

**Comment by TigerWolfDen** [comment]
不代表工人只知道在过年时发柴米油盐的屑工会有什么订阅的必要么（doge）

**Comment by NeverBehave** [comment]
> 从不代表工人只知道在过年时发柴米油盐的屑工会有什么订阅的必要么（doge）

請保持討論友善的氛圍，謝謝
