### ISSUE TITLE
世界社会主义网

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6900]
### 网站地址
https://www.wsws.org/zh
### 网站描述
WSWS每天发布来自世界各地的新闻和事件的文章和分析。该站点还涵盖了工人阶级政治和有组织的劳工运动的历史。WSWS成立于1998年2月14日。它通过读者和支持者的捐赠来维持自身。大卫·诺斯（David North）担任该站点国际编辑委员会主席。
### 需要生成什么内容？
中文的内容。
### 额外描述
https://www.wsws.org/cn/rss.xml 啥都没有。
![image](https://user-images.githubusercontent.com/44609485/107723599-84d51100-6d1c-11eb-929a-448cba1a9877.png)
https://www.wsws.org/en/rss.xml 默认的en英语才有内容

**Comment by tomyangsh** [comment]
恁就是康米小废物？

**Comment by TigerCubDen** [comment]
站点已经自带中文源：https://www.wsws.org/zh/rss.xml
把额外描述中的 cn 改成 zh 就可以了
