### ISSUE TITLE
NEW字幕组RSS失效

### ISSUE THREAD

**Issue by shaonwu** [DIYgod/RSSHub#6902]
#### 路由地址（不包含参数）

```
/newzmz
```

#### 完整路由地址，包含所有必选与可选参数

```
路由: 

/newzmz/:category?

参数:

category, 可选 - 分类，见下表，默认为最近更新

最近更新 | 剧集推荐 | 电影推荐 | 纪录片推荐 | 动画推荐 | 真人秀推荐
-- | -- | -- | -- | -- | --
1 | 2 | 3 | 4 | 5 | 6

```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
正常运行

#### 实际发生了什么
失效

- 额外信息（日志、报错等）

Route requested: /newzmz
Error message: Invalid URL: #

**Comment by queensferryme** [comment]
路由似乎没出问题，@shaonwu 你能再确认一下吗？
- 路由 https://rsshub.app/newzmz
- 文档 https://docs.rsshub.app/multimedia.html#new-zi-mu-zu

**Comment by shaonwu** [comment]
> 路由似乎没出问题，@shaonwu 你能再确认一下吗？
> 
> * 路由 https://rsshub.app/newzmz
> * 文档 https://docs.rsshub.app/multimedia.html#new-zi-mu-zu

之前失效了5天左右，现在又莫名其妙好了，有点玄学，我把它关了吧
