### ISSUE TITLE
片源网RSS失效

### ISSUE THREAD

**Issue by shaonwu** [DIYgod/RSSHub#6904]
#### 路由地址（不包含参数）

```
/pianyuan
```

#### 完整路由地址，包含所有必选与可选参数

```
/pianyuan
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
正常运行

#### 实际发生了什么
失效

- 额外信息（日志、报错等）

Route requested: /pianyuan
Error message: this route is empty, please check the original site or create an issue

**Comment by NeverBehave** [comment]
http://www.pianyuan.tv/ 域名变更
