### ISSUE TITLE
Incorrect parsing in docker hub

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#6914]
- The involved route, with all required and optional parameters
https://rsshub.app/dockerhub/build/mailcow/postfix

- What is expected
Last tag info (11 feb 2021)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/34004367/107847651-4192a500-6de5-11eb-9a1c-d49a950252cd.png">

- What is actually happening
There info about old tag (12 may 2017)
![image](https://user-images.githubusercontent.com/34004367/107847688-7e5e9c00-6de5-11eb-8b3c-696677738a4c.png)
<img width="358" alt="image" src="https://user-images.githubusercontent.com/34004367/107847693-8a4a5e00-6de5-11eb-95c5-6614e75d81b2.png">

**Comment by NeverBehave** [comment]
The default tag followed is latest. you may subscribe via https://rsshub.app/dockerhub/build/mailcow/postfix/1.58

![Screenshot_20210213_143135](https://user-images.githubusercontent.com/17120571/107859557-4ae13900-6e08-11eb-9813-694011bb73ef.png)

There is no tag rss yet, if you would like to request a rss enhancement, please open another issue. Thank you.
