### ISSUE TITLE
Get feed about latest tags in docker hub

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#6916]
### What feature is it?
Get info about new tags

### What problem does this feature solve?
Last tag info (11 feb 2021)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/34004367/107847651-4192a500-6de5-11eb-9a1c-d49a950252cd.png">

- What is actually happening
There info about old tag (12 may 2017), not about new 
![image](https://user-images.githubusercontent.com/34004367/107847688-7e5e9c00-6de5-11eb-8b3c-696677738a4c.png)
<img width="358" alt="image" src="https://user-images.githubusercontent.com/34004367/107847693-8a4a5e00-6de5-11eb-95c5-6614e75d81b2.png">

**Comment by NeverBehave** [comment]
related #6914 

this issue is asking for subscribe tags instead of a specific changes of tags

**Comment by dumprop** [comment]
Or get info about new tags
