### ISSUE TITLE
深影译站指定剧集未优先返回bt磁力链接的问题

### ISSUE THREAD

**Issue by shaonwu** [DIYgod/RSSHub#6918]
#### 路由地址（不包含参数）

```
/shinybbs
```

#### 完整路由地址，包含所有必选与可选参数

```
路由: 
/shinybbs/p/:id

参数:
id, 必选 - 剧集 id，可在剧集页 URL 中找到
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
获取深影译站指定剧集的bt磁力下载链接

#### 实际发生了什么
返回的数据未优先返回bt磁力链接，其中混杂着电驴ed2k和网盘链接，不便于下载。

- 额外信息（日志、报错等）
无

**Comment by TonyRL** [comment]
`https://sub.shinybbs.vip` is dead.
