### ISSUE TITLE
Having trouble for ARM device

### ISSUE THREAD

**Issue by stillli** [DIYgod/RSSHub#6920]
Deployed through docker/compose in ARM device.

Redis potentially get 100% CPU usage.
Rsshub itself also report error according to the log.

Thanks

**Comment by NeverBehave** [comment]
RSSHub is not a small application at this moment, though we are exploring possible option to reduce its size if only a few routes required. 
I will leave this issue open but in the near future, performance won’t be high priority task.

**Comment by youzhi1233** [comment]
解决了吗
