### ISSUE TITLE
头条新闻用workflow看不到时间

### ISSUE THREAD

**Issue by lupin92** [DIYgod/RSSHub#693]
很多rss放在ifttt上都报错
包括地震速报、气象预警、推特。

**Comment by ylc395** [comment]
@lupin92 IFTTT偶尔报错但不影响使用

**Comment by lupin92** [comment]
哦，回头在加进去…
那你试试今日头条放在workflow里，获取不了时间…

**Comment by DIYgod** [comment]
你是指[今日头条](https://docs.rsshub.app/#%E4%BB%8A%E6%97%A5%E5%A4%B4%E6%9D%A1)？数据和在阅读器里都是正常的

**Comment by lupin92** [comment]
不晓得，workflow里的rss获得不了时间。想用关键词搜些新闻看看，有些新闻都好几个月了，想把不新鲜的去掉，把各种关键词的新闻用html在网页看，有兴趣的在打开看看内容…可是获得不了时间…

**Comment by lupin92** [comment]
就那个今日头条…

**Comment by DIYgod** [comment]
应该不是 RSS 的问题，issue 暂时关闭
