### ISSUE TITLE
日志序列logseq

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6933]
### 网站地址
https://logseq.com/blog/changelog
### 网站描述
本地优先，非线性，笔记本组织和分享您的个人知识库。
### 额外描述
有一段时间了，明明插件显示有rss的，但是
![image](https://user-images.githubusercontent.com/44609485/107961636-22606700-6fe1-11eb-9859-79e8614feebc.png)

![image](https://user-images.githubusercontent.com/44609485/107961526-00ff7b00-6fe1-11eb-9df5-198928ad2671.png)

![image](https://user-images.githubusercontent.com/44609485/107961561-09f04c80-6fe1-11eb-98af-dc5c0332ea4a.png)
一直不能订阅。

**Comment by Fatpandac** [comment]
这个路由似乎不是一个RSS路由
该网站提供的路由只有`https://logseq.com/blog/latest.rss`这一个
