### ISSUE TITLE
记住笔记remnote

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub#6934]
### 网站地址
https://www.remnote.io/updates
### 网站描述
remnote=anki【间隔重复】+roam research【双链笔记】 remnote=remember+note。不知道翻译成啥好，记住笔记？【太过简单而直白，搞的有点不习惯了】
anki→暗记，roam research→漫游研究者，很少有人叫他们的中文名字。我比较喜欢敲中文，输入法记录了之后 输入很方便。
### 需要生成什么内容？
更新日志
### 额外描述
双链笔记革新 自印象笔记evernote以来的知识管理方式之后 连以往传统的更新日志的发布方式也一起改了。除了logseq好像都不支持rss？【可能有其他的也支持，不是很清楚】

**Comment by sepwolves** [comment]
强烈支持

**Comment by TonyRL** [comment]
Closed in #10588
