### ISSUE TITLE
小宇宙：一档播客的新单集

### ISSUE THREAD

**Issue by notofoe** [DIYgod/RSSHub#6941]
### 网站地址

https://www.xiaoyuzhoufm.com/

### 需要生成什么内容？

播客单集目录的最新更新，例如：https://www.xiaoyuzhoufm.com/podcast/6021f949a789fca4eff4492c

（注：上述播客至少在2月16日之前，无法导出RSS feed订阅地址。）

![](https://user-images.githubusercontent.com/43095406/108091772-fb746480-70b6-11eb-9a06-c08f590e2521.jpeg)

**Comment by Arler2016** [comment]
支持

**Comment by baygixu** [comment]
我也想要，现在似乎越来越多小宇宙自家的了，如果能导出小宇宙播客的rss就好了，qq音乐也可以啊

**Comment by wwfcnu** [comment]
小宇宙的播客rss，只能显示一个播客最近的15条信息，可以获取所有的吗
