### ISSUE TITLE
bilibili UP主投稿 Rss 抓取显示空白

### ISSUE THREAD

**Issue by longshensanjie** [DIYgod/RSSHub#6943]
![image](https://user-images.githubusercontent.com/16282697/108170492-2e5d3d80-7135-11eb-9b0a-ceafb5bc790f.png)

随便抓取了b站几个up的投稿显示都如上图是undefined的, 相反抓取up的更新动态则有内容, 显示没有问题

**Comment by TigerCubDen** [comment]
我这里运行正常，不知道你那边是什么原因。
<img src="https://s3.ax1x.com/2021/02/17/y2ywTg.png" alt="y2ywTg.png" border="0" />

**Comment by longshensanjie** [comment]
难道是因为我没有自建 RSSHub 服务吗
