### ISSUE TITLE
部署后，一直处于Welcome to RSSHub!界面

### ISSUE THREAD

**Issue by key153** [DIYgod/RSSHub#695]
按照部署文档，一直到了npm start
> rsshub@0.0.1 start D:\RSSHub
> node index.js

warn: pixiv RSS is disabled for lacking config.
warn: Disqus RSS is disabled for lacking config.
warn: Twitter RSS is disabled for lacking config.
warn: Youtube RSS is disabled for lacking config.
warn: Telegram RSS is disabled for lacking config.
warn: GitHub Repos RSS is disabled for lacking config.
info: 🎉 RSSHub start! Cheers!
info: Listening Port 1200

然后登陆 http://127.0.0.1:1200/，就一直处于Welcome to RSSHub!界面，不知道下一步应该怎么办？
麻烦哪位大神可以帮帮忙。

**Comment by DIYgod** [comment]
@key153 docs.rsshub.app

**Comment by key153** [comment]
@DIYgod 我看了半天的文档了，就想问问添加一个类似https://rsshub.app/bilibili/user/article/334958638的，是在哪个文件下面，按照什么样的格式去进行添加？
麻烦了

**Comment by HenryQW** [comment]
使用 RSS 阅读器订阅 [127.0.0.1:1200/bilibili/user/article/334958638](127.0.0.1:1200/bilibili/user/article/334958638)

RSSHub 除生成源之外，不提供阅读，设置等功能。

**Comment by key153** [comment]
@HenryQW 多谢了，我自己试试
