### ISSUE TITLE
订阅任意git repo

### ISSUE THREAD

**Issue by garywill** [DIYgod/RSSHub#696]
想要能够订阅任意git repo，包括commit和tag两种。

有些repo有git web的，一般会自带有commit的rss，但tag没有。
有git web的tag订阅也可以爬web中的tag。如[linux kernel tag](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/refs/tags)。

没有git web那些repo，不知道有没有什么库可以办到。

**Comment by DIYgod** [comment]
git web 有很多，不通用，无法做到任意
