### ISSUE TITLE
小黑盒游戏新闻出现随机性重复内容

### ISSUE THREAD

**Issue by FaintGhost** [DIYgod/RSSHub#6965]
#### 路由地址（不包含参数）

```routes
xiaoheihe/news
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
xiaoheihe/news
```

#### 相关文档地址

- https://docs.rsshub.app/game.html#xiao-hei-he

#### 预期是什么

正常获取内容

#### 实际发生了什么

获取的内容随机性重复

如图：
![](https://i.imgur.com/oCZbaZn.png)

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |         Debian 10      |
| Node version       |        docker       |
| if Docker, version |   19.03.13, build 4484c46d9d            |

- 额外信息（日志、报错等）

rsshub使用watchtower自动更新
使用awesome-ttrss订阅，所有订阅源都使用rsshub只有小黑盒出现了重复内容故猜测应该是小黑盒的订阅源出现问题了

**Comment by hoilc** [comment]
可能是链接query部分有变化，请发一下重复内容的两个链接

**Comment by FaintGhost** [comment]
> 可能是链接query部分有变化，请发一下重复内容的两个链接

请问重复内容的两个链接具体指的什么呢？

**Comment by hoilc** [comment]
> > 可能是链接query部分有变化，请发一下重复内容的两个链接
> 
> 请问重复内容的两个链接具体指的什么呢？

例如对两个「《薄暮传说》……」右键选择「显示网址」

**Comment by FaintGhost** [comment]
> > > 可能是链接query部分有变化，请发一下重复内容的两个链接
> > 
> > 
> > 请问重复内容的两个链接具体指的什么呢？
> 
> 例如对两个「《薄暮传说》……」右键选择「显示网址」

这是两个完全相同文章的链接
`https://api.xiaoheihe.cn/maxnews/app/detail/1957696?from_tag=-1`
`https://api.xiaoheihe.cn/maxnews/app/share/detail/1957696`

其他的例子
`https://api.xiaoheihe.cn/maxnews/app/detail/1956815?from_tag=-1`
`https://api.xiaoheihe.cn/maxnews/app/share/detail/1956815`

`https://api.xiaoheihe.cn/maxnews/app/detail/1957634?from_tag=-1`
`https://api.xiaoheihe.cn/maxnews/app/share/detail/1957634`
