### ISSUE TITLE
部分知乎专栏抓取失败（官网和私有部署）

### ISSUE THREAD

**Issue by wizcabbit** [DIYgod/RSSHub#6983]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/zhihu/zhuanlan/
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/zhihu/zhuanlan/davysay
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#zhi-hu

#### 预期是什么

正常返回专栏的抓取结果

#### 实际发生了什么

部分专栏是可以返回正常结果的，例如官网文章中的示例
https://rsshub.app/zhihu/zhuanlan/googledevelopers

但部分专栏无法返回正常结果，例如
https://rsshub.app/zhihu/zhuanlan/davysay

RSSHub官网返回Error 502，私有部署返回信息：

Error message: Cannot read property 'parent' of undefined

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Ubuntu |
| Node version       |               |
| if Docker, version | 20.10.3 |

- 额外信息（日志、报错等）

**Comment by TigerCubDen** [comment]
自建实例亲测可用，猜测是服务器过载，建议自行搭建测试。

**Comment by TigerCubDen** [comment]
当专栏里面只有视频没有文字时就会报错，返回的api缺少 content 键值。
解决办法，将此类专栏文章返回空字符串处理。
