### ISSUE TITLE
#UP 主投稿   ——失效

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#6989]
- The involved route, with all required and optional parameters
    `/bilibili/user/video/2267573`
- What is expected

- What is actually happening

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v14.15.4     |
| if Docker, version |               |

- Additional info (logs errors etc)
```
    Response code 412 (Precondition Failed)
```

**Comment by lisxray** [comment]
反爬严格，建议自建

**Comment by Crayon-ShinChan** [comment]
我这边是好的。

![image](https://user-images.githubusercontent.com/38809606/109777476-b7e53300-7c3e-11eb-93ec-2005d3e225a9.png)
