### ISSUE TITLE
希望增加南京理工大学通知

### ISSUE THREAD

**Issue by MilkShakeYoung** [DIYgod/RSSHub#699]
- 学校主页 http://www.njust.edu.cn
- 研究生院 http://gs.njust.edu.cn
- 人事处 http://rs.njust.edu.cn
等等

需要提供信息，可以联系我。
dxmcyr[at]gmail.com
MilkShake羊

**Comment by HenryQW** [comment]
欢迎南京理工大学的同学们自主研发 PR

**Comment by MilkShakeYoung** [comment]
那么希望文档和教程更易懂上手一些，没有CS背景的人（我）不太会「自主研发」，TAT

**Comment by MilkShakeYoung** [comment]
1.增加了路由(https://github.com/DIYgod/RSSHub/pull/723/commits/395a758a97e675120c3651dca503147c36055e78)
2.模仿别人写了 .js(https://github.com/DIYgod/RSSHub/pull/722/commits/21074de6247f05b890518ddf071ca2281db5f06f)
3.接下来应该怎么做（测试还是代码需要修改）？

谢谢，
MilkShake羊

**Comment by DIYgod** [comment]
https://docs.rsshub.app/#%E5%8D%97%E4%BA%AC%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6
