### ISSUE TITLE
Pixiv does not display everything

### ISSUE THREAD

**Issue by Anonny96** [DIYgod/RSSHub#70]
Hello, I want to use this software for pixiv but I've found that it's unsatisfactory. It doesn't even work

It does not display everything the artist has uploaded.

Example:
This artist has 88 artworks uploaded: 
https://www.pixiv.net/member_illust.php?id=15944372&type=illust
The software does not generate everything, only 5 pieces of artwork.
https://rss.now.sh/pixiv/user/15944372

Displayed in my RSS reader is only 5 pieces of artwork (I have attached the screenshot as well).
Screenshot: https://i.imgur.com/fGw00Fo.jpg

Would you be able to continue developing this software to support pixiv?
![main 01](https://user-images.githubusercontent.com/38956330/39589321-f6bb3bb4-4f51-11e8-98fc-2495ea3fa2a9.png)

**Comment by DIYgod** [comment]
It's RSS, not API.

**Comment by Anonny96** [comment]
Your software literally does not even work. Did you not read my post?

**Comment by ciskonc** [comment]
rss 订阅的输出的不是最近的5个图片。

**Comment by Anonny96** [comment]
Then this software is useless. What's the point?
