### ISSUE TITLE
豆瓣小组路由异常

### ISSUE THREAD

**Issue by tree7ion** [DIYgod/RSSHub#7003]
#### 路由地址（不包含参数）

```routes

/douban/group/:groupid

```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes

https://rsshub.app/douban/group/camera 

```

#### 预期是什么

恢复正常的feed

#### 实际发生了什么

目前日期停留在1月21日，就无法再获取最新的帖子了

#### 官网状态截图：
![image](https://user-images.githubusercontent.com/49227131/108690535-6f8a8e80-7535-11eb-9e8e-fbf9c3932090.png)

**Comment by Azureki** [comment]
哪个组有问题？你在1楼举的例子没问题啊……
https://rsshub.app/douban/group/camera

**Comment by tree7ion** [comment]
你好，我这边七八个组都试过不行，后来随便找了两个组也不行，就以为是整个出了问题，就没有单独列出了。比如豆瓣鹅组：blabla

**Comment by Azureki** [comment]
“日期停留在1月21日”意思是RSS阅读器中吗？你打开RSS地址试试。
我自建的RSSHub是可以获取最新文章的。如果你不是自建的，使用 https://rsshub.app/douban/group/blabla ，打开后提示
> target website might be blocking our access

应该是ip被豆瓣封了。

**Comment by tree7ion** [comment]
我用的chrome插件，没有这句提示不过确实接收不到更新了。如果被封的话，还有办法解决吗？

**Comment by tree7ion** [comment]
又换了几个阅读器，发现如果小组id是6位数字则无法获取，如果是自定义英文则可以

**Comment by 1Step2Talk** [comment]
2021年3月9日7点起豆瓣似乎全面禁止不带 apikey 的 API 请求了，提示需要 apikey：
```
{
  "msg": "apikey is required(*.*.*.*). Please contact bd-team@douban.com for authorized access.",
  "code": 131,
  "request": "GET /v2/group/babysheep/topics",
  "localized_message": ""
}
```
带上公开的 apikey `0df993c66c0c636e29ecbb5344252a4a` 后报错如下：
```
{
  "msg": "invalid_credencial2",
  "code": 109,
  "request": "GET /v2/group/638298/topics",
  "localized_message": "非法请求"
}
```
使用本地宽带和4G测试同样会报错。

**Comment by TonyRL** [comment]
https://rsshub.up.railway.app/douban/group/camera is working fine on self hosted instance
