### ISSUE TITLE
APnews rss feed stopped working

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#7015]
https://rsshub.app/apnews/topics/apf-topnews

- The involved route, with all required and optional parameters

- What is expected

- What is actually happening

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- Additional info (logs errors etc)

**Comment by evanlihou** [comment]
It looks like AP News implemented some kind of DDoS protection that changes the HTTP response when RSSHub sends its request. In normal use, it seems like one of those systems that briefly checks your browser and then redirects to the real website. It would be great to get this RSS feed working again though, it's been really useful.

**Comment by TonyRL** [comment]
Closed this in https://github.com/DIYgod/RSSHub/pull/7035
