### ISSUE TITLE
网易云音乐播客无法显示封面

### ISSUE THREAD

**Issue by changzhiga** [DIYgod/RSSHub#702]
在泛用型客户端上订阅后无法显示封面，喜马拉雅没有这个问题。

**Comment by lengthmin** [comment]
把订阅链接发一下呗 
可以的话能不能发下 使用的软件/截图

**Comment by changzhiga** [comment]
- 网易的原链接：https://music.163.com/#/djradio?id=527554619；


- 订阅链接：https://rsshub.app/ncm/djradio/527554619；


- 截图（上面没有封面的是用 RSShub 订阅的，下面一个是正常的封面）：

![img_6549](https://user-images.githubusercontent.com/16465863/45597717-d6212f00-ba02-11e8-9e8a-1ac68231eb4b.JPG)

**Comment by lengthmin** [comment]
看了一下，在我这里是下显示正确的
喜马拉雅和网易云对封面的生成规则是一样的
有可能网易云的图片服务器设置了某些限制。
***
能不能配合下做个测试呢？
* 先订阅这个
https://getpodcast.xyz/data/163/1008.xml
* 再订阅这个
https://rsshub.app/ncm/djradio/1008
看看rsshub生成的源是否没图
来确认一下是不是字段的问题

**Comment by changzhiga** [comment]
试了一下，直接订阅 Rsshub 的链接是有图的。

**Comment by lengthmin** [comment]
北方公园这个还是没图咯？
如果轻松一刻可以的话说明源没问题

**Comment by changzhiga** [comment]
看来可能是电台本身的问题🤔

**Comment by lengthmin** [comment]
再观察一段时间吧 有其他问题再提issue
可以先关掉了

**Comment by changzhiga** [comment]
今天又试了一下，发现是图片缓存下来需要一段时间，等待片刻就好了，完全没有问题。
