### ISSUE TITLE
Please make an rss for  https://www.youtube.com/feed/trending

### ISSUE THREAD

**Issue by wowprimitif** [DIYgod/RSSHub#7020]
Hii DIYgod
how i can get of yt tren rss?
https://www.youtube.com/feed/trending
spesific rss trending for local country or for every each country ?

pls ur help for data
thanks before & sorry my bad english :)

**Comment by magictomagic** [comment]
you can refer to https://www.reddit.com/r/rss/comments/k92hhu/how_to_create_rss_feed_from_youtube_trending/

and add feed:
https://www.youtube.com/feeds/videos.xml?playlist_id=PLrEnWoR732-BHrPp_Pm8_VleD68f9s14-

**Comment by wowprimitif** [comment]
Thank you Sir 😘

**Comment by wowprimitif** [comment]
> you can refer to https://www.reddit.com/r/rss/comments/k92hhu/how_to_create_rss_feed_from_youtube_trending/
> 
> and add feed:
> https://www.youtube.com/feeds/videos.xml?playlist_id=PLrEnWoR732-BHrPp_Pm8_VleD68f9s14-

Thank you Sir 😘
