### ISSUE TITLE
【中国化工报】Rss Wanted - 希望能够推送 /市场信息/国内化工/国际化工/综合要闻 四个板块 ，谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#7023]
### 网站地址
[http://www.ccin.com.cn/](http://www.ccin.com.cn/)
### 网站描述
中化新网是中国化工报社建设的，以关注石油和化工行业为主的的大型新闻信息交互平台。
### 需要生成什么内容？
国际化工：[http://www.ccin.com.cn/c/int_main](http://www.ccin.com.cn/c/int_main)

国内化工：[http://www.ccin.com.cn/c/index_domestic](http://www.ccin.com.cn/c/index_domestic)

综合要闻：[http://www.ccin.com.cn/c/index_news](http://www.ccin.com.cn/c/index_news)

市场信息：[http://www.ccin.com.cn/c/index_market](http://www.ccin.com.cn/c/index_market)

希望能够按照时间顺序推送

### 谢谢

**Comment by vanishcode** [comment]
顺手加了一下，https://github.com/DIYgod/RSSHub/pull/7032

**Comment by KwToPA** [comment]
> 顺手加了一下，#7032

谢谢，不过此路由何时能合并? All checks have passed ,9 successful checks  感觉应该没什么问题了

**Comment by vanishcode** [comment]
> > 顺手加了一下，#7032
> 
> 谢谢，不过此路由何时能合并? All checks have passed ,9 successful checks 感觉应该没什么问题了

这项目估计不维护了，有需要自己clone吧

**Comment by KwToPA** [comment]
@NeverBehave 您好，请问合并的前提条件是需要维护吗？  如果不需要，能否帮忙合并一下？ 谢谢

**Comment by Lao-Liu233** [comment]
> > > 顺手加了一下，#7032
> > 
> > 
> > 谢谢，不过此路由何时能合并? All checks have passed ,9 successful checks 感觉应该没什么问题了
> 
> 这项目估计不维护了，有需要自己clone吧

还有在维护吧...只是上班了开发者空余时间不多。

**Comment by KwToPA** [comment]
[https://github.com/DIYgod/RSSHub/pull/7032 feat: add 中国化工报/中化新网](https://github.com/DIYgod/RSSHub/pull/7032)

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/pull/7220

等合并，我先用FEED43顶住
