### ISSUE TITLE
知乎收藏夹，图片地址转为大图地址

### ISSUE THREAD

**Issue by wizos** [DIYgod/RSSHub#703]
例如：
https://pic2.zhimg.com/80/v2-01c559ea13e9fa45764615a6c8b32bed_b.jpg
https://pic2.zhimg.com/80/v2-01c559ea13e9fa45764615a6c8b32bed_hd.jpg
可以转为：
https://pic2.zhimg.com/80/v2-01c559ea13e9fa45764615a6c8b32bed_r.jpg

只要把后缀改为_r.jpg就是图片的大图地址

**Comment by DIYgod** [comment]
第三个地址 403

**Comment by wizos** [comment]
我这可以打开

**Comment by DIYgod** [comment]
哦可以的，但你给的链接第二个和第三个图片大小是一样的，真的是大图么

**Comment by wizos** [comment]
可以参考这个脚本，把其他站点的图片都优化下：https://greasyfork.org/zh-CN/scripts/2312-resize-image-on-open-image-in-new-tab
