### ISSUE TITLE
腾讯游戏开发者社区的 RSS 支持

### ISSUE THREAD

**Issue by bestony** [DIYgod/RSSHub#704]
http://gameinstitute.qq.com/community

可以按左侧的列表进行拆分

![image](https://user-images.githubusercontent.com/13283837/45583852-13e76000-b8fc-11e8-8bb9-87cbe3f6508f.png)

**Comment by bestony** [comment]
@bestony 这个我试试能不能自己解决战斗😅，开个 issue 记录一下， 后面根据 issue 提pr

**Comment by xyqfer** [comment]
Done. f0a0c363a7a96fb44ec4b6d662f8e8822b4e8316

**Comment by goace** [comment]
又挂了 求修
