### ISSUE TITLE
Error in RSSHub!

### ISSUE THREAD

**Issue by Giter-t** [DIYgod/RSSHub#7060]
#### 路由地址（不包含参数）
```
https://rsshub-4gtill0m30b839d5-1305082721.ap-shanghai.app.tcloudbase.com
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub-4gtill0m30b839d5-1305082721.ap-shanghai.app.tcloudbase.com/github/starred_repos/DIYgod
```

#### 相关文档地址

- https://docs.rsshub.app/programming.html#github-yong-hu-star-de-cang-ku

#### 预期是什么
正常运行
#### 实际发生了什么
ERROR in RSSHub
#### 部署相关信息
使用的腾讯云cloudbase部署，其它RSS订阅可以正常使用，有关Github的（需要添加user参数的会出现错误）

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/67638483/109376987-2eaec300-7903-11eb-8221-91f0031398f0.png)

**Comment by NeverBehave** [comment]
Please read the docs in the error page, thank you.
