### ISSUE TITLE
Bilibili关注视频动态RSS Feed获取时出错

### ISSUE THREAD

**Issue by hiDandelion02** [DIYgod/RSSHub#7071]
#### 路由地址（不包含参数）

```routes
/bilibili/followings/video
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/bilibili/followings/dynamic/:uid/:disableEmbed?
```

#### 相关文档地址
- https://docs.rsshub.app/...

#### 预期是什么
获取RSS Feed

#### 实际发生了什么
Error message: Cannot read property 'name' of undefined

#### 部署相关信息
使用说明文档默认，添加了环境变量Cookie。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       CentOS 7        |
| Node version       |        14.16.0       |
| if Docker, version |       20.10.4        |

- 额外信息（日志、报错等）
Looks like something went wrong
Route requested: /bilibili/followings/video/46982202283
Error message: Cannot read property 'name' of undefined

**Comment by YehowahLiu** [comment]
很明显 uid 46982202283 指向的用户不存在

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
