### ISSUE TITLE
游资网部分 id 没办法订阅 502 error

### ISSUE THREAD

**Issue by Crayon-ShinChan** [DIYgod/RSSHub#7072]
#### 路由地址（不包含参数）

```routes
/gameres/list/:id
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/gameres/list/25
https://rsshub.app/gameres/list/33
# 还有某些其他 id 也无法访问 
```

#### 相关文档地址

- https://docs.rsshub.app/game.html#gameres-you-zi-wang

#### 预期是什么

id 25: 成功订阅游资网策划类文章
id 33: 成功订阅游资网数据类文章

#### 实际发生了什么

Error 502 bad gateway，无法访问

- 额外信息（日志、报错等）

**Comment by hoilc** [comment]
502非路由BUG，为公共实例可用性问题，建议自建

**Comment by Crayon-ShinChan** [comment]
> 502非路由BUG，为公共实例可用性问题，建议自建

尝试了下自建，然后解决了！感谢！！！
