### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by junjieit** [DIYgod/RSSHub#7073]
- 完整路由地址，包含所有必选与可选参数
    `/bilibili/user/channel/54992199/82529`
- 预期是什么
 订阅bilibili-UP 主频道
- 实际发生了什么
页面报错
- 部署相关信息
 https://rsshub.app/bilibili/user/channel/54992199/82529

**Comment by queensferryme** [comment]
Bilibili 反爬严格，建议自建。#7149 也是同样的问题。
