### ISSUE TITLE
请求抓取新华社-新华网新闻

### ISSUE THREAD

**Issue by frankieyue96** [DIYgod/RSSHub#7095]
### 网站地址
http://www.news.cn/whxw.htm
### 网站描述
新华网-新华社新闻频道
### 需要生成什么内容？
全文输出rss
### 额外描述
新华网自带的rss好像也已失效，如果有兴趣也可以抓一下

**Comment by NeverBehave** [comment]
#2086

**Comment by NeverBehave** [comment]
可以贴一下失效rss链接吗
