### ISSUE TITLE
看项目并没有做es6语法的处理，题主是做node环境全局的es6兼容？

### ISSUE THREAD

**Issue by WangZi1997** [DIYgod/RSSHub#71]
![image](https://user-images.githubusercontent.com/19681693/39610053-32e45584-4f80-11e8-81dd-e4a8b9cbbed6.png)

**Comment by tgly307** [comment]
是不是node版本比较低？node在较新的版本中已经支持ES6语法了，不用额外处理

**Comment by DIYgod** [comment]
请更新 node 版本
