### ISSUE TITLE
Github RSS feed doesn't work any more

### ISSUE THREAD

**Issue by corteum** [DIYgod/RSSHub#7100]
- The involved route, with all required and optional parameters
I have created route to github issues list of project 'allegro-api' with filtering of 'news' labels:
https://rsshub.app/github/issue/allegro/allegro-api/open/news

- What is expected
- What is actually happening
It worked for a few weeks, but it doesn't work any more recently. Cloudflare returns 'Error 524', my RSS app returns 'source unreachable' .

**Comment by hoilc** [comment]
The public instance seems to be unstable.

 Self deployment is recommended.

**Comment by chenrui333** [comment]
> The public instance seems to be unstable.

you mean `github.com` for public instance?

**Comment by chenrui333** [comment]
@corteum, you can try `http://gh-feed.imsun.net/`, which works for me.

**Comment by corteum** [comment]
Thanks @chenrui333 , I found that too.
