### ISSUE TITLE
肯请大佬帮忙制作RSS https://ecchi.iwara.tv/

### ISSUE THREAD

**Issue by zuijiasy** [DIYgod/RSSHub#7107]
### 网站地址
https://ecchi.iwara.tv/
### 网站描述
MMD视频网站
### 需要生成什么内容？
指定用户发布的视频及下载地址

**Comment by zuijiasy** [comment]
![1](https://user-images.githubusercontent.com/64622956/109975668-da0dac80-7d35-11eb-91d1-688449332734.png)
![2](https://user-images.githubusercontent.com/64622956/109975672-db3ed980-7d35-11eb-936e-fa73fbad9555.png)

**Comment by hoilc** [comment]
不可行，视频下载地址是会失效的

**Comment by zuijiasy** [comment]
> 不可行，视频下载地址是会失效的

好的，谢谢啦

**Comment by TomIsFat** [comment]
iwara都没人上的嘛
求个大佬只做个视频更新提醒也行阿😭
