### ISSUE TITLE
[BUG]无法抓取豆瓣小组rss

### ISSUE THREAD

**Issue by stipsmong** [DIYgod/RSSHub#7146]
显示status down
呃，看到有其他人反馈是豆瓣api问题了，这个issue请删除或合并吧

- 完整路由地址，包含所有必选与可选参数
    `/douban/group/camera`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v14.15.4     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 400 (Bad Request)
```

**Comment by TonyRL** [comment]
Duplicate of #7003
