### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2845815262** [DIYgod/RSSHub#7149]
- 完整路由地址，包含所有必选与可选参数
    `/bilibili/user/fav/396793759/0`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v14.15.4     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 412 (Precondition Failed)
```

**Comment by queensferryme** [comment]
Bilibili 反爬严格，建议自建。

**Comment by TonyRL** [comment]
`/bilibili/user/fav/396793759/0` works as of replying
