### ISSUE TITLE
邮箱设置出错

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#7159]
#### 路由地址（不包含参数）

```
/mail/imap/rss@mala***.net
```

#### 预期是什么
接收邮件讯息
#### 实际发生了什么
```
root@iZwz9is0zhairp9z8f0eo0Z:~# docker run -d --name rsshub -p 1200:1200 -e EMAIL_CONFIG_rss.mala***.net=password=spw*****clalt&host=imap.****com&port=993 diygod/rsshub
[1] 6800
[2] 6801
-bash: diygod/rsshub: No such file or directory
root@iZwz9is0zhairp9z8f0eo0Z:~# "docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
```
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |          Ubuntu 18     |
| Node version       |               |
| if Docker, version |        20.10.5, build 55c4c88       |

- 额外信息（日志、报错等）

**Comment by starsareintherose** [comment]
我改变了指令
```
Looks like something went wrong
Route requested: /mail/imap/rss@malacology.net
Error message: mails.reverse is not a function
```
出现如下报错

**Comment by starsareintherose** [comment]
Sloved, will pr

**Comment by starsareintherose** [comment]
目前出现错误
```
Error message: this route is empty, please check the original site or create an issue

**Comment by starsareintherose** [comment]
继续报错
```
Error message: mails.reverse is not a function

**Comment by starsareintherose** [comment]
已解决，will PR

**Comment by Colin-XKL** [comment]
似乎这个问题并没有被解决。

- 本issue关联的pr中对文档的一处进行了修改，将邮箱设置的两处`&`更改为了`/&`，但是那几个pr并没有被merge，单纯被CI 检测到有问题然后被close了。https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 的文档内容的更新日期在3月7日，邮箱设置处并没有被更改。
- 我在发出本issue时使用当天的最新的rsshub docker镜像自建实例做了测试，无法使用，报错信息为
```
error: undefined
error: Error in /mail/imap/<MYEMAILPROTECT>: mails.reverse is not a function
```
- 测试了将邮箱设置的环境变量更改为`/&`和`\&`，都不能解决此问题

附加信息：
我测试时使用的时自建域名邮箱，腾讯企业邮服务，imap地址已更改，端口也检查过了，IMAP权限也有开启

**Comment by starsareintherose** [comment]
> 似乎这个问题并没有被解决。
> 
> * 本issue关联的pr中对文档的一处进行了修改，将邮箱设置的两处`&`更改为了`/&`，但是那几个pr并没有被merge，单纯被CI 检测到有问题然后被close了。https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 的文档内容的更新日期在3月7日，邮箱设置处并没有被更改。
> * 我在发出本issue时使用当天的最新的rsshub docker镜像自建实例做了测试，无法使用，报错信息为
> 
> ```
> error: undefined
> error: Error in /mail/imap/<MYEMAILPROTECT>: mails.reverse is not a function
> ```
> 
> * 测试了将邮箱设置的环境变量更改为`/&`和`\&`，都不能解决此问题
> 
> 附加信息：
> 我测试时使用的时自建域名邮箱，腾讯企业邮服务，imap地址已更改，端口也检查过了，IMAP权限也有开启

您好，我是docker运行所有有所差别。并且你要检查是不是有app passport，若email为空，也会失败。

**Comment by Colin-XKL** [comment]
OK 我又测试了下可以使用了。
根据我这边的测试，之前不能使用是因为我使用的腾讯企业邮，每一个账号都必须绑定手机和微信才可以使用，设定完之后没有绑定的就不能使用。现在换了另外一家就没有这个限制，设定完邮箱地址就可以直接使用
RSShub这边没有问题

**Comment by starsareintherose** [comment]
> OK 我又测试了下可以使用了。
> 根据我这边的测试，之前不能使用是因为我使用的腾讯企业邮，每一个账号都必须绑定手机和微信才可以使用，设定完之后没有绑定的就不能使用。现在换了另外一家就没有这个限制，设定完邮箱地址就可以直接使用
> RSShub这边没有问题

那就OK，建议Yandex
