### ISSUE TITLE
centos7 已经安装g++，gcc；npm install 始终不成功，而直接在windows上将包传入linux系统也无法成功跑起来

### ISSUE THREAD

**Issue by z1429170900** [DIYgod/RSSHub#7195]
#### 路由地址（不包含参数）

```routes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
npm install成功
#### 实际发生了什么
[root@localhost RSSHub-master]# npm i
npm ERR! code 1
npm ERR! path /usr/local/project/RSSHub-master/node_modules/re2
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory `/usr/local/project/RSSHub-master/node_modules/re2/build'
npm ERR!   CXX(target) Release/obj.target/re2/lib/addon.o
npm ERR! make: Leaving directory `/usr/local/project/RSSHub-master/node_modules/re2/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.8.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/project/RSSHub-master/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/project/RSSHub-master/node_modules/re2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/project/RSSHub-master/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/15.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/project/RSSHub-master/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/project/RSSHub-master/node_modules/re2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /root/.cache/node-gyp/15.8.0/include/node/node.h:63:0,
npm ERR!                  from ../../nan/nan.h:56,
npm ERR!                  from ../lib/./wrapped_re2.h:4,
npm ERR!                  from ../lib/addon.cc:1:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h: In member function ‘void v8::TracedReferenceBase<T>::SetSlotThreadSafe(T*)’:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:22: error: expected type-specifier
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:22: error: expected ‘>’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:22: error: expected ‘(’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:22: error: ‘atomic’ is not a member of ‘std’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:35: error: expected primary-expression before ‘*’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                    ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:36: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                     ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:912:38: error: expected primary-expression before ‘>’ token
npm ERR!      reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
npm ERR!                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:913:54: error: ‘memory_order_relaxed’ is not a member of ‘std’
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:913:80: error: expected ‘)’ before ‘;’ token
npm ERR!                                                       std::memory_order_relaxed);
npm ERR!                                                                                 ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h: In member function ‘const T* v8::TracedReferenceBase<T>::GetSlotThreadSafe() const’:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:29: error: expected type-specifier
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                              ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:29: error: expected ‘>’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:29: error: expected ‘(’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:29: error: ‘atomic’ is not a member of ‘std’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:41: error: expected primary-expression before ‘const’
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                          ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:41: error: expected ‘)’ before ‘const’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:41: error: expected ‘;’ before ‘const’
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:49: error: expected unqualified-id before ‘>’ token
npm ERR!      return reinterpret_cast<std::atomic<const T*> const*>(&val_)->load(
npm ERR!                                                  ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:920:49: error: expected initializer before ‘>’ token
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h: At global scope:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:1631:58: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                  Local<Value> export_value);
npm ERR!                                                           ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:3405:23: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Local<Value> Name() const { return Description(); }
npm ERR!                        ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5223:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5270:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5297:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5307:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5318:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5706:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5755:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
npm ERR!                                                                             ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5764:21: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    bool IsExternal() const;
npm ERR!                      ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5780:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents Externalize();
npm ERR!                         ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5790:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void Externalize(const std::shared_ptr<BackingStore>& backing_store);
npm ERR!                                                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:5805:24: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Contents GetContents();
npm ERR!                         ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7150:28: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t code_range_size() const { return code_range_size_ / kMB; }
npm ERR!                             ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7152:46: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_code_range_size(size_t limit_in_mb) {
npm ERR!                                               ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7156:38: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_semi_space_size_in_kb() const;
npm ERR!                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7158:56: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_semi_space_size_in_kb(size_t limit_in_kb);
npm ERR!                                                         ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7160:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
npm ERR!                                ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7162:49: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_old_space_size(size_t limit_in_mb) {
npm ERR!                                                  ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7166:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    size_t max_zone_pool_size() const { return max_zone_pool_size_; }
npm ERR!                                ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:7168:43: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
npm ERR!                                            ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:8758:59: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                      MeasureMemoryMode mode);
npm ERR!                                                            ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:8821:36: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    Local<Context> GetEnteredContext();
npm ERR!                                     ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9105:22: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
npm ERR!                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9149:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                            ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9157:78: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
npm ERR!                                                                               ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9341:30: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    UnwindState GetUnwindState();
npm ERR!                               ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9404:54: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!        AllowCodeGenerationFromStringsCallback callback);
npm ERR!                                                       ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:9764:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    static bool TryHandleSignal(int signal_number, void* info, void* context);
npm ERR!                                                                            ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:10723:55: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!                                  const void* stack_base);
npm ERR!                                                        ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/v8.h:10749:65: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
npm ERR!    static bool PCIsInV8(const UnwindState& unwind_state, void* pc);
npm ERR!                                                                  ^
npm ERR! In file included from ../../nan/nan.h:56:0,
npm ERR!                  from ../lib/./wrapped_re2.h:4,
npm ERR!                  from ../lib/addon.cc:1:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/node.h: In lambda function:
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/node.h:613:43: error: parameter packs not expanded with ‘...’:
npm ERR!              std::forward<EnvironmentArgs>(env_args)...);
npm ERR!                                            ^
npm ERR! /root/.cache/node-gyp/15.8.0/include/node/node.h:613:43: note:         ‘env_args’
npm ERR! At global scope:
npm ERR! cc1plus: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]
npm ERR! make: *** [Release/obj.target/re2/lib/addon.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/project/RSSHub-master/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 3.10.0-1127.19.1.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/node/node-v15.8.0-linux-x64/bin/node" "/usr/local/project/RSSHub-master/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/project/RSSHub-master/node_modules/re2
npm ERR! gyp ERR! node -v v15.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T11_33_50_595Z-debug.log

#### 部署相关信息
ocent7 py3.8

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
merged with #6785
