### ISSUE TITLE
自己动手：解决官方youtube视频博主订阅失效的方案

### ISSUE THREAD

**Issue by psterman** [DIYgod/RSSHub#720]
官方提供的rss订阅youtuber的方法已失效，更新一个我自己的方案：

关键句型举例
https://www.youtube.com/feeds/videos.xml?channel_id=UCO4sVIFDtO8JhfUi23Pt9Kg

如何查找channel_id？
1.打开你想订阅的youtube博主首页
2.ctrl+f查找“   <href="https://www.youtube.com/channel/**UCO4sVIFDtO8JhfUi23Pt9Kg**">”
3.将id套用到关键句型内即可
4.获得你需要的列表填入rss阅读器内
5.点赞我

各位大爷有空来我b站玩
https://space.bilibili.com/6885201/#/

**Comment by lengthmin** [comment]
官方提供了一个u2b的rss

**Comment by DIYgod** [comment]
感觉不如 RSSHub 的，路由先留着吧
