### ISSUE TITLE
Hugo 博客抓取

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#7214]
### 这是一个什么样的功能？
抓取Hugo搭建博客全文
### 这个功能可以解决什么问题？
Hugo的博客文章抓取
### 额外描述
示例站点 https://xmag.yihui.org

**Comment by queensferryme** [comment]
Hugo 生成的站点默认都有 RSS，例如 https://xmag.yihui.org/index.xml 。

**Comment by starsareintherose** [comment]
> Hugo 生成的站点默认都有 RSS，例如 https://xmag.yihui.org/index.xml 。

Dank
