### ISSUE TITLE
【Google Site】博客 Rss wanted —— 找到一个最近编辑页面

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#7222]
### 网站地址
https://sites.google.com/site/ID/ ，例如[https://sites.google.com/site/outlierseconomics/](https://sites.google.com/site/outlierseconomics/)，其ID为outlierseconomics

我找到了一个最近编辑页面，[https://sites.google.com/site/*/system/app/pages/recentChanges](https://sites.google.com/site/*/system/app/pages/recentChanges)，*代表ID，例如[https://sites.google.com/site/outlierseconomics/system/app/pages/recentChanges](https://sites.google.com/site/outlierseconomics/system/app/pages/recentChanges)
### 网站描述

官方名称叫：Google 协作平台

### 需要生成什么内容？

- [ ] 根据网站ID，按时间顺序生成网站最近编辑的变更内容

### 额外描述

@zoenglinghou ，@hoilc 俩位网友，我找到了一个最近编辑页面，比这个 https://github.com/DIYgod/RSSHub/issues/4007 更好用

zoenglinghou发现Google Site自带rss，[https://sites.google.com/site/*/activity.xml](https://sites.google.com/site/*/activity.xml)，推送结果和recentChanges 一致。

**Comment by zoenglinghou** [comment]
这个页面就自带 RSS Feed 呀，用 RSSHub-Radar 就可以看到：

https://sites.google.com/site/outlierseconomics/activity.xml

**Comment by KwToPA** [comment]
@zoenglinghou   谢谢，没想到还有这xml。经测试，recentChanges和xml反馈的结果是一样的。 不过我发现点击xml推送的标题，跳转的是空白页，[https://sites.google.com/site/*/system/app/pages/](https://sites.google.com/site/*/system/app/pages/)

**Comment by zoenglinghou** [comment]
看起来文章的链接是位于RSS的内容里，可以使用吗？

**Comment by KwToPA** [comment]
@zoenglinghou  只能通过点击内容中的链接跳转。 经过测试，我发现似乎只有三种操作，编辑，创建和删除，其中我最关注的就是创建。

自带rss推送的标题不包含这三种操作方式，只包含操作对象的标题。

例如删除了《XXX》，推送的标题是《XXX》。若能像recentChanges页面那样，推送包含作者和操作方式 "Outliers HKG 已編輯 DSE 經濟學文章"，而不单单是"DSE 經濟學文章"，那就完美。
