### ISSUE TITLE
Matters.news的pubDate缺失

### ISSUE THREAD

**Issue by NodeBE4** [DIYgod/RSSHub#7227]
#### 路由地址（不包含参数）
/matters/
```routes
```

#### 完整路由地址，包含所有必选与可选参数
/matters/author/Luterngun
```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
item中應包含pubDate 
#### 实际发生了什么
item中不包含pubDate
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by NodeBE4** [comment]
https://github.com/DIYgod/RSSHub/pull/7230

麻煩手動合併PR

**Comment by TonyRL** [comment]
Closed in #8056
