### ISSUE TITLE
bilibili起小点专栏无法订阅

### ISSUE THREAD

**Issue by Qeynos** [DIYgod/RSSHub#7232]
#### 路由地址（不包含参数）

/bilibili/user/article/:uid

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/bilibili/user/article/1565155

#### 相关文档地址

https://docs.rsshub.app/social-media.html#bilibili

#### 预期是什么
可以正常订阅

#### 实际发生了什么
rsshub.app显示502，自建rsshub显示"this route is empty"

**Comment by TonyRL** [comment]
https://space.bilibili.com/1565155/article
This user publish 0 articles
