### ISSUE TITLE
微博uid查询失败

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#724]
<img width="760" alt="wx20180917-112558 2x" src="https://user-images.githubusercontent.com/6291329/45605028-795a5e80-ba6c-11e8-9fc2-0bae707ec7c1.png">

---
比如这个 [微博](https://weibo.com/ticktickteam),获取的时候就出错了
![photo_2018-09-17_10-49-06](https://user-images.githubusercontent.com/6291329/45605057-aeff4780-ba6c-11e8-9920-b4d68858ce1f.jpg)

---
目前我的解决方案是查询源代码,然后在里面搜索`fnick`,这个搜索结果第一个前面的就是uid
![photo_2018-09-17_11-04-50](https://user-images.githubusercontent.com/6291329/45605082-d9510500-ba6c-11e8-9b8f-520be7019129.jpg)

**Comment by DIYgod** [comment]
文档已更新 1948bd73dc3aab59d24f357df9b7ccf533a21576

**Comment by brilon** [comment]
其实完全可以不用脚本，打开一个用户任意一条微博，URL就自带uid
譬如：https://weibo.com/1644114654/GzY26u4Y1
uid就是1644114654
