### ISSUE TITLE
npm install fails on windows 2019

### ISSUE THREAD

**Issue by jcmag** [DIYgod/RSSHub#7240]
---
name: 🐛 Bug Report
about: npm install fails
---

I've cloned the repo, and when I execute npm install I get this error:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/postlight/browser-request.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    Windows 2019           |
| Node version       |     14.16.0          |
| npm version |    6.14.11           |

**Comment by zoenglinghou** [comment]
It seems that you need to install `git`

https://stackoverflow.com/questions/58658954/npm-install-returns-syscall-spawn-git-error

**Comment by jcmag** [comment]
> 
> 
> It seems that you need to install `git`
> 
> https://stackoverflow.com/questions/58658954/npm-install-returns-syscall-spawn-git-error

Thanks! it works now
