### ISSUE TITLE
西瓜视频个人页面失效了。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7247]
#### 路由地址（不包含参数）

- https://rsshub.app/ixigua/user/video/

#### 完整路由地址，包含所有必选与可选参数

- https://rsshub.app/ixigua/user/video/3342105524571859

#### 相关文档地址

- https://docs.rsshub.app/multimedia.html#xi-gua-shi-pin

#### 预期是什么
有RSS项目
#### 实际发生了什么
报错，未能生成RSS项目。
#### 部署相关信息
官方demo和自建最新。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/112142740-ef2d7b00-8c11-11eb-9ff5-c35d7fb6ca99.png)

我观察了一下，好像是西瓜视频页面有改版导致出错。

原路由作者 @FlashWingShadow 或者其他路过的大神可以抽空修复一下吗？

多谢啦。

**Comment by yunyu950908** [comment]
#7405
