### ISSUE TITLE
[BUG]keep运动日志路由错误

### ISSUE THREAD

**Issue by wanghuibin0** [DIYgod/RSSHub#7252]
#### 路由地址（不包含参数）

```
/keep/user/5703f54db40371ab37791f32
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/keep/user/5703f54db40371ab37791f32
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#keep

#### 预期是什么
能够以xml格式获取指定keep用户的动态数据

#### 实际发生了什么
服务器程序发生了异常，报错信息参见下面额外信息部分

#### 部署相关信息
访问rsshub.app就会出现此错误。
自己部署也会一样的错误

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | ubuntu 18.04 LTS       |
| Node version       | v14.15.4              |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/14231615/112261176-4bda7580-8ca6-11eb-93ac-8d19c2a0b6ec.png)

**Comment by wanghuibin0** [comment]
### 背景
我是在用rsshub.app解析自己的keep运动日志的时候发现此问题。
### 问题
如本贴一楼所述。
### 原因
经过调试，已经找到了bug发生的原因。
`https://api.gotokeep.com/social/v3/people/${id}/home`返回的数据，一般来说是个人的打卡记录。但是本人的页面返回的数据包含一个特殊的条目，这个条目恰好没有`item.meta.title`这个属性，于是调用其`trim`方法当然报错。
### 解决方法
将这种特殊条目过滤出去，具体来说，在给`ctx.state.data`生成`item`数据时，改`data.map(...)`为`data.filter(...).map(...)`。

怎么把我的bug fix合进去呢？

**Comment by murphysking** [comment]
可以fork这个项目，在自己的项目中修改，然后再提交pr
