### ISSUE TITLE
South China Morning Post - China coronavirus outbreak 这个路由失效。

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7266]
#### 路由地址（不包含参数）

https://rsshub.app/coronavirus/scmp

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/coronavirus/scmp

#### 相关文档地址

https://docs.rsshub.app/other.html#xin-guan-fei-yan-yi-qing-xin-wen-dong-tai-south-china-morning-post-china-coronavirus-outbreak

#### 预期是什么
正常显示RSS条目
#### 实际发生了什么
报错，未能显示RSS条目
#### 部署相关信息
官方demo和自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/112511926-d7025b00-8dcd-11eb-8c7c-b5fb9db17540.png)

**Comment by murphysking** [comment]
该源指向的地址是[https://www.scmp.com/topics/coronavirus-outbreak](https://www.scmp.com/topics/coronavirus-outbreak)，页面已重定向至[https://www.scmp.com/coronavirus](https://www.scmp.com/coronavirus)，规则无效
