### ISSUE TITLE
订阅的 RSS 得到的内容有时间限制，可以访问更早的内容吗

### ISSUE THREAD

**Issue by Crayon-ShinChan** [DIYgod/RSSHub#7291]
#### 路由地址（不包含参数）

```routes
/telegram/channel/:username/:searchQuery?
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/telegram/channel/embypub
```

#### 相关文档地址

https://docs.rsshub.app/social-media.html#telegram

#### 预期是什么

这个频道是 2020 年 12 月开始有消息的，希望获得这个频道 12 月份开始的消息

#### 实际发生了什么

只能够读取最早 2021 年 2 月份的消息

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       CentOS 7        |
| Node version       |               |
| if Docker, version |         20.10.5      |

- 额外信息（日志、报错等）

**Comment by yefoenix** [comment]
rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

**Comment by Crayon-ShinChan** [comment]
> rss 就是用来跟踪内容源的更新内容的，采集全部内容不是rsshub要做的，建议你去找一个爬虫

你说的有道理。

不过不知道 RSSHub 能不能设置比如采集到多少天之前的消息呢？因为有些资源刚加入 RSSHub，可能希望一口气把比如前 120 天的消息在 RSSHub 阅读器读完。

不过上面这个需求也不是刚需，使用者的确可以直接去原来的地方看完那么几个月的所有内容。只是有办法调节的话可能更好。

另一个方面，的确其实更适合爬虫。比如我想要访问一个留学网站在近半年的所有关于某个国家某个专业的筛选消息的话，如果 RSSHub 可以直接调节追溯日期长度的话，可能就可以省了爬虫的事，不过时间太长可能会出现一些运行效率的问题？可能还是爬虫能合适。
