### ISSUE TITLE
中华人民共和国政府部委信息发布

### ISSUE THREAD

**Issue by jefflou** [DIYgod/RSSHub#7297]
### 网站地址
http://www.gov.cn/xinwen/lianbo/bumen.htm
### 网站描述
中华人民共和国政府部委信息发布
### 需要生成什么内容？
政务消息

**Comment by starsareintherose** [comment]
建议关闭
https://docs.rsshub.app/government.html#zhong-guo-zheng-fu-zheng-fu-xin-wen
