### ISSUE TITLE
rsshub的ncm/djradio路由貌似有问题

### ISSUE THREAD

**Issue by lengthmin** [DIYgod/RSSHub#730]
自行测试可以(国外服务器)
![snipaste_2018-09-17_20-16-52](https://user-images.githubusercontent.com/13938334/45622665-52754a00-bab7-11e8-9650-74882ede6130.png)
![snipaste_2018-09-17_20-16-44](https://user-images.githubusercontent.com/13938334/45622680-5b661b80-bab7-11e8-9ae6-cef5cfbced99.png)

**Comment by DIYgod** [comment]
现在是好的，猜测可能网络问题
