### ISSUE TITLE
希望添加蜜柑计划

### ISSUE THREAD

**Issue by uorzen** [DIYgod/RSSHub#7302]
网站
https://mikanani.me/
网站描述

采集季番网站

需要生成什么内容？

每日更新，订阅更新，直接有种子文件

额外描述

**Comment by shaonwu** [comment]
蜜柑计划自带 RSS，https://mikanani.me/RSS/Classic

**Comment by uorzen** [comment]
> 蜜柑计划自带 RSS，https://mikanani.me/RSS/Classic

但是这个不直接输出链接

**Comment by shaonwu** [comment]
> > 蜜柑计划自带 RSS，https://mikanani.me/RSS/Classic
> 
> 但是这个不直接输出链接

你用的什么工具？rss自动下载吗？我这边可以直接获取到bt磁力下载链接
