### ISSUE TITLE
希望添加 nippon.com 的路由

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#7306]
### 网站地址

https://www.nippon.com/cn
目前有七种不同的语言可以选择，简体中文为 cn

### 网站描述

以七种语言为载体，与全世界分享日本的 “今时今日”
这是公益财团法人 Nippon Communications Foundation 及其运营的网站 nippon.com 的抱负，也是我们赋予自己的使命。

日本是拥有高度发达的经济、社会和政治制度的国家，但同时也经受着人口老龄化、生产力停滞不前等诸多问题的困扰。我们将即时介绍日本探索解决这些问题方法，分享给世界各地面临着同样难题的国家。

日本的文化和传统绵延两千年，其间不断地吸收着各种外来文化。我们将为您讲述当今文化最前沿的变化。因为我们总是徘徊在传统与时尚之间。而最重要的，是我们希望为读者传播富于 “吸引力” 的信息。我们是一个不依赖政府资助的组织，因此在物质和精神两个层面都不受束缚，可以完全自由地去追求自己有兴趣的一切内容，并期望它们同样会让世界上所有人感兴趣，这也是我们满腔热情的唯一源泉。

英文、中文（简体字和繁体字）、法文、西文、阿文、俄文和日文，我们拥有精通这七种语言的专家团队。放眼全球 70 亿受众，我们期待着与所有读者分享日本的方方面面，点点滴滴。

### 需要生成什么内容？

根据不同的分类获取文章更新推送 

文章链接示例 https://www.nippon.com/cn/japan-data/h00944/

分类链接示例 https://www.nippon.com/cn/economy/

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
