### ISSUE TITLE
部分微博超话限时报错

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7308]
#### 路由地址（不包含参数）

https://rsshub.app/weibo/super_index/

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/weibo/super_index/10080809d8f325d9e28c59ce26b082dee5af33

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#wei-bo-chao-hua

#### 预期是什么
有条目
#### 实际发生了什么
报错，如下图。
![image](https://user-images.githubusercontent.com/3047708/113176536-2e497500-927f-11eb-890a-7e8e03e7b736.png)

#### 部署相关信息
官方demo和自建最新。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
只是偶尔遇到，好像此时是遇到了特殊的“screen_name”导致的，如果下次刷新后，没有这个特殊的“screen_name”，我推测，就不会报错了。比如，现在换其它的超话，也应该不会报错。

不知道 @shunf4 ，还有其它大佬是否能尽快看看，修复一下。错过了的话，也不知下次会何时遇到。

**Comment by shunf4** [comment]
无法复现
