### ISSUE TITLE
A 岛匿名版：多条时间线

### ISSUE THREAD

**Issue by notofoe** [DIYgod/RSSHub#7309]
### 网站地址

https://adnmb.com

### 需要生成什么内容？

`/adnmb/timeline/{id}` 多条时间线：[综合线](https://adnmb.com/Forum/timeline/id/1)、[岛风线](https://adnmb.com/Forum/timeline/id/2)、[游戏线](https://adnmb.com/Forum/timeline/id/3)、[亚文化线](https://adnmb.com/Forum/timeline/id/4)

### 额外描述

API：

- https://adnmb.com/api/getTimelineList
- https://adnmb.com/api/timeline == https://adnmb.com/api/timeline/id/1
- https://adnmb.com/api/timeline/id/2

其他 API：https://gist.github.com/zhihaofans/16aebe635a509f1b1b107b759bbe5753

**Comment by Ovler-Young** [comment]
Already exist https://docs.rsshub.app/bbs.html#a-dao-ni-ming-ban
已经有路由生成。

**Comment by notofoe** [comment]
> Already exist https://docs.rsshub.app/bbs.html#a-dao-ni-ming-ban

并非重复。原路由 `/adnmb/:pid/:page` 系 [板块](https://web.archive.org/web/20220206105455/https://adnmb3.com/f/%E7%BB%BC%E5%90%88%E7%89%881)，这个 issue 系 [时间线](https://web.archive.org/web/20220127130421/https://adnmb3.com/Forum/timeline/id/1)。

**Comment by Ovler-Young** [comment]
> > Already exist https://docs.rsshub.app/bbs.html#a-dao-ni-ming-ban
> 
> 并非重复。原路由 `/adnmb/:pid/:page` 系 [板块](https://web.archive.org/web/20220206105455/https://adnmb3.com/f/%E7%BB%BC%E5%90%88%E7%89%881)，这个 issue 系 [时间线](https://web.archive.org/web/20220127130421/https://adnmb3.com/Forum/timeline/id/1)。

原路由 /adnmb/:pid/:page 中，当pid 为 `-1` 时，即为所需的时间线。
另，现 A 岛匿名版状态不明无法访问，此issue在目前并没有做的必要性。

**Comment by notofoe** [comment]
Closing this issue, may reopen it when [nimingban.org](https://nimingban.org) get online again.
