### ISSUE TITLE
希望增加中国药科大学的通知

### ISSUE THREAD

**Issue by Ivysauro** [DIYgod/RSSHub#731]
- 首页通知：http://www.cpu.edu.cn/4133/list.htm
- 教务处：http://jwc.cpu.edu.cn/851/list.htm
- 研究生院：http://yjsy.cpu.edu.cn/6335/list.htm

**Comment by tomatomash** [comment]
@Ivysauro  
研究生院feed43源转成全文： http://ftr.fivefilters.org/makefulltextfeed.php?url=https%3A%2F%2Ffeed43.com%2F0783081517830718.xml&max=3
（同是药大人，虽然毕业了，加油）
如果等不到大佬来做，我再把另外2个也做出来吧，主要是feed43刷新比较慢，所以只是临时做出来，全文只能抓3个，如果你只想看看标题，那就用这个吧
https://feed43.com/0783081517830718.xml

**Comment by SettingDust** [comment]
@tomatomash 建议你参考其他学校做 有缘人不好等

**Comment by Ivysauro** [comment]
@SettingDust 流下了没有技术的眼泪😆

**Comment by tomatomash** [comment]
@SettingDust 暂时只会用feed43做。。。ψ(._. )>明年再拓宽一下知识面。

**Comment by tomatomash** [comment]
@Ivysauro  要是你想试试feed43，可以看看这个，https://www.bilibili.com/video/av31361577/ ，我做的入门

**Comment by Ivysauro** [comment]
@tomatomash 首页通知我已经用feed43弄好了，改下编码方式就能显示中文了✔

**Comment by tomatomash** [comment]
@Ivysauro wow，这么厉害！突然觉得有好多因为乱码而放弃的网页。。。。。还没加入收藏

**Comment by Ivysauro** [comment]
@HenryQW 啊哈，这是我们临时搭建自用的，不会混入Rsshub的😸（咦 评论删了吗🤔

**Comment by DIYgod** [comment]
Done. 8b842c2f67f39e0c5dab06acb0072e88cc9159f5
