### ISSUE TITLE
Daily briefing | The Economist

### ISSUE THREAD

**Issue by famiji** [DIYgod/RSSHub#7323]

**Comment by cyzs233** [comment]
The Economist 本身提供rss源，espresso对应的源地址为：https://www.economist.com/prospero/rss.xml

**Comment by famiji** [comment]
不是一个东西

Zhang Qiang ***@***.***> 于2021年4月3日周六 下午6:31写道：

**Comment by cyzs233** [comment]
我回复后去二次检查了，发现网站确实没有提供request的源，也马上删掉了回复，不知道为什么还被你看到了。

**Comment by famiji** [comment]
邮件还是提醒了，哈哈哈，还有解决方法吗？

**Comment by cyzs233** [comment]
用了通用的rss路径，没找到相关的。我们还是删评吧😊

**Comment by famiji** [comment]
呃呃 好吧

Zhang Qiang ***@***.***> 于2021年4月3日周六 下午10:14写道：

**Comment by famiji** [comment]
我是邮件里看到的

qood ***@***.***> 于2021年4月3日周六 下午10:16写道：

**Comment by BeautyYuYanli** [comment]
> ### https://www.economist.com/espresso
> ### Take five minutes to catch up on today’s essential news
> ### 每天生成一次此网站的内容
> ### 如有需要，可用[https://github.com/iamadamdev/bypass-paywalls-chrome提供的插件访问。](https://github.com/iamadamdev/bypass-paywalls-chrome%E6%8F%90%E4%BE%9B%E7%9A%84%E6%8F%92%E4%BB%B6%E8%AE%BF%E9%97%AE%E3%80%82)

你所提及的 bypass-paywalls 插件已失效。出于版权考虑我也不建议 RSSHub 抓取全文。
