### ISSUE TITLE
希望增加恩山无线论坛帖子的抓取

### ISSUE THREAD

**Issue by Arler2016** [DIYgod/RSSHub#7363]
希望增加恩山无线论坛帖子的抓取

### 网站地址

https://www.right.com.cn/forum/forum.php

### 网站描述

恩山论坛是目前中国的最大专业无线论坛，是众多无线网络使用者钟爱的一款无线网。恩山论坛里边包括无线路由器、硬件拆迁、智能设备。隐身WiFi、硬件改造、无线DIY等设备

### 需要生成什么内容？

论坛各板块下帖子内容的抓取

比如：无线设备硬件相关板块下的新手入门及其它(硬件)

帖子：新房装修求大佬看看怎样布置wifi
https://www.right.com.cn/forum/thread-4108981-1-1.html

[截图演示](https://i.loli.net/2021/04/11/cO62oPz4VZ1QMiK.jpg)

**Comment by cnkmmk** [comment]
恩山论坛不是自带RSS的吗？怎么还要另外抓取？
