### ISSUE TITLE
TitsGuru很长一段时间没有更新

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#7364]
#### 路由地址（不包含参数）
/tits-guru/home
/tits-guru/daily
```routes
```

#### 完整路由地址，包含所有必选与可选参数
https://rsshub.app/tits-guru/home
https://rsshub.app/tits-guru/daily
```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
正常更新
#### 实际发生了什么
网站有正常更新图片，但rss这边没有
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by zoenglinghou** [comment]
我在本地测试没问题，应该是你使用的 RSSHub 实例被网站屏蔽了。可以自建或者使用这些实例：https://github.com/AboutRSS/ALL-about-RSS#rsshub

**Comment by tomatomash** [comment]
抱歉，因为也读不懂回复内容，所以单纯问一句，是因为 https://tits-guru.com/ 这个网站屏蔽了rsshub的意思吗？或者换个问法，如果不会自建的话，这问题是不是就无法解决了？

**Comment by zoenglinghou** [comment]
是这个网站屏蔽了 rsshub.app

不自建的话可以去[这里](https://github.com/AboutRSS/ALL-about-RSS#rsshub)选取其他 rsshub 实例使用。

**Comment by tomatomash** [comment]
十分感谢

> 是这个网站屏蔽了 rsshub.app
> 
> 不自建的话可以去[这里](https://github.com/AboutRSS/ALL-about-RSS#rsshub)选取其他 rsshub 实例使用，如：
> 
> https://uneasy.win/rss/tits-guru/daily
