### ISSUE TITLE
网易人间-rss源生成-活在尘间，看见人间

### ISSUE THREAD

**Issue by pplps** [DIYgod/RSSHub#7388]
### 网站地址
http://renjian.163.com/
### 网站描述
网易新闻旗下的新闻网站，
在机器聚合的新闻泛滥的情况下，落点在人的身上，
讲述每个渺小而又在人间活生生的人的各种故事，悲欢离合阴晴圆缺，
有特写、记事、大写、好读、看客等板块，
### 需要生成什么内容？
希望能有特写、记事、大写、好读、看客几个板块的rss更新订阅，
因为文章都是作者采访写作的，更新频率也不高，
几个板块一个rss订阅也可以，分开也行——感谢
### 额外描述
活在尘间，看见人间

**Comment by pplps** [comment]
> > 感谢nczitzk和rsshub，已经可以使用特写和记事的rss了，我看有一个测试failed，不知道影响不影响
> > https://rsshub-do-not-use-itoofpd9l-diy.vercel.app/netease/renjian/daxie - **Failed**
> 
> 修复了大写 😃

感谢fix，不过现在还是订阅不了，打开显示如下：
Looks like something went wrong
Route requested: /netease/renjian/daxie
Error message: Cannot read property 'slice' of null

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
