### ISSUE TITLE
有办法批量订阅微博用户吗?

### ISSUE THREAD

**Issue by Mcthp** [DIYgod/RSSHub#7393]
请教一下,我是昨天才开始使用RSS的,此前在微博、B站已经关注了很多用户，想问问有没有批量导入已关注用户的方法

**Comment by 10362227** [comment]
建议用个人时间线rss

**Comment by Mcthp** [comment]
> 建议用个人时间线rss

请问那个是需要在微博开放平台认证身份再获取token什么的吗,我大前天提交了身份认证但到现在还没通过

**Comment by ZhuningS** [comment]
> 请教一下,我是昨天才开始使用RSS的,此前在微博、B站已经关注了很多用户，想问问有没有批量导入已关注用户的方法

有
