### ISSUE TITLE
bilibili UP主投稿 img src URL错误

### ISSUE THREAD

**Issue by Dong-Cao** [DIYgod/RSSHub#7404]
#### 路由地址（不包含参数）

```routes
/bilibili/user/video
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/bilibili/user/video/240788688
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
显示正确图片URL

#### 实际发生了什么
https://www.bilibili.com/video/http://i1.hdslb.com/bfs/archive/19cf87196806ced1e7b0ed5e0d7482a548d90323.jpg

<item>
<title>
<![CDATA[ 【1080P】《奇妙的命运呀》剧情版预告 ]]>
</title>
<description>
<![CDATA[ weibo 《奇妙的命运呀》是由星瀚佰年影业、凡酷文化、敦禾影视联合出品的古装轻喜剧。由曾黄武、姜天航执导，张悦楠、曹峻祥、王煜霖、李乐晴主演。 该剧讲述了学习成绩班级垫底的高中生李福珠，由于沉迷漫画，穿越到了漫画中的朝代，一下子从不受待见的差生变成了一人之下万人之上的天女的逆袭趣事，同时，还与当朝的冷面皇帝云奕，一边斗智斗勇，一边擦出了甜蜜的火花。<br><br><iframe src="https://player.bilibili.com/player.html?aid=845200853&high_quality=1" width="650" height="477" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe><br><img src="https://www.bilibili.com/video/http://i1.hdslb.com/bfs/archive/19cf87196806ced1e7b0ed5e0d7482a548d90323.jpg" referrerpolicy="no-referrer"> ]]>
</description>
<pubDate>Sat, 17 Apr 2021 11:25:12 GMT</pubDate>
<guid isPermaLink="false">https://www.bilibili.com/video/BV1f54y1L7Kp</guid>
<link>https://www.bilibili.com/video/BV1f54y1L7Kp</link>
<author>
<![CDATA[ 预告片放映室 ]]>
</author>
</item>

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by hyxxsfwy** [comment]
确实存在这个问题，希望尽快修正。
