### ISSUE TITLE
纽约时报的每日简报停止更新

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#7418]
#### 路由地址（不包含参数）

```routes
/nytimes/morning_post
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/nytimes/morning_post
```

#### 相关文档地址

- https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao

#### 预期是什么
每天更新一篇每日简报。
#### 实际发生了什么
该路由抓取的链接 [https://m.cn.nytimes.com/morning-brief](https://m.cn.nytimes.com/morning-brief) 已经不更新每日简报了。但是纽约时报首页还能看见今日要闻。

应该是纽时每日简报改版，不在 `/morning-brief` 这个路径下更新了还是什么情况？

**Comment by zx31415** [comment]
每日简报已改版，建议修改抓取链接为：
https://www.nytimes.com/zh-hans/series/daily-briefing-chinese
