### ISSUE TITLE
微博个人时间线授权重定向地址不匹配

### ISSUE THREAD

**Issue by mcthp** [DIYgod/RSSHub#7428]
#### 路由地址（不包含参数）

weibo/timeline/0

#### 完整路由地址，包含所有必选与可选参数

RSSHub 地址/weibo/timeline/0

#### 相关文档地址

-https://docs.rsshub.app/install/#pei-zhi-qi-ta-ying-yong-pei-zhi
-https://docs.rsshub.app/social-media.html#wei-bo

#### 预期是什么
授权页
#### 实际发生了什么
![msedge_tvoojciCgI](https://user-images.githubusercontent.com/35915872/115945132-c89e8080-a4ec-11eb-8c91-586c6e40d18f.png)
#### 部署相关信息
![msedge_x20lJqjX7a](https://user-images.githubusercontent.com/35915872/115945256-714ce000-a4ed-11eb-9c31-f20fc4add8e2.png)
![putty_83ob5ySiNj](https://user-images.githubusercontent.com/35915872/115945382-24b5d480-a4ee-11eb-8f74-dbc9202289af.png)

请教一下,我是哪里还没配置或配置错误了吗

**Comment by zytomorrow** [comment]
![image](https://user-images.githubusercontent.com/16175551/119785086-74c6f300-bf01-11eb-8d67-de57b46c83b9.png)
缺少了`WEIBO_REDIRECT_URL`环境变量
