### ISSUE TITLE
[RSS 提案] Topbook

### ISSUE THREAD

**Issue by Geeyun-JY3** [DIYgod/RSSHub#7436]
### 网站地址
https://topbook.cc/
### 网站描述
高效生活视频书
### 需要生成什么内容？
全站 RSS

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
