### ISSUE TITLE
纽约时报英文路由中，图片全部无法显示

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#7442]
#### 路由地址（不包含参数）

```routes
/nytimes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/nytimes/en
```

#### 相关文档地址

- https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao-xin-wen

#### 预期是什么
获取到的文章中显示图片
#### 实际发生了什么
只要路由参数为英文，图片就无法获取，但若参数为无（即默认中文）、中英对照、繁中 - 英文对照或繁体中文时，图片可以加载

- 额外信息（日志、报错等）
看了一下输出的 html 信息，当文章中有中文时，图片的 html 是这样的：

```html
<figure class="article-span-photo">
  <img src="https://static01.nyt.com/images/2021/04/26/world/00virus-india-dispatch-promo/merlin_186812691_eff259bb-dcaa-448c-a995-218b4b41f6de-master1050.jpg" width="1050" height="700" alt="周五，在东德里，一处为新冠病毒死亡者准备的火葬地点。" referrerpolicy="no-referrer">
  <figcaption>
    <span>周五，在东德里，一处为新冠病毒死亡者准备的火葬地点。</span> 
    <cite>Atul Loke for The New York Times</cite>
  </figcaption>
</figure>
```

而当网页为纯英文时，输出的 html 是这样的：
```html
<figure>
  <img src="https://www.nytimes.com/2021/04/27/world/asia/undefined" referrerpolicy="no-referrer">
  <br>
  <figcaption>A crematorium ground for Covid-19 victims in East Delhi, on Friday.</figcaption>
</figure>
```

推测是 `lib\routes\nytimes\utils.js` 下的 `ProcessImage` 函数出了问题，没有解析出正确的 img src.

另外，改版后的每日简报栏目（见 issue #7418 ），虽然输出是中文，但是他的域名仍是 [www.nytimes.com](www.nytimes.com)，所以也需要使用英文的解析方式来输出内容

**Comment by RekiDunois** [comment]
#7418

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/pull/7449
