### ISSUE TITLE
代理配置报错: Protocol "https:" not supported

### ISSUE THREAD

**Issue by zololucky** [DIYgod/RSSHub#7469]
#### 预期是什么
正常使用代理

#### 实际发生了什么
在 RSSHub/.env 文件加入代理后报错，移除代码可恢复正常使用。
![Xnip2021-05-04_03-26-50](https://user-images.githubusercontent.com/8132278/116923098-c96fa900-ac88-11eb-962f-d438b512da9a.png)

#### 部署相关信息
根据文档我在 RSSHub/.env 文件键入以下内容
`PROXY_URI = socks5h://用户名:密码@地址:端口
`

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Ubuntu 18         |
| Node version       |        16       |
| if Docker, version |               |

- 额外信息（日志、报错等）
- Error message: Protocol "https:" not supported. Expected "http:": target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by NeverBehave** [comment]
地址中不应当包含https，协议只可能是socks5h或者https
