### ISSUE TITLE
唱吧用户页面变更，路由报错

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#7470]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/7470)

#### 路由地址（不包含参数）
路由: /changba/:userid
#### 完整路由地址，包含所有必选与可选参数
https://rsshub.app/changba/34108440
#### 相关文档地址
https://docs.rsshub.app/social-media.html#chang-ba
#### 预期是什么
正常抓取用户作品
#### 实际发生了什么
报错 empty route
#### 部署相关信息
官方 Demo 及 Docker 自建（最新版）
#### 额外信息（日志、报错等）

唱吧官方变更了用户页面地址，（可能页面内容也有变化，不确定）
新的用户页面地址示例：
https://changba.com/wap/index.php?s=skp6hhF59n48R-UpqO3izw

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($2.00)

### Submitted pull Requests
- [#7538 fix(route): changba user](https://issuehunt.io/r/DIYgod/RSSHub/pull/7538)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by jaychoubaby** [comment]
> 
> [<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/7470)
> 
> 
> 
> #### 路由地址（不包含参数）
> 
> 路由: /changba/:userid
> 
> #### 完整路由地址，包含所有必选与可选参数
> 
> https://rsshub.app/changba/34108440
> 
> #### 相关文档地址
> 
> https://docs.rsshub.app/social-media.html#chang-ba
> 
> #### 预期是什么
> 
> 正常抓取用户作品
> 
> #### 实际发生了什么
> 
> 报错 empty route
> 
> #### 部署相关信息
> 
> 官方 Demo 及 Docker 自建（最新版）
> 
> #### 额外信息（日志、报错等）
> 
> 
> 
> 唱吧官方变更了用户页面地址，（可能页面内容也有变化，不确定）
> 
> 新的用户页面地址示例：
> 
> https://changba.com/wap/index.php?s=skp6hhF59n48R-UpqO3izw
> 
> 
> 
> 
> ---
> 
> <details>
> <summary>
> <b>IssueHunt Summary</b>
> </summary>
> 
> #### [<img src='https://avatars.githubusercontent.com/u/44920131?v=4' alt='xizeyoupan' width=24 height=24> xizeyoupan](https://issuehunt.io/u/xizeyoupan) has been rewarded.
> 
> ### Backers (Total: $2.00)
> 
> - [<img src='https://avatars.githubusercontent.com/u/8215230?v=4' alt='yefoenix' width=24 height=24> yefoenix](https://issuehunt.io/u/yefoenix) ($2.00)
> 
> ### Submitted pull Requests
> - [#7538 fix(route): changba user](https://issuehunt.io/r/DIYgod/RSSHub/pull/7538)
> ---
> 
> ### Tips
> 
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
> </details>
> 

请问唱吧的新的链接要如何才能获取到用户ID呢，我尝试了很多办法都不行
