### ISSUE TITLE
[RSS Proposal] Bandcamp

### ISSUE THREAD

**Issue by BingoKingo** [DIYgod/RSSHub#7477]
### Website URL

https://bandcamp.com/

### Website description

Discover amazing new music and directly support the artists who make it.

#### Main

| Name | Description | Link Example | Route Example | Require |
| --- | --- | --- | --- | --- |
| Weekly | Bandcamp Weekly Show | **https://bandcamp.com/?show=448** | /bandcamp/weekly | Text, Audio, Image |
| Live Streams | Upcoming Bandcamp Live Streams | https://bandcamp.com/live_schedule | /bandcamp/live | Text, Image |

#### Daily

| Name | Description | Link Example | Route Example | Require |
| --- | --- | --- | --- |  --- |
| Daily | Bandcamp Daily - Posts | https://daily.bandcamp.com/ | **/bandcamp/daily/posts (Default /bandcamp/daily)** | Text, Audio, Image |
| Daily Latest | Bandcamp Daily - Latest | https://daily.bandcamp.com/latest | /bandcamp/daily/latest | Text, Audio, Image |
| Daily Lists | Bandcamp Daily -  Lists | https://daily.bandcamp.com/lists | /bandcamp/daily/lists | Text, Audio, Image |
| Daily Features | Bandcamp Daily -  Features | https://daily.bandcamp.com/features | /bandcamp/daily/features | Text, Audio, Image |
| Daily Album | Bandcamp Daily - Album of the Day | https://daily.bandcamp.com/album-of-the-day | /bandcamp/daily/album | Text, Audio, Image |
| ... | ... | ... | ... | ... |
| Daily Best Ambient | Bandcamp Daily - Best Ambient | https://daily.bandcamp.com/best-ambient | /bandcamp/daily/best-ambient | Text, Audio, Image |
| ... | ... | ... | ... | ... |
| Daily Acoustic | Bandcamp Daily - Acoustic | https://daily.bandcamp.com/genres/acoustic | **/bandcamp/daily/acoustic** | Text, Audio, Image |
| ... | ... | ... | ... | ... |

More on https://daily.bandcamp.com/#all-nav

#### Tags (Releases)

| Name | Description | Link Example | Route Example | Require |
| --- | --- | --- | --- | --- |
| Electronic Releases | Bandcamp - Tag - Electronic Music & Artist | https://bandcamp.com/tag/electronic?tab=all_releases | /bandcamp/tag/electronic | Audio, Text, Image |
| ... | ... | ... | ... | ... |
| United Kingdom Relases | Bandcamp - Tag - United Kingdom Music & Artist | https://bandcamp.com/tag/united-kingdom?tab=all_releases | /bandcamp/tag/united-kingdom | Audio, Text, Image |
| ... | ... | ... | ... | ... |

More on https://bandcamp.com/tags

#### Artists

| Name | Description | Link Example | Route Example | Require |
| --- | --- | --- | --- | --- |
| xxx | xxx | **https://xxx.bandcamp.com/releases** | **/bandcamp/artist/releases/xxx (Default /bandcamp/artist/xxx)** | Audio, Text, Image |
| xxx’s Community | xxx’s Community | **https://xxx.bandcamp.com/community** | /bandcamp/artist/community/xxx | Text, Image |
| ... | ... | ... | ... | ... |

More on https://bandcamp.com/artist_index

### Additional description

None

**Comment by TonyRL** [comment]
Closed this in #7480 #7523 #8512
