### ISSUE TITLE
Feature Request: 自定义路由(插件)目录

### ISSUE THREAD

**Issue by qjebbs** [DIYgod/RSSHub#749]
现有的RSS路由支持全部放在`routes`目录,并在`routes.js`中引入，这看起来像是一种官方的正式收录，并且在一些场景下存在不方便：

1. 用户想添加一些自定义的路由，他必须提交issue并等待收录
1. 每次添加新的路由就必须发布新版本，哪怕程序主逻辑没有修改

我建议再增加一个允许用户自定义的`routes`目录，比如，`user-routers` 或者 `plugins`，这个目录的组织方式与`routes`目录一致，比如：

```js
router.js
plugins.js
plugins
|__ example
    |__ index.js
|__ ...
    |__ ...
    |__ ...
```

其中的每个目录表示一个新的rss，在现有的`router.js`中引入`plugins.js`用来遍历并加载所有的插件。这样的好处，除了解决上述2个场景的不便，使程序更灵活之外，还能：

- 在 Docker 这种场景下，方便地把 `plugins` 映射出来管理。
- 更长远地想，围绕这个项目，也许还能出现很多的插件项目。

我自己写了一个简陋的实现，验证过这个设想：

index.js:

```js
module.exports.path = '/example';
module.exports.middleware = async (ctx) => {
    // ...
};
```
plugins.js:

```js
const fs = require('fs');
const path = require('path');
const pluginsPath = path.join(__dirname, 'plugins');

module.exports = router => {
    fs.readdirSync(pluginsPath).forEach(
        item => {
            item = path.join(pluginsPath, item)
            if (!fs.lstatSync(item).isDirectory()) return;
            use(item);
        }
    );

    function use(directory) {
        fs.readdirSync(directory).forEach(
            item => {
                item = path.join(directory, item)
                if (!fs.lstatSync(item).isFile() || path.extname(item).toLowerCase() != '.js') return;
                const plugin = require(
                    './' + path.join(
                        path.relative(__dirname, path.dirname(item)),
                        path.basename(item, '.js')
                    )
                );
                if (!plugin.path || !plugin.middleware) return;
                router.get(plugin.path, plugin.middleware);
            }
        );
    }
}
```

routers.js:

```js
// ...

// plugins
require('./plugins')(router);

// ...
```

PS: 编辑了一下，之前的想法有个瑕疵，应该把`plugins.js`放在`plugins`目录之外，这样 Docker 做目录映射时，这个文件不会被覆盖掉。

**Comment by tgly307** [comment]
这个想法我觉得ok

**Comment by DIYgod** [comment]
1. 自定义路由可以参考 protected_router 的实现

2. 这样的模块没法复用，也不能加参数，局限性很大，添加新的路由需要重启是个合理的做法，不觉得有什么问题

**Comment by tgly307** [comment]
我想这里主要是考虑不要和主线版本的文件冲突吧，这样可以无痛拉取




来自客户端
在2018年09月19日 17:40，DIYgod 写道：

自定义路由可以参考 protected_router 的实现

这样的模块没法复用，也不能加参数，局限性很大，添加新的路由需要重启是个合理的做法，不觉得有什么问题

**Comment by HenryQW** [comment]
@tgly307 如果这个是目的，可以通过 env 来实现无痛拉取
```js
const routeDir = process.env.ROUTE_DIR;

router.get('/dongqiudi/daily', require(`./${routeDir}/dongqiudi/daily`));
```

**Comment by tgly307** [comment]
还有这种操作？涨姿势




来自客户端
在2018年09月19日 17:47，Henry Wang 写道：

@tgly307 如果这个是目的，可以通过 env 来实现无痛拉取

constrouteDir=process.env.ROUTE_DIR;

router.get('/dongqiudi/daily', require(`./${routeDir}/dongqiudi/daily`));

**Comment by qjebbs** [comment]
@DIYgod, 可能你有更好的方案，或者现有版本已经可以通过什么做法实现了？

我关心的使用场景其实也就很简单：在docker容器下映射一个目录，可以放置我自己编写的路由（插件），而不必等这个项目正式收录，或者有些私人用的RSS，并不想被收录。

或者，你的意思是，自己写好路由，自己编译 Docker 镜像？

**Comment by qjebbs** [comment]
@DIYgod，已改用类似`protected_router `的实现方式。不过对于`模块没法复用，也不能加参数`不是很理解：
1. 理论上，插件和收录的路由是同等地位，可以复用项目提供的工具模块的。如果指插件跟项目分离管理后，两者的代码兼容（对有些工具模块变更的及时兼容），似乎是有点问题
1. 加参数什么好像也和收录的路由一样
1. 添加路由是要重启，我只是想方便地添加路由😀

**Comment by DIYgod** [comment]
@qjebbs 参数是在路由里的，如果使用读取文件的方式，路由是自动生成的，无法定义参数，而且这样写也要重启程序才能生效，除非再监听文件变化

热加载意义不大，没有很好的做法的话暂不考虑

**Comment by qjebbs** [comment]
我想你没明白我的用意，我不是为了不重启就能加载路由，也更不会有参数问题。这个做法的意义很简单，就是等不及官方收录路由的，或者有私人用的不想被官方收录的，可以在自己部署的时候通过插件方式加上去，并且加上后，不会因为更新一下docker镜像就失效。

现在项目的状态要达成这个目标，就只有自己改router文件和目录，如果项目有更新路由，我又想要同时享受这个更新，就不得不重新改，重新编译镜像。

如果你认为开放插件这个做法有损项目的`rss路由可以集中更新、更丰富、更有凝聚力相关方面`的话，另当别论了。

**Comment by qjebbs** [comment]
我不是很明白你所说的具体怎么实施，是：

- 写一个新的类似 protected_router 这样的文件吗，那需要改动 index 文件来加载这它
- 还是在 protected_router 里直接加上呢？

这2种办法都需要动到现有的文件，那么在下次更新docker镜像的时候就会被干掉了。如果在镜像外映射，把镜像的`index.js`覆盖了，也不安全吧？

可能还需要官方的一个方案来支持这种场景吧？我给出的只是一个简陋的设想，期待你有更好的方案^_^
