### ISSUE TITLE
bilibili 动态  不显示详细内容了

### ISSUE THREAD

**Issue by xjushi** [DIYgod/RSSHub#7496]
动态中不能正常显示标题和内容介绍了。
变成了 undefined 和 NaN 字样。
更新倒是正常在更新。

如图：

![iShot2021-05-08 07.28.42.png](https://i.loli.net/2021/05/08/xMYDTLyGIi28Ejp.png)

其它如投稿等，也无法正常显示。

**Comment by TonyRL** [comment]
https://rsshub.app/bilibili/user/dynamic/2267573 is working as of replying
