### ISSUE TITLE
b9c7ed24 版本 Heroku 下部署失败

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#7510]
#### 预期是什么
在heroku下正常部署rsshub
#### 实际发生了什么
失败报错
#### 部署相关信息
Heroku, master分支最新版 b9c7ed24
####  额外信息（日志、报错等）
报错内容:

> -----> Building on the Heroku-18 stack
> -----> Using buildpack: heroku/nodejs
> -----> Node.js app detected
> -----> Build failed
>  !     Two different lockfiles found: package-lock.json and yarn.lock
>        Both npm and yarn have created lockfiles for this application,
>        but only one can be used to install dependencies. Installing
>        dependencies using the wrong package manager can result in missing
>        packages or subtle bugs in production.
>        - To use npm to install your application's dependencies please delete
>          the yarn.lock file.
>          $ git rm yarn.lock
>        - To use yarn to install your application's dependences please delete
>          the package-lock.json file.
>          $ git rm package-lock.json
>     
>        https://help.heroku.com/0KU2EM53
>  !     Push rejected, failed to compile Node.js app.
>  !     Push failed

**Comment by NeverBehave** [comment]
a8c1497
