### ISSUE TITLE
ResearchGate的个人页抓取

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#7526]
### 这是一个什么样的功能？
抓取ResearchGate个人页的publication
### 这个功能可以解决什么问题？
ResearchGate是著名的学术交流媒体
### 额外描述
如https://www.researchgate.net/profile/Somsak-Panha ，不同的Profile后面的的人名不同。抓取Publication部分。

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
