### ISSUE TITLE
路透社英文分站无法正常获取

### ISSUE THREAD

**Issue by duguyipiao** [DIYgod/RSSHub#7529]
#### 路由地址（不包含参数）

```routes
/reuters/channel/:site/:channel
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/reuters/channel/us/world
https://rsshub.app/reuters/channel/uk/world
```

#### 相关文档地址

https://docs.rsshub.app/traditional-media.html#lu-tou-she

#### 预期是什么

正常获取

#### 实际发生了什么

英文分站 (us, uk) 无法正常获取，cn 正常。

**Comment by LyleLee** [comment]
我修复了us的站点，还在等待maintainer合入。 https://github.com/DIYgod/RSSHub/pull/7456
