### ISSUE TITLE
纽约时报每日简报失效

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#7549]
#### 路由地址（不包含参数）
- https://rsshub.app/nytimes/morning_post

#### 相关文档地址
- https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao-mei-ri-jian-bao

#### 预期是什么
https://www.nytimes.com/zh-hans/series/daily-briefing-chinese 每日简报更新

#### 实际发生了什么
由于网站改版，抓取更新在4月15号就停止了

**Comment by TonyRL** [comment]
Duplicate of #7418
