### ISSUE TITLE
docs.rsshub.app 搜索 bug

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#7550]
#### 相关文档地址

- https://docs.rsshub.app/

#### 预期是什么
搜索结果点击后，准确跳转到相关条目。
#### 实际发生了什么
刷新后访问 docs.rsshub.app ，搜索关键词，点击搜索结果，直接跳转到了相关条目的上一层级目录，同时地址栏也会瞬间从相关条目变成上一层级。

印象里该 bug 已经出现很长时间，在 PC 端、Android 端，Chrome、Edge，无痕模式、不装扩展的环境下都会复现。

https://user-images.githubusercontent.com/51783873/118763635-bf65c100-b8aa-11eb-9d67-353d4fab91ef.mp4

**Comment by TonyRL** [comment]
No longer an issue since the docs is moved to docusaurus.
