### ISSUE TITLE
希望能添加laosiji.com  RSS订阅

### ISSUE THREAD

**Issue by Nat30** [DIYgod/RSSHub#759]
http://www.laosiji.com/new_web/index.html  这个网站能增加一个RSS订阅么？试着用feed43来处理，发现节目列表在JS代码里面，feed43加载不到。

**Comment by Nat30** [comment]
主页的RSS、24小时热榜的RSS

**Comment by Nat30** [comment]
靴靴～

**Comment by xyqfer** [comment]
@Nat30 我看了下 laosiji.com 接口返回的数据，有些确实是没有标题(`title`)这个字段的，然后网站上显示的似乎是没有标题就取描述(`description`)作为标题，详情可见以下两图：

<img width="1410" alt="wx20181015-104450 2x" src="https://user-images.githubusercontent.com/5186792/46927440-fbd43f00-d067-11e8-895f-5efde6d6f01b.png">
<img width="790" alt="wx20181015-104521 2x" src="https://user-images.githubusercontent.com/5186792/46927447-055da700-d068-11e8-8ff0-ef51a83c844c.png">

如果这种方式能接受的话稍后我提个 pr 修复这个问题

**Comment by DIYgod** [comment]
@xyqfer 可以的，title 可以直接用 description 的值，长度过长会有[中间件](https://github.com/DIYgod/RSSHub/blob/master/middleware/template.js#L36)自动处理的

**Comment by xyqfer** [comment]
@DIYgod 好的谢谢，稍后我修复掉这个问题

**Comment by DIYgod** [comment]
Fixed. b43855666cf539f3392a6f8eec219cbab88a9bc8

**Comment by Nat30** [comment]
感谢！
