### ISSUE TITLE
Docker编译出来的带chrome的image在运行时找不到chrome

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub#7612]
#### 构建和运行镜像所用的指令

从Dockerfile看，`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0`应该就是在编译时安装Chrome的选项，于是我尝试：

```shell
docker build -t test --build-arg PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0 --no-cache .
docker run --rm -it -p 1200:1200 test
```

#### 路由地址（不包含参数）

```routes
/routes/xiaohongshu/user
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/xiaohongshu/user/593032945e87e77791e03696/notes
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#xiao-hong-shu

#### 预期是什么

返回RSS XML

#### 实际发生了什么

找不到chrome

Route requested: /xiaohongshu/user/593032945e87e77791e03696/notes
Error message: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (869685).

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Windows 10        |
| Node version       |       使用官方Dockerfile构建        |
| if Docker, version |       Docker 20.10.6 (Docker Desktop)         |

- 额外信息（日志、报错等）

**Comment by Fofade** [comment]
我也遇到这个问题，官方docker部署后无法订阅小红书，报错也是Could not find expected browser (chrome) locally。兄弟有解决办法了吗

**Comment by yindaheng98** [comment]
> 我也遇到这个问题，官方docker部署后无法订阅小红书，报错也是Could not find expected browser (chrome) locally。兄弟有解决办法了吗

官方Dockerfile里的Chrome安装方式有点小问题，你可以弄个自己的Dockerfile，puppeteer默认安装方式会自动下载Chrome

**Comment by Fofade** [comment]
> > 我也遇到了这个问题，官方docker部署后无法订阅小红书，报错也是本地找不到预期的浏览器（chrome）。兄弟有解决办法
> 
> 官方Dockerfile里的Chrome安装方式有点小问题，你可以弄个自己的Dockerfile，puppeteer默认安装方式会自动下载Chrome

感谢！🙇‍
