### ISSUE TITLE
docker-compose中browserless里的核心转储文件占满磁盘空间

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub#7622]
https://github.com/browserless/chrome/issues/985

如上，如果不加限制，browserless在session关闭时会产生核心转储文件，一个大概200M。如果在TTRSS订阅几个用puppeteer的路由，更新频率调高点，很快就会把磁盘空间占满

#### 路由地址（不包含参数）

```routes
/routes/xiaohongshu/user
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/xiaohongshu/user/593032945e87e77791e03696/notes
```

#### 相关文档地址

- https://docs.rsshub.app/install/#docker-compose-bu-shu

#### 预期是什么

订阅多个用了puppeteer的路由，每半小时更新一次，用docker-compose启动后持续稳定运行

#### 实际发生了什么

运行一天左右，browserless中产生大量core dump文件，40G磁盘空间全满，服务全崩

<img width="1424" alt="微信截图_20210601104947" src="https://user-images.githubusercontent.com/37261065/120261379-5f1f4800-c2ca-11eb-9963-cfe78c704338.png">

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       CentOS Linux release 7.9.2009 (Core)        |
| Node version       |       官方docker镜像diygod/rsshub:latest        |
| if Docker, version |       docker 19.03.9        |

- 额外信息（日志、报错等）

**Comment by NeverBehave** [comment]
可以的话拆分一个单独的pr，我会跟进

**Comment by SukkaW** [comment]
See also: https://github.com/browserless/chrome/issues/985
