### ISSUE TITLE
网易号全文乱码

### ISSUE THREAD

**Issue by aoaowangxiao** [DIYgod/RSSHub#7637]
#### 路由地址（不包含参数）

``` 
/netease/dy/:id
```

#### 完整路由地址，包含所有必选与可选参数

```
/netease/dy/W4983108759592548559
```

#### 相关文档地址

- https://docs.rsshub.app/new-media.html#wang-yi-hao

#### 预期是什么
全文不乱码
#### 实际发生了什么
全文乱码
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
