### ISSUE TITLE
电影首发站的原域名 http://www.dysfz.cc 被墙，更换成了http://www.dysfz.vip

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#764]
@epirus @DIYgod 注意到源站域名是因为被墙才换的新域名，从 http://www.dysfz.cc 变成了 http://www.dysfz.vip 。

如果RSSHub搭建在国内的vps上，dysf的路由就用不了了，需要修复。

**Comment by epirus** [comment]
请关闭这个Issue

**Comment by DIYgod** [comment]
Done. efeb1a49d0261931d416a1e2139414f92821ea81
