### ISSUE TITLE
加入扩展后报错

### ISSUE THREAD

**Issue by 861130245** [DIYgod/RSSHub#7658]
![image](https://user-images.githubusercontent.com/44253690/120927979-6a80d200-c715-11eb-90c9-862cbe09b6ad.png)

#### 路由地址（不包含参数）

```routes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
Please create this issue in responsible repository [DIYgod/RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar).
