### ISSUE TITLE
【Rss Wanted】E站

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub#7665]
#### 主页

https://e-hentai.org/

#### 收藏

https://e-hentai.org/favorites.php?favcat=0

https://e-hentai.org/favorites.php?page=1

https://e-hentai.org/favorites.php?inline_set=fs_p

#### 标签

https://e-hentai.org/tag/male:glasses

https://e-hentai.org/tag/parody:original

#### 搜索

https://e-hentai.org/?f_cats=256&f_search=parody%3Aoriginal%24

https://e-hentai.org/?f_cats=384&f_search=parody%3Aoriginal%24

### 网站描述

E站

### 需要生成什么内容？

标题、作者、发布时间、链接

对于收藏，还需要添加收藏的时间

**Comment by SukkaW** [comment]
Already supported.

**Comment by SukkaW** [comment]
We will not support E-Hentai, due to its very strict Rate Limit Policy and IP-based HTTP request quotas.

**Comment by SukkaW** [comment]
If you are looking for front page RSS only: https://xml.e-hentai.org/ehg.xml
