### ISSUE TITLE
[RSS proposal] Harvard Health Blog

### ISSUE THREAD

**Issue by johan456789** [DIYgod/RSSHub#7673]
### 网站地址

https://www.health.harvard.edu/blog

### 网站描述

Join the discussion with experts from Harvard Health Publishing and others like you on a variety of health topics, medical news, and views.

### 需要生成什么内容？

標題、文章摘要、封面圖

以上三個都可以在 https://www.health.harvard.edu/blog 頁面直接讀取：

![image](https://user-images.githubusercontent.com/14802181/121309402-b78ebf00-c934-11eb-8a8a-9ae78a2d866e.png)

### 额外描述

（[官方的RSS連結](https://www.health.harvard.edu/blog/feed)在大約一個月前失效，看起來官方可能不提供了。）

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
