### ISSUE TITLE
贴吧用户帖子的路由报错

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7677]
#### 路由地址（不包含参数）

 https://rsshub.app/tieba/user/

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/tieba/user/%E7%90%B4%E8%BB%92%E5%B1%85%E5%A3%AB

即用户 [琴軒居士](https://tieba.baidu.com/home/main?un=%E7%90%B4%E8%BB%92%E5%B1%85%E5%A3%AB)
#### 相关文档地址

https://docs.rsshub.app/bbs.html#tie-ba-yong-hu-tie-zi

#### 预期是什么
正常显示RSS条目
#### 实际发生了什么
报错。如下图：
![image](https://user-images.githubusercontent.com/3047708/121491456-8c759f80-ca08-11eb-8c00-4cc11935ba81.png)

#### 部署相关信息
官方demo和自建最新都如此。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
请 @igxlin 作者抽空看一下，是否能修复一下。目前只发现这一个用户是这样的，或许还存在其他用户也是报错的。
多谢了。

**Comment by igxlin** [comment]
修改后的是 @nczitzk 写的了，麻烦看一下？

**Comment by nczitzk** [comment]
> 修改后的是 @nczitzk 写的了，麻烦看一下？

先回滚到 e2e7648c0e3d25da04b35bdd6d11ac55ca160ae2 了 😂

之前在 3fb58e7ea894743caeeaa237307be4d1b67fcca7 更新的 [API](https://tieba.baidu.com/home/get/getthread?un=斗鱼游戏君&pn=1) 方法不能获取到所有用户的帖子（当时没有做足够多的测试，但文档中的例子“斗鱼游戏君”是可行的），原因未知。

**Comment by igxlin** [comment]
> > 修改后的是 @nczitzk 写的了，麻烦看一下？
> 
> 先回滚到 [e2e7648](https://github.com/DIYgod/RSSHub/commit/e2e7648c0e3d25da04b35bdd6d11ac55ca160ae2) 了 😂
> 
> 之前在 [3fb58e7](https://github.com/DIYgod/RSSHub/commit/3fb58e7ea894743caeeaa237307be4d1b67fcca7) 更新的 [API](https://tieba.baidu.com/home/get/getthread?un=%E6%96%97%E9%B1%BC%E6%B8%B8%E6%88%8F%E5%90%9B&pn=1) 方法不能获取到所有用户的帖子（当时没有做足够多的测试，但文档中的例子“斗鱼游戏君”是可行的），原因未知。

看来直接爬网页比较粗暴泛用:joy:
