### ISSUE TITLE
网易云音乐-歌单歌曲报错

### ISSUE THREAD

**Issue by CI2VO5IXZ7** [DIYgod/RSSHub#7686]
Route requested: /ncm/playlist/35798529
几天前开始无法抓取
报错信息：
Error message: Cannot read property 'trackIds' of undefined

尝试使用国内IP，也无法抓取。

**Comment by nczitzk** [comment]
[该歌单](https://music.163.com/#/playlist?id=35798529) 可能是隐私歌单或不存在，所以无法正常抓取。

**Comment by AgFlore** [comment]
6月10日左右开始，网易云调整了对包括“XXX喜欢的歌单”在内的部分歌单的访问策略，以未登陆的身份访问时会返回`{"code":20001,"message":"登录后才可查看","debugInfo":null,"msg":"登录后才可查看"}`。

之后需要为自建用户提供登陆抓取Cookie的功能。
