### ISSUE TITLE
新手询问：如何生成feedly可订阅的订阅源

### ISSUE THREAD

**Issue by hblin94** [DIYgod/RSSHub#769]
各位好，请问，出现欢迎页面后，该怎么生成rss订阅源呢？
![image](https://user-images.githubusercontent.com/26139472/45915791-0008a480-be8e-11e8-8945-1e8257a7c122.png)
![image](https://user-images.githubusercontent.com/26139472/45915795-0ac33980-be8e-11e8-9931-803504cd9e79.png)

**Comment by lengthmin** [comment]
@hblin94 参考docs.rsshub.app
