### ISSUE TITLE
pixiv radar-rules 更新

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub#7699]
pixiv页面的链接规则已改变，对应的radar-rules需要修改。

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#pixiv

- 额外信息（日志、报错等）

页面|之前URL|现在URL
-|-|-
Pixiv用户收藏|/bookmark.php&id=11|/users/11/bookmarks/artworks
Pixiv用户动态|/member.php&id=11|/users/11
Pixiv排行榜|/search.php|/tags/:keyword

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
