### ISSUE TITLE
youtube-community(社群) RSS需求

### ISSUE THREAD

**Issue by borislee0227** [DIYgod/RSSHub#7706]
### 网站地址
https://www.youtube.com/
### 网站描述
一個視頻網站
### 需要生成什么内容？
擴展/細分rss訂閱內容，比如youtube目前的"社區"功能，以目前的rsshub功能已經無法訂閱
### 额外描述
以官方文檔的用戶(https://www.youtube.com/c/JFlaMusic)為例子，它的各分類後綴分別為：

首頁 - featured (https://www.youtube.com/c/JFlaMusic/featured)
影片 - videos (https://www.youtube.com/c/JFlaMusic/videos)
播放清單 - playlists (https://www.youtube.com/c/JFlaMusic/playlists)
社群 - community (https://www.youtube.com/c/JFlaMusic/community)
頻道 - channels (https://www.youtube.com/c/JFlaMusic/channels)

我不了解要如何創建一個新路由，因此根據上面的邏輯，是否可以新增一個路由為：
/youtube/community/:id

<img width="879" alt="螢幕截圖 2021-06-15 下午11 34 12" src="https://user-images.githubusercontent.com/19435818/122082380-89c4e100-ce32-11eb-8560-48dc4ebf23db.png">

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI

**Comment by wft44maqb** [comment]
@nczitzk @linbuxiao 👀

**Comment by wft44maqb** [comment]
@nczitzk @linbuxiao

![image](https://user-images.githubusercontent.com/86122516/135542088-a55d9b13-fe96-4e2d-a306-a348f545c1db.png)

![image](https://user-images.githubusercontent.com/86122516/135542131-45da7b04-0be0-46c8-8049-6e319a9988b5.png)

**Comment by hzwyw** [comment]
@borislee0227

https://rssgo.top

**Comment by borislee0227** [comment]
@hzwyw
這個對我太V幫助了，非常非常非常感謝你
