### ISSUE TITLE
GitHub's repository issues feed doesn't work

### ISSUE THREAD

**Issue by PeterDaveHello** [DIYgod/RSSHub#7708]
- The involved route, with all required and optional parameters

  - https://rsshub.app/github/issue/docker-library/official-images/open/library/node
  - https://rsshub.app/github/issue/docker-library/official-images/open/library%2Falpine

- What is expected

  RSS of https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fnode returned

- What is actually happening

  `Error in RSSHub!`

  ```
  Looks like something went wrong

  Route requested: /github/issue/docker-library/official-images/open/library/node

  Error message: wrong path
  ```

  Not sure if it's caused by the `/` in the label.

**Comment by markcellus** [comment]
Same here, @PeterDaveHello. Did you ever find a fix?

**Comment by TonyRL** [comment]
> https://rsshub.app/github/issue/docker-library/official-images/open/library%2Falpine

This one is working as of replying. You need an url-encoded label.


You can try https://rsshub.app/github/issue/docker-library/official-images/open/library%2Fibmjava (only opening issue w/ label)
