### ISSUE TITLE
巴哈姆特 GNN 新闻无法抓取

### ISSUE THREAD

**Issue by dAlucard** [DIYgod/RSSHub#7713]
#### 路由地址（不包含参数）

/gamer/gnn/:category?

#### 完整路由地址，包含所有必选与可选参数

/gamer/gnn/5

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
正常抓取

#### 实际发生了什么
六月之前还正常抓取，六月开始无法抓取「动漫画」板块的数据，经验证，板块「4」、「5」均无法抓取，其余板块正常

返回报错：
Route requested: /gamer/gnn/5
Error message: Cannot read property 'replace' of undefined
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
