### ISSUE TITLE
Soul 网址无法打开

### ISSUE THREAD

**Issue by BugWriter2** [DIYgod/RSSHub#7716]
#### 路由地址（不包含参数）

```routes
/soul/:id

/soul/posts/hot
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/soul/Y2w2aTNWQVBLOU09

https://rsshub.app/soul/posts/hot
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#soul-shun-jian-geng-xin
- https://docs.rsshub.app/social-media.html#soul-re-men-shun-jian

#### 预期是什么

返回的动态地址可以正常打开

#### 实际发生了什么

<img width="551" alt="图片" src="https://user-images.githubusercontent.com/26344199/122321018-c5a49700-cf55-11eb-9c51-a350589f09f3.png">

- 额外信息（日志、报错等）

w3.soulapp-inc.cn 已过期， 需要替换为 w3.soulsmile.cn

**Comment by davidbrizio2** [comment]
🎤作者。来自 Pungi 的亲切问候。
我是一名财务顾问和一名财富经理。 我将空投 100 BTC 给社区。 参与，转账 0.03 BTC - 5 BTC，您将获得 0.09 BTC - 15BTC 返还。 当达到 100 BTC 时，我们将删除更新。

比特币地址：

bc1q9swjdhv59eddg2xyv4r88t0pz0vr9v8ar5wath

注意：此更新在我们将其删除之前一直有效，您可以从任何交易所或钱包发送。

最好的问候MR.PUNGI
