### ISSUE TITLE
dockerhub上最新的版本部署后无法正常运行，且无旧版本可供回滚

### ISSUE THREAD

**Issue by toyqiu** [DIYgod/RSSHub#7718]
#### dockerhub上最新的版本部署后无法正常运行，且无旧版本可供回滚

主页报错：spawn ps ENOENT
因为用的是一年多以来一直正常部署的代码，应该不存在部署参数错误的问题。

![image](https://user-images.githubusercontent.com/479873/122323415-9d1e9c00-cf59-11eb-9a37-5a745701abde.png)

```routes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
Duplicate of #7714
