### ISSUE TITLE
懂球帝早报报错

### ISSUE THREAD

**Issue by MouseWhite** [DIYgod/RSSHub#7719]
#### 路由地址（不包含参数）

- /dongqiudi/daily

#### 完整路由地址，包含所有必选与可选参数

- https://rsshub.app/dongqiudi/daily

#### 相关文档地址

- https://docs.rsshub.app/new-media.html#dong-qiu-di

#### 预期是什么
返回懂球帝每日头条
#### 实际发生了什么
报错
Route requested: /dongqiudi/daily
Error message: Cannot read property 'newData' of undefined

- 额外信息（日志、报错等）

**Comment by ruleroller** [comment]
俺也一样，16号开始就没收到早报了。 cc @HenryQW
