### ISSUE TITLE
微博RSS已不能使用

### ISSUE THREAD

**Issue by In2013** [DIYgod/RSSHub#7735]
#### 路由地址（不包含参数）

```
/weibo/keyword/
/weibo/search/hot
/weibo/user/
```

#### 完整路由地址，包含所有必选与可选参数

```
/weibo/keyword/:keyword/:routeParams?
/weibo/search/hot
/weibo/user/:uid/:routeParams?
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#wei-bo

#### 预期是什么
正常抓取

#### 实际发生了什么
Timeout awaiting 'request' for 20000ms

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by yefoenix** [comment]
微博反爬严格，需要自建服务

**Comment by WellFolg** [comment]
> 微博反爬严格，需要自建服务

我是在腾讯云自建的RSSHub服务，但使用RSS阅读器拉取个人微博博主的信息时，有时会出现错误，可能是如你所说被反扒机制击中。我看到搭建的服务首页Debug下有个参数Request Frequency:0.543 times/minute 这个是访问的频率吗？两分钟一次，这样的访问频次已经很低了，为何还会被禁止访问

**Comment by wyzane** [comment]
我自己搭建的服务，有时候出现这个错误：Error in /weibo/user/6704843422: TypeError: Cannot read property 'screen_name' of undefined\n    at module.exports (/home/service/RSSHub/lib/routes/weibo/user.js:16:55)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async cache (/home/service/RSSHub/lib/middleware/cache.js:203:9)\n    at async module.exports (/home/service/RSSHub/lib/middleware/parameter.js:8:5)\n    at async module.exports (/home/service/RSSHub/lib/middleware/template.js:15:5)\n    at async /home/service/RSSHub/lib/middleware/api-response-handler.js:143:9\n    at async module.exports (/home/service/RSSHub/lib/middleware/api-template.js:2:5)\n    at async module.exports (/home/service/RSSHub/lib/middleware/utf8.js:4:5)\n    at async module.exports (/home/service/RSSHub/lib/middleware/debug.js:14:5)\n    at async module.exports (/home/service/RSSHub/lib/middleware/access-control.js:29:13)\n    at async module.exports (/home/service/RSSHub/lib/middleware/header.js:20:5)\n    at async module.exports (/home/service/RSSHub/lib/middleware/onerror.js:20:9)","level":"error"}

**Comment by wyzane** [comment]
error: Error in /weibo/user/6704843422: TypeError: Cannot read property 'screen_name' of undefined
    at module.exports (/home/service/RSSHub/lib/routes/weibo/user.js:16:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/home/service/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/service/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/template.js:15:5)
    at async /home/service/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/service/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/debug.js:14:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/access-control.js:29:13)
    at async module.exports (/home/service/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/onerror.js:20:9)

**Comment by RekiDunois** [comment]
我在heroku自建的rsshub服务，微博路由似乎也不能工作了

**Comment by vicat47** [comment]
我在阿里云自建的服务，被反爬了。。
Response code 403 (Forbidden): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.

**Comment by dsnw11** [comment]
看来都被反爬了？我看官方的还可以爬，但是添加不上去
无法从指定的网址下载:; 28 Failed to connect to rsshub.app port 443 after 7703 ms: Operation timed out

**Comment by In2013** [comment]
频率低一般不会反爬

**Comment by TonyRL** [comment]
/test
```routes
/weibo/user/1195230310
/weibo/keyword/DIYgod
/weibo/search/hot
```

**Comment by Mapz** [comment]
我也被反爬了，总超时
