### ISSUE TITLE
readhub已失效

### ISSUE THREAD

**Issue by billLiao** [DIYgod/RSSHub#775]
readhub 已失效

readhub 使用的 API 地址已经更换，当前使用的为
```
https://api.readhub.me
```
检查发现已更换为
```
https://api.readhub.cn
```

**Comment by Maecenas** [comment]
`https://api.readhub.me` 是做了301到 `https://api.readhub.cn` 的，路由没有识别到。

**Comment by DIYgod** [comment]
Done. cacee641e327ddea84671d9c192b94612f17abab
