### ISSUE TITLE
品葱所有路由都不能用了

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7755]
#### 路由地址（不包含参数）

https://rsshub.app/pincong/hot

#### 完整路由地址，包含所有必选与可选参数
https://rsshub.app/pincong/hot
https://rsshub.app/pincong/category/1/new
https://rsshub.app/pincong/topic/美国

#### 相关文档地址

https://docs.rsshub.app/bbs.html#pin-cong-jing-xuan

#### 预期是什么
正常显示条目
#### 实际发生了什么
![image](https://user-images.githubusercontent.com/3047708/122892437-f7639680-d377-11eb-90a2-4dd80a912392.png)

#### 部署相关信息
官方demo和自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
看报错信息，应该不是反爬。

**Comment by murphysking** [comment]
看错误信息是puppeteer启动失败，可能是没有安装，请参照[部署说明](https://docs.rsshub.app/install/#docker-compose-bu-shu)安装或更换部署方式

**Comment by ruleroller** [comment]
> 看错误信息是puppeteer启动失败，可能是没有安装，请参照[部署说明](https://docs.rsshub.app/install/#docker-compose-bu-shu)安装或更换部署方式

可问题是官方demo也这样啊（今天也还是如此），不只是我自建的会这样啊…… 部署也都是按照说明正常部署了的。

![image](https://user-images.githubusercontent.com/3047708/128065240-de1c5b79-323d-4546-b80a-e341d0c693f5.png)

**Comment by TonyRL** [comment]
Routes using puppeteer is working again on demo instance.
