### ISSUE TITLE
Error: Cannot find module 'city-timezones'

### ISSUE THREAD

**Issue by aotian16** [DIYgod/RSSHub#7756]
#### 路由地址（不包含参数）

```routes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么

启动RSSHub

#### 实际发生了什么

RSSHub启动失败

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       mac big sur 11.4        |
| Node version       |       v16.2.0        |
| if Docker, version |               |

- 额外信息（日志、报错等）

node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'city-timezones'

**Comment by murphysking** [comment]
未能复现问题，提供具体的错误信息吧

**Comment by aotian16** [comment]
日志里只有这么一些日志

```sh
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'city-timezones'
Require stack:
- /xxx/RSSHub/lib/routes/japanpost/utils.js
- /xxxRSSHub/lib/routes/japanpost/track.js
- /xxxRSSHub/lib/router.js
- /xxxRSSHub/lib/app.js
- /xxxRSSHub/lib/index.js
```

**Comment by aotian16** [comment]
重新安装过程中也报错

```
/Users/xxxx/Library/Caches/node-gyp/16.2.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
```

我按照提示修改`remove_cv_t`为`remove_cv`， 安装成功了
