### ISSUE TITLE
某mac OS app 价格更新订阅失败

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [DIYgod/RSSHub#777]
https://itunes.apple.com/us/app/ligand-viewer/id1357881958?mt=12
 该软件，订阅价格更新在这个链接：
https://rsshub.app/appstore/price/us/mac/id1357881958

返回错误：
RSSHub 发生了一些意外:
TypeError: Cannot read property 'title' of undefined
    at module.exports (/app/routes/appstore/price.js:25:77)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by HenryQW** [comment]
底层采用的是 http://cheapcharts.de 的 API.

很不幸这个 app 蜜汁无法显示，API 也返回空值。

http://cheapcharts.de/itunes/us/macapps/detail-view/1357881958
