### ISSUE TITLE
[Bug] 澎湃新闻 -  频道 - 504 超时错误

### ISSUE THREAD

**Issue by JaydenMcEncroe** [DIYgod/RSSHub#7775]
#### 路由地址（不包含参数）

```routes
/thepaper/list/:id
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/thepaper/channel/27224
```

#### 相关文档地址

- https://docs.rsshub.app/traditional-media.html#peng-pai-xin-wen-pin-dao

#### 预期是什么

生成澎湃新闻对应频道 RSS。

#### 实际发生了什么

504 超时错误。

注：澎湃的 首页头条 及 列表 仍可正常工作。

**Comment by Dong-Cao** [comment]
应该是被反爬了，自建就能解决。

**Comment by Dong-Cao** [comment]
https://rsshub.app/thepaper/channel/36079 
测试并没有任何问题。只是抓去内容不是最新，自建就能解决。

**Comment by JaydenMcEncroe** [comment]
测试自建可用。不过为什么同样都是频道路由，rsshub.app 上面有的 id 可以（而且很稳定），有的 id 就不行？
