### ISSUE TITLE
Rarbg rss wanted

### ISSUE THREAD

**Issue by JasonKhew96** [DIYgod/RSSHub#778]
`https://rarbg.com/torrents.php`

Found `https://torrentapi.org/apidocs_v2.txt` but
Tokens automatically expire in 15 minutes.
1 request / 2 seconds limit

🤔🤔🤔

**Comment by 10362227** [comment]
https://rarbg.to/rss.php

**Comment by LiamKarlMitchell** [comment]
By categories.
https://rarbg.to/rssdd.php?categories=14;48;17;44;45;47;50;51;52;42;46

**Comment by ebubekirttr** [comment]
This link contains all of the categories, if smone trying to add their client today 
http://rarbg.to/rssdd.php?categories=4;44;51;54;23;40;14;45;52;18;25;32;48;47;42;41;27;33;17;50;46;49;28;53
