### ISSUE TITLE
微博发布时间存在问题

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#780]
博主方案一：`/weibo/user/:uid`

下面的举例微博下，实际时间应该是 ` Mon, 24 Sep 2018 01:58:12 GMT`，RssHub给出的时间是 `Sun, 23 Sep 2018 18:00:58 GMT`

这里*秒*的误差不需要关心，因为微博 API 获取的时间是不精准的，且存在截图时间的误差。
但是粗略观察可以发现，小时上**差了 8 个小时**，明显是时差问题。

举例微博：https://weibo.com/2019071187/GANRXic8u
![image](https://user-images.githubusercontent.com/21376471/45936424-d617c500-bfe8-11e8-8d7b-5e8b95883a8a.png)

RssHub：https://rsshub.app/weibo/user/2019071187
![image](https://user-images.githubusercontent.com/21376471/45936432-ecbe1c00-bfe8-11e8-9c61-a8113cbcdcdf.png)

**Comment by Andiedie** [comment]
推测这个误差是由于下面问题导致的：

https://github.com/DIYgod/RSSHub/blob/5cbd189546fabffd54e2af12b1211be031635cd5/routes/weibo/utils.js#L39-L79

这部分代码中 `setTimeZone` 似乎可以用来纠正时差问题，但是 43 行 64 列有个 Magic Number `8` ，定死了运行服务器的时区位于东八区。

RssHub的公共服务器似乎运行在外网，不再东八区。

**Comment by Maecenas** [comment]
@Andiedie 看起来并不是 `setTimeZone` 的问题，这一段的逻辑我觉得是：将服务器所在时区获得的微博发送时间，转化为东八区的时间。这里的假设是微博显示的时间会随用户时区改变，而假设如果不成立，`setTimeZone` 也就没有必要了。

另外 `setTimeZone` 重构成单例模式会比较好。

**Comment by HenryQW** [comment]
这个是修复微博方案2时区错误，我没看方案1。
方案2是通过微博挂件获取微博内容，挂件时间为绝对东八区时间，所以需要 magic number 8 加上服务器所在时区`serverOffset`，得出 GMT。
