### ISSUE TITLE
希望能增加网页版的抖音个人用户页面新增视频项目的RSS

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7834]
### 网站地址
https://www.douyin.com/
### 网站描述
抖音短视频网页版
### 需要生成什么内容？
用户个人的新增视频项目的rss

个人用户页面举例：[首尔大表哥](https://www.douyin.com/user/MS4wLjABAAAALPhIGRZkt_pueaSdG5dJIp8kI03yTl4wWDlekBp5oTQ)
### 额外描述
注意排除掉个人项目里“置顶”视频的干扰。

**Comment by JJrousi** [comment]
+1

**Comment by matakk** [comment]
+1

**Comment by line2** [comment]
+1

**Comment by nokaka** [comment]
+1

**Comment by nokaka** [comment]
附议附议
