### ISSUE TITLE
创业板发行上市审核信息公开网站/项目动态/IPO

### ISSUE THREAD

**Issue by chinobing** [DIYgod/RSSHub#7850]
### 这是一个什么样的功能？
地址：http://listing.szse.cn/projectdynamic/ipo/index.html

捉取rss

### 这个功能可以解决什么问题？
目前rsshub只有针对科创板审核情况的rss
希望可以添加针对创业板

### 额外描述

**Comment by chinobing** [comment]
你好，显示path wrong，是不是输入有误？
https://docs.rsshub.app/other.html#shen-zhen-zheng-quan-jiao-yi-suo-chuang-ye-ban-xiang-mu-dong-tai

![image](https://user-images.githubusercontent.com/27722028/126095961-c86a47e0-8e90-4c6e-b93b-ab7fba658f3b.png)

**Comment by auto-bot-ty** [comment]
正常，https://rss.shab.fun/szse/projectdynamic

**Comment by chinobing** [comment]
> 正常，https://rss.shab.fun/szse/projectdynamic

my bad. 我刚刚更新了docker，确实是可以用，谢谢回复
