### ISSUE TITLE
GitLab文档错误

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#7893]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/gitlab
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/gitlab/release/pleroma/pleroma/git.pleroma.social
https://rsshub.app/gitlab/tag/rluna-open-source%2Ffile-management%2Fowncloud/core/gitlab.com
```

#### 相关文档地址

- https://docs.rsshub.app/programming.html#gitlab-releases
- https://docs.rsshub.app/programming.html#gitlab-tags

#### 预期是什么
获取对应Project的Release或者Tag信息
#### 实际发生了什么
Route requested: /gitlab/tag/rluna-open-source%2Ffile-management%2Fowncloud/core/gitlab.com

Error message: wrong path
#### 部署相关信息
官方路由

**Comment by zoenglinghou** [comment]
我去研究一下...目前你可以用 gitlab 自己的 tag RSS Feed

**Comment by zoenglinghou** [comment]
`master` 本地测试没有出现错误...可能是 rsshub.app 尚未部署最新版？

**Comment by wym3253** [comment]
> 
> 
> `master` 本地测试没有出现错误...可能是 rsshub.app 尚未部署最新版？

自建测试工作正常
