### ISSUE TITLE
希望能给全国气象应急预警增加上正文内容

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7905]
### 这是一个什么样的功能？
给全国气象预警的路由增加正文内容
### 这个功能可以解决什么问题？
可以防止nmc网站上的预警过期失效，无法在nmc网站上回顾过去预警内容的问题。
### 额外描述
@MisteryMonster 老哥以及各位路过的大佬们，有空的话，是否能再给此气象预警增加一下**正文内容**呢，目前RSS的正文是和标题一样的，只有点击链接进入nmc网站才能看到详细的预警内容，可nmc网站上不会一直保存预警的内容（请见附图1，最后一页也只有44页到7月19日），因此一段时间过后，想回顾一下都不可能（请见附图2）。所以，如果能将详细的内容直接加入到正文里，那就能解决此问题了。

附图1:
![image](https://user-images.githubusercontent.com/3047708/126374329-2eb157d0-c86c-4178-a7a9-32f6431979ca.png)

附图2:
![image](https://user-images.githubusercontent.com/3047708/126374650-63442028-8517-4dd6-afc8-20010cbec87c.png)

**Comment by ruleroller** [comment]
或许增加上那个页面内容到正文里，会影响抓取效率和提高被封禁的可能，所以我想，如果以增加一个参数的方式，给需要正文内容的人用参数后添加上正文内容，不需要的人不用那个参数，就保持原状。这样是否比较好呢？

**Comment by MisteryMonster** [comment]
[通用参数](https://docs.rsshub.app/parameter.html#quan-wen-shu-chu)里面的 `mode=fulltext` 可以用来全文获取。

**Comment by ruleroller** [comment]
Good。挺好用的！
