### ISSUE TITLE
二十次幂网址变了，不能再获取微信订阅，能否更新路由

### ISSUE THREAD

**Issue by god-hu** [DIYgod/RSSHub#7911]
### 这是一个什么样的功能？
二十次幂网址变更，能否更新路由
### 这个功能可以解决什么问题？
网址变更后似乎原来的路由不能用了
原路由：/wechat/ershicimi/:id
### 额外描述
原网址：https://www.ershicimi.com/
现网址：https://www.cimidata.com/

**Comment by Darkluna999** [comment]
不过我这旧路由还能用啊
