### ISSUE TITLE
希望可以适配托管平台 glitch.com

### ISSUE THREAD

**Issue by ArsenicX** [DIYgod/RSSHub#7912]
### 这是一个什么样的功能？
之前在用 **Heroku.com**，但是这个平台每月有时长限制，临近月末就会耗尽时长，不能继续抓取了
于是发现了一个新的部署托管平台 **[glitch](https://glitch.com/)**
每月1000h时长，足够普通用户使用了，希望大佬们可以适配一下

我在这里注册并导入了 https://github.com/DIYgod/RSSHub.git ，已经可以正常使用了，但是 environment 不知道怎么配置，比如说YOUTUBE_KEY，所以希望大佬们可以适配一下，出个教程

**Comment by TonyRL** [comment]
> 但是 environment 不知道怎么配置

[Home > Project Editor > How do I store secrets, credentials or private data?](https://help.glitch.com/kb/article/18-how-do-i-store-secrets-credentials-or-private-data/)

**Comment by ArsenicX** [comment]
> > 但是 environment 不知道怎么配置
> 
> [Home > Project Editor > How do I store secrets, credentials or private data?](https://help.glitch.com/kb/article/18-how-do-i-store-secrets-credentials-or-private-data/)

哇感谢😘😘
