### ISSUE TITLE
art 模板在路由中使用的文档

### ISSUE THREAD

**Issue by SettingDust** [DIYgod/RSSHub#7929]
### 这是一个什么样的功能？
art 模板在路由中使用的文档，参考 rsshub 的 xml [生成方式](https://www.github.com/DIYgod/RSSHub/tree/master/lib%2Fmiddleware%2Ftemplate.js)

### 这个功能可以解决什么问题？
不用大量文本拼接 rss 内容

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/pull/8224
