### ISSUE TITLE
Telegram channel 频道路由的某些频道报错无法获取RSS项目

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#7938]
#### 路由地址（不包含参数）
http://rsshub.app/telegram/channel/

#### 完整路由地址，包含所有必选与可选参数

http://rsshub.app/telegram/channel/pincongessence

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#telegram-pin-dao

#### 预期是什么
能正常生成RSS
#### 实际发生了什么
![image](https://user-images.githubusercontent.com/3047708/127257802-b94570a7-0551-46d9-8aa0-a412c38b3ec9.png)

#### 部署相关信息
自建最新和官方demo都有此问题

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
请 @notofoe 老哥和其他路过的大佬有空是否能尽快修复一下，目前就这个频道有问题，t.me/s/pincongessence 是没问题的。其它我所关注的频道也都是正常的。担心和最新的频道文章有关系，希望能尽快看看，如果该频道出了新文章，或许就又找不到这个问题了。。

**Comment by ericworks** [comment]
`https://t.me/pincongessence/2387`

telegram channel web preview 更新媒体文件预览机制，大媒体文件不再显示web预览，提示“media too big”

at `lib/routes/telegram/channel.js` : `131-137` 

```
poster="${
                                $(this)
                                    .find('.tgme_widget_message_video_thumb')
                                    .css('background-image')
                                    .match(/url\('(.*)'\)/)[1]
                            }"
```

对于大媒体文件，`.tgme_widget_message_video_thumb` 元素不存在，因此 `$(this).find('.tgme_widget_message_video_thumb')` 返回 `undefined`

**Comment by ruleroller** [comment]
@ericworks 那是否可以进行判断如果遇到 "media too big"的时候，进行例外处理呢，不然现在RSS都无法获取了。

**Comment by ruleroller** [comment]
@nczitzk 大佬是否能抽空看看这个issue，根据楼上另一位大佬的找出来的问题所在，进行一下适当的修复啊？真的半个多月了，就一直报错，恼火呀。🙄

我想法大概是：如果出现“大媒体文件”，用其它方法显示，如果无法进行直接展示大文件，那么就给出相关的提示，再至少放个大文件的链接地址。

也不知道我说清楚没有。

**Comment by nczitzk** [comment]
> @nczitzk 大佬是否能抽空看看这个issue，根据楼上另一位大佬的找出来的问题所在，进行一下适当的修复啊？真的半个多月了，就一直报错，恼火呀。🙄

因为消息页没有提供链接，所以仅增加了媒体文件过大的提示 🤝

**Comment by ruleroller** [comment]
> > @nczitzk 大佬是否能抽空看看这个issue，根据楼上另一位大佬的找出来的问题所在，进行一下适当的修复啊？真的半个多月了，就一直报错，恼火呀。🙄
> 
> 因为消息页没有提供链接，所以仅增加了媒体文件过大的提示 🤝

经过了大半天、多个频道的测试，Good！ 👍
