### ISSUE TITLE
[BUG]网易新闻排行榜 路由报错－源链接更换，rss 失效

### ISSUE THREAD

**Issue by rockbenben** [DIYgod/RSSHub#7945]
#### 路由地址（不包含参数）

```
https://rsshub.app/netease/news/rank/whole/click/day
```

#### 实际发生了什么
网易新闻24小时点击榜 - 全站 链接已更改。
原先为`http://news.163.com/special/0001386F/rank_whole.html`，现在为`http://news.163.com/special/000120FU/test080617.html`。

源链接更改后，rss 失效不再抓取。

**Comment by nczitzk** [comment]
[提供的链接](http://news.163.com/special/000120FU/test080617.html) 估计应该是排行榜测试页（展示的是过时的旧闻），[原链接](http://news.163.com/special/0001386F/rank_whole.html) 似乎依然可用，只不过直接访问会跳转到主页。
