### ISSUE TITLE
语雀知识库：401 [BUG]

### ISSUE THREAD

**Issue by Lianglw** [DIYgod/RSSHub#7950]
- 完整路由地址，包含所有必选与可选参数
    `/yuque/doc/1776696`
- 预期是什么

- 实际发生了什么

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |v14.17.3     |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
    Response code 401 (Unauthorized)
```

**Comment by laosuan** [comment]
https://github.com/DIYgod/RSSHub/pull/7851
似乎这个commit打算解决这个问题,但是修复的不完善没有合进去?
