### ISSUE TITLE
Bilibili用户动态无法正常抓取

### ISSUE THREAD

**Issue by Yuan68** [DIYgod/RSSHub#7959]
#### 路由地址（不包含参数）

```routes
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by huLter** [comment]
路由地址
```
/bilibili/followings/dynamic
```
同样报错，提示
```
Error message: Cannot read property 'title' of undefined
```

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/issues/7959
