### ISSUE TITLE
package.json main workers_index.js

### ISSUE THREAD

**Issue by liuxy0551** [DIYgod/RSSHub#7962]
package.json 中 `main` 字段的值是 `lib/workers_index.js`，但是 `/lib` 文件下并没有 `workers_index.js`，观察源码后发现 `main` 字段的值应该是 `lib/pkg.js`

#### 预期是什么

package.json 中 `main` 字段的值是 `lib/pkg.js`

#### 实际发生了什么

package.json 中 `main` 字段的值是 `lib/workers_index.js`

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    mac os  big sur 11.3       |
| Node version       |       1.0.0-master.b101ba9      |
| if Docker, version |        -       |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/34759874/128053514-1f84e978-b395-42c5-b234-54e7276e0812.png)
![image](https://user-images.githubusercontent.com/34759874/128109633-e6fd7a0d-ab08-4a65-8c86-6b7ef6757360.png)

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/pull/7921
