### ISSUE TITLE
申请为"turbulence.nei.st"制作 RSS 订阅源

### ISSUE THREAD

**Issue by osiren** [DIYgod/RSSHub#8007]
### 网站地址
https://turbulence.nei.st/

### 网站描述
新闻聚合类网站

### 需要生成什么内容？
希望能支持订阅网站首页 Latest 标签下的内容，支持按新闻来源分类订阅。若无法查看内容，仅提供文章列表也可。

### 额外描述
网站除 https://turbulence.nei.st/publication/standard/ 页面以外的其他内容需要登录后才能查看。根据网站客服人员所述，RSS Feed 地址为：https://turbulence.nei.st/bareback/wp-u0066u0065u0065u0064/ 且需要阅读器支持登录验证才能读取，但我尝试过多个支持登录验证的阅读器，均无法订阅，提示错误消息为：指定的 URL 没有包含任何订阅源或找不到任何订阅。

**Comment by TonyRL** [comment]
nei.st is dead.
