### ISSUE TITLE
Vercel部署后提示504错误

### ISSUE THREAD

**Issue by huLter** [DIYgod/RSSHub#8009]
#### 部署地址

https://tptest.vercel.app/

#### 预期是什么

能正常访问

#### 实际发生了什么

提示
```
504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
```

#### 部署相关信息

最新版本vercel一键部署

**Comment by NeverBehave** [comment]
能复现但是无法诊断

**Comment by NeverBehave** [comment]
经调查，Vercel免费版可能有更严格的限制，Pro计划部署无问题，建议换用其他方式部署

**Comment by huLter** [comment]
但是部署之前的版本（7月17日的版本）却可以正常运行

**Comment by auto-bot-ty** [comment]
精简路由，不再提示超时 👌

**Comment by TN29S** [comment]
怎么精简路由？

**Comment by auto-bot-ty** [comment]
> 怎么精简路由？

router

> 怎么精简路由？

注释 `lib/router.js`文件中的代码

**Comment by TN29S** [comment]
> > 怎么精简路由？
> 
> 注释 `lib/router.js`文件中的代码

感谢，精简之后确实是不提示错误了。

**Comment by NeverBehave** [comment]
#8021 已经优化
