### ISSUE TITLE
最新版的镜像  在docker中  部署失败

### ISSUE THREAD

**Issue by alfchao** [DIYgod/RSSHub#8011]
#### 路由地址（不包含参数）

```routes  
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes  
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么

部署成功

#### 实际发生了什么
部署失败，在不同的环境中试了好几次，报错信息相同。
#### 部署相关信息
失败信息：

npm ERR! Failed at the rsshub@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-13T12_32_45_237Z-debug.log

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

用2021-07-17的镜像，没有任何问题。

**Comment by NeverBehave** [comment]
Potential Duplicate https://github.com/DIYgod/RSSHub/issues/7997
