### ISSUE TITLE
pixiv中用户动态是只能获取30个吗

### ISSUE THREAD

**Issue by jyeric** [DIYgod/RSSHub#8016]
#### 路由地址（不包含参数）

```routes
/pixiv/user/
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/pixiv/user/:id
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#pixiv-yong-hu-dong-tai

#### 预期是什么
能获取到按照顺序的pixiv图片动态

#### 实际发生了什么
未按照顺序，中间有缺少，且只有30个

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Ubuntu 20.04        |
| Node version       |               |
| if Docker, version |        Docker version 20.10.8, build 3967b7d       |

具体的信息在文档中找不到

**Comment by NeverBehave** [comment]
more information required for missing items, closed because of stale.

一般来说，路由本身有自己的条目限制，limit只能限制数量往下，而不能往上
