### ISSUE TITLE
天天基金无法抓取

### ISSUE THREAD

**Issue by haiyangzhijia** [DIYgod/RSSHub#8017]
#### 路由地址（不包含参数）
/eastmoney/user/

#### 完整路由地址，包含所有必选与可选参数
/eastmoney/user/4477112899863748

#### 相关文档地址
- https://docs.rsshub.app/finance.html#tian-tian-ji-jin

#### 预期是什么
正常抓取用户内容

#### 实际发生了什么
自己搭建的RSSHub，别的都是正常抓取，天天基金抓取返回404

#### 部署相关信息
树莓派-docker

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | raspios-32|
| Node version       |2021-05-07|
| if Docker, version | Docker version 20.10.8|

- 额外信息（日志、报错等）
- Route requested: /eastmoney/user/6551094298949188
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

**Comment by TonyRL** [comment]
route path has been changed to `/eastmoney/ttjj/user/:uid`

User id `4477112899863748` has no posts as you can see in https://fundbarmob.eastmoney.com/index.html?goPage=personDetailView&userid=4477112899863748
