### ISSUE TITLE
新聞聚合類網站

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8030]
### 网站地址
yahoo新聞 tw:
https://tw.news.yahoo.com/

yahoo新聞 hk:
https://hk.news.yahoo.com/

line today tw:
https://today.line.me/tw/v2

line today hk:
https://today.line.me/hk/v2

msn新聞 tw:
https://www.msn.com/zh-tw/news

msn新聞 hk:
https://www.msn.com/zh-hk/news

google新聞 tw:
https://news.google.com/?gl=TW

google新聞 hk:
https://news.google.com/?gl=HK

### 网站描述
新聞聚合類網站

### 需要生成什么内容？
n/a

**Comment by nczitzk** [comment]
https://tw.news.yahoo.com/rss
https://hk.news.yahoo.com/rss
https://rss.msn.com/zh-tw
https://rss.msn.com/zh-hk
https://news.google.com/rss?hl=zh-tw
https://news.google.com/rss?hl=zh-hk

**Comment by TonyRL** [comment]
Yahoo
https://docs.rsshub.app/traditional-media.html#yahoo

Google
https://docs.rsshub.app/new-media.html#gu-ge-xin-wen
