### ISSUE TITLE
[TelegramBridge] Images in old posts do not load due to media URLs with expiration date

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#8031]
Describe the bug
URLs for media in Telegram returned in web preview (https://cdn4.telesco.pe/file/…) are not persistent, they work only for limited amount of time. Due to this fact, the older Telegram posts in the channel have broken images and other media elements in the RSS reader.

The bridge should implement a jumper URLs to the bridge script itself, which would update the links and redirect the request to working updated URLs with HTTP redirect.

To Reproduce

    Subscribe to Telegram channel using RSS client
    Wait ≈2 days
    Open older posts containing media elements (images, video, audio)
    Result: no media is loaded

Expected behavior
The media should be loaded even in the older posts.

Screenshots
![image](https://user-images.githubusercontent.com/34004367/129607496-634c92d2-4446-4d62-9d1a-52d5c0a0139a.png)

The image URL returns HTTP 404.

FIX: use telegra.ph img instead of telesco.pe?
![image](https://user-images.githubusercontent.com/34004367/129607556-9a286fb3-6fd6-4ef9-9c46-e50f53bdcd73.png)

**Comment by TonyRL** [comment]
What your screenshot is showing is the "link preview"'s image.

It's not the case if it is an image post on a channel.
Take a look at [an image post in Telegram Beta channel](https://t.me/s/tgbeta/4390). You can see we can only get the image URL from telesco.pe in `a`'s style.
<details>

<summary>4390's HTML source</summary>

![4](https://user-images.githubusercontent.com/11386903/131899664-e3fbe0fd-144e-4c5a-98fb-a9fd0058b529.PNG)

</details>

**Comment by dumprop** [comment]
> 
> 
> What your screenshot is showing is the "link preview"'s image.
> 
> It's not the case if it is an image post on a channel.
> Take a look at [an image post in Telegram Beta channel](https://t.me/s/tgbeta/4390). You can see we can only get the image URL from telesco.pe in `a`'s style.
> 4390's HTML source
> 
> ![4](https://user-images.githubusercontent.com/11386903/131899664-e3fbe0fd-144e-4c5a-98fb-a9fd0058b529.PNG)

https://t.me/s/cash_in_tablic
![image](https://user-images.githubusercontent.com/34004367/131906124-09709d7b-a8f0-4b6f-b850-19cfe06ebd8a.png)
They have it in every post
But many channels doesn't have a telegra.ph url, yes :(

**Comment by TonyRL** [comment]
Closed in #13255
