### ISSUE TITLE
[TelegramBridge] Disable limit to the number of parsed articles

### ISSUE THREAD

**Issue by dumprop** [DIYgod/RSSHub#8032]
Often I need to get not only the last articles from a channel, but also previous 100-200-500 and more messages. It will be great to have an option to regulate limit of messages to grab or to turn off this limit (best solution for me).

https://t.me/s/telegram?before=20 and you get first 20 posts, https://t.me/s/telegram?before=40 and you get 21-40 posts, etc
There no too much channels with 1k+ posts
I think it will be cool feature out of the box
But probably it's a headache for public instances, some possible restrictions are needed

**Comment by TonyRL** [comment]
Closed in #13255
