### ISSUE TITLE
建议更新紫竹张先生

### ISSUE THREAD

**Issue by StrollStars** [DIYgod/RSSHub#8046]
#### 路由地址（不包含参数）

```
https://rsshub.app/zzz
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/zzz/:category?/:language?
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
能够正常接收文章更新

#### 实际发生了什么
文章在6月15日之后不再更新，因为网址发生了一些变化，从原来的[https://z-z-z.vip/](https://z-z-z.vip/)变更为[https://www.z-z-z.vip/](https://www.z-z-z.vip/)。

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
Duplicate of #7881
Already fixed in #7890

**Comment by StrollStars** [comment]
@TonyRL 但是现有路由地址无效

**Comment by TonyRL** [comment]
> 
> 
> @TonyRL 但是现有路由地址无效

See Discussion #7724.
