### ISSUE TITLE
人民网观点求rss

### ISSUE THREAD

**Issue by coolarec** [DIYgod/RSSHub#8078]
### 标题及文章

**Comment by TonyRL** [comment]
https://docs.rsshub.app/traditional-media.html#ren-min-ri-bao

**Comment by coolarec** [comment]
这一个似乎不能用了

**Comment by guangwenzhu** [comment]
人民网观点频道官方源 http://www.people.com.cn/rss/opinion.xml
其他频道订阅源见 http://www.people.com.cn/rss/opml.xml
均支持全文输出
