### ISSUE TITLE
一些港、台網站

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8080]
### 网站地址
~

### 网站描述
# hk:
uwants https://www.uwants.com/
香討 https://www.discuss.com.hk/
高登 https://hkgolden.com/
連登 https://lihkg.com/

# tw:
- ptt 批踢踢: https://www.ptt.cc/bbs/
https://www.ptt.cc/bbs/{板名}/index.html --> https://www.ptt.cc/atom/{板名}.xml
https://www.ptt.cc/bbs/Gossiping/index.html --> https://www.ptt.cc/atom/Gossiping.xml

- 記者快抄 https://ptt.islander.cc/ (ptt出品?)

- 島民衛星 https://islander.cc/ (ptt出品?)

- Zuvio https://irs.zuvio.com.tw/student5/chickenM/articles

- Plurk噗浪 https://www.plurk.com/portal/

- 巴哈姆特 https://www.gamer.com.tw/
https://gnn.gamer.com.tw/

- 波波黛莉的異想世界 PopDaily https://www.popdaily.com.tw/

- Meteor https://meteor.today/

- Dcard https://dcard.tw/

- Mobile01 https://www.mobile01.com/

# cn

-TapTap https://www.taptap.io/forum/hot
https://www.taptap.io/forum/groups

- 膜乎 https://mohu.rocks/

### 需要生成什么内容？
首頁內容（、熱門、最新）

**Comment by TonyRL** [comment]
Have you ever **SEARCHED** before raising an issue?


> Generic Discuz 
> https://docs.rsshub.app/bbs.html#discuz
> 
> 巴哈姆特電玩資訊站
> https://docs.rsshub.app/bbs.html#ba-ha-mu-te-dian-wan-zi-xun-zhan
> https://docs.rsshub.app/game.html#ba-ha-mu-te-gnn-xin-wen
> https://docs.rsshub.app/social-media.html#ba-ha-mu-te
> 
> Dcard
> https://docs.rsshub.app/bbs.html#dcard
> 
> TapTap
> https://docs.rsshub.app/game.html#taptap
