### ISSUE TITLE
百度搜索风云榜 无法抓取

### ISSUE THREAD

**Issue by dawnyesky** [DIYgod/RSSHub#8108]
#### 路由地址（不包含参数）

/baidu/topwords/

#### 完整路由地址，包含所有必选与可选参数

/baidu/topwords/:boardId? 

#### 相关文档地址

- https://docs.rsshub.app/other.html#bai-du-sou-suo-feng-yun-bang

#### 预期是什么
正常抓取

#### 实际发生了什么
返回错误

#### 部署相关信息

- 额外信息（日志、报错等）

**Comment by Whichbfj28** [comment]
同求恢复
