### ISSUE TITLE
文档添加站点直链

### ISSUE THREAD

**Issue by KimYangOfCat** [DIYgod/RSSHub#8112]
### 这是一个什么样的功能？
文档指南中路由部分给各个站点添加原站点链接，其 mardown 修改如下：
![image](https://user-images.githubusercontent.com/32960305/131424857-8413d2ec-b3e8-40b3-98b5-c735c44571b6.png)

### 这个功能可以解决什么问题？
方便不知道该站点的用户直接从文档跳转到原站点，直接游览站点信息，以判断是否需要将其纳入自己的 RSS 订阅；
免去用户自行复制站点名字到搜索引擎进行检索的时间，且大概率会被搜索引擎的广告浪费时间！
### 额外描述
如果官方支持添加原站直链的话，我可以抽时间把目前路由里面所有站点的原链都补充完整
当然，最好的情况是在官方文档中加入要求补充原始站点链接的规范！

**Comment by TonyRL** [comment]
Added in 939a77ecab36f2f51d2c4220c142d2bb84bddccb.
