### ISSUE TITLE
RSS Feed for Github comments from a particular issue

### ISSUE THREAD

**Issue by oliroe** [DIYgod/RSSHub#8116]
### What feature is it?
Currently there's a feed for new issues on a particular repository but there isn't a feed for comments on an individual issue. 
### What problem does this feature solve?
I would like to be updated whenever there's a new comment on an issue i am following
### Additional description
As an example I would like to be able to follow any changes to this issue user-DIYgod, repository-RSSHub, issue-8116

**Comment by oliroe** [comment]
Hi. Thanks for the work on this
I've just got one small issue with it, it appears to be bringing through the comment body in the title and nothing in the body of the feed

![image](https://user-images.githubusercontent.com/4500141/152244052-b0b29325-d9b9-460c-8fd2-4164ffb057c5.png)

![image](https://user-images.githubusercontent.com/4500141/152244200-576be1e4-26a1-4191-8cc7-c92e56ea4b43.png)

In this example I would expect to see 'Tamberlox commented........ as the title and the body of the feed would include "is there an existing issue for this.....
What we have currently is a small portion of the body as the title

![image](https://user-images.githubusercontent.com/4500141/152244294-04304270-321d-4a34-88c4-f504f9d3eec6.png)

**Comment by TonyRL** [comment]
Please open a new issue for this.
