### ISSUE TITLE
微博的rss发布时间不是北京时间

### ISSUE THREAD

**Issue by 10362227** [DIYgod/RSSHub#812]
能不能修正一下，要不然和别的rss放在一起阅读，按时间（最新）排序，更新了的微博永远靠后面

**Comment by DIYgod** [comment]
时区没有问题，只是微博时间只能精确到天，这个问题无解

**Comment by 10362227** [comment]
> 时区没有问题，只是微博时间只能精确到天，这个问题无解

但确实不是北京时间 https://github.com/DIYgod/RSSHub/issues/780
