### ISSUE TITLE
台灣文化銀行

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8151]
### 网站地址
http://bankofculture.com/

### 网站描述
> 我們是臺灣第一間文化銀行，這裡存有不想被遺忘的記憶。 不甘於只留下文化標本，文化銀行不僅留存記憶的圖像及形體，更要發揮人文思考的價值，使文化並不只是靜靜被 ...

> 台灣第一間文化銀行。 我們致力於文化保存與文化永續。讓「文化」不只是個名詞，而能成為一種生活 ...

### 需要生成什么内容？
http://bankofculture.com/%e8%a1%8c%e5%93%a1%e8%a9%95%e8%ab%96
http://bankofculture.com/%e6%96%87%e5%8c%96%e9%87%91%e5%ba%ab

### 额外描述
![image](https://user-images.githubusercontent.com/86122516/132234876-c43043d3-ded5-4861-9752-56c64718456d.png)

**Comment by TonyRL** [comment]
http://bankofculture.com/feed

[RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar) Browser extension that simplifies finding and subscribing RSS and RSSHub
