### ISSUE TITLE
微博路由故障

### ISSUE THREAD

**Issue by stonek22** [DIYgod/RSSHub#8182]
路由地址（不包含参数）
/weibo/user/:uid/:routeParams?

完整路由地址，包含所有必选与可选参数
https://rsshub.wkfg.me/weibo/user/1623886424/1

相关文档地址
https://docs.rsshub.app/social-media.html#wei-bo
预期是什么
正常抓取

实际发生了什么
不定时返回错误
或504超时，

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
- 
![S10912-08423749](https://user-images.githubusercontent.com/90534890/132967023-ff3ef7c4-90be-4d9c-a21e-9572e9b13ffe.jpg)

**Comment by CaptNo1** [comment]
同样出现该问题

**Comment by TonyRL** [comment]
/test
```routes
/weibo/user/1623886424/1
```
