### ISSUE TITLE
请求加入知网"某期刊文章更新“的RSS

### ISSUE THREAD

**Issue by WYEEE** [DIYgod/RSSHub#8186]
**### 网站地址**

这是刊物总导航 ：https://navi.cnki.net/knavi/
具体到某一刊物1：https://navi.cnki.net/knavi/rss/LNZY
具体到某一刊物2：https://navi.cnki.net/knavi/rss/XXYY

说是rss，但是在tgbot上无法订阅，提示：

”订阅失败: 网络错误（error sending request for url (https://navi.cnki.net/knavi/rss/XXYY): error trying to connect: received fatal alert: HandshakeFailure）“

**### 网站描述**

某一刊物的文章更新

**### 需要生成什么内容？**

以 https://navi.cnki.net/knavi/rss/LNZY 为例，希望能生成：

====================================================================
辽宁中医杂志9月

复方苦参注射液联合化疗治疗晚期结肠癌临床研究（可点击进入）

青黛灌肠液灌肠联合美沙拉嗪治疗溃疡性结肠.......（可点击进入）

...
...

====================================================================

**### 额外描述**
路由中如果能添加”点击链接直接下载“的路由配置就最好了（自备账号的环境）

**Comment by linbuxiao** [comment]
使用GET方式请求https://navi.cnki.net/knavi/rss/LNZY 即可返回可识别的XML格式文档 浏览器请求时会返回一个XSL文件 合并XML渲染为HTML 导致直接抓取无法识别 如无法使用 请提供tgbot案例
