### ISSUE TITLE
希望能增加企鹅直播的主播房间开播提醒

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#8197]
### 网站地址
https://live.qq.com
### 网站描述
企鹅直播，目前是主要播一些体育赛事的直播网站
### 需要生成什么内容？
主播们开播时的提醒
- https://live.qq.com/10012045
- https://live.qq.com/10148437

### 额外描述
这个和目前已有的“企鹅电竞”直播是不一样的，这个更偏向体育类目的，但一直纠结于是称它为“企鹅直播”还是“企鹅体育”，可看到用上live.qq.com这种二级域名，并且类目里，也还有“女神”等，估计未来还是会增加不同的直播种类的，google搜索的第一条，也都是“企鹅直播”。因此，个人认为还是直接叫“企鹅直播”比较合适。

希望呈现效果能和旺球体育、黑白体育那样的。 

@nczitzk ，大佬有空制作一个吗？ 😍  先谢过了。

其它路过的大佬也欢迎啊，嘿嘿。

**Comment by nczitzk** [comment]
被淹没在通知的涌泉中 😊 久等啦
