### ISSUE TITLE
希望能增加蓝鲸体育的主播房间开播提醒

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#8198]
### 网站地址
https://www.lanjing.live/
### 网站描述
蓝鲸体育，体育赛事直播。
### 需要生成什么内容？
主播们的开播提醒：
- https://www.lanjing.live/live/1298315
- https://www.lanjing.live/live/1030151
### 额外描述
@nczitzk ，大佬，我看了一下，用的和黑白以及旺球都是同一套模板，求制作呀~ ❤️
关注的主播，各个平台跳啊跳，可喜欢看啊，没有办法。

也欢迎路过的，有能力的可以帮忙制作一下……同样感谢！

**Comment by TonyRL** [comment]
The website is no longer accessible.
