### ISSUE TITLE
香港衞生署 & 香港衞生防護中心

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8201]
### 网站地址
香港衞生防護中心 https://www.chp.gov.hk/tc/index.html
香港衞生署 https://www.dh.gov.hk/tc_chi/index.html

### 网站描述
~

#### 香港衞生防護中心
- 重要資訊
- 新聞稿
- 期刊及刊物
- 應變級別
- 健康小貼士
- 健康通告
- 健康資訊
- 新聞稿
- 健康統計數字
- 報告及刊物
- 指引
- 健康資訊

#### 香港衞生署
- 新聞公報
-

**Comment by TonyRL** [comment]
> 
> #### 香港衞生防護中心
> 

https://www.chp.gov.hk/tc/static/24063.html
