### ISSUE TITLE
台灣衛生福利部

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8203]
### 网站地址
https://www.mohw.gov.tw/

### 网站描述
~

### 需要生成什么内容？
![image](https://user-images.githubusercontent.com/86122516/133620766-b6353764-78ef-4fa6-83ad-644178d3cdaa.png)

**Comment by nczitzk** [comment]
https://www.mohw.gov.tw/cp-2661-6125-1.html
