### ISSUE TITLE
[BUG]36Kr资讯板块出错

### ISSUE THREAD

**Issue by tanyuzhou** [DIYgod/RSSHub#8222]
- 完整路由地址，包含所有必选与可选参数
    `/36kr/news/latest`
- 预期是什么
返回36Kr资讯

- 实际发生了什么
请求返回404错误
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Windows Server 2016    |
| Node version       |v14.17.4     |
| if Docker, version |No      |

- 额外信息（日志、报错等）
```
    Response code 404 (Not Found)
```

**Comment by tanyuzhou** [comment]
@nczitzk 作者大大能帮忙看看吗QwQ

**Comment by tanyuzhou** [comment]
@NeverBehave

**Comment by nczitzk** [comment]
请等待 #8024 合并

**Comment by tanyuzhou** [comment]
> 请等待 #8024 合并

了解啦！感谢大佬的及时回复，我先自己手动修改一下好了[OK]
