### ISSUE TITLE
希望支持软餐

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#8230]
### 网站地址
https://www.ruancan.com/
### 网站描述
软餐创建于2011年，是聚焦国内外移动应用、PC软件生态和业界消息的原创科技媒体。
### 需要生成什么内容？
首页全文 RSS 输出，或分 tag 输出
### 额外描述
网站自带的 RSS (https://www.ruancan.com/feed) 不支持全文输出，也无法按 tag 分类

**Comment by Alphabet1226** [comment]
@nczitzk 请问为什么下线了该 Feed？

**Comment by nczitzk** [comment]
> @nczitzk 请问为什么下线了该 Feed？

rsshub.app 的 RSSHub 实例不是最新的版本，旧版本还没有包含该路由的支持，所以并非将其下线 😅

**Comment by Alphabet1226** [comment]
> > @nczitzk 请问为什么下线了该 Feed？
> 
> rsshub.app 的 RSSHub 实例不是最新的版本，旧版本还没有包含该路由的支持，所以并非将其下线 sweat_smile

这样啊，抱歉误会了😢只看到 rsshub.app 的 status down 就冒然来提 issue 了

**Comment by nczitzk** [comment]
> 这样啊，抱歉误会了😢只看到 rsshub.app 的 status down 就冒然来提 issue 了

这个也不是误会啦，感谢你的反馈 😃
