### ISSUE TITLE
Github 中一些仓库的 ISSUE 无法订阅

### ISSUE THREAD

**Issue by bestony** [DIYgod/RSSHub#825]
比如：https://rsshub.app/github/issue/Parkpaopao/-

仓库地址：https://github.com/Parkpaopao/-/issues

**Comment by HenryQW** [comment]
LGTM: 
![image](https://user-images.githubusercontent.com/5896343/46472592-9f566180-c7d5-11e8-9332-b54f6f41e726.png)
