### ISSUE TITLE
新加坡 8视界

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8252]
### 网站地址
https://www.8world.com/

### 网站描述
新加坡公视?
`关于我们 - 8world`: https://www.8world.com/about-us

### 需要生成什么内容？
- 即时
- 热门
- 新闻快报
- 新闻深呼吸
- 专题
![image](https://user-images.githubusercontent.com/86122516/134720062-4015d922-c2f6-42b0-9d79-fdb403f56d27.png)

### 额外描述
`8視界新聞（英語：8world News）`: https://zh.wikipedia.org/zh-tw/8%E8%A7%86%E7%95%8C%E6%96%B0%E9%97%BB

https://www.mediacorp.sg/en/your-mediacorp/news

**Comment by linbuxiao** [comment]
There are many boards, please check the priority boards first.

**Comment by wft44maqb** [comment]
> There are many boards, please check the priority boards first.

?

**Comment by linbuxiao** [comment]
> > There are many boards, please check the priority boards first.
> 
> ?

It's okay, at the time I was more confused about whether the video below needed to be pushed. So I've closed that comment.

**Comment by wft44maqb** [comment]
`Error message: wrong path` @nczitzk @NeverBehave
