### ISSUE TITLE
Bilibili 频道失效

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#826]
UP 主频道 By @HenryQW #
举例: https://rsshub.app/bilibili/user/channel/142821407/23390

![image](https://user-images.githubusercontent.com/21376471/46470223-756a6280-c808-11e8-93ee-345699ac649d.png)

**Comment by HenryQW** [comment]
发现了2个问题：

1. https://github.com/DIYgod/RSSHub/commit/6bb6b375f7647c97784279083a924ed1a0fcc38b @SevenOutman  改了路由栗子但是 router.js 没有改，正确的路由应该是 https://rsshub.app/bilibili/channel/142821407/23390

2. bilibili 的这个接口蜜汁失效了 
![image](https://user-images.githubusercontent.com/5896343/46473349-bdbd5c80-c7d7-11e8-87c6-3890ad24e9ea.png)
