### ISSUE TITLE
今日热榜rss查看原始网址时会出错

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#8261]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/tophub/
```
 
#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/tophub/:id
```

#### 相关文档地址

- https://docs.rsshub.app/new-media.html#jin-ri-re-bang

#### 预期是什么
查看rss原始地址文章，显示正确内容
#### 实际发生了什么
查看原始文章，显示《您访问的链接来自「今日热榜」，请从今日热榜官方访问，谢谢！》
![image](https://user-images.githubusercontent.com/18500636/134763681-0012c075-2aa9-4010-939e-e7342b28d1a7.png)

- 额外信息（日志、报错等）
希望有人告诉我这个怎么处理，谢谢！

**Comment by kemistep** [comment]
+1
