### ISSUE TITLE
MM范报错

### ISSUE THREAD

**Issue by songbangyan** [DIYgod/RSSHub#8266]
#### 路由地址（不包含参数）
https://rsshub.app/95mm/

#### 完整路由地址，包含所有必选与可选参数
https://rsshubs-ten.vercel.app/95mm/category/1
#### 相关文档地址
https://docs.rsshub.app/picture.html#mm-fan
#### 预期是什么
预期可以在客户端查看部分图片
#### 实际发生了什么
实际上完全不能查看图片，只能跳转到源地址浏览

- 额外信息（日志、报错等）
根据我打开网页后查看XML文件发现，能查看图片的链接地址是正常地址，而MM范这边返回的地址是类似于：
https://cdn.zzdaye.com:8443//images//8//3//7//8372b070-fb92-11ea-8301-f5453caeab3f.jpg
除了头部的双反斜杠，后面所有的间隔都是双反斜杠，这个看起来似乎不正常。

**Comment by linbuxiao** [comment]
![image](https://user-images.githubusercontent.com/56839018/134792775-1371141f-24a5-4b5e-913d-1503fcf05e67.png)
According to your example, the return is normal within my reader.

**Comment by songbangyan** [comment]
我使用的是自建的TTRSS,估计是因为更新的原因……

**Comment by linbuxiao** [comment]
> 我使用的是自建的TTRSS,估计是因为更新的原因……

应当是订阅器的问题。可以参考https://github.com/HenryQW/Awesome-TTRSS/issues/138这种解决方式。
麻烦close下issue~。
