### ISSUE TITLE
wsj bug

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8298]
#### 路由地址（不包含参数）

```
wsj
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/wsj/zh-tw
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 预期是什么
![image](https://user-images.githubusercontent.com/86122516/135184696-8321ec9e-87df-49b4-a095-088710ef92a1.png)

#### 实际发生了什么
![image](https://user-images.githubusercontent.com/86122516/135184634-61ef79a8-ec3e-4c0c-8253-61fac37c8a7b.png)

![image](https://user-images.githubusercontent.com/86122516/135184646-63e7bd6b-1724-4b92-8029-5d1c646c5af4.png)

#### 部署相关信息

n/a

- 额外信息（日志、报错等）

**Comment by wft44maqb** [comment]
![image](https://user-images.githubusercontent.com/86122516/135196485-abbd5997-32db-42ff-a607-211d9138108e.png)

![image](https://user-images.githubusercontent.com/86122516/135196472-2f7b6b00-a342-41cf-819d-bfef2ceccd0e.png)

**Comment by wft44maqb** [comment]
feed標題可以更好?

**Comment by TonyRL** [comment]
Have you ever **SEARCHED** before raising an issue?

> https://docs.rsshub.app/en/parameter.html#fulltext

**Comment by changlan** [comment]
> Have you ever **SEARCHED** before raising an issue?
> 
> > https://docs.rsshub.app/en/parameter.html#fulltext

`?mode=fulltext` doesn't seem to work either.

`zh-cn` has been broken for quite a while (https://github.com/DIYgod/RSSHub/issues/7378) but `zh-tw` was working until recently.
