### ISSUE TITLE
台灣關鍵評論網

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8304]
### 网站地址
https://www.thenewslens.com/

### 网站描述
> 關鍵評論網是創立於臺灣的中英文雙語網路媒體，於2013年8月正式上線，創辦人為鍾子偉、楊士範。關鍵評論網以「獨立評論媒體」作為定位，內容針對關注亞洲訊息的海外華僑、在台外籍人士等。 維基百科

### 需要生成什么内容？
~

**Comment by TonyRL** [comment]
https://feeds.feedburner.com/TheNewsLens
