### ISSUE TITLE
暫存圖片

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8309]
### 这是一个什么样的功能？
- 为`feed全文`里面的圖片进行缓存
- 預設关闭
- 另有开关为所有feed建立圖片缓存 (不只`全文`)

### 这个功能可以解决什么问题？
"加速"?
沒翻牆的用戶 可以獲得更佳體驗

### 额外描述
~

**Comment by TonyRL** [comment]
Have you ever **SEARCHED** before raising an issue?

> https://docs.rsshub.app/en/install/#configuration-other-application-configurations
> 
> `HOTLINK_TEMPLATE`
