### ISSUE TITLE
`HOTLINK_TEMPLATE` url編碼

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8314]
### 这是一个什么样的功能？
對url參數進行編碼

### 这个功能可以解决什么问题？
防止例外發生?
我現在的`HOTLINK_TEMPLATE`設定: `https://images.weserv.nl/?url=${protocol}//${host}${pathname}&af&output=png`
--> `https://images.weserv.nl/?url=encodeURIComponent(${protocol}//${host}${pathname})&af&output=png`

### 额外描述
- `https://images.weserv.nl/?url=https://d32kak7w9u5ewj.cloudfront.net/media/image/2021/09/2af23cbc89c544a8b4c91674a153a247.jpg` ➜ `https://images.weserv.nl/?url=https%3A%2F%2Fd32kak7w9u5ewj.cloudfront.net%2Fmedia%2Fimage%2F2021%2F09%2F2af23cbc89c544a8b4c91674a153a247.jpg`

**Comment by wft44maqb** [comment]
還有把`${protocol}`的值改成`http(s)` 而不是`http(s):`?

**Comment by TonyRL** [comment]
Closed in #9997
