### ISSUE TITLE
即時轉傳影片

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8315]
### 这是一个什么样的功能？
- 即時轉傳影片 讓沒翻牆的用戶可以獲得更佳體驗 (只限`短影片`?)

- 可能的話............................... 压縮影片? 🤔🤔🤔🤔 ( `1080p` ➜ `720p`? )

### 这个功能可以解决什么问题？
即時轉傳影片 讓沒翻牆的用戶可以獲得更佳體驗

### 额外描述
`Video Stream With Node.js and HTML5 | by Diogo Spínola | Better Programming`: 
https://betterprogramming.pub/video-stream-with-node-js-and-html5-320b3191a6b6

`Building A Video Streaming App With Nuxt.js, Node And Express`: 
https://www.smashingmagazine.com/2021/04/building-video-streaming-app-nuxtjs-node-express/

`教學課程：使用Node.js 和TypeScript 以媒體服務即時串流`: 
https://docs.microsoft.com/zh-tw/azure/media-services/latest/stream-live-tutorial-with-nodejs

...

**Comment by TonyRL** [comment]
Out of scope.
