### ISSUE TITLE
臺灣獨立媒體 - 上下游新聞市集

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8320]
### 网站地址
新聞 https://www.newsmarket.com.tw/
副刊 https://www.newsmarket.com.tw/mag/

### 网站描述
> 上下游News&Market，又稱上下游新聞市集，是一個臺灣的獨立媒體、農產品銷售平台及社會企業，其主要關注議題為農業及友善土地，成立於2011年。 維基百科

### 需要生成什么内容？
~

### 额外描述
**台灣公視P#新聞實驗室推薦**

**Comment by nczitzk** [comment]
https://www.newsmarket.com.tw/mag/feed

**Comment by wft44maqb** [comment]
> https://www.newsmarket.com.tw/mag/feed

新聞 https://www.newsmarket.com.tw/
副刊 https://www.newsmarket.com.tw/mag/
