### ISSUE TITLE
zhihu分类热榜返回的url不是实际html地址

### ISSUE THREAD

**Issue by tomasWade** [DIYgod/RSSHub#8323]
---
name: 🐛 Bug 报告
about: zhihu分类热榜返回的url不是实际html地址
---

#### 路由地址（不包含参数）

```routes
https://rsshub.app/zhihu/hot
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/zhihu/hot/digital
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#zhi-hu

#### 预期是什么
返回url是直接可以点开的url网页地址,例如
https://www.zhihu.com/questions/490037728
#### 实际发生了什么
实际返回的url地址为
<link>https://api.zhihu.com/questions/490037728</link>

#### 部署相关信息
NOTEXIST

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        linux       |
| Node version       |       10.19.0        |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
closed this in #9220
