### ISSUE TITLE
微博-博主 路由，对于无置顶微博的情况，无法抓取最新一条微博

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub#8336]
#### 路由地址（不包含参数）

```
/weibo/user/:uid/
```
例：/weibo/user/1215468900

#### 相关文档地址

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

#### 预期是什么
抓取博主的最新微博
#### 实际发生了什么
无法抓到最新一条，仅能获取到第二条及以后的内容
#### 部署相关信息
Heroku、Docker 最新版本代码自建
（官方Demo因反爬无法测试） 
- 额外信息（日志、报错等）

**Comment by xmt328** [comment]
debian 10 docker-compose部署也有一样的问题

/weibo/user/5977512966/readable=1

**Comment by BruceZhang1993** [comment]
同样的问题 自建部署的

**Comment by Rongronggg9** [comment]
@BruceZhang1993 @xmt328 @yefoenix 我已经提交了一个 PR #8633 修复这个问题。在等待合并的过程中，可以暂时使用我的 fork https://github.com/Rongronggg9/RSSHub 部署。同样也推到了 docker hub 上，替换镜像为 `rongronggg9/rsshub` 即可部署。

**Comment by BruceZhang1993** [comment]
> @BruceZhang1993 @xmt328 @yefoenix 我已经提交了一个 PR #8633 修复这个问题。在等待合并的过程中，可以暂时使用我的 fork https://github.com/Rongronggg9/RSSHub 部署。同样也推到了 docker hub 上，替换镜像为 `rongronggg9/rsshub` 即可部署。

谢谢～ 已经 cherry-pick 了这个 commit 💯

**Comment by yefoenix** [comment]
> @BruceZhang1993 @xmt328 @yefoenix 我已经提交了一个 PR #8633 修复这个问题。在等待合并的过程中，可以暂时使用我的 fork https://github.com/Rongronggg9/RSSHub 部署。同样也推到了 docker hub 上，替换镜像为 `rongronggg9/rsshub` 即可部署。

https://weibo.com/u/3339648794
这个账号的最新微博没有抓到：
https://rsshub-git-fork-rongronggg9-weibo-user-fix-diy.vercel.app/weibo/user/3339648794
