### ISSUE TITLE
希望增加山东大学通知

### ISSUE THREAD

**Issue by ipssyoungman** [DIYgod/RSSHub#834]
* 学校主页http://www.sdu.edu.cn/
* 研究生院http://www.grad.sdu.edu.cn/default.site
* 材料学院http://www.cmse.sdu.edu.cn/
* 机械学院http://www.mech.sdu.edu.cn/
* 控制学院http://control.sdu.edu.cn/
* 电气学院http://www.ee.sdu.edu.cn/
* 能动学院http://www.epe.sdu.edu.cn/
感谢

**Comment by sqliuchang** [comment]
各个学校通知还是自己学校学生写比较好吧…

**Comment by ipssyoungman** [comment]
> 各个学校通知还是自己学校学生写比较好吧…

有教程吗？我学学

**Comment by SettingDust** [comment]
@ipssyoungman 百度搜索w3school

**Comment by Ji4n1ng** [comment]
@ipssyoungman 好巧，我抽空做一做吧。。

**Comment by Ji4n1ng** [comment]
研究生院学术活动通知已提交，各学院后面会更新。

**Comment by Ji4n1ng** [comment]
@ipssyoungman  已增加山东大学软件学院、材料学院、机械工程学院和能源与动力工程学院通知。

**Comment by ron159** [comment]
> 研究生院学术活动通知已提交，各学院后面会更新。

请问以下需要用到什么东西，打算自己写自己学校得。
