### ISSUE TITLE
中国工业和信息化部订阅需要修复

### ISSUE THREAD

**Issue by ShuiHuo** [DIYgod/RSSHub#8351]
#### 路由地址（不包含参数）

```routes
/gov/miit/zcjd
/gov/miit/wjgs
/gov/miit/zcwj
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/gov/miit/zcjd
https://rsshub.app/gov/miit/wjgs
https://rsshub.app/gov/miit/zcwj
```

#### 相关文档地址

- https://docs.rsshub.app/government.html#zhong-guo-gong-ye-he-xin-xi-hua-bu

#### 预期是什么

　　访问工业和信息化部网站，获取相关文章完整内容。

#### 实际发生了什么

　　没有访问正确的页面，没有获取到内容。

**Comment by chancenju** [comment]
同

**Comment by chancenju** [comment]
球球来个人帮帮忙啊。修改了地址后总是返回521.cookie 和headers的问题。但我不会写。折腾25小时了
