### ISSUE TITLE
希望增加36氪的8点一氪专栏的单独rss

### ISSUE THREAD

**Issue by pipiepig** [DIYgod/RSSHub#837]
36氪官网有全站的rss订阅，希望增加8点一氪专栏的单独rss，8点一氪链接：https://36kr.com/tags/8dianyike

**Comment by pipiepig** [comment]
呃，突然发现8点1氪栏目的链接好久没更新，这个issue就关了

**Comment by pipiepig** [comment]
8点1氪栏目的链接好久没更新

**Comment by realliyifei** [comment]
@blanksir 请问36氪是只有全站这一个rss订阅吗？感觉一天更新太频繁了，但没找到比较精品少量的36氪rss订阅
