### ISSUE TITLE
如何成为开发者？

### ISSUE THREAD

**Issue by Javalover93** [DIYgod/RSSHub#838]
RSSHub 是个好东西。我想加入到开发者的队列中，但是不是很懂应该如何进行。有基础的编程知识，没有用过 JS。是只需要学会 JavaScript 的基础语法就能看懂如何增加新的源了吗？还是说需要别的什么知识呢？

**Comment by Javalover93** [comment]
找到这个。https://docs.rsshub.app/joinus/#%E6%95%B0%E6%8D%AE 我先试试。

**Comment by DIYgod** [comment]
js 基础即可
