### ISSUE TITLE
rsshub小bug?

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8382]
#### 路由地址（不包含参数）

```routes
https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/
```

#### 完整路由地址，包含所有必选与可选参数
```fullroutes
1. https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/rthk-news/hk/greaterchina.atom
2. https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/rthk-news/hk/greaterchina?mode=fulltext
```

#### 相关文档地址

1. https://docs.rsshub.app/parameter.html#shu-chu-ge-shi
2. https://docs.rsshub.app/parameter.html#quan-wen-shu-chu

#### 预期是什么
`https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/rthk-news/hk/greaterchina`
![image](https://user-images.githubusercontent.com/86122516/137002594-690fb46f-9912-445b-80cc-66885b0766fa.png)

#### 实际发生了什么
1. 內容沒了.......
`https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/rthk-news/hk/greaterchina.atom`
![image](https://user-images.githubusercontent.com/86122516/137002925-a84820da-2abd-4aef-8337-cae90b85efc1.png)

2. 格式丟了?.. 
`https://wft44maqb-rsshub-gnb6i.ondigitalocean.app/rthk-news/hk/greaterchina?mode=fulltext`
![image](https://user-images.githubusercontent.com/86122516/137002802-8b3bcc4f-6b45-4e8f-86fd-952d5b53226a.png)

#### 部署相关信息

digitalocean apps

![image](https://user-images.githubusercontent.com/86122516/137003277-4de30a0d-7091-479d-b0fe-82eedbdb2b0b.png)

- 额外信息（日志、报错等）

**Comment by TonyRL** [comment]
/test
```routes
/rthk-news/hk/greaterchina.atom
```

**Comment by TonyRL** [comment]
`/rthk-news/hk/greaterchina.atom` is working.
All contents parsed using the parameter `mode=full` depends on [upstream](https://github.com/postlight/mercury-parser)
