### ISSUE TITLE
預設的env

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8383]
### 这是一个什么样的功能？
預設的env

### 这个功能可以解决什么问题？
傻瓜化 對一般人來說能得到更友善、易用的使用體驗

### 额外描述
比如說.. 為了照顧生活在中國大陸的人, env預設有: `HOTLINK_TEMPLATE = https://images.weserv.nl/?url=${protocol}//${host}${pathname}&af&output=png`, 另設`HOTLINK_TEMPLATE_SWITCH`開关 且預設為`关` (当然預設為`开`会更好)

那麼要用`HOTLINK_TEMPLATE`的話就只需要把`HOTLINK_TEMPLATE_SWITCH`改成`on`?🤔

以及因為網絡環境欠佳而預設輸出全文 或把輸出全文的env設定成必要

把某些env設定為必要 這樣digitalocean apps等平台才会在安裝時顯示輸入框 方便改动

**Comment by TonyRL** [comment]
> 应该可以关闭了，demo站不应该设置这个
> 个人站点有需要可以自行参考设置
> https://github.com/DIYgod/RSSHub/commit/cde5d9af45c6e7383f48ab3ced3de60b2e310db1

_Originally posted by @NeverBehave in https://github.com/DIYgod/RSSHub/issues/2769#issuecomment-620343076_
