### ISSUE TITLE
华夏文摘

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8387]
### 网站地址
- http://www.cnd.org/
- http://hxwk.org/

### 网站描述
> 《華夏文摘》是網上最早的獨立海外華人中文媒體之一，由海外中國大陸留學生梁路平、朱若鵬、熊波、鄒孜野等人創辦於1989年3月6日，當時叫做《新聞文摘》(NEWS DIGEST) ...

### 需要生成什么内容？
~

### 额外描述
`華夏文摘 - 維基百科`: https://zh.wikipedia.org/zh-tw/%E5%8D%8E%E5%A4%8F%E6%96%87%E6%91%98

**Comment by TonyRL** [comment]
http://new.hxwk.org/feed/

[RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar) Browser extension that simplifies finding and subscribing RSS and RSSHub
