### ISSUE TITLE
豆瓣浏览发现路由失效

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#8391]
#### 路由地址（不包含参数）

https://rsshub.app/douban/explore

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/douban/explore

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#dou-ban-liu-lan-fa-xian

#### 预期是什么
正常显示
#### 实际发生了什么
Error message: this route is empty
#### 部署相关信息
自建和官方demo

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/137204526-58a3ea95-0015-4b15-b869-97c323134b02.png)

**Comment by rhhu** [comment]
发现了同样的问题，所有群组都无法打开，包括官方教程里的示例
Looks like something went wrong
Route requested: /douban/group/648102
Error message: this route is empty, please check the original site or create an issue
