### ISSUE TITLE
HeaDuck研究所

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8396]
### 网站地址
https://blog.headuck.com/

### 网站描述
小鴨幹線 https://evchk.wikia.org/zh/wiki/%E5%B0%8F%E7%86%8A%E4%BE%86%E9%9B%BB%E9%80%9A%E7%9F%A5

### 需要生成什么内容？
https://blog.headuck.com/ 近期文章

### 额外描述
- https://blog.headuck.com/2020/10/17/how-samsung-addressed-the-114-dns-issue-in-october-2020-firmware-update/
- https://blog.headuck.com/2021/02/05/%e5%b0%8f%e9%b4%a8%e5%8c%96%e8%ba%ab-amabie%ef%bc%81%e3%80%8c%e5%87%ba-duck-%e5%9a%9f%e8%a1%8c%e3%80%8d-%e9%96%8b%e6%94%be%e6%ba%90%e7%a2%bc%e7%9a%84%e8%87%aa%e9%a1%98%e5%88%b0%e8%a8%aa%e8%a8%98/

**Comment by TonyRL** [comment]
https://blog.headuck.com/feed/
