### ISSUE TITLE
请求 literotica

### ISSUE THREAD

**Issue by pikawindy** [DIYgod/RSSHub#8398]
### 网站地址
https://www.literotica.com/beta/stories/
### 网站描述
小说网站
### 需要生成什么内容？
请问能提取这网站 **EROTIC STORIES**和 **EROTIC STORY CATEGORIES** 下面的栏目吗？主要是**New Erotic Stories**，**Story Top Lists**，**Story Series**，还有 **EROTIC STORY CATEGORIES** 下面的所有。
### 额外描述

![Quicker_20211015_224445](https://user-images.githubusercontent.com/63467634/137506594-39937f97-7774-4ca7-bd78-8585664e29a6.png)

**Comment by TonyRL** [comment]
closed in https://github.com/DIYgod/RSSHub/pull/8410 and https://github.com/DIYgod/RSSHub/pull/8415
