### ISSUE TITLE
纽约时报中英对照路由失效

### ISSUE THREAD

**Issue by ellenandyoung** [DIYgod/RSSHub#8407]
#### 路由地址（不包含参数）

```routes
https://rsshub.app/nytimes/dual
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/nytimes/dual
```

#### 预期是什么

正常显示

#### 实际发生了什么

Error message: Failed to launch the browser process !

**Comment by TonyRL** [comment]
Routes using puppeteer is working again on demo instance.
