### ISSUE TITLE
大佬能添加mp4ba.com的rss源吗?这个网站最近复活了

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#843]
[mp4ba.com](mp4ba.com)
<img width="1136" alt="snipaste_2018-10-08_10-33-15" src="https://user-images.githubusercontent.com/6291329/46590417-a0dd9d80-cae5-11e8-8c34-31ba700ea82c.png">

**Comment by oklong** [comment]
订阅源：http://feed43.com/0386740036763343.xml

**Comment by SKY-rainbow-lh** [comment]
这个站不是原来的了，原来的站长几个域名全部给别人拿走了，具体原因不清楚，感觉现在的站不怎么靠谱

**Comment by pcwuyu** [comment]
> 订阅源：http://feed43.com/0386740036763343.xml

这个源不行,我订阅了,几天就给我更新了接近1k条,问题是都是重复的.

**Comment by pcwuyu** [comment]
> 这个站不是原来的了，原来的站长几个域名全部给别人拿走了，具体原因不清楚，感觉现在的站不怎么靠谱

怪不得我觉得logo啥的都换了.

**Comment by mpc2008cn** [comment]
https://feed43.com/4482344224774533.xml

**Comment by yefoenix** [comment]
已有 https://github.com/DIYgod/RSSHub/tree/master/lib/routes/mp4ba ，可以关闭了 @DIYgod
