### ISSUE TITLE
Telegram integration doesn't work or slow almost for all channels

### ISSUE THREAD

**Issue by Vadimkin** [DIYgod/RSSHub#8444]
All telegram channels fails with timeout error or very slow.

Also, [status image](https://docs.rsshub.app/en/social-media.html#telegram) doesn't work (I guess for the same reason):

![image](https://user-images.githubusercontent.com/2240404/138589746-3a98f2b7-9ab9-42e5-ad01-dfbec7640ab9.png).

My initial thoughts that it something related with slow parsing, but it looks like something wrong with networking.

- The involved route, with all required and optional parameters

Routes:
1. https://rsshub.app/telegram/channel/startupcontent
2. https://rsshub.app/telegram/channel/ctodaily

- What is expected

Telegram endpoint expected to work without any timeout error.

- What is actually happening

Timeout error for some (as I see, all except Durov's channel) telegram services.

```
curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/durov
> 0.059644

curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/startupcontent
> timeout

curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/ctodaily
> timeout
```

- Self-deployment information

I tried to recreate this issue with self-deployment service, but it works fine without any issues:

```
curl --write-out '%{time_total}' http://127.0.0.1:1200/telegram/channel/durov
> 1.016092

curl --write-out '%{time_total}' http://127.0.0.1:1200/telegram/channel/startupcontent
> 0.745072

curl --write-out '%{time_total}' http://127.0.0.1:1200/telegram/channel/ctodaily
> 0.195775
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | MacOs 12.0.1  |
| Node version       |               |
| if Docker, version | 20.10.8       |

- Additional info (logs errors etc)

**Comment by TonyRL** [comment]
You can setup your own instance as [rsshub.app](https://rsshub.app) is a shared demo.

**Comment by TonyRL** [comment]
```shell
$ curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/durov
> 0.037080
$ curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/startupcontent
> 1.297390
$ curl --write-out '%{time_total}' https://rsshub.app/telegram/channel/ctodaily
> 0.217955
```
It seems fine after https://github.com/DIYgod/RSSHub/pull/9213
