### ISSUE TITLE
epicgames RSS Error

### ISSUE THREAD

**Issue by karma-sun** [DIYgod/RSSHub#8446]
https://rsshub.app/epicgames/freegames

Route requested: /epicgames/freegames
Error message: wrong path

Path: /epicgames/freegames
Node version: v16.3.0

**Comment by karma-sun** [comment]
并未自己部署，直接访问demo站点链接https://rsshub.app/epicgames/freegames就报错，与#8254不是一回事

> 
> 
> Possible duplicate #8254

并未自己部署，直接访问demo站点链接https://rsshub.app/epicgames/freegames就报错，与#8254不是一回事

**Comment by NeverBehave** [comment]
问题是重复添加了namespace到路由中，应该很亏可以修复

**Comment by TonyRL** [comment]
https://rsshub.app/epicgames/freegames is working as of replying
