### ISSUE TITLE
Deployment on Cloudflare Pages

### ISSUE THREAD

**Issue by keane234** [DIYgod/RSSHub#8463]
### What feature is it?
Cloudflare recently release Jamstack platform call Cloudflare Pages to compete with Vercel and Netlify. 
For versatile selection, it would be good to select and provide deployment guide on Cloudflare pages
https://pages.cloudflare.com/
https://docs.rsshub.app/en/install/#deploy-to-vercel-zeit-now

### What problem does this feature solve?
Granular option to run RSSHub depend on user's enviornment

**Comment by TonyRL** [comment]
RSSHub cannot be deployed on Cloudflare Pages. But the docs site can be deployed on there. However, I guess it won't be happened anytime soon until https://community.cloudflare.com/t/324582 is solved
