### ISSUE TITLE
V2路由bug：少一根斜杠，route就无法访问

### ISSUE THREAD

**Issue by thphd** [DIYgod/RSSHub#8510]
首先感谢各位朋友对RSSHub的付出。我是2047.name的owner，最近有人跟我说2047被添加到了RSSHub，在此感谢各位网友对本站的关注。

我注意到RSSHub项目在9月中切换到了V2格式，新route要求用这种格式添加，而2047的route也是用这种新的V2格式添加的。

目前发现一个bug：

访问路径<https://rsshub.app/2047> (如 <https://docs.rsshub.app/bbs.html#_2047>所刊载) 会返回 wrong path错误, 而路径 <https://rsshub.app/2047/>就没有这个问题。v1的route均没有这个问题。

在 <https://github.com/DIYgod/RSSHub/pull/8302#issuecomment-964549096> 询问作者 @NeverBehave @nczitzk  之后，得到回应如下：

>Hi there, this might be related to a recent changes of our new standards. The namespace handling seems to break lots of stuff and we are still investigating it. If you could like to change a look at this checkout load-module middleware.

debug乃兵家常事，相信RSSHub一定能找到解决办法的。

**Comment by TonyRL** [comment]
Both `/2047` and `/2047/` works on my self-hosted instance.

![wo slash](https://user-images.githubusercontent.com/11386903/141125022-f24a1e03-9eb3-4dcb-92d6-7b8e77f2474b.png)

![w slash](https://user-images.githubusercontent.com/11386903/141125087-d68a4db9-0138-4d01-b519-5060b6bd7ff8.png)

Possible related issue #8254

**Comment by thphd** [comment]
@wft44maqb @TonyRL thank you! 这样我就确定不是代码的问题了。

刚刚又测试了一次，发现 <https://rsshub.app/2047> 和 <https://rsshub.app/2047/> 都提示wrong path，不知道怎么了。

**Comment by wft44maqb** [comment]
@thphd 官方demo站點:
![image](https://user-images.githubusercontent.com/86122516/141418730-bd3620d4-47a4-4046-8870-4d5d564a43f1.png)

但他們已經在使用最新版本的`RSSHUB`
![image](https://user-images.githubusercontent.com/86122516/141418875-68607f60-3ed4-42d9-becf-9d62d2587e43.png)

🤔🤔🤔🤔🤔🤔🤔🤔🤔

**Comment by Clackz** [comment]
手动加上.rss或者.atom貌似就没问题了
