### ISSUE TITLE
Looks like something went wrong

### ISSUE THREAD

**Issue by QingYawar** [DIYgod/RSSHub#8513]
Route requested: /uestc/sice
Error message: Failed to launch the browser process!
/root/RSSHub/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Helpful Information to provide when opening issue: 
Path: /uestc/sice
Node version: v16.3.0

**Comment by TonyRL** [comment]
Potential duplicate of https://github.com/DIYgod/RSSHub/issues/7591, https://github.com/DIYgod/RSSHub/issues/7755 and https://github.com/DIYgod/RSSHub/issues/8407

Puppeteer is not available on demo instance.

> You are encouraged to [host your own RSSHub instance](https://docs.rsshub.app/en/install/) to get a better usability.
>
> [FAQs | RSSHub](https://docs.rsshub.app/en/faq.html)

**Comment by TonyRL** [comment]
Routes using puppeteer is working again on demo instance.
