### ISSUE TITLE
喜马拉雅电台的全部路由都不能用了

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#8516]
#### 路由地址（不包含参数）

/ximalaya/album/:id/:all?
/ximalaya/album/:id/:all/:shownote?

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/ximalaya/album/299146
https://rsshub.app/ximalaya/album/39488639/0/shownote

#### 相关文档地址

- https://docs.rsshub.app/multimedia.html#xi-ma-la-ya-zhuan-ji-bu-shu-chu-shownote

#### 预期是什么
能输出条目
#### 实际发生了什么
404错误
#### 部署相关信息
官方demo和自建最新

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
![image](https://user-images.githubusercontent.com/3047708/141280415-7862d7aa-fa80-4c4b-957d-5da522f9864f.png)

**Comment by lengthmin** [comment]
@prnake 老哥有空看一下嘛

**Comment by Shane-Meng** [comment]
昨天，老路由又莫名其妙的好了

**Comment by lengthmin** [comment]
有可能是喜马拉雅官方发布了一个不兼容更新，然后又修复了哈哈哈哈哈

**Comment by Shane-Meng** [comment]
感谢 @prnake 做的修改，虽然可能没用了。感谢 @lengthmin 一直关注本路由，代表播客爱好者致谢

**Comment by ruleroller** [comment]
> 有可能是喜马拉雅官方发布了一个不兼容更新，然后又修复了哈哈哈哈哈

哈哈，我第一时间看到有pr提交上来后马上自己照着 @prnake 老哥做的改动修改了自建的，然后一个个feed再进行修改，退订了当时失效的旧的，又重新一个个订阅新的回来，今天跟我说旧的又可以用了，人生啊，着急吃到烫豆腐了。

不过经我初步验证，新版也能用旧版的ximalaya/album/XXX的方式进行订阅，感觉 pr 还是留着好，以防将来再发生这样临时不兼容的更新？但最好pr中，还是能修改一下说明，提示建议先用旧版的格式，毕竟更方便，一个个找“分类”名，可太耗费时间了。

再次感谢 @lengthmin 老哥的协调 以及 @prnake 的光速pr！
