### ISSUE TITLE
台灣 巴哈姆特電玩資訊站

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8540]
### 网站地址
https://www.gamer.com.tw/
https://forum.gamer.com.tw/
https://gnn.gamer.com.tw/

### 网站描述
> 巴哈姆特電玩資訊站是台灣的一個經營ACG主題之網路論壇與新聞網站，1996年10月28日以電子布告欄系統的形式建立，1999年11月10日網站化。網站名稱源自遊戲《Final Fantasy系列》中的龍形傳說生物「巴哈姆特」，網站標誌亦是以其在遊戲中的形象製作。 維基百科

### 需要生成什么内容？
~

### 额外描述
`巴哈姆特電玩資訊站` 維基百科: https://zh.wikipedia.org/zh-tw/%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%E9%9B%BB%E7%8E%A9%E8%B3%87%E8%A8%8A%E7%AB%99

**Comment by TonyRL** [comment]
Duplicate of https://github.com/DIYgod/RSSHub/issues/8080.

Have you ever **_SEARCHED_** before raising an issue?

> Have you ever **SEARCHED** before raising an issue?
> 
> > Generic Discuz
> > https://docs.rsshub.app/bbs.html#discuz
> > 巴哈姆特電玩資訊站
> > https://docs.rsshub.app/bbs.html#ba-ha-mu-te-dian-wan-zi-xun-zhan
> > https://docs.rsshub.app/game.html#ba-ha-mu-te-gnn-xin-wen
> > https://docs.rsshub.app/social-media.html#ba-ha-mu-te
> > Dcard
> > https://docs.rsshub.app/bbs.html#dcard
> > TapTap
> > https://docs.rsshub.app/game.html#taptap
