### ISSUE TITLE
喜马拉雅路由挂了

### ISSUE THREAD

**Issue by stefaneliu** [DIYgod/RSSHub#8544]
#### 路由地址（不包含参数）

```[routes](https://rsshub.app/ximalaya/album/39488639/0/shownote)
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
无论用rsshub.app还是自建都返回404错误。不会是官方封掉了吧？

**Comment by TonyRL** [comment]
Duplicate of https://github.com/DIYgod/RSSHub/issues/8516

**Comment by TonyRL** [comment]
closed this in https://github.com/DIYgod/RSSHub/pull/8520
