### ISSUE TITLE
區塊鏈影音平台 `Odysee`

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8555]
### 网站地址
https://odysee.com/

### 网站描述
區塊鏈影音平台 `Odysee`

### 需要生成什么内容？
~

### 额外描述
- https://www.potatomedia.co/post/7f588dfe-ede2-45e7-b777-7398d83a191c
- https://zh.wikipedia.org/zh-tw/LBRY

**Comment by TonyRL** [comment]
Please do double check before creating an issue
https://twitter.com/odyseeteam/status/1411023502459736072
