### ISSUE TITLE
订阅豆瓣广播每次更新时会拉取重复文章

### ISSUE THREAD

**Issue by Liu-Guang** [DIYgod/RSSHub#8566]
#### 路由地址（不包含参数）

douban/people/:userid/status/:routeParams

#### 完整路由地址，包含所有必选与可选参数

http://rsshub.app/douban/people/62759792/status

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#dou-ban-yong-hu-guang-bo

#### 预期是什么
只会有新文章被加入

#### 实际发生了什么
每次更新时会拉取重复的文章，导致现在已有几千条重复文章
仅有豆瓣用户广播出现此情况

**Comment by KawausoJyou** [comment]
已经修复，如果是手动部署可以更新下。Docker部署还要再等等

**Comment by Liu-Guang** [comment]
> 

大概是什么问题导致的呢

**Comment by KawausoJyou** [comment]
https://github.com/DIYgod/RSSHub/commit/a43b67bc1f6d04519c09ac04f3fce4c9e074381a

**Comment by ctrsgithub** [comment]
我这边还是更新重复诶，请问 @Liu-Guang 你那边找到办法了吗？

**Comment by KawausoJyou** [comment]
> 我这边还是更新重复诶，请问 @Liu-Guang 你那边找到办法了吗？

因为docker还没更新
