### ISSUE TITLE
Mirror RSS请求(Web 3.0的Blog)

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#8567]
### 网站地址 : 
http://mirror.xyz/

### 网站描述：
Web 3.0的Blog系统

### 需要生成什么内容？
http://mirror.xyz/对应用户下面所有博文

**Comment by fifteen42** [comment]
我可以尝试做一下这个

**Comment by lylunula** [comment]
感谢~

**Comment by lylunula** [comment]
> 我可以尝试做一下这个

感谢你的贡献，但可能是我没有表达清楚，mirror是每个用户都有不同的主页，希望是类似订阅地址有个变量是用户id，举例来说，以下几个都是不同用户的主页，是希望订阅rss有个标量就是对应的用户id，这样就可以订阅指定id的用户博文
https://mirror.xyz/gasdao.eth
https://mirror.xyz/0x4631e0eCda7a39ba951f297c65C1A6E680dc94c4
https://x.mirror.xyz/

**Comment by aturX** [comment]
类似这个吧： https://mirrorgateway.cincel.xyz/feed/

**Comment by lylunula** [comment]
> 

这个是平台全部文章的feed，但其实这个是平台性质，每个地址都是单独的blog

**Comment by lylunula** [comment]
现在已经有大佬做了一个网站用于订阅：https://submirror.xyz/，需要可以拿去用~
