### ISSUE TITLE
希望有缘人添加多维新闻网

### ISSUE THREAD

**Issue by HenryQW** [DIYgod/RSSHub#858]
http://www.dwnews.com/

挖个坑

**Comment by tgly307** [comment]
期待henry做自己的有缘人

**Comment by hillerliao** [comment]
小心被喝茶啊，别把项目搞坏了

**Comment by lychichem** [comment]
emm现在多维的图片链接没加密，然后直接就会因为连接重置显示不出来，有办法把它搞成加密连接吗？

**Comment by HenryQW** [comment]
@lychichem 应该是域名都被墙了，你确定 https 图就能显示吗？https://pic9.dwnews.net/20190226/b9367af82b855ef89141a4be155265c3_w.jpg

**Comment by lychichem** [comment]
> @lychichem 应该是域名都被墙了，你确定 https 图就能显示吗？https://pic9.dwnews.net/20190226/b9367af82b855ef89141a4be155265c3_w.jpg

可以确定，目前只是会重置未加密连接，加密之后图片（pic[1-9].dwnews.net）可以正常显示
