### ISSUE TITLE
香港大學民意研究計劃 www.pori.hk

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8586]
### 网站地址
https://www.pori.hk/

### 网站描述
> 關於我們
> 關於香港民意研究所
> 
> 香港民意研究所（下稱研究所）於二零一九年二月十九日正式註冊為有限公司，並於同年五月四日正式營運。研究所前身是香港大學民意研究計劃（下稱港大民研）。在二零一九年七月一日脫離香港大學社會科學學院後，研究所堅守作為公民社會良心企業，仿效外國著名民意機構，例如芝加哥大學的全國民意研究中心、康乃爾大學的羅普公眾輿論研究中心、劍橋大學的YouGov-Cambridge Centre和哈佛大學的甘迺迪政府政治學院及其轄下組織，繼續進行研究工作。
> 
> 研究所會積極尋找合作機構和夥伴，一同推廣和建立公民社會良心企業的形象。研究所也願意分享知識、技術和發展意念，給予志同道合的合作單位。當社會有清楚的準則去釐定何謂良心企業，研究所只會繼續與該等良心企業合作。但在此前，研究所會繼續努力闡述和探索何謂良心企業。
> 
> 關於民意研究計劃
> 
> 自一九九一年六月成立以來，研究團隊最先以香港大學民意研究計劃（港大民研）的名稱，繼而再以香港民意研究所轄下的香港民意研究計劃（香港民研）的名稱，一直向不同私人和公立機構提供高質素的調查服務。我們決志為學術界、傳媒界、政策制定者和一般市民，收集和分析在不同範疇值得他們參考的公衆意見。
> 
> 直至現在，我們已經進行了二千多項獨立調查和其他類型的研究，這些研究大多數由外來經費支付。我們的項目合作夥伴包括學者（包括來自香港，中國和海外的）、政府部門、公營機構、民間組織、專業團隊、政治團體、領先商業機構、中小企業和本地及海外的傳媒。

https://www.pori.hk/about-us.html

### 需要生成什么内容？
![image](https://user-images.githubusercontent.com/86122516/143566510-3229ce2a-7c62-4dfd-92a4-242af814333c.png)

### 额外描述
唉~

**Comment by TonyRL** [comment]
> https://www.pori.hk/
>> https://www.pori.hk/feed

[RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar) Browser extension that simplifies finding and subscribing RSS and RSSHub
