### ISSUE TITLE
瑞士资讯SWI(swissinfo.ch)翻译的法新社中文新闻

### ISSUE THREAD

**Issue by HamadaMasatoshi** [DIYgod/RSSHub#8589]
### 网站地址

https://www.swissinfo.ch/chi/afp

### 网站描述

创建于1999年的瑞士资讯SWI swissinfo.ch是瑞士广播电视集团(Swiss Broadcasting Corporation)旗下的国际服务机构，致力于提供关于瑞士的独立报道。

**该板块目前是我能检索到的唯一长期公开、稳定、免费提供法新社中文新闻的渠道。**

### 需要生成什么内容？

https://www.swissinfo.ch/chi/afp 这个页面的内容

### 额外描述

这个板块的文章没有图片，只有文字，因此希望能够全文输出。如果做不了，只有摘要也可以。

**Comment by TonyRL** [comment]
Duplicate of https://github.com/DIYgod/RSSHub/pull/8466
Fixed in #8466

**Comment by HamadaMasatoshi** [comment]
首先感谢能够制作这个路由，使用一段时间后发现两个小瑕疵，在 swissinfo.ch 英文 feed 中也同样存在

- 每篇文章的中间或者结尾，都有下面这个模块，比较影响阅读。使用者这边用广告屏蔽工具也不太好去除，不知道能否直接在  
feed 里移除？
![image](https://user-images.githubusercontent.com/77891959/144681028-f4ce38b0-e3e3-428e-b5ff-f804f5559a42.png)

> <div class="si-grid">
<article class="si-teaser si-teaser--focus beat--switzerland" data-beat="democracy" data-group="44685898">
<h2 class="show-for-sr">相关内容</h2>
<p class="si-teaser__label" aria-hidden="true">相关内容</p> <a class="si-teaser__link" href="https://www.swissinfo.ch/chi/%E6%8D%8D%E5%8D%AB%E8%A8%80%E8%AE%BA%E8%87%AA%E7%94%B1%E7%9A%84%E6%88%98%E6%96%97%E6%B0%B8%E4%B8%8D%E4%BC%91%E6%AD%A2/46613138?utm_content=o&utm_campaign=own-posts&utm_medium=display&utm_source=swissinfoch">
<div class="si-teaser__image" style="background-image: url('/resource/image/46347986/landscape_ratio3x2/640/426/93ecd08450e992bb1e73e813cf1c66c6/41E821FCF1A00BF279C8C6F2C11CDC58/11_freedom-of-expression.jpg')">
</div><div class="serie-icon"><img src="https://www.swissinfo.ch/resource/blob/46557868/75dcfb43c12bab0384cda0dab89bc9ef/ico_expression-data.png" alt="系列" referrerpolicy="no-referrer"></div><div class="si-teaser__content">
<h3 class="si-teaser__title">捍卫言论自由的战斗永不休止</h3> <p class="si-teaser__lead">
民主的一块基石正在摇摇欲坠。在世界各地，都有对保护言论自由置若罔闻的政府。而有些个人和团体则打着言论自由的旗号，宣传仇恨和歧视的的思想。在瑞士，公民针对言论自由多次做出过重要裁决。 </p>
</div>


示例链接：
https://www.swissinfo.ch/chi/巴黎奥运赞助商有阿里巴巴--法国忧资安/47163726
https://www.swissinfo.ch/chi/中国民航局批准-波音737max最快年底复飞/47163462

- 发布时间也存在重复显示的情况，希望能够移除
![image](https://user-images.githubusercontent.com/77891959/144680744-9aea5ef7-68d0-4984-a361-59de9810f772.png)

**Comment by TonyRL** [comment]
#8671
