### ISSUE TITLE
Route down: /gamer/hot/:bsn

### ISSUE THREAD

**Issue by ToffeeNeko** [DIYgod/RSSHub#8638]
#### 路由地址（不包含参数）

```routes
/gamer/hot/:bsn
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.app/gamer/hot/47157
```

#### 相关文档地址

- https://docs.rsshub.app/bbs.html#ba-ha-mu-te-dian-wan-zi-xun-zhan

#### 预期是什么
Feed

#### 实际发生了什么
Error 403

**Comment by SettingDust** [comment]
这个提示就是反爬被触发了，应该是获取原文的部分触发的

**Comment by ToffeeNeko** [comment]
啊这。。目前情况还有救吗😅
