### ISSUE TITLE
希望增加爱范儿的其他的栏目的rss

### ISSUE THREAD

**Issue by pipiepig** [DIYgod/RSSHub#864]
玩物志：https://www.ifanr.com/coolbuy
知晓程序 文章：https://minapp.com/article
董车会：https://www.ifanr.com/category/intelligentcar

**Comment by HenryQW** [comment]
知晓程序和主站不一样，改天再写。

**Comment by pipiepig** [comment]
再加一个主站上的每日早报吧

**Comment by HenryQW** [comment]
支持主站所有栏目，自行阅读文档

**Comment by DIYgod** [comment]
Done. b12b9ee20181bfe83c13015551e3b12b7b8de2c8
