### ISSUE TITLE
人民网的路由坏了

### ISSUE THREAD

**Issue by kut2tjjj** [DIYgod/RSSHub#8648]
### 路由地址

/people/env/

### 完整路由地址

https://rsshub.app/people/env/74877

### 相关文档

docs.rsshub.app

### 预期是什么？

环保频道

### 实际发生了什么？

使用https://rsshub.app域名时页面显示:
Looks like something went wrong
Route requested: /people/opinion/223228
Error message: Cannot read property 'trim' of null
但是某些第三方域名如https://rss.shab.fun/可以正常访问。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: Cannot read property 'trim' of null
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by guangwenzhu** [comment]
人民网环保频道官方源 http://www.people.com.cn/rss/env.xml
其他频道订阅源见 http://www.people.com.cn/rss/opml.xml
