### ISSUE TITLE
Unable to follow certain Twitter users on rsshub.app

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub#8650]
### Routes

https://rsshub.app/twitter/user/linusgsebastian

### Full routes

https://rsshub.app/twitter/user/linusgsebastian

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter

### What is expected?

For Twitter feed to display.

### What is actually happening?

Error message: Unable to verify your credentials

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
This happens with this one as well:
https://rsshub.app/twitter/user/Anjyoun

While this one works just fine:
https://rsshub.app/twitter/user/LinusTech
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
All of the three Twitter users feed work fine at the time of replying.

<details>

<summary>linusgsebastian</summary>

![image](https://user-images.githubusercontent.com/11386903/144631236-f025577e-91d1-4557-ada9-7f2475bb3fdc.png)

</details>
<details>

<summary>Anjyoun</summary>

![image](https://user-images.githubusercontent.com/11386903/144631276-f700af3b-7775-45e6-85e0-5b1a749a0349.png)

</details>
<details>

<summary>LinusTech</summary>

![image](https://user-images.githubusercontent.com/11386903/144631336-c5cc340f-ca38-4e9d-9796-e4c08f1d73f2.png)

</details>

**Comment by justaghostly1** [comment]
The issue still exists, here are a few that still have it happen as of right now:

https://rsshub.app/twitter/user/Anjyoun
https://rsshub.app/twitter/user/roseonlinemmo

![rsshub-twitter-unable-to-verify-your-credentials](https://user-images.githubusercontent.com/96978769/147874099-2c0fdc81-34c5-4266-91dc-2f264e5f5adc.png)
