### ISSUE TITLE
学习强国

### ISSUE THREAD

**Issue by chaixuqing** [DIYgod/RSSHub#8654]
### 类型

新媒体

### 网站地址

https://www.xuexi.cn/98d5ae483720f701144e4dabf99a4a34/5957f69bffab66811b99940516ec8784.html

### 网站描述

“学习强国”学习平台是由中共中央宣传部主管，以习近平新时代中国特色社会主义思想和党的十九大精神为主要内容，立足全体党员、面向全社会的优质平台。

### 需要生成什么内容？

主页所有新内容的推送

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by wft44maqb** [comment]
...

**Comment by wft44maqb** [comment]
這個到底是不是高級黑？你們有誰能告訴我嗎？哈哈！
