### ISSUE TITLE
恳请大佬加入煎蛋-热榜-妹子图的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#867]
如题，http://jandan.net/top-ooxx 。
平常都用着按oo数量来排序的脚本，现在rsshub上只有妹子图和无聊图（由于只是按上传的时间顺序，我更期待看到热榜），所以恳请大佬加入热榜-妹子图。
（用feed43也第一次遇到根本没有图片地址的情况，笑尿，完全不懂这么弄）

**Comment by xyqfer** [comment]
Done. 6dee8af7098dc44c7f43ee1a9bcf2f5a76199ff3

**Comment by ayucapal** [comment]
顺带恳请dalao增加 4小时热门 
http://jandan.net/top-4h
和无聊图热榜
http://jandan.net/top

**Comment by tomatomash** [comment]
令人遗憾的事情是，妹子图被关闭了，RIP

**Comment by ruich97** [comment]
@tomatomash 红红火火恍恍惚惚
