### ISSUE TITLE
/RSSHub下出现一堆core dump文件,占满磁盘空间

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#8683]
### 路由地址

NONE

### 完整路由地址

none

### 相关文档

none

### 预期是什么？

正常工作不会吞噬磁盘空间

### 实际发生了什么？

/RSSHub下出现core.一串数字 此类文件，直到占满磁盘空间，和此问题现象雷同 /issues/7622  ，原因未知

### 部署

自建

### 部署相关信息

Linux，Nodejs 14.18.1，yarn 1.22.15

### 额外信息

```shell
一个CORE文件的大小是299M
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
Git Hash: b5be05b

**Comment by KwToPA** [comment]
我用 ls -XSsh 发现的，看频率应该是某个RSS源抓一次会触发生成一个 CORE.一串数字 文件，请教如何确认是何RSS源？谢谢

**Comment by TonyRL** [comment]
What route(s) you have subscribed? Are you using puppeteer with bundled chrome or browserless?

**Comment by KwToPA** [comment]
@TonyRL 刚刚检查了一次，没有出现 CORE.NUMBER 文件，之前更新过几次RSSHUB，或许已经修复。过几天我在检查看看。

**Comment by KwToPA** [comment]
@TonyRL  Too  many. How can I figure out the feeds that create the core file? Error is still the same.  
```
384M Feb  8 15:10 core.20945
383M Feb  8 13:05 core.23960
382M Feb  8 16:10 core.3472
378M Feb  8 14:08 core.5761
383M Feb  8 12:04 core.9530
```
My update command 
```
git clone https://github.com/DIYgod/RSSHub.git;
yarn ;
```

my yarn version
```
yarn --version
1.22.15
```

npm version
```
npm version
{
  rsshub: '1.0.0',
  npm: '8.1.4',
  node: '14.18.1',
  v8: '8.4.371.23-node.84',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.4',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

the file under /RSSHub/node_modules/puppeteer
```
CHANGELOG.md  cjs-entry-core.js  cjs-entry.js  install.js  lib  LICENSE  node_modules  package.json  README.md  typescript-if-required.js
```

the file under /RSSHub/node_modules/puppeteer/lib
```
cjs  esm  types.d.ts
```

the file under /RSSHub/node_modules/puppeteer/node_modules
```
debug  ms  node-fetch  rimraf  tr46  webidl-conversions  whatwg-url
```
How can I find chrome is bundled or browserless?

**Comment by TonyRL** [comment]
If you do not have `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true` set or `PUPPETEER_WS_ENDPOINT` is not set then you're using puppeteer's bundled chrome.
Currently, these rotues are using puppeteer:
```
/prestige-av
/pincong
/ncwu/notice
/xiaohongshu
/njust
/nuaa
/nju
/apnews
/pbc
/ccac
/uestc

```

**Comment by KwToPA** [comment]
```
cat /RSSHub/lib/config.js | grep puppeteer
        puppeteerWSEndpoint: envs.PUPPETEER_WS_ENDPOINT,

cat /RSSHub/docker-compose.yml  | grep puppeteer

nothing happened
```

And I do NOT subscribe any feed you mentioned.

**Comment by yindaheng98** [comment]
#7624
