### ISSUE TITLE
怎么输出日志？

### ISSUE THREAD

**Issue by iferencz** [DIYgod/RSSHub#8687]
### 这是一个什么样的功能？

翻遍了issue，也百度谷歌了。怎么查看`console.log();`输出的内容？
例如[https://github.com/DIYgod/RSSHub/blob/d82847f5410676635f8766681dcb642d7b3f8aa4/lib/routes/ipsw/index.js](https://github.com/DIYgod/RSSHub/blob/d82847f5410676635f8766681dcb642d7b3f8aa4/lib/routes/ipsw/index.js)中所注释的`console.log();`，我访问路由地址，在控制台看不到呀？

### 这个功能可以解决什么问题？

帮助调试

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Fatpandac** [comment]
我可以看到呀，就在终端

**Comment by iferencz** [comment]
暂未解决

**Comment by iferencz** [comment]
> 暂未解决

原因：没有已开发模式运行
