### ISSUE TITLE
希望chrome浏览器插件rsshub radar一键订阅增加ego reader

### ISSUE THREAD

**Issue by pxz666** [DIYgod/RSSHub#8727]
### 这是一个什么样的功能？

增加一键订阅支持的软件

### 这个功能可以解决什么问题？

让ego reader可以实现一键订阅功能，免除复制操作

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please create the issue in respective repository [DIYgod/RSSHub-Radar](https://github.com/DIYgod/RSSHub-Radar).
