### ISSUE TITLE
豆瓣一周口碑榜不可访问

### ISSUE THREAD

**Issue by JaminYe** [DIYgod/RSSHub#8732]
### Routes

/douban/movie/weekly/:type?

### Full routes

/douban/movie/weekly/tv_weekly_best

### Related documentation

https://docs.rsshub.app/social-media.html#dou-ban

### What is expected?

正常返回rss信息

### What is actually happening?

Route requested: /douban/movie/weekly/tv_weekly_best
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /douban/movie/weekly/tv_weekly_best
Node version: v16.3.0

### Deployment information

Self-hosted

### Additional info

```shell
Route requested: /douban/movie/weekly/tv_weekly_best
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /douban/movie/weekly/tv_weekly_best
Node version: v16.3.0
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Fatpandac** [comment]
这个榜好像**不存在**了，
https://m.douban.com/subject_collection/tv_weekly_best
如果你有他现在的网址麻烦分享一下。

**Comment by NeverBehave** [comment]
不存在就把对应路由删掉吧

**Comment by Fatpandac** [comment]
好的 👌🏻

**Comment by JaminYe** [comment]
close
