### ISSUE TITLE
COCOMANGA

### ISSUE THREAD

**Issue by gao-shi** [DIYgod/RSSHub#8751]
### 类型

二次元

### 网站地址

https://www.cocomanga.com/

### 网站描述

漫画网站，主要为国漫

### 需要生成什么内容？

漫画更新通知，如一人之下：
https://www.cocomanga.com/10263/

### 额外描述

感谢各位大佬

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Closing in favour of https://github.com/DIYgod/RSSHub/issues/11692
