### ISSUE TITLE
包子漫画RSS

### ISSUE THREAD

**Issue by gao-shi** [DIYgod/RSSHub#8752]
### 类型

二次元

### 网站地址

https://www.baozimh.com/

### 网站描述

漫画网站，主要是国漫

### 需要生成什么内容？

漫画更新通知，如一人之下：
https://www.baozimh.com/comic/yirenzhixia-dongmantang

### 额外描述

感谢各位大佬

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by 13653042750** [comment]
很好用，希望可以坚持下去

**Comment by cxheng315** [comment]
包子漫畫的 rss 缺少了 `<pubDate>` 的 tag
一般 rss : https://rsshub.app/blockbeats/flash

```ruby
<item>
<title>
<![CDATA[ 美国国会或在年底前签署《数字商品消费者保护法》 ]]>
</title>
<description>
<![CDATA[ 美国国会或在年底前签署《数字商品消费者保护法》 ]]>
</description>
<pubDate>Sun, 23 Oct 2022 04:18:52 GMT</pubDate>
<guid isPermaLink="false">https://www.theblockbeats.info/flash/110185</guid>
<link>https://www.theblockbeats.info/flash/110185</link>
</item>
```


包子漫畫的 rss : https://rsshub.app/baozimh/comic/zhuangbeiwozuiqiang-teamargomonohumbugredicestudiosaenalredicestudio_ak

```ruby
<item>
<title>
<![CDATA[ 143 制鑰者 ]]>
</title>
<description>
<![CDATA[ 143 制鑰者 ]]>
</description>
<guid isPermaLink="false">https://www.baozimh.com/user/page_direct?comic_id=zhuangbeiwozuiqiang-teamargomonohumbugredicestudiosaenalredicestudio_ak&section_slot=0&chapter_slot=143</guid>
<link>https://www.baozimh.com/user/page_direct?comic_id=zhuangbeiwozuiqiang-teamargomonohumbugredicestudiosaenalredicestudio_ak&section_slot=0&chapter_slot=143</link>
</item>
```
