### ISSUE TITLE
澳門消費者委員會

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#8753]
### 类型

其他

### 网站地址

https://www.consumer.gov.mo/News/Public.aspx?lang=zh

### 网站描述

> 消費者委員會是澳門特別行政區的政府部門，由經濟財政司監督，主要負責保障澳門及來自各地的所有消費者權益。 消委會的主要工作，包括測試市面上各種產品的安全程度和質素，處理消費者對店舖的投訴，向市民提供產品及服務資訊，並透過各類宣傳教育消費者，使消費者知道自己應有的權利及懂得保障自己的權益。

> 澳門消費者委員會是澳門特別行政區的政府部門，由經濟財政司所監督，對政府將訂定之保護消費者政策發表意見，並推動各項保護消費者之工作。澳門消費者委員會的主要工作，包括測試市面上各種產品的安全程度和質素，處理消費者對店舖的投訴，向市民提供產品及服務資訊。本會網站提供加盟商號誠信店、消委會公佈最新超市物價調查報告、澳門消費、消費提示等各類資訊，消費者也可使用在線投訴諮詢,本會亦設有手機應用程式下載給消費者使用。

### 需要生成什么内容？

~

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by Fatpandac** [comment]
官方 RSS
https://www.consumer.gov.mo/News/rss.aspx?lang=zh
