### ISSUE TITLE
telegram频道抓取无法抓取，频道链接能访问

### ISSUE THREAD

**Issue by ChirmyRam** [DIYgod/RSSHub#8766]
### 路由地址

https://t.me/MSEdgeUpdates

### 完整路由地址

https://rsshub.app/telegram/channel/MSEdgeUpdates

### 相关文档

https://docs.rsshub.app/social-media.html#telegram

### 预期是什么？

抓取成功

### 实际发生了什么？

无法抓取

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /telegram/channel/MSEdgeUpdates
Error message: Unable to fetch message feed from this channel. Please check this URL to see if you can view the message preview: https://t.me/s/MSEdgeUpdates
Helpful Information to provide when opening issue: 
Path: /telegram/channel/MSEdgeUpdates
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
RTFM.

>**TIP**
>
>Due to Telegram restrictions, some channels involving pornography, copyright, and politics cannot be subscribed. You can confirm by visiting https://t.me/s/:username.

> **提示**
> 
> 由于 Telegram 限制，部分涉及色情、版权、政治的频道无法订阅，可通过访问 https://t.me/s/:username (opens new window)确认。

`MSEdgeUpdates` is restricted. https://t.me/s/MSEdgeUpdates is not available.

Channels that are available like `awesomeDIYgod` in docs have a different view on https://t.me/s/awesomeDIYgod.

**Comment by ChirmyRam** [comment]
> RTFL.
> 
> > Error message: Unable to fetch message feed from this channel. **Please check this URL to see if you can view the message preview: https://t.me/s/MSEdgeUpdates**
> 
> RTFM. For the docs link you have provided
> 
> > **提示**
> > 由于 Telegram 限制，部分涉及色情、版权、政治的频道无法订阅，可通过访问 https://t.me/s/:username (opens new window)确认。
> 
> `MSEdgeUpdates` is restricted. https://t.me/s/MSEdgeUpdates is not available.
> 
> Channels that are available like `awesomeDIYgod` in docs have message previews on https://t.me/s/awesomeDIYgod.

了解，谢谢。
