### ISSUE TITLE
能否添加一个抖音网页版的抖音号视频的抓取

### ISSUE THREAD

**Issue by zwb124** [DIYgod/RSSHub#8770]
### 类型

音视频

### 网站地址

https://www.douyin.com/user/MS4wLjABAAAA_M54dBbTHVPncnFVJVrN6VJXM9v2HBhVna1iN4AqUN2qudL4PBgCKiyExhvWZxcn

### 网站描述

短视频网站

### 需要生成什么内容？

目前网页版已经很完善了，我觉得完全可以直接抓取，感谢

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nokaka** [comment]
附议附议

**Comment by Rongronggg9** [comment]
Duplicate of #7834
