### ISSUE TITLE
台灣和香港的新聞網站

### ISSUE THREAD

**Issue by ufo1024k** [DIYgod/RSSHub#8784]
### Category

News

### Website URL

https://hk.on.cc/hk/news/index.html
### Website description

台灣和香港的新聞網站

### What content should be included?

即時新聞推送

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by wft44maqb** [comment]
... 你上面舉的都是....... 親共藍媒.... (不是親中, **親共**)

台湾tvbs --> htc --> 有中國業務 + `TVBS多名高層亦曾出席「兩岸媒體人北京峰會」。` --> 親共...

香港on.cc --> 某節目主節目主持人一直說`「中國台灣 中國台灣..」`.................

台湾udn --> `聯合報`旗下 --> `聯合報創辦人王惕吾為國民黨黨員，聯合報立場偏向國民黨。聯合報多名高層亦曾參與「兩岸媒體人北京峰會」。`................. (但`udn國际`曾是台湾公視p#推廌的`優質媒體`)

香港tvb............ 大家都知道的.... 

> 其新聞報道在2000年代中後期起在沒有明顯證據支撐的情況下，被與該台立場相左的一部分親民主派及其支持者認為偏袒香港政府及建制派，並遭到民主派及其支持者的反對，續引發更多不同爭議。

具體都有哪些爭議請自行google...........

**Comment by wft44maqb** [comment]
親中沒問題 內容不要跟中時一樣.. 不要瞞報 虛報啥的就行 udn我也还有在看...~

**Comment by wft44maqb** [comment]
udn有了?

![image](https://user-images.githubusercontent.com/86122516/147625436-e4f747a7-dba9-4632-a229-d9eb3d786fe6.png)

**Comment by wft44maqb** [comment]
你们许多人都是一样的，你们知道如何访问互联网，我是说真正的互联网，但你们仍然用老方法思考。(墙内那一套....)

![image](https://user-images.githubusercontent.com/86122516/147625749-f6b95919-2eb0-441e-a68f-3ce2f25dae7a.png)

**Comment by Fatpandac** [comment]
网站有点多，可以拆开吗？
建议，一个网站开一个 issue 吧。

**Comment by JanWhite** [comment]
> 親中沒問題 內容不要跟中時一樣.. 不要瞞報 虛報啥的就行 udn我也还有在看...~
> 
> 但很明显tvb瞞報 虛報 兩样都整了... 1000%的明显.............

所以呢...端新闻照样只报道一半的东西也不是有...人家提需求你觉得不做就不做...非要跳出批判一番看不懂

**Comment by wft44maqb** [comment]
> 所以呢...

沒事~ 有感而發而已~ 😑

**Comment by wft44maqb** [comment]
![image](https://user-images.githubusercontent.com/86122516/147796566-09804def-d94f-4f8e-a5cd-194c28663ecf.png)

這个適合您😊😉

**Comment by JanWhite** [comment]
> > 所以呢...
> 
> 沒事~ 有感而發而已~ 😑 @JanWhite

他急了，急了

**Comment by wft44maqb** [comment]
您可以参考一下。 @JanWhite 

# 彭帅指控张高丽性丑闻事件

东方传媒:
![image](https://user-images.githubusercontent.com/86122516/147841545-c7530236-5297-4568-b89e-540f17ace28a.png)

谈论中国时比较保守的新加坡官媒:
![image](https://user-images.githubusercontent.com/86122516/147841567-d3cc96de-e5fc-4073-8c0d-b80481ea993a.png)

曾经激进，现在非常保守的香港公视rthk:
![image](https://user-images.githubusercontent.com/86122516/147841594-1b71760e-ecbe-4e07-b9f1-0c334883b933.png)

维基百科: https://zh.wikipedia.org/zh-hans/%E5%BD%AD%E5%B8%A5%E6%8C%87%E6%8E%A7%E5%BC%B5%E9%AB%98%E9%BA%97%E6%80%A7%E9%86%9C%E8%81%9E%E4%BA%8B%E4%BB%B6

补充:
|  | 东方传媒 | 新加坡官媒 | rthk |
|--|--|--|--|
|彭帅事件|❌|✔️|✔️|
|彭帅事件 + 彭帅|❌|✔️|✔️|
|彭帅事件 + 彭帅 + 张高丽|❌|✔️|❌|


# 威尔逊·爱德华兹虚假新闻事件

东方传媒:
![image](https://user-images.githubusercontent.com/86122516/147841683-8e045ebc-05cc-4868-8d81-c48514f5e620.png)

新加坡官媒:
![image](https://user-images.githubusercontent.com/86122516/147841692-e595f671-c582-4e2d-bba3-8513e197d0d5.png)

香港公视rthk:
![image](https://user-images.githubusercontent.com/86122516/147841699-bf2ce58b-1474-4b99-975f-e9117de557b5.png)

维基百科: https://zh.wikipedia.org/zh-hans/%E5%A8%81%E7%88%BE%E9%81%9C%C2%B7%E6%84%9B%E5%BE%B7%E8%8F%AF%E8%8C%B2%E8%99%9B%E5%81%87%E6%96%B0%E8%81%9E%E4%BA%8B%E4%BB%B6
