### ISSUE TITLE
某些微博账号抓不到最新条目

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#8798]
### 路由地址

https://rsshub.app/weibo/user/

### 完整路由地址

https://rsshub.app/weibo/user/2239792910

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

### 预期是什么？

能够抓到最新的条目

### 实际发生了什么？

无法抓到最新的条目，以微博2239792910 为例子，能够抓到的最新一条是[https://weibo.com/2239792910/L8kibtMjw](https://weibo.com/2239792910/L8kibtMjw)，<pubDate>Wed, 29 Dec 2021 12:55:14 GMT</pubDate>

而账号的最新一条是 [https://weibo.com/2239792910/L8tJr3kQ0](https://weibo.com/2239792910/L8tJr3kQ0)，21-12-30 20:57

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自建和RSSHub 均出现该问题
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #8336

**Comment by KwToPA** [comment]
@BruceZhang1993 您好，请问 #8633 目前是否合并成功？  我用人民日报 2803301701 测试 发现还是漏了第一条

**Comment by BruceZhang1993** [comment]
@KwToPA 合并是成功的

**Comment by KwToPA** [comment]
@BruceZhang1993 
我想咨询下，[https://rsshub.app/weibo/user/2803301701](https://rsshub.app/weibo/user/2803301701) 
![image](https://user-images.githubusercontent.com/16444568/149606241-57dca2f0-9f86-4070-b03c-0434f9d392f6.png)

和我自建的 
![image](https://user-images.githubusercontent.com/16444568/149606278-c357640d-94db-4162-a9e9-9a1043ce7c73.png)

都不是最新的一条 [https://weibo.com/2803301701/LaQq7pUGg](https://weibo.com/2803301701/LaQq7pUGg) ，最新和第二新的发布时间差了28分钟，我自建的设置成15分钟抓一次。

刚刚更新了RSSHUB ，在TTRSS的对应路由Feed Debugger界面 勾选了 Force refetch和Force rehash，跑了一次，还是抓不到最新的一条。

又在TTRSS上查了一遍，发现最迟的一条差了20个小时，即20小时前作者发布微博，我用自建的RSSHUB+ttrss 20小时后才推送，TTRSS上设置的是15分钟抓一次

是我哪里设置的不对吗？  感谢，感谢

**Comment by BruceZhang1993** [comment]
@KwToPA #8633 目前还没有合并到仓库，你得在你的分支上

**Comment by KwToPA** [comment]
> @KwToPA #8633 目前还没有合并到仓库，你得在你的分支上捡一下这个 commit [`d6c3e34` (#8633)](https://github.com/DIYgod/RSSHub/pull/8633/commits/d6c3e34d17f56bdaf9e25fabb8a5365d97bea7e0)

我是直接 git clone RSSHub没有分支，如果我把微博对应的weibo/user.js 文件替换成 [https://github.com/DIYgod/RSSHub/blob/d6c3e34d17f56bdaf9e25fabb8a5365d97bea7e0/lib/routes/weibo/user.js#L77](https://github.com/DIYgod/RSSHub/blob/d6c3e34d17f56bdaf9e25fabb8a5365d97bea7e0/lib/routes/weibo/user.js#L77) 再编译  就OK了吧？效果相当于合并

**Comment by TonyRL** [comment]
Fixed in https://github.com/DIYgod/RSSHub/commit/2a03a4cf6d844b00993b15a652443de8f4218a5e
