### ISSUE TITLE
请问是否会考虑增加开发者头条和CSDN极客？

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#88]
您好：
RSSHub功能太好用了，配合TT-RSS没话说了。请问是否会考虑增加开发者头条和CSDN极客？谢谢。

CSDN极客，网址：http://geek.csdn.net/

开发者头条，网址：https://toutiao.io

**Comment by jjeejj** [comment]
@ccinoo  
CSDN极客 已经关闭了 ，其对应的blog有RSS
![xnip2018-05-127_10-05-04](https://user-images.githubusercontent.com/15176971/39681673-45f34102-51de-11e8-8ec2-a8aec333fea0.jpg)

开发者头条 有用，可以添加。会慢慢的加上哈。

哈哈，会不会抢作者  @DIYgod  的饭碗了 :smile:

**Comment by ccinoo** [comment]
@jjeejj 不会啊，做大做强对大家都好。期待这个新功能。
