### ISSUE TITLE
日本经济新闻中文版

### ISSUE THREAD

**Issue by HamadaMasatoshi** [DIYgod/RSSHub#8800]
### 类型

传统媒体

### 网站地址

https://cn.nikkei.com/

### 网站描述

《日本经济新闻》（日语：日本経済新聞／にほんけいざいしんぶん Nihon keizai shinbun */?），简称《日经》（日経／にっけい Nikkei）或《日经新闻》（日経新聞／にっけいしんぶん Nikkei shinbun），是日本一份以刊载经济相关新闻为主的全国性报纸，为日本五大报之一（读卖、朝日、每日、日经、产经），创刊于1876年12月2日。出版该报的日本经济新闻社，亦负责算出东京证券交易所的日经平均指数（Nikkei 225），是全球主要的股市指标之一。
《日本经济新闻》以财经新闻为主，也是日本公认在政治、经济方面相对权威，政治派系色彩较淡的报纸，被认为属于中间派。该报反对日本首相参拜靖国神社[5]。相较日本其他媒体，《日本经济新闻》更关注中国快速增长的经济状况。日本经济新闻社在中国设有4处支局，分别是：北京、上海、重庆、广州。

### 需要生成什么内容？

官方提供 RSS ，但是较长的文章都是分页显示，导致一般的 RSS 软件或者在线 RSS 服务的获取全文功能只能提取第一页的内容，例如[《2021年的半导体：采购难、招商热》](https://cn.nikkei.com/industry/itelectric-appliance/47170-2021-12-30-09-46-16.html)

但是通过官方提供的打印功能，是可以让全文在[一个页面显示的](https://cn.nikkei.com/industry/itelectric-appliance/47170-2021-12-30-09-46-16.html?tmpl=component&print=1&page=)，不清楚能否通过这个方式制作全文输出的RSS源。

![image](https://user-images.githubusercontent.com/77891959/147793158-28dea9cc-9b85-4ce1-b4fc-7054af08d191.png)

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by HamadaMasatoshi** [comment]
@nczitzk 感谢那么快制作出来，但是跟官方源对比起来，遗漏的似乎有些多？

https://rsshub-git-fork-nczitzk-feature-nikkei-diy.vercel.app/nikkei-cn
![image](https://user-images.githubusercontent.com/77891959/147810973-c618754e-4166-49d2-88a3-5aa17ca74220.png)

https://cn.nikkei.com/rss.html
![image](https://user-images.githubusercontent.com/77891959/147811083-98737ce8-56c7-4f5e-bb32-e804e973b5ad.png)

以上标黄的是遗漏的部分，能否直接在官方源的基础上输出全文呢？如一开始提到的，利用官方的打印功能来解决分页的文章无法获取完整内容的问题

**Comment by Fatpandac** [comment]
确实没有拿到文章第二页及以上的内容
我看了一下在 **文章链接** 后面加上 `?print=1` 就可以拿到文章全部内容了

**Comment by Fatpandac** [comment]
似乎没有拿到第二页及以上的内容而是重复了第一页的内容？

我自己试了以下在 **文章链接** 后面加上 `?print=1` 就可以拿到全文内容

**Comment by HamadaMasatoshi** [comment]
@Fatpandac 全文输出问题已解决，限制的问题是 rsshub 这里对比官方源遗漏了不少文章

**Comment by Fatpandac** [comment]
@HamadaMasatoshi  在[中国经济](https://cn.nikkei.com/china/ceconomy.html)的栏目中的[霍华德·马克斯：没有理由不投资中国](https://cn.nikkei.com/columnviewpoint/viewpoint/46486-2021-10-29-05-05-00.html)是有两页内容的，在生成中的 [rss](https://rsshub-git-fork-nczitzk-feature-nikkei-diy.vercel.app/nikkei-cn/cn/china/ceconomy) 并没有第二页内容而是重复了第一页的内容（有可能是个例吧）
![image](https://user-images.githubusercontent.com/30423976/147815050-bcc40088-a942-4f94-bb6a-e8e22482d4f1.png)

**Comment by nczitzk** [comment]
> @nczitzk 感谢那么快制作出来，但是跟官方源对比起来，遗漏的似乎有些多？
> 
> 以上标黄的是遗漏的部分，能否直接在官方源的基础上输出全文呢？如一开始提到的，利用官方的打印功能来解决分页的文章无法获取完整内容的问题

抱歉，一开始没有注意到你已经提到了使用打印文章的功能获取全文，现在已经修改成用此方法获取全文 😅

该路由默认无参数获取的是 [首页](https://cn.nikkei.com) 的文章，并且支持传入 limit 参数来指定获取的数目，理论上应该是比 [官方 RSS 源](https://cn.nikkei.com/rss.html) 内容更为丰富（官方 RSS 源一次性只能推送 10 篇）。但是正如你指出的标黄的部分，官方 RSS 源更新的内容一部分没有在首页上体现。于是我决定增加一个分类用于获取官方 RSS 推送的文章，同时保留了首页的路由。

现在，将 `category` 参数指定为 `rss`，即 [`/nikkei-cn/zh/rss`](https://rsshub-git-fork-nczitzk-feature-nikkei-diy.vercel.app/nikkei-cn/zh/rss)，就可以实现直接在官方 RSS 源的基础上输出全文 👌

**Comment by nczitzk** [comment]
> @HamadaMasatoshi 在[中国经济](https://cn.nikkei.com/china/ceconomy.html)的栏目中的[霍华德·马克斯：没有理由不投资中国](https://cn.nikkei.com/columnviewpoint/viewpoint/46486-2021-10-29-05-05-00.html)是有两页内容的，在生成中的 [rss](https://rsshub-git-fork-nczitzk-feature-nikkei-diy.vercel.app/nikkei-cn/cn/china/ceconomy) 并没有第二页内容而是重复了第一页的内容（有可能是个例吧）

谢谢反馈，修改了实现方式后，现在应不会出现这样的情形 🤝

**Comment by HamadaMasatoshi** [comment]
@nczitzk 感谢，添加新的参数就能解决这个问题了

**Comment by rainrdx** [comment]
我测试了一下日经的rss.html需要设置user-agent才能访问。没有user-agent的时候会不定期阻断。
