### ISSUE TITLE
今日热榜tophub被无意删除

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#8813]
### 路由地址

 https://rsshub.app/tophub/

### 完整路由地址

https://rsshub.app/tophub/:id

### 相关文档

https://docs.rsshub.app/new-media.html#jin-ri-re-bang

### 预期是什么？

今日热榜能正常使用

### 实际发生了什么？

https://tophub.today/ 原始网站一切正常，但rsshub却有人删除了rsshub代码

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: this route is empty, please check the original site or create an issue
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
可以提供一下您现在所处的 commit hash 值吗？

我在当前的 master 分支可以看到该 route 并没有被无意删除
还有可能是被反爬了，我在[我自建](https://rss.fatpandac.tk/tophub/mproPpoq6O)的测试是可以获取的

**Comment by geerda123** [comment]
> 可以提供一下您现在所处的 commit hash 值吗？
> 
> 我在当前的 master 分支可以看到该 route 并没有被无意删除 还有可能是被反爬了，我在[我自建](https://rss.fatpandac.tk/tophub/mproPpoq6O)的测试是可以获取的

我改成自建了，没有问题了，原来是rsshub官方链接删除，比如https://rsshub.app/tophub/NKGoRAzel6. 请问下你是怎么处理 {您访问的链接来自「今日热榜」，请从今日热榜官方访问，谢谢！}链接跳转问题的，谢谢！

**Comment by Fatpandac** [comment]
@geerda123 
不好意思，这个路由不是我写的，这个问题我无法回答。
