### ISSUE TITLE
希望增加微信公众平台-系统公告栏目rss

### ISSUE THREAD

**Issue by hillerliao** [DIYgod/RSSHub#883]
https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncementlist&lang=zh_CN&token=

**Comment by xyqfer** [comment]
@hillerliao 需要输出全文吗？

**Comment by hillerliao** [comment]
@xyqfer 有的话最好了

**Comment by DIYgod** [comment]
Done. 9dd63f19ffb5bd0df91a55eb3b5fc77446bea925
