### ISSUE TITLE
t66y提示Error message: Cannot read property 'splice' of undefined

### ISSUE THREAD

**Issue by fengixng** [DIYgod/RSSHub#8855]
### 路由地址

/t66y/25

### 完整路由地址

/t66y/25

### 相关文档

https://docs.rsshub.app/multimedia.html#cao-liu-she-qu

### 预期是什么？

预期正确输出

### 实际发生了什么？

更新前输出乱码，更新后打开提醒

### 部署

自建

### 部署相关信息

heroku

### 额外信息

```shell
Error message: Cannot read property 'splice' of undefined
Helpful Information to provide when opening issue: 
Path: /t66y/25
Node version: v14.18.2
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
#8763 已处理

**Comment by TonyRL** [comment]
Duplicate of #8758 and #8645

> 这不是重复的 issue
>
> 我已经搜索了现有 issue，以确保该错误尚未被报告。

You lie. You didn’t search before submitting this issue.
