### ISSUE TITLE
[RSS需求]链新闻abmedia

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#8861]
### 类型

新媒体

### 网站地址

https://www.abmedia.io/

### 网站描述

链新闻是关于区块链相关时事的网站

### 需要生成什么内容？

需要抓取最新时事专栏下面文章，建议是直接合成一个feed就行，主要更新还是在产品技术专栏上，其他更新不多。另外麻烦选择简体中文来抓取。

https://www.abmedia.io/category/****
包含：
产品技术：https://www.abmedia.io/category/technology-development
商业应用：https://www.abmedia.io/category/business-application
政策监理：https://www.abmedia.io/category/regulation
人物观点：https://www.abmedia.io/category/people
资讯安全：https://www.abmedia.io/category/security
CBDC：https://www.abmedia.io/category/cbdc
Libra：https://www.abmedia.io/category/libra
活动资讯：https://www.abmedia.io/category/event

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by lylunula** [comment]
感谢~

**Comment by lylunula** [comment]
@ Fatpandac 感谢，但是我试了下，发现1.是繁体，能不能切换成简体；2.能不能合并在一个feed里面，如果不行，那麻烦能不能直接爬取首页的最新更新新闻，做成一个feed，如下图位置
![image](https://user-images.githubusercontent.com/2727281/149269446-872cdc2c-efe3-4a5f-b8dd-ee34137b5a02.png)

**Comment by Fatpandac** [comment]
> @ Fatpandac 感谢，但是我试了下，发现1.是繁体，能不能切换成简体；2.能不能合并在一个feed里面，如果不行，那麻烦能不能直接爬取首页的最新更新新闻，做成一个feed，如下图位置
> 
> ![image](https://user-images.githubusercontent.com/2727281/149269446-872cdc2c-efe3-4a5f-b8dd-ee34137b5a02.png)
> 
> 

不好意思😬，刚看到，我晚上看看

**Comment by Fatpandac** [comment]
似乎切换不了简体，他的数据都是繁体的

**Comment by TonyRL** [comment]
You can use opencc parameter.

**Comment by Fatpandac** [comment]
@lylunula 
关于[路由简繁体转换](https://docs.rsshub.app/parameter.html#zhong-wen-jian-fan-ti-zhuan-huan)
