### ISSUE TITLE
Twitter profile error: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by freddd2** [DIYgod/RSSHub#8870]
### Routes

/twitter/user/heinzbelgium

### Full routes

/twitter/user/heinzbelgium

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter

### What is expected?

For RSS feed to show up.

### What is actually happening?

https://rsshub.app/twitter/user/heinzbelgium

Looks like something went wrong

Route requested: /twitter/user/heinzbelgium

Error message: Cannot read property 'user' of undefined

Helpful Information to provide when opening issue: 
Path: /twitter/user/heinzbelgium
Node version: v16.3.0

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
https://twitter.com/heinzbelgium
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
https://twitter.com/HeinzBelgium

This user has no tweets
