### ISSUE TITLE
Call for maintainer

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#8871]
As you can see, although there are many pull requests submissions, the project does not get enough manpower to be maintained and is being flooded by issues and pull requests.

So I'm looking for a maintainer to help the project grow healthily.

You need to do
- Resolve issues and merge pull requests
- Make reasonable updates to the core code

You can get
- A financial reward that makes you happy
- Maintenance experience on a large open source project

I expect you to have
- Contribution to the project (no matter what form)
- A resume to i@diygod.me

**Comment by ANTONIOJURET3388** [comment]
Al final putos

**Comment by DIYgod** [comment]
Happy to announce @TonyRL as our subsequent primary maintainer 🎉
