### ISSUE TITLE
general route/通用路由

### ISSUE THREAD

**Issue by markzsh** [DIYgod/RSSHub#8874]
### 这是一个什么样的功能？

# work for web site has rss feed/网站提供rss feed

### 这个功能可以解决什么问题？

RSSHub solved that many web site without rss feed，why not support the web site has rss feed？/RSSHub解决了很多内容没有rss的问题，为什么不通过一个通用路由模块来支持那些本就支持rss功能的站点呢？

### 额外描述

RSS for everything/不管内容支不支持RSS，RSSHub 统统搞定

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Fatpandac** [comment]
没必要吧，
这样做反而增加了服务器的成本呀。

**Comment by TonyRL** [comment]
See https://github.com/DIYgod/RSSHub/discussions/6671

**Comment by markzsh** [comment]
> See #6671

@TonyRL
Is it possible to Implement this feature by creating a general route?

**Comment by TonyRL** [comment]
> > See #6671
> 
> @TonyRL Is it possible to Implement this feature by creating a general route?

See https://github.com/DIYgod/RSSHub/pull/7296

**Comment by TonyRL** [comment]
Closed in #12882
