### ISSUE TITLE
希望heroku上的一键部署能增加缓存时间的自定义。

### ISSUE THREAD

**Issue by avexova** [DIYgod/RSSHub#8875]
### 这是一个什么样的功能？

可能是我蠢，看了好久文档也没看到该怎么变更缓存时间。
由于需要获取推特即时信息的缘故，现有heroku一键部署默认的缓存刷新时间大概是5-10分钟的样子，导致收到的信息都延迟了4-5分钟。
因为属于个人小众使用，不存在访问量过大的问题，所以不知能不能添加一个自定义缓存时间的功能？
如果真的没有时间调整，那有没大大告知一下heroku上该怎么去变更这个缓存时间？
又或者说，把代码fork下来后，我该修改哪个路径的文件更新才能生效？

### 这个功能可以解决什么问题？

为了解决访问量低，要接收即时信息，不需要缓存时间的问题。

### 额外描述

求设置办法

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/install/#pei-zhi
