### ISSUE TITLE
工信部rss无效

### ISSUE THREAD

**Issue by chancenju** [DIYgod/RSSHub#8896]
### 路由地址

/gov/miit/zcwj

### 完整路由地址

https://rsshub.app/gov/miit/zcwj

### 相关文档

https://docs.rsshub.app/government.html#zhong-guo-gong-ye-he-xin-xi-hua-bu

### 预期是什么？

应该能实时反应工信部信息

### 实际发生了什么？

Response code 521

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
RSSHub
Looks like something went wrong
Route requested: /gov/miit/zcwj
Error message: Response code 521 (undefined): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /gov/miit/zcwj
Node version: v16.3.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #8351
