### ISSUE TITLE
即刻的图片貌似加载不了？

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#890]
![image](https://user-images.githubusercontent.com/33424662/46929879-b407e480-d074-11e8-98f0-4f4002c8591d.png)

**Comment by ShimotsukiH** [comment]
即刻app里面看到图片的……

**Comment by ShimotsukiH** [comment]
![screenshot_20181015-161615](https://user-images.githubusercontent.com/33424662/46938264-df4efb80-d095-11e8-8b82-2299505656a1.jpg)

**Comment by HenryQW** [comment]
本来就无图，是即刻 app 加载的外链缩略图

![image](https://user-images.githubusercontent.com/5896343/46971109-fe0fbb00-d0b2-11e8-8f25-77c69a8155e7.png)
