### ISSUE TITLE
小红书订阅源好像失效了？

### ISSUE THREAD

**Issue by danmo66** [DIYgod/RSSHub#8905]
### 路由地址

/rsshub/xiaohongshu

### 完整路由地址

/xiaohongshu/user/5c8889770000000016003acb/notes

### 相关文档

https://docs.rsshub.app/social-media.html#xiao-hong-shu

### 预期是什么？

有抓取结果

### 实际发生了什么？

Looks like something went wrong

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /xiaohongshu/user/593032945e87e77791e03696/notes
Error message: Failed to launch the browser process!
/root/RSSHub/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Helpful Information to provide when opening issue: 
Path: /xiaohongshu/user/593032945e87e77791e03696/notes
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #8113 
Duplicate of #6622

**Comment by TonyRL** [comment]
Routes using puppeteer is working again on demo instance.
