### ISSUE TITLE
Twitter Response code 429. Error message: Response code 429 (Too Many Requests): target website might be blocking our access

### ISSUE THREAD

**Issue by laraws** [DIYgod/RSSHub#8919]
### Routes

Error message: Response code 429 (Too Many Requests): target website might be blocking our access

### Full routes

https://your_host.test/twitter/user/caddyserver

### Related documentation

https://docs.rsshub.app/en/install/#docker-deployment

### What is expected?

When I buit rsshub by docker-compose and run it at my own server, It worked about 2 months, but it can't work today, and displayed the error mesage below:

```
Looks like something went wrong

Route requested: /twitter/user/caddyserver

Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue: 
Path: /twitter/user/caddyserver
Node version: v14.18.3
```
Why did this hapen? How to fix it?

### What is actually happening?

When I buit rsshub by docker-compose and run it at my own server, It worked about 2 months, but it can't work today, and displayed the error mesage below:

```
Looks like something went wrong

Route requested: /twitter/user/caddyserver

Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue: 
Path: /twitter/user/caddyserver
Node version: v14.18.3
```
Why did this hapen? How to fix it?

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Ubuntu 21.04 x86_64           docker Version:           20.10.7   rsshub:https://hub.docker.com/r/diygod/rsshub

### Additional info

```shell
When I buit rsshub by docker-compose and run it at my own server, It worked about 2 months, but it can't work today, and displayed the error mesage below:


Looks like something went wrong

Route requested: /twitter/user/caddyserver

Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue: 
Path: /twitter/user/caddyserver
Node version: v14.18.3
```
Why did this hapen? How to fix it?
```


### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by UnoSD** [comment]
Same problem here and I also changed the public IP of the container as I thought it would be blacklisted, but even a different source IP gives the 429.

**Comment by heddxh** [comment]
same problem. using vercel

**Comment by zym27187** [comment]
same problem

**Comment by Jiematcha** [comment]
一样的问题
有解吗

**Comment by heddxh** [comment]
@Jiematcha 可以试试用API的方式

**Comment by liuqian1996** [comment]
me too

**Comment by syco** [comment]
Same here, I'm using docker from my home ip, I still get 429

**Comment by antv199** [comment]
Same here, but for me, it's probably because I'm using Heroku for my instance.

**Comment by arnonel** [comment]
Same for me

Is there a workaround for this?

**Comment by xministone** [comment]
Same for me

**Comment by Clackz** [comment]
隔了差不多两个月，还是显示429

**Comment by Rein-Ou** [comment]
same problem. using vercel and self-hosted
/twitter/user/kano_2525

**Comment by xministone** [comment]
“https://rsshub.app/twitter/user ”can use now ,but vercel and heroku still 429

**Comment by Rongronggg9** [comment]
The reason why this error occurs is that the API method RSSHub uses is outdated, instead of "Too Many Requests" (though Twitter does return this status code). I have updated the route with the latest API method, please check #9471.

**Comment by spencer17x** [comment]
same problem. using vercel.The problem still exists
