### ISSUE TITLE
Route for Logseq Changelog is no longer being updated

### ISSUE THREAD

**Issue by Endle** [DIYgod/RSSHub#8925]
### Routes

logseq/changelog

### Full routes

logseq/changelog

### Related documentation

https://docs.rsshub.app/en/program-update.html#logseq

### What is expected?

Should show new changelog of logseq (v0.5.8)

### What is actually happening?

The last update is on Mon, 05 Oct 2020

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Logseq dev team has abandoned the old website https://logseq.com/blog
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Endle** [comment]
@nczitzk

**Comment by nczitzk** [comment]
Since the old website has been abandoned, this might be what you need 😃

https://github.com/logseq/logseq/releases.atom

**Comment by Endle** [comment]
> Since the old website has been abandoned, this might be what you need smiley
> 
> https://github.com/logseq/logseq/releases.atom

Thank you for pointing it out!

Would it be better if logseq is removed from document?
