### ISSUE TITLE
javlibrary貌似失效了?

### ISSUE THREAD

**Issue by wedcf120** [DIYgod/RSSHub#8936]
### 路由地址

rsshub/javlibrary

### 完整路由地址

https://rsshub.app/javlibrary/stars/aegeq

### 相关文档

https://rsshub.app/javlibrary/stars/aegeq

### 预期是什么？

无法抓取内容

### 实际发生了什么？

Looks like something went wrong

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /javlibrary/stars/aegeq
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /javlibrary/stars/aegeq
Node version: v16.3.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
似乎可以了
![image](https://user-images.githubusercontent.com/30423976/151198193-9244e6c6-80c8-4aee-8fd2-d57575e7775e.png)
