### ISSUE TITLE
希望增加“商务印书馆新书速递”的RSS。

### ISSUE THREAD

**Issue by sutking** [DIYgod/RSSHub#894]
商务印书馆发布新书信息地址在此：
https://site.douban.com/commercialpress/room/827243/
希望加入RSS。

**Comment by xyqfer** [comment]
@sutking 输出最近两个月(比如现在是2018年9、10月这一项)的**全部**新书可以吗？
<img width="791" alt="wx20181016-092634 2x" src="https://user-images.githubusercontent.com/5186792/46987217-d9086000-d125-11e8-9274-12c338251de3.png">

**Comment by sutking** [comment]
> @sutking 输出最近两个月(比如现在是2018年9、10月这一项)的**全部**新书可以吗？
> <img alt="wx20181016-092634 2x" width="791" src="https://user-images.githubusercontent.com/5186792/46987217-d9086000-d125-11e8-9274-12c338251de3.png">

那就可以说是堪称完美啦😝

**Comment by DIYgod** [comment]
Done.
