### ISSUE TITLE
fulltext 全文输出模式，description里都是乱码

### ISSUE THREAD

**Issue by ruleroller** [DIYgod/RSSHub#8946]
### 路由地址

/bilibili/user/article/

### 完整路由地址

https://rsshub.app/bilibili/user/article/334958638?mode=fulltext

### 相关文档

https://docs.rsshub.app/parameter.html#quan-wen-shu-chu

### 预期是什么？

正文不发生乱码，正常输出该有的人类能直接理解的内容。

### 实际发生了什么？

正文乱码。

![image](https://user-images.githubusercontent.com/3047708/151293515-55ddffa3-a657-4fc8-b3bc-d6d1f0e4d658.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
官方demo里的例子：
https://rsshub.app/bilibili/user/article/334958638?mode=fulltext

另一个天气预报里的例子：
https://rsshub.app/weatherAlarm?mode=fulltext

我一直有订阅天气预报的，之前都没乱码，翻阅了一下记录，最后一次在2021-11-26至2021-11-29日之间，发生了某种情况，导致之后我订阅的天气预报里的正文都是乱码状态了，现在怀疑所有的路由，如果带上 mode=fulltext 都会是乱码状态。

请大佬们看看，是否能修复一下啊？
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
cheerio's behaviour got changed in 1.0.0-rc5 vs 1.0.0-rc3
