### ISSUE TITLE
请问微博的rss 标题捕抓的规律是什么？

### ISSUE THREAD

**Issue by ShimotsukiH** [DIYgod/RSSHub#897]
![image](https://user-images.githubusercontent.com/33424662/46938012-3ef8d700-d095-11e8-94b1-428a02661077.png)
为何会跳了两行直接捕抓到这里为标题？判断的是第一个书名号么？

**Comment by HenryQW** [comment]
例子都没有。。方案1 还是方案2 ？

**Comment by DIYgod** [comment]
缺少描述，暂时关闭

**Comment by ShimotsukiH** [comment]
emm 是我没贴例子么……
我试试详细说说吧……
我用rsshub关注的weibo中其中有这个

订阅源网站: | https://weibo.com/2592843922
-- | --
XML 地址: | https://api.izgq.net/weibo/rss/2592843922

 
rss爪过来的标题有时候是头几个字 
有时候就跳到第N行上
![image](https://user-images.githubusercontent.com/33424662/47341844-ad144e00-d6d4-11e8-92bf-ca15d8f43980.png)

不知道是出现什么毛病 
问题虽然不大，有图基本大概知道内容了
但这种有点诡异的事情 还是先发给大家看看……

**Comment by xyqfer** [comment]
> XML 地址: https://api.izgq.net/weibo/rss/2592843922

看了下来源是 https://github.com/zgq354/weibo-rss ，这个不是 RSSHub  的吧...
