### ISSUE TITLE
[UX] bilibili/user/channel: B站用户空间视频合集改版，路由需跟进

### ISSUE THREAD

**Issue by flosnvjx** [DIYgod/RSSHub#8985]
### 路由地址

/bilibili/user/channel

### 完整路由地址

/bilibili/user/channel/142821407/49017

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

请求适配B站空间视频合集改版。
见下述。

### 实际发生了什么？

B站从2021年12月月底正式上线了视频合集功能给一般up主。（见 [创作中心公告](https://www.bilibili.com/read/cv14415006)）

此次改版导致本issue所述之路由之用户体感url亦发生了改动。具体表现为：
- 原先仅开放给一些大UP主的「频道」功能改版（现在在web端的用户空间中被标作播放列表），其用户体感url由形如`https://space.bilibili.com/${uid}/#/channel/detail?cid=${cid}&ctype=0`变更为`https://space.bilibili.com/${uid}/channel/seriesdetail?sid=${sid}&ctype=0`——其中，旧版频道参数`cid`与新版空间播放列表的参数`sid`不共key——因此文档中的表述「频道 id, 可在频道的 URL 中找到」已不准确，虽然老route仍可用，但用户已无法再通过网址栏轻松提取订阅参数cid。
- 新上线的视频合集功能，目前rsshub似无route支持，其url形如`https://space.bilibili.com/${uid}/channel/collectiondetail?sid=${sid}&ctype=0`，似乎与上述sid不共key（条件受限，未通过devtools分析xhr api求证）

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
将从url中提取的sid赋值为cid参数在现有路由上不工作。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Reborn404** [comment]
希望可以添加哔哩哔哩的“合集和列表”的路由
