### ISSUE TITLE
Telegram频道里面的图片无法显示

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#903]
eg. https://t.me/liyuans/16398

---
## RSS显示:
![image](https://user-images.githubusercontent.com/6291329/47005287-05dc6780-d166-11e8-9741-cff049178a7e.png)

---
## t.me上的显示
![image](https://user-images.githubusercontent.com/6291329/47005370-30c6bb80-d166-11e8-8679-97c0b09a8cd5.png)

---
我尝试了好几个频道,都显示不了图像.

**Comment by yefoenix** [comment]
提供一个思路，可以把 <link>?embed=1 这个页面的内容抓过来，
例如 https://t.me/awesomeDIYgod/2118?embed=1 
不过图片是以 background-image: url 的形式出现的，需要处理一下……

**Comment by xyqfer** [comment]
@yefoenix 我试了下发现有个坑，如果频道发布的时候一次传多张图，上面这种形式是看不到图的，很迷....

**Comment by yefoenix** [comment]
@xyqfer 凉凉辛苦了😂 telegram channel 内容输出格式太多了吧太复杂

**Comment by yefoenix** [comment]
看了一下，
一次传多张图的时候，貌似每张图还是有一个单独的地址，例如

https://t.me/baisi/1579 这个链接有多图，可以分解成

https://t.me/baisi/1579?embed=1&single=1
https://t.me/baisi/1580?embed=1&single=1
https://t.me/baisi/1581?embed=1&single=1
……
@xyqfer

**Comment by xyqfer** [comment]
@yefoenix 囧，看来之前的姿势不对 = =
