### ISSUE TITLE
中山大学粤港澳发展研究院

### ISSUE THREAD

**Issue by Ganluo1999** [DIYgod/RSSHub#9033]
### 类型

论坛

### 网站地址

http://ygafz.sysu.edu.cn/opinion

### 网站描述

中山大学粤港澳发展研究院（以下简称研究院）是首批国家高端智库试点单位。研究院成立于2015年，在教育部人文社会科学重点研究基地中山大学港澳珠江三角洲研究中心、港澳与内地合作发展协同创新中心等基础之上，整合了校内经济学、政治学、法学、社会学、公共管理、新闻传播等优势学科研究力量，是港澳治理与粤港澳合作发展领域的专业化高端智库。

### 需要生成什么内容？

需要生产的栏目为：专家观点、新闻动态
十分感谢！

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by Fatpandac** [comment]
我来
