### ISSUE TITLE
【新闻联播】 网页改版 导致 故障

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#9036]
### 路由地址

/cctv/xwlb

### 完整路由地址

https://rsshub.app/cctv/xwlb

### 相关文档

https://docs.rsshub.app/traditional-media.html#yang-shi-xin-wen-xin-wen-lian-bo

### 预期是什么？

正常工作

### 实际发生了什么？

[http://tv.cctv.com/lm/xwlb/](http://tv.cctv.com/lm/xwlb/) 改版导致故障

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /cctv/xwlb

Error message: Invalid time value

Helpful Information to provide when opening issue: 
Path: /cctv/xwlb
Node version: v16.3.0
        
```
谢谢
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Closed this in #9568
