### ISSUE TITLE
【证券时报网-股市】希望能按照时间顺序推送，谢谢

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#9072]
### 类型

金融

### 网站地址

https://www.stcn.com/stock/

### 网站描述

证券时报网是中国证监会指定的信息披露媒体

### 需要生成什么内容？

希望能按照时间顺序推送

### 额外描述

谢谢

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nczitzk** [comment]
WIP

**Comment by KwToPA** [comment]
> WIP

感谢网友
