### ISSUE TITLE
微信公众号的TG路由获取的RSS几乎没有软件可以正常订阅

### ISSUE THREAD

**Issue by 212-mei** [DIYgod/RSSHub#9086]
### Routes

/wechat/tgchannel

### Full routes

/wechat/tgchannel/:id/:mpName?

### Related documentation

https://docs.rsshub.com

### What is expected?

期望能够在软件中订阅正常显示字体

### What is actually happening?

几乎所有的软件订阅这种方式获取的微信公众号RSS都会字体特别大，格式很乱

例如: https://hub.cue.ee/wechat/tgchannel/weixincc

![Screenshot_2022-02-13-16-06-16-904_me hyliu fluent_reader_lite](https://user-images.githubusercontent.com/62559713/153744598-47473355-bd98-48ce-aa25-8be0f88b2504.jpg)

### Deployment information

Self-hosted

### Additional info

```shell
无
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Fatpandac** [comment]
可以说一下你使用的阅读器是什么吗？
我在浏览器插件、Inoreader 以及 Feedly 都没能复现你的问题。
测试源为：https://hub.cue.ee/wechat/tgchannel/weixincc
