### ISSUE TITLE
龙空论坛改版导致故障

### ISSUE THREAD

**Issue by GTagent** [DIYgod/RSSHub#9089]
### 路由地址

/lkong/forum

### 完整路由地址

https://rsshub.app/lkong/forum/60

### 相关文档

https://docs.rsshub.app/bbs.html#long-kong-fen-qu

### 预期是什么？

https://www.lkong.com/forum/60 正常工作

### 实际发生了什么？

由于龙空论坛改版，新网址转移到www.lkong.com，并且论坛原有api更改导致故障

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /lkong/forum/60

Error message: Cannot read property 'map' of undefined

Helpful Information to provide when opening issue: 
Path: /lkong/forum/60
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nczitzk** [comment]
WIP
