### ISSUE TITLE
rsshub.app Picuki service is down

### ISSUE THREAD

**Issue by freddd2** [DIYgod/RSSHub#9093]
### Routes

https://rsshub.app/picuki/profile/user

### Full routes

https://rsshub.app/picuki/profile/user

### Related documentation

https://docs.rsshub.app/en/social-media.html#picuki

### What is expected?

A working RSS feed of updates on user posts.

### What is actually happening?

Route requested: /picuki/profile/user

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue: 
Path: /picuki/profile/user
Node version: v16.3.0

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Perhaps figure out if this block is intentional. And maybe remove Picuki as a service if it can no longer be made in a working state.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Demo is blocked. Route is working good on self-hosted instances.

**Comment by skatkov** [comment]
@TonyRL I'm using a self-hosted rsshub and still receive this error.

**Comment by skatkov** [comment]
@TonyRL strangely enough, I'm receiving this error from time to time with a self-hosted instance.

**Comment by TonyRL** [comment]
> @TonyRL strangely enough, I'm receiving this error from time to time with a self-hosted instance.

`/picuki/profile/user` contains an invalid username so it will definitely cause an error. You need to replace `user` with an Instagram username like `stefaniejoosten`. It would be better if you can provide a detailed log for troubleshooting.
