### ISSUE TITLE
IELTS雅思最新消息

### ISSUE THREAD

**Issue by vfanghao** [DIYgod/RSSHub#9094]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/DIYgod/RSSHub/issues/9094)

### 类型

学习

### 网站地址

https://ielts.neea.cn/allnews?locale=zh_CN

### 网站描述

雅思中国新闻通知网站

### 需要生成什么内容？

·原文链接
·标题
·正文

### 额外描述

网站的消息顺序似乎并不是按照日期来排的，希望大佬们能按照时间顺序排列一下

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/40256755?v=4' alt='vfanghao' width=24 height=24> vfanghao](https://issuehunt.io/u/vfanghao) ($5.00)

### Submitted pull Requests
- [#9217 feat: add ielts](https://issuehunt.io/r/DIYgod/RSSHub/pull/9217)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/DIYgod/RSSHub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by zenxds** [comment]
@DIYgod https://issuehunt.io/r/DIYgod/RSSHub/issues/9094 已解决

**Comment by vfanghao** [comment]
目前还是不能用呀

**Comment by zenxds** [comment]
> 

这个网站对爬虫的防范做的比较严格，我本地调试都是没问题的，RSSHub可能因为访问频率等其他原因导致拿不到正确的内容，有条件的话自己部署一个服务试试

**Comment by TonyRL** [comment]
/test
```routes
/ielts
```

**Comment by vfanghao** [comment]
现在已经可以用了，多谢啦
