### ISSUE TITLE
Route requested: /toutiao/today Error message: wrong path

### ISSUE THREAD

**Issue by Lowpower** [DIYgod/RSSHub#9099]
### 路由地址

 /toutiao/today

### 完整路由地址

 /toutiao/today

### 相关文档

 /toutiao/today

### 预期是什么？

Route requested: /toutiao/today Error message: wrong path

### 实际发生了什么？

Route requested: /toutiao/today Error message: wrong path

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /toutiao/today Error message: wrong path
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
I can't find this route in [document](https://docs.rsshub.app/), please tell me where this route document is.

**Comment by TonyRL** [comment]
This route does not exist.
