### ISSUE TITLE
证券时报网要闻和股市信息获取报错

### ISSUE THREAD

**Issue by ICEY1W32** [DIYgod/RSSHub#9100]
### 路由地址

/stcn

### 完整路由地址

/stcn/xw/*, /stcn/stock/*

### 相关文档

https://docs.rsshub.app/finance.html#zheng-quan-shi-bao-wang

### 预期是什么？

预期正常获取

### 实际发生了什么？

“Looks like something went wrong”报错，信息如下

### 部署

自建

### 额外信息

```shell
Route requested: /stcn/xw/news
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /stcn/xw/news
Node version: v14.19.0

Route requested: /stcn/stock/gsdt
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /stcn/stock/gsdt
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
我尝试了对应的 v14.19.0 版本以及我自建的
[/stcn/stock/gsdt](https://rss.fatpandac.com/stcn/stock/gsdt) ![https://rss.fatpandac.com/stcn/stock/gsdt](https://img.shields.io/website?label=status&style=flat-square&url=https://rss.fatpandac.com/stcn/stock/gsdt)
[/stcn/xw/news](https://rss.fatpandac.com/stcn/xw/news) ![https://rss.fatpandac.com/stcn/xw/news](https://img.shields.io/website?label=status&style=flat-square&url=https://rss.fatpandac.com/stcn/xw/news)
都没有能复现

**Comment by ICEY1W32** [comment]
> 

您提供的链接我也可以正常使用，这边因为是内网搭建所以无法提供测试链接
另发现/stcn/news地址可获取要闻
提供我的详细部署环境为：OS：Raspbian GNU/Linux 10 (buster)，Node：v14.19.0，Docker：v20.10.12

**Comment by ICEY1W32** [comment]
此问题已在系统更换为64位
OS：Raspbian GNU/Linux11 (bullseye)
并重新部署后得到了解决，原因未知

**Comment by ICEY1W32** [comment]
> 此问题已在系统更换为64位
> OS：Raspbian GNU/Linux 11 (bullseye)
> 并重新部署后得到了解决，原因未知
推测可能为重新部署时使用了同版本但是更新的镜像
