### ISSUE TITLE
希望可以增加豆瓣同城_南京的rss

### ISSUE THREAD

**Issue by AltiaEvan** [DIYgod/RSSHub#911]
如题，谢谢

**Comment by xyqfer** [comment]
Done. 0449e781dc04de9f9603fee2f3a05bff2631c4bb

**Comment by xyqfer** [comment]
南京的可以用这个地址：https://rsshub.app/douban/event/hot/118159

**Comment by AltiaEvan** [comment]
非常感谢！！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 凉凉 <notifications@github.com>
发送时间: Thursday, October 18, 2018 2:56:29 PM
收件人: DIYgod/RSSHub
抄送: Evan Liu; Author
主题: Re: [DIYgod/RSSHub] 希望可以增加豆瓣同城_南京的rss (#911)


南京的可以用这个地址：https://rsshub.app/douban/event/hot/118159

―
