### ISSUE TITLE
Odaily网址更换导致抓取失败

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#9118]
### 路由地址

/odaily

### 完整路由地址

/odaily

### 相关文档

https://docs.rsshub.app/odaily

### 预期是什么？

可以正常抓取，但由于域名更换，导致抓取失败。麻烦将域名改为：https://www.0daily.com/

### 实际发生了什么？

抓取失败

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: getaddrinfo ENOTFOUND www.odaily.news: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Again? Last URL change was 25 days ago (https://github.com/DIYgod/RSSHub/issues/8703)

**Comment by lylunula** [comment]
嗯，域名没有那么稳定😯
