### ISSUE TITLE
乃木坂 46 新闻失效

### ISSUE THREAD

**Issue by guangwenzhu** [DIYgod/RSSHub#9128]
### 路由地址

/nogizaka46/news

### 完整路由地址

/nogizaka46/news

### 相关文档

https://docs.rsshub.app/new-media.html#ban-dao-xi-lie-guan-wang-zi-xun

### 预期是什么？

重新抓取该网站的最新资讯

### 实际发生了什么？

该[网站](https://www.nogizaka46.com)今天大改版，整个网站的架构已经与以前不同，导致该路由失效。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
目前官网新闻输出的页面是 https://www.nogizaka46.com/s/n46/news/list?ima=0113 ，由于官方提供多国语言翻译，输出摘要就可以了，不用输出全文。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
之前的路由内容显示的是日文吗？

**Comment by guangwenzhu** [comment]
> 之前的路由内容显示的是日文吗？

对，是日文。还是保持日文就可以，官方不是每条消息都翻译中文。

**Comment by Fatpandac** [comment]
> > 之前的路由内容显示的是日文吗？
> 
> 对，是日文。还是保持日文就可以，官方不是每条消息都翻译中文。

我也拿不到翻译🐶，他的翻译似乎是本地完成的

**Comment by guangwenzhu** [comment]
> > > 之前的路由内容显示的是日文吗？
> > 
> > 
> > 对，是日文。还是保持日文就可以，官方不是每条消息都翻译中文。
> 
> 我也拿不到翻译🐶，他的翻译似乎是本地完成的

不需要翻译啊，输出摘要就可以了，不用输出全文，自己用浏览器跳转到官网看就行了

**Comment by Fatpandac** [comment]
> > > > 之前的路由内容显示的是日文吗？
> > > 
> > > 
> > > 对，是日文。还是保持日文就可以，官方不是每条消息都翻译中文。
> > 
> > 
> > 我也拿不到翻译🐶，他的翻译似乎是本地完成的
> 
> 不需要翻译啊，输出摘要就可以了，不用输出全文，自己用浏览器跳转到官网看就行了

晓得👌
