### ISSUE TITLE
腾讯研究院

### ISSUE THREAD

**Issue by Alphabet1226** [DIYgod/RSSHub#9141]
### 类型

新媒体

### 网站地址

https://www.tisi.org/

### 网站描述

是腾讯公司设立的社会科学研究机构。非盈利性学术网站，所有文章约为学术研究用途。

### 需要生成什么内容？

首页文章

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by Fatpandac** [comment]
请问首页文章指的是那一部分？

**Comment by Alphabet1226** [comment]
> 请问首页文章指的是那一部分？

抱歉没有描述清楚，是指的**最近更新**这部分。
![image](https://user-images.githubusercontent.com/51783873/154804463-f3492a39-1254-4a74-b675-918833a09663.png)

**Comment by TonyRL** [comment]
They have their RSS https://www.tisi.org/feed
