### ISSUE TITLE
ResearchGate Publication 针对反爬的更新需求

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#9142]
### 这是一个什么样的功能？

获取 ResearchGate Publication

### 这个功能可以解决什么问题？

目前的RG Publication无法抓取，需要反爬的策略更新

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Fatpandac** [comment]
官方示例可能被拉黑了，自建可以
[/researchgate/publications/Somsak-Panha](https://rss.fatpandac.com/researchgate/publications/Somsak-Panha)![https://rss.fatpandac.com/researchgate/publications/Somsak-Panha](https://img.shields.io/website?label=status&style=flat-square&url=https://rss.fatpandac.com/researchgate/publications/Somsak-Panha)

**Comment by starsareintherose** [comment]
我的自建不行哎

**Comment by starsareintherose** [comment]
Route requested: /researchgate/publications/Guoyi-Zhang
Error message: Response code 429 (Too Many Requests): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /researchgate/publications/Guoyi-Zhang
Node version: v17.5.0

**Comment by Fatpandac** [comment]
你自建的也被拉黑了呀，你用我的吧

**Comment by lanmo0923** [comment]
我的自建也不行，有其他办法吗？

**Comment by starsareintherose** [comment]
> 

Notice, yours is also blocked
