### ISSUE TITLE
Bioone Journal

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#9143]
### 类型

科学期刊

### 网站地址

https://bioone.org/journals/ANY_JOURNAL/current 

替换 `ANY_JOURNAL`

### 网站描述

BioOne 系列期刊的最新一期的publication
比如 https://bioone.org/journals/invasive-plant-science-and-management/current

### 需要生成什么内容？

- 题目
- 作者
- 摘要
- 关键词

### 额外描述

不同期刊的 HTML class 一类可能不一样，需要综合多个期刊

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #6979 
https://rsshub.app/bioone/journals/invasive-plant-science-and-management

**Comment by starsareintherose** [comment]
> Duplicate of #6979
> 
> https://docs.rsshub.app/journal.html#bioone

The issues mentioned are main web page instead of journal page

**Comment by TonyRL** [comment]
> > Duplicate of #6979
> > https://docs.rsshub.app/journal.html#bioone
> 
> The issues mentioned are main web page instead of journal page

https://rsshub.app/bioone/journals/invasive-plant-science-and-management
