### ISSUE TITLE
推特web-api相关说明和文档好像没有

### ISSUE THREAD

**Issue by skilittle** [DIYgod/RSSHub#9146]
### 这是一个什么样的功能？

增加使用推特web-api相关配置的详细说明

### 这个功能可以解决什么问题？

推特开发者难申请，只能用web-api了

### 额外描述

虽然看到有关于web-api相关的提案和支持，但是我找了很久都没看到有配置相关的说明

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Rongronggg9** [comment]
The only config for Twitter "web-api" is:

https://github.com/DIYgod/RSSHub/blob/300af7318702953c6478feabe76678c52e967741/lib/config.js#L224

Unfortunately, the "web-api" is actually reverse-engineered from Twitter Web so every user is using the same token (yes, this is exactly what Twitter sets for every user)...

![](https://user-images.githubusercontent.com/15956627/161483679-a618f40b-9553-4ae7-b3a8-aaef5ff46c33.png)

So as you can see, no further documentation may help self-hosted instance maintainers to avoid being rate limited...

**Comment by CXwudi** [comment]
@Rongronggg9 It looks like you can not just only have the `web-api` to enable twitter RSS feed on RssHub, which is what the documentation said `如果上述两个环境变量中的任意一个未设置，就会使用 Twitter Web API`. 
![image](https://user-images.githubusercontent.com/17377423/163733506-5174159a-2bd4-4a18-9a13-4e4a6d09e36f.png)
This is what I got:
![image](https://user-images.githubusercontent.com/17377423/163733247-39124f0e-54b7-497d-b721-73252465f312.png)
![image](https://user-images.githubusercontent.com/17377423/163733201-f648a913-8aab-49d2-8814-6bf3925d4dcb.png)
So even with the `web-api`, is applying a Twitter developer account still the only way to use Twiiter RSS from RssHub?

**Comment by Rongronggg9** [comment]
@CXwudi Check if you are using an old version

https://github.com/DIYgod/RSSHub/blob/6b7381e1e3c41c395ee1dabbd004901765ada25f/lib/routes/twitter/user.js#L6-L16

**Comment by CXwudi** [comment]
@Rongronggg9 Thanks for reply, yes I was using an old version, now it works
