### ISSUE TITLE
知乎问题抓取失败

### ISSUE THREAD

**Issue by data7799** [DIYgod/RSSHub#9151]
### 路由地址

/rsshub.app/zhihu/question

### 完整路由地址

/zhihu/question/:questionId

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu

### 预期是什么？

正常抓取

### 实际发生了什么？

无法正常抓取，出现报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /zhihu/question/19763541
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /zhihu/question/19763541
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KanswerG** [comment]
同样问题

**Comment by Colin-XKL** [comment]
这是公用rsshub实例（rsshub.app）的IP被知乎禁了吧？可以考虑下自部署rsshub

**Comment by KanswerG** [comment]
找了个能用的解析服务，已解决

发自我的iPhone

**Comment by data7799** [comment]
> ```shell
> /zhihu/question/19763541
> ```

我用vercel搭建的rsshub和别人搭建的rsshub都试过了，都不行，报错如下：
	• 我自己的：
Route requested: /zhihu/question/19763541
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /zhihu/question/19763541
Node version: v14.18.3
	• 别人的：
Route requested: /zhihu/question/19763541
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /zhihu/question/19763541
Node version: v14.19.0

**Comment by Colin-XKL** [comment]
> 我用 vercel 搭建的 rsshub 和别人搭建的 rsshub 都试过了，都不行，报错如下：

vercel这个平台本来就是开放的，早就有很多人在这上面部署过rsshub之类的服务，服务商的IP被知乎禁了，你启再多实例也没用。  
> Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

报错信息也说了，遇到这种情况，建议你自己单独部署个rsshub实例，最好是个人的服务器上面的。我在我自己的服务器上部署的rsshub正常使用快两年了，依然可以正常爬取知乎的内容。

**Comment by data7799** [comment]
> > 我用 vercel 搭建的 rsshub 和别人搭建的 rsshub 都试过了，都不行，报错如下：
> 
> vercel这个平台本来就是开放的，早就有很多人在这上面部署过rsshub之类的服务，服务商的IP被知乎禁了，你启再多实例也没用。
> 
> > Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
> 
> 报错信息也说了，遇到这种情况，建议你自己单独部署个rsshub实例，最好是个人的服务器上面的。我在我自己的服务器上部署的rsshub正常使用快两年了，依然可以正常爬取知乎的内容。

Oh,I see.Thank you!
