### ISSUE TITLE
俄国网站vk订阅

### ISSUE THREAD

**Issue by Pepperzxy** [DIYgod/RSSHub#9154]
### Category

Social Media

### Website URL

https://vk.com/feed

### Website description

这是一个俄国的社交媒体网站，类似于国内的微博

### What content should be included?

希望可以像订阅微博某一个博主一样，订阅vk所关注的人的动态（请去重）

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Duplicate of #3193
