### ISSUE TITLE
Oxford Journal

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#9178]
### 路由地址

/oup/journals

### 完整路由地址

/oup/journals/:name

### 相关文档

https://docs.rsshub.app/journal.html#oxford-university-press

### 预期是什么？

can work

### 实际发生了什么？

I input `/oup/journals/sysbio` but it shows `/journals/sysbio`

And some of them works, so strange

### 部署

自建

### 部署相关信息

ArchLinux

### 额外信息

```shell
Route requested: /journals/sysbio
Error message: TypeError: Cannot read properties of undefined (reading 'map')
    at module.exports (/opt/rsshub/lib/v2/oup/index.js:14:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/rsshub/node_modules/koa-mount/index.js:58:5
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/lib/middleware/load-on-demand.js:29:9
    at async /opt/rsshub/lib/middleware/cache/index.js:119:13
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/opt/rsshub/lib/middleware/parameter.js:10:5)
    at async module.exports (/opt/rsshub/lib/middleware/anti-hotlink.js:33:5)
Helpful Information to provide when opening issue: 
Path: /journals/sysbio
Node version: v17.5.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by rainrdx** [comment]
I have a lot of issues with oxford journals. Almost always returning error with "Error message: Cannot read property 'map' of undefined" due to anti-crawling. I use my own self-hosted rsshub and seems there is no easy way to get around oxford journals' detection...?

**Comment by starsareintherose** [comment]
Right, it would be quite difficult

**Comment by TonyRL** [comment]
`/oup/journals/sysbio` works as of replying.
The error may be caused by strict anticrawler limits.
