### ISSUE TITLE
readhub抓取信息出错

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#9188]
### 路由地址

/readhub

### 完整路由地址

/readhub/category/topic

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

抓取正常
![image](https://user-images.githubusercontent.com/2727281/155515228-d6e08309-e7de-4a06-b0f0-5e2b1ef6e09f.png)

### 实际发生了什么？

抓取内容好像把第一个链接的全文抓出来了

![image](https://user-images.githubusercontent.com/2727281/155515352-1f01293f-3b9f-4185-9813-16ea8650211c.png)

### 部署

自建

### 额外信息

```shell
之前一直抓取正常，但是最近2天的数据抓取有问题
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
你需要显示的是简介内容而不是文章的全部内容吗？即下图框选内容
<img width="668" alt="截屏2022-02-25 上午9 20 17" src="https://user-images.githubusercontent.com/30423976/155635450-f1fb23fd-e172-4862-866a-02fa392e44d2.png">
