### ISSUE TITLE
PANews不可用

### ISSUE THREAD

**Issue by mxinyi** [DIYgod/RSSHub#9198]
### 路由地址

https://rsshub.app/panewslab

### 完整路由地址

https://rsshub.app/panewslab

### 相关文档

无

### 预期是什么？

正常可用。

### 实际发生了什么？

RSSHub
Looks like something went wrong
Route requested: /panewslab
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /panewslab
Node version: v16.3.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=&template=bug_report.md)
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=&template=bug_report.md)
        
在线文档与支持，请访问[docs.rsshub.app](https://docs.rsshub.app/)。

For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
RSSHub
Looks like something went wrong
Route requested: /panewslab
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /panewslab
Node version: v16.3.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Demo does not run the latest RSSHub.

**Comment by TonyRL** [comment]
`/panewslab` is working as of replying
