### ISSUE TITLE
首页的DEBUG能否关闭？

### ISSUE THREAD

**Issue by universehello** [DIYgod/RSSHub#9206]
### 这是一个什么样的功能？

通过字段，关闭debug

### 这个功能可以解决什么问题？

防止debug的rss泄露

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/install/#pei-zhi-qi-ta-ying-yong-pei-zhi

**Comment by zeze0556** [comment]
如果设置了ACCESS_KEY的情况下，debug信息应该只在key存在并且正确的情况下显示。
