### ISSUE TITLE
帮忙抓取一下通信人家园

### ISSUE THREAD

**Issue by mucstudio** [DIYgod/RSSHub#9209]
### 这是一个什么样的功能？

https://www.txrjy.com/c114-listnewtopic.php

订阅该站最新发帖，和某个类目最新发帖

### 这个功能可以解决什么问题？

每日手工查看信息的不准确性

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please use the correct form for new RSS proposal.
