### ISSUE TITLE
APnews路由抓取失败

### ISSUE THREAD

**Issue by congnews** [DIYgod/RSSHub#9225]
### 路由地址

/apnews/topics2/:topic

### 完整路由地址

/apnews/topics2/ap-top-news

### 相关文档

https://docs.rsshub.app/traditional-media.html#ap-news

### 预期是什么？

返回ap top news

### 实际发生了什么？

Route requested: /apnews/topics2/ap-top-news
Error message: wrong path

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
Helpful Information to provide when opening issue: 
Path: /apnews/topics2/ap-top-news
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Use `/apnews/topics/ap-top-news`
