### ISSUE TITLE
TASS.com

### ISSUE THREAD

**Issue by Jiematcha** [DIYgod/RSSHub#9226]
### Category

News

### Website URL

https://tass.com/

### Website description

RUSSIAN NEWS AGENCY

### What content should be included?

http://tass.com/rss/v2.xml

### Additional description

Official RSS http://tass.com/rss/v2.xml Can't work on FreshRSS

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
> TASS has fixed the js redirection requirement. Also the link in the official feed is now fixed.
This feature is no longer needed.

_Originally posted by @mkmark in https://github.com/DIYgod/RSSHub/issues/9293#issuecomment-1072062682_
