### ISSUE TITLE
爱奇艺动画出错

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#923]
![image](https://user-images.githubusercontent.com/21376471/47168746-3f62cd80-d334-11e8-85b6-d8eace61c5cb.png)

以上是文档中的示例：https://rsshub.app/iqiyi/dongman/a_19rrh1sifx
爱奇艺地址：https://www.iqiyi.com/a_19rrh1sifx.html

**Comment by jiey2016** [comment]
爱奇艺动画再次出错，上报时间2020.02.22
![image](https://user-images.githubusercontent.com/19381978/75052240-38406680-550a-11ea-8b44-fd1c559fc2e0.png)
https://rsshub.app/iqiyi/dongman/a_19rrh1sifx

**Comment by jiey2016** [comment]
> @爱奇艺动画再次出错，上报时间2020.02.22 @DIYgod @xyqfer 
> ![image](https://user-images.githubusercontent.com/19381978/75052240-38406680-550a-11ea-8b44-fd1c559fc2e0.png)
> https://rsshub.app/iqiyi/dongman/a_19rrh1sifx

**Comment by jiey2016** [comment]
@DIYgod 请求尽快并入，已经有大神修复了
