### ISSUE TITLE
Furaffinity rss question

### ISSUE THREAD

**Issue by Destroyer77d** [DIYgod/RSSHub#9240]
### Category

Pciture

### Website URL

https://www.furaffinity.net/

### Website description

Various furry art, both safe and not safe for work

### What content should be included?

Hi, this is the best way I've found to reach out for an answer. I've been trying to get these rss feed examples working https://docs.rsshub.app/en/social-media.html#fur-affinity.

In the example it says: nsfw, optional - NSFW Mode, do not filter NSFW contents when value set to 1

How do you set the value to 1? That's my only question. Probably stupid. I appreciate any help.

### Additional description

Thanks for your help

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
/furaffinity/home/artwork/1
