### ISSUE TITLE
请支持订阅 npm 包的下载量和更新

### ISSUE THREAD

**Issue by radiorz** [DIYgod/RSSHub#9243]
### 这是一个什么样的功能？

npm 是 前端重要的包管理网站,希望可以支持订阅 npm 的包的下载量和更新,以便更好地写代码

### 这个功能可以解决什么问题？

npm 是 前端重要的包管理网站,希望可以支持订阅 npm 的包的下载量和更新,以便更好地写代码

### 额外描述

网址 http://npmjs.com/

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please use the correct form for new RSS proposal.
