### ISSUE TITLE
【部分微博用户无法抓取】Error message: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#9245]
### 路由地址

/weibo/user/id

### 完整路由地址

/weibo/user/id

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

### 预期是什么？

正常工作

### 实际发生了什么？

报错，以ID=7450620993 为例子  [https://weibo.com/u/7450620993](https://weibo.com/u/7450620993)

```
Route requested: /weibo/user/7450620993

Error message: Cannot read property 'user' of undefined

Helpful Information to provide when opening issue: 
Path: /weibo/user/7450620993
Node version: v16.3.0
```

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
报错，以ID=7450620993 为例子

Route requested: /weibo/user/7450620993

Error message: Cannot read property 'user' of undefined

Helpful Information to provide when opening issue: 
Path: /weibo/user/7450620993
Node version: v16.3.0
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/30423976/156887468-ecd2a0f5-06b6-47b0-b9f6-e52f15aa81d7.png">

**Comment by KwToPA** [comment]
@Fatpandac  这账户没想到是登录可见
