### ISSUE TITLE
ERROR: for rsshub_browserless_1  Cannot start

### ISSUE THREAD

**Issue by snakwu** [DIYgod/RSSHub#9254]
### Routes

rsshub运行报错

### Full routes

rsshub运行报错

### Related documentation

https://docs.rsshub.app/install/  Docker Compose 部署

### What is expected?

https://raw.githubusercontent.com/DIYgod/RSSHub/master/docker-compose.yml部置
运行出错！

ERROR: for rsshub_browserless_1  Cannot start service browserless: unable to find user node: no matching entries in passwd file

ERROR: for browserless  Cannot start service browserless: unable to find user node: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.

### What is actually happening?

希望修复运行！

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

ubuntu20.04

### Additional info

```shell
ERROR: for rsshub_browserless_1  Cannot start service browserless: unable to find user node: no matching entries in passwd file

ERROR: for browserless  Cannot start service browserless: unable to find user node: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please delete the old browserless image and repull it.

**Comment by snakwu** [comment]
> 请删除旧的无浏览器图像并重新发布。

root@ubuntu:~/Docker/RSSHub$ docker-compose down
Stopping rsshub_redis_1 ... done                                                                                                                Removing rsshub_redis_1       ... done                                                                                                          Removing rsshub_browserless_1 ... done                                                                                                          Removing network rsshub_default
root@ubuntu:~/Docker/RSSHub$ docker-compose up -d 
Creating network "rsshub_default" with the default driver
Creating rsshub_browserless_1 ... error                                                                                                         Creating rsshub_redis_1       ... 

Creating rsshub_redis_1       ... done                                                                                                          
ERROR: for browserless  Cannot start service browserless: unable to find user node: no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
root@ubuntu:~/Docker/RSSHub$

**Comment by TonyRL** [comment]
Please provide the output of `docker inspect rsshub_browserless_1`

**Comment by snakwu** [comment]
> 

   {
        "Id": "4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529",
        "Created": "2022-03-06T13:18:31.213782389Z",
        "Path": "./start.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 470589,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-03-06T13:18:31.515390705Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:ec7bb30f39c544fa44a74e6f5c65d33fc28959028e0551d3b63d3ede72a68608",
        "ResolvConfPath": "/var/lib/docker/containers/4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529/hostname",
        "HostsPath": "/var/lib/docker/containers/4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529/hosts",
        "LogPath": "/var/lib/docker/containers/4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529/4a666fa1933d7fba543267b45f3f5b70c950d9eb0ab827bf61b467ddad40c529-json.log",
        "Name": "/rsshub_browserless_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "rsshub_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [
                {
                    "Name": "core",
                    "Hard": 0,
                    "Soft": 0
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/be16c71b63a6331b15c5420b1aceceeaeea093c99eeeb5dc089a47c46ffe6472-init/diff:/var/lib/docker/overlay2/0a18e822f6e71fcd94e67b22ec8e80559d46b341009f9979d5fe8775d9648e77/diff:/var/lib/docker/overlay2/21229ec4579b5c770c8cc867f4f1ce19a275b35cfc0beba3ebf6d89338e9e6e2/diff:/var/lib/docker/overlay2/02cd065a9a2ae2ac9e4c78b7cda54a64d47e62e3b01ddf33fdb786903beba514/diff:/var/lib/docker/overlay2/cc66b4270c64bb354877c33dc6d8d4ec723780ba5e5c8657d4dcd017eacc4cd6/diff:/var/lib/docker/overlay2/be02ce157a738a262d70ab4964a6b8dc8656b7e44f4834a0f408f0e91fd60436/diff:/var/lib/docker/overlay2/9fb1251e75e25ac90918c16b150d01f9f7b308fd7a98bd58cf9321034249656c/diff:/var/lib/docker/overlay2/13344e5587d20d7e3684abf1c009ee38ff6c0e55f10b2888945428efc87759a4/diff:/var/lib/docker/overlay2/d05a4b455b536c5c51099214cabd9db15f6512b639db79e239ca98f461d36bdf/diff:/var/lib/docker/overlay2/21d9909fd57ad903ff698f13f765920eb0de5a8b17b7329272021668f0d2ba93/diff:/var/lib/docker/overlay2/424b905a7cf62d3eb749488baac73fd0b614221e64c47ca2fae00cfcfdf32e27/diff:/var/lib/docker/overlay2/c898ec00ee139b47968c213d48a7d80452a0f3799a3e8843dcca8f56deb50cc7/diff:/var/lib/docker/overlay2/17732d5a2db2ca7b8cab3718f08a5baf2b9478fd5cf0f7c394a7401ae12700e4/diff:/var/lib/docker/overlay2/fd4d829c9b0d739825c45bbfb4f797535e7a0e7a59906ce1d79fbfd4208624a5/diff:/var/lib/docker/overlay2/e1d59e730b147005c5f9699abde2c6d26f4de5ba2fea823248118ea987062912/diff",
                "MergedDir": "/var/lib/docker/overlay2/be16c71b63a6331b15c5420b1aceceeaeea093c99eeeb5dc089a47c46ffe6472/merged",
                "UpperDir": "/var/lib/docker/overlay2/be16c71b63a6331b15c5420b1aceceeaeea093c99eeeb5dc089a47c46ffe6472/diff",
                "WorkDir": "/var/lib/docker/overlay2/be16c71b63a6331b15c5420b1aceceeaeea093c99eeeb5dc089a47c46ffe6472/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "4a666fa1933d",
            "Domainname": "",
            "User": "blessuser",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "APP_DIR=/usr/src/app",
                "CONNECTION_TIMEOUT=60000",
                "CHROME_PATH=/usr/bin/google-chrome",
                "HOST=0.0.0.0",
                "IS_DOCKER=true",
                "LANG=C.UTF-8",
                "NODE_ENV=production",
                "PORT=3000",
                "PUPPETEER_CHROMIUM_REVISION=809590",
                "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
                "USE_CHROME_STABLE=true",
                "WORKSPACE_DIR=/usr/src/app/workspace"
            ],
            "Cmd": [
                "./start.sh"
            ],
            "Image": "browserless/chrome:1.43-chrome-stable",
            "Volumes": null,
            "WorkingDir": "/usr/src/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "browser": "HeadlessChrome/87.0.4280.66",
                "com.docker.compose.config-hash": "7af672bea89a1ce17804ed5db9e744d9cc19e4b883fe388ba51ba2ea3f4d9e7e",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "rsshub",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/snakwu/Docker/RSSHub",
                "com.docker.compose.service": "browserless",
                "com.docker.compose.version": "1.25.0",
                "debuggerVersion": "fd98a29dd59b36f71e4741332c9ad5bda42094bf",
                "protocolVersion": "1.3",
                "puppeteerVersion": "5.4.1",
                "v8Version": "8.7.220.25",
                "webkitVersion": "537.36 (@fd98a29dd59b36f71e4741332c9ad5bda42094bf)"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d14d847980046822ed25b14db56070078c34e7216a21243263ce7077e42614a4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/d14d84798004",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "rsshub_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "4a666fa1933d",
                        "browserless"
                    ],
                    "NetworkID": "4d37e77d54acb731611afb746bdb8e6db2accbe71cc8603c93d1c46edd491ac2",
                    "EndpointID": "65892c614cc957ae2c4f73c7fb4844ac342dc6f5130f4e8c3c2fbe132826461e",
                    "Gateway": "192.168.48.1",
                    "IPAddress": "192.168.48.3",
                    "IPPrefixLen": 20,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:30:03",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by snakwu** [comment]
> 

  {
        "Id": "dc72e47d2feee34300880e43ad3e0635236633f99bdce8d9032b7b3e7af5ce24",
        "Created": "2022-03-06T13:54:56.934844688Z",
        "Path": "./start.sh",
        "Args": [],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "unable to find user node: no matching entries in passwd file",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:5cfb12cb6ba6d22c705d67dc8de38427cc71ba139e8e0c2158dca7d87cc083c8",
        "ResolvConfPath": "/var/lib/docker/containers/dc72e47d2feee34300880e43ad3e0635236633f99bdce8d9032b7b3e7af5ce24/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/dc72e47d2feee34300880e43ad3e0635236633f99bdce8d9032b7b3e7af5ce24/hostname",
        "HostsPath": "/var/lib/docker/containers/dc72e47d2feee34300880e43ad3e0635236633f99bdce8d9032b7b3e7af5ce24/hosts",
        "LogPath": "",
        "Name": "/rsshub_browserless_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "rsshub_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [
                {
                    "Name": "core",
                    "Hard": 0,
                    "Soft": 0
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/db4b83c9252f558e7cb3451913615daa6aa8fd05e8e7a79c8faea454b6511b1c-init/diff:/var/lib/docker/overlay2/7af6898b3f8a4dbf2f183cf87266ccf3a989b1c6f3c4e94114e30f21b6f38faf/diff:/var/lib/docker/overlay2/182af0fa4dd9c900791b918c3ed726f6bbf3d185924bdb6fa1355f3cf3734ab5/diff:/var/lib/docker/overlay2/d551fe4cca49ef4aa8f2568980423c34db783092d4dd35223f5b6b559280c871/diff:/var/lib/docker/overlay2/02b6a3a6d8c24b9eecbdc91e318b116faa7c7b4ccda3020d82b1f95fae67f120/diff:/var/lib/docker/overlay2/ddb8c448b0983e9f4757f94d5d4ce220933604b93a76de221a86328105ba9021/diff:/var/lib/docker/overlay2/82424a67dbaf92deabe8480974460b88dad867dcd9a3a38636f2427757c8732c/diff:/var/lib/docker/overlay2/2e459c65fe24f8f34820e0b0b08581eab454ef5e03703121217a4ac5cb590f0e/diff:/var/lib/docker/overlay2/47e7b8a7dd49517cce6375cdd6b220d2b3edbaf117681f4b8123be70d2fb4222/diff:/var/lib/docker/overlay2/1596c7bcceaaebba6409fd2d001a2da103b53c61f3fc947102d1e96203e4da81/diff:/var/lib/docker/overlay2/17109414679c49d4afd3b04de000f7daa01be59b67a152afbc9aadbd7a2f715c/diff:/var/lib/docker/overlay2/26e09f3167a1e7f82b80a6dd144e876800268f14c62bbab272f8eae31f26cb39/diff:/var/lib/docker/overlay2/594754d90364416bf3c81f79ae33c164578f467f9fc2e9b2fa5ebc42b763f2ab/diff",
                "MergedDir": "/var/lib/docker/overlay2/db4b83c9252f558e7cb3451913615daa6aa8fd05e8e7a79c8faea454b6511b1c/merged",
                "UpperDir": "/var/lib/docker/overlay2/db4b83c9252f558e7cb3451913615daa6aa8fd05e8e7a79c8faea454b6511b1c/diff",
                "WorkDir": "/var/lib/docker/overlay2/db4b83c9252f558e7cb3451913615daa6aa8fd05e8e7a79c8faea454b6511b1c/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "dc72e47d2fee",
            "Domainname": "",
            "User": "node",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "APP_DIR=/home/node/app",
                "CONNECTION_TIMEOUT=60000",
                "CHROME_PATH=/usr/bin/google-chrome",
                "HOST=0.0.0.0",
                "IS_DOCKER=true",
                "LANG=C.UTF-8",
                "NODE_ENV=production",
                "PORT=3000",
                "PUPPETEER_CHROMIUM_REVISION=",
                "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true",
                "USE_CHROME_STABLE=false",
                "WORKSPACE_DIR=/home/node/app/workspace"
            ],
            "Cmd": [
                "./start.sh"
            ],
            "Image": "browserless/chrome",
            "Volumes": null,
            "WorkingDir": "/home/node/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "browser": "",
                "com.docker.compose.config-hash": "65016aaeed5553f7f0688e19858b0c7eb18bf7d804cd93eeeae9113b4835987b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "rsshub",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/snakwu/Docker/RSSHub",
                "com.docker.compose.service": "browserless",
                "com.docker.compose.version": "1.25.0",
                "debuggerVersion": "",
                "protocolVersion": "",
                "puppeteerVersion": "",
                "v8Version": "",
                "webkitVersion": ""
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f408a6f038bc67935abfdff41a9bb0ac6b5cbdc4d51536884d9674b96dfd4c57",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/f408a6f038bc",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "rsshub_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "browserless",
                        "dc72e47d2fee"
                    ],
                    "NetworkID": "a470299a561f02a98541eed3c0e51646a77a676c59f4d4835782d492d9921ef5",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by snakwu** [comment]
如果使用browserless/chrome:1.43-chrome-stable，就正常运行

**Comment by TonyRL** [comment]
Please also provide output of `docker image ls` and `docker ps`

**Comment by snakwu** [comment]
@ @TonyRL   谢谢你的回复，问题解决了！
