### ISSUE TITLE
俄罗斯卫星通讯社

### ISSUE THREAD

**Issue by HamadaMasatoshi** [DIYgod/RSSHub#9265]
### 类型

传统媒体

### 网站地址

https://sputniknews.cn/

### 网站描述

俄罗斯卫星通讯社是俄罗斯三大通讯社之一，简称卫星社，前身是2013年撤销的俄罗斯新闻社（简称俄新社）与俄罗斯之声广播电台。卫星社以报道世界政治和经济新闻为主，主要针对外国受众。在其网站和DAB+/DAB、FM上的总播音时长每天超过800个小时。卫星社的英语、西班牙语、阿拉伯语与汉语新闻专线夜以继日发布新闻资讯。在世界各种社交网络上卫星社的关注人数达到1350万人，卫星社网站的每月受众群体总量超过1300万。网站内容除新闻资讯外，还包括摄影报导、现场直播、信息图形、民意调查《卫星∙观点》以及自己的图片库《卫星∙图片》。

### 需要生成什么内容？

需要生成 https://sputniknews.cn/ 每日发布新闻的 Feed ，因为官网不提供。

从卫星社的网址注意到，根据每天的日期，可以看到当天发布的所有新闻。

例如今天2022年3月8号的新闻，都在这个链接下：
https://sputniknews.cn/20220308/

昨天2022年3月7号的新闻则是这个链接：
https://sputniknews.cn/20220307/

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by wft44maqb** [comment]
這個好像是那個。。最近經常散播有關烏克蘭假新聞的那個新聞機構。。。

中國的官媒都是直接引用那些假新聞的。。然後你還想繼續看那些假新聞？。。。。。你這個人還蠻有趣的。哈哈。

**Comment by wft44maqb** [comment]
我都幫你找好了。這些都是中國的大外宣，App Store跟Google Play也都有：
https://play.google.com/store/apps/developer?id=Information+Service&hl=zh_CN&gl=US

**Comment by HamadaMasatoshi** [comment]
> 這個好像是那個。。最近經常散播有關烏克蘭假新聞的那個新聞機構。。。
> 
> 中國的官媒都是直接引用那些假新聞的。。然後你還想繼續看那些假新聞？。。。。。你這個人還蠻有趣的。哈哈。

[法新社](https://github.com/DIYgod/RSSHub/issues/8800)和[日本经济新闻](https://github.com/DIYgod/RSSHub/issues/8800)也是我提的 issue ，新华社在 rsshub 也有[路由](https://github.com/DIYgod/RSSHub/pull/8514)，有趣的人看什么都是有趣的。

**Comment by wft44maqb** [comment]
我講錯了。App Store好像是比較嚴格的，所以他沒有上架App Store。hhh

**Comment by HamadaMasatoshi** [comment]
> 我都幫你找好了。這些都是中國的大外宣，App Store跟Google Play也都有： https://play.google.com/store/apps/developer?id=Information+Service&hl=zh_CN&gl=US
> 
> 你這麼喜歡看有高牆的國家的國營媒體，那你就去看吧。🤣👍🏼

会说这种话的你，跟只看墙内媒体的小粉红，没有本质区别

**Comment by wft44maqb** [comment]
你好像搞錯的我想說的點，但沒關係。你們大概也就是那個樣子的吧。跟我在遊戲裡面遇到的中國玩家，差不多那樣子。哈哈。

**Comment by wft44maqb** [comment]
它是統派的媒體，絕對沒有問題的。但是不要搞假新聞就可以了。。。

或者比較親中國的媒體。甚至只是不反共的？也都沒有問題。

不是說，你一定要反共什麼的。但你絕對不要搞假新聞。。。。。。。。。。

**Comment by wft44maqb** [comment]
如果是你這種想法的話。。你比較喜歡國營媒體的話。。

那我推薦你以下3個比較親共的媒體。但是呢，是沒有那麼傻的親共媒體：
新加坡–8視界
台灣–風傳媒
台灣–UDN

**Comment by HamadaMasatoshi** [comment]
> 你好像搞錯的我想說的點，但沒關係。你們大概也就是那個樣子的吧。跟我在遊戲裡面遇到的中國玩家，差不多那樣子。哈哈。

搞错的是你，上面我已经提到，法新社和日本经济新闻的 issue 也是我提的，你只凭我这次提交，就认为我喜欢这类媒体，这种观点实在偏颇。

在我看来，只看某家或者某类媒体，并对其他家或者其他类媒体存在先入为主的观念，不管是什么政治立场，在我眼中都没有本质区别。

**Comment by HamadaMasatoshi** [comment]
> 你好像搞錯的我想說的點，但沒關係。你們大概也就是那個樣子的吧。跟我在遊戲裡面遇到的中國玩家，差不多那樣子。哈哈。

更何况，我也不会因为今天你一个人的言行，就对使用繁体中文的非大陆人士做什么一刀切的价值判断，与你不同。

**Comment by wft44maqb** [comment]
所以你是沒有底線的？ ̶專̶門̶搞假新聞的極權政府媒體，你也是覺得沒有問題的嗎？那好吧。。。

你依然是覺得「我又不看那些媒體的，就讓需要看、想看的人去看吧。就算那些有不少都是假新聞。」也無所謂？。。。。。。。。

那你可能是另一種極端了，如果你自認不是小粉紅的話。哈哈。

**Comment by wft44maqb** [comment]
我個人是比較希望你是沒有常看這家媒體的（不是說完全不能看，我是說「常看」。），這種媒體的。。。。

可以了。不要再回覆我了。哈哈。就這樣吧。hhh

**Comment by HamadaMasatoshi** [comment]
> 你依然是覺得「我又不看那些媒體的，就讓需要看、想看的人去看吧。就算那些有不少都是假新聞。」也無所謂？。。。。。。。。

你又一次凭你自己的臆测来揣度我的想法，我想我上面说得很清楚，不能只看某家或者某类媒体，也不能对某家或者某类媒体存在先入为主的偏见。我不清楚你接受的国文教育是什么样的水准，导致你能从我的回复中读出这样的意思。

> 所以你是沒有底線的？ ̶專̶門̶搞假新聞的極權政府媒體，你也是覺得沒有問題的嗎？那好吧。。。

用更通俗的说法，俄罗斯卫星通讯社也好，其他国营媒体也好，是否每条新闻都是作假？你认可的媒体，是否每条新闻都客观描述了每一个事件？

“兼听则明，偏听则暗”，看一家媒体的文章，并不代表一定要认同该媒体的观点，从不同媒体的不同视角去看同一个事件，才能让自己有更加清晰的认知。


> 我個人是比較希望你是沒有常在看這家媒體的（不是說完全不能看，我是說「沒有常看」。），這種媒體的。。。。
> 
> 可以了。不要再回覆我了。哈哈。就這樣吧。hhh..........................................................................

很抱歉让你失望了，你认可的那些媒体跟你不认可的那些媒体，我都经常看。是否继续回复你，是我的自由，不是由你来决定，特别是当你觉得你跟那些不让民众说话的政府不是同类时。

**Comment by wft44maqb** [comment]
「是否继续回复你，是我的自由，不是由你来决定，特别是当你觉得你跟那些不让民众说话的政府不是同类时。」

不知道你是否也會敢跟你的政府這樣說呢，哈哈。沒有關係。我剛剛想說的是，太尷尬了，還是算了吧？但如果你想繼續談的話，絕對沒有問題。我都可以。🤣👍🏼

**Comment by zhuangyin8** [comment]
> 「是否继续回复你，是我的自由，不是由你来决定，特别是当你觉得你跟那些不让民众说话的政府不是同类时。」
> 
> 不知道你是否也會敢跟你的政府這樣說呢，哈哈。沒有關係。我剛剛想說的是，太尷尬了，還是算了吧？但如果你想繼續談的話，絕對沒有問題。我都可以。🤣👍🏼

假新聞谁也没有美帝走狗台独1450专业
