### ISSUE TITLE
Foresight News RSS需求

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#9268]
### 类型

新媒体

### 网站地址

https://foresightnews.pro/

### 网站描述

Web 3.0 & 区块链时代全球资讯前沿站，新闻质量较高

### 需要生成什么内容？

1. 文章：https://foresightnews.pro/article ，期望能包含tag，另外里面混排进了快讯，期望剔除掉（区别在于url，以及类型不一样），具体见附图
2. 快讯：https://foresightnews.pro/news
3. 专栏：https://foresightnews.pro/column/detail/xxxxxx ，最后为专栏id，例如https://foresightnews.pro/column/detail/18

### 额外描述

附图说明
![image](https://user-images.githubusercontent.com/2727281/157196417-18ca8790-cb20-465a-bf01-32119a10c227.png)

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by lylunula** [comment]
> <img alt="@nczitzk" width="40" height="40" src="https://avatars.githubusercontent.com/u/42264778?s=88&amp;u=1f4d2e21e93e71bbcd0bc9c035a22af09464209d&amp;v=4">

太高效了，感谢~
不过有个小问题，文章：https://foresightnews.pro/article ，这个页面里面其实混杂了文章+快讯，希望把快讯剔除掉（要不然就跟另一个feed重复了，而且阅读效率不高），剔除策略就是：

文章url特征是：https://foresightnews.pro/article/detail/xxx
快讯url特征是：https://foresightnews.pro/news/detail/xxx

**Comment by nczitzk** [comment]
> @nczitzk
> 
> 太高效了，感谢~ 不过有个小优化麻烦帮忙看看，文章feed：https://foresightnews.pro/article ，这个页面里面其实混杂了文章+快讯，希望把快讯剔除掉（要不然就跟另一个feed重复了，而且阅读效率不高），剔除策略就是：
> 
> 文章url特征是：https://foresightnews.pro/article/detail/xxx 快讯url特征是：https://foresightnews.pro/news/detail/xxx
> 
> 感谢啦~

Foresight News 首页仅提供了同时返回文章和快讯的 API，其实还需要分别处理才可以合并汇总在一起 😂

当时这么处理的原因是：
1. 希望路由和首页时间流推送内容和顺序保持一致；
2. 如果通过该 API 筛选出文章，则该路由返回的文章数量是不确定的，因为单次获取的文章和快讯的比例是无法预知的。

根据你的需求，我的想法是增加一个 **仅提供文章** 的路由 [/foresightnews/article](https://rsshub.app/foresightnews/article)，同时保留 **首页** 路由（汇总文章和快讯）[/foresightnews](https://rsshub.app/foresightnews) 和 **快讯** 路由 [/foresightnews/news](https://rsshub.app/foresightnews/news)。

#9295

**Comment by yyzfish** [comment]
这个似乎失效了

**Comment by 0xshawn** [comment]
确实失效了
