### ISSUE TITLE
Error in 东方我乐多丛志

### ISSUE THREAD

**Issue by vcup** [DIYgod/RSSHub#9271]
### Routes

/touhougarakuta

### Full routes

/touhougarakuta/cn/interviews

### Related documentation

https://docs.rsshub.app/anime.html#dong-fang-wo-le-duo-cong-zhi

### What is expected?

正常加载rss

### What is actually happening?

jp语言全页面阵亡
interviews页面三语全阵亡

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

两例错误页面
```shell

Route requested: /touhougarakuta/cn/interviews
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /touhougarakuta/cn/interviews
Node version: v16.3.0
```

```
Error message: getaddrinfo ENOTFOUND jp.touhougarakuta.com: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /touhougarakuta/jp/news
Node version: v16.3.0
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by vcup** [comment]
@ttyfly 我在路由页面看到是您在维护

**Comment by ttyfly** [comment]
感谢您的反馈。
1. 关于日语源的问题：日语应填写 ja 而不是 jp。
不过[https://rsshub.app/touhougarakuta/ja/index](https://rsshub.app/touhougarakuta/ja/index)现在不能正常运行，应该是部分文章的格式问题。
2. 关于 interview：官网的 `/interviews` 似乎迁移到了 `/tags/interviews`，应该不难修复。

我最近比较忙，周末再看看。或者您有能力的话可以先给修了（那时候我代码写得挺乱的，见谅）。

**Comment by vcup** [comment]
不好意思，拼写错误闹笑话了(逃

**Comment by vcup** [comment]
我会尝试阅读相关代码，因为这方面基本没有学习过，超出我能力范围了的。但也应该能让我受益匪浅的
