### ISSUE TITLE
明慧網

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#9278]
### 类型

传统媒体

### 网站地址

https://www.minghui.org/

### 网站描述

> 明慧網是由法輪大法學會主辦的網站，於1999年6月21日創辦，6月25日正式開通。該網站稱其旨在於通過直接來自中國大陸的第一手資料，提供全世界法輪功修煉者在修煉方面的信息。有時國際媒體會引用其報導。。聯合國人權報告多次引用大量明慧網案例譴責中共對法輪功學員任意監禁、酷刑致死，並要求停止迫害。 [維基百科](https://zh.wikipedia.org/zh-tw/%E6%98%8E%E6%85%A7%E7%BD%91)

> 法輪大法明慧網成立于九九年六月。明慧網的主旨在于用來自中國大陸的第一手資料，揭露中共對法輪功的迫害，講清法輪功真相，彌補迫害給大陸大法弟子修煉環境帶來的損失。為反迫害、講真相、福益有緣，明慧網在大陸法輪功學員中建立了廣泛的信息渠道，每天提供迫害真相、法輪功學員的修煉心得、海外報道、報紙期刊廣播電視及多語種明慧網等等真相信息。

### 需要生成什么内容？

- https://www.minghui.org/
- https://big5.minghui.org/

### 额外描述

某人曾說：「“兼听则明，偏听则暗”，看一家媒体的文章，并不代表一定要认同该媒体的观点，从不同媒体的不同视角去看同一个事件，才能让自己有更加清晰的认知。」

這個想法乍聽一下是非常好的。但我還是覺得人要有基本底線。至少以前的我是這樣想。

怎麼說呢？。。我以前是不太喜歡這種想法的。我以前也有把它法輪功媒體，還有中國黨媒加到我Google News裡面的黑名單。但他既然這樣說了，那試試也無妨。

---

同時我也很好奇到底又有幾個人是真的能夠接受這樣子的呢？hhh

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by guangwenzhu** [comment]
已存在 http://www.minghui.org/index.xml

**Comment by wft44maqb** [comment]
> 已存在 http://www.minghui.org/index.xml

那你們把它當作是「優先度：低」的就可以了。

（以前就想這樣說了。hhhh）
