### ISSUE TITLE
大紀元時報

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#9279]
### 类型

传统媒体

### 网站地址

https://www.epochtimes.com/

### 网站描述

> 《大紀元時報》是一家總部設在美國的國際多語種報紙和媒體。該報由法輪功學員於2000年在紐約創辦，中央社曾引述該報稱獨立於黨派及商業集團之外，宗旨為「維護人權普世價值、揭露中國共產黨政權極力隱瞞的新聞真相」。 [維基百科](https://zh.wikipedia.org/zh-tw/%E5%A4%A7%E7%BA%AA%E5%85%83%E6%97%B6%E6%8A%A5)

> 包括美國中文媒體在內的海外中文媒體中，大紀元從美國中文報紙開始，現在不僅變成了海外最大中文媒體，美國最有影響力中文媒體，同時也是全球最大中文媒體，新聞即時權威多語種，報紙發行美國、加拿大、歐洲、澳洲、中國、台灣、香港，分佈在紐約、洛杉磯、舊金山、華盛頓DC、亞特蘭大、邁阿密、芝加哥、休斯頓、​​達拉斯、西雅圖、溫哥華、多倫多、悉尼、墨爾本、倫敦、巴黎、柏林、法蘭克福、東京、首爾，內容包括要聞、 社區生活、傳統文化、法律財經、教育移民、醫療健康、藝術時尚、旅遊地產、美食、娛樂體育。

### 需要生成什么内容？

- https://www.epochtimes.com/
- https://www.epochtimes.com/b5/
- https://www.epochtimes.com.tw/

### 额外描述

某人曾說：「“兼听则明，偏听则暗”，看一家媒体的文章，并不代表一定要认同该媒体的观点，从不同媒体的不同视角去看同一个事件，才能让自己有更加清晰的认知。」

這個想法乍聽一下是非常好的。但我還是覺得人要有基本底線。至少以前的我是這樣想。

怎麼說呢？。。我以前是不太喜歡這種想法的。我以前也有把它法輪功媒體，還有中國黨媒加到我Google News裡面的黑名單。但他既然這樣說了，那試試也無妨。

---

同時我也很好奇到底又有幾個人是真的能夠接受這樣子的呢？hhh

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://www.epochtimes.com/b5/nsc413.xml
