### ISSUE TITLE
美国之音中文网

### ISSUE THREAD

**Issue by wft44maqb** [DIYgod/RSSHub#9281]
### 类型

传统媒体

### 网站地址

https://www.voachinese.com/

### 网站描述

> 美國之音成立於1942年2月，是美國政府對外設立和資助的國有非軍事國際廣播宣傳機構，由美國國際媒體署管理，經費由美國國會撥款，美國納稅人出資。旗下擁有廣播電台與電視台，總部座落在首都華盛頓。 [維基百科](https://zh.wikipedia.org/zh-tw/%E7%BE%8E%E5%9B%BD%E4%B9%8B%E9%9F%B3)

> 美国之音是您的可靠和准确的有关中国、美国和国际新闻的来源。欢迎浏览美国之音中文网阅读最新的报道，收听收看美国之音电视广播节目或练习您的英语。

### 需要生成什么内容？

- https://www.voachinese.com/
- https://www.voacantonese.com/

![image](https://user-images.githubusercontent.com/86122516/157441295-0f4bc5bc-963c-459a-8192-c0b61403e230.png)

### 额外描述

某人曾說：「“兼听则明，偏听则暗”，看一家媒体的文章，并不代表一定要认同该媒体的观点，从不同媒体的不同视角去看同一个事件，才能让自己有更加清晰的认知。」

這個想法乍聽一下是非常好的。但我還是覺得人要有基本底線。至少以前的我是這樣想。

怎麼說呢？。。我以前是不太喜歡這種想法的。我以前也有把它法輪功媒體，還有中國黨媒加到我Google News裡面的黑名單。但他既然這樣說了，那試試也無妨。

---

同時我也很好奇到底又有幾個人是真的能夠接受這樣子的呢？hhh

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by guangwenzhu** [comment]
已存在 https://www.voachinese.com/rssfeeds

请在提交前确认源站没有提供 RSS ，否则 issue 后续将被 maintainer 直接关闭
