### ISSUE TITLE
台灣事實查核中心

### ISSUE THREAD

**Issue by LiuYi0526** [DIYgod/RSSHub#9284]
### 类型

传统媒体

### 网站地址

https://tfc-taiwan.org.tw/

### 网站描述

看見真實，才能打造美好台灣

### 需要生成什么内容？

[最新查核報告](https://tfc-taiwan.org.tw/articles/report)

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #8411
