### ISSUE TITLE
飞客论坛路由报错

### ISSUE THREAD

**Issue by hermer** [DIYgod/RSSHub#9313]
### 路由地址

/flyertea/creditcard/:bank

### 完整路由地址

/flyert/creditcard/zhongxin

### 相关文档

https://docs.rsshub.app/travel.html#fei-ke-cha-guan

### 预期是什么？

可以正常抓取

### 实际发生了什么？

应该是论坛的路由路径变化了，导致抓取报错

Route requested: /flyert/creditcard/zhongxin
Error message: wrong path

### 部署

自建

### 额外信息

```shell
Route requested: /flyert/creditcard/zhongxin
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /flyert/creditcard/zhongxin
Node version: v14.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by hermer** [comment]
@nczitzk

**Comment by Fatpandac** [comment]
https://rss.fatpandac.com/flyert/creditcard/zhongxin
正常抓取呀

**Comment by TonyRL** [comment]
https://rsshub.app/flyert/creditcard/zhongxin
also works on demo instance

**Comment by hermer** [comment]
> https://rss.fatpandac.com/flyert/creditcard/zhongxin 正常抓取呀

我也是最新版自建为啥不行

**Comment by Fatpandac** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/30423976/158094833-a18f45b1-50f8-483d-9981-5cefbc638a8e.png">
查看一下你的版本是否和仓库的版本相同
