### ISSUE TITLE
JAVDB路由异常

### ISSUE THREAD

**Issue by JamYiz** [DIYgod/RSSHub#9332]
### 路由地址

/javdb

### 完整路由地址

/javdb/series/ZNvA

### 相关文档

https://docs.rsshub.app/multimedia.html#javdb-zhu-zhu-ye

### 预期是什么？

自建能够正常访问，显示内容

### 实际发生了什么？

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

### 部署

自建

### 部署相关信息

CentOS 8.3.2011 x86_64(Py3.7.9),Node version: v14.19.0

### 额外信息

```shell
该订阅极易触发反爬，均在短时间内被ban。且在#9085中提到加上 ?domain=javdb36.com仍然会触发反爬机制，多个自建均失效。
同时展示的路由地址也已长期失效。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by junfengP** [comment]
既然是严格反扒，又有多个可用代替域名。

不如做一个?domains=a.com,b.com,c.com 的参数

访问时基于顺序重试 or 基于随机策略选择domain

**Comment by JamYiz** [comment]
> You can use `?domain=` from `javdb30.com` to `javdb38.com` as of replying.
> 
> This route has a strict anti-crawler policy badge in docs which means it can get unreliable or even be blocked for the demo instance.
> 
> `/javdb/series/ZNvA` is indeed working fine on self-hosted instance https://rsshub.up.railway.app/javdb/series/ZNvA

Thanks for the reply, but the `?domain` parameter didn't work for me. My self-hostedd instance returned a 403 error after accessing it for a period of time. and using   [javdb30.com](https://javdb30.com/) to javdb38.com also got 403 error. I tested 3 instance，they all have this problem.

**Comment by JamYiz** [comment]
> 既然是严格反扒，又有多个可用代替域名。
> 
> 不如做一个?domains=a.com,b.com,c.com 的参数
> 
> 访问时基于顺序重试 or 基于随机策略选择domain

不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。

**Comment by lychichem** [comment]
> > 既然是严格反扒，又有多个可用代替域名。
> > 不如做一个?domains=a.com,b.com,c.com 的参数
> > 访问时基于顺序重试 or 基于随机策略选择domain
> 
> 不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。

怀疑有以下可能：
1、你没加爬取频率限制导致爬太快被ban实例，这有可能能通过加大缓存解决；
2、你的vps IP段整个被ban了，这个靠自己是没啥好办法了

**Comment by lychichem** [comment]
> > 既然是严格反扒，又有多个可用代替域名。
> > 
> > 不如做一个?domains=a.com,b.com,c.com 的参数
> > 
> > 访问时基于顺序重试 or 基于随机策略选择domain
> 
> 不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。

另外你的？和其他人的?不一样，你打成中文问号了，应该是英文问号

**Comment by JamYiz** [comment]
在实际使用中没有打错，比如我将示例地址加上最新路由也会返回403错误https://rsshub.app/javdb?domain=javdb39.com/rankings

**Comment by JamYiz** [comment]
> > > 既然是严格反扒，又有多个可用代替域名。
> > > 
> > > 不如做一个?domains=a.com,b.com,c.com 的参数
> > > 
> > > 访问时基于顺序重试 or 基于随机策略选择domain
> > 
> > 不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。
> 
> 另外你的？和其他人的?不一样，你打成中文问号了，应该是英文半角问号

在实际使用中没有打错，比如我将示例地址加上最新路由也会返回403错误https://rsshub.app/javdb?domain=javdb39.com/rankings

**Comment by JamYiz** [comment]
> > > 既然是严格反扒，又有多个可用代替域名。
> > > 不如做一个?domains=a.com,b.com,c.com 的参数
> > > 访问时基于顺序重试 or 基于随机策略选择domain
> > 
> > 不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。
> 
> 怀疑有以下可能：
> 1、你没加爬取频率限制导致爬太快被ban实例，这有可能能通过加大缓存解决；
> 2、你的vps IP段整个被ban了，这个靠自己是没啥好办法了
感谢回复
可能是第一个问题，我去试试加缓存。第二个的话，是用的不同的服务器搭建的应该不会有这个问题吧。

**Comment by JamYiz** [comment]
> > > 既然是严格反扒，又有多个可用代替域名。
> > > 不如做一个?domains=a.com,b.com,c.com 的参数
> > > 访问时基于顺序重试 or 基于随机策略选择domain
> > 
> > 不知道为什么在实际使用中，提供`?domain`参数并没有起作用。仍然会返回403错误。
> 
> 怀疑有以下可能：
> 1、你没加爬取频率限制导致爬太快被ban实例，这有可能能通过加大缓存解决；
> 2、你的vps IP段整个被ban了，这个靠自己是没啥好办法了

感谢回复
可能是第一个问题，我去试试加缓存。第二个的话，是用的不同的服务器搭建的应该不会有这个问题吧。
