### ISSUE TITLE
Threads are excluded by `excludeReplies=1` in Twitter feed

### ISSUE THREAD

**Issue by srezasm** [DIYgod/RSSHub#9340]
### Routes

/twitter/user

### Full routes

/twitter/user/SamouraiWallet/excludeReplies=1

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter

### What is expected?

When the `excludeReplies` parameter is set to 1, It's expected to exclude only the replies, but it excludes the following threads of a tweet as well.

What I recommend is adding another parameter to exclude threads and tag following tweets in a thread as RE or TR.

Also, it would be great if you had added the parent (replied tweet or the head of the thread tweet) link somewhere in the feed item like another tag called `parent id`

### What is actually happening?

With the `excludeReplies=1` parameter, it only shows the header tweet of a thread and excludes all the following tweets in the thread.

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
this is a example with `excludeReplies=0`

<!-- #1: The  follower of thread -->
<item>
    <title>
        <![CDATA[ ↩️ Nowadays everyone has to publicly pretend to care about poor foreigners while they backstab their coworkers at home. ]]>
    </title>
    <description>
        <![CDATA[ ↩️ Nowadays everyone has to publicly pretend to care about poor foreigners while they backstab their coworkers at home. ]]>
    </description>
    <pubDate>Fri, 18 Mar 2022 05:55:56 GMT</pubDate>
    <guid isPermaLink="false">https://twitter.com/eric_lombrozo/status/1504698095887548419</guid>
    <link>https://twitter.com/eric_lombrozo/status/1504698095887548419</link>
    <author>
        <![CDATA[ 👑 ]]>
    </author>
</item>

<!-- #2: another tweet -->
<item>
    ...
</item>

<!-- #3: The header of thread -->
<item>
    <item>
        <title>
            <![CDATA[ Remember when wars were simple? We could just go recruit a bunch of men and plunder and pillage and raze neighboring villages to the ground and nobody... ]]>
        </title>
        <description>
            <![CDATA[ Remember when wars were simple? We could just go recruit a bunch of men and plunder and pillage and raze neighboring villages to the ground and nobody else would find out until we were already firmly in charge of the situation. Ah, those were the days... ]]>
        </description>
        <pubDate>Fri, 18 Mar 2022 05:30:55 GMT</pubDate>
        <guid isPermaLink="false">https://twitter.com/eric_lombrozo/status/1504691797867446273</guid>
        <link>https://twitter.com/eric_lombrozo/status/1504691797867446273</link>
        <author>
            <![CDATA[ 👑 ]]>
        </author>
    </item>


The same example with`excludeReplies=1` only shows the #1 tweet
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Rongronggg9** [comment]
This is exactly how Twitter API deals with requests from RSSHub and RSSHub does not perform a filter. There may be some workarounds, and I've figured out one. I may implement it sooner or later, but not now.

**Comment by Rongronggg9** [comment]
Force using Web API on instances with Developer API configured should help solve the issue now.

```
excludeReplies=1&forceWebApi=1
```
