### ISSUE TITLE
Quicker动作今日更新

### ISSUE THREAD

**Issue by PaulHerrero** [DIYgod/RSSHub#9346]
### 类型

程序更新

### 网站地址

https://getquicker.net/Share/Recent

### 网站描述

Quicker动作今日更新列表

### 需要生成什么内容？

动作名称，ICON，动作描述，动作链接

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nczitzk** [comment]
WIP
