### ISSUE TITLE
最终幻想 14 国服 路由无法使用

### ISSUE THREAD

**Issue by Ruikoto** [DIYgod/RSSHub#9368]
### 路由地址

/ff14/zh

### 完整路由地址

/ff14/zh/news

### 相关文档

https://docs.rsshub.app/forecast.html#zui-zhong-huan-xiang-14-zui-zhong-huan-xiang-14-guo-fu

### 预期是什么？

正常订阅

### 实际发生了什么？

Looks like something went wrong
Route requested: /ff14/zh
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /ff14/zh
Node version: v14.18.1
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github

### 部署

自建

### 部署相关信息

docker:latest

### 额外信息

```shell
Looks like something went wrong
Route requested: /ff14/zh
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /ff14/zh
Node version: v14.18.1
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
[官方 demo](https://rsshub.app/ff14/zh) 可以正常访问，能否提供（检查）一下你当前版本的 git commit hash 值

**Comment by Ruikoto** [comment]
> [官方 demo](https://rsshub.app/ff14/zh) 可以正常访问，能否提供（检查）一下你当前版本的 git commit hash 值

Git Hash:970cf5e

**Comment by Ruikoto** [comment]
Epic免费游戏的路由也出现了同样的问题，怀疑是相同原因导致的，我也贴一下：

## 路由地址
/epicgames/freegames

## 相关文档
https://docs.rsshub.app/game.html#epic-games-store

## 错误信息
```
Route requested: /epicgames/freegames
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /epicgames/freegames
Node version: v14.18.1
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

**Comment by Fatpandac** [comment]
请更新到最新的版本

**Comment by Ruikoto** [comment]
> 请更新到最新的版本

好的谢谢，我尝试一下！

**Comment by Ruikoto** [comment]
问题已解决，是因为我在群晖中Docker拉取的Latest是最旧版本的镜像，所以反复拉取最新的都只能获取到以前的镜像，手动选择版本拉取后解决了问题，感谢大佬的帮助🤗
