### ISSUE TITLE
华人成人新闻情报站

### ISSUE THREAD

**Issue by stankyoztc** [DIYgod/RSSHub#9370]
### Category

BBS

### Website URL

http://www.playno1.com/

### Website description

对日本小电影最新的女优和最新即将推出的番号做新闻播送
还有最新的情趣小游戏

### What content should be included?

AV：
- [ ] 全部新闻
- [ ] AV新闻
- [ ] AV导览

情趣
- [ ] 全部新闻
- [ ] 体验报告
- [ ] 情趣新闻
- [ ] 情趣研究所

### Additional description

https://github.com/DIYgod/RSSHub/issues/3203
已经提供了女优专栏文章的RSS

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by HamadaMasatoshi** [comment]
提交 issue 前请适当检索，民间制作的全文 feed 已存在12年：

> 第一次发帖，首先向大家问好！也祝贺AVNO1改版成功！:)
> 
> 小弟十分愚钝，没有找到改版后的RSS输出的地址，请知道的告诉一声，谢谢！
> 
> 更新
> 
> [2010-03-28] 鉴于AVNO1官方暂停RSS，本人制作了一个非官方的RSS，地址在[http://feeds.feedburner.com/avnoone](https://feeds.feedburner.com/avnoone)，有需要的朋友请订阅。这个RSS保留了原文作者和发表时间，输出全文，目前每小时更新一次。
> 
> [2010-06-10] 有朋友希望H No.1和动漫No.1也能有RSS，今天我把这两个RSS也做出来了，地址分别是[http://feeds.feedburner.com/hnoone](https://feeds.feedburner.com/hnoone)（H No.1）和 ~[http://feeds.feedburner.com/cnoone](https://feeds.feedburner.com/cnoone)（动漫No.1）~ 。它们会和AV No.1的RSS一并更新。
> 
> [2010-07-08] 我为好片推荐栏目做了一个RSS，给需要的朋友，地址是 ~[http://feeds.feedburner.com/avideo0](https://feeds.feedburner.com/avideo0)~ 。
> 
> [2013-05-17] 恭喜AVNO1再次改版（应该改口叫PLAYNO1了）。小弟的非官方RSS已经更新，目前能全文输出AV频道（包括新闻、话题和导览）的所有文章，更新频率依然是每小时一次。待测试稳定后，[情趣](http://stno1.playno1.com/)频道的文章会在原来H No.1的RSS更新。另外，原先的动漫No.1和好片推荐的RSS小弟已经放弃，见谅。

http://stno1.playno1.com/thread-2133-1-1.html

**Comment by lychichem** [comment]
> 提交 issue 前请适当检索，民间制作的全文 feed 已存在12年：
> 
> > 第一次发帖，首先向大家问好！也祝贺AVNO1改版成功！:)
> > 
> > 小弟十分愚钝，没有找到改版后的RSS输出的地址，请知道的告诉一声，谢谢！
> > 
> > 更新
> > 
> > [2010-03-28] 鉴于AVNO1官方暂停RSS，本人制作了一个非官方的RSS，地址在[http://feeds.feedburner.com/avnoone](https://feeds.feedburner.com/avnoone)，有需要的朋友请订阅。这个RSS保留了原文作者和发表时间，输出全文，目前每小时更新一次。
> > 
> > [2010-06-10] 有朋友希望H No.1和动漫No.1也能有RSS，今天我把这两个RSS也做出来了，地址分别是[http://feeds.feedburner.com/hnoone](https://feeds.feedburner.com/hnoone)（H No.1）和 ~[http://feeds.feedburner.com/cnoone](https://feeds.feedburner.com/cnoone)（动漫No.1）~ 。它们会和AV No.1的RSS一并更新。
> > 
> > [2010-07-08] 我为好片推荐栏目做了一个RSS，给需要的朋友，地址是 ~[http://feeds.feedburner.com/avideo0](https://feeds.feedburner.com/avideo0)~ 。
> > 
> > [2013-05-17] 恭喜AVNO1再次改版（应该改口叫PLAYNO1了）。小弟的非官方RSS已经更新，目前能全文输出AV频道（包括新闻、话题和导览）的所有文章，更新频率依然是每小时一次。待测试稳定后，[情趣](http://stno1.playno1.com/)频道的文章会在原来H No.1的RSS更新。另外，原先的动漫No.1和好片推荐的RSS小弟已经放弃，见谅。
> 
> http://stno1.playno1.com/thread-2133-1-1.html

这个rss我在用，只是有个奇怪的点，就是它输出的内容有些rss阅读器不能正确排版，比如newsflow订阅这个源，不抓取全文的时候是只有一行字，没图没换行，抓取全文的时候是只有图没字，但是feedly，inoreader和fluentreader是正常的
