### ISSUE TITLE
Response code 404: /nature/research/nature

### ISSUE THREAD

**Issue by alienzj** [DIYgod/RSSHub#9383]
### Routes

/nature/research/nature

### Full routes

https://rsshub.app/nature/research/nature

### Related documentation

https://docs.rsshub.app/journal.html#nature-xi-lie

### What is expected?

Return a XML document which contains the nature rss.

### What is actually happening?

```
Looks like something went wrong

Route requested: /nature/research/nature

Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue:
Path: /nature/research/nature
Node version: v16.3.0
Git Hash: c91a4cd
```

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Nothing.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by cui-2017** [comment]
使用自建同样会404
https://rss-sci.herokuapp.com/nature/research/nature

**Comment by alienzj** [comment]
@TonyRL Still meet error.
![image](https://user-images.githubusercontent.com/8847420/170404019-026d057b-2cf7-4102-816b-73f4d7db15a9.png)

**Comment by TonyRL** [comment]
/test
```routes
/nature/research/nature
```

**Comment by TonyRL** [comment]
/test
```routes
/nature/research/nature
```
