### ISSUE TITLE
weibo 微博可不可以把评论也一起爬下来

### ISSUE THREAD

**Issue by lalasou** [DIYgod/RSSHub#9392]
### 这是一个什么样的功能？

weibo微博 想把微博和评论一起显示出来

### 这个功能可以解决什么问题？

显示微博评论

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by lalasou** [comment]
@Rongronggg9

**Comment by Rongronggg9** [comment]
这么做意义不大：
- 评论会变化
- 需要额外抓取
- 抓取内容会被缓存，缓存生效期间不会更新，如果 RSS 一直有人访问，则缓存永远不会更新（除非特别调降内容缓存的有效期，这么做可导致反爬）
- 抓取到的评论与抓取该微博的时间距离微博发布时间的时间差有关
  - 如果抓取该微博时该微博刚发布，显然抓取不到任何评论

**Comment by lalasou** [comment]
> 这么做意义不大：
> - 评论会变化
> - 需要额外抓取
> - 抓取内容会被缓存，缓存生效期间不会更新，如果 RSS 一直有人访问，则缓存永远不会更新（除非特别调降内容缓存的有效期，这么做可导致反爬）
> - 抓取到的评论与抓取该微博的时间距离微博发布时间的时间差有关
>   - 如果抓取该微博时该微博刚发布，显然抓取不到任何评论

@Rongronggg9 谢谢大佬回复
1：这个评论不一定要很及时，下次刷新时候有就行了
2：这个可不可以做一个备选参数  需要有评论可以有

有些评论其实比微博还有意思，不能保存有些可惜

如果 过了缓存时间 有评论了，刷新请求可不可以把评论也弄下来？

**Comment by Rongronggg9** [comment]
> > 这么做意义不大：
> > 
> > * 评论会变化
> > * 需要额外抓取
> > * 抓取内容会被缓存，缓存生效期间不会更新，如果 RSS 一直有人访问，则缓存永远不会更新（除非特别调降内容缓存的有效期，这么做可导致反爬）
> > * 抓取到的评论与抓取该微博的时间距离微博发布时间的时间差有关
> >   
> >   * 如果抓取该微博时该微博刚发布，显然抓取不到任何评论
> 
> @Rongronggg9 谢谢大佬回复 1：这个评论不一定要很及时，下次刷新时候有就行了 2：这个可不可以做一个备选参数 需要有评论可以有
> 
> 有些评论其实比微博还有意思，不能保存有些可惜
> 
> 如果 过了缓存时间 有评论了，刷新请求可不可以把评论也弄下来？

RSSHub 没有主动刷新缓存的 feature。每次缓存命中都会给内容缓存续期，比如说内容缓存的有效期是 2h，只要 2h 内有人访问过这个 RSS，RSSHub 读取了这个缓存，2h 就会从头开始计算。所以唯一的解决方案就是自建、调降内容缓存有效期低于 RSS 阅读器检查的间隔。

**Comment by lalasou** [comment]
大佬  就是自建的  
求给个更新   🤗

**Comment by lalasou** [comment]
谢谢大佬  大佬最棒😬🤗

**Comment by lalasou** [comment]
@Rongronggg9 @Rongronggg9 
大佬
貌似长微博会 不全  只有一部分？

**Comment by Rongronggg9** [comment]
> @Rongronggg9 @Rongronggg9 大佬 貌似长微博会 不全 只有一部分？

一般是由于微博限制了这条微博在游客状态下的全文访问

**Comment by lalasou** [comment]
好吧
