### ISSUE TITLE
作者你好，知乎用户动态能细分下只订阅用户回答吗？

### ISSUE THREAD

**Issue by jin6220** [DIYgod/RSSHub#94]
用户动态
举例: https://rss.now.sh/zhihu/people/activities/diygod

路由: /zhihu/people/activities/:id

参数: id，用户 id，可在用户主页 URL 中找到

#########################################
关注某人只是想看他回答的问题。
而动态会看到各种领域的内容
不太喜欢知乎这种社交做法所以才觉得靠rss订阅用户回答是个解决办法
所以希望能细分下，有订阅用户回答的功能选项。

**Comment by DIYgod** [comment]
已在计划中 https://github.com/DIYgod/RSSHub/issues/17

**Comment by DIYgod** [comment]
Done. 3398fdec327530735f2dfd6b08ad292bc0654d46
