### ISSUE TITLE
appstore 的应用更新日志会出现 undefined 

### ISSUE THREAD

**Issue by hillerliao** [DIYgod/RSSHub#940]
appstore 的应用更新日志会出现 标题和摘要均为 undefined 的记录，在 inoreader 阅读器上能看到这条item，但再去看 rss 地址，已经没有这一条了。

举例
钠镁股票的更新日志 https://rsshub.app/appstore/update/cn/id1297191884 
<lastBuildDate>Sun, 21 Oct 2018 00:58:40 GMT</lastBuildDate> 凌晨出现了一条 undefined 的记录，但 app 实际并没有在20日更新过，最新的一次更新日志是 2018年10月19日。

**Comment by HenryQW** [comment]
LGTM:
![image](https://user-images.githubusercontent.com/5896343/47285301-4c0c4d80-d5e2-11e8-9bc0-8632c1d90039.png)

**Comment by DIYgod** [comment]
暂时无法复现
