### ISSUE TITLE
虎扑国际足球

### ISSUE THREAD

**Issue by eliotlyn** [DIYgod/RSSHub#9400]
### 类型

新媒体

### 网站地址

https://m.hupu.com/soccer 

### 网站描述

虎扑国际足球新闻

### 需要生成什么内容？

原路由/hupu/dept/soccer 可能由于网址变化已无法获取内容更新

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nczitzk** [comment]
WIP
