### ISSUE TITLE
华硕路由器固件更新

### ISSUE THREAD

**Issue by xieft** [DIYgod/RSSHub#9401]
### 类型

程序更新

### 网站地址

https://www.asus.com.cn/Networking-IoT-Servers/WiFi-Routers/ASUS-Gaming-Routers/RT-AX88U/HelpDesk_BIOS/

### 网站描述

华硕路由器固件更新页面，这里以RT-AX88U这款型号作为例子。

### 需要生成什么内容？

路由器更新项目内容

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by Fatpandac** [comment]
WIP

**Comment by xieft** [comment]
> WIP

这个是不是还有什么问题，目前无法订阅“https://rsshub.app/asus/bios/RT-AX88U”，打开这个页面显示：
Error message: wrong path
Helpful Information to provide when opening issue:
Path: /asus/bios/RT-AX88U
Node version: v16.3.0
Git Hash: 33eb860

**Comment by Fatpandac** [comment]
可能是因为缓存的问题？
其他的[相同格式的路由](https://rsshub.app/asus/bios/RT-AX92U)可以正常访问。

**Comment by xieft** [comment]
> 可能是因为缓存的问题？ 其他的[相同格式的路由](https://rsshub.app/asus/bios/RT-AX92U)可以正常访问。

试了一下，的确除了RT-AX88U这个型号其它都没问题，请问这种情况要怎么解决呢？是不是等一段时间就自己好了😂

**Comment by Fatpandac** [comment]
等一段时间看看吧，目前猜测是缓存导致的

**Comment by xieft** [comment]
把“https://rsshub.app/asus/bios/RT-AX88U”改成“https://rsshub.app/asus/bios/rt-ax88u”，用型号大写改成小写的方式曲线救国，现在可以了，谢谢🙏

**Comment by xieft** [comment]
> 等一段时间看看吧，目前猜测是缓存导致的

你好，我用telegram 机器人（https://t.me/rss2tg_bot）订阅这个链接（https://rsshub.app/asus/bios/RT-AX88U）
会出现以下这种情况：抓不到最新推送。请问这个问题是链接问题，还是这个订阅机器人的问题？
![image](https://user-images.githubusercontent.com/35829258/189514854-be9a57f1-056a-442a-8242-5e4de155daa6.png)

**Comment by Fatpandac** [comment]
这个可能需要修改一下 `guid `
