### ISSUE TITLE
衡阳日报的RSS

### ISSUE THREAD

**Issue by 553059210** [DIYgod/RSSHub#9415]
### 类型

传统媒体

### 网站地址

http://epaper.hyqss.cn/html/2022-03/29/node_1.htm?v=1

### 网站描述

衡阳日报的电子版。
这是请求提交日的页面网址，每天网址都在变。

### 需要生成什么内容？

希望能对于衡阳日报每日的每篇文章进行推送。

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by nczitzk** [comment]
WIP
