### ISSUE TITLE
jimbenton.com漫画网站

### ISSUE THREAD

**Issue by q1lon** [DIYgod/RSSHub#9422]
### Category

Pciture

### Website URL

http://www.jimbenton.com/

### Website description

漫画网站

### What content should be included?

http://www.jimbenton.com/comics
下面更新的漫画内容

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by Fatpandac** [comment]
feed://www.jimbenton.com/page14/files/feed.xml
网站官方 RSS
