### ISSUE TITLE
twitter 用户喜欢列表失效

### ISSUE THREAD

**Issue by i2yeah** [DIYgod/RSSHub#9423]
### 路由地址

https://rsshub.app/twitter

### 完整路由地址

https://rsshub.app/twitter/likes/DIYgod

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

返回用户喜欢列表

### 实际发生了什么？

无法订阅

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: Unable to verify your credentials
Helpful Information to provide when opening issue:
Path: /twitter/likes/DIYgod
Node version: v16.3.0
Git Hash: d50e094
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Rongronggg9** [comment]
目前测试 [rsshub.app/twitter/likes/DIYgod](https://rsshub.app/twitter/likes/DIYgod) 没有问题
