### ISSUE TITLE
微信能抓到阅读量和点赞数吗？

### ISSUE THREAD

**Issue by cqcn1991** [DIYgod/RSSHub#943]
RT
记得很久以前是可以抓到的（当时用搜狗+ PhantomJS），不过现在不知道行不行....

**Comment by HenryQW** [comment]
能，但是不提供公众号全文获取，所以也就不提供阅读量和点赞数。

**Comment by cqcn1991** [comment]
@HenryQW 没太理解。。。。
你说的是，技术上能抓到，但是RSSHub不支持全文获取，所以也就没有，是吗？

**Comment by HenryQW** [comment]
对，获取全文思路参见 https://github.com/DIYgod/RSSHub/issues/311

微信反爬比较严，demo 支持全文抓取不现实。
