### ISSUE TITLE
微博用户失效

### ISSUE THREAD

**Issue by wedcf120** [DIYgod/RSSHub#9442]
### 路由地址

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

### 完整路由地址

https://docs.rsshub.app/social-media.html#wei-bo-bo-zhu

### 相关文档

https://rsshub.app/weibo/user/1195230310

### 预期是什么？

抓取内容失败

### 实际发生了什么？

抓取内容失败

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /weibo/user/1195230310
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /weibo/user/1195230310
Node version: v16.3.0
Git Hash: 96e3b76

https://rsshub.app/weibo/user/1195230310
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Rongronggg9** [comment]
微博近日起加强了反爬，不仅 demo 被反爬，我自己的实例也历史上第一次被反爬了。目前还不知道有什么解决方案😥

**Comment by myxinle** [comment]
确实失效了,希望大佬们能解决下

**Comment by Rongronggg9** [comment]
看起来是微博升级了 API，旧有的请求变得不合法了，正在排查

**Comment by lalasou** [comment]
今天 突然不能用了

可不可以自己加上cookie访问？
https://m.weibo.cn
可以访问 要不然爬这个  感觉手机网页限制少点

**Comment by lalasou** [comment]
> 今天 突然不能用了
> 
> 可不可以自己加上cookie访问？
> https://m.weibo.cn
> 可以访问 要不然爬这个  感觉手机网页限制少点

@Rongronggg9

**Comment by Rongronggg9** [comment]
> 今天 突然不能用了
> 
> 可不可以自己加上cookie访问？ [m.weibo.cn](https://m.weibo.cn) 可以访问 要不然爬这个 感觉手机网页限制少点

现在就是用 `m.weibo.cn` 的
目前没有必要支持添加 cookie，一是不登录时自建实例反爬并不严重（本次只是 API 更改），二是 cookie 有有效期

**Comment by lalasou** [comment]
ok  期待修复
