### ISSUE TITLE
Add debug information subscription.

### ISSUE THREAD

**Issue by Li-Huakang** [DIYgod/RSSHub#9447]
### What feature is it?

To know whether a subsription link is failed in time.
And one day in the future if a subsription is active again, I want to know this information also.

### What problem does this feature solve?

I often can't know whether my subscription is still alive.

### This is not a duplicated feature request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this feature has not already been requested

**Comment by NeverBehave** [comment]
Our current policy would be best effort. To be more specific, we only make sure at the time the pull request is merged, it is working at the time. 

If we do querying, it is hard to cover some routes, and it cost unnecessary traffic/fetching to the target. Mostly we rely on issues/user feedback when a link failed. 

We tried to follow up with these reports and close duplicates issue so all information will be gathered in one place. For now, if you wish to follow up with a route status, you may search related one in the issues and follow up with that issue.
