### ISSUE TITLE
微博显示错误

### ISSUE THREAD

**Issue by c71an** [DIYgod/RSSHub#9452]
### 路由地址

/weibo/user

### 完整路由地址

/weibo/user/2196734667

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo

### 预期是什么？

通过 showEmojiInDescription=0，不显示所有表情以及图标。

### 实际发生了什么？

带有位置信息的微博中，位置图标还是会以图片的方式显示，而且自动换行，影响整体排版。

### 部署

自建

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by c71an** [comment]
参考tag:2021-08-26的版本，微博不显示图标和emoji。以[**]的方式呈现

**Comment by c71an** [comment]
还有以图片显示无法关闭的图标：网页链接，图片评论，视频分享等

**Comment by Rongronggg9** [comment]
Intended behavior. The param `showEmojiInDescription` never takes the control of displaying misc icons or not. It is an internal change, for more details, I've described in #9191.

**Comment by Rongronggg9** [comment]
> 而且自动换行，影响整体排版。

Never observed, could you describe it detailedly and provide a weibo that causing this issue?

**Comment by c71an** [comment]
> 

![67099499-D1BC-4CA0-B7B4-C72CA535E0C5](https://user-images.githubusercontent.com/15607041/161457580-6944b502-4994-4eb3-8dbc-af654745b865.jpeg)

**Comment by c71an** [comment]
在reeder5中的misc icon呈现就是这样，是否可以添加控制icon开关的param。
之前一直用tag:2021-08-26的版本，这次微博api调整了，必须升级了。

**Comment by c71an** [comment]
![E493A3B9-BE6E-45AC-81C4-2959C93CD133](https://user-images.githubusercontent.com/15607041/161458100-8c1a1fe2-cd12-4f9b-813a-940f307a4550.jpeg)

在freshrss 中以图片显示的icon，虽然没有换行，但会影响行间距导致排版的不和谐。

**Comment by c71an** [comment]
@Rongronggg9 
#9458 

![9B542DBE-6CAE-4163-A13D-B9DB96B049B9](https://user-images.githubusercontent.com/15607041/161620543-fcaeac51-81e8-4fab-b98c-06fcfd209fdc.jpeg)

https://m.weibo.cn/1916449873/4752838549570229

正常微博的网页链接icon可以隐去。
但是遇到原微博不可访问的，网页链接的icon无法通过showLinkIconInDescription=0隐去。

**Comment by Rongronggg9** [comment]
#9470
