### ISSUE TITLE
希望添加artstation作者更新

### ISSUE THREAD

**Issue by SKY-rainbow-lh** [DIYgod/RSSHub#946]
artstation是个图片网站，多为cg图画，有很多大牛，希望可以做成rss

**Comment by xyqfer** [comment]
- e.g., https://www.artstation.com/snatti.rss
- source:
    - https://magazine.artstation.com/2016/02/artist-rss-feeds/
    - http://www.artstation.com/artwork.rss
    - http://www.artstation.com/artwork.rss?sorting=latest

**Comment by SettingDust** [comment]
@xyqfer https://www.artstation.com/tyrassic.rss
