### ISSUE TITLE
Weibo RSS not working

### ISSUE THREAD

**Issue by kuraeko** [DIYgod/RSSHub#9460]
### Routes

/weibo/user

### Full routes

/weibo/user/3458899104

### Related documentation

https://docs.rsshub.app/social-media.html#wei-bo

### What is expected?

A RSS feed display of Weibo posts from someone else's account in real time.

### What is actually happening?

![Screen Shot 2022-04-04 at 6 22 00 pm](https://user-images.githubusercontent.com/101419519/161504520-b0e22f68-77c3-4775-8761-5cdd4161ebaf.png)

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

Heroku

### Additional info

```shell
It was working normally up until 2 days ago.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Your version is at least older than `2022-03-24`. This issue has been fixed on `2022-04-02`.
[`/weibo/user/3458899104`](https://rsshub.app/weibo/user/3458899104) is also working on demo instance as of replying. Please update your instance.
