### ISSUE TITLE
少女前线rss源失效

### ISSUE THREAD

**Issue by lindan2000** [DIYgod/RSSHub#9461]
### 路由地址

https://rsshub.app/gf-cn/news

### 完整路由地址

/gf-cn/news/:category?

### 相关文档

https://docs.rsshub.app/game.html#shao-nu-qian-xian

### 预期是什么？

输出少女前线官网情报局新闻和公告

### 实际发生了什么？

该rss源失效

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v16.3.0

### 额外信息

```shell
Route requested: /news
Error message: key.startsWith is not a function
Helpful Information to provide when opening issue:
Path: /news
Node version: v16.3.0
Git Hash: 300af73
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/gf-cn/news
```

**Comment by TonyRL** [comment]
It works as of replying
