### ISSUE TITLE
微博路由403

### ISSUE THREAD

**Issue by centralpro** [DIYgod/RSSHub#9483]
### 路由地址

/weibo/user

### 完整路由地址

/weibo/user/1253846303

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo

### 预期是什么？

可以正常生成内容

### 实际发生了什么？

近2天无法获取到微博内容，对应的报错如下
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/15190825/161922410-aa691a9d-8e9a-4f98-9b1b-6658c1a0ab4a.png">

### 部署

自建

### 部署相关信息

Node version: v14.19.1

### 额外信息

```shell
如上图
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Rongronggg9** [comment]
> ### 这不是重复的 issue
> - [x] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)，以确保该错误尚未被报告。

Really?

Duplicate of #9442 #9460

Please upgrade RSSHub to the latest version.

**Comment by centralpro** [comment]
我来关闭，sorry

**Comment by TonyRL** [comment]
Duplicate of #9442

Your instance is on 2ae88b7 while the issue has been fixed in 63b3b044cda0f8d109ea14d61d8192b499e424dd
