### ISSUE TITLE
知乎个人时间线失效

### ISSUE THREAD

**Issue by luis-arch** [DIYgod/RSSHub#9485]
### Routes

/zhihu/timeline

### Full routes

http://127.0.0.1:1200/zhihu/timeline

### Related documentation

https://docs.rsshub.app/social-media.html#zhi-hu

### What is expected?

展示用户时间线

### What is actually happening?

[图片链接](https://img.so/image/v59WAf)
显示401错误码

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

windows 10 Docker version 20.10.13, build a224086

### Additional info

全程配置
[知乎cookies获取](https://img.so/image/v59eQG)
[docker-compose.yml设置](https://img.so/image/v59DVn)
bilibili及其他配置正确输出xml，只有知乎出现401状态码

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by GeekSquirrel** [comment]
same issue
