### ISSUE TITLE
希望添加gif-nsfw的rss

### ISSUE THREAD

**Issue by tomatomash** [DIYgod/RSSHub#949]
http://www.gif-nsfw.com
feed43做出来只有静态小图，求助大佬能不能把gif拿到

**Comment by SettingDust** [comment]
@tomatomash https://www.reddit.com/r/NSFW_GIF.rss

**Comment by SettingDust** [comment]
@tomatomash

**Comment by SettingDust** [comment]
@SettingDust 那个站点是reddit的频道来源，我认为这种gif获取应该由客户端来
