### ISSUE TITLE
路透社 RSS报错

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#9527]
### 路由地址

rsshub.app/reuters

### 完整路由地址

rsshub.app/reuters/theWire

### 相关文档

https://docs.rsshub.app/traditional-media.html#lu-tou-she

### 预期是什么？

正常输出文章

### 实际发生了什么？

Route requested: /reuters/theWire

Error message: Cannot read property 'map' of undefined

Helpful Information to provide when opening issue:
Path: /reuters/theWire
Node version: v16.3.0
Git Hash: ae66123

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自建与官方均报错
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by RekiDunois** [comment]
```
reuters/theWire
reuters/channel/cn/analyses
```

这两个路由都无法工作了。

**Comment by wym3253** [comment]
> ```
> reuters/theWire
> reuters/channel/cn/analyses
> ```
> 
> 这两个路由都无法工作了。
> 
> 疑似因为 `cn.routers.com` 会被强制重定向到 `www.routers.com` 导致抓不到内容。

是reuters而不是routers

**Comment by RekiDunois** [comment]
typo，别介意。

**Comment by Truth1984** [comment]
https://twitter.com/ulywang/status/1514189780997017607?s=21
