### ISSUE TITLE
steam搜索 路由为空

### ISSUE THREAD

**Issue by FloatStream** [DIYgod/RSSHub#9567]
### 路由地址

/steam/search

### 完整路由地址

/steam/search/:params

### 相关文档

https://docs.rsshub.app/game.html#steam

### 预期是什么？

抓取网页并返回rss订阅源

### 实际发生了什么？

无法抓取，报错

官方演示页面无法使用

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /steam/search/specials=1&term=atelier
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /steam/search/specials=1&term=atelier
Node version: v16.3.0
Git Hash: 3edf239
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
这路由是可以正常访问的，报错是因为当前的搜索条件没有对应的内容所以会有 `this route is empty`
