### ISSUE TITLE
mirror.xyz

### ISSUE THREAD

**Issue by xiaofeigf** [DIYgod/RSSHub#9576]
### Category

Blog

### Website URL

https://mirror.xyz/

### Website description

一个web3交互的博客系统

### What content should be included?

用户文章列表
https://mirror.xyz/userid
用户文章详情
https://mirror.xyz/userid/articleid

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by TonyRL** [comment]
Duplicate of #9576

**Comment by TonyRL** [comment]
Duplicate of #8567

**Comment by TonyRL** [comment]
Please also search the docs https://docs.rsshub.app/new-media.html#mirror before creating an issue.
