### ISSUE TITLE
Facebook 粉絲專頁無法爬取

### ISSUE THREAD

**Issue by NickLin-Tw** [DIYgod/RSSHub#9579]
### 路由地址

/facebook/page

### 完整路由地址

/facebook/page/:id

### 相关文档

https://docs.rsshub.app/social-media.html#facebook

### 预期是什么？

回傳 RSS Feed XML

### 实际发生了什么？

Error message: this route is empty, please check the original site or......

### 部署

自建

### 部署相关信息

OS: Synology DSM(Linux-based), Node: v14.19.1, Docker: 20.10.3-1306, Git Hash: 615c81d

### 额外信息

```shell
Error message: this route is empty, please check the original site or......
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Duplicate of #7512
