### ISSUE TITLE
哔哩哔哩用户关注动态视频没有权限bilibili

### ISSUE THREAD

**Issue by jxjxjhjh** [DIYgod/RSSHub#9605]
### 路由地址

/bilibili/followings/video

### 完整路由地址

http://191954.xyz:1200/bilibili/followings/video/70741404

### 相关文档

rsshub 部署指南

### 预期是什么？

正常显示

### 实际发生了什么？

Error message: 缺少对应 uid 的 Bilibili 用户登录后的 Cookie 值

### 部署

自建

### 额外信息

```shell
使用docker部署，参数是这样的，难道写错了？
docker run -d --name rsshub -p 1200:1200 -e BILIBILI_COOKIE_c3d93773%2C1666311454%2Cb2607%xxxx diygod/rsshub
```

### 这不是重复的 issue

- [x] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by shininome** [comment]
写错了，b_c_uid=cookie,简单写的，自己参考文档吧。

**Comment by jxjxjhjh** [comment]
> 写错了，b_c_uid=cookie,简单写的，自己参考文档吧。

![Screenshot_2022-04-25-17-30-47-781_com huicunjun bbrowser](https://user-images.githubusercontent.com/22759318/165063623-c4b30d2b-11c4-4733-8b20-b54a98f64cf4.jpg)
我那个就是参考文档写的啊，是我理解错了吗？然后按你说的 b_c_uid= 还是同样的问题，我的需求是订阅我正好关注的UP主的视频更新，文档说：视频和专栏只要求 SESSDATA 字段，动态需复制整段 Cookie，我用了sessdata，问题依旧，如果是复制整段 cookie要怎么写？

**Comment by shininome** [comment]
BILIBILI_COOKIE_c3d93773%2C1666311454%2Cb2607%xxxx
 BILIBILI_COOKIE_{uid} = c3d93773%2C1666311454%2Cb2607%xxxx
我不知道该说什么，都说你错了，你告诉我c3d93773%2C1666311454%2Cb2607%xxxx这个东西是uid？例子摆着不看吗

**Comment by jxjxjhjh** [comment]
> 

![Screenshot_2022-04-25-18-15-49-919_alook browser](https://user-images.githubusercontent.com/22759318/165069858-3d0eac6e-0a53-4f0c-81cf-17ed7b532e22.jpg)
应该是哪一个？

**Comment by jxjxjhjh** [comment]
> BILIBILI_COOKIE_c3d93773%2C1666311454%2Cb2607%xxxx BILIBILI_COOKIE_{uid} = c3d93773%2C1666311454%2Cb2607%xxxx 我不知道该说什么，都说你错了，你告诉我c3d93773%2C1666311454%2Cb2607%xxxx这个东西是uid？例子摆着不看吗

能否麻烦您根据上图写一下这条docker代码，这样我一看就懂了。

docker run -d --name rsshub -p 1200:1200 -e BILIBILI_COOKIE_c3d93773%2C1666311454%2Cb2607%xxxx diygod/rsshub

我不是程序员，根据文档和我自己的理解尝试很多次都不行，实在是不知道该怎么做？如果能直接给一条正确的代码，我就能对照看懂了。

**Comment by shininome** [comment]
docker run -d --name rsshub -p 1200:1200 -e BILIBILI_COOKIE_{uid} = “all” diygod/rsshub
到现在你都不把你的uid替换一下，我只能教到这里了，挺暴躁了，只能说加油吧，自己把所有的cooike替换all，自己的uid替换{uid}，路由没问题，自行搜索一下docker环境变量赋值的相关教学

**Comment by jxjxjhjh** [comment]
> docker run -d --name rsshub -p 1200:1200 -e BILIBILI_COOKIE_{uid} = “all” diygod/rsshub 到现在你都不把你的uid替换一下，我只能教到这里了，挺暴躁了，只能说加油吧，自己把所有的cooike替换all，自己的uid替换{uid}，路由没问题，自行搜索一下docker环境变量赋值的相关教学

非常感谢，成功了。
别生气，我的水平属于看一次正确的才能知道怎么做那种，不是我不努力，确实找不到方法。

**Comment by EnderAvaritia** [comment]
> > docker run -d --name rsshub -p 1200:1200 -e BILIBILI_COOKIE_{uid} = “all” diygod/rsshub 到现在你都不把你的uid替换一下，我只能教到这里了，挺暴躁了，只能说加油吧，自己把所有的cooike替换all，自己的uid替换{uid}，路由没问题，自行搜索一下docker环境变量赋值的相关教学
> 
> 非常感谢，成功了。 别生气，我的水平属于看一次正确的才能知道怎么做那种，不是我不努力，确实找不到方法。

你好，请问一下应该怎么填啊，我这也碰到了相似的问题。
