### ISSUE TITLE
希望能设置微博订阅标题

### ISSUE THREAD

**Issue by gjf05** [DIYgod/RSSHub#9606]
### 这是一个什么样的功能？

有的微博内容很长，在Fluent Reader中标题就会很长，希望可以添加对标题的设置，如设置标题的长度。谢谢。

### 这个功能可以解决什么问题？

可以设置微博内容的标题，在阅读器的标题更加简洁

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Please read the docs carefully

**Comment by gjf05** [comment]
你好，你的意思是用通用参数去控制吗？我又看了一遍，好像还是没有找到。你能帮我指出来吗？谢谢

**Comment by TonyRL** [comment]
https://docs.rsshub.app/install/#pei-zhi-qi-ta-ying-yong-pei-zhi
`TITLE_LENGTH_LIMIT`

**Comment by gjf05** [comment]
哦哦，好的。我看到了，但是这种配置不是简单的在后面加内容来限制，我看了一下，不太会。哈哈哈
