### ISSUE TITLE
coomer.party

### ISSUE THREAD

**Issue by ghta01** [DIYgod/RSSHub#9609]
### Category

Multimedia

### Website URL

https://coomer.party

### Website description

Coomer is a public archiver for OnlyFans.

### What content should be included?

Route for: https://coomer.party/onlyfans/user/<username>

### Additional description

Similar to site kemono.party which is already supported.

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by jpgm118** [comment]
Ghvuh

**Comment by jpgm118** [comment]
Gygg

**Comment by jpgm118** [comment]
Hggy

**Comment by jpgm118** [comment]
Hgt7yt

**Comment by amir32** [comment]
I noticed your post regarding the closure of coomer.party , and it's great to see that the task has been successfully completed. It's always a positive sign when tasks are resolved efficiently!

On a related note, if you're looking for a bit of fun and entertainment, you might want to check out FusionCalculator.com. It's a fantastic website where you can explore the fascinating world of Pokémon Fusion, creating unique and imaginative Pokémon combinations. It's a great way to unwind and spark your creativity.

You can visit FusionCalculator.com here: [Pokémon Fusion Calculator](https://fusioncalculator.com/)

I hope you find it enjoyable! Feel free to share it with others who might be interested. 😊
