### ISSUE TITLE
推特基础的时间线、喜欢列表都需要申请高级API吗？

### ISSUE THREAD

**Issue by geeklihui** [DIYgod/RSSHub#9617]
### 路由地址

/twitter/followings/

### 完整路由地址

http://192.168.x.x/twitter/followings/xxx

### 相关文档

https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

### 预期是什么？

申请了API，填好ENV重启以后订阅，尝试了时间线和用户喜爱列表。预期为可以正常订阅。

### 实际发生了什么？

订阅失败，容器日志里有以下报错：

```
error: Error in /twitter/likes/xxx: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
error: Error in /twitter/followings/xxx: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
```

所以现在推特连最基础的喜欢、时间线都要申请高级API吗，我看了下API后台，从Essential升级到Elevated要填好多信息，还要人工审核

### 部署

自建

### 部署相关信息

Docker 20.10.14

### 额外信息

```shell
见上。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
RSSHub's Twitter library [Twit](https://www.npmjs.com/package/twit) supports up to API v1.1 only. Meanwhile, a newly registered developer account can [have Essential access](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api) which can only access v2 endpoints.

**Comment by geeklihui** [comment]
> RSSHub's Twitter library [Twit](https://www.npmjs.com/package/twit) supports up to API v1.1 only. Meanwhile, a newly registered developer account can [have Essential access](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api) which can only access v2 endpoints.

Thanks for your explanation. In that case, there is nothing to be done, I'll close this issue.

**Comment by markx** [comment]
twitter-api-v2 does have a method for this now. https://github.com/PLhery/node-twitter-api-v2/blob/76736eaffbdbae24e6f1786ce752063f691f58a2/doc/v2.md#home-timeline

But the response format seems significantly different, so it likely requires nontrivial change to migrate.
