### ISSUE TITLE
解析失败→内容转义

### ISSUE THREAD

**Issue by sgqy** [DIYgod/RSSHub#962]
有的网页内容直接包含 `<![CDATA[ ... ]]>` 序列，输出 rss xml 后容易解析失败。
希望能在上层把它转义成 `&lt;![CDATA[ ... ]]&gt;`。:thinking:

**Comment by HenryQW** [comment]
在获取数据源的时候可以：
```js
const $ = cheerio.load(content, {
    decodeEntities: false
  });
```

**Comment by sgqy** [comment]
[有的网站](https://kazuuiword.hatenablog.com/entry/2018/10/15/190958)会这样：
```html
<script>// <![CDATA[
(adsbygoogle = window.adsbygoogle || []).push({});
// ]]></script>
```
不过这种情况应该少于2成，为了效率似乎可以在文档里说一下而不是放在rss生成器里。:thinking:

**Comment by HenryQW** [comment]
这个其实可以通过移除所有 <script> tag 来解决，我以为你是要显示`<![CDATA[ ... ]]> `内容。

我在部分路由里清理正文内容的时候：
```js
$('script').each((i, e) => {
      $(e).remove();
});
```

**Comment by HenryQW** [comment]
感觉可以关，不是所有路由都会有这种情况，路由作者应该负责移除 `<script>` 等元素，没有必要在中间价层面做处理。
