### ISSUE TITLE
纽约时报新闻英文源无法访问

### ISSUE THREAD

**Issue by b0ttle** [DIYgod/RSSHub#9682]
### 路由地址

/rsshub/nytimes

### 完整路由地址

/rsshub/nytimes/en

### 相关文档

https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao

### 预期是什么？

输出英文源RSS内容

### 实际发生了什么？

Error message: Cannot read property 'replace' of null

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /en
Error message: Cannot read property 'replace' of null
Helpful Information to provide when opening issue:
Path: /en
Node version: v16.3.0
Git Hash: 569b7d8
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by caisweet** [comment]
hi @b0ttle , 我看了文档，现在完整路由应该是https://rsshub.app/nytimes/en ？

**Comment by b0ttle** [comment]
@caisweet 应该是恢复了, 那我就关了!!
