### ISSUE TITLE
bilibili UP 主投稿 失效

### ISSUE THREAD

**Issue by verity886** [DIYgod/RSSHub#9692]
### 路由地址

https://rsshub.app/bilibili/user/video/510904807

### 完整路由地址

https://rsshub.app/bilibili/user/video/510904807

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

up主稿件更新时，rss订阅更新

### 实际发生了什么？

lastBuildDate里为最新时间，但订阅内容未更新

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

OS：Ubuntu

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://docs.rsshub.app/faq.html
The demo instance has a cache time of 120 mins.
