### ISSUE TITLE
搜狐文章rss失效

### ISSUE THREAD

**Issue by brooktran** [DIYgod/RSSHub#9695]
### Routes

/sohu/mp/99947080

### Full routes

/sohu/mp/99947080

### Related documentation

https://docs.rsshub.app/new-media.html#sou-hu-hao

### What is expected?

生成搜狐RSS源

### What is actually happening?

1. 通过浏览器控制台执行 cfgs.author_id 的方案已失效，移动端为cfgs.authorId，PC端已无效；
2. 通过 /sohu/mp/99947080 提示出错，具体为：
```
Looks like something went wrong
Route requested: /sohu/mp/99947080
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /sohu/mp/99947080
Node version: v14.18.1
```

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS:CentOS 8,Node v14.18.1, Docker:v20.10.5

### Additional info

```shell
Looks like something went wrong
Route requested: /sohu/mp/99947080
Error message: Response code 404 (Not Found): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue: 
Path: /sohu/mp/99947080
Node version: v14.18.1
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Fatpandac** [comment]
能否提供一下你想要订阅的用户主页网址
