### ISSUE TITLE
豆瓣广播 RSS wanted

### ISSUE THREAD

**Issue by driftmc** [DIYgod/RSSHub#97]

**Comment by wilbeibi** [comment]
豆瓣广播 API 都关了好几年了，得用 cookie 爬虫？

**Comment by DerekTso** [comment]
@wilbeibi 关闭了吗？我看它上面还写着。不过需要登录才可以用
[豆瓣广播 Api V2](https://developers.douban.com/wiki/?title=shuo_v2)

**Comment by wilbeibi** [comment]
@DerekTso 点『申请API Key』 会发现申请页面都没了，除了个别商家能用，个人不可能了。

**Comment by tgly307** [comment]
@DerekTso 豆瓣广播是指豆瓣FM？这个rss是指订阅什么信息？

**Comment by tgly307** [comment]
@wydwww 这个不登陆的话，似乎没什么内容，全是豆瓣官方发布的东西。是不是登陆以后会有其他内容

**Comment by wydwww** [comment]
@tgly307 我刚试了下用户广播似乎要登录才能浏览。
入口在一个用户，比如 https://www.douban.com/people/Fenng/ 个人界面的右侧，介绍下面，点全部。

**Comment by wi24rd** [comment]
https://www.douban.com/feed/people/[username]/interests
直接可以用

**Comment by wydwww** [comment]
@wi24rd 这个是「收藏」的 feed

**Comment by yefoenix** [comment]
https://m.douban.com/people/62759792/statuses
这个页面可以免登录直接访问，而且似乎可以抓到API

**Comment by AgFlore** [comment]
Thx！感激.jpg

**Comment by mason1900** [comment]
缺陷：目前过长的广播只能显示前一部分，要看完整的内容只能访问手机网页版。

**Comment by mason1900** [comment]
还有就是分享链接推荐语不显示。
