### ISSUE TITLE
经济学人现在没办法抓取全文了

### ISSUE THREAD

**Issue by Crayon-ShinChan** [DIYgod/RSSHub#9715]
### 路由地址

/the-economist/:endpoint

### 完整路由地址

the-economist/latest 

### 相关文档

https://docs.rsshub.app/traditional-media.html#the-economist-fen-lei

### 预期是什么？

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/38809606/167082737-891ef081-584c-486c-a320-2eb5c1a2332b.png">

### 实际发生了什么？

<img width="766" alt="image" src="https://user-images.githubusercontent.com/38809606/167082767-f0b7f694-b591-4766-8149-77ab71bfc340.png">

### 部署

自建

### 部署相关信息

OS: centOS 7 Docker: version 20.10.5

### 额外信息

```shell
无报错信息
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by hzdaqo** [comment]
可以试试在Feeds上右键勾选Open Articles in Reader View by Default

<img width="1435" alt="Screenshot 05-07 at 12 17 20@2x" src="https://user-images.githubusercontent.com/26734117/167237881-43e1f182-03ac-4689-b49e-ac152ca654b7.png">

**Comment by Crayon-ShinChan** [comment]
> 可以试试在Feeds上右键勾选Open Articles in Reader View by Default
> 
> <img alt="Screenshot 05-07 at 12 17 20@2x" width="1435" src="https://user-images.githubusercontent.com/26734117/167237881-43e1f182-03ac-4689-b49e-ac152ca654b7.png">

可以了！话说这个是 Reeder 特有的能力吗？好强
