### ISSUE TITLE
Youtube 社区内容的 RSS 订阅

### ISSUE THREAD

**Issue by bazing** [DIYgod/RSSHub#9716]
### 这是一个什么样的功能？

当任意 Youtuber 在“社区”中更新动态时，RSS订阅器收到其发布的文字和图片的内容。

### 这个功能可以解决什么问题？

订阅 Youtuber 的“社区”动态。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by TonyRL** [comment]
Duplicate of #7706
