### ISSUE TITLE
增加Lofter用户路由抓取的帖子数量

### ISSUE THREAD

**Issue by KevinSource0** [DIYgod/RSSHub#9723]
### 这是一个什么样的功能？

现在的Lofter用户路由: /lofter/user/:name? 只能显示最近50条动态，希望可以取消这个限制，或者增加到至少200

### 这个功能可以解决什么问题？

在RSS中看到更多条动态，订阅RSS后不需要再访问用户主页查看50条之前的动态。
大多数RSS源都没有这个数量限制，可以显示所有（比如900+）动态。

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求。

**Comment by Fatpandac** [comment]
你可以使用 `limit` 参数实现你的需求，如下
`/lofter/user/i?limit=100`

!! 不过可能会受到缓存影响

**Comment by KevinSource0** [comment]
谢谢@[Fatpandac](https://github.com/Fatpandac) ，加上limit就可以抓取更多动态了。不过有时候需要多刷新几次才能成功（可能是缓存问题？）
