### ISSUE TITLE
keep RSS老用户正常，新用户会报错，然后图片加载失败。

### ISSUE THREAD

**Issue by systemctls** [DIYgod/RSSHub#9724]
### 路由地址

https://rsshub.app/keep/user/

### 完整路由地址

https://rsshub.app/keep/user/624eb511b8659900015bec74

### 相关文档

https://docs.rsshub.app/social-media.html#keep

### 预期是什么？

1. 正常解析
2. 图片正常显示

### 实际发生了什么？

1. RSS链接正常（之前注册的用户，用户id 56dae61344c9612c053bc4a7），图片加载失败
2. RSS链接异常（2022年注册的用户， 用户id 624eb511b8659900015bec74）， Route requested:

### 部署

自建

### 额外信息

```shell
Route requested: /keep/user/624eb511b8659900015bec74
Error message: Cannot read property 'entries' of undefined
Helpful Information to provide when opening issue:
Path: /keep/user/624eb511b8659900015bec74
Node version: v16.3.0
Git Hash: 0c3ca1b
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
能否提供一个有运动日记的2022年注册的用户 ID

**Comment by hnrainll** [comment]
@systemctls 应该不是用户的问题，而是这个用户没有运动记录。到时rsshub在解析空数据的时候异常。

**Comment by systemctls** [comment]
感谢
