### ISSUE TITLE
希望能出一个rss过滤器

### ISSUE THREAD

**Issue by hillerliao** [DIYgod/RSSHub#973]
希望能出一个rss过滤器，且支持正则，比如我只想看36kr的rss里符合某些条件的文章。36kr已经有rss了，不想再重新抓取页面生成rss了，如果有一个代理过滤器一样的东西，就很方便

类似这样，能方便地过滤 https://zapier.com/blog/make-your-own-rss-superfeed/

**Comment by HenryQW** [comment]
同学，这个是阅读器的职责了，RSSHub 不想越俎代庖。

ttrss 考虑一下

![image](https://user-images.githubusercontent.com/5896343/47487434-59237980-d83a-11e8-9926-6a6b4dc2cb8a.png)

![image](https://user-images.githubusercontent.com/5896343/47487339-2c6f6200-d83a-11e8-88d3-b3cd9af6e67e.png)
