### ISSUE TITLE
Misskey: Featured notes

### ISSUE THREAD

**Issue by notofoe** [DIYgod/RSSHub#9737]
### Category

Social Media

### Website URL

> ~~https://misskey.io/featured~~ https://misskey.io/explore
> ~~https://madost.one/featured~~ https://madost.one/explore
> ~~https://mk.nixnet.social/featured~~ https://mk.nixnet.social/explore
> ...
> \# ~~https://misskey.example.invalid/featured~~ https://misskey.example.invalid/explore

### Website description

> [Misskey](https://github.com/misskey-dev/misskey) is a distributed microblogging platform with advanced features such as Reactions and a highly customizable UI. 

### What content should be included?

"Notes" aka posts on featured page. Example: 
![](https://user-images.githubusercontent.com/43095406/167907192-c65c565b-b4e6-4831-b78d-d5581e770450.png)

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by Misaka13514** [comment]
`指定されたURLに該当するページはありませんでした。`

There was no page corresponding to the specified URL.

@notofoe

**Comment by notofoe** [comment]
Thank you for checking, @Misaka13514 ! It seems like the "Explore" page has been relocated to `https://misskey.example.invalid/explore` (eg. https://misskey.io/explore). I will modify the issue to reflect this change.
