### ISSUE TITLE
接收谷歌邮箱邮件错误

### ISSUE THREAD

**Issue by 553059210** [DIYgod/RSSHub#9744]
### 路由地址

/mail/imap/user@gmail.com

### 完整路由地址

/mail/imap/user@gmail.com

### 相关文档

https://docs.rsshub.app/other.html#you-xiang

### 预期是什么？

收到邮件

### 实际发生了什么？

![image](https://user-images.githubusercontent.com/47737576/168209447-661709db-5eb3-4707-9724-6f27f73d476c.png)

### 部署

自建

### 部署相关信息

OS:Windows Node version: v16.14.0 Vercel

### 额外信息

```shell
Error message: mails.reverse is not a function
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by 553059210** [comment]
邮箱相关的密码、接口等设置已经部署，QQ邮箱和Outlook邮箱都有效，翻墙也接收不到谷歌邮件。

**Comment by Rongronggg9** [comment]
https://github.com/DIYgod/RSSHub/blob/a4ce5128abb6b263039b729d0cf7be3590046f88/lib/routes/mail/imap.js#L36

Logs needed.

![](https://user-images.githubusercontent.com/15956627/168479168-24cfd436-e76c-422c-881a-e5a6fb306979.png)

Firstly open the `Function Logs` page, **then** retry requesting your route.

**Comment by 553059210** [comment]
@Rongronggg9 

![image](https://user-images.githubusercontent.com/47737576/169860516-12cf8b42-7c6d-4eb8-b401-482e94075ec0.png)

Is that so? I'm a computer idiot and don't quite understand, please forgive me.

**Comment by Rongronggg9** [comment]
You are mistakenly requesting the wrong path.
✅ `/mail/imap/****@gmail.com`
❎ `/mail/imap/****@gmail.com/feed`

Retry requesting `/mail/imap/****@gmail.com` and show your logs.
