### ISSUE TITLE
能让地址转换成telegram instant view格式吗

### ISSUE THREAD

**Issue by darkskygit** [DIYgod/RSSHub#975]
我给一些小说地址做了模板，但是想要让tg识别成instant view，需要变成
https://t.me/iv?url=源地址&rhash=模板hash
这样的形式，能加一个参数让rss输出成这种形式的地址么
譬如说
?tgiv=模板hash
这样

**Comment by DIYgod** [comment]
@darkskygit 小众需求，建议自行二次开发

**Comment by darkskygit** [comment]
> @darkskygit 小众需求，建议自行二次开发

搞完后可以发pr么

**Comment by SettingDust** [comment]
@darkskygit 我觉得这个搞tg阅读机器人有前途
