### ISSUE TITLE
Add rule for www.cncf.io/blog

### ISSUE THREAD

**Issue by chengjianhua** [DIYgod/RSSHub#9769]
### Category

Programming

### Website URL

https://www.cncf.io/blog/

### Website description

> The Cloud Native Computing Foundation (CNCF) hosts critical components of the global technology infrastructure.
>
> We bring together the world’s top developers, end users, and vendors and run the largest open source developer conferences. CNCF is part of the nonprofit [Linux Foundation](https://linuxfoundation.org/).

https://www.cncf.io/about/who-we-are/

### What content should be included?

Blogs: https://www.cncf.io/blog/
News: https://www.cncf.io/news/
Announcements: https://www.cncf.io/announcements/
Reports: https://www.cncf.io/reports/

### This is not a duplicated rss request

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) and [pull requests](https://github.com/DIYgod/RSSHub/pulls) to ensure this rss proposal has not already been requested

**Comment by chengjianhua** [comment]
@TonyRL PTAL~Thanks

**Comment by chengjianhua** [comment]
@TonyRL Hello~When will this feature be released?

**Comment by TonyRL** [comment]
It's already there after it got merged.

**Comment by chengjianhua** [comment]
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10795207/169661576-3f7cf22b-b88b-4ba4-a9a9-d91ab2ad7f89.png">
@TonyRL I can't see any available rss feeds even if  I have updated rules in RSSHub extension.

**Comment by TonyRL** [comment]
Radar rules remote updating is disabled on Firefox(More details on https://github.com/DIYgod/RSSHub-Radar/issues/408). You can paste the content from https://rsshub.js.org/build/radar-rules.js in the addon setting in the meantime.
The extension works fine on Chromium-based browsers.

**Comment by chengjianhua** [comment]
@TonyRL  I'm using Edge. It's chrome-based. 

After pasting the content of [rsshub.js.org/build/radar-rules.js](https://rsshub.js.org/build/radar-rules.js) into the rules input in the extension settings page, it works. I can subscribe to the feed by rsshub extension.

After updating rules on the settings page, the list of the updated rules doesn't include the rule for `cncf.io`.

Is it possible that the service for updating rules has bugs?

**Comment by TonyRL** [comment]
I just checked RSSHub Radar on Edge add-ons and it has a version of v1.6.0. Due to https://github.com/DIYgod/RSSHub/issues/8269, versions prior to v1.7.0 fetch rules from deprecated location which is no longer updated. You can try re-installing the extension from Chrome Web Store instead.
