### ISSUE TITLE
希望喷嚏图卦能提早推送

### ISSUE THREAD

**Issue by Humecry** [DIYgod/RSSHub#978]
下午4点40分左右喷嚏图卦就出来了, 但推送6点10分才到, 晚了一个半小时左右. 希望能在5点左右就可以推送到.

**Comment by tgly307** [comment]
推送配置应该是阅读器改，可以设置阅读器中图卦的更新频率快一些。RSSHub是收到请求去网站抓取，不负责推送。

**Comment by Humecry** [comment]
@tgly307 那就奇怪了, 我都手动刷RSS但直到6点多才出来, 官网4点多就出来了.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/5165651/47570343-85d5af00-d968-11e8-9c31-1ae5f2518a21.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/5165651/47570372-97b75200-d968-11e8-9ffc-c883b08c8df3.png">

**Comment by tgly307** [comment]
@Humecry 可以试一下4点多直接访问官网看看有没有刷出来，图卦上的时间可能并不是出现在列表上的时间，按理说页面上有就会被rsshub抓到。

**Comment by tgly307** [comment]
@Humecry 可以试一下4点多直接访问官网看看有没有刷出来，图卦上的时间可能并不是出现在列表上的时间，按理说页面上有就会被rsshub抓到。

**Comment by Humecry** [comment]
@tgly307 嗯, 好, 我再观察看看
