### ISSUE TITLE
ao3的rss提案

### ISSUE THREAD

**Issue by Lunannotfound** [DIYgod/RSSHub#9787]
### 类型

阅读

### 网站地址

https://archiveofourown.org/

### 网站描述

大型同人文网站，里面包含了各种各样各类语言的同人小说。

### 需要生成什么内容？

需要生成能够生成每一篇同人小说的网址的feed以便放在rss阅读器中阅读

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by TonyRL** [comment]
https://archiveofourown.org/tags/136512/feed.atom
