### ISSUE TITLE
林志炫微博无法RSS订阅

### ISSUE THREAD

**Issue by zhangjun1996** [DIYgod/RSSHub#9797]
### 路由地址

```routes
https://rsshub.app/weibo/user/1234872834
```

### 完整路由地址

```fullroutes
https://rsshub.app/weibo/user/1234872834
```

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo

### 预期是什么？

预期正常的列表

### 实际发生了什么？

RSSHub
Looks like something went wrong

Route requested: /weibo/user/1234872834

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue:
Path: /weibo/user/1234872834
Node version: v16.3.0
Git Hash: 12bb74d
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行[汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
        

在线文档与支持，请访问[docs.rsshub.app](https://docs.rsshub.app/)。

For online documentation and support please refer to [docs.rsshub.app](https://docs.rsshub.app/).

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
RSSHub
Looks like something went wrong

Route requested: /weibo/user/1234872834

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.

Helpful Information to provide when opening issue:
Path: /weibo/user/1234872834
Node version: v16.3.0
Git Hash: 12bb74d
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        

在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
`/weibo/user/1234872834` works fine on self-hosted instances.
Since the site has a strict anti-crawl policy, you are advised to try on self-hosted instances [FAQ](https://docs.rsshub.app/faq.html)
