### ISSUE TITLE
panewslab

### ISSUE THREAD

**Issue by jimmy798** [DIYgod/RSSHub#9820]
### 路由地址

```routes
https://rsshub.app/panewslab
```

### 完整路由地址

```fullroutes
https://rsshub.app/panewslab/newsflash
https://rsshub.app/panewslab/column/N7042814
```

### 相关文档

https://docs.rsshub.app/new-media.html#panews

### 预期是什么？

https://www.panewslab.com/zh/news/index.html

### 实际发生了什么？

Route requested: /newsflash
Error message: Cannot read property 'list' of undefined
Helpful Information to provide when opening issue:
Path: /newsflash
Node version: v16.3.0
Git Hash: 1c01b70

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /newsflash
Error message: Cannot read property 'list' of undefined
Helpful Information to provide when opening issue:
Path: /newsflash
Node version: v16.3.0
Git Hash: 1c01b70
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nczitzk** [comment]
WIP

**Comment by TonyRL** [comment]
> WIP

https://github.com/DIYgod/RSSHub/blob/134372c8263ed90dd89646a036e6dd9289039f8e/.github/workflows/issue-command.yml#L24-L37
