### ISSUE TITLE
艺术网站rss

### ISSUE THREAD

**Issue by mhh3300** [DIYgod/RSSHub#9823]
### 类型

科学期刊

### 网站地址

http://www.caareviews.org/

### 网站描述

CAA旗下的免费艺术学术文章网站

### 需要生成什么内容？

每个子栏目都可以提醒rss

或者

essays 和 book reviews 生成rss地址

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

**Comment by mhh3300** [comment]
@Fatpandac   抱歉，我看不懂，我是小白，用RSSHUB识别不了，才问的  o(╥﹏╥)o

**Comment by Fatpandac** [comment]
很抱歉，这个路由不支持 `radar` 和 `rssbud` 识别。
但是你可以按照文档使用如下链接进行订阅：
```
https://rsshub.app/caareviews/book
https://rsshub.app/caareviews/exhibition
https://rsshub.app/caareviews/essay
```

**Comment by mhh3300** [comment]
> 

明白了！谢谢示范如何根据文档使用rssub (*￣︶￣)
