### ISSUE TITLE
即刻圈子RSS 没有抓取用户ID和用户昵称信息

### ISSUE THREAD

**Issue by Assazm** [DIYgod/RSSHub#9861]
### 路由地址

```routes
/jike/topic/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/jike/topic/5ab9c9ed2ca389001ba1feb5
```

### 相关文档

https://docs.rsshub.app/social-media.html#ji-ke-quan-zi

### 预期是什么？

即刻圈子RSS中能够显示用户昵称和用户ID

### 实际发生了什么？

在 feed 中没有看到相应的 user 信息

<title>
<![CDATA[ 最近和小红书pr对接的比较多，其实小红书博主除非头部头部头部，一般很难大范围变现。 比如万粉的美妆类博主，一个合集类推广，产品还需要寄回的那种，200块钱。... ]]>
</title>
<description>
<![CDATA[ 最近和小红书pr对接的比较多，其实小红书博主除非头部头部头部，一般很难大范围变现。<br>比如万粉的美妆类博主，一个合集类推广，产品还需要寄回的那种，200块钱。<br>还有就是，很多素人推广，几千粉丝，也是热门赛道，在我看来其实种草就是内容侧的刷单，一次刷单50-100。很多推广也不高。<br>在小红书有两类博主，一类是重IP，vlog居多，人设性很强，一类是纯干货分享，好物分享，种草类的。<br>一般人设类IP的商业价值高于纯干货分享类博主<br>现在很多品牌方要求最多的就是真实、不要摆拍、有一种生活感<br>品牌对博主的风格以及笔记内容要求很严格，比如品牌定位高端，那么合集类的笔记其他产品的价格不能低于甲方品牌，还要求评论区引导。 ]]>
</description>
<pubDate>Mon, 30 May 2022 03:32:07 GMT</pubDate>
<guid isPermaLink="false">https://m.okjike.com/originalPosts/62943ab74c2cdab753d1953f</guid>
<link>https://m.okjike.com/originalPosts/62943ab74c2cdab753d1953f</link>
</item>

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
暂无其他信息

目的：通过圈子抓取到优质即刻用户，然后再利用RSS抓取这些优质用户的个人动态
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Fatpandac** [comment]
用户 ID 指的是链接上面的这个吗？
```
https://m.okjike.com/users/274C130C-E17E-4F6C-ADE2-B85732589D96 
--> 274C130C-E17E-4F6C-ADE2-B85732589D96
```

**Comment by Assazm** [comment]
> 用户 ID 指的是链接上面的这个吗？
> 
> ```
> https://m.okjike.com/users/274C130C-E17E-4F6C-ADE2-B85732589D96 
> --> 274C130C-E17E-4F6C-ADE2-B85732589D96
> ```

是的，用户 ID 就是这个

**Comment by Fatpandac** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/30423976/171103203-2ede5699-4a3d-4423-9a9f-b9af4d7fed13.png">
这样可以吗？

**Comment by Assazm** [comment]
> <img alt="image" width="764" src="https://user-images.githubusercontent.com/30423976/171103203-2ede5699-4a3d-4423-9a9f-b9af4d7fed13.png">
> 
> 这样可以吗？

可以的，完全没问题，非常感谢❤️
