### ISSUE TITLE
tiktok路由问题

### ISSUE THREAD

**Issue by SekiBetu** [DIYgod/RSSHub#9870]
### 路由地址

```routes
/tiktok/user/:user
```

### 完整路由地址

```fullroutes
/tiktok/user/@nozomi0125
```

### 相关文档

https://docs.rsshub.app/en/social-media.html#tiktok

### 预期是什么？

与官方demo rsshub.app一样能抓取内容

### 实际发生了什么？

Looks like something went wrong
Route requested: /user/@nozomi0125
Error message: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Helpful Information to provide when opening issue:
Path: /user/@nozomi0125
Node version: v18.2.0
Git Hash: unknown

### 部署

自建

### 部署相关信息

使用heroku部署，同步最新的commit 9b832f04

### 额外信息

```shell
我注意到Route requested: /user/@nozomi0125中没有出现tiktok，是不是路由有问题
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SekiBetu** [comment]
https://rsshub.app/tiktok/user/@nozomi0125
官方有这个路由，机器人是没更新吗，怎么会无法匹配

**Comment by TonyRL** [comment]
This routes depends on puppeteer

**Comment by SekiBetu** [comment]
> This route depends on puppeteer. You have to set `PUPPETEER_WS_ENDPOINT`

I don't understand what you mean, what do I need to do on heroku to install this "puppeteer"?

**Comment by SekiBetu** [comment]
> You have to put your puppeteer instance IP address/hostname there.

![image](https://user-images.githubusercontent.com/38283893/171379199-a13ce004-6667-4be3-aae1-afdeb3d80cad.png)
![image](https://user-images.githubusercontent.com/38283893/171378589-f75f5401-65ed-4b62-842b-b8e6c0766036.png)
Finally it worked, I know what's going on here, just need to add the puppeteer dependency to heroku, the environment variables mentioned above confused me, how can a dependency library have an instance, and an IP address
