### ISSUE TITLE
🔴 机核网 RSS 报错

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#9877]
### 路由地址

```routes
/gcores/category/:category
```

### 完整路由地址

```fullroutes
https://rsshub.app/gcores/category/news
```

### 相关文档

https://docs.rsshub.app/new-media.html#ji-he-wang-fen-lei

## Looks like something went wrong

- Route requested: /category/news

- Error message: getaddrinfo ENOTFOUND www.gcores.comundefined: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

- Helpful Information to provide when opening issue:

- Path: /category/news

- Node version: v16.3.0

- Git Hash: 548395b

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
「官方示例」和「自建」均出现报错
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by StevenRCE0** [comment]
成功复现，在排查问题了。
