### ISSUE TITLE
Sciencedirect源内容中的@可能被解析为email地址

### ISSUE THREAD

**Issue by lychichem** [DIYgod/RSSHub#9884]
### 路由地址

```routes
rsshub/sciencedirect/journal/catalysis-today
```

### 完整路由地址

```fullroutes
rsshub/sciencedirect/journal/catalysis-today
```

### 相关文档

https://docs.rsshub.app/journal.html#sciencedirect

### 预期是什么？

能够正确把文章中的`Rh@S-1`解析出来。如图：
![image](https://user-images.githubusercontent.com/9316590/171768662-256668fb-faab-42df-8b71-e9536d450222.png)

### 实际发生了什么？

文章中的`Rh@S-1`被解析成了一个邮件地址，然后被email protected。如下图：
![image](https://user-images.githubusercontent.com/9316590/171768609-a85c929c-3f9a-41b4-b382-e2fc461554a8.png)

### 部署

自建

### 部署相关信息

Node: v14.x

### 额外信息

```shell
解析出的email protection的链接为：https://sciencedirect.com/cdn-cgi/l/email-protection
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by lychichem** [comment]
有可能不仅这一个源，而是所有sciencedirect源都有发生此问题的可能。

**Comment by TonyRL** [comment]
https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

**Comment by lychichem** [comment]
> https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

可是这确实不是电子邮件地址，而是一种表示核壳结构材料的记号……
