### ISSUE TITLE
Debugging Issue on "404" websites in local

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#99]
Query:
How to debug those "404" websites in local, such twitter / instagram?
Running the latest package, it shows errors while opening them.

I have tried to set global proxy, not working.
Any idea how to set the proxy successfully in local development env? Thanks~

**Comment by Ir1d** [comment]
https://github.com/rofl0r/proxychains-ng

**Comment by DerekTso** [comment]
thanks
but seems it's NOT for windows.

**Comment by DIYgod** [comment]
@DerekTso 我不用Windows，我也不知道...

**Comment by DerekTso** [comment]
@DIYgod It's the axios proxy problem. I have tried **request** module, and it's good.

I guess this problem will be fixed in next release version of axios. 

**related**
["Request to HTTPS with HTTP proxy fails"](https://github.com/axios/axios/issues/925)
