### ISSUE TITLE
知乎动态挂掉啦

### ISSUE THREAD

**Issue by wangzihan11** [DIYgod/RSSHub#9917]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/diygod
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu

### 预期是什么？

可以看到个人的动态，之前一直在使用

### 实际发生了什么？

网页无法打开

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
RSSHub
Looks like something went wrong
Route requested: /people/activities/diygod
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /people/activities/diygod
Node version: v16.3.0
Git Hash: 8578738
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by zhzy0077** [comment]
`{"error":{"message":"请求参数异常，请升级客户端后重试","code":10003}}`
实际上似乎是这个

**Comment by zhzy0077** [comment]
看样子是x-zse-93这套被拿到用户动态上了
https://github.com/DIYgod/RSSHub/blob/master/lib/v2/zhihu/question.js#L45 可能要把这套搬过来

**Comment by metayoung** [comment]
知乎动态rss挂了，貌似是因为动态页面的链接改变了。people/xxx/activities的“activities”被移除了， www.zhihu.com/people/ji-xuan-yi-9/activities 自动跳转www.zhihu.com/people/ji-xuan-yi-9  

一个电报群友的发言，，，我只是搬运工。

**Comment by metayoung** [comment]
> `{"error":{"message":"请求参数异常，请升级客户端后重试","code":10003}}` 实际上似乎是这个, 自建的也可复现

`https://www.zhihu.com/api/v3/moments/${id}/activities?limit=7&desktop=true`  升级为 v4  接口就可以获取到数据

`https://www.zhihu.com/api/v4/moments/${id}/activities?limit=7&desktop=true`

**Comment by KwToPA** [comment]
我自建设备上虽然知乎路由显示403封IP，但路由只有部分偶尔生效，一百个里面只有一两个的比例。

ttrss上我设定的频率是一小时抓一次，当前抓到的内容是最新的用户动态，但是延迟很久。

rsshub版本是最新的
