### ISSUE TITLE
无法拉取生成Pixiv的rss

### ISSUE THREAD

**Issue by v2cn** [DIYgod/RSSHub#992]
RSSHub安装在远程VPS上。
安装成功运行后出现提示：
```
warn: pixiv RSS is disabled for lacking config.
warn: Disqus RSS is disabled for lacking config.
warn: Twitter RSS is disabled for lacking config.
warn: Youtube RSS is disabled for lacking config.
warn: Telegram RSS is disabled for lacking config.
warn: GitHub Repos RSS is disabled for lacking config.
info: 🎉 RSSHub start! Cheers!
info: Listening Port 1200
```

防火墙规则已经打开1200端口。

浏览器输入 http://vps_ip:1200/pixiv/user/用户ID，发现拉取不到内容。
地址换成官方的 https://rsshub.app/pixiv/user/用户ID 可以。

查看过之前有类似问题的帖子，后来将绑定域名到 vps，开启 https 后，还是不成功。

**Comment by xyqfer** [comment]
- [部分 RSS 模块配置](https://docs.rsshub.app/install/#%E9%83%A8%E5%88%86-rss-%E6%A8%A1%E5%9D%97%E9%85%8D%E7%BD%AE)

<img width="748" alt="wx20181028-143721 2x" src="https://user-images.githubusercontent.com/5186792/47612892-1d4d1600-dabf-11e8-889b-869b29229892.png">

**Comment by v2cn** [comment]
修改config.js文件后，问题解决了。非常感谢！
