### ISSUE TITLE
语雀文档无法抓取

### ISSUE THREAD

**Issue by DophinL** [DIYgod/RSSHub#9948]
### 路由地址

```routes
/yuque/doc/75258
```

### 完整路由地址

```fullroutes
/yuque/doc/75258
```

### 相关文档

https://docs.rsshub.app/study.html#yu-que

### 预期是什么？

正常访问

### 实际发生了什么？

无法访问

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
自建的服务也拉不到
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
https://rsshub.app/yuque/doc/75258 is working fine
