### ISSUE TITLE
纽约时报-新闻简报rss错误

### ISSUE THREAD

**Issue by Yuan68** [DIYgod/RSSHub#9973]
### 路由地址

```routes
/nytimes/daily_briefing_chinese
```

### 完整路由地址

```fullroutes
/nytimes/daily_briefing_chinese
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#niu-yue-shi-bao

### 预期是什么？

正确输出新闻简报

### 实际发生了什么？

链接报错，this route is empty。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
似乎是因为缺少了www。
https://www.nytimes.com/zh-hans/series/daily-briefing-chinese网址能正确显示。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by HamadaMasatoshi** [comment]
实际测试演示实例和自建实例，仍然存在问题，以下是报错信息：

Looks like something went wrong

Route requested: /daily_briefing_chinese/
Error message: Cannot read property '1' of null
Helpful Information to provide when opening issue:
Path: /daily_briefing_chinese/
Node version: v16.3.0
Git Hash: 6bb0972
