### ISSUE TITLE
Dcard RSS被谁更新代码造成失效了，请有缘人修复

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#9980]
### 路由地址

```routes
https://rsshub.app/dcard/
```

### 完整路由地址

```fullroutes
https://rsshub.app/dcard/:section/:type?
```

### 相关文档

https://docs.rsshub.app/bbs.html#citavi-zhong-wen-wang-zhan-lun-tan

### 预期是什么？

自建rsshub能正常使用dcard

### 实际发生了什么？

Route requested: /dcard/posts/popular
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

自建

### 额外信息

```shell
Route requested: /dcard/posts/popular
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /dcard/posts/popular
Node version: v16.15.1
Git Hash: 1e5cab9
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by geerda123** [comment]
现在完全403 forbiden了 ，自建换ip池也没用

**Comment by geerda123** [comment]
难道你们不知道还有https://www.dcard.tw/f/sex?popular=true 这个子板块啊？快来修复啊

**Comment by stevelannist** [comment]
现在自建或者rrshub都不行

**Comment by stevelannist** [comment]
[](http://pic.rmb.bdstatic.com/bjh/8a0b33c3b429630d76ec386fd7f65e48.png)

**Comment by geerda123** [comment]
@DIYgod 老大我看见是你搭建的这个rss地址，能帮忙修复吗？谢谢
